### ISSUE TITLE
Gatsby Plugin library not updated with latest README.md of plugins

### ISSUE THREAD

**Issue by ajayns** [gatsbyjs/gatsby#10008]
## Description

Taking the case of `gatsby-plugin-react-svg`:
The plugin readme doesn't match the info in the gatsbyjs.org plugins library page.

### Steps to reproduce
Site: https://www.gatsbyjs.org/packages/gatsby-plugin-react-svg/
Readme: https://github.com/jacobmischka/gatsby-plugin-react-svg

### Expected result
The site should be constantly updated to ensure no discrepancies.

This could confuse users on what steps to follow and also cause many unnecessary errors.

**Comment by jgierer12** [comment]
As @gurtjun said, Gatsby displays the Readme from the latest published version. GitHub instead shows the latest commit to master. So everything is working as expected.

I would argue that Gatsby's behavior is more user-friendly, since typically you want to see only information relevant to the version you'll actually install.
