### ISSUE TITLE
sharp-plugin reports error symbol not found and does not compile

### ISSUE THREAD

**Issue by ergunpp** [gatsbyjs/gatsby#10092]
I am trying to run starter but can not get the compiler to work in develop mode due to sharp error. 
Here is the compiler output:

![screen shot 2018-11-22 at 18 45 53](https://user-images.githubusercontent.com/24900951/48912544-f946df80-ee86-11e8-87ff-e267bd9dcce0.png)

Any ideas?
Thanks in advance

**Comment by jonniebigodes** [comment]
Please provide us with the output of `gatsby info --clipboard`, the output of `gatsby -v` and if possible a dummy repository with code replicating your issue so that we can take a better look at.

**Comment by ergunpp** [comment]
This is the output of gatsby info --clipboard:

ec2-user:~/environment/bestpetv01 $ gatsby info --clipboard

  System:
    OS: Linux 4.14 Amazon Linux AMI 2018.03
    CPU: (2) x64 Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz
    Shell: 4.2.46 - /bin/bash
  Binaries:
    Node: 6.14.3 - ~/.nvm/versions/node/v6.14.3/bin/node
    npm: 6.4.1 - ~/.nvm/versions/node/v6.14.3/bin/npm
  npmPackages:
    gatsby: latest => 2.0.55 
    gatsby-image: ^1.0.5 => 1.0.37 
    gatsby-link: latest => 2.0.6 
    gatsby-module-loader: latest => 1.0.11 
    gatsby-plugin-google-analytics: latest => 2.0.7 
    gatsby-plugin-i18n: ^0.4.1 => 0.4.1 
    gatsby-plugin-offline: latest => 2.0.17 
    gatsby-plugin-react-helmet: ^1.0.5 => 1.0.8 
    gatsby-source-contentful: latest => 2.0.15 
    gatsby-transformer-remark: latest => 2.1.12 
  npmGlobalPackages:
    gatsby-cli: 1.1.58
    gatsby: 2.0.52


This is the output of gatsby -v

ec2-user:~/environment/bestpetv01 $ gatsby -v
2.0.52

**Comment by jonniebigodes** [comment]
Can you produce a repository url so that the issue can be further investigated?

**Comment by jonniebigodes** [comment]
@ergunpp sorry for the late response.
As i can see you're using aws linux or something in that nature.
From my meager knowledge with gatsby and linux, it sounds to me that you have to make some adjustments, namely add the equivalent of the ubuntu build-essentials package for your distribution and python 2.7 and configure python. Then purge the node modules, cache and public.
Issue `npm install` if you're using npm or `yarn add` to add the packages again to your project.
Then issue `gatsby develop` and see if everything is working properly and that error is no longer present.

**Comment by jonniebigodes** [comment]
@ergunpp i've been talking back and forward with cloud 9 and it seems that they are unable to resolve my issue. I was unable to create an instance so that i could test this particular issue. Also tried a couple of different approaches with glitch and some other editors. But nothing satisfactory. But nonetheless as looking into your activity in here i'm pretty sure that you have moved on past this issue. That you have some projects running and the issue in here was for testing purposes and getting to know Gatsby. So if you don't mind i'm closing this issue. Feel free to open up another issue, should any problems arise. Thanks
