### ISSUE TITLE
Getting empty <p> with markdown images with captions

### ISSUE THREAD

**Issue by arturogh** [gatsbyjs/gatsby#10126]
## Description

When using markdown, the following creates empty `<p></p>` above and below the `<figure>`:

```
![Netflix (Kids section)](./netflix-kids.png 'Netflix (Kids section)')
```

The problem is in the caption inside the `()`.

Here's how it looks with the captions:

<img width="930" alt="image" src="https://user-images.githubusercontent.com/7030831/48986938-33a2bd80-f0cf-11e8-957a-33aaf4cb6beb.png">

And the empty `<p>`s:

<img width="1299" alt="image" src="https://user-images.githubusercontent.com/7030831/48986952-503ef580-f0cf-11e8-8060-8e49729d142f.png">

Here is how it looks with no caption added (`![Netflix (Kids section)](./netflix-kids.png)`):

<img width="834" alt="image" src="https://user-images.githubusercontent.com/7030831/48986899-f807f380-f0ce-11e8-9dad-e1ffa7bc4a3f.png">

### Expected result

No empty `<p>`s are generated.

**Comment by mattdufeu** [comment]
I found your issue because I couldn't get captions to appear at all. I didn't realise the caption text was after the image, but inside the brackets:

`![Netflix (Kids section)](./netflix-kids.png '<this is the caption>')`

So thank you for that!

Yet more good news, is that while playing, I think I found the answer to your extra `<p></p>` statements. It appears that any blank lines before and after the markdown turn into `<p></p>`.

So if I have this in my markdown:

```
Some text before

![Netflix (Kids section)](./netflix-kids.png 'Netflix (Kids section)')

And some text after
```

I get unwanted  `<p></p>`, where as the following works as expected:

```
Some text before
![Netflix (Kids section)](./netflix-kids.png 'Netflix (Kids section)')
And some text after
```

Hope that makes sense, could you try it please?

**Comment by arturogh** [comment]
My short-term solution had been to not include the caption after the image route:

`![Netflix (Kids section)](./netflix-kids.png)`

Now, trying out what you suggested (no break before and after the image), I get something strange happening:

<img width="438" alt="image" src="https://user-images.githubusercontent.com/7030831/51260491-42854e00-1963-11e9-8ef9-7d5b6c4ea00d.png">

I get the text in quotes, not in a `<p>`, and then an empty `<p>` at the end.

FWIW, my expectation would be to not get `<p>` tags created for spaces before and after the image, which is the case when I don't include the caption after the image route (short term solution I mentioned).
