### ISSUE TITLE
Dynamic import of images in Gatsby v2

### ISSUE THREAD

**Issue by ljaniszewski** [gatsbyjs/gatsby#10142]
Hello. I started a new project in Gatsby v2 recently and I stumbled upon a problem with loading images dynamically as such: 

```javascript
  const renderTechnologiesList = (technologies) => {
    return technologies.map(technology => (
      <span
        title={technology.node.title}
        key={technology.node.title}
        className='technology'
        data-toggle='tooltip'
      >
        <img
          src={require(`../assets/${technology.node.image}`)}
          alt={technology.node.title}
        />
      </span>
    ))
  };
```

It was possible in v1, and does not work in v2 for some reason. 
I tried using `import()` instead, but no luck as well.

exception:
```
Uncaught (in promise) Error: Cannot find module 'images/clients/client-ha@2x.png'
```

**Comment by marvinjude** [comment]
`gatsby-image` is most likely what you need. check it out.

**Comment by jonniebigodes** [comment]
I've picked up on your issue and created a dummy component based on the code you provided to test this out and it was showing me the images dynamically, either by running `gatsby develop` and running `gatsby build && gatsby serve`.

Here's the code i used:
```javascript
import React from 'react'

const RenderTechnologiesList = technologies => {
  return (
    <div>
      {
        technologies.technologies.map(technology=>(<span
      title={technology.node.title}
      key={technology.node.title}
      className='technology'
      data-toggle='tooltip'
    >
      <img
        src={require(`../assets/${technology.node.image}`)}
        alt={technology.node.title}
      />
    </span>))
      }
    </div>
    )
}
const TestDynamicimages = () => {
  return (
    <div>
      <RenderTechnologiesList
        technologies={[
          {
            node: {
              title: 'one',
              image: 'images/clients/client-ha@1.jpg',
            },
          },
          {
            node: {
              title: 'two',
              image: 'images/clients/client-ha@2x.jpg',
            },
          },
          {
            node: {
              title: 'three',
              image: 'images/clients/boat.jpg',
            },
          },
        ]}
      />
    </div>
  )
}
export default TestDynamicimages

````
The page code i used
```javascript
import React from 'react'
import { Link } from 'gatsby'

import Layout from '../components/layout'
import TestDynamicimages from '../components/RenderTechnologiesList'
const FifthPage = () => (
  <Layout>
    <h1>Hi from page 5</h1>
    <p>Welcome to page 5</p>
    <div>
      <TestDynamicimages />
    </div>
    <Link to="/">Go back to the homepage</Link>
  </Layout>
)

export default FifthPage

```
The picture bellow shows the rendered output after the build.
![gatsby_dynamic_build_images](https://user-images.githubusercontent.com/22988955/49105210-e9a90b80-f277-11e8-8839-9f4afbf9485b.png)

**Comment by ljaniszewski** [comment]
Ok, thanks for the response. So I assume this has to be something related to project configuration. I am using typescript in this particular project. Could you show me how you configured your path resolvers?

**Comment by Slapbox** [comment]
@ljaniszewski did you figure this out?

**Comment by ljaniszewski** [comment]
Hey, sorry, I haven't got time to do it, I changed the approach as a temporary workaround because now I am trying to figure out why the gatsby prod build is not working properly as this is no1 concern of mine atm

**Comment by jonniebigodes** [comment]
@ljaniszewski if you need help just ask. Open a issue here and see if we can help you with sounds good?

**Comment by leworking** [comment]
@jonniebigodes I'm trying to do what @ljaniszewski was asking (sort-of, I think).

What seems the key of your code for my needs is the line 

```
<img
  src={require(`../assets/${technology.node.image}`)}
  alt={technology.node.title}
/>
```

At the end, this line is doing this (?)
1. you have a url of your image, not in the static folder, but in `/src/images/myGif.gif`
2. once you know the url, then you just `require` it
3. and that's it?

Because I am doing this and when I `require` it I have the `Cannot find module '../src/images/myGif.gif'` error
I've tried `../src`, `./src`, `../images/..`, `./images/..`, just in case I wasn't locating it well (still not sure about that)

Is this a location error in my case? Or I haven't understood your code?

**Comment by fivetwelve** [comment]
Anyone else read this issue searching for a dynamic static image import? `require` does work but if you have es-lint enabled for your project you will need cirvumvent the warnings with `// eslint-disable-next-line global-require, import/no-dynamic-require`.

Gatsby provides a linter-friendly solution with `withPrefix`. Use this approach to reference the static folder when you're authoring your pages. This is what I did after I came across it in the docs. c.f. https://www.gatsbyjs.org/docs/static-folder/

If you store the images within a subfolder in `static`, you have to configure gatsby-config.js to be aware of that. https://www.gatsbyjs.org/docs/path-prefix/ Otherwise, no configuration is required.

I don't know when this feature became available but thanks nonetheless Gatsby team!
