### ISSUE TITLE
Implementing yarn PnP

### ISSUE THREAD

**Issue by Ikana** [gatsbyjs/gatsby#10245]
In order to implement [yarn plug and play](https://github.com/yarnpkg/rfcs/pull/101) with Gatsby some tasks need to be completed first

- [x] Explicitly define any dependencies and not relying  on transitive dependencies to fill in the gaps
- [x] Updating relay-compiler to a compliant with the PnP spec
- [ ] Combing thought Gatsby’s dependencies and making them spec compliant as well 
- [ ] adding a flag on gatsby-cli to trigger the PnP flow
- [ ] refactoring the gatsby-cli to work with out node_modules

Even if the task is practically unattainable (specially from the third step) the other steps are intrinsically worth it.

**Comment by DSchau** [comment]
So glad you opened this! I have the bulk of the functionality built out in gatsbyjs/gatsby#9897 so we can iterate further on any core changes required there _once_ the issues you've identified are solved 😅

**Comment by Ikana** [comment]
No problem @DSchau !
When I was testing this originally, updating relay compiler from 1.5.0 to 1.7.0, showed some test failing but not any more 😝, but I would like to discuss the ramifications of updating that package.

My theory is that specifying the transitive dependencies fixed it.

**Comment by vjpr** [comment]
@DSchau Did you run into any issues relating to the way Gatsby copies all files in `cache-dir` to `.cache`, as this approach relies on hoisting.

I just got Gatsby working with pnpm which requires dependencies to be strictly defined here https://github.com/pnpm/pnpm/issues/991#issuecomment-446330885. Just wondering if you had a similar issue.

**Comment by vjpr** [comment]
Just added an entry to webpack `resolve.modules` config as mentioned in comment link above. No changes to babel.

**Comment by arcanis** [comment]
Hey! I'm playing a bit with Gatsby and I think I could help with this issue (I'm also Yarn's maintainer and PnP's author, which helps)! 🙂 

So far the main issue I have is related to the `.cache` folder: the files seem properly copied from the packages into the cache folder, but since the cache folder isn't part of the dependency tree PnP has no way to know which dependencies it should be able to require.

I'll try to figure out a way to solve this, but the problem is that it's not really a PnP bug: even under the regular install strategy there's nothing that guarantees that the dependencies that will be required by those files will be the one that you expect - hoisting makes it kinda work, but under some circumstances might end up requiring the wrong versions.

**Comment by DSchau** [comment]
@arcanis wow - well this would be amazing :)

We'd certainly appreciate any help in this space. For some prior art here, I did have a PR that _mostly_ implemented this functionality, but ran into some intractable issues. See: gatsbyjs/gatsby#9897

**Comment by arcanis** [comment]
To give you an idea this is the exception thrown. As you can see PnP thinks that `.cache` folder is part of the website workspace - and since the website folder doesn't list `prop-types` in its dependencies, PnP says "no you don't":

![image](https://user-images.githubusercontent.com/1037931/53254641-afef7180-36bb-11e9-9e86-b88372f4279b.png)

@DSchau From which package should the dependencies listed by `cache-dir` be resolved from, btw?

**Comment by arcanis** [comment]
One relatively simple way I can see to solve this would be to have a Webpack resolver exported by the `gatsby` package, that would do something like this (pseudo-code):

```js
const plugin = (request, issuer) => {
  if (issuer.startsWith('.cache/')) {
    return require.resolve(request);
  }
};
```

This way, all files built by Webpack from within the cache folder would see their dependencies resolved relative to the `gatsby` package. Is it something that you think could work? Or do the files within `.cache` come from multiple different packages with different dependency listings?

**Comment by arcanis** [comment]
I've made it work with our v2! I wrote the steps I took here, can be useful for later: https://github.com/yarnpkg/berry/issues/9

If someone with a stronger Gatsby background than me can give it a look I'd be grateful!

**Comment by arcanis** [comment]
I've found an issue in `bootstrap/load-plugins/load.js` - the plugin loader uses `require.resolve` without the `paths` option, meaning that from PnP's point of view the plugin must be listed inside `gatsby`'s dependencies.

I'd recommend to slightly change the `require.resolve` call in order to use something like this:
```js
require.resolve(pluginName, {
  paths: require.resolve.paths(projectRoot),
})
```
The require call would be disambiguated and PnP would return the expected location. Unfortunately it seems that `load-plugin` isn't aware of the project root (yet) so a PR might require some changes outside of this single file. Any idea?

**Comment by DSchau** [comment]
@arcanis awesome (on all accounts!). We'll need to make sure that implementing that functionality doesn't break something unrelated, but that looks good to me.

Would you be interested in PRing anything necessary to get this functionality up and running? We could expose a `--use-pnp` option from the Gatsby CLI once this is all ready!

**Comment by arcanis** [comment]
@DSchau sure, I'll open a PR once I'm done investigating. I'm currently blocked on the following error. I don't have any other error log, so I'm not sure where to look for explanation. Would you have any tip, like the location where `childImageSharp` is registered in the `File` structure?

```
❯ [mael-mbp?] berry/packages/website2 git:(gatsby) ✗ ❯ yarn gatsby develop                                                                                                      [60/1838]

success open and validate gatsby-configs — 0.008 s
success load plugins — 0.409 s
success onPreInit — 0.616 s
success delete html and css files from previous builds — 0.013 s
success initialize cache — 0.005 s
success copy gatsby files — 0.100 s
success onPreBootstrap — 0.015 s
success source and transform nodes — 0.061 s
success building schema — 0.268 s
success createPages — 0.003 s
success createPagesStatefully — 0.066 s
success onPreExtractQueries — 0.005 s
success update schema — 0.118 s
error GraphQL Error There was an error while compiling your site's GraphQL queries.
  Error: RelayParser: Encountered 1 error(s):
- Unknown field 'childImageSharp' on type 'File'. Source: document `usersMaelBerryPackagesWebsite2SrcComponentsImageJs2011440971` file: `GraphQL request`

  GraphQL request (4:11)
  3:         placeholderImage: file(relativePath: { eq: "gatsby-astronaut.png" }) {
  4:           childImageSharp {
               ^
  5:             fluid(maxWidth: 300) {


success extract queries from components — 0.062 s
success run graphql queries — 0.011 s — 5/5 533.59 queries/second
success write out page data — 0.006 s
success write out redirect data — 0.001 s
⢀ onPostBootstrapdone generating icons for manifest
success onPostBootstrap — 0.282 s

info bootstrap finished - 5.638 s
```

**Comment by arcanis** [comment]
I think the problem was at this line - for some reason ``getNodesByType(`ImageSharp`)`` was returning an empty array. I don't understand why, but now it contains two elements, I can't reproduce the crash even after deleting the cache directory :(

**Comment by arcanis** [comment]
Update: now works almost out of the box (note that I test using our [v2](https://github.com/yarnpkg/berry) trunk). Current blockers:

- Figure out a Yarn story for the global `gatsby` binary (the v2 doesn't support global binaries yet)
- Weird issue when using `gatsby new` which requires to call `yarn` manually on the starter clone
- Sharp (on my system) requires `node-gyp` but it's not listed in its dependencies (https://github.com/lovell/sharp/pull/924)
- The `gatsby-node.js` file must be used to tweak the webpack config (will be fixed by #12315)
- Add an integration test to prevent regressions

No real blocker at the horizon 😊

**Comment by arcanis** [comment]
One remark: because [some modules are flagged externals](https://github.com/gatsbyjs/gatsby/blob/c2c66b978242371c8949d4962221f0d2d19fee9e/packages/gatsby/src/utils/webpack.config.js#L417-L440) (implementation here: https://github.com/gatsbyjs/gatsby/pull/7245, cc @pieh), Gatsby+PnP users will have to add them to their own dependencies if a Gatsby plugin happens to depend on them transitively 😢

**Comment by Jamamuuga** [comment]
For me at least, with Yarn PnP enabled on a project & Gatsby 2.13.58 or later (tried up to 2.13.75), yarn build gives an error of "gatsby: not found". Reverting to Gatsby 2.13.57 or disabling Yarn PnP makes it work again. I think I, or someone else, should verify the issue on another project, especially a blank new one.

**Comment by Jamamuuga** [comment]
Hurray, new project works. Must be a complicated dependency issue that none of my meddling has been able to fix yet. Am sticking with non-pnp for now because it also fixed a style application bug with Material-UI...
