### ISSUE TITLE
Regression: Disabling cookies breaks gatsby develop with 'Security Error'

### ISSUE THREAD

**Issue by gswirrl** [gatsbyjs/gatsby#10266]
In Safari and Chrome, with cookies enabled, `gatsby develop` works fine BUT with **cookies disabled**, site fails to render and shows security error instead.

Safari:
<img width="1104" alt="screenshot 2018-12-04 at 05 33 27" src="https://user-images.githubusercontent.com/17145418/49422065-34e88000-f78a-11e8-8539-11f3e8a17718.png">

Chrome:

<img width="1046" alt="screenshot 2018-12-04 at 05 59 09" src="https://user-images.githubusercontent.com/17145418/49422071-3c0f8e00-f78a-11e8-87e5-954cd19cddf9.png">

This worked fine in previous versions.
(`gatsby build`/`gatsby serve` works ok either way)

## gatsby info

```
 System:
    OS: macOS 10.14.1
    CPU: (4) x64 Intel(R) Core(TM) m3-7Y32 CPU @ 1.10GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.3.0 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Safari: 12.0.1
  npmPackages:
    gatsby: ^2.0.53 => 2.0.61 
    gatsby-image: ^2.0.20 => 2.0.22 
    gatsby-plugin-manifest: ^2.0.9 => 2.0.11 
    gatsby-plugin-offline: ^2.0.16 => 2.0.18 
    gatsby-plugin-react-helmet: ^3.0.2 => 3.0.4 
    gatsby-plugin-sharp: ^2.0.12 => 2.0.14 
    gatsby-source-filesystem: ^2.0.8 => 2.0.10 
    gatsby-transformer-sharp: ^2.1.8 => 2.1.9 
  npmGlobalPackages:
    gatsby-cli: 2.4.6
```

## Steps to reproduce:

1) `gatsby new hello`
2) `cd hello`
3) `gatsby develop`
4) in Safari, Preferences > Privacy > Block all cookies: ON
5) open localhost:8000 = ERROR
6) in Safari, Preferences > Privacy > Block all cookies: OFF
7) open localhost:8000 = works

**Comment by gswirrl** [comment]
`gatsby info`

```
  System:
    OS: macOS 10.14.1
    CPU: (4) x64 Intel(R) Core(TM) m3-7Y32 CPU @ 1.10GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.3.0 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm

  npmPackages:
    gatsby: ^2.0.53 => 2.0.61 
    gatsby-image: ^2.0.20 => 2.0.22 
    gatsby-plugin-manifest: ^2.0.9 => 2.0.11 
    gatsby-plugin-offline: ^2.0.16 => 2.0.18 
    gatsby-plugin-react-helmet: ^3.0.2 => 3.0.4 
    gatsby-plugin-sharp: ^2.0.12 => 2.0.14 
    gatsby-source-filesystem: ^2.0.8 => 2.0.10 
    gatsby-transformer-sharp: ^2.1.8 => 2.1.9 
  npmGlobalPackages:
    gatsby-cli: 2.4.6
```

**Comment by gswirrl** [comment]
@jonniebigodes hello - sorry if it looked like i was spamming you - respectfully, i think this is actually a separate issue to #10378 though naturally you may disagree from a position of greater knowledge :-)

- the problem here is that *nothing at all* renders with cookies disabled in *develop* mode

- the problem in the other ticket is that the navigation doesn't work (but everything else is fine) on the site  when *built / served*

i promise you i am being patient and that im very grateful for your attention.

**Comment by jonniebigodes** [comment]
@gswirrl don't worry you're not spamming! As a side note, when you issue `gatsby develop` in your project, gatsby tends to be a little more permissive with some aspects and lets you get away some stuff that you shouldn't normally, from my knowledge and experience, is based on the fact that you shouldn't be impaired at every single keystroke when you are building something with gatsby.

There are currently some issues with this "department"(pardon the bad analogy) and team is looking into it and i appreciate that you are being patient. I can't offer a timetable for this in any shape or form, but be on the look out, because sooner or later you might get some feedback on this issue and then you  can continue your work and deploy it without any issues. I'm retracting my comment on the other issue and reopening it. Sounds good?

**Comment by sidharthachatterjee** [comment]
This was fixed in https://github.com/gatsbyjs/gatsby/pull/10224
