### ISSUE TITLE
Docs guide for adding tags and categories not working in v2

### ISSUE THREAD

**Issue by stevetronix** [gatsbyjs/gatsby#10264]
https://www.gatsbyjs.org/docs/adding-tags-and-categories-to-blog-posts/

This page from the docs does not work for Gatsby v2. It results in the following: "The GraphQL query in the non-page component "/src/templates/tags.js" will not be run." Is there a documentation page published for creating dynamic tags and categories pages in v2 of Gatsby?

**Comment by justinformentin** [comment]
The info it outlines does work with v2, but you need to have other parts of your project that match what's in `gatsby-node.js`. The page that you linked isn't meant to be a "copy this and it will work", it's more just showing you an example, specifically because the other parts of your project, such as the pages and templates, need to have corresponding info/code.

Have you tried following the tutorial? https://www.gatsbyjs.org/tutorial/. The tutorial's `gatsby-node` is a little different than the doc page you linked. I have also written a guide if you'd like to have another reference. If you follow either tutorial from start to finish, you'll have a working project.

**Comment by stevetronix** [comment]
I was trying to follow the full example from the Gatsby tutorial but to no avail. I find your guide easier to follow. I got it working now. Thank you for taking the time to write back and for sharing your guide!

**Comment by justinformentin** [comment]
You're welcome! I'm glad I could help and you got everything working. I'm going to close the issue since you could make it work.
