### ISSUE TITLE
Installing styled components plugins could lead to a blank page

### ISSUE THREAD

**Issue by danielo515** [gatsbyjs/gatsby#10270]
## Description

A blank page without errors on the browser or console

### Steps to reproduce

1. Use the default template starter 
1.  Just install all the dependencies like you were going to use styled components. The package, the plugin and the babel plugin. BUT, do not declare it on the plugins section of gatsby-config
1. Start the dev server

### Expected result

I expected the page to still working (it was doing before and I was just using styled component) or an error

### Actual result

Just a blank page with any kind of error

### Environment

No gatsby local was found. This is weird

This is not a bug report per se, but could be intimidating for beginners that face this situation (like me).
You may want add this info to some kind of FAQ or something like that. It would be nice to explain why it happens too.

Regards

**Comment by LekoArts** [comment]
Hi,
if you want to use styled-components with Gatsby you need to have the plugin installed and in your `gatsby-config`. It handles the SSR part for you. Since you didn't have that I'm not surprised that things broke for you. The page would still have worked if you didn't use styled-components (but installed the dependencies).

> You may want add this info to some kind of FAQ or something like that. It would be nice to explain why it happens too.

The instructions for the plugin already mention that you need to add an entry to `gatsby-config`. So I think that's enough 😊 

Closing this issue as there's no bug 👍

**Comment by danielo515** [comment]
Thanks for the response.
Indeed there is not a bug, I just wanted to explain my experience.
