### ISSUE TITLE
CSS don't load in first visit

### ISSUE THREAD

**Issue by ssshooter** [gatsbyjs/gatsby#10324]
## Description

CSS don't load in first visit

site: https://usubeni.netlify.com/

![first load](https://user-images.githubusercontent.com/13051472/49589172-a8190e80-f9a3-11e8-95b2-32d32398e359.png)
first load

![reload](https://user-images.githubusercontent.com/13051472/49589202-bbc47500-f9a3-11e8-90db-ec9765c9acfc.png)
reload

### Steps to reproduce

the missing css is added in Layout.js

![image](https://user-images.githubusercontent.com/13051472/49589259-e9a9b980-f9a3-11e8-9853-67290b069502.png)

It work perfect in dev environment, but the css is missing in deploy environment.

### Environment
the project init use gatsby blog starter

  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz
  Binaries:
    npm: 5.6.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    gatsby: ^2.0.19 => 2.0.59
    gatsby-image: ^2.0.22 => 2.0.22
    gatsby-plugin-feed: ^2.0.8 => 2.0.10
    gatsby-plugin-google-analytics: ^2.0.8 => 2.0.8
    gatsby-plugin-manifest: ^2.0.5 => 2.0.11
    gatsby-plugin-offline: ^2.0.5 => 2.0.18
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.3
    gatsby-plugin-sass: ^2.0.5 => 2.0.5
    gatsby-plugin-sharp: ^2.0.6 => 2.0.14
    gatsby-plugin-typography: ^2.2.0 => 2.2.2
    gatsby-remark-copy-linked-files: ^2.0.5 => 2.0.7
    gatsby-remark-images: ^2.0.4 => 2.0.6
    gatsby-remark-prismjs: ^3.0.0 => 3.1.2
    gatsby-remark-responsive-iframe: ^2.0.5 => 2.0.7
    gatsby-remark-smartypants: ^2.0.5 => 2.0.7
    gatsby-source-filesystem: ^2.0.2 => 2.0.10
    gatsby-transformer-remark: ^2.1.6 => 2.1.15
    gatsby-transformer-sharp: ^2.1.3 => 2.1.9

**Comment by jgierer12** [comment]
It seems to me that this is a specificity issue, since the CSS is inlined before `typography.js` in empty-cache loads:

![image](https://user-images.githubusercontent.com/4331946/49601181-66796b00-f985-11e8-93ef-d3dafb502af4.png)

Whereas in repeat page loads, the service worker loads it as an external stylesheet after `typography.js`:

![image](https://user-images.githubusercontent.com/4331946/49601285-b3f5d800-f985-11e8-8c6e-c5b7612f84ad.png)

If you inspect the elements, you can see that the `typography.js` styles override your own ones on the first page load.

First of all, you should probably rewrite your styles to use specific, class-based selectors instead of generic tag-based ones. Regardless of the framework and tools you use, it is always a bad idea to write such generic styles since it easily leads to issues like this.

That being said, I do believe that putting the `typography.js` styles below the user-imported ones is not ideal on our side either, and we should think about moving it further to the top..

**Comment by ssshooter** [comment]
understood, thank you 👍

**Comment by derricktsmith** [comment]
I'm having the same issue. How was this fixed?

**Comment by ldc4** [comment]
I'm having the same issue. So is this problem solved？
