### ISSUE TITLE
[gatsby-plugin-offline] adding features to Service Worker

### ISSUE THREAD

**Issue by spektakl** [gatsbyjs/gatsby#10331]
Hi all! 

We are developing a PWA using GatsbyJS and one of the plugins we're using is [gatsby-plugin-offline]. It's all working ok, but we need a way to extend this service worker somehow and the plugin seems to be somehow limited. 

We are using dynamic URLs to get info, so initially, it caches few static assets and no much more. But we want to use the service worker to catch API calls to a third service provider and to manage push notifications to user.

But we can't see how to implement this, as every time we build the project, the generated service worker has only the features that the plugin manages, and things like push notifications are not included. So, if we manually add them to the generated sw.js, we can lost them on the next project build.

Any ideas of how to manage this scenario?

Thanks! :)

**Comment by davidbailey00** [comment]
Hi there, sorry for the slow reply. There's currently a PR open which adds support for custom SW code which can persist between builds: #11626

With this, you'll be able to append your custom code automatically - your existing code should work just fine since it's appended in more-or-less the same way as you would do it manually.

> But we want to use the service worker to catch API calls to a third service provider and to manage push notifications to user.

`gatsby-plugin-offline` uses Workbox behind the scenes, so you can modify the configuration as described here: https://developers.google.com/web/tools/workbox/modules/workbox-build#full_generatesw_config

This link is made more prominent in the plugin's README in the same PR mentioned above. In addition, you can use the Workbox APIs in your custom appended code. For example:

```
workbox.routing.registerRoute(<regex>, workbox.strategies.cacheFirst(), 'POST');
```

This would use the cacheFirst strategy for URLs matching the regex. Note that for third party URLs, the regex has to match the entire URL, not just part of it - e.g. `/https:\/\/thirdpartydomain.com\/.+\.js/` would match all *.js files on thirdpartydomain.com. You can read more about this in the Workbox documentation: https://developers.google.com/web/tools/workbox/modules/workbox-routing#how_to_register_a_regular_expression_route

**Comment by Kalagounet** [comment]
Hi @spektakl, 

I have exactly the same need as you. I want gatsby-plugin-offline to keep working (for its cache management), and I need to override it for other functionalities like push notifications. I don't want to create my own service worker from scratch because I still need gatsby-plugin-offline.

Did you managed to do it ?

**Comment by elie222** [comment]
Also interested in adding push notifications to my Gatsby site

**Comment by Rajarml** [comment]
I've used the link provided by @elie222 but it misses a way to minify the extra push notification script and has a hash to the file name.
The field "importScripts" should take an object with a file path ("src/push-notification.js" for instance) and transforming it in the sw.js into `importScripts("./push-notification.abcd1234.js")`.

**Comment by davidbailey00** [comment]
We just published a new major version of `gatsby-plugin-offline` (3.0.0) which adds support for this feature!

To do this, write a script you want appended to your `sw.js` and then use the option `appendScript` in your `gatsby.config.js`. For more details, please see the README of [gatsby-plugin-offline](https://www.npmjs.com/package/gatsby-plugin-offline).
