### ISSUE TITLE
Path in .cache

### ISSUE THREAD

**Issue by brunogcpinheiro** [gatsbyjs/gatsby#10360]
The error:
Module not found: Error: Can't resolve 'C:UserrunoOneDriveÁrea de TrabalhoCODElog
ode_modulesgatsby-plugin-feedgatsby-ssr' in 'C:\Users\bruno\OneDrive\Área de Trabalho\CODES\blog\.cache'

When I run "gatsby develop" the .cache folder is created and I receive this error in api.runner-ssr.js file becouse it can't avoid the escape "\b" and "\n" in my path.

What I supposed to do?

![Imgur](https://i.imgur.com/F2kUOcw.png)

**Comment by jgierer12** [comment]
You are using a `bash` shell, but a Windows path. Is this WSL or Git bash or something else? Also, it would be very helpful if you could run `gatsby info --clipboard` and paste the output here. Thanks!

**Comment by jonniebigodes** [comment]
@brunogcpinheiro if you can, try to move the folder, minus the public and cache folders, to another one without any portuguese accents and spaces on it and then issue `gatsby develop` once again. When i first tested gatsby, i was using a similar approach with spaces and accents and it started failing on both `gatsby develop` and `gatsby build`. Also one more thing, if is necessary for your project to be stored in the onedrive folder, make sure that onedrive is not running, because it might lock some files for sync and you will get some weird errors. Once more based on a personal experience.
