### ISSUE TITLE
How to use dynamic pages in GatsbyJS?

### ISSUE THREAD

**Issue by Steffi3rd** [gatsbyjs/gatsby#10384]
I already use Gatsby before but only for static content. I love it.

That's why now, I would like to use Gatsby for dynamic content. 

### How/Where should I start? 

I already read the doc of Gatsby about client-only, but I don't really understand.
Is there something more? Starters, tutorials?

Thanks

**Comment by jonniebigodes** [comment]
@Steffi3rd the best advice i can give you is break down the code on the client side routing, then with that and the gatsby docs opened, and some react docs also that might come in handy. start commenting out the code in and out and see what is happening and start taking notes on the process.
To give you a boost the starters page is [here](https://www.gatsbyjs.org/starters/) and the examples [here](https://github.com/gatsbyjs/gatsby/tree/master/examples), but before deep diving into a google search for dynamic content with any type data retrieval and build, go over this first. Go over them at your own pace, don't rush it and try to understand it.

**Comment by sidharthachatterjee** [comment]
In case of static content (that you've already built), Gatsby generates HTML for all the pages at build time (which is one of the things that makes it so fast). 

With dynamic content, since there is no way of knowing what to generate at build time (it _is_ dynamic), you can just go ahead and render any React components like you normally would at runtime _dynamically_. This is as true for Gatsby as any plain React app 🙂 

The only special thing Gatsby needs to know for client side routes is what path prefix is for a client side route. You can use [this plugin](https://www.gatsbyjs.org/packages/gatsby-plugin-create-client-paths/) to tell Gatsby that. 

Check out
- https://www.gatsbyjs.org/docs/building-apps-with-gatsby/ for a more detailed explanation
- https://github.com/gatsbyjs/gatsby/tree/master/examples/client-only-paths for an example Gatsby site that includes client only routes (or dynamic content)

I'm closing this for now but please feel free to reopen if there is anything else. Thank you and happy building!
