### ISSUE TITLE
[gatsby-source-contentful] Multiple copies of data in node (content, [key]) 

### ISSUE THREAD

**Issue by coreyward** [gatsbyjs/gatsby#10403]
I was looking to add input sanitization to some Contentful nodes and noticed that `gatsby-source-contentful` is storing multiple copies of potentially large fields in the GraphQL nodes it creates. 

On lines 182 and 186 `str` is stored:
https://github.com/gatsbyjs/gatsby/blob/60e212f964495747865cc7f942470e46d1f0d7c9/packages/gatsby-source-contentful/src/normalize.js#L176-L189

And again on 203 and 207: 

https://github.com/gatsbyjs/gatsby/blob/60e212f964495747865cc7f942470e46d1f0d7c9/packages/gatsby-source-contentful/src/normalize.js#L198-L210

I don't believe the `internal.content` reference is necessary, but would like to confirm that it's not utilized downstream anywhere before refactoring. Probably not a huge optimization for most people, but for those of us getting into thousands of content-heavy pages, this would ostensibly reduce overhead a bit.

**Comment by sarahbethfederman** [comment]
I'm not sure if this is related, but I'm relying on internal.content for getting the JSON string on rich text fields as shown here: https://github.com/contentful/rich-text/issues/46#issuecomment-447486880 

If this goes away will there be a workaround for my use case?

**Comment by Khaledgarbaya** [comment]
Hi @coreyward,
These are two types of field, `text/markdown` and `text/richtext`. I might be wrong, but IMO it is useful to have `internal.content` raw data so other plugins can further transform it, also it provides an easy way in GraphQL to get all the content at once instead of having to specify all the fields you want from that object which can lead to very verbose query.
This also gives the flexibility to other folks if they don't want to rely on transformers to apply their own transformation because I think even we have a lot of great and amazing transformers, people might have a very specific case that requires manual parsing.

Cheers,
Khaled

**Comment by Khaledgarbaya** [comment]
@coreyward now I get your point, this makes total sense we would need to align with other people to decide which field to keep and which to omit
