### ISSUE TITLE
Remaining steps for launching loki.js support

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#10438]
- [ ] enable for gatsbyjs.org builds
- [ ] Create more tests for edge cases on queries & add loki.js to CI to make sure it's passing all snapshots
- [ ] incremental rollout to folks? Enable for 5% of users and then 10% and then 20%, etc. 

/cc @Moocar @pieh

**Comment by Moocar** [comment]
@KyleAMathews How would an incremental rollout work? How would we enable it on a subset of users? I was thinking we could mention it on the gatsby gazette so that friendly users could try it out first.

@pieh wrote a great tool that compares query output between sift and loki. I think we should be able to extend this functionality to compare example sites during the CI phase. I can add this to my TODO

**Comment by KyleAMathews** [comment]
It'd be automatic. We'd hard code the percentage of the rollout and on bootstrap, if the site wasn't already assigned to one or the other, we'd do Math.random and use that to put them in them in the Loki experiment or redux.

We should definitely push for more friendlies to try it first.

**Comment by Moocar** [comment]
One other thing is that we're using [@moocar/lokijs](https://www.npmjs.com/package/@moocar/lokijs), as the changes to loki haven't been released yet. I'll ping the author and see what the timeline looks like.

**Comment by KyleAMathews** [comment]
@thebigredgeek could you take care of adding the environment variable to the gatsbyjs.org build? The env var is `GATSBY_DB_NODES=loki`

**Comment by KyleAMathews** [comment]
Not stale
