### ISSUE TITLE
Relationships between 3rd party schemas in gatsby-source-graphql

### ISSUE THREAD

**Issue by michaelhayman** [gatsbyjs/gatsby#10692]
I have two GraphQL schemas.  I have them integrated as so in my `gatsby-config.js` file:

````
  plugins: [
    {
      resolve: 'gatsby-source-graphql',
      options: {
        typeName: 'GCMS',
        fieldName: 'gcms',
        url:
          'https://api-apeast.graphcms.com/v1/cjm2g4capq01bn21shzkcx/master',
      },
    },
    {
      resolve: 'gatsby-source-graphql',
      options: {
        typeName: 'PSQL',
        fieldName: 'psql',
        url:
          'https://my-server.herokuapp.com/v1alpha1/graphql',
      },
    },
  ]
````

Say `rooms` are in the first schema, and `availability` is in the second schema, how would I get all of a room's availability?  According to this configuration, the schemas are only merged at a superficial level - i.e. there's no relationships between the two schemas.  I think I'd first have to query for rooms, then query for availability, which is a) inconvenient for a developer and b) would result in an N+1 problem.

Looking at [the schema stitching guide](https://www.apollographql.com/docs/graphql-tools/schema-stitching.html), I'd need to use resolvers, but I don't see an option for that in `gatsby-source-graphql`.

Is there an API I'm missing?  The `gatsby-source-graphql` docs seem to lack this kind of documentation.  I saw some mention of relationships between nodes elsewhere but I'm not sure if this applies to this scenario.

The other option is setting up another graphql server to stitch the two schemas together, and then just simply pass one schema to gatsby, is that what's recommended if one wants to relate 2 schemas together?

Cheers,

**Comment by pieh** [comment]
Hey @michaelhayman!

We currently don't support passing `resolvers` option to `graphql-tools`'s `mergeSchemas` that happens in gatsby core:
https://github.com/gatsbyjs/gatsby/blob/672e2b3087f22f27a0f2763da328c8592e7d69c6/packages/gatsby/src/schema/index.js#L37-L39

This needs a lot of thought to do it properly, because we want to add "cross-schema" resolvers between schema generated by gatsby core and 3rd party and we don't want to create API that will limit us.

But you still should be able to do that - just need some manual intermediatte schema stitching first - in `gatsby-node.js` file you could do:

```js
const { mergeSchemas } = require(`graphql-tools`)

exports.sourceNodes = ({ actions }) => {
  // manually create executable schemas following https://www.apollographql.com/docs/graphql-tools/schema-stitching.html guide
  const mergedSchema = mergeSchemas({
    schemas: [thirdPartyExecutableSchema1, thirdPartyExecutableSchema2, linkTypeDefs],
    resolvers: yourCrossSchemaResolvers,
  })
  addThirdPartySchema({ mergedSchema })
}
```
This is very high-level pseudo-code of course.

It also depends if you will use only 3rd party schemas or you will use any other source/transformer plugins - there would be more things to consider, but it's a bit of time to dive deeper, so let me know about it.

**Comment by michaelhayman** [comment]
Thanks for the reply, will consider and get back to you :)

In the meantime I just stitched our two APIs together, so a gatsby-level solution may be unnecessary.  Cheers!
