### ISSUE TITLE
[gatsby-source-wordpress] Securing APIs called from the browser (authentication, proxy, rate limit)

### ISSUE THREAD

**Issue by cardiv** [gatsbyjs/gatsby#10714]
I want to authenticate with JWT in the browser, for example with [axios](https://www.npmjs.com/package/axios). `gatsby-source-wordpress` supports JWT on build, but is the token saved somewhere for later access in the browser?

If not, how would I safely authenticate with JWT in the browser? Provide username/password using environment variables (beginning with `GATSBY_` to have [access in the browser](https://www.gatsbyjs.org/docs/environment-variables/#client-side-javascript)) and save the token in localstorage or a cookie – is that save?

And which permissions should the user have? I think it is not very save to authenticate as an administrator. One user per use case – for example if I want to create WooCommerce orders, should I create a user only with these capabilities in WordPress?

Is it even possible that a malicious user retrieves the username/password somehow, gets a token with that and does something bad (if administrator is used)?

**Comment by sidharthachatterjee** [comment]
> If not, how would I safely authenticate with JWT in the browser? Provide username/password using environment variables (beginning with GATSBY_ to have access in the browser) and save the token in localstorage or a cookie – is that save?

I wouldn't recommend doing this since exposing credentials in the browser in a bad idea. 

Typically, the ideal way to do this is to let a user authenticate by entering their credentials and calling an API that returns a JWT (a plugin like https://wordpress.org/plugins/jwt-authentication-for-wp-rest-api/ adds an API to allows this)

You can now use this JWT (that will only be short lived and valid for a limited amount of time) to make requests on behalf on the user and store it in local storage if you like. 

Can you elaborate a little more on your usecase?

**Comment by cardiv** [comment]
Yes, I like to use the WordPress plugin you mentioned. Exposing credentials in the browser was one of my intends for this question.

Because of that, I wonder if it would be helpful to create only a WordPress user that can create a new post (WooCommerce order or any other post type) and nothing else.

Use cases:

- Customer orders something (doesn't always have an account).
- User submits a contact form – the message will be saved as a post in a custom post type.

But creating one WordPress user per use case with the only permission to create new posts (orders or form submissions) would not eliminate the danger of malicious users creating spam entries – in the case of credentials getting exposed in the browser.

If JWT is not suitable for that: Is there a better authentication method? Or is there a way to secure these credentials?

**Comment by sidharthachatterjee** [comment]
@cardiv A JWT is fine as long as it is short lived and has restricted permission but that _limits_ risk and doesn't negate it completely

> Customer orders something (doesn't always have an account).
> User submits a contact form – the message will be saved as a post in a custom post type.

An ideal way to do these would be to call a custom API from the client side and let this privileged API authenticate and create the order or post. This will negate the associated risk entirely. 

The API could be rate limited and set to only respond to requests from your domain so that would make it impossible to someone to spam with

**Comment by wardpeet** [comment]
@cardiv in short you can't :( Whenever a request is exposed through the client, the request can be forged.

Like @sidharthachatterjee said you should rate limit it, you can search the web to make your API more robust.

**Comment by sidharthachatterjee** [comment]
@cardiv Closing this for now but please feel free to reopen if there's anything else we can help with! 🙂

**Comment by cardiv** [comment]
I think Netlify's [proxying](https://www.netlify.com/docs/redirects/#proxying) feature could solve most of my issues – if not all.

- Proxy will only be available through the deployed site (e.g. `/api/*`).
- WordPress handles the rest: Validating, authenticating, creating.

The API url does not get exposed to the client nor do any authentication credentials.

One issue could be the response: Will that be proxied too or does it reveal the API?
Do you see any other problems?
