### ISSUE TITLE
Array spread somehow disappears in gatsby-browser.js?

### ISSUE THREAD

**Issue by atomiks** [gatsbyjs/gatsby#10766]
## Description

In `gatsby-browser.js`, I'm trying to monkey-patch a table created with Markdown with some attributes to make it responsive on small screen widths (from this gist https://gist.github.com/AllThingsSmitty/cb32e5a377716bc8f147)

### Steps to reproduce

I found this bug that made me question my sanity:

```js
exports.onRouteUpdate = () => {
  const tds = [...document.querySelectorAll('td')]
  console.log(tds)
}
```

For some reason `tds` is an array with the NodeList inside it, so the spread operator didn't work. 

Maybe a Babel transform is breaking it?

### Expected result

```js
[td, td, td, td] // browser
```

### Actual result

```js
[NodeList(4)] // gatsby
```

It's like it's doing `[document.querySelectorAll('td'])`, essentially evaporating the spread syntax...

### Environment

  System:
    OS: macOS 10.14.1
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.14.1 - /usr/local/bin/node
    Yarn: 1.5.1 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 71.0.3578.98
    Firefox: 64.0
    Safari: 12.0.1
  npmGlobalPackages:
    gatsby-cli: 2.4.8

**Comment by DSchau** [comment]
Hello!

`document.querySelectorAll` returns an array-like object, not an array. I think you're right that you're seeing a transpilation side-effect, e.g. I think the above is transpiled to something like:

```js
const tds = [].concat(document.querySelectorAll('td'))
```

As `document.querySelectorAll` returns a NodeList rather than an Array, I think this is where the error arises--which is confusing because a snippet like the above (before being transpiled) seems to work fine in developer tools in Chrome, at least.

For the time being--could you try the below and see if that irons out your issue?

```js
exports.onRouteUpdate = () => {
  const tds = Array.from(document.querySelectorAll('td'))
  console.log(tds)
}
```

**Comment by DSchau** [comment]
(Also note: this would probably be fairly useful as a `gatsby-remark-` plugin, not sure if you're already going that way or not!)

**Comment by sidharthachatterjee** [comment]
> Maybe a Babel transform is breaking it?

@atomiks Just dug a little deeper and it looks like we have [loose mode](http://2ality.com/2015/12/babel6-loose-mode.html) turned on in `babel-preset-gatsby` which results in `[].concat(document.querySelectorAll('td'))` like @DSchau mentioned

Turning loose mode off results in `[...document.querySelectorAll('td')]` which works because [NodeList](https://developer.mozilla.org/en-US/docs/Web/API/NodeList) is an iterable

**Comment by atomiks** [comment]
Yeah I switched to `Array.from()` but still thought I'd report this

> @atomiks Just dug a little deeper and it looks like we have loose mode turned on in babel-preset-gatsby which results in [].concat(document.querySelectorAll('td')) like @DSchau mentioned

Shouldn't loose mode generate: `[].slice.call(document.querySelectorAll('td'))` instead? The current transform breaks working code.

**Comment by DSchau** [comment]
> Shouldn't loose mode generate: [].slice.call(document.querySelectorAll('td')) instead? The current transform breaks working code.

There's not a great heuristic (that I know of, at least) for detection of array vs. array-like structures, so the best approach is the simple `concat`. Agree that it's confusing though, but I think this is probably not an issue with Gatsby--although perhaps it makes sense to document this behavior somewhere and the "gotchas" with the `loose` preset.

Any interest in doing that or helping out with that effort?

Thanks again for reporting--we appreciate it!
