### ISSUE TITLE
[1.0] TypeError: Cannot read property 'markdownRemark' of undefined

### ISSUE THREAD

**Issue by valeriashpiner** [gatsbyjs/gatsby#1082]
Hi!
First of all, thank you for Gatsby!
Secondly, I just wrote personal blog on previous version of Gatsby and now try to write my blog on Gatsby v1.0. (Node v6.10.3, Windows 7).

So I download Gatsby-Starter-Blog from 1.0 branch and try to launch it. It is launched, I don't edit anything in Gatsby-Starter-Blog and I see main page, but console has warnings: 
**Failed prop type: Template: prop type `children` is invalid; it must be a function, usually from React.PropTypes.** 
I can't understand why, because 
```
Template.propTypes = {
  children: React.PropTypes.function,
  location: React.PropTypes.object,
  route: React.PropTypes.object,
}
```

But these are not main problems :( 
Problem is when I click on any title of post for going on to the blog post I see big error - 
**TypeError: Cannot read property 'markdownRemark' of undefined** in **blog-post.js**, red display and I can't do anything.

**Comment by valeriashpiner** [comment]
I think that something can be wrong in gatsby-node.js: `const slug = /${parsedFilePath.dir}/`
If I write path for page in url by myself, I see post-page. For example, 
```
---
title: First Post
date: "2015-05-01T22:12:03.284Z"
layout: post
readNext: "/my-second-post/"
path: "/my-first-post/"
---

```

and than run `http://127.0.0.1:8000/my-first-post/` - I see my post.
But when url render from node `const slug = /${parsedFilePath.dir}/` - Error.

**Comment by jonrh** [comment]
I ran into a similar issue. I am working on converting my blog from Wordpress to GatsbyJS. Going well but just cleaning up some warning and error message from the Chrome Developer console.

![screen shot 2017-07-13 at 20 28 56](https://user-images.githubusercontent.com/58344/28184806-b8e815aa-680c-11e7-90e5-c4af19fdff1c.png)

For me it was not a critical issue (just a warning in the console). I think it is because the [gatsby-starter-blog](https://github.com/gatsbyjs/gatsby-starter-blog) has an [error](https://github.com/gatsbyjs/gatsby-starter-blog/blob/master/src/layouts/index.js#L68-L72) the file `src/layouts.index.js`:

```javascript
Template.propTypes = {
    children: React.PropTypes.function, // should be "func"
    location: React.PropTypes.object,
    route: React.PropTypes.object,
}
```

I believe the error is the line `children: React.PropTypes.function`. `function` does not exist in `PropTypes`, it is `func`. See the React PropType documentation [here](https://facebook.github.io/react/docs/typechecking-with-proptypes.html#proptypes).

**Comment by yowainwright** [comment]
@jonrh your note worked for me! 🙏
