### ISSUE TITLE
Scroll position flashes when page is reloaded

### ISSUE THREAD

**Issue by d3lm** [gatsbyjs/gatsby#10884]
## Description

I have built a [small site](https://dazzling-bose-d84fff.netlify.com/) with Gatsby and recently upgraded to v2. Now I am facing two issues that I cannot figure out and I have been reading plenty of Github issues already. For your information the site is deployed on Netlify and the **code** can be found [here](https://github.com/yoga-gabi-goeller/website).

**Problem 1: Scroll position flashes when page is reloaded**

This is a very obvious issue and when ever the page is reloaded, it scrolls to the top for a short period of time and then jumps back to its original scoll position.

**Problem 2: Font and content flashes**

I am using the `gatsby-plugin-google-font` to load a font. Even though this adds a link tag to the head, which means the font should be loaded before the content is being rendered, I can see my text flashing. For a short period of time I can see the font changing.

The same goes for the content sometimes. For a short period of time I can see the styles not being loaded but the content is already rendered. I am using bootstrap grid for example. I found a very similar [issue](https://github.com/gatsbyjs/gatsby/issues/5667) but it's still open and no solution was successful for me.

### Steps to reproduce

**Problem 1:** Open the [page])(https://dazzling-bose-d84fff.netlify.com/) scroll down a little bit (or a few sections, doesn't matter) and reload the page. You'll notice that the scroll jumps. I have the feeling that the scroll position is restored once the JS kicks in, but this is a vague guess.

**Problem 2:** Open the [page])(https://dazzling-bose-d84fff.netlify.com/) and hard reload the page a couple of times. You'll notice that the font is flashing and you can also sometimes see unstyled content.

### Expected result

**Problem 1:** I expect the page scroll not to jump, at least this was the case with Gatsby v1. It worked properly and there was no flashes at all. It shouldn't be the solution to stay on v1.

**Problem2:** I expect the fonts to be loaded before the content is rendered. Is the link tag maybe dynamically (with JS) added to the head? The same goes for the styles. I'd love to load the styles before the content is rendered to avoid seeing unstyled content.

### Actual result

See problem description.

### Environment

My local setup is the following:

```
System:
  OS: macOS 10.14
  CPU: (4) x64 Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz
  Shell: 3.2.57 - /bin/bash
Binaries:
  Node: 11.4.0 - /usr/local/bin/node
  Yarn: 1.12.3 - /usr/local/bin/yarn
  npm: 6.4.1 - /usr/local/bin/npm
Languages:
  Python: 2.7.10 - /Users/delm/.pyenv/shims/python
Browsers:
  Chrome: 71.0.3578.98
  Firefox: 64.0
  Safari: 12.0
npmPackages:
  gatsby: ^2.0.85 => 2.0.85
  gatsby-plugin-google-fonts: ^0.0.4 => 0.0.4
  gatsby-plugin-react-helmet: ^3.0.5 => 3.0.5
  gatsby-plugin-sass: ^2.0.7 => 2.0.7
  gatsby-plugin-styled-components: ^3.0.4 => 3.0.4
  gatsby-source-contentful: ^2.0.22 => 2.0.22
  gatsby-transformer-remark: ^2.1.19 => 2.1.19
npmGlobalPackages:
  gatsby-cli: 2.4.8
```

The issues can also be reproduced when running it locally.

**Comment by hagnerd** [comment]
Hi @d3lm in general assets (styles, fonts, and data) take time to load, and many things factor into FOUT/C (flashes of unstyled text/content) but on my initial look it appears to not be an issue with Gatsby. 

It looks like you're loading in data from contentful, which could be taking a second to pull in the content causing jumps, and importing sass into gatsby-browser.js which looks like it isn't the recommended way to include sass in a gatsby project which could be causing the stutters on refresh and issues with unstyled content. 

**Problem 1)** It looks like there have been a few bugs regarding scroll position, and this may be one of them. However the hard part is pinpointing which culprit is to blame because so many things can take control of scroll position. 

I'm not 100% sure, but cleaning up the sass import from gatsby-browser.js and following the [suggested methods](https://www.gatsbyjs.org/packages/gatsby-plugin-sass/?=sass) could potentially help this, but if not `gatsby-browser.js` has a [shouldUpdateScroll api](https://www.gatsbyjs.org/docs/browser-apis/#shouldUpdateScroll) that you can use to control the scroll behavior yourself. Perhaps defaulting to the top of the page on refresh instead. 

**Problem 2)** This appears to just be how `gatsby-plugin-google-fonts` is implemented. The way the fonts are loaded is by hooking into the gatsby-ssr api [onRenderBody](https://www.gatsbyjs.org/docs/ssr-apis/#onRenderBody). 

![image](https://user-images.githubusercontent.com/6313764/50786506-5b15aa00-1279-11e9-9e44-a915f68fdaf4.png)

You can see them using this api [here in the gatsby-plugin-google-fonts](https://github.com/didierfranc/gatsby-plugin-google-fonts/blob/master/gatsby-ssr.js) repo.

![image](https://user-images.githubusercontent.com/6313764/50786534-6a94f300-1279-11e9-8fb8-914c7b9054a3.png)

`gatsby-plugin-google-fonts` is constructing a string from the fonts in your `gatsby-config.js` file, creating a stylesheet link to fetch the fonts remotely, and injecting them into the head of your html file. This could be greatly optimized with caching, or including the fonts as assets directly and serving them alongside the website.

**Comment by d3lm** [comment]
Thanks so much for your response @hagnerd. What would be the suggested way to include global sass such as bootstrap packages?

**Comment by d3lm** [comment]
What I did now is I added the import to the `index.jsx` page and it doesn't seem to solve the issue with the scroll position. The strange thing is this only happens when I build the site. During development it doesn't flash.

Regarding the font, that totally makes sense. But I though that it's being statically rendered and when it's deployed there is already the `link` tag in the head. That was confusing me a little 🤔

**Comment by hagnerd** [comment]
There's a few things to address:
1) Gatsby is more than a _just_ static site generator. It also does client side hydration. So it builds what it can at build time, serves a React app to the client, and allows client side hydration. 

2) The suggested way to include global sass will depend on the packages you are using. I personally don't use sass in my projects so I don't have experience with it in Gatsby. I'd refer you to the [gatsby-plugin-sass](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-sass) documentation for more details. I would assume that importing it in your `index.js` is totally reasonable, but your mileage may vary.

3) I've admittedly never used Contentful, so I'm not sure how all of it is done, but I assume that when the page is loaded on the client, it sends a request to Contentful. Perhaps it pre-fetches on build and caches the results? (If so that's pretty cool).  

4) The stylesheet link for the fonts is constructed and injected at build time, but the font is requested on the client at run time. It's small, but the content could be getting served before the fonts are loaded. 
![font-loading](https://user-images.githubusercontent.com/6313764/50795932-81494300-1295-11e9-89c5-e7a80b97c259.gif).

All of that was to say that the issues you're seeing are _probably_ things you can optimize for, and minimize. It's a normal aspect of having fast loading content. Check out the [gatsbyjs homepage](https://www.gatsbyjs.org/) and refresh a few times. If you watch closely you can see font, styles, and assets load in. 

The scroll issue is still weird, however, I don't think it's a problem with Gatsby in general but a combination of things. I have multiple Gatsby sites in production on Netlify that do not have the issue. I don't see anything that jumps out in your code, but you do have a decent amount of photos. You might benefit from using [gatsby-transformer-sharp + gatsby-plugin-sharp](https://www.gatsbyjs.org/packages/gatsby-transformer-sharp/?=image) and/or [gatsby-image](https://www.gatsbyjs.org/packages/gatsby-image/?=gatsby-image).

**Comment by d3lm** [comment]
Yep, I can see the font flashing for the gatsby site as well. Ok, that's no biggy I guess and I could always serve the font statically and include it in the head via helmet. But I still see unstyled content sometimes which I don't see for the gatsby site. But this is probably the way I import global styles or something. I will also investigate the scroll issue. I am using a package `react-scroll` for smooth scroll and to spy on my menu items. Maybe there's an issue and it doesn't support v2 yet. Just a guess.

**Comment by d3lm** [comment]
I have tried to reproduce the scrolling bug in a fresh gatsby v2 starter and I can. It's really easy to reproduce:

`gatsby new test`

Then go into the `index.js` page and make that div very heigh and give it a background so we can better see the element on the page:

```
<div style={{ maxWidth: `300px`, height: `5000px`, background: `red`, marginBottom: `1.45rem` }}>
  <Image />
</div>
```
So I gave it a height of `5000px` and a background of `red`. If you run `yarn develop` it works perfectly fine and the scroll doesn't flash. However, if you run `yarn build` and serve the `/public` folder you can see the issue in action if you visit the page, scroll down and reload the page.

**Comment by d3lm** [comment]
I also just noticed that the [React documentation](https://reactjs.org/) has exactly the same scrolling issue. Visit the page, scroll and reload it. Tada 😆

**Comment by hagnerd** [comment]
Good deductions! The scroll on refresh does seem to be pretty common then, but I wonder if that is just a constraint to be worked around in a single page web app that supports caching scroll position. 

It's likely because the scroll position is being set by the JavaScript once the page is loaded 🤔. And if that's the case, I'm not quite sure how you'd prevent that from happening or how Gatsby would other than turning the feature off completely. You can override the scroll behavior via the `shouldScrollUpdate` method in your `gatsby-browser.js` file if you'd like to just have it always be set to 0,0. 

It may work differently in development mode because of hot module replacement, but don't quote me on that.

**Comment by d3lm** [comment]
Yea, but again... this was working properly in v1 so there must be some regression, no? I would like to avoid turning this off because this is basically how every other site behaves as well, that if you reload, you end up where you left off - in terms of scroll position.

**Comment by hagnerd** [comment]
If we go further down the rabbit hole, `gatsby` uses `gatsby-react-router-scroll` for scroll behavior, and they implemented a temporary fix for issue #7758 in August which is the last update the source for that project has had and could explain the issue not being present in a v1 website. 

However the issue this was a temp fix for, `@reach/router` [(#119)](https://github.com/reach/router/issues/119), appears to be closed so I'm wondering if `gatsby-react-router-scroll` can now be updated to whatever the intended implementation is/was?

**Comment by d3lm** [comment]
Yep, the issue with the fonts and styles make sense.

@wardpeet Great to see that there's already a potential fix for the scroll jump bug. I'll give it a shot and see if it fixes the issue. Thanks for your work!

**Comment by m-allanson** [comment]
Hey @d3lm, did you get a chance to try @wardpeet's fix? It should be released in the latest version of Gatsby.

**Comment by d3lm** [comment]
Will give it a spin now and get back to you asap.

**Comment by m-allanson** [comment]
@d3lm I'm going to assume no news is good news and close this out 😅 

Let me know if I've got it wrong and we can re-open this issue!

**Comment by joe-safegraph** [comment]
This bug was reintroduced at some point with changes to `gatsby-react-router-scroll`, running into it on Gatsby 3.14
