### ISSUE TITLE
Remove GATSBY_ prefix for environment variables accessed on the client

### ISSUE THREAD

**Issue by chadly** [gatsbyjs/gatsby#11027]
## Summary

Currently, Gatsby makes environment variables prefixed with `GATSBY_` available to client-side scripts via the `Define` webpack plugin. I'd like to make those same environment variables available to the client without the `GATSBY_` prefix as well.

### Basic example

```
GATSBY_MYFLAG=yaaaas gatsby develop
```

from client scripts:

```js
console.log(process.env.GATSBY_MYFLAG); // logs: yaaaas (this is current functionality)
console.log(process.env.MYFLAG); // logs: yaaaas (this is new)
```

### Motivation

I'm pulling in libraries that require some configuration to be set with environment variables. The environment variables the libraries look for are already set (and don't use a `GATSBY_` prefix). The libraries are meant to be used server-side or client-side and hence don't really have a motivation to add an unnecessary `GATSBY_` prefix just because one particular client of the library happens to be a gatsby site.

It's easy enough to make this work with a custom webpack config in `gatsby-node.js`, but I think it makes sense to bring this functionality into gatsby as, for me, it follows the principle of least surprise. Also, I find myself doing it a lot and this would save me some boilerplate.

I can add a PR to support this if it will be welcome.

**Comment by sidharthachatterjee** [comment]
Thank you for opening this @chadly 

The reason we don't _automatically_ make _all_ environment variables available in the bundle is because it could lead to unintentionally leaking credentials to the client side. That's why we require variables to be explicitly prefixed with `GATSBY_`so that it is clear that their inclusion in the bundle is explicit and and intentional. 

Now, with respect to your use case — you should be able to define these variables in a `.env.development` or `.env.production` file (depending on which environment you're working with) and they will be available to the client side JavaScript _without_ any prefix. 

More documentation about this is at https://www.gatsbyjs.org/docs/environment-variables/

**Comment by chadly** [comment]
Yes, I understand the use case for not automatically making all env variables available to client. The proposal here would be to still require the `GATSBY_` prefix for system environment variables to be exposed to the client. The only change here would be to also make those same `GATSBY_` prefixed variables available to the client without the prefix.

**Comment by sidharthachatterjee** [comment]
> The only change here would be to also make those same GATSBY_ prefixed variables available to the client without the prefix.

This would be really confusing in my opinion.

**Comment by sidharthachatterjee** [comment]
@chadly A plugin is a good idea. If there is enough usage and feedback on this issue (let's keep this open), we could always consider merging it into core.

**Comment by chadly** [comment]
I ended up creating a plugin for my use case. [`gatsby-plugin-env-variables`](https://github.com/chadly/gatsby-plugin-env-variables) allows you to whitelist system environment variables to be made available at runtime without the `GATSBY_` prefix.
