### ISSUE TITLE
Gatsby with a million pages

### ISSUE THREAD

**Issue by devbisht** [gatsbyjs/gatsby#11070]
Anyone working /worked with a million pages build in Gatsby?

Just want to see what is the build time and performance of Gatsby before actully implement it.

**Comment by devrchancay** [comment]
I've been asked the same thing several times. for my part I will try to generate many pages with data obtained from faker or something similar and I tell you when I do it.

**Comment by KyleAMathews** [comment]
FYI there's benchmark sites for this sort of thing https://github.com/gatsbyjs/gatsby/tree/master/benchmarks

Also, we don't yet support sites this large. There's a few key blockers e.g. https://github.com/gatsbyjs/gatsby/issues/4746

**Comment by nickreese** [comment]
I'm able to get 10k pages building with 6gb of ram allotted to the build process. If you're using GraphQL queries instead of passing the required data via gatsby-node.js you're going to see insanely long build times. Pre-packaging the data and passing the required data via each template's "pageContext" sped up our build times massively.
