### ISSUE TITLE
Plugin Library: Mark plugins that are officially maintained by Gatsby

### ISSUE THREAD

**Issue by lannonbr** [gatsbyjs/gatsby#11082]
## Summary

It would be helpful to have on plugins that are maintained by Gatsby to have something on each plugin page so devs can know what plugins are official plugins compared to developed by the community. So something like the gatsby-image and other official plugins can be easily noticed as being products being built internally by Gatsby

**Comment by lannonbr** [comment]
So I took a dive into what would actually be needed to do this and we have two places we could put something to distinguish official plugins

1) The Plugins search sidebar. To put it here, there would have to be some logic added to the crawler for Algolia to add a field stating if it is an official plugin (If the plugin is located in the packages/ folder of the Gatsby repo on GitHub) and then maybe add some icon in the [`<Result />`](https://github.com/gatsbyjs/gatsby/blob/master/www/src/components/plugin-searchbar-body.js#L304) component in src/components/plugin-searchbar-body.js if it is an official plugin.

2) The actual rendered plugin body. Given the template for a local / official package (https://github.com/gatsbyjs/gatsby/blob/master/www/src/templates/template-docs-local-packages.js) is separate from a third party package, we would only need to add something in template-docs-local-packages.js if we wish to put some indicator inside the actual body of the package where the README is rendered out.

@m-allanson, @shannonbux, what do you think about this idea?

**Comment by mdashallanson** [comment]
This sounds good, thanks @lannonbr! Step 2. sounds nice and uncomplicated, so that's good.

I have less insight into option 1. Although... I think we're plain using Algolia's npm-search index. Maybe we can highlight results based on the hit data? If this is the right schema (https://github.com/algolia/npm-search#schema) we should be able to highlight based on hit `owner`, `owners` or `repository` in the Result component.

@fk what do you think about adding some way of highlighting official plugins in the plugin library? Either in the body of the results page, or in the search results sidebar (or both)? And if you like the idea, do you want to tell us what it should look like? 😝

**Comment by shannonbux** [comment]
A tiny gatsby logo on the plugin's card (the cards in the sidebar) might be
enough to signal "officialness". I heard someone propose a green check mark
recently, though I think that would be pretty ambiguous. A check mark would
mean more "this passed some sort of test," which could apply to many
plugins that are not official.

Another thing to keep in mind is that it'd be useful to be able to filter
for official plugins.

**Comment by lannonbr** [comment]
Yeah I think the gatsby logo could work and then in the main main portion maybe it could be a bit further extended so it has the logo and then maybe some text next to the logo as a single card like "Official Plugin" or something of that manner.

I'll start an implementation of the two and open a PR and then we can discuss how to make it fit.

**Comment by marcysutton** [comment]
Great discussion here! I like where this is heading. 👍
