### ISSUE TITLE
.cache not deleted when mounted in docker

### ISSUE THREAD

**Issue by edgarnansen** [gatsbyjs/gatsby#11097]
## Description

When running gatsby in a container with a mounted .cache folder, deletion of the .cache folder fails.

### Pre-requisites:
 - git
 - docker

### Steps to reproduce

1. Clone my [dockerized gatsby-default-starter](https://github.com/edgarnansen/gatsby-docker-mounted-cache)
2. Run `docker build -t gatsby-bug-mounted-cache-folder .`
This might take a few minutes the first time.
3. Run `docker run -v mounted-public-folder:/app/public -v mounted-cache-folder:/app/.cache --rm gatsby-bug-mounted-cache-folder`

### Expected result

Gatsby deletes the `.cache` folder.

### Actual result

The folder cannot be deleted.

### Environment
```
  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
  Binaries:
    Yarn: 1.12.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    gatsby: ^2.0.76 => 2.0.76
    gatsby-image: ^2.0.20 => 2.0.25
    gatsby-plugin-manifest: ^2.0.9 => 2.0.12
    gatsby-plugin-offline: ^2.0.16 => 2.0.20
    gatsby-plugin-react-helmet: ^3.0.2 => 3.0.5
    gatsby-plugin-sharp: ^2.0.14 => 2.0.16
    gatsby-source-filesystem: ^2.0.8 => 2.0.12
    gatsby-transformer-sharp: ^2.1.8 => 2.1.9
```
`Docker version 18.09.1, build 4c52b90`

### Possible solutions
The problematic code can be found [here](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/bootstrap/index.js#L200).
We could either replace `fs.remove` with `fs.emptyDir`, or try to `fs.emptyDir` if an `EBUSY` error is thrown.

**Comment by polarathene** [comment]
Is there any reason you're mounting volumes like that vs the whole project as a single volume mount? I use docker as well, I'm not sure if .cache is actually meant to be deleted though(haven't tried without docker), it doesn't happen with my container(my own docker image for gatsby), and since I haven't setup user mapping with docker yet, the files contents are owned by root.

Normally if I want to delete the cache I do so on the host with root permissions. Oh during build my cache is emptied/cleared, I remember that with a recent project, I'm using bind mounts to my local filesystem, you appear to be using docker volumes instead? Any benefit to that?

I could try to reproduce perhaps by using docker volumes instead of bind mounts on my end to confirm.

**Comment by polarathene** [comment]
```
docker run -it --rm -v alpine-gatsby-cache:/site/.cache -v $(pwd):/site -p 9000:8000 gatsby-alpine /bin/sh
/site # gatsby build
/bin/sh: lscpu: not found
success open and validate gatsby-configs — 0.005 s
success load plugins — 0.120 s
success onPreInit — 0.323 s
success delete html and css files from previous builds — 0.154 s
error Failed to remove .cache files.


  Error: EBUSY: resource busy or locked, rmdir '/site/.cache'

success initialize cache — 0.626 s
success copy gatsby files — 0.032 s
success onPreBootstrap — 0.009 s
// In my case I also had folder bind mounted still, so it continued(?), although the /.cache dir was not cleared
```

Sharing that error might have been a bit more useful :P

---

~~So if I understand correctly, `fs.remove()` is equivalent to `rmdir [directory]` and will fail if there is files in that directory, so `fs.emptyDir()` prior would fix that. At least that's what I think @edgarnansen and [this stackoverflow answer](https://stackoverflow.com/questions/52026342/thumbnail-cloud-function-fails-with-error-ebusy-resource-busy-or-locked-rmdi/52028842#52028842) are conveying?~~

Nope that's from `fs-extras` package and is equivalent to `rm -rf [directory]`. Actual error I think is because it's treated as a mount point/directory, rather than a regular directory? As mentioned [here](https://serverfault.com/questions/877123/cannot-remove-file-device-or-resource-busy#comment1129631_877134):

> you can't delete a directory which has a mount hence the resource busy error.. 

I'm guessing you knew all this with the suggestion for using `fs.emptyDir()` as an alternative :) It just wasn't clear in the issue info.

**Comment by edgarnansen** [comment]
>Sharing that error might have been a bit more useful :P
>I'm guessing you knew all this with the suggestion for using fs.emptyDir() as an alternative

Yeah, I guess I could've included a bit more info in the issue. 😛

We _could_ add [fs-filesystem](https://github.com/arthurintelligence/node-fs-filesystem) and actually check if the folder is mounted. That might break builds on Alpine though.

**Comment by polarathene** [comment]
> That might break builds on Alpine though.

Alpine is already painful enough to use with Gatsby(more specifically `gatsby-plugin-sharp`), no thanks :( 

Is there an actual need to delete the folder vs empty it's contents?(I guess the latter might be slower?)

An alternative could be an env var for where the cache folder should be located? That way you could store it in your docker volume without directly being at the mountpoint?

**Comment by edgarnansen** [comment]
> Is there an actual need to delete the folder vs empty it's contents?(I guess the latter might be slower?)

I don't think there's an actual need to **delete** the folder. I haven't compared delete vs empty, but I'd also guess emptying would be slower, the question is how much slower. Will emptying lead to a significant increase in build time? Is trying to empty when deletion fails an acceptable solution?

Should a build even continue when the cache might be stale?

>An alternative could be an env var for where the cache folder should be located? That way you could store it in your docker volume without directly being at the mountpoint?

That would work. An env var for emptying vs deleting would also work without making mounting too "complicated".

**Comment by polarathene** [comment]
> Will emptying lead to a significant increase in build time? 

I'm not knowledgeable enough to answer that. I know some users have very big projects producing thousands of pages or many assets. 

AFAIK deleting a directory and it's contents is a lighter/faster operation as it does something like flag the directory as deleted along with it's contents being available to overwrite? Whereas the empty approach has to do that for every file/directory individually?(It might not be too bad if that's only at the top level)

> Is trying to empty when deletion fails an acceptable solution?

I guess? Shouldn't impact existing users that way and more likely to get accepted.

> Should a build even continue when the cache might be stale?

Not sure. Does build always attempt to clear the cache? If so I guess that's an issue... on the other hand, I could understand wanting to leverage an existing cache to reduce build time(but I'm not sure if that's actually supported).

> That would work. An env var for emptying vs deleting would also work without making mounting too "complicated".

Less code to support the env var for location vs conditional delete/empty behaviour. 

Your suggestion for the empty fallback also means a user doesn't have to be aware of an env var and run into this issue in the first place presumably?

**Comment by polarathene** [comment]
Oh, just checked the source you linked to. The cache may get stale but it's still usable during builds(at a glance, though I think I've always noticed cache to be cleared on build vs develop):

```
// Check if anything has changed. If it has, delete the site's .cache
  // directory and tell reducers to empty themselves.
  //
  // Also if the hash isn't there, then delete things just in case something
  // is weird.
```

Along with the output to console:

> One or more of your plugins have changed since the last time you ran Gatsby. As a precaution, we're deleting your site's cache to ensure there's not any stale data

**Comment by edgarnansen** [comment]
OK, I ran into a problem with building in a docker container today, which was solved by emptying the `.cache` folder. Made a PR that tries to `fs.emptyDir()` if `fs.remove()` throws.
