### ISSUE TITLE
Inconsistencies between develop and build 

### ISSUE THREAD

**Issue by eikhunter** [gatsbyjs/gatsby#11103]
## Description

I am trying to deploy a recently built Gatsby site and having major problems between develop and build which I cannot for the life of me figure out why. Both develop and build compile successfully but when I go to the index.html file or view it on our staging site there seems to be css issues, and no images are showing

Build
![screen shot 2019-01-16 at 14 52 33](https://user-images.githubusercontent.com/19905000/51256913-6f0a8b80-199e-11e9-9ddd-53d388f582be.png)
Develop
![screen shot 2019-01-16 at 14 52 45](https://user-images.githubusercontent.com/19905000/51256916-70d44f00-199e-11e9-817c-33a4c3a3c4a7.png)

I also have a static query 'Loading (StaticQuery)' In the top left hand corner shown as text always

### Expected result

Develop should look the same after you build the project

### Actual result

CSS / Images / Fonts are missing

This is very hard to debug as I can't find any problems when running develop

**Comment by polarathene** [comment]
You're likely going to need to provide more information, a reproduction repo (strip it down to a part that differs, and then make it generic if you feel the need to) for anyone to be able to assist.

At the very least, share more details about the project such as what dependencies(package.json) you're using, gatsby-config.js etc. I have a similar issue where `develop` and `build` are inconsistent with a component that conditionally accepts props based on query string parameters, I also recall a prior project with similar issues when navigating to the index.html, but using any internal links to other pages would render correctly(as they're created as the react app vs loading the contents of `index.html`, might be similar for you?

Your build output didn't throw any errors? No errors in the browser dev tools console(develop or build variants?).

**Comment by sidharthachatterjee** [comment]
Sorry you're seeing this @eikhunter 

This is likely a React hydration issue. Since we don't do server side rendering during `develop`, a lot of these issues become apparent only during `build` at the moment. 

We're trying to converge behaviour between `develop` and `build` as documented in https://github.com/gatsbyjs/gatsby/issues/10706. 

In the mean time, can you link to a reproduction repo?

**Comment by jonniebigodes** [comment]
@eikhunter like @polarathene said, it's really good for us to address the issue you're experiencing with a full blown reproduction, i.e a repository where it can be looked at and reproduced. If the work you're doing is private, or otherwise protected, create a simple dummy repository in order for the issue to be reproduced. Also, and this based without any knowledge of your actual code, the 'Loading (StaticQuery)' is most likely to be a issue with StaticQuery and React Fragments. I believe the issue between the two still exists with Gatsby at this point. If that's actually the issue, at least one of your problems can be solved by simply changing it to a `div` element.

**Comment by eikhunter** [comment]
https://github.com/eikhunter/website-repository - Give this a go

**Comment by eikhunter** [comment]
@sidharthachatterjee Thanks for this, really appreciate it. I have fixed my issue with inconsistencies, there was a media query bug in my code that wasn't generating the correct content which meant all my javascript calculations were screwing up and breaking the whole build, it was an issue with passing down props that had been set to have a media query. Thanks for your help!
