### ISSUE TITLE
Pull GraphQL schema inference out into a separate module

### ISSUE THREAD

**Issue by asolove** [gatsbyjs/gatsby#1116]
As [discussed on Twitter](https://twitter.com/kylemathews/status/872195674690826241), I'd like to help take the Gatsby GraphQL schema inference code and make it into a more generally usable module that Gatsby and other tools could consume.

That said, I know nothing about Gatsby, so it's gonna take me a bit to figure out where things are and how the GraphQL bits currently interact with it. Would appreciate pointers there.

**Comment by KyleAMathews** [comment]
Hey! This is going to be awesome! It'll be great for Gatsby to make things more modular + it'll be cool to see other people make use of the code for whatever it is they make use of it for.

The code is already fairly well abstracted in the `schema` directory https://github.com/gatsbyjs/gatsby/tree/1.0/packages/gatsby/src/schema

The main decoupling work I think is right now it knows how to reach into Gatsby's internals to pull out "nodes". Those would have to be passed in.

One possible interface.

```javascript
const makeServer = require(`json-graphql-server`)

const schema = makeServer(nodes)
```

Any data passed in would need to conform to the Gatsby node format (or abstract this away somehow) https://www.gatsbyjs.org/docs/node-interface/

Thinking about this more, it wouldn't be the best for Gatsby to pull this out completely — that'd mean copying over all nodes into GraphQL which would eat up a lot more memory plus slow things down with all the copying... hmmm... yeah, instead of taking a nodes array, it'd need to take a `getNodes` function I think.

Some interesting files to look at:

* https://github.com/gatsbyjs/gatsby/blob/1.0/packages/gatsby/src/schema/index.js
* https://github.com/gatsbyjs/gatsby/blob/1.0/packages/gatsby/src/schema/infer-graphql-type.js
* https://github.com/gatsbyjs/gatsby/blob/1.0/packages/gatsby/src/schema/data-tree-utils.js
* https://github.com/gatsbyjs/gatsby/blob/1.0/packages/gatsby/src/schema/build-node-connections.js
* https://github.com/gatsbyjs/gatsby/blob/1.0/packages/gatsby/src/schema/run-sift.js

I'd suggest also following the getting started guide for v1 @ https://www.gatsbyjs.org/docs/ and installing the gatsby-starter-blog and playing around in graphiql (it's included with the Gatsby dev server).

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
