### ISSUE TITLE
Querying Strapi GraphQL endpoints with "where"

### ISSUE THREAD

**Issue by Chmarusso** [gatsbyjs/gatsby#11161]
I've configured Gatsby to use GraphQL API exposed by Strapi:

```javascript
//gatsby-config.js
resolve: "gatsby-source-graphql",
options: {
  // This type will contain remote schema Query type
  typeName: "STRAPI",
  // This is field under which it's accessible
  fieldName: "strapi",
  // Url to query from
  url: "http://localhost:1337/graphql",
},
```
Now I have a problem when I want to query for some items with `where` in my index page. Following GraphQL query works fine when executed in Strapi (http://localhost:1337/graphql) and Gatsby (http://localhost:8000/___graphql) playgrounds:
```graphql
query {
  strapi {
    menuitems(where: { id: 1 }) {
      title, description
    }
  }
}
```

But same query does not work in index page: 

```javascript
import React from 'react'
import Layout from '../components/layout'
import SEO from '../components/seo'

import { graphql } from 'gatsby'

const IndexPage = ({data}) => {

  console.log(data)

  return (
    <Layout>
      <SEO title="Home" keywords={[`gatsby`, `application`, `react`]} />
      {data.strapi.menuitems.map(item => <p>{item.title}</p>)}
    </Layout>
  )
}

export default IndexPage

export const query = graphql`
query {
  strapi {
    menuitems(where: { id: 1 }) {
      title, description, category
    }
  }
}
```

I'm getting following error: 
`error GraphQL Error Expected a value matching type STRAPI_JSON, but got an object value`

I thought that I can use same queries in pages as in the playground. I'd be grateful for any advice how I can write query in the proper matter. 

Package.json:

```json
{
  "name": "gatsby-starter-default",
  "private": true,
  "description": "A simple starter to get up and developing quickly with Gatsby",
  "version": "0.1.0",
  "author": "Kyle Mathews <mathews.kyle@gmail.com>",
  "dependencies": {
    "gatsby": "^2.0.76",
    "gatsby-image": "^2.0.20",
    "gatsby-plugin-manifest": "^2.0.9",
    "gatsby-plugin-offline": "^2.0.16",
    "gatsby-plugin-react-helmet": "^3.0.2",
    "gatsby-plugin-sharp": "^2.0.14",
    "gatsby-source-filesystem": "^2.0.8",
    "gatsby-source-graphql": "^2.0.8",
    "gatsby-transformer-sharp": "^2.1.8",
    "prop-types": "^15.6.2",
    "react": "^16.6.3",
    "react-dom": "^16.6.3",
    "react-helmet": "^5.2.0"
  },
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "start": "npm run develop",
    "format": "prettier --write \"src/**/*.js\"",
    "test": "echo \"Write tests! -> https://gatsby.app/unit-testing\""
  },
  "devDependencies": {
    "prettier": "^1.15.2"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/gatsbyjs/gatsby-starter-default"
  },
  "bugs": {
    "url": "https://github.com/gatsbyjs/gatsby/issues"
  }
}

```

**Comment by jonniebigodes** [comment]
@Chmarusso i've picked up on your issue and i can confirm what you are experiencing.
I'm breaking my comments in parts for a better understanding:

1. I've created a new content type in my local strapi installation, it's similar to yours not totally, but it will get the job done in illustrating it, as you can see bellow:

![strapi_1](https://user-images.githubusercontent.com/22988955/51488960-d78ea980-1d9e-11e9-9b8a-4414e2e0fd8a.png)

2. I have enabled graphql locally and issuing my reproduction of the issue it returns the following, the left part of the image is strapi graphql editor and on the right is gatsby graphql editor:

![strapi_2](https://user-images.githubusercontent.com/22988955/51489050-1290dd00-1d9f-11e9-821e-9f3ff1544b01.png)

Without any further knowledge of your code and based on my limited experience with strapi, it seems that you cannot create a content field called `id` as it's reserved, trying to do so will lead into strapi notifying you of the matter. And as you can see both queries work, but are not returning an empty array, but i have content as you can see here:

![strapi_3](https://user-images.githubusercontent.com/22988955/51489285-c1351d80-1d9f-11e9-84f8-68469e9150ad.png)

In this case you have 3 options at your disposal.
1. You update the query on the `index.js` file, tranforming it into what's described bellow and filter the contents in the component, so that the the component will only show your intended item.
I have it and it works.

```graphql
{
    strapi {
      menus {
        title
        content
      }
    }
  }
```
2. You use the Gatsby API to create the page programmatically, more on that [here](https://www.gatsbyjs.org/docs/programmatically-create-pages-from-data/#programmatically-create-pages-from-data), like i'm demonstrating bellow.
If you want to go this route, you need to change your `gatsby-config.js` file with the following contents:
```javascript

exports.createPages = ({ actions, graphql }) => {
    const { createPage } = actions;
    const Wheretemplate=require.resolve(`./src/templates/Wheretemplate.js`)
    return graphql(`
        {
            strapi {
                menus {
                _id
                title
                content
            }
        }
      }
    `).then(result=>{
        if (result.errors) {
            result.errors.forEach(e => console.error(e.toString()))
            return Promise.reject(result.errors)
          }
          result.data.strapi.menus.forEach(item=>{
              if (item._id==='5c45efd626576d06b5a312c9'){ // your intended id
                createPage({
                    path:'/searchcreatepage',
                    component:Wheretemplate,
                    context:{
                      query:{
                          _id:item._id
                      }
                    }
  
                })
              }
              
          })
    })
}
```
Create the file `/src/templates/Wheretemplate.js`, with the following contents:
```javascript
import React from "react";
import { graphql } from "gatsby";
import Layout from "../components/layout";

const Wheretemplate = ({ data }) => (
  <Layout>
    <ul>
      {
          data.strapi.menus.map(item=>{
            return (
              <li key={`menu_item${item.title}`}>
                {item.title}
              </li>
            )
          })
      }
    </ul>
   
  </Layout>
);
export default Wheretemplate;

export const query = graphql`
query allMenus($query: STRAPI_JSON) {
    strapi {
      menus(where: $query) {
        title
        content
      }
    }
  }
`
```
3. You use the official [strapi plugin](https://www.gatsbyjs.org/packages/gatsby-source-strapi/?=gatsby-source-stra#gatsby-source-strapi) to get your data.

Using the first and second approach both worked. There can be something that i might be missing from that particular plugin and some configuration needed that can resolve this issue. But by what i've said, it's working and you are not presented with the error. Feel free to provide feedback.

**Comment by sidharthachatterjee** [comment]
> How I can prepare reproduction in the best way? Creating two repositories (Strapi and Gatsby) and placing the links here would be ok?

This should help us reproduce this @Chmarusso

**Comment by Chmarusso** [comment]
Gatsby repo: https://github.com/Chmarusso/gatsby-graphql
Strapi repo: https://github.com/Chmarusso/strapi-csms

**Comment by sidharthachatterjee** [comment]
Hey @Chmarusso 

Tried setting this up but realised that I'll need Postgres running and probably some data that reproduces this

Could you please update https://github.com/Chmarusso/gatsby-graphql to call a running instance of your strapi cms running somewhere with the issue _reproducible_?

**Comment by jonniebigodes** [comment]
@Chmarusso i believe the answer to your question is in the second approach i've mentioned. when the plugin instrospects and transforms the data it pulls, it expects a certain type to be provided to the query as an argument. in this case a object called `STRAPI_JSON`. If you expand the documentation on the graphql endpoint, you'll see that almost every single item in there as a argument with a certain type to be provided in order for a query to work

**Comment by jonniebigodes** [comment]
@Chmarusso probably i didn't phrase it correctly or there's some miscommunication here. What i meant goes in line with the following images. Taken from the documents sidebar created in graphql.

![1](https://user-images.githubusercontent.com/22988955/51615776-98886180-1f20-11e9-9670-1e4025f1241f.png)

And here:
![2](https://user-images.githubusercontent.com/22988955/51615869-cb325a00-1f20-11e9-94df-78290344ae9b.png)

That's why i said what i said before.

**Comment by Chmarusso** [comment]
I did a small experiment. Instead of using graphql from gatsby I refactored component to use `graphql-client`. Now my page component looks like this: 
```javascript
import React, { Component } from 'react'
import Layout from '../components/layout'
import SEO from '../components/seo'

// import { graphql } from 'gatsby'
const graphql = require('graphql-client')({
  url: 'http://localhost:1337/graphql'
})

class IndexPage extends Component {
  constructor(props) {
    super(props);

    this.state = {
      menuitems: []
    }
  }

  componentDidMount = () => {
    graphql.query(`
      query {
        menuitems(where: { venue: 1 }) {
          id, title, description, category, price
        }
      }`
    ).then(body => {
      this.setState({menuitems: body.data.menuitems})
    })
  }
  render() {
    return (
      <Layout>
      <SEO title="Home" keywords={[`gatsby`, `application`, `react`]} />
      {this.state.menuitems.map(item =>
        <div key={item.id} className="flex flex-column mb3 w-50-ns">
          <div className="flex">
            <div className="w-50">{item.title}</div>
            <div className="w-50 tr">{item.price / 100},-</div>
          </div>
          <div className="w-100">
            {item.description}
          </div>
        </div>
      )}
    </Layout>
    )
  }
}

export default IndexPage

// export const query = graphql`
// query {
//   strapi {
//     menuitems(where: {venue: 1}) {
//       id, title, description, category, price, venue {
//         id
//       }
//     }
//   }
// }
// `

```

Page is working and I do not have any errors complaining about STRAPI_JSON type. 

@jonniebigodes That is why I still do not understand why it is not working when using `import { graphql } from 'gatsby`. I thought that when I'm using `gatsby-source-graphql` I can interact with any GraphQL endpoint in the world. For me it looks like a bug in `gatsby-source-graphql`

**Comment by jonniebigodes** [comment]
@Chmarusso and you can interact with any GraphQL endpoint with the plugin. Based on that, i'm inclined to believe that, it's a strategy that was used by the developer so that the where clause should work more like a sql where clause, making it as abstract as possible, so that it could used in a compound manner, to prevent later issues with people asking for a broader approach, allowing a compound clause and so on. But i might be wrong about it, once again this is based on my experience and use of it.
