### ISSUE TITLE
gatsby-remark-images issues with relative paths in nested pages

### ISSUE THREAD

**Issue by itwasmattgregg** [gatsbyjs/gatsby#11239]
## Description

Using remark images and placing images in the directory next to the markdown file referencing them works fine when those directories are in the top level of the /pages directory. However when you move those page directories into a subdirectory like /posts or /blog the images return 404s. This is when using relative paths to reference the images like `./image-for-post.jpg`. Where the md file and image are located at `/pages/posts/first-post/*`. It does seem to work if the image reference is changed to an absolute path `/image-for-post.jpg`.

Another thing to note: when I move the files under the /posts directory my build tells me that both the md file and image are 'added'.

### Steps to reproduce

Basic starter blog with `gatsby-transformer-remark` and `gatsby-remark-images`. Take hello-world markdown post directory and move it into a sub directory under `/pages`, something like `/pages/posts/`. Start develop build and navigate to that post. It will properly render at /posts/hello-world but the image will not show.

### Expected result

Images should be loaded properly no matter what the nesting structure looks like in the pages directory because they are referenced using relative paths from the md files.

### Actual result

Relative paths seem to not be working to reference images in nested markdown files.

### Environment

```
System:
    OS: macOS 10.14.2
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.5.0 - ~/.nvm/versions/node/v10.13.0/bin/npm
  Browsers:
    Chrome: 71.0.3578.98
    Firefox: 64.0
    Safari: 12.0.2
  npmPackages:
    gatsby: ^2.0.0 => 2.0.93
    gatsby-image: ^2.0.13 => 2.0.27
    gatsby-plugin-catch-links: ^2.0.9 => 2.0.9
    gatsby-plugin-feed: ^2.0.5 => 2.0.11
    gatsby-plugin-google-analytics: ^2.0.5 => 2.0.10
    gatsby-plugin-manifest: ^2.0.2 => 2.0.13
    gatsby-plugin-offline: ^2.0.5 => 2.0.21
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.5
    gatsby-plugin-sass: ^2.0.1 => 2.0.7
    gatsby-plugin-sharp: ^2.0.5 => 2.0.18
    gatsby-plugin-typography: ^2.2.0 => 2.2.5
    gatsby-remark-copy-linked-files: ^2.0.5 => 2.0.8
    gatsby-remark-images: ^2.0.1 => 2.0.6
    gatsby-remark-prismjs: ^3.0.0 => 3.2.0
    gatsby-remark-responsive-iframe: ^2.0.5 => 2.0.8
    gatsby-remark-smartypants: ^2.0.5 => 2.0.7
    gatsby-source-filesystem: ^2.0.1 => 2.0.17
    gatsby-transformer-remark: ^2.1.1 => 2.2.0
    gatsby-transformer-sharp: ^2.1.1 => 2.1.10
  npmGlobalPackages:
    gatsby: 2.0.66
```

**Comment by sidharthachatterjee** [comment]
Hey @itwasmattgregg 

Could you link to a minimal reproduction of this?

**Comment by jonniebigodes** [comment]
@itwasmattgregg i've picked up on your issue and i could not reproduce your issue.
Bellow are the steps i took so that i could attempt to reproduce your issue:
- Created a new gatsby website with the blog starter.
- Updated the packages to the latest version.
- Created a structure like so:

  ![folder_structure_blog](https://user-images.githubusercontent.com/22988955/51807784-77f33b00-2283-11e9-8572-eea3aed43768.png)

- The contents of bananas.md
```markdown
---
title: this-is-a-banana
date: '2019-01-22T22:12:03.284Z'
---

this is a banana, there are many like it but this one is mine.


![banana](./banana.jpg)
```
- Updated the `gatsby-config.js` file to the following:
```javascript
module.exports = {
  siteMetadata: {
    title: `Gatsby Starter Blog`,
    author: `Kyle Mathews`,
    description: `A starter blog demonstrating what Gatsby can do.`,
    siteUrl: `https://gatsby-starter-blog-demo.netlify.com/`,
    social: {
      twitter: `kylemathews`,
    },
  },
  plugins: [
    {
      resolve:`gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/src/pages/posts`,
        name: `posts`,
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/content/blog`,
        name: `blog`,
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/content/assets`,
        name: `assets`,
      },
    },
    {
      resolve: `gatsby-transformer-remark`,
      options: {
        plugins: [
          {
            resolve: `gatsby-remark-images`,
            options: {
              maxWidth: 590,
            },
          },
          {
            resolve: `gatsby-remark-responsive-iframe`,
            options: {
              wrapperStyle: `margin-bottom: 1.0725rem`,
            },
          },
          `gatsby-remark-prismjs`,
          `gatsby-remark-copy-linked-files`,
          `gatsby-remark-smartypants`,
        ],
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-plugin-google-analytics`,
      options: {
        //trackingId: `ADD YOUR TRACKING ID HERE`,
      },
    },
    `gatsby-plugin-feed`,
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `Gatsby Starter Blog`,
        short_name: `GatsbyJS`,
        start_url: `/`,
        background_color: `#ffffff`,
        theme_color: `#663399`,
        display: `minimal-ui`,
        icon: `content/assets/gatsby-icon.png`,
      },
    },
    /* `gatsby-plugin-offline`, */
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-plugin-typography`,
      options: {
        pathToConfigModule: `src/utils/typography`,
      },
    },
  ],
}
```

- Issued `gatsby develop`, opened a chrome window and i was presented with:
![banana_dev_mode](https://user-images.githubusercontent.com/22988955/51807837-0e276100-2284-11e9-82bb-f03e7880949e.png)

- Opened the link in question, was presented with this:

![banana_page](https://user-images.githubusercontent.com/22988955/51807847-1f706d80-2284-11e9-93af-6ddcc8c4fcb2.png)

- So that all was confirmed, deleted the folder `.cache` and `public`, issued `gatsby build && gatsby serve` and was presented with this:

![banana_prod_mode](https://user-images.githubusercontent.com/22988955/51807870-6d857100-2284-11e9-8816-b86c3e61b35c.png)

- Opening the link to the page in production mode resulted in the following:

![banana_prod_mode_page](https://user-images.githubusercontent.com/22988955/51807876-855cf500-2284-11e9-97b5-306d6b44957e.png)

As you can see by my setup, i've commented out the offline plugin and to ensure that nothing was cached all of the tests were done in incognito mode.

So and without any further information, i'm inclined to believe that you probably misconfigured something, or something else is wrong. Feel free to provide further feedback so that we can fix this issue

**Comment by itwasmattgregg** [comment]
Closing this issue. It appears to just be a caching issue. If I delete the cache inbetween moving files into the subfolder it doesn't work.

**Comment by uno-b** [comment]
I'm actually having the exact same issue as you.
