### ISSUE TITLE
Wrapping with PersistGate blocks google/facebook from crawling the site

### ISSUE THREAD

**Issue by benflinn** [gatsbyjs/gatsby#11245]
I started using redux, and wrapped with provider, as described here:
https://github.com/gatsbyjs/gatsby/blob/master/examples/using-redux/wrap-with-provider.js

To use redux-persist, I wrapped with the PersistGate like this:
```
export default ({ element }) =>
  (
    <Provider store={store.store}>
      <PersistGate loading={null} persistor={store.persistor}>
        {element}
      </PersistGate>
    </Provider>
  )
```
It seemed to work great!

Now, I realize, the site won't load without javascript, and google/facebook can't crawl the site.

How are you supposed to use redux-persist with Gatsby? Is there something I'm missing?

**Comment by benflinn** [comment]
There are other examples of people having trouble, I just don't know the best way of fixing this problem?

https://spectrum.chat/gatsby-js/general/edit-fixed-currently-our-site-is-not-rendering-with-js-turned-off~47c0c48e-7394-45a5-98d5-62e061c61177

https://github.com/gatsbyjs/gatsby/issues/10414#issuecomment-448302435

**Comment by DSchau** [comment]
@benflinn I think the linked resources (in particular the comment in #10414) should lead you in the correct direction!

I'm not super familiar with redux-persist, but it sounds like it blocks rendering (and HTML extraction) until after some condition is true. If that condition isn't true during SSR render time, then only _some_ of your tree will be able to be parsed as HTML. Additionally, it could be possible that redux-persist entirely blocks SSR rendering, but I don't know that without a repro!

As I see it, you have two solutions:

1. Move redux-persist further down the tree where it's actually needed so that _more_ content can be rendered without blocking SSR
     - This should be totally doable, as I believe as long as you've wrapped your app in a redux provider you can use the PersistGate component wherever you want
1. Use some other alternative to redux-persist that doesn't block SSR (I can't help as much here!)

Hope this helps answer your question. As there's some prior art here, I'm going to mark as answered, but if you're able to provide a further reproduction or if you need additional help, please feel free to comment/re-open and we'll take another look.

Thanks for using Gatsby 💪

**Comment by alexpchin** [comment]
I'm still unsure of the correct solution to this problem? Does anyone have some working code?
