### ISSUE TITLE
Variable in GraphQL query

### ISSUE THREAD

**Issue by Siregar** [gatsbyjs/gatsby#11261]
👋

I am working on a file named `pages/bookmarks.js`. This should display all the bookmarks which are saved in the local storage. What I want: push the bookmarks array from LS to query and get all the bookmarks. My page looks like that:

```javascript
import React from 'react'
import { graphql } from 'gatsby'
import Layout from '../components/Layout'
import List from '../containers/BookmarksList'

const BookmarksPage = () => {
	return (
	  <Layout>
	  	<List view={'bookmarks'} />
	  </Layout>
	)
}

export default BookmarksPage

export const bookmarksQuery = graphql`
	query BookmarksQuery($bookmarks: String!) {
	  allMarkdownRemark(
	    sort: {fields: frontmatter___date, order: DESC}, 
	    filter: {id: {in: $bookmarks}}
	  ) {
	    edges {
	      node {
	        id
	        html
	        frontmatter {
	          date(formatString: "DD.MM.YY")
	          docs
	          path
	          tag
	          title
	        }
	      }
	    }
	  }
	}
`
```

Any hints on how to do that? I red a lot about createPage but does it make sense? I'm just using the Layout and List components, no markdown file. The function to get the data out of LS isn't implemented yet.

Thanks for your help! 👏

**Comment by shansmith01** [comment]
CreatePage runs at build time on the server and Gatsby has no idea of what is going to be in local storage on the client side at build time.

Have a look at this tutorial https://hackernoon.com/how-to-take-advantage-of-local-storage-in-your-react-projects-a895f2b2d3f2

**Comment by sidharthachatterjee** [comment]
@Siregar This is _not_ possible from what I understand because
1. GraphQL schema generation is done at build time and has no access to browser APIs or the _current_ user's browser instance
2. Queries are also resolved at build time and again in a non browser environment

You could use something like https://github.com/apollographql/apollo-cache-persist to persist to local storage and use apollo to get that data at runtime

Closing this for now thought since this is largely out of scope of what Gatsby can do! Please feel free to reopen or comment if there is anything else I missed.
