### ISSUE TITLE
Most efficient way to load dynamic data for e-commerce

### ISSUE THREAD

**Issue by LpmRaven** [gatsbyjs/gatsby#11306]
I'm looking for some advice on the best way to implement the retrieval of dynamic data. I have been working on building this website for a few weeks now. The page in question is my listing pages, here is an example: [Waterproof Jack - All Mens Products](https://waterproofjack.com/mens/)

Currently, all of my products are created at build-time from Contentful, this has some great advantages such as the load speed and I believe it is great for SEO. The prices on this page are retrieved by Apollo from a graphql-yoga and Prisma backend at load-time, so on a slower connection, you can see prices loading in after the products.

I now want to implement product filtering on my product listing pages, such as sizes, availability, price ranges, and colors, as you would expect these features on an e-commerce website. I am however concerned about the slow load of products onto the page, is there a way I could have best of both such as initially loading build-time products and then when the user modifies the filtering, load data using Apollo?

**Comment by jonniebigodes** [comment]
@LpmRaven if i'm reading this correctly let ask you some questions before i can try and answer your question

- Is the graphql-yoga and Prisma backend going to Contenfull for data or not? 
- Also is your client/website going for both endpoints? Contentfull loading at build time and price fetching on client load?

**Comment by LpmRaven** [comment]
- the graphql-yoga and Prisma backend doesn't get data from contentful, only the data for the prices. This is loaded into the prices component using apollo as shown below (with the apollo provider in both the gatsby-browser.js and gatsby-ssr.js files).
- Yes. Contentful loads data at build and Apollo loads price data on client load. The Contentful data is requested in the page (template) graphql (as you would normally request data) which is resoved at build time. 

### gatsby-ssr.js and gatsby-browser.js
```javascript
import React from 'react';
import { ApolloProvider } from 'react-apollo';
import client from './client';

export const wrapRootElement = ({ element }) => {
    return (
        <ApolloProvider client={client}>
            {element}
        </ApolloProvider>
    )
}
```

### Prices Component
```javascript
import React from 'react';
import { gql } from 'apollo-boost';
import { Query } from 'react-apollo';

import Deals from '../../components/deals';

const Prices = ({ productId }) => {
    return (
        <Query
            query={gql`
                query GetPrices($productId: String!){
                    prices (where: {productId : $productId}) {
                    productId
                    supplier
                    productUrl
                    currentPrice
                    supplierProductId
                    supplierUrl
                    region
                }
            }
        `}
            variables={{ productId: productId.toString() }}
        >
            {({ loading, error, data }) => {
                if (loading) return <p>loading...</p>;
                if (error) return `Error!: ${error}`;
                if (data && data.prices && data.prices.length > 0) {
                    return (
                        <Deals prices={data.prices} size="s" />
                    )
                };

                return null;
            }}

        </Query>
    )
}

export default Prices;
```

### templates/listings
```javascript
import React from "react";
import { graphql } from "gatsby";
import ErrorPage from '../error';

export default function Template({ data, pageContext }) {
  const { products } = data;

  if (products === null) {
    return (
      <ErrorPage />
    )
  }
  return (
    <all my contentful products here>
  )
}

export const pageQuery = graphql`
query {
  products: allContentfulProduct{
    edges {
      node {
          <all my data params here>
        }
      }
    }
  }
}
`
```

**Comment by jonniebigodes** [comment]
@LpmRaven based on my experience and what i'm reading here, i would take a different approach. I would get the contentfull data and the prices data from prism, during build time through `gatsby-node`. Meaning getting two datasets beforehand and when i have my data back i would apply the necessary transformations on it and create the necessary pages based on the template and passing the data via `pageContext`. Reason being, because of this exact issue. You're getting part of the data before. And only when a user visits the page and your website is rehydrated back to him, a request to fetch another part of the data, await for response, transform and finally show it. Which translates in a wait for a fetch request, parsing response, React re-render the contents and so on....
Will it take a little more work yes, it would. If i were you i would take a look at [this](https://www.gatsbyjs.org/packages/gatsby-source-graphql/) and get the prism data through there.

If you can avoid all of that beforehand, people would be more engaged in your product as opposed to get presented with the "loading" lingering on the right side. but these are just my two cents, and i'm stopping here, as this particular issue would lead to a very long discussion with probably very polar opinions and would even drag to what i like to call the "metaphysics" of development/ web development. I wish i could shed some insights on the matter.

**Comment by LpmRaven** [comment]
@jonniebigodes I do agree with you. Unfortunately, the prices data cannot be retrieved at build time as they update frequently and would require me to constantly rebuild the site. 

My question was more about how to implement product filtering, I don't want to have that "loading" state for the products themselves if I switched the product data request to client load.

I was considering having an initial dataset provided by the build time data from contentful and then when the user interacts with the filtering, get the data through some sort of rehydrate. What do you think?

**Comment by KyleAMathews** [comment]
How often do prices change and how quickly do you need to update the price?

**Comment by LpmRaven** [comment]
@jonniebigodes in the end I took your advice. Worked much better. Cheers!
