### ISSUE TITLE
[gatsby-plugin-sharp] Should srcset include the original image size?

### ISSUE THREAD

**Issue by gregrafferty** [gatsbyjs/gatsby#11326]
I've been building an image gallery but I've noticed that, no matter the sizes I specify to generate a fluid image, the srcset always seems to include a reference to the original image at its full resolution.

Is it at all possible to override this? Ideally I want to avoid uploading past a certain resolution or have the option of excluding the original from the srcset. I've included a screenshot below.

![image](https://user-images.githubusercontent.com/944366/51794393-099e7200-21ca-11e9-8691-1c081dd404b8.png)

Maybe there's another way I can do this (like resizing the originals to a lower resolution) but ideally I also want to keep the originals in there somewhere too as I plan to upload full resolution copies for a hidden download section.

**Comment by sidharthachatterjee** [comment]
@gregrafferty We _always_ include the original image by design 
https://github.com/gatsbyjs/gatsby/blob/1d5ccff73b0c6c0dffcb8f812e50f31b2d7b36ee/packages/gatsby-plugin-sharp/src/index.js#L649

If I understand correctly, you want to keep the original image but just not include it in the `srcset`, right?

**Comment by gregrafferty** [comment]
> Can you please elaborate on why you would like to exclude it?

@sidharthachatterjee I'm attempting to build an image gallery that will integrate with a third party API for the purpose of selling prints of photos. Ideally I want to keep the original images at full size in the repo so I can generate the optimised images for the site, but then still have the full quality originals hidden away in a randomly named folder so that I can use a third party service to download them for printing and keep them hidden from end users. So I'd prefer not to show the full resolution image in the srcset to reduce the risk of them being downloaded at full resolution and printed without purchase.

Thanks for your help.

**Comment by sidharthachatterjee** [comment]
Thank you for the details @gregrafferty 

If I understand correctly, besides excluding the original image in `srcset`, you would also need to exclude it from the built assets (since a _sharp_ 😛 user could inspect assets and look for originals in the same folder)

I'd lean towards not including the original image in the repository at all and starting off with a resized image.

**Comment by gregrafferty** [comment]
Thanks @sidharthachatterjee. I'll give that a go, the build time is pretty slow at the moment anyway (with only around 20 images at ~40 megapixels each it's taking around 6 minutes to generate all the resizes) so I think it might be my best option.
