### ISSUE TITLE
Create official page transition documentation

### ISSUE THREAD

**Issue by calcsam** [gatsbyjs/gatsby#11333]
We should convert the content in @TylerBarnes' blog post on `gatsby-plugin-transition-link` into part of our official documentation -- a section on "Adding page transitions" in the "Adding website functionality" section. 

While this should not be portrayed as the *only* way to do page transitions with Gatsby, it should be shown as a *good* way to do this.

An overview can be taken from the Overview page of https://transitionlink.tylerbarnes.ca/docs/ and the code examples can be taken from https://www.gatsbyjs.org/blog/2018-12-04-per-link-gatsby-page-transitions-with-transitionlink/.

Later we can add a second documented option (`gatsby-plugin-page-transitions`) but that will be a separate issue.

**Comment by alexieyizhe** [comment]
Hey, I'm just starting out with open source but I've worked with Gatsby for a bit now; could I work on this issue?

**Comment by stefanprobst** [comment]
@alexieyizhe Definitely!

IMHO what should be noted in a docs section on page transitions is that while `TransitionLink` is awesome it (naturally) does not support transitions when navigating with browser buttons.

**Comment by alexieyizhe** [comment]
Sounds good, noted :)

**Comment by TylerBarnes** [comment]
This is awesome! :)
@stefanprobst that's true and should definitely be noted. I have some plans brewing to add transitions to location history, but nothing in the plugin yet.
If you guys want an example using react-spring I wrote one up recently in this issue https://github.com/TylerBarnes/gatsby-plugin-transition-link/issues/34
It may or may not be useful. Let me know if you have any questions though, I'm happy to help out.

**Comment by gmossong** [comment]
It would be great to have the docs for this follow on from the tutorial, because, I first built my site using the techniques shown in the tutorial and now I'm working on integrating transitions. When dissecting Tyler's demo site there is all sorts of unfamiliar stuff going on that I've not yet encountered on my Gatsby journey so this is making it extra confusing I think and so far I haven't been able to get @TylerBarnes solution working, even after going over [the docs](https://transitionlink.tylerbarnes.ca/docs/transitionlink/) and reading the [blog post](https://www.gatsbyjs.org/blog/2018-12-04-per-link-gatsby-page-transitions-with-transitionlink/).

**Comment by alexieyizhe** [comment]
Hi, I've created a PR for this as you can see :)

**Comment by alexieyizhe** [comment]
@calcsam was wondering if you had a chance to take a look at the PR?
