### ISSUE TITLE
Expire Headers better metrics

### ISSUE THREAD

**Issue by frivolta** [gatsbyjs/gatsby#11388]
Hello,
I just published my first website using Gatsby, works great so far and I have 96 in page speed score and 85 in yslow in GTMetrix, since what seems to be an issue is that I have not set an expire header for the static resources (There are 18 static components without a far-future expiration date.) What would be the best way to achieve this? I couldn't find the right answer online, maybe I am noob.
Thanks!

**Comment by frivolta** [comment]
By the way, I already took a look at https://www.gatsbyjs.org/packages/gatsby-plugin-netlify/ since I am on Netlify but I couldn't figure out what I should do.

**Comment by sidharthachatterjee** [comment]
@frivolta Headers like Expire need to be set up where the content is hosted — in your case, Netlify

Check out the Netlify documentation to add custom headers at https://www.netlify.com/docs/headers-and-basic-auth/#custom-headers

Closing this since this isn't a Gatsby issue but please feel free to comment if there is anything else we can do to help!
