### ISSUE TITLE
[gatsby-source-wordpress] Wordpress Preview Link

### ISSUE THREAD

**Issue by colbyfayock** [gatsbyjs/gatsby#11435]
I'm curious, has anyone has found a good solution for managing the Preview link on Wordpress posts, particularly with the new Gutenberg editor?

The Preview link no longer seems to be as easily filterable, so my current thinking is having to build out the routes in Gatsby and support it, such as:

* /?post_type=blog_posts&p=[id]&preview=true
* /blog_posts/slug/?preview_id=[id]&preview_nonce=[nonce]&preview=true

This doesn't necessarily relate directly to Gatsby or the source plugin itself, but given the nice documentation for other Wordpress integration issues, was hoping someone may have some insight.

**Comment by cardiv** [comment]
Indeed, Gutenberg does not have lots of hooks. I disabled it for now because the available hooks do not allow a convenient workflow for me.

In a custom theme, I work on some workflow enhancements in using WP + Gatsby. This needs much more testing and development at the moment. Currently I test this with two projects and make it production ready.

The theme will feature:

- Publish changes (trigger build using webhook).
- Show current build status.
- Optimize ACF and WPML.
- **Preview** with query params.
- Custom API authentication that does not rely on user permissions.
- WooCommerce integration with Gatsby.
- Probably more.

For now, a preview involves custom development based on your needs. I hope that the theme will be battle tested soon with all the features I intended. And to present it to the public to harden it further.

**Comment by colbyfayock** [comment]
Sounds great! The triggering of builds with the button sounds great too. We're doing something similar hooking into `save_post` I believe in WP.

The Preview prevents the biggest issue for us, a big complaint is not being able to truly see the page on the site before publishing :/

**Comment by sidharthachatterjee** [comment]
Thanks for the info, @cardiv 

@colbyfayock Closing this since it isn't directly relevant to Gatsby or the source plugin but please feel free to reopen if there is anything else we can help with!
