### ISSUE TITLE
has CSS Delay when using client-routes pages (Hybrid app pages)

### ISSUE THREAD

**Issue by Steffi3rd** [gatsbyjs/gatsby#11473]
Hi, 

I'm using gatsby as Hybrid app.

On static pages, CSS is great, and displays instantanely.
But on client-routes only, (example: `/login` or `/account`) I have a delay on these pages.

Is there a way to fix that?

```
 System:
    OS: macOS 10.14.2
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.14.2 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 71.0.3578.98
    Safari: 12.0.2
  npmPackages:
    gatsby: ^2.0.0 => 2.0.85 
    gatsby-cli: ^2.4.6 => 2.4.8 
    gatsby-image: ^2.0.26 => 2.0.26 
    gatsby-plugin-emotion: ^4.0.1 => 4.0.1 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.5 
    gatsby-plugin-sharp: ^2.0.17 => 2.0.17 
    gatsby-source-filesystem: ^2.0.12 => 2.0.12 
    gatsby-transformer-sharp: ^2.1.10 => 2.1.10 
```

**Comment by sidharthachatterjee** [comment]
Hey @Steffi3rd 

If I understand correctly, the delay you're referring to is a result of the client side rendering of the route (or the lack of server side rendered markup for it)

Since client only routes aren't server side rendered this _seems_ unavoidable

Can you try moving some of the styles to a layout component and see if that helps?
