### ISSUE TITLE
gatsby-source-mongodb doesn't support Relationships

### ISSUE THREAD

**Issue by laurenskling** [gatsbyjs/gatsby#11587]
## Description

I have a relationship in my model. This relationship is stored in a `ObjectId`. This doesn't end up in the GraphQL schema (probably because it doesn't understand `ObjectId`'s). I also cannot use the `map` option, because it is not a String (https://github.com/gatsbyjs/gatsby/blob/c6fa2e130f4514713ad371bf431e91bbbc9b910d/packages/gatsby-source-mongodb/src/mapping.js#L5)

Is there a way for gatsby-source-mongodb to support `ObjectId`'s? Or even better, to support relationships and represent them in the GraphQL?

### Steps to reproduce

Create model with a relationship, having: `categories: ObjectId("592b1a24eccb1ddddfe2d593")` in your document.

### Expected result

The GraphQL schema should include `categories` with this ID, or even better, the actual Category from the Categories collection

### Actual result

`categories` was dropped from the node and doesn't end up in the GraphQL

### Environment

System:
    OS: macOS 10.14.2
    CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.5.0 - /usr/local/bin/node
    npm: 5.3.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 72.0.3626.81
    Firefox: 63.0.3
    Safari: 12.0.2
  npmPackages:
    gatsby: ^2.0.76 => 2.0.76 
    gatsby-image: ^2.0.22 => 2.0.25 
    gatsby-plugin-feed: ^2.0.8 => 2.0.11 
    gatsby-plugin-google-analytics: ^2.0.5 => 2.0.8 
    gatsby-plugin-manifest: ^2.0.5 => 2.0.12 
    gatsby-plugin-netlify: ^2.0.6 => 2.0.6 
    gatsby-plugin-offline: ^2.0.5 => 2.0.20 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.5 
    gatsby-plugin-sharp: ^2.0.6 => 2.0.16 
    gatsby-plugin-sitemap: ^2.0.4 => 2.0.4 
    gatsby-plugin-typography: ^2.2.0 => 2.2.3 
    gatsby-remark-copy-linked-files: ^2.0.5 => 2.0.8 
    gatsby-remark-images: ^2.0.4 => 2.0.6 
    gatsby-remark-prismjs: ^3.0.0 => 3.1.4 
    gatsby-remark-responsive-iframe: ^2.0.5 => 2.0.8 
    gatsby-remark-smartypants: ^2.0.5 => 2.0.7 
    gatsby-source-filesystem: ^2.0.2 => 2.0.12 
    gatsby-source-mongodb: ^2.0.12 => 2.0.12 
    gatsby-transformer-remark: ^2.1.6 => 2.1.17 
    gatsby-transformer-sharp: ^2.1.3 => 2.1.9 
    gatsby-transformer-xml: ^2.0.6 => 2.0.6

**Comment by sidharthachatterjee** [comment]
Thank you @laurenskling 

I'm not sure about the mapping but it seems like a bug if it drops the key altogether.

**Comment by laurenskling** [comment]
I've created environments to mimic my setup:
KeystoneJS setup, which is created MongoDB schema's and editing interface:
https://keystonedemoforgatsby.herokuapp.com/
you can log in at  https://keystonedemoforgatsby.herokuapp.com/keystone/
Sign in with the username demo@keystonejs.com and the password demo
Here i've created some relations between documents.

It has a mongoDB connection string: mongodb://heroku_jgnf32k2:dnr2nj3qo69puej1fvrgade7kl@ds129045.mlab.com:29045/heroku_jgnf32k2
as you can see, the relations are stored are `ObjectId()`

I've forked a gatsby starter: https://github.com/laurenskling/gatsby-starter-blog and added the mongo connection.
If you go to GraphQL, you can see most fields added, but not the relations: http://localhost:8000/___graphql?query=%23%20Welcome%20to%20GraphiQL%0A%23%0A%23%20GraphiQL%20is%20an%20in-browser%20tool%20for%20writing%2C%20validating%2C%20and%0A%23%20testing%20GraphQL%20queries.%0A%23%0A%23%20Type%20queries%20into%20this%20side%20of%20the%20screen%2C%20and%20you%20will%20see%20intelligent%0A%23%20typeaheads%20aware%20of%20the%20current%20GraphQL%20type%20schema%20and%20live%20syntax%20and%0A%23%20validation%20errors%20highlighted%20within%20the%20text.%0A%23%0A%23%20GraphQL%20queries%20typically%20start%20with%20a%20%22%7B%22%20character.%20Lines%20that%20starts%0A%23%20with%20a%20%23%20are%20ignored.%0A%23%0A%23%20An%20example%20GraphQL%20query%20might%20look%20like%3A%0A%23%0A%23%20%20%20%20%20%7B%0A%23%20%20%20%20%20%20%20field(arg%3A%20%22value%22)%20%7B%0A%23%20%20%20%20%20%20%20%20%20subField%0A%23%20%20%20%20%20%20%20%7D%0A%23%20%20%20%20%20%7D%0A%23%0A%23%20Keyboard%20shortcuts%3A%0A%23%0A%23%20%20Prettify%20Query%3A%20%20Shift-Ctrl-P%20(or%20press%20the%20prettify%20button%20above)%0A%23%0A%23%20%20%20%20%20%20%20Run%20Query%3A%20%20Ctrl-Enter%20(or%20press%20the%20play%20button%20above)%0A%23%0A%23%20%20%20Auto%20Complete%3A%20%20Ctrl-Space%20(or%20just%20start%20typing)%0A%23%0A%0Aquery%20%7B%0A%20%20allMongodbHerokuJgnf32K2Posts%20%7B%0A%20%20%20%20edges%7B%0A%20%20%20%20%20%20node%20%7B%0A%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20state%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A

This is most likely because `ObjectId`s are a bit weird. They cannot/willnot be converted to Strings when merging objects. So when the plugin does this: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-mongodb/src/gatsby-node.js#L79 the `ObjectId` fields are probably dropped from the object.

The solution? I don't know actually... I'm not a hero in MongoDB or in GraphQL for the matter.

**Comment by jonniebigodes** [comment]
@laurenskling let me take a look at it and see if i can offer a solution if you don't mind the wait.

**Comment by jonniebigodes** [comment]
@laurenskling i believe i have a solution for you. Below are described the steps i took in somewhat of a detail in order to allow the inclusion of relationships between documents in mongodb.

- Created a new Gatsby website using the hello world starter. 
- Created a plugins folder inside that site, to allow the development of a local plugin, more on that [here](https://www.gatsbyjs.org/docs/source-plugin-tutorial/).
- As i have a local mongob installation, i've replicated the mongodb structure you have demonstrated in your comment above and added some data, as you can see [here](https://github.com/jonniebigodes/test_gatsby_source_mongo_relationships/tree/master/db_dump).


- Grabbed the code from the plugin and started testing it to check out what was the problem. And indeed those types are not propagated through spreading the object.
- Did some testing and then it hit me. If you add `JSON.stringify(a_certain_document)` it will parse the ObjectId coming from mongodb.
So with that in mind i modified the `createNode` function inside `gatsby-node.js` file in my local plugin to the following:
```javascript
.....
cursor.toArray((err, documents) => {
            if (err) {
                reject(err)
            }

            documents.forEach(item => {
                var id = item._id.toString()
                delete item._id
                const stringifiedItem= JSON.stringify(item) // stringifies the mongodb object
                let reversed=JSON.parse(stringifiedItem) // parses it back and preserves the objectid's in the form of string
                var node = {
                    // Data for the node.
                   ...reversed,
                    
                    id: createNodeId(`${id}`),
                    mongodb_id: id,
                    parent: `__${collectionName}__`,
                    children: [],
                    internal: {
                        type: `mongodb${sanitizeName(dbName)}${sanitizeName(collectionName)}`,
                        content: JSON.stringify(item),
                        contentDigest: crypto
                            .createHash(`md5`)
                            .update(JSON.stringify(item))
                            .digest(`hex`),
                    },
                }
                const childrenNodes = []
                if (pluginOptions.map) {
                    let mapObj = pluginOptions.map
                    if (pluginOptions.map[collectionName]) {
                        mapObj = pluginOptions.map[collectionName]
                    }
                    // We need to map certain fields to a contenttype.
                    Object.keys(mapObj).forEach(mediaItemFieldKey => {
                        if (
                            node[mediaItemFieldKey] &&
                            (typeof mapObj[mediaItemFieldKey] === `string` ||
                                mapObj[mediaItemFieldKey] instanceof String)
                        ) {
                            const mappingChildNode = prepareMappingChildNode(
                                node,
                                mediaItemFieldKey,
                                node[mediaItemFieldKey],
                                mapObj[mediaItemFieldKey],
                                createNode
                            )

                            node[`${mediaItemFieldKey}___NODE`] = mappingChildNode.id
                            childrenNodes.push(mappingChildNode)

                            delete node[mediaItemFieldKey]
                        }
                    })
                }
                createNode(node)
                childrenNodes.forEach(node => {
                    createNode(node)
                })
            })
```
- Tested it out against my local database, by issuing `gatsby develop` and opening up `http://localhost:8000/___graphql` and the result is the following:
![laurenskling_relation_local_db_result](https://user-images.githubusercontent.com/22988955/53191814-bf5fb380-3604-11e9-9f01-17502b1174e8.png).
As you can see now the array of categories, that were not being created are now added.
- Updated the `gatsby-config` to use the example database you provided in your comment above. And the result is the following:

![laurenskling_relation_remote_db_result](https://user-images.githubusercontent.com/22988955/53192030-4ad94480-3605-11e9-806f-5f8e3f066a03.png)

The only thing i haven't tested out correctly are the mappings. To see if they are done right.
I still need to come up with a viable example for that.
But with this small fix you can have the information at your disposal.
The full code is [here](https://github.com/jonniebigodes/test_gatsby_source_mongo_relationships). If you want to make a pull request out of this, it's fine by me, i don't mind

**Comment by laurenskling** [comment]
Thanks for the research. 
I'm not sure if misusing JSON.stringify/parse is the way to go. Plus it'll be slow and error prone.

I think the best way to handle this is to actually follow the `ObjectId`s to their relationship. This will give the best GraphQL experience as well. But i'm not sure if the pure MongoDB output will actually tell you _what_ the relationship is. I was hoping some MongoDB wizard could shine a light on this.

**Comment by jonniebigodes** [comment]
> I think the best way to handle this is to actually follow the `ObjectId`s to their relationship. This will give the best GraphQL experience as well. But i'm not sure if the pure MongoDB output will actually tell you _what_ the relationship is. I was hoping some MongoDB wizard could shine a light on this.


From what i know it cannot achieve that. See [here](https://docs.mongodb.com/manual/reference/method/ObjectId/). "Thinking out loud", you would have to fetch all of the documents from all collections first and then match the ObjectId_A to collection_B  field_C. 
For small cases scenarios it wouldn't  be too troublesome. But when you go big and have alot of collections it could turn into a troublesome experience.

**Comment by laurenskling** [comment]
Thats what I hope MongoDB and Gatsby wizards can tell us :)

**Comment by jonniebigodes** [comment]
Did a little more research and if you want take a look at [this](https://www.gatsbyjs.org/docs/schema-gql-type/) to get you started if you want to pick up on this and make a change to the plugin.

**Comment by wesleylhandy** [comment]
@laurenskling @jonniebigodes 

I think I have a better solution. I need to run some tests, but I'll put in a pull request shortly if you are okay with it. I ran with some of your ideas, so I hate to take credit for everything, but I think the solution helps us all.

I imported your dataset @jonniebigodes and started working out a solution.

Basically, instead of using `.toString()`, MongoDB provides a function on ObjectID `toHexString()`. So I went ahead and changed that just to use something built in that works. Then, I created a recursive function that goes through each subdocument that looks for `typeof === 'string'` and checks to see if that is a valid `ObjectID` an if so returns it `toHexString()`. The only concern I have is how this will affect massive collections. 

Here's the code

    // add import of ObjectID
    const ObjectID = require(`mongodb`).ObjectID
    ....
    documents.forEach(doc => {
        const item = {...doc} // lets keep doc immutable
        const objectId = new ObjectID(item._id)
        const id = objectId.toHexString();
        delete item._id

        for (let key in item) {
          item[key] = stringifyObjectIds(item[key])
        }
    ....
    function stringifyObjectIds(val) {
      if (typeof val === 'string') {
        if (ObjectID.isValid(val)) {
          const objId = new ObjectID(val)
          return objId.toHexString();
        } else {
          return val
        }
      } else if (typeof val === 'object') {
        if (Array.isArray(val)) {
          return val.map(el=>stringifyObjectIds(el))
        } else {
          const keys = Object.keys(val)
          return keys.reduce((obj, key)=>{
            obj[key] = stringifyObjectIds(val[key])
            return obj;
          }, {})
        }
      } else {
        return val
      }
    }

What do you think?

**Comment by jonniebigodes** [comment]
@wesleylhandy go for it. I havent' had the time to test it out, but if you say it works it's fine by me, good luck with the pull request.

Side note, regarding the large collections you mentioned, for now and if you and the team does not mind, probably start with a modification in the appropriate documentation mentioning that people should be aware that large to extremely large collections can have some impact while building their site. Sounds good @pieh ?

**Comment by wesleylhandy** [comment]
@jonniebigodes you bring up a good point about large collections. It makes me think a few things. 1) how many large collections would use a relational approach over an aggregation approach to their architecture and 2) perhaps it's better to pass a parameter to the plugin to opt in to this feature.

**Comment by jonniebigodes** [comment]
@wesleylhandy regarding your points. For the first one, while being involved in the "industry" for as long as i have, one thing that i've learned early, was that people never cease to amaze and come up with inventive ways to have data stored. Regarding your second point, a option parameter sounds perfect. If people have the data shaped that way, pass in the said parameter in `gatsby-config.js`, under the plugin. Otherwise if not, no need for the said flag or pass it with for instance a value of false.

**Comment by wesleylhandy** [comment]
@jonniebigodes Good points. I made this an opt-in feature by setting `preserveObjectIds: true` within the plugin options

**Comment by laurenskling** [comment]
Thanks @wesleylhandy , this totally fixed it for me!
