### ISSUE TITLE
onInitialClientRender not called on IE10

### ISSUE THREAD

**Issue by gluemonkey** [gatsbyjs/gatsby#11604]
## Description

onInitialClientRender is never called and initial client render does not happen in IE10

### Steps to reproduce

View a basic starter build in IE10 and notice that render is never called within your components.

### Expected result

onInitialClientRender should be called inside of gatsby-browser.js and your React components should render.

### Actual result

onInitialClientRender is not called inside of gatsby-browser.js and your React components do not render.  Pre-rendered version still loads.  Upon navigating and hitting the back button the intended functionality will occur.

### Environment

Standard gatsbyjs build.

### Workaround

Using yarn I am able to override the domready version and this seems to fix the issue
```
"resolutions": {
    "domready": "1.0.7"
  }
```

Please refer to this issue - https://github.com/ded/domready/issues/53

**Comment by jonniebigodes** [comment]
@gluemonkey i've picked up on your issue. And below are the steps i've taken and the results achieved.

- Created a new Gatsby website using the default starter through `gatsby new test_quick_start`
- Updated `gatsby-browser.js` to the following to check if i could get it to trigger:

```javascript
exports.onInitialClientRender=()=>{
    console.log(`onInitialClientRender was fired`);
}
```
- Issued `gatsby develop` and waited to the process to complete.
- Opened edge (as i don't have access to ie10 currently) and the devtools, switched emulation to the following:
![emulation](https://user-images.githubusercontent.com/22988955/52501345-03e85980-2bd8-11e9-84e8-1fdca0ee2e64.png)
- With the emulation activated the site was re-rendered and switching to the console tab i'm presented with this:
![console](https://user-images.githubusercontent.com/22988955/52501390-20849180-2bd8-11e9-9202-eb9e1f98980c.png)

As you can see the site is being rendered and browser api is triggered, No issues whatsoever from my side. It could be that you have something else happening in the api that could be causing the issue.
If the work you're doing is not private or otherwise protected, if you can share a repository with the code it would be great so that it could be further investigated. Otherwise, create a dummy repository with the code that triggers the issue you've experienced.

Feel free to provide further feedback so that this issue can be solved.

**Comment by sidharthachatterjee** [comment]
Based on https://github.com/ded/domready/issues/53 it does seem that IE10 support is broken by domready after 1.0.7 because of some regex matching code that was added

Let me try reproducing this and I'll post what I can find here

**Comment by franksmule** [comment]
Same issue although for me - although 1.0.7 does not work either.
I needed to add a fallback window load listener to the domready lib.

**Comment by mikaelkristiansson** [comment]
any updates about this? It still doesn't work if I downgrade domready to 1.0.7.
