### ISSUE TITLE
Importing data from two excel sheets create issue - gatsby-transformer-excel [help wanted]

### ISSUE THREAD

**Issue by paulgaumer** [gatsbyjs/gatsby#11617]
## Description

Hi there! 
I am developing a paycheck document generator, importing data from an excel file called "salaries" using `gatsby-transformer-excel`. 

This file has 2 sheets: "Sheet1" and "Sheet2". My plan is to have one sheet per employee, meaning the headers will be the same on all sheets, but data will differ.

While the GraphQL request works perfectly if "Sheet1" only exists, I face an error everytime I create "Sheet2" with the same headers as "Sheet1". If the two sheets have totally different headers, everything works fine.

### Steps to reproduce

I created a repo reproducing the error. Simply run `npm install` then `gatsby develop` and the error should appear in your terminal 

[https://github.com/paulgaumer/gatsby_excel_issue_example](https://github.com/paulgaumer/gatsby_excel_issue_example)

### Expected result

Normally, the app should be able to compile and I should be able to run the following request in GraphiQL

```graphql
{
  allSalariesXlsxSheet1 {
    edges {
      node {
        name
        gross
      }
    }
  }
  allSalariesXlsxSheet2 {
    edges {
      node {
        name
        gross        
      }
    }
  }
}
```

### Actual result

The app doesn't compile and terminal displays
```
success open and validate gatsby-configs — 0.009 s
success load plugins — 0.269 s
success onPreInit — 1.146 s
success delete html and css files from previous builds — 0.051 s
success initialize cache — 0.006 s
success copy gatsby files — 0.097 s
success onPreBootstrap — 0.005 s
success source and transform nodes — 0.108 s
success building schema — 0.326 s
error Cannot read property 'allSalariesXlsxSheet1' of undefined


  TypeError: Cannot read property 'allSalariesXlsxSheet1' of undefined

  - gatsby-node.js:21 graphql.then.results
    /Users/paulgaumer/Documents/CODE_PERSO/PDF_generator/pdftest/gatsby-node.js:21:20

  - util.js:16 tryCatcher
    [lib]/[gatsby-cli]/[bluebird]/js/release/util.js:16:23

  - promise.js:512 Promise._settlePromiseFromHandler
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:512:31

  - promise.js:569 Promise._settlePromise
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:569:18

  - promise.js:606 Promise._settlePromiseCtx
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:606:10

  - async.js:142 _drainQueueStep
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:142:12

  - async.js:131 _drainQueue
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:131:9

  - async.js:147 Async._drainQueues
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:147:5

  - async.js:17 Immediate.Async.drainQueues [as _onImmediate]
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:17:14


error UNHANDLED REJECTION


  TypeError: Cannot read property 'allSalariesXlsxSheet1' of undefined

  - gatsby-node.js:21 graphql.then.results
    /Users/paulgaumer/Documents/CODE_PERSO/PDF_generator/pdftest/gatsby-node.js:21:20

  - util.js:16 tryCatcher
    [lib]/[gatsby-cli]/[bluebird]/js/release/util.js:16:23

  - promise.js:512 Promise._settlePromiseFromHandler
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:512:31

  - promise.js:569 Promise._settlePromise
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:569:18

  - promise.js:606 Promise._settlePromiseCtx
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:606:10

  - async.js:142 _drainQueueStep
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:142:12

  - async.js:131 _drainQueue
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:131:9

  - async.js:147 Async._drainQueues
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:147:5

  - async.js:17 Immediate.Async.drainQueues [as _onImmediate]
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:17:14
```

### Environment
```
System:
    OS: macOS 10.14
    CPU: (4) x64 Intel(R) Core(TM) i5-7Y54 CPU @ 1.20GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 11.8.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.5.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 71.0.3578.98
    Firefox: 64.0.2
    Safari: 12.0
  npmPackages:
    gatsby: ^2.0.76 => 2.0.76
    gatsby-image: ^2.0.20 => 2.0.25
    gatsby-plugin-manifest: ^2.0.9 => 2.0.12
    gatsby-plugin-offline: ^2.0.16 => 2.0.20
    gatsby-plugin-react-helmet: ^3.0.2 => 3.0.5
    gatsby-plugin-sass: ^2.0.8 => 2.0.8
    gatsby-plugin-sharp: ^2.0.14 => 2.0.16
    gatsby-plugin-styled-components: ^3.0.4 => 3.0.4
    gatsby-source-filesystem: ^2.0.20 => 2.0.20
    gatsby-transformer-excel: ^2.1.7 => 2.1.7
    gatsby-transformer-sharp: ^2.1.8 => 2.1.9
  npmGlobalPackages:
    gatsby-cli: 2.4.8
```

**Comment by jonniebigodes** [comment]
@paulgaumer i've picked up on your issue, i'm currently testing out something. I'll provide you with an answer shortly. Sounds good?

**Comment by jonniebigodes** [comment]
@paulgaumer after some testing with the repository i was able to come up with a solution for your issue.
Breaking it into smaller parts for better understanding:
- Cloned the repo and installed the dependencies.
- Issued `gatsby develop` got the error you reported straight out of the box.
- Commented out all of the graphql part of the code and issued `gatsby develop` to get at least a successful build. 
- Opened up `http://localhost:8000/___graphql` and tried the following graphql query:
```graphql
allSalariesXlsxSheet1 {
    edges {
      node {
        id
        name
        gross
      }
    }
  }
```
It showed me errors saying that those fields don't exist. 
- Changed the query to:
```graphql
allSalariesXlsxSheet2 {
    edges {
      node {
        id
        name
        gross
      }
    }
  }
```
It worked without any issues.
- Then it hit me, let me check the .xlsx file, both sheets. And i thought ok, the items are equal in both, let's make some adjustments just to see what might be the issue there, so with that reasoning i've prefixed `s1_` to all of the colums in the first sheet, transforming it like so:
```
s1_id, s1_name....
```

- Saved the file, cleared `.cache` and `public` folder to get a clean slate. Build was successful as expected.
Opened up `http://localhost:8000/___graphql`, "threw the kitchen sink" (pardon the bad pun), namelly get all of the data
And it worked, as you can see bellow:
![allsalaries](https://user-images.githubusercontent.com/22988955/52443751-73017780-2b1e-11e9-8170-01ebcc20997d.png)

My reasoning for this issue, is the following, or one of the plugin's dependencies does not like equal names in the columns for separate sheets, or this case was not considered/covered in the plugin. I'm speculating here as i'm not "intimate" with the plugin and it's code. 
So it looks like for you to get your issue solved, it seems that you'll have to make some adjustments beforehand so that Gatsby and the xslx files can work together.
Feel free to provide some feedback if my comment was helpfull, so that we can close this issue.

**Comment by paulgaumer** [comment]
Thanks a lot @jonniebigodes, this does help! I'll fall back to this solution for now.

I was under the impression that simply having a different name for each sheet would create a new node in the data, and that the any children nodes would behave independently. I'd be interested to hear from people in the same situation.

**Comment by pieh** [comment]
@paulgaumer the `id` column in your spreadsheets is used to identify nodes - this mean that when we create nodes for second spreadsheet (nodes with id `1` and `2`) it overwrites nodes from first spreadsheet (with same ids). This is a bug in excel transformer - we shouldn't use value of `id` column for gatsby node id. Instead we should transform `id` from spreadsheet into something like `c_id` or `x_id` (just prefix it with something) and instead generate gatsby node id using name of file, name of stylesheet and row of stylesheet.

In meantime you probably could just rename `id` column to something else - so this is very similar advice as @jonniebigodes gave

**Comment by paulgaumer** [comment]
@pieh thanks a lot, that was it! Naming the column `id` was messing everything up. Makes total sense now!
The ticket can be closed 🙏
