### ISSUE TITLE
Add Loki to npm test script

### ISSUE THREAD

**Issue by stefanprobst** [gatsbyjs/gatsby#11676]
Now that[ we are testing with Loki in CI](https://github.com/gatsbyjs/gatsby/blob/5adb2a3beb10ff9ca9fd58b351d8e6bbb0dd05a1/.circleci/config.yml#L59), should we also adjust the [npm `jest` script](https://github.com/gatsbyjs/gatsby/blob/5adb2a3beb10ff9ca9fd58b351d8e6bbb0dd05a1/package.json#L70) (or add a `jest:loki` script?)

**Comment by pieh** [comment]
Good question. For the most part this doesn't matter for 99% of contributors because they don't touch code related to nodes data store / sorting and filtering nodes when querying (things that are different when using loki), so maybe we could add this as connivence script (`jest:loki`), but don't run it when running regular `jest`?

**Comment by wardpeet** [comment]
how do we feel about running jest:loki in ci when gatsby-core changes?

**Comment by KyleAMathews** [comment]
We can always add more concurrency correct if builds are getting slow?

**Comment by m-allanson** [comment]
> how do we feel about running jest:loki in ci when gatsby-core changes?

I like this idea 👍

**Comment by m-allanson** [comment]
Oh I misread - we already run the Loki tests in CI

**Comment by wardpeet** [comment]
@m-allanson do we? I don't think so :blush:

**Comment by pieh** [comment]
@wardpeet we do: https://github.com/gatsbyjs/gatsby/blob/master/.circleci/config.yml#L58-L59 it just wasn't worth to add another check, so it was added as step to unit tests
