### ISSUE TITLE
pageContext is not updated when context change

### ISSUE THREAD

**Issue by RageYL** [gatsbyjs/gatsby#11691]
Hi,

The issue is not as straightforward as i thought it would be, so here is a repo to reproduce it: https://github.com/RageYL/gatsby-pageContext

And this is different from https://github.com/gatsbyjs/gatsby/issues/6097

I use context from createPage to pass data to a template (I started using gatsby 3 days ago, so not 100% sure if this is the good way), but when the data is updated the pageContext value is not updated.
The pageContext is not updated if:
- there is a query using MarkdownRemark (i tried without query or with sitePage and no problem)

If you confirm this is indeed an issue, i'm ready to dig in and submit a pull request.

**Comment by jonniebigodes** [comment]
@RageYL i've picked up on your issue, i've cloned your repo into my machine installed it and did some tests, namelly:
- Created a json object with a similar structure and provided the data from the json file.
- Updated the template to implemement the livecycle method `componentDidUpdate` and `getDerivedStateFromProps` to see if it could solve the issue.
- Passed not the object but the property to `pageContext`, to see if produced an update.

As you can see bellow, the value of `datafromJson` on the right, the devtools is `x` and on the left is `b`
![noupdate](https://user-images.githubusercontent.com/22988955/52579216-a34a5e00-2e1d-11e9-87d6-ab649c2a1ca0.png)

 My reasoning for this behaviour  is that as is, the api hook, either with your object or mine, is on a "fire and forget" mode, it fetches the data once, passes it along and doesn't care about subsequent changes. What you could probably do is on `gatsby.node.js` filem is the following, you add a watcher to the file to see if it has changed, and if so, delete the page and recreate it. I have not tested this And it's not tested.

Also three days into Gatsby and already into one api that people tend to struggle more. Congratulations are in order.
Feel free to provide feedback ,so that we can close this issue

**Comment by RageYL** [comment]
What i find very strange is that everything works fine if there is no query or if i change the query's content (maybe something related to MarkdownRemark resolvers and the cache).
I updated my gatsby-node.js to use createPageStatefully (better choice indeed as my data is not managed by gatsby): https://github.com/RageYL/gatsby-pageContext/blob/createPagesStatefully/gatsby-node.js

Now if i update the data and restart gatsby the change is reflected on the page, but when i update without restarting gatsby, the page still display the same value. So it's already better, but it seems there is still something wrong with the cache.

**Comment by pieh** [comment]
Ok, this is bit problematic. There was related fix some time ago - https://github.com/gatsbyjs/gatsby/pull/11048 (which is totally fine).

But reason it doesn't work for this use case is that we don't check page contexts between runs (and this is not quite easy to do right now, but doable). In `createPage` we could first check if we already have that page in memory store - if we do continue as is, if not we would want to load cached query results for that page - just to grab content used for that, and then we could compare and set `contextModified` flag on action which will trigger query re-run

**Comment by pieh** [comment]
I didn't notice you commented while I was writing previous comment

> What i find very strange is that everything works fine if there is no query or if i change the query's content (maybe something related to MarkdownRemark resolvers and the cache).

For the most part this is because we try to cache our query results so subsequent runs don't do extra work and re-use cached results. But there are cases where we don't invalidate our cache and you hit one of those.

**Comment by RageYL** [comment]
Hum, i think i managed to make it work with createPagesStatefully.

When the file changed i was deleting the page and then creating it again.
But by studying `redux/actions.js`, if the page is deleted, `oldPage` is undefined and `contextModified` is set to `false`.
By not deleting the page, `contextModified` is set to `true` and the page is refreshed correctly.

So it seems to work correctly with createPagesStatefully: https://github.com/RageYL/gatsby-pageContext/tree/createPagesStatefully

As the documentation says: "Like createPages but for plugins who want to manage creating and removing pages themselves in response to changes in data not managed by Gatsby". So maybe this is a non-issue and was just me using the wrong approach ?

**Comment by pieh** [comment]
@RageYL this change would cause gatsby to always rerun all queries in bootstrap.
What we probably need is to purge node dependencies for page when you delete - in here https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/redux/reducers/component-data-dependencies.js we would need to handle `DELETE_PAGE` action and remove node/connection dependencies. Then we you re-create page our query runner will run query for it because the path doesn't yet have any dependencies ( https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/internal-plugins/query-runner/page-query-runner.js#L43-L45 )

**Comment by RageYL** [comment]
I think your solution may not work in certain situations: in the first case I
presented, the page is created once with createPage. The server had to be
reloaded manually for the change to take effect. In this case the next time
gatsby is run, createPage would be called again, but deletePage would be never
called and thus the page would not be re-evaluated (this could also happen if
there is a watcher calling deletePage when the file is modified: if the file is
modified while gatsby is not running, the deletePage would never be called).

One way I can think about solving this would be to also write the context in
.cache and compare it with the newly created context. like you do with the
pages.

Or maybe why is `oldPage` undefined on the first run if the page is still in the
cache ?

Just some thoughts =)

**Comment by RageYL** [comment]
I'm not sure if i'm allowed to do that, but as yesterday's last edit may provide a solution for the problem, i'm writting a new comment to be sure you get notified.

**Comment by LekoArts** [comment]
This was fixed in the meantime.
