### ISSUE TITLE
react-select css not working on Gatsby Static Build

### ISSUE THREAD

**Issue by nsisodiya** [gatsbyjs/gatsby#11704]
This may be the most probably problem with React Select.
I have created Issue on their github repo too - https://github.com/JedWatson/react-select/issues/3422

Here is the summary of the issue.
When I am using react-select, I am seeing difference in static build vs development ui.

So, If I don't disable the JavaScript, This is what it shows on browser.
![image](https://user-images.githubusercontent.com/333455/52616822-d80ef180-2ebf-11e9-987c-0d05d611f508.png)

But If I disable the JavaScript, I am seeing this
![image](https://user-images.githubusercontent.com/333455/52616841-e8bf6780-2ebf-11e9-8660-59996858b718.png)

Please guide us.

**Comment by nsisodiya** [comment]
Here is the repo for this bug - https://github.com/nsisodiya/react-select-gatsby-bug

**Comment by pieh** [comment]
Hmmm this is tough and not very intuitive. `react-select` seems to use `emotion` for styling (no regular plain css). 

Because of that you would need to add `gatsby-plugin-emotion` plugin so it can extract critical css for initial render/javascript disabled scenario. Kind of another tricky thing is that `react-select` uses `emotion@9` (latest is `emotion@10`), so you would also need to install older version of `gatsby-plugin-emotion` (and its peer dependencies):

```
npm install gatsby-plugin-emotion@^2 emotion@^9 emotion-server@^9 react-emotion@^9
```

and then add `gatsby-plugin-emotion` to your `gatsby-config` plugin list.

This seems to fix it for me.

**Comment by nsisodiya** [comment]
@pieh Thanks a help. Just curious,
because Styled-Component is also css in js kind of mechanism, This kind of problem will occur with styled-components too?
it is true.

**Comment by lhache** [comment]
Hey @nsisodiya, did it fix your issue? I'm having the same one but no luck, it didn't help.
