### ISSUE TITLE
gatsby-transformer-xml uses unmaintained dependencies to parse xml

### ISSUE THREAD

**Issue by laurenskling** [gatsbyjs/gatsby#11736]
## Summary

`gatsby-transformer-xml` uses https://github.com/segmentio/xml-parser to parse XML, but this package is not being maintained. 
For me, it's lacking CDATA support, but without a maintainer there is no fix for me to get this working in Gatsby :(
What can we do about it?

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by jonniebigodes** [comment]
@laurenskling thank you for opening the issue.
As this is being addressed i'm currently working on a alternative so that you can parse xml documents with Gatsby. If you don't mind waiting a bit longer, i'll post a alternative for you shortly, i have almost complete just needs a bit of tweaking, sounds good?

**Comment by pieh** [comment]
@jonniebigodes does your alternative have similar api to `gatsby-transformer-xml`? Maybe we should just bump major version and use that for it?

**Comment by pieh** [comment]
But back to the question - we are happy to review / accept PR that will swap unmaintained dependency in the plugin - ideally if it would mean breaking changes for users, but it wouldn't be blocker if there would be (as mentioned in previous comment - we can bump major version if there would be breaking changes)

**Comment by laurenskling** [comment]
@jonniebigodes , sure I can wait :) currently I'm running a fork of `xml-parser` with a dirty CDATA `.replace`, but would love to get a stable fix.

I'm no hero in XML, but would love to help out testing a new tool.

**Comment by jonniebigodes** [comment]
@laurenskling i've created a simple proof of concept like i mentioned. But before we head down that road, a side note.
Before some actual implementation i did a little research on alternative packages that could be more of help.
After applying some metrics to it, namelly:
 - Package update ratio
 - Number of uses/downloads in both github and npmjs.com
- Options available
- Ease of use
- Adaptability to the current plugin.
- Package dependencies

After taking some "out for a spin"( pardon the bad pun), i narrowed it down to these 3
- [xml-js](https://github.com/nashwaan/xml-js)
- [fast-xml-parser](https://github.com/NaturalIntelligence/fast-xml-parser)
- [xml2js](https://github.com/Leonidas-from-XIV/node-xml2js)

Regarding update they all seem pretty active in the past year.
After some more reading and testing on them, it looks like that fast-xml-parser is basically a carbon copy of xml2js with some tweaks. xml2js looks good on paper but the way it handles the element attributes can be a bit tricky. 
Regarding the options all of them are basically the same.
Same as the ease of use, 
Regarding adaptability to the current plugin, all of them look good on paper.
In terms of dependencies xml2-js adds one more, due to the fact that it works both ways, it can parse and can create, which could be used further down the line but not at this moment.

I narrowed it down to  xml-js as at this point creating xml is not a option at this moment.

A couple more things before the actual implementation:
- This example was built trying to respect the existing api, in order not to introduce some breaking changes. It's nowhere perfect and probably still needs some work, i've probably missed out some cases while doing this.
- There's one thing that might be a bit problematic, the packages used add a property `text` or `_cdata` to diferentiate the types.
- There are some examples provided with the code. the ones that i've used to try it out. They contain some xml files that were used to test out this.


The full code is hosted [here](https://github.com/jonniebigodes/test_gatsby_xml_parser_alternative). It was implemented as a local gatsby plugin, more on that [here](https://www.gatsbyjs.org/docs/source-plugin-tutorial/), so that it could be better tested with graphiql and so on.
If you want to check out the actual code on how it's parsed and the nodes are generated it's [here](https://github.com/jonniebigodes/test_gatsby_xml_parser_alternative/blob/master/plugins/gatsby-transformer-xml-alternative/gatsby-node.js). Once again i would like to point out that is nowhere perfect and that some cases might not work. Also that the code itself could be more streamlined.

**Comment by laurenskling** [comment]
Thanks for the detailed research. 
@pieh what would be steps to take to create a new version for gatsby-transformer-xml?

**Comment by jonniebigodes** [comment]
@laurenskling i'm going to push tomorrow some changes i've done to the code i've provided. If you want to pick up from there fine by me. At least two issues are corrected.

**Comment by laurenskling** [comment]
I would still love to see a fix for this, dear gatsbot :)

**Comment by jonniebigodes** [comment]
haven't had the time to work on this....will get back soon

**Comment by laurenskling** [comment]
Thanks Gatsbot! Still would like to keep this open a bit

**Comment by MadsMadsDk** [comment]
I'm currently looking into this issue. I've started out with @jonniebigodes example, and it seems to be working pretty well with a rather complex XML file I have at hand.

There's some breaking changes to how to write a query though.

**Before**

```graphql
{
  allBooksXml {
    edges {
      node {
        name
        xmlChildren {
          name
          content
        }
      }
    }
  }
}
```

**After**
```graphql
{
  allBooksXml {
    edges {
      node {
        attributes { id }
        author { text }
        title { text }
        genre { text }
        price { text }
        publish_date { text }
        description { text }
        description_html { cdata }
      }
    }
  }
}
```

So basically you would query the name of your XML element instead of just having an array of XML children.

I think we might need to bump to a new major version for this package, if this is the way to go. It supports cdata as well.

**Comment by laurenskling** [comment]
@jonniebigodes think we can give this a swing again? My project is still struggling with this old xml-parse tool

**Comment by MadsMadsDk** [comment]
This issue is not stale. An open pull request is awaiting review.

**Comment by jonniebigodes** [comment]
this is not stale the pr is still under review
