### ISSUE TITLE
Styling applies to all documents not documents that import the stylesheet.

### ISSUE THREAD

**Issue by ChildishhAlbino** [gatsbyjs/gatsby#11756]
## Relevant information

Was creating a page on my website for my friends birthday which used a separate scss file. Upon importing it into the relevant page, all my pages now shared the styling. I'm not saying this is a bug but it seems weird that documents that no direct link to said SCSS file would be affected by it's styling.

Is this intended behaviour or a side affect of something in the way the styling is applied? 

I've found a workaround for now but if anyone has a better idea please let me know.

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by pieh** [comment]
We don't automatically scope styles, so they are always global. Workaround (that you might have used) is to add scoping on your own - i.e.:

```scss
.template-X {
  .rule {
    color: pink;
  }
}
```

and add `template-X` class to top level html element in your template

**Comment by ChildishhAlbino** [comment]
Thanks for answering my question. I wasn't expecting this

From what I understand of your workaround, it would work as long as the element I was trying to change the background of was inside of the top level HTML object on my page. 

Unfortunately my problem occurs because both stylesheets are changing the background of the body element. My workaround involved changing the background of a div and making it look like it was the body. Probably could've explained this better in my original post.

```
.div {
	background-color: hotpink;
	color: white;
	position: absolute;
	border-radius: 0;
	top: 0;
	left: 0;
}
```

Not the cleanest solution imo but i'll live. Feel free to let me know if i've misunderstood something :D

**Comment by pieh** [comment]
Ah, yeah if you have rules applying to elements above "page" component then my suggestion wouldn't work. I think your workaround is best solution here.

What we would need to do is to load/unload styles, but we currently are not in charge of it - this is all handled by webpack runtime :(

**Comment by tjmcewan** [comment]
I was bitten by this also - twice.  The two side effects I noticed are:

1. page looks good in dev, but deploy to prod and find that there are no styles because I forgot the layout component.
2. want to start a page with an entirely new layout but this is impossible to develop on because another page loads `foundation.css` which applies styles globally (so the above workaround won't work).

To isolate foundation, I've found I can rename it to `foundation.js` and make the whole file a string 

```
export default `
@charset "UTF-8"; /*! normalize.css v8.0.0 | MIT License | github.com/necolas/normalize.css */
html {
  line-height: 1.15;
  -webkit-text-size-adjust: 100%;
}
...
`
```
and import into `emotion` like this:
```
import { css } from "@emotion/core"
import foundationCSS from '../styles/foundation'
...
<div css={css(foundationCSS)}>
  {children}
</div>
```

But now I need to find a way to isolate 40-odd individual & linked `.scss` files with variables and mixins throughout.  Is there a way to isolate `.scss` imports without having to put them all into their own scoping classes or converting them all to a component-based solution?  I.e. at the webpack level?

To be clear, the built site works as expected; it's just development that displays the issue.  For now, I'll probably just comment out the other imports while I'm working on the new layout.
