### ISSUE TITLE
Layout components best practices

### ISSUE THREAD

**Issue by iakovosvo** [gatsbyjs/gatsby#11769]
Can someone recommend a good approach for customizing layout components with Styled Components? I am trying to decide whether I should have one big layout component on which I will conditionally render children using the location pathname to each own layout tags or have separate layout components for each page. 

For example for my index, contact and about section I can use the main Layout component I already have. For the page that I am listing items, I need a grid layout but for the detailed item page, I need a different layout.

**Comment by pieh** [comment]
It might depend on how much your layout changes - if those are subtle changes then single layout is ok. But I would advise not to use location, but instead pass prop from page component:

```
<Layout variant="grid">
  <RestOfPageComponents/>
</Layout>
```

That way your pages control which layout exactly is used and you don't need to rely on location to pick correct one.

If you changes are vast then creating separate layout components make sense - it would still be similar to what I showed above, but instead page component would use different layout instead of passing prop.

**Comment by aesthytik** [comment]
Yeah like @pieh said. Depending upon your extent of changes between your pages you can have separate layouts. If changes are minor simply passing props from each page is a great choice :)
