### ISSUE TITLE
Question about gatsby queries

### ISSUE THREAD

**Issue by universse** [gatsbyjs/gatsby#11766]
I am just curious how data from page queries and static queries are stored client-side. Say I have the exact same queries in different pages/components, are the data shared between those pages or the browser needs to download the data separately for each page/component. And what about cases where I run multiple queries in a page, in which one queries data without page variables while others query the exact same data, but with variables (for sorting/limiting/filtering etc).

**Comment by pieh** [comment]
We currently don't optimize results of queries like that. It's just one .json file with query results for each page

**Comment by pieh** [comment]
But if we were to do something like that, we would definitely try to match queries exactly so if one query used some arguments (sorting/limiting/filtering) it would be different than query not using them or using different arguments

**Comment by pieh** [comment]
So right now, it's up to user to "optimize" queries. If in page/template query you have queries that don't use parameters/variables - it's probably good opportunity to move them to [`StaticQuery`](https://www.gatsbyjs.org/docs/static-query/) / [`useStaticQuery`](https://www.gatsbyjs.org/docs/use-static-query/) - because then data won't bu duplicated for each page query results

**Comment by universse** [comment]
Thanks for the clarifications.
