### ISSUE TITLE
Can I create nodes based on a graphql query?

### ISSUE THREAD

**Issue by leworking** [gatsbyjs/gatsby#11760]
I am trying to create nodes in `gatsby-node.js` through `sourceNodes`, so that I can read them later on through `createPages` 

But I want to create nodes based on information I retrieve through *graphql*.

AFAIS, I only have access to *graphql* within the `createPages` function

```
export const createPages = ({ graphql, actions }) => {
```

So the question is, if I want to have access to `graphql` in `sourceNodes`

```
export const sourceNodes = ({ actions, createNodeId, createContentDigest }) => {
```

how could I? Or can I?

**Comment by pieh** [comment]
It's not possible because graphql schema doesn't exist yet. But you have some programmatic access to already existing nodes through some functions passed to our node APIs:

```js
export const sourceNodes = ({ actions, createNodeId, createContentDigest, getNode, getNodes, getNodesByType }) => {
  const singleNodeById = getNode("some-id")
  const arrayOfAllTheNodes = getNodes()
  const arrayOfNodesOfGivenType = getNodesByType("some_type")
  // do some programmatic with those nodes
}
```

What are you trying to do?

**Comment by leworking** [comment]
No, but I'm trying to use `graphql` to retrieve data from an **external** api. Maybe all I need is to import `graphql` and use it as usual?

**Comment by pieh** [comment]
Ah!
Then yeah. You need to have your own graphql client. There are few examples of this:
 - we do it on gatsbyjs.org site (to get extra data from github graphql api - https://github.com/gatsbyjs/gatsby/blob/master/www/gatsby-node.js#L26-L33 + https://github.com/gatsbyjs/gatsby/blob/master/www/gatsby-node.js#L572-L587)
 - gatsby-source-shopify does this too https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-shopify/src/lib.js

**Comment by leworking** [comment]
Yes, that's it, thanks a lot :)

**Comment by napso** [comment]
@kuworking  can you specify an example how you went on doing this in the end ?

**Comment by kuworking** [comment]
> @kuworking can you specify an example how you went on doing this in the end ?

Sincerely, I have no clue of what I was asking back then (and sure I'm not using it now), it is almost 2 years 😓

Sorry

**Comment by dungle-scrubs** [comment]
I'm actually trying to figure out how to do what I thought the original question was, so I figured adding to this thread is the right place to ask.  I need to add an array of Shopify products to a site-wide header based on dynamic user-populated info from a CMS.

I can't figure out how to do it because the `graphql` helper isn't available outside of `createPages`.  The following would happen after all source plugins have run, which in my mind would make use of `sourceNodes`.

According to the docs, "If you define this hook in `gatsby-node.js` it will be called exactly once after all of your source plugins have finished creating nodes."

1. Source array of strings (Shopify product handles) from CMS
2. Create a new base-level node by running a GraphQL query on allShopifyProducts, filtering by product handle based on the new array of sourced handles.
3. Within the 'Header', run `useStaticQuery` to pull that new node of product objects.

I'm trying to get around the fact that I can't use variable in a `useStaticQuery` query and that the header is site-wide and not specific to any particular page.

Conceptually, and I have no idea how to do this, some way of relating to existing product nodes rather than duplicating them into a brand new node seems reasonable as well.

Thoughts?
