### ISSUE TITLE
To get `createContentDigest` do I need to be inside `sourceNodes`?

### ISSUE THREAD

**Issue by leworking** [gatsbyjs/gatsby#11772]
If I want to create a node outside the `createNode` hook, I (think I) can by extracting the function from `actions`, for example inside the `createPages` hook

```
export const createPages = ({ graphql, actions }) => {
  const { createPage, createNode } = actions
```

But then, I cannot get the helper `createContentDigest`, as I am not in the `sourceNodes` hook

```
exports.sourceNodes = ({ actions, createNodeId, createContentDigest }, configOptions) => {
```

Is that right?

**Comment by pieh** [comment]
This helper should be passed to every gatsby-node API (same with `createNodeId`). So you should have access to it in `createPages`.

That said creating nodes in `createPages` (or other, non `sourceNodes` / `onCreateNode` APIs) is dangerous, because we create graphql schema in 2 places right now:
 - after `sourceNodes`, so you can use `graphql` queries in `createPages` to grab data and create pages from that data.
 - after `createPages` (to update schema with `SitePage` type)

if you create nodes after those points, then it's possible that schema won't have types for your nodes (if those are new node types or if are of type that existed when creating schema, but have added more fields than those wouldn't show in schema)

**Comment by leworking** [comment]
Point taken, thanks :)
