### ISSUE TITLE
gatsby build failes: WebpackError: TypeError: Cannot read property 'item' of undefined

### ISSUE THREAD

**Issue by engmagdy87** [gatsbyjs/gatsby#11784]
## Description
Build process failed

### Steps to reproduce
I'm in **Home page**, when i click on image, i'll be redirected to **Details page** with state in `gatsby link`

**Home page** 
`<Link
                key={item.node.id}
                to="/details"
                state={{
                  item: item.node,
                }}
              >
                <ImgWrapper
                  fluid={item.node.frontmatter.cover.childImageSharp.fluid}
                />
              </Link>
`

**Details page**
`const Details = props => {
  const { location } = props
  const book = location.state.item
  return (
    <Layout pathname={location.pathname}>
      <MainWrapper>
        <DetailsWrapper>
                  ....
`

### Actual result

when run `gatsby build`, it fails on this line
`const book = location.state.item`
`WebpackError: TypeError: Cannot read property 'item' of undefined`

### Environment

System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
  Binaries:
    Yarn: 1.12.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.7.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.6.5 - C:\users\mm\appdata\local\programs\python\python36-32\python.EXE
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    gatsby: ^2.1.2 => 2.1.2
    gatsby-image: ^2.0.29 => 2.0.29
    gatsby-plugin-manifest: ^2.0.17 => 2.0.17
    gatsby-plugin-offline: ^2.0.23 => 2.0.23
    gatsby-plugin-react-helmet: ^3.0.6 => 3.0.6
    gatsby-plugin-sharp: ^2.0.20 => 2.0.20
    gatsby-plugin-sitemap: ^2.0.5 => 2.0.5
    gatsby-plugin-typography: ^2.2.7 => 2.2.7
    gatsby-source-filesystem: ^2.0.20 => 2.0.20
    gatsby-source-strapi: 0.0.5 => 0.0.5
    gatsby-transformer-remark: ^2.2.5 => 2.2.5
    gatsby-transformer-sharp: ^2.1.13 => 2.1.13

**Comment by pieh** [comment]
You won't have `location.state` in html builds, so to avoid errors during the build you would need to add check to see if it's truthy:

```
if (location.state) {
  const book = location.state.item

  // rest of your render
}

// fallback to null
return `null`
```

But there are also other issues with passing data like that through history/location state:

If you visit your Details page directly (without clicking link from home page or when using "open in new tab" option) it will also crash in browser.

So instead of passing `item` data through `<Link>` state, and creating single `/details` page - you probably need to create `details` pages for each book (https://www.gatsbyjs.org/docs/programmatically-create-pages-from-data/#programmatically-create-pages-from-data) with `/details/${book.id}` (or whatever url pattern you chose) and link to those pages from your home page

**Comment by engmagdy87** [comment]
thx @pieh
