### ISSUE TITLE
Refactor tracedSVG calls from transformer-sharp into plugin-sharp

### ISSUE THREAD

**Issue by oorestisime** [gatsbyjs/gatsby#11912]
## Description

Right now tracedSVG support is handled mostly in the transformer plugin rather than the plugin-sharp itself. https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-transformer-sharp/src/extend-node-type.js#L65

It would be better if plugin-sharp takes all the necessary configuration options and creates tracedSVG images when needed.

This would enable third-party plugins to add tracedSVG support without needing to take care of it on themselves

### A bit more context

A bit more context can be found here https://github.com/oorestisime/gatsby-remark-rehype-images/issues/2

## Problem

While the refactoring wouldn't be complicated or hard to do introduce a possible conflict. What happens when newest plugin-sharp is installed but transformer one is on the previous version?
Would the cache take it upon it hence not really create any issues?

**Comment by pieh** [comment]
We talked with @oorestisime on discord a bit about it before he created the issue.

One of potential problem that I initially didn't thought about with this:
SVG tracing is considerably more expensive than base64 placeholder generation. Right now we only do this if user specifically request `tracedSVG` field on `fixed`/`fluid` objects/transformations (either directly or through our fragments).

Checking if `traceSVG` arg actually changes behaviour - because user definitely can do:
```graphql
fluid(maxWidth: 800, traceSVG: { color: "#FF0000" }) {
  ... GatsbyImageSharpFluid
}
```
which doesn't contain `tracedSVG` field and currently wouldn't cause svg tracing - but would if we only checks for args.

But we could definitely provide convience utility that would not cause change for `gatsby-transformer-sharp` by having extra flag in args:

```js
const { fluid } = require(`gatsby-plugin-sharp`)
[...]
fluid({
  ...allUsualArgs,
  tracedSVG: {
    color: "#FF0000"
  },
  generateTracedSVG: true // if this is true and `tracedSVG` options are passed - then generate traced svg
})
```
?

**Comment by oorestisime** [comment]
Yeap sounds fair to me.
and actually pass those flags along from transformer as well?

**Comment by pieh** [comment]
I think transformer would need to stay as-is unless we have access to what subfields are requested at `fluid`/`fixed` resolver level (no idea if we do)
