### ISSUE TITLE
Docs: list available components when writing blog posts and docs

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#11946]
In https://github.com/gatsbyjs/gatsby/pull/11939#discussion_r258702209, I learned about a reusable `<pullquote>` component available when writing blog posts for gatsbyjs.org. Given there are probably others, it would be great to list these and show usage on a page in the contributing docs!

To figure out where this page will live, I could use some help from the core team to learn about what's available. Is `pullquote` only available for blog posts, or docs too? Are there other Gatsby site components that you've found useful?

**Comment by DSchau** [comment]
Great idea! Let me answer some of your questions:

> Is `pullquote` only available for blog posts, or docs too

Currently only blog posts, but we could make it available to general docs, as well. If you're curious, we're adding that functionality [like so](https://github.com/gatsbyjs/gatsby/blob/master/www/src/templates/template-blog-post.js#L23) in the blog post template. It would be a matter of adding similar functionality to other templates (e.g. docs).

> Are there other Gatsby site components that you've found useful?

We also have `chart` and `hubspot-form` components, but technically we can render other components as well. It's a _little_ janky, but it does work quite well and gives us the ability to render React components to the DOM.

Longer term, it'd be super cool to be able to have our docs be authored in mdx, so that we can import _any_ component that is available in our components directory. This would open up the door to some really slick things because we could then easily embed _any_ React component in our Markdown files.

**Comment by marcysutton** [comment]
@DSchau another component that I've seen in the codebase is `guidelist` (we talked about it in Slack yesterday). Do you know anything about that one? Is that blog-only too?

**Comment by DSchau** [comment]
@marcysutton not a problem!

We could actually probably replace that with an actual React component, but for now, it's just string replacement, e.g. `[[guidelist]]` is replaced by HTML content like so: https://github.com/gatsbyjs/gatsby/blob/master/www/src/templates/template-docs-markdown.js#L38-L56

(MDX would help us a lot here too! We'd just have a Guidelist component that we can use _wherever_)

**Comment by wardpeet** [comment]
@DSchau I think it's great if we move to mdx someday as it will be more implicit than replacing shortcodes.

**Comment by lannonbr** [comment]
Switching this to not stale as @johno and @ChristopherBiscardi are working on switching the .org site to mdx here: https://github.com/gatsbyjs/gatsby/pull/12514

**Comment by lannonbr** [comment]
And with the switch to MDX on the .org site, this issue should no longer be blocked

**Comment by muescha** [comment]
We should aDid some documentation of the TOC component (#15251) and the usage `disableTableOfContents`

**Comment by marcysutton** [comment]
Recommendation: add a new page called "Docs and Website Components" that lists available components and their API options. It could go under [Setting up your dev environment](https://www.gatsbyjs.org/contributing/setting-up-your-local-dev-environment/) in the contributing sidebar.

**Comment by muescha** [comment]
Maybe we can do this as a [storybook](https://storybook.js.org/) so it is easy to play with the components?

**Comment by muescha** [comment]
Is there any umbrella issue we can track this issue?

**Comment by gillkyle** [comment]
I'll take this on, one thing worth noting is that with adding dark mode and changing to Theme-UI, we can add some more of the notes in the `www` README to the Contributing docs as well so folks contributing can be aware how the design tokens are working.
