### ISSUE TITLE
[1.0] Client routing ignores index.html 

### ISSUE THREAD

**Issue by eddywashere** [gatsbyjs/gatsby#1197]
I built a site with 1.0 beta and noticed some external links to the site that included `index.html` were rendering a 404/page not found route. 

Steps to reproduce issue:

- navigate to root of site with index.html extension - https://www.gatsbyjs.org/index.html
- verify content exists: `curl https://www.gatsbyjs.org/index.html` (inspect built html)

**Comment by KyleAMathews** [comment]
This is deliberate as the `index.html` file only exists to emulate "clean" urls on the server because most web servers resolve `/a/path/` to `/a/path/index.html`. Once you're in the client, there's no concept of html files anymore so the client router has no reason to care that somewhere there's an html file that corresponds to a client route.

If you want `.html` routes to work in the client, [you need create pages with `.html`](https://www.gatsbyjs.org/docs/creating-and-modifying-pages/) in their pathname.
