### ISSUE TITLE
[docs] gatsby-image docs usage could note the example is a page query

### ISSUE THREAD

**Issue by lannonbr** [gatsbyjs/gatsby#11991]
## Summary

In the [code example](https://www.gatsbyjs.org/packages/gatsby-image/#how-to-use) for gatsby-image, it shows off a full example of loading in an image through a page query and then passing it to the `<Img>` component. That said, a thing that people could get caught up on is think that this pattern can be used anywhere which could cause some issues down the road if they try doing this in a plain react component if one hasn't grasped the difference between a page query and a static query.

There are two approaches I currently see that could be taken to make this easier to understand:

1) Explicitly saying this is a page query (and possibly link to Page query docs) and say it can only be done either on a page in `src/pages` or one dynamically made using gatsby-node APIs.
2) Switch the example over to a static query which can be used in any JS file.

**Comment by jonniebigodes** [comment]
@lannonbr if you don't mind my two cents. You have a point in there. i agree to with you but you can add a link [here](https://www.gatsbyjs.org/docs/static-query/#how-staticquery-differs-from-page-query) so that people can learn about the differences between a page query and a static query .

Also in your second bullet point mention that static queries don't accept parameters for now. And with that, don't lead people to think a "general" component can be created, supply some image name as a prop and expect it will work.

**Comment by lannonbr** [comment]
1) I think we just need to note explicitly that the query in the code example is a page query.

2) Yeah makes sense
