### ISSUE TITLE
Gatsby image sharp tracedSVG misalignment when cropped

### ISSUE THREAD

**Issue by baobabKoodaa** [gatsbyjs/gatsby#12008]
## Description

TracedSVG image placeholders are not aligned to the original image when cropped. It looks like this was reported already [here](https://github.com/gatsbyjs/gatsby/issues/9204) 4 months ago, but the original poster didn't provide a reproducible demo and the issue was closed. He/she explains the issue very well. I'm providing a demo.

### Steps to reproduce

Website that demos the problem: https://gatsby-bug-reports.netlify.com/misaligned-placeholder/

Source for the demo: https://github.com/baobabKoodaa/blog/tree/imageBugsDemo

### Expected result

Expected placeholder to be aligned.

### Actual result

Actually placeholder was not aligned.

**Comment by freiksenet** [comment]
Thank you for the report and great reproduction example! It seems to be a bug with transformer-sharp. Possibly the original file is used instead of cropped one to create a traced SVG. Do you want to try to create a PR to fix this?

**Comment by baobabKoodaa** [comment]
@freiksenet Could you help me understand where the transformation happens exactly?

This is the only relevant file I could find: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-transformer-sharp/src/extend-node-type.js

It's not documented or commented and I'm struggling to understand how it's supposed to work. To me it looks like this function in `transformer-sharp` calls `plugin-sharp` to do the transformation:

```
const getTracedSVG = async ({ file, image, fieldArgs }) =>
  traceSVG({
    file,
    args: { ...fieldArgs.traceSVG },
    fileArgs: fieldArgs,
  })
```
When we call `getTracedSVG` in `fluidNodeType` and `fixedNodeType`, we are passing the original non cropped image ("parent"):

```
tracedSVG: {
          type: GraphQLString,
          resolve: parent => getTracedSVG(parent),
}
```

So at this point I'm thinking: I need to modify that to be similar to the "blur-up" placeholder, which I believe is being cropped correctly. But then I look at the code and I can't see that happening anywhere either:

```
base64: { type: GraphQLString }
```

Both `traceSVG` and `base64` are just imported from `gatsby-plugin-sharp`. Where do we tell plugin-sharp "here is a cropped image, please generate a blur-up placeholder for it"?

**Comment by baobabKoodaa** [comment]
Some more information: if the original file was used to create the tracedSVG, then we should expect `cropFocus: NORTH` to align placeholders nicely. Surprisingly, it doesn't. The only cropFocus which works is `CENTER` for some reason. So clearly the tracedSVG placeholders are in fact being created from a cropped image, just something goes wrong which misaligns the cropping.

**Comment by freiksenet** [comment]
I read the code wrong first time - the resizing happens in traceSVG, so issue is inside it in `plugin-sharp`. Seems there are two problems, one is that maxHeight and maxWidth aren't used in `traceSVG`. I guess logic from fluid should be copied to traceSVG or somehow split out so it can be reused. Second is that there is an issue with the memoization of the tracedSVG. It memoizes by file name and args, while the crop is set in `fileArgs` parameters. Adding stringified `fileArgs` to memoize cache key will probably fix this.

**Comment by baobabKoodaa** [comment]
Thanks for the explanation. I will take another stab at this!

**Comment by baobabKoodaa** [comment]
@freiksenet I tried to look into plugin sharp, but unfortunately I can't understand how it works :( I think this has to be done with someone who is already familiar with that plugin.

**Comment by pridyok** [comment]
I have run into this issue as well and it renders the SVG trace functionality pretty much entirely useless when using cropped images in a responsive site. Is there a reason this was removed from the roadmap?

**Comment by dcastil** [comment]
I have the same issue, also on non-cropped images. The bug appeared in a PR while I was adding functionality which was not touching the parts of the website which broke. I can't share the PR itself unfortunately because it's in a private repo, but I hope I can still provide valuable information.

Here is a deploy preview from an article page where the traced SVG is cropped correctly, it is the last commit on master as of writing this comment: https://5dbf31e95b3c1a000838239c--nn-website.netlify.com/magazin/social-entrepreneurship-weltretten-mit-businessplan/

On a PR I'm working on at the moment, the bug from this issue appeared on the same page: https://deploy-preview-43--nn-website.netlify.com/magazin/social-entrepreneurship-weltretten-mit-businessplan/

Here is a screenshot of the page with the image loaded. The image has its original aspect ratio and was not cropped with GraphQL.

<img width="1440" alt="Screenshot 2019-11-09 at 23 56 41" src="https://user-images.githubusercontent.com/31006608/68536053-ee61b500-034c-11ea-86c7-5282feb3b8ff.png">

Here the same page with the traced SVG before the image is loaded. You can see that it is more zoomed in.

<img width="1440" alt="Screenshot 2019-11-09 at 23 56 46" src="https://user-images.githubusercontent.com/31006608/68536060-01748500-034d-11ea-9356-fdb6bbadf2c6.png">

After removing the CSS property `width: 100%` from the traced SVG image, it becomes visible that the traced SVG has an aspect ratio of 3:4 rather than the original 3:2.

<img width="1440" alt="Screenshot 2019-11-09 at 23 58 12" src="https://user-images.githubusercontent.com/31006608/68536096-a8f1b780-034d-11ea-97c2-3f52e2385ada.png">

In the PR I added an article collection which is visible at the bottom of the page. It includes previews of articles with the respective hero image cropped to a 3:4 format. Maybe Gatsby image retrieves a cached version of the traced SVG without taking image crop into consideration. So when the same image is used with different crop parameters, the same traced SVG is applied.

**Comment by dcastil** [comment]
I opened a PR to fix the bug here: https://github.com/gatsbyjs/gatsby/pull/19398. @freiksenet Maybe you can review it as you're already involved in the discussion here? 😊

**Comment by mashabow** [comment]
I found that there is the same issue in the [Using Gatsby Image demo page](https://using-gatsby-image.gatsbyjs.org/traced-svg/).

![Jul-16-2020 22-06-21](https://user-images.githubusercontent.com/6268183/87674190-a3881f00-c7b0-11ea-8afa-cb6b66fd8716.gif)

**Comment by LekoArts** [comment]
Closing this as stale since in the meantime Gatsby v3 and updated related packages (gatsby-plugin-image) were released. Please try with the latest versions and if you still see this problem open a new bug report (it must include a [minimal reproduction][reproduction]).

[reproduction]: https://gatsby.dev/reproduction

**Comment by raae** [comment]
I see this issue with latest "gatsby-plugin-image": "1.14.0",

**Comment by gridig** [comment]
This issue is still present in 1.14.0, with cropped and non-cropped image

![RPReplay-Final1633296336(2)](https://user-images.githubusercontent.com/44157921/135772334-600b005e-37b7-4bfb-9674-ffa5ff95a348.gif)
