### ISSUE TITLE
Add structured error for VALIDATION_ERROR action

### ISSUE THREAD

**Issue by stefanprobst** [gatsbyjs/gatsby#12050]
In the `createNode` action creator, when a node fails Joi validation, we dispatch a [VALIDATION_ERROR action](https://github.com/gatsbyjs/gatsby/blob/024f6f4629dc9634ce02887fe82708048f9158b4/packages/gatsby/src/redux/actions.js#L510), but we don't handle it anywhere at the moment.

We probably want to handle this and warn using `reporter.warn`

**Comment by stefanprobst** [comment]
Related: https://github.com/gatsbyjs/rfcs/pull/31

**Comment by samrae7** [comment]
Hi I would like to take this on

**Comment by samrae7** [comment]
Having said that I'd like to take this on I have noticed that since the issue was created, there is now some error handling added: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/redux/actions/public.js#L676 so I think this should possibly be closed. @stefanprobst what do you think?

In any case I am struggling to find a test case that covers this (failed validation) case. Am I right in thinking that a test for this code is missing here: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/redux/__tests__/nodes.js

I am new to the project so maybe I am missing something

**Comment by LekoArts** [comment]
This has been fixed in the meantime.
