### ISSUE TITLE
[gatsby-plugin-google-adsense] does not exist anymore?

### ISSUE THREAD

**Issue by saranshkataria** [gatsbyjs/gatsby#12187]
## Description

https://www.gatsbyjs.org/packages/gatsby-plugin-google-adsense/ is empty, https://github.com/callicoder/gatsby-plugin-google-adsense gives a 404

**Comment by sidharthachatterjee** [comment]
Looks like it is still on npm but the repository was taken down or made private by @callicoder?

**Comment by DSchau** [comment]
Looks to be the case. This isn't really an issue with Gatsby (this is an external plugin), but I'd love to hear more about what happened here.

@callicoder if you have a few minutes to spare, would love to know if taking down the repo was intentional! If so, perhaps @saranshkataria would be interested in taking over maintenance from you?

Going to close this out--but please feel free to chime in if we can discuss this further or help transition anything here!

Thanks!

**Comment by tonystaark** [comment]
Anyone able to get google Adsense on Gatsby?
