### ISSUE TITLE
gatsbyjs.org plugin search breaks with some values

### ISSUE THREAD

**Issue by alexanderjsx** [gatsbyjs/gatsby#12294]
## Description

Plugin search on www.gatsbyjs.org break page with some search phrases 

### Steps to reproduce

Just open this in a browser:
https://www.gatsbyjs.org/plugins/?=len
or
https://www.gatsbyjs.org/plugins/?=lenr
or
https://www.gatsbyjs.org/plugins/?=lern

### Expected result

0 to many search results should be visible.

### Actual result

Empty white page and error in console: `TypeError: Cannot read property 'toLocaleString' of undefined`

### Environment

Website. The same result on chrome and firefox (Kubuntu).

**Comment by DSchau** [comment]
Yikes.

Should be an easy fix! You've already gone through the work of identifying the issue--would you be interested in PRing the fix?

Looks like that toLocaleString call happens in react-instantsearch, so it could be a case of us passing props down or otherwise invoking one of those components incorrectly [here](https://github.com/gatsbyjs/gatsby/blob/master/www/src/components/plugin-searchbar-body.js#L233)
