### ISSUE TITLE
Create way to quickly test potential breaking changes on large numbers of "in the wild" Gatsby sites

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#12300]
There's occasional PRs that touch a lot of surface area and can break in subtle ways that it'd be good to have a way to test really throughly against real-life sites.

Like 1000s of sites.

We have two features that are largely done but we haven't released due (in part) to uncertainties around whether they 100% work — the loki.js replacement for sift.js for querying & the schema refactor so we need a way to ensure things will keep working the same way across the long-tail of sites.

This idea is throughly inspired by GitHub's Scientist library https://githubengineering.com/scientist/

Currently there's 49,477 repositories that depend on Gatsby (woah) https://github.com/gatsbyjs/gatsby/network/dependents

When starting a new experiment, the scientist [pause for meme break]

![I'm kind of a scientist meme](https://i.kym-cdn.com/entries/icons/mobile/000/025/351/afoeeee.jpg)

[resume]

would specify the PR (and optionally commit & env variables) and number of sites to test against.

Then the tool would pick a random subset of public Gatsby sites and run two builds — one using master and one using the selected PR.

The tool would measure various build-related metrics e.g. build time for each segment plus if the build succeeds and if not, what errors were hit.

The tool would also compute a hash for each generated file.

The tool would show the aggregated analytics for the run showing what % of sites were different in any way and how the build times / error rate compared between the control and test results.

The workflow would be:

1) put up a PR
2) test locally against our example/benchmark sites to verify most things are working
3) go to the tool [replace with cool tool name] and start an experiement
4) fix errors that arise (by cloning sites that show problems and creating fixes against them)
5) rinse and repeat until a large number of bulds are identical

Some design considerations:
- Probably it'd make the most sense to run this on Lambda as it has a default concurrency of 1000 which is a large enough to throughly test most sites
- We'd need to blacklist sites that are don't ever build — not very helpful
- We'd need to store state — dynamodb perhaps? Store logs in s3? Or GCP equivalent
- We'd need a frontend of some sort — running in a lambda and talking to the db
- We'd want to authenticate this — perhaps authenticate to GitHub and verify the person is a member of the gatsbyjs org? That should cover pretty much everyone that wants to use this tool — if someone isn't yet a member, we can add them easily enough.

**Comment by sidharthachatterjee** [comment]
Now that Lambda supports being run from SQS, we should be able to put a 1000 jobs in a queue, wait for them (and maybe let them retry once or twice) and then put the ones that didn't work in a dead letter queue. 

If DLQ is empty, we're good. If not, the ones that will break can be pulled out of it for stats

**Comment by KyleAMathews** [comment]
SQS would be great!

**Comment by sidharthachatterjee** [comment]
Just realised that we should just be able to run this on the urls in sites.yml since they are more likely to be working in general

**Comment by DSchau** [comment]
## Implementation Notes

- Create the job
- Goes into a queue
- Job gets processed
- Randomly selected sites (from showcase, and repos that have Gatsby as a dependency from Github)
- Maintain a blacklist of sites that consistently fail
- Create jobs for each of the jobs that we will run
- Set up Verdaccio for the PRs, so that we can update dependencies and install them for the sites
- Two builds: one from Verdaccio, one from master
- May update the packages to the latest in the sites
- Filter by 2.x versions of Gatsby (or some range of semver)
- Lambda should probably be used (1000 concurrent function instances)
- Should be relatively cheap even at scale
- Push results to DynamoDB
- Can use Google Cloud too, if we want
- Once job is finished, report back data/metadata/etc.
- Dashboard/tool shows the latest results, querying, filtering, sorting, etc.
- Requires a login for starting the test

**Comment by wardpeet** [comment]
In the lighthouse project there is a project called DZL which also runs lighthouse on a number of sites. It was created by the awesome @patrickhulce. The output looks like this: http://lh-dzl-6730.surge.sh/

Script that pulls down the PR and does a lighthouse run
https://github.com/patrickhulce/dzl-lighthouse/blob/97f845a45e5460d51c32e81fc16ae07837aa7f04/ansible/files/scripts/agent-run-branch.sh
The html of the files can be found https://github.com/patrickhulce/dzl-lighthouse/tree/11b057424fe7a43ba5f324e08ede1f8f8475f74a/cli/lib/www

DZL is running on GCP because google cloud functions were having a lot of variances so we should measure the same PR a few times just to make sure our infra isn't wonky.

**Comment by patrickhulce** [comment]
Hey there awesome ideas floating around!

As @wardpeet mentioned, I put together something like this for lighthouse and ran into a number of issues ([best summarized in this comment if you're interested](https://github.com/GoogleChrome/lighthouse/issues/6775#issuecomment-454261826)).

My biggest advice would be to start with breaking changes only and table performance issues for now. Cloud infra, *especially* lambda-style functions, has a lot of variability that requires very large sample sizes to get statistically significant data when it comes to performance. 

My two 💰: focus on the error rates/content changes and have a way of easily re-running sites that differ before resorting to a local investigation

**Comment by polarathene** [comment]
Not sure if this is relevant as an alternative for Lamda, but would a CI service like [semaphore](https://semaphoreci.com/pricing) make sense? 

Looks like they can exceed the concurrent lamda jobs jobs mentioned(no idea how well that works in practice), (auto)scaling to such demands seems to be a focus of this CI provider, they're also working towards an open-source tier(there's an existing 1,300 minutes per month free tier), so getting in touch with the provider, they're likely more than happy to assist gatsby with their service?

As shown on their [product page](https://semaphoreci.com/product), they support features like dashboards with custom metrics, I haven't got around to trying this vendor out yet, so I'm not sure if it'll meet your needs but I think they could be worth looking into for the requirements here?

**Comment by KyleAMathews** [comment]
@pieh did a basic test of this on his own machine. Next step is to try building a setup for a kubernetes cluster. Next step after that is to "productize" this a bit where we can run tests on demand for PRs.

**Comment by m-allanson** [comment]
WIP for this is at https://github.com/pieh/develop-runner

**Comment by LekoArts** [comment]
We have a similar solution to this problem internally now.
