### ISSUE TITLE
Navigation is not responding while assets are loading

### ISSUE THREAD

**Issue by CodeVersusMan** [gatsbyjs/gatsby#12377]
## Description

When you try to navigate across the site after an initial load, links do not change routes until all assets have finished loading.

I am aware that the image sizes are huge (1 - 1.5 MB), we are currently optimizing them, but isn't asset loading supposed to be cancelable by navigation? 

### Steps to reproduce

Visit this link: https://www.domonap.ru/domonap-app/tech/

Try to visit another page as soon as possible, click multiple links in a rapid succession.

### Expected result

Links should switch the route immediately, without being dependant on assets.

### Actual result

Routes wont change until all assets have loaded

**Comment by DSchau** [comment]
Generally - waiting for assets is a behavior you want. We wouldn't be waiting for _all_ images, just the necessary resources to load the _next_ page.

However, in your case, it looks like the main page is blocking the loading of the next page because resources are imported as images (e.g. .png files loaded off of disk).

For example, [this image](https://www.domonap.ru/static/main-domonap-bg-23f4e80b1df7299e3a658571b6a5325e.png) is blocking the main route.

There are a number of ways you could avoid this--first and foremost would be to investigate using [gatsby-image](https://www.gatsbyjs.org/packages/gatsby-image/) which would let you load your images via GraphQL, so you would load a tiny, optimized Base64 image and then lazily load the larger, full image in the background when the page is accessed.

More general advice would be to consider tweaking whether images are necessary for the assets you're loading. Something like a repeating SVG pattern (for the white, clear images) and then a CSS gradient background would seem to deliver the same effect, but in a much, much more performant manner.

I would encourage you to revisit how you're loading images--as you note--but in the interim, if you want to opt-out of waiting for the next resource, I believe something like the below should work--but note haven't tested this at all!

```
import React from 'react'
import { Link } from 'gatsby'
import { navigate, withPrefix } from '@reach/router'

// this should be invoked immediately by Gatsby Link
// which would short-circuit the prefetching
function CancelableLink({ to, ...props }) {
  return (
    <Link onClick={() => navigate(withPrefix(to))}{...props} />
  )
}

export default CancelableLink
```

I'm going to close this as answered, but happy to continue the discussion if you'd like!

Thanks for using Gatsby! 💜
