### ISSUE TITLE
onPreRouteUpdate appears to execute after route change

### ISSUE THREAD

**Issue by cwgw** [gatsbyjs/gatsby#12426]
## Description

The browser api method `onPreRouteUpdate` seems to be executed after my components are rendered.

### Steps to reproduce

Log some message in `onPreRouteUpdate`

```
// gatsby-browser.js
export const onPreRouteUpdate = () => {
  console.log('onPreRouteUpdate')
}
```

Log some message in `Layout` or another component

```
// layout.js
const Layout = ({ children }) => {
  console.log('rendering component');
  ...
```

### Expected result

`onPreRouteUpdate` and `rendering component` should be logged to the console in that order on every route change.

### Actual result

The initial client render goes fine, but after a route change or two the console ends up looking like this:

```
[HMR] connected
onPreRouteUpdate
rendering component
rendering component
onPreRouteUpdate
rendering component
onPreRouteUpdate
...
```

`onPreRouteUpdate` is being logged *after* `rendering component`. This is not the intended behavior, right?

### Environment

  System:
    OS: macOS 10.14.3
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  Browsers:
    Chrome: 72.0.3626.121
    Firefox: 65.0.1
    Safari: 12.0.3
  npmPackages:
    gatsby: ^2.1.27 => 2.1.27 
    gatsby-image: ^2.0.31 => 2.0.31 
    gatsby-plugin-manifest: ^2.0.22 => 2.0.22 
    gatsby-plugin-offline: ^2.0.24 => 2.0.24 
    gatsby-plugin-react-helmet: ^3.0.8 => 3.0.8 
    gatsby-plugin-sharp: ^2.0.25 => 2.0.25 
    gatsby-source-filesystem: ^2.0.23 => 2.0.23 
    gatsby-transformer-sharp: ^2.1.15 => 2.1.15 
  npmGlobalPackages:
    gatsby-cli: 2.4.14
    gatsby-dev-cli: 2.4.10

**Comment by sidharthachatterjee** [comment]
Hey @cwgw 

`onPreRouteUpdate` is called once after init and then before an impending route update (if pathname changes)

In your above example, is the `Layout` component wrapping the root element using `wrapPageElement`? If yes, that will be not get unmounted on route change since it will sit above the router in the tree. 

That's probably why you're seeing it render before the `onPreRouteUpdate`.

**Comment by pieh** [comment]
The `onPreRouteUpdate` should be called before changes are committed to the DOM by react (we are using [`getSnapshotBeforeUpdate`](https://reactjs.org/docs/react-component.html#getsnapshotbeforeupdate) lifecycle method of react).

This means that actual React `render` method will be called already, but the DOM didn't change yet. Instead of checking if render was called, please check if DOM has been updated.

This can be done with adding `data-domMarker={location.pathname}` to some element, and then examining value of that:

```
const el = document.querySelector(`[data-domMarker]`)
if (el) {
  console.log('onPreRouteUpdate', el.data.domMarker)
}
```

**Comment by cwgw** [comment]
Okay, Thanks for the explanation.

I saw that `onPreRouteUpdate` was being called from `getSnapshotBeforeUpdate`, but I did not get the order of execution. I should read the docs more carefully.
