### ISSUE TITLE
Using Gatsby together with Netlify Large Media

### ISSUE THREAD

**Issue by ludwigbacklund** [gatsbyjs/gatsby#12438]
## Summary

(This might not be the right forum for this but I'm not sure where the problem lies)

I'm trying to get Gatsby working together with Netlify deployment, Netlify CMS and Netlify Large Media. The reason for this using Netlify Large Media is to not bloat my git repository with large images. When Netlify is deploying my app it first tries to build it but fails with a: 

```
8:39:31 PM: error Failed to process image /opt/build/repo/static/images/009-an9qq9c.jpg
8:39:31 PM: 
8:39:31 PM:   Error: Input file contains unsupported image format
```

because Gatsby can't do anything with the file pointers that Git LFS (which Netlify Large Media is built upon) put in my repo. My guess for how this is supposed to work out is Netlify should pull the actual images to let Gatsby use them when building, but it doesn't (it even says in the Netlify deployment log that is uses `GIT_LFS_SKIP_SMUDGE=1` which skips downloading the images on git pull). 

I'm very lost in who to ask for help with this so any relevant information is very appreciated.

### Environment (if relevant)
```
  System:
    OS: macOS 10.14
    CPU: (8) x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 11.7.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.5.0 - /usr/local/bin/npm
  Languages:
    Python: 3.7.0 - /Users/dash/.pyenv/shims/python
  Browsers:
    Chrome: 72.0.3626.121
    Firefox: 59.0.1
    Safari: 12.0
  npmPackages:
    gatsby: ^2.1.19 => 2.1.19
    gatsby-image: ^2.0.29 => 2.0.29
    gatsby-plugin-manifest: ^2.0.17 => 2.0.17
    gatsby-plugin-netlify: ^2.0.11 => 2.0.11
    gatsby-plugin-netlify-cms: ^3.0.12 => 3.0.12
    gatsby-plugin-netlify-cms-paths: ^1.2.1 => 1.2.1
    gatsby-plugin-offline: ^2.0.22 => 2.0.22
    gatsby-plugin-react-helmet: ^3.0.6 => 3.0.6
    gatsby-plugin-react-svg: ^2.0.0 => 2.0.0
    gatsby-plugin-sharp: ^2.0.20 => 2.0.20
    gatsby-plugin-styled-components: ^3.0.5 => 3.0.5
    gatsby-remark-copy-linked-files: ^2.0.9 => 2.0.9
    gatsby-remark-images: ^3.0.3 => 3.0.3
    gatsby-remark-relative-images: ^0.2.1 => 0.2.1
    gatsby-source-filesystem: ^2.0.20 => 2.0.20
    gatsby-transformer-remark: ^2.2.3 => 2.2.3
    gatsby-transformer-sharp: ^2.1.13 => 2.1.13
```

**Comment by abstracthat** [comment]
I was about to try the same thing. I don’t think this setup will work with the Sharp transforms as that works with local files.

I think the proper setup for this is to build the props that gatsby-image takes yourself (instead of relying on the GraphQL snippet). You should be able to replicate the srcset, etc by appending a query string that Netlify transforms can work with.

I think the main downside is you lose the base64 blur up. But your build should be dramatically faster.

**Comment by ludwigbacklund** [comment]
@abstracthat Ah, yeah that does make sense. But isn't Git LFS meant to be used to replace the file pointers with the actual images when pulling the repository (like it does locally)? I feel like it kind of defeats the point of using it at all within Netlify Large Media if the Netlify build bot doesn't use it like its supposed to. One of the main reasons I was trying Netlify Large Media is because I wanted to retain the local image manipulation stuff with sharp.

**Comment by abstracthat** [comment]
This will be my first foray into LTS but you are right it does seem like it should have access. Your local build works right? I wonder if it would work if you set that smudge environment variable.

**Comment by abstracthat** [comment]
If you get this working I’m curious to know the build time difference.

**Comment by badiuoanaalexandra** [comment]
I just tried the same thing and unfortunately encountered the same error... at least so far I couldn't get gatsby to work with netlify large media :(

**Comment by ludwigbacklund** [comment]
@abstracthat I tried setting that env variable myself but it says that it conflicts with Large Media so I'm not allowed.

**Comment by sidharthachatterjee** [comment]
Just did some reading up on the documentation at https://www.netlify.com/docs/large-media/

It looks like this won't work. 😞 Ideally setting `GIT_LFS_SKIP_SMUDGE=0` should've done the trick but like you mentioned, it is being overridden (and is the whole point of Large Media if I understand correctly)

One option is to create a gatsby source plugin that "follows" the pointers to the images, downloads them and runs `sharp` but I'd argue that defeats the whole purpose of Large Media. 

Maybe use the transformations at https://www.netlify.com/docs/image-transformation/ and disable `sharp`?

**Comment by ludwigbacklund** [comment]
@sidharthachatterjee 
> (and is the whole point of Large Media if I understand correctly)

I'm not so sure about that. Isn't the point of Git LFS to act as a transparent middleman between the end-user (be it me working locally, or the Netlify build bot) by replacing those file pointers in my repo with the actual images during `git pull`? If that is not the case, how is Netlify supposed to deploy my application without the images that comes with it? If Netlify just has access to those file pointers and not the images themselves then it couldn't possibly serve them either.

**Comment by pieh** [comment]
This is partly question to Netlify - if users should be allowed to instruct netlify build bot to actually download images. I tried doing this manually with `git lfs pull` as part of build command but seems like this cause build errors on netlify.

If Netlify doesn't want to allow to pull lfs files in their build container then only way would be to create alternative version of plugins (gatsby-transformer-sharp / gatsby-remark-images) that instead of calling `sharp` would use Netlify [image processing](https://www.netlify.com/docs/image-transformation/), but not sure how exactly could that work if those images that use LFS would not be places in `public` directory.

**Comment by polarathene** [comment]
I've not actually got around to using Git LFS with Netlify yet, and haven't heard of Netlify Large Media until now(I guess it just came out recently?).

I looked into doing this earlier in the year with just Git LFS and Github. Netlify has(or had) support for such, but there was something required ENV var wise that wasn't documented(and only discussed in one github issue in a Netlify repo). If that still works, then you could go that route instead presumably?

The way it should work, is you'll have stored in git the pointers to the files, and upon a pull, you'd have those replaced by images pulled from the LFS store/server(which I assume Netlify Large Media is, once I read up about it).

> if users should be allowed to instruct netlify build bot to actually download images

You can definitely remotely download images during a build, I've done it before sourcing images from Unsplash, rather than storing them in the repo.

**Comment by fool** [comment]
Hi folks!  I work at Netlify and while I didn't create this feature I do know the answer here:  large media images are ONLY available at serve time, not build time.  Even fetching them with a `git lfs pull` will be super challenging since we drop git access permissions before you can run that command as part of your build pipeline.  There are no plans at this time to provide those assets for use during build.

In [our helpdesk](https://www.netlify.com/support) We can potentially talk you through providing a separate Deploy Key for that repo so you can pull from there, but it will require some manual configuration at your repos to set that up after we've created a Deploy Key for you.

**Comment by sidharthachatterjee** [comment]
Thank you for the response, @fool 

> There are no plans at this time to provide those assets for use during build.

Closing this issue for now since it can't be explicitly handled by Gatsby if not available at build time

**Comment by janosh** [comment]
> There are no plans at this time to provide those assets for use during build.

Ah, that's too bad. It would certainly be a great feature to pull in large files at build time!

**Comment by muescha** [comment]
As I understand would be here instead of pulling an processing the image on build time and then create the different sourcemaps with the processed result:

Skip the first Step and then generate image Sourcemaps which fits the netlify image processing on netlify like this`/images/apples.jpg?nf_resize=fit&w=300&h=400`
Processing and caching is then on the netlify side

Maybe an plugin also trigger all the possible image formats once so that they created
