### ISSUE TITLE
Strange bug with deletePage and createPage 

### ISSUE THREAD

**Issue by secondary-school55** [gatsbyjs/gatsby#12480]
## Description

After modifing placeholder file in /src/data/ index page is removed and server returns 404

### Steps to reproduce

[Repository with code](https://github.com/secondary-school55/bug-with-pages)

### Expected result

Index page must not be deleted.

### Actual result

After hot reloading index page is removed and server returns 404

### Environment

  System:
    OS: Windows 7
    CPU: (2) ia32 AMD Athlon(tm) II X2 240 Processor
 Binaries:
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    gatsby: ^2.1.28 => 2.1.28 
    gatsby-source-filesystem: ^2.0.23 => 2.0.23

**Comment by pieh** [comment]
I defenitely can reproduce. Investigating right now

**Comment by pieh** [comment]
Ok, so here are my findings:

this deletes pages:
https://github.com/gatsbyjs/gatsby/blob/26580a0b85327c97108a62b5b1119a8fe69408bf/packages/gatsby/src/bootstrap/page-hot-reloader.js#L61-L71

because when you re-create page in `onCreatePage` hook, page is taken over from `gatsby-plugin-page-creator` (which is stateful plugin) by yours `gatsby-node` which is not stateful.

I think we would need to adjust
https://github.com/gatsbyjs/gatsby/blob/26580a0b85327c97108a62b5b1119a8fe69408bf/packages/gatsby/src/redux/reducers/pages.js#L18-L20

so page doesn't change `pluginCreator` (if it's already set)

**Comment by secondary-school55** [comment]
gatsby-mdx not working correctly after hot reloading too. So hmr only working correctly with pages that was created programmatically and they are not stateful.

**Comment by secondary-school55** [comment]
Bug is fixed with #12671
