### ISSUE TITLE
(www) "Starters" and "Showcase" sidebar accordions "disappear" when collapsing

### ISSUE THREAD

**Issue by fk** [gatsbyjs/gatsby#12517]
* visit https://www.gatsbyjs.org/starters/?v=2
* click "Categories" or "Gatsby Dependencies" in the filter sidebar
* see the filters "disappear" instead of collapse
* markup is still there: 
![image](https://user-images.githubusercontent.com/21834/54207963-68e6e600-44db-11e9-9843-d469d5f0f486.png)

**Comment by amad-person** [comment]
A possible fix for this bug is to add the `fixed` prop to the `<LHSFilter>` components for "Categories" and "Gatsby Dependencies" in `www/src/views/starter-library/filtered-starters.js`.

The reason the "Gatsby Version" accordion doesn't exhibit this behaviour is because its `<LHSFilter>` has the prop `fixed={150}`. On removing it, it disappears instead of collapsing too. 

P.S. I can open a PR for fixing this bug!

**Comment by fk** [comment]
Hey @amad-person! 👋 

> I can open a PR for fixing this bug!

That'd be great! 🙏

**Comment by jgalat** [comment]
Hi @fk! I've made some research and found that the `overflow-y` in the component property was causing the issue when collapsed (still don't know how haha). 
I'm making a PR with the change (#13673).
Can you please review it? Thanks!

**Comment by fk** [comment]
Thank you (again ;-)) @jgalat! <3 🙏
