### ISSUE TITLE
Window scroll listener causes scroll stuttering in Chrome

### ISSUE THREAD

**Issue by atomiks** [gatsbyjs/gatsby#12520]
## Description

In Chrome DevTools using the FPS meter, the scroll listener that Gatsby seems to add causes poor scrolling performance. I noticed this on my website and on React's website. I don't add a scroll listener anywhere so I guess it's coming from Gatsby.

### Steps to reproduce

1. Visit https://atomiks.github.io/tippyjs/
2. Open FPS Meter in Chrome DevTools
3. For me it's showing ~45 - 55 FPs with lots of frame drops and stuttering
4. Type this into the console

```js
getEventListeners(window).scroll.forEach(({ listener }) => {
  window.removeEventListener('scroll', listener)
})
```

5. Much improved scrolling, way less frame drops once the listener has been removed.

---

Before: https://gyazo.com/57edc6fb31e1e06725f7e31c3b2a51a0
After: https://gyazo.com/3b4070170309a1c0037272a3cb3d3d17

**Comment by pieh** [comment]
The `scroll` event listener is added by `scroll-behavior` package that gatsby uses internally. I'll create issue there about and reference this one.

**Comment by scottyeck** [comment]
Is there any interest in re-opening this issue? We're experiencing similar behavior. I'm commenting here in particular (rather than the cross-referenced issue) as this behavior is affecting a `develop` instance moreso than a `build` instance whenever scroll-events are attached the `window`.

As there seems to be little appetite on the part of `scroll-behavior` to resolve this issue - there's a PR that makes use of `debounce()` to modify performance - we could easily do so within `gatsby-react-router-scroll`. Some preliminary investigation tells me that just wrapping the `getCurrentLocation()` call in a `throttle()` helps substantially. Any interest there? I'd be happy to put together a branch that takes care of this as well as a before / after audit. It'd help us tremendously as we attempt to attach some animations to scroll events.

**Comment by sebpettersson** [comment]
@scottyeck I'd love to see a work around / fix for this. 

It's just sad when you spend a lot of time optimising to hit 60 fps and then `scroll-behavior` comes and ruins the day.

**Comment by bradley** [comment]
This seems to still be an issue.

**Comment by lindaoc79** [comment]
I am also experiencing this issue - scroll lag and general lag in elements moving from inactive to clickable, active state.
