### ISSUE TITLE
2 sites using the same acf field type which is "image-array" for the image field, graphql query is not consistent between url and source_url

### ISSUE THREAD

**Issue by jerus1403** [gatsbyjs/gatsby#12527]
So I have 2 sites using 2 different wordpress CMS. However, they have the same type of acf field for image which is "image array", but in the graphQL, one site requires sub-field "url" and the other one requires sub-field "source_url". Anyone has any idea how the graphql query sub-field is not consistent between the 2 sites?

**Comment by pieh** [comment]
Are those using same versions of Wordpress and ACF plugin? Can you share urls to those 2 wordpress instances so we could reproduce this and find out why this is happening?

**Comment by jerus1403** [comment]
Hi Pieh,
Thank you for your quick response. So both of the 2 sites is a part of a multisite project that we are working for a client. Is there any way that we can message the urls in private because it's a part of the privacy policy. My apologies for the inconvenience.

**Comment by pieh** [comment]
Sure, You can DM me privately via Twitter - https://twitter.com/mipiechowiak

**Comment by jerus1403** [comment]
I just messaged you on twitter. Thank you for helping me with this

**Comment by robinmetral** [comment]
Same question here, did you ever find out why @jerus1403?

**Comment by pieh** [comment]
Problem in this case was that referenced image was not in `/wp-json/wp/v2/media` wordpress REST endpoint response in one of the sites (one that had `url` instead of `source_url`), so it didn't convert field to Media object (so it wouldn't allow to run image processing)

While we can't fix that in gatsby as this is something on wordpress side, we should be able to show some meaningful warning in cases like that (especially for ACF image fields using Image Object format)

**Comment by robinmetral** [comment]
Thanks @pieh! I had a similar case where `url` showed up for a misconfigured WordPress. So a working endpoint should expose `source_url` :slightly_smiling_face:

**Comment by jerus1403** [comment]
@robinmetral it was the way we imported the images. So now we have to do it manually to ensure all the images are imported to the same place.
