### ISSUE TITLE
Conditionally setPostBodyComponents using pathname... what does pathname look like?

### ISSUE THREAD

**Issue by danboyle8637** [gatsbyjs/gatsby#12579]
I use setPostBodyComponents to create my Facebook Messenger div... but I don't want to show it on every single page... 

I have code like... 

```
if (
    pathname !== '/' ||
    pathname !== '/privacy' ||
    pathname !== '/disclaimer'
  ) {
    setPostBodyComponents([
      <div
        key={'fb-messenger-div'}
        dangerouslySetInnerHTML={{ __html: facebookMessenger }}
      />,
    ])
  }
```

On my last deploy this doesn't seem to work. The Messenger chicklet gets rendered on all pages.

What does pathname look like? 

I tried console logging but in production it doesn't log the pathname out.

Can I do what I'm tryning?

**Comment by pieh** [comment]
You can check `.cache/pages.json` - this will be array of objects and `path` field in those objects is your `pathname`

But in here there is different issue - your condition should use `&&` (not `||`)

because `pathname !== '/' || pathname !== '/privacy' will always be true (no matter what pathname is used one of those will be always true)

**Comment by danboyle8637** [comment]
@pieh Thanks! Yes... right... Always messing up my conditionals. Thanks for the help!

**Comment by sidharthachatterjee** [comment]
Closing this as it seems answered but please feel free to comment or reopen if there's anything else related to this that we can help you with
