### ISSUE TITLE
[examples]: Add "using-i18n" example

### ISSUE THREAD

**Issue by LekoArts** [gatsbyjs/gatsby#12713]
Since more and more people show interest in "How to use i18n with Gatsby" a first step can & should be adding a `using-i18n` example. There are various third-party libaries like [react-i18next](https://react.i18next.com/) or [lingui](https://github.com/lingui/js-lingui) and also already multiple gatsby-plugins like:
- https://github.com/angeloocana/gatsby-plugin-i18n
- https://github.com/ikhudo/gatsby-i18n-plugin
- https://github.com/ikhudo/gatsby-i18n-plugin

In my opinion we should show an example that uses none of these third-party libaries and also no gatsby-plugins because it can all be done with Gatsby's APIs and React itself. Also I think it's nice to show how things work and not hide something behind a plugin.

I have a working example (with a CMS) here: https://github.com/LekoArts/gatsby-starter-prismic-i18n

However, the example should use `gatsby-mdx` and for that one decision is still open: What strategy to use for the blogposts?

- Individual folders, so e.g.: `content/en/topic-1/index.mdx` and `content/de/topic-1/index.mdx`
- Same folders but different filenames, so e.g. `content/topic-1/index.en.mdx` and `content/topic-1/index.de.mdx`

----

Please let me know your thoughts about this `using-i18n` example

**Comment by lannonbr** [comment]
I like the idea of having it without using any 3rd party plugin so rather than abstracting things away, you can focus in on the key architecture of doing internationalization.

With the blogpost strategy, I'm thinking the 2nd option is going to be cleaner in the long run so if you want to create a blog post and then have other people translate it, you can just tell them to duplicate the file in the folder it currently exists and then have them rename the file and translate the text
