### ISSUE TITLE
Phantom of the gatsby-dev

### ISSUE THREAD

**Issue by moonmeister** [gatsbyjs/gatsby#12751]
## Description

My sanity is at stake here ya'll, so please help. Basically `gatsby-dev` just seems not to work...but it's also working perfectly. 🤯

I'm trying to make changes to the `gatsby-cli`, so I've done my edits in `gatsby` and `gatsby-cli` packages, and I've got `yarn run watch --scope={gatsby,gatsby-cli}` running happily. 

In my test Gatsby site (created from `gatsby new` with no changes) i run `gatsby-dev --packages gatsby-cli gatsby` This copies lots of stuff. If I save changes to `gatsby` or the `gatsby-cli` packages I see it copy those changes across. :+1: 

If I run `./node_modules/gatsby/dist/bin/gatsby.js` I get the CLI with all my changes. YAY!!!...except it throws an error. Missing package (in this case `enquirer`). I've added this new package as a dependency but gatsby-dev hasn't helped me here. NO BIG DEAL!? I should be to `npm install enquirer` and go on my merry way. NOPE. My new CLI command is gone. 

Restart `yarn run watch` and `gatsby-dev`? NOPE. Randomly save files I've edited to trigger the copy to happen? NOPE.

BUT!!!! If I open `./node_modules/gatsby/dist/bin/gatsby.js` It's a red hearing (as expected) and just runs `/node_modules/gatsby-cli/lib/create-cli.js`...so inspecting `create-cli.js` shows that it is in fact updated. All my code changes are there in the code. :eyes: My new CLI command is there. gatsby-dev is in-fact doing it's job. :+1: But some how running `./node_modules/gatsby/dist/bin/gatsby.js` still doesn't see the code changes...it's just the standard CLI.

My only explanation is that because `gatsby.js` is requiring `gatsby-cli` it's some how using a different instance of `gatsby-cli` then it's peer in the local `./node-modules` folder. I've uninstalled my global copies of `gatsby-cli` to no avail. I've straight up deleted the local copy of `create-cli.js` and this thing keeps working...so something is wrong.

### Environment
  System:
    OS: Linux 4.18 Ubuntu 18.10 (Cosmic Cuttlefish)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Shell: 4.4.19 - /bin/bash
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.15+ - /usr/bin/python
  Browsers:
    Chrome: 73.0.3683.75
    Firefox: 65.0.1
  npmPackages:
    gatsby: ^2.2.5 => 2.2.5 
    gatsby-image: ^2.0.34 => 2.0.34 
    gatsby-plugin-manifest: ^2.0.24 => 2.0.24 
    gatsby-plugin-offline: ^2.0.25 => 2.0.25 
    gatsby-plugin-react-helmet: ^3.0.10 => 3.0.10 
    gatsby-plugin-sharp: ^2.0.30 => 2.0.30 
    gatsby-source-filesystem: ^2.0.27 => 2.0.27 
    gatsby-transformer-sharp: ^2.1.17 => 2.1.17 
  npmGlobalPackages:
    gatsby-dev-cli: 2.4.8

PLEASE SEND HELP! :pray: lol...I've been dramatic...I'm really not mad though...I've just been troubleshooting for 4 hrs on this :face_with_head_bandage:. Thanks for the assistance!

**Comment by moonmeister** [comment]
FYI: the gatsby info output above is from the test repo.

**Comment by DSchau** [comment]
Yup, there are (minimally) at least one or two gotchas with gatsby-dev-cli that you've uncovered. We're working on them :)

>  YAY!!!...except it throws an error. Missing package (in this case enquirer)

Note here (and we should document this), upgrade any packages you're using _locally_ to the latest releases before running gatsby-dev-cli. What's happening is that your version was a little older, we've added dependencies, and those dependencies aren't available in `node_modules`.

> NOPE. My new CLI command is gone

Yep - you need to re-run `gatsby-dev` after making changes to node_modules (the files that were copied are replaced, and because zero changes occurred in packages/gatsby, no changes are copied over). This would be technically sorta weird to implement on our end, so just restarting the process seems to work OK here!

> My only explanation is that because gatsby.js is requiring gatsby-cli

Testing gatsby-cli is a little challenging. It's hard to directly answer what's going on here--because I don't have any detail into what you're changing! My approach has usually been to use `gatsby-dev` and then point my `gatsby-cli` command in my scripts to use the local version, e.g.

```json
{
  "scripts": {
    "build": "./node_modules/gatsby-dev-cli/lib/index.js build"
  }
}
```

This is slightly different than your use-case though, correct?

Finally - thanks for pointing out these pain points. We're aware of most of them, and @pieh is working on a slick PR to improve this experience in #11525

**Comment by pieh** [comment]
for cli changes - instead of running global `gatsby-(dev-)cli` - I use these aliases:
```
alias gatsby-dev-l="/Users/misiek/dev/gatsby/packages/gatsby-dev-cli/dist/index.js"
alias gatsby-l="/Users/misiek/dev/gatsby/packages/gatsby-cli/lib/index.js"
```
(not ideal naming, but they do the work)

and if your changes are just in cli packages - you don't even need `gatsby-dev` (so this helps with any dependency changes there).

**Comment by moonmeister** [comment]
@pieh @DSchau Thanks gents. It sounds like some of this is expected but that I should try using local gatsby-dev-cli and not a global copy and go from there. Thanks for the hints on the aliases (I've tried similar things but not these exact ones). I'll let ya'll know how it goes!

FYI:  I'm trying to work on #10294

**Comment by moonmeister** [comment]
Okay, actually got work done on this thanks gentlemen! Ya'll are the best.
