### ISSUE TITLE
[themes] component shadowing has unexpected behavior with parent themes

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/gatsby#12813]
I just hit some weird behavior with component shadowing that I _think_ is a bug.

Here's what I'm doing:

1. I have a parent theme
2. I have a child theme that shadows a parent component
3. i have a site that needs to shadow a parent component

My goal was to allow shadowing in the child theme by defining the shadowed component in `src/components` in the child theme, then exporting it from `src/gatsby-theme-a/components/foo.js`:

```jsx
import Foo from '../../components/foo';

export default Foo;
```

My expectation is that the file at `gatsby-theme-b/src/components/foo.js` is shadowable, and that this shadowed component would be picked up by `gatsby-theme-a` in the import/export dance.

This doesn't work as expected, though. Somehow, the import/export dance seems to break shadowing for that component.

I put together a minimal repro showing what's going on. `gatsby-theme-a` is the parent, `gatsby-theme-b` is the child.

https://github.com/jlengstorf/component-shadowing-weirdness

Am I doing something wrong, or is this actually a bug?

**Comment by ChristopherBiscardi** [comment]
It's a bug in the parent-shadow-import.

If
the `issuer`: `theme-b/src/gatsby-theme-a/components/foo.js`
and the required path: `theme-b/src/components/foo.js`
end with the [same suffix](https://github.com/gatsbyjs/gatsby/blob/03b766210aec74d804fcd528899bb3f13f33d490/packages/gatsby/src/internal-plugins/webpack-theme-component-shadowing/index.js#L54) that is the universal component path (that is, the path at which this component would sit in any theme or site base location: `components/foo.js`), we [skip shadowing](https://github.com/gatsbyjs/gatsby/blob/03b766210aec74d804fcd528899bb3f13f33d490/packages/gatsby/src/internal-plugins/webpack-theme-component-shadowing/index.js#L56).

**Comment by ChristopherBiscardi** [comment]
We could make this check more restrictive and only check valid shadow paths instead of the "same suffix" that worked for the PoC. Basically this would consist of constructing the list of potential paths and then running `potentialPaths.includes(issuer)` without the extensions.

**Comment by jlengstorf** [comment]
That seems right to me. This pattern makes it possible to avoid needing to know the parent theme(s) to shadow properly. (E.g. using `gatsby-theme-b` but needing to shadow `gatsby-theme-a`.)

Are there any pitfalls to getting more restrictive? Another approach would be to warn that a component has been duplicated and tell me to rename that component to avoid collisions, e.g.:

```jsx
import React from 'react';
import Foo from '../../components/child-foo.js';

export default Foo;
```

I'm not sure if there are _more_ confusing edge cases if the Russian nesting doll of shadowed components within shadowed components. I can't think of any off the top of my head; my gut currently says it'll be overall less painful if the child theme shadowing worked as expected (e.g. any component in the theme will be shadowable, even if that component itself is shadowing a parent theme component).

I'm not sure if @johno found a better way to manage this, but the pattern I'm following in the repro above is the best I've found so far (assuming there's a way to make the double-shadow work).

Is there something I can do to help here?

**Comment by ChristopherBiscardi** [comment]
> Are there any pitfalls to getting more restrictive? 

Not that I know f, it should've been more restrictive from the start but the import didn't work anyway, so we weren't introducing any new bugs to existing code by merging the original PR :)

I think that for the use case of "having a child theme that exposes it's own API and the parent theme is an implementation detail", this is a feasible pattern and a nice way to handle modifying the API surface of component shadowing for consumers without having to introduce a new core Gatsby API.

> Is there something I can do to help here?

Feel free to do the implementation of the shadowing checks! hopefully I've explained it well enough in my last comment. We don't need to check that the paths actually exist, just check if they match any possible "parent" import (hence `.includes`) because this is a "normal import" so if the module doesn't exist on disk we still want standard webpack to process and be like "hey yo, you required a file that doesn't exist" like it normally would.

This is a good change, I like the pattern you have in the repo, and we should do it.

**Comment by jlengstorf** [comment]
Cool. I'll take a crack at this in the next few days and see if I can figure it out. 😄
