### ISSUE TITLE
The files within `.cache` and `public` should see their dependencies pre-resolved

### ISSUE THREAD

**Issue by arcanis** [gatsbyjs/gatsby#12948]
## Description

The files within the `.cache` and `public` folders (here `public/render-page.js`) contain the bare, unresolved, imports. This causes issues under PnP (because as far as the loader goes the public files belong to the project rather than Gatsby), but also in general (depending on the hoisting, the wrong dependencies will be loaded).

The resolution should instead be pre-resolved, at least partially (relative paths, which would be portable across systems), so that you can guarantee that the files will use exactly the same version as you expect.

### Expected result

```js
exports["lib"] = factory(require("./node_modules/@reach/router/index.js"), require("./node_modules/core-js/modules/es6.object.assign.js"), ...);
```

### Actual result

Example of the `render-page.js`:

```js
exports["lib"] = factory(require("@reach/router"), require("core-js/modules/es6.object.assign"), ...);
```

**Comment by sidharthachatterjee** [comment]
> but also in general (depending on the hoisting, the wrong dependencies will be loaded).

Can you elaborate on this?

**Comment by pieh** [comment]
> > but also in general (depending on the hoisting, the wrong dependencies will be loaded).
> 
> Can you elaborate on this?

In our `cache-dir` (gatsby runtime / static html files template) we do require dependencies declared by `gatsby` package, but later on we copy them to project directory (to `.cache`) - so in those copied files we do require things that are `dependencies` of `gatsby` and not necesairly project `deps` (in example `@reach/router`) - if package manager decide to install those deps in `node_modules/gatsby/node_modules` instead of top level `node_modules` (it won't hoist them) - this will fail (and also cause problems for PnP).

I'm thinking instead of copying those files to project's `.cache`, we should keep them as they are (in `gatsby` package), and instead adjust any imports to dynamically generated files (for example `async-requires.js`) to use webpack alias. This _should_ work and also we can skip "copying `cache-dir` to `.cache` step with this
