### ISSUE TITLE
Consistent use of Promise or aysnc/await in related docs for creating page from graphql

### ISSUE THREAD

**Issue by erichgoldman** [gatsbyjs/gatsby#12955]
## Summary

Inconsistent use of Promise vs async/await in GraphQL examples in documentation

### Basic example

In [Part 7 of the tutorial](https://github.com/gatsbyjs/gatsby/blob/master/docs/tutorial/part-seven/index.md) Promises are used e.g.,

```
exports.createPages = ({ graphql, actions }) => {
  // **Note:** The graphql function call returns a Promise
```

However, when you visit the docs for [Programmatically create pages from data](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/programmatically-create-pages-from-data.md) async/await is being used e.g.,,

```
exports.createPages = async function({ actions, graphql }) {
  const { data } = await graphql(`
```

### Motivation

I see some existing issues( #11548 and #5424) that were closed relating to this.

It would seem it should either be consistently one way or that both options should be provided with an explanation of trade-offs. 

Were the [issues with babel](https://github.com/gatsbyjs/gatsby/issues/11548#issuecomment-460524605) resolved or is this just an issue of two different people writing docs the way they preferred?

For tutorials I would recommend whichever is more readable over more performant, but then maybe provide a note on the other option

**Comment by erichgoldman** [comment]
Another page to be synced: https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/creating-and-modifying-pages.md

**Comment by sidharthachatterjee** [comment]
Thank you for opening this @erichgoldman 

It seems that https://github.com/gatsbyjs/gatsby/issues/11548 got closed due to inactivity. I've gone ahead and reopened it since it makes sense to move over to async await but only once https://github.com/gatsbyjs/gatsby/issues/2114 is resolved so we don't encourage heavy shims in browser code. 

In the mean time, there is definitely value in consistency and I think moving docs over to use Promise everywhere is probably a good idea. I'd like to hear what @marcysutton has to say about this.
