### ISSUE TITLE
Use https://zeit.co/blog/ncc to compile gatsby-cli to a single file for faster installs & startups

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#12953]
We want our CLI to be as fast as possible to install and bootup since we expect people to run it all the time. Compiling the package with [ncc](https://zeit.co/blog/ncc) could help a lot with that.

**Comment by polarathene** [comment]
Would porting the CLI to something like Rust also work? The source doesn't look too big, but then I see quite a bit of dependencies in the package.json. 

With Rust you should be able to support each platform/OS that `gatsby-cli` does, and get a very small binary executable out of it. They have great tooling for making CLI tools among the other benefits of Rust. 

Downside is, it's another language which'd hurt maintenance/development due to less devs with Rust knowledge I guess.. And there have been some issues with the image processing packages when it comes to npm packages handling their binaries, which I imagine you'd still want to use for delivering/distributing `gatsby-cli`?

**Comment by KyleAMathews** [comment]
Moving to rust would be a lot of work :-)

ncc is a much smaller task.

Also this is just for the cli package, not the main gatsby package.

**Comment by DSchau** [comment]
Note: we tried this in #13256 and didn't see a big speed-up, or really any discernible difference. Hard to merge that PR in the absence of a clear and obvious benefit due to the additional (small!) complexity of using another tool like ncc.

It's possible we don't necessarily have the kind of project that would benefit from this (e.g. _tons_ of require statements that slow down the Node.js process on boot-up).

Going to close for now--but we'd love to revisit this again in the future
