### ISSUE TITLE
[gatsby-plugin-offline] Service worker does not update on route change

### ISSUE THREAD

**Issue by tessereth** [gatsbyjs/gatsby#12964]
## Description

As described in the [this documentation](https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle#updates), service workers only update on navigation, which in the world of an SPA means only on page refresh. This causes the site to continue to show the old content until the user refreshes or visits an un-cached page. If you add something like the following to `gatsby-browser.js`, the service worker will get refreshed whenever the user clicks a link.

```js
exports.onRouteUpdate = () => {
  navigator.serviceWorker.register('/sw.js').then(reg => {
    reg.update()
  })
}
```

### Steps to reproduce

Demo: https://github.com/tessereth/sw-refresh-bug. There are reproduction steps in the readme.

### Expected result

Clicking on links should give me the latest content.

### Actual result

Continue to see stale content due to using an old service worker.

### Environment

<details>
  <summary>environment</summary>
<pre><code>  System:
    OS: macOS 10.14.4
    CPU: x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Shell: 5.6 - /usr/local/bin/zsh
  Binaries:
    Node: 8.11.4 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 5.6.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 73.0.3683.86
    Firefox: 64.0.2
    Safari: 12.1
  npmPackages:
    gatsby: ^2.3.3 => 2.3.3 
    gatsby-image: ^2.0.35 => 2.0.35 
    gatsby-plugin-manifest: ^2.0.25 => 2.0.25 
    gatsby-plugin-offline: ^2.0.25 => 2.0.25 
    gatsby-plugin-react-helmet: ^3.0.11 => 3.0.11 
    gatsby-plugin-sharp: ^2.0.32 => 2.0.32 
    gatsby-source-filesystem: ^2.0.28 => 2.0.28 
    gatsby-transformer-sharp: ^2.1.17 => 2.1.17 
</code></pre></details>

**Comment by pieh** [comment]
I'm not sure what's best way to approach this. We would need to make extra network request (either after navigation like in your workaround or periodically) to check if service worker did update since initial load.

This is not strictly a "bug", but I do agree it's also not intuitive (at least for users that expect that behaviour). I would be weary to make checking for SW updates after initial load a default behaviour tho.

@davidbailey00 do you have any thoughts? Are you aware if there is any "prior art" to doing this? Most service worker example I saw were just registering SW just on initial load

**Comment by tessereth** [comment]
Yeah, I figured this lives somewhere between bug and feature. But it was unexpected and as someone not particularly familiar with service workers it took me a long time to debug.

> We would need to make extra network request

This was why I decided to do the check on navigation rather than periodically. It just seemed more "expected" to do a network request then. And it's more obvious at that point that the user's interacting with the site (so we don't check in the middle of the night when said user just left their browser tab open).

> I would be weary to make checking for SW updates after initial load a default behaviour tho

Doing it via config, so long as said config is documented and thus the issue is discoverable, would be fine by me.

**Comment by tessereth** [comment]
I'm happy to open a PR for this, I just need to know whether your interested. In particular:

1. Is this something you think the plugin should fix or something the user should handle?
2. Assuming you want to handle it, do you want a periodic or on-navigation strategy?
3. What, if anything, should be configurable?

**Comment by davidbailey00** [comment]
Hey there! Sorry for replying late - just wanted to give my two cents :)

I think we have discussed this behavior before internally and agreed that there are some advantages and disadvantages to both the current behavior and proposed. Primarily, introducing an instant refresh would cause a delay and might appear odd to users of a site.

If you want to force a refresh immediately, you can use the [`onServiceWorkerUpdateReady`](https://www.gatsbyjs.org/docs/browser-apis/#onServiceWorkerUpdateReady) API to trigger a refresh as soon as a service worker update is ready. See [this page](https://www.gatsbyjs.org/docs/add-offline-support-with-a-service-worker/#displaying-a-message-when-a-service-worker-updates) for an example, using a prompt rather than an immediate reload.

Also, currently @Moocar is working on a lot of internal refactoring which would change the way page manifests work, and after these changes are implemented it should make it easier to update the page to the latest version without having to do a full refresh in some cases - please correct me if I'm wrong Anthony!

Let me know if you have any other questions - I'll keep this issue open for now for discussion.

**Comment by tessereth** [comment]
That all makes sense but I think you might have missed what I'm actually concerned by. Let me try and explain. The service worker update lifecycle is something like:

1. Original version of the service worker is installed
2. Browser checks if `sw.js` has changed
3. New service worker is installed
4. New service worker takes over pages

`onServiceWorkerUpdateReady` is to do with steps 3->4. I'm concerned here with step 2. What I'm suggesting is that we check (in the background) whether the service worker has changed or not on route changes so the user will get the new service worker (and thus the new content) sooner. Does that make sense?
