### ISSUE TITLE
Scroll position behaviour not as expected with gatsby navigate

### ISSUE THREAD

**Issue by t2ca** [gatsbyjs/gatsby#12997]
I have a page with a list of links to filter data and the following useEffect hook is causing me problems:

```
  useEffect(() => {
    const {
      location: { pathname, search },
    } = props

    const queryString = qs.stringify({ filters: filters })

    if (search !== `${queryString}`) {
      navigate(`${pathname}?${queryString}`, { replace: true })
    }
  }, [filters])
```

The issue is that every time i click on a link, the scroll position jumps to the top. Im expecting the scroll position to remain the same after clicking the link, which i believe should be the normal behaviour.

I was able to solve this issue by adding the following code to gatsby-browser.js

```
exports.shouldUpdateScroll = () => {
  if (window.__navigatingToLink === true) {
    return [0, 0]
  }
  return true
}

exports.onRouteUpdate = () => {
  window.__navigatingToLink = false
}
```
However, since gatsby-react-router-scroll was updated to version 2.0.7, the above code is no longer working for some reason. Im able to downgrade gatsby-react-router-scroll to version 2.0.6 to fix this problem but i'm looking for a real solution. Thank you

**Comment by pieh** [comment]
Can you provide more complete reproduction? Ideally one that can be cloned and run to see the issue?

**Comment by KyleAMathews** [comment]
http://gatsby.dev/reproduction for instructions

**Comment by t2ca** [comment]
Thank you for looking into this problem for me, I have made a reproduction here:

https://github.com/t2ca/scroll-issue

The issue is that when clicking the button the scroll position jumps to the top.

index.js and gatsby-browser.js are the only files modified.

Once you downgrade gatsby-react-router-scroll to version 2.0.6

The scroll behaviour is as expected.

Thank you!

**Comment by narration-sd** [comment]
And, I may see the reason for what's happening here. NOT a good thing, if so..

- the change from gatsby-react-router-scroll 2.0.6 to 2.0.7 is indeed where the regression happened, at least as visible here. Lock 2.0.6, and works again.
- just from the commit note on 2.0.7, apparently the idea is to restrict scroll memory to history back-button only (??)
- this, apparently also, has something to do with a more obscure issue set, #12390 - #135 , though I'm not seeing this yet, if not digging in
- but if you need this 2.08 functionality, _please_ make it or reversion a settable option!
- that's the way, right?
- don't-regress suggests the default should be original behavior, but you can sort that out by your  own view, as far a needs here are concerned, thanks - as long as the option is provided so memory always happens, exactly in the previous 2.06 way.

Why is this important? Well, it's a bit too much to fully explain, but I'm providing live preview editing for Gatsby pages before they're (re-)built, when driven by a remote page data service, and this requires reloading the current page at the current url. So, no back button or  route change occurs. 

It's critical that an editor not see their page jump around. That's what I need to preserve, and with thanks, and please.

**Comment by narration-sd** [comment]
For some reason, the note I placed on the 2.0.7 mod isn't getting referenced here, maybe because  that's not an issue post, so you can connect to those messages here:  https://github.com/gatsbyjs/gatsby/pull/12403#issuecomment-480455275

**Comment by narration-sd** [comment]
Right on time, as I'm about to release a complicated product, and it must not have its screen jumping around.

I've been leaving it pinned to the version before this bug showed up, and will check if there's been any silent repair. 

Meanwhile, kindly do not close this issue, thanks.

**Comment by narration-sd** [comment]
Ok. @KyleAMathews , I've just spent hours I didn't have untangling this, I hope, for responsibility on the project I'm about to release. 

It would be very helpful if you could explain what is actually going on.

To make a long story short, _now_ scroll memory has returned to working as it had prior to this change. But the code...that's the question.

I set up to do a PR, in fact, and then found the current code worked. It looks different, as delivered by npm compared to my fork of gatsby at the time, with something like a type coercion protection inserted in what appears logically the same for the problem routine. But there's a wholesale change in JavaScript method in the file, and so I believe all of this is result of some filters you pass source through on the way to production.

This likely means it's something else that changed, in Gatsby's _use_ of ScrollStorage.

It would be great, and confidence-building, to know what that other change might be.

With that notated here, it would be fair to close this issue.

Thanks, and in hopes you can remember,
Clive

**Comment by narration-sd** [comment]
(@KyleAMathews, an intermediate message deleted, as a cache apparently fooled tests, and this mod still causes the same trouble. I'll be back...)

**Comment by narration-sd** [comment]
@KyleAMathews  Ok, I've fixed this for our purposes, so shipping can happen. First the fix for others interested, and then a comment or two may not go amiss.

- If you are trying to get your page to use the current scroll position it, by looking at the list Gatsby is using, this will work now, after gatsby-react-router-scroll changes at version 2.0.7. Something like:
```
import ScrollStorage from 'gatsby-react-router-scroll/StateStorage.js'

class yourReactComponent {

  scrollStore = new ScrollStorage()

  componentWillUpdate = () => {  //  put in also any of its args you will use
      this.location = window.location // window is safe here
      this.location.key = 'initial' // this is what targets the grrs 2.07 change
      try {
        const currentPosition = this.scrollStore.read(this.location, null)
        if (currentPosition) {
          yourDevLog ('scrolling to: ' + JSON.stringify(currentPosition))
          let [x, y] = currentPosition
          window.scrollTo(x, y)
        }
      } catch (e) {
        yourDevLog ('no currentPosition yet: ' + e)
      }
  }
}

```
That's I think pretty bullet-proof, so here's comment:

- honestly, the routine modified for the 2.07 changes is a very obscure piece of code. What it's hiding is apparently a clip job to marry up other systems that never bothered to be compatible. One would think you could at least unroll it a bit, and _comment_ what it's doing and why.

Because of these difficulties, it's very clear why @pieh created a passel of tests to accompany the change. That part, well done, respectful in the circumstance.

- I found I couldn't just PR the problem routine, so it would return to expected behavior, because this would unravel why the 2.07 change was made. 

- Looking a bit further, this whole 'must return to top' thing has clearly been a problem for reach-router and Gatsby. People think they want this. They obviously always don't -- it's just one possible state, and in those cases a convenience. reach-router actually has code which can make it  work either way. 

- I submit that it would be very good then for Gatsby to _implement_ this reach-router feature, and so that individual pages or groups of them can have either always-to-top or what-it-was-before scroll behavior. Even blog-makers will thank you, according to case, and for those doing more, it's often going to be essential. Nobody should have to hack in on your interior components as I have done.

- finishing, I realize it's common for you to expect a) a squashed test case b) an idea what the real usage is.  I haven't provided, because I'm doing something unusual, making a and b both difficult, and not a  help. It's pretty useful, though, what this 'unusual' accomplishes, if it takes a great deal else to get it going. I think not a detriment to your cause, at the least.

Regards,
Clive

**Comment by narration-sd** [comment]
Just to close this off, the solution for a need I posted just above doesn't work for a home page. Thus I simply stopped using Gatsby's mechanism at all; simple to provide one's own.

_Why_ this failed appears to show up interesting if not improper scroll memory behavior in the Gatsby system now. I've detailed that in another posting, where there actually was some attention paid, and won't comment further here. See for that info:  https://github.com/gatsbyjs/gatsby/issues/12560#issuecomment-501904947
