### ISSUE TITLE
[feat]: augment gatsby-source-contentful to look for certain environment variables to define options

### ISSUE THREAD

**Issue by DSchau** [gatsbyjs/gatsby#13050]
## Summary

Contentful has first-class integration with [Gatsby Preview](https://www.gatsbyjs.com/preview/). As a user/developer _using_ this feature, we defer to the `gatsby-config.js` for the "source of truth" for these plugin options and configuration, oftentimes driven by environment variables.

What I propose is a way to _continue_ to support this as a source of truth, but provide a quick escape hatch in `gatsby-source-contentful` to prefer certain environment variables if they exist, otherwise fall back to the passed-in config.

This is a _quick fix_ to improve user experience across the board, but a better/longer-term fix that has general applicability is [detailed here](https://github.com/gatsbyjs/gatsby/issues/12919#issuecomment-479108368)

### Basic example

We will want to augment [these lines](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-contentful/src/gatsby-node.js#L62-L66) to prefer Gatsby Preview environment variables, if they exist. To a regular user--this will have no impact, whatsoever.

The algorithm is quite simple, e.g. if we want to check for host, it's:

```js
options.host = process.env.___GATSBY_CONTENTFUL_HOST___ || options.host || `cdn.contentful.com `
```

We will check for three variables, specifically:

- `host`: `process.env.___GATSBY_CONTENTFUL_HOST___`
- `accessToken`: `process.env.___GATSBY_CONTENTFUL_ACCESS_TOKEN___`
- `spaceId`: `process.env.___GATSBY_CONTENTFUL_SPACE_ID___`

These should be checked _first_--if they exist use them, otherwise fall back to the existing/passed option.

### Motivation

The end-user experience with using Gatsby Preview is measurably improved and simplified with this change, whereas a non-Gatsby Preview user has the _exact same experience._ Win win!

cc @thebigredgeek @abhiaiyer91

**Comment by DSchau** [comment]
As usual--@pieh has an excellent point!

How do we handle multiple instances of `gatsby-source-contentful`? There doesn't appear to be a readily apparent heuristic that would let _someone_ (e.g. Gatsby Preview) know which instance of the plugin to inject. For example, consider the following `gatsby-config.js`:

```js
module.exports = {
  plugins: [
    {
      resolve: 'gatsby-source-contentful',
      options: {
        accessToken: `hunter2NonPreviewAPI`,
        spaceId: `some-space-id`
      }
    },
    {
      resolve: 'gatsby-source-contentful',
      options: {
        accessToken: `this-is-the-gatsby-preview-one`,
        spaceId: `some-gatsby-preview-space-id`,
        // host _needs_ to be preview.contentful.com
      }
    },
    {
      resolve: 'gatsby-source-contentful',
      options: {
        accessToken: `a-preview-access-token`,
        spaceId: `some-other-space-id`,
        host: `preview.contentful.com`
      }
    }
  ]
}

```

There isn't a great heuristic to know that the _second_ instance of `gatsby-source-contentful` is the one that we should inject.

## Proposed Solutions

- Provide a library that is a no-op in non-Gatsby Preview environments, but _in_ Gatsby Preview will use overrides, e.g. something like
    ```js
    module.exports = function gatsbyPreviewOverrides(plugin, options) {
      if (!process.env.GATSBY_PREVIEW) {
        return options
      }

      let overrides = {}
      // this could also be less generic, e.g. the contentful plugin could just be a single, standalone library, e.g. `gatsby/cloud/contentful`
      switch (plugin.name) {
        case 'gatsby-source-contentful':
          overrides = {
            host: process.env.___GATSBY_PREVIEW_HOST___,
            accessToken: process.env.___GATSBY_PREVIEW_ACCESS_TOKEN___,
            spaceId: process.env.___GATSBY_PREVIEW_SPACE_ID___
          }
          break;
        default:
          break;
      }

      // this may need to be a deep merge
      return {
        ...options,
        ...overrides
      }
    }
    ```
- Provide an environment variable (e.g. `GATSBY_CONFIG_PATH`) that will override the default `gatsby-config.js` loading, e.g. `GATSBY_CONFIG_PATH=gatsby-config.preview.js gatsby develop` 
    - This is _still_ an issue, but at least in this scenario we can warn or provide some way to alert the user that they have multiple instances and we're not sure which one to use
- Janky mechanism to detect if a given plugin has an accessToken. If it has an access token, these overrides noop, otherwise if no access token, will try to inject one, e.g.
    ```js
    const getContentfulOptions = options => {
      const overrides = options.accessToken ? options : {
        accessToken: process.env.___GATSBY_CONTENTFUL_ACCESS_TOKEN___,
        host: process.env.___GATSBY_CONTENTFUL_HOST___,
        spaceId: process.env.___GATSBY_CONTENTFUL_SPACE_ID___
      }
      return {
        ...overrides,
        host: overrides.host || `api.contentful.com`, // default to the production API
        environment: overrides.environment || `production`
      }
    }
    ```

**Comment by DSchau** [comment]
Also note in the above example: generally accessToken (and other "secrets") would not and should not be committed to source control. Done just for the sake of example 🙃

**Comment by MarcCoet** [comment]
Hey, I've got a similar issue with other plugins. See my [Spectrum post](https://spectrum.chat/gatsby-js/general/collect-config-variables-from-source~e09b5425-1316-42d6-84a9-eb039813fb06).
I would like to be able to set plugin options (or env variables) during build so that API hooks/plugins that are called later during build can use the specified options.
I believe that resolving this issue specifically for contentful previews is not a good idea since the problem apply to all plugins. We don't have a way to 'compute' or fetch plugin options during build.

**Comment by thebigredgeek** [comment]
@pieh @DSchau any updates on this?

**Comment by DSchau** [comment]
@thebigredgeek nothing as of yet--I would say this is sort of blocked until we figure out a reliable solution that doesn't introduce hacky workarounds.

My post above is a good summation of the current state of things.

**Comment by DSchau** [comment]
Going to close this out. Magic is _bad_, and we want to provide a clear, easy experience for users even if it's not 100% automated. As such--we're going to recommend to continue to use environment variables for secrets and provided data, rather than bake-in defaults that could be unclear.

@MarcCoet it seems your issue is a little different, here. I'd recommend just using a prebuild script to expose those environment variables, e.g.

```js
async function getEnvironmentVariables() {
  // do async stuff
}

getEnvironmentVariables()
```

Also, this isn't totally true.

> We don't have a way to 'compute' or fetch plugin options during build

Because plugin options are a JavaScript object, you can certainly build in a hook to do async setup work _before_ something else, e.g.

```js
{
  resolve: `gatsby-source-whatever`,
  options: {
    setUp() {
      return new Promise(resolve => setTimeout(resolve, 2000))
    }
  }
}
```

it's just on the implementer of the plugin to add in that functionality. In some cases--it may make sense to do that if it's a likely async operation. In others--maybe not so much and a setup script works just as well.

**Comment by MarcCoet** [comment]
Thanks @DSchau.
> We don't have a way to 'compute' or fetch plugin options during build
I mean for plugins we didn't write ourselves.
Correct me if I am wrong but you are talking about writing my own source plugin so I can set it up as I please. I have got a few custom plugins but writing my own source plugin for one that already exists defeats the whole purpose of using a plugin architecture I believe.
It would be nice to have a way to make plugins communicate with one another through config so that we can actually do it even with plugins we didn't write.
Env variables would be fine but if I change a variable value in an early called plugin, later ones' config will still get the original value. It is not surprising. I guess the whole config is 'read' once at the very beginning of the build so changing variable after won't matter.
An idea to potentially handle that with few hassle and without any breaking change could be allowing resolving plugins with a callback.
```
{
  resolve: `gatsby-plugin-awesome`,
  cb: (someVar = process.env.MYVAR) => ({
    // returns options
    pluginOption: someVar
  })
}
```
The callback function will only be called when the plugin is called and options specified in the returned object can hydrate plugin options.
With that, a plugin called earlier in the chain can change the value of `process.env.MYVAR` and we will get the fresh value in the plugin's options.
Right ? Wrong ?
Hopefully something will make sense in this post or at least make you understand my issue better. ;)
