### ISSUE TITLE
gatsby-transformer-documentationjs creates non-unique ids

### ISSUE THREAD

**Issue by stefanprobst** [gatsbyjs/gatsby#13052]
`gatsby-transformer-documentationjs` creates nodes that can have non-unique ids, for example for comments like these:

```js
/**
 * This is a free-floating comment
 */

/**
 * This is a function
 */
const fn = () => {}
```

When trying to build such a site with `GATSBY_DB_NODES=loki` this will throw:
```
error Error processing Markdown in node 27c286f3-9f32-5454-9d77-a9265e600a7d:
Trying to update unsynced document. Please save the document first by using insert() or addMany()
```

See repo: https://github.com/stefanprobst/gatsby-bug-docjs

**Comment by pieh** [comment]
Some context on why this happened:
`documentation` creates 2 objects for the same `path` (`fn` function):
![Screenshot 2019-04-03 at 01 38 27](https://user-images.githubusercontent.com/419821/55443964-f4bcd100-55b4-11e9-88e6-94b38b3fb616.png)

I'm not sure if this is something that actually should be handled in `documentation` package, but I did open PR (#13058) with fix/workaround for this.

Other thought I have about this is that, while it's nice that loki helped to catch this issue in documentatino plugin - it essentially mean you can't really update plugin with loki? Because this is what was happening with documentation - it created a node, and then tried to create another node with same id and loki just throw - but it should work (even if outcome in this scenario is not desired).

**Comment by stefanprobst** [comment]
Yes i agree that Loki's node updating should check for `node.$loki` and if it's not there get the node-to-update from the store instead of throw.
