### ISSUE TITLE
[gatsby-source-filesystem] processRemoteNode concurrent requests overload

### ISSUE THREAD

**Issue by violy** [gatsbyjs/gatsby#13073]
## Relevant information

During build, on my local environment, using `gatsby-source-wordpress` to fetch Wordpress `custom_post`, `acf` (with `image` and `gallery`) I observe the `Failed to process remote content` warning during media fetching, warning logged in `gatsby-source-filesystem`, `create-remote-file-node`.

This failure prevents media to be fetched, and the build failed. 
In walking through gatbsy github issues… and found this comment, https://github.com/gatsbyjs/gatsby/issues/5371#issuecomment-390969703 
and fix the warning ! 
only replace `concurrent` value `200` with  `10` in `Queue` managment !

https://github.com/gatsbyjs/gatsby/blob/15cdf2c77e4e5cd1086b87bc9c828128c9022f24/packages/gatsby-source-filesystem/src/create-remote-file-node.js#L80-L92

But i fix this locally… 
**is there a way to configure this _concurrent value_, maybe through a `gatsby-source-filesystem` config options ?** 
the value seems actuallys static… why is this value static ?

thanks.

### Environment

Mac OS, local dev build.

**Comment by pieh** [comment]
It's not feasible to do this via pluginOptions, because it's the other plugins (not `gatsby-source-filesystem`) that are calling `createRemoteFileNode`. All this code really need to be rewritten to handle failures much better, but in meantime perhaps we can use env var to overwrite default limit - for example:

```
concurrent: process.env.GATSBY_CONCURRENT_DOWNLOAD || 200, 
```

and use it either in `.env` files ( https://www.gatsbyjs.org/docs/environment-variables/#server-side-nodejs ) or command line / package.json script ( `GATSBY_CONCURRENT_DOWNLOAD=10 gatsby develop` )

**Comment by violy** [comment]
Ok, it's a quick resolution, and I like it. 

Such _similar_ environment core configurations is listed/documented somewhere ?

**Comment by violy** [comment]
According your resolution, @pieh 
I've made a Pull Request. 

## other statics in `create-remote-file-node.js`

The PR adding 2 others environment const, initially statics, in `create-remote-file-node.js` 

* `GATSBY_DOWNLOAD_TIMEOUT`
* `GATSBY_DOWNLOAD_RETRIES`

assuming previous statics values as default, preventing breaking change. 

## more verbose warning

Also, I improve the `Failed to process remote content` warning, including the error message, after url. 
During my build debug, I haven’t any idea of why this warning appears, and a more verbose warning would have help me. 

## explanation in my local and project context

During my build debugging, the download failed on random URLs, and don’t strictly stop the build (only warnings mentioned above was displayed) and never complete. This was very frustrating.

So I put more verbose warning (like in my PR) it understood the *cause* of the failure. 

Initially, it was a `503` response returned by server overload (WP hosted on legacy platform of my customer)
After that I've decided to push a CloudFlare in front of my host. 
But even with CloudFlare, that was not enough to solve the problem, I had `request timeout` error message … may be due to local network overload over anything else … a very painful situation !

**Comment by Eltyo** [comment]
For those waiting patiently for this PR, I'll quickly share my solution for deploying to Netlify:

In your `.gitignore` file replace `node_modules/` with
```
!node_modules/
node_modules/*
!node_modules/gatsby-source-filesystem/
node_modules/gatsby-source-filesystem/*
!node_modules/gatsby-source-filesystem/create-remote-file-node.js
```

Save and commit the PR changes, then change your Netlify build command to `git reset --hard && gatsby build` (git reset is needed since `yarn install` will overwrite your changes). Give your site the `GATSBY_CONCURRENT_DOWNLOAD` environment variable and set it to `10`.

Voila! Good to go.

**Comment by TylerBarnes** [comment]
The `GATSBY_CONCURRENT_DOWNLOAD` env variable is now available in production and it looks like this has been resolved. Please re-open or comment if you feel I missed something and this should still be open. Additionally, https://github.com/gatsbyjs/gatsby/issues/10049 is tracking ways of solving this in potentially more intelligent ways.
