### ISSUE TITLE
Get request external website

### ISSUE THREAD

**Issue by lpluispacheco** [gatsbyjs/gatsby#13126]
Hi, is possible show information of an external website? 

If I need show data on my website (build in gatsby) of an external website how can I make this work? 

Any documentation about it?

Thanks

**Comment by marcysutton** [comment]
Hi @lpluispacheco, what kind of information are you hoping to show, and from what website? Is it a domain you own or a random one (the latter will limit what you can do)? 

It would help to qualify this request a bit to know what parameters we're working with. Does the website have an API you can call, or are you trying to scrape the content?

**Comment by lpluispacheco** [comment]
Hi @marcysutton, sorry for details left. 

It's a API of Booking: https://developers.booking.com/api/commercial/index.html?version=2.4&page_url=how-to-book

Technically i'll putting the dates, persons but I want to show it directly on my website, is it possible? I was trying to find information about it but I couldn't find nothing.

Thanks for your answer!

**Comment by marcysutton** [comment]
@lpluispacheco I don't see why it wouldn't be possible to hit an API, since you can use web technologies on a Gatsby site just like in any React application. A quick search came up with multiple plugins for sourcing content from APIs:

- https://www.gatsbyjs.org/packages/gatsby-source-apiserver/?=api
- https://www.gatsbyjs.org/packages/gatsby-source-custom-api/?=api
- https://www.gatsbyjs.org/packages/gatsby-source-thirdparty/?=api

I'm not familiar with Booking's API though–are you trying to display read-only content or enable the whole booking/purchase flow? The former seems like something you could do on the server-side potentially, but you may be limited to client-side API calls...that is something you'll have to investigate. The plugins listed above may give you some ideas of where to start.

**Comment by andrewfairlie** [comment]
Another option that might be viable is to use Axios to pull in the content from Booking.com on the client-side which may be better suited here because the (presumably) real-time nature of the booking information?
