### ISSUE TITLE
IE10 - 'Set' is undefined

### ISSUE THREAD

**Issue by MariuszDabrowski** [gatsbyjs/gatsby#13166]
## Description

Using the [Gatsby default starter](https://github.com/gatsbyjs/gatsby-starter-default), if you build the project and preview the built project in IE10 you get the following error:

`SCRIPT5009: 'Set' is undefined `

### Steps to reproduce

1. Setup a new project using [Gatsby default starter](https://github.com/gatsbyjs/gatsby-starter-default)
2. Build the project using `npm run build`
3. Start up a web server in the public directory and preview the site using IE10
4. Open up the console and refresh the page to see the error

### Environment

Browser testing was done in [Browser stack](https://browserstack.com) - Win 7 IE 10

**Comment by jonniebigodes** [comment]
@MariuszDabrowski let me start by saying i'm sorry for the issue you're having, but some tangible issues regarding this type of situation keep being created in here. 
As a workaround, i would like for you to add to your `gatsby-browser.js` the following:
```javascript
import 'core-js/modules/es6.set'; 
import 'core-js/modules/es6.map';
```

Be advised that using Gatsby with ie10 in development mode there are some issues regarding hmr (hot module replacement). But for production build adding those imports should resolve your issue.

A little more context on the issue in [here](https://www.gatsbyjs.org/docs/browser-support/)

Feel free to provide feedback

**Comment by MariuszDabrowski** [comment]
@jonniebigodes thank you for the prompt reply.

Still working with [Gatsby default starter]() without any modifications besides adding the code below to `gatsby-browser.js`:

```
import 'core-js/modules/es6.set'; 
import 'core-js/modules/es6.map';
```

A strange issue occurs. The page will load fine without any errors. But it you click on `Go to page 2` then on `Go back to the homepage`, eventually the app crashes on the homepage with the following error:

<img width="1743" alt="Screen Shot 2019-04-05 at 5 15 15 PM" src="https://user-images.githubusercontent.com/4285139/55656985-d8907e00-57c6-11e9-8f57-026a13c38a52.png">
<img width="434" alt="Screen Shot 2019-04-05 at 5 17 22 PM" src="https://user-images.githubusercontent.com/4285139/55656994-de865f00-57c6-11e9-92a7-19b5703aa8fc.png">
<img width="1021" alt="Screen Shot 2019-04-05 at 5 15 41 PM" src="https://user-images.githubusercontent.com/4285139/55657020-eba34e00-57c6-11e9-830a-7414467d85d4.png">

**Comment by jonniebigodes** [comment]
@MariuszDabrowski i've been trying to see if i could see what is the problem you're experiencing and i wasn't able to reproduce it. 

Now i tested it out with a production build and Gatsby's internal server through `gatsby build && gatsby serve`, opened edge(as i don't have access to a ie10 anymore) with emulation activated. Opened the page and the result was the following:
![localhost_edge_emulation_ie10_1](https://user-images.githubusercontent.com/22988955/55831964-5973b080-5b0c-11e9-9688-6e38ee9af5a2.png)

![localhost_edge_emulation_ie10_console](https://user-images.githubusercontent.com/22988955/55831969-5ed0fb00-5b0c-11e9-8563-e22fa12febd5.png)

![localhost_edge_emulation_ie10_page_2](https://user-images.githubusercontent.com/22988955/55831977-62fd1880-5b0c-11e9-843c-eef86a591bac.png)

![localhost_edge_emulation_ie10_page_2_console](https://user-images.githubusercontent.com/22988955/55831985-67293600-5b0c-11e9-9481-f8896a6a72d3.png)

Going back and forward always produced the same result, no errors.

I took it a step further, deployed to netlify and applied the same test as above and the results are as you can see below:

![netlify_edge_emulation_ie10_1](https://user-images.githubusercontent.com/22988955/55832090-93dd4d80-5b0c-11e9-911c-834af68b10ed.png)

![netlify_edge_emulation_ie10_console](https://user-images.githubusercontent.com/22988955/55832108-a22b6980-5b0c-11e9-9268-8b4806c29619.png)

![netlify_edge_emulation_ie10_page_2](https://user-images.githubusercontent.com/22988955/55832114-a5265a00-5b0c-11e9-95cf-3fb60322a97b.png)

![netlify_edge_emulation_ie10_page_2_console](https://user-images.githubusercontent.com/22988955/55832121-a8b9e100-5b0c-11e9-99c0-05a6784102e1.png)

To cover my basis, i've added a dummy express server with the following code:
```javascript
const express= require('express');

const app= express()
app.use(express.static('public'))
app.set('port', process.env.PORT || 5000)

app.get('*', (req, res) => {
    res.sendFile('./public/index.html')
})

app.listen(app.get('port'),error=>{
    if (error){
        console.log('====================================');
        console.error(`error starting server with error:\n${error}`);
        console.log('====================================');
    }
    else{
        console.log('====================================');
        console.info(`dummy express server running @ ${app.get('port')}`)
        console.log('====================================');
    }
})
```` 
Added the production build to it. Issued `node index.js` to start the server, same results.
Took it even further, grabbed the production build and added it to a apache server i have running on a WSL machine, started the server and the same results, no errors. 
And finally grabbed the production build and added it to a windows server 2008 RC2 running iis 7.5 and the same results, no errors. 

Now after all of this, it led me to two things. One, what kind of server you're using and how you're running it and two, as i have only access to a trial version of browserstack and with that the number of testing options at my disposal are really very limited i'm not sure if the problem is actually with browserstack and how it emulates the os/browser and the versions they emulate, namely to what point in time

**Comment by MariuszDabrowski** [comment]
@jonniebigodes thank you for the thorough response. I have to admit that I'm not an expert when it comes to the server portion of web apps, but here's what we figured out:

- Running a nginx server caused the same error I was getting above
- Running Python SimpleHTTPServer caused the same error
- Running Gatsby serve didn't cause the error
- Running a separate express server (width your config) also didn't cause the issue

So it looks like the error was happening because the other ways I tried to serve the site weren't redirecting to `./public/index.html` on every request - which is what seems to fix the issue. This was only an issue in IE10 - the other server methods I tried were fine in all other browsers.

Thanks again for the help!

**Comment by jonniebigodes** [comment]
@MariuszDabrowski i factored in what you said and expanded my tests.

- Added ngnix to my wsl installation, running on ubuntu 18.04, created a new folder to test it out and copied over the production build inside, below is the setup i used for nginx to test your issue.
![marius_ngnix](https://user-images.githubusercontent.com/22988955/56097252-a7602e00-5ee9-11e9-9ed4-f2ae191fa5d0.png)

On the left is the configuration for the site, on the right the contents of the folder with the Gatsby production build files.

Starting nginx and applying the same tests like before yelded the same results as i mentioned abvode.

- Created a simple Python http server and made it serve the files for the build and no issues whatsoever. 

As i'm not aware of the setup you used probably was something related to what you said. It was probably a misconfiguration on the server part. Also no need to thank, glad that i could help out in at least point you in the right direction for solving your issue.

**Comment by wardpeet** [comment]
Sadly we don't include polyfills for react.
you can enable this by using this plugin https://www.gatsbyjs.org/packages/gatsby-plugin-compile-es6-packages/ and use react-dom. For your use case you'll have to add

```js
{
  resolve: `gatsby-plugin-compile-es6-packages`,
  options: {
    modules: [`react-dom`]
  }
}
```
