### ISSUE TITLE
[gatsby-transformer-remark] An anchor should be inserted after excerpt

### ISSUE THREAD

**Issue by problem233** [gatsbyjs/gatsby#13185]
## Summary

A `more` anchor should be inserted after excerpt.

### Basic example

```markdown
---
title: Article
---

The Excerpt...

<!-- more -->

More content...
```

should be transformed into

```html
<p>The Excerpt...</p>
<div id="more"></div>
<p>More content...</p>
```

### Motivation

To add "continue reading" buttons in the post listing page.

**Comment by sidharthachatterjee** [comment]
@problem233 If I understand this correctly (please correct me if I am wrong), you'd like `gatsby-transformer-remark` to automatically insert an anchor tag after the excerpt? 

What does `<!-- more -->` in your example signify? Could you please elaborate on the motivation behind this?

This would be tricky to do since the url to the full page isn't in this node.

**Comment by problem233** [comment]
@sidharthachatterjee The "continue reading" button can link to the `#more` anchor so that the reader can actually "continue" reading the post.
