### ISSUE TITLE
Unstyles flash on gatsby-starter-blog with no changes

### ISSUE THREAD

**Issue by sethreidnz** [gatsbyjs/gatsby#13182]
## Description

I deployed the gatsby-blog-starter (https://github.com/gatsbyjs/gatsby-starter-blog) using netlify right from the README of that project, and when I load it it has a flash of unstyled content that quickly become styled.

Also if I turn off JavaScript then I cannot get the site to load unless I do a hard refresh. And if I just do a regular refresh after that then it doesn't load and has this warning

```
The resource https://5ca92723a535b8a153bf3c32--vibrant-tesla-778c98.netlify.com/static/d/604/path---offline-plugin-app-shell-fallback-a-30-c5a-BawJvyh36KKFwbrWPg4a4aYuc8.json was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
```

### Steps to reproduce

1. Load this site https://5ca92723a535b8a153bf3c32--vibrant-tesla-778c98.netlify.com/
2. Notice the unstyled flash of the fonts before they pick up the correct font and it renders as the final state.

For the issue of the JavaScript disabled site

1. Load this site in Chrome https://5ca92723a535b8a153bf3c32--vibrant-tesla-778c98.netlify.com/
2. Open dev tools
3. Press ctrl+shift+P
4. Search for JavaScript and select Disable JavaScript
5. Reload page without doing a hard-reload
6. See that the page only shows `This app works best with JavaScript enabled.`

### Expected result

1. Load this site https://5ca92723a535b8a153bf3c32--vibrant-tesla-778c98.netlify.com/
2. Site to render normally as a regular website

### Actual result

Site renders first without fonts applied, and then flashes into the final state

### Environment

Environment is netlify. I just used the "Deploy to netlify" button to deploy the code directly from the Github here https://github.com/gatsbyjs/gatsby-starter-blog

**Comment by DSchau** [comment]
> Also if I turn off JavaScript then I cannot get the site to load unless I do a hard refresh. And if I just do a regular refresh after that then it doesn't load and has this warning

This is (unfortunately) a known issue with Chrome/service workers. It seems sorta paradoxical that this isn't solved--but if the service worker never registers the site works without JavaScript. However--if JavaScript is disabled _after_ a service worker has loaded the site doesn't work. The bug is filed on [Chrome's issue tracker](https://bugs.chromium.org/p/chromium/issues/detail?id=656516)

Re: the unstyled flash of text--that seems to be a separate issue. I do think we can/should improve our typography handling in the default starters as I've noticed the flash of unstyled text before, as well.

If you'd be interested--I think incorporating some of the techniques in [the font loading checklist](https://www.zachleat.com/web/font-checklist/) would be extremely beneficial. In the absence of that--following some of those techniques on the blog you're using would alleviate some of the issues you're seeing there.

I'm going to close this as answered--please feel free to reply back or re-open if we can help further. Thanks!

**Comment by sethreidnz** [comment]
I have just opted to not use the typography stuff since I assume that will solve the problem? I haven't got that far yet but I assume if I just use fonts like a normal website then I won't have that issue? I only raised it since it's an issue on a core starter that imo I wouldn't use because , especially once tehre is a lot of text on the page, won't look that great.

Is there any reason why I would really want to use `gatsby-plugin-typography` that would outweight the fact that you get that flash of styled content? Sorry I'm very new to Gatbsy and it's overwhelming the number of various different plugins discussed in the tutorials. Not sure how many are best-practice and which are just examples
