### ISSUE TITLE
Feature request: Magic Numbers and default settings

### ISSUE THREAD

**Issue by muescha** [gatsbyjs/gatsby#13198]
There are many "magic numbers" or default settings via `process.env.XXXXXX`

I suggest to have a main defaults file where all these magic numbers refunded and added also a description why this settings are there. And also a mechanism or doc how to overwrite this settings

Just now the code base have many places where this magic numbers are used (search for `process.env` over this repo) but there is no main documentation or explaination about this

I think every possible overwrite should be documented (in an main defaults file or in doc)

**Comment by DSchau** [comment]
@muescha so--there are a few things to consider here, and I have a few clarifying questions. Let's start with the questions.

> There are many "magic numbers" or default settings via process.env.XXXXXX

Environment variables are quite different to "magic numbers." For my benefit--could you provide some examples of what you mean here? Specific files/lines/etc. would be ideal!

Secondly, could you provide a _why_ for what you've been struggling with re: these environment variables? Knowing the issue further will help us understand how we can best formulate a feature or documentation for helping others most effectively.

_Most_ of these environment variables are necessary for internal stuff. For example, `process.env.NODE_ENV` has special significance when building vs. development, as do other environment variables, e.g. `process.env.GATSBY_BUILD_STAGE`.

We do document [some of these variables here](https://www.gatsbyjs.org/docs/environment-variables/#reserved-environment-variables) but admittedly that page has probably gotten a little out of date.

**Comment by muescha** [comment]
i just see so much hits if i search over the repo for [process.env](https://github.com/gatsbyjs/gatsby/search?utf8=%E2%9C%93&q=%22process.env%22&type=) 

if they all internal then it would be ok - but documentation or a list on your page with just a hint (only internal - or an info how to use) would be a little better.

**Comment by DSchau** [comment]
@muescha yeah, most if not all of these are internals, as you note.

The ones that aren't are generally what we'd categorize as experiments--which are sort of intended to be kinda non-discoverable because they're generally opt-in enhancements for features/tweaks/etc. that we want "power users" to discover.

I _do_ think we can make these experiments more discoverable, e.g. I've tossed around the idea of something like this before (in gatsby-config.js).

```js
module.exports = {
  experiments: {
    disableOOM: true // this will set process.env.DANGEROUSLY_DISABLE_OOM=true
  }
}
```

but for now--I think this process works OK. I'm going to take the liberty of closing this out, because I don't think this feature request, as authored, necessarily provides anything actionable that someone could work on.

If you feel differently, happy to discuss this further and provide something actionable. Thanks for opening this!

**Comment by muescha** [comment]
👍  - thx for your explanation.
