### ISSUE TITLE
Issues with redirection

### ISSUE THREAD

**Issue by vedranvinko** [gatsbyjs/gatsby#13211]
Hi,

At work we are using Gatsby to develop a static website, and hosting it on Azure with IIS.

Now comes the problematic part, I am having issues with redirections that happen regardless of my setup. I will now describe whole process, so you can better understand the problem.

I am running this locally on IIS 10, but the issue happens on staging / live environments as well.

When we request some URL, for example root page of project this happens; server does the initial redirect which I wrote, to redirect to /en-ca. This gets redirected with status 301 and redirects to /en-ca/, (notice the trailing slash).

Same thing happens with other URLs. Also worth mentioning is that the address bar in browser doesn't show trailing slash, although tools to follow redirects, do.

One thing that is also good to notice, is that the rule to remove trailing slash by doing it on server level, doesn't get us anywhere, issue still persists. I am 100% sure that rule works, as I tested on another static build, not connected to Gatsby.

To try and investigate issue from another POV, I ran gatsby-contentful starter (https://www.contentful.com/r/knowledgebase/gatsbyjs-and-contentful-in-five-minutes/) and deployed built website locally to IIS. Same issue happens, just slightly different.

When I navigate to localhost/blog, my networking tab is not updating in real time, only when I press refresh on purpose. I understand it as Gatsby router handling the content update, as in JavaScript populates content instead of issuing server request for content.

Other URLs have same behavior, and rule to remove trailing slash is not working (also implemented on server).

Another thing that is weird to me is that initial request issued to server returns 301 on type text/html which gets redirected to type document.

Thank you

**Comment by DSchau** [comment]
@vedranvinko this is a hard one to debug, since it seems specific to a particular hosting provider (Azure with IIS).

Are you able to provide your Azure settings? Could it be a redirect for static content (e.g. analogous to a htaccess, _redirects in Netlify, etc.) that's causing issues?

If nothing else--a link to your site would be most helpful, as would a [reproduction](https://gatsby.dev/reproduction). In this case--what could be worth checking out is trying a separate hosting provider (e.g. Netlify) to see if the issue persists or if this is something unique to Azure or your settings.

Thanks!

**Comment by vedranvinko** [comment]
Hi @DSchau, I am afraid I cannot provide any specific details about Azure; but I will try some other hosting, to check and validate. 

Thank you for your time.
