### ISSUE TITLE
Gatsby-image and Contentful JS SDK

### ISSUE THREAD

**Issue by wdestin** [gatsbyjs/gatsby#13224]
## Summary

I want to get Contentful data with its SDK at runtime and use gatsby-image for optimization. It is possible ?

## Relevant information

I want something like that :

```
import React from "react"
import Image from "gatsby-image"

later in the code...

  async fetchData() {
    const result = await client.getEntries({
      content_type: "images",
      order: "-sys.createdAt",
      limit: 3,
      skip: 0,
    })
   this.setState({result})
  }

later in the code...

  render() {
    return (
      <>
            result.map((e, index) => {
              return <Image sizes={e.sizes} />
            })
      </>
    )
  }
```

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by jonniebigodes** [comment]
@wdestin if i understand correctly what you described in your issue description, you want to fetch the content, the images from contentful use `gatsby-image` to apply the same effect as if it was in your machine. If that's the case, to the best of my knowledge, no, you cannot, the file needs to exist physically in your machine, so that `gatsby-image` combined with the associate plugins can do their job at build time.

**Comment by sidharthachatterjee** [comment]
Hey @wdestin 

Like @jonniebigodes mentioned, this wouldn't work because `gatsby-image` expects a structure (and associated files) processed by `gatsby-plugin-sharp` at build time. 

Closing this out for the moment but please do feel free to comment or reopen if we can help with this further!
