### ISSUE TITLE
Update a live Gatsby website

### ISSUE THREAD

**Issue by omattman** [gatsbyjs/gatsby#13255]
How would one go about updating a live Gatsby website, and where should I place all of my wordpress content?

Can I add the backend wordpress folders to the FTP root directory + the Gatsby frontend and then run a script to check for new posts or updates?

Any suggestions are much appreciated since this is the only concern I have when publishing my website.

**Comment by sidharthachatterjee** [comment]
Hey @omattman 

> Can I add the backend wordpress folders to the FTP root directory + the Gatsby frontend and then run a script to check for new posts or updates?

Sure, you could write a `bash` script that checks for new posts and runs `gatsby build`

Since Gatsby _builds_ your site to static assets though, you could serve the built assets off a CDN (Netlify for example) with your WordPress instance running on a server somewhere else. 

In a setup like this, to "update" your site, you need to trigger a build. With WordPress and Netlify, you can setup web hooks as documented in https://en.support.wordpress.com/webhooks/ (and set the URL to a build hook in Netlify https://www.netlify.com/docs/webhooks) 

This would trigger a new build on Netlify every time content on WordPress is edited.

**Comment by omattman** [comment]
@sidharthachatterjee Thanks for reaching out.

Okay, that seems very reasonable. How would one manage the hosting? Should the wordpress installation be on its own domain plus having the gatsby site on the primary domain? This is the kind of setup im referring to:

Gatsby site: `https://www.primarywebsite.com`
Wordpress: `https://www.wordpress.primarywebsite.com`

Or am I able to host both the wordpress installation and gatsby site on one URL?
