### ISSUE TITLE
How to use gatsby-image with external source

### ISSUE THREAD

**Issue by Hypothesis-github** [gatsbyjs/gatsby#13340]
I was wondering if I can inject an uploaded image's url into <Img /> and expect a lazy loading.

**Comment by jonniebigodes** [comment]
@Hypothesis-github if you mean use that approach with `gatsby-image` as of the present version of `gatsby-image` and it's accompanying plugins, you cannot do it. The image needs to be physically present  so that the plugins can apply the necessary work to it.

**Comment by polishedwp** [comment]
But, there are other plugins available to interact with image services:

[gatsby-remark-yuque-images](https://www.gatsbyjs.org/packages/gatsby-remark-yuque-images/?=unspl)
[gatsby-source-unsplash](https://www.gatsbyjs.org/packages/gatsby-source-unsplash/?=unspl)
[Gatsby-Source-Cloudinary](https://www.gatsbyjs.org/packages/gatsby-source-cloudinary/?=Cloudinary.)

Just to name few examples.

**Comment by jonniebigodes** [comment]
@polishedwp yes..you're right, .but out of the box as of the present state, there's that limitation,

**Comment by polarathene** [comment]
@Hypothesis-github I've raised [a more broader issue](https://github.com/gatsbyjs/gatsby/issues/13353) for `gatsby-image` regarding this request which isn't uncommon. There are other cases where `gatsby-image` would be nice but has become a bit inflexible.

For the time being, as such a refactor may be a while off before started/completed. It's advised like above to pull remote sources during build or provide the image locally, so that it can be processed into a input format `gatsby-image` expects.
