### ISSUE TITLE
Remark Transformer can not properly parse links with parentheses

### ISSUE THREAD

**Issue by billie66** [gatsbyjs/gatsby#13362]
## Description

Remark Transformer can not properly parse links with parentheses

### Steps to reproduce

```js
const Remark = require('remark');
const html = require('remark-html');

let remark = new Remark()
  .data(`settings`, {
    commonmark: true,
    footnotes: true,
    pedantic: true,
    gfm: true
  })
  .use(html);

remark.process('https://en.wikipedia.org/wiki/RSA_(cryptosystem)', function(
  err,
  file
) {
  if (err) throw err;
  console.log(String(file));
});

```

### Expected result

```
<p><a href="https://en.wikipedia.org/wiki/RSA_(cryptosystem)">https://en.wikipedia.org/wiki/RSA_(cryptosystem)</a></p>
```

### Actual result

```
<p><a href="https://en.wikipedia.org/wiki/RSA_(cryptosystem">https://en.wikipedia.org/wiki/RSA_(cryptosystem</a>)</p>
```

### Environment

```
Node: 10.15.0
Yarn: 1.13.0
```

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by billie66** [comment]
I am sorry for replying late.

I create a code repo based on gatsby-starter-blog to reproduce the problem that I met before. The repo url is https://github.com/billie66/gatsby-demo

If you launch the gatsby-demo in your local machine,  please access the page `http://localhost:8000/hello-world`, then you would see the post content as follows:

<img width="724" alt="Screen Shot 2019-04-18 at 10 17 35 AM" src="https://user-images.githubusercontent.com/102444/56332530-3eb3d280-61c3-11e9-8629-ed6eee3673a9.png">

the problem is the link `https://en.wikipedia.org/wiki/RSA_(cryptosystem`  is wrong, it should be `https://en.wikipedia.org/wiki/RSA_(cryptosystem)`

So, I think gatsby-transformer-remark did not transform the following markdown text correctly,

`https://en.wikipedia.org/wiki/RSA_(cryptosystem)`

it ignored the trailing right parethesis sign.

**Comment by d4rekanguok** [comment]
This is a problem with `remark-parse` & not with Gatsby, I think it's better to open an issue over there: https://github.com/remarkjs/remark/issues

I've just realized you've already known this since in your first comment you reproduced the bug explicitly with `remark`, sorry that you went through the trouble of creating a test gatsby repo!

**Comment by billie66** [comment]
@d4rekanguok 

The two methods can fix the problem. Thanks for your help.
