### ISSUE TITLE
Gatsby-offline blank screen with mp4 video on safari

### ISSUE THREAD

**Issue by Sjarj** [gatsbyjs/gatsby#13371]
when I used gatsby-offline plugin my background video mp4 didn't work on safari mobile and desktop  it send me a blank screen , I'have used gatsby-plugin-remove-serviceworker and my background video mp5 work good ?

**Comment by wardpeet** [comment]
Hi @Sjarj!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a minimal reproduction. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could provide a minimal reproduction and we'll be able to take another look.

Thanks for using Gatsby! 💜

**Comment by Sjarj** [comment]
I had make a new projet for to see the bug together and it work fine now ?? I close the issue
