### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by alexsinfarosa** [gatsbyjs/gatsby#13384]
## Description
Running `gatsby build `gives the following error: SyntaxError: Unexpected end of JSON input
And it points to this function: 
```
readFromLS() {
 return JSON.parse(window.localStorage.getItem('example')) || []
}
```
If I return an empty array in the function, it works and the app builds just fine.

Describe the issue that you're seeing.
The app does not build

### Steps to reproduce
gatsby build

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

### Expected result
The app should build

What should happen?
It does not build. It works in development mode though.

### Actual result

What happened.
SyntaxError: Unexpected end of JSON input

- JSON.parse

  - render-page.js:107597 readFromLS
    /Users/alex/code/irrigation-tool-v2/public/render-page.js:107597:15

  - react-dom-server.node.production.min.js:26 ya
    [irrigation-tool-v2]/[react-dom]/cjs/react-dom-server.node.production.min.js:26:264

  - react-dom-server.node.production.min.js:29 Object.useState
    [irrigation-tool-v2]/[react-dom]/cjs/react-dom-server.node.production.min.js:29:82

  - react.production.min.js:23 useState
    [irrigation-tool-v2]/[react]/cjs/react.production.min.js:23:312

  - render-page.js:107613 AppProvider
    /Users/alex/code/irrigation-tool-v2/public/render-page.js:107613:75

  - react-dom-server.node.production.min.js:33 c
    [irrigation-tool-v2]/[react-dom]/cjs/react-dom-server.node.production.min.js:33:501

  - react-dom-server.node.production.min.js:36 Sa
    [irrigation-tool-v2]/[react-dom]/cjs/react-dom-server.node.production.min.js:36:1

  - react-dom-server.node.production.min.js:41 a.render
    [irrigation-tool-v2]/[react-dom]/cjs/react-dom-server.node.production.min.js:41:467

  - react-dom-server.node.production.min.js:41 a.read
    [irrigation-tool-v2]/[react-dom]/cjs/react-dom-server.node.production.min.js:41:58

  - react-dom-server.node.production.min.js:53 renderToString
    [irrigation-tool-v2]/[react-dom]/cjs/react-dom-server.node.production.min.js:53:83

  - render-page.js:832 Module../.cache/static-entry.js.__webpack_exports__.default
    /Users/alex/code/irrigation-tool-v2/public/render-page.js:832:18

  - worker.js:35 Promise
    [irrigation-tool-v2]/[gatsby]/dist/utils/worker.js:35:36

  - debuggability.js:313 Promise._execute
    [irrigation-tool-v2]/[bluebird]/js/release/debuggability.js:313:9

  - promise.js:483 Promise._resolveFromExecutor
    [irrigation-tool-v2]/[bluebird]/js/release/promise.js:483:18

  - promise.js:79 new Promise
    [irrigation-tool-v2]/[bluebird]/js/release/promise.js:79:10

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.
System:
    OS: macOS 10.14.2
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Shell: 2.6.0 - /usr/local/bin/fish
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Languages:
    Python: 3.6.4 - /Users/alex/anaconda3/bin/python
  Browsers:
    Chrome: 73.0.3683.103
    Firefox: 65.0
    Safari: 12.0.2
  npmPackages:
    gatsby: ^2.3.23 => 2.3.20
    gatsby-image: ^2.0.39 => 2.0.38
    gatsby-plugin-manifest: ^2.0.29 => 2.0.29
    gatsby-plugin-offline: ^2.0.25 => 2.0.25
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12
    gatsby-plugin-react-svg: ^2.1.1 => 2.1.1
    gatsby-plugin-sharp: ^2.0.34 => 2.0.34
    gatsby-plugin-styled-components: ^3.0.7 => 3.0.7
    gatsby-source-filesystem: ^2.0.29 => 2.0.29
    gatsby-transformer-sharp: ^2.1.18 => 2.1.18
  npmGlobalPackages:
    gatsby-cli: 2.5.8

**Comment by wardpeet** [comment]
It's hard to help you without an example project but the reason probably is `window.localstorage`.

Try
```
readFromLS() {
 if (typeof window === 'undefined') {
  return [];
 }

 return JSON.parse(window.localStorage.getItem('example')) || []
}
```

**Comment by alexsinfarosa** [comment]
I had already tried that but It did not work.

**Comment by wardpeet** [comment]
Mind sharing your repo? Or create a reproduction?

**Comment by alexsinfarosa** [comment]
This is the link: https://github.com/alexsinfarosa/irrigation-tool-v2

**Comment by jonniebigodes** [comment]
@alexsinfarosa i've picked up on your issue. I've cloned the repository you provided and i've been testing with it. And i think i have a solution for you.
It looks like the problem is the `browser-monads` package and how you structured your code in `appContext`.
From your code you had the function like this:
```javascript
import React, { createContext, useState, useReducer } from "react"

// utils ------------------------------------------------
import { window } from "browser-monads"
....
function readFromLS() {
  return JSON.parse(window.localStorage.getItem(lsKey)) || []
  // return []
}
```
It should work out of the box, but that won't work, reason being, because that package, that "wrapper" will not expose the localStorage function, in your end, if you mouse over the `localStorage`
 or the `getItem` functions, with your ide of choice, you'll get the famous `any` item as you can see below:

For  `getItem` function:

![getitem](https://user-images.githubusercontent.com/22988955/56391243-05607e80-6226-11e9-8adb-c94577d12a3e.png)

For the `localStorage` API

![local_storage](https://user-images.githubusercontent.com/22988955/56391223-f679cc00-6225-11e9-8576-bdcbe78c9b0e.png)

If you comment out the package in question and transform your `readFromLS` function into something like the following block of code, you'll get access to it like you should.

```javascript

function readFromLS() {
  if (typeof window!=='undefined'){
    const datafromStorage= JSON.parse(window.localStorage.getItem(lsKey))
    if (datafromStorage!==null){
      return datafromStorage
    }
    else{
      return []
    }
  }
  else{
    return []
  }
}
```
Through the access to the native API's and functions, you'll get access to the `getItem` function and the `localStorage` api. As you can see below:
For `locaStorage`
![window_local_storage](https://user-images.githubusercontent.com/22988955/56391594-0cd45780-6227-11e9-9ffe-8d6af7345019.png)

For `getItem` function
![window_local_storage_getitem](https://user-images.githubusercontent.com/22988955/56391602-1067de80-6227-11e9-9d6d-e7de762355c5.png)

After that, if you issue `gatsby build`, you'll get a sucessfull production build as you can see below:

![success_build](https://user-images.githubusercontent.com/22988955/56391930-01356080-6228-11e9-9e8f-7d1e1338aa7a.png)

Feel free to provide feedback so that we can close this issue, or continue to work on it until it's resolved.

**Comment by alexsinfarosa** [comment]
Thank you very much!

**Comment by jonniebigodes** [comment]
@alexsinfarosa no need to thank, just glad i could help out and help you solve your issue.
