### ISSUE TITLE
Deprecated packages in Gatsby

### ISSUE THREAD

**Issue by eclectic-coding** [gatsbyjs/gatsby#13387]
## Description

After installing the gatsby dependencies `npm install` i noticed the following two packages are depreciated: 

```
npm WARN deprecated eslint-plugin-flow-vars@0.5.0: eslint-plugin-flow-vars has been deprecated in favor of eslint-plugin-flowtype@2.4.0 or higher

npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
```
Does `eslint-plugin-flow-vars` need to be updated to `eslint-plugin-flowtype`? 
It appears `coffee-script` is a dependency of a package. 

### Steps to reproduce

1. Clone the gatsby repository
2. Run `npm install`

### Environment

Results of  `gatsby info --clipboard`
```
  System:
    OS: macOS 10.14.4
    CPU: (4) x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 73.0.3683.103
    Firefox: 66.0.3
    Safari: 12.1
  npmGlobalPackages:
    gatsby-cli: 2.5.7
```

**Comment by lannonbr** [comment]
I did confirm these two notices appear. I am not sure if there is any breaking changes for each of these package upgrades, but I can mark this as an issue for now.

**Comment by lannonbr** [comment]
That said, when working with the Gatsby core repo, we use Yarn given it is a monorepo architecture and we use Yarn Workspaces, but it is interesting these deprecations don't appear in yarn.

**Comment by polishedwp** [comment]
@lannonbr That is interesting. According to the npm page, it appears the last update to `eslint-plugin-flow-vars` was three years ago. 

![Screen Shot 2019-04-16 at 10 16 53 AM](https://user-images.githubusercontent.com/13651291/56217276-f49ae780-6030-11e9-9e26-0c61e086b4e1.png)

I wonder if there are other cases of difference like this between npm and yarn? 
Let me know if I can help in anyway.

**Comment by lannonbr** [comment]
Yeah if you are interested into researching the upgrade path to get these two packages to be updated and if there would be anything that we would need to change, we'd love a contribution

**Comment by lannonbr** [comment]
I at least saw that eslint-plugin-flow-vars is a direct dev-dependency for Gatsby. Not quite certain where coffee-script is being used in the repo.

**Comment by polishedwp** [comment]
Looking through the yarn.lock file it appears coffee-script (coffeescript) is a dependency as follows: 
```
markdown-magic
  >markdown-toc 
    >gray-matter
      > coffeescript 
```
I checked the npm page for `[gray-matter](https://www.npmjs.com/package/gray-matter)` and their Dependencies indicate `coffeescript`(no hyphen).  I will investigate today and offer a PR.

**Comment by polishedwp** [comment]
To follow up on `coffee-script`
After some investigation I determined `markdown-toc` was upgraded to `gray-matter@3.1.1` which depends on the deprecated package `coffee-script`.

The new package, `coffeescript@4.0.0` has the breaking change of requiring node v. 4 or greater. Since `gray-matter` has not upgraded to the newer package, Gatsby-core may want to investigate further.

**Comment by lannonbr** [comment]
@polishedwp So given we do not maintain `markdown-toc`, we are going to have to wait it out till they update to use the new version of `gray-matter`

It looks like there's an issue on `markdown-toc` about such: https://github.com/jonschlinkert/markdown-toc/issues/138

That said, the package hasn't been updated since late 2017 and the issue has been open for a month with no comment from the maintainer, so I am unsure on what to on this front other than wait it out. Marked this as an upstream issue to match such.

**Comment by polishedwp** [comment]
Thanks @lannonbr, I didn't notice the outstanding issue, but I totally agree. Thank you for looking at this and giving me the opportunity to assist.
