### ISSUE TITLE
npm pages' repo link should link directly

### ISSUE THREAD

**Issue by tomByrer** [gatsbyjs/gatsby#13416]
Eg: https://www.npmjs.com/package/gatsby-transformer-sqip

`repository github` now points to [the main repo](https://github.com/gatsbyjs/gatsby).  It would be more useful for this to directly link to the actual transformer's page:
https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-transformer-sqip

Might not be a big deal if there was only a dozen sub-packages, but seems there are nearly 50; quite a few to dig though.  & since Gatsby is somewhat geared to non to low-JavaScript people they might not understand Lerna & the need to dig though `/packages/....`.

cheers :)

**Comment by DSchau** [comment]
Hello again!

This is not intentional and we'd certainly welcome a PR improving this. After a quick search, I've found the following plugins need updated:

- gatsby-codemods
- gatsby-plugin-facebook-analytics
- gatsby-plugin-flow
- gatsby-plugin-fullstory
- gatsby-plugin-guess-js
- gatsby-plugin-layout
- gatsby-plugin-subfont
- gatsby-source-wikipedia
- gatsby-transformer-sqip

The process will be something like, checking out those plugin's package.json, and making the following change:

```diff
  "repository": {
    "type": "git",
-   "url": "https://github.com/gatsbyjs/gatsby.git"
+   "url": "https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-codemods"
  },
```

If someone (perhaps yourself!) would be willing to make these changes, we'd certainly love the PR.

**Comment by adarshlilha** [comment]
Would like to take this up, if available

**Comment by tomByrer** [comment]
This could be done manually to fix, but isn't there a CLI to build a new package so it doesn't have manually added?

**Comment by sidharthachatterjee** [comment]
> This could be done manually to fix, but isn't there a CLI to build a new package so it doesn't have manually added?

Not sure if it's worth the effort. @adarshlilha fixed all of these in https://github.com/gatsbyjs/gatsby/pull/13570 🎉
