### ISSUE TITLE
gatsby-plugin-netlify: Missing security headers 

### ISSUE THREAD

**Issue by sidharthachatterjee** [gatsbyjs/gatsby#13459]
Seems like some security headers are missing (as seen in https://securityheaders.com/?q=gatsbyjs.org&followRedirects=on)

Referrer Policy was added recently thanks to @browniebroke 

These are still missing:

- [ ] Content-Security-Policy
- [ ] Feature-Policy

**Comment by DSchau** [comment]
Are there reasonable defaults that we _should_ be using (and making them extensible?) or is this something that should live in userland, e.g. using the `headers` option of the plugin and improving documentation?

I'm not sure off hand, so a little further research would be helpful to answer that question to then drive development efforts.

**Comment by browniebroke** [comment]
CSP is not an easy one, it belongs in user land in my opinion. There is a community plug-in for it, and as you can see the configuration can be complex:
https://www.gatsbyjs.org/packages/gatsby-plugin-csp/

**Comment by wardpeet** [comment]
@sidharthachatterjee, I feel like we should rename this issue. The problem you're raising is valid but it's hard to get right from a gatsby point of view. We can from a .org point of view because we what we load, or at least we should know.

I don't think we can detect `Feature-Policy` correctly due third party scripts. Same goes for csp. We can add integrity attributes to our scripts
