### ISSUE TITLE
Consider adding first-class support for AMP

### ISSUE THREAD

**Issue by hdoro** [gatsbyjs/gatsby#13454]
## Summary

The [AMP project](https://amp.dev) is being pushed hard by Google and is quite aligned with Gatsby's vision of a better web. With the [release of amp-script](https://www.youtube.com/watch?v=sYXkVOiz77I), integrating React with AMP is now possible (and [already being done by Next](https://nextjs.org/blog/next-8-1)), so we're finally in a moment where a **first-class effort** to bring this ecosystem into Gatsby can be **seriously considered**.

### Basic example

We can take inspiration from [Next's implementation](https://nextjs.org/blog/next-8-1#amp-first-pages), although I doubt we'd be able to serve AMP-first pages without getting into hosting redirections 🤔

Being very honest though, **this issue is meant to spark a discussion**, not to provide a specific implementation, as I myself still don't know quite well the ins-and-outs of Gatsby, and am far from comprehending AMP in its entirety.

### Motivation

The AMP Project is not what it used to be, and with Google investing so much energy, time and resources in making this a standard, I believe that, as a community, **we must board this ship** or risk losing relevancy over time... Take PWAs as an example: invented by Google, pushed by Google, and yet it's already made its way into every modern browsers, and even Apple is getting into it. I'd bet AMP'll go the same way, so Gatsby should follow 😄

**Comment by hcavalieri** [comment]
Oh, and @tomoyukikashiro might be interested in this as well, given his effort in creating [html2amp](https://github.com/tomoyukikashiro/html2amp) and [gatsby-plugin-html2amp](https://github.com/tomoyukikashiro/gatsby-plugin-html2amp) 😉

**Comment by DSchau** [comment]
Hello Henrique!

Agreed that it's probably high time to begin some more focused discussion with Amp making some moves that it make it more appealing for usage (e.g. not obscuring the URL!).

A non-exhaustive list of priorities could be created (and probably spawning additional issues), but to start:

What additional work needs to be done outside of gatsby-plugin-html2amp (and do we need to do this in core?)

Answering this question will help us drive prioritization of this feature, and help make it clear what needs to be done to support this feature.

**Comment by hcavalieri** [comment]
Thanks for the quick answer, Dustin 😄

So, as I said before, I'm no expert at anything, but I'll give my 2 cents in what I believe we should take attention to:

1. _IF_ we intend to add support for hydrated react apps in AMP instead of just basic HTML, then we must start a long-term effort together with the `amp-script` / amp for websites team. They are, apparently, [already thinking of how to implement stateful pages](https://youtu.be/rx74ySmQFXs?t=395), which is a step forward, but still far from what we'd need to run full-blown Gatsby sites;
1. For the "hybrid" approach in which we offer the regular _and_ the AMP version, @jafaircl is already doing a great job with `gatsby-plugin-amp`, but I'm unsure if asking for everyone to create a `.amp` version of their pages is enough in terms of developer experience. Sure, not everyone is interested in AMP, but interest rates are going to keep low if refactoring is always needed... That's why `gatsby-plugin-html2amp` feels like a good bet to me, but I'm unsure of how resilient this approach can be... @tomoyukikashiro will be able to give more input on it;
1. [AMP stories](https://amp.dev/about/stories) could be interesting for tons of folks creating websites for clients, myself included, as we'd be able to deliver more value to the business and end users... This doesn't have to go through `core`, though, as it'd just be an implementation effort. I'm thinking in ways of integrating a CMS "story builder" with Gatsby's build time to render pages that use AMP story components and then are transformed into AMP-first via `gatsby-plugin-html2amp`... Not sure how Gatsby SSR reacts to web components, though.

There are other things to which I'd rather not talk about due to lack of expertise (such as Signed Exchanges and integration with PWAs), but overall the more I think about it, the more I realize **this is less of a `core` effort (for now, at least), and more of a community and documentation endeavor!**

By officially supporting [gatsby-plugin-amp](https://www.gatsbyjs.org/packages/gatsby-plugin-amp/) and/or [gatsby-plugin-html2amp](https://www.gatsbyjs.org/packages/gatsby-plugin-html2amp/) - or maybe by creating a hybrid of those behind some option flags -, creating some pages in the documentation, adding AMP support to the Gatsbyjs.org website where relevant and overall talking about it, I believe we'll already be in a good place :)

Sure, Next's `withAmp` API is cool and all, but as Gatsby's philosophy is to attribute most of functionalities to plugins, a rock-solid `gatsby-amp`, with great documentation, would do the trick 😉

**Comment by tomoyukikashiro** [comment]
@hcavalieri @DSchau 

Thank you for mentioned my projects `gatsby-plugin-html2amp` and `html2amp`. 😄 
I am so interested in supporting AMP by Gatsby 👍 😄 

Originally `html2amp` is a simple module to convert `Standard HTML tags` to AMP tags so that most of `AMP` unique tags which can not be replaced with standard HTML tags are not support now like `<amp-story>`, `<amp-sidebar>` etc.... the module will just convert....

- `<img>` to `<amp-img>`
- `<iframe>` to `<amp-iframe>`

etc...

So I am not sure about that module can fit our target.
Let me check [Next.js AMP Support](https://github.com/zeit/next.js#amp-support) ( I've not checked their implementation yet 😅 .

**Comment by KyleAMathews** [comment]
What exactly is Next doing? It seems like it's just a toggle switch that turns on/off a React Context variable? https://github.com/zeit/next.js/blob/e5111745b55a618caa58b14f73f1451e0319b4c6/packages/next-server/lib/head.tsx

**Comment by jafaircl** [comment]
@hcavalieri the `gatsby-plugin-amp` plugin doesn’t *need* a .amp version of the template. If it finds a matching page, it’ll try to convert it to an AMP page either way. Most simple gatsby sites would probably be fine. But, any dynamic content or functionality would break during this process. That’s why there’s the option to create an AMP-specific template. It’s not strictly necessary, though.

Let me know if there’s anything I can do to help with this effort.

**Comment by hcavalieri** [comment]
@KyleAMathews it seems that their implementation is actually quite basic... You're right, they're simply toggling an AMP context and then it's up to you to do the appropriate changes for it to work properly.

Based on a big commit they did on ["Update to use withAmp"](https://github.com/zeit/next-site/commit/c95a37b8a91161a7e152f4935d3850fd13d7c302), developers have to manually check the `useAmp()` hook from `next/amp` in order to decide on using `amp-img` or `img`, `a` or `Link`, etc., like shown in [their example](https://nextjs.org/blog/next-8-1#distinguishing-amp-rendering-in-components). They also have automatic validation through [amphtml-validator](https://www.npmjs.com/package/amphtml-validator), but that's it.


From what

**Comment by hcavalieri** [comment]
@KyleAMathews it seems that their implementation is actually quite basic... You're right, they're simply toggling an AMP context and then it's up to you to do the appropriate changes for it to work properly.

Based on a big commit they did on ["Update to use withAmp"](https://github.com/zeit/next-site/commit/c95a37b8a91161a7e152f4935d3850fd13d7c302), developers have to manually check the useAmp() hook from next/amp in order to decide on using amp-img or img, a or Link, etc., like shown in [their example in the blog post](https://nextjs.org/blog/next-8-1#distinguishing-amp-rendering-in-components). They also have automatic validation through [amphtml-validator](https://www.npmjs.com/package/amphtml-validator), but that's it.

From what @jafaircl said, Gatsby might even be better off, than, considering we can always rely on build time to do some automatic transformations:

> @hcavalieri the `gatsby-plugin-amp` plugin doesn’t _need_ a .amp version of the template.

--------

So, again, Next took the opportunity to market themselves by surfing Google's AMP wave with Next 8.1, and this is not far from our reach! I'll be testing `gatsby-plugin-amp` in the following weeks to see what can be improved on, but in the meantime we could:

- Author an AMP page in the docs;
- Maybe tweak the `gatsby-plugin-amp`'s documentation to make it clear that AMP pages can be generated automagically without different templates;
- Get @tomoyukikashiro onboard to join efforts in creating a single, close-to-perfection plugin;
- Also get some inputs from @c0b41 and understand why he forked his [own version of plugin-amp](https://www.npmjs.com/package/@c0b41/gatsby-plugin-amp);
- Test and test and test before transforming `gatsby-plugin-amp` into an official plugin. On this:
  - Would you be willing to do this transition, @jafaircl ?
  - Is there any extra work we need to do about `Link` elements?
  - Can we alert devs when a specific to-be-amped-page relies too heavily on React, so then they can find ways of either solving this or removing the page from the AMP config?
- Do some marketing effort to increase awareness on AMP + Gatsby and get closer to our goal of helping to shape a better, faster and more accessible web 😉

Does this all make sense? Can we count on the Gatsby core team to help when needed? @lindaleebumblebee is this relevant to marketing?

**Comment by KyleAMathews** [comment]
@hcavalieri sounds excellent! Would be great to add "official" support as well for AMP. Perhaps we can move `gatsby-plugin-amp` into this repo for extra love?

**Comment by jafaircl** [comment]
@hcavalieri I’d be happy to help and I’m fine with moving the plugin in to the main repo. I’ll confess I’m not super confident I know the best way to do that, though. 

While you’re testing just remember that you only need the *page* to exist for the plugin to find and convert it, not the template. We could probably integrate the `amphtml-validator` package to check if a page passes and throw a warning at build time.

**Comment by c0b41** [comment]
@hcavalieri I'm just testing my own fork with new stuff and sent them `gatsby-plugin-amp` repo today.

**Comment by nyedidikeke** [comment]
Quite fascinating 😀 AMP-first support will be awesome. 💯 💯 💯 
Any roadmap or milestone?

**Comment by tomoyukikashiro** [comment]
Can I handle this issue 😄 ? ( I'm interested in it yet )

I'll share following things later...

- What is the requirement for AMP actually to align the viewpoint
- To achieve that what `Next.js` is doing
- How to implement by Gatsby using existing APIs

**Comment by PolGuixe** [comment]
Is there a current way forward?

**Comment by tomoyukikashiro** [comment]
To align the viewpoint I'll put note for AMP and Next.js implementation 😄 
Also I'll put blueprint / idea that how to implementation AMP in Gatsby as First class support later 🤔 

Feel free ask me about this 👌 

# Requirements / Optional for AMP

## HTML

Need these tags in head.

- `<!doctype html>`
- `<html amp>`
- `<meta charset="utf-8" />`
- `<meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">`
- `<link rel="canonical" href="${ORIGINAL_URL}">` in AMP page
- `<link rel="amphtml" href="${AMP_URL}">` in original page

## CSS

- Need [AMP CSS boilerplate](https://amp.dev/documentation/guides-and-tutorials/learn/spec/amp-boilerplate?format=websites)
- All custom CSS should be defined in `<style amp-custom><style/>` as inline CSS
- `!imporant` isn't allowed

## Javascript

- Need runtime script `<script async src="https://cdn.ampproject.org/v0.js"></script>`
- All scripts isn't allowed *1
- Some HTML tags should be replaced with AMP tags such as `<iframe>`, `<img>`, `<video>` *2

> *1 There is <amp-script> component that allow you to use custom Javascript.
> But it is still `experimental`.
> https://amp.dev/documentation/components/amp-script?format=websites 

> *2 Check more detail in [amp.dev](https://amp.dev/documentation/guides-and-tutorials/learn/spec/amphtml?format=websites#html-tags)

## Optional

- Schema.org definition in the head

> It isn’t a strict requirement for AMP, but it is a requirement to get your content distributed in certain places (for example, in the Google Search top stories carousel).
> [Optional metadata in amp.dev](https://amp.dev/documentation/guides-and-tutorials/start/create/basic_markup?format=websites#optional-metadata)


# Page Structure Patterns

## AMP First and Paired AMP
AMP team mentioned officially in [AMP conf 2019](https://youtu.be/rx74ySmQFXs?t=541).

- AMP First : The page is built using AMP only
- Paired AMP : The page has Non-AMP page and AMP page

Next.js calls `AMP First` `AMP-only` and `Paired AMP` `Hybrid`. [Next.js document](https://nextjs.org/docs#amp-page-modes)

## Optimized AMP

AMP page can be cached in Google AMP CDN then served.
But we can make it faster by using [AMP Optimizer](https://www.npmjs.com/package/amp-toolbox-optimizer).

Optimizer will do...

- Server side rendering AMP Layout
- Removing the AMP boilerplate

and so on. 

please check repository for more detail.


One thing you need to be aware that optimized AMP page is `invalid as AMP`. This means the page won't be cached Google AMP CDN.
So that Next.js will make both pages (optimized and non optimized) for `AMP First` structure.

For example when you create `pages/about.js` using Next.js with AMP First structure, Next will generate

- /page/about/index.html (optimized AMP)
- /page/about.amp/index.html (non optimized AMP)


There is one good new in AMP Conf @tokyo this year, AMP team mentioned that...


> Optimized AMP page will be recognized as valid AMP in few months.

https://youtu.be/UDqTVMQeucQ

So actually no need to create both pages (optimized AMP and non optimized AMP) in AMP Frist structure near future.

# Next.js implementation


As everyone mentioned above...
Next.js just a toggle switch that turns on/off a React Context variable then generate AMP / optimized AMP / non AMP (regular HTML) based on that value in build tasks.

**Comment by jcayzac** [comment]
While I'm looking forward to better AMP support in Gatsby, I though I'd just remind everybody here that AMP pages are not meant to be served from arbitrary servers "as-is", as becomes obvious when you benchmark them with e.g. lighthouse. They're made for loading quick from Google search results on mobile, that's all. So "AMP first" seems a bit ill-thought and a recipe for making very slow websites.

**Comment by PolGuixe** [comment]
@jcayzac how they should be served?

**Comment by jafaircl** [comment]
@PolGuixe you shouldn’t be directing your users to AMP pages by default. You should be directing users to your Gatsby page which would have a `rel=amphtml` tag in the head which would point to an AMP version of the page. When Google/Twitter/whoever crawls your site, they’ll find and cache your amp version to serve to their users.

**Comment by jcayzac** [comment]
@PolGuixe: @jafaircl answered perfectly.

**Comment by jcayzac** [comment]
The reason why AMP is fast when served from google search on mobile is that google pushes those pages’ markup, preprocessed, to a google cache node close to your location, renders the page inside a container of the google search website, and the page never has to actually load all those AMP runtime javascript files because they’ve already been loaded for it by the google search page.

**Comment by KyleAMathews** [comment]
Not stale

**Comment by tomoyukikashiro** [comment]
@KyleAMathews 

I'm sorry for late reply....
I have been thinking about `How do I define that the page is AMP in Gatsby` 🤔 
I thought that using `gatsby-transformer-javascript-frontmatter`  is good for Gatsby.

```js
// src/page/index.js
import React from "react"

const MyComponent = () => (<div></div>);

exports.frontmatter = {
  title: "Choropleth on d3v4",
  amp: true  // define this page is AMP.
}

export default MyComponent
```

then I wanted to pass the flag to react context via `wrapRootElement` API.
But I do'nt know how to get it....

```js
// gatsby-ssr.js and gatsby-browser.js

export const AmpContext = React.createContext({})

export const wrapRootElement = ({ element }) => {
  const isAmp = /* How do I query `frontmatter` of MyComponent  */
  return (
    <AmpContext.Provider value={isAmp}>
      {element}
     </AmpContext.Provider>
  )
}
```

and also I need to use the query in `onRenderBody` and `onPreRenderHTML` API to modify html attribute and head tags.

```js
// gatsby-ssr.js
export const onRenderBody = ({setHtmlAttributes}) => {
  const isAmp = /* How do I query `frontmatter` of MyComponent  */
  if (isAmp) {
    setHtmlAttributes({amp: true})
  }
}
```

Do you have any idea to use `graphquery` in that context ??

**Comment by lmuntaner** [comment]
This issue has been stale for a while.

We are considering using Gatsby for a project but we need AMP support. After my first test it seems that `gatsby-plugin-amp` is doing the trick.

However, I would like to know whether there has been some updates regarding AMPs an Gatsby.

@tomoyukikashiro did you stop working on this?

Thanks!

**Comment by jsbrain** [comment]
I am also very interested in that and could try to help with implementation!

**Comment by wardpeet** [comment]
We don't have anything on our roadmap to support Amp out of the box. Can I ask what's the biggest reason why you would want amp support?

**Comment by jsbrain** [comment]
Amp is a highly relevant feature in terms of SEO optimization which could lead to advantage over competitors to rank better in SERP. Even that static generated pages are already blazing fast in terms of SEO this can make a difference.

**Comment by Eyas** [comment]
There's also mukul-rathi/gatsby-plugin-google-amp, by @mukul-rathi. it's description indicates that the original plugin is not being maintained, as of recently.

Per @KyleAMathews suggestion to merge a package into the mainline, would that package be a better fit?

Seems like putting something here would be the first step of getting momentum.

**Comment by Eyas** [comment]
> Do you have any idea to use `graphquery` in that context ??

@tomoyukikashiro maybe just use the path? e.g. a configurable `/amp/` in the suffix?

**Comment by Fziliotti** [comment]
I'm interested in this and could try to help with the implementation, but I haven't tested the gatsby-plugin-amp, does it do this job?

**Comment by Eyas** [comment]
I have a branch at  https://github.com/Eyas/gatsby-plugin-google-amp/tree/local-fixes that I'm using to play around with getting something viable.

Short answer is, not out of the box. I tried a lot to go by what @jafaircl said, but the issue is that a lot of the core pieces around Gatsby Image, etc. need to be changed. So I have something that works for me, but is done through a lot of hacky dom manipulation.

I think the gatsby-plugin-amp approach, plus some sense of a "global amp context" that can provide AMP outputs of a small number of core components (e.g. Gatsby Image), might be the ideal approach.

**Comment by Eyas** [comment]
gatsby-plugin-amp2html might do a better job translating some elements, but it still breaks layouts considerably with GatsbyImage for example. 

`<amp-img>` is really what gatsby-image is trying to be, which is why I think it's easier to emit the right thing from the component level in GatsbyImage, rather than trying to reverse extrapolate from the HTML, which is how both plugins do this.

**Comment by jsbrain** [comment]
@Eyas thanks for sharing your approach I will check it out in the near future. I find your arguments are pretty solid why those plugins don't really do the job in the right way. As Gatsby gets more and more popular and more people use it in the business context (as I) gatsby should really support this in the first place as it, as said earlier, can make a big difference in terms of SEO ranking and whatnot.

@Eyas you obviously have dealt with the problem quite a bit. Would you consider collaborating on a pull request on this? I would be down as well if I find the time!

**Comment by pmarxbraun** [comment]
Hiya,

Any news about this concern ?
None of the above mentionned plugin work with MDX files. 

Is there a way to modify default **html.js** on certain files ? because this is basically the missing **<html amp>** tag that is making impossible to turn page into AMP. If we can achieve that building page layout according to AMP guidelines will be fairly easy.

**Comment by KyleAMathews** [comment]
@pmarxbraun check out this doc for creating a custom html.js https://www.gatsbyjs.org/docs/custom-html/

You can check what path is being passed in to vary the html tag.

**Comment by Eyas** [comment]
@pmarxbraun I'm using MDX for my site just fine. I had to:

1. Clone one of the plugins and make some local changes (I mentioned it in a previous commit)

2. Do my own helmet header for amp link

3. Use custom queries for Sitemap and RSS Feed to exclude amp pages.

**Comment by pmarxbraun** [comment]
@Eyas Hi, tried all plugins. My `html tag`does not even contain amp :-/ 

Then tried putting ` <html lang="fr" amp />` in my Helmet conf AMP layout and then in `html.js`

`export default function HTML(props) {
  return (
    {props.htmlAttributes.amp ? <html amp {...props.htmlAttributes} : <html {...props.htmlAttributes}>}
      <head>
        <meta charSet="utf-8" />
        <meta httpEquiv="x-ua-compatible" content="ie=edge" />
       ...`

but it throws err. Maybe `props.htmlAttributes.amp`that I'm not doing well ?

**Comment by nyedidikeke** [comment]
> Then tried putting `<html lang="fr" amp />` in my Helmet conf AMP layout and then in `html.js`

@pmarxbraun : you may want to add the mandatory AMP attribute to the `<html>` tag of your [custom html](https://www.gatsbyjs.org/docs/custom-html/) at `/src/html.js` as below (with your language HTML attribute set to French);

```html
<html lang="fr" amp="" {...props.htmlAttributes}>
````
Shared a recent post on same intent on [Stack Overflow]( https://stackoverflow.com/a/61303078/6381711).

**Comment by pmarxbraun** [comment]
@nyedidikeke hi ! yes but all my pages will have this amp attribute 😟. How can I specify it only for my AMP pages ?

**Comment by nyedidikeke** [comment]
> How can I specify it only for my AMP pages ?

@pmarxbraun You could create an AMP component similar to the SEO component of the [Gatsby Starter Default](https://github.com/gatsbyjs/gatsby-starter-default/blob/master/src/components/seo.js) template by making use of [Helmet](https://github.com/nfl/react-helmet) and [PropTypes](https://github.com/facebook/prop-types), then import it (your AMP component) only in specific pages as you require. Below, an illustration below;

```js
// src/components/amp.js
import React from "react"
import PropTypes from "prop-types"
import Helmet from "react-helmet"

function InitialiseAmpHtmlAttribute({ amp }) {
  return (
    <Helmet
      htmlAttributes={{
        amp,
      }}
    />
  )
}

InitialiseAmpHtmlAttribute.defaultProps = {
  amp: ``,
}

InitialiseAmpHtmlAttribute.propTypes = {
  amp: PropTypes.string.isRequired,
}

export default InitialiseAmpHtmlAttribute
```

```js
// src/pages/my-amp-page.js
import React from "react"
import AMP from "../components/amp"

const MyAmpPage = () => {
  return (
    <>
      <AMP />
      <h1>Sample page with mandatory AMP HTML attribute</h1>
      <p>Using Gatsby with AMP HTML.</p>
    </>
  )
}

export default MyAmpPage
```

**Comment by pmarxbraun** [comment]
@nyedidikeke Thanks for your help. 

I can add amp attribute to my AMP pages now but the required  [boilerplate code](https://amp.dev/documentation/guides-and-tutorials/learn/spec/amp-boilerplate/?format=websites) is causing this issue [TypeError: tag[primaryAttributeKey].toLowerCase is not a function](https://github.com/nfl/react-helmet/issues/448#issuecomment-570815636)

Tried adding as stipulated

```
exports.onCreateWebpackConfig = ({
  stage,
  rules,
  loaders,
  plugins,
  actions,
}) => {
  actions.setWebpackConfig({
    module: {
      rules: [
        {
          use: [
            {
              loader: "file-loader",
              options: {
                esModule: false,
              },
            },
          ],
        },
      ],
    },
  })
}
```

with no luck. It thows me :

```
 ERROR 

There was an error compiling the html.js component for the development server.

See our docs page on debugging HTML builds for help https://gatsby.dev/debug-html TypeError: htmlComponentRenderer.default is not a function

  TypeError: htmlComponentRenderer.default is not a function
```
Any thoughts ?

**Comment by dandv** [comment]
> There's also mukul-rathi/gatsby-plugin-google-amp, by @mukul-rathi. it's description indicates that the original plugin is not being maintained, as of recently.

@mukul-rathi's plugin hasn't been maintained either, and it has no Issues tab on its GitHub page.

BTW, any chance we could clean up the irrelevant "stale" bot messages from this thread, and keep only the last one? Previous ones don't really add to the conversation. Thanks.

**Comment by Eyas** [comment]
My take here, after having worked on enabling AMP on my own blog for a while:

- The right solution is not straightforward and involves any plugin generating arbitrary HTML/client-side JS to be AMP aware.
- There's some "core" work for an AMP plugin to do, including AMP linting, and potentially some common work like inserting required scripts, etc. but, it seems like the other ting going on is that an AMP plugin should be inserting an "AMP context" for other plugins to use, e.g.
  - Gatsby Images should be generating totally different HTML in AMP mode.
  - Videos (e.g. the remark youtube plugin, etc.) should generate different HTML
  - Sharing button plugins should generate different HTML

The ideal AMP plugin wouldn't know about these plugins and have fixes for them directly (as I've had to do in my own branch), but instead the plugin itself would be doing this work.

Is there a mechanism to do this?

**Comment by ku8ar** [comment]
@Eyas It is even possible without neural network? I tried a lot of AMP plugins and they each created invalid code.
I think the only way is to add some flag to Gatsby, which will inject "isAmp = true" context into plugins, and AMP support will depend on the plugin's maintainers.

**Comment by Eyas** [comment]
> I think the only way is to add some flag to Gatsby, which will inject "isAmp = true" context into plugins, and AMP support will depend on the plugin's maintainers.

Yes I completely agree, this is exactly what I meant in my last comment
