### ISSUE TITLE
[gatsby-source-wordpress] Sidebar widget content endpoints not accessible from graphql

### ISSUE THREAD

**Issue by joeldbirch** [gatsbyjs/gatsby#13541]
The issue is well described in this old issue https://github.com/gatsbyjs/gatsby/issues/5239 

I can get the index for the sidebars, which is the `/wp-json/wp-rest-api-sidebars/v1/sidebars` endpoint ([the results of which can be seen in this screenshot](https://dl.dropboxusercontent.com/s/1gb87kkzxpj7ig8/sidebars.png?dl=0
)), but that only lists the sidebars registered in the WordPress theme. The actual widget content used in each sidebar (ie, the important stuff) is not accessible from graphql, although the [WP Rest API Sidebars](https://es-mx.wordpress.org/plugins/wp-rest-api-sidebars/) endpoints for them do work, ie: `/wp-json/wp-rest-api-sidebars/v1/sidebars/{id}`.

We really need to be able to access the widgets the WordPress site owner adds in order to complete WP migrations to Gatsby.

**Comment by pieh** [comment]
This is because wordpress plugins doesn't access details routes and rely on data being available in "index" routes.

Changing that would mean that fetching data for 200 posts would need to make 200 requests instead of 2. We have special cases for some plugins (i.e. one for fetching menu data) that fetch detailed pages. But in this case I think better solution would be to created alternative wordpress plugin (probably based on https://wordpress.org/plugins/wp-rest-api-sidebars/ ) which would have needed data in `/wp-json/<plugin-namespace>/v1/sidebars` without the need to make extra requests
