### ISSUE TITLE
updating dependencies project 

### ISSUE THREAD

**Issue by polishedwp** [gatsbyjs/gatsby#13544]
## Summary
Last week there were several issues released "[examples]: update ... dependencies in example project." All of these `good-first-issues` have been completed. 

When you browse the `examples/using-*` directories, there are a lot of example which are out of date. For instance, most of them still use react@16.4.0, which does not include useStaticQuery. 

Are these additional `examples` areas in which you need help?

**Comment by pieh** [comment]
The issues were posted because those examples were using outdated `gatsby` related packages (not on latest major version). Which is most of what we care about in our examples.

Our examples don't have lock files - so even if they specify `react@^16.4.0` - they will install latest react (at least until react@17 comes out). Examples also don't need to use `useStaticQuery` instead of `<StaticQuery>` - both are correct.

It's ok to update them when it makes sense and meaningfully improve them, but right now we don't think any of them _need_ it
