### ISSUE TITLE
Is it possible to externalize gatsby logic (tmp, configs, plugins, components) as an NPM module ?

### ISSUE THREAD

**Issue by gael-boyenval** [gatsbyjs/gatsby#13571]
## Summary

I would like to pack all gatsby logic (components, templates, configs, custom plugins) into an external dependency to reuse logic, and have it imported as a dependency in multiple projects.

The idea being to share a common build across multiple projects with the same architecture.
Those projects, would only contain pages (markdown files in my case)

Could you point me toward a possible solution ?

Generally speaking, it seems to me that Gatsby is relying on a very rigid directory structure, and it would make gatsby a far more flexible tool to be able to set custom path to stuffs like : 

- plugins
- static
- src dir
- templates dir
- configs files
- UI components
- etc...

It would enable Gatsby to by highly modularized and to reuse/share business logic from a project to another.

**Comment by pieh** [comment]
We agree! :)

That's why we work on "themes" support which will do what you describe. Right now they are marked as experimental as we iterate on them quite heavily and we might introduce some breaking changes, but those are already usable.

Here's couple of resources that are available:
 - https://www.gatsbyjs.org/docs/themes/
 - https://www.gatsbyjs.org/blog/tags/themes/

The brief overview is that you would package Gatsby site as npm package - this mostly mean, so you could reuse configuration (plugins and their options), components / src/pages without duplicating this inside all similar sites.

Here's example of site that uses themes: https://github.com/gatsbyjs/gatsby/tree/master/themes/gatsby-starter-theme-blog-mdx - if you check config and files in there - you can notice that it only defines theme in configuration and itself doesn't have any components/pages as those are handled by theme

**Comment by gael-boyenval** [comment]
how can I have missed that ? 👍
Thank's I'll look into it !
