### ISSUE TITLE
Docs: some packages show up without Gatsby site chrome

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#13638]
## Description

Some package listings open on the .org site without the Gatsby site navigation and gloabl markup. We should determine why!

### Steps to reproduce

- Visit this page: https://www.gatsbyjs.org/packages/gatsby-dev-cli/
- Observe how the style differs from another package: https://www.gatsbyjs.org/packages/gatsby-plugin-sharp/?=

![gatsby-dev-cli](https://user-images.githubusercontent.com/1045233/56774808-11de5d00-6779-11e9-95b0-3db6471180c1.png)

![gatsby-plugin-sharp](https://user-images.githubusercontent.com/1045233/56774816-173ba780-6779-11e9-87c8-14b8106da547.png)

### Expected result

Packages should have a consistent look and feel.

### Actual result

Certain packages are treated differently, and it is unclear why.

**Comment by lannonbr** [comment]
Linking another issue as it is related to this: #13457

**Comment by paschalidi** [comment]
@marcysutton I am trying to start working on this, it seems to be that somehow when      
```
       <InstantSearch
          apiKey="ae43b69014c017e05950a1cd4273f404"
          appId="OFCNCOG2CU"
          indexName="npm-search"
          searchState={this.state.searchState}
          onSearchStateChange={this.onSearchStateChange}
        >
          <Search
            pathname={this.props.location.pathname}
            query={this.state.searchState.query}
          />
        </InstantSearch>
```
is being defined https://github.com/gatsbyjs/gatsby/blob/master/www/src/components/plugin-searchbar-body.js#L486 

Some list is being parsed to the component that is being determined from `appId` and `apiKey`. Is there a way that we have access into that so that we can list all the plugins and therefore make all the plugins to be visible on search?

**Comment by paschalidi** [comment]
@KyleAMathews 👋
Sorry to ask since you are not part of this discussion at the moment but you might have an idea.
Can you please have a look on the question above https://github.com/gatsbyjs/gatsby/issues/13638#issuecomment-487386898? 

☮️
