### ISSUE TITLE
Support symlinked node_modules for gatsby-theme package

### ISSUE THREAD

**Issue by adrw** [gatsbyjs/gatsby#13707]
## Description

I'm working with the new Gatsby-Themes API and Gatsby won't build my child theme if the parent theme is in a symlinked directory in the child's node_modules. This is the standard repo setup for a [Rush monorepo](https://rushjs.io/) and allows you to test against local changes very easily. Could symlinked node_modules be supported? Other JS projects I've worked on which rely on the default node_modules resolution algorithms support this functionality.

### Steps to reproduce

Parent Theme: `gatsby-theme-parent`
Child Theme: `gatsby-theme-child`

Child Package.json
```JSON
{
"name": "gatsby-theme-child",
"dependencies": {
"gatsby-theme-parent": "0.0.1",
"react": "16.8.0",
"react-dom": "16.8.0",
}}
```

Child Gatsby Config
```Javascript
module.exports = {
  __experimentalThemes: [
    {
      resolve: "gatsby-theme-parent",
      options: {}
    }
  ],
}
```

Failing Directory Structure
```
/test-project
   /gatsby-theme-parent
      /lib
   /gatsby-theme-child
      /node_modules
         gatsby-theme-parent (symlink -> /test-project/gatsby-theme-parent/)
```

### Expected result

Gatsby should build even if the parent theme in node_modules is symlinked.

### Actual result

```
error Cannot find module 'gatsby-theme-parent'


  Error: Cannot find module 'gatsby-theme-parent'
```

**Comment by freiksenet** [comment]
Thank you for the report! CC-ing our theme experts @ChristopherBiscardi.

**Comment by ChristopherBiscardi** [comment]
Hey @adrw, Gatsby supports symlinks, as evidenced by working projects that use yarn workspaces (our suggested approach) and lerna with themes. If the directory structure you've provided is fully accurate, then you're missing an `index.js` file (or a `main` field in `package.json`) in the parent theme, so when `require`d node can't find it. This is how the default node_modules resolution works (it requires a default of `index.js` or a specified `main` field).

If this is not your issue, please provide a minimal example repo with instructions detailing how to run it and I'm happy to look into it. Since themes work successfully with yarn workspaces and lerna, I'm inclined to believe this is an issue with either Rush (which I've never used) or a misconfiguration.

**Comment by adrw** [comment]
@ChristopherBiscardi Thanks for clarifying current Gatsby capabilities. I copied the code from jlengstorf/livestream-gatsby-themes into a fresh Rush monorepo so that you can play around and better understand the problem. Check it out here: https://github.com/adrw/gatsby-13707

Happy to help with resolving it if it can be pinpointed where the problem is in the stack. Huge fan of the work you and team are doing with Gatsby! Thanks

**Comment by wodenx** [comment]
@ChristopherBiscardi  I am having a similar issue when using `lerna bootstrap --hoist`.  Here is a simple example: https://github.com/wodenx/gatsby-theme-issue.  Run `lerna bootstrap` and then `gatsby develop` and it is fine.  Run `lerna bootstrap --hoist` and `gatsby develop` and you get the following:
```
  Error: Cannot find module 'gatsby-theme-bodiless'
```

**Comment by wodenx** [comment]
Workarounds for my use case:

- `lerna bootstrap --hoist --nohoist=gatsby`
- `ln -s ./packages/site/node_modules/gatsby_theme_bodiless ./node_modules/gatsby_theme_bodiless`

So it seems gatsby is looking for the theme relative to the node_modules directory where gatsby itself is installed.  This seems to be a peculiar lerna edge-case, where an external dependency is somehow dependent on a package in the monorepo.  Hope this is helpful information.

**Comment by ChristopherBiscardi** [comment]
@adrw could you add run/install instructions there as well? I'm unfamiliar with rush and how it works.

**Comment by adrw** [comment]
@ChristopherBiscardi Added them to the repo!

**Comment by adrw** [comment]
@ChristopherBiscardi Any thoughts?

**Comment by ChristopherBiscardi** [comment]
@adrw This is, as far as I can tell after doing some research, a long-standing problematic area with respect to pnpm, which rush seems to use under the hood that breaks `require.resolve` in this case.

Since Gatsby is using `require.resolve` to find the module, which is exactly node's resolution algorithm, I'm going to close this since pnpm/rush should support this. To clarify, when using rush/pnpm `require.resolve('gatsby-theme-child')` breaks.
