### ISSUE TITLE
Gatsby SVGs

### ISSUE THREAD

**Issue by ernestosotelo** [gatsbyjs/gatsby#13724]
**Edit:** This issue has been pointed out here: https://github.com/jhamlet/svg-react-loader/issues/102 which seems to be affecting **gatsby-plugin-react-svg**.

**Comment by jonniebigodes** [comment]
@ernestosotelo if you don't mind follow [this](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/) and share the link so that we can take a look at it and track down the actual problem  and work on a solution for your issue?

**Comment by ernestosotelo** [comment]
@jonniebigodes I think I'm going to close this issue and troubleshoot more. I inserted the SVG components inside the Header component initially, and now I inserted the components into the IndexPage component to do additional testing and it rendered in an awful way. It's much more complicated than I thought - or I am missing something regarding using SVG components in Gatsby...

**Comment by jonniebigodes** [comment]
@ernestosotelo it's entirely up to you, if you want, share a repository emulating the issue you're experiencing so that it can be looked at. Otherwise feel free to close it and come back afterwards and reopen it when you're willing.

**Comment by Strangehill** [comment]
I'm having this issue. The solution I can't get to work, as I gather from the [svg-react-loader docs](https://github.com/jhamlet/svg-react-loader#query-params), and the [gatsby-plugin-react-svg docs](https://github.com/jacobmischka/gatsby-plugin-react-svg), is to use query parameter `classIdPrefix` in gatsby-config to namespace class names and id names. I tried this, as follows:
```
      resolve: "gatsby-plugin-react-svg",
      options: {
        rule: {
          include: /\.inline\.svg$/,
          options: {
            classIdPrefix: "[name]-[hash:8]__"
          }
        }
      }
```
but instead of resulting turning class/id names such as `.st4` into `.logo-a91$s@Fq__st4` which is what I expected, the resulting name was `.[name]-[hash:8]__st4`
I hope to have a reproduction ready soon.

**Comment by LekoArts** [comment]
We're not maintaining this plugin here, please open an issue on their issue tracker. Thanks!
