### ISSUE TITLE
Set plugin configuration from graphql query

### ISSUE THREAD

**Issue by Zyclotrop-j** [gatsbyjs/gatsby#13763]
### My use-case:
- I want to set the manifest's values based on values I have in a database
- I want to process the icons (public path to picture (S3-bucket) stored in the database) with 'gatsby-transformer-sharp' / 'gatsby-plugin-sharp' and use these in the manifest

### More abstract use-case:
Programmatic injection of plugin options from 'gatsby-node.js', where the injection-code has access to gatsby-apis / gatsby's 'data-layer' (graphgl)
Alternatively, expose data-layer/apis in gatsby-config and allow returning a promise

## Relevant information

I'm trying to get information about a website, I have in a db (exposing graphql-interface) into gatsby's plugin-options.

Different ways of setting plugin-options, I'm aware of:
gatsby-config
```
{
      resolve: 'gatsby-plugin-manifest',
      options: {
        name: "some hardcoded value", // hardcoded
        short_name: config.siteTitleAlt,  // from shared file
        description: process.env.description, // from env-var
        start_url: ??? get from db ???, // <- This is my question
        .....
      },
    }
```

How to query data (working):
gatsby-node.js
```
graphql(`{
    data {
      website {
        name,
        short_name,
        description,
        start_url,
        ...
      }
    }
  }`)
```

### https://github.com/gatsbyjs/gatsby/issues/12919
Discusses the same, but closed with the argument to use environment variables. Environment variable won't work in my use-case, as there is no way in gatsby to query the data and then write it into env-variables which will be picked up in the config.
Using the gatsby-graphql-query is mandatory for plugins like sharp work in there - e.g. for setting up the manifest's fav-icon (create different renditions).

### https://github.com/gatsbyjs/gatsby/issues/13050#issuecomment-479141305
Similar approach

### https://github.com/gatsbyjs/gatsby/issues/12227
Trying to solve the issue with themes
But themes just overwrite the config from configs "further up" in the project - they don't solve the issue of querying.

**Any help is highly appreciated!!!**

**Comment by DSchau** [comment]
I think this issue is rather more focused with setting dynamic values for a plugin, which is a reasonable use case. I'm less convinced of using Gatsby's internal APIs in this pre-config phase because that seems to be more of a niche use case? (and would also be fairly challenging to implement in core, e.g. plugins _create_ the schema so how would we know which plugins are safe to use and which need further configuration we need to wait for?)

Just so I understand, this value you're querying for is available in a database? And also is available to Gatsby's GraphQL layer? I'll be a broken record here--but if you can query it with Gatsby's GraphQL layer, you can also make this available dynamically as an environment variable by querying the database directly, which is probably what I'd recommend here.

**Comment by Zyclotrop-j** [comment]
`which need further configuration we need to wait for` -> maybe the second idea I listed `allow returning a promise [in gatsby-config]` would solve this.

Yes, the value is available in a database. The solution you suggest, `querying the database directly` is the workaround I'm currently using. This approach duplicates the entire "query"-setup though (like schemas, ...) - I'd love to reuse the existing, amazing gatsby-setup for this :)

**Comment by Zyclotrop-j** [comment]
Has there been any idea how to approach this problem?
