### ISSUE TITLE
Layout SSR based on the React.Context value

### ISSUE THREAD

**Issue by teimurjan** [gatsbyjs/gatsby#13793]
## Summary

I need to have the ability to control the layout in my pages component. I implemented it using React.Context API.
Everything works fine at the development stage. But after building the static site, if I go to the page with the hidden header, I see it for some milliseconds and then it's disappeared. 

## Relevant information

For example, I want to hide the header and footer on some page. I have the file [layout-context.js](https://github.com/teimurjan/issue-gatsby-layout-context/blob/master/src/layouts/layout-context.js).

So, if I need to change an option on some page, I just add `<LayoutOptions shouldHideHeader={true} shouldHideFooter={true} />` in [the page component](    https://github.com/teimurjan/issue-gatsby-layout-context/blob/d73ea2f9d2cf0c4b02ba918cef87d3de1874e011/src/pages/page-2.js#L9).

I see that during the build, React.Context value is always the default one. That's why the built signup HTML page is appeared with the header at first.

![May-02-2019 11-47-30](https://user-images.githubusercontent.com/17337276/57058196-30d87400-6cd0-11e9-826d-f15efe507192.gif)

Here is the archive with the built demo site: [public.zip](https://github.com/gatsbyjs/gatsby/files/3136840/public.zip).

PS: I tried to use HOC instead of `LayoutOptions`, move the logic from `componentDidMount` to `constructor` but none works for me.
 
### Environment (if relevant)

```
  System:
    OS: macOS 10.14.4
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
    Yarn: 1.6.0 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.15.1/bin/npm
  Languages:
    Python: 3.7.1 - /Users/teimurgasanov/miniconda3/bin/python
  Browsers:
    Chrome: 73.0.3683.103
    Firefox: 65.0
    Safari: 12.1
  npmPackages:
    gatsby: ^2.3.34 => 2.3.34 
    gatsby-image: ^2.0.41 => 2.0.41 
    gatsby-plugin-layout: ^1.0.15 => 1.0.15 
    gatsby-plugin-manifest: ^2.0.29 => 2.0.29 
    gatsby-plugin-offline: ^2.0.25 => 2.0.25 
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12 
    gatsby-plugin-sharp: ^2.0.35 => 2.0.35 
    gatsby-source-filesystem: ^2.0.33 => 2.0.33 
    gatsby-transformer-sharp: ^2.1.18 => 2.1.18 
  npmGlobalPackages:
    gatsby-cli: 2.5.8
```

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by freiksenet** [comment]
Thank you for the issue! This happens because SSR doesn't wait for `componentDidMount` to pass the layout options through. The way it works is that you first render you tree with default (context provided) options. With those, your header is rendered and your options component is rendered inside. This state is the one saved by Gatsby. Only after that, `componentDidMount` will run, LayoutContext will get updated and then the re-render without header will happen.

Could you explain in more detail what you are trying to do? Generally, if you want to configure some settings per page, you can use Gatsby [page context](https://www.gatsbyjs.org/docs/creating-and-modifying-pages/#pass-context-to-pages).

**Comment by teimurjan** [comment]
@freiksenet I want to configure layout settings from the page component. I have a `LayoutOptions` component which sets the values to the context:

```jsx
export const LayoutOptions = withLayoutContext(
  // tslint:disable-next-line:max-classes-per-file
  class extends React.Component {
    areOptionsSet = false;

    componentDidMount() {
      const { layoutState, ...props } = this.props;

      if (!this.areOptionsSet) {
        layoutState.setLayoutOptions(props);
        this.areOptionsSet = true;
      }
    }

    componentWillUnmount() {
      const { layoutState } = this.props;

      layoutState.setLayoutOptions(DEFAULT_LAYOUT_OPTIONS);
    }

    render() {
      return null;
    }
  },
);
```

And then I use this component inside the page component to configure layout context.

```jsx
const SecondPage = () => (
  <>
    <LayoutOptions shouldHideHeader={true} shouldHideFooter={true} />
    <SEO title="Page two" />
    <h1>Hi from the second page</h1>
    <p>Welcome to page 2</p>
    <Link to="/">Go back to the homepage</Link>
  </>
)
```

I think it won't work with Gatsby page context as I need this configuration to be given from page to layout.

**Comment by freiksenet** [comment]
Do you want to dynamically change it from the component? I mean, do they change during the runtime? I don't understand why you need to control it from the component this way :)

**Comment by teimurjan** [comment]
No, I don't need to have dynamic changes. I just followed the instruction [here](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-layout#passing-data-from-layout-to-page--from-page-to-layout) to pass the data from page to layout. Is there another way to have a layout configured differently for some pages?

**Comment by wardpeet** [comment]
@teimurjan you're making it a bit more complex than needed. In gatsby v2 we advocate to explicitly use Layout in each page instead of using the gatsby-plugin-layout package.

which means you can just go for: (no need to do any context api stuff)
```js
const SecondPage = () => (
  <Layout shouldHideHeader={true} shouldHideFooter={true}>
    <SEO title="Page two" />
    <h1>Hi from the second page</h1>
    <p>Welcome to page 2</p>
    <Link to="/">Go back to the homepage</Link>
  </LayoutOptions>
)
```

demo:
https://github.com/wardpeet/gatsby-demos/tree/pass-data-to-layout

**Comment by teimurjan** [comment]
@wardpeet got it! I just was afraid of duplications. Thank you!

**Comment by wardpeet** [comment]
duplications can be good for composition, it's less magic and it's more maintainable if you ever want to have a page without a layout or with something different it's all in the component no trickery.

**Comment by teimurjan** [comment]
@wardpeet Thanks for the explanation, it's clear now 🙂

**Comment by magnusarinell** [comment]
I have the same problem but cannot simply move to having the layout in the page because I have some css transitions when moving between pages. Any suggestions on how to solve this? Can I wrap some of my pages in gatsby-browser and gatsby-ssr wrapPageElement (the pages with transitions between them) and some not? I really want the prerendered page to match perfectly for every page.
