### ISSUE TITLE
Changing siteMetadata fed through themes options returns null

### ISSUE THREAD

**Issue by baukevanderlaan** [gatsbyjs/gatsby#13808]
## Description

Thanks for your work on themes, they're incredible! 👍 

I'm working simultaneously on a theme and a site that's using that theme. I want to set the `siteMetadata` in that theme based on the theme `options` defined in the site. It looks like it's working when I run `yarn workspace site develop` but whenever I change the theme options in the `gatsby-config.js` in the site folder, the siteMetadata properties return `null` (as I can see in GraphiQL).

### Steps to reproduce

1. Have a _theme_ with this `gatsby-config.js`:

```
module.exports = themeOptions => {
  return {
    siteMetadata: {
      title: themeOptions.title,
      author: themeOptions.author,
    },
  }
}
```
2. Have a _site_ with this `gatsby-config.js`:
```
module.exports = {
  __experimentalThemes: [
    {
      resolve: `gatsby-theme-mytheme`,
      options: {
        title: `My site`,
        author: `Bauke`,
      },
    },
  ], 
}
```
3. Run `yarn workspace site develop`. As you can see, the `siteMetadata` correctly fetches the data from the `themeOptions`.
4. Change any of the `options` properties in the site. Now the `title` and `author` properties on `siteMetadata` return `null` in GraphQL.

### Expected result

I expect the `siteMetadata` properties to reflect the changes, like they would do when I would set them directly in the site itself.

### Actual result

The properties return `null`.

**Comment by ChristopherBiscardi** [comment]
I've reproduced the issue with changing `siteMetadata` while gatsby-develop is still running and getting `null` for that value in GraphiQL.

---

That said, I'd suggest *not* setting `siteMetadata` this way. Instead, since `siteMetadata` merges, you can set up a theme as such with default values:

```js
// theme gatsby-config.js
module.exports = {
    siteMetadata: {
        title: 'My Awesome Site With a Theme!',
        author: 'Jane Doe'
    }
}
```

and let the user set the fields as such:

```js
// user's gatsby-config.js
module.exports = {
    siteMetadata: {
        title: 'site title',
        author: 'site author'
    },
    __experimentalThemes: ["gatsby-theme-minimal"]
};
```

This approach allows the standardization of specific fields in different themes, such as `author` and `title`, doesn't have the bug mentioned in this issue, and I can't think of a good use case for a user setting `siteMetadata` from a theme's options instead of letting the user control it directly. If a use case comes up I'm happy to re-open, until then I suggest the pattern above instead.

**Comment by baukevanderlaan** [comment]
Thanks for looking into it @ChristopherBiscardi!

My specific use case is that I use the values not only for `siteMetadata` but also in the configuration of other plugins that are specified in the theme. For example I'd use the `title` theme option from my initial post both in the `siteMetaData` and in the `name` option of `gatsby-plugin-manifest`.

Anyway, it's a minor nuisance that occurs only very rarely, so I'm not bothered by it at all.
