### ISSUE TITLE
Focus Management

### ISSUE THREAD

**Issue by gkemp94** [gatsbyjs/gatsby#13853]
## Description

I thought Reach Router is supposed to jump focus to the content when a link is selected. I'm not getting this behavior as I progress through the tutorial. 

### Steps to reproduce

I just finished https://www.gatsbyjs.org/tutorial/part-three/ of the tutorial, and was testing the accessibility but haven't got the expected behavior. 

### Expected result

After link is selected, focus should jump to content

### Actual result

Focus is moved back to body tag

**Comment by diegohaz** [comment]
I'm also having this problem. I'd guess that's because the navigation links are placed inside the page container (the element with `role="group"` on which reach router puts focus). But even using `wrapPageElement` on `gatsby-ssr` and `gatsby-browser` puts the navigation inside that container (the only difference is that the navigation doesn't get unmounted on page changes).
