### ISSUE TITLE
Flood of deploy status messages

### ISSUE THREAD

**Issue by whmountains** [gatsbyjs/gatsby#1391]
Any way we can get rid of the incessant "Deploy preview failed." and "Deploy preview succeeded." messages?  I'm trying to follow the Gatsby project so I can contribute when possible, but those messages really flood my inbox.

It seems like for every commit there are duplicate messages from @gatsbybot and from @KyleAMathews.  Also the current status is shown at the end of the comments, so maybe you could eliminate them all together?

**Comment by KyleAMathews** [comment]
Agreed 👍 I want to handle those updates ourselves so just put them all in one comment and keep updating that comment via the API.

Netlify is annoyingly unreliable at indicating when something succeeds or fails so having all the example sites say when they failed (we build every example site on every PR) hasn't been very helpful.

**Comment by whmountains** [comment]
Awesome.  Thank you!

Good to know about Netlify.  Do you mean unreliable in terms of sometimes it gives false positives, or unreliable in the sense that sometimes it takes a long time to get the message?

**Comment by KyleAMathews** [comment]
Sometimes false negatives (not sure if I've seen a false positive before) but also often builds fail because of no fault of our own e.g. problems with Netlify or problems with an NPM install so the build fails.

No one site is that likely to fail but when you have a dozen+ almost every PR gets a handful of fails and sometimes a wave of failures when some upstream is being especially flaky.

**Comment by biilmann** [comment]
@KyleAMathews Do you have some examples of false negatives ? Would want to dig into why those fails...
