### ISSUE TITLE
Gatsby Source GraphQL, where can I loop through the nested fields

### ISSUE THREAD

**Issue by ArcaneTSGK** [gatsbyjs/gatsby#13922]
## Summary
I am trying to modify gatsby-source-graphql to utilise the createRemoteFileNode for media provided by the CMS (via a graphql endpoint). I am struggling to identify at which point I need to iterate through the fields so that I can do the create remote node for things like images.

## Relevant information

In transforms.js I can see where the GraphQLSchema types are being generated

```
return new GraphQLSchema({
            query: newQuery,
            types: allTypes,
        })
```
allTypes is of course giving the 'top level' types, so from this example schema:

```
{
  managedContent(managedContentRequest:{Id:181}){
    content{
      homePage{
        seoTiles{
          content
          icon
          name
          title
        }
        reassuranceImages{
          cmsImage{
            absolutePath
            fileExtension
            fileName
            fileSize
            mime
          }
        }
      }
    }
  }
}
```

I can see `Query_ReassuranceImage: Query_ReassuranceImage` as one of the items returned in  'allTypes'

I need to be able to drill down further to iterate through the 'cmsImage' field so I can do something similar to the following

```
if (field !== null && field.hasOwnProperty('mime')) {
let fileNode;
    try {
       fileNode = await createRemoteFileNode({
        url: field.thumbnail,
        cache,
        store,
        createNode,
        createNodeId,
        ext: 'field.fileExtension',
      });
    } catch (error) {
      console.warn('error creating node', error);
    }
}
```
Wherever an image is coming from the cms in any part of my schema I would like to be able to create an image node and cache the image in gatsby in this way

A point in the direction would be greatly appreciated.

**Comment by sidharthachatterjee** [comment]
@ArcaneTSGK Sounds like you're trying to _transform_ some specific type of nodes. In situations like this, you could write a _transformer_ plugin 👻 

1. Instead of editing `gatsby-source-graphql`, make a separate plugin 
1. Use the `onCreateNode` API documented in https://www.gatsbyjs.org/docs/node-apis/#onCreateNode
1. Check for node.internal.mediaType or other field to see that it is coming from the CMS
1. Use createRemoteFileNode

Might help to see `gatsby-transformer-json`

https://github.com/gatsbyjs/gatsby/blob/8829e8baa883bfd1584c501ee961ae245ef50138/packages/gatsby-transformer-json/src/gatsby-node.js#L4

**Comment by jeremylynch** [comment]
Did you have any luck with this @ArcaneTSGK ?
