### ISSUE TITLE
Mixed Content http:// Roboto font

### ISSUE THREAD

**Issue by donaldboulton** [gatsbyjs/gatsby#13988]
Mixed Content: The page at 'https://publiuslogic.com/' was loaded over HTTPS, but requested an insecure font 'http://fonts.gstatic.com/s/roboto/v18/KFOkCnqEu92Fr1MmgVxFIzIFKw.woff2'. This request has been blocked; the content must be served over HTTPS.

All Gatsby sites I visit have the same error and it showed up recently. Searched the gatsby code and found noting related to calling http://fonts.gstatic.com/s/roboto/....

tried
`"typeface-roboto": "^0.0.54",`

and adding to layout
`require('typeface-roboto')`

Nothing fixed it???

**Comment by daydream05** [comment]
Hey there. All you have to do is to use “https://“ instead of “http://” to load your font. Google recommends not to mix content

https://developers.google.com/web/fundamentals/security/prevent-mixed-content/fixing-mixed-content

You can also use typography.js or this https://www.npmjs.com/package/gatsby-plugin-web-font-loader if there’s no https version of the the font link you’re trying to use. (But i’m sure there is)

I’ve had this issues before with my Jekyll site where I was serving images over http. So take it easy on gatsby 😅

**Comment by crashuniverse** [comment]
This isn't related to Gatsby. Marked for closing. 

If you look for mixed content in stackoverflow, it should be possible to find a lot of useful approaches to manage fonts. Here is one: https://stackoverflow.com/q/35978316/1290185
