### ISSUE TITLE
starters from subdir

### ISSUE THREAD

**Issue by maecapozzi** [gatsbyjs/gatsby#14007]
Issue moved from https://github.com/ChristopherBiscardi/gatsby-theme-examples/ at the request of @ChristopherBiscardi.

## Summary

The gatsby cli today doesn't allow installing starters from a subdirectory of a git repo. it should because with themes, a lot more monorepo workflows make sense

**Comment by DSchau** [comment]
Hey @maecapozzi (and nice to see you around here!) 👋 

Thanks for opening this. We've tossed around the idea before, but it's not _as_ trivial as we'd expect to do in a nice, performant and cross-platform way.

A simple (but not necessarily ideal) solution is to do something like we do in our monorepo, e.g. a script to clone a subdirectory to a standalone repo (gatsbyjs/gatsby/starters/gatsby-stater-default -> gatsbyjs/gatsby-starter-default). Github Actions could theoretically be a good use case for this too.

@ChristopherBiscardi is there more context to this issue that we may not have? I know that @johno mentioned working o something like this before, as well.

**Comment by maecapozzi** [comment]
Hey @DSchau - @ChristopherBiscardi asked me to help out by moving some issues over from https://github.com/ChristopherBiscardi/gatsby-theme-examples! This is just one of those issues :). He said more context would be added later.

**Comment by johno** [comment]
> I know that @johno mentioned working on something like this before, as well.

Yeah, unfortunately it's [not something that's cross-platform](https://github.com/c8r/initit) so we wouldn't be able to use it for the purposes of Gatsby without solving that (which is indeed non-trivial).

GitHub Actions could be a solid way to solve it, especially if we can bundle something up for the GitHub Marketplace. I think that having the tooling prepackaged is important so that theme authors don't necessarily have to start dabbling with Actions directly since it will be a common workflow.

I should have time this afternoon so I could play around with building out an Action to do that which we could potentially submit (never done that before so not sure what's required on the Marketplace end).

**Comment by johno** [comment]
Had a quick spike of what an action might look like to handle this. You can see it here: https://github.com/johno/actions-push-subdirectories

I've wired up a basic [usage example](https://github.com/johno/gatsby-theme-example) which publishes subdirs to a [standalone starter](https://github.com/johno/gatsby-starter-theme-example) and [added to the Marketplace](https://github.com/marketplace/actions/github-action-to-push-subdirectories-to-another-repo).

The workflow feels decent, but it's a bummer that it'd be a required workflow for a theme author with a smallish monorepo with a handful of themes and starters. So, ultimately figuring out some way to handle subdirectories in the `gatsby new` CLI since it will be plenty solid for the majority of use cases. Large, complex monorepos, like Gatsby itself, are a much better fit for this GitHub Actions workflow.

**Comment by ChristopherBiscardi** [comment]
@DSchau Yeah, the plan was to clone the repo anyway since theme repos are likely to be small collections of themes, then copy a subdir into the relevant working directory. We also discussed in the future potentially building a caching service if we felt there were performance issues and people were using the functionality on 100+ package repos.

The reasoning for this specific issue is that having a starter for a theme and a theme you're working on in the same monorepo is a very common configuration. Our documentation even suggests using https://github.com/ChristopherBiscardi/gatsby-starter-theme which uses this configuration.

Thanks @maecapozzi :)

**Comment by ChristopherBiscardi** [comment]
To add to this issue, we should document a github actions approach that is suitable for larger mono-repos. With larger repos I think the additional tooling overhead becomes less of an issue.

**Comment by vpicone** [comment]
I think this makes a lot of sense considering the go-to method for theme development is in a yarn workspace monorepo. Updating a separate starter is a bit of a pain.

**Comment by sidharthachatterjee** [comment]
Closing this in favour of https://github.com/gatsbyjs/gatsby/issues/16135

Let's move the discussion there
