### ISSUE TITLE
[themes] Write a tutorial for authoring themes

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/gatsby#14099]
Part of getting themes to a stable launch includes writing a tutorial on how to author themes.

## Proposed table of contents

- [ ] Setting up your environment for theme development (i.e. Yarn workspaces)
- [ ] Bare essentials for a theme
- [ ] How to install the theme in a site for local development
- [ ] How to apply config options from the site to the theme
- [ ] Configure the theme to use MDX from the site
- [ ] Best practices for progressive disclosure of complexity
- [ ] Setting up design tokens
- [ ] How to architect components for easier shadowing

Tagging @ChristopherBiscardi @marcysutton @johno @jxnblk for feedback on the ToC.

___

7.11.2019 Update

This tutorial will live in the themes tutorial section, and will be a written translation (and therefore written companion) to the egghead course.

**Comment by ChristopherBiscardi** [comment]
I think the first three options (or at least the latter two) can be encapsulated in telling people to use a `gatsby-starter-theme` like https://github.com/ChristopherBiscardi/gatsby-starter-theme and explaining what files exist and why. We can move that repo into the Gatsby repo as a starter.

Should best practices exist in the tutorial at all? or should they be an entirely separate docs page.

It sounds like for design tokens in the official themes we're going to end up with a `gatsby-plugin-tokens` (or similar) so that will be nice for that section.

**Comment by jlengstorf** [comment]
> I think the first three options (or at least the latter two) can be encapsulated in telling people to use a gatsby-starter-theme like ChristopherBiscardi/gatsby-starter-theme and explaining what files exist and why.

@ChristopherBiscardi I guess that's a good question. Is the goal of this doc to teach people how to build a theme from scratch (e.g. full understanding by stepping through the whole process) or to guide them through using a boilerplate?

I can make a good argument for both cases, so I'm happy to go either way.

> Should best practices exist in the tutorial at all?

Maybe they start here and move to a separate page(s) as they expand over time?

**Comment by maecapozzi** [comment]
As someone who has been working on exploring themes, just having those first four topics covered would be valuable. Once that's fleshed out, it might be easier to see where the holes are, or which other topics might belong in the tutorial? 

I'd be happy to take the first section to start it off, if that'd be helpful.

**Comment by jlengstorf** [comment]
@maecapozzi that would be amazing! @jxnblk wrote an [article about workspaces](https://www.gatsbyjs.org/blog/2019-05-22-setting-up-yarn-workspaces-for-theme-development/) recently, so that should be a great starting point. Thank you!

**Comment by maecapozzi** [comment]
@jlengstorf, I created a [first draft](https://github.com/gatsbyjs/gatsby/pull/14536) of that section. I'm not quite sure where we'd like the tutorial to live, but I gave it a shot!

**Comment by maecapozzi** [comment]
I think it'd be useful to come up with a process for how you'd like to collect the content for this tutorial. Will a single person write most of the sections? Do you want to merge it section-by-section with a note that the rest of the tutorial is a stub, or all at once? @marcysutton brought up these questions on my PR, and I just wanted to bring them up on this issue as well.

**Comment by jlengstorf** [comment]
@marcysutton do you have thoughts on this? It seems to me like we could stub out what we need and tackle these a section at a time, which means it can be done piecemeal without requiring a single person to go all-in on writing the full guide. That should also cut down on review overhead.

I'll defer to your judgment here, and I'm not sure where it should live. Let us know!

**Comment by marcysutton** [comment]
> we could stub out what we need and tackle these a section at a time, which means it can be done piecemeal without requiring a single person to go all-in

That sounds like a great approach to me!

Right now my recommendation for location is to add theme authoring tutorials to the "Creating Themes" section within the Themes docs, similar to the [Creating Plugins](https://www.gatsbyjs.org/docs/creating-plugins/) section. That said: before we move Themes docs to GA (general availability), we'll need to merge them with the plugins docs. But I need to punt on that for a week or two due to workload, so that's my best answer today. 😜

**Comment by marcysutton** [comment]
Tagging @amberleyromo who is working on Themes docs, since our current recommendation for the theme authoring tutorial location is in that section. We can also link to "Building for Gatsby" content from the Additional Tutorials page (see #14847)

**Comment by lannonbr** [comment]
@jlengstorf @amberleyromo I would say this issue is resolved so I am going to close it. Feel free to reopen it if there is still work to be done with the Theme Authoring Tutorial
