### ISSUE TITLE
FEATURE: Add scroll-behavior

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#141]
https://github.com/taion/scroll-behavior

Right now you don't get scrolled to the top when you click on a link which is weird behavior.

I'm assuming we want the `useStandardScroll` behavior.

**Comment by ztrayner** [comment]
@KyleAMathews - Is there currently a way to opt out of this behavior so that the page doesn't scroll to the top on specific route changes?

I have a layout with some static stuff at the top, then a menu for a bunch of pages on the left with the dynamic page content on the right.  I'd like it if the user didn't have to scroll down past the top stuff to the dynamic content on route change.

**Comment by KyleAMathews** [comment]
Aye https://www.gatsbyjs.org/docs/browser-apis/#shouldUpdateScroll

if you search the repo, there's a few places it's used in example sites
