### ISSUE TITLE
Retrieving images with special chars in the filename with gatsby-source-wordpress

### ISSUE THREAD

**Issue by daniloef** [gatsbyjs/gatsby#14124]
I am working in a blog using the gatsby-source-wordpress plugin, and executing the following query I noted that **the field "localFile" returns NULL** when the source image has special chars (á, é, í, ó, ú, ñ, etc.). 

```
  query {
    allWordpressPost {
      edges {
        node {
          wordpress_id
          title
          excerpt
          slug
          author {
            name
          }
          date(formatString: "MMMM DD, YYYY")
          featured_media{
            localFile{
              childImageSharp{
                resolutions(width:300,height:300){
                  src
                  width
                  height
                }
              }
            }
          }
        }
      }
    }
  }
```

Anyone resolve that? 

Regards.

**Comment by jonniebigodes** [comment]
@daniloef i'm going to check out in my local installation and get back to you, but i'm pretty much convinced that special characters, like in this case portuguese and spanish characters with accents do not work well with Gatsby, i don't know if this particular case is with the characters being escaped when retrieved via the rest api or probably something else during the download and graphql node generation.

**Comment by daniloef** [comment]
@jonniebigodes Thank you! 

The alternative solution is to "clean" the filenames in WP, but for sites with a lot of posts it can be difficult. 

Waiting for your update :)

**Comment by jonniebigodes** [comment]
@daniloef sorry for the wait. I'm going to describe the methodology used to tackle this issue. And beforehand the issue is accurate, i was able to reproduce it.

- Created a new Gatsby website based on the hello world starter to keep it simple.

- Added the necessary dependencies, namely `gatsby-source-wordpress`,`gatsby-image` and it's accompanying plugins, `gatsby-transformer-sharp` and `gatsby-plugin-sharp`.

- Modified `gatsby-config.js` for my local wordpress installation, resulting in the following:
```javascript
module.exports = {
  /* Your site config here */
  plugins:[
    `gatsby-plugin-sharp`,
    `gatsby-transformer-sharp`,
    {
      resolve:`gatsby-source-wordpress`,
      options:{
        baseUrl: `localhost/wordpress/`,
        hostingWPCOM: false,
        protocol:`http`,
        useACF:false,
        auth:{},
        verboseOutput: false,
        includedRoutes: [
          "/*/*/posts",
          "/*/*/media",
        ],
      }
    }
  ]
}
```
- Grabbed some images and renamed them to portuguese named files, with accents and uploaded them to wordpress and created a post for each item as you can see below, the top 4 items on each side.

![danilo_1](https://user-images.githubusercontent.com/22988955/57973347-7dde6a80-799f-11e9-8c79-78227e7e1b81.png)

- Issued `gatsby develop` and it yelded the following result:

![danilo_2](https://user-images.githubusercontent.com/22988955/57973366-c8f87d80-799f-11e9-9e7c-6d381e5e624a.png)
One would assume that the data was downloaded right?

- Opened up `http://localhost:8000/___graphql` and entered the following graphql query:
```graphql
{
  allWordpressPost {
    edges {
      node {
        id
        date(formatString: "YYYY/MM/DD")
        slug
        title
        featured_media {
          localFile {
            id
            childImageSharp {
              fluid(maxWidth: 2000) {
                originalName
                src
                srcSet
                originalImg
              }
            }
          }
        }
      }
    }
  }
}

```
It yelded the following:
![danilo_3](https://user-images.githubusercontent.com/22988955/57973399-59cf5900-79a0-11e9-837e-ed1a1c339004.png)

As you said in your issue description, it's true, the files are not present it's returning `null` for the items that have those characters. 

So i went bit further and checked the rest endpoint that is also consumed by Gatsby. Opened up a new browser window and entered the following `localhost/wordpress/wp-json/wp/v2/media` it gave me the list of the media files, i then tracked down a particular item and issued `http://localhost/wordpress/wp-json/wp/v2/media/239`, 239 is the id of the image called `árvore.jpg` and it returned the following:
```json
{
  "id": 239,
  "date": "2019-05-18T15:49:05",
  "date_gmt": "2019-05-18T15:49:05",
  "guid": {
    "rendered": "http://localhost/wordpress/wp-content/uploads/2019/05/árvore.jpg"
  },
  "modified": "2019-05-18T15:49:05",
  "modified_gmt": "2019-05-18T15:49:05",
  "slug": "arvore",
  "status": "inherit",
  "type": "attachment",
  "link": "http://localhost/wordpress/arvore/",
  "title": {
    "rendered": "árvore"
  },
  "author": 1,
  "comment_status": "open",
  "ping_status": "closed",
  "template": "",
  "meta": [],
  "description": {
    "rendered": "<p class=\"attachment\"><a href='http://localhost/wordpress/wp-content/uploads/2019/05/árvore.jpg'><img width=\"300\" height=\"200\" src=\"http://localhost/wordpress/wp-content/uploads/2019/05/árvore-300x200.jpg\" class=\"attachment-medium size-medium\" alt=\"\" srcset=\"http://localhost/wordpress/wp-content/uploads/2019/05/árvore-300x200.jpg 300w, http://localhost/wordpress/wp-content/uploads/2019/05/árvore-768x512.jpg 768w, http://localhost/wordpress/wp-content/uploads/2019/05/árvore-1024x683.jpg 1024w, http://localhost/wordpress/wp-content/uploads/2019/05/árvore-1568x1045.jpg 1568w\" sizes=\"(max-width: 34.9rem) calc(100vw - 2rem), (max-width: 53rem) calc(8 * (100vw / 12)), (min-width: 53rem) calc(6 * (100vw / 12)), 100vw\" /></a></p>\n"
  },
  "caption": {
    "rendered": ""
  },
  "alt_text": "",
  "media_type": "image",
  "mime_type": "image/jpeg",
  "media_details": {
    "width": 5184,
    "height": 3456,
    "file": "2019/05/árvore.jpg",
    "sizes": {
      "thumbnail": {
        "file": "árvore-150x150.jpg",
        "width": 150,
        "height": 150,
        "mime_type": "image/jpeg",
        "source_url": "http://localhost/wordpress/wp-content/uploads/2019/05/árvore-150x150.jpg"
      },
      "medium": {
        "file": "árvore-300x200.jpg",
        "width": 300,
        "height": 200,
        "mime_type": "image/jpeg",
        "source_url": "http://localhost/wordpress/wp-content/uploads/2019/05/árvore-300x200.jpg"
      },
      "medium_large": {
        "file": "árvore-768x512.jpg",
        "width": 768,
        "height": 512,
        "mime_type": "image/jpeg",
        "source_url": "http://localhost/wordpress/wp-content/uploads/2019/05/árvore-768x512.jpg"
      },
      "large": {
        "file": "árvore-1024x683.jpg",
        "width": 1024,
        "height": 683,
        "mime_type": "image/jpeg",
        "source_url": "http://localhost/wordpress/wp-content/uploads/2019/05/árvore-1024x683.jpg"
      },
      "post-thumbnail": {
        "file": "árvore-1568x1045.jpg",
        "width": 1568,
        "height": 1045,
        "mime_type": "image/jpeg",
        "source_url": "http://localhost/wordpress/wp-content/uploads/2019/05/árvore-1568x1045.jpg"
      },
      "full": {
        "file": "árvore.jpg",
        "width": 5184,
        "height": 3456,
        "mime_type": "image/jpeg",
        "source_url": "http://localhost/wordpress/wp-content/uploads/2019/05/árvore.jpg"
      }
    },
    "image_meta": {
      "aperture": "0",
      "credit": "",
      "camera": "",
      "caption": "",
      "created_timestamp": "0",
      "copyright": "",
      "focal_length": "0",
      "iso": "0",
      "shutter_speed": "0",
      "title": "",
      "orientation": "0",
      "keywords": []
    }
  },
  "post": null,
  "source_url": "http://localhost/wordpress/wp-content/uploads/2019/05/árvore.jpg",
  "_links": {
    "self": [
      {
        "href": "http://localhost/wordpress/wp-json/wp/v2/media/239"
      }
    ],
    "collection": [
      {
        "href": "http://localhost/wordpress/wp-json/wp/v2/media"
      }
    ],
    "about": [
      {
        "href": "http://localhost/wordpress/wp-json/wp/v2/types/attachment"
      }
    ],
    "author": [
      {
        "embeddable": true,
        "href": "http://localhost/wordpress/wp-json/wp/v2/users/1"
      }
    ],
    "replies": [
      {
        "embeddable": true,
        "href": "http://localhost/wordpress/wp-json/wp/v2/comments?post=239"
      }
    ]
  }
}
``` 
- Checked the json and the characters were not escaped or anything like that, tested by opening directly and it worked. 

- So i went ahead and checked the source code for `gatsby-plugin-wordpress` and after looking at the code, my analysis is that in a nutshell it's not doing anything else than creating the necessary graphql nodes, prunes a couple of items and then delegates the download to `gatsby-source-filesystem` and there's where "magic"(pardon the bad pun) happens. From my read on it it seem that asset download is based the `source_url` element above, not the ones inside the `full`, `medium` and so on. And the appropriate function in `gatsby-source-filesystem` does not like items with special characters so it seems.  It doesn't complain or anything it just basically ignores it and doesn't download the file.

Like you said in your previous comment the solution for your case is to rename the assets, stripping them of any special portuguese accents and re-upload them. I don't know how big is your blog and how may assets you have in there, but i'm sorry for this cumbersome task if this is the case.

Feel free to provide feedback. Thanks for using Gatsby 👍

**Comment by daniloef** [comment]
Hi @jonniebigodes 

Thank you very much for your answer and the dedication you applied in test step by step. 

I have about 40 sites, which some of them has more than 800 posts. So, it's a lot of work!

**Comment by wardpeet** [comment]
@daniloef mind sharing an image url with us or your wordpress api so we can patch gatsby-source-filesystem. Feel free to send me a personal email on ward@gatsbyjs.org

**Comment by daniloef** [comment]
Hi @wardpeet 

Thank you! I sent you an email.
