### ISSUE TITLE
gatsby-source-wordpress: Processing the images in the posts

### ISSUE THREAD

**Issue by daniloef** [gatsbyjs/gatsby#14145]
Hi, 

Using the plugin **gatsby-source-wordpress** I noted that the images inner post aren't loaded from the new Gatsby site. Instead of that, they are loaded from **http:///my-old-wordpress-site.com/wp-content/uploads/...**. 

Is there a way to copy and optimize the images from WordPress site, in the same way that Gatsby do with, for example, featured images, which are loaded from something like **http://localhost:8000/static/...**. 

Thank you!

**Comment by jonniebigodes** [comment]
@daniloef based on my earlier response to your other issue. I've updated the Gatsby website in question. 

- Created a couple of posts one with a single image like you can see below:

![danilo_imageinside1](https://user-images.githubusercontent.com/22988955/57976485-881d5a80-79d9-11e9-8cb9-90fe51ede840.png)

- Created another with a gallery inside as you can see.

![danilo_imageinside2](https://user-images.githubusercontent.com/22988955/57976497-ad11cd80-79d9-11e9-99f2-e2ba0ae78390.png)


- Created `gatsby-node.js` with the following code:

```javascript
exports.createPages = ({ graphql, actions }) => {
    const {createPage}= actions

    return graphql(`
    {
        allWordpressPost {
          edges {
            node {
              id
              date(formatString: "YYYY/MM/DD")
              slug
              title
              content
              featured_media {
                localFile {
                  id
                  childImageSharp {
                    fluid(maxWidth: 2000) {
                        src
                        srcSet
                        sizes
                        aspectRatio
                        originalName
                    }
                  }
                }
              }
            }
          }
        }
      }      
    `).then(result=>{
        if (result.errors){
            throw result.errors
        }
        const {data}= result
        const {allWordpressPost}=data
        const {edges}= allWordpressPost
        
        edges.forEach(element => {
            createPage({
                path:`/${element.node.slug}/`,
                component:require.resolve('./src/templates/blog-template.js'),
                context:{
                    blogItem:element.node
                }
            })
        });

    })

}
```

- Created a template called `blog-template.js` inside `./src/templates` with the following code:

```javascript
import React from "react"
import Img from "gatsby-image"
const BlogTemplate = props => {
  const { pageContext } = props
  const { blogItem } = pageContext

  return (
    <div style={{ margin: "0.85rem" }}>
      {blogItem.featured_media && <Img fluid={blogItem.featured_media} />}
      <h2>{blogItem.title}</h2>
      <hr />
      <div dangerouslySetInnerHTML={{ __html: blogItem.content }} />
      <hr />
      <h5>published in {blogItem.date}</h5>
    </div>
  )
}

export default BlogTemplate

```

- Issuing `gatsby develop` and opening up `http://localhost:8000/something-with-a-gallery-inside/` or `http://localhost:8000/post with single image` shows that behaviour.

All of this to what? To demonstrate that as of the current state of the plugin in question all of the data inside a post/article will be fetched via the rest endpoint and based on that, the content is sent back already formatted as html so that it can be injected into the DOM. You can check it for yourself if you open a new browser window to the a similar url, `http://localhost/wordpress/wp-json/wp/v2/posts`, you might need to adjust to your wordpress installation, If you look closely at the JSON returned you'll see the element `content` and inside you'll see your post content already formatted.

To be able to achieve what you propose the plugin in question would have to include something like [gatsby-remark-copy-linked-files](https://www.npmjs.com/package/gatsby-remark-copy-linked-files) for instance.
