### ISSUE TITLE
Allow to pass functions in gatsby-config.js for browser and SSR

### ISSUE THREAD

**Issue by mike1808** [gatsbyjs/gatsby#14199]
## Summary

Currently, options for the plugins in `gatsby-config.js` are stringified for the browser and SSR as mentioned in #13440 However, in some plugins functions are the part of the configurations. So preserving functions would be a great addition for the config file.'
### Basic example

Imagine you have a plugin which calls your provided callback. 
```
plugins: [
  { 
    resolve: 'gatsby-plugin-on-page-load',
    options: { onLoad() { sessionStorage.setItem('loaded', 'true'); }
  }
]
```

### Motivation

In some plugins, you need to provide some kind of callback. I faced this issue with `gatsby-plugin-web-font-loader` where I needed to provide a callback for font load.

**Comment by wardpeet** [comment]
This is a hard nut to crack at the moment. We have to send this function over to webpack which is a bit hard. We can stringify it but a better ways it to compile it to an AST and reconstruct it on gatsby-browser.

**Comment by joefiorini** [comment]
I running into this issue as well. I'm using a gatsby theme and I have multiple sites. Each one needs to pass an object that is used for some central configuration, and that object can have functions (it's for mocking API endpoints client-side). In the theme's `gatsby-browser` I take the configuration object and pass it on to a provider component. At that point it's lost the functions :(. Note that I can't import this configuration in the theme's gatsby-browser or gatsby-ssr because it is unique for each gatsby site that uses the theme. I can't seem to find anywhere else I can pass it, unless I completely change my architecture and set it up using a hook, which doesn't sound very easy either.
