### ISSUE TITLE
Warn when pageContext is too large

### ISSUE THREAD

**Issue by m-allanson** [gatsbyjs/gatsby#14213]
## Summary

Warn when creating too large a `pageContext`, as this may be a sign that you're passing data via context. Typically you should only pass enough context to allow you to query for the data you need. Pick an arbitrary limit like 500Kb. This could trigger a warning when running the `createPage` API.

**Comment by me4502** [comment]
They end up in the same file anyway though? In most cases it's faster to pass in via pageContext due to query speeds. Plus, GraphQL queries have a fair bit of boilerplate which contributes to a larger file size. (Unless this is being changed in @Moocar's per-page manifest setup)

If anything, it may make sense to warn when the size of the produced file is over a specific amount due to browser requests.

**Comment by emmetthannigan** [comment]
hi @m-allanson - myself and two other computer science students would like to work on this issue if that's ok

**Comment by KyleAMathews** [comment]
That'd be great!

**Comment by lxfu1** [comment]
I have the same problem and my page is missing.

**Comment by lxfu1** [comment]
> I have the same problem and my page is missing.

Solved, caused by graphql limit.
