### ISSUE TITLE
[gatsby-transformer-json] parse json with a field that has multiple types

### ISSUE THREAD

**Issue by ahmdsolmn** [gatsbyjs/gatsby#14256]
## Summary
Using `gatsby-transfromer-json` and the `data` folder contains `terms.json`
```js
[
  "title": "some title",
  "items": [
    "item number one",
    {
      "title": "nested items",
      "items": [
        "This array could also contain another nested items and so on..."
      ]
    }
  ]
]
```
The type interface is 
```ts
interface Term { title: string; items: [string | Term]}
```
When trying to parse the above json the `items` field is ignored. What I expect is to be able to do a query and get the whole json with `items` and `title`

### Environment (if relevant)

  System:
    OS: Linux 4.4 Ubuntu 16.04.5 LTS (Xenial Xerus)
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Shell: 5.1.1 - /usr/bin/zsh
  Binaries:
    Node: 10.6.0 - ~/.nvm/versions/node/v10.6.0/bin/node
    npm: 6.1.0 - ~/.nvm/versions/node/v10.6.0/bin/npm
  Languages:
    Python: 2.7.12 - /usr/bin/python
  Browsers:
    Chrome: 71.0.3578.98
    Firefox: 66.0.5
  npmPackages:
    gatsby: ^2.3.34 => 2.3.34 
    gatsby-image: ^2.0.41 => 2.0.41 
    gatsby-plugin-intl: ^0.1.7 => 0.1.7 
    gatsby-plugin-manifest: ^2.0.29 => 2.0.29 
    gatsby-plugin-offline: ^2.0.25 => 2.0.25 
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12 
    gatsby-plugin-sass: ^2.0.11 => 2.0.11 
    gatsby-plugin-sharp: ^2.0.35 => 2.0.35 
    gatsby-plugin-typescript: ^2.0.13 => 2.0.13 
    gatsby-source-filesystem: ^2.0.33 => 2.0.33 
    gatsby-transformer-json: ^2.1.11 => 2.1.11 
    gatsby-transformer-sharp: ^2.1.18 => 2.1.18 

### File contents (if changed)

`gatsby-config.js`: 
```js
module.exports = {
  siteMetadata: {
    title: 'test',
    description: 'Presentations They Will Never Forget',
    author: 'test',
  },
  plugins: [
    'gatsby-plugin-react-helmet',
    {
      resolve: 'gatsby-source-filesystem', 
      options: { 
        name: 'images',
        path: `${__dirname}/src/images`,
       },
      },
      {
        resolve: 'gatsby-source-filesystem', 
        options: { 
          name: 'data',
          path: `${__dirname}/src/data`,
        },
      },
    'gatsby-transformer-sharp',
    'gatsby-transformer-json',
    'gatsby-plugin-sharp',
    {
      resolve: 'gatsby-plugin-manifest',
      options: {
        name: 'gatsby-starter-default',
        short_name: 'starter',
        start_url: '/',
        background_color: '#663399',
        theme_color: '#663399',
        display: 'minimal-ui',
        icon: 'src/images/test-icon.png', // This path is relative to the root of the site.
      },
    },
    {
      resolve: `gatsby-plugin-intl`,
      options: {
        path: `${__dirname}/src/intl`,
        languages: [`en`, `fr`],
        defaultLanguage: `en`,
        redirect: false,
      },
    },
    // 'gatsby-plugin-offline',
    'gatsby-plugin-sass',
    'gatsby-plugin-typescript',
  ],
}
```
package.json`: 
```js
{
  "name": "test",
  "private": true,
  "description": "test",
  "version": "0.1.0",
  "author": "test",
  "dependencies": {
    "@types/react": "^16.8.15",
    "@types/react-dom": "^16.8.4",
    "@types/react-helmet": "^5.0.8",
    "gatsby": "^2.3.34",
    "gatsby-image": "^2.0.41",
    "gatsby-plugin-intl": "^0.1.7",
    "gatsby-plugin-manifest": "^2.0.29",
    "gatsby-plugin-offline": "^2.0.25",
    "gatsby-plugin-react-helmet": "^3.0.12",
    "gatsby-plugin-sass": "^2.0.11",
    "gatsby-plugin-sharp": "^2.0.35",
    "gatsby-plugin-typescript": "^2.0.13",
    "gatsby-source-filesystem": "^2.0.33",
    "gatsby-transformer-json": "^2.1.11",
    "gatsby-transformer-sharp": "^2.1.18",
    "node-sass": "^4.12.0",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-helmet": "^5.2.0",
    "reakit": "^0.16.0",
    "reakit-theme-default": "^0.2.0",
    "tslint": "^5.16.0",
    "tslint-config-prettier": "^1.18.0",
    "tslint-loader": "^3.5.4",
    "tslint-react": "^4.0.0",
    "typescript": "^3.4.5"
  },
  "devDependencies": {
    "@types/styled-components": "^4.1.14",
    "prettier": "^1.17.0"
  },
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop --port=${PORT:-8000} --host=0.0.0.0",
    "format": "prettier --write src/**/*.{js,jsx}",
    "start": "npm run develop",
    "serve": "gatsby serve",
    "test": "echo \"Write tests! -> https://gatsby.dev/unit-testing\"",
    "type-check": "tsc --noEmit",
    "lint": "tslint --project ."
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/gatsbyjs/gatsby-starter-default"
  },
  "bugs": {
    "url": "https://github.com/gatsbyjs/gatsby/issues"
  }
}

```
gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by jonniebigodes** [comment]
@ahmdsolmn can you share a reproduction following this [steps](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/) , so that it can be looked at? I don't mind going over it and try to solve your issue. Sounds good?

**Comment by jonniebigodes** [comment]
@ahmdsolmn with this comment, i'm going to enumerate the steps i took to replicate your issue and how to solve it and what is actually happening.
- Created a new Gatsby website with the hello world starter to keep it simple.
- Added the dependencies `gatsby-source-filesystem` and `gatsby-transformer-json`.
- Created a `data` folder in the root of the project and added inside the `terms.json` file with the content you supplied.
- Modified `gatsby-config.js ` to the following:
```javascript
module.exports = {
  /* Your site config here */
  plugins:[
    {
      resolve:`gatsby-source-filesystem`,
      options:{
        name:'jsondata',
        path:`./data/`
      }
    },
    `gatsby-transformer-json`
  ]
}

```
- Issued `gatsby develop`, waited for the build to complete and opened up `http://localhost:8000/___graphql` with the query shown below and i was able to confirm that your issue happens. 
![ahmdsolmn_1](https://user-images.githubusercontent.com/22988955/58343902-22ebbe00-7e4c-11e9-9fc4-a43c5480ddff.png)

- Checked the json supplied and basically it's not actually correct, It's not a correct JSON structure. 
- Modified the file to the following, which logically it's probably what you would want. I added some more items for testing purposes.

```json
[
    {
      "title": "some title",
      "items": [
        "item number one",
        {
          "title": "nested items",
          "items": [
            "This array could also contain another nested items and so on..."
          ]
        }
      ]
    },
    {
      "title": "another title",
      "items": [
        "item number two",
        {
          "title": "more nested items",
          "items": [
            "This array could also contain more nested items and so on..."
          ]
        }
      ]
    },
    {
      "title": "one other title",
      "items": [
        "item number three",
        {
          "title": "items in three",
          "items": [
            "Array with nested data"
          ]
        }
      ]
    }
  ]
````
- Repeated the test above and same result, based on my knowledge of the plugin it technically doesn't like "apples and bananas"(pardon the bad pun) out of the box, more on that [here](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-transformer-json#troubleshooting), if you want to enforce that structure you would have to make some modifications and i'll get into that in just a bit. If you want to streamline the file and get all the information you need without any extra configurations you can adjust your json file to the following content:
```json
[
    {
      "title": "some title",
      "items": [
        {"title":"item number one"},
        {
          "title": "nested items",
          "items": [
            "This array could also contain another nested items and so on..."
          ]
        }
      ]
    },
    {
      "title": "another title",
      "items": [
        {"title":"item number two"},
        {
          "title": "more nested items",
          "items": [
            "This array could also contain more nested items and so on..."
          ]
        }
      ]
    },
    {
      "title": "one other title",
      "items": [
        {"title":"item number three"},
        {
          "title": "items in three",
          "items": [
            "Array with nested data"
          ]
        }
      ]
    }
  ]
```
- With this small change when you issue `gatsby develop` for instance and go into `http://localhost:8000/___graphql` and issue a query to fetch all the data you need like i did below you won't get more squigly lines mentioning the data is not present. 

![ahmdsolmn_2](https://user-images.githubusercontent.com/22988955/58344462-a5c14880-7e4d-11e9-8dc4-30335bdf0dad.png)

As you can see on the left is the change to the json file i mentioned and on the right the query working and fetching the data.

Now if you want to preserve the structure you mentioned or a similar, you will have to make some modifications to the plugin so that it understands what you want and how you want it. More on that [here](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-transformer-json#configuration-options) 


Feel free to provide feedback so that we can close this issue, or continue to work on it till we find a suitable solution to your issue.

**Comment by ahmdsolmn** [comment]
Modifying all items to be objects seems a reasonable change. Thank you for your  effort  🙏
