### ISSUE TITLE
How to integrate gatsby.js with Bugsnag?

### ISSUE THREAD

**Issue by rgesulfo** [gatsbyjs/gatsby#14263]
## Summary

I was wondering if anyone had some experience using Bugsnag (bugsnag.com) with Gatsby?
As I'm not too sure how to do it.

Thank you in advance for your help.

**Comment by lannonbr** [comment]
@rgesulfo It looks like they have support for React as described here: https://docs.bugsnag.com/platforms/javascript/react/

That said, they describe that you can call ReactDOM.render to wrap your app with a `<ErrorBoundary>` component. In the Gatsby world, we reccomend if you want to wrap the root element, use the `wrapRootElement` api described in the [Gatsby Browser APIs](https://www.gatsbyjs.org/docs/browser-apis/#wrapRootElement)

**Comment by DSchau** [comment]
@lannonbr @rgesulfo exactly! You'll want to use the APIs that Benjamin noted.

What would be _super cool_ is you first get this working with your own application, and once done, this can then be extracted into a standalone plugin so that anyone in the Gatsby ecosystem can get Bugsnag functionality working in their application super-easily!

The idea here is that you'll use gatsby-browser.js to import the necessary dependencies, and then wrap your root element if you want the additional functionality specific to React (which you probably do).

Hope this helps--going to close as answered, but please reply or re-open if we can help further. Thanks for using Gatsby!

**Comment by rgesulfo** [comment]
Thank you @lannonbr for your quick reply. It works.

Here is what I ended up doing for future reference:

_gatsby-browser.js_
`import React from 'react';
import { Provider } from 'react-redux';
import bugsnag from '@bugsnag/js';
import bugsnagReact from '@bugsnag/plugin-react';
import createStore from './src/state/createStore';

const bugsnagClient = bugsnag('BUGSNAG_ID');
bugsnagClient.use(bugsnagReact, React);
const ErrorBoundary = bugsnagClient.getPlugin('react');

const store = createStore();

const wrapRootElement = ({ element }) => (
  <Provider store={store}>
    <ErrorBoundary>
      {element}
    </ErrorBoundary>
  </Provider>
);

export default wrapRootElement;`

**Comment by tbrannam** [comment]
I have attempted to write such a plugin - but it's somewhat tricky in that if the application's gatsby-browser implements wrapRootElement - then the Application is wrapping the plugin's implementation.   I wonder if there's an opportunity to think about a hook especially for placing an ErrorBoundary at the top of the stack.  

In the example above I think that errors that occur in the Provider would not be caught by the ErrorBoundary.  Or am I missing a detail?
