### ISSUE TITLE
Events data from The Events Calendar WP plugin not showing up in GraphQL

### ISSUE THREAD

**Issue by bruceontheloose** [gatsbyjs/gatsby#14285]
## Summary
Events data from The Events Calendar is showing up in WordPress API but not GraphQL.

## Relevant information
Hello,

We are using the free version (i.e., non-Pro) of The Events Calendar (https://theeventscalendar.com/product/wordpress-events-calendar/) WP plugin in WordPress 5.1.1. The events do show up in the WP API (at https://our-domain.com/wp-json/tribe/events/v1/events), but they don't show when testing with GraphiQL. The only GraphQL queries available are the following, which appear to only contain information about the event categories:

* wordpressAcfTribeEventsCat
* allWordpressAcfTribeEventsCat
* wordpressWpTribeEventsCat
* allWordpressWpTribeEventsCat

Does anyone have any suggestions for how to surface the events in GraphQL? I've also contacted the folks at Modern Tribe (makers of The Events Calendar).

Thank you in advance for any ideas!

Bruce

### Environment
* Gatsby 2.3.25
* gatsby-source-wordpress 3.0.53
* WordPress 5.1.1
* The Events Calendar (free version)

**Comment by pieh** [comment]
Is there any chance you can share url to wordpress instance with this plugin enabled? It would save us some time having to setup this up before even starting to debug it.

**Comment by minigopher17** [comment]
I'm having the same problem not knowing how to access the events via GraphQL. However, after putting `verbose: true` in the `gatsby-source-wordpress` plugin in `gatsby-config.js`, I've noticed that it picks up on build the Categories and Events from different endpoints correctly:

`http://xyz.local/wp-json/wp/v2/tribe_events_cat`
`source and transform nodes -> wordpress__wp_tribe_events_cat fetched : 1`

`http://xyz.local/wp-json/tribe/events/v1/events`
`source and transform nodes -> wordpress__tribe/events_events fetched : 1`

However, since the second one above has a `/` in the fetched node, how do you access this in GraphQL? First one above is accessed by `wordpressWpTribeEventsCat` following the "query any other entity" documentation, but how do you access the second one since there's a slash in it? Think that's why it doesn't come up in GraphiQL. Is this a The Events Calendar plugin owner issue or a Gatsby WP plugin issue?

**Comment by minigopher17** [comment]
Found the issue. 2 reasons, firstly the returned data object needs a `wordpress_id`, as all objects need a "wordpress_id" (as I discovered making my own custom API route where another Github issue said that's what you need for GraphQL to pick it up) and the route namespace has an extra "folder" in its path and for some reason the entity can't be read in properly by the plugin because of this.

So, this is what I did to get it working for my purposes to get all events:

In "/src/Tribe/REST/V1/Endpoints/Archive_Event.php", line 196, add: `$data['wordpress_id'] = 1;` - that is, add the necessary "wordpress_id" in the returned object - I just hardcoded it to "1" to make it work - it should probably be some dynamic ID instead.

In "/src/Tribe/REST/V1/Main.php", line 174, change to: `return $this->get_namespace() . '/' . $this->get_version();` - that is, remove the "events" folder path in the middle. This in turn changes the REST API endpoint from `/wp-json/tribe/events/v1/events` to `/wp-json/tribe/v1/events`

Now, after a rebuild, in GraphiQL you can query something like this and get all the events and its details that you want:
```
query {
  allWordpressTribeEvents {
    edges {
      node {
        events {
          title
          start_date
          end_date
          #...
        }
      }
    }
  }
}
```

Not sure why the plugin can't handle a folder path with an extra layer in it, but the above is a good enough hack to get things going.

**Comment by bruceontheloose** [comment]
Philip, thank you so, so much for investigating this and tracking down a solution! I really appreciate it. We'll give it a shot this week.

And thank you, Michal, for the quick reply when I posted the question. We were going to deploy a test environment this week for you (since we can't make our client's environment public), but will hold off now.

Thanks again, everyone!

Bruce

**Comment by lannonbr** [comment]
Hey @bruceontheloose any updates if you ended up getting this working?

**Comment by bruceontheloose** [comment]
Hey, @lannonbr. Sorry for the delay. One of our back-end devs implemented the changes to `Archive_Event.php` and `Main.php`, and they worked to a point. Events started to show in GraphQL but only six of them. (I'm sure there's a way to correct this.) Also, there's the risk that these changes to The Event Calendar's code would be overwritten when updating the plugin. We won't have total control over the environment indefinitely so can't rely on updates being disabled.

I'm not especially knowledgeable about WordPress back-end inner workings so haven't done any troubleshooting, plus we've had a lot of other tasks to press forward with. Absent other ideas, we'll probably use `fetch()` in gatsby-node.js to get the events from the WordPress REST API. Open to more ideas from anyone.

Thanks.

**Comment by peshyyy** [comment]
Will there be any further changes? There is no workaround atm to get this work, i tried with multiple node versions.
@erinoerin

**Comment by therealgilles** [comment]
FYI There is an wp-graphql TEC extension here: [https://github.com/simplur/ql-events](https://github.com/simplur/ql-events)
but it only partially works and may well require rewriting to use the TEC ORM functions instead of trying to use the WP_Query directly.
