### ISSUE TITLE
Release v1 of style guide currently located on mutability.netlify.com

### ISSUE THREAD

**Issue by prestonso** [gatsbyjs/gatsby#14427]
This is a request from Marketing to:

- treat the current style guide as MVP and prepare it to be released to the public as v1.
- publish the style guide on gatsbyjs.org so that it can be referred to by contributors and external folks.

**Comment by prestonso** [comment]
This replaces gatsby-inc/mansion#3400.

**Comment by prestonso** [comment]
Pull request is open at #14360.

**Comment by marcysutton** [comment]
We should add a `/guidelines` landing page at some point. The PR includes a few pages for `/guidelines/color`, `/guidelines/logo`, `/guidelines/design-tokens/` and `/guidelines/typography`

**Comment by lannonbr** [comment]
@prestonso @fk So the guidelines pages are now live on .org, but as Marcy commented it may be useful to have a landing page too. That said, is this good to close now?

**Comment by fk** [comment]
Thanks Benjamin for giving this a bump! <3 🙏 

Shortly before merging #14360 we decided to "dark deploy" and not link it in the footer and navigation for now so that @lindaleebumblebee can give https://www.gatsbyjs.org/guidelines/logo/ a (hopefully pro-forma) look.

I'll get a PR up now that adds links to the individual pages (_Logo_, _Colors_, _Typography_, _Design Tokens_) from the https://www.gatsbyjs.org/contributing/ sidebar. Since there's no `gatsbyjs.org/guidelines/` yet, I want to suggest grouping them in a _Gatsby Brand Guidelines_ sidebar item for now. I'll also link as _Logo & Assets_ in the footer.

**Comment by fk** [comment]
#15016 has been merged, closing!
