### ISSUE TITLE
Is it possible for Gatsby to define browser globals during the rendering process?

### ISSUE THREAD

**Issue by jharrilim** [gatsbyjs/gatsby#14504]
## Summary

Currently, code that uses browser globals or anything related to the `window` object break during production/SSR builds in Gatsby. There are a bunch of other [issues](https://github.com/gatsbyjs/gatsby/issues?utf8=%E2%9C%93&q=is%3Aissue+window+undefined+) related to this.

Would it be possible for Gatsby to handle this by any means? Perhaps it would be possible to alleviate the issue by leveraging [jsdom](https://github.com/jsdom/jsdom) like the way [Jest](https://github.com/facebook/jest) does. I would like to hear your thoughts around this and how it can possibly handle `window`, or if not possible, why?

**Comment by jennasalau** [comment]
I'm literally looking at this too! Almost wish Gatsby just renders as a SPA instead.

**Comment by joeynimu** [comment]
This would be a good one. There are lots of issues related to this. I am also using a library that uses `window.customEvent` and I am stuck at fixing this for it's not so apparent to me.

**Comment by k-n-sk** [comment]
Yep, definitely need something to handle the window issues. I can only perform production builds if I wrap the libraries triggering errors with ```if (type of(window) !== undefined)```

**Comment by amimas** [comment]
Can this be reopened? It'd be really helpful if Gatsby could natively handle consumption of webcomponents. I'm trying to follow this doc but haven't been successful yet following the workarounds:

https://www.gatsbyjs.org/docs/using-client-side-only-packages/

**Comment by adonig** [comment]
I ran into this issue when I had to use Base64 encoding, because my image handler wants me to pass the JSON request as part of the url. Most browsers come with a global `btoa` function but Node.js doesn't, so the build fails. First I tried to write my own btoa function using Node's Buffer class, but it increases the bundle size by 6 kb, which equals around +10%. That's pretty much for such a simple thing as Base64 encoding. I thought about writing a simple TypeScript implementation of Base64, but then I found a package called [abab](https://github.com/jsdom/abab) which provides `btoa` and `atob` implementations and increases the bundle size only by 605 bytes. Nevertheless the best would be if there's a way to define certain globals during the build process. There probably is one, but I'm not really into webpack.

**Comment by Daavidaviid** [comment]
Hi,
I'm sure the solution I used is not "clean", but it's working.
I'm using an animation library (react-native-reanimated) in my gatsby project, and this library rely on `global.requestAnimationFrame `, so I mocked it like that in `gatsby-ssr.js` :

```
global.requestAnimationFrame = function (callback) {
  setTimeout(callback, 0);
};
```

And the production build is working.
