### ISSUE TITLE
Layout if statement possibly blocking SSR and in turn bad SEO

### ISSUE THREAD

**Issue by hihellosm** [gatsbyjs/gatsby#14503]
## Summary

I have a Gatsby website which as been live for over a month and am having issues getting it to rank on Google. It's currently not indexed at all! Upon adding the website to Google's Search Console it says that every URL is "excluded" by Google.

I've checked the site URLs in Screaming Frog and it all appears to be ok. So I'm quite confused.

My question is: Could a blocking check for the presence of `windowSize` early in the render of my `layout.js` be causing my SSR to basically be empty or never happen?

Simplified example:
```javascript
import { withWindowSizeListener } from 'react-window-size-listener';

class Layout extends React.Component {
	render() {
		const { children, windowSize } = this.props;

		if (!windowSize) return null;

		return (
			<p>Hello</p>
		);
	}
}

export default withWindowSizeListener(Layout);
```

I'm worried that the SSR render of the above would always be empty because of `if (!windowSize) return null;`

Anyone have any knowledge of this? 

Since my layout depends on knowing the window dimensions, is there another check I can do which ensures that SSR always proceeds. I'm thinking maybe `if (window && !windowSize) return null;`

This means that if no `window` exists it will just continue (for SSR). Otherwise if the window exists it requires that also the windowSize has been computed.

PS The site in question is [here →](https://ratioliving.com.au/)

**Comment by marcysutton** [comment]
@hihellosm your SSR rendering seems to be working fine–you can verify this by running a build with `gatsby build`, turning JavaScript off in your browser, and viewing source. I was able to view the source just now on your live site by turning JS off in my own browser. 

It's likely something else entirely causing your SEO issue, as Googlebot does use client-side scripting to crawl sites. Maybe there's an issue with what it perceives as canonical URLs or something? Does that content exist anywhere else?

**Comment by DSchau** [comment]
@hihellosm ^ Marcy is 💯 above, but wanted to add a few clarifying points.

You can validate the live site is statically rendering HTML by using curl, and then grepping for content. For example, to validate your site you could do:

```shell
curl https://ratioliving.com.au/ | grep "Find your balance"
```

and you can see it's returning HTML.

To your actual question though:

> I'm worried that the SSR render of the above would always be empty because of if (!windowSize) return null;

That utility exports a higher-order component that injects a `windowSize` prop. You'll note [in the code](https://github.com/kunokdev/react-window-size-listener/blob/master/src/index.js#L89-L117) that it returns a windowSize object, with windowSize.windowHeight and windowSize.windowWidth. Therefore, the `windowSize` conditional won't be triggered, so that check will be skipped.

In general -- you want to avoid rendering different content between SSR (Node.js at build time) and runtime, but you were "saved" here because the check wasn't returning null!

Hope that helps!
