### ISSUE TITLE
Site navigation creates increasingly detached DOM nodes

### ISSUE THREAD

**Issue by diegodorado** [gatsbyjs/gatsby#14525]
## Description

When I navigate to another page, new DOM nodes are created, but old one aren't disposed or even cached.

### Steps to reproduce

```bash
gatsby new gatsby-site
cd gatsby-site
```

Edit `index.js` and `page-2.js` to get as minimal as posible:
// index.js
```js
import React from "react"
import { Link } from "gatsby"
const IndexPage = () => (<Link to="/page-2/">Go to page 2</Link>)
export default IndexPage
```
// page-2.js
```js
import React from "react"
import { Link } from "gatsby"
const SecondPage = () => (<Link to="/">Go back to the homepage</Link>)
export default SecondPage
```

```bash
gatsby build
gatsby serve
```

Open `localhost:9000` on chrome, and open the  Performance Monitor.
Every time you click on the links, DOM Nodes increase (but never gets garbage collected)

### Expected result

DOM Nodes should remain more or less steady

### Actual result

DOM Nodes keeps increasing on each click

### Environment

  System:
    OS: Linux 4.15 Linux Mint 19 (Tara)
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Shell: 5.4.2 - /usr/bin/zsh
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.16.0 - ~/.nvm/versions/node/v10.15.3/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Languages:
    Python: 2.7.15 - /usr/bin/python
  Browsers:
    Chrome: 72.0.3626.119
    Firefox: 65.0.1
  npmPackages:
    gatsby: ^2.8.2 => 2.8.2 
    gatsby-image: ^2.1.2 => 2.1.2 
    gatsby-plugin-manifest: ^2.1.1 => 2.1.1 
    gatsby-plugin-offline: ^2.1.1 => 2.1.1 
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12 
    gatsby-plugin-sharp: ^2.1.3 => 2.1.3 
    gatsby-source-filesystem: ^2.0.38 => 2.0.38 
    gatsby-transformer-sharp: ^2.1.21 => 2.1.21 
  npmGlobalPackages:
    gatsby-cli: 2.6.4

**Comment by diegodorado** [comment]
Here's a gif showing this behaviour

![test](https://user-images.githubusercontent.com/208685/58842214-8db6a980-8643-11e9-9fde-0129fa0d5952.gif)

**Comment by KyleAMathews** [comment]
Hmmm that's no good. We've got a memory leak somewhere...

**Comment by phacks** [comment]
This has been discussed in a previous issue for reference: https://github.com/gatsbyjs/gatsby/issues/12198

I’m willing to work on this, any hints to where I should begin with?

**Comment by phacks** [comment]
Will try and work on it this weekend!

**Comment by diegodorado** [comment]
> Will try and work on it this weekend!

Let me know if I can be of any help.

**Comment by phacks** [comment]
Sooo, I dug around a bit, created a repro repo, managed to get some insights with the Chrome Dev Tools, however it appears my knowledge of the inner workings of Gatsby isn’t deep enough to know where to start 😅

What I did:

- Created a repro repository following @diegodorado’s repro: https://github.com/phacks/gatsby-memory-leak-repro. Bumped the number of `<a>`s to 10 so that it’s easier to see the impact.
- Played around with snapshots, and I noticed that the increased DOM size seems to come from “Detached DOM Nodes” :

_Before clicking on a link_:
![image](https://user-images.githubusercontent.com/2587348/59964627-5da44d00-9503-11e9-8db4-2acc3a72f0b4.png)

_After clicking on a link_:
![image](https://user-images.githubusercontent.com/2587348/59964640-790f5800-9503-11e9-8c84-bc16774ef506.png)

Per [this SO answer](), Detached DOM Nodes are:

> HTML elements are instance of objects that consume memory. Each such element can store on them event listeners and data associated with it. Now "Detached DOM Trees" are nothing but DOMs that are in the Browser's memory but are NOT attached to the main DOM tree aka "Document DOM Trees".

Hopefully this may help @diegodorado or someone else have some ideas about where to start!

**Comment by oorestisime** [comment]
I wonder whether this issue is related to https://github.com/facebook/react/pull/15157

**Comment by phacks** [comment]
@oorestisime Interesting issue, nice catch! 

When I patch, in the repro, `react-dom` by the [discordapp#react](https://github.com/discordapp/react/pull/1) suggested dirty fix (mentioned in https://github.com/facebook/react/pull/15157#issuecomment-503679734), no “Detached DOM Nodes” appear in subsequent snapshots, so it _seems_ to be _doing_ something.

However, the DOM Node counter is still increasing, which gets me even more perplex.

I updated the repro repo (https://github.com/phacks/gatsby-memory-leak-repro) to explain how to reproduce (and how to visualise) the leak, so hopefully it’ll be easier to help along.

To test out Discord’s hotfix, you may change the following in the `package.json`:

```diff
- "react-dom": "^16.8.6",
+ "react-dom": "discordapp/react#cfda84f6b3c49a1398709cf43b3b959366f7e01a",
```

**Comment by phacks** [comment]
Looks like a memory leak was [fixed](https://github.com/facebook/react/pull/16115) in React very recently (see [this long discussion](https://github.com/facebook/react/pull/15157#issuecomment-514775335) about the topic).

I’ll try and have a look this week to see whether that fixes the problem in Gatsby!

**Comment by phacks** [comment]
Update: tried running the [example repo](https://github.com/phacks/gatsby-memory-leak-repro) against the `master` branch of  `react` and `react-dom`, and it did not fix the memory leak.

**Comment by diegodorado** [comment]
Wow... seems to be hard to fix... does this means that this is not a react
issue but a gatsby issue?

**Comment by RyKilleen** [comment]
Jumping in to take a look at the repro repo to see if I can glean some insight from it!

**Comment by phacks** [comment]
Oops, I fixed the `IntersectionObserver` leak a while back but completely forgot to update this issue!

Your insight is spot on, you can see how it was fixed in this PR: https://github.com/gatsbyjs/gatsby/pull/17056

I’ll close the issue now to avoid further confusion, however if there’s another leak in there we can totally reopen it. Sorry about that @RyKilleen !

**Comment by RyKilleen** [comment]
@phacks no worries, it was fun to dig in! Glad to know my hunch was in the right direction!
