### ISSUE TITLE
Rename a file to be compatible with modclean

### ISSUE THREAD

**Issue by TomFreudenberg** [gatsbyjs/gatsby#14554]
Hi,

when using [ModClean](https://www.npmjs.com/package/modclean) to shrink the node_modules folder size, gatsby won't run anymore after using their _default:safe_ pattern.

This happens in case that gatsby's schema infer package will require a file called **example-value.js**

Link to source: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/schema/infer/index.js#L3

If the file could be just renamed like **schema-example-value.js** or **infer-example-value.js** modclean default pattern would work without problems.

Would you accept a PR for that change? 

It seemed easier and more senseful to do this change in the opposite of writing a separate pattern modules for modclean.

Thanks for some feedback
Tom

**Comment by TomFreudenberg** [comment]
Hi after checking more deeply the documentation of modclena - you may set an ignore pattern which will work.

``` bash
modclean -n default:safe --ignore="gatsby/**/schema/infer/example-value.js" --run
```

Maybe it is still something to think about renaming that file from an _example-_ file.

**Comment by wardpeet** [comment]
Thanks for taking the time to open up an issue about this. Sadly it's not a Gatsby issue and it is more something that needs to be fixed in modclean. Adding `example*` as a glob pattern isn't really "safe". They should do some additional checks, it also removes a `.eslintrc.json` from the cache-dir that might be problematic.

There is also the reason that we can't be sure we won't break modclean in future releases of Gatsby.

https://github.com/ModClean/modclean-patterns-default/blob/1f06be1da666c2ec0508c22e04e2f7058322bceb/patterns.json#L27

Sorry for the inconveniences it may cause

**Comment by TomFreudenberg** [comment]
Hi @wardpeet, thanks for your feedback.

I can take your points and it is still working for our usecase when using _--ignore_ as commented.

So for me its fine also to close this as answered.

Cheers
Tom

**Comment by wardpeet** [comment]
Thanks for understanding. :muscle:
