### ISSUE TITLE
Awesome list?

### ISSUE THREAD

**Issue by samburgers** [gatsbyjs/gatsby#1461]
Couldn't seem to find a Gatsby `awesome list` anywhere, any interest in maintaining one?

**Comment by KyleAMathews** [comment]
Soa new repo inside the gatsbyjs organization? That could work or if you want to get internet points, you could start one yourself :-)

We could pull it into gatsbyjs.org as well

**Comment by prayasht** [comment]
Great idea! I've started an awesome-list here, please send PRs if you have something to add!
https://github.com/prayasht/awesome-gatsby

**Comment by acomito** [comment]
are there any templates/themes marketplaces around for gatsby yet?

**Comment by benjaminhoffman** [comment]
super cool!  Thanks @prayasht for creating that list.  Closing this issue for now but feel free to open a PR with a link to your list (esp if you continue to keep it update to date!)

**Comment by prayasht** [comment]
Circling back to this since I now see an awesome-list on the official site [here](https://www.gatsbyjs.org/docs/awesome-gatsby/). I've got a running list at [awesome-gatsby](https://github.com/prayasht/awesome-gatsby) but not sure what to do with it. 

Should I make another PR to transfer what I have over to the official gatsby repo?

Thoughts, @KyleAMathews?

**Comment by KyleAMathews** [comment]
Yeah, would love if you could add your items!

**Comment by KyleAMathews** [comment]
I want to do most stuff on gatsbyjs.org as it'll be easier to find stuff plus we can make richer versions of stuff in a normal awesome page e.g. a showcase page which is searchable plus has screenshots of the site.
