### ISSUE TITLE
How to check an array with regular expression in GraphQL

### ISSUE THREAD

**Issue by Hypothesis-github** [gatsbyjs/gatsby#14615]
I need to check the existence of some elements in an array as such

I have an array as such

ar = ['one','two','three']

I want to know how I can individually check the elements in the regular expression code below instead of "/something/" that would map through my array and check if they exist in graphQL one by one.

```
similar : allCockpitHello (filter: {Association : {value : {regex: "\/something/" }}} limit:2){
      nodes{
        Name{
          value
        }
}
```

**Comment by DSchau** [comment]
@Hypothesis-github could you share a link to your project so that we can experiment most quickly with what you've already set up? See: [creating a reproduction](https://gatsby.dev/reproduction) for more info on how to do this.

In general, I would recommend the [GraphQL Reference](https://www.gatsbyjs.org/docs/graphql-reference/) page for some more assistance with this. It wouldn't allow regular expressions as far as I know, but you should be able to do something like:

```graphql
{
  usingIn: allCockpitHello(
    filter: {
      Association: {
        in: ["one", "two"]
      }
    }
  ) {
    # whatever
  }

  usingGlob: allCockpitHello(
    filter: {
      Association: {
        glob: "*something*"
      }
    }
  ) {
    # whatever
  }
}
```
