### ISSUE TITLE
.markdown files turned into .html

### ISSUE THREAD

**Issue by cluzier** [gatsbyjs/gatsby#14638]
I've recently decided to clone my repo of my blog off GitHub, it wasn't until I cloned it that I realized the file/folder structure was different than the last time that I uploaded and made changes to the site. 

originally the structure was as follows

```
posts
|_ article.markdown
|_ article2.markdown
|_ article3.markdown
```

but now that I've cloned it the structure is as follows

```
posts
|_article
    |_ article.html
|_article2
    |_ article2.html
|_article3
    |_ article3.html
```

Has anyone else had this issue before? 
Here is a link to my repo if you wanted to check it out(there are 2 branches, check them both out): https://github.com/cluzier/cluzier.github.io

**Comment by superhawk610** [comment]
Gatsby's hosting model involves generating a static HTML file structure matching your site's  routing layout to enable serverless routing. For example, if your source `pages` directory contains the following files:

```
src
|- pages
  |- page1.md
  |- page2.md
  |- page3.md
```

then when Gatsby builds your app it will mirror that structure with its generated HTML files:

```
src
|- public
  |- page1
    |- index.html
  |- page2
    |- index.html
  |- page3
    |- index.html
```

When you deploy, you just need to statically serve the `public` folder generated by `gatsby build` and whenever a user navigates to `yoursite.com/page2`, they will be served the generated HTML file from `src/public/page2/index.html` containing a prerendered version of that page's content and a script for hydrating the rest of your SPA.

Since you're hosting with GitHub Pages and they require the root directory of your site to be the root of your repo, it looks like you've moved the contents of `public` directly to the root directory on `master` - you should never have to edit these files directly, you should edit your markdown files and then rerun `gatsby build`. For deploys via GitHub Pages I usually recommend keeping your source files (markdown, etc) in `master` (you currently have them in the `core-files` branch) and then pushing your build output to a separate `gh-pages` branch that only contains generated files. You can read more on the recommended method [here](https://www.gatsbyjs.org/docs/how-gatsby-works-with-github-pages/).

If you need any other help with developing or deploying with Gatsby, be sure to check out our [Spectrum](https://spectrum.chat/gatsby-js) community. Thanks for building with Gatsby!
