### ISSUE TITLE
GraphQL Error There was an error while compiling your site's GraphQL queries.   Error: RelayParser: Encountered duplicate defintitions for one or more documents: each document must have a unique name. Duplicated documents: - cUsersGuimo000DesktopDevReactCubitFoxSrcPagesBlogJs3560622269     

### ISSUE THREAD

**Issue by ZolderonGitHub** [gatsbyjs/gatsby#14820]
hello i start to use gatsby yesterday with this tutorial : [https://www.youtube.com/watch?v=8t0vNu2fCCM](url)

at 2:17:00 that's work for him but me i have this error:

>GraphQL Error There was an error while compiling your site's GraphQL queries.   Error: RelayParser: Encountered duplicate defintitions for one or more documents: each document must have a unique name. Duplicated documents: - cUsersGuimo000DesktopDevReactCubitFoxSrcPagesBlogJs3560622269     

and i don't see why, here's is my blog.js file : [https://github.com/ZolderonGitHub/Zolder-Website/blob/master/blog.js](url)

**Comment by sidharthachatterjee** [comment]
Thank you for opening this @ZolderonGitHub 

I checked out the timestamp in the linked video and saw the file you linked to but we'll need a little more information to be able to help you with this. 

1. Can you push your entire site and link to it? The issue could be due to several things (like in this case it seems like multiple files with the same name)
2. Can you elaborate on what you did that led to the error? It wasn't clear from the video since it seems he is adding some JSX in 2:17:00

**Comment by ZolderonGitHub** [comment]
I have an error when i try to push in a repo and the problem is from the query.
I have test the blog project official in gatsby: https://www.gatsbyjs.org/starters/gatsbyjs/gatsby-starter-blog/ and i have the same problem
