### ISSUE TITLE
delete html and css files from previous builds

### ISSUE THREAD

**Issue by bjatwork** [gatsbyjs/gatsby#14845]
i want to make shop on gatsby. 
There is about 15 k products and build takes about 10 min. 

Since gatsby delete files and after that create new files my shop is unavialbele 10 mintus to users after each update starts. 

I Want make new build every one hour. 
How prevent deliting files?

Or how i make gatsby to work this way: 
1. make new build to "public_temp" 
2. (after build went well) rename "public" to "public_old" 
3. rename "public_temp" to "public" 
4. then delete "public_old" 
?

**Comment by sidharthachatterjee** [comment]
> Or how i make gatsby to work this way:
> 
> make new build to "public_temp"
> (after build went well) rename "public" to "public_old"
> rename "public_temp" to "public"
> then delete "public_old"
> ?
> 

You could run `gatsby build` in a separate folder from the one that is being served. Write a script that runs `gatsby build`, then copies over the `public` directory to the location where you serve your assets from. 

Closing this issue for the moment since this is tangential to gatsby itself. Hope this was useful! Thank you for using Gatsby 💪 💜
