### ISSUE TITLE
setWebpackConfig not setting values as expected

### ISSUE THREAD

**Issue by herecydev** [gatsbyjs/gatsby#14882]
## Summary

I expect the following:

```js
exports.onCreateWebpackConfig = ({ stage, actions}) => {
actions.setWebpackConfig({
    resolve: {
      extensions: [".foo"]
    },
  })
}
```

To only resolve ".foo" files when webpack is resolving modules. It actually looks like the setWebpackConfig is adding foo on to the end of the existing (default) list. So you end up with something similar to:

 ['.mjs', '.wasm', '.js', '.jsx', '.json', '.foo' ]

If that's intended/how it **is** working at the moment... that's really not intuitive or well described. Especially the outcome of using [webpack extensions](https://webpack.js.org/configuration/resolve/#resolveextensions) is to **change** the priority in which files are chosen. Current behavior means that .js will always take precedence as additional extensions are placed at the lower priority side of the array.

## Workaround?

This is what I'm currently doing to overcome this

```js
exports.onCreateWebpackConfig = ({ stage, actions, getConfig }) => {
  let config = getConfig()
  config.resolve.extensions = ['.mjs', '.wasm', '.json', ".foo", '.js', '.jsx', ],
  actions.replaceWebpackConfig(config)
}
```

**Comment by freiksenet** [comment]
Hello @herecydev!

In the [action documentation](https://www.gatsbyjs.org/docs/actions/#setWebpackConfig) it says:

```Merge additional configuration into the current webpack config.```

Therefore this is an expected behaviour and your workaround is indeed the way we recommend solving this issue. 

I'm closing this as we won't be changing this behaviour. Feel free to open it if you have any more questions. Thank you for using Gatsby! :purple_heart: :muscle:
