### ISSUE TITLE
[docs] add doc on "Life and Times of a Gatsby Build"

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#14937]
## Summary

Through feedback provided on gatsbyjs.org, it has become clear that the stub article on Life and Times of a Gatsby Build is an important one that needs filling out to explain Gatsby concepts: https://www.gatsbyjs.org/docs/life-and-times-of-a-gatsby-build/

> "This is possibly the most important page and it's empty!"

This page is a stub in the [Conceptual Guide](https://www.gatsbyjs.org/docs/conceptual-guide/) section, and would be a great opportunity to clarify what happens at build time vs. runtime. I couldn't find a GitHub issue for it, so I created this one to capture it as something we need.

There was a related question about the doc on [Client Data Fetching](https://www.gatsbyjs.org/docs/client-data-fetching/), which assumes a lot of knowledge about build time vs. runtime processes. A dedicated doc on this would be very helpful, and this seems like a good one.

**Comment by m-allanson** [comment]
I made a start on this, but didn't get to the main "what's actually happening" section. Posting here in case someone else gets to this before me.

--- 

# Life and Times of a Gatsby Build
## Building with Gatsby
Gatsby is a framework for creating web sites and web apps. As part of creating your site you’ll provide Gatsby with the code, configuration and data it needs to output a speedy, optimised site.

When working with Gatsby it has two modes. You can start gatsby in either mode by running `gatsby develop` or `gatsby build`.

### gatsby develop 
Gatsby develop is optimised for rapid feedback and extra debugging information. 

Using `gatsby develop` runs a server in the background enabling useful features like hot reloading and Gatsby’s data explorer.

### gatsby  build 
You’ve added the finishing touches to your site and everything looks great. What now? This is where the build step comes in. Run `gatsby build` to create a version of your site with 

will package up your site’s config, data, and code then optimise the heck out of it, and finally 


## What happens when you run `gatsby build`
This is a high-level overview. For more detailed information, check TODO, TODO, TODO.

**Comment by alexluong** [comment]
I happened to write a blog post covering this topic. It's a bit more anecdotal as I describes what's going on with codes, but I think some part of it can be recycled to a documentation page.

If you're interested, you can find it [here](https://www.notion.so/alexluongg/A-Journey-Through-Gatsby-Build-Process-via-Building-a-Plugin-10eb8112478844ed9ba4759804e9821b).

Would love to hear your thoughts on it and hope that it helps writing this doc!
