### ISSUE TITLE
Firing Custom Events

### ISSUE THREAD

**Issue by daningamells** [gatsbyjs/gatsby#15001]
Hey all,

I'm having an issue firing custom events for Analytics in Gatsby, this is how I'm doing it:

  componentWillMount() {
    var event= new CustomEvent('event-view-start');
    var obj = document.dispatchEvent(event);
  }

Everything works great when I use Gatsby Develop but when I go to build my application I get this:

**WebpackError: ReferenceError: CustomEvent is not defined** and the build fails.

Thanks

Dan

**Comment by lourd** [comment]
Have you tried dispatching a normal `Event` as a workaround?

**Comment by daningamells** [comment]
You mean like this?

componentWillMount() {
var event= new Event('event-view-start');
var obj = document.dispatchEvent(event);
}

If so, I used this but got the same error on Gatsby Build.

**Comment by jonniebigodes** [comment]
@daningamells as Gatsby is built with node, some apis  are not available at build time.
Based on your information, here are the steps i took and my results.
- Created a new Gatsby website based on the hello world starter.
- Created a new page called `about.js` inside the the pages folder with the following content:
```javascript
import React,{Component} from 'react';


class About extends Component{

    componentDidMount(){
        if (typeof window!=='undefined'){
            const event= new CustomEvent('event-view-start');
            document.dispatchEvent(event)
        }
    }
    render(){
        return(
            <>
                <h1>This is a dummy page</h1>
                <h3>this is some content</h3>
            </>
        )
    }
}

export default About
```
- Issued `gatsby build` to get a production build and i'm presented with the following:
![daningamells](https://user-images.githubusercontent.com/22988955/59951243-2f296200-9470-11e9-8b25-7c552c9a7c8e.png)

As you can see the error did not show, but so far i'm unable to check if this will actually be fired. What i would like is modify the code and test it to see if the event is picked up and you don't get build errors.

Feel free to provide feedback so that this issue can be closed or continue to work on it so that we can find a solution

**Comment by daningamells** [comment]
Hey Jonnie,

That worked perfectly!!!!

Thank you so much for taking the time to figure this out (I was one step away from banging head off the wall).

Dan
