### ISSUE TITLE
'env-cmd' is not recognized as an internal or external command and can't start gatsby file

### ISSUE THREAD

**Issue by DinaShantina** [gatsbyjs/gatsby#15025]
## Description

I have a problem 
'env-cmd' is not recognized as an internal or external command
My Gatsby site is not starting and it was working, before few minutes everything was ok. 
Someone maybe know what can be the issue? 

### Steps to reproduce
[https://github.com/DinaShantina/gatsby-shanti-hostel]

**Comment by sidharthachatterjee** [comment]
Hey @DinaShantina 

It looks like maybe `env-cmd` isn't installed? Can you try deleting `node_modules` and installing them again? 

Also, you could try replacing `"develop_env_cmd": "env-cmd -f gatsby develop"` in https://github.com/DinaShantina/gatsby-shanti-hostel/blob/master/package.json#L12 to `"develop_env_cmd": "./node_modules/.bin/env-cmd -f gatsby develop"`

Since this seems tangential to Gatsby, we will be closing this out for now! Please feel free to open in case there is anything else that we can help with.

**Comment by saqlain455** [comment]
run this command
npm i env-cmd

**Comment by Mahendra-graas** [comment]
it can node version issue, version can be changed using nvm
