### ISSUE TITLE
 Using the #title in the MD file does not seem to work.

### ISSUE THREAD

**Issue by 97thjingba** [gatsbyjs/gatsby#15042]
![image](https://user-images.githubusercontent.com/39749571/59960773-c5f12f80-94ff-11e9-8aa5-48cb01f57b8b.png)
![image](https://user-images.githubusercontent.com/39749571/59960776-d1dcf180-94ff-11e9-9193-d3c246d8d7f6.png)

![image](https://user-images.githubusercontent.com/39749571/59960781-e1f4d100-94ff-11e9-80fe-7e3bbcd0a0ac.png)

**Comment by robinmetral** [comment]
Hi @97thjingba, if you're referring to [this page](https://elated-lewin-51cf0d.netlify.com/blog4/blog-4/), it looks like the Markdown is correctly parsed and renders an `h1`:

| Screenshot from Firefox devtools |
| --- |
| ![screenshot](https://user-images.githubusercontent.com/35560568/59979080-302ed080-95e3-11e9-9e13-ac9f9116a70a.png) |

Your problem is caused by the Bulma stylesheet you're importing.

As a CSS framework, Bulma starts by [resetting default CSS](https://en.wikipedia.org/wiki/Reset_style_sheet), including heading styles and font sizes, for consistency. More specifically, heading styles are reset at [these lines](https://github.com/jgthms/bulma/blob/412bef468fbc057cf495810e5abe81a3fc9ff20c/sass/base/minireset.sass#L29-L37) in the Bulma codebase.

This is where your `h1` element is given a `font-size` of `100%` and a `font-weight` of `400`.

If you would like to use Bulma, you need to make sure you're using the [Bulma Title element](https://bulma.io/documentation/elements/title/) for your headings.

I would recommend taking a look at the [Gatsby with Bulma docs](https://www.gatsbyjs.org/docs/bulma/), or at any of the [Gatsby starters using Bulma](https://www.gatsbyjs.org/starters/?c=Styling%3ABulma&v=2) to see real examples of working with this stack.

Let me know if this helped :slightly_smiling_face:

**Comment by 97thjingba** [comment]
Thank you very much, I found the problem, it is indeed the CSS reorganization caused by Bulma. I am trying my best to find a new way to replace Bulma. I have not read the documentation of Gatsby seriously before, thank you. I will read it carefully. Thank you for visiting the blog that I started to write. @robinmetral

**Comment by 97thjingba** [comment]
I still haven't replaced Bulma, but I rewrote an **H1 style in the CSS file,** which looks very effective.

![image](https://user-images.githubusercontent.com/39749571/59993503-07f6ae80-9683-11e9-8196-4f2b5d6b45bb.png)

![image](https://user-images.githubusercontent.com/39749571/59993508-0dec8f80-9683-11e9-8d36-f266c67cf6cd.png)

**Comment by robinmetral** [comment]
Glad to hear this solved your problem! Enjoy Gatsby :slightly_smiling_face:
