### ISSUE TITLE
Divide pages into small component's folders.

### ISSUE THREAD

**Issue by magdalena-dering** [gatsbyjs/gatsby#15107]
Hi,
First of all, thank you for your time.
I want to divide pages into components to keep separate styles, data and component.
[Showcase](http://prntscr.com/o6d5iu)

- pages 
-     components 
-                404.jsx (React component) 
-                404Data.jsx (GraphQL)
-     styles.js (Styled components)
-     index.js (export { default } from "./components/404Data";)

## Description
I want to have the same plan/ tree of folders as I have in components folders:
[link](https://github.com/magdalena-dering/megportfolio/tree/master/src/components)

### Steps to reproduce

`yarn build` reproduce an error:
``` 
error [C:/Users/Magdalena/www/js/react/megportfolio/src/pages/404.jsx] The page component must export a React component for it to be valid
⠋ createPagesStatefully

```

### Expected result
I want to have the same plan of the folder as I have in the **components** folders. Is it a good way to keep them separate? I want to keep the Separation Of Concerns pattern as much as I can.

### Actual result
The view on localhost is working fine, after `yarn build` I have got an error which I mentioned above.

### Environment

```
  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
  Binaries:
    Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.7.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    gatsby: ^2.0.33 => 2.9.0
    gatsby-cli: ^2.6.5 => 2.6.5
    gatsby-image: ^2.1.2 => 2.1.3
    gatsby-plugin-offline: ^2.1.1 => 2.1.1
    gatsby-plugin-react-helmet: ^3.0.4 => 3.0.12
    gatsby-plugin-sass: ^2.0.7 => 2.0.11
    gatsby-plugin-sharp: ^2.1.3 => 2.1.3
    gatsby-plugin-styled-components: ^3.0.7 => 3.0.7
    gatsby-remark-external-links: ^0.0.4 => 0.0.4
    gatsby-remark-prismjs: ^3.2.9 => 3.2.11
    gatsby-source-filesystem: ^2.0.38 => 2.0.39
    gatsby-transformer-json: ^2.1.6 => 2.1.11
    gatsby-transformer-remark: ^2.3.12 => 2.3.12
    gatsby-transformer-sharp: ^2.1.21 => 2.1.21

```

**Comment by freiksenet** [comment]
Hi @magdalena-dering!

Sorry to hear you are having an issue!

First of all, the re-export that you are doing in `pages/404.js` is not correct. To re-export default from the file, you need to use

```js
export default from "./404/components/404Data"
```

However, even with this you'll have a similar error about `styles.js`. This is because all files in `pages` folder in Gatsby are processed as "pages", therefore you can't have any non-page components there. I recommend that you put all `404` related components and styles into `components/404` folder outside of the page folder and only use `page` folder for pages.

Hope this helps! :purple_heart: :muscle:

**Comment by magdalena-dering** [comment]
Yes, this helps a lot.
Thank you. :)
