### ISSUE TITLE
error GraphQL Error  

### ISSUE THREAD

**Issue by bjatwork** [gatsbyjs/gatsby#15130]
getting a error

`error GraphQL Error Variable "$id" of type "Int!" used in position expecting type "String".

```
     query($id: Int!, $limit: Int!, $skip: Int!) {
        ^
  category(category_id: {eq: $id}) {`
```

My schema

` rootKey: "category",   schemas: {  category: `   category_id: Int! .... `

This error does not appear when I define in schema "category_id: String!" and I will use the query "query ($ id: String !, $ limit: Int !, $ skip: Int!) {"

It works without a problem with "String", but if I use "String!" instead of "Int!" in schema and "query ( ..", does it slow down queries (gatsby build)?

I use "gatsby-source-custom-api"

**Comment by sidharthachatterjee** [comment]
> It works without a problem with "String", but if I use "String!" instead of "Int!" in schema and "query ( ..", does it slow down queries (gatsby build)?

I wouldn't worry too much about slowing down queries but I would prefer that we use the right data type! 

> This error does not appear when I define in schema "category_id: String!" and I will use the query "query ($ id: String !, $ limit: Int !, $ skip: Int!) {"

This does seem strange though 🤔 @freiksenet Any ideas?

**Comment by wardpeet** [comment]
Hey again!

It’s been 30 days since anything happened on this issue, so our friendly neighborhood robot (that’s me!) is going to close it.

Please keep in mind that I’m only a robot, so if I’ve closed this issue in error, I’m HUMAN_EMOTION_SORRY. Please feel free to reopen this issue or create a new one if you need anything else.

Thanks again for being part of the Gatsby community!
