### ISSUE TITLE
Improve title for /how-to-make-a-reproducible-test-case

### ISSUE THREAD

**Issue by sidharthachatterjee** [gatsbyjs/gatsby#15147]
Improve title and SEO for https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/

Maybe it needs to be called "How to make a minimal reproduction"

**Comment by marcysutton** [comment]
I was going to close this as there has been a PR merged, but I think the rest of the text should be revisited in addition to the title to optimize for on-page content and flow. Should we rename the file and add a redirect too? Because now the title and URL don’t match. What was the motivation to change the title, and how can we measure success here?

**Comment by gillkyle** [comment]
Good points @marcysutton, in this particular case we might find ourselves in a case of pre-optimizing too much, since this guide is mostly just linked to and the SEO difference might be trivial. I think you're right that it probably is confusing to have a different URL and link in the sidebar than the actual title on the page though. 

Maybe we have some analytics we could track on this kind of thing for other guides and tutorials though.

**Comment by marcysutton** [comment]
Going to close this as it's outdated now!
