### ISSUE TITLE
dynamic robots.txt with gatsby

### ISSUE THREAD

**Issue by khus29** [gatsbyjs/gatsby#15141]
I have a requirement to fetch domain name from contentful CT via a graphql query. Plugins I am using from graphql query is gatsby-source-graphql. 
Current implementation is below 
_{
      resolve: 'gatsby-plugin-robots-txt',
      options: {
        policy: [{ userAgent: '*', allow: '/' }],
        query: `{
          site: mySite {
            siteMetadata {
              siteUrl
            }
          }
        }`
      }
    },_
It is working fine now.
But I am not sure if we can fetch domain(siteUrl) name dynamically. Please help.

**Comment by prestonso** [comment]
Hi @khus29!

Thank you for reporting this issue! I see that you've said it's working fine now, but could you be a bit more specific about what you're trying to achieve?

In addition, to help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction](http://gatsby.dev/reproduction). This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction](http://gatsby.dev/reproduction) and we'll be able to take another look.

Thanks for using Gatsby! 💜

**Comment by khus29** [comment]
I have solved this issue. I am querying CT while build run and updating siteMetaData using onCreateNode lifecycle methods. We can close this issue.
Thanks.
