### ISSUE TITLE
[bug] Route components are mixed up after refreshing

### ISSUE THREAD

**Issue by tabneib** [gatsbyjs/gatsby#15159]
## Description
* In production: client-side routing works perfectly well until we refresh the page. If the current path is not root, say "/foo", the rendered page is a mixture of the the Route component for root "/" and the Route component for "/foo".
* In development: this issue does not exist.

### Steps to reproduce

I have setup a repo to illustrate this issue:
[https://github.com/tabneib/gatsby-router-issue
](https://github.com/tabneib/gatsby-router-issue
)
The sample application is found at 
[https://gatsby-router-issue.web.app
](https://gatsby-router-issue.web.app
)

Step 1: Navigate to the sample app
Step 2: Click on "Issue Page"
Step 3: Refresh page

### Expected result

The background color of the h1 text should be white when user navigates directly to [https://gatsby-router-issue.web.app/issue](https://gatsby-router-issue.web.app/issue) or when user refreshes the page.

### Actual result

The background color of the h1 text is red which is the background color of the h1 header of the Route component for "/"  [https://gatsby-router-issue.web.app](https://gatsby-router-issue.web.app).
However the content of the h1 text is still correct, it is just the style of the corresponding div-container being mixed up with other component.

### Environment

  System:
    OS: Linux 5.0 Ubuntu 19.04 (Disco Dingo)
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 10.15.2 - /usr/bin/node
    Yarn: 1.16.0 - /usr/bin/yarn
    npm: 5.8.0 - /usr/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 74.0.3729.169
    Firefox: 67.0.4
  npmPackages:
    gatsby: ^2.10.4 => 2.10.5 
    gatsby-image: ^2.1.0 => 2.2.3 
    gatsby-plugin-create-client-paths: ^2.0.5 => 2.1.1 
    gatsby-plugin-favicon: ^3.1.6 => 3.1.6 
    gatsby-plugin-manifest: ^2.1.1 => 2.2.0 
    gatsby-plugin-offline: ^2.1.1 => 2.2.0 
    gatsby-plugin-react-helmet: ^3.0.12 => 3.1.0 
    gatsby-plugin-tslint: 0.0.2 => 0.0.2 
    gatsby-plugin-typescript: ^2.0.14 => 2.1.0 
    gatsby-source-filesystem: ^2.0.37 => 2.1.1 
    gatsby-transformer-sharp: ^2.1.19 => 2.2.0

**Comment by NicklasKnell** [comment]
Are there any updates on this?

**Comment by 0tho** [comment]
Perhaps this could be caused by SSR rehydratation?

During development as far as I know gatsby does not trigger the SSR cycle and thus does not use the built files for rehydratating react, but when you build gatsby it will.

I believe react is rehydratating the page with the '/' componet and then loading '/issue', and for some reason it is only updating the <h1> element and not the parent <div>

I might be wrong though

**Comment by allforabit** [comment]
I'm having the same issue as this. Has anyone found any workarounds?

**Comment by tabneib** [comment]
We still suffer the bug and are considering downgrading gatsby.

**Comment by allforabit** [comment]
This seems to fix the issue (by disabling ssr):
```
exports.replaceRenderer = ({ replaceBodyHTMLString }) => {
  replaceBodyHTMLString('<div id="___gatsby"></div>');
};
```
(added to gatsby-ssr.js).

However I'm still getting a white screen when I enable the offline plugin.

**Comment by allforabit** [comment]
Actually my issue is a separate one it seems. I tried out the fix I suggested on @tabneib's test repo and it seems to fix the issue. Obviously at the cost of disabling ssr. This may be acceptable as a temporary workaround because ssr is not likely to be as important for a more clientside oriented app.

**Comment by tabneib** [comment]
I have updated the pipeline with the hard-coded workaround mentioned by @allforabit and the issue seems to be solved now. The workaround is this two lines: https://github.com/tabneib/gatsby-router-issue/blob/a0b32b7ebcbe8ab371a610a07d253545cf8c111d/.travis.yml#L8

Btw, the app deployed at https://gatsby-router-issue.web.app does not illustrate the issue any more.

**Comment by zcmgyu** [comment]
This issue still can reproduce on v2.23.12.
A workaround of @allforabit temporarily worked for me.

**Comment by jordan-arteaga** [comment]
I'm facing the same issue (gatsby 2.24.11), does anyone knows if it's solved in some version? Or the only way is use the solution provided by @allforabit ?

**Comment by geekdaniels** [comment]
I am currently facing this issue. Is there a working fix for this?

**Comment by ccssmnn** [comment]
I was experiencing the same issue recently and came to this issue after eliminating other factors. The reason is rehydration.

When react applies rehydration to your page, the state of the app is assumed to be equal to the state when the page was rendered on the server. Client Side Routing renders on the default page on the server. Reloading in a nested client route can lead to incorrect rehydration. Because we are using the production build, error warnings are suppressed. 

The solution is to return `null` whenever the state might be unknown client side. When using `@reach/router` this means to return `null` unless you are mounted and return `<Router>...</Router>` after mounting. An example:

```typescript
...imports

const Page: React.FC = () => {
  const [hasMounted, setHasMounted] = React.useState(false);
  React.useEffect(() => {
    setHasMounted(true);
  }, []);
  return (
    <div>
      <NavBar/>
      {!hasMounted ? null : (
        <Router basepath="/demo">
          <Home path="/" />
          <Account path="/account" />
          <Issue path="/issue" />
        </Router>
      )}
    </div>
  );
};

export default Page;
```
Here the matching path is not known when statically generated. After rehydration, we will trigger a rerender, because the effect fires. No more rehydration issues in that case.

Many thanks to [this article](https://www.joshwcomeau.com/react/the-perils-of-rehydration/) by @joshwcomeau !

We should add this to Gatsby's documentation for [client-only routes](https://www.gatsbyjs.com/docs/how-to/routing/client-only-routes-and-user-authentication/).

**Comment by zcmgyu** [comment]
Maybe relevant

https://stackoverflow.com/questions/52051090/gatsbyjs-client-only-paths-goes-to-404-page-when-the-url-is-directly-accessed-in
