### ISSUE TITLE
[docs] React hydration mismatch 

### ISSUE THREAD

**Issue by sidharthachatterjee** [gatsbyjs/gatsby#15150]
We've seen several issues (like https://github.com/gatsbyjs/gatsby/issues/15033) where hydration tends to break something and therefore develop and build aren't the same. 

We should probably document this better in https://www.gatsbyjs.org/docs/debugging-html-builds/

What do you think @gatsbyjs/docs?

**Comment by elliotdickison** [comment]
I would appreciate this. I just ran into it twice, and not having experience a hydration issue before was pretty concerned the way React was just falling flat on its face without error.

For the record, my first problem was depending on Gatsby's `location` object for the first render pass. On the server `location.hash` was empty (as you would expect) but on the client it was set. This was particularly surprising because Gatsby provides the location via a nice API, so I assumed it was safe to use. My second problem was referencing localstorage for the first render pass. This one was definitely more my fault because I had it wrapped in a try/catch since I knew it would fail during pre-rendering 😬.

**Comment by k-conway** [comment]
I can take this if you folks are looking for help! no worries if not!

**Comment by marcysutton** [comment]
@k-conway yes, I'd say go for it!

**Comment by k-conway** [comment]
will do!
