### ISSUE TITLE
Question regarding integrating gatsby-plugin-google-tagmanager

### ISSUE THREAD

**Issue by zohaib10** [gatsbyjs/gatsby#15166]
I am having a bit of trouble with gatsby-plugin-google-tagmanager integration into my app. Im very new to gatsby & react

  Useful Links:
  - Documentation: https://www.gatsbyjs.org/packages/gatsby-plugin-google-tagmanager/
 
I followed this link and have added the plugin into my gatsby-config.js file. Once adding the appropriate id I set includeInDevelopment: true, so I am able to test this locally.  

Once I start my local server I get ```Uncaught SyntaxError: Unexpected token <``` error, with a link (https://localhost:8000/app/%E2%80%9Chttps://static.zdassets.com/ekr/snippet.js) the link also includes a key. 

Questions: 
1) The solution might be really simple but can someone explain why I am getting this error? 2) How can I solve this? 
3) Also to integrate gatsby do I just add the gatsby-plugin-google-tagmanager plugin or do I also need to add the script that the Tag manager gives us?

Note: I don't get this error when I am using my personal account. It only occurs when I use my company's workspace.

**Comment by prestonso** [comment]
Hi @zohaib10!

Sorry to hear you're running into this issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction](https://gatsby.dev/reproduction). 

This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction](https://gatsby.dev/reproduction) and we'll be able to take another look.

Thanks for using Gatsby! 💜
