### ISSUE TITLE
use yarn in package.json if selected as package manager

### ISSUE THREAD

**Issue by EverlastingBugstopper** [gatsbyjs/gatsby#15421]
## Description

When a new project is generated from the cli and `yarn` is selected as the package manager, the `start` script in package.json calls `develop` with `npm`.

### Steps to reproduce

Just `gatsby new my-project`, select `yarn` and inspect `package.json`

### Expected result

`start` script uses `yarn`

### Actual result

`start` script uses `npm`

### Environment

```
  System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 11.9.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.8.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 75.0.3770.100
    Firefox: 62.0
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.13.3 => 2.13.3 
    gatsby-image: ^2.2.4 => 2.2.4 
    gatsby-plugin-manifest: ^2.2.1 => 2.2.1 
    gatsby-plugin-offline: ^2.2.0 => 2.2.0 
    gatsby-plugin-react-helmet: ^3.1.0 => 3.1.0 
    gatsby-plugin-sharp: ^2.2.2 => 2.2.2 
    gatsby-source-filesystem: ^2.1.2 => 2.1.2 
    gatsby-transformer-sharp: ^2.2.1 => 2.2.1 
```

**Comment by moonmeister** [comment]
I'm wondering if there is a reason start calls npm explicitly instead of just calling `gatsby develop` directly. Seems strange, thanks for catching this. Maybe someone in the @gatsbyjs/core knows if this was just overlooked or there for a reason.

**Comment by wardpeet** [comment]
no real reason, "start" is an alias for the develop script. We could replace "NPM" into yarn with a regex replace or we could explicitly set `gatsby develop`.

**Comment by sidharthachatterjee** [comment]
The package manager selection has to do with picking which one to install dependencies with (and which lock file to persist as a result) 

As far as I know `yarn run develop` and `npm run develop` shouldn't have any perceivable difference. 

> I'm wondering if there is a reason start calls npm explicitly instead of just calling gatsby develop directly

Just an alias to the `develop` script like @wardpeet mentioned. 

Since the `package.json` file comes from the starter the user uses, the CLI will have to update this after cloning and I don't think the effort in managing this in the CLI is worth the minimal (and vanity only) benefit in my opinion. 

Closing this as a non issue as a result but please feel free to comment or reopen if you disagree or would like to continue discussing this. And thank you for pointing it out nonetheless @EverlastingBugstopper 🙂
