### ISSUE TITLE
Code Splitting Like NextJS

### ISSUE THREAD

**Issue by zappys** [gatsbyjs/gatsby#15425]
Hello 

I'm porting a website from NextJS to Gatsby and i run into some issues with code splitting. 

The website is an e-commerce app that has a lot of logic in a Checkout modal. Normally i want to load these components only after the initial payload as they are not visible in any page because this is a modal. 

In NextJS i was doing this - https://nextjs.org/docs#dynamic-import
```js
const CartModal = dynamic(() => import("../components/CartModal"), {
  ssr: false,
  loading: () => <div> Loading ... </div>
});
```

In Gatsby i'm trying this using react-loadable (which is used by NextJS as well)
```js
const CartModal = Loadable({
  loader: () => import("../components/CartModal"),
  loading: () => <div> Loading ... </div>,
})
```

It works but the initial payload is the same size as not loading the component dynamically. Most likely component code is in the same file as the entire page. 

I tried using loadable-components as well but i get the same result.

**Comment by thomkrupa** [comment]
Aren't prefetching/preloading modules something you are looking for?
Here is an example https://github.com/gatsbyjs/gatsby/tree/master/examples/using-prefetching-preloading-modules

**Comment by slorber** [comment]
Hi

As far as I understand, in webpack 4 you give him heuristics for doing the code splitting, and webpack tries its best to do it. If a module is loaded dynamically does not guarantee that webpack will code split it, but you can fine tune the config to help him do so.

Webpack by default will try to make sure not too much requests need to be triggered on app startup

You may find this issue useful: https://github.com/gatsbyjs/gatsby/issues/16661

**Comment by wardpeet** [comment]
Hi @zappys!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a minimal reproduction. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could provide a minimal reproduction and we'll be able to take another look.

Thanks for using Gatsby! 💜
