### ISSUE TITLE
`runQuery` does not support `limit`

### ISSUE THREAD

**Issue by coreyward** [gatsbyjs/gatsby#15453]
## Description

According to [this documentation](https://www.gatsbyjs.org/docs/node-model/#runQuery), `runQuery` (e.g. `context.nodeModel.runQuery`) accepts an object argument with a `query` property that accepts `limit` (along with `filter`, `sort`, and `skip`), but passing it doesn't actually limit the result count.

I assume that since I haven't set `GATSBY_DB_NODES` I'm running the redux backend; presumably the `limit` option would be implemented in this function, but I only see `filter`, `sort`, `group`, and `distinct` being destructured and handled:

https://github.com/gatsbyjs/gatsby/blob/e423cb23c390ad751e59cfe3f5bef07621c2fdca/packages/gatsby/src/redux/run-sift.js#L107-L146

### Steps to reproduce

```js
exports.createResolvers = ({ createResolvers }) => {
  createResolvers({
    BlogPosts: {
      otherPosts: {
        type: ["BlogPost"],
        resolve: (source, args, context, info) =>
          context.nodeModel.runQuery({
            query: {
              filter: { id: { ne: source.id } },
              limit: 5
            },
            type: "BlogPost"
          })
      }
    }
  })
}
```

### Expected result

`otherPosts` field should be limited to `5` posts

### Actual result

The limit appears to be ignored; `otherPosts` will contain all matching (i.e. not filtered out) posts.

### Environment

  System:
    OS: macOS 10.14.4
  Binaries:
    Node: 12.1.0 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  npmPackages:
    gatsby: ^2.6.0 => 2.13.3 
    gatsby-image: ^2.0.38 => 2.2.4 
    gatsby-plugin-emotion: ^4.0.1 => 4.1.0 
    gatsby-plugin-react-helmet: ^3.0.1 => 3.1.0 
    gatsby-plugin-segment-analytics: ^0.2.1 => 0.2.1 
    gatsby-plugin-sharp: ^2.1.1 => 2.2.2 
    gatsby-plugin-svgr: ^2.0.2 => 2.0.2 
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4 
    gatsby-source-contentful: ^2.0.63 => 2.1.6

**Comment by stefanprobst** [comment]
Thanks for the report!

`skip` and `limit` are only applied in the `paginate` helper, so both are not actually available in `runQuery`:

https://github.com/gatsbyjs/gatsby/blob/b4b809733ab0c6c28d499f055c69f8d0221fcb3f/packages/gatsby/src/schema/resolvers.js#L80-L116

I think this should be treated as a documentation bug, since the same thing (slicing the results array) can be easily done directly in the custom field resolver. What do you think?

**Comment by coreyward** [comment]
@stefanprobst I could see the value of adding these to `runQuery` if it's not a terrible amount of work. Mostly I worry about memory usage for larger datasets; if I need the first 3 related blog posts for each blog post on a blog with 10,000 posts, I'm going to be copying 10,000 blog posts in memory 10,000 times, which will slow things down and could cause some out of memory issues depending on GC.

**Comment by stefanprobst** [comment]
@coreyward sorry for the long silence! I have since removed `limit`/`skip` from the `runQuery` docs -- as things stand currently, there's no benefit to using them as `runQuery` arguments, since they just slice the results array, which can be done directly in the field resolver as well. Afaik, this is unfortunately also true with LokiJs as a backend.

However, we might want to expose some internal helpers on `context` for paginating, grouping etc.

In the long run, real gains will only come when switching to a db backend that can handle this differently and a better caching story.

**Comment by coreyward** [comment]
Sounds good to me. I'm going to close this since this is pretty low priority and has some significant dependencies.
