### ISSUE TITLE
[component-shadowing] Nested shadowing causes issues with a index.js file.

### ISSUE THREAD

**Issue by lannonbr** [gatsbyjs/gatsby#15456]
## Description

When doing a nested shadow in a site `site/src/theme-a/theme-b/index.js`, it doesn't use it and fallsback to `theme-a/src/theme-b/index.js`.

That said, this issue doesn't appear when the shadowed file is not an `index.js` file

cc: @ChristopherBiscardi 

### Steps to reproduce

Doing this with a theme that shadows gatsby-plugin-theme-ui's index.js file.

https://github.com/lannonbr/gatsby-component-shadowing-bug-repro

### Expected result

the site's shadow should properly work

### Actual result

the shadow in the site doesn't resolve and it fallsback to the theme's shadow

### Environment

```
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 11.10.0 - /usr/local/bin/node
    Yarn: 1.16.0 - ~/.yarn/bin/yarn
    npm: 6.7.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 75.0.3770.100
    Firefox: 67.0.4
    Safari: 12.1.1
  npmGlobalPackages:
    gatsby-cli: 2.5.4
```

**Comment by lannonbr** [comment]
Chris is trying to debug through this issue

**Comment by ChristopherBiscardi** [comment]
> That said, this issue doesn't appear when the shadowed file is not an index.js file

On stream we've discovered that this is not the case. The reason this was originally thought to be the case is that `gatsby-theme-blog` shadows `gatsby-plugin-theme-ui` and extends it with additional files that can be shadowed.

---

In the repro repo, there are two themes and the user's site. `gatsby-plugin-theme-ui`, `gatsby-theme-bug`, and the user's site. In that case, the following paths are all valid for the given root (root being the original `gatsby-plugin-theme-ui/src/index.js`).

```
> gatsby-plugin-theme-ui/src/index.js
gatsby-theme-bug/src/gatsby-plugin-theme-ui/index.js
site/src/gatsby-plugin-theme-ui/index.js
```

If a file exists in the above list, the last existing file in the list wins.

What the repro repo does is fork the shadowing tree into a new context by creating a chain rooted at `gatsby-theme-bug/src/gatsby-plugin-theme-ui/index.js`. This is the list of possible shadow paths for that root:

```
> gatsby-theme-bug/src/gatsby-plugin-theme-ui/index.js
site/src/gatsby-theme-bug/gatsby-plugin-theme-ui/index.js
```

If we allow the last path to shadow the original, then what we're saying is that any theme can extend the shadow context, creating a potentially infinite tree of possible shadow locations. In this specific case, the list of shadow paths would include all four potential paths for the root `gatsby-plugin-theme-ui/src/index.js` instead of the original three.

```
> gatsby-plugin-theme-ui/src/index.js
gatsby-theme-bug/src/gatsby-plugin-theme-ui/index.js
site/src/gatsby-plugin-theme-ui/index.js
site/src/gatsby-theme-bug/gatsby-plugin-theme-ui/index.js
```

This results in an ambiguous ordering for the following two paths. There is no, as far as I can tell, "intuitive" way to define an order for which of these paths wins as they are both at the "end" of the shadow paths.

```
site/src/gatsby-plugin-theme-ui/index.js
site/src/gatsby-theme-bug/gatsby-plugin-theme-ui/index.js
```

Because there is no non-confusing way to define nested shadow paths that roll up to the original root, I propose that we document this and do not extend to implement it. There is already a way to shadow files from a parent theme, so this is not restricting functionality if we do not implement it.
