### ISSUE TITLE
gatsby new error

### ISSUE THREAD

**Issue by rccclr** [gatsbyjs/gatsby#15465]
Help for this error

Many thanks

![image](https://user-images.githubusercontent.com/5550864/60755382-3c595b80-9fef-11e9-954d-5d080d1242d4.png)

**Comment by jonniebigodes** [comment]
@rccclr do you have python added to your system? Namely 2.7? And also check if you have the `build-essential` linux package installed. If not you might need to add them. 

Feel free to provide feedback and report back so that we can close this issue or continue to work on it till we find a solution for your issue

**Comment by rccclr** [comment]
Many thanks for your response. 
I check this but not work.
This fix working with node 10, not node 12.
