### ISSUE TITLE
[blog] write a blog post about wordpress menu

### ISSUE THREAD

**Issue by Boussama** [gatsbyjs/gatsby#15501]
## Summary

I want to write a blog post about how to retrieve wordpress's menus into Gatsby

### Motivation

I found what I needed on the documentation and in the forums but I didn't find it in one single place. So, I thought that making a blog post to talk about it in one single place will be helpful for everyone. This will be example base blog post rather than reference/doc type

**Comment by marcysutton** [comment]
@Boussama are there updates we can make to the docs to provide more information where people will find it (either reference guides or a tutorial)? While the blog is great, we're trying to consolidate learning materials in the docs themselves since the blog is best for time-sensitive content (and stuff gets buried pretty quickly as more posts are added). Perhaps these contributing docs would help: https://www.gatsbyjs.org/contributing/docs-templates/

**Comment by Boussama** [comment]
@marcysutton I think that adding the part where we actually use the graphql request will add more clarity to the subject. Here's my blog post you can reference it if you find it useful. Better yet, I can help with the documentation.
