### ISSUE TITLE
gatsby-plugin-google-tagmanager doesn't work correctly

### ISSUE THREAD

**Issue by vasaeps3** [gatsbyjs/gatsby#15542]
The link for the script is forming incorrectly.

Actual behavior
`https://www.googletagmanager.com/gtm.js?id=GTAG_ID`

Expected behavior

`https://www.googletagmanager.com/gtag/js?id=GTAG_ID`

https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-google-tagmanager/src/gatsby-ssr.js#L29

**Comment by wardpeet** [comment]
Could you explain a little bit more? gtm.js?id=GTAG_ID is working just fine. Did google update their snippet?

**Comment by bensbigolbeard** [comment]
@wardpeet I came across this same issue, but it seems the root cause is that there are two main ways to integrate with the Google Infrastructure for tags: gtag.js and Tag Manager(gtm). 

Essentially they are two implementations (Tag Manager being Google's version) that abide by the same schema/contract. [More on the topic here](https://support.google.com/tagmanager/answer/7582054?hl=en)

So, some people use `gtag` and others use `gtm`. They are interoperable, but you need to call the script url that corresponds to your setup (the two urls posted by OP).

Perhaps the fix/improvement here would be to allow users to specify if they are using `gtm` or `gtag` in the plugin options. The rest of the integration should (hopefully) be the same.
