### ISSUE TITLE
Querying graphql when using commonjs style

### ISSUE THREAD

**Issue by pcr910303** [gatsbyjs/gatsby#15562]
#  Summary
I, as a node developer, use CommonJS style even in frontend code as that makes the codebase (backend & frontend) more coherent.
I would like to use CommonJS style-require & exports in Gatsby pages, but I could not get graphql queries to work.
I expect CommonJS style available since Gatsby seems to have existed before the ES6 import-style became commonplace.
How do I have to export my data to execute my query?

## Relevant information
I have tried
```js
module.exports = Component;
module.exports.query = graphql`{}`;
```
and
```js
module.exports.default = Component;
module.exports.query = graphql`{}`;
```
but have all failed to make the query execute.

### Environment (if relevant)
```
  System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Shell: 3.0.2 - /usr/local/bin/fish
  Binaries:
    Node: 12.4.0 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /Users/josungbin/.pyenv/shims/python
  Browsers:
    Firefox: 67.0.4
  npmPackages:
    gatsby: ^2.10.4 => 2.10.4 
    gatsby-plugin-jss: ^2.1.1 => 2.1.1 
    gatsby-plugin-typography: ^2.3.0 => 2.3.0 
    gatsby-source-filesystem: ^2.1.1 => 2.1.1 
    gatsby-transformer-remark: ^2.6.1 => 2.6.1 
```

### File contents (if changed)

`gatsby-config.js`: 
```js
module.exports = {
    siteMetadata: {
        title: "sshs.dev"
    },
    plugins: [{
        resolve: "gatsby-plugin-typography",
        options: {
            pathToConfigModule: "src/utils/typography"
        }
    }, "gatsby-plugin-jss"]
};
```
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by pcr910303** [comment]
I would like an answer.

**Comment by ervasive** [comment]
I have the same question.

As far as I understand there is no easy way to define page queries in CommonJS style, here is an explanation: https://github.com/gatsbyjs/gatsby/issues/4984#issuecomment-588466441

But here is my issue.

I use typescript to compile my code to CommonJS. The problem is that it consists of node related code as well as of some pages with page queries which, with the rest of the code are compiled to CommonJS, and as far as I know, there is no easy way to configure typescript so it would compile different filetypes (.ts, .tsx) into different standards (CommonJS, ES6 etc.).

Does anyone have any recommendations about how to make it work?

Thanks

**Comment by ksjogo** [comment]
Running into the same thing at the moment.
