### ISSUE TITLE
gatsby-source-wordpress API Menus error with 2.1.0

### ISSUE THREAD

**Issue by itwasmattgregg** [gatsbyjs/gatsby#15612]
Getting this error when trying to pull data from Wp Api Menus plugin:

`- Unknown field 'allWordpressWpApiMenusMenusItems' on type 'Query'.`

This is only happening after upgrading to gatsby 2.1.0.
My gatsby-source-wordpress is 3.1.5.

I am using the REST api.

**Comment by pieh** [comment]
Can you provide reproduction?

Also latest gatsby version is `2.13.15` - this might have been fixed already - please try updating gatsby (and plugins) to latest version

**Comment by jonniebigodes** [comment]
@itwasmattgregg i'm going to detail the steps i took to try and triage this issue.

- Created a new Gatsby website based on the hello world starter
- Added the `gatsby-source-wordpress` plugin to the site.
  And with that my package.json file looks like the following, just leaving in the dependencies in for brevity purposes:
```json
{
  
  "dependencies": {
    "gatsby": "^2.13.13",
    "gatsby-source-wordpress": "^3.1.6",
    "react": "^16.8.6",
    "react-dom": "^16.8.6"
  },
  "devDependencies": {
    "prettier": "^1.18.2"
  }
}
```
- Modified my `gatsby-config.js` file with the following content:
```javascript
/**
 * Configure your Gatsby site with this file.
 *
 * See: https://www.gatsbyjs.org/docs/gatsby-config/
 */

module.exports = {
  /* Your site config here */
  plugins:[
    {
      resolve:`gatsby-source-wordpress`,
      options: {
        // your wordpress source
        baseUrl: `localhost/wordpress`,
        protocol: `http`,
        // is it hosted on wordpress.com, or self-hosted?
        hostingWPCOM: false,
        // does your site use the Advanced Custom Fields Plugin?
        useACF: false,
        includedRoutes: [
          "**/categories",
          "**/posts",
          "**/pages",
           "**/media",
           "**/tags",
           "**/taxonomies",
           "**/users",
           "**/menus"
        ],
      }
    }
  ]
}
```
- Modified my local wordpress installation by adding the following [menu plugin](https://pt.wordpress.org/plugins/wp-api-menus/). Don't know if the plugin is actually needed but it worked for this reproduction.
- Created a new menu following these [steps](https://www.wpbeginner.com/beginners-guide/how-to-add-navigation-menu-in-wordpress-beginners-guide/) i've added all of the posts instead of the actual pages. Named the menu `DummyMenu`.
- Opened up a new browser window to `http://localhost/wordpress/wp-json/wp-api-menus/v2/menus` and i get the following results back.
```json
[{
    "term_id": 17,
    "name": "DummyMenu",
    "slug": "dummymenu",
    "term_group": 0,
    "term_taxonomy_id": 17,
    "taxonomy": "nav_menu",
    "description": "",
    "parent": 0,
    "count": 9,
    "filter": "raw",
    "ID": 17,
    "meta": {
        "links": {
            "collection": "http:\/\/localhost\/wordpress\/wp-json\/wp-api-menus\/v2\/menus\/",
            "self": "http:\/\/localhost\/wordpress\/wp-json\/wp-api-menus\/v2\/menus\/17"
        }
    }
}]
```
- Issued `gatsby develop` and waited for the build to finish.
- Opened up a new brower window to`http://localhost:8000/___graphql`  and added the following query:
```graphql
{
  allWordpressWpApiMenusMenus {
    edges {
      node {
        id
        name
        term_group
      }
    }
  }
}
```
And it yelds the following:

![menu_items_1](https://user-images.githubusercontent.com/22988955/61087895-d590d380-a42e-11e9-9f4e-6b25bdf7fe72.png)

- Went ahead and issued the following query 
```graphql
{
  allWordpressWpApiMenusMenusItems {
    edges {
      node {
        id
        wordpress_id
        name
        slug
        description
      }
    }
  }
}
```
And it yelds the following:
![menu_items_2](https://user-images.githubusercontent.com/22988955/61088100-5f40a100-a42f-11e9-95c3-a46eda6ebf61.png)

Feel free to provide feedback so that we can close this issue or continue to work on it till we find a solution.

**Comment by itwasmattgregg** [comment]
It seems to work now. I must not have updated one of those dependencies to a version that was friendly with the others. I'm sorry I didn't respond to this sooner, things have been crazy.
Thank you so much @jonniebigodes for listing the exact dependencies you changed in package.json. Your response was amazingly helpful.
