### ISSUE TITLE
Problem installing Gatsby in windows 7

### ISSUE THREAD

**Issue by gurpr33t** [gatsbyjs/gatsby#1562]
Hi, I am trying to make it work using this tutorial on windows 7 using command prompt
https://www.gatsbyjs.org/tutorial/part-one/

This is what I have reached to 
D:\nodejs\apps\example>type package.json
```
{
  "name": "example",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "gatsby": "^1.3.0",
    "gatsby-link": "^1.3.0"
  }
}
```
On running this command,
`./node_modules/.bin/gatsby develop`

I get this and localhost doesn't open.
```
D:\nodejs\apps\example\node_modules\.bin>gatsby develop
A local install of Gatsby was not found.
You should save Gatsby as a site dependency e.g. npm install --save gatsby
```

I can't figure out what is the problem. Can you helpl?

**Comment by nicholaswyoung** [comment]
Have you tried one of the starters, like [gatsby-starter-blog](https://github.com/gatsbyjs/gatsby-starter-blog)?

Gatsby 1.0 is exponentially more powerful than 0.12 thanks to the GraphQL data layer. Unfortunately, it also can be quite a bit more complex since so many modules are in play. I found it easier to start with a fully-loaded starter kit and strip out the modules I didn't need. The same approach may help you, too.

**Comment by sebastienfi** [comment]
You should run `npm i` in `D:\nodejs\apps\example` then `npm run develop` in the same folder.
