### ISSUE TITLE
Slow page build times (~13k pages)

### ISSUE THREAD

**Issue by bbaker6225** [gatsbyjs/gatsby#15628]
##  Summary
Our project is building slightly over 13,000 pages, and the build times seem quite slow to us, and we would ideally like to our page build and query speed to improve the build time.

## Relevant information
When running the benchmark builds in this repo for ~13,000 pages we get the following build times (some data omitted for brevity)

Create pages benchmark
```
success run static queries - 0.002 s
success Building production JavaScript and CSS bundles - 2.790 s
success run page queries - 24.041 s — 13324/13324 555.49 queries/second
success Building static HTML for pages - 16.841 s — 13324/13324 800.89 pages/second
info Done building in 71.14 sec
```

Markdown benchmark (MAX_NUM_ROWS=100)
```
...⠀
success run static queries - 0.004 s
success Building production JavaScript and CSS bundles - 13.045 s
success Rewriting compilation hashes - 0.073 s
success run page queries - 202.963 s — 13324/13324 65.67 queries/second
success Building static HTML for pages - 59.094 s — 13324/13324 228.98 pages/second
info Done building in 315.724 sec
```

For our project, the relevant times from our build are:
```
success run page queries - 279.872 s — 13323/13323 47.61 queries/second
success Building static HTML for pages - 322.152 s — 13323/13323 42.77 pages/second
```
which are much slower.

### Environment (if relevant)

```
  System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.15.2 - /usr/local/bin/node
    npm: 6.4.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 75.0.3770.100
    Firefox: 67.0
    Safari: 12.1.1
  npmGlobalPackages:
    gatsby-cli: 2.4.8
```

**Comment by pieh** [comment]
Speed of running queries depends on complexity of the queries, but said that - it seems like running queries in markdown benchmark and in your project are fairly close (at least in the same ballpark). Query used in markdown benchmark is one of more basic scenarios, where it really depend mostly just on `MAX_NUM_ROWS`.

There are opportunity for improvements here, but it's difficult matter and might depend on improving things case by case. We tried approach of spreading query running across multiple threads/cores, but because we can't access shared memory in Node easily it required inter process communication (IPC), which actually made things slower to run in multiple threads. We are working and making steady progress on different approach that could utilize 3rd party databases for our data store that will be more optimized for handling large amount of data (and making it actually viable to spread query running across multiple cores), but this is huge project.

Speed of generating html pages depend on complexity of your templates - in this case template used for markdown is also pretty small which will positively impact speed.

I'm not sure if generating html pages can be improved much further, as bulk of the time there is spent running `react`'s `renderToStaticMarkup` function and this part is already spread across multiple cores.

That said we are making progress toward incremental builds, that could make subsequent builds faster by rebuilding just parts of site that changed ( https://www.gatsbyjs.org/blog/2019-06-12-performance-improvements-for-large-sites/ ), but this will require much more changes

**Comment by bbaker6225** [comment]
Thanks for the response. You're right that our queries/second is pretty close to the benchmark, it's mainly the pages/second that is much slower than I would hope for.
