### ISSUE TITLE
 How should gatsby-remark-prismjs be used correctly?

### ISSUE THREAD

**Issue by 97thjingba** [gatsbyjs/gatsby#15672]
**How to use gatsby-remark-prismjs correctly?**

gatsby-config.js 
```
module.exports = {
  siteMetadata: {
    title: `beibei-blog`,
    description:  `李贝贝的小博客`
  },
  plugins: [
    `gatsby-plugin-sharp`,
    `gatsby-transformer-sharp`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `blog`,
        path: `${__dirname}/content`,
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/static/assets/`,
        name: `assets`,
      },
    },
    {
      resolve: `gatsby-transformer-remark`,
      options: {
        plugins: [
            "gatsby-remark-prismjs",
          {
            resolve: `gatsby-remark-images`, //remarkdown里配置maxwidth的大小
            options: {
              maxWidth: 728,
            },
          },
        ],
      },
    }
  ],
}
```

**This is my usage in markdown**

```javascript
constructor(props) {
  super(props)
  console.log(this.props) 
  this.state = {
    //
  }
}
```
[https://elated-lewin-51cf0d.netlify.com/](https://elated-lewin-51cf0d.netlify.com/)

I use it in this web.

by the way .I use bulma and don't know if it has anything to do with this.

**Comment by jonniebigodes** [comment]
@97thjingba so far from skimming your repository i don't see anything wrong with aside from the fact that and this is a personal opinion of mine. For instance references to code should be go with the way you're using in your issue description. 

If you want just update the markdown files in your code accordingly as there's some code excerpts that are using only the backticks, not specifying the language.

Also i'm going to leave the link to the plugin [here](https://www.gatsbyjs.org/packages/gatsby-remark-prismjs/) so that you go over it in more detail.

Feel free to provide feedback so that we can close this issue or continue to work on it until we find a suitable solution.

**Comment by 97thjingba** [comment]
@jonniebigodes  
It seems to have some effect, but the color of the code that needs to be highlighted has not changed. I really can't find why this is.

**Comment by jonniebigodes** [comment]
@97thjingba could be that you're not adding a theme? That could be reason for it. Check [this](https://www.gatsbyjs.org/packages/gatsby-remark-prismjs/#include-css).

**Comment by 97thjingba** [comment]
@jonniebigodes 
Thank you very much, I have solved my problem.
