### ISSUE TITLE
Pulling in images from Google Cloud Storage and "running" them through image sharp

### ISSUE THREAD

**Issue by danboyle8637** [gatsbyjs/gatsby#15683]
I have some large images in my site and I wanted to store them in Google Cloud Storage. 

I wanted to learn more about the Gatsby node api and get my images from my bucket and have image sharp do it's thing so I can get the image processing on my site. 

Are there any steps or tutorials for this?

I have looked at some plugins that do this for S3 and I'm still going through their code to figure some things out. 

Thanks for any help!

**Comment by sidharthachatterjee** [comment]
Thank you for opening this @danboyle8637 

Let's walk through what you would need to do to support this (following along https://github.com/jessestuart/gatsby-source-s3-image as an example which does the same but for AWS S3)

1. You would need to actually need to request the list of images from the bucket using some Google Cloud Storage API

In gatsby-source-s3-image, this happens in `source-nodes.ts` in https://github.com/jessestuart/gatsby-source-s3-image/blob/9ed8d5114fce83733624cc9ff6757447284be995/src/source-nodes.ts#L62

2. Once you have the list of images and their URLs (perhaps signed URLs if the bucket is private), you can need to loop over them and create `File` nodes for each of them 

`gatsby-source-filesystem` has a useful `createRemoteFileNode` API for this (https://www.gatsbyjs.org/packages/gatsby-source-filesystem/#createremotefilenode)

In gatsby-source-s3-image, this happens in `source-nodes.ts` in https://github.com/jessestuart/gatsby-source-s3-image/blob/9ed8d5114fce83733624cc9ff6757447284be995/src/source-nodes.ts#L101

(`createRemoteFileNode` will download the file you)

3. Finally you will need to create the actual `ImageSharp` node (so that `gatsby-plugin-sharp` can work its magic) and a link from the node above. 

In gatsby-source-s3-image, this happens in `on-create-node.ts` in https://github.com/jessestuart/gatsby-source-s3-image/blob/57a168d6424625d3990da5c4c8d6c74880aa8416/src/on-create-node.ts#L16

Hope this helps! Marking this an answered and closing but of course feel free to comment/reopen if there is anything else we can help with 💜

**Comment by danboyle8637** [comment]
@sidharthachatterjee Thank you so much for the steps. I will go through this today and get it hooked up and make an npm module too. I appreciate the help!
