### ISSUE TITLE
Official themes should only pass in an ID to page templates

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#15687]
As otherwise hot reloading doesn't happen and it's harder to shadow the logic as you have to copy out code from the theme's gatsby-node.js.

**Comment by msimmer** [comment]
Hey, I'd like to take this on :) Would be great if you could point me in the direction of where to get started!

**Comment by sidharthachatterjee** [comment]
@msimmer Thank you for volunteering to take this up!

Currently the official themes (https://github.com/gatsbyjs/gatsby/tree/master/themes/gatsby-theme-blog and https://github.com/gatsbyjs/gatsby/tree/master/themes/gatsby-theme-notes) pass in data as context when creating pages 

https://github.com/gatsbyjs/gatsby/blob/9d3dad0e9ad4cc45fd30177776c615df888ce9b2/themes/gatsby-theme-notes/gatsby-node.js#L82
https://github.com/gatsbyjs/gatsby/blob/9d3dad0e9ad4cc45fd30177776c615df888ce9b2/themes/gatsby-theme-blog/gatsby-node.js#L143

This needs to be changed to pass in just the `id` (like @KyleAMathews mentions) so that the page component itself can query necessary data. 

To this do, you will have to:

- [ ] Change the queries in the `gatsby-node.js` files above to only get the `id`
- [ ] Pass in only the `id` into context 
- [ ] Export page queries from the respective template files to get the necessary data 
- [ ] Update the components to consume the data from `data` and not `pathContext`

Hope this helps!

**Comment by msimmer** [comment]
Hey @sidharthachatterjee, thanks for the detailed walkthrough!

Started working on this and ran into a couple of things:

> Change the queries in the gatsby-node.js files above to only get the id

It looks like the queries will still need to include the [slug](https://github.com/gatsbyjs/gatsby/blob/9d3dad0e9ad4cc45fd30177776c615df888ce9b2/themes/gatsby-theme-blog/gatsby-node.js#L114) field though, since it's used by [`createPage`](https://github.com/gatsbyjs/gatsby/blob/9d3dad0e9ad4cc45fd30177776c615df888ce9b2/themes/gatsby-theme-blog/gatsby-node.js#L141) below - is that right?

> Pass in only the id into context

Since the [logic for the pagination](https://github.com/gatsbyjs/gatsby/blob/9d3dad0e9ad4cc45fd30177776c615df888ce9b2/themes/gatsby-theme-blog/gatsby-node.js#L137-L138) is done during `createPage`, I'll still need to pass in the `previous` and `next` nodes here, though, correct? I was looking into handling the pagination in the components, but since it doesn't look like the `allBlogPosts` accepts `find` or `after` params, it seems like it might be difficult to manage from there.

This is my first contribution here, so let me know if I'm totally off-base with anything!

**Comment by wardpeet** [comment]
@msimmer sorry to keep you waiting. You're right you will need the slug and id for the post. This could work for previous & next too and write a pagequery using the `in` operator. This makes it possible for the theme users to fully own the query if they like to modify their template.

```js
const result = await graphql(`
    {
      site {
        siteMetadata {
          title
          social {
            name
            url
          }
        }
      }
      mdxPages: allBlogPost(
        sort: { fields: [date, title], order: DESC }
        limit: 1000
      ) {
        edges {
          node {
            id
            slug
          }
        }
      }
    }
  `)
```

**Comment by ChristopherBiscardi** [comment]
With the release of gatsby-theme-blog-core, pages only get [the relevant ids](https://github.com/gatsbyjs/gatsby/blob/71f133b9b8d90d5d029b268f7a548c40e201805f/themes/gatsby-theme-blog-core/gatsby-node.js#L195-L203)
