### ISSUE TITLE
[gatsby-source-drupal] fetching data fails when there are 0 images

### ISSUE THREAD

**Issue by pieh** [gatsbyjs/gatsby#15761]
## Description

When there are 0 images in drupal site, `gatsby-source-drupal` crashes with:
![D_ilNTNX4Ag4c-0](https://user-images.githubusercontent.com/419821/61247048-99bc7d80-a750-11e9-931a-4bbc83ac3d23.png)

This happens in this part of code - https://github.com/gatsbyjs/gatsby/blob/98511d678f58fc63387ebfa8aa898c7a9761c1e4/packages/gatsby-source-drupal/src/gatsby-node.js#L139-L154

plugin should determine array of File nodes first:
```
const fileNodes = [...nodes.values()].filter(isFileNode)
```

and only use `asyncPool` (and reporter for logging) when there are any images.

**Comment by harshil1712** [comment]
@pieh I would like to take this, but I would need your help :sweat_smile:

**Comment by jdiglesias** [comment]
Thanks Kayla, your fix works for me. In order to test it, you'll have to include a mock fixture that returns no file nodes (i.e. [this file](https://github.com/gatsbyjs/gatsby/blob/98511d678f58fc63387ebfa8aa898c7a9761c1e4/packages/gatsby-source-drupal/src/__tests__/fixtures/file.json) but with an empty array as the data field) and run a test using that fixture.
