### ISSUE TITLE
`gatsby serve` ignores assetPrefix config

### ISSUE THREAD

**Issue by disintegrator** [gatsbyjs/gatsby#15902]
## Description

`gatsby serve` ignores `assetPrefix` configuration

### Steps to reproduce

- Set an `assetPrefix` value in `gatsby-config.js` such as `/demo`
- Run `gatsby build --prefix-paths && gatsby serve --prefix-paths`
- Open browser and navigate to the built site
- Notice 404 errors in console when trying to load assets

### Expected result

`gatsby serve` should set up a route prefix for assets if `assetPrefix` is setup

### Actual result

Several 404 errors because the prefixed asset paths could not be resolved by the gatsby server

### Environment

```
  System:
    OS: macOS 10.14.5
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 5.7.1 - /usr/local/bin/zsh
  Binaries:
    Node: 10.16.0
    Yarn: 1.16.0
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 75.0.3770.142
    Firefox: 67.0.3
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.13.28 => 2.13.28 
    gatsby-cli: ^2.7.15 => 2.7.15 
    gatsby-image: ^2.2.6 => 2.2.6 
    gatsby-plugin-catch-links: ^2.1.2 => 2.1.2 
    gatsby-plugin-manifest: ^2.2.3 => 2.2.3 
    gatsby-plugin-offline: ^2.2.4 => 2.2.4 
    gatsby-plugin-react-helmet: ^3.1.2 => 3.1.2 
    gatsby-plugin-sharp: ^2.2.8 => 2.2.8 
    gatsby-plugin-sitemap: ^2.2.3 => 2.2.3 
    gatsby-plugin-svgr: ^2.0.2 => 2.0.2 
    gatsby-plugin-typescript: ^2.1.2 => 2.1.2 
    gatsby-plugin-webpack-bundle-analyzer: ^1.0.5 => 1.0.5 
    gatsby-remark-prismjs: ^3.3.3 => 3.3.3 
    gatsby-source-contentful: ^2.1.14 => 2.1.14 
    gatsby-source-filesystem: ^2.1.4 => 2.1.5 
    gatsby-transformer-remark: ^2.6.7 => 2.6.7 
    gatsby-transformer-sharp: ^2.2.4 => 2.2.4 
  npmGlobalPackages:
    gatsby-cli: 2.7.15
```

**Comment by DSchau** [comment]
@disintegrator this is sort of a known/intentional issue.

Asset Prefix is usually used for e.g. a CDN, so serving your content from "public" (and the CDN) would be a bit of a challenging endeavor for us to implement. The local path option (e.g. `/demo`) is of course easier, but it's also likely used entirely less often.

It is possible to get this working, you'll just want to add a postbuild script so that the assets are copied to the correct directory then things will "just work."

See [this example](https://github.com/gatsbyjs/gatsby/blob/master/e2e-tests/path-prefix/package.json#L25) from our e2e-tests for more info.

I'm going to close this as answered -- but we would accept a PR fixing this behavior for the local assetPrefix functionality with serve. It would likely involve setting a proxy from the `public` folder to a local folder (or a CDN/url).

Thanks for using Gatsby 💪
