### ISSUE TITLE
Using Sitemeta data in gatsby-config.js for Submenu

### ISSUE THREAD

**Issue by jnsrikanth** [gatsbyjs/gatsby#15927]
Hi,

I have seen very little documentation related to the complete usage of the gatsby-config.js and the Site and Site Meta Data objects. I am curious as to how I configure sub-menu items under the menuLinks object in  the Site Meta Data in gatsby-config.js.

Has anyone found a good way to do comprehensive Site Navigation using GatsbyJS? 
Any pointers in this direction would be highly appreciated.

**Comment by wardpeet** [comment]
I assume you're following https://www.gatsbyjs.org/docs/centralizing-your-sites-navigation/ to add navigation to your website.

```js
module.exports = {
  siteMetadata: {
    title: 'Gatsby Default Starter',
     menuLinks:[
       {
          name:'home',
          link:'/',
          items: [
            {
              name:'subnav',
              link:'/subnav',
            }
          ]
       },
       {
          name:'page2',
          link:'/page-2'
       }
     ]
  },
  plugins: []
}
```

**Comment by jnsrikanth** [comment]
@wardpeet thank you for your response. I did not see such explicit mention for sub-menu navigation. Could you please elaborate how to configure the folders and how to retrieve the submenus using the Graphql queries. A complete example would be a great help and that could finally end up in Gatsby documentation. Thank You in advance.

**Comment by sidharthachatterjee** [comment]
@jnsrikanth The structure of `siteMetadata` is free form and you're free to put anything you would like there

> Could you please elaborate how to configure the folders (folder structure) and how to retrieve the submenus using the Graphql queries

Folder structure is irrelevant here since objects in `menuLinks` have just a name and a link. 

Like in the example @wardpeet inlined above, you should be able to include submenu items (like in the `items` key in his example) and change your query to include it in the result as follows

### Before 

query SiteQuery {
  site {
    siteMetadata {
      title
      menuLinks {
        name
        link
      }
    }
  }
}

### After 

query SiteQuery {
  site {
    siteMetadata {
      title
      menuLinks {
        name
        link
		items
      }
    }
  }
}

> A complete example would be a great help and that could finally end up in Gatsby documentation

We would love to accept a PR to the guide! 🙂 

Marking this as answered and closing the issue for now but please feel free to comment or reopen if there is anything else we can help with.
