### ISSUE TITLE
I follow this video lesson in docs,why I don't have `allProductsJson`?

### ISSUE THREAD

**Issue by zwl1619** [gatsbyjs/gatsby#15938]
In this [video lesson](https://egghead.io/lessons/gatsby-make-data-queryable-in-graphql-with-gatsby?pl=why-gatsby-uses-graphql-1c319a1c),there is an `allProductsJson` at 04:13
![Snipaste_2019-07-21_02-37-38](https://user-images.githubusercontent.com/13177997/61583701-32e2fe00-ab6e-11e9-984b-48908c28d371.png)

I create a project following  [quick-start](https://www.gatsbyjs.org/docs/quick-start), then  follow 
the video above to write that demo, but I can not find  `allProductsJson` in the GraphQL playground:
![Snipaste_2019-07-21_04-15-02](https://user-images.githubusercontent.com/13177997/61583700-2bbbf000-ab6e-11e9-82c5-6d7d16ffab0a.png)

Why is it? 

below is my project structure.
![Snipaste_2019-07-21_04-19-30](https://user-images.githubusercontent.com/13177997/61583745-e9df7980-ab6e-11e9-95ab-c088fd10cb95.png)

**Comment by jonniebigodes** [comment]
@zwl1619 i've just checked the video you mentioned and i was able to run it to completion without any issues. Below are the steps i took to triage this issue.
- Created a new gatsby website based on the hello-world starter.
- Installed the dependencies required, namely `gatsby-image`, `gatsby-plugin-sharp`, `gatsby-source-filesystem`, `gatsby-transformer-json`, `gatsby-transformer-sharp`.
- Created the folder structure like mentioned in the video, namely, `data` and inside `images`.
Inside i've added the following
![all_json_1](https://user-images.githubusercontent.com/22988955/61584305-4aee5980-ab3d-11e9-8f60-42440f30b9d6.png)
The images are some random images i had laying around.
- Added the following content to `products.json` 
```json
[
    {
        "title":"first item",
        "slug":"first-item",
        "description":"<p>a random item</p>",
        "price":"10.00",
        "image":"./images/1196_1269477347_large.jpg"
    },
    {
        "title":"second item",
        "slug":"second-item",
        "description":"<p>a random item 2</p>",
        "price":"13.00",
        "image":"./images/49534_1251087275_large.jpg"
    },
    {
        "title":"third item",
        "slug":"third-item",
        "description":"<p>a random item 3</p>",
        "price":"10.00",
        "image":"./images/64489_1228413956_large.jpg"
    },
    {
        "title":"fourth item",
        "slug":"fourth-item",
        "description":"<p>a random item 4</p>",
        "price":"10.00",
        "image":"./images/3770028466_36fe94e49a_o.jpg"
    },
    {
        "title":"fifth item",
        "slug":"fifth-item",
        "description":"<p>a random item 5</p>",
        "price":"10.00",
        "image":"./images/alien_tako_sashimi_wallpaper_by_psychopulse-d33cvhr.jpg"
    }
]
```
- Modified `gatsby-config.js` to "activate" the plugins and enable data fetching like mentioned in the video, transforming it into:

```javascript
module.exports = {
  plugins: [
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `data`,
        path: `./data`,
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    `gatsby-transformer-json`
  ],
}
```
- Issued `gatsby develop` and waited for the build process to complete, opened up `http://localhost:8000/___graphql` and issued the following query:

```graphql
{
  allProductsJson {
    edges {
      node {
        title
        description
        slug
        price
        image {
          childImageSharp {
            fluid {
              srcSet
            }
          }
        }
      }
    }
  }
}
```

And it yelded the following:
![all_json_2](https://user-images.githubusercontent.com/22988955/61584363-378fbe00-ab3e-11e9-87b1-6674045d5d88.png)

Tested it with graphql playground by setting the url to `http://localhost:8000/___graphql` and it yelded the following:

![all_json_3](https://user-images.githubusercontent.com/22988955/61584477-352e6380-ab40-11e9-8f91-3c94b78a5061.png)



I would like you check on something on your end. Clear the `.cache` and `public` folder by issuing `gatsby clean` and issue again `gatsby develop` and open a new browser window to `http://localhost:8000/___graphql` and see if the types are there.

Also if you want i can put my code on a github repository so you can look at it in your own pace and try and see if what could be different.

Feel free to provide feedback so that we can close this issue or continue to work on it till we find a solution.

**Comment by zwl1619** [comment]
Thanks！It is ok after using the hello-world starter.

**Comment by zwl1619** [comment]
@jonniebigodes One more thing, what is the meaning of "edges" and "node"?

```
  const results =await graphql(`
    {
      allProductsJson{
        edges{
          node{
            slug
          }
        }}
    }
  `);
```

**Comment by jonniebigodes** [comment]
@zwl1619 in a nutshell, think of edges as a placeholder/list that contains all of your information, doing a loose analogy here, think of edges as a table that stores all the data. The node is an object that contains all the information, in this case all the information generated internally by Gatsby's internal graphql mechanism. Doing the same analogy as before, think of a node as a table record.
