### ISSUE TITLE
[docs] Broken reference in "GraphQL Node Types Creation" 

### ISSUE THREAD

**Issue by plhnk** [gatsbyjs/gatsby#15978]
## Description

In the [Mapping Field](https://www.gatsbyjs.org/docs/schema-gql-type/#mapping-field) section, there's a reference to `inferFromMapping` but the link is broken.

[A quick search](https://www.google.com/search?q=inferFromMapping) doesn't reveal anything helpful.

Browsing one level up to [the schema folder](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby/src/schema) doesn't really show a clear link to anything related.

### Steps to reproduce

1. Navigate to the [`Mapping Field`](https://www.gatsbyjs.org/docs/schema-gql-type/#mapping-field) section of the *GraphQL Node Types Creation* page.
1. Click on the [`inferFromMapping`](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/schema/infer-graphql-type.js#L129) link.
1. Experience the GitHub 404 page.

### Expected result

Go to a page with more information on inferFromMapping.

### Actual result

[GitHub 404](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/schema/infer-graphql-type.js#L129)

### Environment

[Gatsbyjs.org/docs](https://www.gatsbyjs.org/docs)

**Comment by stefanprobst** [comment]
As hidden on the top of the docs page you linked to, this part of the documentation (and the schema-related parts of "Gatsby Internals" more generally) is unfortunately quite outdated. There is an open issue to address this in #14228 

wrt mapping: if you're interested in where this now lives in the codebase, check here:
https://github.com/gatsbyjs/gatsby/blob/2616e379b157a0693ed8b34afc177027a58ad413/packages/gatsby/src/schema/infer/add-inferred-fields.js#L235-L243
since v2.2 we also enabled a different approach to creating relations between fields with the schema customization apis. you can find relevant docs for creating foreign-key relations [here](https://www.gatsbyjs.org/docs/schema-customization/#foreign-key-fields).

Related docs issue: #15816

**Comment by plhnk** [comment]
Thanks for the help @stefanprobst!

**Comment by stefanprobst** [comment]
I'm going to close this, but feel free to reopen if something remains unclear!
