### ISSUE TITLE
gatsby-starter-blog issues possibly due to defining path?

### ISSUE THREAD

**Issue by gregsqueeb** [gatsbyjs/gatsby#1601]
This is what I am seeing with basically stock build of gatsby-starter-blog with a path on gh-pages: https://www.dropbox.com/s/zf9qhbl3nkmuimx/Screenshot%202017-07-24%2018.40.26.png?dl=0

Links do not work on the blog.

Not totally sure what is breaking when I push it up to gh-pages. Here is the live link: https://gregsqueeb.github.io/gregdmathews.com/

Sorry I can't be of more help, don't exactly know where to look :(
Can anyone help?

**Comment by KyleAMathews** [comment]
Sounds like this is what you need https://www.gatsbyjs.org/docs/path-prefix/

**Comment by KyleAMathews** [comment]
Any way we could make that more obvious?

**Comment by gregsqueeb** [comment]
It was fairly obvious :) 

I have a pathPrefix defined in the gatsby-config.js.

To build and push to the gh-pages I am using `npm deploy` which is executing `gatsby build --prefix-paths && gh-pages -d public`

But it is still running into this issues. Any thoughts?

**Comment by KyleAMathews** [comment]
Haha oh ok :-)

Hmm no, I'd add some console.logs in gatsby-link to see what's happening.

**Comment by gregsqueeb** [comment]
Ok cool! Will do! Thanks!

**Comment by mplis** [comment]
I'm running into a similar issue. I'm trying to deploy a blog based off of [this](https://github.com/dschau/gatsby-blog-starter-kit) template to Github Pages. [Here's](https://github.com/mplis/blog) my repo and [here's](https://mplis.github.io/blog/) the Github Pages link.

Everything works fine when I run locally with `npm run develop`, but when I deploy to Github, the [Hello World](https://mplis.github.io/blog/hello-world) post doesn't render correctly because the image link doesn't include the `pathPrefix`. What's strange is that if you navigate to that post from another page, it works fine. The image link is only missing the `pathPrefix` when the Hello World post is the initial page you visit.

Steps to reproduce:

1. Go to the blog [homepage](https://mplis.github.io/blog/)
2. Click on the Hello World post (should work)
3. Refresh the page (should break)
