### ISSUE TITLE
How to overcome HTML build failure due to external JavaScript plugin (TypewriterJS) that uses “browser globals” like window or document?

### ISSUE THREAD

**Issue by wenhuangzeng** [gatsbyjs/gatsby#16022]
I really want to use [TypewriterJS](https://www.npmjs.com/package/typewriter-effect/v/2.8.2) in my Gatsby project but I noticed that I get the error `Building static HTML failed` when I run `gatsby build` with TypewriterJS used in the project. When I remove the part of my project that uses TypewriterJS, it built without any error. I also tried importing `browser-monad` but no luck.

**Comment by jonniebigodes** [comment]
@wenhuangzeng i've picked up on your issue and i think i have a solution for your case. Upon looking at the documentation and code of package, it seem that it's not ssr(server side friendly), and Gatsby operates on the server side spectrum. What this means is that when you issue a build all of the work is done in node and with that certain apis are not available like `window` for instance. Below are the steps i took to tackle this issue.
- Created a new Gatsby website based on the hello world starter.
- Added the package you mentioned in your issue description and also [react-loadable](https://github.com/jamiebuilds/react-loadable).
- Created a new component called `MyTypewriter.js` under `/src/components` with the following code:
```javascript
import React, { useRef } from "react"
import Typewriter from "typewriter-effect"

const MyTypewriter = () => {
  const typewritterinput = useRef()

  const dummyTypewriter = new Typewriter(typewritterinput.current, {
    loop: true,
    delay: 75,
  })


  return (
    <div>
      <Typewriter
        onInit={dummyTypewriter => {
            dummyTypewriter
            .typeString("Hello World!")
            .callFunction(() => {
              console.log("String typed out!")
            })
            .pauseFor(2500)
            .deleteAll()
            .callFunction(() => {
              console.log("All strings were deleted")
            })
            .start()
        }}
      />
      <div id="typewritercontainer" ref={typewritterinput}></div>
    </div>
  )
}

export default MyTypewriter;
```
This is the most simple implementation i could come up with following the documentation. I've used a [ref](https://reactjs.org/docs/refs-and-the-dom.html) so that i could get "access" to the element that will be used to display the text.

- Modified `/src/pages/index.js` to the following:
```javascript
import React from "react"
import Loadable from 'react-loadable'
const loader=()=>(<div>Loading...</div>)
const LoadableComponent = Loadable({
    loader: () => import('../components/MyTypewriter'),
    loading: loader,
  });
export default () => (
  <div>
    <p>Hello world!</p>
    <LoadableComponent/>
  </div>
)
```

With this small change, the component `MyTypewriter` will only be loaded on the client side through the use of `react-loadable`.

- Issued `gatsby build && gatsby serve` to get a production build and emulate a live production server and i'm presented with:

![typewriter1](https://user-images.githubusercontent.com/22988955/61749212-1b885880-ad9a-11e9-9f5d-e5d14697ea79.png)

- Opening up a new browser window to `http://localhost:9000` will show the text being animated by the package.

Feel free to provide feedback so that we can close this issue, or continue to work on it till we find a suitable solution.

**Comment by wenhuangzeng** [comment]
> 
> 
> @wenhuangzeng i've picked up on your issue and i think i have a solution for your case. Upon looking at the documentation and code of package, it seem that it's not ssr(server side friendly), and Gatsby operates on the server side spectrum. What this means is that when you issue a build all of the work is done in node and with that certain apis are not available like `window` for instance. Below are the steps i took to tackle this issue.
> 
>     * Created a new Gatsby website based on the hello world starter.
> 
>     * Added the package you mentioned in your issue description and also [react-loadable](https://github.com/jamiebuilds/react-loadable).
> 
>     * Created a new component called `MyTypewriter.js` under `/src/components` with the following code:
> 
> 
> ```js
> import React, { useRef } from "react"
> import Typewriter from "typewriter-effect"
> 
> const MyTypewriter = () => {
>   const typewritterinput = useRef()
> 
>   const dummyTypewriter = new Typewriter(typewritterinput.current, {
>     loop: true,
>     delay: 75,
>   })
> 
> 
>   return (
>     <div>
>       <Typewriter
>         onInit={dummyTypewriter => {
>             dummyTypewriter
>             .typeString("Hello World!")
>             .callFunction(() => {
>               console.log("String typed out!")
>             })
>             .pauseFor(2500)
>             .deleteAll()
>             .callFunction(() => {
>               console.log("All strings were deleted")
>             })
>             .start()
>         }}
>       />
>       <div id="typewritercontainer" ref={typewritterinput}></div>
>     </div>
>   )
> }
> 
> export default MyTypewriter;
> ```
> 
> This is the most simple implementation i could come up with following the documentation. I've used a [ref](https://reactjs.org/docs/refs-and-the-dom.html) so that i could get "access" to the element that will be used to display the text.
> 
>     * Modified `/src/pages/index.js` to the following:
> 
> 
> ```js
> import React from "react"
> import Loadable from 'react-loadable'
> const loader=()=>(<div>Loading...</div>)
> const LoadableComponent = Loadable({
>     loader: () => import('../components/MyTypewriter'),
>     loading: loader,
>   });
> export default () => (
>   <div>
>     <p>Hello world!</p>
>     <LoadableComponent/>
>   </div>
> )
> ```
> 
> With this small change, the component `MyTypewriter` will only be loaded on the client side through the use of `react-loadable`.
> 
>     * Issued `gatsby build && gatsby serve` to get a production build and emulate a live production server and i'm presented with:
> 
> 
> ![typewriter1](https://user-images.githubusercontent.com/22988955/61749212-1b885880-ad9a-11e9-9f5d-e5d14697ea79.png)
> 
>     * Opening up a new browser window to `http://localhost:9000` will show the text being animated by the package.
> 
> 
> Feel free to provide feedback so that we can close this issue, or continue to work on it till we find a suitable solution.

This works! Thank you so much.
