### ISSUE TITLE
Can't see example gatsby-plugin-categories on document 

### ISSUE THREAD

**Issue by NantipatSoftEn** [gatsbyjs/gatsby#16058]
## Description

I open https://www.gatsbyjs.org/packages/gatsby-plugin-categories/   then I click see example 

![Screenshot_119](https://user-images.githubusercontent.com/9590823/61809999-8a33e780-ae68-11e9-8633-dedc2736808a.png)

### Expected result
I expected  see example.

### Actual result
![image](https://user-images.githubusercontent.com/9590823/61810107-c1a29400-ae68-11e9-8452-bd392d22299a.png)

**Any one can change URL ?**

**Comment by joealden** [comment]
@NantipatSoftEn `gatsby-plugin-categories` isn't maintained by the Gatsby team, and is actually maintained by https://github.com/rmcfadzean. Please create an issue on https://github.com/rmcfadzean/gatsby-pantry to get this broken link fixed.

---

I completely understand why you might have created this issue here though, as the link appears on Gatsby's website. However, The "Plugins" page (https://www.gatsbyjs.org/plugins) is created dynamically, and pulls in plugins that have been created by people other than just the Gatsby team.

If the plugin has the Gatsby logo next to the download count, and shows the "Official Plugin" text at the top of the actual plugin page (as shown in the below screenshot), then please file issues here for those plugins, as those **are** maintained by the Gatsby team.

![screenshot](https://user-images.githubusercontent.com/10297243/61823697-34554480-ae54-11e9-8074-ae64e4c16c10.png).

**Comment by NantipatSoftEn** [comment]
Thank You  and sorry ,I misunderstood. 👍
