### ISSUE TITLE
Unable to find local plugin from installed theme

### ISSUE THREAD

**Issue by bensbigolbeard** [gatsbyjs/gatsby#16128]
## Description

When a gatsby theme with a local plugin is installed into a project (or a co-located directory, using something like `yarn` workspaces) the gatsby build fails the `load plugins` step, claiming it cant find that local plugin and that it should be installed.

It's possible that this was never an intended use-case, but my current setup led to this particular issue.

### Steps to reproduce

1. clone [this example repo](https://github.com/bensbigolbeard/gatsby-theme-test)
2. run `yarn workspace gatsby-theme-test` to install packages
3. run `yarn workspace gatsby-theme-test develop` to see it successfully pass `load plugins` build step
4. run `yarn workspace site` to install packages (including gatsby-theme-test)
5. run `yarn workspace site develop` or `cd site && gatsby develop` to see it fail the load plugins build step displaying this error:

### Expected result
Local plugin would be found in the installed theme directory and build should pass 

### Actual result

Local plugin was not found and this error was thrown:
```bash
ERROR

UNHANDLED REJECTION Unable to find plugin "gatsby-local-plugin". Perhaps you need to install its package?

  Error: Unable to find plugin "gatsby-local-plugin". Perhaps you need to install its package?
  - load.js:109 resolvePlugin
    [test-gatsby-theme]/[gatsby]/dist/bootstrap/load-plugins/load.js:109:11
  ...
```

### Environment
```
  System:
    OS: macOS High Sierra 10.13.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.16.0 - ~/n/bin/node
    Yarn: 1.17.3 - ~/n/bin/yarn
    npm: 6.9.0 - ~/n/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 75.0.3770.80
    Safari: 12.1.1
```

**Comment by bensbigolbeard** [comment]
Not sure what☝️this is referencing, but let me know if something isn't correct with my issue format.

**Comment by ChristopherBiscardi** [comment]
themes intentionally don't support local plugins. If they did we would have to cut it off at some arbitrary point anyway since it could lead to recursive requiring of sub-local plugins when we merge [local theme support](https://github.com/gatsbyjs/gatsby/pull/15856). Since you're already using workspaces, I'd suggest moving the local plugin out to it's own package in the workspace.

If you feel strongly that local plugins in themes should be supported feel free to open a feature request detailing your use case and we can have a discussion there about potentially supporting it :)
