### ISSUE TITLE
clarify gatsby/themes folder structure

### ISSUE THREAD

**Issue by sw-yx** [gatsbyjs/gatsby#16145]
## Question

this structure is confusing: https://github.com/gatsbyjs/gatsby/tree/master/themes

what is the difference between `gatsby-starter-blog-theme` and `gatsby-theme-blog`? where is `gatsby-theme-blog` published from, the starter or the theme?

i can kinda figure it out, but lets just say its potentially quite confusing. opportunity to better document.

**Comment by ChristopherBiscardi** [comment]
The names tell you what they are: `gatsby-starter-*` vs `gatsby-theme-*`

* `gatsby-starter-blog-theme` is a starter that uses the blog theme and comes with demo content, etc. [Starters](https://www.gatsbyjs.org/starters/?v=2) are a fairly common concept in the Gatsby ecosystem.
* `gatsby-theme-blog` is a theme that is released as an npm package. You can see this since the `package.json` name is `gatsby-theme-blog` as well.
