### ISSUE TITLE
Default Gatsby Themes don't compose well together

### ISSUE THREAD

**Issue by sw-yx** [gatsbyjs/gatsby#16143]
## Description

The composition story for [default themes](https://github.com/gatsbyjs/gatsby/tree/master/themes) needs to be tested and explained. here's an example of the user experience: https://www.youtube.com/watch?v=oxgzfBaQMik

### Steps to reproduce

clone https://github.com/sw-yx/browse-gatsby-themes/tree/reproGatsbyThemesClash

and follow 

https://www.youtube.com/watch?v=oxgzfBaQMik

### Expected result

seamless composition as long as i get the theme options right

### Actual result

clashy clashy

### Environment

```

    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
    Yarn: 1.17.0 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 75.0.3770.142
    Firefox: 67.0.4
    Safari: 12.1.1
```

**Comment by alexluong** [comment]
Hey @sw-yx. I think the 2 default themes weren't supposed made to work together.

In the video, you mention some JS were broken when you were trying to switch from light -> dark mode. What happened was that both themes overshadow `gatsby-plugin-theme-ui/index.js`, and whichever theme is registered after takes precedence.

Since `gatsby-theme-notes` was after and it doesn't have dark and light mode functionality, switching it didn't work.

Overall, I think themes composition is a great thing but not every theme will play well with one another.
