### ISSUE TITLE
Gatsby build error "TypeError: Cannot read property 'split' of null" related to firebase

### ISSUE THREAD

**Issue by maximechofflet** [gatsbyjs/gatsby#16181]
## Description:
error message on gatsby build on Netlify: TypeError: Cannot read property 'split' of null

#### My code 

`import React, {Component} from 'react';

import StyledFirebaseAuth from "react-firebaseui/StyledFirebaseAuth"
import firebase from "firebase/app"
import "firebase/auth"

firebase.initializeApp({
  apiKey: "xxxxxx",
    authDomain: "xxxxx",
    databaseURL: "xxxxx",
    projectId: "xxxx",
    storageBucket: "",
    messagingSenderId: "xxxxx",
    appId: "xxxxx"
})

class IndexPage extends Component {
  state = {
    isSignedIn : false,
}

uiConfig = {
  signInFlow: 'popup',
  signInOptions: [
    firebase.auth.GoogleAuthProvider.PROVIDER_ID,
    firebase.auth.EmailAuthProvider.PROVIDER_ID,
  ], callbacks: {
    signInSuccessWithAuthResult : () => false
  }
}

componentDidMount = () => {
  const app = import ('firebase')
  if (typeof window !== `undefined`) {
    const app = import ('firebase')
  firebase.auth().onAuthStateChanged(user => {
   
      this.setState({ isSignedIn: !!user })
 
})
  }
}

render() {
    return(
      <div>
      {this.state.isSignedIn ? (
        <div>Sign In !</div>)
        : (
          
            < StyledFirebaseAuth 
        uiConfig = {this.uiConfig} 
        firebaseAuth={firebase.auth()}/>
      
    )}
    </div>
    )
}
}

export default IndexPage`

##### Error message on Netlify

![Capture d’écran de 2019-07-29 13-56-03](https://user-images.githubusercontent.com/45247673/62046729-f156f080-b208-11e9-922d-bd5bc505eeaa.png)

If someone can explain me how to make this working, thanks !

**Comment by alexluong** [comment]
Hey @maximechofflet, the problem with Firebase is that `firebase.initializeApp` uses `window`, which is `undefined` in build step. Here are a few resources that can help you set up Firebase with Gatsby:

- https://kyleshevlin.com/firebase-and-gatsby-together-at-last
- https://github.com/muhajirdev/gatsby-starter-firebase

I also wrote a blog post regarding Firebase and Gatsby that's about to be published. You can get a "sneak peak" here: https://www.notion.so/alexluongg/A-Journey-Through-Gatsby-Build-Process-via-Building-a-Plugin-10eb8112478844ed9ba4759804e9821b

And consider using [my plugin](https://github.com/alexluong/gatsby-plugin-firebase) that I literally just released. Feel free to reach out if you have any questions.

**Comment by maximechofflet** [comment]
Thank you very much for your answer @alexluong  this is very helpful. For now I still have the same error maybe due to `uiConfig` that I can't put in `componentDidMount() `  because it becomes undefined in rendering.

**Comment by alexluong** [comment]
If you read my [blog post](https://dev.to/alexluong/a-journey-through-gatsby-build-process-via-building-a-plugin-4nei) (which is published btw), I explained what’s the pitfall of setting up firebase, dealing with undefined, and the solutions.

**Comment by jonniebigodes** [comment]
@maximechofflet i've picked up on your issue and if you don't mind i can expand a bit on this issue.
Below are the steps i took to triage this and get a working gatsby site with firebase auth.
- Created a new gatsby site based on the hello world starter.
- Added the necessary dependencies, `firebase`, `react-firebaseui` and `react-loadable`.
Nothing to much in here asides from the last package added, which you can read more about it [here](https://github.com/jamiebuilds/react-loadable#readme), despite the fact that the project is probably dead at this point from what i search. But It will work in the meantime until `Suspense` is working properly with Gatsby and SSR.
- Created a new firebase project and added only the email/password auth provider for simplicity.
- Grabbed the project configuration from firebase and moved into a .env file to allow Gatsby access to it without exposing it widely. You can more about it in [here](https://www.gatsbyjs.org/docs/environment-variables/.
- Created a component called `SimpleFirebase.js` under `src/components` with the following code:
```javascript
import React, { Component } from "react"
import StyledFirebaseAuth from "react-firebaseui/StyledFirebaseAuth"
import firebase from "firebase/app"
import "firebase/auth"
import "../assets/css/app.css"
import "../assets/css/simplefirebase.css"

const firebaseApp=firebase.initializeApp({
  apiKey: process.env.GATSBY_FIREBASE_APIKEY,
  authDomain: process.env.GATSBY_FIREBASE_AUTHDOMAIN,
  databaseURL: process.env.GATSBY_FIREBASE_DATABASEURL,
  projectId: process.env.GATSBY_FIREBASE_PROJECT_ID,
  storageBucket: process.env.GATSBY_FIREBASE_STORAGE,
  messagingSenderId: process.env.GATSBY_FIREBASE_MESSAGESENDER,
  appId: process.env.GATSBY_FIREBASE_APPID,
})

class SimpleFirebase extends Component {
  state = {
    isSignedIn: false,
  }
  componentDidMount() {
    this.unregisterAuthObserver = firebase.auth().onAuthStateChanged(user => {
      this.setState({ isSignedIn: !!user })
    })
  }
  componentWillUnmount() {
    this.unregisterAuthObserver()
  }
  render() {
    const { isSignedIn } = this.state
    return (
      <div className="container">
        <div className="caption">This is a cool demo app</div>
        {isSignedIn !== undefined && !isSignedIn && (
          <div>
            <StyledFirebaseAuth
              className="firebaseUi"
              uiConfig={{
                // Popup signin flow rather than redirect flow.
                signInFlow: "popup",
                // We will display Google and Facebook as auth providers.
                signInOptions: [
                    firebase.auth.EmailAuthProvider.PROVIDER_ID,
                ],
                credentialHelper: 'none', // disables authchooser when logs out
                callbacks: {
                  // Avoid redirects after sign-in.
                  signInSuccessWithAuthResult: () => false,
                },
              }}
              firebaseAuth={firebaseApp.auth()}
            />
          </div>
        )}
        {isSignedIn && (
          <div className='signedIn'>
            Hello {firebaseApp.auth().currentUser.displayName}. You are now
            signed In!
            <a
              className='button'
              onClick={() => firebaseApp.auth().signOut()}
            >
              Sign-out
            </a>
          </div>
        )}
      </div>
    )
  }
}
export default SimpleFirebase
```
This component is based on the example provided in [here](https://github.com/firebase/firebaseui-web-react). The only exceptions are,  `credentialHelper` is set to none to prevent a redirect to the authchooser website as in this case it's not needed. Also all css added is the one used for that example.
- Modified `pages/index` to the following:
```javascript
import React from "react"
import Loadable from "react-loadable"
const loader = () => <div>Setting up firebase auth...</div>

const MyLoadableFirebaseAuth = Loadable({
  loader: () => import("../components/SimpleFirebase"),
  loading: loader,
})
export default () => (
  <div>
    <MyLoadableFirebaseAuth />
  </div>
)

```
With this small change it will make the component being loaded only on the client side and avoid issues like the one you've experienced.
- Issued `gatsby build && gatsby serve` and i was able to get a production build without issues and test it.
- Added the code to a [github repo](https://github.com/jonniebigodes/gatsby-simple-firebase-auth-example) and deployed it to [netlify](https://fervent-shannon-4eef92.netlify.com/) and no issues there.

Feel free to provide feedback so that we can close this issue or continue to work on it until we find a suitable solution.

**Comment by maximechofflet** [comment]
Sorry for the late reply. I close the issue.

**Comment by dougwithseismic** [comment]
Anyone having their builds blocked because they're calling firebase functions in client, the tl;dr that wasn't all that obvious from here is to check for whether window exists when defining firebase, as so: 

`  
import firebase from 'gatsby-plugin-firebase'

const isBrowser = () => typeof window !== 'undefined'
  const Firebase = isBrowser() ? firebase : {}`

**Comment by eerrecalde** [comment]
If anyone coming over to this issue looking to fix this, I've got the build working with `react-firebase-hooks` and `gatsby-plugin-firebase` by replacing useAuthState from `react-firebase-hooks` with a custom hook as suggested here: 

https://gist.github.com/jeffreymeng/78bd7f6b0f301fa5ef04359cd512222b 

So if you have created the hook as in the link above, the next step would be to change the implementation as following: 

```old
import firebase from 'gatsby-plugin-firebase';
import { useAuthState } from 'react-firebase-hooks/auth';
...
const [user, userLoading] = useAuthState(firebase.auth());
```

```new
import firebase from 'gatsby-plugin-firebase';
import useAuthState from '../hooks/use-auth-state'; // Changed
...
const [user, userLoading] = useAuthState(firebase); // Changed
```
