### ISSUE TITLE
--https fails if the path of the project contains spaces

### ISSUE THREAD

**Issue by salmaDariwsh** [gatsbyjs/gatsby#16212]
## Description

command `gatsby run develop --https` fails in the generate certificate step if the path of the project contains spaces

### Steps to reproduce

I'm on windows, so I don't know if the same steps will reproduce the issue on other OS's
1. Create a user whose name contains spaces
1. Create a project anywhere
1. Install openssl and add it to the PATH env variable
1. run the command `gatsby develop --https`

### Expected result

Gatsby generates certificate and starts an https server

### Actual result

Error
`Error: Command failed: openssl genrsa -out C:\Users\User Name With Spaces\AppData\Local\devcert\config\devcert-ca-root.key 2048`
and process exits

### Environment

  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
  Binaries:
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.15
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    gatsby: ^2.13.3 => 2.13.3 
    gatsby-image: ^2.2.4 => 2.2.4 
    gatsby-plugin-intl: ^0.2.6 => 0.2.6 
    gatsby-plugin-manifest: ^2.2.1 => 2.2.1 
    gatsby-plugin-offline: ^2.2.0 => 2.2.0 
    gatsby-plugin-react-helmet: ^3.1.0 => 3.1.0 
    gatsby-plugin-sharp: ^2.2.2 => 2.2.2 
    gatsby-source-filesystem: ^2.1.2 => 2.1.2 
    gatsby-transformer-sharp: ^2.2.1 => 2.2.1

**Comment by freiksenet** [comment]
Hello!

Thank you for reporting this! I suspect that the generated certificate isn't escaped. It shouldn't be a very big fix. Would you like to make a PR fixing that? We would greatly appreciate that.

Thank you! :purple_heart: :muscle:

**Comment by sagarnasit** [comment]
@freiksenet I would love to contribute by fixing this. Let's discuss how to achieve this.

**Comment by Js-Brecht** [comment]
The issue here is in the npm package `devcerts-san`, called from here:
> <https://github.com/gatsbyjs/gatsby/blob/c1960a260d3fbd5b6f57fb29317693d45a0686d3/packages/gatsby/src/utils/get-ssl-cert.js>

That particular error is generated here:
> <https://github.com/davewasmer/devcert/blob/v0.3.2/src/utils.ts#L36>

But this whole function will have trouble:
> <https://github.com/davewasmer/devcert/blob/v0.3.2/src/index.ts#L81-L88>

That utility is calling `openssl` from the shell, and unquoted/unescaped strings are being dropped into the command.

There is version 1.0.0, though.  It is now called [`devcert`](https://www.npmjs.com/package/devcert) (instead of `devcert-san`), and after a quick look at these few lines, it looks like the bug has been fixed:
> <https://github.com/davewasmer/devcert/blob/master/src/certificates.ts#L28>
> <https://github.com/davewasmer/devcert/blob/master/src/certificates.ts#L36>
> <https://github.com/davewasmer/devcert/blob/master/src/certificates.ts#L44>


Upgrading the package should work, but it wouldn't be just a simple version upgrade, since there were breaking changes.  A few things that would effect Gatsby.
* [For one, the function is now a named export, and the name has changed](https://github.com/davewasmer/devcert/blob/master/src/index.ts#L38)
* [The options parameter has changed](https://github.com/davewasmer/devcert/blob/master/src/index.ts#L20-L24)
* The path where it installs certs has changed, so anything that relies on them being in a certain location will break.
* The return values have changed
     * Notice that the `keyPath` and `certPath` are no longer returned.

> <https://github.com/davewasmer/devcert/blob/v0.3.2/src/index.ts#L71-L76>
 vs
> <https://github.com/davewasmer/devcert/blob/master/src/index.ts#L71-L74>

(Node's `https.createServer()` [(called here to setup the server)](https://github.com/gatsbyjs/gatsby/blob/c1960a260d3fbd5b6f57fb29317693d45a0686d3/packages/gatsby/src/commands/develop.js#L283) does not require the key/cert paths.  Which is probably why they are no longer returned by `devcert`.)

> Options are listed here:
> <https://nodejs.org/api/tls.html#tls_tls_createsecurecontext_options>

**Comment by rmorabia** [comment]
I'm currently tackling this issue! I'm running some tests and should have a PR this weekend.

**Comment by rmorabia** [comment]
Hey, made a PR above! I'm running Linux, so I can't confirm if the fix runs on Windows. Can someone on Windows run my fork and see if this issue still fails? Thank you!

**Comment by Js-Brecht** [comment]
Still in progress

**Comment by Js-Brecht** [comment]
PR fixing this issue is ready to be reviewed/merged.
