### ISSUE TITLE
svg-sprite-loader does not seem to work 

### ISSUE THREAD

**Issue by Polyhistor** [gatsbyjs/gatsby#16236]
Once I install **gatsby-plugin-svg-sprite** I get the following weird error: 

```
 error  in ./src/fonts/Nunito/fonts/subset-Nunito-SemiBold.svg

Module build failed (from /Users/navigate_17/Desktop/Gatsby/WildKiwi/node_modules/svg-sprite-loader/lib/loader.js):
ExtractPluginMissingException: svg-sprite-loader exception. svg-sprite-loader in extract mode requires the corresponding plugin
    at Object.loader (/Users/navigate_17/Desktop/Gatsby/WildKiwi/node_modules/svg-sprite-loader/lib/loader.js:53:13)
```

I get that error for **every svg file** that I've got in my project. I've read both the **documentation on Gatsby and Github**, but it's quit thin and I haven't found any question with the relevant issue.

 Why the plugin causes such an issue?  and how can I make this work?

**Comment by freiksenet** [comment]
Hi @Polyhistor!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction
