### ISSUE TITLE
[gatsby-plugin-offline] Uncaught (in promise) DOMException

### ISSUE THREAD

**Issue by bjatwork** [gatsbyjs/gatsby#16311]
i get errors: 
"Uncaught (in promise) DOMException" sw.js:1 
The installing service worker became redundant.   register-service-worker.js:50 

with gatsby-plugin-offline and no other error messages. I used pure gatsby starter. 
What is next step to debug that?  
**https://imgur.com/a/qiMETkT**

**Comment by freiksenet** [comment]
Hi @bjatwork!

Sorry to hear you're running into an issue. Unfortunately I couldn't reproduce it. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by bjatwork** [comment]
@freiksenet  Thanks, this problem has disappeared, I don't know what caused it
