### ISSUE TITLE
when I add gatsby-plugin-page-creator to gatsby-config.  The createPagesStatefully is execed twice in the gatsby build.

### ISSUE THREAD

**Issue by bojan0624** [gatsbyjs/gatsby#16379]
## Summary

when I add gatsby-plugin-page-creator to gatsby-config.  The createPagesStatefully is execed twice in the gatsby build.

## Relevant information

Gatsby CLI version: 2.7.21
Gatsby version: 2.3.22
Gatsby-plugin-page-creator version: 2.1.5

### Environment

gatsby build --prefix-paths

### File contents (if changed)

`gatsby-config.js`: 
{
    resolve: `gatsby-plugin-page-creator`,
    options: {
      path: `${__dirname}/src/pages`,
      ignore: [`**/components/*.(js|ts)`, `**/_*/**`],
    }
  }

**Comment by freiksenet** [comment]
Hi @bojan0624!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by bojan0624** [comment]
> Hi @bojan0624!
> 
> Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction](https://gatsby.dev/reproduction). This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.
> 
> If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction](https://gatsby.dev/reproduction) and we'll be able to take another look.
> 
> Thanks for using Gatsby! 💜

I think I have problems like the https://github.com/gatsbyjs/gatsby/issues/12937.  
createPagesStatefully is executed once with Gatsby-cli default settings and once with custom settings.
I have modified my page root path /pages with /views, to avoid default settings。

Could you add prompt for this situation in Gatsby build command?
Debugging the source code is really painful.

Do you still need me to provide an example?

And thanks for u2 reply! ❤️

**Comment by wardpeet** [comment]
Closing as it's a duplicate of https://github.com/gatsbyjs/gatsby/issues/17379
