### ISSUE TITLE
Cannot query field "featured_media" on type "wordpress__PAGE"

### ISSUE THREAD

**Issue by xuweiwei117526** [gatsbyjs/gatsby#16378]
During our Gatsby build,the project can not start when using npm start

Any assistance would be appreciated!

Describe the issue that you're seeing.

### Steps to reproduce

npm start

### Actual result

There was an error in your GraphQL query:
Cannot query field "featured_media" on type "wordpress__PAGE"

**Comment by jonniebigodes** [comment]
@xuweiwei117526 can you confirm something for me.
In your `gatsby-config.js` do you have the media route activated in the included routes?
Something like this:
```javascript
{
      resolve: `gatsby-source-wordpress`,
      options: {
        .........
        includedRoutes: [
          "**/categories",
          "**/posts",
          "**/pages",
          "**/media",
        ],
      }
    }
```
If not that might be the case. I've tested against my local wordpress installation and if i don't have it activated it results in that issue.

Feel free to provide feedback so that we can close this issue or continue to work on your issue until we find a suitable solution.

**Comment by chawax** [comment]
Hello,

I had such an error and I found it was due to a 500 HTTP error with `/wp/v2/media` request. I work with a shared web hosting service, so it was not that easy to get logs. But i finally understood it came from maximum MySQL opened connections exceeded.

I set `concurrentRequests` to 1 in `gatsby-node-config.js` and I have no more the problem. It takes longer to build of course, but at least it is stable now !

Hope it will help.
