### ISSUE TITLE
theme extending causes looping in some cases

### ISSUE THREAD

**Issue by mischor** [gatsbyjs/gatsby#16383]
## Description

When extending a component in a theme, the instructions say to create a same-named file in <myProj>/<the-theme>/src/components/  folder.  There are many ways to do this, and some of them cause infinite looping (in the browser, if running with gatsby develop, or in the creation of static web pages, when running gatsby build).

### Steps to reproduce

It's easy to reproduce.  Here's an example (running with node.js current version 10.16.1, on Windows 10).  
1) in some working directory, run:  npx gatsby new my-carbon-site https://github.com/carbon-design-system/gatsby-starter-carbon-theme 

2) verify the starter site is OK: do gatsby develop, and when it's ready, look at the site on localhost:8000.

3)here's how to cause the loop.  
  3a) add a Footer folder to mimic the node_modules folder structure for Footer:
        add a folder: <testProj>/src/gatsby-theme-carbon/components/Footer
        move the existing extend-version of Footer into that folder:
          <testProj>/src/gatsby-theme-carbon/components/Footer.js  move to
          <testProj>/src/gatsby-theme-carbon/components/Footer/Footer.js

Now reset the browser, and do a gatsby clean, followed by a gatsby develop, and when it finishes, try to open the file - it will "loop", and not show the result.

This can be avoided, even with this mimicking folder structure, by changing the import statement in the extending-version of Footer from:
   import Footer from 'gatsby-theme-carbon/src/components/Footer/Footer.js'
to
  import Footer from 'gatsby-theme-carbon/src/components/Footer/Footer'
that is, just drop the file type.

It seems that if the folder structure and the file name are exact matches for the thing being extended, a loop results.

### Expected result

The resulting web page should display in a browser (for gatsby develop), or the gatsby build command should complete.

### Actual result

for gatsby develop, the resulting web page "loops" and won't display, or for gatsby build, the command loops in the step where it is generating the static web site.

### Environment

  System:
    OS: Windows 10
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.17763.1.0
  npmPackages:
    gatsby: ^2.13.39 => 2.13.50 
    gatsby-theme-carbon: ^1.6.1 => 1.7.0

**Comment by freiksenet** [comment]
CC @ChristopherBiscardi

**Comment by ChristopherBiscardi** [comment]
The core problem here is that when performing step 3a, the file being shadowed changes from `Footer` to `Footer/Footer`. According to the node require algorithm (without shadowing), `Footer.js` and `Footer/index.js` are the same file, so the original shadowing works because `Footer.js` in the site shadows `Footer/index.js` in the theme. When the file is moved to `Footer/Footer.js`, it changes to shadow `Footer/Footer.js` in the theme, which is a different file. So conceptually, without shadowing, you end up with `Footer/Footer.js` importing `Footer/index.js` *and* `Footer/index.js` importing `Footer/Footer.js`, resulting in an infinite loop.

So we could implement some sort of cycle detection possibly. I opened up a new issue for that #16449 

Basically the problem is that you've created an infinite loop, with or without shadowing, by having one file import another and that file import the original.

---

Here's more of a in depth explanation from my twitch stream today (video available as VOD here: https://www.twitch.tv/chrisbiscardi; will post youtube link when it uploads.):

````
# src/components/Footer in theme
# ~ == src/components/

---

~/Footer/index.js
[shadows at] site/src/gatsby-theme-carbon/components/Footer.js
[shadows at] site/src/gatsby-theme-carbon/components/Footer/index.js

```js
// ~/Footer/index.js
// same as ~/Footer.js
import Footer from './Footer';

export default Footer;
```

---

~/Footer/Footer.js
[shadows at] site/src/gatsby-theme-carbon/components/Footer/Footer.js
[shadows at] site/src/gatsby-theme-carbon/components/Footer/Footer/index.js

```
import React from 'react';
import Footer from 'gatsby-theme-carbon/src/components/Footer';

const CustomFooter = () => <Footer />;

export default CustomFooter;
```

````
