### ISSUE TITLE
[gatsby-remark-autolink-headers] Icons don't hide and headings aren't centered correctly when used with gatsby-plugin-mdx

### ISSUE THREAD

**Issue by hanzhihua72** [gatsbyjs/gatsby#16422]
## Description

The icons are showing even when you don't hover over, and the headings aren't centered correctly.

### Steps to reproduce

https://minimal-blog.lekoarts.de/react-live-code-example#a-live-code-sample

Code for the starter blog can be found here:

https://github.com/LekoArts/gatsby-starter-minimal-blog

### Expected result

The icon should show only when you hover the mouse over, and the headings should be left centered correctly.

### Actual result

![image](https://user-images.githubusercontent.com/43427025/62589140-8602c380-b885-11e9-8ed7-40053a2a3b23.png)

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by freiksenet** [comment]
This theme isn't an official Gatsby starter, please report this issue to https://github.com/LekoArts/gatsby-starter-minimal-blog.

**Comment by LekoArts** [comment]
@freiksenet 	It's not really an issue with my starter but rather with `gatsby-plugin-mdx`. You can see it working in this codesanbox: https://codesandbox.io/s/gatsby-starter-minimal-blog-wyk4i

Because I added the workaround:

```js
plugins: [`gatsby-remark-autolink-headers`]
```

Bug report: https://github.com/gatsbyjs/gatsby/issues/15486
It's the same issue basically
