### ISSUE TITLE
wrapPageElement still remounts everything on certain pages

### ISSUE THREAD

**Issue by kmcaloon** [gatsbyjs/gatsby#16489]
So I am using wrapPageElement to wrap pages with a layout that I don't want remounting when transitioning from page to page. What's weird is that when I start on a page and go to any page other than home for the first time everything remounts. Then if I go back to the first page that I already accessed it transitions as it should. Plus, if I start on any page other than the homepage then go to the homepage it transitions the way it should. All of my pages are being created during build with createPage. Any ideas??

**Comment by freiksenet** [comment]
Hello @kmcaloon!

Sorry to hear you are having an issues. I wonder if you could produce a minimal reproduction for this issue, this would help us immensely in trying to debug it.

Thanks! :purple_heart: :muscle:

**Comment by herecydev** [comment]
Very similar to what I've raised: #16243

**Comment by ValeraS** [comment]
In development mode, `JSONStore` detaches page while page data fetching and this cause page rerender:
https://github.com/gatsbyjs/gatsby/blob/d055527b3be04639d572b052535c7c13b7317efe/packages/gatsby/cache-dir/json-store.js#L85-L95

This happens if we did not visit this page yet and a page data was not prefetched.

**Comment by kmcaloon** [comment]
Awesome, thanks for the clarification @ValeraS. Is this necessary to have in development? If so, the docs probably want to indicate that layouts will not always function as expected when developing.
