### ISSUE TITLE
gatsby-plugin-layout nav links wont work

### ISSUE THREAD

**Issue by SSelke** [gatsbyjs/gatsby#16485]
My application is having a problem with the navigation links being re rendered every time I click on a Link. I had it narrowed down to pages that were created using contentful page data so I assumed that I should try to move the layout up above the pages so they will not re render. When I used gatsby-plugin-layout, the component stopped re rendering when the nav links were clicked, however they no longer work. They change the URL however they do not initiate a re render of the pages. Any ideas on this on guys? I would be open to not having to use the layout plugin if there is a known work around. I also checked up on some other issues that are similar to mine however they do not help.

**Comment by freiksenet** [comment]
Hi @SSelke!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by SSelke** [comment]
Thank you for reaching out. It appeared the issue was a conflict between gatsby-plugin-layout and styled-components; in particular when loading fonts. Will post bug issue soon.
