### ISSUE TITLE
Test suite failed to run with Cannot find module gatsby

### ISSUE THREAD

**Issue by sidharthachatterjee** [gatsbyjs/gatsby#16535]
Tests fail _strangely_ sometimes like in https://circleci.com/gh/gatsbyjs/gatsby/192130?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Currently no idea why (re running the workflow resolves this) but it would be nice to investigate this and make this less flaky

**Comment by Darking360** [comment]
Hey @sidharthachatterjee I've been taking a look to this and trying some combinations in my own fork, but inspecting a little more the build for that PR that you attached I found that one of the requires is `bootstrap` and this is in charge of run `bootstrap` from `lerna` on all packages and the prepares, the problem is that looking into [that step](https://circleci.com/workflow-run/8dffaf2e-f7a1-4ae3-b37f-bd72b73242dc) in particular, it looks like it didn't run the `bootstrap` because it seems that [it thinks](https://circleci.com/gh/gatsbyjs/gatsby/192123) that there were no changes with this function:

```
./scripts/assert-changed-files.sh "packages/*|(e2e|integration)-tests/*|.circleci/*"
```

Inside the function, it compares if there are files diff in git, the problem is that it marks it as success and that's ok, but since it's finished **before** it generates the `bootstrap` it continues to the other pipeline steps like the tests for `unit_tests_node10` or `unit_tests_node12` and they fail because they don't have the packages bootstrapped 🤔 What I found really weird is that you mentioned that re-running the workflow it works, so that means that in the new workflow the `bootstrap` function did generate for good the files, it's really weird 💥 

Another thing is that if you take a look into the steps I found really strange that `unit_tests_node8` passed without the bootstrapped files, but when expanding [that step](https://circleci.com/gh/gatsbyjs/gatsby/192126) it looks like it happens the same as bootstrap with a call to the diff files function, maybe it's because of the `requires: - bootstrap` inside CircleCI configuration 🤔 

The script for the diff was made by @DSchau maybe he could have a clue, but it's really weird anyway. I'm not a CircleCI master though hehe I think we should take a look maybe to the diff files function to check, maybe it doesn't see the changes, or is being done before the git checkout command? Something like that 🤔 Or maybe always generate the bootstrap? Not pretty sure 

I think is a start to look 😅 

Some images from CircleCI:

![image](https://user-images.githubusercontent.com/4975574/63455658-30005500-c41b-11e9-8b5a-f23b3304dd50.png)

![image](https://user-images.githubusercontent.com/4975574/63455720-52926e00-c41b-11e9-9ced-a367fdd9c1d3.png)
