### ISSUE TITLE
gatsby-transformer-react-docgen not picking up components wrapped with forwardRef

### ISSUE THREAD

**Issue by tu4mo** [gatsbyjs/gatsby#16544]
## Description

gatsby-transformer-react-docgen not picking up components wrapped with `forwardRef`.

### Steps to reproduce

1. Install `gatsby-transform-react-docgen`.
2. Add component with `forwardRef`.

### Expected result

You should see the component by querying allComponentMetadata.

### Actual result

Component isn't listed in allComponentMetadata.

### Environment

  System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.16.2 - ~/.nvm/versions/node/v10.16.2/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.2/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 76.0.3809.100
    Firefox: 68.0.1
    Safari: 12.1.2
  npmPackages:
    gatsby: ^2.13.58 => 2.13.58 
    gatsby-image: ^2.2.8 => 2.2.8 
    gatsby-plugin-manifest: ^2.2.5 => 2.2.5 
    gatsby-plugin-offline: ^2.2.5 => 2.2.5 
    gatsby-plugin-react-helmet: ^3.1.3 => 3.1.3 
    gatsby-plugin-sharp: ^2.2.11 => 2.2.11 
    gatsby-source-filesystem: ^2.1.9 => 2.1.9 
    gatsby-transformer-react-docgen: ^5.0.1 => 5.0.1 
    gatsby-transformer-sharp: ^2.2.6 => 2.2.6 
  npmGlobalPackages:
    gatsby-cli: 2.7.30

**Comment by tu4mo** [comment]
Not stale.

**Comment by lavelle** [comment]
Is there any progress on this? It's preventing us from migrating some of our components to TypeScript, since the API docs then no longer appear. It works fine with components using `forwardRef` and the `prop-types` library though.

I'd be happy to contribute a fix myself if you could provide some pointers on where to look. I'm interested on where the bug arises, because it seems like a similar issue was closed in the underlying `react-docgen` library a while ago: reactjs/react-docgen#267

**Comment by lavelle** [comment]
cc @danoc who may be interested in fixing the missing API docs in thumbtack/thumbprint

**Comment by tu4mo** [comment]
Looks like `forwardRef` components work with the latest `gatsby-transformer-react-docgen`, so I'm closing this.
