### ISSUE TITLE
gatsby-theme-blog error when using footnotes

### ISSUE THREAD

**Issue by ManoelLobo** [gatsbyjs/gatsby#16578]
## Description

The gatsby-theme-blog produces an error when trying to use markdown footnotes

### Steps to reproduce

1. Create a new Gatsby site using the gatsby-theme-blog (e.g `gatsby new my-themed-blog https://github.com/gatsbyjs/gatsby-starter-blog-theme`)
2. Create a post with footnotes in it (or add a footnote to one of the sample pages)
3. Run `yarn develop`

### Expected result

The page content should be generated and the development site should be available.

### Actual result

Errors on terminal [full log](https://gist.github.com/ManoelLobo/1ce21d45aee57827d239c4f76ca8b8be)

```
 ERROR #11321  PLUGIN

"gatsby-plugin-mdx" threw an error while running the onCreateNode lifecycle:

definition.identifier.toUpperCase is not a function

// here goes the trace

success building schema - 0.201 s

 ERROR 

definition.identifier.toUpperCase is not a function

// here goes the trace
```

### Environment
  System:
    OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: x64 Intel(R) Xeon(R) CPU E3-1280 v3 @ 3.60GHz
    Shell: 5.4.2 - /bin/zsh
  Binaries:
    Node: 10.16.2 - /usr/bin/node
    Yarn: 1.17.3 - /usr/bin/yarn
    npm: 6.9.0 - /usr/bin/npm
  Languages:
    Python: 2.7.15+ - /usr/bin/python
  Browsers:
    Firefox: 68.0.1
  npmPackages:
    gatsby: ^2.13.61 => 2.13.61 
    gatsby-image: ^2.2.8 => 2.2.8 
    gatsby-plugin-manifest: ^2.2.5 => 2.2.5 
    gatsby-plugin-offline: ^2.2.5 => 2.2.5 
    gatsby-plugin-react-helmet: ^3.1.3 => 3.1.3 
    gatsby-plugin-sharp: ^2.2.11 => 2.2.11 
    gatsby-source-filesystem: ^2.1.9 => 2.1.9 
    gatsby-theme-blog: ^1.0.2 => 1.0.2 
    gatsby-transformer-sharp: ^2.2.6 => 2.2.6 

### More info

It looks like one of the remark plugins of the theme - `gatsby-remark-numbered-footnotes` - is causing the issue. Removing it from the gatsby-config of the theme made it work (obviously without the functionality of the plugin)

**Comment by kennethvandenberghe** [comment]
I narrowed this down to a issue between remark-numbered-footnotes and mdast-util-definitions.

1. remark-numbered-footnotes changes the footnotes identifiers to numbers [here](https://github.com/zestedesavoir/zmarkdown/blob/master/packages/remark-numbered-footnotes/src/index.js#L35).

2. Later on the mdast-util-to-hast `onfootnotedefinition()` get's called with `definition.identifier` to be a number, and trying to call `toUpperCase()` on it. [here](https://github.com/syntax-tree/mdast-util-to-hast/blob/master/lib/index.js#L88)

3. Later on in the mdast-util-to-hast footer.js file the util tries to call `toUpperCase()` again on the identifier. [here](https://github.com/syntax-tree/mdast-util-to-hast/blob/master/lib/footer.js#L21)


If I make sure to return a string in the `createIds()` from remark-numbered-footnotes it solves the errors you encounter.

```diff
function createIds(footnotes) {
  return function (node, index, parent) {
    var identifier = node.identifier;

    if (!footnotes.hasOwnProperty(identifier)) {
---   footnotes[identifier] = Object.keys(footnotes).length + 1;
+++   footnotes[identifier] = `${Object.keys(footnotes).length + 1}`;
    }

    node.identifier = footnotes[identifier];
  };
}
```

But not sure if it is indeed the correct solution for this problem, since I have not a lot of knowledge about this all (mdast, remark, ...). Hope this can start solving the issue.

**Comment by jlengstorf** [comment]
I opened https://github.com/syntax-tree/mdast-util-to-hast/pull/34 to see if we can get this fixed upstream. I don't think this is something we can address in Gatsby, though.

**Comment by jlengstorf** [comment]
Also needs https://github.com/zestedesavoir/zmarkdown/pull/362 now that the `node.label` is used for ref links.

**Comment by pieh** [comment]
Update on this: Jason's pull request ( https://github.com/syntax-tree/mdast-util-to-hast/pull/34 ) has been merged and released and new `@mdx-js/mdx` version was published.

You should be able to reinstall dependencies to grab new versions that fixes the problem. If you have `yarn.lock` - you might need to run something like `yarn remove gatsby-theme-blog && yarn add gatsby-theme-blog` to force refresh of dependencies of those)

**Comment by jlengstorf** [comment]
I can confirm that this update fixes the error. However, we're still waiting on https://github.com/zestedesavoir/zmarkdown/pull/362 because the footnoes use `node.label` instead of `node.identifier` now, which means the numbered footnotes plugin only kinda works at the moment.

**Comment by jlengstorf** [comment]
This is fixed!

**Comment by ManoelLobo** [comment]
Thank you very much @jlengstorf and everyone else that contributed on this issue. You are all awesome!
