### ISSUE TITLE
failed during stage 'building site': Build script returned non-zero exit code: 127

### ISSUE THREAD

**Issue by DavidTNguyen** [gatsbyjs/gatsby#16570]
## Description

**11:18:24 PM: Error running command: Build script returned non-zero exit code: 127
11:18:24 PM: Failing build: Failed to build site
11:18:24 PM: failed during stage 'building site': Build script returned non-zero exit code: 127**
11:18:24 PM: Finished processing build request in 1m25.704599563s

### Steps to reproduce

github repo: https://github.com/davidtnguyen/blog
netlify build command: `yarn build`
master branch

### Expected result

build complete exit 0

### Actual result

`failed during stage 'building site': Build script returned non-zero exit code: 127`

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

  System:
    OS: macOS 10.14.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.8.0 - ~/.nvm/versions/node/v12.8.0/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.10.2 - ~/.nvm/versions/node/v12.8.0/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 75.0.3770.142
    Safari: 12.0.3
  npmPackages:
    gatsby: ^2.13.61 => 2.13.61 
    gatsby-link: ^2.2.4 => 2.2.4 
    gatsby-plugin-catch-links: ^2.1.2 => 2.1.2 
    gatsby-plugin-feed: ^2.3.6 => 2.3.6 
    gatsby-plugin-flow: ^1.1.2 => 1.1.2 
    gatsby-plugin-google-gtag: ^1.1.4 => 1.1.4 
    gatsby-plugin-manifest: ^2.2.5 => 2.2.5 
    gatsby-plugin-netlify: ^2.1.4 => 2.1.4 
    gatsby-plugin-netlify-cms: ^3.0.18 => 3.0.18 
    gatsby-plugin-offline: ^2.2.5 => 2.2.5 
    gatsby-plugin-react-helmet: ^3.1.3 => 3.1.3 
    gatsby-plugin-sass: ^2.1.8 => 2.1.8 
    gatsby-plugin-sharp: ^2.2.11 => 2.2.11 
    gatsby-plugin-sitemap: ^2.2.6 => 2.2.6 
    gatsby-remark-autolink-headers: ^2.1.3 => 2.1.3 
    gatsby-remark-copy-linked-files: ^2.1.5 => 2.1.5 
    gatsby-remark-images: ^3.1.10 => 3.1.10 
    gatsby-remark-katex: ^3.1.2 => 3.1.2 
    gatsby-remark-prismjs: ^3.3.5 => 3.3.5 
    gatsby-remark-relative-images: ^0.2.3 => 0.2.3 
    gatsby-remark-responsive-iframe: ^2.2.4 => 2.2.4 
    gatsby-remark-smartypants: ^2.1.2 => 2.1.2 
    gatsby-source-filesystem: ^2.1.9 => 2.1.9 
    gatsby-transformer-remark: ^2.6.13 => 2.6.13 
    gatsby-transformer-sharp: ^2.2.6 => 2.2.6 
  npmGlobalPackages:
    gatsby-cli: 2.7.30

**Comment by jonniebigodes** [comment]
@DavidTNguyen i've picked up on your issue. 

These are the steps i took to triage your issue.
- Cloned your repo.
- Installed the dependencies
- Modified `gatsby-config.js` to the following:
```javascript
'use strict';

const siteConfig = require('./config.js');
const postCssPlugins = require('./postcss-config.js');

module.exports = {
  siteMetadata: {
    url: siteConfig.url,
    title: siteConfig.title,
    subtitle: siteConfig.subtitle,
    copyright: siteConfig.copyright,
    disqusShortname: siteConfig.disqusShortname,
    menu: siteConfig.menu,
    author: siteConfig.author
  },
  plugins: [
  ......
    {
      resolve: 'gatsby-plugin-netlify-cms',
      options: {
        modulePath: `${__dirname}/src/cms/index.js`,
      }
    },
    `gatsby-plugin-netlify`
  ]
};

```
I omitted the full plugin configuration for brevity. But the key part of this is that when using netlify and netlify and it's cms, i had to push down the the location of the plugins to the end so that i could get a working build, either in development or production.

- Modified `static/admin/config.yml` to the following:
```yml
backend:
  #name: git-gateway
  name: github
  #branch: master
  repo: jonniebigodes/test_gatsby_netlify_cms
```
Once again based on a personal experience between the two, some people have reported issues with the git gateway aswell, so probably you could try it out on your end with this approach, modifying the repo key to your own repo.
- Issued `gatsby build && gatsby serve` and i'm presented with the following:

![davidtnguyen_dry_run_2_error](https://user-images.githubusercontent.com/22988955/62953423-6ae40680-bde5-11e9-8306-93b0d1e820cd.png)

After testing out which plugin was responsible for the issue i finally narrowed it down to the gatsby netlify plugin. You can read more on it in #15256. With that in mind i bumped the packages version and added [netlify-cms-app](https://www.npmjs.com/package/netlify-cms-app).
Your package.json now looks like this:
```json
"dependencies": {
    "bluebird": "^3.5.5",
    "classnames": "^2.2.6",
    "codecov": "^3.5.0",
    "gatsby": "^2.13.61",
    "gatsby-link": "^2.2.4",
    "gatsby-plugin-catch-links": "^2.1.2",
    "gatsby-plugin-feed": "^2.3.6",
    "gatsby-plugin-flow": "^1.1.2",
    "gatsby-plugin-google-gtag": "^1.1.4",
    "gatsby-plugin-manifest": "^2.2.5",
    "gatsby-plugin-netlify": "^2.1.4",
    "gatsby-plugin-netlify-cms": "^4.1.6",
    "gatsby-plugin-offline": "^2.2.5",
    "gatsby-plugin-react-helmet": "^3.1.3",
    "gatsby-plugin-sass": "^2.1.8",
    "gatsby-plugin-sharp": "^2.2.11",
    "gatsby-plugin-sitemap": "^2.2.6",
    "gatsby-remark-autolink-headers": "^2.1.3",
    "gatsby-remark-copy-linked-files": "^2.1.5",
    "gatsby-remark-images": "^3.1.10",
    "gatsby-remark-katex": "^3.1.2",
    "gatsby-remark-prismjs": "^3.3.5",
    "gatsby-remark-relative-images": "^0.2.3",
    "gatsby-remark-responsive-iframe": "^2.2.4",
    "gatsby-remark-smartypants": "^2.1.2",
    "gatsby-source-filesystem": "^2.1.9",
    "gatsby-transformer-remark": "^2.6.13",
    "gatsby-transformer-sharp": "^2.2.6",
    "invariant": "^2.2.4",
    "katex": "^0.11.0",
    "lodash": "^4.17.15",
    "moment": "^2.24.0",
    "netlify-cms": "^2.9.7",
    "netlify-cms-app": "^2.9.7",
    "node-sass": "^4.12.0",
    "normalize-scss": "^7.0.1",
    "prismjs": "^1.17.1",
    "react": "^16.9.0",
    "react-disqus-comments": "^1.4.0",
    "react-dom": "^16.9.0",
    "react-helmet": "^5.2.1"
  },
  "devDependencies": {
    "@babel/core": "7.5.5",
    "@babel/plugin-proposal-class-properties": "7.5.5",
    "@babel/plugin-proposal-optional-chaining": "7.2.0",
    "@babel/plugin-transform-flow-strip-types": "^7.4.4",
    "@babel/preset-env": "7.5.5",
    "@babel/preset-react": "7.0.0",
    "autoprefixer": "9.6.1",
    "babel-core": "7.0.0-bridge.0",
    "babel-eslint": "10.0.2",
    "babel-jest": "24.8.0",
    "babel-preset-gatsby": "0.2.8",
    "browserslist": "4.6.6",
    "concurrently": "4.1.1",
    "eslint": "6.1.0",
    "eslint-config-airbnb-base": "14.0.0",
    "eslint-plugin-import": "2.18.2",
    "eslint-plugin-jest": "22.15.1",
    "eslint-plugin-jsx-a11y": "6.2.3",
    "eslint-plugin-react": "7.14.3",
    "eslint-watch": "6.0.0",
    "flow-bin": "^0.105.2",
    "flow-typed": "^2.6.1",
    "gh-pages": "2.0.1",
    "identity-obj-proxy": "3.0.0",
    "jest": "24.8.0",
    "jest-cli": "24.8.0",
    "lost": "8.3.1",
    "postcss-pxtorem": "4.0.1",
    "react-test-renderer": "16.9.0",
    "rimraf": "2.6.3",
    "standard-version": "7.0.0",
    "stylelint": "10.1.0",
    "stylelint-config-recommended-scss": "3.3.0",
    "stylelint-scss": "3.9.3"
  }
```
- Modified `src/cms/index.js` to the following to accomodate the change made:
```javascript
// import CMS from 'netlify-cms';
import CMS from 'netlify-cms-app';
import PagePreview from './preview-templates/page-preview';
import PostPreview from './preview-templates/post-preview';

CMS.registerPreviewTemplate('pages', PagePreview);
CMS.registerPreviewTemplate('posts', PostPreview);

```
- Issued `gatsby build && gatsby serve` and i'm presented with the following:


![davidtnguyen_dry_run_3](https://user-images.githubusercontent.com/22988955/62954319-1a6da880-bde7-11e9-8980-69b5a9496d0d.png)

- Opened up a new browser window to `http://localhost:9000` and i'm presented with the following:
![davidtnguyen_dry_run_4](https://user-images.githubusercontent.com/22988955/62954418-42f5a280-bde7-11e9-8a4f-dbe5636f4e82.png)


Feel free to provide feedback so that we can close this issue or continue to work on it until we find a suitable solution.

**Comment by DavidTNguyen** [comment]
Thank you @jonniebigodes for a very thorough explanation!

I thought to clarify that the issue has never been about running the site locally in 'develop' mode.  It's when I try to deploy it on Netlify.  The exception report was excerpted from the  Netlify blog itself during deployment.

Was you able to deploy it on your own Netlify sandbox?

**Comment by DavidTNguyen** [comment]
I also had to change the netlify.toml file to the following.  it worked now ✅
> [build]
>   publish = "public"
>   command = "gatsby build"
>
> [build.environment]
>   YARN_VERSION = "1.3.2"
>   YARN_FLAGS = "--no-ignore-optional"
>
