### ISSUE TITLE
Extend themes with subplugins

### ISSUE THREAD

**Issue by lannonbr** [gatsbyjs/gatsby#16593]
> @lannonbr Any idea what I'm doing wrong here? I'm hoping to extend `@narative/gatsby-theme-novela`'s use of `gatsby-transformer-remark`: https://github.com/AryanJ-NYC/webdev-coach-blog/blob/move-to-narrative/gatsby-config.js#L32.

_Originally posted by @AryanJ-NYC in https://github.com/gatsbyjs/gatsby/issues/15549#issuecomment-520958930_

With plugins that have sub-plugins, how do we particularly extend the a plugin like this so we can add more sub-plugins inside a theme. In this instance @AryanJ-NYC wants to add in an additional remark plugin.

**Comment by lannonbr** [comment]
cc: @ChristopherBiscardi

**Comment by ChristopherBiscardi** [comment]
in the future we'll have an `onPluginOptions` lifecycle so that all `gatsby-transformer-remark` sub-plugins could be combined into a single instance. For now themes have to expose the optionality to modify sub-plugins or allow users to turn off the `gatsby-transformer-remark` plugin and instantiate their own.

**Comment by ChristopherBiscardi** [comment]
Closing in favor of the feature request ticket at https://github.com/gatsbyjs/gatsby/issues/16697
