### ISSUE TITLE
gatsby-source-shopify 2.2.2 build error

### ISSUE THREAD

**Issue by adamonsoon** [gatsbyjs/gatsby#16702]
gatsby-source-shopify v 2.2.2 attempts to read the const `NODE_TO_ENDPOINT_MAPPING` from `./nodes` instead of `./constants`, which results in failure.
https://github.com/gatsbyjs/gatsby/commit/ce1bf9c8446083ed38667c37b2c7ded04ac89561#diff-9f1a842cf44ff7772dcebf087a07eb00L17

The issue is fixed in the following commit, which also removes references to `PRODUCT_TYPE`, and has not been merged to the 2.x branch.
https://github.com/gatsbyjs/gatsby/commit/7c62aea35200e7eef5ef9bdd58b511540ff7ebc4#diff-9f1a842cf44ff7772dcebf087a07eb00R29

Until an updated version is available, I found that v 2.2.1 works as expected.

**Comment by sidharthachatterjee** [comment]
@adamonsoon [gatsby-source-shopify](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-source-shopify) 3.0.0 was published with this fix. 

The reason it is a major version bump is because the shopify API removed the undocumented `ProductType` and therefore that was removed as a root query type. 

Please upgrade to `3.0.0` as `2.x` will no longer be maintained.
