### ISSUE TITLE
Adding print and social share buttons (including email) in a markdown file

### ISSUE THREAD

**Issue by jnsrikanth** [gatsbyjs/gatsby#16710]
## Summary
I am trying to add print and social share capabilities to my blog post page (the final page for a Blog Item/Post) inside the markdown body of the blog post. 
I wanted to know how to achieve this in the current GatsbyJS / ReactJS environment.

I have not seen specific documentation at GatsbyJS site pertaining to adding such extraneous capabilities inside a Markdown file using GatsbyJS

### Environment (if relevant)
GatsbyJS V2 

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by sidharthachatterjee** [comment]
A Gatsby app is simply a React app so you should be able to use React components to add social sharing buttons etc

A library that I found is https://github.com/SaraVieira/react-social-sharing (seems to include social sharing buttons for most platforms)

If you want to use React components in Markdown, you can do so using MDX which you can learn more about at:

- https://www.gatsbyjs.org/docs/mdx/
- https://www.gatsbyjs.org/packages/gatsby-plugin-mdx/

Hope this answers your question! Closing this since further implementation details are largely out of scope of Gatsby.
