### ISSUE TITLE
Can the output of gatsy be served by any server?

### ISSUE THREAD

**Issue by hhimanshu** [gatsbyjs/gatsby#16752]
## Summary
I used `gatsby build` and have the `public` directory.
I ran `python -m SimpleHTTPServer 8000`, and I am able to serve `hello-world`.

```sh
➜  public git:(master) ✗ python -m SimpleHTTPServer 8000
Serving HTTP on 0.0.0.0 port 8000 ...
127.0.0.1 - - [19/Aug/2019 17:14:20] code 404, message File not found
127.0.0.1 - - [19/Aug/2019 17:14:20] "GET /socket.io/?EIO=3&transport=polling&t=MoiN-7a HTTP/1.1" 404 -
127.0.0.1 - - [19/Aug/2019 17:14:26] code 404, message File not found
127.0.0.1 - - [19/Aug/2019 17:14:26] "GET /socket.io/?EIO=3&transport=polling&t=MoiN_fr HTTP/1.1" 404 -
127.0.0.1 - - [19/Aug/2019 17:14:28] "GET /page-data/contact/page-data.json HTTP/1.1" 200 -
127.0.0.1 - - [19/Aug/2019 17:14:29] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Aug/2019 17:14:29] "GET /webpack-runtime-d1964fddcd1401535e40.js HTTP/1.1" 200 -
127.0.0.1 - - [19/Aug/2019 17:14:29] "GET /app-dc3dfc0e62aa3bc13266.js HTTP/1.1" 200 -
127.0.0.1 - - [19/Aug/2019 17:14:29] "GET /component---src-pages-index-js-221f4bd3dfba5cced8ac.js HTTP/1.1" 200 -
127.0.0.1 - - [19/Aug/2019 17:14:29] "GET /page-data/index/page-data.json HTTP/1.1" 200 -
127.0.0.1 - - [19/Aug/2019 17:14:29] "GET /component---src-pages-contact-js-e2244f8d527736478721.js HTTP/1.1" 200 -
127.0.0.1 - - [19/Aug/2019 17:14:30] "GET /favicon.ico HTTP/1.1" 200 -
127.0.0.1 - - [19/Aug/2019 17:14:31] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Aug/2019 17:14:32] "GET /favicon.ico HTTP/1.1" 200 -
127.0.0.1 - - [19/Aug/2019 17:14:35] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Aug/2019 17:14:35] "GET /favicon.ico HTTP/1.1" 200 -
127.0.0.1 - - [19/Aug/2019 17:14:44] "GET /contact HTTP/1.1" 301 -
127.0.0.1 - - [19/Aug/2019 17:14:44] "GET /contact/ HTTP/1.1" 200 -
```

What I am interested is in if the `public` directory can be served by any server such as `serve`, `python -m SimpleHTTPServer 8000` in production

Thanks

**Comment by georgiee** [comment]
1. Yes, that folder is intended to hold only files that can be served by any webserver.

2. Most people will pick apache or nginx but you can indeed pick anything that is suitable for production (security, performance & configuration options). You don't want to use `SimpleHTTPServer` for any production usage. Their documentation tells you about this and that's what you should check for any server you want to try
> SimpleHTTPServer is not recommended for production. It only implements basic security checks.

You neither want to use [gatsby serve](https://www.gatsbyjs.org/docs/gatsby-cli/) as it's meant for testing.
> At the root of a Gatsby site, serve the production build of your site for testing.

It's using a node express server internally which would be fine to serve static files but even then you would put a nginx or apache in front of it (reverse proxy) to save requests to it as it's less performant than any nginx/apache.

3. Instead of building your own server a specialized service like https://www.netlify.com/  or https://zeit.co/now might help you.

There is a a whole chapter about deployment on the Gatsby documentation:
https://www.gatsbyjs.org/docs/deploying-and-hosting/

**Comment by sidharthachatterjee** [comment]
Closing this as @georgiee has answered this better than we could! Please feel free to reopen or comment if you have any other related questions.

**Comment by hhimanshu** [comment]
All makes sense. Thanks @georgiee !
