### ISSUE TITLE
[gatsby-remark-images] Option to download remote images

### ISSUE THREAD

**Issue by rikakomoe** [gatsbyjs/gatsby#16780]
## Summary

gatsby-remark-images [doesn't](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-images/src/index.js#L133) process images located on other hosts, may there be an option to download remote images

### Basic example

If the image path appears not hosted locally, run [createRemoteFileNode](https://www.gatsbyjs.org/packages/gatsby-source-filesystem/#createremotefilenode) API and replace the original image path with file node's publicURL

### Motivation

 To use the fancy lazy load and blur in feature with a CMS backend, instead of local md files

**Comment by jamessimone** [comment]
@rikakomoe this is not a total solution, but I [wrote a blog post](https://www.jamessimone.net/blog/image-optimization-with-gatsby) about how to do this with createRemoteFileNode as a local plugin for gatsby. The article may need some updating - your suggestion of using the file node's publicURL may be all that is necessary, instead of what I do (which is using react-dom to fully render the gatsby-image component), but I won't have the chance to test that theory at the moment as I am traveling.

Hopefully the final example code at the end of my post ends up being of some use to you; if gatsby-remark-images can pick up on the presence of remotely downloaded files by just swapping the URL referenced after downloading the images with createRemoteFileNode, please let me know. Otherwise, I will follow up when I have some more time to attempt that solution myself.

**Comment by rikakomoe** [comment]
@jamessimone Thank's for the post and response.

I guess it won't be a problem for `gatsby-remark-images` to do this since it handles the process of local images at the moment and there shouldn't be so much differences after a remote image is downloaded. 

However I'm just suggesting this feature, never have I read the code thoroughly so there could be something I've missed.

**Comment by rikakomoe** [comment]
Replying doesn't keep the issue open, I just had an issue closed by the bot 🙃

**Comment by joewood** [comment]
I forked the remark-images plugin and changed the Markdown Image find to use the url property, rather than the dirname. This seems to have worked (as long as you preload your remote images into the tree first). I can do a PR and add a "remote mode" for this plugin, but there is the assumption that the image nodes would be created first.

**Comment by rikakomoe** [comment]
@joewood Glad to hear that but I wished it could fetch the remote image automatically ("`createRemoteFileNode`" after it parsed the Markdown document) couldn't it? I didn't know what image will be included in the Markdown document so there's no way can I do this "preload" outside the plugin.

**Comment by joewood** [comment]
That's really a separate phase of the build process. It's quite easy to parse the markdown for images and call createRemoteFileNode for the image URL. The complete fix for this will depend very much on your the source of your nodes.

**Comment by benedictjohannes** [comment]
This plugin looks promising, [gatsby-remark-images-anywhere](https://www.gatsbyjs.org/packages/gatsby-remark-images-anywhere/). Have you given it a try?
