### ISSUE TITLE
Move loaders out of Gatsby into starters

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#168]
Loaders should be easily owned/modified by site builders. They are the key part to the file => data => HTML/JS processing pipeline Gatsby provides. The default loaders should be easily hackable and moving them to starters would support that.

This is a potent source of confusion as shown by #134 and #167.

**Comment by phlogisticfugu** [comment]
In using gatsby, I'm actually finding that I'd want the opposite of this.  It'd be nice if the base gatsby came more "batteries included", loaded, wrappers, and all.

Right now one is required to do some hacking (React code) in order to use gatsby at all.  For example, I would expect that putting in a "title" in the front-matter in markdown files would specify the page title, but find I need to use react-document-title and implement that myself.

It'd be really great if the core gatsby just let one write some HTML/CSS/markdown, and have a site (or better yet, just write some markdown).  Progressive levels of customization could then be added for folks who want to get more "advanced", instead of requiring that from the start.  It isn't quite there yet, as gatsby is still in a work in progress, but I was wondering @KyleAMathews, if that is your vision for the project?  Or is the "easy to use"/"batteries included" part meant to be built on top of gatsby?

I wonder if the confusion is because these are folks who want to use gatsby for the powerful hybrid static/SPA implementation it provides, and who find themselves drowning in the deep end, because there is no shallow end to the pool.

**Comment by KyleAMathews** [comment]
Yes! Thanks for bringing this up!

I've been trying to find time to write this up but Gatsby will be adding soon both a plugin system (all currently part of core functionality will be moved to plugins) and a theme system which are NPM-distributable packaged Gatsby site which has plugins and (optionally) components/content/templates/css pre-specified.

So this issue (needs closed) was written a while ago when my thinking wasn't quite crystallized but I agree 100% with you. There needs to be a "batteries-included" onramp for newcomers to Gatsby (or React/Webpack) or non-programmers while still retaining (and improving) the current easy customization.
