### ISSUE TITLE
Awesome Gatsby for react native?

### ISSUE THREAD

**Issue by santoshgistto** [gatsbyjs/gatsby#1695]
Is there any plan to support react native also 

_Sent from my Xiaomi Redmi Note 3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by slorber** [comment]
@KyleAMathews I'm trying to figure this out. This would mean using ReactNativeWeb which support SSR.

**Comment by slorber** [comment]
@santoshgistto hope this is what you were looking for:

https://github.com/slorber/gatsby-plugin-react-native-web
https://twitter.com/sebastienlorber/status/968510640762576896

**Comment by fk** [comment]
@slorber 👋 Hey! Wondering if you want to add https://github.com/slorber/gatsby-plugin-react-native-web to the list of Community plugins at https://www.gatsbyjs.org/docs/plugins/#community-plugins?

**Comment by slorber** [comment]
Hi

Sure I'll add it soon. I'm travelling and didn't have time to make a pr :)


Le 28 févr. 2018 11:52 AM, "Florian Kissling" <notifications@github.com> a
écrit :

@slorber <https://github.com/slorber> 👋 Hey! Wondering if you want to add
https://github.com/slorber/gatsby-plugin-react-native-web to the list of
Community plugins at https://www.gatsbyjs.org/docs/
plugins/#community-plugins?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/gatsbyjs/gatsby/issues/1695#issuecomment-369202510>,
or mute
the thread

**Comment by santoshgistto** [comment]
@slorber  yes,  thanks a lot 💯

**Comment by slorber** [comment]
@fk I made a PR: https://github.com/gatsbyjs/gatsby/pull/4309

**Comment by Jphilistin12** [comment]
> How would you imagine that working?

I can't assume to know what the OP meant. But I am trying to add contentful to my react native project using a gatsby plugin but I am running into a wall trying to figure out how to integrate gatsby then the contentful plugin.

**Comment by slorber** [comment]
@Jphilistin12 it's not really clear to me what you are trying to do at all. Gatsby plugins are not meant to be run inside ReactNative apps.
