### ISSUE TITLE
Gatsby Remark Prismjs Doesn't spread additional metadata From Code Block

### ISSUE THREAD

**Issue by GoPro16** [gatsbyjs/gatsby#16965]
## Description

When using `gatsby-remark-prismjs` with `@mdx-js/react` the remark transformer transforms the language in a code block to a corresponding `className`. When that happens it also doesn't take into account any arguments passed in after the fact.

### Steps to reproduce

Add additional metadata onto a codeblock in `mdx` and the resulting `className` will contain the additional metadata.

Example:
```
````jsx{showLineNumbers: true} live=true
<Button color="primary>Hello</Button>
```

### Expected result

Props sent to the mdx renderer
```js
{
 className: 'language-jsx'
live: true
}
```

### Actual result
```js
{
 className: 'language-jsxlive=true'
}
```
### Environment

```
  System:
    OS: macOS 10.14.5
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
    Yarn: 1.16.0 - ~/.nvm/versions/node/v10.15.0/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.15.0/bin/npm
  Languages:
    Python: 2.7.15 - /Users/kgray/.homebrew/bin/python
  Browsers:
    Chrome: 76.0.3809.87
    Firefox: 68.0.1
    Safari: 12.1.1
  npmGlobalPackages:
    gatsby-cli: 2.5.3
```

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction
