### ISSUE TITLE
Move needed require.context into an auto-written dot file and deprecate app.js

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#17]
Every site needs a `loadContext` function to create a Webpack context (Webpack doesn't let you create require contexts with variables meaning `loadContext` has to have a hardcoded path which means it must have a known relationship with the pages source directory.).

Right now you need an `app.js` file for this function. We should make that optional by auto-writing a `.gatsby.js` file in the root directory of a site. This would also remove a potential roadblock from people creating a Gatsby site + allow us to easily change/add to this `loadContext` function.

**Comment by andreypopp** [comment]
I think it should be possible to wrap `compiler.inputFileSystem` into some sort of virtual filesystem and write `app.js` there not to touch the real filesystem.

**Comment by KyleAMathews** [comment]
That would be *very* cool.

This is what I found from googling around https://github.com/webpack/webpack/issues/806 Looks like @theplan wasn't able to quite get it going...

Oh also this https://github.com/shama/webpack-stream/issues/3

**Comment by andreypopp** [comment]
So another idea is to move all site related metadata/config into a single place (I think `package.json` could be that place, we can store config under `gatsby` key instead of a separate TOML file) which could serve as an entry point for webpack compiler.

We would need another webpack loader which would transform `package.json` into `loadContext` function.
