### ISSUE TITLE
Having problems with react-responsive as in the closed issue #5183

### ISSUE THREAD

**Issue by greaber** [gatsbyjs/gatsby#17278]
I just tried using react-responsive today, and I'm facing the same issues discussed in #5183.  On the initial render, some desktop styles get applied on mobile on production builds (using a "mobile last" design where the default styles are for desktop -- maybe there would be the reverse problem with a "mobile first" design).  It doesn't happen in development, and even in production it only happens on the intial page load; after you navigate to a new route, everything is as it should be.

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by xuezzou** [comment]
same here!
