### ISSUE TITLE
Why are there no fields in contentful-source-gatsby DRAFT entries?

### ISSUE THREAD

**Issue by aofolts** [gatsbyjs/gatsby#17394]
## Summary

I have a `articleSeries` entry in Contentful, which contains a reference to some articles. I haven't published them all yet, but I linked to the drafts because I wanted to display links for published articles and plain text titles for the draft articles to show what's coming up.

- [Link] Example Published Article
- [Text] Example Draft Article
- etc...

Unfortunately, the draft entries don't have a `fields` field—just `sys`.

Why is this?

Shouldn't you be able to access fields on draft entries?

**Comment by LekoArts** [comment]
This sounds like you're expecting something from their API but don't get that data back, right? Have you already contacted contenful's support to ask if this data is available through their API? Maybe @Khaledgarbaya 	can chime in to say if that's a limitation of the source plugin or the API itself 👍

**Comment by Khaledgarbaya** [comment]
Hi @aofolts, draft entries won't show up in the payload that's why you won't see them.
you can use the preview API token to be able to see all the drafts.

Check the docs [here](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-source-contentful#using-preview-api) on how to use the preview api with the source plugin.

**Comment by aofolts** [comment]
Awesome, thanks @Khaledgarbaya! I haven't used the preview API yet, so I didn't think of that. I'll dive in tomorrow. Appreciate the tip. 👏
