### ISSUE TITLE
Errors on build process with 3rd party modules

### ISSUE THREAD

**Issue by deebov** [gatsbyjs/gatsby#17395]
Everything works on fine on development mode. But when I run `gatsby build` I get errors with 3rd party modules

```jsx
****
import onClickOutside from "react-onclickoutside"
****
const clickOutsideConfig = {
  handleClickOutside: () => Navigation.handleClickOutside,
}

export default onClickOutside(Navigation, clickOutsideConfig)
```

I am getting this error:

![image](https://user-images.githubusercontent.com/28673719/64281371-718d1600-cf6c-11e9-85c8-8f748f1cb104.png)

excluding this 3rd party didn't help because there are other 3rd parties. 
I tried to ignore this module via custom webpack configuration but it didn't help too. This is what I got after adding custom webpack configuration:
![image](https://user-images.githubusercontent.com/28673719/64281551-d183bc80-cf6c-11e9-874a-b870beddaf93.png)

This is my custom webpack config:

```javascript
exports.onCreateWebpackConfig = ({ stage, loaders, actions }) => {
  if (stage === "build-html") {
    actions.setWebpackConfig({
      module: {
        rules: [
          {
            test: /react-onclickoutside/,
            use: loaders.null(),
          },
        ],
      },
    })
  }
}
```

**Comment by jonniebigodes** [comment]
@deebov i've picked up on your issue and i have a solution for your issue. 
Despite you setting the ` use: loaders.null(),`, it seems that some packages, like the one you're using will still have some incompatibilities with gatsby.
Below are the steps i took to solve this.
- Created a new gatsby site based on the hello world starter.
- Added the following dependencies `react-onclickoutside` and `react-loadable`, this last one will defer the loading of the component to client side, with this package it will help with some issues like yours.
- Checked the following [example](https://codesandbox.io/s/vn66kq7mml) based on the [npm package](https://www.npmjs.com/package/react-onclickoutside) page.
- With the above in mind, created a new component called `Menu.js` inside `/src/components` with the following content:
```js
import React, { useState } from "react"
import onClickOutside from "react-onclickoutside"
import "../assets/css/menu.css"

const Menu = () => {
  const [isOpen, setIsOpen] = useState(false)

  const toggle = () => setIsOpen(!isOpen)
  Menu.handleClickOutside = () => setIsOpen(false)
  return (
    <li className={isOpen ? "m-menu -active" : "m-menu"} onClick={toggle}>
      <div> Open Menu </div>
      <ul className="m-menu__list">
        <li className="m-menu__item">
          <div className="m-menu__link">Log Out</div>
        </li>
      </ul>
    </li>
  )
}

const clickOutsideConfig={
    handleClickOutside: () => Menu.handleClickOutside
}

export default onClickOutside(Menu,clickOutsideConfig)
```
- Modified `src/pages/index.js` to the following:
```js
import React from "react"
import Loadable from "react-loadable"
import "../assets/css/menu.css"
// component to show something to the user while the actual component is loaded on the client side
const loader = () => <div>Loading Menu...</div>
//
const MyMenuLoadable = Loadable({
  loader: () => import("../components/Menu.js"),
  loading: loader,
})
export default () => (
  <div className="App">
    <MyMenuLoadable />
  </div>
)
```
Issued `gatsby build && gatsby serve` and i'm presented with the following:
![deebov_1](https://user-images.githubusercontent.com/22988955/64302574-e4ea5400-cf7b-11e9-8bc7-5114b111cd8f.png)

- Opened up a new browser window to `http://localhost:9000` and i'm presented with the following:
![deebov_2](https://user-images.githubusercontent.com/22988955/64302633-2b3fb300-cf7c-11e9-8f6a-a8ef0f9824d7.png)

And also:
![deebov_3](https://user-images.githubusercontent.com/22988955/64302643-34308480-cf7c-11e9-9bfb-1ee79652ec95.png)

One caveat with this approach/workaround. As basically defering the component to be loaded on the client side, so to say. You get the `Loading Menu...` text for a bit and then the actual component is loaded. I have the code hosted [here](https://github.com/jonniebigodes/gatsby_test_onclickoutside) and a live version [here](https://angry-mccarthy-7f1cda.netlify.com/).

Feel free to provide feedback so that we can close this issue, or continue to work on it until we find a suitable solution.

**Comment by deebov** [comment]
thank you @jonniebigodes for the response. The solution that you showed helped me )
