### ISSUE TITLE
Click on the same page goes to top is not working on production

### ISSUE THREAD

**Issue by mustofa-binary** [gatsbyjs/gatsby#17401]
## Description

Clicking on the same route using gatsby link won't go to the top of the page only when its deployed. it works fine on localhost. I host my gatsby app in netlify.

this is how I use the gatsby link
```
import { Link } from 'gatsby'
<Link
     activeClassName="active"
     to="/contact-us/"
     aria-label="Contact us"
     partiallyActive={true}
>
Contact us
</Link>
```

### Steps to reproduce

- Go to any page
- scroll down -> click the link route to the same page you are in

### Expected result

Go to the top of the page

### Actual result

Nothing happen

### Environment

  System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.11.2 - ~/.nvm/versions/node/v10.15.1/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 76.0.3809.132
    Firefox: 69.0
    Safari: 12.1.2
  npmPackages:
    gatsby: ^2.13.77 => 2.13.77
    gatsby-image: ^2.2.12 => 2.2.12
    gatsby-plugin-eslint: ^2.0.5 => 2.0.5
    gatsby-plugin-google-tagmanager: ^2.1.6 => 2.1.6
    gatsby-plugin-manifest: ^2.2.8 => 2.2.8
    gatsby-plugin-react-helmet: ^3.1.4 => 3.1.4
    gatsby-plugin-react-svg: ^2.1.2 => 2.1.2
    gatsby-plugin-remove-serviceworker: ^1.0.0 => 1.0.0
    gatsby-plugin-robots-txt: ^1.5.0 => 1.5.0
    gatsby-plugin-sharp: ^2.2.16 => 2.2.16
    gatsby-plugin-sitemap: ^2.2.8 => 2.2.8
    gatsby-plugin-styled-components: ^3.1.2 => 3.1.2
    gatsby-plugin-stylelint: ^3.2.0 => 3.2.0
    gatsby-source-filesystem: ^2.1.14 => 2.1.14
    gatsby-transformer-sharp: ^2.2.10 => 2.2.10
  npmGlobalPackages:
    gatsby-cli: 2.7.19

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction
