### ISSUE TITLE
Feature request: display a custom error page when a page is unavailable offline [gatsby-plugin-offline]

### ISSUE THREAD

**Issue by bjatwork** [gatsbyjs/gatsby#17569]
When i use "gatsby plugin offline" this work good in offline mode until user click page that he do not visit before. Then browser display no connection info and app crash. 

What is the best approach to prevent for this?

For example if client click link to the subpage that he do not have in cache i want want to display mesage "This page is not available in offline mode" and block moving to this location. 

Where can i find sample code to do this?

**Comment by p1t1ch** [comment]
So is it still not possible to add custom offline page instead of "dino page" for better UX? My idea was to add global catch handler on requests and send offline page from cache in response:

1. Create new page at `pages/offline.tsx`
2. Modify plugin config at `gatsby-config.js` to precache this page and append custom service worker code:
```js
{
    resolve: 'gatsby-plugin-offline',
    options: {
      appendScript: 'src/utils/sw.ts',
      precachePages: ['/offline'],
    },
},
```
3. Add catch handler in `src/utils/sw.ts` (not sure about this, maybe we need to filter navigation requests first somehow):
```ts
workbox.routing.setCatchHandler(() => {
  // ignoreSearch to skip WB_REVISION query
  return caches.match('/offline/index.html', { ignoreSearch: true })
})
```

But this approach doesn't work because `offline/index.html` is not added to Cache Storage like it was already pointed in issue #22439. In source code we can see that all HTML files except `offline-plugin-app-shell-fallback/index.html` are ignored: https://github.com/gatsbyjs/gatsby/blob/1cfa511af81dabf3f9ceb4741a63f726c774d4d8/packages/gatsby-plugin-offline/src/gatsby-node.js#L110-L114

If only we could add another exception in this array via some option... I was trying to add `globPatterns: ['**/*'],` in config just for testing purposes and it works indeed. But overriding this low level option is not a solution because it ended with all assets were added in precache manifest.
