### ISSUE TITLE
[meta] How to manage issue process when someone is assigned to an issue

### ISSUE THREAD

**Issue by lannonbr** [gatsbyjs/gatsby#17587]
## Summary

It has come up recently that there has been incidents in which someone asks to work on an issue, they are assigned, and then someone else goes ahead and creates a PR which gets merged. This leaves the original person who was going to work this in the dark which can look bad on many ends.

This was discussed yesterday in the Community Maintainers Meeting and we did talk about it, but given this is a human issue in the end, we were not able to have a solution to this problem, and such I suggested to bring this topic to a larger audience and collect feedback from the community on some ideas to go forward so we can try to mitigate this.

Some things brought up included:
* Having a time range after inactivity so if a person assigned to an issue is dormant, we could reach out and ask if they are still working on the issue or if it's alright if we un-assign them if they don't have the time to work on the issue and someone is interested in hopping in to work on it.
* have some more content in our contributing docs to point out suggestions on etiquette for when working through the issue -> PR process.

So with such, what other suggestions would possibly help out with this? Has things like this been tackled before in other larger OSS projects?

**Comment by harshitjuneja** [comment]
>> Has things like this been tackled before in other larger OSS projects? 
Happens frequently with projects after they achieve a certain scale in terms of contributors. 

Most projects go by the points that have been mentioned already in the discussion.

1. Having an informative label e.g. claimed for issues, that discourages others to pick an issue that's claimed.

2. Defining a time range after inactivity for issues and unassigning/assigning them accordingly. I think post 5 days of inactivity, there should be an automated warning and if the issue is still inactive, post 2 more days, it should be un-assigned. To remove the load from maintainers, it should be a bot.
