### ISSUE TITLE
[gatsby-remark-images] Large blank spaces / blurs in RSS feeds

### ISSUE THREAD

**Issue by fionawhim** [gatsbyjs/gatsby#17593]
## Description

The `gatsby-remark-images` plugin causes large blank space above images in RSS readers that apply the page’s inline styles.

This seems to be due to #14816, which moved the `<img>` tag’s positioning out of the `style` attribute and into a `<style>` tag that is not seen by RSS readers.

Because of this, the `<img>` is not absolutely positioned over the background element, which causes either a large white space or a blurry background, depending on the HTML support in the reader. Additionally, the image is not correctly sized.

### Steps to reproduce

1. Include `gatsby-remark-images` in a site and put an image in a blog post.
1. View the site in Reeder or NetNewsWire

### Expected result

Images naturally fit in with the content of the post.

### Actual result

The background element is not covered up, leaving either white space or a blurry image.

Here are shots of the Gatsby blog post [Creating a purpose-driven media platform](https://www.gatsbyjs.org/blog/2019-08-23-creating-a-purpose-driven-media-platform/)

NetNewsWire 5.0 on OS X:

<img width="923" alt="Screen Shot 2019-09-12 at 1 49 56 PM" src="https://user-images.githubusercontent.com/260837/64808212-d34d1180-d564-11e9-9219-a125085fb2eb.png">

Reeder on iOS:

![IMG_4160](https://user-images.githubusercontent.com/260837/64808254-dfd16a00-d564-11e9-8ab2-3a7ca8ac5fc9.PNG)

In some cases, such as FeedBin for the web, the RSS reader throws out enough of the CSS and HTML that it strips the background padding element, so things look fine:

<img width="690" alt="Screen Shot 2019-09-12 at 1 55 33 PM" src="https://user-images.githubusercontent.com/260837/64808320-0394b000-d565-11e9-9a00-a4e3820d5cd8.png">

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

  System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-4288U CPU @ 2.60GHz
    Shell: 3.0.2 - /usr/local/bin/fish
  Binaries:
    Node: 8.16.0 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.10.3 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  Browsers:
    Chrome: 76.0.3809.132
    Firefox: 68.0.2
    Safari: 12.1.2
  npmPackages:
    gatsby: ^2.13.68 => 2.15.5

**Comment by fionawhim** [comment]
Reopening because I'm finally pushing a PR to fix it.

**Comment by sslotsky** [comment]
Sorry to chime in on a closed issue but I think I'm also having this problem. When I view my feed I only see the blurred image. The URL to the high-res image is correct. I can open the image in a new tab and see the image. The problem appears to be that the `img` tag itself is taking up zero height. Any insight here? Help is appreciated.

https://saxyfool.dev/rss.xml

**Comment by sslotsky** [comment]
Update on the above :point_up: 

My conclusion that the image takes up zero height was hasty. It does take up zero height when I delete the sibling span node that contains the blurry image data. I did this to see if my image would show up. If I leave the span there, the image takes up the same dimensions and position, but isn't visible. This is on feedreader.com.

On the other hand, if I try to view my feed on feeder.io, they are using a relative URL for my image. When I inspect my rss.xml, I can see that the image paths are indeed relative, so feedreader.com must be doing some transformation that feeder.io is skipping. So I guess I have two questions:

1. Is there a way for the rss generation to transform image URLs so that they use the full image URL?
2. Any idea why my image isn't visible on feedreader.com despite the fact that they are using the full image URL?

**Comment by fionawhim** [comment]
@sslotsky Different readers are just gonna do different things I guess. I looked at your feed in NetNewsWire and the image at the top (of the street) looked as expected. No blank spaces or blurs anywhere.

**Comment by sslotsky** [comment]
That's Mac only, yeah? Sadly I can't verify. I'll take your word for that but so far the ratio isn't very good :smile: 

Even so. If we assume that some readers won't style these images well, I still think that using the absolute URL to the image file would be ideal so that readers don't have to transform. Is there a way to do that?
