### ISSUE TITLE
Add ARIA name to gatsby wrapper

### ISSUE THREAD

**Issue by trickydisco78** [gatsbyjs/gatsby#17617]
## Summary

Brief explanation of the feature.
Add accessibility ARIA name to outer div

currently set at

```
<div style="outline:none" tabindex="-1" role="group" id="gatsby-focus-wrapper">
```

### Motivation

This has been flagged by accessibility auditors as an accessibility issue

![image](https://user-images.githubusercontent.com/3627429/64879540-19ca6b00-d64e-11e9-93dc-07f132d405e1.png)

**Comment by r-i-c-h** [comment]
Dunno what tool you're using but for my 2c, I disagree with your auditor. The use of WAI-ARIA should be minimized, not aggressively thrown around which is the tendency of ppl less familiar with it. There is ZERO(?) circumstance in which a user will want to select\be-aware-of the existence of the overall wrapper. If anything, I wonder why the role="group" is there to begin with...

(Plus, if nothing else, it isn't a problem for Lighthouse).

**Comment by marcysutton** [comment]
Hey all, thanks for the issue. Regardless of what any given tool is reporting, it's worth considering the user impact of such a recommendation. The purpose of an accessible name for a landmark region would be to identify it from a list of landmarks and audibly present a string of information when that element is focused (as opposed to its contents). We're currently still in a research phase for how focus management will be handled in Gatsby, see this blog post: https://www.gatsbyjs.org/blog/2019-07-11-user-testing-accessible-client-routing/

Anything we change in the core framework should be tested extensively, and we're hiring someone to take that work on internally at the moment. Rather than add something by reacting to an automated test result, we should evaluate whether an accessible name would improve the outcome of focus management on route changes. See https://github.com/gatsbyjs/gatsby/issues/5581 for more information on the specifics of Gatsby's setup and what's happening in screen readers at the moment.

**Comment by LekoArts** [comment]
Thanks for the issue! As Marcy wrote we shouldn't just rely on an automated test but look into this in more detail. I'm closing this issue so that we can track it in https://github.com/gatsbyjs/gatsby/issues/5581 – please comment there if you further want to follow this up. Thanks!
