### ISSUE TITLE
"gatsby-source-custom-api" threw an error while running the sourceNodes lifecycle:

### ISSUE THREAD

**Issue by bjatwork** [gatsbyjs/gatsby#17628]
After "npm upgrade latest" i get following error: 
 
ERROR #11321  PLUGIN

"gatsby-source-custom-api" threw an error while running the sourceNodes lifecycle:

ENOENT: no such file or directory, open 'internal/process/task_queues.js'

  Error: ENOENT: no such file or directory, open 'internal/process/task_queues.js'

  - stack-trace-utils.js:33 getNonGatsbyCodeFrame
    [system]/[gatsby]/dist/utils/stack-trace-utils.js:33:19

  - public.js:637 createNode
    [system]/[gatsby]/dist/redux/actions/public.js:637:33

  - public.js:761
    [system]/[gatsby]/dist/redux/actions/public.js:761:19

  - index.js:11
    [system]/[redux-thunk]/lib/index.js:11:18

  - redux.js:481
    [system]/[redux]/lib/redux.js:481:12

**Comment by jonniebigodes** [comment]
Could you provide a reproduction, so that it could be looked at in more detail?

**Comment by bjatwork** [comment]
@jonniebigodes 
https://github.com/bjatwork/gatsbyreproduce

this happened on pure gatsby / gatsby-custom-api installation, after update. With previous gatsby version there was no errors.

**Comment by bjatwork** [comment]
@jonniebigodes 
repository - 

This happend on pure installation, with no modification


PS G:\work\gatsbyjs\reproduce> gatsby develop
success open and validate gatsby-configs - 0.076 s
success load plugins - 0.723 s
success onPreInit - 0.048 s
info One or more of your plugins have changed since the last time you ran Gatsby. As
a precaution, we're deleting your site's cache to ensure there's not any stale
data
success initialize cache - 0.076 s
success copy gatsby files - 0.171 s
success onPreBootstrap - 0.056 s
Object 'product': Better provide a schema!

 ERROR #11321  PLUGIN

"gatsby-source-custom-api" threw an error while running the sourceNodes lifecycle:

ENOENT: no such file or directory, open 'internal/process/task_queues.js'



  Error: ENOENT: no such file or directory, open 'internal/process/task_queues.js'

  - stack-trace-utils.js:33 getNonGatsbyCodeFrame
    [reproduce]/[gatsby]/dist/utils/stack-trace-utils.js:33:19

  - public.js:637 createNode
    [reproduce]/[gatsby]/dist/redux/actions/public.js:637:33

  - public.js:761
    [reproduce]/[gatsby]/dist/redux/actions/public.js:761:19

  - index.js:11
    [reproduce]/[redux-thunk]/lib/index.js:11:18

  - redux.js:481
    [reproduce]/[redux]/lib/redux.js:481:12

  - api-runner-node.js:73 doubleBoundActionCreators.<computed>
    [reproduce]/[gatsby]/dist/utils/api-runner-node.js:73:20

  - gatsby-node.js:54
    [reproduce]/[gatsby-source-custom-api]/gatsby-node.js:54:5

  - Array.forEach

  - gatsby-node.js:53 Object.exports.sourceNodes
    [reproduce]/[gatsby-source-custom-api]/gatsby-node.js:53:12

  - task_queues.js:89 processTicksAndRejections
    internal/process/task_queues.js:89:5


warn The gatsby-source-custom-api plugin has generated no Gatsby nodes. Do you need it?
success source and transform nodes - 1.211 s
success Add explicit types - 0.052 s
success Add inferred types - 0.210 s
success Processing types - 0.134 s
success building schema - 0.502 s
success createPages - 0.044 s
success createPagesStatefully - 0.117 s
success onPreExtractQueries - 0.051 s
success update schema - 0.070 s
success extract queries from components - 0.384 s
success write out requires - 0.079 s
success write out redirect data - 0.076 s
success Build manifest and related icons - 0.194 s
success onPostBootstrap - 0.285 s
⠀
info bootstrap finished - 7.832 s
⠀
success run static queries - 0.100 s — 3/3 52.74 queries/second
success run page queries - 0.063 s — 5/5 252.33 queries/second
success start webpack server - 1.251 s — 1/1 4.25 pages/second
 DONE  Compiled successfully in 3131ms                                                                                                                                                                     11:09:19⠀
You can now view gatsby-starter-default in the browser.
⠀
  http://localhost:8000/
⠀
View GraphiQL, an in-browser IDE, to explore your site's data and schema
⠀
  http://localhost:8000/___graphql
⠀
Note that the development build is not optimized.
To create a production build, use npm run build
⠀
i ｢wdm｣: Compiled successfully.

**Comment by jonniebigodes** [comment]
@bjatwork it seems that the issue lies with the plugin itself and a bit with your configuration/endpoint.
Looking at the documentation for the plugin itself and the response i got from the endpoint it seems that the plugin is expecting a certain type of data structure and what is being returned is a diferent thing.

Here are the steps i took to test this issue.
- Cloned the repo
- Removed `package-lock.json` and installed the dependencies, getting the latest versions of the required packages.
- Ran `gatsby develop` and and i'm presented with;
![bjatwork_1](https://user-images.githubusercontent.com/22988955/64927680-cac73600-d805-11e9-956c-f876f2f9bc40.png)

- Opened up postman and issued a request to the endpoint and i'm presented with the following:
![bjatwork_2](https://user-images.githubusercontent.com/22988955/64927676-c00ca100-d805-11e9-9698-d88200e1454f.png)

As it's expecting a certain type of structure and it's not there it throws the error, as it's not finding any images to fetch and process.

- Took the reproduction a bit further and created a simple express server with the following code:
```js
const express = require("express");

const app = express();

const port = 3000;

app.use(express.static("public"));
app.get("/", (_, res) => res.send("Hello World!"));
app.get("/data", (_, res) => {
  return res
    .status(200)
    .json([
      { name: "random-1", images:[{url: "http://localhost:3000/image-1.jpg"}] },
      { name: "random-2", images:[{url: "http://localhost:3000/image-2.jpg"}] },
      { name: "random-3", images:[{url: "http://localhost:3000/image-3.jpg"}] }
    ]);
});

app.listen(port, () => console.log(`Example app listening on port ${port}!`));

```
`image-1.jpg`,`image-2.jpg`, `image-3.jpg` are three random pictures i have laying around to triage issues.

With this in mind and the documentation for the plugin i changed `gatsby-config.js` to the following:
```
plugins:[
{
      resolve: "gatsby-source-custom-api",
      options: {
        url: {
          development: `http://localhost:3000/data`,
        },
        rootKey: "dummyData",
        imageKeys: ["images"],
        schemas: {
          dummyData: `
            name:String,
            images: [images]
          `,
          images: `
            url: String
          `,
        },
      },
    },
....
]
```
What the configuration is doing is trying to match what is returned from the api to a graphql schema and also providing a key namely `rootKey` to define the root type incoming from the api.
- Issued `gatsby clean && gatsby develop` to purge any data that was cached and issued a new build in development mode and i'm presented with the following:
```shell
$ gatsby develop
success open and validate gatsby-configs - 0.030 s
success load plugins - 1.204 s
success onPreInit - 0.004 s
success initialize cache - 0.011 s
success copy gatsby files - 0.271 s
success onPreBootstrap - 0.018 s
Image downloaded: image-1.jpg
Image downloaded: image-2.jpg
Image downloaded: image-3.jpg

 ERROR #11467 

The new node didn't pass validation: child "internal" fails because ["url" is not allowed]

Failing node:

{
    "name": "random-1",
    "images___NODE": [
        "4e8e485b-7d3f-52df-94fc-80cb8ddea34b"
    ],
    "id": "c46cd874-c31e-5254-bd6b-c76909e5b774",
    "parent": null,
    "children": [],
    "internal": {
        "type": "dummyData",
        "content": "{\"name\":\"random-1\"}",
        "contentDigest": "d2987078bb436ad8a07d949d333c66b9",
        "counter": 33,
        "owner": "gatsby-source-custom-api"
    }
}

Note: there might be more nodes that failed validation. Output is limited to one node per type of validation failure to limit terminal spam.

See our docs page for more info on this error: https://www.gatsbyjs.org/docs/actions/#createNode

warn The gatsby-source-custom-api plugin has generated no Gatsby nodes. Do you need it?
success source and transform nodes - 0.256 s
success Add explicit types - 0.008 s
⠀
```
In this mode i can get the data and see it in graphql explorer. But doing a production build fails.

After all of this it seems that the plugin needs probably some changes are in order to keep up with the constant mutation of gatsby . I would recomend you open a issue in that specific plugin repo and feel free to link my comment.

Feel free to provide feedback
