### ISSUE TITLE
gatsby-starter-default is flashing/ stuck in infinite loop

### ISSUE THREAD

**Issue by michelle-hoang** [gatsbyjs/gatsby#17621]
## Description

I am working on a project using the gatsby-starter-default. When I run gatsby-develop, my project will spin up on localhost/8000, but it flashes in different css styles and will not stop hot reloading (even though no changes have been made during this time). I had previously installed the gatsby manifest and offline plugins, but have since removed them from the config file. My project was loading properly without the flashing until today. 

I created a new gatsby-starter-default and did not make any changes to the repo. Upon calling gatsby develop, localhost:8000 goes into an infinite loop and gives an error about StaticQuery. 

### Steps to reproduce

Link to repo: https://github.com/michelle-hoang/gatsby-site

Git clone repo --> gatsby develop --> open localhost:8000 in google chrome

### Expected result

Site should load. 

### Actual result

My repo flashes rapidly in different css styles 
The gatsby-starter-default (no changes made) does not load at all and enters infinite loop. Hard refresh will stop the loop, but any change will cause the site to enter the loop again. 

[gatsby-error.mov 2.zip](https://github.com/gatsbyjs/gatsby/files/3611928/gatsby-error.mov.2.zip)

### Environment

System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - ~/n/bin/node
    npm: 6.10.3 - ~/n/bin/npm
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  Browsers:
    Chrome: 76.0.3809.132
    Safari: 12.1.2
  npmPackages:
    gatsby: ^2.15.14 => 2.15.14
    gatsby-image: ^2.2.18 => 2.2.18
    gatsby-plugin-manifest: ^2.2.16 => 2.2.16
    gatsby-plugin-react-helmet: ^3.1.7 => 3.1.7
    gatsby-plugin-robots-txt: ^1.5.0 => 1.5.0
    gatsby-plugin-sharp: ^2.2.21 => 2.2.21
    gatsby-source-filesystem: ^2.1.22 => 2.1.22
    gatsby-transformer-sharp: ^2.2.14 => 2.2.14
  npmGlobalPackages:
    gatsby-cli: 2.7.47

**Comment by michelle-hoang** [comment]
error is shown in .zip file

**Comment by michelle-hoang** [comment]
Here is the error from the gatsby-starter-default. 
[gatsby-starter.mov.zip](https://github.com/gatsbyjs/gatsby/files/3611947/gatsby-starter.mov.zip)

**Comment by simonjoom** [comment]
try to remove completely inside public/ and remove the folder .cache before to build again
it's look like the offline plugin do problem. on chrome remove the cache completly . in develop tools remove the cache from Application -> clear storage

**Comment by LekoArts** [comment]
So I cloned your project @michelle-hoang 	and run `gatsby develop`. I guess the good news are: I don't see the behavior you described / showed in the video. Bad news: I'm not 100% sure why that's happening to you.

Have you tried another browser? Which editor do you use (and maybe use a auto-saving extension/hot reloading?). Maybe try another editor. Can you try it on a different computer?

**Comment by joelwilsonmt** [comment]
I am having the same problem. In my case the loop doesn't appear to be infinite, but resolves after 10-15 reloads it would appear.

 Here are some more details:

- As far as I can tell, it is only happening on one page of the site (mypage.com/pricing)

- It is happening only in Google Chrome (I am running version 76.0.3809.132). It does not happen when accessing the page via a Chrome incognito window or any other browser

- It only happens when I navigate to the page directly. Going to mypage.com/pricing starts the loop. If I go to mypage.com and then click on a link to /pricing/, the loop does not happen

- It looks to be redirecting back on itself with/without the trailing slash in the URL. Here is a gif of the end of the URL as it loads: [http://www.giphy.com/gifs/WnBSdt6fEbsa0S2LcP](http://www.giphy.com/gifs/WnBSdt6fEbsa0S2LcP)

- As is the case with @michelle-hoang, it is only reproducible on my machine. I have checked on other machines and devices without the same result. Further, it does not occur during development (localhost:8000/pricing works fine), nor does it occur in a Netlify deploy preview - only when served to my domain.

Hope these details can help us get to the bottom of this

**Comment by waltercruz** [comment]
Hi @michelle-hoang! Cloned the project here and it runs fine, without any issues.

**Comment by michelle-hoang** [comment]
Hi all -- I am closing this issue. It turns out it was a cache issue with my Google Chrome browser. The issue is resolved when I run gatsby clean and clear the application cache on my dev tools.

**Comment by jacklaurencegaray** [comment]
I've just encountered this issue recently and was also fixed by clearing browser cache. This happens every now and then despite not having bugs within the app.

**Comment by nandorojo** [comment]
This happened to me on Safari. I fixed it by going to Develop -> Empty Caches

<img width="682" alt="Screen Shot 2020-06-14 at 1 19 07 PM" src="https://user-images.githubusercontent.com/13172299/84599657-a1454480-ae41-11ea-931e-640133960cbd.png">

**Comment by beamercola** [comment]
@nandorojo is there anything else you did here?  This has been plaguing me for 4 days now - across all projects

My steps:
1. Deleted localhost cookies
2. Develop > Empty Caches
3. Restart Safari
4. `gatsby clean`
5. `gatsby develop`
6. Refresh
7. Change something + Save
8. Disco duck

**Comment by nandorojo** [comment]
Honestly, don't remember, it was a long time ago. I use next.js now, I've liked it much more honestly. Fewer bugs like this.

**Comment by beamercola** [comment]
These fixes only seem to be temporary - i'm finding myself doing this 10+ times/day - across all projects.

Has anybody found a permanent solution to this?
