### ISSUE TITLE
[docs] [workflows] Implementing Google Amp

### ISSUE THREAD

**Issue by brolag** [gatsbyjs/gatsby#17645]
Part of the **Top 25 Learning Workflows initiative**. See #13708 for the meta issue that this issue falls under.

# User story

As a new Gatsby user, I want to implement Google AMP.

# Evaluation

[Change emoji below based on your evaluation.]

| Search | Discover | Complete | Linked | Tone | Style | Overall |
| --- | --- | --- | --- | --- | --- | --- |
| 😄 | 😞| 😐| 😄| 😐| 😐 | 😐 |

# Steps taken to implement

1. Searchability
i. Searched `gatsby implement google amp`; clicked [first result](https://www.gatsbyjs.org/packages/gatsby-plugin-amp/).

2. Discoverability
i. Searched `google amp` in search bar but didn't find the package link.

3. Completness
i. Followed steps in [Gatsby Plugin Amp](https://www.gatsbyjs.org/packages/gatsby-plugin-amp/)
ii. Installed Gatsby Plugin Amp
iii. Replaced `Img` component with `amp-img`  
vi. Success!
Notes: no tall tags are completed and documented.

4. Linked
i. Link to general information about Google AMP.
ii. Link to analytics types.
iii. Available components link is *broken*.
iv. Link for Google Analytics Client ID tutorial.

5. Tone
i. Very technical tone for options section and caveats section.

6. Style.
i. Minor issues only such as periods at ends. 

7. Overall
i. Not all tags are completed however plugin documentation is very self explanatory, it requires previous AMP knowledge. 

# Recommendations

- [ ] Provide examples for YouTube, Twitter and iframe, like it is described for amp-img.
- [ ] Fix end of paragraph punctuation. 
- [ ] Try Google Analytics, YouTube and Twitter implementations.

Feel free to edit this issue with more results about other HTML tags.

**Comment by marcysutton** [comment]
Reopening this as the workflow evaluation still needs to be implemented. Thanks so much for opening this issue!

**Comment by joyfulelement** [comment]
There had been discussions on https://github.com/gatsbyjs/gatsby/issues/13454 about the proposed requirement, POC experiments and action items on how Gatsby could provide first-class support for Google AMP. 

As much as myself also looking for information about how to support Google AMP with Gatsby, correct me if I am wrong, but base on what I understand on people's prior attempts with various plug-ins such as [gatsby-plugin-amp](https://github.com/jafaircl/gatsby-plugin-amp) mentioned by @brolag, [gatsby-plugin-google-amp](https://github.com/mukul-rathi/gatsby-plugin-google-amp) and [gatsby-plugin-html2amp](https://github.com/tomoyukikashiro/gatsby-plugin-html2amp), there are still work to be done in Gatsby core or plug-ins in order to complete the support for Google AMP. 

I believe this would continue block the recommended docs items until there is a clear path on how Gatsby decide to support Google AMP. Any idea if this is still on Gatsby's current roadmap @marcysutton? while [AMP continue to evolve](https://amp.dev/community/roadmap/), which is also [supported by Next a year ago](https://nextjs.org/blog/next-8-1). Thanks.
