### ISSUE TITLE
gatsby-link parse-path problem for full url. described & fixed here

### ISSUE THREAD

**Issue by simonjoom** [gatsbyjs/gatsby#17656]
I found a problem that gatsby load 404 resource on click on a link with a custom navigation
i use the code below
```
  $("#md-widget-toc a").each(function (i, a) {
    a.addEventListener("click", function (e) {
      console.log("clickwidget", e.currentTarget.href);
      e.preventDefault();

      window.___navigate(e.currentTarget.href);
    });
  });

```

the problem is e.currentTarget.href is a full url with the hostname, and gatsby is not properly parsing it, as a result the 404 resource are loaded. (even if it's not a real problem because the anchoring is working)

the code for 
https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-link/src/parse-path.js

below resolve it and remove the hostname of a full url

```
export function parsePath(path) {
  var pathname = path || `/`
  var search = ``
  var hash = ``
    var match = pathname.match(/^(https?\:)\/\/(([^:\/?#]*)(?:\:([0-9]+))?)([\/]{0,1}[^?#]*)(\?[^#]*|)(#.*|)$/);
   if(match){
  return { 
        pathname: match[5]?match[5]:"/",
        search: match[6],
        hash: match[7]
        }
}

  var hashIndex = pathname.indexOf(`#`)
  if (hashIndex !== -1) {
    hash = pathname.substr(hashIndex)
    pathname = pathname.substr(0, hashIndex)
  }

  var searchIndex = pathname.indexOf(`?`)
  if (searchIndex !== -1) {
    search = pathname.substr(searchIndex)
    pathname = pathname.substr(0, searchIndex)
  }

  return {
    pathname: pathname,
    search: search === `?` ? `` : search,
    hash: hash === `#` ? `` : hash,
  }
}
```

the problem come from gatsby (cache-dir/navigation) who use parsePath of gatsy-link but don't properly parse and remove the hostname.

const navigate = (to, options = {}) => {
  // Temp hack while awaiting https://github.com/reach/router/issues/119
  if (!options.replace) {
    window.__navigatingToLink = true
  }

  let { pathname } = parsePath(to)
...

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction
