### ISSUE TITLE
[feat]: enable source plugins to be called from the client

### ISSUE THREAD

**Issue by thomaswangio** [gatsbyjs/gatsby#17740]
## Summary

This FR is coming from @rmorabia's use case on [using a source plugin on the client side](https://twitter.com/radhikamorabia/status/1174565210591391744?s=20), which is currently not possible, because source plugins run at build time and is static data, unless the site is re-built. A poor solution would to be to trigger webhooks periodically to re-build the site, but this isn't ideal.

### Basic example

A possible solution could be a new Gatsby API that would look something like this:

```
import { SourcePlugins } from 'gatsby'

const SomeComponent = () => (
  <div>
    { SourcePlugins.[plugin-name].data }
  </div>
)
```

### Motivation

To allow source plugins to be run on the client side, and generate dynamic content on the client, when a user visits a specific page or opens a specific component.

**Comment by joperron** [comment]
This is basically Gatsby's caveat, it's the trade off we all make to get amazing performance.

I think a better approach to this would be the ability to query a specific node again, because I can see the massive performance drawbacks of having to source thousands of nodes and build a schema in the browser *while* a component loads.
