### ISSUE TITLE
How to use Iframe to introduce HTML files in Gatsbyjs?

### ISSUE THREAD

**Issue by PiccoloYu** [gatsbyjs/gatsby#17761]
I have an HTML file that I need to import and display in the form of an Iframe
![IAK45BAFRTPP 8%A{I%TUWI](https://user-images.githubusercontent.com/44945137/65322505-a7233780-dbd9-11e9-94de-58703d210295.png)
. But... I haven't found a way to achieve it. Can you tell me how to achieve it? It is an HTML file and cannot be converted into a react component.

**Comment by PiccoloYu** [comment]
![IEC%)TYB)JRKBD0JL5S8~LK](https://user-images.githubusercontent.com/44945137/65322913-9fb05e00-dbda-11e9-801d-755c29f497f5.png)
![H~ 12~Q}IC{OE@45XHUL{TV](https://user-images.githubusercontent.com/44945137/65322917-a17a2180-dbda-11e9-8818-2a93d62feb62.png)

**Comment by LekoArts** [comment]
Have you tried using the static folder?
https://www.gatsbyjs.org/docs/static-folder/

So placing the HTML file there and pointing the src there instead of using GraphQL.

**Comment by PiccoloYu** [comment]
> 您是否尝试过使用静态文件夹？
> https://www.gatsbyjs.org/docs/static-folder/
> 
> 因此，将HTML文件放在此处并将src指向那里，而不是使用GraphQL。

![4$CA}9}Y02I{`H%C10N}(`H](https://user-images.githubusercontent.com/44945137/65365922-7a5e3700-dc50-11e9-8ef7-337202264ad1.png)
Yes, there is no problem in introducing pictures. But Iframe will make a mistake.

`Create a React.js component in your site directory at src/pages/impress/impress.html.js and this page will automatically refresh to show the new page component you created.
If you were trying to reach another page, perhaps you can find it below.`
![IV00)6O%9$LF{ABPO1C RAJ](https://user-images.githubusercontent.com/44945137/65365976-ef317100-dc50-11e9-80d8-f14a73978e56.png)

**Comment by jonniebigodes** [comment]
@PiccoloYu if you want i can make a small reproduction and describe how you can do it. Sounds good?

**Comment by PiccoloYu** [comment]
@jonniebigodes 当然，这是再好不过的啦。非常感谢！

**Comment by PiccoloYu** [comment]
@jonniebigodes Of course, this is the best. Thank you very much.

**Comment by jonniebigodes** [comment]
No need to thank, i'm going make the reproduction and report back.

**Comment by jonniebigodes** [comment]
@PiccoloYu i have a solution for you, i'm going to describe the steps i took to triage below:
- Created a new gatsby site based on the hello world starter.
- Based on the guidelines and best practices in gatsby, i created a new file called `test.html` inside the static folder with some random content. 
- Modified `/src/pages/index.js` to the following:
```js
import React from "react"

export default () => (
  <div
    style={{
      display: "flex",
      alignContent: "center",
      margin: "3rem auto",
      justifyContent: "space-around",
      
    }}
  >
    <div>
      <iframe src="/test.html" title="dummy" style={{width:'800px',height:'600px'}}></iframe>
    </div>
    <div>this is content for the page</div>
  </div>
)

```
- Issued `gatsby develop` and opened up `http://localhost:8000` and i'm presented with the folllowing, also on the right side i tried to access the page directly and as you can see by the image the issue persists:
![picollo_1_dev](https://user-images.githubusercontent.com/22988955/65376873-40ffe880-dc9d-11e9-842b-2b3f78961949.png)
- Tried `gatsby build && gatsby serve` and i opened up `http://localhost:9000` on one window and `http://localhost:9000/test.html` and i can now see the content as you can see below:
![picollo_2_build](https://user-images.githubusercontent.com/22988955/65377015-d485e900-dc9e-11e9-8c88-eddb787dd033.png)


It seems that on build you can see the actual html without any issues. 

- Did a little search and it seems your issue is related to #13072 . Went through the issue and [pieh's comment](https://github.com/gatsbyjs/gatsby/issues/13072#issuecomment-523204930) offered a workaround and a explanation on what is happening. With that in mind i changed `gatsby-node.js` to contain the following:
```js
const express= require('express');

exports.onCreateDevServer=({app})=>{
    app.use(express.static('public'))
}
```
- Issued `gatsby develop` and opened up browser windows to both`http://localhost:8000` and `http://localhost:8000/test.html` and i'm presented with the following:
![picollo_3_dev](https://user-images.githubusercontent.com/22988955/65376953-401b8680-dc9e-11e9-968f-a8ebca9e9f1a.png)

If you want i can hoist up the code to a repo and you can go over it at your own pace.

Feel free to provide feedback so that we can close this issue or continue to work on it until we find a suitable solution.

**Comment by PiccoloYu** [comment]
@jonniebigodes (∩_∩)It would certainly be very helpful to provide an example.

**Comment by jonniebigodes** [comment]
@PiccoloYu here you go, i've set up a repo with the code used for this issue in [here](https://github.com/jonniebigodes/gatsby_iframe_example)

**Comment by PiccoloYu** [comment]
@jonniebigodes  Yes, it works！！

**Comment by jonniebigodes** [comment]
@PiccoloYu glad that i was able to help you and you managed to get it to work.

**Comment by LukyVj** [comment]
@jonniebigodes Just a comment to say thank you, your well detailed explanatory comment was super helpful, thanks a lot.

**Comment by jonniebigodes** [comment]
@LukyVj no need to thank, glad that i was able to help you aswell.

**Comment by stevemarksd** [comment]
> ```js
> 
> exports.onCreateDevServer=({app})=>{
>     app.use(express.static('public'))
> }
> ```

you just need to add this code in `gatsby-node.js`

```
const express = require('express')
exports.onCreateDevServer=({app})=>{
    app.use(express.static('public'))
}
```

**Comment by desorgui** [comment]
There is someone who know gatsby-remark-responsive-iframe ?
