### ISSUE TITLE
Language toggle UI

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#17776]
## Summary

Add a UI component (such as a dropdown or a `languages` page) so that users can toggle between languages

### Basic example

* A Spanish-speaking user opens a link to "quick-start" in English
* The user clicks the "Languages" icon in the toolbar
* The user clicks the "Español (es)" link
* The user is sent to the Spanish version of the Quick Start page

### Motivation

Users should be able to switch to their preferred language and remain on the same page.

## Steps

1. Language toggle
2. Language settings page
3. "Always view in this language" popup

## Examples from other websites

[Electron](https://electronjs.org/languages)

<img width="1280" alt="Electron.js language selector" src="https://user-images.githubusercontent.com/1278991/65367853-b4521d80-dbfd-11e9-81e4-38e190e4d91e.png">
<img width="1280" alt="Electron.js languages page" src="https://user-images.githubusercontent.com/1278991/65367854-b74d0e00-dbfd-11e9-9b1b-5d0d18a14b52.png">

[Yarn](https://yarnpkg.com/lang/en/)

<img width="302" alt="yarnpkg.com language dropdown" src="https://user-images.githubusercontent.com/1278991/65367866-dba8ea80-dbfd-11e9-97ed-048fe5008d61.png">

[MDN](https://developer.mozilla.org)

<img width="1280" alt="MDN language dropdown" src="https://user-images.githubusercontent.com/1278991/65367874-03984e00-dbfe-11e9-8293-d37f5378f73c.png">

**Comment by antonfrolovsky** [comment]
@tesseralis @fk ✋Hi, i would try make it.

**Comment by fk** [comment]
Hey there @tesseralis, and @antonfrolovsky! 👋 🤗 

Here's a first shot (finally! :pray:) that hopefully solves our rudimentary UI needs …
and _maybe_ some more; I explored a little further, inspired by the excellent resources you provided:

[Clickable prototype](https://www.figma.com/proto/UcsUDRdCoJaQdfITkcKMnU/.org-language-toggle-UI?node-id=1%3A614&viewport=849%2C4485%2C1&scaling=min-zoom):
- Click the _Languages_ item in the main navigation to see the dropdown.
- Select _Spanish_ in the dropdown to switch the current page's language.
- I went for the dropdown because it provides a direct result without the need to switch to an intermediate "Language" page, and then go back to the original page.
  - IMO a dropdown is a good way to start out and should serve us well for the time we do have less than ~10 translations available, and/or do not have all content translated for a language.
  - I like how https://electronjs.org/languages handles a the (larger) amount of translations they offer, and think once we reach that point, this is the way to go (at least for the most requested/visited translations).
- You'll note a notification modal on the spanish version of the page, inspired by what [MDN](https://developer.mozilla.org/) does to handle setting a language preference. I understand we do not need this for now, but wanted to include it to spark a discussion. IMO being able to set a default could be a "nice to have" feature, but things should just work fine without.
- Click _Settings and language details_ in the dropdown to go to a page that could provide
  - an overview of all available languages (and potentially their translation status)
  - a way to set the default language (see above)
  - information irt how to help with translations
  - links to the GitHub pages for each language/translation

[Figma designs](https://www.figma.com/file/UcsUDRdCoJaQdfITkcKMnU/.org-language-toggle-UI?node-id=1%3A614)

**Comment by muescha** [comment]
Amazon Web Services has also translated documentation. if there is no translation available then an info is displayed and then the english content

**Comment by tesseralis** [comment]
Split this up into three separate concrete issues based on @fk's design: #21750 #21746 #21751
