### ISSUE TITLE
wordpress error

### ISSUE THREAD

**Issue by jeffrson** [gatsbyjs/gatsby#17772]
## Description

gatsby/gatsby-source-wordpress gives this error:

> Path: /wp-json/wp/v2/themes?per_page=100&page=1
> The server response was "400 Bad Request"
> Inner exception message: "Fehlende(r) Parameter: status"

(missing parameter).

### Steps to reproduce

```
gatsby new wp-test
cd wp-test
yarn add gatsby-source-wordpress
```

Put this into gatsby-config.js:
```
module.exports = {
  siteMetadata: {
    title: `Gatsby Default Starter`,
  },
  plugins: [
    {
      resolve: 'gatsby-source-wordpress',
      options: {
        baseUrl: '<address>',
        hostingWPCOM: false,
        protocol: 'https',
        useACF: false,
        auth: {},
        verboseOutput: false,
      },
    },
    'gatsby-plugin-sharp',
    'gatsby-transformer-sharp',
  ],
}
```

Run `yarn run build`

### Actual result

See error above

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.
```
 System:
    OS: Windows 10
  Binaries:
    Node: 10.16.3
    Yarn: 1.17.3
    npm: 6.9.0
  Languages:
    Python: 3.7.3
  npmPackages:
    gatsby: ^2.15.19 => 2.15.19
    gatsby-image: ^2.2.20 => 2.2.20
    gatsby-plugin-manifest: ^2.2.18 => 2.2.18
    gatsby-plugin-offline: ^3.0.8 => 3.0.8
    gatsby-plugin-react-helmet: ^3.1.8 => 3.1.8
    gatsby-plugin-sharp: ^2.2.25 => 2.2.25
    gatsby-source-filesystem: ^2.1.25 => 2.1.25
    gatsby-source-wordpress: ^3.1.34 => 3.1.34
    gatsby-transformer-sharp: ^2.2.16 => 2.2.16

    Wordpress: 5.2.3
```

**Comment by jonniebigodes** [comment]
@jeffrson see if [this](https://www.gatsbyjs.org/packages/gatsby-source-wordpress/#fetching-data-wordpress-rest-api-route-selection) helps. Try adding the routes you need. As by default it will try and fetch everything and probably that endpoint cannot be properly processed,

**Comment by jeffrson** [comment]
Thank you, this will probably help.

Nevertheless, it seems strange to me, that https://github.com/GatsbyCentral/gatsby-starter-wordpress works when used with npm, which apparently is locked to some old version. It does not, however, work with yarn (which appears to use up-to-date packages).

**Comment by jonniebigodes** [comment]
@jeffrson let me see if i can clarify this for you.

If you execute the commands you mentioned in the description:

```shell
gatsby new wp-test
yarn add gatsby-source-wordpress
```
It will fetch the default starter from the github repo, clone it locally and install the dependencies that are present in the package.json, but instead of installing the latest versions of each package,  it will install the ones specified in the lock file.

Then it will install `gatsby-source-wordpress` but this time it will fetch the latest version of that package from the registry and update the corresponding entries either in `package.json` and the `yarn.lock` file.

I've checked [https://github.com/GatsbyCentral/gatsby-starter-wordpress](https://github.com/GatsbyCentral/gatsby-starter-wordpress) and it has both lock file types, so when you issue for instance `gatsby new wp-test-2 https://github.com/GatsbyCentral/gatsby-starter-wordpress` it should clone the repo locally and install the dependencies locked down to the version that is present. Not the most recent ones.
