### ISSUE TITLE
Gatsby is not picking up OG tags even when using react helmet

### ISSUE THREAD

**Issue by wahlforss** [gatsbyjs/gatsby#17846]
My site clearly has the OG tags when I'm inspecting it but facebook does not pick up on them.

https://www.bemlo.se/companies/agila

[facebook debugger](https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fwww.bemlo.se%2Fcompanies%2Fagila)

It is not picking up the og tags! It falls back to bemlo.se. I am using netlify, Contentful and gatsby.

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. Can you please follow our issue template as I unfortunately can't follow your train of thought and understand what the problem looks like.

To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction
