### ISSUE TITLE
TypeError: superClass is undefined

### ISSUE THREAD

**Issue by AidenFaulconer** [gatsbyjs/gatsby#17853]
## Description

I am simply just trying to import my components so I can use them. These components contain state and props, but I imagine this should not cause any problems with Gatsby's environment. This is the error message I get on my page

![image](https://user-images.githubusercontent.com/22147836/65560978-228f3b00-df84-11e9-8ab3-70ba04e4c817.png)

![image](https://user-images.githubusercontent.com/22147836/65560930-e6f47100-df83-11e9-9485-59a0ae060799.png)

the problem comes from here
![image](https://user-images.githubusercontent.com/22147836/65560957-07bcc680-df84-11e9-81d4-01febf5db113.png)

### Expected result

I should be able to import my components 

### Actual result

Error messages, and inability to have my page rendered

### Environment

  System:
    OS: Windows 10
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K 
CPU @ 3.70GHz
  Binaries:
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.329.0
  npmPackages:
    gatsby: ^2.13.73 => 2.13.73
    gatsby-plugin-google-analytics: ^2.1.12 => 2.1.12
    gatsby-plugin-manifest: ^2.2.13 => 2.2.13    gatsby-plugin-nprogress: ^2.1.4 => 2.1.4 
    gatsby-plugin-offline: ^3.0.1 => 3.0.1   
    gatsby-plugin-react-helmet: ^3.1.5 => 3.1.5
    gatsby-plugin-robots-txt: ^1.5.0 => 1.5.0    gatsby-plugin-sass: ^2.1.12 => 2.1.12    
    gatsby-plugin-sentry: ^1.0.1 => 1.0.1    
    gatsby-source-filesystem: ^2.1.18 => 2.1.18

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. I don't think this is an issue with Gatsby but a user error on your side with using React itself. If you can [provide a minimal reproduction][reproduction] you maybe might see the error. It would also be highly appreciated if you could link your repository instead of posting images of your code. Thanks a lot! :)

[reproduction]: https://gatsby.dev/reproduction
