### ISSUE TITLE
PostCss plugin is not executed when using Scss

### ISSUE THREAD

**Issue by muuvmuuv** [gatsbyjs/gatsby#17887]
## Description

I've tried to use the postcss plugin __[postcss-easing-gradients](https://github.com/larsenwork/postcss-easing-gradients)__ and it seems that it does not work properly. I have added a console log to its code in node_modules to see if it even gets executed but no. When I use it in normal CSS it works only when I use it in SCSS I don't get the expected result. I guess there is something wrong with the execution order or passing the parsed CSS to postcss?

Issue for referrence: https://github.com/larsenwork/postcss-easing-gradients/issues/11

### Steps to reproduce

https://codesandbox.io/s/gatsby-starter-default-y8slq?fontsize=14

### Expected result

---

### Actual result

The CSS does not get compiled correctly.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by nickmcmillan** [comment]
I had what was probably the same issue as @muuvmuuv. I was able to solve my issue with the following `gatsby.config.js` settings;

`
{
  resolve: `gatsby-plugin-sass`,
  options: {
    postCssPlugins: [require('postcss-easing-gradients')],
  },
},
`


So I actually didn't need `gatsby-plugin-postcss` at all, because as it turns out, `gatsby-plugin-sass` already comes with postcss; https://www.gatsbyjs.org/packages/gatsby-plugin-sass/#with-css-modules
