### ISSUE TITLE
using useStaticQuery hooks but can't find any documentation how test components with GraphQL 

### ISSUE THREAD

**Issue by HUFGhani** [gatsbyjs/gatsby#17902]
i've looked at website docs "https://www.gatsbyjs.org/docs/testing-components-with-graphql/" but there is only have reference to StaticQuery but not useStaticQuery can the docs be update

**Comment by simrankaurmann** [comment]
Would it be sufficient to edit the above page to include a useStaticQuery mock implementation example?

**Comment by gillkyle** [comment]
That would be great @simrankaurmann! A section similar to the section titled "Testing StaticQuery", maybe called "Testing useStaticQuery" would be welcome for this! Feel free to reference what's already been done for this guide and add a new section, [the guides on using useStaticQuery](https://www.gatsbyjs.org/docs/use-static-query/#how-to-use-usestaticquery-in-components) might be helpful in finding some code to use or showing you how that testing would happen! If you'd like to take it on we can label it Hacktoberfest - Claimed 🙂

**Comment by imthinhvu** [comment]
@gillkyle - since I didn't yet see this issue being officially claimed, I ended up making a PR for this here: https://github.com/gatsbyjs/gatsby/pull/18202

@simrankaurmann - Feel free to add onto my PR if you have any other ideas. Since you had originally requested this, I also don't mind closing my PR and finding something else to work on. I was mostly going through the open Hacktoberfest issues that weren't yet marked as claimed.

Either way, would be great to get both of your reviews on it.
