### ISSUE TITLE
[Discussion] Gatsby, React & Hydration

### ISSUE THREAD

**Issue by eyalroth** [gatsbyjs/gatsby#17914]
Seems that hydration-related issues are [extremely common](https://github.com/gatsbyjs/gatsby/search?q=hydrate&type=Issues) when developing in GatsbyJS, but the issue has not been fully and formally addressed, so I would like to do so here.

## The problem
Due to many Gatsby sites having some dynamic components  -- despite being mostly statically generated -- and due to the SSR model behind Gatsby, many Gatsby sites fails to properly update HTML attributes; most notably `class`, but also `href` and so forth. This happens when the client and server DOMs differ in their attributes, as the React hydration functionality does not [(re)consolidate](https://reactjs.org/docs/reconciliation.html) them as well as the render method:

> React expects that the rendered content is identical between the server and the client. It can patch up differences in text content, but you should treat mismatches as bugs and fix them. In development mode, React warns about mismatches during hydration. **There are no guarantees that attribute differences will be patched up in case of mismatches**. This is important for performance reasons because in most apps, mismatches are rare, and so validating all markup would be prohibitively expensive.
>
> https://reactjs.org/docs/react-dom.html#hydrate

To give a few instances of this problem from this repository, here is a short list: #3741 #5100 #8560 #9911 #10370 #12360 #14601 #17676 .

It is not surprising that the problem is so common. It is often hard to detect and resolve, and for two main reasons:
1. There is a difference between production and development modes in regards to how Gatsby uses hydration (addressed by #10706).
2. The problem has vague and indirect side-effects, and it not necessarily easy to debug and reach to the conclusion that it's the root of the situation.

### Reproduction

I also created a minimal Gatsby site repository to reproduce the problem: https://github.com/eyalroth/gatsby-hydrate-bug

The site has only 2 pages and a layout. The layout is automatically added to the 2 pages via `wrapPageElement` (same code as in `gatsby-plugin-layout`). The layout wraps the page content with a `div` that has a `class` attribute set to the current time, while also appending the time as text beneath the page content.

Upon building (and serving) the site, navigating to the index and inspecting it in the developer tools, one can see that the time displayed in the page is not the same as in the div class attribute:

![gatsby-hydrate-bug1](https://user-images.githubusercontent.com/6641808/65697524-c0b5fa80-e083-11e9-99f2-87be39731a12.png)

Navigating to the second page will correct this behavior, and you'll see that the time will be the same between the page content and the `class` attribute:

![gatsby-hydrate-bug2](https://user-images.githubusercontent.com/6641808/65697547-cad7f900-e083-11e9-8b96-1bd3f8611b7f.png)

This will remain so as long as you keep navigating between the pages in the same window. If you happen to refresh the page or open it in a window, the inconsistency will creep back; you'll actually notice that the time in the `class` attribute will remain the same every time you refresh (hinting that it is cached). "Hard refresh" (CTRL + F5) will load the page properly.

### Replacing hydration with rendering

One possible solution to (some instances of) the problem is to [entirely replace the hydration with rendering](https://www.gatsbyjs.org/docs/browser-apis/#replaceHydrateFunction):
```js
const ReactDOM = require('react-dom')

export function replaceHydrateFunction() {
    return (element, container, callback) => {
        ReactDOM.render(element, container, callback)
    }
}
```
However, there are two major drawbacks to this workaround:
1. It may very well reduce performance, as the whole idea behind the hydration functionality is to improve performance.
2. Directly rendering from the client, instead of hydrating, is deprecated in React 16, and is [said to be completely removed in React 17](https://github.com/facebook/react/blob/3694a3b5e9a5a3c80d47f9889a17d8337573d513/packages/react-dom/src/client/ReactDOM.js#L551).

### Two pass rendering

The other workaround is to re-render a component which is expected to change between the client and the server when it first mounts, and attach a different `key` attribute to the component the second time around:
```jsx
class Layout extends React.Component {
  constructor(props) {
    super(props)
    this.state = { isClient: false }
  }
  render() {
    // can be `div` or anything else, I tried to keep this generic
    return <React.Fragment key={this.state.isClient}> 
      {/*...*/}
    </React.Fragment/>
  }
  componentDidMount() {
    this.setState({ isClient: true })
  }
}
```

This workaround is also documented in [React's website](https://reactjs.org/docs/react-dom.html#hydrate):

>If you intentionally need to render something different on the server and the client, you can do a two-pass rendering. Components that render something different on the client can read a state variable like `this.state.isClient`, which you can set to true in `componentDidMount()`. This way the initial render pass will render the same content as the server, avoiding mismatches, but an additional pass will happen synchronously right after hydration. Note that this approach will make your components slower because they have to render twice, so use it with caution.

The drawback of this approach is that the user may very well visually notice the re-rendering, which wouldn't be the best user experience.

## What's next?

I believe this problem should be better highlighted and documented in the Gatsby site. As I said earlier, it is hard to detect and be aware of, especially when (new) developers -are not always aware of the entire design behind the framework, and may very well not be able to tell what's the differences between server-side or client-side rendering, and when the components are expected to differ between the two.

This is most notable with `gatsby-plugin-offline`, where (I believe) the problem is happening since the default shell page is first generated with all the components in `wrapPageElement` (but without any page content), so only these components are actually affected by the problem; for instance, a layout component "injected" by `gatsby-plugin-layout`.

#17676 is reporting that the problem occurs even when the offline plugin is disabled, so I'm not sure whether a builtin workaround in that plugin -- for instance, generating the default shell app without `wrapPageElement` -- will be enough to solve the problem for all the various use-cases.

Thoughts?

**Comment by sidharthachatterjee** [comment]
Thank you for the detailed issue, @eyalroth 

I think we should do two things here 

- Document this better, maybe in https://www.gatsbyjs.org/docs/debugging-html-builds/

> for instance, generating the default shell app without wrapPageElement -- will be enough to solve the problem for all the various use-cases
- We could try this, cc @davidbailey00 (who maintains the offline plugin)

**Comment by eyalroth** [comment]
@sidharthachatterjee 

> Document this better, maybe in https://www.gatsbyjs.org/docs/debugging-html-builds/

I feel like this should be mentioned in multiple locations, not just in the debugging section, which I believe people tend to get to very late in their development and/or debugging process (and some might not even notice the problems at first).

Of the locations I thought would be appropriate to mention this:
1. Anywhere where hydration is addressed:
1.a https://www.gatsbyjs.org/docs/glossary/#hydration
1.a https://www.gatsbyjs.org/docs/client-data-fetching/
1.a https://www.gatsbyjs.org/docs/production-app/#dom-hydration
2. Layout-related pages:
2.a https://www.gatsbyjs.org/docs/layout-components/#how-to-prevent-layout-components-from-unmounting
2.b https://www.gatsbyjs.org/packages/gatsby-plugin-layout/
3. The "wrap" APIs:
3.a https://www.gatsbyjs.org/docs/browser-apis/#wrapPageElement
3.b https://www.gatsbyjs.org/docs/browser-apis/#wrapRootElement
3.c https://www.gatsbyjs.org/docs/ssr-apis/#wrapPageElement
3.d https://www.gatsbyjs.org/docs/ssr-apis/#wrapRootElement
4. The offline plugin, which seem to be involved in many of the problem's instances: https://www.gatsbyjs.org/packages/gatsby-plugin-offline/

Perhaps this problem deserves a dedicated page / blog post?

> Would you like to do this considering you've done all this great work in investigating this? 🤗

I actually mentioned the problem in part of my guide on how to implement a layout in a Gatsby site. It's in my blog, which is not published yet, and will likely go through several more edits. The post is currently online [here](https://dev--wizardly-khorana-5b5fee.netlify.com/en/blog/2019/08/gatsby-layout/), where's the source for it is [here](https://github.com/eyalroth/blog-gatsby/blob/dev/src/posts/en/2019/Gatsby%20Series/Layout/index.md). I'm not sure it follows [the official style guide](https://www.gatsbyjs.org/contributing/gatsby-style-guide/) though 😆

**Comment by SMerdzhanov** [comment]
I'm quite confused by the last few replies around this so broadly mentioned issue.

Thank you for suggesting these workarounds @eyalroth! I'm actually already testing the hydration-one. However, as you mentioned yourself, this might have a performance impact and in general, is still a "workaround". However, I really appreciate your efforts and will get back to you when I have more feedback from my experiments.

@sidharthachatterjee wouldn't it be better if we come up with a reasonable and grounded explanation of why this issue is happening in the first place? Instead of thinking about how to document a workaround which is still unverified? Did anyone confirm that these proposed solutions fixed the initial issue? What about `gatsby-plugin-offline` and the assumption it might play a role too? 

Does this mean we're accepting a potential performance hit? Is this **the** solution we're accepting? Just trying to understand what's next here?

**Comment by pitkes22** [comment]
I have been struggling with this bug for a very long time. Happy to see that it is finally getting some attention. 👍

I have recently run in it when I was using `gatsby-plugin-layout` with multiple layouts and I was conditional rendering them one at the time but in a production version of the site, there was part of one wrapped in component from the other one which doesn't make any sense. 

Also, I have noticed that this behavior varies when I load the page for the first time. Probably because of the `gatsby-plugin-offline` mentioned above. 

One more issue that may be related to this bug: #15993

**Comment by eyalroth** [comment]
> I have recently run in it when I was using `gatsby-plugin-layout` with multiple layouts and I was conditional rendering them one at the time but in a production version of the site, there was part of one wrapped in component from the other one which doesn't make any sense.

Multiple layouts are actually quite a complicated feature, and may not work hand in hand with the layout plugin. I've written about it [here](https://dev--wizardly-khorana-5b5fee.netlify.com/en/blog/2019/08/gatsby-layout/#multiple-layouts) (note that this is still unpublished and may be subjected to edits).

**Comment by gillkyle** [comment]
This is great research and an awesome writeup! Thanks a bunch @eyalroth 🙂 

I think based off your suggestions to update several pages, a Reference Guide would probably make the most sense that we could link off to with notes from other guides about how it relates and how you can find more at the guide on the other page. I think this could go in the Custom Configuration section though I'm interested in @marcysutton's thoughts too.

What the nature of that guide looks like though I'm not totally sure, maybe a write up similar to what you've done in this issue.

**Comment by DavidDeprost** [comment]
It seems to me that at least a subset of these mysterious issues where `gatsby build` styles differ from `gatsby develop` are caused by preprocessor imports.

I've had a similar issue that was caused by variables imported from an .scss stylesheet:
```js
import vars from './layout.scss'
```
The imported variables are **undefined** on `gatsby build` (but work fine on `gatsby develop`).
This results in obscure bugs that only manifest themselves on first page load in production.

Can anyone confirm if this is a gatsby issue or a configuration issue?

**Comment by DavidDeprost** [comment]
@eyalroth @sidharthachatterjee @SMerdzhanov @LekoArts 

For your convenience, I filed #19563 to track this preprocessor issue.
Since this probably also happens to each theme or plugin that uses preprocessor imports, it might actually be causing more problems than apparent at first glance.

It includes a minimal reproduction that clearly demonstrates this problem:
https://github.com/DavidDeprost/gatsby-build--sass-bug

**Comment by eyalroth** [comment]
@DavidDeprost Thank you for filing that issue. I think it's more related to #10706, and not so much to this ticket. The problem addressed here seems to be rooted in a behavior which affects both the production and development builds.

**Comment by DavidDeprost** [comment]
You're totally right, it is more related to that issue. I only came to this issue because it was mentioned in some of the other issues that they were closed in favor of this one. I guess I had the mistaken impression this was also the place to gather other possible causes.

Thanks for the issue number, the preprocessor issue will be of more use in there.

**Comment by SMerdzhanov** [comment]
Thank you for keeping this thread up 👍 

Both issues linked #19563 and #10706 seems related, but not quite actionable/active. I'm curious how there aren't more people experiencing the same issue.

In any case, for the moment I've managed to apply a workaround that seems to be a fix for now. However it's a _workaround_ and has some negative performance impact. I'm talking about replacing the `hydrate()` function as suggested above ^^

So far I haven't found any better solution.

**Comment by RuudBurger** [comment]
Just wanted to pitch in with a reproducable example. 

```js
import React, { useCallback, useEffect, useState } from 'react';

export default () => <div>
    <DoesntWorkComponent />
    <WorksComponent />
</div>

const hasWindow = typeof window !== 'undefined';

const DoesntWorkComponent = () => {
    const [dimensions, setDimensions] = useState({
        innerWidth: hasWindow ? window.innerWidth : 0,
        innerHeight: hasWindow ? window.innerHeight : 0,
    });

    const handleResize = useCallback(() => {
        setDimensions({
            innerWidth: hasWindow ? window.innerWidth : 0,
            innerHeight: hasWindow ? window.innerHeight : 0,
        });
    }, []);

    useEffect(() => {
        handleResize();
        hasWindow && window.addEventListener('resize', handleResize);
        return () => {
            hasWindow && window.removeEventListener('resize', handleResize);
        };
    }, []);

    return <div width={dimensions.innerWidth}
                height={dimensions.innerHeight}
                style={{
                    width: dimensions.innerWidth,
                    backgroundColor: 'gray',
                }}>{dimensions.innerWidth} x {dimensions.innerHeight}</div>;
};

const WorksComponent = () => {
    const [dimensions, setDimensions] = useState({
        innerWidth: 0, // THIS IS THE ONLY DIFFERENCE
        innerHeight: 0, // THIS IS THE ONLY DIFFERENCE
    });

    const handleResize = useCallback(() => {
        setDimensions({
            innerWidth: hasWindow ? window.innerWidth : 0,
            innerHeight: hasWindow ? window.innerHeight : 0,
        });
    }, []);

    useEffect(() => {
        handleResize();
        hasWindow && window.addEventListener('resize', handleResize);
        return () => {
            hasWindow && window.removeEventListener('resize', handleResize);
        };
    }, []);

    return <div width={dimensions.innerWidth}
                height={dimensions.innerHeight}
                style={{
                    width: dimensions.innerWidth,
                    backgroundColor: 'gray',
                }}>{dimensions.innerWidth} x {dimensions.innerHeight}</div>;
};
```

Note the "THIS IS THE ONLY DIFFERENCE" comment on the 2 lines. 
This will render the `width x height` inside the components correctly. But if you look at the following gif, you will see that the dom (and the styles) don't update correctly. 
If I resize the window (height only) it will update the one prop, but not the other. If I resize the window (width only) it will snap to the state I expected in the first place.
Adding `hasWindow` to the deps array in useEffect or useCallback doesn't change anything.

![Untitled](https://user-images.githubusercontent.com/38136/69819091-732e4900-11fe-11ea-80fe-90eb0f0d06ae.gif)
(sorry for the slow gif, converting it from mov to gif changed the framerate..)

**Comment by chandlervdw** [comment]
I've run into this issue and was about to pull my hair out. The only solution (janky) I've found was [here](https://github.com/gatsbyjs/gatsby/issues/14601#issuecomment-499922794).  This is obviously less than ideal but I'm not sure how to help debug this further.

**Comment by wahlforss** [comment]
This is a constant issue in my experience. It constantly pops up and is a total pain. This happened while using Formik

**Comment by fullofcaffeine** [comment]
Started using Gatsby recently. In some ways, it improves the static-site generation workflow a lot, and in other ways I really wished I was using something like jekyll or middleman instead. It all started when I needed to simply push the typography.js styles down the stack so that it could override the bootstrap typeface settings, but something so simple in concept is far from trivial with Gatsby, unfortunately. 

I then found an example here: https://www.gatsbyjs.org/docs/ssr-apis/#replaceRenderer on how you'd re-order the `Typography.js` styles (in the example it was putting it on the top, but it was trivial to modify to push it to the bottom) __however__ this only works when the site is actually built! To really fully implement the change I wanted, I needed to modify two files with different APIs. Just to make sure a CSS is loaded after another. Wow.

**Comment by gaearon** [comment]
With React we expect that anyone using SSR would run it in development too. Hydration warnings are very important to address. I don’t think this can just be mitigated by the documentation. It seems like a fundamental issue.

Has it been considered to do a client side emulation of SSR render in development? If you don’t want to do a real one. For example, renderToString the root and put it into innerHTML in development. And then hydrate. This won’t catch all issues but should catch a reasonable subset.

What am I missing?

**Comment by gaearon** [comment]
To clarify. Here's what I mean

```js
// in dev
node.innerHTML = renderToString(<App />)
hydrate(<App />, node)
```

This wouldn't reproduce all hydration issues (e.g. the ones caused by `typeof window` checks) but should be a reasonable start?

**Comment by pieh** [comment]
What kind/class of hydration issues could be caught by using `renderToString` + `hydrate` with instances of same component as input?

**Comment by mrlubos** [comment]
Ooh, so this is what was tripping me up. My use case was to display a welcome message on page load. However, I don't want this message to appear in meta tags if you were to share the page on social media, so I won't render it during the build.

```js
const [showWelcomeMessage] = useState(!__SSR__);
```

Changing this to `false` will cause the content to briefly flash before rendering the welcome message, whereas setting this to `true` won't satisfy the meta tags requirement. Would be great to have this resolved!

**Comment by CanRau** [comment]
This article by @joshwcomeau might be interesting as he explains pretty good what's happening.
https://joshwcomeau.com/react/the-perils-of-rehydration
I had an idea yet his post made it more clear, I think.
Explaining in depth with examples why your issue happens @mrlubos

**Comment by mrlubos** [comment]
That’s what brought me here @CanRau 😬

**Comment by verekia** [comment]
I haven't tried this yet but it seems like a possible workaround could be temporarily replacing `react-dom` by `react-dom/cjs/react-dom.development.js` so that we get the hydration warnings even in production mode. Seen in https://github.com/facebook/react/issues/17499.

You would only do that when you notice weird bugs or just once in a while for sanity check, and put back `react-dom` when you're done fixing the bugs.

**Comment by CanRau** [comment]
@verekia `webpack.resolve.alias` should do it I guess. [gatsby-plugin-alias-imports](https://www.gatsbyjs.org/packages/gatsby-plugin-alias-imports/) might help

**Comment by pieh** [comment]
@verakia @CanRau that alone might not work as-is because of the `if (process.env.NODE_ENV !== "production")` check in https://unpkg.com/browse/react-dom@16.13.0/cjs/react-dom.development.js (gatsby build will set NODE_ENV to production).

You might get around this by using webpack's define plugin and setting NODE_ENV to development for `build-javascript` stage.

**Comment by cesarvarela** [comment]
I come across this issue from time to time, I don't remember experiencing it as frequently as when working with NextJS, so I wonder if maybe it handles this differently?

**Comment by nolandg** [comment]
This is an expected issue to tackle whenever you make [client-only routes](https://www.gatsbyjs.org/docs/client-only-routes-and-user-authentication/) correct? When I make any client-only route and navigate directly to it, the static HTML file does not contain any of the sub/nested routes. On page load, Reach Router is powered up and renders the client-only routes HTML which is obviously different from static SSR stuff.

The only viable option I see for now is to 2-pass render all client-only routes. Or am I missing something more obvious?

**Comment by abohannon** [comment]
FWIW we've experienced this off and on. The first time we fixed it by upgrading to Material UI v4 and using the `gatsby-plugin-top-layout` pattern used in their MUI starter found in their repo. This ensures the `gatsby-ssr` and `gatsby-browser` root element renders are the same.

However, we started seeing this issue again a couple weeks ago on a handful of pages and tracked it down to a component that was being conditionally rendered based on `window.location`. When we updated that condition to rely on the `location` prop offered by Reach Router instead of the `window` object, the rehydration bugs went away (in our case it was CSS classes being all out of wack and affecting the page style significantly). This makes sense since on the server rendered version that conditionally wrapped component wouldn't show vs. on the client render it would, so the DOM differences would confuse the rehydration process (if I understand correctly).

**Comment by wahlforss** [comment]
Why can't we show hydration errors with a flag in Gatsby Build or development?

**Comment by blainekasten** [comment]
We've got an umbrella ticket now to track all of these develop SSR issues. I'll be closing this one in favor of that ticket. #25729

**Comment by eyalroth** [comment]
@blainekasten This is not a develop-only problem, it's affection production as well.

**Comment by SMerdzhanov** [comment]
Hey @blainekasten, I'm a bit confused maybe.

Issue #25729 is about running true SSR in `development` mode. 

If I understand correctly, that's an attempt to be able to see and eventually prevent the issue from happening by pointing it out while developing.

But this isn't actually going to solve it, right? 

So then @25729 would be helpful but it seems not like a solution but patch? Don't we want to keep this thread open and actually resolve the issue?

**Comment by verekia** [comment]
If I'm not mistaken, the fact that SSR & client mismatches mess up the DOM is not a Gatsby problem it's a React problem, and it's expected to happen. It doesn't matter if we are in development or production mode, these issues in your code must be fixed before shipping to production. If we have SSR in development, we will be able to fix those issues and there shouldn't be mismatches in production. In my opinion I don't think there is anything to "fix" in Gatsby, except being able to see those React warnings when developing. It's the same as missing `key` attributes, you are supposed to catch those when developing, and it's expected to break your prod if you don't. But maybe there is an other scenario I'm not seeing.

**Comment by eyalroth** [comment]
@verekia There are no fixes, only partial workarounds.

This might be a problem stemming from React, but dismissing it as a non-Gatsby problem for this reason is akin to dismissing a food poisoning in your restaurant due to bad handling by the food supplier. At the end of the day, no one will come eat at your restaurant.

This issue might have been dismissed if it didn't affect anyone, or affected only a niche use-case, but this is one of the highest voted issues in this repository. This is no surprising, because it is a big problem with one of _the_ most fundamental features / characteristics that Gatsby is aiming to provide --  fast (static) yet flexible (dynamic) web pages.

**Comment by polarathene** [comment]
While it won't affect many users, those who use art direction feature of `gatsby-image` have experienced issues from hydration since the SSR can only bake in the state and CSS for a particular breakpoint. 

React hydrates to the SSR state assuming it's the same instead of re-rendering if not, but due to the nature of that problem, you'd also have breakage prior to JS being available, so that needed to be addressed to. [I created a PR that resolves all that](https://github.com/gatsbyjs/gatsby/pull/24811), the hydration issue is a pretty simple fix toggling a bool state as the official React docs advise.

---

I'd prefer the benefits of `gatsby develop` and wouldn't want to lose those for serving SSR in develop mode personally, you're just trading one set of issues for another. Instead it's best just to provide solid documentation on the "phenomena", so that confused users can understand the issue and what the common avenues for resolving it are, just providing SSR during develop doesn't magically solve the problem, only make it visible sooner while potentially hiding other information worth knowing.

Developers can get an SSR update via `gatsby build` followed by `gatsby serve` and visiting `localhost:9000`. Might seem like a hassle, but it's probably better than some fast iteration developer mode that rebuilds/refreshes SSR output with file changes, since that'd be leveraging cache which can hide/cause other problems. Better practice to do a fresh build & serve before deploying to production/staging.

**Comment by verekia** [comment]
Well if they do implement SSR in development mode, it's pretty easy to put it behind a flag.
`gatsby develop` for fast builds without SSR
`gatsby develop --ssr` for slower builds with SSR

**Comment by eyalroth** [comment]
@verekia I agree that the development mode should resemble production as much as possible, but the development mode has other workflow features in mind, such as reloading changes on the fly. If those are incompatible (I can't say as I'm not proficient enough in this), then the choice is between two separate workflows.

This is outside of the scope of this issue, and in fact, this is addressed by [this issue](https://github.com/gatsbyjs/gatsby/issues/10706), which is also linked in the description of this one.

Regardless, even if development mode was identical to production, I believe this issue would've plagued many projects. It is hard to detect for other reasons as well, and in general it is not documented enough -- in fact, some official guides of certain plugins contain instructions that will raise this problem.

IMO gatsby should aim to provide plugins and other solutions that make it easy to avoid this problem, and that it should only be encountered in niche use cases, which doesn't seem to be current state of affairs.

**Comment by bogdibota** [comment]
If you are just looking to copy-paste the two-pass rendering solution, here's the HOC version:
```jsx
export const withTwoPassRendering = (WrappedComponent) => ({
  children,
  ...rest
}) => {
  const [isClient, setIsClient] = useState(false);

  useEffect(() => {
    setIsClient(true);
  }, [setIsClient]);

  return (
    <WrappedComponent {...rest} key={isClient}>
      {children}
    </WrappedComponent>
  );
};
```
And the usage example:

Before:
```jsx
<MyComponent prop={value}>
   ...children
</MyComponent>
```

After:
```jsx
const MyComponentWithTwoPass = withTwoPassRendering(MyComponent);

// ...

<MyComponentWithTwoPass prop={value}>
   ...children
</MyComponentWithTwoPass>
```
