### ISSUE TITLE
Mock window object when server rendering

### ISSUE THREAD

**Issue by whmountains** [gatsbyjs/gatsby#1793]
A lot of client-side libraries incorrectly expect `window` to always be defined and cause the gatsby build to fail.  The obvious solution would be to fix the libraries themselves, but I'm wondering if this could be patched on Gatsby's end as well.

Would it be possible to include jsdom at the beginning of `render-page.js` so that there would be mock window object and more libraries would work out of the box?

**Comment by KyleAMathews** [comment]
My main concerns are this would slow down page rendering plus introduce inconsistent rendering.

If you want to do some experiments and report back on your findings that's be really helpful.

Also if we could detect somehow when failures are due to this and report that to users that'd speed debugging time.

**Comment by whmountains** [comment]
Okay, I will do some tests and report back if I have time.  Could you point me to the Gatsby source file that generates `render-page.js`?

**Comment by KyleAMathews** [comment]
`src/utils/build-html.js` & `src/utils/develop-html.js`

**Comment by KyleAMathews** [comment]
We're not going to do this — libraries increasingly handle this correctly as server rendering is quite common now.
