### ISSUE TITLE
[gatsby-transformer-remark] how to sort pages by date desc but keep date null valued pages at the end?

### ISSUE THREAD

**Issue by muuvmuuv** [gatsbyjs/gatsby#17953]
## Summary

I have some pages where each page has a __started__ and __ended__ frontmatter key. Those are not required, therefore a page can have both, one or none set. The problem I have ATM, is that when I use `sort`, `fields` and `order` (with __ended__ as first field), all pages that have null as value are before the once that has a value. I can use `ASC` to bring them before the null value pages but then the ordering is not longer correct (2017 before 2019).

## Relevant information

Example pages
```md
---
started: null
ended: 2017-03-20
---
Some text
```

```md
---
started: null
ended: null
---
Some text
```

```md
---
started: null
ended: 2018-03-20
---
Some text
```

```md
---
started: 2018-04-13
ended: 2017-11-20
---
Some text
```

GraphQL
```graphql
{
  allMarkdownRemark(
    sort: {
      fields: [frontmatter___ended, frontmatter___started]
      order: DESC
    }
  ) {
    edges {
      node {
        frontmatter {
          ended
          started
        }
      }
    }
  }
}
```

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by jonniebigodes** [comment]
@muuvmuuv can you make a reproduction following [these steps](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/) so that it can be better triaged?

**Comment by muuvmuuv** [comment]
@jonniebigodes I made a Sandbox. Sorry, I thought it would just be something I need to add to the query that is not known for a GraphQL newbie.

https://codesandbox.io/s/gatsby-starter-default-m0nlb?fontsize=14

**Comment by jonniebigodes** [comment]
@muuvmuuv i've been tinkering with the reproduction and it seems that yours is a bit of a edge case and it seems that the behaviour you're seeing is the default one. The null dates value will default to the top. In this case, to the best of my knowledge and someone more knowledgeable might offer some better insight, but i think that you'll have to do some changes and probably sort the data a bit different.

Here are the steps i took for this workaround:

- Grabbed your codesandbox code
- Added a couple of more items to get some more content to test out in the form of some md files, called `p05.md` and `p06.md` and `p07.md`.
  - `p05.md` has the following content:
      
     ```md
        ---
        started: 2017-03-20
        ended: null
        ---

        One more without end date
     ```

- `p06.md` has the following content:
    ```md
       ---
      started: null
      ended: 2018-03-20
      ---

     NO start date
    ```
- `p07.md` has the following content:
   ```md
      ---
     started: null
     ended: null
     ---
     Both dates gone
   ```

- Ran your query once again and the result of the query was consistent with the issue you're experiencing.
- I then changed the query to first fetch the contents that has both dates present, then the contents that has no start date and finally no end date. 
Tranforming the query into:
```graphql
{
      withDates: allMarkdownRemark(
        filter: { frontmatter: { started: { ne: null }, ended: { ne: null } } }
        sort: {
          fields: [frontmatter___ended, frontmatter___started]
          order: DESC
        }
      ) {
        edges {
          node {
            id
            fields {
              slug
            }
            frontmatter {
              started
              ended
            }
            excerpt
          }
        }
      }
      withoutStartDate: allMarkdownRemark(
        filter: { frontmatter: { started: { eq: null } } }
        sort: { fields: frontmatter___ended, order: DESC }
      ) {
        edges {
          node {
            id
            fields {
              slug
            }
            frontmatter {
              started
              ended
            }
            excerpt
          }
        }
      }
      withoutEndDate: allMarkdownRemark(
        filter: { frontmatter: { ended: { eq: null } } }
        sort: { fields: frontmatter___started, order: DESC }
      ) {
        edges {
          node {
            id
            fields {
              slug
            }
            frontmatter {
              started
              ended
            }
            excerpt
          }
        }
      }
    }
```
- The output given by the graphiql explorer is the following:

![muuvmuuv_1](https://user-images.githubusercontent.com/22988955/65819850-5e8efe00-e219-11e9-98cb-aafafda22788.png)

- Modifiied your `src/pages/index.js` to the following:
```js
const IndexPage = () => {
 
  const results = useStaticQuery(graphql`
    {
      withDates: allMarkdownRemark(
        filter: { frontmatter: { started: { ne: null }, ended: { ne: null } } }
        sort: {
          fields: [frontmatter___ended, frontmatter___started]
          order: DESC
        }
      ) {
        edges {
          node {
            id
            fields {
              slug
            }
            frontmatter {
              started
              ended
            }
            excerpt
          }
        }
      }
      withoutStartDate: allMarkdownRemark(
        filter: { frontmatter: { started: { eq: null } } }
        sort: { fields: frontmatter___ended, order: DESC }
      ) {
        edges {
          node {
            id
            fields {
              slug
            }
            frontmatter {
              started
              ended
            }
            excerpt
          }
        }
      }
      withoutEndDate: allMarkdownRemark(
        filter: { frontmatter: { ended: { eq: null } } }
        sort: { fields: frontmatter___started, order: DESC }
      ) {
        edges {
          node {
            id
            fields {
              slug
            }
            frontmatter {
              started
              ended
            }
            excerpt
          }
        }
      }
    }
  `)

// merges all of the date into a unique set/array orders it by end date
  const idList = new Set(results.withoutStartDate.edges.map(x => x.node.id))
  const datesmerged = [
    ...results.withDates.edges,
    ...results.withoutStartDate.edges,
    ...results.withoutEndDate.edges.filter(d => !idList.has(d.node.id)),
  ].sort((starting,ending)=>{
    return new Date(ending.node.frontmatter.ended) - new Date(starting.node.frontmatter.ended);
  })

  return (
    <div>
      <h3>merge raw output</h3>
      <pre>
        <code>{JSON.stringify(datesmerged, null, 2)}</code>
      </pre>
    </div>
  )
}

export default IndexPage
```
What is happening here is the following, i'm taking in the query mentioned above, and based on the results given, i'm creating a array with unique data, removing any duplicate data that the query might give back.  Sort it by end date, showing the most recent items first. Then displaying it under a raw format.

- Opened up `http://localhost:8000` and i'm presented with the following:

![muuvmuuv_2](https://user-images.githubusercontent.com/22988955/65820319-4326f180-e21f-11e9-80a0-486c6bfeb442.png)

Sorry for not being more helpful and offer a more simpler way to achieve the same result.

Feel free to provide feedback so that we can close this issue, or continue to work on it until we find a suitable solution.

**Comment by muuvmuuv** [comment]
Hm, yes, that would have been my idea of a workaround too. I assumed there would be a simpler way of doing this. Is this something that could be modified/added in/to `gatsby-transformer-remark` plugin? 

Thank you anyway, I will use this for now. :)

**Comment by jonniebigodes** [comment]
Probably yes, probably some safeguard could be added to the plugin, but i'm not familiar with the code of the plugin and i can't say for sure. Also thinking about it could something related to the data layer ho it handles it. If you don't mind i'm closing this marking it as answered, but feel free to reopen and comment if you want to continue the discussion. Once again sorry for not being more helpfull.

**Comment by muuvmuuv** [comment]
Found an easier way to sort them; 

1. all items with no end date, sorted by start date (the newest first)
2. all items with start and end date, sorted by end date (the newest first)
3. all items without start or end date, sorted by nothing

```javascript
  const items = allMarkdownRemark.edges.sort((nodeA, nodeB) => {
    const AF = nodeA.node.frontmatter
    const BF = nodeB.node.frontmatter

    const future = dayjs().add(10, 'y')
    const present = dayjs().add(-10, 'y')
    const AEnded = AF.ended ? dayjs(AF.ended) : future
    const BEnded = BF.ended ? dayjs(BF.ended) : future
    const diffEnded = BEnded.diff(AEnded)
    const AStarted = AF.started ? dayjs(AF.started) : present
    const BStarted = BF.started ? dayjs(BF.started) : present
    const diffStarted = AStarted.diff(BStarted)

    if (!BF.started && !BF.ended) {
      return -1
    } else if (!AF.started && !AF.ended) {
      return 1
    }

    return diffEnded - diffStarted
  })
```
