### ISSUE TITLE
Partial rehydration

### ISSUE THREAD

**Issue by endymion1818** [gatsbyjs/gatsby#17993]
## Summary

Instead of replacing all of the HTML tree with the React app tree, would it be possible to have the option to only rehydrate the parts which use React functionality (ie. forms).

### Motivation

The reason for this request is that many users in various countries do not have access to the fastest internet or the latest smart phones, and React sites often chew through bandwidth and battery.

We could better meet the needs of those who live in or are visiting areas where this situation is common by using the partial rehydration method.

I would really like to see GatsbyJS as a more viable solution to people in this situation.

## Blockers

I think this would require React to first be entirely asynchronous.

**References:**
https://www.smashingmagazine.com/2017/03/world-wide-web-not-wealthy-western-web-part-1/

**Comment by KyleAMathews** [comment]
Yes! This will be a huge improvement once it lands in Gatsby. We can automatically create much smaller bundles for pages by lazy loading much of the code.

**Comment by probablyup** [comment]
Can this be reopened and left open? Definitely something I hope the team will take on.

**Comment by endymion1818** [comment]
Me too, but unfortunately the idea is dependent on React being asynchronous, and the React team seem to be going in a different direction for now with server components. No doubt server components will improve performance quite a bit, and I'm sure Gatsby are already looking into how that improves the situation.

**Comment by shadowtime2000** [comment]
I am a little new to Gatsby, but when I used to work with some Next projects there was this certain NPM package that provided some React components which allowed me to declaratively disable rehydration. I forgot the name of that NPM package, but would that work here?

**Comment by endymion1818** [comment]
I'm not sure, it would be cool to see what that package could do! 

However, react is currently synchronous, which means it renders out the DOM tree from parent to children, top to bottom. For Gatsby to do partial hydration we would need React to be asynchronous, so as to hydrate only the components that had interactivity. It's a difficult problem.

I'd like to see that package if you remember what it was called 👍

**Comment by shadowtime2000** [comment]
@endymion1818 The package was [react-lazy-hydrate](https://www.npmjs.com/package/react-lazy-hydrate) which allows you to just disable hydration for static parts of the page. I have no idea if it would work for Gatsby, but I know it worked in Next. 

As you said, React is synchronous and it hydrates everything top to bottom. This just basically has the hydration skip hydrating over parts of pages you don't want to hydrate. I don't think it actually causes changes in bundle size.

**Comment by jhukdev** [comment]
There are other strategies to provide partial hydration that don't involve React being asynchronous. A common pattern is localized hydration via a Higher order Component. We currently use this in production and it works great.

The HOC simply wraps the provided component with a call to `hydrate` or `render` if it's running in the context of a browser. Otherwise it returns the virtual dom nodes wrapped in a target element that the call to `hydrate` (or `render`) uses to query the DOM.

That way, you only need to include the wrapped components in your client bundle, saving a lot of bytes.

I don't know how this might work in the context of Gatsby, but doing this on a production Preact app was fairly trivial.

I wrote about it here with an example for anyone that's interested:
https://www.jameshill.dev/articles/partial-hydration/#how-do-we-fix-this

**Comment by kaushalyap** [comment]
@KyleAMathews Can we please keep this open and add "not stale" tag.
