### ISSUE TITLE
I have a page the url is '/USER' and I want '/user' also can open this page how can I write

### ISSUE THREAD

**Issue by silenceM** [gatsbyjs/gatsby#18041]
### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by jonniebigodes** [comment]
@silenceM based on the title of the issue is not clear what you intend to achieve, if you can provide a bit more context to this? On what you want to achieve? And if possible make a reproduction following [these steps](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/) so that it can be looked at in more detail.

But two things come into mind while reading this,
1- If you have a page called `USER` inside the pages folder, something like so:
![silenceM_1](https://user-images.githubusercontent.com/22988955/66083594-8907f080-e564-11e9-8464-a88c67c8e0f4.png)

you can achieve what you want by simply renaming it into `user`, if you restart the development server it should pick up on the change and show the correct endpoint, meaning `/user`, you might need to update some links that point to that page in the meantime.

2- If the page is actually created in `gatsby-node.js`, something like how it's detailed in [here](https://www.gatsbyjs.org/docs/client-only-routes-and-user-authentication/), then you can do something like the following in `gatsby-node.js` 
```js
exports.onCreatePage = async ({ page, actions }) => {
  const { createPage } = actions
  // page.matchPath is a special key that's used for matching pages
  // only on the client.
  if (page.path.match(/^\/USER/)) {
    page.matchPath = "/user/"
    // Update the page.
    createPage(page)
  }
}
```
With this small snippet of code it will modify the path of the page to `/user`.

But once again this is based on the information at hand that you supplied, if you follow what i've mentioned above, the issue you're experiencing might be better triaged.

**Comment by silenceM** [comment]
@jonniebigodes  thank you  This is the answer I want.

**Comment by jonniebigodes** [comment]
No need to thank, i'm glad that I managed to offer a solution for your issue.
