### ISSUE TITLE
npm run build adding an extra wrapper div with no class.

### ISSUE THREAD

**Issue by alqamabinsadiq** [gatsbyjs/gatsby#18117]
## Description

I am working on an application. I was facing an issue with `npm run develop` and `npm run build` commands. `npm run develop` adding a wrapper div with `tabIndex` and `role:group` which makes it easier to give it `height: 100%`, but when I am running `npm run build` it's adding a wrapper div with no class.

## npm run develop
When I run `npm run build` I see this:

<img width="703" alt="Screenshot 2019-10-04 at 6 59 08 PM" src="https://user-images.githubusercontent.com/16412803/66213379-1409f780-e6d9-11e9-8d60-05cce726956f.png">

## npm run build
When I run `npm run build` I see this:

![Screenshot 2019-10-04 at 6 59 56 PM](https://user-images.githubusercontent.com/16412803/66213488-516e8500-e6d9-11e9-938e-972723706796.png)

### Modules
```
    "axios": "^0.19.0",
    "gatsby": "^2.15.21",
    "gatsby-plugin-react-helmet": "^3.0.0",
    "gatsby-plugin-sass": "^2.1.15",
    "gatsby-source-filesystem": "^2.1.26",
    "prop-types": "^15.6.1",
    "react": "^16.9.0",
    "react-dom": "^16.9.0",
    "react-helmet": "^5.2.0"
```

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction
