### ISSUE TITLE
Error: ENFILE File Table Overflow

### ISSUE THREAD

**Issue by nicholaswyoung** [gatsbyjs/gatsby#1822]
As I've slowly added content, generating my site is beginning to strain Gatsby. Most builds now take at least 2-4 minutes, and I can generally go get coffee while `develop` loads the schema. Now I've uncovered a new error: 

```
Error: Unhandled Rejection
Error: ENFILE: file table overflow, open {filepath}`.
```

I'm truly not sure where to begin digging into this, but it's on my radar since I'm the only person to have encountered this error so far. Reducing the number of markdown files by several hundred tends to usually do the trick, but I have a lot of content (including even bigger projects) that could benefit from Gatsby.

**Comment by KyleAMathews** [comment]
There's something goofy about the schema generation as the time to generate it seems highly variable.

The EMFILE error is a OS problem. There's perhaps things we could do in Gatsby to limit the number of open files but not much AFAIK. If you Google around, there's easy ways to open the OS limits. I ran into this at some point and raised the limits and haven't had trouble since.

If you'd like to create a doc page on scaling Gatsby for large sites with stuff like this that's be great!

**Comment by nicholaswyoung** [comment]
I'd like to bake in a fix rather than asking folks to tweak their OS settings, if at all possible. Even if I find a workaround, documenting is less than ideal in the long run.

**Comment by nicholaswyoung** [comment]
This issue hasn't come up recently. It was marked as stale, and so it is!

**Comment by mayankchd** [comment]
@nicholaswyoung how was you able to fix it?

**Comment by guilhermebpereira** [comment]
> Probably [this](https://stackoverflow.com/questions/45004352/error-enfile-file-table-overflow-scandir-while-run-reaction-on-mac?answertab=active#tab-top) could help.
> 
> However in my case it was enough to `rm -rf .cache`.
> 
> _[not-related-question]_
> @KyleAMathews is there a way to force that `.cache` invalidation when running `gatsby develop`? something like a `--flag`

couldn't you just add something like this on your package.json? `"scripts": { 
      "develop": "gatsby clean && gatsby develop"
}`
