### ISSUE TITLE
Irrelevant starters included in search results thanks to being hosted on Firebase

### ISSUE THREAD

**Issue by dandv** [gatsbyjs/gatsby#18223]
I was searching for starters that implement Firebase features, and found a few [that have nothing to do with Firebase](https://github.com/lewislbr/lewis-gatsby-starter-blog/issues/2#issuecomment-538631324), but still show up in searches because they're hosted on `firebaseapp.com`.

![image](https://user-images.githubusercontent.com/33569/66250720-bfcc3b00-e70b-11e9-817d-1f000c06cf1b.png)

**Comment by LekoArts** [comment]
Thank you for opening this!

I've looked at https://www.gatsbyjs.org/starters/?c=Firebase&v=2 and all the starters that are presented use Firebase in some way. We can't remove starters because they are hosted there -- you should use the category to filter for it :)

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby!

**Comment by davwheat** [comment]
My thoughts:

Setting up Firebase Hosting isn't particularly difficult, and any starter that uses it doesn't help people that much, especially as the Firebase CLI wizard walks you through each step and sorts it all out for you.

The Hosting only sites cloud up the tag heavily, preventing people finding useful sites which demonstrate the other 90% of Firebase's more complex services and how to get them to interact with Gatsby, which I initially found very difficult and took me several weeks to crawl through all sorts of SO questions, issues here, and 3rd party documentation.

In my opinion, the Firebase tag could be split into two: "Firebase Hosting", and "Firebase Services". Yes, Hosting is a Service (so the tag names could be improved) but I still believe it's critical not to let the Hosting only sites hide all of the really useful sites for people new to Gatsby, React, Node. After all, we want to be welcoming and encourage people to try something new, right?
