### ISSUE TITLE
redux.state file corruption causes ERROR #85907 GRAPHQL

### ISSUE THREAD

**Issue by TomSwiedler** [gatsbyjs/gatsby#18339]
## Description

The project will build the first time. After that it will fail with: ERROR #85907 GRAPHQL

### Steps to reproduce

The initial build of the project proceeds without error.
Subsequent builds fail with: ERROR #85907 GRAPHQL
Removing the redux.state file from .cache between builds allows subsequent builds to succeed

The application uses a number of JSON files for content.
I believe I have attached the minimum number of files to reproduce.

[query_error_minimum_files.zip](https://github.com/gatsbyjs/gatsby/files/3704118/query_error_minimum_files.zip)

### Expected result

Repeated builds should not fail

### Actual result

Any build that commences with the redux.state file in the .cache directory will  fail

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
  Binaries:
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.387.0
  npmPackages:
    gatsby: ^2.15.29 => 2.15.33
    gatsby-image: ^2.2.12 => 2.2.12
    gatsby-plugin-canonical-urls: ^2.1.2 => 2.1.2
    gatsby-plugin-manifest: ^2.2.4 => 2.2.4
    gatsby-plugin-react-helmet: ^3.1.3 => 3.1.3
    gatsby-plugin-sharp: ^2.2.9 => 2.2.9
    gatsby-plugin-styled-components: ^3.1.2 => 3.1.2
    gatsby-plugin-typescript: ^2.1.2 => 2.1.2
    gatsby-remark-autolink-headers: ^2.1.3 => 2.1.3
    gatsby-remark-copy-linked-files: ^2.1.4 => 2.1.4
    gatsby-remark-images: ^3.1.7 => 3.1.7
    gatsby-remark-prismjs: ^3.3.4 => 3.3.4
    gatsby-remark-responsive-iframe: ^2.2.4 => 2.2.4
    gatsby-remark-smartypants: ^2.1.2 => 2.1.2
    gatsby-source-filesystem: ^2.1.8 => 2.1.8
    gatsby-transformer-json: ^2.2.3 => 2.2.3
    gatsby-transformer-remark: ^2.6.10 => 2.6.10
    gatsby-transformer-sharp: ^2.2.5 => 2.2.5

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by TomSwiedler** [comment]
I believe the file I attached is a minimal project required to reproduce the error.
