### ISSUE TITLE
Error'window is not defined'while running the'gatsby develop' command

### ISSUE THREAD

**Issue by PiccoloYu** [gatsbyjs/gatsby#18366]
I have an external NPM component that uses window, which causes me to make a mistake in building.
I found out why in the answers to other questions:
This fails when server rendering as you're not in a browser so window doesn't exist. My current solution is to comment out the component when running the'gatsby develop'command. When the project is ready, uncomment the component. This ensures that the component runs in the browser.
       So is there a one-time solution?
                                                                                                                                                   
                
                Thank

**Comment by kdichev** [comment]
You can wrap your component with a `window` check
```
window && <MyComponent />
```

**Comment by PiccoloYu** [comment]
> You can wrap your component with a `window` check
> 
> ```
> {window && <MyComponent />}
> ```

It's no use, but thank you.

**Comment by jonniebigodes** [comment]
@PiccoloYu take a look at [this](https://www.gatsbyjs.org/docs/debugging-html-builds/), more specifically to [this section](https://www.gatsbyjs.org/docs/debugging-html-builds/#fixing-third-party-modules). The documentation offers a couple of workarounds to help you get past the problem. But based on the information at hand it seems that the problem might be solved by [react-loadable](https://github.com/jamiebuilds/react-loadable), here's a [example](https://github.com/jonniebigodes/gatsby-react-owl-carousel) on how to use it with gatsby, it was originally intended for another issue, but i'm confident that with some tweaks you will get it to work. 

Feel free to provide feedback so that we can close this issue or continue to work on it until we find a suitable solution.

**Comment by PiccoloYu** [comment]
Thank you very much. I solved the problem using [react-loadable] (https://github.com/jamiebuilds/react-loadable)
@jonniebigodes
