### ISSUE TITLE
Missing images in build

### ISSUE THREAD

**Issue by ndotmdot** [gatsbyjs/gatsby#18530]
## Description

Not all images are being fetched from wordpress during gatsby build. Gatsby develop works fine and fetches all.

### Steps to reproduce
Live site
- [Example missing image in the third row on the left](https://5d9f386a8b1301eededd28d6--eham-live.netlify.com/projekte/)

Backend
- Wordpress 5.2.3 hosted on bluehost.com
- Content is structured with Advanced Custom Fields, flexible content and polylang
- About 40 pages
- About 200 images total with each max. 3000x3000px and 1.5MB

### Expected result

App with all images

### Actual result

- The build produced by gatsby cli or netlify results in an app with several missing images.
- The console does not throw any error
- These are no broken links
- It seams that graphQl skipped fetching these images
- *This error happens only with gatsby build and not with gatsby develop*

### Further detail

- It seams that this problem happens more often once the total amount of images on the site grows
- Aside from this, it is hard to find a specific pattern.
- Sometimes it helps to delete the image in WordPress and re-uploading it. But then, some other image is missing
- Find netlify's the deploy log [here](https://gist.github.com/ndotmdot/db74558a76226dec83dd250985d7960e)

### Environment

  System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i7-6660U CPU @ 2.40GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 11.6.0 - ~/.nvm/versions/node/v11.6.0/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.5.0-next.0 - ~/.nvm/versions/node/v11.6.0/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 77.0.3865.90
    Firefox: 67.0.4
    Safari: 11.1.2
  npmPackages:
    gatsby: ^2.13.29 => 2.13.29 
    gatsby-image: ^2.2.6 => 2.2.6 
    gatsby-link: ^2.2.2 => 2.2.2 
    gatsby-plugin-catch-links: ^2.1.2 => 2.1.2 
    gatsby-plugin-eslint: ^2.0.5 => 2.0.5 
    gatsby-plugin-feed: ^2.3.4 => 2.3.4 
    gatsby-plugin-google-analytics: ^2.1.4 => 2.1.4 
    gatsby-plugin-mailchimp: ^5.1.2 => 5.1.2 
    gatsby-plugin-manifest: ^2.2.3 => 2.2.3 
    gatsby-plugin-netlify: ^2.1.3 => 2.1.3 
    gatsby-plugin-nprogress: ^2.1.2 => 2.1.2 
    gatsby-plugin-offline: ^2.2.4 => 2.2.4 
    gatsby-plugin-page-transitions: ^1.0.8 => 1.0.8 
    gatsby-plugin-react-helmet: ^3.1.2 => 3.1.2 
    gatsby-plugin-root-import: ^2.0.5 => 2.0.5 
    gatsby-plugin-sass: ^2.1.3 => 2.1.3 
    gatsby-plugin-sharp: ^2.2.8 => 2.2.8 
    gatsby-plugin-sitemap: ^2.2.3 => 2.2.3 
    gatsby-plugin-svgr: ^2.0.2 => 2.0.2 
    gatsby-plugin-transition-link: ^1.13.0 => 1.13.0 
    gatsby-plugin-twitter: ^2.1.2 => 2.1.2 
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4 
    gatsby-source-filesystem: ^2.1.5 => 2.1.5 
    gatsby-source-wordpress: ^3.1.41 => 3.1.41 
    gatsby-transformer-sharp: ^2.2.4 => 2.2.4 
  npmGlobalPackages:
    gatsby-cli: 2.4.17

Any insights on this problem or ideas on how to debug gatsby-source-wordpress and the build process are much appreciated!

Thanks a lot!

**Comment by ndotmdot** [comment]
I think this might be related https://github.com/gatsbyjs/gatsby/issues/6654

**Comment by TylerBarnes** [comment]
Hi @ndotmdot ,
Sorry to hear you're running into an issue. My initial instinct is that this is related to a core WordPress REST api bug which prevents images from being accessed via REST if the post they were originally uploaded to becomes private. [Check here](https://www.gatsbyjs.org/packages/gatsby-source-wordpress/#graphql-error---unknown-field-localfile-on-type-image-field) for more info. 
It's likely this is why re-uploading the images sometimes fixes the problem.

To debug and figure out if this is the issue, give this a shot (from the link above):
`
In order to resolve this, you can manually change the post_parent value of the image record to 0 in the database. The only side effect of this change is that the image will no longer appear in the “Uploaded to this post” filter in the Add Media dialog in the WordPress administration area.
`

Alternatively you could try uploading that image directly to the media library and then add that re-uploaded image to your ACF field to see if it shows up.

If this is your issue, it's been a known bug in WordPress core for [over 2 years](https://core.trac.wordpress.org/ticket/41445). It looks like they're planning to ship a fix for it in the next release though!

**Comment by TylerBarnes** [comment]
Thank you for opening this, @ndotmdot 

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜

**Comment by peach-inzn** [comment]
I am having a similar issue. For my posts I have the `createPages` function in `gatsby-node` and it works fine. However, my pages are built manually and query for the content using `props.data.wpPage.content` and then `dangerouslySetInnerHTML` (I have also tried parse from `html-react-parser`). My problem is, that content images do not get downloaded to the `public` folder if the page is viewed after a re-route. 

Meaning: I go to example.com/about. All images are there, text content also there. In the menu I go to /publications via `<Link>`. Now, all the text gets changed and the image too (based on source code), but the image frame stays empty. 
<img width="605" alt="Screenshot 2022-03-11 at 11 20 38 PM" src="https://user-images.githubusercontent.com/100540199/157980406-d92b5383-87ef-4f4a-884d-281f0f0d6cd9.png">
<img width="299" alt="Screenshot 2022-03-11 at 11 21 04 PM" src="https://user-images.githubusercontent.com/100540199/157980450-d584cc73-ff4b-4efe-a918-fe9edfe0d850.png">

What's strange: The moment I change route again, to /home or any other sub-page that is in the menu via `<Link>` the image suddenly shows up, but then of course the new page gets displayed with the exact same issue.
