### ISSUE TITLE
[gatsby-plugin-mdx] MDX in frontmatter

### ISSUE THREAD

**Issue by mrozilla** [gatsbyjs/gatsby#18570]
## Summary

Following the conversation in https://github.com/ChristopherBiscardi/gatsby-mdx/issues/352

Since we're already parsing the body of an .mdx file, we could do the same thing to certain fields in the frontmatter which can then be rendered through the MDXRenderer just like the body.

### Basic example

I'd imagine a flag (off by default) for the plugin options that triggers the mechanism, e.g.

```js
// gatsby-config.js
module.exports = {
  plugins: [
    {
      resolve: `gatsby-plugin-mdx`,
      options: {
        parseFrontmatter: [`mdx`, `markdown`], // keys which to parse in the frontmatter
      },
    },
  ],
}
```

which would turn the following .mdx file

```markdown
---
title: This doesn't get processed
nested:
  mdx: This gets processed [link](https://example.com)
---

This gets processed [link](https://example.com)
```

into the following query output

```
{
  frontmatter: {
    title: "This doesn't get processed"
    nested: {
      mdx: {
        body: <processed MDX>
      }
    }
  }
  body <processed MDX>
}
```

We'd need to deeply traverse the whole frontmatter object. I'd see this happening as an in-place transformation of the frontmatter object as opposed to creating extra gatsby nodes as discussed in https://github.com/ChristopherBiscardi/gatsby-mdx/issues/352#issuecomment-490746054

### Motivation

I'm using this package to process [output from Netlify CMS](https://github.com/mrozilla/gatsby-starter-netlify_cms/blob/master/src/content/cms/pages/home.mdx). There are situations (e.g. with [variable list types](https://www.netlifycms.org/docs/beta-features/#list-widget-variable-types)) when mdx/markdown ends up saved in the frontmatter of an .mdx file. I'm currently using a [half-assed userland solution](https://github.com/mrozilla/gatsby-starter-netlify_cms/blob/master/gatsby/onCreateNode.js#L22-L54) dissected out of the plugin's functionality

I'd love to take a stab at a PR but wanted to check with the maintainers (for opinions and possibly guidance) and the community (for interest) first :) Cheers for a lovely package!

**Comment by dustinhorton** [comment]
Just ran into this need as well.

> There are situations (e.g. with [variable list types](https://www.netlifycms.org/docs/beta-features/#list-widget-variable-types)) when mdx/markdown ends up saved in the frontmatter of an .mdx file.

Markdown widgets are my use case so far.

Currently all my markdown is passed to a custom Markdown component. Think I'll work around this limitation for now by checking the type of `children`—if it's a `string`, return via [ReactMarkdown](https://github.com/rexxars/react-markdown), otherwise, via MDXRenderer.

**Comment by LekoArts** [comment]
@dustinhorton You could have a look at these solutions in the meantime: https://github.com/gatsbyjs/gatsby/issues/5021

**Comment by janosh** [comment]
I just asked a [related question in the MDX spectrum chat](https://spectrum.chat/mdx/general/gatsby-parse-mdx-in-yaml-frontmatter~e4510d04-852a-49df-a0b0-b08ed8274c79).

**Comment by renvrant** [comment]
@janosh For parsing frontmatter MDX in Gatsby I did use @mdx/runtime successfully, which should be safe because it isn't actually runtime. See: https://github.com/renvrant/gatsby-mdx-netlify-cms-starter

I'm thinking there are performance implications though. It would be great if gatsby-mdx exposed some mechanism to parse MDX from a string, since this is a pretty common use case with configurable CMSes like Netlify CMS.

**Comment by janosh** [comment]
I tried [this suggestion](https://github.com/ChristopherBiscardi/gatsby-mdx/issues/352#issuecomment-490746054) by @ChristopherBiscardi and added the following to `gatsby-node.js`
```js
const crypto = require(`crypto`)

exports.onCreateNode = async ({ node, actions, createNodeId }) => {
  const { createNode, createParentChildLink } = actions

  if (node.internal.type === `Mdx`) {
    const { frontmatter } = node
    if (frontmatter.mdxTitle) {
      const child = await createNode({
        id: createNodeId(`${node.id} >>> MdxTitle`),
        parent: node.id,
        children: [],
        internal: {
          type: `MdxTitle`,
          contentDigest: crypto
            .createHash(`md5`)
            .update(node.frontmatter.mdxTitle)
            .digest(`hex`),
          content: node.frontmatter.mdxTitle,
          mediaType: `text/markdown`,
          description: `A custom node so that MDX will process the mdxTitle field`,
        },
      })
      await createParentChildLink({ parent: node, child })
    }
  }
}
```
but that throws
```
TypeError: Cannot read property 'internal' of undefined  
  - schema.js:1019 
    [repo]/[gatsby]/dist/schema/schema.js:1019:99
```

**Comment by zslabs** [comment]
Is this the official "MDX in frontmatter" topic? There's a few floating around and figured it might be a good to keep one open until an official solution is figured out/a plugin (or support) is added. I did come across [gatsby-transformer-remark-fronmatter](https://github.com/WhiteAbeLincoln/gatsby-transformer-remark-frontmatter#readme) so that could be a starting point, but appears it may have issue with repeating fields/lists.

**Comment by zslabs** [comment]
👋 I [wrote an article](https://zslabs.com/articles/mdx-frontmatter-in-gatsby/) on how I was able to accomplish this. Huge props to [this comment](https://github.com/gatsbyjs/gatsby/issues/21789#issuecomment-592110650). I hope this helps someone else out!

**Comment by zslabs** [comment]
This is now available as [a plugin](https://github.com/zslabs/gatsby-plugin-mdx-frontmatter) to help get everyone up and running even quicker!
