### ISSUE TITLE
Support local plugins in theme

### ISSUE THREAD

**Issue by universse** [gatsbyjs/gatsby#18713]
I have a set of local plugins that I want to include for every site that I develop. As some of those are super simple plugins, moving each of them to its own package seems to be an overkill and adds unnecessary complexity (i.e managing and publishing etc...)

From #16128 I understand there's potentially some technical roadblock.

Is there a way around this?

**Comment by LekoArts** [comment]
Generally speaking we want our users to build small, re-usable themes but since this has come up multiple times now there is work done on that.

It'll be fixed by https://github.com/gatsbyjs/gatsby/pull/15856

**Comment by universse** [comment]
Not sure if it's the same thing. I'm requesting for theme that can resolve its own local plugins. This way, I can publish this theme and share among projects.

On the other hand, the PR is to enable local theme that is exclusive to individual project.

**Comment by pieh** [comment]
Enabling this is relatively straight forward. I was thinking about enabling local plugins/themes in themes themselves (in the PR that @lekoarts linked) but it can introduce problems that we don't have sane way of handling right now - because local plugins are not managed by some global repository like npm there is possibility of conflicts, because main identifier we use is plugin name and 2 different themes can use 2 completely different plugins with the same name which will lead to unspecified behaviour.

I.e.
 - `theme-a` has local plugin `theme-helpers`,
 - `theme-b` has local plugin `theme-helpers`
those local plugins are specific to their themes, so what should happen if we try to shadow `theme-helpers`? I know you mention your want local plugins and not themes, but a theme is a plugin and there is no difference for gatsby core if it implement theme specific APIs or not (config files merging / shadowing)

**Comment by universse** [comment]
Ah okay. The distinction between theme and plugin was a little bit hazy for me but I got it now. Thanks so much for the clarification. Looking forward to it.
