### ISSUE TITLE
Gatsby querying and rebuilding unchanged pages on Netlify after Contentful fetch

### ISSUE THREAD

**Issue by neefrehman** [gatsbyjs/gatsby#18731]
## Description

We're working on ustwo.com at the moment and are trying to tackle our ever-growing build times. We're finding that Gatsby is querying and rebuilding every page on when deployed to Netlify. I'm unsure if this is an issue with how Gatsby manages the `.cache`, how Netlify deals with it, or if it is an issue with `gatsby-source-contentful`, but the end result is much longer build times than needed. This is an issue for us as our build hooks from Contentful and Greenhouse trigger multiple times per day, which outputs a hefty amount of build minutes!

I've tried using both `gatsby-plugin-netlify-cache` as described in #16590 and `gatsby-plugin-remove-fingerprints` as mentioned in #11961, and neither are reducing build times as we were hoping.

*Update:* From running `gatsby build` Successive times locally this also seems to be a problem: Gatsby runs every query and builds every page. 

### Steps to reproduce

Deploy any project that sources data from Contentful to Netlify.

### Expected result

Gatsby should fetch Contentful data, find which entries and assets are new, and then only build affected pages, the rest remaining the same in the `/public` directory.

### Actual result

Gatsby is fetching contentful data, finding that all entries and assets are new, and then running every query again. Below is part of the CLI output with zero changed pages on any of our sources or in the codebase.

```
Updated entries  548
Deleted entries  0
Updated assets  1724
Deleted assets  0
[...]
success run page queries — 28.003 — 494/494 17.67 queries/second
success Building static HTML for pages — 13.417 — 494/494 99.11 pages/second
```

### Environment

```
  System:
    OS: macOS 10.14.4
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Shell: 5.3 - /bin/zsh

  Binaries:
    Node: 12.4.0 - /usr/local/bin/node
    npm: 6.11.3 - /usr/local/bin/npm

  Languages:
    Python: 2.7.10 - /usr/bin/python

  Browsers:
    Chrome: 77.0.3865.120
    Firefox: 68.0.1
    Safari: 12.1

  npmPackages:
    gatsby: ^2.13.39 => 2.13.39 
    gatsby-cli: ^2.7.19 => 2.7.19 
    gatsby-image: ^2.2.6 => 2.2.6 
    gatsby-node-helpers: ^0.3.0 => 0.3.0 
    gatsby-plugin-algolia: ^0.3.0 => 0.3.2 
    gatsby-plugin-canonical-urls: ^2.0.10 => 2.1.2 
    gatsby-plugin-catch-links: ^2.0.8 => 2.1.2 
    gatsby-plugin-eslint: ^2.0.5 => 2.0.5 
    gatsby-plugin-google-analytics: ^2.0.16 => 2.1.4 
    gatsby-plugin-google-tagmanager: ^2.1.10 => 2.1.10 
    gatsby-plugin-html-attributes: ^1.0.5 => 1.0.5 
    gatsby-plugin-layout: ^1.0.9 => 1.1.2 
    gatsby-plugin-manifest: ^2.0.5 => 2.2.4 
    gatsby-plugin-netlify: ^2.0.11 => 2.1.3 
    gatsby-plugin-netlify-cache: ^1.2.0 => 1.2.0 
    gatsby-plugin-nprogress: ^2.0.8 => 2.1.2 
    gatsby-plugin-offline: ^2.0.11 => 2.2.4 
    gatsby-plugin-page-transitions: ^1.0.7 => 1.0.8 
    gatsby-plugin-postcss: ^2.0.5 => 2.1.2 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.1.2 
    gatsby-plugin-remove-fingerprints: 0.0.2 => 0.0.2 
    gatsby-plugin-robots-txt: ^1.4.0 => 1.5.0 
    gatsby-plugin-sharp: ^2.0.31 => 2.2.9 
    gatsby-plugin-sitemap: ^2.0.6 => 2.2.3 
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4 
    gatsby-remark-images-contentful: ^2.0.8 => 2.1.4 
    gatsby-remark-prismjs: ^3.3.5 => 3.3.5 
    gatsby-source-contentful: ^2.1.17 => 2.1.17 
    gatsby-source-filesystem: ^2.1.8 => 2.1.8 
    gatsby-source-greenhouse: file:./local-npm/gatsby-source-greenhouse => 2.0.2 
    gatsby-source-medium: ^2.1.2 => 2.1.2 
    gatsby-transformer-remark: ^2.1.12 => 2.6.9 
    gatsby-transformer-sharp: ^2.1.4 => 2.2.4 

  npmGlobalPackages:
    gatsby-cli: 2.7.14
```

**Comment by iDatLe** [comment]
Hello! I've had a huge problem with this issue for the past month. The problem was obscure and took me a while to find it.

Netlify has its own caching system, caching files upon every build and does a checksum to see if any file has changed since the previous build. If it has then it will reupload that file. Gatsby has this thing called the webpackCompilationHash.

Problem: Gatsby will build your pages and give it a webpackCompilationHash. This hash is given to every single HTML file and changes with every build. Netlify will detect that one line with the new hash and reupload that file. Well, if you have 10k pages then Netlify will reupload all those pages on every. single. build.

https://github.com/gatsbyjs/gatsby/pull/16686

The issue is raised and provides an update to fix it. It worked for me.
Apply the update, then incrementally upload to Netlify. Should work.

**Comment by neefrehman** [comment]
@iDatLe Thanks for the info!

We were hoping that using [`gatsby-plugin-remove-fingerprints`](https://www.npmjs.com/package/gatsby-plugin-remove-fingerprints) would achieve the same outcome for us. We've verified that the hashes are being removed from the filenames when we use the plugin, but the issue persists so I'm guessing there's more nuance to the hashes when it comes to Netlify's diffing than just filenames.

I'll take a look the PR you linked and see if this solves the problem.

**Comment by iDatLe** [comment]
@neefrehman 

Yup, no problem! Unfortunately, that plugin only removes the hash from javascript file names. Gatsby bakes another hash (webpackCompilationHash) into HTML files (every one of em it seems). There was no solution to this until that PR arose. 

They've now removed the hash from all HTML files and put it into a singular app-data.json file.

**Comment by neefrehman** [comment]
@iDatLe Thanks for the extra details, that makes sense!

One more question, when deploying your site with the linked branch are you still `gatsby-plugin-remove-fingerprints` and/or `gatsby-plugin-netlify-cache`, or does moving the hash into `app-data.json` remove the need for these as well?

**Comment by iDatLe** [comment]
Short answer: I think yes

Long answer: It is my understanding (and if I'm incorrect then anyone feel free to correct me) that when Gatsby builds your project, it gives a hash to the names of JS files. HTML files still inline reference those JS files. So because those JS file names have changed, Netlify will reupload those JS files. And because HTML files reference those changed JS files, Netlify will reupload those HTML files too and we're back to the problem.

This is based on my vague understanding of the Gatsby build process so if anyone can correct me or add more then please feel free.

I think this is a Gatsby-Netlify compatibility issue when increasing the amount of pages you have. Netlify has its own fingerprinting technique so we can remove Gatsby's fingerprinting technique. If Netlify wasn't used as a hosting service, it's probably best to not remove any hashes Gatsby provides.

**Comment by neefrehman** [comment]
Closing issue as PR #16686 that solves the problem has been merged!
