### ISSUE TITLE
How can get current building path without `window.location` in component when running build?

### ISSUE THREAD

**Issue by jerry-i** [gatsbyjs/gatsby#1875]
How can get current building path without `window.location` in my component when running gatsby build?

I just Want to add an active className in current actived Link like navigation.

**Comment by fk** [comment]
Hi @jerry-i! Not 100% sure if this is what you are looking for, but please take a look at https://www.gatsbyjs.org/packages/gatsby-link/, specifically the third paragraph where `activeStyle` and `activeClassName` are mentioned.

**Comment by fk** [comment]
PS: In the case that `gatsby-link` doesn't solve your needs, peep what `this.props.location.pathname` returns in your layout, template or page.

**Comment by jerry-i** [comment]
@fk THX

**Comment by skjorrface** [comment]
I tried (window.location/location).pathname and it only works in development mode (it will throw an error in production because of ssr), this.props.location.pathname (this.props.location either) is "undefined" inside the <Link></Link> component imported from gatsby-link or inside any component in general. How do I get current location working in production mode as well?

**Comment by schwiet** [comment]
@jlengstorf I just read your article [Life After Layouts](https://www.gatsbyjs.org/blog/2018-06-08-life-after-layouts/), what will be the right way to get at the current path when layouts are gone?  Will it just be up to individual `pages` to pass relevant Location-like information as a prop to the layout component?

**Comment by Kadrian** [comment]
Would it make sense to support something like `withRouter` then, to avoid passing location all the way down?

**Comment by jlengstorf** [comment]
@Kadrian It turns out that's already supported!

Starting in Gatsby V2, you can use the [`Location` component from `@reach/router`](https://reach.tech/router/api/Location) to grab the location data from anywhere in your app.

```jsx
import React from 'react';
import { Location } from '@reach/router';

export default () => (
  <Location>
    {({ navigate, location }) => /* ... */}
  </Location>
);
```

**Comment by imshuffling** [comment]
Hey @jlengstorf, is there any examples of location being used on the starter site?

I'm simply trying to pass the current location of the user when they submit a form.

Thanks

**Comment by jlengstorf** [comment]
@imshuffling I just made a CodeSandbox with two usage examples. See `index.js` and `page-2.js` for two ways of getting the location: https://codesandbox.io/s/v82ol26w9l

**Comment by ChiaraSammarco** [comment]
I have a question on this topic (maybe for you it's an easy one). 
I'm using react-router-dom and redux-saga. I need to get some params in the URL. I've done by using withRouter in the component that triggers the action the saga is listen at and then in this way

```
import qs from 'query-string';
...
const someParams = qs.parse(this.props.location.search, { ignoreQueryPrefix: true });
this.props.myAction(someParams);
```

Now I've realized that by using window.location inside the saga would be faster. So my question is: is there a reason to use props.location instead of  window.location.

Thanks in advance for your help! 
Regards

**Comment by imshuffling** [comment]
> @imshuffling I just made a CodeSandbox with two usage examples. See `index.js` and `page-2.js` for two ways of getting the location: https://codesandbox.io/s/v82ol26w9l

Thanks really helpful.

**Comment by jlengstorf** [comment]
@ChiaraSammarco the downside of `window.location` is that it doesn’t exist during server-side rendering, which will [cause the Gatsby build to fail without adding extra checks](https://www.gatsbyjs.org/docs/debugging-html-builds/#how-to-check-if-window-is-defined).

**Comment by damassi** [comment]
Note that you can also pull it out via 

```js
import { globalHistory } from "@reach/router"
```

If you don't want rerenders due to  `<Location>` changes.

**Comment by skylarweaver** [comment]
> Note that you can also pull it out via
> 
> ```js
> import { globalHistory } from "@reach/router"
> ```
> 
> If you don't want rerenders due to `<Location>` changes.

Thanks @damassi!

And to add some specificity:
`import { globalHistory } from "@reach/router"`
`const path = globalHistory.location.pathname`

**Comment by Dara-To** [comment]
Weird, I used `globalHistory` as per suggested here and it worked not long ago but today I got undefined. Any idea?

```
import { globalHistory } from "@reach/router"
const BASE_URL = globalHistory.location.origin
```

**Comment by jonniebigodes** [comment]
@Dara-To just ran it and it's working, at least locally.
I have the following gatsby dependencies installed, also some others but they are not relevant to this issue and i'm leaving them out:

```json
"dependencies": {
    "gatsby": "^2.15.12",
    "react": "^16.9.0",
    "react-dom": "^16.9.0"
  },
```
Created a new page called `page3.js` with the following code:
```jsx
import React from 'react'
import { globalHistory } from '@reach/router'

const Page3=()=>{
     const BASE_URL = globalHistory.location.origin
    return(
        <div>
            <h3>banana</h3>
            <h4>
                running in {BASE_URL}
            </h4>
        </div>
    )
}

export default Page3
````
Issuing `gatsby develop`  and opening up a new browser window to `http://localhost:8000/page3` yelds the following:
![dara_to_dev](https://user-images.githubusercontent.com/22988955/64655337-d7254a80-d423-11e9-817f-aae2724a812c.png)


Issued `gatsby clean` to purge the cached items and the public folder to get a clean slate and then `gatsby build && gatsby serve` to get a production build and i'm presented with:

![dara_to_build](https://user-images.githubusercontent.com/22988955/64655098-2159fc00-d423-11e9-98b9-26ccc2c75a40.png)

**Comment by Dara-To** [comment]
Thanks for the lead. I created and tested it on a new bug repo as outlined in those steps.

I console logged in my config file the `globalHistory.location.origin`. I realized that I was reading from my terminal which said undefined instead of my browser's console which was correct. But from my memory, a couple of weeks ago, both places had the same logs...that's why I thought something went wrong.

Here is my reproducible test case repo: https://github.com/Dara-To/config-bug-repro

**Comment by jonniebigodes** [comment]
@Dara-To i went through the reproduction you supplied and it looks like everything is in working order.
- Issued gatsby develop and i'm presented with:
![dara_to_1](https://user-images.githubusercontent.com/22988955/64738992-c12d8d80-d4e8-11e9-958f-dfa8fca6d969.png)
- Opening up `http://localhost:8000` i'm presented with:
![dara_to_2](https://user-images.githubusercontent.com/22988955/64739023-d60a2100-d4e8-11e9-858d-a74bf32e0d37.png)
- Issued `gatsby build && gatsby serve` and i'm presented with:
![dara_to_3](https://user-images.githubusercontent.com/22988955/64739152-2e412300-d4e9-11e9-8d74-407a66436b49.png)
- Opening up `http://localhost:9000` and i'm presented with:
![dara_to_4](https://user-images.githubusercontent.com/22988955/64739167-3bf6a880-d4e9-11e9-986e-c5d12eb11d33.png)

In both cases you see the `globalHistory.location.origin undefined` in the console, because as gatsby is a ssr framework, all of the work is done in node, with that in mind at build time the router, it does not know nothing about the history, because the history is a prop that is specific to the client, only when you/another user visits the page, then the prop will be injected with content. 
Could be that something was left in, some stale data and it could have affected it. 

The last test i did was run the production build 25 times and no issues there, everything was working has expected. Once again the output was the one expected.

**Comment by alexeychikk** [comment]
Guys, does anyone know why in production build gatsby passes `path="*"` to the page instead of the actual path like it does in dev?

**Comment by farisadlin** [comment]
> > Note that you can also pull it out via
> > ```js
> > import { globalHistory } from "@reach/router"
> > ```
> > 
> > 
> > If you don't want rerenders due to `<Location>` changes.
> 
> Thanks @damassi!
> 
> And to add some specificity:
> 
> ```js
> import { globalHistory } from "@reach/router"
> const path = globalHistory.location.pathname
> ```

Thank you for this wonderful solution!
