### ISSUE TITLE
childOf field directive doesn't replicate createParentChildLink behavior on parent deletion

### ISSUE THREAD

**Issue by pauleveritt** [gatsbyjs/gatsby#18820]
## Description

When using `@childOf` in a type definition, it correctly assembles the parent-child relationship. However, deleting the parent doesn't delete the child unless you restart the dev server to clear Redux. `createParentChildLink` works correctly.

### Steps to reproduce

[This `childOf` branch in this repo](https://github.com/pauleveritt/gatsby-plugin-paulcms/tree/childof) has a reproducible example.

1. Start the dev server.

2. Issue this GraphQL query to go up the parents:

```
{
  allBlogPost {
    nodes {
      title
      slug
      parent {
        ... on Mdx {
          parent {
            ... on File {
              relativePath
            }
          }
        }
      }
    }
  }
}
```

3. Delete `src/content/blogposts/post1.mdx`

4. Re-execute the query. The result is still there.

5. Restart the dev server.

6. Re-execute the query and there are no matches.

### Expected result

To see this work with `createParentChildLink`:

1. Edit `src/createNode.js` and [uncomment the `createParentChildLink` lines](https://github.com/pauleveritt/gatsby-plugin-paulcms/blob/childof/src/createNode.js#L39) at the bottom.

2. Possibly clean the cache and make sure `post1.mdx` is back.

3. Repeat the steps above. After the file deletion, the query will return (correctly) zero results.

### Actual result

The `BlogPost` nodes aren't cleaned up in Redux when the parent `Mdx` node is deleted.

### Environment

```shell script
$ gatsby info --clipboard

  System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Shell: 5.0.7 - /usr/local/bin/bash
  Binaries:
    Node: 12.12.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /Users/pauleveritt/.pyenv/shims/python
  Browsers:
    Chrome: 78.0.3904.63
    Firefox: 70.0
    Safari: 13.0.2
  npmPackages:
    gatsby: ^2.13.50 => 2.15.34
    gatsby-plugin-mdx: ^1.0.0 => 1.0.50
    gatsby-source-filesystem: ^2.1.8 => 2.1.31
  npmGlobalPackages:
    gatsby-cli: 2.7.57
    gatsby: 2.0.28
```

**Comment by pauleveritt** [comment]
As a note...I spent a lot of time researching this ticket and making a reproducible case in a repo.

It got no response, so it gets closed. "Oh wait, I can add the label 'not stale' to keep it open." But I don't have write access, so I can't change the label.

I recognize you have to take measures to keep the pile under control. Please recognize the side effects of those measures.

**Comment by pauleveritt** [comment]
Not stale, though Gatsby might decide this isn't worth fixing.

**Comment by vladar** [comment]
Thank you for opening this, @pauleveritt 

I'd say we still need `createParentChildLink` to make deletes perform relatively well. Yes, `@childOf` helps us determine the type of a child node but we still need foreign keys to specific nodes to track data dependencies efficiently.

Otherwise, when we delete a node we would have to scan all nodes of a child type to check if their `parent` matches the node we are about to delete. It would be even worse if there are multiple child types.

Some day we may add some kind of indexing on top of the node store to track such relationships automatically but until then we need `createParentChildLink`.

I am going to close this for now but please feel free to reopen this and comment if you would like to continue this discussion or if you think that I am missing something (make sure to mention me in this case).
