### ISSUE TITLE
How to extend custom interface

### ISSUE THREAD

**Issue by alexluong** [gatsbyjs/gatsby#18865]
## Summary
I'm using `gatsby-theme-blog` and would like to extend `BlogPost` interface

## Relevant information

I tried using `createResolvers` but receive an error `Error: Cannot find ObjectTypeComposer with name BlogPost`.

```js
exports.createResolvers = ({ createResolvers }) => {
  createResolvers({
    BlogPost: {
      hello: {
        type: "String,
        resolve: () => "world",
      },
    },
  })
}

```

**Comment by alexluong** [comment]
Hello @pieh @siddharthkp @freiksenet any chance you can take a look at this?

**Comment by jessevdp** [comment]
In Gatsby, I think it's more common to create a child node for a node created by a plugin. That way you're absolutely sure that you don't have any overlap. (If another plugin would add a field to a a type created by the first plugin, and you add some fields as well, field name collisions are going to happen.)

Have a look at [transformer plugins](https://www.gatsbyjs.org/docs/creating-a-transformer-plugin/).

Let's say you create a type `MyBlogPost` which is a child of the `BlogPost` type. A query might look like this:

```graphql
query {
  allBlogPost {
    childMyBlogPost {
      myCustomField
    }
  }
}
```

---

Also, have you tried using [`setFieldsOnGraphQLNodeType`](https://www.gatsbyjs.org/docs/schema-generation/#1-plugins-create-custom-fields)?

---

You mentioned you we're trying to do this on an interface. That might actually be the issue. In interface is nothing more than a description/contract of the shape of the data for types that implement it. It's not concrete. Therefore you can't add implementation details (e.g. resolvers) to it.

This might not be entirely apparent in the context of GraphQL, since `type` and `interface` definitions look very much alike.

Are you familliar with interfaces in a language like `c#`? The analogy might help you understand why it doesn't make sense to add a resolver to an interface. You see an interface just describes the shape of the class that implements it. It defines what public methods it should have, and what the return types are. There is no way to add implementation details to an interface, you can't specify the body. The class implementing the interface is required to implement the methods of the interface, it has to implement the method body.

For example:

```csharp
interface ISampleInterface
{
  string GetName();
}

class ImplementationClass : ISampleInterface
{
  public string GetName()
  {
    return "John Doe";
  }
}
```

Much like in GraphQL, where you need to copy the fields of the interface to the definition of the type implementing it.

```graphql
interface SampleInterface {
  name: String
}

type Sample implements SampleInterface {
  # Required to 'implement' the fields of the interface:
  name: String

  # May add custom, type specific fields too  
  age: Int
}
```

Note that my analogy is just that, an analogy. I don't know if it actually holds up, but I think the explanation makes sense.

**Comment by vladar** [comment]
@jessevdp gave an excellent explanation of why extending interfaces makes little sense. An interface is just a declaration of what fields an object type must include ([relevant graphql docs](https://graphql.org/learn/schema/#interfaces)). Actual field resolving occurs in object types that implement this interface.

One legit case when you may want to extend an interface is to simplify querying for a field of this interface type.

But it actually requires extending an interface **and all of its implementations**. You can do it using `createSchemaCustomization` API:

```js
exports.createSchemaCustomization = ({ actions }) => {
  const { createTypes } = actions
  const typeDefs = `
    interface BlogPost {
      hello: String
    }
    type MyBlogPost implements BlogPost {
      hello: String
    }
    type FriendBlogPost implements BlogPost {
      hello: String
    }
  `
  createTypes(typeDefs)
}
```

And then using `createResolvers` to actually add resolvers to implementor fields:

```js
exports.createResolvers = ({ createResolvers }) => {
  createResolvers({
    MyBlogPost: {
      hello: {
        resolve: () => "from me",
      },
    },
    FriendBlogPost: {
      hello: {
        resolve: () => "from friend",
      },
    },
  })
}
```

The crucial point here is that you must extend **all** object type implementing the interface otherwise your schema will fail validation.

Hope it helps!

**Comment by jessevdp** [comment]
Makes sense, every type that implements the interface must implement the field. What that implementation looks like can vary between types. Implementation is the resolver function.

Side note—with Gatsby the implementation can simply be data, not all fields need resolver functions, most are implicit.
