### ISSUE TITLE
Exclude noindexed pages from gatsby-plugin-sitemap?

### ISSUE THREAD

**Issue by joelwilsonmt** [gatsbyjs/gatsby#18896]
## Summary
I am getting errors in my Google Search Console for "Submitted URL marked ‘noindex’". I am using both the React Helmet and gatsby-plugin-sitemap plugins. I know there is an option in the sitemap plugin to exclude certain predefined pages from the generated sitemap, but is there a way to programmatically exclude pages from the sitemap if a "noindex" can be found in that page's <head>? Thanks!

## Relevant information

Currently I have the default setup for gatsby-plugin-sitemap:
`plugins: ["gatsby-plugin-sitemap"]`
Then in an SEO component that uses React Helmet, this bit of code:
`{noIndex ? <meta name="robots" content="noindex" /> : null}`

But noindexed pages are still showing up in my sitemap, causing site coverage errors via Google Search Console.

I know you can include individual pages, or splatted pages (`/mypath/*`) to exclude from the sitemap, but is there a way when building the sitemap to exclude a page if it contains a noindex <meta> tag injected by React Helmet?

Thanks!

**Comment by cathysiller** [comment]
@joelwilsonmt found a solution that worked for me for this, the issues so old not sure if still is for you!

**Comment by aliwilsonph** [comment]
@cathysiller what was your solution? I'm looking for the same!

**Comment by cathysiller** [comment]
@aliwilsonph are you using graphql or a cms for content? this will be helpful if you are! i utilized serialize option within the gatsby-plugin-sitemap to find every single page that had a robots of nofollow, noindex (inside query context)

`{
      resolve: `gatsby-plugin-sitemap`,
      options: {
        query: `
          {
            site {
              siteMetadata {
                siteUrl
              }
            }
            allSitePage {
              edges {
                node {
                  path
                  context {
                    robots
                  }
                }
              }
            }
          }
        `,
        serialize: ({ site, allSitePage }) => {
          return allSitePage.edges.map(edge => {
            if (edge.node.context.robots === 'noindex,nofollow') {
              return null
            } 

            return {
              url: site.siteMetadata.siteUrl + edge.node.path,
              changefreq: 'daily',
              priority: 0.5,
            };
          })
          .filter(node => node);
        },
      },
}
`

this [video](https://egghead.io/lessons/gatsby-generate-an-seo-friendly-sitemap-for-your-gatsby-site) inspired this solution, so that may be helpful to check out as well! hopefully this helps!

**Comment by cathysiller** [comment]
@aliwilsonph are you using graphql or a cms for content? this will be helpful if you are! i utilized serialize option within the gatsby-plugin-sitemap to find every single page that had a robots of nofollow, noindex (inside query context)

<img width="557" alt="Screen Shot 2021-01-15 at 11 09 51 AM" src="https://user-images.githubusercontent.com/10750223/104757090-3d119880-5722-11eb-8d8c-0e8199d34c3f.png">

this [video](https://egghead.io/lessons/gatsby-generate-an-seo-friendly-sitemap-for-your-gatsby-site) inspired this solution, so that may be helpful to check out as well! hopefully this helps!
