### ISSUE TITLE
Updating Gatsby instance with new build?

### ISSUE THREAD

**Issue by cakerake** [gatsbyjs/gatsby#18894]
So i got my first gatsby test site up and running and ive been trying to figure out an elegant way to update app with a new build and i can't seem to figure out an elegant/non-interruptive method yet

this is the basic method : 
- Work locally running yarn develop
- Push git with all the latest updates
- Run yarn build on the server (the website at this point is throwing errors)
- Run yarn serve (new build is live after 1m~)

an alternate : 
- Work locally with yarn develop
- Build locally with yarn develop
- Remove public folder from .gitignore
- Push git WITH public folder with new build  (all public files get replaced in an instant minimum downtime)
- If yarn serve is running - the website is blank
- if using express - the site has errors

Can you guys help me out? I need the easiest way to deploy a new gatsby build without disrupting the live site

**Comment by universse** [comment]
Check out this [Deploying and Hosting Guide](https://www.gatsbyjs.org/docs/deploying-and-hosting/). I would recommend [Netlify](https://www.gatsbyjs.org/docs/deploying-to-netlify/).

**Comment by LekoArts** [comment]
Thank you for opening this!

As universse said we'd recommend reading our docs on that or using a service that handles that for you. Otherwise you'll need to figure out this yourself unfortunately (as we currently have no docs on that).

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
