### ISSUE TITLE
Improve docs on import vs require

### ISSUE THREAD

**Issue by dnsbty** [gatsbyjs/gatsby#18927]
## Summary
As someone with a pretty low understanding of Javascript coming into the project, I don't know much about the difference between `import` and `require` and when to use one over the other. Better documentation on that could be nice. Specifically in [part 7 of the tutorial](https://www.gatsbyjs.org/tutorial/part-seven/#creating-slugs-for-pages) near the text that says `function for creating slugs`

## Relevant information

Currently the only information I've seen about it is in step 2 [here](https://www.gatsbyjs.org/tutorial/part-two/#-include-the-stylesheet-in-gatsby-browserjs), where it says that usually we'll use `import`. However, when I got to part 7, I'm told to use `require` to get the `createFilePath` function from the `gatsby-source-filesystem` package with no explanation why it's using `require`. I thought maybe I could change that to use `import` instead, but that seems to break when I restart the server.

Because this is a different behavior from the rest of the tutorial, an explanation on why it needs to happen this way would be awesome. It could be like some of the "side quest" tutorials that are optional reading and not part of the critical path.

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: 
This works
```javascript
const { createFilePath } = require(`gatsby-source-filesystem`)

exports.onCreateNode = ({ node, getNode }) => {
  if (node.internal.type === "MarkdownRemark") {
    console.log(createFilePath({ node, getNode, basePath: `pages` }))
  }
}
```

But this doesn't
```javascript
import { createFilePath } from `gatsby-source-filesystem`

exports.onCreateNode = ({ node, getNode }) => {
  if (node.internal.type === "MarkdownRemark") {
    console.log(createFilePath({ node, getNode, basePath: `pages` }))
  }
}
```
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by lekterable** [comment]
The reason why you have to use `require` know as `CommonJS` in `gatsby-node.js` is that this file is executed in the node env, not in the browser. Depending on your version of node it might not support `import` syntax known as `ES Modules` at all, or you might have to use a special flag to turn it on. There are some differences between `CommonJS` and `ES Modules` imports, but none of them matter in this case so this is purely because of the env the code is executed in. I suppose small note wouldn't hurt anyone so feel free to use some of the information I provided if you would like to open a PR :)
