### ISSUE TITLE
Need suggestion for really large site

### ISSUE THREAD

**Issue by chetanbane** [gatsbyjs/gatsby#18946]
Hi Team,

I need suggestions, my client's website. 
I have already done the website for my other client. 

Currently, we are not following any CI/CD process for any of our websites. We do FTP for the production site. While uploading I found there are more than 1800+ files and so on. 
For every small change, I have to upload all the files. Kindly suggest for the same How I can tackle such Problem 
The above problem is for 5 pages website.

I am looking for a solution for 50+ static pages as well as 200+ dynamic pages.

Thanks in advance

**Comment by sidharthachatterjee** [comment]
After https://github.com/gatsbyjs/gatsby/pull/16686 you should only need to upload files that have changed! 

You should be able to diff the `public` directory after every build and see what's changed and only upload those. 

Since this isn't really relevant to gatsby specifically, I'll be closing this for now. But please feel free to reopen or comment if there is anything else we can help with. 

Thank you! 💪
