### ISSUE TITLE
Convert API pages to MDX.

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#19035]
## Summary

The following pages under `www/src/pages/docs` need to be converted to MDX:

* actions.js
* browser-apis.js
* node-api-helpers.js
* node-apis.js
* node-model.js
* ssr-apis.js

### Basic example

See `/docs/docs/graphql-api.md` to see how to integrate the query

### Motivation

The API files are some of the core files to translate to gatsby, and they need to be extracted to MD to make it easier to translate. In addition, the current JS implementation is clunky and relies on `__dangerouslySetInnerHTML` to properly render code blocks.

## Related Issues

#19027 #18704

**Comment by alexluong** [comment]
Hey, I'd love to help with this 👋

**Comment by tesseralis** [comment]
@alexluong sure, go ahead!

**Comment by sever1an** [comment]
Removing the JSDoc may have negative side effects for tools that use it directly such as IDEs. The JSDoc schema also enforces a rigorous format that developers are comfortable with. 

Would it be possible to use https://www.npmjs.com/package/documentation to perform the conversion automatically to ensure consistency and maintain the JSDoc as an original source of truth? If the resultant markdown was tracked in git and used by the website, would this provide an equally viable thing to translate?

**Comment by tesseralis** [comment]
Honestly... I don't know why most of the JSDoc comments are living in stub files. I'd have to ask the team that. The plan is to just convert the text above the JSDoc part to MDX and to pull in the JSDoc using the <APIReference> component.

**Comment by sever1an** [comment]
I definitely misread the other issue about translating source comments. It would definitely be interesting to know what the core team thinks about JSDoc and if it will always be isolated in separate no-code js files.

**Comment by sever1an** [comment]
I have started work on this

**Comment by tesseralis** [comment]
@alexluong @sever1an would you mind splitting the work since there are multiple API files?

**Comment by sever1an** [comment]
I just noticed it was back in the help wanted pile, but would be happy to wait and see if @alexluong is still interested.

**Comment by alexluong** [comment]
If you wanna work on it @sever1an, be my guest. I haven't started yet.

**Comment by sever1an** [comment]
Having the mdx outside of the www folder seems to preclude the execution of static graphql queries within them. Moving forward it would seem that the queries would need to be extracted to

**Comment by sever1an** [comment]
I will have an PR for everyone to consider soon, I hope. 

Having a pageQuery in mdx rendered by `<MDXRenderer>` seems to be impossible, so the graphql in the api docs files needs to be extracted and performed in a component (probably the mdx template). Currently I am comparing two solutions.

### A complicated one with graphql variables and more garbage in `gatsby-node` and the mdx template.
Puts the jsdoc path in frontmatter, then loads it into page context during `createPage`. Another graphql expression using $variables would be added to the mdx template which replaces those in the JS files. 

This seems to inevitably involve a significant amount of bloat to the mdx template file, so there may be some question of relative value considering that the mdx files seem to contain only a few lines of text.

### Something very simple, but that involves api specific components.
Something that might perhaps be simpler considering the relatively stable number of api documents would be to simply create a component for each one containing the required graphql query that *could* be used from mdx.

Internationalization would have total control over them pending the outcome of https://github.com/gatsbyjs/gatsby/issues/19036

### Discussion 
I am gravitating towards the simple solution. Does anybody have insight that I am missing here?

**Comment by tesseralis** [comment]
Thank you so much for the detailed explanation, Bailey!

I think you're right that Single Component Queries would be the best option out of the two. It's a bit inelegant, especially if we do #19036 and these components end up still importing gatsby and relying on a graphql schema, but that's something we can deal with later.

It also seems like, for everything except `actions`, the queries and how they're processed are similar, so maybe we can only have one or two components instead?

**Comment by sever1an** [comment]
Something like `<APIDocs name="browser-apis"/>`?

**Comment by tesseralis** [comment]
Yeah, that's my thought!

**Comment by tesseralis** [comment]
There's something going on with "normalizing" in some of the pages (using two queries and combining them together) and I don’t really know what's going on with that.

**Comment by pieh** [comment]
What about this:

Instead of individual pages like they are right now, we make them templates. We would keep page query (as we kind of need page query to be able to query for different languages if we want both free-form content and jsdocs to be translated):

```js
import { MDXRenderer } from "gatsby-plugin-mdx"

export default class MyPageLayout {
  render() {
    const funcs = sortBy(
      this.props.data.file.childrenDocumentationJs,
      func => func.name
    )

    const normalized = normalizeGatsbyApiCall(this.props.data.nodeAPIs.group)

    const mergedFuncs = funcs.map(func => {
      return {
        ...func,
        ...normalized.find(n => n.name === func.name),
      }
    })

    // according to https://www.gatsbyjs.org/packages/gatsby-plugin-mdx/#mdxrenderer
    // we can pass arbitrary props to MDXRenderer so data becomes available to use in .mdx file
    return <MDXRenderer mergedFuncs={mergedFuncs}>{this.props.data.mdx.body}</MDXRenderer>
  }
}

export const pageQuery = graphql`
  query Docs($language: String!) {
    mdx(<select_node_apis_content>, <select_proper_language>) {
      body
    }
    file(relativePath: { regex: "/src.*api-node-docs.js/" }, <select_proper_language>) {
      childrenDocumentationJs {
        name
        ...DocumentationFragment
      }
    }
    nodeAPIs: allGatsbyApiCall(filter: { group: { eq: "NodeAPI" } }) {
      group(field: name) {
        ...ApiCallFragment
      }
    }
  }
`
```

And then in `api-node-docs.mdx` it could have all the content that is currently hard-coded in react component and at the end import `<APIReference>` component and use `mergedFuncs` passed via MDXRenderer?

**Comment by pieh** [comment]
> There's something going on with "normalizing" in some of the pages (using two queries and combining them together) and I don’t really know what's going on with that.

This is because the content is source from 2 different sources - we should use schema customization for it, so we use single query (and connect those at build time, rather than on runtime) - schema customization just wasn't built yet when this page/template was written.

What this does is combines jsdocs (`DocumentationJs` part) and plugin that looks through gatsby code base to figure out where those extension points (so in gatsby-node, gatsby-browser and gatsby-ssr) are being called in gatsby code base (`GatsbyApiCall` part) - result are those links in our docs ( [`createPages` example](https://www.gatsbyjs.org/docs/node-apis/#createPages) ):
![Screenshot 2019-11-04 at 23 54 49](https://user-images.githubusercontent.com/419821/68165003-90089100-ff5e-11e9-9191-36caa7c10471.png)

**Comment by sever1an** [comment]
@pieh Do you think it would be an acceptable solution to include the jsdoc search stuff as frontmatter with a single new template for api doc mdx? It would be possible to get the values into a page query using graphql parameters and page context.

I am not familiar enough with the inner workings of Gatsby graphql to identify whether this is a good idea, although I can definitely implement it...

```
---
jsdoc: "/src.*api-node-docs.js/"
apicalls: "NodeAPI"
---
```

**Comment by pieh** [comment]
> @pieh Do you think it would be an acceptable solution to include the jsdoc search stuff as frontmatter with a single new template for api doc mdx?

This technically can be done - just the question where this should live - should be in component level or in .md level - using frontmatter will allow us to have single template for all API reference pages. But even then - we could provide this via context when calling `createPage`, so maybe we should just define this in gatsby-node, so .md file don't need to define/track it themselves?

**Comment by sever1an** [comment]
With my current PR I have pursued the frontmatter strategy, but it could easily be modified to use any strategy for mapping jsdoc to mdx.

The mdx files are done and demonstrate how they can use received props in components to render the docs.

A major goal has been to create graphql and normalizing code that can be used for all of the api doc pages. The solution in the PR seems to work (mostly) except some of the original pages filter things out of the jsdoc. 
### Typedefs
Are typedefs *never* supposed to be in the docs or are these cases special?

https://github.com/gatsbyjs/gatsby/blob/d2fdae0129fa1fd2ac7e945581e9d82ba4420f93/www/src/pages/docs/ssr-apis.js#L17-L19

https://github.com/gatsbyjs/gatsby/blob/d2fdae0129fa1fd2ac7e945581e9d82ba4420f93/www/src/pages/docs/browser-apis.js#L17-L19

https://github.com/gatsbyjs/gatsby/blob/d2fdae0129fa1fd2ac7e945581e9d82ba4420f93/www/src/pages/docs/node-model.js#L18

### Forbidden methods
Should this be metadata from jsdoc instead of hard coded into a template?

https://github.com/gatsbyjs/gatsby/blob/d2fdae0129fa1fd2ac7e945581e9d82ba4420f93/www/src/pages/docs/actions.js#L23-L25

**Comment by muescha** [comment]
Since there is a goal for native TypeScript (#18983) in Gatsby: 

would it make sense to put the JSDoc information instead in separate `api-*-docs.js` better into the TypeScript `.d.ts` files?

Then we have this goals fixed:
- doc are decoupled from code (can be pushed to repo for translatIon)
- dts files are up to date (this is needed for right type checking)
- IDE editors can use it for assistance
- more rich descriptive types can be displayed in API Reference

**Comment by sever1an** [comment]
I sincerely doubt that this issue should be closed.

**Comment by sever1an** [comment]
The auto close bot is way too aggressive
