### ISSUE TITLE
docs: how to add styling to the docs website, modifying pseudo-elements

### ISSUE THREAD

**Issue by pranshuchittora** [gatsbyjs/gatsby#19060]
## Summary
Hi,
I am looking forward to bring some styling changes to the docs website but not able to find the style files. I tried the `/www` directory.

**Comment by lannonbr** [comment]
So Gatsby uses [Theme UI](https://theme-ui.com/) for styling which is a few layers on top of the [Emotion](https://emotion.sh/docs/introduction) CSS-in-JS framework so rather than having explicit `.css` files, styles are applied in the JSX either by default with default styles applied by Theme UI or by styles added on specific components using either Theme UI's `sx` prop or other abstractions provided by Emotion.
