### ISSUE TITLE
Issues Getting Closed with One Time Answers

### ISSUE THREAD

**Issue by laurieontech** [gatsbyjs/gatsby#19143]
## Description

Tickets are getting closed when community members respond with a satisfactory solution. However, the response is then limited to the user who opened the ticket.

### Steps to reproduce

N/A

### Expected result

If a user opens an issue and there is an available fix, the responder should be able to point to that answer in the documentation.

If that answer is not reflected in the docs, the issue should be tagged for documentation so that the answer given is available to project users at large.

This expectation should be included in the contributor docs.

### Actual result

Tickets are closed with one-off answers and the hope for future users with that issue is they stumble upon the GitHub issue through a search engine.

### Environment

N/A

**Comment by marcysutton** [comment]
Love this! Documenting and acting on a policy like this would really help to get answers written down so that people can find them more easily. One of our biggest challenges is when answers are buried on GitHub or Stack Overflow–if we instead made a habit of documenting them (and we could even promote new docs from the Twitter account), that would be extremely useful.

**Comment by muescha** [comment]
@marcysutton Is there a way to mark issues with solutions?
And also issues which can be enhance the documentation?
What's the best way to document this?

I see here in #19294 an info about missing parameters documentation (for example in Layout docs)

**Comment by marcysutton** [comment]
This issue is now resolved with @20100.
