### ISSUE TITLE
gatsby-remark-prismjs Toggle themes at runtime

### ISSUE THREAD

**Issue by satvikpendem** [gatsbyjs/gatsby#19155]
I'm using the `gatsby-remark-prismjs` plugin along with `gatsby-plugin-mdx`, and for a theme to be picked up by prism, in `gatsby-browser.js`, I add `require("prism-themes/themes/prism-material-dark.css")`. However, I want the user to toggle the theme dynamically as on the [PrismJS website](https://prismjs.com/), how can I do that, since Gatsby includes everything at build time rather than run time? Is there a method to access the prism CSS and replace it with another theme?

**Comment by LekoArts** [comment]
Thank you for opening this!

This doesn't seem to be an issue/question about Gatsby itself so it's probably best to ask this question in a more general React platform like Reactiflux or Reddit. To give you a short answer: You could e.g. include different CSS with prefixes and toggle the class prefix so that only the CSS with the correct prefix is applied.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by tmkasun** [comment]
Hi @satvikpendem,

 Did you find a way to achieve this requirement, I too want to change the `prismjs` theme based on user theme preference dynamically in the run time ?

Can you please share a method if you found any

Thanks
~Kasun
