### ISSUE TITLE
SSR generated html only contains layout

### ISSUE THREAD

**Issue by magnusarinell** [gatsbyjs/gatsby#19216]
## Description

The html pages for my Gatsby site only contain the layout component. All other page content is shown only after hydration. I can see this through previewing the html response in.my browser and also by the delay for loading the non-layout content. Where can I start to look for the cause of this? Isnt the prerendered page supposed to show other content besides the lauout?

### Expected result

I expect also the other components and page data to be in the ssr generated html pages. 

### Actual result

Only the layout is included in the generatee html. 

### Environment

Gatsby v 2.15.2

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by magnusarinell** [comment]
I found the cause. It was the gatsby-plugin-offline. When I removed that everything works as expected.
