### ISSUE TITLE
gatsby-plugin-mdx: Changing Information needs restart

### ISSUE THREAD

**Issue by Knaackee** [gatsbyjs/gatsby#19273]
I use "gatsby-plugin-mdx" latest version (1.0.55).

If I change something other than the "body" of a MDX file I need to restart the Gatsby server. 
Changes on the body gets hot reloaded, others don't. E.g. if I change the `title` or `description` I need to restart.

```
---
templateKey: blog-post
title: Hello World
description: Something
date: '2017-07-12T17:12:33.962Z'
---
# Hello World 
```

Did i miss something here?

**Comment by LekoArts** [comment]
Hi!

I spun up a Gatsby project that uses MDX and changing e.g. the title of an article works fine. Hot-Reloading works: https://codesandbox.io/s/gatsby-starter-blog-mdx-72975

Can you please share a project where you're seeing this behavior?

**Comment by Knaackee** [comment]
Problem solved. You can close this. Thx @LekoArts !

**Comment by sebastienbarre** [comment]
With that being said, I see something similar as of today running [Part 6 of the tutorial](https://www.gatsbyjs.com/docs/tutorial/part-6/): "Congratulations, you now have a multi-page blog site! Try adding some new .mdx files to your top-level blog directory. They should get added to your Blog page automatically when your site rebuilds!". 

I added an MDX file, and sure enough it showed up in the *list* of blog posts, but when I clicked on it, so it seems the file node was there, but once I clicked on the link, I got a 404 instead of the new blog post page. I had to restart the server to make the latter happen.
