### ISSUE TITLE
Document how to use Gatsby with PNPM (& Rush with PNPM)

### ISSUE THREAD

**Issue by hcharley** [gatsbyjs/gatsby#19316]
For users of PNPM (& Rush with PNPM), a little workaround is needed to resolve modules.

This workaround written by @vjpr did the trick for me:

https://github.com/pnpm/pnpm/issues/991#issuecomment-446330885

> ## Workaround
> ```js
> let gatsbyNodeModules = require('fs').realpathSync('node_modules/gatsby')
> gatsbyNodeModules = require('path').resolve(gatsbyNodeModules, '..')
> 
> exports.onCreateWebpackConfig = ({ stage, actions }) => {
> 
>   actions.setWebpackConfig({
>     resolve: {
>       modules: [gatsbyNodeModules, 'node_modules'],
>     },
>   })
>   
> }
> ```

Related tickets:

- https://github.com/gatsbyjs/gatsby/issues/2948
- https://github.com/pnpm/pnpm/issues/991#issuecomment-446330885

**Comment by wardpeet** [comment]
oh @charlex we should have pnpm support without any troubles.

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a minimal reproduction. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could provide a minimal reproduction and we'll be able to take another look.

Thanks for using Gatsby! 💜

**Comment by Js-Brecht** [comment]
There's probably always going to wind up being issues, because of the way Webpack works, and because of how its configuration is extended sometimes.  It would be impractical, and excessive, for Gatsby to try to cover every edge case.

Somebody else ran into problems recently with `gatsby-plugin-react-svg`, because of the way that plugin defines `loader`... they just use `loader: 'svg-react-loader'`, instead of `loader: require.resolve('svg-react-loader')`.  Because of that, Webpack has no idea where to look for `svg-react-loader`

Because of all of that, and to kind of fill in some gaps in support (plus, I got tired of having to take care of shortcomings in every project), I created [`gatsby-plugin-pnpm`](https://github.com/Js-Brecht/gatsby-plugin-pnpm).  v1.0.0 handles the most basic use case, but I'm about to release v1.1.0, which will make it much easier to define resolutions for packages that need a little extra help, or even to define your own custom paths that Webpack can use for resolving modules & loaders.

**Comment by nikoladev** [comment]
For yarn and npm there's documentation pages:

- https://www.gatsbyjs.org/docs/glossary/npm/
- https://www.gatsbyjs.org/docs/glossary/yarn/

Is there any reason we shouldn't have one for pnpm too? Then we could also mention [gatsby-plugin-pnpm](https://github.com/Js-Brecht/gatsby-plugin-pnpm) by @Js-Brecht.

Also, it seems that this issue was auto-closed without actually being resolved so I opened it again.

**Comment by Js-Brecht** [comment]
Btw, I've done some small bits of work recently to make Gatsby work better with Rush.  I use a Rush monorepo successfully now; it has several Gatsby sites in it already, and it is steadily getting bigger.  Still need `gatsby-plugin-pnpm`, but the other blocking issues are getting fixed as I encounter them.

**Comment by wardpeet** [comment]
@Js-Brecht is pnpm different from yarn2 pnp? Cause I had some success with gatsby and yarn2

**Comment by Js-Brecht** [comment]
It is.  pnpm still relies on node_modules, while yarn2 has gotten rid of it for the most part.  yarn2 also does some patching of the native `require` & `fs`, to name a few, so that it can sit between your `require()` calls and the actual package on the disk.  This is the way it eliminates copying/linking everything into your local project, and also guards against phantom dependencies during runtime.

yarn2 aims to download/store once, use everywhere (without linking/copying at all).

pnpm relies on its node_modules structure to isolate packages with access to only their dependencies.  This has changed some over time, to where it now places dependencies and their sub-dependencies in their own little bucket so that they can take advantage of hoisting among themselves (to a certain extent), but keeps your project's direct dependencies separate to enforce stricter dependency management.

pnpm downloads packages to its global store, and when you need to install it, it will hard link it instead of copying.  This is what makes it so much faster than yarn & npm.  The dependency handling is much more reliable, too.  

I really like yarn2, and I think that it is the future of dependency management, but it is still lacking first-class support in certain areas, so it can make the DX a little painful sometimes (getting better all the time).  If node, vscode, and typescript were to all get on board with it, I would use it everywhere.

For now, I like to use yarn2 in my personal projects, including a couple Gatsby projects.  Since pnpm is more stable (less troublesome?) and works great with Rush, I use it for business.

**Comment by nyn3x** [comment]
In respect to https://www.gatsbyjs.com/docs/reference/gatsby-cli/#how-to-change-your-default-package-manager-for-your-next-project I naive tried to change the config.js by setting pnpm as my package manager. But this doesn't seem to impress gatsby at all.

Is there any trick to convince the gatsby cli to use pnpm for new projects?

As far as I understand https://github.com/Js-Brecht/gatsby-plugin-pnpm is being used to support pnpm while running gatsby, not during initial creation of a new project.

**Comment by LekoArts** [comment]
Fixed with https://github.com/gatsbyjs/gatsby/pull/31732

**Comment by hcharley** [comment]
Thank you @LekoArts!
