### ISSUE TITLE
window is not defined on build using Skrollr,  then ERROR #95313 after bypassing bad module

### ISSUE THREAD

**Issue by franszo** [gatsbyjs/gatsby#19346]
## Summary
Working on a site in gatsby , using react-skrollr https://www.npmjs.com/package/react-skrollr  an animation library on scroll. All working in development mode, but when I try to build the project, obviously drops `window is not available`. Found out I can bypass the wrong module with the below in my `gatsby-node.js`

````
exports.onCreateWebpackConfig = ({ stage, loaders, actions }) => {
  if (stage === "build-html") {
    actions.setWebpackConfig({
      module: {
        rules: [
          {
            test: /skrollr/,
            use: loaders.null(),
          },
          {
            test: /react-skrollr/,
            use: loaders.null(),
          },
        ],
      },
    })
  }
}
````

then I get this weird error I can't figure out

````
failed Building static HTML for pages - 2.901s

 ERROR #95313

Building static HTML failed for path "/about/"

Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=1  30&args[]=undefined&args[]= for the full message or use the non-minified dev environment for fu  ll errors and additional helpful warnings.
````

and this at the end :
````
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in StoreStateProvider
    in App
````

Here is a stripped out code of the About page, producing the error, problem is the `<ParallaxProvider>` for sure, because without it working but I'd very much need this component. Any help would be appreciated.

````
import React from "react"
import Layout from "../components/Layout/Layout"
import { graphql } from "gatsby"
import SEO from "../components/seo"
import { ParallaxProvider } from "react-skrollr"


const AboutPage = () => {

  return (
    <Layout className="about">
      <ParallaxProvider>
        <div>HEllo</div>
      </ParallaxProvider>
    </Layout>
  )
}

export default AboutPage
````

**Comment by jonniebigodes** [comment]
@franszo i've picked up on your issue and i think i have a solution for you.

Here are the steps i took to triage your issue:
- Created a new gatsby website with the default starter.
- Added the package you've mentioned and also [react-loadable](https://github.com/jamiebuilds/react-loadable), this package helps out in some cases like this one.
- Created a new page in `src/pages` callled `about.js` with the following code:
```js
import React from "react"
import Layout from '../components/layout'
import Loadable from "react-loadable"


const loader=()=>(<div>Loading about content.....</div>)
const MyParallaxComponent = Loadable({
  loader: () => import("../components/LoadableParallax"),
  loading: loader,
})
const AboutPage = () => {
  return (
    <Layout className="about">
      <MyParallaxComponent />
    </Layout>
  )
}

export default AboutPage
```
This is a straightforward gatsby page with a caveat. The `MyParallaxComponent ` loading will be defered to the client side. Meaning that when a user lands on this page ony then the component will be loaded and content displayed.
- Created the `LoadableParallax` in `src/components/LoadableParallax.js` with the following content:
```js
import React from "react"
import { ParallaxProvider, Parallax } from "react-skrollr"

const LoadableParallax = () => (
  <ParallaxProvider
    init={{
      smoothScrollingDuration: 500,
      smoothScrolling: true,
      forceHeight: false,
    }}
  >
    <Parallax
      data={{
        "data-center-center": "opacity: 1;",
        "data-bottom-top": "opacity: 0;",
      }}
    >
      <div>
        Doggo ipsum heckin good boys doggorino. Heckin good boys doggorino shibe
        puggorino I am bekom fat doge, clouds bork I am bekom fat puggorino.
        What a nice floof blop thicc puggo extremely cuuuuuute, doge pupperino
        h*ck. such treat wow such tempt mlem. Snoot borking doggo extremely
        cuuuuuute length boy borkf you are doin me a concern smol, length boy
        dat tungg tho stop it fren noodle horse. Maximum borkdrive many pats
        shoober, long bois. Thicc very hand that feed shibe long woofer wow very
        biscit heckin big ol pupper I am bekom fat puggorino, long bois shibe
        heckin good boys boofers puggo pats. Pats you are doin me a concern
        snoot porgo what a nice floof mlem boof woofer extremely cuuuuuute,
        shoober floofs long water shoob wow such tempt snoot long doggo such
        treat. Heckin good boys and girls length boy ur givin me a spook stop it
        fren, doggorino. shibe very taste wow blep. 
       ........
      </div>
    </Parallax>
  </ParallaxProvider>
)
export default LoadableParallax
```
The options provided here are the default ones that the npm page offers. 
- Ran `gatsby develop` and i was able to get a successfull build and the content showing correctly. Same as with a production build with `gatsby build && gatsby serve`.
- I have hoisted the code to a repo in [here](https://github.com/jonniebigodes/gatsby-react-SKrollr) and a live version running [here](https://frosty-boyd-b8dc47.netlify.com/)

Feel free to provide feedback so that we can close this issue or continue to work on it until we find a suitable solution.

**Comment by muescha** [comment]
one note about the seo: i think the content of the LoadableParallax is not visible to google crawler?

**Comment by franszo** [comment]
@jonniebigodes  wow, Loadable just did the trick! many thanks for the effort and the quick response!
@muescha thanks for pointing this out, think I can place my main SEO component outside the loadable component, so at least can have some SEO for the head, title, desc, etc.

Thanks again!

**Comment by jonniebigodes** [comment]
@franszo no need to thank, glad that i was able to solve your issue.
