### ISSUE TITLE
Gatsby automatically loading dotenv in an undocumented way

### ISSUE THREAD

**Issue by patspam** [gatsbyjs/gatsby#19388]
Gatsby automatically loads the dotenv file `.env.${GATSBY_ACTIVE_ENV || NODE_ENV}`. This is not documented on the [environment variables](https://www.gatsbyjs.org/docs/environment-variables/) page.

I see this as pretty dangerous - a developer who puts their production deployment config into `.env.production` could end up unintentionally talking to prod backends when running `gatsby build && gatsby serve` from their local machine.

**Comment by muescha** [comment]
Here about this in Examples: https://www.gatsbyjs.org/docs/environment-variables/#example-1

**Comment by muescha** [comment]
You mean this here:

https://github.com/gatsbyjs/gatsby/blob/76ac266a19502c5c038a5fab697dcbfaed5ec664/packages/gatsby/src/utils/webpack.config.js#L45-L65

**Comment by muescha** [comment]
I see it is not clear documented there, because it is only in example for custom code. 

The story behind this is only in issue/commit comments: https://github.com/gatsbyjs/gatsby/search?q=GATSBY_ACTIVE_ENV&type=Issues

**Comment by muescha** [comment]
Realted also #19387

**Comment by LekoArts** [comment]
> I see this as pretty dangerous - a developer who puts their production deployment config into .env.production could end up unintentionally talking to prod backends when running gatsby build && gatsby serve from their local machine.

I'm not sure I follow. Creating a `.env.production` is exactly for that use case IMO. If you only explicitly create a `.env.development` you intend to only use that while developing. If you then don't want to use in while testing `gatsby build` locally, don't create the `.production` file. You wouldn't commit it to GitHub anyways.

But I agree that the automatic reading should be documented with a one-liner somewhere in the doc.

**Comment by patspam** [comment]
If I was working with prod from a local machine, I still don't see any situation where you'd want it to be governed by mode Gatsby was running in - they're completely tangential concerns.

**Comment by muescha** [comment]
Maybe it is also useful to have some messages in the log to avoid some confusion about this

```javascript
success: open and validate gatsby-configs
success: using env file: .env.staging
success: using Gatsby mode: production
```

**Comment by bobylito** [comment]
Hi there,

My use case: I use the .env files to configure "ok to publish" information such as backend URL and public API keys per environment. I have 2 files (commited): `.env.production` `.env.staging`. I use netlify to build my website. I use `ENVIRONMENT` to set my environment in the same spirit as [here](https://www.gatsbyjs.org/docs/environment-variables/#example-1)

Reading the discussion and from my own (mind boggling) experience using a staging setup:
 - when going through the `gatsby-config.js` file I have the correct environment
 - then in my code, the process.env contains the production variables. From what I read, this is because Gatsby also leverages the environment in the webpack config.

This is confusing and not what I expected. From what I understand of the [example](https://www.gatsbyjs.org/docs/environment-variables/#example-1), I should make the variables available through GraphQL and never use the environment with `process.env`.

Let me know if you have any questions about my use-case or if you have some suggestions about handling environment configuration.

**Comment by LekoArts** [comment]
The initial issue was addressed in the doc, the follow-up is tracked here: https://github.com/gatsbyjs/gatsby/issues/19388

**Comment by muescha** [comment]
> The initial issue was addressed in the doc, the follow-up is tracked here: #19388

did you mean #21004?
