### ISSUE TITLE
tailwind.config.js inside a theme

### ISSUE THREAD

**Issue by alexluong** [gatsbyjs/gatsby#19395]
## Summary

I'm building a Gatsby theme using `tailwindcss`. However, when I create `tailwind.config.js` file inside the theme, it's not used. I have to put it inside the site instead.

Is there anything I can do about this?

## Expected behavior

```
// this file structure to work
- site
- theme
  |-- tailwind.config.js

// I have to do this
- site
  |-- tailwind.config.js
- theme
```

Ideally, it will check `site/tailwind.config.js` first, and if it doesn't exists, it will check `theme/tailwind.config.js`.

Right now, I need to re-export the config inside the site directory.

```
// site/tailwind.config.js
module.exports = require("theme/tailwind.config");
```

This is not **too bad**, but I think it can be better. Thank you!

**Comment by LekoArts** [comment]
Hi! This doesn't sound like it's a problem with Gatsby but with Tailwind. Please ask on their repository first and if it's absolutely sure that it's an issue with Gatsby, feel free to reopen this.

**Comment by sabrinaluo** [comment]
I have encountered the same issue, no solution yet except for the above mentioned one

**Comment by tiggeymone** [comment]
Given that you have to configure postcss plugins inside gatsby-config.js, you can configure tailwind to require a custom config file path as well:

`````
plugins: [
    {
      resolve: `gatsby-plugin-postcss`,
      options: {
        postCssPlugins: [
          require("postcss-import"),
          require("tailwindcss")({ config: `${__dirname}/tailwind.config.js` }),
          require("postcss-preset-env")({ stage: 1 }),
        ],
      },
    },
`````

This way your tailwind configuration file should have the right path and you can use it inside your gatsby theme.

**Comment by ashiishme** [comment]
I had a similar problem. I was building a theme that uses `tailwind` but because of the configuration file I was getting an error:

```ts
ERROR in ../<theme-directory>/src/styles/global.css
Module build failed (from ../node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from 
../node_modules/gatsby-plugin-postcss/node_modules/postcss-loader/dist/cjs.js):
TypeError: Cannot read properties of undefined (reading 'config')
    at getTailwindConfig
    ....
```

The test site using my theme was failing whenever I try to import the CSS in `gatsby-browser.js` file. The issue was with the `tailwind` config file not available for the test site although themes depends on it.

The Tailwind documentation ( integration with Gatsby ) doesn't mention about loading the config file ( which is required in case of theme ).

To fix this, as mentioned in above comment we need to include the config file which can also be done from `postcss.config.js` which comes with Tailwind.

```js
module.exports = {
  plugins: {
    tailwindcss: { config: `${__dirname}/tailwind.config.js` },
  },
}

```
