### ISSUE TITLE
Client only route flickers page not found and misconfigured layout on reload

### ISSUE THREAD

**Issue by zanehiredevs** [gatsbyjs/gatsby#19394]
Hi I have a website made with Gatsby that went live recently https://www.bambooasia.com.  I am seeing some strange rendering issues with `refreshing the browser` on our `client only routes` (`/checkout` in particular).  Any help is appreciated.

We are using the recommended approaches for loading client only routes for checkout.  We do not use the offline plugin.  We do use react-mobx and inject our stores via `wrapWithProvider`.
https://www.gatsbyjs.org/docs/building-apps-with-gatsby/
https://www.gatsbyjs.org/docs/client-only-routes-and-user-authentication/

Issues:

1) In chrome if you `refresh` the checkout page (a client only route page) the layout is all screwed up like the rendering was borked somehow. (see picture below)  Firefox seems to handle it a bit better but the styles are still off on refresh.  This does not happen when using using the router to navigate and it is only reproducible with `browser refresh` with the built files and does not occur when running the local dev server.  I've tried clearing browser caches and it still happens.

<img width="1373" alt="Screen Shot 2019-11-09 at 4 25 01 PM" src="https://user-images.githubusercontent.com/44630404/68536934-06671380-0310-11ea-93cb-a78e1769629e.png">

2) The checkout page will flash `page not found` message on render on `browser refresh` before it renders the components for the page.  See below gif for example.

![bamboo-pagenotfound](https://user-images.githubusercontent.com/44630404/68536969-d10ef580-0310-11ea-8047-a741c48c58d2.gif)

**Comment by zanehiredevs** [comment]
Forgot to mention a third issue, the client only routes do not scroll the browser up automatically like normal gatsby link driven pages.  We tried manually scrolling up with something like this on our checkout component but it needs a huge timeout to actually scroll up which is not a great experience, is there a recommended way to auto scroll up client only routes?  Thanks

```
    componentDidMount = () => {
        if (typeof window !== 'undefined') {
            setTimeout(() => {
                window.scrollTo(0, 0);
            }, 1000); // <= 500 does nothing
        }
    }
```

**Comment by sever1an** [comment]
This is usually caused by not having a url rewrite rule for the client only path on the webserver. Instead the `404` page is sent. When the app hydrates from the `404` page, internal routing takes over and actually finds the correct page. `HTTP --> 404.js --> matchPath `

It looks like you are using Netlify, which is capable of handling the rewrites perfectly. `gatsby-plugin-netlify` should make them for you. With an in-house solution it might not.

A good place to start debugging would be to see what rewrites are defined in the deployment:
https://docs.netlify.com/routing/redirects/rewrites-proxies/

**Comment by zanehiredevs** [comment]
@sever1an thanks I was thinking it had to do with the redirects I’ll look into that and report back.  FWIW we are using gatsby-plugin-netlify but maybe that doesn’t have auto support for client only routes.

**Comment by sever1an** [comment]
The plugin is definitely supposed to support them. It appears to put the paths in `public/_redirects`. Knowing what is there will really help isolate the issue. Another file of interest would be `.cache/match-paths.json`.

There was a pretty big fix for client only routes in a recent version of `gatsby`, so updating might actually help too.

**Comment by zanehiredevs** [comment]
@sever1an ok I upgraded all packages and it did help with the css/layout display issues on refresh.  I fixed the issue with page not found by changing some custom routes we had configured with reach router it was redirecting to another route `/checkout/customer` on the client side when hitting `/checkout` so that explains why it wasn't found.  I changed it to stay at the root `/checkout` for the first step to match what gatsby is expecting and it fixed the page not found issue on refresh.  Appreciate the help digging into that really helped 👍

**Comment by JustFly1984** [comment]
@sever1an We have a setup I have a case with flickering 404 for client-render routes for reset password page in netlify(staging) and AWS CloudFront/S3(production) it is the same issue.

We have a URL https://example.com/en/reset/TOKEN. generated in backend email.

All pages in Gatsby.js are generated with node api.

```javascript
{
      path: '/en/reset',
      matchPath: '/en/reset/*',
      component: ResetTemplate,
},
```

and in ResetTemplate I have code with Router and I grab token from the component.

```typescript
import * as React from 'react'
import { Router } from '@reach/router'
import { useIntl } from 'react-intl'

import FormattedMessage from 'src/components/common/formatted-message'

import Layout from 'src/components/layout/static'
import Seo from 'src/components/seo'

import FormReset from 'src/components/auth-reset'

import * as auth from 'src/styles/auth.module.css'
import * as layout from 'src/styles/layout.module.css'

import { StaticPage } from 'src/types/common'

const values = {
  amber(str: string): JSX.Element {
    return <span className={auth.titleAmber}>{str}</span>
  },
}

interface Props {
  path: string
  token?: string
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
function ResetContent({ path, token }: Props): JSX.Element {
  return (
    <div className={layout.section}>
      <h1 className={auth.title}>
        <FormattedMessage
          id='reset.headline'
          defaultMessage='Reset your <amber>password</amber>'
          values={values}
        />
      </h1>

      {token !== undefined && token !== '' && <FormReset token={token} />}
    </div>
  )
}

function Content(): JSX.Element {
  const intl = useIntl()

  return (
    <Router>
      <ResetContent path={`/${intl.locale}/reset/:token`} />
    </Router>
  )
}

function ResetPage({ pageContext }: StaticPage): JSX.Element {
  return (
    <Layout pageContext={pageContext}>
      <Seo title='reset.title' />

      <Content />
    </Layout>
  )
}

export default React.memo(ResetPage)
```

The issue I see, that only `<ResetContent path='/en/reset/:token' />` actually should be client-side rendered.

`/en/reset/` itself should be statically pre-rendered.

If I get rid of matchPath in reset page generation, I got /en/reset pre-rendered, but navigating to `/en/reset/token` shows me 404 page, and I can't have mixed rendering content. very frustrating.

I have created static routes:

```
    {
      path: '/en/reset',
      component: ResetTemplate,
    },
    {
      path: '/en/reset/:token',
      matchPath: '/en/reset/*',
      component: ResetTemplate,
    },
```

but it did not help either. Still have 404 flickering for `/en/reset/:token`

Please reopen an issue.

**Comment by sever1an** [comment]
@JustFly1984 Are you sure that the nested router is actually producing the HTML you want it to on SSR? It looks like you only have the match-path for `/en/reset`, not a static page. If this is the case the nested router must produce content for `/en/reset/` as well.

The enclosed router does not appear to match the base path, so perhaps it is actually producing a 404 response? I would inspect the generated HTML to see what is coming out of the router in SSR.

If the router is producing nothing, it is worth noting that reach router needs *help* choosing what url to render in SSR [Reach Router SSR Docs](https://reach.tech/router/server-rendering). The *mystery* is whether this *magically happens* because of something from the enclosing gatsby site, or if you have to actually do it.

**Comment by JustFly1984** [comment]
@sever1an In my case I got an url in password reset email. Url is https://{domain}/{locale}/reset/{token}

token is always unique, and I'm taking in from url with @reach/router.

I could manage it working on netlify with gatsby-plugin-netlify, and it generated correct redirects:

```
## Created with gatsby-plugin-netlify

/en/reset/*  /en/reset/:token  200
/en/account/*  /en/account/:page  200
/en/*  /en/404.html  200
/ru/reset/*  /ru/reset/:token  200
/ru/account/*  /ru/account/:page  200
/ru/*  /ru/404.html  200
/*  /404.html  200
```

but it does not work correctly for AWS s3/cloudfront.

I have tried to deploy with gatsby-plugin-s3, but it generates broken redirects in s3. Then I navigate from an email link, it replaces real token with /[:token] line, and it is breaking functionality.

The only way I can think about to fix it - wait for a backend guy to change email link generation code to put token to querystring instead of route part of url.

**Comment by JustFly1984** [comment]
@sever1an  We have fixed our issue by adjusting the link to reset page with token

before:

```
https://example.com/reset/token
```

after:
```
https://example.com/reset/?token=token
```

Please pay attention to `/` at the end of path - it is required, otherwise AWS Cloudfront web server will redirect you to path with reset without saving querystring, and you end up with lost data and UX fatal issue.

We have not noticed this behavior on netlify, so this bug skipped to production deploy on AWS.

**Comment by sever1an** [comment]
@JustFly1984  With `gatsby-plugin-s3`, CloudFront acts as a proxy to an HTTP server provided by S3. The buckets have some facility to create metadata about redirects, but it is honestly an awkward language that clashes with the ideology of `@reach/router`. We considered it for production and decided not to use it. Your problem might not even be a bug, just a limitation of S3....

CloudFront has a more recent ability to access and serve files directly from S3 using something like `aws-sdk` instead of the bucket serving content using HTTP. In this scenario `lambda@edge` functions for origin request and origin response are necessary to handle rewrite/routing and cache rules. Someone could write a facility to automatically create the lambda function and deploy it, but there seems to really be zero interest. 

AFAIK The Netlify plugin is the only one that *just works* with rewrites/redirects. With Zeit Now and Heroku it is at least possible to create rewrites using a sane syntax, but still by hand.

**Comment by JustFly1984** [comment]
@sever1an 
I'm deploying with simple aws-sdk s3 sync + invalidation. btw still having same kind of 404 flickering for /account/ client-side rendered pages, so I would love if anybody will reopen this issue
There should be some kind of server-side rendered fallback for client-side rendered routes, so they don't go 404 on AWS, nor netlify.

**Comment by JustFly1984** [comment]
the most annoying part of the bug is that layout of 404 page DOM merges with client-side rendered DOM incorrectly, which breaks layout and functionality.

**Comment by tayrotayro** [comment]
> @sever1an ok I upgraded all packages and it did help with the css/layout display issues on refresh. I fixed the issue with page not found by changing some custom routes we had configured with reach router it was redirecting to another route `/checkout/customer` on the client side when hitting `/checkout` so that explains why it wasn't found. I changed it to stay at the root `/checkout` for the first step to match what gatsby is expecting and it fixed the page not found issue on refresh. Appreciate the help digging into that really helped 👍

Can I get some more info on how you resolved this because the exact same thing is happening on all of my client side routes(private routes with prefix '/app'). When i refresh, its hitting not found page then messing with the layout. It's messing with the layout by pulling stying from the "Not found" page.
