### ISSUE TITLE
[gatsby-plugin-mdx] onCreatePage throw an error when my babel.config.js add presets: @babel/preset-typescript

### ISSUE THREAD

**Issue by littledian** [gatsbyjs/gatsby#19419]
## Description

throw an error as shown when I set my babel.config.js like it:

{
presets: [
      [
        '@babel/preset-env',
        {
          modules: false,
          useBuiltIns: false
        }
      ],
      '@babel/preset-typescript',
      '@babel/preset-react'
    ],
    plugins: [
      '@babel/plugin-transform-runtime',
      ['@babel/proposal-class-properties', { loose: true }]
    ]
}

errors:

Error: [BABEL] unknown: Preset /* your preset */ requires a filename to be set when babel is called directly,
  ```
  babel.transform(code, { filename: 'file.ts', presets: [/* your preset */] });
  ```
  See https://babeljs.io/docs/en/options#filename for more information.
  
  - full.js:239 validateIfOptionNeedsFilename
    [common]/[@babel]/core/lib/config/full.js:239:11
  
  - full.js:251 options.overrides.forEach.overrideOptions
    [common]/[@babel]/core/lib/config/full.js:251:52
  
  - Array.forEach
  
  - full.js:251 validatePreset
    [common]/[@babel]/core/lib/config/full.js:251:25
  
  - full.js:258 loadPresetDescriptor
    [common]/[@babel]/core/lib/config/full.js:258:3
  
  - full.js:79 config.presets.reduce
    [common]/[@babel]/core/lib/config/full.js:79:21
  
  - Array.reduce
  
  - full.js:76 recurseDescriptors
    [common]/[@babel]/core/lib/config/full.js:76:38
  
  - full.js:110 loadFullConfig
    [common]/[@babel]/core/lib/config/full.js:110:6
  
  - transform.js:41 transformSync
    [common]/[@babel]/core/lib/transform.js:41:38
  
  - transform.js:22 Object.transform
    [common]/[@babel]/core/lib/transform.js:22:38
  
  - extract-exports.js:9 module.exports.code
    [common]/[gatsby-plugin-mdx]/utils/extract-exports.js:9:9
  
  - on-create-page.js:20 Object.module.exports [as onCreatePage]
    [common]/[gatsby-plugin-mdx]/gatsby/on-create-page.js:20:29

### Steps to reproduce

Get error when run cmd: gatsby develop, I just do it follow https://www.docz.site/docs/powered-by-gatsby and my file replace with tsx not effect

**Comment by LekoArts** [comment]
Thank you for opening this!

Unfortunately it's not absolutely clear from your issue description what your real issue is. Please try to follow the issue template in the future so that we can help you better, thanks!

If you want to use TypeScript, you can have a look at these docs: https://www.docz.site/docs/usage-with-typescript

I'd also recommend opening an issue on their repository if that doesn't help as this project is not directly affiliated to us and thus we don't handle bug reports for that.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
