### ISSUE TITLE
I can't install Gatsby

### ISSUE THREAD

**Issue by codder404** [gatsbyjs/gatsby#19425]
## Description

Describe the issue that you're seeing.

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

How to Make a Minimal Reproduction: https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/

### Expected result

What should happen?

### Actual result

What happened.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by ccchapman** [comment]
@codder404 Sorry you are having trouble installing Gatsby. Here are resources that may help resolve your issue:

- [Gatsby.js Tutorials](https://www.gatsbyjs.org/tutorial/)
- [Where to get community support](https://www.gatsbyjs.org/contributing/community/#where-to-get-support)

I will close this since these issues are for bug reports and feature requests. Feel free to provide details per the issue template if this is a bug report.
