### ISSUE TITLE
[gatsby-source-cosmicjs] Error: Request failed with status code 502

### ISSUE THREAD

**Issue by grace000** [gatsbyjs/gatsby#19421]
## Summary
After running `gatsby develop` locally or `gatsby build` on CI, the following error is displayed and prevents build:

<img width="681" alt="Screen Shot 2019-11-11 at 10 24 35 AM" src="https://user-images.githubusercontent.com/21062007/68606129-64603c00-0473-11ea-98b8-354909b10f59.png">

```
warn The gatsby-source-cosmicjs plugin has generated no Gatsby nodes. Do you need it?
success source and transform nodes - 3.772 s
success Add explicit types - 0.031 s
success Add inferred types - 0.276 s
success Processing types - 0.150 s
success building schema - 0.592 s
```

## Relevant information
Code source started from "gatsby started default" and later included the CosmicJS plugin:

```
 {
      resolve: `gatsby-source-cosmicjs`,
      options: {
        bucketSlug: [slug info],
        objectTypes: [
          `brands`,
          `tags`,
        ],
        // If you have enabled read_key to fetch data (optional).
        apiAccess: {
          read_key: [key info],
        },
      },
},
```

### Environment 

```
 System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.12.0 - ~/.nvm/versions/node/v12.12.0/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.11.3 - ~/.nvm/versions/node/v12.12.0/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 78.0.3904.87
    Firefox: 69.0.1
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.15.28 => 2.15.28
    gatsby-awesome-pagination: ^0.3.4 => 0.3.4
    gatsby-cli: ^2.7.53 => 2.7.53
    gatsby-image: ^2.2.23 => 2.2.23
    gatsby-plugin-google-tagmanager: ^2.1.12 => 2.1.12
    gatsby-plugin-manifest: ^2.2.20 => 2.2.20
    gatsby-plugin-offline: ^2.2.10 => 2.2.10
    gatsby-plugin-react-helmet: ^3.1.10 => 3.1.10
    gatsby-plugin-root-import: ^2.0.5 => 2.0.5
    gatsby-plugin-s3: ^0.3.2 => 0.3.2
    gatsby-plugin-sass: ^2.1.17 => 2.1.17
    gatsby-plugin-sharp: ^2.2.27 => 2.2.27
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4
    gatsby-source-cosmicjs: 0.0.7 => 0.0.7
    gatsby-source-filesystem: ^2.1.28 => 2.1.28
    gatsby-transformer-sharp: ^2.2.19 => 2.2.19
  npmGlobalPackages:
    gatsby-cli: 2.8.9
```

**Comment by LekoArts** [comment]
Thank you for opening this!

As also written on [their docs](https://cosmicjs.com/docs/rest-api/errors.html) the 502 error means that something on their end didn't work. Therefore I'd recommend opening an issue on the source plugin repository or contacting their support so that they can help you solving the problem :)

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
