### ISSUE TITLE
Allow specifying image width via attribute in gatsby-remark-images

### ISSUE THREAD

**Issue by alexlouden** [gatsbyjs/gatsby#19439]
## Summary

I've forked gatsby-remark-images and added the ability to specify a width for individual images: https://github.com/Bonobolabs/gatsby-remark-image-custom-widths

### Basic example

Old:
```md
![My image](./image.jpg)
```

New:
```md
<img src="./image.jpg" alt="My image" width="500px"/>
```

This passes in 500px to the plugin's `maxWidth` option (so generated responsive images are 0.25x, 0.5x, 1x, 2x, 3x of 500px), and also styles the image wrapper class to `max-width: 500px` so it's displayed at that size.

I'm currently using this with `mdx`, but it can be used anywhere `gatsby-remark-images` is used. 
`gatsby-config`:
```js
    {
      resolve: 'gatsby-plugin-mdx',
      options: {
        extensions: ['.mdx', '.md'],
        plugins: [
          '@bonobolabs/gatsby-remark-images-custom-widths',
        ],
        gatsbyRemarkPlugins: [
          {
            resolve: '@bonobolabs/gatsby-remark-images-custom-widths',
            options: {
              maxWidth: 740,
              linkImagesToOriginal: false,
              quality: 80,
            }
          },
          ...
```

(I went with a `width` attribute in HTML as a first version since it's an existing spec, will render nicely in Github, and is supported by MDX/etc. This is also easier than agreeing on which syntax to use from all the different flavours of markdown, and ensuring that the markdown renderer will parse this consistently etc).

### Motivation

At the moment, markdown images are always displayed at the full width of the page. This is a pretty simple change that adds support for images to be displayed at a custom width - e.g. for portrait orientation images, image galleries, or even just displaying two images side by side:

```md
<div class="side-by-side">
<img src="image1.png" alt="Image one" width="300px"/>
<img src="image2.png" alt="Image two" width="300px"/>
</div>
```

```css
.side-by-side: {
    display: flex;
    justify-content: space-evenly;
}
.side-by-side > span {
   flex: 1;
}
```

#### Alternatives

I think another way to achieve this would be with a custom image component (MDX/remark-component/etc), but I think that'd be quite difficult to implement (e.g. given that there's no support for dynamic graphql queries), wouldn't be as well supported by other plugins/sources, and adds a fair bit of complexity (a second way of processing/resizing/caching images).

**Comment by alexlouden** [comment]
Let me know if you think this would be a useful change and I'll make it into a proper PR :)

**Comment by LekoArts** [comment]
For my taste this is a bit too much magic and not really straightforward for other people to figure out. Take this as an example:

Theme A/Starter A uses this plugin, the end user doesn't know that it's in there and wants to use the `<img />` tag instead of `![]()` - but the person will then be surprised that it doesn't behave like expected.

You can also read previous discussions here: https://github.com/gatsbyjs/gatsby/issues/2609

I'd prefer syntax like that.

**Comment by henrikwirth** [comment]
I believe this implementation is more than valid. Surely it would be nice to have a `![alt](src){attributes}` syntax too, but as that is not a standard it would mess around with markdown that people write for different systems. 

The `<img />` approach instead is basic html and will be interpreted just fine in most cases. The magic from width to maxWidth is only hapening because of gatsby-image's wrapper that needs to be sized down. If gatsby-image is not in place, most other markdown parsers will just render the image with the given width.

I'd be very happy, if that makes it into the main plugin.

**Comment by zaeyeon** [comment]
Thank you!!

**Comment by lookdeceline** [comment]
This sounds amazing! Definitely need it !

**Comment by musicbyjing** [comment]
Absolutely!

**Comment by suhasdara** [comment]
I would like this. Really hard to work around it, if anyone knows how to make dynamic maxWidth possible, please let me know

**Comment by NiallLDY** [comment]
Is there any solution here at present? How to specify the size of the picture in markdown?

**Comment by ejscribner** [comment]
+1 wondering if theres a solution to this?

**Comment by simplenotezy** [comment]
@henrikwirth you could also consider adding [support for width like Mou or Marked 2 does it](https://stackoverflow.com/a/21242579/2118665)

**Comment by andrewd72** [comment]
I'm stuggling with this also.
There are a few things I can do easily with the Hugo version of my photo blog - one is to be very exact about the sizes of images with two side by side. 
If a couple of images are 4 times too big it isn't so bad but if there are 20 side by side images in between full width images, the performance hit is significant.
