### ISSUE TITLE
Page not reinitialized when going back to it

### ISSUE THREAD

**Issue by adamjw3** [gatsbyjs/gatsby#19430]
I'm using a plugin on the homepage that works fine when the site loads or you link direct to the page. 

if you go to https://pup.adamwright90.now.sh/, then click "about" in navigation, Then click "all" in navigation. The JS doesn't seem to get reinitialized.

i'm guessing its cause its a react app and is just one page and routing to make it appear like pages.

Anyone come across this?

**Comment by adamjw3** [comment]
Anyone?

**Comment by LekoArts** [comment]
Hi!

Please follow our issue template as we otherwise can't really help you. Thanks!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by adamjw3** [comment]
Going to close this, was me using useeffect hook and not doing it right. Thanks
