### ISSUE TITLE
Client-side script compilation for static site (no react)

### ISSUE THREAD

**Issue by leo-ar** [gatsbyjs/gatsby#19478]
## Summary
- I'm building a static site which does not include react once compiled.
- I'd like to add some javascript on a per page basis (not a single global bundle).
- The scripts are written as ES6 and compiled to ES5.
- I can accomplish this by running a parallel watcher that outputs to the static folder, but I'd rather integrate it to gatsby's build process if possible.
- What approach do you recommend?

## Relevant information
- React is removed using [gatsby-plugin-no-javascript](https://www.npmjs.com/package/gatsby-plugin-no-javascript)

## Why use gatsby without react?
- The site's basic functionality needs to work even without JS.
- JS is used to progressively enhance the (simple) functionality, but is not required.
- React is popular and it works well as a server side templating engine.
- Gatsby's ecosystem is productive
- Gatsby provides a documented structure for the project

**Comment by LekoArts** [comment]
Thank you for opening this!

Since we believe Gatsby sites are better and more powerful with React included, we currently have no interest in further pursuing features in the direction you're mentioning, e.g. integrating things into the build process. You'd need to handle that on your own but it seems you got something working!

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
