### ISSUE TITLE
Using github action to send organization invitations

### ISSUE THREAD

**Issue by lekterable** [gatsbyjs/gatsby#19574]
## Summary

I'm not sure what's the current solution for inviting contributors to Gatsby's github organization and posting a comment on merge, but I wrote an open source [github action](https://github.com/lekterable/inclusive-organization-action) which is serving the exact same purpose in [styled-components](https://github.com/styled-components/styled-components/issues/2836) repo and was wondering if you would like to use it instead of an app/hook or whatever it is.

### Basic example

The only needed changes would be adding a `secret` to the gatsby repo with the gatsbybot's account personal access token as a value, and configuring the action in the workflow as in those PR's: 
https://github.com/styled-components/styled-components/pull/2867 
https://github.com/styled-components/styled-components/pull/2868

### Motivation

Using the open-sourced action would probably be easier to maintain and fix if needed, and regarding the features, I think that my repo is able to perfectly mimic the current flow, It can add a contributor to the specified team in the given organization, and can add a multiline comment using a provided personal access token.

**Comment by LekoArts** [comment]
Hi, thanks for bringing this up!

Unfortunately some of our tests with GitHub actions on our repository have shown that using GitHub actions that use personal access tokens are not safe. Anyone who has access to the (Gatsby) org can get access to the secrets.

Hence we're currently not interested in switching to actions.

**Comment by lekterable** [comment]
Could you elaborate @LekoArts ? Is this a matter of permissions in the organization? I have access to the styled-components org and I cannot access the repo secrets 🤔

**Comment by lekterable** [comment]
not trying to be rude or anything with reopening, just wanted to get more info about it as I wouldn't want to use it if it truly is unsafe, let me know if thats okay @LekoArts

**Comment by lannonbr** [comment]
@lekterable So I've been helping out in this space and at the current moment, anyone in a GitHub Organization can create branches on the main repo, and with that, you could make a PR that pulls a secret down into a new workflow and then runs a command to send that secret off to a third party. when they open this PR, given it is in the main repo, it will pull down said secrets.

There is no permission system yet that blocks individuals from accessing these tokens yet, so due to this hole and how Gatsby and Styled-Components allow anyone in with a low barrier to entry, it is a bit of a barrier for the types of actions we can run.

In the future if they do add more permissions to resolve this issue, I could see us building this in, but for now it would be a security risk to add something like this.

(As an aside, I would recommend bringing this info the styled components team as well)

**Comment by LekoArts** [comment]
@lekterable We don't intend to publicly share this here as otherwise people can use that to e.g. steal the secrets on the styled-components repo now. @pieh has told me that he wrote you in private on Discord, haven't you seen that? 🤔

**Comment by lekterable** [comment]
@LekoArts my bad, I was using just my mobile for a couple of days and I didn't check discord, thanks guys for your help, I'll reach you out there if needed!
