### ISSUE TITLE
Compatibility gatsby-remark-embed-markdown <=> gatsby-remark-prismjs

### ISSUE THREAD

**Issue by Energizz** [gatsbyjs/gatsby#19585]
## Description

Hello, I'm using gatsby with prismjs and embed markdown in order to split some long markdown files in multiple smaller one. 
It works perfectly but there is no syntax highlighting from primjs when the code is put in split markdown. (The syntax highlight works in the main markdown but not when I try to include a mardown)

### Steps to reproduce

- Create small new project
- Add gatsby-remark-prismjs
- Add gatsby-remark-embed-markdown
- Create a main md file
- Create one other md file
- Include the second one inside the first one 
`markdown:/path_to_md_file.md`

### Expected result

The syntax highlighting should work even if it's split in different md files (include)

### Actual result

There is no syntax highlighting, the code stay grey.

### Environment

  System:
    OS: macOS 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.11.2 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 78.0.3904.97
    Firefox: 69.0.3
    Safari: 13.0.3
  npmPackages:
    gatsby: ^2.3.34 => 2.17.15 
    gatsby-image: ^2.0.41 => 2.2.33 
    gatsby-plugin-algolia: ^0.4.0 => 0.4.0 
    gatsby-plugin-exclude: ^1.0.0 => 1.0.2 
    gatsby-plugin-google-analytics: ^2.1.25 => 2.1.27 
    gatsby-plugin-iubenda-cookie-footer: ^1.1.1 => 1.1.1 
    gatsby-plugin-manifest: ^2.0.29 => 2.2.28 
    gatsby-plugin-offline: ^2.0.25 => 2.2.10 
    gatsby-plugin-react-helmet: ^3.0.12 => 3.1.15 
    gatsby-plugin-sharp: ^2.2.32 => 2.3.1 
    gatsby-remark-autolink-headers: ^2.1.4 => 2.1.18 
    gatsby-remark-component: ^1.1.3 => 1.1.3 
    gatsby-remark-component-parent2div: ^1.2.3 => 1.2.3 
    gatsby-remark-custom-blocks: ^2.1.15 => 2.1.18 
    gatsby-remark-embed-markdown: 0.0.4 => 0.0.4 
    gatsby-remark-embed-snippet: ^4.1.15 => 4.1.15 
    gatsby-remark-images: ^3.1.28 => 3.1.31 
    gatsby-remark-prismjs: ^3.3.6 => 3.3.23 
    gatsby-source-filesystem: ^2.0.33 => 2.1.37 
    gatsby-source-wordpress: ^3.1.16 => 3.1.48 
    gatsby-transformer-remark: ^2.6.32 => 2.6.36 
    gatsby-transformer-sharp: ^2.1.18 => 2.3.5 
  npmGlobalPackages:
    gatsby-cli: 2.7.31

Thanks a lot ! :)

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

> Add gatsby-remark-prismjs
Add gatsby-remark-embed-markdown

Especially about that part. The order of remark plugins in gatsby-config.js does matter.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction
