### ISSUE TITLE
husky fails to install when using `gatsby new <starterUrl>`

### ISSUE THREAD

**Issue by selrond** [gatsbyjs/gatsby#19589]
## Description

When using `gatsby new <starterUrl>`, where starter uses `husky` (to be used together with `lint-staged`), husky fails to install complaining:

```sh
husky > Setting up git hooks
Command failed: git rev-parse --show-toplevel --git-common-dir
fatal: not a git repository (or any of the parent directories): .git
husky > Failed to install
```

I have a suspicion, that while `gatsby new` [changes node process directory to install starter's packages](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-cli/src/init-starter.js#L105), `$GIT_DIR` points to some different directory.  

### Steps to reproduce

run `gatsby new my-project https://github.com/selrond/gatsby-starter-essentials` and watch the console for the above mentioned error

### Expected result

husky should install normally

### Actual result

husky failed to install

### Environment

```sh
  System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
    npm: 6.12.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
  Languages:
    Python: 2.7.17 - /usr/local/bin/python
  Browsers:
    Chrome: 78.0.3904.97
    Firefox: 70.0
    Safari: 13.0.3
```

**Comment by selrond** [comment]
This confirms my suspicion: https://stackoverflow.com/questions/34886198/do-hooks-run-in-the-git-directory-or-the-hooks-directory#comment57512051_34886198

**Comment by TylerBarnes** [comment]
@selrond `gatsby new` clones the git repo of the starter and then deletes the .git directory since the git repo connected to the starter is the starter repo, but the developer running the command will want to have their own git repo. See https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-cli/src/init-starter.js#L177
For that reason, I don't believe we'll be able to make this work and this feature would be outside the scope of `gatsby new`.
