### ISSUE TITLE
(node:4770) [DEP0130] DeprecationWarning

### ISSUE THREAD

**Issue by t2ca** [gatsbyjs/gatsby#19604]
Getting the following error since upgrading node to v13.1.0

```
success load plugins - 1.937s

 ERROR

(node:4770) [DEP0130] DeprecationWarning: Module.createRequireFromPath() is deprecated. Use Module.createRequire() instead.
```

**Comment by LekoArts** [comment]
Hi!
Please follow our issue template in the future so that we can help you better.

We still support Node 8 and hence some of our dependencies might use deprecated APIs. Similar issue: https://github.com/gatsbyjs/gatsby/issues/18433#issuecomment-545040822

Depending on your stack it might or might not be possible right now to update.

**Comment by LekoArts** [comment]
Duplicate of https://github.com/gatsbyjs/gatsby/issues/19634
