### ISSUE TITLE
Gatsby Contentful reference blocks issue

### ISSUE THREAD

**Issue by Sanj718** [gatsbyjs/gatsby#19619]
## Summary
On Gatsby I made a graphQL request and calling for a Reference Blocks from Contentful.
On Contentful if I have this field but not filled yet, It does not receive such content type in gatsby graphQL and it is causing a problem on build. 

I tried to fix this problem with predefined sourceNodes in gatsby-node.js however, it was unsuccessful. 

Please help to find solution for this issue or alternative method. 

Thanks

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by Sanj718** [comment]
Hello, thank you. 

Here is test repo. Now it will show an error as (since i've removed component TextBlock in the Reference block in Contentful):

` 169:17  error  Fragment cannot be spread here as objects of type "ContentfulBannerContentfulBottomCtaContentfulLogoListContentfulMediaTextContentfulOurServicesContentfulOurWorkContentfulTextImageUnion" can never be of type "ContentfulTextBlock"  graphql/template-strings`

REPO : 
https://github.com/Sanj718/gatsbytest.git
