### ISSUE TITLE
[Safari] After refresh scroll position is not restored.

### ISSUE THREAD

**Issue by rroslaniec** [gatsbyjs/gatsby#19632]
## Description
Right now (even on gatsby.org) gatsby is not restoring scroll position after refresh.
Bug appears only in Safari
### Steps to reproduce

1. open Safari
2. goto https://www.gatsbyjs.org/
3. scroll to the bottom of the page
4. refresh page
5. page is scrolled to the top

### Expected result

1. open Safari
2. goto https://www.gatsbyjs.org/
3. scroll to the bottom of the page
4. refresh page
5. browser should be scrolled to the bottom

### Environment

Safari 13.0.3

I was digging into that problem and I realize gatsby did not even tries to restore position. **Maybe** it is because in scroll-behavior library scrollRestoration is set to "manual".

Everything is in sessionStorage so I've prepared "little" hack for that but it should be natively supported.

Hack:
```ts
//Key for inital view - taken from sessionStorage
const SCROLL_INITIAL_CACHE_KEY = "@@scroll|initial";

export const onInitialClientRender = () => {
  if ("sessionStorage" in window && window.sessionStorage.getItem(SCROLL_INITIAL_CACHE_KEY)) {
    const scrollPosition = window.sessionStorage.getItem(SCROLL_INITIAL_CACHE_KEY) || "[0,0]";
    window.scrollTo(...JSON.parse(scrollPosition));
  }
};
```

There is tons of dependencies and actually I'am not able to prepare good PR for that case.

**Comment by marceloschreiber** [comment]
Am I wrong in assuming this is the correct behavior? See https://github.com/gatsbyjs/gatsby/pull/11224

**Comment by rroslaniec** [comment]
@marceloschreiber I think it is not correct behavior because in Safari on normal static pages I got restored scroll position after refresh.

**Comment by sidharthachatterjee** [comment]
Gatsby doesn't restore scroll positions explicitly anymore since https://github.com/gatsbyjs/gatsby/pull/11224. Before the PR, there was janky behaviour where a site would load, get hydrated with JavaScript and then scroll to the top because Gatsby included code to do that. 

The PR removed this to _fix_ this behaviour and we now rely on the browser's default `scrollRestoration` behaviour where the browser _should_ restore position back for you correctly. 

The `scroll-behavior` if I recall correctly was also fixed to update `scrollRestoration` to `auto`
