### ISSUE TITLE
Data queried with useStaticQuery disappears on build after load

### ISSUE THREAD

**Issue by JuhG** [gatsbyjs/gatsby#19638]
## Description

I have a site using Prismic as a headless CMS. Some data comes from a query in gatsby-node.js and some from using useStaticQuery in the templates. Everything works in development. But when I build with `gatsby build` all the data from useStaticQuery is empty on load. Before the loading finishes the data is there and checking the public directory, everything looks fine, but as soon `app-data.js` is loaded, everything is gone.

Here's a video of it happening slowed down: https://vimeo.com/374224949
The black background image, the button text and the logo in the header disappears.

### Steps to reproduce

Demo site: https://amazing-perlman-363986.netlify.com/

### Expected result

The data is already there in the static files, why does it go away?

### Actual result

I have no idea why would it happen. Can it be an issue with prismic? (https://github.com/birkir/gatsby-source-prismic-graphql)

### Environment

```
  System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.0.1 - ~/.nvm/versions/node/v13.0.1/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.13.0 - ~/.nvm/versions/node/v13.0.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 78.0.3904.108
    Firefox: 70.0.1
    Safari: 13.0.3
  npmPackages:
    gatsby: ^2.17.15 => 2.17.15 
    gatsby-theme-dromedar: 0.2.17 => 0.2.17 
  npmGlobalPackages:
    gatsby-cli: 2.8.12
    gatsby: 2.17.2
```

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by JuhG** [comment]
I couldn't figure it out, so I switched to the other Prismic source plugin and the issue went away. It was most likely the mentioned plugin causing it. (Possibly related to [this issue](https://github.com/birkir/gatsby-source-prismic-graphql/issues/77).)
