### ISSUE TITLE
Ink CLI logger truncates long messages

### ISSUE THREAD

**Issue by vladar** [gatsbyjs/gatsby#19658]
## Description

Some of our warnings are quite long. If warning text doesn't fit into terminal window width, `ink` will wrap the text. But when this happens it will also truncate the last line of the text.

As a result, some warnings are truncated which causes confusion for people seeing them. Example: https://github.com/gatsbyjs/gatsby/issues/19314

This should be probably fixed upstream - https://github.com/vadimdemedes/ink/issues/245

But then we should update as soon as it's fixed. Other options to fix this are:

1. Do not use `textWrap="wrap"` for messages
2. Wrap a message text with a separate box and move `textWrap` to this box (but this will change console output a bit)

**Comment by kilburn** [comment]
Sometimes this turns into a significant issue. In my case, the "word" being truncated is precisely the path to the file I should fix. As it stands right now I cannot deal with this warning because I don't know how to locate the problematic file!

![image](https://user-images.githubusercontent.com/116100/76747133-f4dbbf80-6778-11ea-9865-2b7c6e156a4d.png)

**Comment by vladar** [comment]
Should be fixed in ink v3: https://vadimdemedes.com/posts/ink-3 Keeping this open until we switch to v3 in `gatsby-cli`
