### ISSUE TITLE
Gatsby Build "allfile" nodes not generated but work correctly when using gatsby develop

### ISSUE THREAD

**Issue by ArcaneTSGK** [gatsbyjs/gatsby#19659]
## Description

When using the gatsby build command, the static HTML files are missing multiple Gatsby Image components, however when using gatsby develop all Gatsby Image components are rendered correctly.

It should be noted that the following process is being performed to render the image

The images are downloaded remotely from our CMS server using the following code

gatsby-node.js

```
exports.createResolvers = (
	{
		actions,
		cache,
		createNodeId,
		createResolvers,
		store,
		reporter,
	},
) => {
	const { createNode } = actions;
	console.warn('Create Resolvers');
	createResolvers({
		GraphQLSource_CmsImage: {
			imageFile: {
				type: 'File',
				resolve: (source, args, context, info) => {
					return createRemoteFileNode({
						url: source.absolutePath,
						store,
						cache,
						createNode,
						createNodeId,
						reporter,
					})
				},
			},
		},
	})
};
```

During both develop and build, the output shows that remote media files were downloaded

It is then after this point that it only appears to generate image thumbnails for gatsby develop, image thumbnails are not being generated for gatsby build, here is the code we are using for gatsby image

```
import * as React from 'react';
import Img from 'gatsby-image';
import { graphql, StaticQuery } from 'gatsby';

interface IImageProps {
	imgName: string;
	alt: string;
}

const ImageHandler = ({ imgName, alt }: IImageProps) => {
	return (
		<StaticQuery
			query={graphql`
				query {
					images: allFile {
						edges {
							node {
								relativePath
								name
								childImageSharp {
									fluid(maxWidth: 2000) {
										...GatsbyImageSharpFluid
									}
								}
							}
						}
					}
				}
			`}
			render={(data) => {
				const image = data.images.edges.find((n: { node: { name: string } }) => {
					return n.node.name === imgName;
				});

				if (!image) {
					return null;
				}

				if (image.node.childImageSharp == null) {
					return <img src={image.node.absolutePath} alt={alt} />;
				}

				const fluid = image.node.childImageSharp.fluid;
				return <Img alt={alt} fluid={fluid} />;
			}}
		/>
	);
};

export default ImageHandler;
```

An example snippet of a page query where we are passing the data returned to a child component which subsequently is passed to the ImageHandler component

```
smallMarketingTile {
							altTag
							image {
								absolutePath
								fileName
								imageFile {
									publicURL
								}
							}
							link
						}
```

### Expected result

gatsby build should render the gatsby image components in the same manner as gatsby develop

### Actual result

gatsby build does not render the gatsby image component

### Environment

  System:
    OS: Windows 10
  Binaries:
    npm: 6.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.1.0 => 2.3.35 
    gatsby-image: ^2.0.20 => 2.0.41 
    gatsby-plugin-emotion: ^3.0.0 => 3.0.1 
    gatsby-plugin-favicon: ^3.1.6 => 3.1.6 
    gatsby-plugin-google-fonts: 0.0.4 => 0.0.4 
    gatsby-plugin-html-attributes: ^1.0.5 => 1.0.5 
    gatsby-plugin-json-output: ^1.1.0 => 1.1.0 
    gatsby-plugin-manifest: ^2.0.9 => 2.0.29 
    gatsby-plugin-react-helmet: ^3.0.2 => 3.0.12 
    gatsby-plugin-recaptcha: ^1.0.5 => 1.0.5 
    gatsby-plugin-remove-serviceworker: ^1.0.0 => 1.0.0 
    gatsby-plugin-robots-txt: ^1.5.0 => 1.5.0 
    gatsby-plugin-sharp: ^2.0.12 => 2.0.35 
    gatsby-plugin-sitemap: ^2.1.0 => 2.1.0 
    gatsby-plugin-typescript: ^2.0.2 => 2.0.13 
    gatsby-source-filesystem: ^2.0.33 => 2.0.33 
    gatsby-source-graphql: ^2.0.11 => 2.0.18 
    gatsby-transformer-json: ^2.1.11 => 2.1.11 
    gatsby-transformer-remark: ^2.1.15 => 2.3.12 
    gatsby-transformer-sharp: ^2.1.8 => 2.1.18

**Comment by lordoffreaks** [comment]
same issue here

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by lordoffreaks** [comment]
Hi @LekoArts !

Thanks for that, the site is (not) deployed due to the mentioned error in https://github-issue-19659.netlify.com/ linked to the repo https://github.com/lordoffreaks/gatsby-starter-hello-world 

It fails with

```11:24:40 AM: - Unknown field 'coverImage' on type 'Vimeo____video!'.```

when trying to read it from https://github.com/lordoffreaks/gatsby-starter-hello-world/blob/master/src/pages/index.js#L28 

Thanks in advance

**Comment by lordoffreaks** [comment]
@LekoArts I've added github actions to it so you can see the build failing in https://github.com/lordoffreaks/gatsby-starter-hello-world/commit/1821187786be62261ddc980f76745707e9405590/checks?check_suite_id=330953893

**Comment by LekoArts** [comment]
Your issue seems unrelated to the problem that the author of this issue described. You probably have an error in your code regarding the downloading. Hence the error message you're seeing.

You can read more here on how to do it:
https://www.gatsbyjs.org/docs/schema-customization/#feeding-remote-images-into-gatsby-image
https://www.gatsbyjs.org/docs/preprocessing-external-images/

**Comment by lordoffreaks** [comment]
@LekoArts FYI the issue was fixed as part of https://github.com/gatsbyjs/gatsby/issues/19716 by this PR https://github.com/gatsbyjs/gatsby/pull/19781

**Comment by vladar** [comment]
This should be working again in `gatsby 2.18.5`. But please also check #19876 for the follow up.
