### ISSUE TITLE
Gatsby inside React application

### ISSUE THREAD

**Issue by KoushikGoramane** [gatsbyjs/gatsby#19682]
I created the React application and inside src folder of React application i created Gatsby. How to import gatsby components in the parent react application and also how to import parent react component inside the Gatsby component?

**Comment by maecapozzi** [comment]
Hey @KoushikGoramane, I'd love to better understand what you mean when y ou say you "created Gatsby" inside the "src folder of a React application". If you're starting a new Gatsby project, you'll want to follow these steps: https://www.gatsbyjs.org/docs/quick-start

**Comment by sidharthachatterjee** [comment]
@KoushikGoramane If I understand correctly, you mean that you have two separate apps and you'd like to reuse components between them?

Gatsby apps _are_ React apps so should be able to import any React component in your Gatsby app and use it. 

The other way around does _not_ work though in case you use queries in Gatsby. Since a plain React app won't know how to run them without Gatsby. 

Hope this helps! Please elaborate when you have a moment. Would love to help 🙂

**Comment by muescha** [comment]
FYI: 
there is guide: https://www.gatsbyjs.org/docs/porting-from-create-react-app-to-gatsby/

**Comment by LekoArts** [comment]
Thank you for opening this!

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
