### ISSUE TITLE
Shopify and users

### ISSUE THREAD

**Issue by turbiarz** [gatsbyjs/gatsby#19696]
I would like to build custom shop with shopify and gatsby, but I would like to have user's to login and check some information about last order ect. (like in norml shopify store), is any way to do it with GatsbyJS?

**Comment by Yofamb** [comment]
I'd imagine you would need to fetch the orders from the Admin API once a user has logged in. I think you would want to do this client side and not build the pages. https://help.shopify.com/en/api/reference/customers/customer#orders-2019-10

**Comment by turbiarz** [comment]
@Yofamb what about creating new user?

**Comment by angeloashmore** [comment]
@turbiarz Admin API is probably not what you’re looking for. Check out Shopify’s GraphQL Storefront API.

**Comment by LekoArts** [comment]
Thank you for opening this!

Since this question is not related to a bug or feature request I can only forward you to e.g. our own shop that runs Shopify: https://github.com/gatsbyjs/store.gatsbyjs.org

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
