### ISSUE TITLE
Art Direction with Gatsby Image has strange behavior

### ISSUE THREAD

**Issue by danboyle8637** [gatsbyjs/gatsby#19702]
## Summary

I am trying to use art-direction with Gatsby Image but for my mobile, tablet, and ipadPro images... they are not using their entire height... only the height of the content that overlays them.

See below...

## Relevant information

I'm using Styled Components.

Here is my sources array: 
```
const sources = [
    {
      ...laptopBackground,
      media: `(min-width: 1100px)`,
    },
    {
      ...ipadProBackground,
      media: `(min-width: 960px)`,
    },
    {
      ...tabletBackground,
      media: `(min-width: 600px)`,
    },
    mobileBackground,
  ];
```

I am using fluid images and just like the docs say... I am passing sources to the fluid prop in Gatsby Image.

My query for the image uses maxWidth, maxHeight, and quality. Nothing else.

I have content over my images using CSS Grid so they overlap using the same grid column and row. But the image's height is only as big as the content that overlays it... when you think it should be the height of the image.

Any ideas? 

This works in a normal React environment using Styled Components.

The image should extend to the bottom of the screen... it's 1300 pixels tall.

![Screen Shot 2019-11-21 at 3 09 18 PM](https://user-images.githubusercontent.com/26289514/69373043-ed942180-0c70-11ea-8dd6-93b542bfa3ea.png)

**Comment by danboyle8637** [comment]
I found what seems to be a rouge div in my DOM tree with nothing in it, but styling and a padding-bottom that seems to be messing with everything. 

![Screen Shot 2019-11-21 at 4 02 18 PM](https://user-images.githubusercontent.com/26289514/69376552-782c4f00-0c78-11ea-8f7a-6bd76b44cc3b.png)

**Comment by polarathene** [comment]
> rouge div in my DOM tree with nothing in it, but styling and a padding-bottom that seems to be messing with everything.

That's to enforce the aspect ratio iirc, which is a feature of fluid images afaik(I haven't used Gatsby or worked with the `gatsby-image` code in a while). The issue should be reproducible without multiple sources for Art Direction?

If the issue is only from different images(with different aspect ratios), then the problem is likely due to the Art Direction feature. IIRC, the code defaults to the 1st images aspect ratio:

https://github.com/gatsbyjs/gatsby/blob/0da6dbba7d311d44442dc7ecce507ff35c0b9b0c/packages/gatsby-image/src/index.js#L436

The remaining issues `gatsby-image` has to address for Art Direction are identified [here](https://github.com/gatsbyjs/gatsby/pull/13395#issuecomment-493640397).
