### ISSUE TITLE
Is it possible to opt out of generating page-data.json for AMP pages?

### ISSUE THREAD

**Issue by asilgag** [gatsbyjs/gatsby#19718]
I have a use case where we are using Gatsby to generate 10,000 HTML pages, and another 10,000 AMP pages, both at the same time, on the same building process.

Both page types, HTML and AMP, are built and their corresponding page-data.json files are generated. I would like to opt out from generating 10,000 page-data.json file for AMP, because theiy are not used at all (and they slow down the building process).

Is there any way to achieve that? I'm not using gatsby-plugin-amp, but instead using a different template for AMP pages.

**Comment by sidharthachatterjee** [comment]
Thank you for opening this @asilgag 

> I would like to opt out from generating 10,000 page-data.json file for AMP, because theiy are not used at all (and they slow down the building process).

This isn't possible at the moment since the Gatsby runtime expects those files and uses them upon hydration. 

Using `gatsby-plugin-amp` will remove JavaScript assets etc but these files will still be generated irrespective. 

> I have a use case where we are using Gatsby to generate 10,000 HTML pages, and another 10,000 AMP pages, both at the same time, on the same building process.

On a separate note, would you like to help us scale up Gatsby performance? We're looking for real world sites with lots of pages. If you're interested in sharing your site, please take a look at https://github.com/gatsbyjs/gatsby/issues/19512

Marking this as answered and closing this since there isn't any immediate step that we can take here. 

Thanks!
