### ISSUE TITLE
Error: The result of this StaticQuery could not be fetched.

### ISSUE THREAD

**Issue by siccoo** [gatsbyjs/gatsby#19797]
## Description

Describe the issue that you're seeing.

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

How to Make a Minimal Reproduction: https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/

### Expected result

What should happen?

### Actual result

What happened.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

### Description 
I changed the StaticQuery of gatsby-config.js and it threw an error: There was an error in your GraphQL query:

- Unknown field 'author' on type 'SiteSiteMetadata'. So I changed back to the default and it was successful on the terminal but displayed an error of the result of this static query could not be fetched. How do I go about it? Thank you

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction
