### ISSUE TITLE
Custom environment vars overwritten when running netlify dev

### ISSUE THREAD

**Issue by kmcaloon** [gatsbyjs/gatsby#19845]
Not sure if this should be posted on Gatsby's end or Netlify's. I have a custom environment set up as per https://www.gatsbyjs.org/docs/environment-variables/#additional-environments-staging-test-etc.  

My custom dev command is `ACTIVE_ENV=netlifyDev netlify dev`.

In `gatsby-node.js` I have the following:

```
const activeEnv = process.env.ACTIVE_ENV || process.env.NODE_ENV || 'development';
require( 'dotenv' ).config( {
  path: `.env.${activeEnv}`,
} );
console.log( '========== Running in environment:', activeEnv ); // This outputs correctly
```

When I check the console during build, I am seeing `netlifyDev`. So far so good. In the frontend if I check any `process.env` variables found _**only**_ in my `.env.netlifyDev` file, all is well. But if I have any variables found in _**both**_ `.env.netlifyDev` and `.env.development`, the latter seems to be overriding the former. `gatsby-node.js` only always logs `netlifyDev` as the active environment. I don't have any of these environment variables in the Netlify UI or .toml. I just don't know where the main development variables are coming from.

Could this be an issue with Gatsby itself if `.env.development` and a custom env share the same variables?

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction
