### ISSUE TITLE
Very slow build and develop times, even with no extra pages created.

### ISSUE THREAD

**Issue by dante-blitz** [gatsbyjs/gatsby#19897]
## Summary

I'm trying to get some detailed insight as to how the build process works in relation to slow build times, due to large amounts of content in DatoCMS. This happens even when gatsby does not create any pages from that content.

## Relevant information

A few details about our use case...

- We are using gatsby with DatoCMS and the gatsy-source-datocms plugin.
- All packages are up to date.
- In DatoCMS we have over 26,000 news items, which are basically a headline, external url and tags (references to other content).
- We create landing pages in gatsby-node.js of the news items (24 per page). We do not create individual pages for each new item.

The build and develop times were fast until we imported all the news items into DatoCMS. Since everything slowed down.  The main culprits of the build process are:

```
success loading DatoCMS content - 757.070s
success source and transform nodes - 761.229s
```

Its worth noting that sometimes the above times is significantly less:

```
5:43:51 PM: success loading DatoCMS content — 95.863
5:44:18 PM: success source and transform nodes — 122.330
```

This happens randomly and infrequently. I assuming the faster times are due to caching.

As I test, I started a fresh gatsby project, added the gatsby-source-datocms plugin and connected the plugin to our cms instance. I have not created any additional pages. The result is the same.

I then read the [Schema Customisation docs](https://www.gatsbyjs.org/docs/schema-customization/) and attempted to opt the new items out of inference by creating type definitions with @dontInfer. This doesn't appear to work.

The main questions I have are:

- Am I right in thinking that, with correctly set custom schema type definitions, the build process should not scan the 26,000+ new items and hence the build times will significantly improve?
- Could the gatsby-source-datocms plugin somehow by overriding the @dontInfer type directive?
- Is there a way to verify that the @dontInfer directive is having an effect?
- Any ideas as to why the build times are randomly (and infrequently) faster?
- Is there anything else that I may be able to try to avoid the excessive build times, given our use case?

Any help is highly appreciated.

**Comment by freiksenet** [comment]
This isn't slow because of schema inference - it's just slow to load 26000 items from DatoCMS. DatoCMS plugin already does schema customization for you, so you wouldn't get any more speed up in this case. 

Possible ways to improve it would be not loading all this data or storing the cached data on the disk. This all requires changes to datocms plugin. Unfortunately, we aren't maintaining the datocms plugin, it's maintained by Dato themselves (https://github.com/datocms/gatsby-source-datocms/issues). Therefore I think you should file an issue in their repo. Feel free to point to this issue!

I'll be closing this issue for now.
