### ISSUE TITLE
Error in Netlify CMS: ___loader is not defined

### ISSUE THREAD

**Issue by alexeychikk** [gatsbyjs/gatsby#19898]
## Description

I'm using `gatsby-plugin-netlify-cms` and `gatsby-plugin-netlify`. When I open a preview in CMS the following error shows up and the preview is not interactive anymore.
```
index.js:131 Uncaught ReferenceError: ___loader is not defined
    at index.js:131
    at index.js:58
    at Array.forEach (<anonymous>)
    at IntersectionObserver.<anonymous> (index.js:51)
```
This error occurs in `gatsby-link` package.

### Steps to reproduce

Just open any preview that has `gatsby-link`.

### Expected result

No errors.

### Actual result

Error occurs. Preview becomes non-interactive.

### Environment

  System:
    OS: Linux 5.0 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 10.14.2 - ~/.nvm/versions/node/v10.14.2/bin/node
    npm: 6.9.2 - ~/.nvm/versions/node/v10.14.2/bin/npm
  Languages:
    Python: 2.7.15+ - /usr/bin/python
  Browsers:
    Chrome: 78.0.3904.108
    Firefox: 70.0.1
  npmPackages:
    gatsby: ^2.13.13 => 2.13.52 
    gatsby-image: ^2.2.4 => 2.2.8 
    gatsby-plugin-canonical-urls: ^2.1.0 => 2.1.2 
    gatsby-plugin-catch-links: ^2.1.0 => 2.1.2 
    gatsby-plugin-material-ui: ^2.1.4 => 2.1.5 
    gatsby-plugin-netlify: ^2.1.25 => 2.1.25 
    gatsby-plugin-netlify-cms: ^4.1.28 => 4.1.28 
    gatsby-plugin-react-helmet: ^3.1.0 => 3.1.3 
    gatsby-plugin-sharp: ^2.2.3 => 2.2.10 
    gatsby-plugin-smoothscroll: ^1.0.3 => 1.0.3 
    gatsby-plugin-typescript: ^2.1.0 => 2.1.2 
    gatsby-remark-copy-linked-files: ^2.1.0 => 2.1.4 
    gatsby-remark-images: ^3.1.3 => 3.1.7 
    gatsby-remark-prismjs: ^3.3.1 => 3.3.4 
    gatsby-remark-relative-images: ^0.2.2 => 0.2.3 
    gatsby-remark-responsive-iframe: ^2.2.1 => 2.2.4 
    gatsby-remark-smartypants: ^2.1.0 => 2.1.2 
    gatsby-source-filesystem: ^2.1.3 => 2.1.9 
    gatsby-transformer-json: ^2.2.0 => 2.2.2 
    gatsby-transformer-remark: ^2.6.2 => 2.6.11 
    gatsby-transformer-sharp: ^2.2.1 => 2.2.5

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by duranmla** [comment]
Any luck with this @alexeychikk ?
I am running a project based upon the netlify base with gatsby. But I have made a lot of changes already and not sure at which point I break the functionality

**Comment by ramonmostert** [comment]
Same problem here, I think this has something to do with prefetching of links?
Some gatsby global functions seem not to be available in Netlify CMS preview

**Comment by wardpeet** [comment]
I'm assigning @erezrokah to these issues as he is going to work on it from the netlify side. At least that's what I'm told

**Comment by erezrokah** [comment]
@wardpeet for assigning me, looking into it

**Comment by erezrokah** [comment]
> Same problem here, I think this has something to do with prefetching of links?
> Some gatsby global functions seem not to be available in Netlify CMS preview

You are correct. Gasby sets some global variables on the window to be used by plugins:
https://github.com/gatsbyjs/gatsby/blob/deb41cdfefbefe0c170b5dd7c10a19ba2b338f6e/docs/docs/production-app.md#window-variables
https://github.com/gatsbyjs/gatsby/blob/deb41cdfefbefe0c170b5dd7c10a19ba2b338f6e/packages/gatsby/cache-dir/production-app.js#L28

Since this happens in gatsby's core and not as a plugin the CMS plugin can't recreate it.
I'm currently thinking of just stubbing these objects.
As a workaround until a fix is merge you can add the following to your `cms.js` file

```js
window.___loader = { enqueue: () => {}, hovering: () => {} }
```

**Comment by ramonmostert** [comment]
@erezrokah This would work. There's no need for prefetching in preview. Although it might feel as a workaround it won't interfere with the functionality of the CMS or Gatsby.
