### ISSUE TITLE
Weird undefined error while building

### ISSUE THREAD

**Issue by atiyahio** [gatsbyjs/gatsby#19901]
I get this weird undefined error with no message whenever I try to build the website and there's no actual reason to know what's wrong for me.

everything builds great but one page and I can't really tell why I changed everything in it and i still get the same error!

![image](https://user-images.githubusercontent.com/47905558/69917408-58faa200-146e-11ea-9936-be0fb1b79085.png)

**Comment by atiyahio** [comment]
ok so a small update the page not being created was on contentful's side, the page now renders normally but I still get that undefined error!

**Comment by LesleyLai** [comment]
Do you have any `console.log` in `gatsby-node.js`?

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction
