### ISSUE TITLE
Gatsby-image loads WebP and Jpeg formats at same time in Swiper and Masonry

### ISSUE THREAD

**Issue by tonicastillo** [gatsbyjs/gatsby#19919]
## Description

When I use Gatsby-image in webp inside Swiper slider, it loads two formats at same time: Webp and Jpeg. This also happens using react-masonry-component.
<img width="2162" alt="image" src="https://user-images.githubusercontent.com/167335/69974931-81de6e00-1526-11ea-9bee-b2cbff4640d7.png">

### Steps to reproduce

Minimal Reproduction:
Here you can see two examples: Inside Swiper slider and without Swiper (index.js and page-2.js).
-Sandbox: https://codesandbox.io/s/gatsby-starter-default-p82ym
-Deploy: https://csb-p82ym-2lui22som.now.sh/

### Expected result

Browser only needs to load webp formats (if it compatible)

### Actual result

Loads two formats.

### Environment

gatsby: 2.18.4
gatsby-image: 2.2.34
gatsby-plugin-sharp: 2.3.4
gatsby-source-filesystem: 2.1.39
gatsby-transformer-sharp: 2.3.6
react: 16.12.0
react-dom: 16.12.0
react-id-swiper: 2.4.0
swiper: 5.2.1

Thanks!

**Comment by graysonhicks** [comment]
This is because the `swiper.bundle.esm.js` source code is doing a check for `image.src` (line 2806):

``` if (src) {
        image.src = src;
      }```

More importantly, I think this may be relevant to [this issue](https://github.com/gatsbyjs/gatsby/issues/18528) which notes that Swiper is referencing DOM nodes (it is looking for all `<img />`tags on line 2819), and not React elements, so I'm not sure it will work with `gatsby-image`.

This is an upstream library problem, and not a `gatsby-image` bug.  Ideally the carousel would allow children of any type, and not try to process images specially (it is preloading them, which is why you are seeing that network request).

**Comment by tonicastillo** [comment]
It works!
This is the fixed fork: https://codesandbox.io/s/testing-gatsby-image-with-swiper-dbkn5

Maybe Masonry does something like this.
Thank you!

**Comment by ositaka** [comment]
Hello, I am also having a big issue with this react-id-swiper, on the duplicated slides...

On your sandbox, if you add "loop: true, autoplay: true", you see that the swiper doesn't work properly on Gatsby.

Do you guys have any solution for this?

In my case I had to hide the preview image from Gatsby, which it sucks, because in the end I am building a website in Gatsby and I can't really take advantage of the gatsby-image :/
