### ISSUE TITLE
Gatsby Plugin Create client Paths

### ISSUE THREAD

**Issue by arhoy** [gatsbyjs/gatsby#20034]
In the plugin https://www.gatsbyjs.org/packages/gatsby-plugin-create-client-paths/?=create%20clien
I am not sure how to add multiple clients paths. 
For example I would like app/ and store/ to be client only paths

I have tried
```
    {
      resolve: `gatsby-plugin-create-client-paths`,
      options: { prefixes: [`/app/*`, `/store/*`] },
    },
```

And this does not work for me

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by wardpeet** [comment]
@arhoy it should work, please create a small reproduction for us that will help us debug this issue.
