### ISSUE TITLE
intl + create-client-path (gatsby-plugin)

### ISSUE THREAD

**Issue by Jamyth** [gatsbyjs/gatsby#20049]
## Summary
I would like to create E-commerce website using gatsbyJS + Express as backend,
I have a problem with multi-lang and the client-only paths.

I want to achieve something like this:
https://localhost:8000/en/products/25468

with gatsby-plugin-intl + gatsby-plugin-create-client-paths

I have something like this

-> https://localhost:8000/en/products

And the props.location.pathname only returns '/en/products'...

I tried to change the order in plugin array in gatsby.config.js like back and forth,

I have something like this too:

-> https://localhost:8000/products/25468

in which the locale function is missing.

## Relevant information

Gatsby-Plugin-intl:
https://www.gatsbyjs.org/packages/gatsby-plugin-intl/

Gatsby-Plugin-create-client-paths:
https://www.gatsbyjs.org/packages/gatsby-plugin-create-client-paths/

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction
