### ISSUE TITLE
[gatsby-source-contentful]:Error: Request failed with status code 400

### ISSUE THREAD

**Issue by sliktrik** [gatsbyjs/gatsby#20081]
I have generated a new gatsbyjs project, added gatsby-source-contentful and added the configuration to gatsby.config.js

```
{
      resolve: `gatsby-source-contentful`,
      options: {
        spaceId: process.env.CONTENTFUL_SPACE,
        accessToken: process.env.CONTENTFUL_ACCESS_TOKEN,
        host: process.env.CONTENTFUL_HOST,
      },
},
```
(at this point i have not created any pages or queries, this is a brand new project)

upon running... 
`CONTENTFUL_SPACE=<spaceid> CONTENTFUL_ACCESS_TOKEN=<access_token>
CONTENTFUL_HOST="preview.contentful.com" gatsby develop`

I receive the following error...

```
success open and validate gatsby-configs - 0.048s
success load plugins - 0.591s
success onPreInit - 0.007s
success initialize cache - 0.049s
success copy gatsby files - 0.109s
success onPreBootstrap - 0.015s
success createSchemaCustomization - 0.006s
Starting to fetch data from Contentful
Fetching default locale
default locale is : en-AU

 ERROR 

Fetching contentful data failed Request failed with status code 400

  Error: Request failed with status code 400
  
  - contentful.node.js:886 createError
    [droptest]/[contentful]/dist/contentful.node.js:886:15
  
  - contentful.node.js:1049 settle
    [droptest]/[contentful]/dist/contentful.node.js:1049:12
  
  - contentful.node.js:294 IncomingMessage.handleStreamEnd
    [droptest]/[contentful]/dist/contentful.node.js:294:11
  
  - task_queues.js:80 processTicksAndRejections
    internal/process/task_queues.js:80:21
  
not finished source and transform nodes - 6.880s
```

I can confirm both the spaceid and access_token are correct.

I have contacted contentful support and they have indicated the request size is too large however there are no GraphQL queries in the project

Has anyone come across this issue before?

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction
