### ISSUE TITLE
Disable inline style tags when using ExtractTextPlugin

### ISSUE THREAD

**Issue by kigorw** [gatsbyjs/gatsby#201]
I've built site with ExtractTextPlugin and it loads single styles.css file but along with that it adds in runtime link tags. How to disable them?

As an example the same problem on http://graphene-python.org/

![example](https://dl.dropboxusercontent.com/spa/xn10ba9vstdiy8k/e2awulbg.png)

**Comment by KyleAMathews** [comment]
Which version of gatsby are you using? Also it'd really help if you could
zip up your site and attach it here so I could reproduce the problem.

**Comment by kigorw** [comment]
I'm using 0.8.10
Here is zip (I included node_modules)
https://dl.dropboxusercontent.com/u/1332389/chromestorebot.zip

**Comment by KyleAMathews** [comment]
Ok, the problem is you need to extract styles in the `production` build not the `static` build. The `production` build is where the bundle.js is created so right now styles are still being included in that build.

These names are super confusing—which @scottnonnenberg pointed out to me already. Based on his suggestion I'm renaming soon the build step names to `build_html`, `build_css`, and `build_javascript`. This hopefully will happen on Saturday for a 0.9 release.

**Comment by kigorw** [comment]
Thanks, it works!
