### ISSUE TITLE
localhost:8000 blank page on Chrome! working on incognito and Mozilla

### ISSUE THREAD

**Issue by alesdonoso** [gatsbyjs/gatsby#20117]
## Description

localhost:8000 is not working on normal Chrome mode, but is working fine on incognito mode and Mozilla Dev version Browser.

### Steps to reproduce

1. `gatsby develop`
2. Running localhost:8000 on normal Chrome mode
3. Getting a blank_page

4. Works fine on incognito mode and Mozilla browser

### Expected result

The developement mode should appear.

### Actual result

![image](https://user-images.githubusercontent.com/48650098/70790853-2ddd5000-1d96-11ea-96b6-2bdb6ede8bdd.png)

I also can't open the inspect or the console.

### Environment

> System:
>     OS: Linux 4.4 Ubuntu 18.04.2 LTS (Bionic Beaver)
>     CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
>     Shell: 5.4.2 - /usr/bin/zsh
>   Binaries:
>     Node: 10.16.3 - /usr/local/bin/node
>     Yarn: 1.19.1 - /usr/bin/yarn
>     npm: 6.7.0 - /usr/local/bin/npm
>   Languages:
>     Python: 2.7.15+ - /usr/bin/python
>   npmPackages:
>     gatsby: ^2.7.5 => 2.7.5
>     gatsby-cli: ^2.7.47 => 2.7.47
>     gatsby-image: ^2.1.2 => 2.1.2
>     gatsby-plugin-advanced-sitemap: ^1.4.5 => 1.4.5
>     gatsby-plugin-drift: ^1.0.0 => 1.0.0
>     gatsby-plugin-google-analytics: ^2.1.23 => 2.1.23
>     gatsby-plugin-manifest: ^2.1.1 => 2.1.1
>     gatsby-plugin-offline: ^2.1.1 => 2.1.1
>     gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12
>     gatsby-plugin-sass: ^2.0.11 => 2.0.11
>     gatsby-plugin-sharp: ^2.1.2 => 2.1.2
>     gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4
>     gatsby-source-filesystem: ^2.0.37 => 2.0.37
>     gatsby-theme-stripe-checkout-button: ^1.0.4 => 1.0.4
>     gatsby-transformer-sharp: ^2.1.20 => 2.1.20
>   npmGlobalPackages:
>     gatsby-cli: 2.7.53

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by alesdonoso** [comment]
> Hi!
> 
> Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction](https://gatsby.dev/reproduction). This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.
> 
> If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction](https://gatsby.dev/reproduction) and we'll be able to take another look.
> 
> Thanks for using Gatsby! 💜

Hi there Leko!

I've done the minimal reproduction. Just created a new gatsby from `gatsby new bug-repro https://github.com/gatsbyjs/gatsby-starter-hello-world` --> `gatsby develop` without installing ANY plugin and it doesn't work yet.

Working fine on incognito and mozilla. In normal Chrome mode, I can't even open console.

**Comment by alesdonoso** [comment]
Up, waiting response from you guys.

**Comment by alesdonoso** [comment]
@LekoArts Hi Leko. I could reproduce one redirect bucle in one of my gatsby repositories. Let me show you the console logs.

![Bug_Gatsby_1](https://user-images.githubusercontent.com/48650098/71517570-f0f17d00-28ae-11ea-95fe-3b95288098d8.PNG)

![Bug_Gatsby_2](https://user-images.githubusercontent.com/48650098/71517571-f222aa00-28ae-11ea-9d68-80ad0bae6553.PNG)

**Comment by alesdonoso** [comment]
@LekoArts ?

**Comment by DSchau** [comment]
@alesdonoso that error in your console appears to be from an extension.

You can see it with `Uncaught TypeError: Cannot read property 'hasAttribute' of null` from `global-shortcut.js`.

It's working in Incognito because that particular extension is most likely disabled. I recommend you disable extensions (e.g. one by one) and see which one is causing the issue.

If you're able to reproduce with a specific extension, we'd love for you to report back as to which one seems to causing the issue.

I'm going to close as this is not a Gatsby-specific issue, but please do reply back and/or re-open if we can help further.

Thanks! 💜

**Comment by Ruchika30** [comment]
Hi , I am facing this same issue. And things are not working for me . Can't even open console, hard refresh is also not working. Kindly help
