### ISSUE TITLE
function component force render when using gatsby-link and anchor link

### ISSUE THREAD

**Issue by Austaras** [gatsbyjs/gatsby#20127]
## Description

When using archor link and gatsby-link together in a function component used as a page's component, click on anchor link(and thus changes location.hash) will always cause a re-render, even using `memo`

This bug is a bit wired and I don't have enough experience in React ecosystem so maybe it's expected behaviour?.

### Steps to reproduce

[here](https://github.com/Austaras/bug-reprod), 2nd commit is for function comp and 3rd is for class component

### Expected result

Both shouldn't re-render when hash change

### Actual result

Memo function component does re-render

**Comment by LekoArts** [comment]
Thank you for opening this!

You should use Link like `import { Link } from "gatsby"` and not use `gatsby-link`. Please read this StackOverflow post as it should answer your question (it's kinda expected behavior): https://stackoverflow.com/questions/56051736/gatsby-clicking-in-route-anchor-element-leads-to-re-render

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by Austaras** [comment]
@LekoArts I have read the stackoverflow question before and it still doesn't answer my question. I updated my repo accordingly and it still re-renders. Is it expected behaviour? If so, why?

**Comment by LekoArts** [comment]
Do you see that behavior in Chrome or Firefox?

**Comment by Austaras** [comment]
I see it in both,

**Comment by LekoArts** [comment]
Then I'll keep it open for my colleagues as I sadly won't have time to look into it deeper this week.

**Comment by LekoArts** [comment]
Re-reading your question: You shouldn't use gatsby-link for internal anchors, use the normal anchor tag for that :)

**Comment by mjmaurer** [comment]
FWIW I'm also running into this. I have a Link (from `gatsby` not from `gatsby-link`) inside a memo'd function component. The link is `to` a different page on my site. Clicking on the link results in all Links rerendering even though nothing has changed. Replacing the function componenet with the exact same fixes the issue
