### ISSUE TITLE
GraphQLError: Syntax Error: Expected Name, found Int "2"

### ISSUE THREAD

**Issue by paolodedomini** [gatsbyjs/gatsby#20130]
i'm trying to connect to directus graphql api service:
` {
        resolve: "gatsby-source-graphql",
        options: {
          typeName: "items",
          fieldName: "mokacms",
          url: "http://mokacms.monemacms.it/mokacms/gql?access_token=2xxxxxxxxxxxxxxxx",
        },
      },`

and the result is:
GraphQLError: Syntax Error: Expected Name, found Int "2"

where i do wrong?
Any idea? Thanks

**Comment by vladar** [comment]
Hey, I couldn't reproduce it locally with your config. For me `gatsby build` outputs:

```
ServerError: Response not successful: Received status code 401
```

which makes sense since I am not authorized in the service. So I suspect there is an error somewhere in your GraphQL query. But in order to help you, we will need more details and ideally a [reproduction repository](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/).
