### ISSUE TITLE
Gatsby includes many js-files to simple blog

### ISSUE THREAD

**Issue by zhandosweb** [gatsbyjs/gatsby#20135]
Hello! 

I am the first time to try Gatsby. Before I will sorry maybe for stupid questions. 

I develop a Test Blog site. Then I write command `gatsby build` to generate finally site. 

And if I go to **public>index.html** file, I see, that Gatsby creates many javascript-files. Here is a screenshot, what I mean: https://prnt.sc/qau1nk

It's a normal situation? If I create a simple blog, my site really needs all these javascript-files? 

Sorry again for the stupid questions. I am working with PHP last 3 years, and first time to try React + Gatsby.

**Comment by LekoArts** [comment]
Thank you for opening this!

> It's a normal situation?

Yes, it is! Gatsby/Webpack creates bundles for each page (code-splitting) so that only the necessary data for each page is loaded when you view the site. Together with "gatsby-link" this gives you fast & responsive page changes. You can learn more about the build process here: https://www.gatsbyjs.org/docs/overview-of-the-gatsby-build-process/#what-happens-when-you-run-gatsby-build

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
