### ISSUE TITLE
context state is not persistent across pages

### ISSUE THREAD

**Issue by y-sumanth** [gatsbyjs/gatsby#20238]
I am using gatsby-plugin-layout. Context state is not persistent across pages. 
What can I do to achieve state persistence across pages?

**Comment by wardpeet** [comment]
Hi @y-sumanth!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a minimal reproduction. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could provide a minimal reproduction and we'll be able to take another look.

Thanks for using Gatsby! 💜

**Comment by y-sumanth** [comment]
Sorry for the issue. I could achieve this by using wrapRootElement. Thanks

**Comment by MikeBroders** [comment]
@sumanthyedoti can u give some example on how u achieved this?

**Comment by sumanthyedoti** [comment]
@MikeBroders 
Create context and add that to `wrapRootElement` in both **gatsby-browser** and **gatsby-ssr**
```
const React = require("react")
const { ContextComponent } = require("./src/Context");

exports.wrapRootElement = ({ element }) => {
  return <ContextComponent>{element}</ContextComponent>;
};
```
