### ISSUE TITLE
there is no (css) changes when i run gatsby develop

### ISSUE THREAD

**Issue by kherwata** [gatsbyjs/gatsby#20255]
sometimes when i modify **css** file and run **gatsby develop** ... no changes until i **reload vscode**...
and when i run **gatsby build** ..i cannot even run **gatsby develop** or **npm run build** ... i think i lot of people suffers from this issue ... thanks **gatsby team**

**Comment by vladar** [comment]
Hi @kherwata !

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue with detailed "steps to reproduce" that makes it clear and obvious what the issue is and how we can begin to debug it.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by kherwata** [comment]
i dont know  how to reproduce it but .. it solved the problem by adding my **global.css** file to **gatsby-browser.js**
