### ISSUE TITLE
Best way to create and get slugs for Blog Posts

### ISSUE THREAD

**Issue by zhandosweb** [gatsbyjs/gatsby#20287]
Hello!

Please, can you tell me the best way to create and get slugs for Blog Posts? I mean .md posts. 

For example. On Jekyll or Hugo, I can set permalink on Frontmatter using the command: `permalink: /some-slug`. And it's will be enough for it. 

I learn Gatsby`s documentation. And for creating slug's I should work with Node.js API? With API's like onCreateNode, createFilePath, etc. I think it's very difficult.. 

Maybe there is have some plugin or something else? For easily create post-permalinks for .markdown files..

**Comment by jonniebigodes** [comment]
@zhandosweb i understand that dealing with the whole Gatsby api hooks can be a bit daunting at first. Gatsby does not support it, basically the way for gatsby to generate slugs/pages and so on is through one of two ways, one you get the page structure based on what's inside the `pages`, or two, you create the content programmatically through `gatsby-node`. I remember that a plugin was added to the plugin ecosystem. More specifically [this](https://github.com/cedricdelpoux/gatsby-plugin-slug), going over it a bit, it seems that this package is way outdated and i don't recomend it. Since the last commit and the current state of Gatsby, there were alot of changes introduced in the code base and with that it might even not work. 

If you don't mind, my recomendation would be to continue to learn about the apis, you might think that those can be a bit overwhelming at first, when you first approach them, but basically for almost 90% of the times, you'll only deal with `createPages`, `createNode`/`onCreateNode`. It's only if you plan to do some stuff that is more exotic that you might have to go deeper. Also on the starters that were created and made available by both the team and the community can even help you further.

My take/experience with this when i was first introduced to it was the exactly the same what you're feeling. But i decided to stick with it and with by using i expanded my js knowledge, my graphql knowledge and so on. 

Sorry that i wasn't more helpfull

Feel free to provide feedback so that we can close this issue or continue to work on it until we find a suitable solution

**Comment by zhandosweb** [comment]
@jonniebigodes thank you for the answer! Your reply is helpful for me. 

I understand and will continue to learn about that. At this time my goal is detailing learn `createPages, createNode/onCreateNode` API-s.

**Comment by jonniebigodes** [comment]
@zhandosweb no need to apologize, they are valid questions, more even to people that come into contact with Gatsby, the documentation goes a long way, but sometimes some details are ommited. And when that happens these questions pop up. Me personally i'm glad that you asked it. Reason being that should someone else be in the same situation they will have their answer. 

Once again, glad that i was able to help, giving you some insights. 

Should any more issues/questions, feel free to create a issue detailing them and if i'm able i'll gladly try and answer them to the best of my knowledge.
