### ISSUE TITLE
[gatsby-image] Images cropped in height

### ISSUE THREAD

**Issue by marcheimendinger** [gatsbyjs/gatsby#20306]
## Description

Some of my images are cropped in height even if I don't set both a `maxWidht` and `maxHeight`.

### Steps to reproduce

Here is a demo of the issue : https://github.com/marcheimendinger/gatsby-image-crop-issue

- `npm install` and `gatsby develop`
- On the home page, click on the "Color" link
- You'll see two images, originally of the same size (width and height)

### Expected result

The two images on the page should be entirely displayed.

### Actual result

 The first one is cropped in height but not the second one.
It looks like it depends of the images as I don't always have this issue on all of them. But I can't find the exact reason why.

### Environment

```
System:
    OS: macOS Mojave 10.14.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.15.1 - /usr/local/bin/node
    npm: 6.13.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 79.0.3945.88
    Firefox: 70.0.1
    Safari: 13.0.4
  npmPackages:
    gatsby: ^2.18.12 => 2.18.16
    gatsby-cypress: ^0.2.19 => 0.2.19
    gatsby-image: ^2.2.36 => 2.2.37
    gatsby-plugin-google-analytics: ^2.1.31 => 2.1.31
    gatsby-plugin-manifest: ^2.2.33 => 2.2.34
    gatsby-plugin-netlify: ^2.1.30 => 2.1.30
    gatsby-plugin-offline: ^3.0.29 => 3.0.30
    gatsby-plugin-react-helmet: ^3.1.18 => 3.1.18
    gatsby-plugin-sharp: ^2.3.7 => 2.3.10
    gatsby-plugin-sitemap: ^2.2.24 => 2.2.24
    gatsby-plugin-styled-components: ^3.1.16 => 3.1.16
    gatsby-plugin-typescript: ^2.1.23 => 2.1.23
    gatsby-source-filesystem: ^2.1.42 => 2.1.43
    gatsby-transformer-sharp: ^2.3.9 => 2.3.9
    gatsby-transformer-yaml: ^2.2.20 => 2.2.20
    gatsby-transformer-yaml-full: ^0.2.0 => 0.2.0
    gatsby-yaml-full-markdown: ^0.2.0 => 0.2.0
```

**Comment by marcheimendinger** [comment]
I solved the issue by re-exporting the images with Preview.app (macOS). But still a strange issue…

**Comment by LekoArts** [comment]
Thank you for opening this and glad that you got it solved.

This might have been a problem with your setup or image export and I haven't seen this behavior on my starter with different images, too. If other people see this issue here and have the same problem, please provide a reproduction :)

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
