### ISSUE TITLE
Styled Components CSS delayed loading

### ISSUE THREAD

**Issue by marekmika** [gatsbyjs/gatsby#20329]
Everything works well when the webpage is tested on the localhost. Anyway, when the page is deployed on, for example, Netlify, so the CSS style is applied after some time so the user can see the lag which doesn't look very good.

[Video](https://streamable.com/p1inc) where is recorded the problem. [Here](https://adoring-visvesvaraya-fff191.netlify.com/) is a webpage deployed. Here is [repository](https://github.com/marekmika/gatsby-landing-page-problem). Basically webpage is composed of [section-one.tsx](https://github.com/marekmika/gatsby-landing-page-problem/blob/master/src/components/sections/section-one.tsx). 

Please, can you tell me what is the best solution for this problem? Maybe I can add just some loader spin, etc ...

**Comment by tcope25** [comment]
I'm not sure this is a Gatsby specific issue.

**Comment by sidharthachatterjee** [comment]
The issue here isn't `styled-components`. 

It's that the page isn't getting SSRed correctly. That's why _Section One_ is only visible after JavaScript loads. Disabling JavaScript never renders it. 

This is because the component at https://github.com/marekmika/gatsby-landing-page-problem/blob/master/src/components/sections/section-one.tsx conditionally renders stuff based on Media Queries. 

All of which would be false in a SSR environment. You'll want to return something by default so that the SSRed page includes something. 

Hope that helps! Marking this as answered and closing but please feel free to comment if there is anything else related to this that I can help with.
