### ISSUE TITLE
Gatsby with Contentful on AWS not updating

### ISSUE THREAD

**Issue by keithpacana** [gatsbyjs/gatsby#20335]
Hi so I deployed a static gatsby site through aws s3 and I made an update on one of the blog posts, however, the update is not reflected on prod. Anyone know why this is happening? On localhost it's fine. Thanks

**Comment by AkashRajpurohit** [comment]
I believe you have to rebuild the application and deploy on AWS. After you have updated the content of blog post, the site has to be rebuild which will bring the updated content from contentful and update the UI as expected

**Comment by sidharthachatterjee** [comment]
Hey @keithpacana 

@AkashRajpurohit is absolutely right. On `localhost` you are likely running `gatsby develop`? On production, you will need to trigger a new build to occur when changing blog post contents (say on GitHub)

Since you're using AWS, maybe [this](https://www.gatsbyjs.org/blog/2018-08-24-gatsby-aws-hosting) blog post will interest you. It discusses how to use Amplify to set up CI/CD. 

Marking this as resolved and closing for now but please feel free to comment/reopen if I wasn't clear or if there is anything else related to this that you need help with!
