### ISSUE TITLE
Ability to update the statically fetched data at runtime.

### ISSUE THREAD

**Issue by Jaikant** [gatsbyjs/gatsby#20399]
I have a static page. A user can optionally change some data on this page. If the user updates any data in the db, I would like to set a `dirty` bit for that record in the db and only fetch that record at runtime and update the previously stored build-time static data.

### Motivation

My app has user profiles (say like facebook), the user profile page is static. The user has the ability to change his data on the page, say his image. I would prefer the page to be static in nature, but the particular image to be the latest image if the user updated it since the last time the app was deployed.

**Comment by jonniebigodes** [comment]
@Jaikant depending on what you use for db and how you've set it up with gatsby in terms of communication you can still have the most recent information. 
When a user visits the page, with a `useEffect` hook or using `componentDidMount` if you're using a class based component, which is triggered when the component/page is mounted it makes a call to your backend to retrieve the information and store it locally in the state. 

For instance the username, it's real name and the profile pic, Something like:
```json
{
  "userInformation":{
   "id":"a unique id",
   "username":"a username",
   "profilePic":"https://theserverlocation/folder-where-the-images-will-stored/randomProfile.jpg"
  }
}
```

When the user modifies the information, you mentioned a image, what you could do is push the image up to the server, wait for a response being sent back and update the image url accordingly.

Without any more information on how you've setup the site on your end, this could tend to become a bit of a "metaphysical" discussion. If you're willing, you could create a simple reproduction following [these steps](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/) so that it can be further looked at and possibly provide a more accurate answer.

**Comment by Jaikant** [comment]
@jonniebigodes Thx for your inputs, much appreciated!

I was looking for a way to update the app level data, so every component gets updated, rather than maintaining state for every component. 

But thinking about this little more, my requirements change and I would want the updated information to be visible across users/browsers. I did read somewhere about incremental gatsby builds, probably that is the feature which would help me. @KyleAMathews is this what incremental builds are about?

Closing this issue as it is no longer relevant for me, but would be interested to get more details on incremental builds.
