### ISSUE TITLE
Can I configure apollo server to store information in backend using gatsby?

### ISSUE THREAD

**Issue by ankitpatelinitio** [gatsbyjs/gatsby#20391]
Hello,

  I have to configure backend with gatsby to store information in database. So is it possible to configure it with backend? I am new in gatsby and I read the documentation of gatsby but didn't find anything.

Anyone please give me a reply.

Thanks.

**Comment by jonniebigodes** [comment]
@ankitpatelinitio the short answer is yes. But let me give some context, i have used apollo server some time ago to fetch data from my own server, see my response [here](https://github.com/gatsbyjs/gatsby/issues/12945#issuecomment-478376174). In the Gatsby ecosystem most plugins are a "one way street", which means that they are used to pull in data to be consumed by your website, in order for you to actually add, update or even delete data from a database with graphql and apollo you could use something like [this](https://github.com/jlengstorf/gatsby-with-apollo) and take a look at the [gatsby store](https://github.com/gatsbyjs/store.gatsbyjs.org) for some insights, or if you want something a little simpler and you don't mind waiting a bit i could create a reproduction for you. Do you mind waiting a bit?

**Comment by ankitpatelinitio** [comment]
@jonniebigodes Is there any simple example available where we can save and manage data with a database using the apollo server.

**Comment by jonniebigodes** [comment]
@ankitpatelinitio if you don't mind waiting a bit i can set a repo with a server and Gatsby website during the weekend and come back with a response for your issue

**Comment by ankitpatelinitio** [comment]
@jonniebigodes Yes Sure. I will be waiting for your response.

**Comment by jonniebigodes** [comment]
@ankitpatelinitio i've created a full reproduction of a graphql server, for simplicity purposes i used sqlite  and sequelize for the data modeling/storage. Added `apollo-server-express` to keep the implementation simple. 

The server will allow you to:
- Read
- Create
- Update
- Delete

Also created a simple Gatsby website that will consume and change the data in the server.

Traditionally and like i mentioned above, when you use Gatsby and some sort of graphql it's basically a "one way street" (pardon the bad pun), which means Gatsby will only consume it, not change it per se. Turning into a static site generator. But one thing that is great about it is that you can still use it as a static site generator and take it a bit further turning the app into a dynamic webapp. @DSchau  gave a great talk the past year about this topic during the London Gatsby Days, you can watch it in [here](https://www.youtube.com/watch?v=zeVC-gD3u7M). For your case, with a bit of work you can safely interact with a graphql backend and modify the data at will.

The code repo [here](https://github.com/jonniebigodes/gatsby_apollo_with_dummy_server) that contains both the server and the Gatsby website configured to interact the server. All of the code is commented out. Go at it your own pace and let me know if you have any further questions. 

Feel free to provide feedback so that we can close this issue or continue to work on it until we find a suitable solution.

**Comment by anandtoshniwal** [comment]
@jonniebigodes I also did the same for setting up the apollo server locally, but I was wondering if it's possible to pull the gatsby graphql schema and resolver and setup apollo-server-lambda using netlify function.
I was able to extract the graphql schema and import it but facing problem with resolvers.. would love to hear if you have achieved something like this or you can suggest any approach to achieve the above

**Comment by jonniebigodes** [comment]
@anandtoshniwal to clarify what you are asking, you're saying use `apollo-server-lambda` and netlify functions working together for the graphql data endpoint and pull the data in to Gatsby, possibly using `gatsby-source-graphql`. Or don't use gatsby's plugin and use the same approach mentioned here but instead of using the local server use the lambda functions?

Can you clarify this a bit? And i can go from there and possibly provide you with a more detailed explanation

**Comment by wardpeet** [comment]
@anandtoshniwal currently the only way to have the same resolvers and schema is to run gatsby develop on a server which isn't recommended. At this moment we don't have a great solution for it. It's on our roadmap to look more into this.

**Comment by LekoArts** [comment]
Thank you for opening this!

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
