### ISSUE TITLE
gatsby tutorial sidebar animation bug

### ISSUE THREAD

**Issue by soohoowoohoo** [gatsbyjs/gatsby#20416]
**Summary**
I'm going through the [gatsby tutorial part one](https://www.gatsbyjs.org/tutorial/part-one/) and noticed that the sidebar animation shows the "linking between pages" highlighted when not in that section and that when in the "linking between pages" section the sidebar animation has "deploying a gatsby site" selected. I've also tested this in multiple browsers on my mac with the same results.

**OS / browser versions**
macOS version: 10.15.2
safari version: 13.0.4
firefox version: 71.0
chrome version: 79.0.3945.88

**Steps to reproduce**
1. Go to "linking between pages" anchor (https://www.gatsbyjs.org/tutorial/part-one/#linking-between-pages)
2. Notice "linking between pages" sidebar item is not highlighted
3. Scroll up out of "linking between pages" section until it's sidebar item highlights.

**Screenshots**
- Linking between pages sidebar item highlights outside of it's section
- Linking between pages section does not have its sidebar item highlighted

![image](https://user-images.githubusercontent.com/8563758/71775848-1df7fc80-2f4d-11ea-8f69-763cb1a9c0ce.png)

![image](https://user-images.githubusercontent.com/8563758/71775854-37994400-2f4d-11ea-82cc-1a875524861c.png)

**Comment by soohoowoohoo** [comment]
bump

**Comment by yash-chowdhary** [comment]
Hi, I'd like to take a look at this if it's up for grabs. :)
Noticed this issue here as well - [Part 8 - Add Offline Support](https://www.gatsbyjs.org/tutorial/part-eight/#add-offline-support) and [Part 8 - Add Page Metadata](https://www.gatsbyjs.org/tutorial/part-eight/#add-page-metadata). 
There could be more of these. I just noticed these ones above.
