### ISSUE TITLE
Deploy failure of gatsby example "data-fetching" on windows

### ISSUE THREAD

**Issue by yuxiang660** [gatsbyjs/gatsby#20552]
## Description

After running "gatsby build & gatsby serve" for "data-fetching" example **on windows**, the Chrome cannot load "localhost:9000" correctly.

### Steps to reproduce

1. Download latest ["data-fetching" example](https://github.com/gatsbyjs/gatsby/tree/master/examples/data-fetching) from GitHub.
2. Add your GitHub token to the project.
3. Run following command on windows:
```
> npm install
> gatsby build
> gatsby serve
```
4. Open Chrome with "localhost:9000".  It reports following error:
<img width="933" alt="error" src="https://user-images.githubusercontent.com/6477589/72213600-8128f680-352c-11ea-8c05-7a350916ebc5.png">

**Note**: 
  - Linux doesn't have this issue.
  - `gatsby develop` also works on windows.

### Expected result

Should be: https://gatsby-data-fetching.netlify.com/

### Actual result

The chrome failed with white page.

### Environment

  System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz
  Binaries:
    Node: 12.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.21.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.6 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.17 - /cygdrive/c/Python27/python
  Browsers:
    Edge: 44.19041.1.0
    Chrome: 79.0.3945.117

**Comment by LekoArts** [comment]
So are you reporting that `gatsby serve` doesn't work on Windows or that this specific example doesn't work on Windows?

**Comment by yuxiang660** [comment]
> So are you reporting that `gatsby serve` doesn't work on Windows or that this specific example doesn't work on Windows?

This specific example doesn't work on Windows. I think `gatsby serve` works for other examples.

**Comment by jonniebigodes** [comment]
@yuxiang660 i've just finished running the example and it's working in windows 10.

With the packages that are mentioned in the example's `package.json` running `gatsby build && gatsby serve` yelds the following:
![yuxiang660_1](https://user-images.githubusercontent.com/22988955/72392083-0a0b8200-3727-11ea-88e9-70a2cf170a54.png)

From your screenshot adding both `gatsby-plugin-manifest` and `gatsby-plugin-offline` and changing my `gatsby-config.js` to use both of them, turning it into the following:
```javascript
require("dotenv").config({})
module.exports = {
  siteMetadata: {
    title: `Testing extraction of data`,
    description: `random text to be used here`,
    author: `dummy user`
  },
  plugins: [
    {
      resolve: `gatsby-source-graphql`,
      options: {
        typeName: `GitHub`,
        fieldName: `github`,
        url: `https://api.github.com/graphql`,
        headers: {
          Authorization: `bearer ${process.env.GATSBY_GITHUB_TOKEN}`
        }
      }
    },
    {
        resolve: `gatsby-plugin-manifest`,
        options: {
          name: `gatsby-starter-default`,
          short_name: `starter`,
          start_url: `/`,
          background_color: `#663399`,
          theme_color: `#663399`,
          display: `minimal-ui`,
          icon: `src/images/gatsby-icon.png`, // This path is relative to the root of the site.
        },
      },
      `gatsby-plugin-offline`
  ]
};
```
yelds the following:
![yuxiang660_2](https://user-images.githubusercontent.com/22988955/72392300-961da980-3727-11ea-961d-5d09bf26eae9.png)

Checking it in a normal chrome window yelds the same result.

It could be that you have probably some stale data in the browser's cache, you could clean the cache and re-run the code, or try it in incognito mode like i did and check if the issue is still present. 
If it's there, what you're experiencing might be associated with something else.

**Comment by yuxiang660** [comment]
Thank you for your reply. I will check it on my side.
