### ISSUE TITLE
external script not being fired on prod

### ISSUE THREAD

**Issue by keithpacana** [gatsbyjs/gatsby#20561]
I'm trying to integrate a service into my gatsby site, basically the script function injects the widget into a specific class name on my page. It's working fine on localhost gatsby develop but not on prod. Any ideas to this?

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by keithpacana** [comment]
for anyone with a similar issue, my problem was the react-helmet-plugin didn't update the head until the component finished mounting, which as a result didn't inject run the function that injected the widget. my solution was adding the property deferred=false into the Helmet tag.
