### ISSUE TITLE
Future routing library

### ISSUE THREAD

**Issue by vaclavnovotny** [gatsbyjs/gatsby#20598]
First of all, thank you for great work on Gatsby. The ecosystem is thrilling and documentation is simply great.

I'm currently porting heavy SPA to Gatsby, where all the public web pages will be static and only small portion remains SPA. The SPA relies heavily on react-router while GatsbyJS shifted to reach-router in its v.2.

Reach-router, having so much benefits over react-router, seemed as a good choice, but since Ryan Florence, author of reach-router, moved his attention to react-router [[1]](https://reacttraining.com/blog/reach-react-router-future/) the reach-router slows down its development. The main disadvantage IMHO is lack of hooks API and I anticipate that react-router will be better choice in the near future [[2]](https://reacttraining.com/blog/reach-react-router-future/).

Does the Gatsby team consider going back to react-router sometime soon?

**Comment by pieh** [comment]
We currently don't have a plan to move back soon. This will be very likely breaking change and if we decided to do this - we would need to wait for Gatsby v3 to make that swap.

I do agree with general sentiment (hooks are 🔥 ! ;) ), but we will also need to do lot of research here, if it will play nicely with accessibility (focus management, screen readers support, etc), so it's not as straight forward as just if API design is more compelling than currently used router.

It's also in realm of possibilities that Gatsby would create/maintain our own router. As we had troubles integrating routers and had to resort to some hacks to be able to use them. This is not a knock on those routers - they work very well within usecases they are build for, but Gatsby "stretches" its usecase a bit. If we would end up building our own, we would aim for router API compatible with one of popular routers (which could very well be react-router's API).

But because we are still not nearing Gatsby v3 those are still just ideas that need a lot of research before they become something concrete.
