### ISSUE TITLE
Support passing pathPrefix in via CLI

### ISSUE THREAD

**Issue by micahgodbolt** [gatsbyjs/gatsby#20688]
## Summary

For every PR to our Gatsby site we build and push the assets to a server at "website.com/pr/123"

Obviously to make this work I need to set pathPrefix, but since the prefix will change with every PR i need a way to do it dynamically on each build.

One nice solution would be to use yargs and pass in a build param

```
gatsby build ----prefix-path --path="pr/123"` 
```

But path isn't a valid gatsby param, so you have to do unnamed params

```
gatsby build pr/123 --prefix-path
```

then grab it with
```js
 process.argv[3]
```
and hope that no one changes the order of the params.

## Solution

Either add `path` as a param or simply allow --prefix-path to take in a string value

**Comment by wardpeet** [comment]
Hey,

We don't want to bloat the cli with too many options. More options makes the cli harder to use and we want it to be as simple as we can.

Your issue is still solvable with env variables. Change your gatsby-config into
```
module.exports = {
  pathPrefix: process.env.PATH_PREFIX || ``,
}
```

Run gatsby like `PATH_PREFIX=pr/123 gatsby build --prefix-path`. If you have windows users you should use [cross-env](https://www.npmjs.com/package/cross-env) to make this work on all operating systems.

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜
