### ISSUE TITLE
Json transformer is not producing a consistent graphql output on windows

### ISSUE THREAD

**Issue by decimoseptimo** [gatsbyjs/gatsby#20703]
I have a products.json, and a categories.json file. I query in gatsby-node, but also in pages, and in components with StaticQuery.

Given the following order of commands:
`gatsby clean && gatsby develop`, the generated build is corrrect.
`CTRL + C, gatsby develop`, the result is inconsistent. When the build is fast (little products) graphql  returns less nodes (either less products or categories). When the build is slow (more products) graphql is returning even less nodes. 

There are even cases where it throws an error refering to my graphql syntax being incorrect! The solution is to trigger an update to categories.json, changing one little char is enough, just to trigger a gatsby update.

After that `CTRL + C, gatsby develop` should work properly (not 100% sure, as I haven't done much testing).
Does this make any sense?

### Environment

```
  System:
    OS: Windows 10
    CPU: (2) x64 AMD Athlon(tm) II X2 250 Processor
  Binaries:
    npm: 6.12.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.5.0 => 2.13.31 
    gatsby-awesome-pagination: ^0.3.4 => 0.3.4 
    gatsby-image: ^2.1.0 => 2.2.6 
    gatsby-plugin-favicon: ^3.1.6 => 3.1.6 
    gatsby-plugin-local-search: ^1.0.0 => 1.0.0 
    gatsby-plugin-manifest: ^2.1.1 => 2.2.3 
    gatsby-plugin-offline: ^2.1.0 => 2.2.4 
    gatsby-plugin-react-helmet: ^3.0.12 => 3.1.2 
    gatsby-plugin-sharp: ^2.0.37 => 2.2.8 
    gatsby-plugin-styled-jsx: ^3.0.5 => 3.1.2 
    gatsby-source-filesystem: ^2.0.38 => 2.1.5 
    gatsby-transformer-json: ^2.1.11 => 2.2.2 
    gatsby-transformer-sharp: ^2.1.19 => 2.2.4 
```

**Comment by jonniebigodes** [comment]
@decimoseptimo can you make a reproduction following [these steps](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/)

**Comment by decimoseptimo** [comment]
I tried. Unable to reproduce, the issue must be elsewhere, thanks.

**Comment by decimoseptimo** [comment]
@jonniebigodes This was still bothering me, so i gave it anoher look. Please check: https://github.com/decimoseptimo/gatsby-starter-default/tree/graphql-inconsistent-nodes-test

This were the commands i issued and the output i had (in order):

`gatsby clean && gatsby develop`:
```
products: 210
categories: 63
...
215 pages                                  Success                                 gatsby-starter-default
```

`gatsby develop`:
```
products: 210
categories: 2
...
215 pages                                  Success                                 gatsby-starter-default
```

The issue is with the categories array not being consistent.

**Comment by jonniebigodes** [comment]
@decimoseptimo i've been checking your code and below i'm going to detail what i did to try and replicate the issue.
- Cloned your repo and switched to the branch.
- Installed the dependencies.
- As a testing method i ran 20 times your reproduction in development mode and production mode on my box, i'm also running win 10. As i wasn't happy with the results i booted wsl and repeated the process. Ran it 20 more times. I've compiled the results for development in [here](https://gist.github.com/jonniebigodes/1150a1dc17d95c6b7a66a0963c47f838) and in production [here](https://gist.github.com/jonniebigodes/423bff2e70ce852cd935aee7b7daeaeb). These cover only 10 iterations in each mode to prevent the gist to become way to big. But as you can see the issue didn't surface.

Also after each run i was checking `http://localhost:8000` and `http://locahost:9000`, for development and production mode to see if it all matched up and i was presented with the following:
![decimo_1](https://user-images.githubusercontent.com/22988955/73858888-0b653180-4831-11ea-9eef-6ee298c0cf1d.png)

- Today i circled back to this and i ran `yarn develop` and i'm presented with the following:

```bash
yarn develop
yarn run v1.21.1
$ gatsby develop
success open and validate gatsby-configs - 0.045s
success load plugins - 1.280s
success onPreInit - 0.005s
success initialize cache - 0.062s
success copy gatsby files - 0.248s
success onPreBootstrap - 0.014s
success createSchemaCustomization - 0.005s
success source and transform nodes - 0.771s
warn Plugin `gatsby-source-filesystem` tried to define the GraphQL type `File`, which has already been defined by the plugin `null`.
warn Plugin `gatsby-source-filesystem` tried to define the GraphQL type `File`, which has already been defined by the plugin `null`.
success building schema - 0.481s
products: 210
categories: 2
success createPages - 0.285s
success createPagesStatefully - 0.157s
success onPreExtractQueries - 0.002s
success update schema - 0.061s
success extract queries from components - 0.534s
success write out requires - 0.102s
success write out redirect data - 0.006s
success Build manifest and related icons - 0.212s
success onPostBootstrap - 0.221s
⠀
info bootstrap finished - 10.312 s
⠀
success run queries - 0.059s - 7/7 119.19/s
⠀
You can now view gatsby-starter-default in the browser.
⠀
  http://localhost:8000/
⠀
View GraphiQL, an in-browser IDE, to explore your site's data and schema
⠀
  http://localhost:8000/___graphql
⠀
Note that the development build is not optimized.
To create a production build, use gatsby build
```
Opened up the graphql editor in `http://localhost:8000/___graphql` and used the following query:
```graphql
{
  allCategoriesJson {
    edges {
      node {
        id
        name
        parent_id
      }
    }
  }
}
```
I get the following result:
```json
{
  "data": {
    "allCategoriesJson": {
      "edges": [
        {
          "node": {
            "id": "1",
            "name": "Frutas y Verduras",
            "parent_id": null
          }
        },
        {
          "node": {
            "id": "14",
            "name": "Queso",
            "parent_id": 10
          }
        }
      ]
    }
  }
}
```
There's definitely something happening here. I'm guessing that it could be related to either the usage of `id` in the file as a key for the category and the plugin also uses a id and it might break the node creation, or the usage of `parent_id` as it's also similar to a "reserved" word for the Gatsby plugin. What i would like you to do is the following. In the `categories.json` change `id` to `category_id` and in products `id` to `product_id`  and see if it fixes the issue. I'm going to do the same and apply the same testing methodology and see if the issue will pop up again. See if it happens on your end and provide feedback so that we can proceed from there. Sounds good?

**Comment by decimoseptimo** [comment]
The fix seems succesful in the minimal reproduction. I still have to do more testing in the real app, so far so good. https://github.com/decimoseptimo/gatsby-starter-default/commit/78e7e7f39b0346a24179572c874d0964507ea217

**Comment by jonniebigodes** [comment]
@decimoseptimo glad to hear it. a bit ago i repeated the test methodology once again and so far so good the issue did not present itself. I'm going to make a couple more rounds of tests. Hoping to hear that is all good on your side.

**Comment by decimoseptimo** [comment]
Thanks, my app seems working correctly after applying the changes you suggested. 

Also, I don't recall this issue was present earlier (when the nodes count in `products.json, categories.json`was smaller). Nor I see any referece to a reserved word `id` in the plugin docs.

**Comment by LekoArts** [comment]
Thank you for opening this!

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by decimoseptimo** [comment]
Isn't this a bug report?
