### ISSUE TITLE
SEO Tools showing single page twice with /index.html and without it

### ISSUE THREAD

**Issue by malik9353** [gatsbyjs/gatsby#20707]
## Description

After a build, the public folder has folders with router name. When i do SEO Audit i find each page route with /index.html and without that. And that is effecting my SEO rate.

### Steps to reproduce

After build, we can see that.

### Expected result

I should create a single route without /index.html.

### Actual result

I will attach screenshots below.
![image](https://user-images.githubusercontent.com/34607108/72678993-b0aba600-3acc-11ea-901b-00081a2e1c69.png)

### Environment

System:
    OS: Linux 5.0 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i3-4005U CPU @ 1.70GHz
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 10.0.0 - /usr/local/bin/node
    npm: 6.13.6 - /usr/local/bin/npm
  Languages:
    Python: 2.7.15+ - /usr/bin/python
  Browsers:
    Chrome: 78.0.3904.97
  npmPackages:
    gatsby: ^2.18.4 => 2.18.4
    gatsby-image: ^2.2.34 => 2.2.34
    gatsby-plugin-brotli: ^1.3.1 => 1.3.1
    gatsby-plugin-facebook-pixel: ^1.0.3 => 1.0.3
    gatsby-plugin-layout: ^1.0.14 => 1.1.16
    gatsby-plugin-manifest: ^2.2.31 => 2.2.31
    gatsby-plugin-offline: ^3.0.29 => 3.0.29
    gatsby-plugin-react-helmet: ^3.1.16 => 3.1.16
    gatsby-plugin-robots-txt: ^1.5.0 => 1.5.0
    gatsby-plugin-sass: ^2.0.11 => 2.1.24
    gatsby-plugin-sharp: ^2.3.4 => 2.3.4
    gatsby-plugin-zopfli: ^1.3.2 => 1.3.2
    gatsby-remark-copy-linked-files: ^2.1.13 => 2.1.31
    gatsby-remark-images: ^3.1.19 => 3.1.34
    gatsby-remark-lazy-load: ^1.0.2 => 1.0.2
    gatsby-remark-relative-images: ^0.2.2 => 0.2.3
    gatsby-source-filesystem: ^2.1.39 => 2.1.39
    gatsby-transformer-remark: ^2.3.8 => 2.6.38
    gatsby-transformer-sharp: ^2.3.6 => 2.3.6
  npmGlobalPackages:
    gatsby-cli: 2.8.14

**Comment by LekoArts** [comment]
Thank you for opening this!

> I should create a single route without /index.html

That's not possible as it's rather mandatory to create those files. You can access `/blogs` because it contains this file and your webserver understands that as the index file (e.g. [nginx](https://docs.nginx.com/nginx/admin-guide/web-server/serving-static-content/#root)). So you'll need to adjust your webserver to not server the index.html file but to redirect/rewrite the URL to the one without.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
