### ISSUE TITLE
Static Page with params ends on 404

### ISSUE THREAD

**Issue by cinder92** [gatsbyjs/gatsby#20736]
Hello, this works for me but only on local, on prod, i first get a 404 then render the page... i created a folder structure like this

```
- pages
 - post
  - *
   - store
     - *
```

i can access with `localhost:8000/post/1/store/2` everything works fine, but on prod, i first get a 404, any advice?

**Comment by TylerBarnes** [comment]
Hi @cinder92 !

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction
