### ISSUE TITLE
[docs][contributing] Settle on a Terminal profile for screencasts & screenshots

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#20765]
We're developing a [screencast and screenshot specification](https://docs.google.com/document/d/1za0rTGBzxpdYxPkYIncArfbSngSI0IldePDHFdUUzHQ/edit#) for Gatsby Learning, and this includes creating a reusable Terminal profile.

It's recommended to hide usernames to provide better continuity, in case a single screenshot needs to be updated by a different team member. 

We need to make a decision on which terminal app to recommend (Terminal? iTerm? Hyper.js?), and whether to use oh my zsh. Amberley has a profile, which we don't necessarily have to use but is available here: https://github.com/amberleyromo/screencast-spec

You are welcome to experiment and make recommendations. We'll want to test the profile out on various machines, some of which may have less clean installs from years of development and Time Machine backups. So clear install instructions would really help to try and get consistent results!

**Comment by gillkyle** [comment]
I recorded the information in this internal document: https://docs.google.com/document/d/1za0rTGBzxpdYxPkYIncArfbSngSI0IldePDHFdUUzHQ/edit#heading=h.rqf7vigyayt

To summarize the decisions and outcomes made:

## Terminal 

- iTerm2 is recommended since it offers the most automated customization
- Hyper is the best back up for someone working on Windows since it is cross platform

## Shell

The shell shouldn't affect anything because all commands between zsh and bash will be the same for Gatsby. This is only a problem for Windows users who are recommended to use a bash shell on Windows through WSL or a similar alternative.

## Styles

Important styles for high contrast and easy readability are:

- font-size: 20px
- background-color: #000
- font-color: #fff
- font: Menlo
