### ISSUE TITLE
chore(packages): 404 on `gatsby-cypress`

### ISSUE THREAD

**Issue by muescha** [gatsbyjs/gatsby#20773]
## Description

404 on `gatsby-cypress`

### Steps to reproduce

- i open this starter:
https://www.gatsbyjs.org/starters/parmsang/gatsby-starter-ecommerce/

- i click on dependencies:
https://www.gatsbyjs.org/packages/gatsby-cypress

- get a 404

### Expected result

no 404

### Actual result

404

**Comment by LekoArts** [comment]
I closed the PR due to: https://github.com/gatsbyjs/gatsby/pull/20774#issuecomment-577065757

It get's the internal link because of:
https://github.com/gatsbyjs/gatsby/blob/master/www/gatsby-node.js#L690-L697

I don't find it too important of an issue but feel free to correct the filtering here to exclude gatsby-cypress. It's probably the only package that this will happen with though.

**Comment by muescha** [comment]
so removing from `gatsbyDependencies` 
and adding to `miscDependencies` would show the npm link?

**Comment by wardpeet** [comment]
Thank you for opening this, @muescha 

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜

**Comment by muescha** [comment]
created #21479
