### ISSUE TITLE
Support @defer in graphql queries to load expensive data on-demand

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#2080]
https://dev-blog.apollodata.com/new-features-in-graphql-batch-defer-stream-live-and-subscribe-7585d0c28b07 has a good explanation.

This would be useful in cases where you don't need some data on the initial render (or perhaps ever) so you could avoid loading it until requested.

I think in our implementation the deferred section of the data would be replaced with a URL pointing to a JSON file for that portion of the query. That could be fetched as determined by the site's logic.

A use case gatsbyjs.org will have for this in the short-term is a plugins browsing/search tool. We'd only want the minimal info needed to display a table initially to make sure loading the page is as fast as possible. But then as people search or click on categories, we'd load in more info. Also if you click on a package, we'd want to show the README for that package. Almost all of the very large query for this page should be deferred until needed.

Thoughts?

**Comment by sibelius** [comment]
you can use @defer with relay style using this package https://github.com/relay-tools/fetch-multipart-graphql

**Comment by marcysutton** [comment]
I'm interested in this idea as well for loading content inline rather than linking off to separate pages (when client-side JS is enabled, anyway). It would be nice to load more blog post titles or small video embeds on click of a "show more" link rather than querying everything on load to keep the page lighter. Would that use case fall under deferred queries?

Something like this:
![grid of 4 video embeds with a load more link circled in red](https://user-images.githubusercontent.com/1045233/51436507-70a8ad80-1c43-11e9-8801-59dadb5ea9a4.jpg)

**Comment by entr** [comment]
Still interested. Would like to use it in Gatsby some day :)

**Comment by marcysutton** [comment]
I am also interested in this. I asked @DSchau for context, and he said it would be challenging to implement because:

> Requires a fair amount of core changes! (e.g. I don’t think we even support graphql directives, e.g. `@defer`)
> Some work that @freiksenet is working on should make this easier though!

So a fix won't happen right away, but potentially in the future? I'll mark this as not stale to keep it open so we can track it.

**Comment by freiksenet** [comment]
We will support directives with #11480. 

There are two parts of this issue:

a) implementing the directive that will put data behind @defer to a separate data chunk that page can load
b) implementing the convenient client-side abstractions to trigger the loading of that chunk. 

I feel b) will also be tricky because we probably want to fetch it optimistically (same way we do with the links).

**Comment by alexfornuto** [comment]
@KyleAMathews Has this stayed closed because it's resolved? If so, can we reference where/how for those like me who end up on this issue while looking for documentation on how to query on demand?
