### ISSUE TITLE
Passing static query data

### ISSUE THREAD

**Issue by pmarxbraun** [gatsbyjs/gatsby#20833]
## Summary

I'm trying to use ['react-grid-gallery'](https://benhowell.github.io/react-grid-gallery/) component in my Gatsby project. It works perfectly when I copy/paste the example code. But when I want to use staticQuery to get my images I can't pass the data in the IMAGES array.

Here's my code

## Relevant information

import React from "react"
```
import { useStaticQuery, graphql } from "gatsby"
import imageGalleryStyles from "./imagegallery.module.css"
import Button from "../Button/Button"
import TwoCol from "../Layout/TwoCol"
import Gallery from "react-grid-gallery"

const ImageGallery = props => {
  const data = useStaticQuery(graphql`
    {
      file(name: { eq: "base-aerienne-Bricy-2-FEHR-Group" }) {
        publicURL
      }
    }
  `)
  console.log(data)

  const IMAGES = [
    {
      src: "https://c2.staticflickr.com/9/8817/28973449265_07e3aa5d2e_b.jpg",
      thumbnail:
        "https://c2.staticflickr.com/9/8817/28973449265_07e3aa5d2e_n.jpg",
      thumbnailWidth: 320,
      thumbnailHeight: 174,
      caption: "After Rain (Jeshu John - designerspics.com)",
    },
    {
      src:{data.file.publicURL},
      thumbnail:{data.file.publicURL},
      thumbnailWidth: 320,
      thumbnailHeight: 174,
      caption: "After Rain (Jeshu John - designerspics.com)",
    },
  ]

  return (
    <div className={imageGalleryStyles.section}>
      <TwoCol>
        <div>
          <h2>{props.title}</h2>
          <Button
            buttonString="toutes nos réalisations"
            buttonURL="/realisations"
          ></Button>
        </div>
      </TwoCol>
      <Gallery enableImageSelection={false} images={IMAGES} />
    </div>
  )
}

export default ImageGallery
```
The first image in my array from staticflickr gets displayed but the one I queried {data.file.publicURL} does not. 
What am I doing wrong here ? Can you help me out ?

Thanks a lot !
Do you

**Comment by jonniebigodes** [comment]
@pmarxbraun as probably @sidharthachatterjee is busy continuing to build awesome stuff and further improving Gatsby and to avoid the issue being without answer for more time and if you both don't mind, i've taken a look at your issue and i have a solution for you. 

Going to detail the steps i took to triage this.

- Created a new Gatsby website using the hello world starter.
- After that the following packages were added `gatsby-source-filesystem`  and `react-grid-gallery` 
- Changed my `gatsby-config.js` to the following:
```javascript
module.exports = {
  /* Your site config here */
  plugins:[
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `assets`,
        path: `${__dirname}/src/assets/`,
      },
    },
  ]
}
```
- Created and copied over a couple of images over to the `src\assets\` folder.
- Created a component called `ImageGallery_V1.js` inside `src\components` with the following code:
```javascript
import React from "react"
import { useStaticQuery, graphql } from "gatsby"
import Gallery from "react-grid-gallery"

const ImageGalleryV1 = () => {
  const data = useStaticQuery(graphql`
    {
      file(name: { eq: "op_lemurs" }) {
        publicURL
      }
    }
  `)
  console.log(data)

  const IMAGES = [
    {
      src: "https://c2.staticflickr.com/9/8817/28973449265_07e3aa5d2e_b.jpg",
      thumbnail:
        "https://c2.staticflickr.com/9/8817/28973449265_07e3aa5d2e_n.jpg",
      thumbnailWidth: 320,
      thumbnailHeight: 174,
      caption: "After Rain (Jeshu John - designerspics.com)",
    },
    {
      src:{data.file.publicURL},
      thumbnail: data.file.publicURL,
      thumbnailWidth: 320,
      thumbnailHeight: 174,
      caption: "After Rain (Jeshu John - designerspics.com)",
    },
  ]
  return (
    <div>
      <Gallery enableImageSelection={false} images={IMAGES} />
    </div>
  )
}
export default ImageGalleryV1
```
 As you can see it's quasi equal to the one you posted in the issue description. And right out of the bat the issue presents itself, you have a issue in the assignment of the src and thumbnail element, more specifically:

```javascript
src:{data.file.publicURL}, //<- here
```
Changing it to:
```javascript
 src: data.file.publicURL,
```
Dropping the `{...}` and issuing `yarn develop` for a development build and opening up `http://localhost:8000` will yeld the following:
![pmarxbraun_1](https://user-images.githubusercontent.com/22988955/73555916-599bbe80-4446-11ea-973b-5d11b673ad23.png)

As you can see the image on the left is the one brought in from flickr and the one on the right my own. 

Clicking on it yelds the following:
![pmarxbraun_2](https://user-images.githubusercontent.com/22988955/73556040-8fd93e00-4446-11ea-9fc6-206392200e7e.png)

Issued a production build with `yarn build && yarn serve` and opening up `http://localhost:9000` yelds the same result.

- Took the reproduction a bit further and created a new component called `ImageGallery_V2` inisde `src\components` with the following content:
```javascript
import React from "react"
import { useStaticQuery,graphql } from 'gatsby'
import Gallery from "react-grid-gallery"

const ImageGallery_V2 = () => {
  const multipleImages=useStaticQuery(graphql`
  {
    allFile(filter: {ext: {eq: ".jpg"}}) {
      edges {
        node {
          name
          publicURL
        }
      }
    }
  }
  
  `)
  const {allFile} = multipleImages
  const IMAGES= allFile.edges.map(item=>{
    return{
      src:item.node.publicURL,
      thumbnail:item.node.publicURL,
      thumbnailWidth: 320,
      thumbnailHeight: 174,
      caption: `a random caption for ${item.node.name}`,
    }
  })
  
  return (
    <div>
    <Gallery enableImageSelection={false} images={IMAGES} />
    </div>
  )
}

export default ImageGallery_V2
```

- Created a new page inside the `src\pages` folder called `page-2.js` and imported the component above.
- Issued `yarn develop`, waited for the build to complete and opened up `http://localhost:8000/page-2` i'm presented with the following:
![pmarxbraun_3](https://user-images.githubusercontent.com/22988955/73557778-bb115c80-4449-11ea-8569-8ac69dbe733b.png)

- The same outcome will present itself if instead of development mode i switch to production mode with `yarn build && yarn serve`.

Feel free to provide feedback so that we can close this issue, or continue to work on it until we find a suitable solution.

**Comment by pmarxbraun** [comment]
@jonniebigodes thanks so much ! Both solutions work like a charm :-)

**Comment by jonniebigodes** [comment]
@pmarxbraun no need to thank, glad that i was able to help you solve your issue. Feel free to close this issue when you're able.
