### ISSUE TITLE
url-loader is missing

### ISSUE THREAD

**Issue by tleunen** [gatsbyjs/gatsby#209]
Webpack uses the url-loader to load the `woff` fonts, but the package is missing from the dependencies
https://github.com/gatsbyjs/gatsby/blob/master/lib/utils/webpack.config.js#L203-L207

**Comment by KyleAMathews** [comment]
Ooops :-| want to add a PR to fix this?

**Comment by tleunen** [comment]
Thanks Kyle, sorry. I was very busy this weekend :/

**Comment by KyleAMathews** [comment]
No worries :-)

**Comment by abenjamin765** [comment]
This seems to still be an issue...

**Comment by zauni** [comment]
Hello @abenjamin765 

which error messages do you get? Because the url-loader dependency is in v1 and v2 of gatsby:

v1: https://github.com/gatsbyjs/gatsby/blob/44b0c231eeaf94cc6f861e3d078daccc3d36a776/packages/gatsby/package.json#L111

v2: https://github.com/gatsbyjs/gatsby/blob/2c908b60771fe38a47be527d60c44569af41d7b4/packages/gatsby/package.json#L127

The url-loader dependency is no longer in the root package.json file, but in the `packages/gatsby/package.json` file. Maybe you can add a bit more about your environment and which versions you are using.
