### ISSUE TITLE
   TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by lawwantsin** [gatsbyjs/gatsby#20920]
Why is there no way to debug GraphQL if it doesn't load on start?
TypeError: Cannot read property 'match' of undefined with no line numbers is not a useful error.  
I've been on this bullshit for hours.  There's no problem exxcept Gatsby can't keep relevant line numbers.  Must be busy with all that interconnectedness.
I quit Gatsby!

**Comment by danspratling** [comment]
There are plenty of users willing to help and potentially fix errors which will cause substantial issues for users of Gatsby, but in order to do so they need clear descriptive issues to work with.

Unfortunately, this is not clear what's causing your error. As this seems more like venting frustrations than attempt to resolve the issue, i'll close this bug. If you can provide a more substantial error report, we can look into the potential issue.

**Comment by lawwantsin** [comment]
Haha.  Damn right it's venting.  Fix your software.  These errors are a black box.

**Comment by wolfeidau** [comment]
We are getting the same error on our builds of gatsby.

```
2:22:51 PM: failed Building production JavaScript and CSS bundles - 11.865s
2:22:51 PM: error Generating JavaScript bundles failed
2:22:51 PM: Cannot read property 'match' of undefined
```

Looking for any tips on how to resolve it, this is only happening when we build in netlify at the moment. Local builds are 👍

**Comment by hfellerhoff** [comment]
I'm currently using NetlifyCMS + Gatsby, and this error started occurring when I removed some template files from the NetlifyCMS + Gatsby starter. I continued to remove references to that removed file from the CMS config.yml and the CMS preview files, and all of the sudden it worked.

I doubt that'll help anyone else, but it's better than nothing. Good luck in figuring it out!

**Comment by rachanakashyap** [comment]
In my case, this error message was a red herring from a GraphQL issue. 'title' and 'keywords' were required values in my frontmatter. Ensuring that my Markdown files had them fixed the error!

**Comment by AntonioRedondo** [comment]
Having the same error when running `npm run dev`:

![image](https://user-images.githubusercontent.com/5444421/75766945-da95f080-5d39-11ea-9315-5212db98a3ee.png)

**Comment by veksen** [comment]
Honestly wishing the Gatsby team could consider this an actual problem @KyleAMathews, as this error is several months old and still plaguing users. Black box error with no descriptive error or feedback.

It happens on production (Netlify), but not on development, neither as a `build` locally.

This issue is the first link on Google for me, at the moment. If you have a redirection, or a duplicate, it would be awesome to link to it so users know what/where to follow up, if a fix is to be made.
