### ISSUE TITLE
Unable to create redux store with gatsby's state

### ISSUE THREAD

**Issue by aeneasr** [gatsbyjs/gatsby#2098]
I want to create a new redux store (similar to [the redux example](https://github.com/gatsbyjs/gatsby/tree/master/examples/redux)) that contains *all data* from gatsby's internal redux store. So basically instead of this:

```
import { createStore as reduxCreateStore } from "redux"

const reducer = (state, action) => state

const initialState = { foo: 0 }

const createStore = () => reduxCreateStore(reducer, initialState)
export default createStore
```

I want this:

```
import { createStore as reduxCreateStore } from "redux"

const reducer = (state, action) => state

const initialState = // inject the gatsby store here

const createStore = () => reduxCreateStore(reducer, initialState)
export default createStore
```

So far, I was unable to figure out how this works as I only have access to the redux store in the Node API but not the SSR nor Browser API.

**Comment by Chuloo** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues as many of them have already been resolved with the latest updates or explained in a previous issue.

Feel free to [open a new one](https://github.com/gatsbyjs/gatsby/issues/new/choose) if you still experience this problem or a similar one! 👍
