### ISSUE TITLE
GraphQL for a single pdf file

### ISSUE THREAD

**Issue by brandontb12** [gatsbyjs/gatsby#21053]
I found documentation for querying all pdf files by using the allFile type, but I want to query a single pdf file. I haven't been able to find any documentation on querying a single pdf file. This is what I have tried so far but I haven't had any luck.

const data = useStaticQuery(graphql `
        query {
            pdf: file(base: { eq: "resume.pdf" }) {
                publicURL
            }
        }
    `)

"a<href={this.props.data.pdf}>a"

**Comment by classicmatsuo** [comment]
@brandontb12 try this:
`query {
  allFile(filter: { base: { eq: "resume.pdf" } }) {
    edges {
      node {
        publicURL
      }
    }
  }
}`

**Comment by brandontb12** [comment]
I was able to get further with that query! Unfortunately, {this.props.data.allFile.edges.node.publicURL} can't find publicURL, but it the edges and node no longer throw an error.

**Comment by jonniebigodes** [comment]
@brandontb12 i've picked up on your issue and based on the information you mentioned in the description i'm going to detail a possible solution for your case. This will extrapolated from the information available.

- Created a new Gatsby website based on the hello world starter.
-  Installed `gatsby-source-filesystem` 
- Changed `gatsby-config.js` to the following:
```javascript
module.exports = {
  /* Your site config here */
  plugins:[
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `data`,
        path: `${__dirname}/src/data/`,
      },
    },
  ]
}
```
- Created the `src\data` folder and copied over a sample pdf file called `a_random_example.pdf`
- In my `src\pages\index.js` i changed it to the following:
```javascript
import React from "react"
import { useStaticQuery, graphql } from "gatsby"
export default () => {
  const myexamplePdf = useStaticQuery(graphql`
    {
      pdf: file(name: { eq: "a_random_example" }) {
        name
        extension
        publicURL
      }
    }
  `)
  return (
    <div >
      <h1>example with a single pdf</h1>
      <a href={myexamplePdf.pdf.publicURL}><p>{myexamplePdf.pdf.name} without download</p></a>
      <a href={myexamplePdf.pdf.publicURL} download><p>{myexamplePdf.pdf.name} with download</p></a>
    </div>
  )
}

``` 
I'm fetching a single file, this time the pdf file i've mentioned and adding two links, the first one will display the pdf content and the second one will allow the pdf download. A small caveat regarding the second one. With the `gatsby-source-filesystem` package, the filename will be changed into `name-of-file-uuid.pdf`.
I've issued `yarn develop` waited for the build process to complete and opening up `http://localhost:8000` i'm presented with the following:

![brandontb12_file_1](https://user-images.githubusercontent.com/22988955/73554490-b5187d00-4443-11ea-9a9d-46914538b97c.png)

As you can see in the left side is the "page" and on the right side the pdf being displayed.

Feel free to provide feedback so that we can close this issue, or continue to work on it until we find a suitable solution.

**Comment by brandontb12** [comment]
I have gatsby-source-filesystem installed.
This is in my gatsby-config

``module.exports = {
  plugins: [
    {
      resolve: `gatsby-source-filesystem`,
      options: {
          name: `files`,
          path: `${__dirname}/src/assets/files`
      }
    },
  ],
}``

I have a `src\assets\files` folder with `resume.pdf` inside.

In my `src\components\example.js` I have the following

`export default () => {`
`const data = useStaticQuery(graphql `
`{`
`pdf: file(name: { eq: "resume" }) {`
`name`
`extension`
`publicURL`
`}`
`}`
`)`
`return (`
`<Example data={data}/>`
`)`
`}`



`class Example extends React.Component`
`    render() {`
`return (`
`<a href={this.props.data.pdf.publicURL} target="_blank">{this.props.data.pdf.name}</a>`
`);`
`}`
`}`

Unfortunately, I keep getting Cannot read property 'name' of null. Same with 'publicURL'.

Sorry about my format, this is the second time I've posted comments on github.

**Comment by classicmatsuo** [comment]
@brandontb12 try updating your `src\components\example.js` file to this. worked for me.

```javascript
import React from "react"
import { useStaticQuery, graphql } from "gatsby"

export default () => {
  const data = useStaticQuery(graphql`
    {
      pdf: file(name: { eq: "resume" }) {
        name
        extension
        publicURL
      }
    }
  `)
  return (
    <Example data={data}/>
  )
}

class Example extends React.Component {
  render() {
    return (
      <a href={this.props.data.pdf.publicURL} target="_blank">{this.props.data.pdf.name}</a>
    );
  }
}

```

you can also post a link to your repo if you'd like

**Comment by jonniebigodes** [comment]
@brandontb12 if you can please make a reproduction following [these steps](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/), so that it can be better looked at, with all the code you're using and files, but one thing, for the resume, it would be best if you created a dummy pdf file with some content, to avoid having your personal information be displayed while this issue is being triaged. For instance, you can use [this](https://doggoipsum.com/) for instance to generate the content, like i used above.

**Comment by brandontb12** [comment]
Finally got it to work, thanks for all of the help @jonniebigodes & @classicmatsuo! Switched my example.js to the most recent post and re-ran gatsby develop and it worked like a charm.

**Comment by jonniebigodes** [comment]
@brandontb12 ok, no need to thank, glad to hear it, feel free to close this as it's fixed if you don't mind.
