### ISSUE TITLE
Inconsistent CSS on serving production build on S3

### ISSUE THREAD

**Issue by knowBalpreet** [gatsbyjs/gatsby#21076]
I am seeing different results when pushing production build on s3 with respect to when doing `gatsby serve`. During build creation, I see a bunch of mini-css-extract-plugin warnings. Attaching screenshots for reference. I have also tried to extend webpack config to enable `ignoreOrder` in mini-css-extract-plugin. 

Output with S3:
<img width="1437" alt="Screenshot 2020-01-31 at 11 49 02 AM" src="https://user-images.githubusercontent.com/19731500/73517263-fd727380-4420-11ea-96db-82565e38b7d5.png">

Output with `gatsby serve` on server: 
<img width="1437" alt="Screenshot 2020-01-31 at 11 51 41 AM" src="https://user-images.githubusercontent.com/19731500/73517265-fd727380-4420-11ea-8785-306572ce2b82.png">

Thanks in advance!

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction
