### ISSUE TITLE
[gatsby-plugin-preload-fonts] Skip route scraping

### ISSUE THREAD

**Issue by jacobrienstra** [gatsbyjs/gatsby#21111]
### Summary

I was wondering if it would be possible to use the preload fonts feature without having to scrape every page. 

### Motivation

I have about 2K pages in my site and only 3 fonts, all of which are used on every page. So it seems an unnecessary overhead to crawl every route, especially when I'll be adding pages fairly regularly, and will want the fonts automatically preloaded on those pages without running the script. 

I can load the fonts in gatsby-broswer or gatsby-ssr, but I've searched high and low and can't figure out how to automatically include preload links to the hashed font files programmatically. Is there a way of getting these without using Puppeteer? I haven't familiarized myself with the webpack process yet.

**Comment by jamessimone** [comment]
If you only have three fonts, consider downloading the font files themselves and doing the preload yourself. An example repo that does this to great effect is the Third And Grove site: https://github.com/thirdandgrove/thirdandgrove-com-gatsby/blob/431e99bcfeec7cae8294d73653c8e38d2ac1c61e/src/components/seo.js

You don’t have to implement preloading the way they did; I find it easier to just make a list of the font names and their location and then to just map over that list in gatsby-ssr.

If you don’t have access to the font files without using remote sources, this won’t help you ... but otherwise it should definitely do the trick!

**Comment by LekoArts** [comment]
Thank you for opening this!

As James said I'd also recommend using our SSR APIs or something like React-Helmet + `static` folder to preload the fonts.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
