### ISSUE TITLE
[Plugin] Add server-side rendering capability for Material-UI v1

### ISSUE THREAD

**Issue by kripod** [gatsbyjs/gatsby#2116]
Considering that [Material-UI](https://github.com/callemall/material-ui) is a fairly large React UI framework with almost 30,000 stars on GitHub, I think it would be reasonable to support [server-side rendering](https://material-ui-1dab0.firebaseapp.com/guides/server-rendering) of their upcoming components.

**Comment by whmountains** [comment]
Why does Material-UI need special support?  Isn't everything in Gatsby pre-rendered by default?

**Comment by whmountains** [comment]
Oh, I see that Material-UI uses JSS, so server-side rendering won't work out of the box.  `gatsby-plugin-jss` should do the job.

**Comment by KyleAMathews** [comment]
Yup, looks like we're covered already!

**Comment by oliviertassinari** [comment]
Sweet :)

**Comment by kripod** [comment]
For anyone wondering about how to make the integration possible:

1. Install `gatsby-plugin-jss` and add it to the project's `gatsby-config.js` file
2. Use The `MuiThemeProvider` component of Material-UI with the `sheetsManager={new Map()}` attribute specified

**Comment by oliviertassinari** [comment]
Material-UI now hosts an official integration with Gatsby in [/examples/gatsby](https://github.com/mui-org/material-ui/tree/v1-beta/examples/gatsby).

**Comment by IljaDaderko** [comment]
@kripod Hi, I've followed those two steps you mentioned, but my ui is still flickering in terms of MU components, are these two the only steps needed with current gatsbyjs and MU v1?

**Comment by kripod** [comment]
After all, adding SSR support for Material-UI v1 is not even nearly as straightforward as utilizing `gatsby-plugin-jss`.

I think we should consider opening this issue again and make an official plugin based on the example at https://github.com/mui-org/material-ui/tree/master/examples/gatsby.

**Comment by cpboyd** [comment]
Anyone trying to use @oliviertassinari's example with Gatsby v2: Note that it uses `pageContext` (which Gatsby v1's `pathContext` was renamed to in v2)

Further, since material-ui uses `MuiThemeProvider` rather than standard jss's `ThemeProvider`, I don't think that `gatsby-plugin-jss` is a straight drop-in.

**Comment by cpboyd** [comment]
One more thing: the example uses a `export default` from `getPageContext`...

Perhaps due to the v2 changes regarding ES6 & CommonJS separation, you'll need to use `getPageContext.default()`

**Comment by oliviertassinari** [comment]
@cpboyd When building the Material-UI example integration with Gatsby, I have started using `gatsby-plugin-jss`. But It doesn't work, I ended up with a custom solution. The logic can always be abstracted away into a plugin, but it's fairly simple. I'm not 💯 % convinced people need it.

I didn't know Gatsby was working on a v2. It would be good to update our example once it's released.

**Comment by natterstefan** [comment]
Hi @cpboyd,

I have not yet tested @oliviertassinari's example with gatsby@v2, but according to [their latest example it](https://github.com/mui-org/material-ui/tree/master/examples/gatsby) should be possible as package.json says `"gatsby": "latest",` doesn't it?

> Perhaps due to the v2 changes regarding ES6 & CommonJS separation, you'll need to use require() syntax (rather than import) and getPageContext.default() in gatsby-ssr.

Have you tested it?

I have also [issues to ssr my material-ui page](https://github.com/natterstefan/react-trello-multiboard-page/tree/8c1823cf50a36e13c867a88f491a5312caa48ff8). as soon as it is rehydrated in the client (or people start clicking) it works...

**Comment by cpboyd** [comment]
@oliviertassinari Your example was great!  And even follows the new [v2 layout suggestions](https://next.gatsbyjs.org/docs/migrating-from-v1-to-v2/#update-layout-component) by utilizing the `withRoot()` wrapper.  I'd seen some other examples that had placed the `MuiThemeProvider` within the old layout component.

The only real changes needed are renaming `pageContext` (I just used `muiContext`) and then using the `require()` syntax within the `gatsby-ssr.js`

@natterstefan I'm not completely familiar with how NPM & yarn handle versioning, but I think "latest" still corresponds to v1, as v2 has only had beta releases thus far.  Similarly, I'm not entirely sure why the `import` statements didn't work for me, but I know that changing them to `require()` resulted in it working as expected.  I'm just making note of what changes I had to make, in case anyone else winds up here having trouble with v2.

**Comment by natterstefan** [comment]
Hi @cpboyd,

> I'm not entirely sure why the import statements didn't work for me, but I know that changing them to require() resulted in it working as expected. 

I think this is because of this part here of the migration guide: [Convert to either pure CommonJS or pure ES6](https://next.gatsbyjs.org/docs/migrating-from-v1-to-v2/#convert-to-either-pure-commonjs-or-pure-es6). Because moving to `require` in `gatsby-ssr.js` solved the issue on my side as well.

But only when [I did not remove the SSR css styles](https://github.com/natterstefan/react-trello-multiboard-page/commit/ad7ef5dc1f8ed6307ee7626943305e382356bc2a#diff-ebcf83e42f39d4e7da065fc9c206cc46R19), which is contrary to what the [MaterialUI documentation](https://material-ui.com/guides/server-rendering/#the-client-side) says. But then it works. This requires further investigation, but right now I am happy with this "hack".

**Comment by cpboyd** [comment]
@natterstefan I'd seen the CommonJS/ES6 stuff in the migration guide but couldn't find it when making my prior posts.

I hadn't noticed any issues with my layout leaving everything in `componentDidMount()`, but it'd probably be safest to move it to `gatsby-browser.js` like in [gatsby-plugin-jss](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-jss/src/gatsby-browser.js) so that it doesn't accidentally remove the styles from the server version.

**Comment by natterstefan** [comment]
Thanks @cpboyd for the hint, I will definitely check it out and let you know if it works.

**Comment by nareshbhatia** [comment]
I tried the Material UI Gatsby example with gatsby@next, but it throws the following error:

```
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/narbhati/projects/material-ui/examples/gatsby/.cache/develop-static-entry.js:
Support for the experimental syntax 'objectRestSpread' isn't currently enabled (72:5):

  70 |
  71 |   const htmlElement = React.createElement(Html, {
> 72 |     ...bodyProps,
     |     ^
  73 |     body: ``,
  74 |     headComponents: headComponents.concat([
  75 |       <script key={`io`} src="/socket.io/socket.io.js" />,

Add @babel/plugin-proposal-object-rest-spread (https://git.io/vb4Ss) to the 'plugins' section
of your Babel config to enable transformation.
```

Adding `plugin-proposal-object-rest-spread` to that example's `.babelrc` does not help. Don't know where to go from here.

**Comment by oorestisime** [comment]
FWIW i am having several problems with the material-ui integration as well, only for me it happens on build and not on develop.
Details here https://github.com/mui-org/material-ui/issues/12649

**Comment by natterstefan** [comment]
Hi @oorestisime, I had similar issues as you. I kinda solved it (with some workarounds, mentioned earlier in this issue) here: https://github.com/natterstefan/react-trello-multiboard-page. Maybe this helps you, at least a little.

**Comment by cpboyd** [comment]
@natterstefan Have you had any issues with the recent v2 RC?

My project now renders fine in `develop` mode, and the SSR builds the HTML successfully...
But once the Javascript rendering takes over, the styles get messed up.

**Comment by oliviertassinari** [comment]
@cpboyd have you checked out the example we host on Material-UI ?

**Comment by oorestisime** [comment]
@cpboyd  i fixed my issue by removing the withRoot call on all but root component (like index.jsx or another page just not in the components). It was causing everything to be re-rendered multiple times otherwise. now everything works good for me in develop and build. I am willing to PR a documentation warning or notice on that if anyone could confirm on their side that this is the case for them as well (or if someone for material-ui can pitch in and say that this actually makes sense :) )

@natterstefan thanks, i had a look at your repo before and saw the hack you did with not removing server side injected CSS but didn't fix the issue for my case unfortunately so i continued to debug

**Comment by nareshbhatia** [comment]
I created a [starter template for Material-UI](https://github.com/nareshbhatia/gatsby-starter-material-ui) using Gatsby v2 and Material-UI v3. This is based on the example hosted on the Material-UI site. I have not run into the issue with `withRoot()` even though I am using it in root components as well as layout components - in develop and in build. You can see the live site [here](https://gatsby-starter-material-ui.netlify.com/). While @oorestisime's comments make sense, I wonder why I am not running into this issue!!
