### ISSUE TITLE
Depending on the Gatsby version, the Netlify CLI UI breaks (long standing issue)

### ISSUE THREAD

**Issue by tr1s** [gatsbyjs/gatsby#21251]
## Description

I've been having this UI issue for so long now, I posted the issue in [Netlify's CLI github issues list](https://github.com/netlify/cli/issues/698) as well. **Please close if this feels unrelated to Gatsby, and is solely Netlify's problem to fix.**

**Issue:** The Netlify CLI UI get's cut off by an "In Progress" bar that just sits there even though it's completed, cutting off the green "Server now ready on localhost:8888" section.

This issue doesn't happen when running the `gatsby develop` command, but does happen when running `netlify dev`, which in turn runs `gatsby develop`. I'm posting here in case anyone here might have some insights into the UI issue based on the two versions of Gatsby I outline below.

I decided to get to the bottom of it and figure out when this this issue starts... **It doesn't happen on `gatsby@2.15.17`, but it does happen on `gatsby@2.16.0` and later**. But `gatsby@2.16.0` is the very specific moment things break.

---

Here's a screenshot on `gatsby@2.15.17`, running `netlify dev` when things look normal:

<img width="1136" alt="Hyper 2020-02-06 at 16 37 19@2x" src="https://user-images.githubusercontent.com/19172250/73983995-a6c7d680-4905-11ea-8180-2cc51d7e34da.png">
<img width="1136" alt="Hyper 2020-02-06 at 16 37 25@2x" src="https://user-images.githubusercontent.com/19172250/73983997-a6c7d680-4905-11ea-8d5d-ed3c5ff84cb9.png">

Here's a screenshot on `gatsby@2.16.0`, running `netlify dev` when things look broken:

<img width="1136" alt="Hyper 2020-02-06 at 16 57 33@2x" src="https://user-images.githubusercontent.com/19172250/73984130-f7d7ca80-4905-11ea-877a-c457c5c44393.png">

---

### Environment

```
  System:
    OS: macOS 10.15.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.6.0 - ~/.nvm/versions/node/v13.6.0/bin/node
    npm: 6.13.4 - ~/.nvm/versions/node/v13.6.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 79.0.3945.130
    Safari: 13.0.5
  npmPackages:
    gatsby: ^2.16.0 => 2.16.0
    gatsby-plugin-catch-links: ^2.1.25 => 2.1.25
    gatsby-plugin-manifest: ^2.2.41 => 2.2.41
    gatsby-plugin-offline: ^3.0.34 => 3.0.34
    gatsby-plugin-react-helmet: ^3.1.22 => 3.1.22
    gatsby-plugin-sass: ^2.1.28 => 2.1.28
    gatsby-plugin-sharp: ^2.4.5 => 2.4.5
    gatsby-remark-images: ^3.1.44 => 3.1.44
    gatsby-remark-relative-images: ^0.2.3 => 0.2.3
    gatsby-source-contentful: ^2.1.85 => 2.1.85
    gatsby-source-filesystem: ^2.1.48 => 2.1.48
    gatsby-transformer-remark: ^2.6.50 => 2.6.50
    gatsby-transformer-sharp: ^2.3.14 => 2.3.14
  npmGlobalPackages:
    gatsby-cli: 2.8.27
```

```
Gatsby CLI version: 2.8.27
Gatsby version: 2.16.0
  Note: this is the Gatsby version for the site at: /Users/tris/Sites/tris/tris-gatsby
```

`netlify-cli/2.31.0 darwin-x64 node-v13.6.0`

**Comment by jlengstorf** [comment]
I posted this on https://github.com/netlify/cli/issues/698 as well, but just to surface this in both places:

this is happening on the repo I'm using for my Frontend Masters "Introduction to the JAMstack" course, which is scheduled to be released soon

if we could get this fixed before that goes live, that would probably help us avoid a lot of confusion

**Comment by erquhart** [comment]
A bit of research:

- this bug of Gatsby cli eating previous external logs was introduced in https://github.com/gatsbyjs/gatsby/pull/14973
- it _might_ be due to this component, not positive: https://github.com/gatsbyjs/gatsby/pull/14973/files#diff-b4c4175f0cc66bb26a4dc466da3f6319 (cc/ @pieh)
- is definitely related to ink, either the library itself or Gatsby's implementation of it
- may also be related to #19314
- setting `GATSBY_LOGGER` to `yurnalist`, as suggested in #19314 by @jlengstorf, is an effective workaround (not a solution, though)

**Comment by vladar** [comment]
May be also related: #19658

**Comment by erquhart** [comment]
Not stale

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by pieh** [comment]
https://github.com/netlify/cli/blob/master/src/utils/command.js#L99 well here's netlify CLI trying to output directly to stdout, which `ink` supposed to have sole ownership of. This will make `ink` try to fight it.

It's not obvious how to solve this because to my understanding `gatsby` is spawned in separate process that inherit same stdio as `netlify dev` process?

**Comment by pieh** [comment]
In general `ink` was introduced because of issues when multiple "interactive" elements would fight for control over stdout which would result in flashing progress bars - something like this:
![example](https://user-images.githubusercontent.com/71047/51065658-e7e29f80-15ba-11e9-8840-0c2af9c3d3a7.gif)

This is similar case, just here is something in completely different process which can't be reconciled (netlify CLI tries to append to stdout, but because this is "interactive" part of gatsby output - where we have spinners etc - parts of it will be cleared)

**Comment by pieh** [comment]
While I don't suggest to make this change in netlify CL master, as experiment, I I do wonder if changing https://github.com/netlify/cli/blob/master/src/utils/command.js#L99 to `stderr` from `stdout` would result in output not being cut 🤔 

Other idea (more involved one) is to investigate `ink` internals and possibly make improvements there to prevent issues like that

**Comment by pieh** [comment]
Here's issue in `ink` about this https://github.com/vadimdemedes/ink/issues/162

**Comment by LekoArts** [comment]
Closing out as stale.
