### ISSUE TITLE
Fails to generate post thumbnails

### ISSUE THREAD

**Issue by expatguideturkey** [gatsbyjs/gatsby#21270]
I get build error for thumbnail null  https://prnt.sc/qyvids 
Whereas they exist in my WordPress posts and also inside the static folder. It shows null value for featured image every time on different posts. 

Has anyone experience this problem and how did you fixed it. Please advise.

**Comment by expatguideturkey** [comment]
I updated the code to below but still it sometimes fails to build thumbnail of posts.

  ```
{post.node.featured_media ? (
      <div>
      <Img resolutions={post.node.featured_media.localFile.childImageSharp.resolutions} />  
      </div>
    ) : null}
```

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction
