### ISSUE TITLE
Can't build with on Ubuntu or Windows.

### ISSUE THREAD

**Issue by vsolanogo** [gatsbyjs/gatsby#21286]
## Description

Can't build on Ubuntu on Windows

### Steps to reproduce

Builds fine on MacOs. Can't build on Windows at all. Builds on Ubuntu only without --prefix-paths, okay without it.
I need to build it with --prafix-paths
I can run development on all the systems.
### Actual result

![Screenshot (195) - Copy](https://user-images.githubusercontent.com/13319110/74076604-b76d6f00-4a21-11ea-87a9-74f5333647e2.png)
![Screenshot (196) - Copy](https://user-images.githubusercontent.com/13319110/74076606-ba685f80-4a21-11ea-8539-f4ef002a8fc7.png)

### Environment

Ubuntu 18.04.3, Windows Version 10.0.18363.592

**Comment by jonniebigodes** [comment]
@vsolanogo a couple of quick questions:
1- In MacOS are you using the same file/folder structure?
2- What happens if get the Gatsby site into another folder, build it there and copy the contents of the public folder to what it seems your apache folder? 

I'm asking these questions, more specifically the second one because it might be due to permissions and i tend to avoid developing/building directly in the folder that will be used to host the site. In the past i've used both ngix and apache to test out Gatsby and i usually tend to put there the "finished product". But if you're willing please create a reproduction following [these steps](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/) and i can take a look at it, as i'm running a win 10 machine and i have wsl with ubuntu

**Comment by piyushkantm** [comment]
Are you using sharp plugins and sharp is not properly installed in your windows/mac??

**Comment by vsolanogo** [comment]
> structure



> @vsolanogo a couple of quick questions:
> 1- In MacOS are you using the same file/folder structure?
> 2- What happens if get the Gatsby site into another folder, build it there and copy the contents of the public folder to what it seems your apache folder?
> 
> I'm asking these questions, more specifically the second one because it might be due to permissions and i tend to avoid developing/building directly in the folder that will be used to host the site. In the past i've used both ngix and apache to test out Gatsby and i usually tend to put there the "finished product". But if you're willing please create a reproduction following [these steps](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/) and i can take a look at it, as i'm running a win 10 machine and i have wsl with ubuntu

Thanks for help! Folder structure of the project is the same, it's cloned from git repo. Or you're asking about something else?

It Throws same error. Firstly i did build it in home folder of user.

I suspect on Ubuntu server it has to do somthing with next part of code, i use gatsby image and and receive images from static query like : 

`
export default () => (
  <StaticQuery
    query={graphql`
      query {
        allFile(filter: { relativeDirectory: { eq: "carousel" } }) {
          edges {
            node {
              id
              name
              childImageSharp {
                fluid {
                  ...GatsbyImageSharpFluid
                }
              }
            }
          }
        }
      }
    `}
    render={data => <Component data={data} />}
  />
)
`

**Comment by vladar** [comment]
What is your version of `gatsby`? You can run `gatsby info --clipboard` and then paste the result here.
