### ISSUE TITLE
TypeError: typeComposer.addInterface is not a function

### ISSUE THREAD

**Issue by kamleshchandnani** [gatsbyjs/gatsby#21343]
## Description

I'm using `gatsby-theme-blog` and after I updated my dependencies the project doesn't just stopped running and throws error `TypeError: typeComposer.addInterface is not a function`. In suspect the issue in `gatsby-node.js` but unable to mitigate what is the exact issue since it's difficult to identify from the error message. This issue was not happening before the dependencies upgrade.

### Steps to reproduce

- Head to [this repo](https://github.com/kamleshchandnani/awesome-interview-process)
- Clone `git@github.com:kamleshchandnani/awesome-interview-process.git`
- run `yarn`
- run `yarn develop`
Attaching the screenshot for more reference
<img width="681" alt="Screenshot 2020-02-10 at 8 55 35 PM" src="https://user-images.githubusercontent.com/11384858/74163026-bf0e5d00-4c47-11ea-93d0-e72cb4227787.png">

### Expected result

The project should build schema and run in development mode

### Actual result

The build failed on schema building

### Environment
**System:**
    OS: macOS 10.15.2
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Shell: 5.7.1 - /bin/zsh
**Binaries:**
    Node: 12.14.0 - ~/.nvm/versions/node/v12.14.0/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.14.0/bin/npm
**Languages:**
    Python: 2.7.16 - /usr/bin/python
**Browsers:**
    Chrome: 79.0.3945.130
    Safari: 13.0.4
**npmPackages:**
    gatsby: 2.19.14 => 2.19.14
    gatsby-plugin-google-analytics: 2.1.35 => 2.1.35
    gatsby-plugin-manifest: 2.2.41 => 2.2.41
    gatsby-theme-blog: 1.2.42 => 1.2.42

**Comment by pieh** [comment]
This line https://github.com/kamleshchandnani/awesome-interview-process/blob/388bf0708c14392c07d3c5daaef2fb8957b6cc14/gatsby-node.js#L4 here should be `interface BlogPost @nodeInterface` (to unblock you).

But the error message is not great here and something we could fix

**Comment by kamleshchandnani** [comment]
Whoop that fixed the problem. Thanks for the quick response @pieh 🙌

Curious in which version this got changed? This was working on 2.15.x. Also is this documented somewhere? I would like to understand about the decision to move away from `implements node` to just the `@nodeInterface` directive. It's confusing because

```
type BlogPost @nodeInterface {
 date: Date @dateformat
}
type MdxBlogPost implements Node @infer {
 fields: MdxBlogPostFields
}
type MdxBlogPostFields @infer {
 index: Int
}
```
`BlogPost` just uses directive but `MdxBlogPost` uses `implements Node` and then `MdxBlogPostFields` again uses directive.

**Comment by vladar** [comment]
The issue is that `BlogPost` is by itself an interface (not an object type):

```graphql
interface BlogPost @nodeInterface {
    id: ID!
    title: String!
    body: String!
    slug: String!
    date: Date! @dateformat
    tags: [String]!
    keywords: [String]!
    excerpt: String!
}
```
It is defined [here](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-theme-blog-core/gatsby-node.js#L48-L57). `@nodeInterface` is just a workaround in Gatsby for missing interface inheritance in GraphQL.

So ideally it would look like this:

```graphql
interface BlogPost extends Node {
}
```

But this is not supported in GraphQL yet (will be supported in one of the next versions).

Now back to what is going on in your case:

1. Your typing is syntactically correct (`type BlogPost implements Node`) so it doesn't produce a meaningful syntax error. 

2. Gatsby starts processing it: it takes the existing `BlogPost` type (defined in the `gatsby-theme-blog-core` as shown above) and tries to modify it according to your type defs.

3. Since your type definition is an object type, Gatsby tries to merge it assuming the existing definition is also an object type. But it is an interface.

4. So Gatsby tries adding `Node` interface to the existing `BlogPost` interface which is not supported by GraphQL yet, hence you get this error.

Ideally, we should add validation to make sure that new typedefs are the same as the existing one (only allow `interface` for interfaces and `type` for objects).

The fun part is that we have [this comment](https://github.com/gatsbyjs/gatsby/blob/1c495ee0d8d81791c3361bc905a04c6f086fa5e8/packages/gatsby/src/schema/schema.js#L1133-L1135):

```
      // We don't check if ast.kind matches composer type, but rely
      // that this will throw when something is wrong and get
      // reported by `reportParsingError`.
```

So I guess it works as expected? 😁 

If you are interested - the PR is welcome to add this kind of check and throw something more meaningful when this happens. I will be happy to assist you if you decide to tackle it.

**Comment by daugsbi** [comment]
This error also happens if you use `Reference` or `Entity` as a content model name, see also #29434.
