### ISSUE TITLE
Node schema validation

### ISSUE THREAD

**Issue by angeloashmore** [gatsbyjs/gatsby#2144]
The joi schema states the `internal.fieldOwners` property on a node must be an array, but based on the docs, it should be an object.

Since `internal.fieldOwners` should be a map defining the plugin owner for a node property, it looks like the schema needs to be updated.

#### Schema
https://github.com/gatsbyjs/gatsby/blob/0945d3dc2305798f8cf556e63f1dc5081340fc50/packages/gatsby/src/joi-schemas/joi.js#L38-L57

#### Docs
https://github.com/gatsbyjs/gatsby/blob/0945d3dc2305798f8cf556e63f1dc5081340fc50/docs/docs/node-interface.md
> ```
> // Stores which plugins created which fields.
> fieldOwners: Object,
> ```

**Comment by KyleAMathews** [comment]
Hmmm yeah you're right. The only reason it hasn't failed I guess is since we don't validate after adding fieldOwners. Could you update the schema?

**Comment by KyleAMathews** [comment]
Thanks for reporting the issue!

**Comment by angeloashmore** [comment]
Sorry for the late reply! Sure, I should have some time coming up where I can take a look at this.

**Comment by Chuloo** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues as many of them have already been resolved with the latest updates or explained in a previous issue.

Feel free to [open a new one](https://github.com/gatsbyjs/gatsby/issues/new/choose) if you still experience this problem or a similar one! 👍
