### ISSUE TITLE
jquery not detected when link in html.js or gatsby-ssr.js

### ISSUE THREAD

**Issue by KamranMaqbool** [gatsbyjs/gatsby#21507]
jquery cdn link and other .js files like main.js (which have jquery) but not detected 

1- i'am using CDN link and other's .js files in html.js file  like this 

![Screenshot from 2020-02-16 17-04-38](https://user-images.githubusercontent.com/53546053/74604322-b81b9a80-50de-11ea-8400-3c0d92d91402.png)

2- then i'am using same above liks use  in gatsby-ssr.js =>  setPostBodyComponents 
![Screenshot from 2020-02-16 17-01-08](https://user-images.githubusercontent.com/53546053/74604333-d41f3c00-50de-11ea-87e5-de7d001dc1fd.png)

after includes this files i'am go to our site and open inspect element (developer tool) and type `window.jquery` then give 'undefined' output

![Screenshot from 2020-02-16 17-23-08](https://user-images.githubusercontent.com/53546053/74604583-3711d280-50e1-11ea-8f80-6e45694a020a.png)

but when i'am using above these files in out layout.js then work's fine. 
![Screenshot from 2020-02-16 17-00-27](https://user-images.githubusercontent.com/53546053/74604600-54df3780-50e1-11ea-9c4b-569b2bf07ecb.png)

but some error are show in console like below.
![Screenshot from 2020-02-16 17-33-40](https://user-images.githubusercontent.com/53546053/74604913-75f55780-50e4-11ea-8959-965f9d77e281.png)

1- My Question is why not work these .js files in html.js and gatsby-ssr.js ?
2- but work in my layout.js file. why ?

**Comment by wardpeet** [comment]
Hi @KamranMaqbool!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a minimal reproduction. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could provide a minimal reproduction and we'll be able to take another look.

Thanks for using Gatsby! 💜

**Comment by KamranMaqbool** [comment]
@wardpeet what's the minimal reproduction ?

**Comment by jonniebigodes** [comment]
@KamranMaqbool the minimal reproduction is a compact version of your project with the packages that you're using and components that are involved in the issue so that the person that is willing to help you could have a clearer picture of what might be the issue and possibly help you fix it. When you're able follow [these steps](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/) and report back so that i can be better looked at. Sounds good?

**Comment by KamranMaqbool** [comment]
@jonniebigodes ok i understand.i will contact after create minimal reproduction of project
