### ISSUE TITLE
Creation of test sites for error testing

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#21564]
Summary

I'm proposing creating a test site with a known error. We'll use this site In a cluster of 5 usability tests, during which each user will clone the site and watch how well the error message helps them resolve the error. This is a continuation of the [Error Message Survey and Improvement Project RFC](https://github.com/gatsbyjs/rfcs/pull/37/files#diff-347573ff03d70265b4be97ab180ca491).

### Basic example

Here is the first error we'd like to test:
[#85910](https://github.com/gatsbyjs/gatsby/blob/239ac3970db28d2c13dbc49a536281a7c84ad07d/packages/gatsby-cli/src/structured-errors/error-map.js#L72)

### Motivation

In the last year, quite a few Gatsby error messages have become "structured errors," a term that means the error has an ID, a description, and tips on how to resolve it and/or report it. 

We want to measure how successful these error messages are at helping users resolve errors. 

Two bits of data we need in order to measure success:
1. Can the user resolve the error?
2. If yes, how much time does it take for the user to resolve the error? 

If the answer to question 1 is yes, and the answer to number two decreases over time, then we're succeeding.

So, in order to gather this data, we need test sites.

**Comment by LekoArts** [comment]
This intro is more or less tangential to your issue but wanted to write it out anyways:

What I've done for my error message PRs is cloning the hello-world starter and thinking about what errors people might run into / look into e.g. [this error parser](https://github.com/gatsbyjs/gatsby/blob/239ac3970db28d2c13dbc49a536281a7c84ad07d/packages/gatsby/src/query/error-parser.js) to see that we specifically target GraphQL errors. And then just experiment with that hello-world starter and some changes.

---

In order to find out how to reproduce the error:
- Sometimes the error message itself gives it away, in the case of `85910` the message is pretty clear on what happened
- If not, you should search for the ID in the Gatsby codebase and eventually you'll find where the error is called

For `85910` a realistic real-world example site would have two components with each a `useStaticQuery` hook in it in **one** file. This can easily happen when prototyping or wanting to place similar components in one file. The error message should prompt them to move one file or combine the two components.

**Comment by LekoArts** [comment]
The test suite exists now!
https://github.com/gatsbyjs/error-testing
