### ISSUE TITLE
feature(www): Add <link rel="alternate"> to www site metadata 

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#21566]
From the react helmet examples:

```jsx
    {locales.map((locale) => {
        <link rel="alternate" href="http://example.com/{locale}" hrefLang={locale} key={locale}/>
    })}
```

We can add the `<link rel="alternate" />` head [property](http://microformats.org/wiki/rel-alternate) to tell SEO that alternate versions of our page exists.

**Comment by bcye** [comment]
Is someone working on this? Else I would like to look into it :)

**Comment by jacquesporveau** [comment]
I took a look at this. I don't think there is a solid was to do this right now IMO.

I posted in the Gatsby slack:

Hey :wave: 

I am new here. Just picked up this issue: https://github.com/gatsbyjs/gatsby/issues/21566

The issue seems pretty straight forward once you get the locales that the website is being offered in but getting those is kind of tricky. I don't think they're able to be queried via GraphQL on a standard install.

After that it seems like Gatsby doesn't really make a lot of assumptions about how one manages their locales. It seems like you might get them via Contentful if you are using that service or you might roll something on your own like described here: https://github.com/gatsbyjs/gatsby/tree/561d33e2e491d3971cb2a404eec9705a5a493602/examples/using-i18n

As such I am not sure if there is a silver bullet solution that would work for everyone. At least something that I could implement without a more knowledge around the project.

I think a good feature could be potentially having locales available to be queried by GraphQL.

But... Maybe I am missing something. Anyone know of any easy way to get the locales that the site is being offered in?

I didn't get a response though. 

I am not working on this anymore but maybe this can be of help to you.

**Comment by bcye** [comment]
@jacquesporveau I thought this was concerning the https://gatsbyjs.org website, and not Gatsby as a whole (it's tagged www). And as far as I know, the Gatsby Site has localisation set up.

You're right, for Gatsby as a whole there isn't one way to do localisation yet (just wrote my own little implementation of it, maybe I'll publish it as a plugin).

**Comment by bcye** [comment]
I am gonna work on this then now :)

**Comment by tesseralis** [comment]
Hi @bcye, could we hold off on this for now? As the alternate language pages aren't available yet, we're not ready to have this tag implemented.

**Comment by bcye** [comment]
@tesseralis ok, I was already a little confused why I couldn't find out how to access a translated version of the gatsby site.

Just as some documentation for when this gets implemented, as I think I have found out how to do it:

[src/utils/i18n.js](https://github.com/gatsbyjs/gatsby/src/utils/i18n.js) contains the property `langCodes`. We can import this and add these lines to [src/site-metadata.js](https://github.com/gatsbyjs/gatsby/src/site-metadata.js):

```jsx
{langCodes.map((langCode) => {
        <link rel="alternate" href={`${siteUrl}/${langCode}${pathname}`} hrefLang={langCode} key={langCode}/>
})}

@tesseralis I can quickly write this up as a draft PR or hold off it.
```

**Comment by tesseralis** [comment]
@bcye please hold off on it for now. Supporting translations is in development right now so the code is in flux. I'll update this issue when this is ready to be implemented.

**Comment by jacquesporveau** [comment]
Ah thanks @byce, I didn't know the www prefix meant it was the gatsby org website. Thanks.

**Comment by bcye** [comment]
Yeah no worries, must have been really confusing to you
