### ISSUE TITLE
onCreateNode not running each build

### ISSUE THREAD

**Issue by amykapernick** [gatsbyjs/gatsby#21573]
# Summary
I'm creating a custom plugin, that creates nodes from json files sourced via `gatsby-source-filesystem`. But the `onCreateNode` function isn't being triggered each time I run the build, it only gets run if I clear the cache or change the `gatsby-config` file

## Relevant information

Because the function isn't running, the nodes aren't being generated each build and I get an error when trying to query the data.
This is the `gatsby-node` file in my plugin
```
async function onCreateNode({ node, loadNodeContent, createNodeId, createContentDigest, actions }) {
	const {createNode} = actions

	if (node.internal.type !== 'File') {
		return
	}

	const content = await loadNodeContent(node)

	let info = {
		id: `${node.sourceInstanceName}-${node.name}`,
		title: node.name,
		parent: `conferences-${node.name}`,
		internal: {
			contentDigest: createContentDigest(content),
			type: node.sourceInstanceName,
		}
	}
	createNode(info)
	console.log(`Created node for ${node.sourceInstanceName}/${node.relativePath}`)
}

exports.onCreateNode = onCreateNode

```

Not sure if I'm just not using it properly, or misunderstanding how I need to set this up

**Comment by vladar** [comment]
Hey, thanks for sharing this! Creating plugins definitely has some learning curve. So, some context first. 

Gatsby doesn't run `onCreateNode` every time intentionally. Under the hood, Gatsby has a cache of nodes which is persisted between builds.

So when you run build for the second time and try calling `createNode` Gatsby will compare `contentDigest` of a new node and the saved one with the same id. If they are the same - gatsby will not create a new node (and won't call `onCreateNode`).

But it shouldn't be a problem for you because your transformed nodes are also persisted. So the idea is that if the source node hasn't changed then the transformed node shouldn't change as well.

I think the problem is that you set a wrong `parent` value. It is supposed to be an `id` of the parent node. So replace this:

```js
parent: `conferences-${node.name}`,
```
with this:
```js
parent: node.id,
```

Another thing to consider is adding [createParentChildLink](https://www.gatsbyjs.org/docs/actions/#createParentChildLink). This is required to remove all of your derived nodes when the parent is removed.

Also, check out our docs on [how to create transformer plugins](https://www.gatsbyjs.org/docs/creating-a-transformer-plugin/)

Hope it helps!

**Comment by amykapernick** [comment]
So I understand that the file nodes don't get re-created, but while they are persisting, mine aren't. Even without linking to parent nodes, they still won't persist

If I clear the cache, the build works fine. But if I don't, the custom queries don't work anymore, the new nodes aren't available to query via graphql

Also, the parent node ids are correct, they link fine when the build works, and I've used the standard naming format so that I know which parent node I'm linking to. They're all automatically generated from the data and unique.

**Comment by vladar** [comment]
I tried `onCreateNode` from issue description on a local site. And changing `parent` to `node.id` fixed errors I saw in the console when running `develop` the second time.

But if the problem in your situation is not just about this error, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction] (and explain steps to reproduce in details). This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by amykapernick** [comment]
I created a minimal repo and confirmed the issue is still present - https://github.com/amykapernick/gatsb-createNodes-issue

When I initially run the build (`npm start`), it generates nodes for each file and the custom graphql nodes get created as well (see the allConferences and conferences queries)
![image](https://user-images.githubusercontent.com/15953185/75201947-cf284f80-57a4-11ea-8e90-b699678b0f2b.png)

But when I run `npm start` a second time, the file nodes seem to be persisting, they're still there and searchable, but because they haven't just been created, nothing triggers the creation of the custom nodes and I can no longer query for conferences in graphql, and they don't seem to persist the same way the file nodes do.
![image](https://user-images.githubusercontent.com/15953185/75202336-e156bd80-57a5-11ea-86fc-5766ad96703d.png)


If I clear the cache, it triggers the file nodes to be re-created, which triggers the custom nodes to create as well.

**Comment by KyleAMathews** [comment]
Thanks for the reproduction!

Under this line https://github.com/amykapernick/gatsb-createNodes-issue/blob/823d473b4a3c1f9335cc249a0729fb6bb8f6df68/plugins/gatsby-source-confengine/gatsby-node.js#L13

Add `parent: node.id,` and it should work

**Comment by amykapernick** [comment]
My understanding was that the parents were to link between nodes, is that not the case?

**Comment by KyleAMathews** [comment]
Right -- the new nodes you're creating are transformed from the File node so there's a parent/child relationship. If you don't specify the relationship, Gatsby doesn't know they should be kept around when the parent File node doesn't change so it gets garbage collected.

**Comment by amykapernick** [comment]
Ok, thanks that's working now
