### ISSUE TITLE
page-data//page-data.json 404 not found / failed to fetch

### ISSUE THREAD

**Issue by joebentaylor1995** [gatsbyjs/gatsby#21581]
Hi,

for somereason im my recent builds and only when running gatsby serve do i get the error:

`
prefetch.js:37 GET http://localhost:9000/page-data//page-data.json net::ERR_ABORTED 404 (Not Found)
`

What can be causing this?
is there a known fix?

Im not doing anything out of the extra ordinary

My setup:
`
  System:
    OS: macOS 10.15.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.10.0 - /usr/local/bin/node
    npm: 6.13.7 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 79.0.3945.130
    Firefox: 72.0.2
    Safari: 13.0.5
  npmPackages:
    gatsby: ^2.19.18 => 2.19.18 
    gatsby-plugin-alias-imports: ^1.0 => 1.0.5 
    gatsby-plugin-google-tagmanager: ^2.1.25 => 2.1.25 
    gatsby-plugin-layout: ^1.1.22 => 1.1.22 
    gatsby-plugin-manifest: ^2.2.41 => 2.2.41 
    gatsby-plugin-offline: ^3.0.35 => 3.0.35 
    gatsby-plugin-robots-txt: ^1.3 => 1.5.0 
    gatsby-plugin-sass: ^2.1.28 => 2.1.28 
    gatsby-plugin-sharp: ^2.4.5 => 2.4.5 
    gatsby-plugin-sitemap: ^2.2.27 => 2.2.27 
    gatsby-plugin-styled-components: ^3.1.19 => 3.1.19 
    gatsby-source-filesystem: ^2.1.48 => 2.1.48 
    gatsby-transformer-remark: ^2.6.52 => 2.6.52 
    gatsby-transformer-sharp: ^2.3.14 => 2.3.14 
  npmGlobalPackages:
    gatsby-cli: 2.8.30
`

**Comment by vladar** [comment]
Hi @joebentaylor1995 !

This sounds similar to #20160 Let's track the state of this problem in a single place to collect more context. I will close this one as a duplicate.

Also if you have a chance please prepare a [minimum reproduction][reproduction] so that we could start debugging it. It is rather hard to understand what is going on without some code at hand.

And thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction
