### ISSUE TITLE
Node.js vs Gatsby

### ISSUE THREAD

**Issue by LeuAlmeida** [gatsbyjs/gatsby#21596]
Hello,

Have any Node.js version that Gatsby doesn't work?

**Comment by herecydev** [comment]
https://www.gatsbyjs.org/docs/upgrading-node-js/#gatsbys-nodejs-support-policy

As of today that means anything **less** than node 8 will not be supported

**Comment by pieh** [comment]
We technically didn't drop our node 8 support yet (our telemetry data say that , but lot of dependencies that we don't directly control did (think dependencies of dependencies), so Gatsby *should* still work on Node 8, but because Node 8 reached end of life lots of packages already dropped it.

Also about 4-5% of our users used Node 8 in the last week which is another data point that tells us not to drop it just yet.
