### ISSUE TITLE
(docs) Add context to the existing Plugin README template

### ISSUE THREAD

**Issue by JQuinnie** [gatsbyjs/gatsby#21599]
## Summary

With the refactor of the Plugin README template into its own page (#21574) additional context should be added. This issue covers adding a quick blurb explaining a README and its purpose/goal for Plugin projects.

### Motivation

Help people creating Plugins make them more approachable to users!

### Draft the doc

- [ ] Update the doc with the above information

### Open a pull request

- [ ] Open a pull request with your work including the words "closes #[this issue's number]" in the pull request description

**Comment by laurieontech** [comment]
I'm not sure this is the best approach. We have an issue #20527 for creating a tutorial on writing a plugin. In general, the contributing section focuses on adding content to the monorepo rather than creating resources for Gatsby users. Those are in the main docs. 

Based on the slug/title in the other PR it seems like this doc is actually meant to be a template for the README of a plugin? If that's the case, we should update the description of this issue.

**Comment by JQuinnie** [comment]
Hi @laurieontech ,

This issue and the associated issue #21600 was created in response to comments guidance I received from PR #21574 , I will update the description of the issue per your request. Let me know if I need to change anything in particular as I might not extremely familiar with terms and nomenclatures. Thank you so much!

**Comment by laurieontech** [comment]
So I think the issue is that the comments on that PR discuss "How to Write a Plugin README" which is different than a README for "How to Write a Plugin" as this issue phrases it.

The goal here is to create instructions/a template for the README that contributors create when developing a Plugin. 

The current phrasing implies that instructions for how to create a plugin should be added to a README document that will then be in the contributing docs, which is not the intention.

I'll go ahead and update this issue. Thanks again for your help!

**Comment by wardpeet** [comment]
ping @laurieontech

**Comment by mohmmad0505** [comment]
EEEERR

**Comment by mohmmad0505** [comment]
> EEEERR

Www
```suggestion

```
e
```suggestion

```
t
