### ISSUE TITLE
Porting a Gatsby site to HTML

### ISSUE THREAD

**Issue by mostafachatillon** [gatsbyjs/gatsby#21594]
Hi,

I want to port a Gatsby website to a standard html/CSS static website, how can I do?

**Comment by LeuAlmeida** [comment]
You can build the project running `$ npm run build` and use the static generated files, is it?

**Comment by rahul3v** [comment]
You can build the project by running command `gatsby build` or `$ npm run build` and 
your static website files get generated into the  **public folder** of your gatsby app

Now just grab your files **from 'public' folder of your gatsby app** and put it into your server file system

- make sure you **put all the files into your root directory** to avoid file linking errors

And enjoy running you website live,

**Comment by mostafachatillon** [comment]
No, it's not so simple, because the rendering is different, see https://github.com/gatsbyjs/gatsby/issues/21607

**Comment by rahul3v** [comment]
Yes, because all links are pointed to `file:///` in directory by default if you run it normally , so you have to do lot of manual linking in `index.html` to point all external files from **/fileName** to **fileName** and much more stuffs as per you website,

So for start you can **edit all links** in "index.html" file from **/fileName** to **fileName** then check it in your browser to reflect functional works


And to run it without any modifications  you need any **local server or online server** to host it on that by putting all files into the root directory of it

**Comment by freiksenet** [comment]
Gatsby sites run fine without Javascript enabled, so it's possible to put a result of Gatsby Build to CDN and it will work. You might need to customize default layout to remove "Gatsby works best with JavaScript enabled error".
