### ISSUE TITLE
Images render blurred or do not load when launching site from public folder

### ISSUE THREAD

**Issue by mostafachatillon** [gatsbyjs/gatsby#21607]
Locally, my website works well with `gatsby serve`, but if I launch `index.html` from the public folder, images render blurred or do not load. 
That affects me because when I deploy on Netlify through a proxy 200 rewrite, the broken images displays exactly as in the public folder.  (issue: https://github.com/gatsbyjs/gatsby/issues/21525)

![Screenshot from 2020-02-20 09:34:40](https://user-images.githubusercontent.com/8183572/74915280-41272000-53c4-11ea-9efb-410dc55a7b42.png)

I get the error in the javascript console: 

![Screenshot from 2020-02-20 09:33:31](https://user-images.githubusercontent.com/8183572/74915213-205eca80-53c4-11ea-9e57-eb6d58d193d5.png)

**Comment by rahul3v** [comment]
Yes, because all links are pointed to `file:///` in directory by default if you run it normally , so you have to do lot of manual linking in `index.html` to point all external files from **/fileName** to **fileName** and much more stuffs as per you website,

So for start you can **edit all links** in "index.html" file from **/fileName** to **fileName** then check it in your browser to reflect functional works


And to run it without any modifications  you need any **local server or online server** to host it on that by putting all files into the root directory of it

**Comment by freiksenet** [comment]
This works as expected, it shouldn't possible to see images on your pages this way. What you see are fallbacks that are displayed when images are still loading, which is a correct behavior.

**Comment by mostafachatillon** [comment]
@freiksenet why is it expected?

**Comment by AlFalahTaieb** [comment]
@mostafachatillon did you find a way to fix it ??
