### ISSUE TITLE
Gatsby Performance is not OK

### ISSUE THREAD

**Issue by jdrag12** [gatsbyjs/gatsby#21613]
## Summary

This is my first project in Gatsby JS. I am not happy with the results of Google Lighthouse because it shows me a performance of less than 80. 

## Relevant information

The most critical issue I think that is the Max Potential First Input Delay. The same tool suggests me to minimize main-thread work, but I don't know where to start. I did everything suggested on Improving Performance page of Gatsby: https://www.gatsbyjs.org/docs/performance/.

![Captura de pantalla 2020-02-20 a las 13 09 22](https://user-images.githubusercontent.com/45635528/74932720-cd484000-53e2-11ea-9709-b4451ac7e3d2.png)
![Captura de pantalla 2020-02-20 a las 13 09 52](https://user-images.githubusercontent.com/45635528/74932723-cf120380-53e2-11ea-96ec-e945821e4822.png)

### Environment (if relevant)

  System:
    OS: macOS 10.15
    CPU: (4) x64 Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Safari: 13.0.2
  npmPackages:
    gatsby: ^2.19.16 => 2.19.16
    gatsby-image: ^2.2.40 => 2.2.40
    gatsby-plugin-google-analytics: ^2.1.35 => 2.1.35
    gatsby-plugin-manifest: ^2.2.41 => 2.2.41
    gatsby-plugin-offline: ^3.0.34 => 3.0.34
    gatsby-plugin-preload-link-crossorigin: ^1.0.2 => 1.0.2
    gatsby-plugin-react-helmet: ^3.1.22 => 3.1.22
    gatsby-plugin-sharp: ^2.4.5 => 2.4.5
    gatsby-plugin-sitemap: ^2.2.27 => 2.2.27
    gatsby-source-filesystem: ^2.1.48 => 2.1.48
    gatsby-theme-material-ui: ^1.0.8 => 1.0.8
    gatsby-transformer-json: ^2.2.26 => 2.2.26
    gatsby-transformer-remark: ^2.6.50 => 2.6.50
    gatsby-transformer-sharp: ^2.3.14 => 2.3.14
  npmGlobalPackages:
    gatsby-cli: 2.8.22

### File contents (if changed)

`gatsby-config.js`: 
```js
  plugins: [
     `gatsby-plugin-google-analytics`
    `gatsby-plugin-sharp`,
    `gatsby-transformer-sharp`,
    `gatsby-transformer-remark`,
    `gatsby-theme-material-ui`,
    `gatsby-plugin-sitemap`,
    `gatsby-plugin-preload-link-crossorigin`,
    `gatsby-transformer-json`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `src`,
        path: `${__dirname}/src/pages`
      }
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/src/assets/images`
      }
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/src/data/`
      }
    },
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `Ruedas Verdes`,
        short_name: `Ruedas Verdes`,
        start_url: `/`,
        background_color: `#efefef`,
        theme_color: `#64ce16`,
        display: `standalone`,
        icon: `src/assets/images/icon.png`
      }
    },
    `gatsby-plugin-offline`,
    `gatsby-plugin-react-helmet`
  ]
```
`package.json`:
```json
{
  "name": "ruedas-verdes",
  "version": "1.0.0",
  "private": true,
  "dependencies": {
    "@loadable/server": "^5.12.0",
    "@material-ui/core": "^4.9.2",
    "@material-ui/icons": "^4.9.1",
    "gatsby": "^2.19.16",
    "gatsby-image": "^2.2.40",
    "gatsby-plugin-google-analytics": "^2.1.35",
    "gatsby-plugin-manifest": "^2.2.41",
    "gatsby-plugin-offline": "^3.0.34",
    "gatsby-plugin-preload-link-crossorigin": "^1.0.2",
    "gatsby-plugin-react-helmet": "^3.1.22",
    "gatsby-plugin-sharp": "^2.4.5",
    "gatsby-plugin-sitemap": "^2.2.27",
    "gatsby-source-filesystem": "^2.1.48",
    "gatsby-theme-material-ui": "^1.0.8",
    "gatsby-transformer-json": "^2.2.26",
    "gatsby-transformer-remark": "^2.6.50",
    "gatsby-transformer-sharp": "^2.3.14",
    "react": "latest",
    "react-dom": "latest",
    "react-helmet": "^5.2.1",
    "react-share": "^4.0.1"
  },
  "scripts": {
    "develop": "gatsby develop",
    "build": "gatsby build",
    "serve": "gatsby serve"
  }
}
```
`gatsby-node.js`:
```js
const path = require(`path`);
const {
  createFilePath,
  createRemoteFileNode
} = require(`gatsby-source-filesystem`);

exports.createPages = async ({ graphql, actions }) => {
  const { createPage } = actions;
  const result = await graphql(`
    query {
      allMarkdownRemark {
        edges {
          node {
            fields {
              slug
            }
          }
        }
      }
    }
  `);
  result.data.allMarkdownRemark.edges.forEach(({ node }) => {
    createPage({
      path: node.fields.slug,
      component: path.resolve(`./src/templates/category.js`),
      context: {
        slug: node.fields.slug
      }
    });
  });
};

exports.onCreateNode = async ({
  node,
  getNode,
  actions: { createNode, createNodeField },
  store,
  cache,
  createNodeId
}) => {
  try {
    if (node.internal.type === `MarkdownRemark`) {
      const slug = createFilePath({ node, getNode, basePath: `pages` });
      createNodeField({
        node,
        name: `slug`,
        value: `categorias${slug}`
      });
    } else if (node.internal.type === "ProductsJson" && node.imgUrl !== null) {
      let fileNode = await createRemoteFileNode({
        url: node.imgUrl,
        parentNodeId: node.id,
        createNode,
        createNodeId,
        cache,
        store
      });
      if (fileNode) {
        node.imgFile___NODE = fileNode.id;
      }
    }
  } catch (e) {
    console.log(e);
  }
};
```

`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by herecydev** [comment]
Gatsby performance is great! If you run lighthouse against some of the starter

https://gatsby-starter-default-demo.netlify.com/
https://gatsby-starter-blog-demo.netlify.com/

It scores 100 in every category. It's hard to fully understand what your issue is without starting with one of the starter kits and "working" towards what you have now. Each step you can monitor what impact adding certain plugins or code has

**Comment by pieh** [comment]
The base is fine (as mentioned in previous comment), so to understand what's going on in your project we will need access to it (or at least hosted site that is built with it)

**Comment by rogermparent** [comment]
I've had problems with the First Input Delay metric on Lighthouse before, and it seems primarily related to React's rehydration interacting with Gatsby's pre-built entry points.

Essentially, First Input Delay is the difference between First Contentful Paint and when the site's JS makes it interactive (which is usually hydration in Gatsby sites), and since a Gatsby site's FCP is near instant, the entire rehydration time is considered as FID. This problem is exacerbated on large SPA-esque scroll-driven pages since React can't partially rehydrate and thus must process the whole page before the initial viewport's contents are interactive.

As it pertains to your project, the issue likely lies in the component of whatever page you're Lighthouse testing, so we'll need that or a recreation to help you out in more detail.

[You can find more details on FID here](https://web.dev/fid/)

There's a few factors to tackle that can mitigate Gatsby's FID issue in my experience:

- First and foremost, breaking a large scroll-driven page into separate pages seems to be the most effective direct solution since it splits up the rehydration task.
- Having lots of CSS-in-JS can contribute to FID, but not as much as scrolling multi-pages.

I should note that your numbers are worse than mine were when I dealt with this, but that was a very simple page despite being a scrolling multi-page; even so, it's possible another issue could be at play here.

**Comment by LekoArts** [comment]
Thank you for opening this!

As my colleague said the base of Gatsby is fine and the problems you're seeing are most likely related to your code. Hence it's not a Gatsby bug or something we can really fix.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
