### ISSUE TITLE
Hero image doesn't show in social media posts except Facebook

### ISSUE THREAD

**Issue by mostafachatillon** [gatsbyjs/gatsby#21628]
Hero image of my blog post doesn't show in most social media posts. It failed with LinkedIn, Twitter and Reddit. Only Facebook worked.

**Comment by freiksenet** [comment]
Hi @mostafachatillon!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by mostafachatillon** [comment]
I solved my problem, it was in gatsby-config.js:
I had to put: `siteUrl: `https://mywebsite.com`,`

instead of: `siteUrl: `https://mywebsite.com/basepath` (which is the real URL of the page)

So that's a problem with `basepath` documentation (there is basically no documentation about this feature).
I hope it will not create bugs elsewhere.
