### ISSUE TITLE
Configure robots.txt disallow pages based off wpgraphql value

### ISSUE THREAD

**Issue by taylorchance** [gatsbyjs/gatsby#21655]
The title says it all. I know there is gatsby-plugin-robots-txt plugin, but how can I make the list of disallowed pages conditional based of whether or not the user has chosen to have a specific page hidden.

The hidden pages will be spread throughout the site and not necessarily in one directory.

**Comment by LekoArts** [comment]
Thank you for opening this!

We don't maintain said plugin, so at first I'd suggest asking on their repository. You could make an API request to your endpoint at `onPreBootstrap`, write that result to a file and require it in your `gatsby-config.js`. Because you can't make (async) GraphQL requests in said file.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
