### ISSUE TITLE
Gatsb-Source-Contentful localeFilter does not alert when it should

### ISSUE THREAD

**Issue by joshuagagne** [gatsbyjs/gatsby#21651]
## Description

A user can provide a localeFilter that reduces the locales list to an empty set.  This results in errors that are very similar to https://github.com/gatsbyjs/gatsby/issues/15397 A consumer should be alerted if they provide no informaiton 

### Steps to reproduce
Easiest way to reproduce is to simply make localeFilter return false against any repo. 

    {
      resolve: `gatsby-source-contentful`,
      options: {
        environment:  master,
        accessToken: <token>,
        localeFilter: locale => [].includes(locale)
      },
    }
### Expected result

A message should be shown in the console to indicate a miss-configuration as the cause of the failure. 

### Actual result

Plugin fails with graphql errors as none of the default content types were created. 

```
ERROR #85901  GRAPHQL
There was an error in your GraphQL query:
Unknown type "ContentfulFixed".
File: node_modules\gatsby-source-contentful\src\fragments.js:20:37
ERROR #85901  GRAPHQL
There was an error in your GraphQL query:
Unknown type "ContentfulFixed".
File: node_modules\gatsby-source-contentful\src\fragments.js:34:47
...
```

**Comment by TylerBarnes** [comment]
Hi @joshuagagne !

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by joshuagagne** [comment]
I'm a little confused about how to go about giving a good example that doesn't expose contentful API keys.  I went ahead and opened the change as a PR, I hope the unit test is sufficient to show the use case.
