### ISSUE TITLE
bug(www): Docsearch doesn't work when tabbed into.

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#21705]
## Description

The algolia autocomplete doesn't work when using `Tab` to navigate to it.

### Steps to reproduce

1. Open https://gatsbyjs.org.
2. Press `Tab` multiple times until the search bar is highlighted.
3. Type something to search for it.

### Expected result

The Algolia autocomplete loads.

### Actual result

The autocomplete doesn't work.

### Environment

N/A

**Comment by tesseralis** [comment]
I did some digging and it seems we only start the algolia loading script on `mouseover` and `click`. I tried to add `loadAlgoliaJs` to `onFocus`, but it caused the form to immediately unfocus for some reason.

We should probably add some tests afterwards to verify this behavior.

**Comment by Usamaliaquat123** [comment]
@tesseralis right I think it causes the problem with  `toLowerCase` or  `includes` cause its getting undefined..

**Comment by dmitriyaa** [comment]
@tesseralis I've investigated this bug and submitted a fix in this PR #23040 
Basically I've added `loadAlgoliaJs` to `onFocus` as you mentioned above.
After some trials, I discovered that on `window.docsearch` function call, form loses the focus. 
And it happens not only when the user focuses the form via tabs, but it also happens on other events (mouse hover and click). 
It was not so visible, because when the user clicks on the form, he/she is also hovering the mouse. 
So the flow was like this: hover -> `window.docsearch` -> lose focus -> click -> focus -> seems to be working.
Eventually, I've added `searchInput.current.focus()` after `window.docsearch`.

**Comment by tesseralis** [comment]
@dmitriyaa thank you for looking into this and opening a PR! The solution you mentioned makes sense — and a test would be fantastic. Thank you!

**Comment by dmitriyaa** [comment]
@tesseralis, I've just added tests to the PR, could you please have a look?
It's my first experience writing test, would love some feedback. I know the code appeared to be pretty repetitive since we have 3 similar cases. Do you know some better options? Should I move common login into a separate function?
[https://github.com/gatsbyjs/gatsby/pull/23040](https://github.com/gatsbyjs/gatsby/pull/23040)
