### ISSUE TITLE
Link to page doesn't fire new GraphQL Query

### ISSUE THREAD

**Issue by grantmac** [gatsbyjs/gatsby#21726]
## Description

I have a number of static pages and generated pages from a template. Both the pages and templated pages are using GraphQL query to fetch data. I'm also using the gatsby-source-prismic-graphql plugin.

### Steps to reproduce

- Standard install of Gatsby
- Add gatsby-source-prismic-graphql and config with a single generated page type.
- In page templakte use the passed :uid to fetch data via the query.
- Load page directly. Query will fire and data is rendered.
- Click on a Link component to another generated page.
- GraphQL query won't refire, the data will remain that of the previous page 

### Expected result

Clicking on the Link component should load the new page with fresh data via the GraphQL Query

### Actual result

The URL changes but the data isn't refreshed.

### Environment

  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.3.0 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 79.0.3945.130
    Firefox: 67.0.4
    Safari: 13.0.5
  npmPackages:
    gatsby: ^2.19.21 => 2.19.21
    gatsby-image: ^2.2.41 => 2.2.41
    gatsby-plugin-layout: ^1.1.22 => 1.1.22
    gatsby-plugin-manifest: ^2.2.41 => 2.2.42
    gatsby-plugin-offline: ^3.0.35 => 3.0.35
    gatsby-plugin-prismic-preview: ^2.0.0 => 2.0.0
    gatsby-plugin-react-helmet: ^3.1.22 => 3.1.22
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0
    gatsby-plugin-sharp: ^2.4.5 => 2.4.5
    gatsby-plugin-styled-components: ^3.1.19 => 3.1.19
    gatsby-plugin-svgr: ^2.0.2 => 2.0.2
    gatsby-source-filesystem: ^2.1.48 => 2.1.48
    gatsby-source-prismic-graphql: 3.4.1-alpha.0 => 3.4.1-alpha.0+474efaa
    gatsby-transformer-sharp: ^2.3.14 => 2.3.14
  npmGlobalPackages:
    gatsby-cli: 2.9.0

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction
