### ISSUE TITLE
fix: starters_validate failing builds because of npm vulnerabilities

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#21831]
## Description

The starters_validate check is failing on all builds because of vulnerabilities found by npm's automatic audit. Run `npm audit fix` to resolve these.

**Comment by jordanlesich** [comment]
I've been recieving similar errors on my laptop. My desktop PC simply wouldn't load any plugin from npm. I had assumed it was becuase of a space in the naming of my windows user account (a common problem apparently). I can load a plugin on my laptop, but I get this message in command prompt:

 ```

> npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules\chokidar\node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
> 
> + gatsby-source-filesystem@2.1.48
> updated 1 package and audited 23125 packages in 23.329s
> 
> 40 packages are looking for funding
>   run `npm fund` for details
> 
> found 9 high severity vulnerabilities
>   run `npm audit fix` to fix them, or `npm audit` for details

```

What concerns me the most is the high severity vulnerabilities. Am I good to go ahead and make sites while these exist? Sorry, I'm new to Gatsby, and kind of new to web dev in general. I've never had this much trouble with configuration before. 

On my desktop, I recieved pages full of the 'npm WARN notsup SKIPPING OPTIONAL DEPENDENCY:' error, then the plugin wouldn't load. I tried to follow the Gatsby Windows instructions on the desktop PC, but kept finding dead ends. Some research told me that some of the problems might have been caused by the space in the username. However, I'm still recieving problems on my laptop, which does not contain that space. The error on my laptop isn't exactly as desried here, but the desktop errors sound pretty close.

**Comment by jordanlesich** [comment]
I also definitely tried, 'npm run audit'. It said that 0 of 9 were fixed and that I would have to fix them manually. That's a bit beyond my comfort level with Gatsby as it is pretty much my first time using it.

**Comment by chriswales95** [comment]
Hi everyone,

was also going to being using Gatsby but decided not to because of the sheer numbers of vulnerabilities when generating fresh builds.

Any news on this?

**Comment by chriswales95** [comment]
Seems that the high security vulnerabilities have been resolved 👍
