### ISSUE TITLE
Add link to Starters to the main menu of the website

### ISSUE THREAD

**Issue by yurist38** [gatsbyjs/gatsby#21923]
## Summary

I suggest adding a link "Starters" to the main menu

### Basic example

Right now there is no quick and intuitive way to access the page with all starters. I think the "Starters" link should be included in the main menu of the website.

### Motivation

To simplify users' access to the starters

...
Please let me know if there are any reasons why it's not there now. And if you agree with this fix, I'd love to work on it. Thanks!

**Comment by kanolato** [comment]
Ill take this one @yurist38

**Comment by yurist38** [comment]
@kanolato are you still planning to work on this one?

**Comment by visshaljagtap** [comment]
@yurist38 Please review the changes!

**Comment by LekoArts** [comment]
Hi!

Unfortunately this issue has some problems I'd like to explain so that you all can react better to that in the future.

The initial issue was a suggestion which we would have closed as we don't want to do that right now. So in the future @kanolato and @yurist38 please wait for an approval/comment from an employee of Gatsby first.
@kanolato did in theory the right thing and assigned it to himself.

Hence it wasn't right from you @visshaljagtap to open a PR before things were cleared up whether @kanolato has time to do it or not. You shouldn't take on a PR that someone else said they want to work on.

Reading this doc section should also clear some things up: https://www.gatsbyjs.org/contributing/how-to-contribute/

As I said, we don't want to implement this and thus I'll close this.

**Comment by visshaljagtap** [comment]
@Leko Understood! Thanks for the clarification :)
