### ISSUE TITLE
chore(cli): gatsby info and gatsby --version should print which packageManager used

### ISSUE THREAD

**Issue by muescha** [gatsbyjs/gatsby#21989]
## Summary

`gatsby info` and `gatsby --version` should print which `packageManager` used

### Motivation

Some errors resulting because of `yarn` is selected as `packageManager` but in tutorials and other places then `npm` is used for installing. to identify this it would be nice to have some hints at `gatsby info`

### related Issues

- #6834 `gatsby develop is not working after npm install`
- #20225 `Failed to 'gatsby develop' after installing typography plugin`
- #19827 `Ambiguous "StoreStateProvider" error for all gatsby commands`

**Comment by pieh** [comment]
Notes on this - we use [`update-notifier`](https://www.npmjs.com/package/update-notifier) to print out this information

By default, it will keep track of last check and only limit it to 1 check per day. Package doesn't have builtin method to "force check", but we might be able to trick it with setting `updateCheckInterval` option to something really low (1s?) for `--version`/`info`. Would need to make sure also to not display it multiple times so implementation might be hairy, because right now we do the check for each command (and whichever happen to be command 1 day from last one will get the notification)

**Comment by muescha** [comment]
@pieh I think You note was to this issue #21940 `feat(gatsby-cli): show update notification with gatsby --version`

**Comment by pieh** [comment]
Ops, yes sorry I had 2 tabs open with your CLI issues and of course wrote in wrong tab ;) Will "move" the comment when I'm back in front of computer

**Comment by muescha** [comment]
i transfered your comment to  #21940
