### ISSUE TITLE
gatsby-transformer-json, no UTF8 encoding for key names ?

### ISSUE THREAD

**Issue by MeilleurExcellentOptimal** [gatsbyjs/gatsby#22005]
Hello there,

I have a `.json` file containing french accents such as`{ "Métal": "Argent 925" }`

When using `gatsby-transformer-json` and querying my data it becomes `{"M_tal": "Argent 925"}`

It seems that JSON key names are not UTF8 encoded.

What do you think about that ?

**Comment by vladar** [comment]
Unfortunately, GraphQL spec allows only [alpha-numeric characters and underscore](https://spec.graphql.org/draft/#sec-Names) in field names (so that they could be safely mapped to variables in any programming language).

As a workaround you can express your data as a list of `name/value` pairs, for example:

```json
[ { "name": "Métal", "value": "Argent 925" } ]
```

**Comment by MeilleurExcellentOptimal** [comment]
@vladar Thanks for your answer. Now I understand.
