### ISSUE TITLE
Gatsby don't create a file node in graphql

### ISSUE THREAD

**Issue by Merciful12** [gatsbyjs/gatsby#22007]
## Description
Gatsby when building schema don't create file node in graphql base on relative path to file.
I think problen inside [is-file.js](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/schema/infer/is-file.js)

### Steps to reproduce
Minimal Reproduction: https://github.com/Merciful12/gatsby-bug
 - npm install
 - npm start
 - goto graphiQl
 - execute query

Query:
```
query MyQuery2 {
  allMarkdownRemark {
    nodes {
      frontmatter {
        headerSection {
          logo {
            relativePath
          }
        }
        sections {
          widgets {
            features {
              icon
            }
          }
        }
      }
    }
  }
}
```

### Expected result
headerSection logo is file node
features icon is file node

### Actual result
headerSection logo is file node
features icon is **string** node

### Environment

  System:
    OS: Windows 10 10.0.17763
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
  Binaries:
    Node: 12.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.9.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.3 - C:\Python27\python.EXE
  Browsers:
    Edge: 44.17763.831.0
  npmPackages:
    gatsby: ^2.19.7 => 2.19.7
    gatsby-image: ^2.2.39 => 2.2.39
    gatsby-plugin-manifest: ^2.2.39 => 2.2.39
    gatsby-plugin-offline: ^3.0.32 => 3.0.32
    gatsby-plugin-react-helmet: ^3.1.21 => 3.1.21
    gatsby-plugin-sharp: ^2.4.3 => 2.4.3
    gatsby-source-filesystem: ^2.1.46 => 2.1.46
    gatsby-transformer-remark: ^2.6.53 => 2.6.53
    gatsby-transformer-sharp: ^2.3.13 => 2.3.13

**Comment by vladar** [comment]
Thank you for opening this, @Merciful12 

This is one of the known issues with Gatsby type inference. Basically, the tradeoff here is `fast` vs `precise`. 

Take a look at your example. You have a single node of type `MarkdownRemark`. But this node has a bunch of nested objects most of which are empty.

<details>
<summary>Show</summary>

```json
{
  "data": {
    "markdownRemark": {
      "frontmatter": {
        "sections": [
          {
            "widgets": [
              {
                "features": null
              },
              {
                "features": null
              },
              {
                "features": null
              },
              {
                "features": null
              },
              {
                "features": null
              },
              {
                "features": null
              },
              {
                "features": null
              }
            ]
          },
          {
            "widgets": [
              {
                "features": null
              },
              {
                "features": null
              },
              {
                "features": [
                  {
                    "icon": "../static/img/1.jpg"
                  },
                  {
                    "icon": "../static/img/1.jpg"
                  },
                  {
                    "icon": "../static/img/1.jpg"
                  },
                  {
                    "icon": "../static/img/1.jpg"
                  }
                ]
              }
            ]
          }
        ]
      }
    }
  }
}
```

</details>

In order to reach a first non-null field of `frontmatter.sections.widgets.features.icon` we must traverse all of those other arrays and objects. For situations when there are many nodes - scans like this kill performance very quickly.

So instead Gatsby uses a simple heuristic to decide if some deeply nested field is a file: it only visits the very first branch of this tree. Which is fast but also sometimes produces false negatives.

In your case, it traverses a path `frontmatter.sections[0].widgets[0].features` which is `undefined`. So Gatsby doesn't detect it as a file. This is a tradeoff for speed.

For situations like this, we've introduced a [schema customization API](https://www.gatsbyjs.org/docs/schema-customization/). You can use it to **hint** Gatsby which types you actually have.

So in cases like yours, you can explicitly define a type for your field so that Gatsby didn't have to guess it.

Try adding following lines to `gatsby-node.js`:

```js
exports.createSchemaCustomization = ({ actions }) => {
  actions.createTypes(`
    type MarkdownRemarkFrontmatterSectionsWidgetsFeatures {
      icon: File @fileByRelativePath
    }
  `)
}
```

This way you can explicitly set the type of your field in edge cases like this.

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜
