### ISSUE TITLE
onMouseOver event does't work after build

### ISSUE THREAD

**Issue by nikita-seliverstov** [gatsbyjs/gatsby#22015]
Hi I ran into a problem with onMouseOver event in video tag:
` <video class="video-slide" src={video} 
  onMouseOver={event => event.target.play()}
  onMouseOut={event => event.target.pause()}
  loop >` which works absolutely fine in dev mode but after build onMouseOver does't execute

Env:
gatsby 2.19.18
react 16.12.0

**Comment by vladar** [comment]
Hi @nikita-seliverstov !

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by nikita-seliverstov** [comment]
After making reproduction repo I realized the problem was on my side because of error on run time script
