### ISSUE TITLE
docs: gatsby-plugin-sass global import methods

### ISSUE THREAD

**Issue by gillkyle** [gatsbyjs/gatsby#22119]
## Summary

There has been confusion with configuring Sass in sites using `gatsby-plugin-sass` because some methods seem to be undocumented.

This came up in a Tweet thread: 
https://twitter.com/triscodes/status/1237117936281825281

(Copying the text in case the tweet is deleted):
> It took me forever to figure out how to do it. Found out from some obscure gitub thread. This method is nowhere in the docs! Plus these are all utils, when I tried to use actual code (globals, typography, etc), the order was wrong. So I took them out. Are there better ways?
![image](https://user-images.githubusercontent.com/21114044/76263454-8b156000-6224-11ea-8811-3df7beeea6b1.png)

Some recommended topics to cover:

- Provide examples of what could be passed into the plugin's options (as part of node-sass or dart-sass) to be more explicit in the README: https://www.gatsbyjs.org/packages/gatsby-plugin-sass/#other-options - instead of just saying to refer to the other docs
- Explain global imports with more clarity in the guide on [using sass with Gatsby](https://www.gatsbyjs.org/docs/sass/), step 3 doesn't have a title on the code block to show that those imports should happen in the `gatsby-browser` file. That could be outlined like the tweet author's method shows in his tweet as well.

### Motivation

Why should we document this and who will benefit from it?

Users of `gatsby-plugin-sass`, this is also a workflow from #13708.

## Steps to resolve this issue

Covering more use cases will make these guides more practical for folks using Sass. 

### Draft the doc

- [ ] Make some improvements to the README to state options that can be passed in [which are used by the plugin](https://github.com/gatsbyjs/gatsby/blob/509339f2aeecc261c0c7e1193d873a6d4b183a35/packages/gatsby-plugin-sass/src/gatsby-node.js#L5-L12).
- [ ] Add some clarity to the example in the [Using Sass guide](https://www.gatsbyjs.org/docs/sass/), especially in the 3rd step.

### Open a pull request

- [ ] Open a pull request with your work including the words "closes #22119" in the pull request description

**Comment by tr1s** [comment]
Yeah, I'm a huge proponent of thorough documentation and not assuming everyone knows everything, because I sure don't. 

I was involved in the setup and development of my works [education website](https://junocollege.com/) and it was our first time using Gatsby V2 and using CSS modules. We wanted to use SCSS variables and obviously didn't want to import them into every single component manually. Like I mentioned it took me forever to find a method that allowed me to inject them in using that method I took a screenshot of. A tradeoff was that when you inject them in the from the `gatsby-config.js`, you don't get any VSCode helpers when you begin to start typing the variable name in the editor.. but it was worth it to have all functions, mixins, and variables accessible in all the `*.module.scss` files.

I assumed it would be a good idea to inject my normalize, typography, and global styles in the gatsby config as well because they are rarely changing.. but I was having issues with the ordering of the styles. Normalize was overriding global, and it appeared that no matter what order you put the files, it was just doing it's own thing.

----

Just yesterday playing around with Nuxt, I then found this out while setting up my SCSS:

<img width="918" alt="CleanShot 2020-03-10 at 11 45 55@2x" src="https://user-images.githubusercontent.com/19172250/76330871-bf405d80-62c4-11ea-9fb7-c2616a1a0932.png">

[Nuxt style resources](https://github.com/nuxt-community/style-resources-module) posted this warning, and if it's the same situation as in Gatsby? then it would be great to know in the docs as well. 

Also linking to node/sass docs which don't have any straightforward examples themselves doesn't seem like the best idea. 

In this line `includePaths: ["absolute/path/a", "absolute/path/b"],`, it would be better to have an actual example instead. I don't know what this means, there's no simple explanation and it feels akin to seeing `foo`, `bar`, `baz` everywhere.

Anyways, these were just some of my experiences, hope this helps, cheers!
