### ISSUE TITLE
gatsby-plugin-mdx: Display helpful message instead of blowing up in development mode when invalid mdx is present

### ISSUE THREAD

**Issue by PaulBunker** [gatsbyjs/gatsby#22135]
## Summary

When in you save a file with some invalid jsx i.e. an unclosed tag The node is not created in graphql and this means the page/site breaks and it isn't immediately obvious why.

My suggestion is that while in development mode, instead of blowing up. Return the error as the MDX body that way the user doesn't have to wonder why the page isn't working switch to the console, search for an error.

Instead, The webpage that the user is creating displays the appropriate error rather than a graphql error

### Motivation

I believe this would make it faster to spot errors and development of pages smoother.

**Comment by axe312ger** [comment]
I can deeply understand you, the fact that MDX errors do not output enough context is very annoying, especially for my editors in production.

Especially which gatsby page causes the MDX error is not output. At least sometimes the message leads to the actual broken part where the MDX code is faulty.

The root of the issue might be in MDX itself, if this is the case, I'd vote for keeping this one open as meta issue and work with the MDX community to solve this.

My current workaround:

Before I save anything to Contentful (or to disk in your case), you can validate if your MDX is correct via https://mdxjs.com/advanced/api

The error message gives you (most of the time) a human readable snippet of the broken source code with an arrow pointing on the broken tag.

It even comes with line numbers but these are off by X (Because MDX actually wraps your source before passing it to babel)

**Comment by PaulBunker** [comment]
I believe [this check](https://github.com/gatsbyjs/gatsby/blob/dc4e21e7c50cc52db757dad611d35caf08d6785a/packages/gatsby-plugin-mdx/utils/create-mdx-node.js#L10) and early return is the cause of the node not being created. 

I feel like a check for `node_env !== 'production'` and adding the `e.message` to the mdx body should be possible and result in a better user and developer experience

**Comment by jonniebigodes** [comment]
Despite the scope being a bit off...the same applies, i've ran into that and mentioned in my comment in #21934

**Comment by PaulBunker** [comment]
> The plugin starts it's job, generating nodes and with the help of @mdx/react transpilling the js and markdown and then passes onto Gatsby to continue it's job. (as a side note to whoever is maintaining the plugin, it would be a good thing that the plugin to be more permissive in development mode, meaning that it does not kill the development server if for instance i save a mdx file and i accidently forgot to close a html element or import. The messages in the console help out to some degree but killing the server is a bit to extreme ).

Quote for reference as it's an in depth reply :)
