### ISSUE TITLE
Is there a way to add preloader animation i.e during the initial loading of the website, a animation should happen till the page is loaded completely

### ISSUE THREAD

**Issue by SajithRAP** [gatsbyjs/gatsby#22203]
Is there a way to add preloader animation i.e during the initial loading of the website, a animation should happen till the page is loaded completely

**Comment by SajithRAP** [comment]
I have reference nplugin it is a loader post the page load. I'm looking for something pre-load of the webiste

**Comment by svandersteene** [comment]
I have the same question.

I'm trying to add page transition animations.
I used the react-transition-group dependency to wrap my page element in a transition-component as suggested on the web. However, this transition happens after the initial page-data loader.

Preferred behaviour;
The page animation starts just before the page load and animates whilst the page-data is loading.

**Comment by Js-Brecht** [comment]
@SajithRAP  I have a couple of ideas for how that could be done.  I haven't done this myself, so I'm just brainstorming here.

* If you wanted to, you could make an "app shell" that shows the loading animation, and in `useEffect()`/`componentDidMount()`, load the rest of the page.  However, that will stop your page from being rendered during SSR (it will only render the animation)... and it makes your site 100% dependent on javascript.

* Another thing that might work is to add your loading component to [`wrapRootElement`](https://www.gatsbyjs.org/docs/ssr-apis/#wrapRootElement), maybe inside of a Context provider, like:
  ```js
  exports.wrapRootElement = ({ element }) => {
    return (
      <Context.Provider value={state}>
        <Context.Consumer>
          {(context) => (
            <React.Fragment>
              {context.isLoading && <Loader />}
              {element}
            </React.Fragment>
          )}
        </Context.Consumer>
      </Context.Provider>
    )
  }
  ```
  Then in your top level component of your pages, in the "mounted" lifecycle event, you could tell it to turn off `isLoading`.  So long as `isLoading` default to true, the loading animation _should_ make it into the static HTML.
   
  Downside to that is if somebody has javascript turned off, the loading animation will never turn off.

* You could also add an external, static script.  Using the [onPreRenderHTML](https://www.gatsbyjs.org/docs/ssr-apis/#onPreRenderHTML) endpoint in `gatsby-ssr`, you could use `replaceHeadComponents()` to insert a script in the `<head>`, and then use `replacePreBodyComponents()` (or `replacePostBodyComponents()` 🤷‍♂), to add a custom container for your loading animation.  If you make the `<head>` script a synchronous load, it will force it to load before the rest of the page, which should allow it to load up its animation before everything else starts downloading.  When the script loads, it mounts its loading animation.  Then, in [`onInitialClientRender()`](https://www.gatsbyjs.org/docs/browser-apis/#onInitialClientRender) (i.e. when React has mounted/hydrated), you could turn off the animation.

  This would make it so that if javascript is turned off, the loading animation never gets turned on.  Downside here is the thread blocking script, but if it's tiny, then it shouldn't impact the performance too much... and it should really only have to be downloaded and run once.  It would probably rely on global window properties so that the main React app could call out to the external script, though.

**Comment by LekoArts** [comment]
Thank you for opening this!

First and foremost, I don't think such an animation is necessary with pages built on Gatsby. You'd be artificially slowing down your website and annoying your user with a wait time that is unnecessary. If you load something heavy on the site you can lazy load it and show most of the page nevertheless.

Regarding Jeremy's suggestions, I'd also go with the last option as the other two would totally defeat the purpose of Gatsby (being accessible also without JavaScript).

> I'm trying to add page transition animations.
I used the react-transition-group dependency to wrap my page element in a transition-component as suggested on the web. However, this transition happens after the initial page-data loader.

This is another issue really and probably something wrong on your end. You won't need to slow down Gatsby at some point. You could try out https://www.gatsbyjs.org/docs/adding-page-transitions-with-plugin-transition-link/ or have a look at the source code how it adds page transitions.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
