### ISSUE TITLE
How to do authentication and RBAC authorization?

### ISSUE THREAD

**Issue by zwl1619** [gatsbyjs/gatsby#22236]
How to do authentication and RBAC authorization when using gatsby?
Not using Netlify Identity and Auth0.

**Comment by LekoArts** [comment]
Thank you for opening this!

As this isn't a bug report or feature request or a question related to Gatsby I'll have to close this. In a nutshell you'll be able to do authentication with Gatsby like with any other React app since you'll have a client-side only portion: https://www.gatsbyjs.org/docs/client-only-routes-and-user-authentication/

Following guides/articles on that (which reference general React and hosting setup) should also work for Gatsby.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
