### ISSUE TITLE
Question about gatsby-plugin-mdx

### ISSUE THREAD

**Issue by gojutin** [gatsbyjs/gatsby#22248]
`gatsby-plugin-mdx` does not seem to be including code blocks or JSX (imported or not) as part of an excerpt. I am not sure if this is by design, but I wanted to ask if there was a way to change this behavior? I am using the excerpt to send data to Algolia and would like code blocks and components output to show up as part of the excerpt. 

I have included examples of an `mdx` and the related GraphQL query as a demonstration.

Any help is appreciated. Thanks!

![query](https://user-images.githubusercontent.com/21136155/76626937-6fee6d00-6510-11ea-9e2f-f5e10476c949.png)
![mdx](https://user-images.githubusercontent.com/21136155/76626939-71b83080-6510-11ea-8908-94d574f8e9b8.png)

**Comment by laurieontech** [comment]
Thanks for the question and apologies for the delay!

This behavior is expected and by design. Since an excerpt is generated for you, it ignores code blocks and components in favor of more "readable" plain text.

If you'd like that information to be included you can set your own "excerpt" in frontmatter which will take precedence.

**Comment by gojutin** [comment]
I didn't know you could provide a frontmatter excerpt. Thanks for the response.
