### ISSUE TITLE
Problem with SEO using Wordpress + Gatsby

### ISSUE THREAD

**Issue by gjpsiqueira** [gatsbyjs/gatsby#22261]
My gatsby is at domain.com, and my wordpress at wp.domain.com. When I post in Wordpress, create a slug wp.domain.com/slug, and domain.com/slug.
The problem than Google is indexed only the wp.domain.com/slug and exclude the domain.com/slug.
I try to Disallow: / in Robots.txt, but not working.

How I do to fix it ?

**Comment by TylerBarnes** [comment]
Hi @gjpsiqueira I'm not entirely sure what you mean. Can you provide some more info about how you're hosting your backend and frontend?

**Comment by gjpsiqueira** [comment]
Hi, @TylerBarnes , Thank you for response! I will try explain. Sorry for my English. 
I'm using the Wordpress like Backend in my app and Gatsby as FrontEnd. In same domain, I'm hosting the backend and frontend. So, the mysite.com is hosted the frontend and the subdomain wp.mysite.com, is the backend.

When I do create a post within Wordpress, the slug wp.mysite.com/slug is created and index at Google. However, when I pull within Gatsby: mysite.com/slug, the Google can't index.

I hope to understand my issue.
Thank you!

**Comment by TylerBarnes** [comment]
@gjpsiqueira , thanks for the additional info. What do you mean when you say Google can't index your Gatsby urls? Is it that they just aren't showing up in search results or are you seeing some other issue?

If google is somehow crawling your backend WP instance, you probably need to [check the option to discourage search engines from indexing](https://www.wpbeginner.com/beginners-guide/how-to-stop-search-engines-from-crawling-a-wordpress-site/). As for making sure your Gatsby urls are indexed, you can try creating a sitemap and [submitting it to Google search console](https://support.google.com/webmasters/answer/183668?hl=en).

It sounds like this is an SEO configuration discussion rather than an issue with Gatsby so I'm going to close this issue for now. Feel free to ask me any additional questions here though. :) hope that helps
