### ISSUE TITLE
Convert svg's to inline during build time

### ISSUE THREAD

**Issue by taylorchance** [gatsbyjs/gatsby#22341]
I have a gatbsy site sourcing a very secure wordpress database. I am using gatsby-image and its working perfectly to pull the data down using graphql and compress and move over to the /static folder for png/jpg images.

I am using react-inlinesvg to convert the svg images to inline, but I only just realized now that this happens during client side run time, not during the build time. Is there anything that will pull the svg image from the secure server during build time, and have all the relevant image data inside the /public folder?

**Comment by ascorbic** [comment]
Sharp doesn't process SVG files, and there's no benefit to using gatsby-image with them as they already resize to whatever size you need. If you want to use SVGs loaded from Wordpress you should load them as files rather than childImageSharp. You can get a path in your graphql query and load that in a normal img tag. If you want them inline then that isn't supported directly. There's [a plugin](https://github.com/axe312ger/gatsby-transformer-inline-svg) that promises to do just that, though it only talk about Contentful not Wordpress. I've not tried it, but it may work, or could perhaps be modified to work with Wordpress.
