### ISSUE TITLE
gatsby-plugin-stylus: translate3d(0, 0, 0) -> translateZ(0)

### ISSUE THREAD

**Issue by vovalukashov** [gatsbyjs/gatsby#22428]
## Description

Hi! I often write css animations, and therefore often use translate3d (0,0,0), but when compiling it turns into translazeZ (0). In safari, when creating @keyframes, animation stops working because of this.

### Steps to reproduce

before:

@keyframes animation {
  0% {
    transform: translate3d(0, 0, 0);
  }

  100% {
    transform: translate3d(0, 5%, 0);
  }
}

after:
@keyframes animation {
  0% {
    transform: translateZ(0);
  }

  100% {
    transform: translateY(5%) translateZ(0);
  }
}

### Expected result

for this to work in safari, after compilation, translate3d (0, 0, 0) and translate3d (0, 5%, 0) should remain

### Actual result

transform: translateZ(0) and transform: translateY(5%) translateZ(0)

### Environment

 System:
    OS: macOS 10.15.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.8.0 - /usr/local/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 80.0.3987.149
    Firefox: 73.0.1
    Safari: 13.0.5
  npmPackages:
    gatsby: ^2.19.25 => 2.19.25
    gatsby-background-image: ^0.10.2 => 0.10.2
    gatsby-cli: ^2.7.26 => 2.9.0
    gatsby-image: ^2.2.41 => 2.2.42
    gatsby-plugin-purgecss: ^4.0.0 => 4.0.1
    gatsby-plugin-react-helmet: ^3.0.12 => 3.1.22
    gatsby-plugin-robots-txt: ^1.5.0 => 1.5.0
    gatsby-plugin-sharp: ^2.0.34 => 2.4.5
    gatsby-plugin-sitemap: ^2.2.6 => 2.2.27
    gatsby-plugin-styled-components: ^3.1.5 => 3.1.19
    gatsby-plugin-stylus: ^2.0.7 => 2.1.21
    gatsby-plugin-typescript: ^2.1.26 => 2.2.0
    gatsby-source-contentful: ^2.0.67 => 2.1.89
    gatsby-transformer-remark: ^2.3.8 => 2.6.53
    gatsby-transformer-sharp: ^2.3.13 => 2.3.16

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction
