### ISSUE TITLE
`typography-plugin-cache-endpoint` not found

### ISSUE THREAD

**Issue by siawyoung** [gatsbyjs/gatsby#22477]
After upgrading `react-plugin-typography` from `2.3.22` to `2.4.0`, `npm install` gives me the following error:

```
 ERROR  Failed to compile with 1 errors                                                    4:36:32 PM
⠀
This dependency was not found:
⠀
* typography-plugin-cache-endpoint in ./node_modules/gatsby-plugin-typography/gatsby-browser.js
⠀
To install it, you can run: npm install --save typography-plugin-cache-endpoint
```

Not sure if it has anything to do with this change: https://github.com/gatsbyjs/gatsby/commit/b28c27aa9eb8b7d29692c7d6bca54350bdc057e9#diff-f0581f3936b2499afc86d794aa16310a

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by daleyd** [comment]
Hello,

I'm also receiving this same issue. Reproduction steps are basically follow this article:

https://www.gatsbyjs.org/docs/typography-js/ 

At the point where I run gatsby develop it fails with the following error:

 ERROR  Failed to compile with 1 errors                                                                                                                                                         3:26:27 pm
⠀
This dependency was not found:
⠀
* typography-plugin-cache-endpoint in ./node_modules/gatsby-plugin-typography/gatsby-browser.js
⠀
To install it, you can run: npm install --save typography-plugin-cache-endpoint

If you run npm install --save typography-plugin-cache-endpoint the following error is displayed:

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/typography-plugin-cache-endpoint - Not found
npm ERR! 404 
npm ERR! 404  'typography-plugin-cache-endpoint@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

Are you able to shed any light on this issue?
