### ISSUE TITLE
MaxWidth is ignored when Markdown image is displayed

### ISSUE THREAD

**Issue by digitalcolony** [gatsbyjs/gatsby#22482]
The good news is that the images I have inside Markdown are displaying. However, they are displaying full-sized. The MaxWidth parameter is being ignored. What am I missing? 

gatsby-config.js

module.exports = {
  /* Your site config here */
  siteMetadata: {
    title: "My Site",
  },
  plugins: [
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `src`,
        path: `${__dirname}/src/`,
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-transformer-remark`,
      options: {
        plugins: [
          {
            resolve: `gatsby-remark-images`,
            options: {
              // It's important to specify the maxWidth (in pixels) of
              // the content container as this plugin uses this as the
              // base for generating different widths of each image.
              maxWidth: 590,
            },
          },
        ],
      },
    },
  ],
}

Dependencies:
"dependencies": {
    "bootstrap": "^4.4.1",
    "gatsby": "^2.19.45",
    "gatsby-image": "^2.3.0",
    "gatsby-plugin-sharp": "^2.5.1",
    "gatsby-remark-images": "^3.2.0",
    "gatsby-source-filesystem": "^2.2.1",
    "gatsby-transformer-remark": "^2.7.0",
    "gatsby-transformer-sharp": "^2.4.1",
    "react": "^16.12.0",
    "react-bootstrap": "^1.0.0-beta.17",
    "react-dom": "^16.12.0"
  },

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by digitalcolony** [comment]
Once I added the plugin "gatsby-remark-relative-images" and rearranged a few things, it started working.

    "gatsby-transformer-sharp",
    "gatsby-plugin-sharp",
    {
      resolve: "gatsby-transformer-remark",
      options: {
        plugins: [
          "gatsby-remark-relative-images",
          {
            resolve: "gatsby-remark-images",
            options: {
              maxWidth: 100,
              linkImagesToOriginal: false,
            },
          },
        ],
      },
    },
