### ISSUE TITLE
gatsby-remark-images: Append custom class to element from MD

### ISSUE THREAD

**Issue by mor10** [gatsbyjs/gatsby#22554]
## Summary

[gatsby-remark-images](https://www.gatsbyjs.org/packages/gatsby-remark-images/) has a `wrapperStyle` option, but this only accounts for situations where the developer wants to inject inline CSS to image elements, and assumes all images will be treated the same.

It should be possible for the developer to add a classname to each image in the .md file and have this translate during processing to allow for customization of image display.

### Basic example

There are multiple examples of how this _could_ be done from various flavors of Markdown. Something like this would serve as a basic example:

```![alt text](./link/to/file.jpg){.alignright}```

### Motivation

For images and other graphics to be effective, they need to be styled. I can think of very few situations where all images would be styled identically. Being able to control the styling of an individual image from markdown opens the door for easier user customization.

**Comment by johno** [comment]
Hey @mor10, we definitely see the value in being able to apply styles at a more granular level for elements like images.

This is something you can achieve using [interleaving in the commonmark spec](https://spec.commonmark.org/0.29/#example-122). This is probably the _preferred_ approach because it doesn't require us to extend the markdown syntax.

In practice, you can wrap your image with a div and apply a class like so:

```md
<div class="rightalign">

![random unsplash image](https://images.unsplash.com/photo-1583941533567-4008a12e100d?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=400&ixlib=rb-1.2.1&q=80&w=100)

</div>
```

This will allow you to target styles to child elements because the resulting HTML is:

```html
<div class="rightalign">
  <p>
    <img alt="some random unsplash image" src="https://images.unsplash.com/photo-1583941533567-4008a12e100d?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=400&ixlib=rb-1.2.1&q=80&w=100"
  </p>
</div>
```

You can see it in action on [CodeSandbox](https://codesandbox.io/s/remark-interleaving-md-and-html-cu77n).

Does this approach suit your needs? If it doesn't you _should_ be able to write a custom [remark plugin](https://www.gatsbyjs.org/blog/2019-07-03-using-themes-for-distributed-docs/#leveraging-gatsby-remark-plugins) to achieve this functionality.

I'm going to close this for now since we can achieve similar functionality using existing markdown syntax. Let me know if you have any questions and thanks for opening an issue!

**Comment by mor10** [comment]
Thanks for the suggestion @johno, but doing what you suggest produces an unnecessary (and semantically inaccurate) paragraph which introduces a new set of problems. It also invalidates the purpose of markdown which is to avoid having to write code. For the non-coder user this is problematic.

I think what we have here is Gatsby highlighting a severe limitation in the Markdown spec. Bloggers expect to be able to place and align images. Going the Markdown route, this is not possible without doing something outside the spec which makes the Markdown route a non-starter for many uses.
