### ISSUE TITLE
Page flashes after initial load in gatsby-starter-blog

### ISSUE THREAD

**Issue by pietrorea** [gatsbyjs/gatsby#22573]
## Description

The issue is very easy to see. If you go to the [starter blog demo](https://gatsby-starter-blog-demo.netlify.com) and load any page, the unstyled version of the page is shown for a fraction of a second before the styles are applied. The result is a jerky user experience for someone browsing around. 

I noticed this does not happen in the [default starter demo](https://github.com/gatsbyjs/gatsby-starter-default.

### Steps to reproduce

- Go to https://gatsby-starter-blog-demo.netlify.com
- See page flashing for a fraction of a second

### Expected result

What should happen?

- There should be minimal jerkiness on initial load

### Actual result

- The page flashes for a fraction of a second until the styles are applied

### Environment

This happens in develop and production builds

**Comment by Js-Brecht** [comment]
This is because `typography.js` isn't doing any prefetching of the fonts.  That starter uses the [typography-theme-wordpress-2016](https://github.com/KyleAMathews/typography.js/blob/master/packages/typography-theme-wordpress-2016), which you'll see [loads up some google fonts](https://github.com/KyleAMathews/typography.js/blob/master/packages/typography-theme-wordpress-2016/src/index.js#L11-L20); that process doesn't set them up for prefetching, though.

One way you could fix it is to use [gatsby-plugin-preload-fonts](https://www.gatsbyjs.org/packages/gatsby-plugin-preload-fonts/), which takes a snapshot of your pages to find what fonts are needed, creates an index, and caches them.  Then when you build, it makes sure they are preloaded.

I prefer using [gatsby-plugin-prefetch-google-fonts](https://www.gatsbyjs.org/packages/gatsby-plugin-prefetch-google-fonts/), in combination with `typography.js` for setting the font families, and I just forgo the use of the `googleFonts` property with `typography`.  It works pretty well for me, and I don't have to think about making sure the font index is up to date for the other plugin.

Maybe one of those options could be integrated into the starter?  I'd imagine that since it's an official starter, it should also use the official plugin (`gatsby-plugin-preload-fonts`).
