### ISSUE TITLE
Showing a pre rendering for a fraction of seconds

### ISSUE THREAD

**Issue by ajmeraaxesh** [gatsbyjs/gatsby#22640]
In the development phase, you see that the page shows a non styled layout for a fraction of seconds and then renders correctly.

Is there a reason to see something like this. This is even more obvious when using images

As an example, when using the Starter kit, if we just add the following in "header.js'

<img  style={{height: '12px' }} src={gatsbyicon} alt="" />

the page shows a larger image first and then renders correctly

**Comment by vladar** [comment]
Hi @ajmeraaxesh 

Sorry to hear you're running into an issue. I tried to reproduce this locally but couldn't. Can you provide a bit more information? What browser do you use? Maybe you can record a short video so that we could see the problem?

Also, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by ajmeraaxesh** [comment]
Attached file contains the recording the preview. You can understand what I am referring to


[Screen Recording 2020-04-05 at 10.08.44 AM.zip](https://github.com/gatsbyjs/gatsby/files/4432959/Screen.Recording.2020-04-05.at.10.08.44.AM.zip)

**Comment by ajmeraaxesh** [comment]
Also just for your reference. I am using tailwindcss for the recording I have attached. I am attaching a very minimal project and the link I have referred to. 

Reference:
https://www.gatsbyjs.org/docs/tailwind-css/

In addition, Please see package.json, Header.js and tailwind.css as this is the only files I have made changes from default project that comes in-built

[test-plain-gatsby.zip](https://github.com/gatsbyjs/gatsby/files/4433068/test-plain-gatsby.zip)

**Comment by ajmeraaxesh** [comment]
Tried even steps in this article and followed the steps, still see a similar issue
https://dev.to/jakedohm_34/using-tailwind-with-gatsby-js-10fj

**Comment by vladar** [comment]
It happens in `develop` only, right? If you build and run `gatsby serve` you shouldn't see this problem. And I think it is expected because of how style-loader works. See this for details: https://github.com/webpack-contrib/style-loader/issues/107

This is happening in `develop` to enable support for hot reloading of styles with source maps. It shouldn't happen in the production build.

**Comment by vladar** [comment]
Thank you for opening this, @ajmeraaxesh !

There is an old standing issue about it: #6211, so closing this one as a duplicate.
We hope we managed to explain what's going on and thank you for using Gatsby! 💜
