### ISSUE TITLE
SEO Component on blog post

### ISSUE THREAD

**Issue by olegKusov** [gatsbyjs/gatsby#22677]
I cant make SEO component work in blog post template. im using starter blog project and standart seo component. but it doesnt work

![image](https://user-images.githubusercontent.com/28058268/77978529-13aa8c00-730b-11ea-93b4-d3422a6d63e4.png)

**Comment by LekoArts** [comment]
Thank you for opening this!

Please have a look at the starter file:
https://github.com/gatsbyjs/gatsby-starter-blog/blob/master/src/templates/blog-post.js

Make sure that your component is correct. Since this isn't an error with Gatsby I'm closing this. Moreover I kindly ask you to follow our issue template in the future as we otherwise have to close your issues as we can't help you.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
