### ISSUE TITLE
Gatsby __refresh for production returns 404

### ISSUE THREAD

**Issue by gadzet** [gatsbyjs/gatsby#22683]
Hey my setup is `gatsby-wordpress-source-plugin` with gatsby.  I've been testing the refresh function locally and it works fine, but when moving to staging or production where I am using built files my server will return 404 for some reason.

Enviroment variables that i set in my jenkins build:
`
GATSBY_ACTIVE_ENV=staging
ENABLE_GATSBY_REFRESH_ENDPOINT=true
`

The setup is copied from the github example with wordpress.

Is it even supported for builds or is it only working for dev enviroment ? Any tips on resolving it if possible?

**Comment by LekoArts** [comment]
Thank you for opening this!

Not sure what plugin you're using because there only exists `gatsby-source-wordpress`. And the refresh hook you're referring to is only available in the `develop` stage. You need to run `gatsby develop` to use it. Also overriding the GATSBY_ACTIVE_ENV would be problematic (if you'd do that for a `gatsby develop` run).

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
