### ISSUE TITLE
  WebpackError: ReferenceError: window is not defined | "window" is not available during server side rendering.

### ISSUE THREAD

**Issue by SajithRAP** [gatsbyjs/gatsby#22680]
I have installed plugin "react-typing-effect" and it's working in development. While building the project, I got the error as  "WebpackError: ReferenceError: window is not defined". I referenced document "https://www.gatsbyjs.org/docs/debugging-html-builds/" but unable to sort out the issue. 

Below are code detils
 import ReactTypingEffect from 'react-typing-effect'; -> This failed during build as "window is not defined"

Per document I'd rewritten this to:
const Sample= () => {
  if (typeof window !== `undefined`) {
    const ReactTypingEffect = require('react-typing-effect')
  }
  return ( ...... blah blah

But this errored as "ReactTypingEffect is undefined"

I'm not sure of the workaround to fix this. Any assistance on this is much appreciated.

**Comment by LekoArts** [comment]
Thank you for opening this!

Please follow the other suggestions in the doc. You could try:

```js
const ReactTypingEffect = typeof window !== `undefined` ? require("react-typing-effect").default : null
```

Or:

```js
exports.onCreateWebpackConfig = ({ stage, loaders, actions }) => {
  if (stage === "build-html") {
    actions.setWebpackConfig({
      module: {
        rules: [
          {
            test: /react-typing-effect/,
            use: loaders.null(),
          },
        ],
      },
    })
  }
}
```

Alternatively you should reach out to the maintainers of react-typing-effect and ask for SSR support.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by SajithRAP** [comment]
> Thank you for opening this!
> 
> Please follow the other suggestions in the doc. You could try:
> 
> ```js
> const ReactTypingEffect = typeof window !== `undefined` ? require("react-typing-effect").default : null
> ```
> 
> Or:
> 
> ```js
> exports.onCreateWebpackConfig = ({ stage, loaders, actions }) => {
>   if (stage === "build-html") {
>     actions.setWebpackConfig({
>       module: {
>         rules: [
>           {
>             test: /react-typing-effect/,
>             use: loaders.null(),
>           },
>         ],
>       },
>     })
>   }
> }
> ```
> 
> Alternatively you should reach out to the maintainers of react-typing-effect and ask for SSR support.
> 
> We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

Both didn't work. Still the same error is poping up

**Comment by jonniebigodes** [comment]
@SajithRAP to not let you go without a answer and a bit more context. What was forgotten before this issue was closed is that you have another option. You can "offload the package" and code to the client side side and with that prevent the errors you're getting.

Here are the steps i took to triage this:

- Created a new Gatsby website based on the hello world starter.
- Added the package in question, more specifically `react-typing-effect` and also `@loadable/babel-plugin`, `@loadable/component` and `@loadable/webpack-plugin`. The the latter ones will be the ones responsible to handle the offloading and allow to use the package that triggered the issue. You'll see it in action shortly.
- Created `gatsby-node.js` with the following:

```javascript
const loadablePlugin=require('@loadable/webpack-plugin');
exports.onCreateWebpackConfig =({ actions })=>{
    actions.setWebpackConfig({
        plugins: [new loadablePlugin()]
    })
}
```
- Created a `.babelrc` file with the following inside:

```json
{
    "plugins": [
        "@loadable/babel-plugin"
    ],
    "presets": [
        [
            "babel-preset-gatsby",
            {
                "targets": {
                    "browsers": [
                        ">0.25%",
                        "not dead"
                    ]
                }
            }
        ]
    ]
}
```

These two changes take care of the configuration part. Now onto the code itself.
- Created a new component called `my-typing-component.js` inside `src\components` folder with the following:

```javascript
import React from 'react'
import ReactTypingEffect from 'react-typing-effect'
const MyTypingExample=()=>{
    const textToDisplay=["Hello","this","is","being","typed","inside","a","gatsby","website","with","loadable components."]
    return(
        <ReactTypingEffect text={textToDisplay}/>
    )
}

export default MyTypingExample
```
Nothing to exotic in the code, this is a basic React functional component that will use the package and show the text inside the array as per the instructions provided by `react-typing-effect` .

- Changed `src\pages\index.js` to the following:

```javascript
import React from "react"
import Loadable from "@loadable/component"
const LoadableTypewriter = Loadable(() =>
  import("../components/my-typing-component")
)
export default () => <div><LoadableTypewriter /></div>

```
The key thing to take from this change, is the `Loadable ` import, as it will split the code and offload it to the client side. So when you issue `gatsby develop` for a development build or `gatsby build && gatsby serve` to generate a production build and serve it emulating a live production server and open up the page it would probably take a little bit but eventually see the text being typed.

If you want i can hoist up my reproduction to a repo so that you can take a better look at the code.

Feel free to provide feedback
