### ISSUE TITLE
[Build Error] Out of memory when pages exceed 95

### ISSUE THREAD

**Issue by siriwatknp** [gatsbyjs/gatsby#22691]
## Description

Everything works fine when pages are 95, but after adding one more simple page and run `build` I got this error.

![image](https://user-images.githubusercontent.com/18292247/78040976-5ebfb000-739a-11ea-9c26-86b8369cdaaa.png)

I searched and tried this `node --max_old_space_size=12000 ./node_modules/.bin/gatsby build`. There is no error but the build time is very long (from 100s to around 600s with 1 more page) and still fail in Circle CI, so I don't think that is a solution. I totally stuck and need help. 

### Steps to reproduce

Clone this project. https://github.com/siriwatknp/mui-treasury
```
// at master branch
yarn install
yarn build
```

### Expected result

It should be able to build. If delete some page in `/website/src/pages/styles/...` and then run `yarn build` it will pass. 😱

### Actual result

Build fail with the error above.

### Environment

  System:
    OS: macOS 10.15.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 80.0.3987.149
    Firefox: 73.0.1
    Safari: 13.0.3

**Comment by micaelr95** [comment]
This doesn't seem like a bug or problem in Gatsby but rather a limitation in Nodejs.

As you pointed out, using the flag --max-old-space-size to increase the amount of RAM used by Nodejs seems to do the trick.

**Comment by pvdz** [comment]
Well, that kind of depends. Considering this is <100 pages nothing should OOM with default RAM settings. It is possible, of course, if you put enough content in each page. That's not generally the case, so I'll check this out.

Additionally I'm interested to see which stringify is OOMing here, since the heavy serialization goes through `v8.serialize` these days :)

Thanks for the report

**Comment by siriwatknp** [comment]
@pvdz Thanks, it could possibly my fault that I make mistake somewhere but I have know idea right now.

**Comment by kuworking** [comment]
I've opened a new issue https://github.com/gatsbyjs/gatsby/issues/22717 that sounds very much like this one, could you test if downgrading to gatsby 2.20.5 solves your issue?

**Comment by siriwatknp** [comment]
@kuworking I tried but it does not solve my issue.

**Comment by freiksenet** [comment]
Potential fix published in `2.20.12`, does it work for you?

**Comment by pvdz** [comment]
@siriwatknp when I try to build your site it OOMs when creating a webpack bundle. Might be caused by minification (although running it with `--no-uglify` runs into different problems) but indicates there's just too much JS For the site.

So this is unrelated to page count, or the telemetry issue mentioned by @freiksenet, but related to how much client side JS webpack is processing.

Try to have a look at how you might reduce that. Your config contains a lot of plugins and I think you're including a bunch as well. Was that intentional?

**Comment by siriwatknp** [comment]
@pvdz Have u ever seen other use case that use a lot of JS, do they face the same issue I have? If I want to handle a lot of page, I should do it with `createPage` API instead of creating js under `pages` folder, is that correct?

**Comment by kuworking** [comment]
I've tried (287 pages) with gatsby 2.20.12 and `gatsby develop` works, and `gatsby build` works

Still, I get an ERROR label that I guess it's because in my core theme requires gatsby 2.20.5 (see image)

Other than that `gatsby serve` looks well

![image](https://user-images.githubusercontent.com/4474004/78701175-d9427f80-7906-11ea-8aa3-db4c3f49f6d2.png)

**Comment by pvdz** [comment]
Yeah the error is caused by the update notification that was injected. Annoying :(

**Comment by pvdz** [comment]
@siriwatknp eh, tbh, I actually don't know the perf implications of that choice. All I see is `createPage` api, though. I'm not sure if that should affect the JS bundle, or why it would, but maybe.

I've seen issues like this before and it's usually a configuration issue of some kind. Perhaps @wardpeet has a better insight.

**Comment by siriwatknp** [comment]
I will close this issue for now.
