### ISSUE TITLE
Require adds base64 two times

### ISSUE THREAD

**Issue by SimonKlausLudwig** [gatsbyjs/gatsby#22715]
I have a bunch of base64 images which I want to include in my page. I want them to be added to the .html file. This works fine. The only problem is, that Gatsby adds the base64 strings also to the .js files which enlarges them a lot.

Is this behaviour wanted ? just makes the js file larger.

**Comment by vladar** [comment]
If you add them to React components then it is quite expected. Make sure to read about [React hydration](https://www.gatsbyjs.org/docs/react-hydration/) to understand what is going on under the hood.

**Comment by SimonKlausLudwig** [comment]
Okay I see, is there any way to change this behaviour ? Thank you for your help.

**Comment by Js-Brecht** [comment]
@SimonKlausLudwig is your goal with adding them to your `.html` file to reduce the size of your Javascript bundles?

**Comment by SimonKlausLudwig** [comment]
Yes Exactly. Google Page Speed insight gives me 100%  Desktopscore and 82% Mobilescore. The reason why the mobile score is 'just' 82% are the base64 images in my javascript bundle. About 30% of the script content are base64 encoded images.

**Comment by Js-Brecht** [comment]
Out of curiosity, can you show how you’re loading them into the HTML?  I just want to see if there will be a decent way to reuse what’s there, rather than use them directly from the JS.

**Comment by SimonKlausLudwig** [comment]
Sure: I just use basic require 

```
<a key={i} rel="noopener noreferrer" target="_blank" href={""}><img
                    alt={`${i} logo`}
                    src={idx <= 3 ? i : require(`./${i}.png`)}/></a>
```

My workaround at the moment: Just use base64 for the first 3 images and for the remaining 20 use a regular URL. But this feels a bit 'dirty' and still the three base64 are included in the javascript bundle.

**Comment by Js-Brecht** [comment]
That looks like a React component to me.  That would be why it’s included in the Javascript bundle.  It also winds up in the static HTML because of SSR.

SSR is basically taking all of your React, and rendering it to HTML.  Then, when the page loads, React hydrates and takes over.  Without it being in React, it wouldn’t make it into the HTML.

I’ll have to do some R&D to see if there’s a way to have a React component render statically, but not hang on to some of the data on the client.  Maybe make it read the data it needs from the DOM during hydration instead, somehow 🤔.

One alternative would be to use something like [loadable-components](https://github.com/gregberge/loadable-components) with [gatsby-plugin-loadable-components-ssr](https://www.gatsbyjs.org/packages/gatsby-plugin-loadable-components-ssr/).  That will work for SSR, and it should split them out into different chunks and also load them dynamically on the front end.  That should reduce the size of your bundle, at least, but the data will still be downloaded as a different javascript piece.

**Comment by Js-Brecht** [comment]
It appears to have a reason to do it this way, but I’m curious about why you don’t use [gatsby-image](https://www.gatsbyjs.org/packages/gatsby-image/)?

**Comment by Js-Brecht** [comment]
After further thought, I don't think it's really reasonable to have data in the HTML, but not in JS.  After React hydrates, it doesn't touch any more HTML files, so if you tried to navigate to another page, it wouldn't know how to render those images unless they exist in the Javascript.

I also think it might not be a great idea to inline all of your images into the HTML, either.  That basically forces the client to download everything, all at once, which slows down the time to your first render.  I think a better approach would be to optimize the images as much as possible, and render a placeholder (like the `gatsby-image` traced svg placeholder), then lazy-load the pictures directly from the URL.  This is usually a good balance between UX and performance.

This is one good argument for using `gatsby-image`, in conjunction with `gatsby-transformer-sharp` and `gatsby-plugin-sharp`.  It handles all of that for you, and it makes it easy to optimize your images during build-time.  The `base64` data that it **does** load into the HTML is the placeholder SVG I mentioned, and all of that is stored in a separate `json` chunk which gets lazy-loaded.

The only other decent alternative I can think of is to minimize the size of one single JS chunk, and that is by using `loadable-components` like I mentioned earlier.

**Comment by SimonKlausLudwig** [comment]
Gatsby-Image also puts the base64 image in the resulting javascript bundle.

**Comment by Js-Brecht** [comment]
> Gatsby-Image also puts the base64 image in the resulting javascript bundle.

In my projects, I see the base64 in the data chunks (`.json`) for the page queries and the static queries.  Not in the `.js` chunks themselves :thinking:.  Maybe, that's because I'm only using Gatsby's GraphQL with `gatsby-image`, though.  If you are getting the base64 in the `.js` chunks when using the same method, I'd be curious to see it in action.  I don't think that's supposed to be happening, especially since that would force your users to download the data 3 times (once in HTML, once in the data chunk, and once in JS).

> If I use Gatsby image for this the base64 images looks blurry at first pint which is pretty ugly.

Yeh, that is because the base64 that's included is the light-weight placeholder, which is supposed to be blurry; it kind of acts like a "loading... " indicator.  I totally understand how it's not a good experience to use it for critical images, though!

For images that you want to bypass the blur-up effect, you could use the `fadeIn={false}` property on `gatsby-image`.  I would also make sure to exclude the `base64` from the GraphQL query though, too, so you don't wind up with that extraneous base64 placeholder in your HTML, or weighing down your data chunks.  All of this together should make it act like a normal image load, without the blur-up effect, and with the added benefit of `srcSet` and `<source>` elements set up for you.  (_If you want the images to be loaded ASAP, you can also use `loading="eager"`._)

But those images you want to be visible on first paint... yeah, I think you'd still have to inline them.  I can't think of a way to get around that.

> I think to put the base64 strings for the first three images and "lazy-load" the remaining 20 is reasonable.

Yeah, that does make sense, especially for those images that **must** be visible on first load, :100:.  Sorry I couldn't be more help!

**Comment by freiksenet** [comment]
It's not possible to change this behavior because .html files are a product of running React code in the .js bundles. I recommend not using base64 images if you are worried about their size and to use external images instead. 

You can also configure gatsby-image to not include base64 images by changing the fragment that you are using, this will also eliminate the fade-in effect.
