### ISSUE TITLE
[gatsby-plugin-mdx]wordCount for chinese is wrong

### ISSUE THREAD

**Issue by suanmei** [gatsbyjs/gatsby#22811]
## Description

In chinese, there are no spaces between words。If I wrote a paragraph, your statistics here only think it is a word

**Comment by Eyas** [comment]
Looks like the issue is here: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-mdx/gatsby/source-nodes.js#L30-L35

MDX uses `remark-retext` to compute word counts and hard-codes English (imported from `retext-english`).

[Retext](https://github.com/retextjs/retext) seems to only support English, Dutch, and Laten.

So the problems here include:

1. MDX should make the retext language parsing package parameterizable
  - It probably shouldn't include all languages, since that might balloon the package size.
2. We should figure out a retext-compatible package that works for Chinese. This might include a contribution to retextjs.

**Comment by suanmei** [comment]
I can't agree it more, do you have plan to support it.

I'm working on a boilerplate for the document web site, because I'm sick of vuepress, but the documentation site in Gatsby's theme lacks some nice-looking ones. 

If this feature is supported, this might be a good point

**Comment by danabrit** [comment]
I wonder if this is related to #22390, which has a PR attached to it.

**Comment by Eyas** [comment]
It's unfortunately not related :( the truncation library also assumed Latin script, but the remark plugin that counts words doesn't use that all all.

**Comment by jlkiri** [comment]
It is related to these issues:
https://github.com/gatsbyjs/gatsby/issues/21311
https://github.com/gatsbyjs/gatsby/issues/21357

Both issues are in `gatsby-transformer-remark` but I see the problem exists in `gatsby-plugin-mdx` as well. The fix that I wrote for `gatsby-transformer-remark` does not work with nodes yet and I think once it is refactored into a common util we can apply the same logic to  `gatsby-plugin-mdx` .

**Comment by LekoArts** [comment]
Hi!

We merged https://github.com/gatsbyjs/gatsby/pull/35650 which means that a new major version of `gatsby-plugin-mdx` will be released on August 16. You can already try it out by installing `gatsby-plugin-mdx@next` & `gatsby@next`.

We removed the `wordCount` GraphQL node and it's now in user land to add this information. So you can use whatever library you want to get a correct result.
