### ISSUE TITLE
Recommended setup for developing an external library to be used in gatsby with yarn workspaces (+lerna)? (babel-webpack)

### ISSUE THREAD

**Issue by kuworking** [gatsbyjs/gatsby#22821]
In an attempt to isolate some code that was part of a gatsby-theme into a npm library, I'm having difficulties in implementing it

I've made a repo https://github.com/kuworking/workspace-test where two setups can be tested, one that kind-of works, and the other that gives a `React minified error`

```
git clone https://github.com/kuworking/workspace-test.git
yarn
npm run build
npm run start
// (this one works)
npm run build-fail
npm run start-fail
// (this one doesn't work)
```

The one that works only uses `babel` and `babel-preset-gatsby-package` (in the package)

- it fails if using `babel-preset-gatsby`
- it also works if using `["@babel/preset-env", "@babel/preset-react"]`

```js
// .babelrc
{
  "plugins": ["babel-plugin-emotion"],
  "presets": [["babel-preset-gatsby-package", { "browser": true }]]
}

// package.json
{
  "name": "test",
  "version": "0.1.0",
  "description": "test",
  "main": "lib/index.js",
  "author": "kuworking.com",
  "license": "MIT",
  "dependencies": {
    "@babel/runtime": "^7.8.7",
    "@emotion/core": "10.0.28",
    "@emotion/styled": "10.0.27",
    "emotion-icons": "1.0.0",
    "react-helmet": "5.2.1",
    "react-intersection-observer": "8.26.1",
    "react-share": "4.1.0",
    "react-spring": "8.0.27"
  },
  "peerDependencies": {
    "gatsby": "^2.0.0"
  },
  "devDependencies": {
    "@babel/cli": "^7.8.4",
    "@babel/core": "^7.8.7",
    "babel-plugin-emotion": "^10.0.33",
    "babel-preset-gatsby-package": "^0.3.1",
    "cross-env": "^5.2.1"
  },
  "scripts": {
    "build": "babel src --out-dir lib --ignore **/__tests__,**/__mocks__",
    "build2": "webpack --config ./webpack.config.js --mode=production",
    "start": "webpack --config ./webpack.config.js --mode=development",
    "prepare": "cross-env NODE_ENV=production yarn build"
  }
}
```

And the one that doesn't work uses `webpack`, in a way that IMO should work (obviously not, but first time using `webpack` here)

- It neither works if using `babel-preset-gatsby-package`

```js
// .babelrc
{
  "plugins": ["babel-plugin-emotion"],
  "presets": ["@babel/preset-env", "@babel/preset-react"]
}

// webpack.config.js
module.exports = (env, argv) => {
  const mode = argv.mode || 'development'

  const config = {
    entry: './src/index.js',
    output: {
      path: `${__dirname}/lib`,
      filename: 'index.js',
      library: 'test-fail',
      libraryTarget: 'umd',
    },
    module: {
      rules: [
        {
          test: /\.(js|jsx)$/,
          exclude: /node_modules/,
          use: ['babel-loader'],
        },
      ],
    },
    devtool: mode === 'development' ? 'cheap-module-eval-source-map' : false,
  }
  return config
}

// package.json
{
  "name": "test-fail",
  "version": "0.1.0",
  "description": "test-fail",
  "main": "lib/index.js",
  "author": "kuworking.com",
  "license": "MIT",
  "dependencies": {
    "@babel/runtime": "^7.8.7",
    "@emotion/core": "10.0.28",
    "@emotion/styled": "10.0.27",
    "emotion-icons": "1.0.0",
    "react-helmet": "5.2.1",
    "react-intersection-observer": "8.26.1",
    "react-share": "4.1.0",
    "react-spring": "8.0.27"
  },
  "peerDependencies": {
    "gatsby": "^2.0.0"
  },
  "devDependencies": {
    "@babel/cli": "^7.8.4",
    "@babel/core": "^7.8.7",
    "@babel/node": "^7.8.7",
    "@babel/preset-env": "^7.9.0",
    "@babel/preset-react": "^7.9.4",
    "babel-loader": "^8.1.0",
    "babel-plugin-emotion": "^10.0.33",
    "webpack": "^4.42.1",
    "webpack-cli": "^3.3.11"
  },
  "scripts": {
    "build": "webpack --config ./webpack.config.js --mode=production",
    "start": "webpack --config ./webpack.config.js --mode=development",
    "prepare": "yarn build"
  }
}
```

What is the recommended way? Is there a `webpack` configuration that works? or some doc that clarifies this a little bit?

**Comment by Js-Brecht** [comment]
`babel-preset-gatsby-package` is generally for compiling gatsby's internal packages.  It will transpile everything to CommonJS, so that it can be consumed by Node.  `babel-preset-gatsby` is what is used for transpiling everything for consumption on the web, so pretty much all of the standard App stuff.

You might use `babel-preset-gatsby-package` if you're writing a plugin in ES6, and you want to transpile it to CommonJS so that Gatsby can pick it up without a problem.

It's not usually recommended to create a `.babelrc`, or a `webpack.config.js`, when using Gatsby, mainly because it overwrites the internal configurations that Gatsby uses.

To alter the `babel` or `webpack` configs, it's usually better to use [onCreateWebpackConfig](https://www.gatsbyjs.org/docs/node-apis/#onCreateWebpackConfig) and [onCreateBabelConfig](https://www.gatsbyjs.org/docs/node-apis/#onCreateBabelConfig)

**Comment by Js-Brecht** [comment]
If what you're trying to do is design some React components that you can reuse in your other projects, then I think you should be able to use `babel-preset-gatsby`.  As for the Webpack configuration... it's been so long since I've tried to build that from the ground up... I'd have to brush up on it a bit :laughing: .

**Comment by Js-Brecht** [comment]
I actually just had a closer look your repo, and I see that is what you are doing.  It makes sense, then, to just use babel.  There's no need to bundle everything with Webpack, because it will all get bundled up in the final product anyway.  You just need it in a format that can be consumed easily.

I think it's interesting that `babel-preset-gatsby` doesn't work for you.  I'll clone your repo, and try out a few things, and see what I can come up with.

**Comment by Js-Brecht** [comment]
Sorry about the rapid fire comments.

---

Okay, I've got a working prototype.  It makes sense that `babel-preset-gatsby` wasn't working... it's Gatsby specific, naturally!  So it depends on some Gatsby related information that is set up during a build.

However, it is probably the best configuration to do this, so I just took it and adapted it to work for you.  I've taken your `test-fail` project, and turned it into a `test-working!`

<details>
<summary>This is the <code>.babelrc.js</code> I used to make it work</summary>

```js
// .babelrc.js
const resolve = m => require.resolve(m)

module.exports = {
  presets: [
    [
      resolve(`@babel/preset-env`),
      {
        corejs: 2,
        loose: true,
        modules: `commonjs`, // <-- this is important
        useBuiltIns: `usage`,
        targets: {
          node: `current`,
        },
        // Exclude transforms that make all code slower (https://github.com/facebook/create-react-app/pull/5278)
        exclude: [`transform-typeof-symbol`],
      },
    ],
    [
      resolve(`@babel/preset-react`),
      {
        useBuiltIns: true,
        pragma: `React.createElement`,
        development: false,
      },
    ],
  ],
  plugins: [
    [
      resolve(`@babel/plugin-proposal-class-properties`),
      {
        loose: true,
      },
    ],
    [resolve(`@babel/plugin-proposal-nullish-coalescing-operator`)],
    [resolve(`@babel/plugin-proposal-optional-chaining`)],
    resolve(`babel-plugin-macros`),
    resolve(`@babel/plugin-syntax-dynamic-import`),

    [
      resolve(`@babel/plugin-transform-runtime`),
      {
        corejs: false,
        helpers: true,
        regenerator: true,
        useESModules: false,
      },
    ],

    [
      resolve(`@babel/plugin-transform-spread`),
      {
        loose: false,
      },
    ],
    resolve(`babel-plugin-dynamic-import-node`),
  ],
}
```
</details>

<details>
<summary>This is how I needed to change <code>package.json</code></summary>

```diff
diff --git a/packages/test-fail/package.json b/packages/test-fail/package.json
index afde12c..4abf794 100644
--- a/packages/test-fail/package.json
+++ b/packages/test-fail/package.json
@@ -22,16 +22,22 @@
     "@babel/cli": "^7.8.4",
     "@babel/core": "^7.8.7",
     "@babel/node": "^7.8.7",
+    "@babel/plugin-proposal-class-properties": "^7.8.3",
+    "@babel/plugin-proposal-nullish-coalescing-operator": "^7.8.3",
+    "@babel/plugin-proposal-optional-chaining": "^7.9.0",
+    "@babel/plugin-syntax-dynamic-import": "^7.8.3",
+    "@babel/plugin-transform-runtime": "^7.9.0",
+    "@babel/plugin-transform-spread": "^7.8.3",
     "@babel/preset-env": "^7.9.0",
     "@babel/preset-react": "^7.9.4",
     "babel-loader": "^8.1.0",
+    "babel-plugin-dynamic-import-node": "^2.3.0",
     "babel-plugin-emotion": "^10.0.33",
+    "babel-plugin-macros": "^2.8.0",
     "webpack": "^4.42.1",
     "webpack-cli": "^3.3.11"
   },
   "scripts": {
-    "build": "webpack --config ./webpack.config.js --mode=production",
-    "start": "webpack --config ./webpack.config.js --mode=development",
-    "prepare": "yarn build"
+    "build": "babel src -d lib"
   }
 }
```

</details>

**Comment by kuworking** [comment]
I'll need some time to understand what you've done here 😅 but thanks a lot (!) for your time and efforts, I mean big thanks 🙌

Perhaps you (as gatsby) could offer in the future one (this) boilerplate for structuring development setups (i'd swear this is already done for gatsby-themes in the docs, or maybe it was in some blog post...)

Anyway, I'll work on this asap, and I guess we can close the issue now

**Comment by Js-Brecht** [comment]
I think why this particular case isn’t generally covered is because it’s pretty much external to Gatsby.  You’re basically creating a React component library that can be consumed by any React project, not just Gatsby.

I’m pretty sure it can also be done through Webpack if you really wanted to, or Rollup.  I think you can even use create-react-app to do this.  It just has to be consumable by node/webpack.

Gatsby themes are a little different.  I was actually going to suggest looking into them, because you’re using `emotion`.  With a theme, you could set up a `gatsby-config` that configures `gatsby-plugin-emotion` for the consumer, and still have it act as mostly just a library.  Check out [this post on shadowing](https://www.gatsbyjs.org/docs/themes/shadowing/).  Done that way, you shouldn’t even need to worry too much about transpiling your source.

It doesn’t really replace the feel of using an actual component library, though.  Perhaps it would make sense to set up your component library like a theme, in the sense that you set up the `gatsby-config` with the plugins needed to operate in a Gatsby environment, but still get all of your source files “production ready”, so you can consume them the same way you would from a production library.  In your consuming project, you add your library to the `gatsby-config` so that it receives all of those plugin configurations, and then use all of the components how you normally would.

---

Okay, I’ll go ahead and close this now.  If you have more questions, don’t hesitate to ask!
