### ISSUE TITLE
Markdown Content source from REST API - How to have image processed by Gatsby Image

### ISSUE THREAD

**Issue by phanatuan** [gatsbyjs/gatsby#22847]
Hi, 

I have trouble config Gatsby to process image in the `markdown content` I source from an external REST API. 

I do research and `gatsby-remark-image` could only transform image in `markdown` file source from `fileSystem`. 

The `Gatsby Remark Images Anywhere` (https://www.gatsbyjs.org/packages/gatsby-remark-images-anywhere/) also depends on markdown file in the filesystem. 

How could I do it in this scenario? 

My `create-node`: 

```javascript
exports.sourceNodes = async ({
  actions,
  createNodeId,
  createContentDigest,
}) => {
  const postRes = await axios.get(`http://localhost:8082/api/post`) // <----- SOURCE FROM REST API
  const allPosts = postRes.data.data;

  await Promise.all(
    allPosts.map(post => {
      const node = {
        id: createNodeId(`Post-${post.slug}`),
        title: post.title,
        description: post.description,
        content: post.content,
        internal: {
          type: "CustomPost",
          contentDigest: createContentDigest(post),
        },
      };
      return actions.createNode(node);
    }),
  );
};
```

I then use `react-markdown` to display the content: 

```javascript
<div className="blog-post-content">
     <ReactMarkdown source={content} /> 
     //<----- the content is markdown string with images such as [](http://amazon.aws.com/random-image.png)
 </div>
```

How could I have Gatsby to process these images in the custom` content` Markdown string. 

Thank you so much

**Comment by LekoArts** [comment]
Thank you for opening this!

As written out in the docs (https://www.gatsbyjs.org/docs/creating-a-source-plugin/#transforming-data-received-from-remote-sources) you'll need to set your `mediaType` to `text/markdown` and add `gatsby-transformer-remark` to your gatsby-config.js so that the transformer automatically adds a `childMarkdownRemark` field.

Then the mentioned `gatsby-remark-images-anywhere` should work.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
