### ISSUE TITLE
core(www): unpkg responds with  "Response code 429 (Too Many Requests)"

### ISSUE THREAD

**Issue by muescha** [gatsbyjs/gatsby#22894]
## Description

requesting README from `https://unpkg.com/` results in "Response code 429 (Too Many Requests)"

### Steps to reproduce

- checkout gatsby
- open https://github.com/gatsbyjs/gatsby/blob/f95cd06bb8454ae3a9dd746f6e4fa3f12bdc3717/packages/gatsby-source-npm-package-search/src/gatsby-node.js#L38-L46
- add line into the catch blog:

```javascript
console.log(`"${hit.objectID}" - error "${err.message}" `);
```
- run `gatsby develop`

### Expected result

- it should only print 404 error messages resulting from missing README

### Actual result

many times i see the error:

-  "Response code 429 (Too Many Requests)"

**Comment by pieh** [comment]
Related (why we get 429 responses) - https://github.com/mjackson/unpkg/issues/237

Seems like in most cases the request is handled by CDN, but sometimes it passes it directly to server which might just not be able to handle high load.

Just a question is how we should handle this more gracefully 🤔

**Comment by arguiot** [comment]
The best option is to use jsDelivr. It's currently the best CDN out there with CDNJS and unlike CDNJS, it supports all npm packages. It relies on multiple CDN providers (Cloudflare, Fastly, StackPath, ...).

**Comment by muescha** [comment]
intersting suggestion...

**Comment by arguiot** [comment]
I've looked on Google for a possible answer and I found that the response on UNPKG: `Response code 429 (Too Many Requests)` was due to a bug/config problem on CloudFlare which causes the traffic to be redirected to Google Cloud in some situations: https://github.com/mjackson/unpkg/issues/237#issuecomment-568770980

I'm not sure if the issue comes from Cloudflare or UNPKG (honestly I believe this is a problem with UNPKG, but the developer hasn't spoken on this yet...).

The obvious solution for Gatsby is to use jsDelivr (as I said before). The PR would be super easy to do and it will fix this issue.

**Comment by muescha** [comment]
@arguiot there are more arguments that jsDeliver is better?

Note to me: i removed the stale, because i try to check if some README are available which are not in unpkg but in the repo (i working on a PR about this)

**Comment by arguiot** [comment]
Well, the technology used by jsDelivr and UNPKG is the same (Cloudflare), but jsDelivr also uses multiple external providers on top of Cloudflare, like Fastly, NS1, ... so in the case one of them fails, the traffic will be redirected. It's not the case for UNPKG unfortunately, that's why errors happen from time to time.

jsDelivr has other advantages, but we don't care about them here I think.
