### ISSUE TITLE
Feature Request: Expose graphql source query.

### ISSUE THREAD

**Issue by MarcMcIntosh** [gatsbyjs/gatsby#22919]
## Summary

At prismic we have a use-case for re-running a graphql source query during runtime and would like to know if there is an already existing solution to exposing the source-query or make a feature request.

Our main use-case is to re-run the query at run-time in-order to make preview work. see example below:
```jsx
import { StaticQuery, graphql } from 'gatsby';
import { withPreview } from 'gatsby-source-prismic-graphql';

const articlesQuery = graphql`query { prismic { ... } }`;

export const Articles = () => (
  <StaticQuery query={articlesQuery} render={withPreview(data => { ... }, articlesQuery)} />
);
```

### Basic example

Our current solution involves patching the babel-plugin-remove-graphql with this <https://github.com/birkir/gatsby-source-graphql-universal/blob/master/scripts/patches/babel-plugin-remove-graphql-queries.patch>
But this patch breaks useStaticQuery site-wide.

### Motivation

Why are we doing this?
+ We do this to provided a better user experience when using our preview feature

What use cases does it support?
+ Fetching and using data from a content management service client side.

What is the expected outcome?
+ Alternative methods to achieve these same goals.
+ or expose the graphql query source so it can be re-run

We would be happy to make a PR to enable this feature.

**Comment by pieh** [comment]
Question - what's the shape of expected 2nd parameter for `withPreview`?

Another question about
> But this patch breaks useStaticQuery site-wide.

Does it break it for both `gatsby build` and `gatsby develop`? or just `gatsby develop`? I would expect it to break only for `gatsby develop` and it would fail with `Loading (StaticQuery)` behaviour? Is that correct? If that's not the case - could you describe how exactly it breaks?

As far as to how this could be attacked - I have few ideas:
I think that changing our replacing from ``graphql`query { }` `` -> `<hash>` to object that contains `<hash>` and `<query_text>` is good direction, but we will need more changes:
- our `<StaticQuery>` component / `useStaticQuery` hook relies right now on the `query` prop to be a hash string - see implementation of those in https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/cache-dir/gatsby-browser-entry.js - in particular how we try to get data from StaticQueryContenxt (which is a dictionary of `hash` -> `result`):
  - `<StaticQuery>`: https://github.com/gatsbyjs/gatsby/blob/246c39cf2dc419fc2bc55ff95812598d90e97789/packages/gatsby/cache-dir/gatsby-browser-entry.js#L22
  - `useStaticQuery`: https://github.com/gatsbyjs/gatsby/blob/246c39cf2dc419fc2bc55ff95812598d90e97789/packages/gatsby/cache-dir/gatsby-browser-entry.js#L60
So those would likely need to be adjusted to access `query.id` (if I read the babel plugin changes correctly)

**Comment by pieh** [comment]
Just to note so it's not forgotten - making change like that in babel plugin will require major version bump for babel plugin (not a blocker) - needed because older gatsby version could accidenetally pull `latest` babel plugin and that would be incompatible with implementation of static queries in older gatsby versions

**Comment by MarcMcIntosh** [comment]
Hi Pieh,

Thanks for writing back.

To answer your questions.

> the shape of expected 2nd parameter for withPreview?
In the code it can either be `undefined`, a `sting` or on object with a source property that contains the query.
Here's a diff from the `Transforms queries in useStaticQuery` snapshot:
```diff
import staticQueryData from "public/static/d/2626356014.json";
import * as React from 'react';
export default (() => {
-   const siteTitle = staticQueryData.data;
+   const siteTitle = {
+     id: "2626356014",
+     source: "{site { siteMetadata { title }}}",
+
+     toString() {
+       return this.id;
+     }
+
+   };
  return React.createElement("h1", null, siteTitle.site.siteMetadata.title);
});
```
Here's the fork for `gatsby-source-prismic-graphql` the test where run from if you would like a closer look: <https://github.com/prismicio/gatsby-source-prismic-graphql/tree/flat>

> Does it break it for both gatsby build and gatsby develop?
Oddly enough it breaks in `gatsby devlop` with an error `TypeError: Cannot read property 'siteMetadata' of undefined` happening on the client side.
Here's an example project we're using <https://github.com/matthewlein/prismic-gatsby-errors> 

Looking at the diff maybe the source-prismic-graphql plugin is stripping out some of the data that would explain there error above.

>So those would likely need to be adjusted to access query.id (if I read the babel plugin changes correctly).
Yes that seems to be the case, How would this influence other parts of the code base?

**Comment by MarcMcIntosh** [comment]
Wait... actually that example could another project that was having issue with the plugin. 
Let me double check :/

**Comment by MarcMcIntosh** [comment]
Hi,
I made an new test/example project to confirm some of the previous errors with useStaticQuery breaking. https://github.com/MarcMcIntosh/use-static-query-gatsby-prismic-source-graphql-bug

From what I can tell the breakage of useStaticQuery seems to have stoped, although it usually comes back after an update as one of the plugins patches `babel-plugin-remove-graphql-queries`.

**Comment by MarcMcIntosh** [comment]
@pieh 
Will the integration and end-to-end tests be able to detect what packages will be impacted by any changes to `babel-plugin-remove-graphql-queries`?

**Comment by pieh** [comment]
> > Does it break it for both gatsby build and gatsby develop?
> 
> Oddly enough it breaks in `gatsby devlop` with an error `TypeError: Cannot read property 'siteMetadata' of undefined` happening on the client side.

Ah the error is different, but it's actually pretty similar root reason - it's just that user code expect query result output, which it doesn't get and there is no "null checking" likely in the code so it fails hard with error like that instead of displaying "placeholder".

I also was made aware of https://www.gatsbyjs.org/packages/gatsby-source-graphql-universal/#getisolatedquery which seems pretty similar to what we are trying to do here? This might be "solved" problem already?

**Comment by MarcMcIntosh** [comment]
@pieh 

We're aware of the `gatsby-source-graphql-universal` the plugin works by replacing `babel-plugin-remove-graphql-queries.js` with a slightly modified version. 

I've made pull request that fixes the `siteMetadata` error. https://github.com/birkir/gatsby-source-graphql-universal/pull/15 as it's a dependancy of https://github.com/birkir/gatsby-source-prismic-graphql. At prismic we recommend people to use the `gatsby-source-prismic-graphql` plugin so they easily use the features prismic offers in their gatsby project.

Although modifying the `babel-plugin-remove-graphql-queries.js` via a plugin does work it this can cause other issues when updates to the original babel plugin are done, or if other plugins rely on the out put of the plugin such as the `gatsby/packages/gatsby/cache-dir/gatsby-browser-entry.js` you mentioned earlier. 

Ideally we would like to add the modifications done to the babel plug's source rather than replacing the plugin with `gatsby-source-graphql-universal`.

Are there tests to check all the plugins work together? 

I saw that there are some integration and end-to-end tests and would like to know if there is any additional set-up required to get them to pass before making any modifications to the `babel-plugin-remove-graphql-queries.js` file.

**Comment by pieh** [comment]
It does seems sensible to put modifications that `gatsby-source-graphql-universal` does in core. Just keep in mind that we need to make sure that the query text we will leave in source code can be "tree shaken" so if user doesn't try to reuse it in runtime it doesn't bloat bundles we produce. Terser should take care of that if they are not referenced anywhere but it needs some manual checking (and we might just add some hacky test that tries to `grep` produced bundles and only can find queries that are being referenced again).

I mentioned that plugin mostly because this problems was solved already in some way, so we should use whatever that plugin is doing to not have to re-invent the wheel here ;) (or at least as starting point, I have no insight into how exactly it's done in that plugin so we might discover issues with it)

> Are there tests to check all the plugins work together?

Depends what exactly you mean - our e2e tests will use `babel-plugin-remove-graphql-queries` (so when you open PR with modifications there, those will use modified versions) as part of regular `gatsby build`/`gatsby develop`

Not real e2e-test / integration tests (at least in our repo) when it comes to 3rd party plugins. Our e2e tests do check for couple of usual and common plugins or packages (like `react-helmet` / `gatsby-link` / `gatsby-image` ). But we do run gatsby using changed.

You can run the locally using https://github.com/gatsbyjs/gatsby/blob/master/scripts/e2e-test.sh as starting point:
 - use `gatsby-dev-cli` in one of e2e tests directories (ideally both https://github.com/gatsbyjs/gatsby/tree/master/e2e-tests/production-runtime and https://github.com/gatsbyjs/gatsby/tree/master/e2e-tests/development-runtime as `dev` and `prod` versions are bit different)
 - run `yarn test` in those e2e tests (it might take a bit of time)

**Comment by MarcMcIntosh** [comment]
Hi @pieh 

Thanks for the info about running the end-to-end tests, they pass with the modifications made to `babel-plugin-remove-graphql-queries` :)

> Just keep in mind that we need to make sure that the query text we will leave in source code can be "tree shaken" so if user doesn't try to reuse it in runtime it doesn't bloat bundles we produce.

Sounds interesting, I'll take a quick look through to see what I can find then make a PR :)

**Comment by MarcMcIntosh** [comment]
PR https://github.com/gatsbyjs/gatsby/pull/23423
