### ISSUE TITLE
Handling page redirects based on visitor location in Gatsby

### ISSUE THREAD

**Issue by woodwoerk** [gatsbyjs/gatsby#22938]
## Summary

I'm building a Gatsby site deployed to Netlify and I'm wondering if there's a recommended way to make Netlify redirects work nicely with Gatsby Link and Gatsby's clever preloading of pages and assets.

For example, I have a redirect set up in Netlify to redirect visitors in the US from `/store/` to `/us-store/`. The other pages are the same for all visitors in all countries with no redirects. If a visitor in the US arrives at `/`, Gatsby will preload `/store/` and a request will never hit Netlify's servers to handle the redirect.

1. Is there a recommended approach for these kinds of redirects in Gatsby?
2. Is there a workaround to "force" Gatsby Link to navigate using `window.location` in certain cases (similar to the behaviour of [handling stale pages](https://www.gatsbyjs.org/docs/gatsby-link/#handling-stale-client-side-pages), or should I just use an `<a>` element?

A huge thank you to all Gatsby contributors ❤️

**Comment by pieh** [comment]
The netlify redirects are "server" redirects and Gatsby itself is just not aware of them.

One way to handle this is to create locale-aware wrapper around `gatsby-link` that would automatically adjust `to/href`.

For example here's what we have for gatsbyjs.org (which is in the process of adding translation - not yet shipped) - https://github.com/gatsbyjs/gatsby/blob/317da55266d31fb7794e453fdf37ae0578ee5da1/www/src/components/localized-link.js

But there is one additional quirk in your case - the `/` page being shared for all languages, means that there will be single `.html` file for it. One the react mount on that file it uses hydration, which requires first client render to match exactly what is in .html file (which in practice for you means that you will have to make sure the first render is using un-localized link, and then update it with localized one - see React documentation about hydration - https://reactjs.org/docs/react-dom.html#hydrate
> React expects that the rendered content is identical between the server and the client. It can patch up differences in text content, but you should treat mismatches as bugs and fix them.
> [...]
> There are no guarantees that attribute differences will be patched up in case of mismatches.
The attribute part is important because `to` prop / `href` attribute is an attribute

On the same page there is note about how to workaround this:

> If you intentionally need to render something different on the server and the client, you can do a two-pass rendering. Components that render something different on the client can read a state variable like this.state.isClient, which you can set to true in componentDidMount(). This way the initial render pass will render the same content as the server, avoiding mismatches, but an additional pass will happen synchronously right after hydration. Note that this approach will make your components slower because they have to render twice, so use it with caution.

**Comment by woodwoerk** [comment]
Thanks @pieh for the thorough response! 

The tricky part in this use case is that translations must be kept separate from regional pages. For example, visiting `/store/` from the US should be redirected to `/us-store/` (and this redirect is handled by Netlify). However the `/us-store/` page itself has a language selector allowing a visitor to view that regional page in Spanish. This is to ensure we show US specific content regardless of selected language (bear with me because I realise this isn't Gatsby specific).

> The netlify redirects are "server" redirects and Gatsby itself is just not aware of them.

Exactly right, this is why I was wondering with point 2 if there's a way to "force" Gatsby Link to send a request to the server for the clicked page. This would then mean Netlify can handle my redirects successfully. Is this possible?

**Comment by woodwoerk** [comment]
I opted for a similar solution that you guys are working on for translating gatsbyjs.org. I'm using the user's IP location and checking this against a page's possible `regionalPaths`, then as you suggested switching in the regional link after hydration. Thanks again!

```js
import React from 'react'
import PropTypes from 'prop-types'
import { Link } from 'gatsby'
import { useIpLocation } from '../context/global'

const RegionalLink = ({ page, ...props }) => {
  const countryCode = useIpLocation()

  let { path } = page
  const { regionalPaths } = page

  if (countryCode && regionalPaths?.length) {
    const regionalPath = regionalPaths.find(({ countries }) =>
      countries.includes(countryCode)
    )

    if (regionalPath) {
      path = regionalPath.path
    }
  }

  return <Link to={path} {...props} />
}

RegionalLink.propTypes = {
  page: PropTypes.shape({
    path: PropTypes.string,
    regionalPaths: PropTypes.arrayOf(
      PropTypes.shape({
        countries: PropTypes.arrayOf(PropTypes.string),
        path: PropTypes.string,
      })
    ),
  }).isRequired,
}

export default RegionalLink

```
