### ISSUE TITLE
No change in innerHtml if navigation between pages in jest wit nested Link & fireEvent.click(tree.getByTestId("blabla"))

### ISSUE THREAD

**Issue by dmandreev** [gatsbyjs/gatsby#22980]
I'm trying to simulate navigation clicks from page component. I successfylly get link instance by getByTestId,
but then I call click(), excception thrown 

`"Not implemented: navigation (except hash changes)"`

how correctly configure test and  check that actual html was changed after Link navigation

```
import * as React from "react"
import { render, waitFor } from "@testing-library/react";
import IndexPage from "../index.js"

describe("IndexPage", () => {

  it("renders correctly", async () => {


    const rendered = render(<IndexPage />);

    const productsModalButton = rendered.getByTestId("product-greenrain-facility");

    waitFor(() => productsModalButton.click());

    // eslint-disable-next-line no-console
    console.log(rendered);

  })

})
```

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction
