### ISSUE TITLE
Injecting CSS reset before typography.js styles?

### ISSUE THREAD

**Issue by nextriot** [gatsbyjs/gatsby#23039]
Hi.

I'm using Tailwind CSS in conjunction with typography.js via the official plugin.
I want to use tailwind's base styles and want typography to overwrite the styles thereafter.

The issue being that both in development and production, typography inserts itself as the first style component in the head tag.

I currently import tailwind in the `gatsby-browser` file which is too late. It mentions in the following [Styling with CSS](https://www.gatsbyjs.org/docs/recipes/styling-css/) article:

> Note: You can also make use of require('./src/styles/global.css') to import the global CSS file in your gatsby-config.js file.

Though in practice this doesn't seem to be correct. It reports an `invalid symbol...` error once it meets a curly brace when building.

Can anyone outline how I could influence the build ordering, or provide an alternative solution that would let me import the reset before typography injects its styles?

I tried via html.js also, but to no avail.

Thanks in advance.

**Comment by Js-Brecht** [comment]
The issue you're encountering is caused by `gatsby-plugin-typography` [reordering the head components](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-typography/src/gatsby-ssr.js#L24-L35) during SSR.

I think an easy way for you to do this would be to create your own `gatsby-ssr`, and load the CSS into the top of the `<head>` element yourself.

Here's an example where I use an inline loader to read/process the CSS, and then prepend it to the rest of the head components.

```js
import React from 'react';
import FooCss from '!postcss-loader!./src/test.css';

export const onPreRenderHTML = ({ getHeadComponents, replaceHeadComponents }) => {
    replaceHeadComponents([
        <style
            key='custom-styles'
            dangerouslySetInnerHTML={{
                __html: FooCss,
            }}
        />
    ].concat(getHeadComponents()))
}
```

Because I wanted to do CSS minifying, I included this `postcss.config.js` file in the root of my repository:

```js
module.exports = {
    plugins: {
        autoprefixer: {},
        cssnano: { preset: 'default' },
    }
}
```

My `test.css` file looks like this:
```js
.foobar {
    font-weight: 800;
}
```

And the relevant part of my resulting pages look like this:
```html
<style>.foobar{font-weight:800}</style><style id="typography.js">
```

More could probably be done with `css-loader` and others, but it was more than I needed for this little bit.  You could also do `!file-loader!extract-loader!... etc`, and then load the value of that into a `<link>` element, instead of inlining it into a `<style>` element.

**Comment by nextriot** [comment]
Thanks a bunch for the awesome insight @Js-Brecht!

I replicated your initial example, and though it did append the styles as the first tag after meta tags, typography.js appends itself at the very top of head. 

Not sure how the ordering is dictated, so I'm still at a loss.

**Comment by Js-Brecht** [comment]
Can you share your repo, or a reproduction?  It might be easier to see what’s happening with yours if I can see the code

**Comment by nextriot** [comment]
Thank you so much for the generous help. Certainly, the code is here: https://github.com/nextriot/nextriot.github.io/tree/develop

If you inspect the h1 tag on the index page you'll see an example of the undesired order, and of course just seeing the tag order in head itself.

Thanks again!

**Comment by Js-Brecht** [comment]
This is the rendered order of the CSS in inspector:
![image](https://user-images.githubusercontent.com/1935258/79089082-7bd07900-7ce0-11ea-8a93-fc0f019edf41.png)

If I go to the stylesheet itself for each section, I see that the top is generated by `typography`, and the next three are generated by `./src/utils/base.min.css` (the `normalize.css`).  That's not what you're aiming for?

Looking at the HTML, I also see that the CSS injected from `gatsby-ssr` is the first `<style>` in the `<head>`:
![image](https://user-images.githubusercontent.com/1935258/79089278-4bd5a580-7ce1-11ea-830a-b8ed0f7c04f6.png)

Perhaps I've misunderstood what you're goal is.

---

On a semi-unrelated note, you probably don't need `postcss-loader` if the CSS is already processed.  `raw-loader` would be simpler, since no extra configurations are needed.  I guess it just depends on what kind of processing you want to do with it.

**Comment by nextriot** [comment]
Right! My apologies, I should have clarified that this was talking place in dev via gatsby develop.

**Comment by Js-Brecht** [comment]
Ohhh, I see.  Yeah... that ones going to be a bit harder to fix since it doesn't follow the same procedures as a production build.

You can see how `typography` loads those styles in development [here](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-typography/src/gatsby-browser.js#L18), and that `injectStyles()` function is [here](https://github.com/KyleAMathews/typography.js/blob/master/packages/typography/src/index.js#L68-L85).  You see [here](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-typography/src/gatsby-ssr.js#L6) that it completely skips injecting the styles during SSR if it is a production build.

Altogether, this means that typography's `onPreRenderHTML()` doesn't have any effect during a development build, because it relies on the component being injected in `onRenderBody()` in order to sort it.  That also means that `injectStyles()` in `gatsby-browser` forces `typography` to inject its styles directly into the DOM, at the very top of the `<head>` element.

So, here's the fun part.  You need to inject your styles in much the same way as `typography`, but you also need to make sure you only do it during `develop` mode, because you don't want it happening during runtime in production.  The other thing you need to do is make sure that your `gatsby-ssr` only does its work during a production build.

```js
// gatsby-ssr.js
import React from 'react'
import { wrapRootElement as wrap } from './wrap-root-element'
import CSSReset from '!postcss-loader!./src/utils/base.min.css'

export const onPreRenderHTML = ({
  getHeadComponents,
  replaceHeadComponents,
}) => {
  if (process.env.BUILD_STAGE === 'build-html') {
    replaceHeadComponents(
      [
        <style
          key="custom-styles"
          id="css-reset-ssr"
          dangerouslySetInnerHTML={{
            __html: CSSReset,
          }}
        />,
      ].concat(getHeadComponents())
    )
  }
}

export const wrapRootElement = wrap
```
```js
// gatsby-browser.js
import './src/utils/prism.css'
import './src/utils/global.css'
// import 'tailwindcss/dist/base.css'

import { wrapRootElement as wrap } from './wrap-root-element'

export const wrapRootElement = wrap

export const onClientEntry = () => {
    if (process.env.BUILD_STAGE === 'develop') {
        const head = document.head;
        const typographyEl = document.getElementById('typography.js');

        const CSSReset = require('!postcss-loader!./src/utils/base.min.css');
        const styleNode = document.createElement('style')
        styleNode.id = 'css-reset';
        styleNode.innerHTML = CSSReset;
        
        if (typographyEl) {
            head.insertBefore(styleNode, typographyEl);
        } else {
            if (head.firstChild) {
                head.insertBefore(styleNode, head.firstChild);
            } else {
                head.appendChild(styleNode);
            }
        }
    }
}
```

You should only see your `<style id="css-reset">` in the DOM during development, and you should only see `<style id="css-reset-ssr">` in the DOM during production.  They should never be there at the same time.

Since that part in `gatsby-browser` only runs during `develop`, you shouldn't have to worry about it getting bundled up into the production code.  I did some testing to make sure, and the only time I saw the CSS get bundled in production was if I accessed the `require()` value from outside of the `if` condition.  Webpack will handle a `require()` statement like that dynamically if it's not at the top level.

You should be able to grep your `public` folder for `normalize.css` and not find anything in your `.js` files after a production build.  You can also run `gatsby build --no-uglify` so that it's easier to read the Webpack code, then look in `app.*.js` for `onClientEntry` and trace it to where ever it leads to make sure no data wound up in there that you don't want.

**Comment by Js-Brecht** [comment]
> Note: You can also make use of require('./src/styles/global.css') to import the global CSS file in your gatsby-config.js file.

It seems really strange to me that that would be in the docs.  It doesn't make any sense; `gatsby-config` is not processed by Webpack... if you **were** able to import CSS directly into a CommonJS file without the help of Webpack, you would still need to get it into the bundle somehow.  Weird :thinking:

**Comment by nextriot** [comment]
You are a king amongst men @Js-Brecht! Thank you so much for not only providing a solution, but even going into the logic behind the decisions. You truly satisfied the maxim of 'Give a man a fish... teach a man to fish...'

Thank you again for your time, help & knowledge. 
I hope I can repay the kindness.
