### ISSUE TITLE
Error when building in develop but not in release

### ISSUE THREAD

**Issue by ZenTauro** [gatsbyjs/gatsby#23054]
## Description

Since I updated Gatsby from 2.18.5 to 2.18.17 I now always get the following error when I use `npx gatsby develop` in the browser: `ReferenceError: _createSuper is not defined`

### Steps to reproduce
```
git clone 'https://github.com/ZenTauro/web-blog.git'
git checkout 0509604986a5efd812d0ca3e016300e6143577e2
npm install
npx gatsby develop
```
Open the browser in the address where gatsby develop is serving and you will see the error:
```
ReferenceError: _createSuper is not defined
./.cache/query-result-store.js/</StaticQueryStore<
```

### Expected result

Everything builds correctly as it did with the previous version and as it does with a release version.

### Actual result

I get an error and nothing renders.

### Environment
```
  System:
    OS: Linux 5.5 Manjaro Linux
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 13.12.0 - /usr/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 6.14.4 - /usr/bin/npm
  Languages:
    Python: 3.8.2 - /usr/bin/python
  Browsers:
    Firefox: 75.0
  npmPackages:
    gatsby: ^2.20.18 => 2.20.18
    gatsby-background-image: ^0.3.6 => 0.3.6
    gatsby-image: ^2.3.2 => 2.3.2
    gatsby-plugin-catch-links: ^2.2.1 => 2.2.1
    gatsby-plugin-google-tagmanager: ^2.2.1 => 2.2.1
    gatsby-plugin-lodash: ^3.2.1 => 3.2.1
    gatsby-plugin-manifest: ^2.3.3 => 2.3.3
    gatsby-plugin-offline: ^2.2.10 => 2.2.10
    gatsby-plugin-react-helmet: ^3.2.2 => 3.2.2
    gatsby-plugin-sass: ^2.2.1 => 2.2.1
    gatsby-plugin-sharp: ^2.5.4 => 2.5.4
    gatsby-plugin-sitemap: ^2.3.1 => 2.3.1
    gatsby-plugin-styled-components: ^3.2.1 => 3.2.1
    gatsby-plugin-tslint: 0.0.2 => 0.0.2
    gatsby-plugin-typescript: ^2.3.1 => 2.3.1
    gatsby-plugin-typography: ^2.4.1 => 2.4.1
    gatsby-remark-autolink-headers: ^2.2.1 => 2.2.1
    gatsby-remark-copy-images: ^0.2.1 => 0.2.1
    gatsby-remark-external-links: 0.0.4 => 0.0.4
    gatsby-remark-images: ^3.2.2 => 3.2.2
    gatsby-remark-prismjs: ^3.4.1 => 3.4.1
    gatsby-remark-relative-images: ^0.2.3 => 0.2.3
    gatsby-source-filesystem: ^2.2.2 => 2.2.2
    gatsby-transformer-remark: ^2.7.1 => 2.7.1
    gatsby-transformer-sharp: ^2.4.4 => 2.4.4
  npmGlobalPackages:
    gatsby-cli: 2.8.27
```

**Comment by LekoArts** [comment]
Thank you for opening this!

I cloned your repository and checked out the hash you gave me. I deleted the `package-lock.json` and ran a fresh install, then run `npm run start` and all works fine. My suspicion is that 2.18.7 changed something that is incompatible with the latest version of `gatsby-cli` or your `.cache` folder is outdated and you'll need to do a `gatsby clean`.

You shouldn't run `npx gatsby develop` as it's unnecessary. The local project you have already has `gatsby` installed so you should run `npm run start` instead.

Since I deleted your lock file I installed the `latest` version of every package, e.g. `gatsby@2.20.19` and it worked :)

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by ZenTauro** [comment]
Thanks, however, I ran `rm -rf .cache package-lock.json` followed by `npm install` and then `npm start` and I still get the same error in the browser

**Comment by LekoArts** [comment]
You should delete both `.cache` and `public` if you clear out the cache (that's what `gatsby clean` is doing). That's the state I had after cloning your repository -- as I haven't run the build process yet. However, this shouldn't really be necessary as older projects can be upgraded and a new build would overwrite it.

Which browser are you using?

**Comment by ZenTauro** [comment]
I'm using Firefox 75.0 and Google Chrome 81.0
