### ISSUE TITLE
Gatsby-Image + CraftCMS

### ISSUE THREAD

**Issue by joebentaylor1995** [gatsbyjs/gatsby#23131]
Im currently working with CraftCMS. Im trying to get gatsby-image to work with craft, however im struggling, is there a way to do this that i'm not aware of?

**Comment by ascorbic** [comment]
Hi. If you're using gatsby-source-graphql, it doesn't by default download images, because it has no way of knowing which fields are images. You could try using a plugin such as [gatsby-plugin-remote-images](https://github.com/graysonhicks/gatsby-plugin-remote-images) to specify which fields hold images and to then download them to use with gatsby-image.

**Comment by ascorbic** [comment]
I'll close this but if you have any more questions then please reopen it or open a new one!

**Comment by jjrchrds** [comment]
Hey @ascorbic I can't seem to figure out how the hell to use gatsby-plugin-remote-images. Is there any better documentation on using this craft that you know of?
