### ISSUE TITLE
Graphql useStaticQuery returns different object in production

### ISSUE THREAD

**Issue by Funkh0user** [gatsbyjs/gatsby#23162]
## Description

Graphql useStaticQuery returns a different object when in production vs my development enviornment
heres a picture of useStaticQuery generating the correct results (in development 
<img width="1410" alt="Screen Shot 2020-04-15 at 6 17 40 PM" src="https://user-images.githubusercontent.com/52063586/79412231-cf013080-7f59-11ea-96ae-947619ef7eb1.png">
)

and heres a screenshot of the same query but in production.

<img width="1432" alt="Screen Shot 2020-04-15 at 6 17 07 PM" src="https://user-images.githubusercontent.com/52063586/79412265-e7714b00-7f59-11ea-80ff-83363aff3f9d.png">

### Steps to reproduce
clone repo: https://github.com/Funkh0user/Global-Paradise-Studios
npm install
npm start
click on an affiliate link in development mode and note the result in the console.
go to www.gps936.com
click an affiliate link
look in the console and note the different staticquery console.log result

### Expected result

the query should behave the same way in production as in development

### Actual result

the query in production mode generates a different result, thus breaking the site.

### Environment

  System:
    OS: macOS Mojave 10.14.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
    npm: 6.14.4 - ~/.nvm/versions/node/v12.13.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  Browsers:
    Chrome: 80.0.3987.163
    Firefox: 72.0.2
    Safari: 12.1
  npmPackages:
    gatsby: ^2.19.45 => 2.19.45 
    gatsby-image: ^2.2.44 => 2.2.44 
    gatsby-plugin-mailchimp: ^5.1.2 => 5.1.2 
    gatsby-plugin-manifest: ^2.3.3 => 2.3.3 
    gatsby-plugin-offline: ^3.0.41 => 3.0.41 
    gatsby-plugin-react-helmet: ^3.1.24 => 3.1.24 
    gatsby-plugin-sharp: ^2.5.3 => 2.5.3 
    gatsby-source-filesystem: ^2.1.56 => 2.1.56 
    gatsby-source-prismic-graphql: ^3.5.0 => 3.5.0 
    gatsby-source-wordpress: ^3.2.3 => 3.2.3 
    gatsby-transformer-remark: ^2.7.1 => 2.7.1 
    gatsby-transformer-sharp: ^2.4.3 => 2.4.3 
  npmGlobalPackages:
    gatsby-cli: 2.11.7

**Comment by freiksenet** [comment]
Hi!

Could you provide link to the repo that we can clone to produce a reproduction?

**Comment by Funkh0user** [comment]
yeah I'm an idiot, thought I had already :(. anyway, post updated with the whole repo. i'm working on creating a minimal reproduction repository (its a really small project though so maybe someone looks into it anyway, but i'm working on the minimal repo.....)

the whole repo is here, and its a small project right now. If it needs to be a

**Comment by Js-Brecht** [comment]
@Funkh0user I notice you're using the plugin `gatsby-source-prismic-graphql`.  That plugin uses [gatsby-source-graphql-universal](https://www.gatsbyjs.org/packages/gatsby-source-graphql-universal/) which swaps out Gatsby's `babel-plugin-remove-graphql-queries` with their own.  It's meant to leave the query in the source, so that it can be reused.  The idea is to have GraphQL queries that Gatsby can use during build-time, and be used to refresh data at run time.

I think that you might need to use their `withGraphql` or `getIsolatedQuery` function to get the data... ?  I can't say for sure.  I'm not a fan of that particular plugin, since it [exposes its options](https://github.com/birkir/gatsby-source-graphql-universal/blob/master/src/gatsby-ssr.js#L9) in the browser.  If somebody were using sensitive authentication tokens to access their API, they would be exposing them to the world and not even know it.

That said, I don't think `gatsby-source-prismic-graphql` has the same vulnerability, because it just appears to use the Webpack config from `gatsby-source-graphql-universal`, and a couple of its utilities.

**Comment by Js-Brecht** [comment]
Oh, correction.  `gatsby-source-prismic-graphql` also [exposes its options in the browser](https://github.com/birkir/gatsby-source-prismic-graphql/blob/08609fc3b066850ccd93a019e16114a27dd8d636/packages/gatsby-source-prismic-graphql/src/gatsby-ssr.tsx#L17).  Just something to keep in mind.  Maybe it's not an issue if nothing sensitive is being exposed.

**Comment by Js-Brecht** [comment]
One more thing: apparently, [useStaticQuery is not supported](https://github.com/birkir/gatsby-source-prismic-graphql/tree/20f26e39cb3f54425d291828eafb14ba7cb0fdd5#staticquery-and-usestaticquery).

**Comment by Funkh0user** [comment]
Thank you so much for helping me clarify that. I came up with a workaround to get the functionality I needed up and running, but now I understand why I needed to. 

its also very helpful to know about the security implications of this plugin. the client I'm building this page for isn't doing anything with sensitive information and probably won't but now I know If that changes, I need to be aware of this. You're a lifesaver!

i'm still not sure why my usestaticquery call would work in dev but not production, but for now, i'm closing this issue.
