### ISSUE TITLE
Can not be able to query data properly with nested reference field filtration

### ISSUE THREAD

**Issue by amaan-nadeem** [gatsbyjs/gatsby#23167]
## Description

When i'm trying to query the data from nested reference field while hitting the url of the page which is dynamically created through create pages it shows awkward behaviour. Sometime it query properly but sometime it doesn't work. 

`couponCards: allContentfulCouponCard(
      filter: { storeReference: { category: { eq: $categoryTitle } } }
    ) {
      edges {
        node {
          discount
          couponType
          discountDescription
          totalHits
          sitewide
          verified
          cardLogo {
            fluid(maxWidth: 400) {
              src
            }
          }
          details {
            details {
              details
              minimumOrder
              exclusion
            }
          }
          storeReference {
            slug
          }
          verified
          sitewide
          createdAt
          id
          expiryDate
        }
      }
    }`

this code sometime works but it sometime fails to deliver the right result even though i have the
same field for both category title and category in the store reference. 
### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

How to Make a Minimal Reproduction: https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/

### Expected result
expected result should be consistent not fluctuating when fields matches it should query the data
and give me the result.
What should happen?

### Actual result

What happened.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by freiksenet** [comment]
Hi @amaan-nadeem!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction
