### ISSUE TITLE
[gatsby-plugin-mdx] defaultLayouts not being applied

### ISSUE THREAD

**Issue by danieltott** [gatsbyjs/gatsby#23227]
## Description

I hope this is my doing something wrong but I really can't figure it out.

I'm trying to use [`defaultLayouts`](https://www.gatsbyjs.org/packages/gatsby-plugin-mdx/#default-layouts) for mdx and they're not being applied. Exporting a layout directly in the mdx file is working fine.

Here is the lines in `gatsby-config`:

https://github.com/danieltott/gatsby-mdx-blog-starter-project/blob/8fc2daf50493b7d5629253f4182d7d039332d261/gatsby-config.js#L44-L51

And here is the layout:

https://github.com/danieltott/gatsby-mdx-blog-starter-project/blob/8fc2daf50493b7d5629253f4182d7d039332d261/src/components/mdx-test-layout.js#L1-L5

I added a layout directly to one of the mdx files to confirm that part was working.

I added an example to [this repo](https://github.com/danieltott/gatsby-mdx-blog-starter-project), and it's on netlify. [This page](https://vigilant-booth-55dc85.netlify.app/graphql-book) has no layout set even though `defaultLayouts` is set. [This page](https://vigilant-booth-55dc85.netlify.app/mdx-example) is using the layout, but it's being imported/exported directly in the mdx file.

### Steps to reproduce

* `gatsby new gatsby-mdx-blog-starter-project git@github.com:danieltott/gatsby-mdx-blog-starter-project.git`
* `cd gatsby-mdx-blog-starter-project`
* `gatsby develop`
* Visit http://localhost:8000/graphql-book for _no_ layout, visit http://localhost:8000/mdx-example for _yes_ layout.

### Expected result

I would expect default layouts to be applied from mdx files.

### Actual result

Layouts are not being applied be default, only by manually exporting them directly from the mdx files.

### Environment

  System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.8.1 - ~/.nvm/versions/node/v12.8.1/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.10.2 - ~/.nvm/versions/node/v12.8.1/bin/npm
  Languages:
    Python: 2.7.13 - /usr/local/bin/python
  Browsers:
    Chrome: 81.0.4044.113
    Firefox: 74.0.1
    Safari: 13.1
  npmPackages:
    gatsby: ^2.16.1 => 2.16.1 
    gatsby-image: ^2.2.29 => 2.2.29 
    gatsby-plugin-manifest: ^2.2.23 => 2.2.23 
    gatsby-plugin-mdx: ^1.0.52 => 1.0.52 
    gatsby-plugin-offline: ^3.0.16 => 3.0.16 
    gatsby-plugin-react-helmet: ^3.1.13 => 3.1.13 
    gatsby-plugin-sharp: ^2.2.31 => 2.2.31 
    gatsby-plugin-styled-components: ^3.1.11 => 3.1.11 
    gatsby-remark-copy-linked-files: ^2.1.28 => 2.1.28 
    gatsby-remark-images: ^3.1.28 => 3.1.28 
    gatsby-remark-prismjs: ^3.3.20 => 3.3.20 
    gatsby-source-filesystem: ^2.1.33 => 2.1.33 
    gatsby-transformer-sharp: ^2.2.23 => 2.2.23

**Comment by Js-Brecht** [comment]
Hey @danieltott,

It looks like the issue is [here](https://github.com/danieltott/gatsby-mdx-blog-starter-project/blob/8fc2daf50493b7d5629253f4182d7d039332d261/gatsby-node.js#L51).  Default layouts only work if the page component has the extension `.mdx`.  Your page component is defined as `./src/templates/post.js`.

If you wish to use a template like that for your page component, then you could import your layout component into your template and use it there.

**Comment by danieltott** [comment]
I am (obviously) confused. The "page component" is not MDX by design, the _source_ is MDX. The page component looks like this:

```jsx
import React from 'react';
import { graphql } from 'gatsby';
import MDXRenderer from 'gatsby-plugin-mdx/mdx-renderer';

export default function Post({ data: { mdx } }) {
  console.log(mdx.body);
  return <MDXRenderer>{mdx.body}</MDXRenderer>;
}

export const pageQuery = graphql`
  query($id: String!) {
    mdx(fields: { id: { eq: $id } }) {
      body
    }
  }
`;
```

I don't think just converting this file to `.mdx` would even make sense, but even if I did, would the default layout apply to `page.mdx` and still not to the source `mdx` file?

The docs say:

> `default` applies to any MDX file that doesn’t already have a layout defined, even if it’s imported manually using import MDX from './thing.mdx.

Which makes me think that the default mdx layout really should be being applied if it's being created via `createPosts`. As I noted above, if the source mdx file `export default`s a layout, it _is_ being applied the way I expect, but never when set via `defaultLayouts`.

**Comment by Js-Brecht** [comment]
> I don't think just converting this file to `.mdx` would even make sense, but even if I did, would the default layout apply to `page.mdx` and still not to the source `mdx` file?

No no, you're right.  That wouldn't work.  What I was more referring to was this:

```js
    createPage({
      path: node.fields.slug,
//    component: path.resolve(`./src/templates/post.js`), // <--- This page component could be:
      component: node.fileAbsolutePath, // <-- have to include `fileAbsolutePath` in query, though
      context: {
        id: node.id,
        prev,
        next,
      },
    });
  });
```

If you pointed that to the `.mdx` files instead of the template, it would use the `defaultLayouts` option from `gatsby-plugin-mdx` to wrap the files.  There is code in `gatsby-plugin-mdx` that looks for the `.mdx` extension of that component property, and if it's there, it looks for a default export.  If it doesn't find a default export, it adds the one that you've defined in your `gatsby-config`.  `@mdx-js/mdx` uses that default export to wrap the rendered markdown content. _(The default layout receives all of the same props as the page, too, by the way)_

In that case, you wouldn't need to use your template component at all.  Gatsby would take care of rendering all of the content to React, and generating your page.

The one thing about doing it this way is that you won't have a centralized page query, like you do in your current template.  If you had to query the same kind of stuff for every page, you would then have to put the page queries in the `.mdx` files themselves.

> If you wish to use a template like that for your page component, then you could import your layout component into your template and use it there.

What I was referring to here is this:

```js
import React from 'react';
import { graphql } from 'gatsby';
import MDXRenderer from 'gatsby-plugin-mdx/mdx-renderer';
import Layout from '../components/mdx-test-layout'

export default function Post({ data: { mdx } }) {
  console.log(mdx.body);
  return (
    <Layout>
      <MDXRenderer>{mdx.body}</MDXRenderer>
    </Layout>
  );
}

export const pageQuery = graphql`
  query($id: String!) {
    mdx(fields: { id: { eq: $id } }) {
      body
    }
  }
`;
```

That approach is an issue because it makes it harder to define different layouts for different types of `Mdx` nodes, but it really shines if you have a lot of generic work that needs to be done in GraphQL, and would be extremely redundant to put in every `.mdx` file.  One way you could work around it not using different layouts for different blog posts is to define a different template in `createPosts` for different groups of blog posts.  How you group them is up to you.  You could even have the blog posts themselves define a template in their frontmatter, and use _that_ in your `createPosts()` function instead.

**Comment by danieltott** [comment]
OK so let me confirm my thinking: 

- The _only_ way that `defaultLayouts` is _ever_ used is if the mdx file itself is what gets passed directly to `component` in `createPage`. 
- However, if you `export default` a layout (in the mdx sense of the word) in an mdx file, it will get used everywhere regardless of how you create a page. (you can see this working in the starter I cloned for this issue [here on the blog list page](https://vigilant-booth-55dc85.netlify.app/blog/1) and [here on the blog post itself](https://vigilant-booth-55dc85.netlify.app/mdx-example))

Does that sound right? I'm happy to close this if there's no bug, I just want to make sure I am understanding correctly.

**Comment by Js-Brecht** [comment]
> * However, if you `export default` a layout (in the mdx sense of the word) in an mdx file, it will get used everywhere regardless of how you create a page. (you can see this working in the starter I cloned for this issue [here on the blog list page](https://vigilant-booth-55dc85.netlify.app/blog/1) and [here on the blog post itself](https://vigilant-booth-55dc85.netlify.app/mdx-example))

That's correct.  That's something that `@mdx-js/mdx` does.  All `gatsby-plugin-mdx` does with `defaultLayouts` is inject an `export default` into the rendered mdx code, so that it can be picked up by `@mdx-js/mdx` ([ref](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-mdx/loaders/mdx-loader.js#L141-L154)).  If you do it yourself, you're essentially doing the same thing.

**Comment by Js-Brecht** [comment]
You can look [here](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-mdx/gatsby/create-webpack-config.js#L70-L84) to see how `gatsby-plugin-mdx` uses that `mdx-loader` I linked to in my last comment.

**Comment by danieltott** [comment]
OK great, thank you so much for your time and help!
