### ISSUE TITLE
Error installing Gatsby

### ISSUE THREAD

**Issue by engrmartins** [gatsbyjs/gatsby#23268]
When I try to install Gatsby using the command below.
$ npm install -g gatsby-cli

I get this error. 

npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version
of core-js@3.
npm ERR! Unexpected end of JSON input while parsing near '...":"6.0.1","devDepende'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ehealth4everyone\AppData\Roaming\npm-cache\_logs\2020-04-19T07_54_00_688Z-debug.log

**Comment by Js-Brecht** [comment]
Can you show your `package.json`?

**Comment by LekoArts** [comment]
Hi, please follow our issue template and fill out these details:

---



## Description

Describe the issue that you're seeing.

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

How to Make a Minimal Reproduction: https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/

### Expected result

What should happen?

### Actual result

What happened.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by engrmartins** [comment]
Here is the package.json

{
  "name": "zipcode-pwa",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "@ionic/core": "^5.0.7",
    "@ionic/vue": "0.0.4",
    "core-js": "^3.6.4",
    "vue": "^2.6.11",
    "vue-router": "^3.1.6"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^4.3.0",
    "@vue/cli-plugin-eslint": "^4.3.0",
    "@vue/cli-plugin-router": "^4.3.0",
    "@vue/cli-service": "^4.3.0",
    "@vue/eslint-config-prettier": "^6.0.0",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-prettier": "^3.1.1",
    "eslint-plugin-vue": "^6.2.2",
    "prettier": "^1.19.1",
    "vue-template-compiler": "^2.6.11"
  }
}

**Comment by LekoArts** [comment]
As said above, please follow the template I've given you. Also, what is the complete error output when you run `npm install -g gatsby-cli` ?

**Comment by engrmartins** [comment]
**Expected result**
gatsby cli should be installed

**Actual result**
$ npm install -g gatsby-cli
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please,
upgrade your dependencies to the actual version of core-js@3.
npm ERR! Unexpected end of JSON input while parsing near '...":"6.0.1","devDepende'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ehealth4everyone\AppData\Roaming\npm-cache\_logs\2020-04-20T09_54_14_951Z-debug.log


**Environment**
Run gatsby info --clipboard in your project directory and paste the output here.
I cannot run  gatsby info --clipboard , because is not installed, so it is not a recognizable command

**Comment by LekoArts** [comment]
The `package.json` you showed is a Vue project so I don't think this is related to Gatsby.

If your only output is what you pasted in `Actual result` then I'm afraid we can't help further. As commented in https://github.com/gatsbyjs/gatsby/issues/23289#issuecomment-616442119 this is then an issue on your local environment. Please try the solutions suggested in:

- https://github.com/gatsbyjs/gatsby/issues/14074
- https://github.com/gatsbyjs/gatsby/issues/4967
- https://github.com/gatsbyjs/gatsby/issues/8138
- https://github.com/gatsbyjs/gatsby/issues/15276
- https://github.com/gatsbyjs/gatsby/issues/20502
- https://github.com/gatsbyjs/gatsby/issues/18327

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. This is a problem with npm and your local environment as it works for a lot of other people. I know, it might be frustrating, so please try the solutions above!

**Comment by AshadulMridha** [comment]
System:
    OS: Windows Server 2012 6.3.9600
    CPU: (4) x64 Intel(R) Core(TM) i7-2640M CPU @ 2.80GHz
  Binaries:
    Node: 14.2.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  npmGlobalPackages:
    gatsby-cli: 2.12.21
this massege of my but i cann't build new site properly please help anyone

**Comment by edenbotra** [comment]
someone know what should i do in this case? 
`C:\Users\Eran Botrashvili>npm install -g gatsby-cli@2.12.99
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
npm WARN deprecated axios@0.19.2: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
npm WARN deprecated highlight.js@8.9.1: Version no longer supported. Upgrade to @latest
npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.

added 701 packages, and audited 702 packages in 52s

153 packages are looking for funding
  run `npm fund` for details

18 vulnerabilities (2 low, 10 moderate, 6 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
`
