### ISSUE TITLE
Source code line highlighting using gatsby-remark-prismjs in gatsby-starter-blog-theme not working

### ISSUE THREAD

**Issue by ChristianIvicevic** [gatsbyjs/gatsby#23276]
I followed the [Using a Theme][1] tutorial over on Gatsby to get acquainted with it which worked without issues. Afterwards I wanted to adjust the syntax highlighting to allow highlighting of certain lines and found the [gatsby-remark-prismjs][2] plugin and followed the README but I cannot get it to work at all.

For instance having a code block in my content as follows:

    ```js{2}
    module.exports = {
      plugins: [
         "gatsby-theme-blog", // highlight-line
         "gatsby-theme-notes",
      ],
    }
    ```

doesn't highlight either the second or the third line. Analyzing the HTML output the annotation with the curly braces isn't properly picked up as the CSS class for the code block is set to `language-js{2} prism-code language-js{2} css-w0h414`. Even with the freshly checked out project after running `gatsby new my-blog https://github.com/gatsbyjs/gatsby-starter-blog-theme` the line commented using `highlight-line` wasn't highlighted.

I'd like to keep this starter template since it's fairly lightweight and even has the dark mode toggle which works nicely, yet I need to get the highlighting of particular lines and ranges enabled. What is necessary to enable that in the first place seing that me following the explanation in the plugin README does nothing?

  [1]: https://www.gatsbyjs.org/tutorial/using-a-theme/
  [2]: https://www.gatsbyjs.org/packages/gatsby-remark-prismjs/

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction
