### ISSUE TITLE
timestamp cache with GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES 

### ISSUE THREAD

**Issue by salientknight** [gatsbyjs/gatsby#23384]
Is it worth pursuing timestamp caching for data pulls if I am already using GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES ? 

If it is, how to I Store, Access and Stitch? Store the full data pull, accessed during a partial pull and stitch the two together? I have tried doing a partial pull and that results in a partial amount of pages being built, so I am left needing to know — how do I access the cached data? 

Thank you 

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by pieh** [comment]
Can you expand a little bit - are you talking about how to implement "delta sync" in custom source plugin?

If so - take a look how `gatsby-source-contentful` does it. What happens there is that first pull (no cache) will pull everything, plus so called "sync token", and the next pull will pull changes to content that happened since that particular "sync token".

What's happening there is that it "touches" nodes that are in the cache (from previous run) - to prevent them from being automatically garbage collected by Gatsby core. And then updates nodes, create new ones and delete ones that were deleted in the source

**Comment by salientknight** [comment]
First question. I am using GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES  Should I even bother pursuing https://www.gatsbyjs.org/docs/build-caching/ or is it redundant? 

Part two —  I have been all over gatsby-source-contentful. I am doing a fetch from json data that has about 40K nodes -- so there code doesn't play well with what I am doing — they seem to be requesting single files and  I cannot make 40K fetch requests on every clean build :)  I also wont know the nodes array until do I the fetch. 

I need a solution like the one described in your docs, where I save a timestamp and then add that timestamp to my API call — Do I then use touch as I parse through my createNode loop?

**Comment by unclecheese** [comment]
+1 for delta fetching. Although I don't know enough about the wordpress API to say how much work it would be to implement a "sync" token. I'm guessing it's nontrivial.
