### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by kalinchernev** [gatsbyjs/gatsby#2340]
I know it's not common to use an issue queue to say thanks, but here it is. I'm sure that a good word among a list of issues could be appreciated.

Although I don't have much time to do side projects, I did find some time to evaluate Gatsby for making one blog and a simple demo site. I really loved the concepts of the data layer and the plugin architecture. For a person who has missed all the gaps of webpack configuration depths, but still knowing the tricky parts of the MEAN stack, I really appreciate Gatsby so far.

So I decided to write an [article](https://kalinchernev.github.io/learn-gatsbyjs/) about it. It's a bit long, but I since I've spent the time, I had to make it more detailed. I will use it as a reference when suggesting Gatsby for future projects in my working place :)

Thank you again @KyleAMathews and all maintainers

**Comment by jeroenransijn** [comment]
Hi @kalinchernev, after seeing your post, I knew Gatsby issues would be one of the few repos out there with a comment like this. It's because Gatsby and Kyle are both really awesome, which is somewhat rare in Open Source.

That is why I also want to share my gratitude towards @KyleAMathews and all the maintainers. I have worked in person with @KyleAMathews on our company blog, and can say he is one of the fastest and most helpful developers I have worked with. The thing that really sets him apart is his focus and determination on open source and providing for the Gatsby community.

I have used Gatsby ever since I got my hands on it, and there have been some issues here and there with our requirements, and Kyle was always super responsive in helping out.

It feels like Gatsby gives me wings every time I use it!

🎉 Thanks Kyle and maintainers! 🎉

**Comment by Maxhodges** [comment]
just got a stackoverflow badge for creating the gatsby tag

![image](https://user-images.githubusercontent.com/957271/31268849-13ae4d08-aab9-11e7-933a-d65448619f8a.png)

**Comment by benjaminhoffman** [comment]
Thank you @kalinchernev @jeroenransijn & @Maxhodges for the kind words!  Glad to see your support and positive feedback.  Please continue to contribute and encourage others to do the same. :)

Closing this issue now as we're looking to get a handle of all our open issues.  Thanks again! 👍 😄 📉
