### ISSUE TITLE
Add publishedAt to Contentful nodes

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#2342]
@Khaledgarbaya re: https://stackoverflow.com/questions/46561916/how-to-retrieve-published-post-date-from-query-in-gatsby-with-contentful

Should we just add the `publishedAt` and `updatedAt` fields? Seems like an oversight on my part that they weren't added originally.

**Comment by Khaledgarbaya** [comment]
Hey @KyleAMathews, yeah sure I can do that.

**Comment by mannieschumpert** [comment]
Please do! I'm setting up a blog with Contentful, and this is pretty essential data.

**Comment by bradgarropy** [comment]
👍 Would really appreciate this!

**Comment by haxzie** [comment]
Yay! This would be really helpful. :+1:

**Comment by Khaledgarbaya** [comment]
This was added in https://github.com/gatsbyjs/gatsby/pull/2398 but forgot to close the issue, sorry.

**Comment by bradgarropy** [comment]
@Khaledgarbaya,
There may be a misunderstanding here. It  looks like #2398 does not add the `publishedAt` field. Instead, it adds the `createdAt` and `updatedAt` fields.

Looks like `publishedAt` is only returned with the [Content Management API][1], and not with the [Content Delivery API][2].

[1]: https://www.contentful.com/developers/docs/references/content-management-api/#/introduction/common-resource-attributes
[2]: https://www.contentful.com/developers/docs/references/content-delivery-api

**Comment by jorgemarrero** [comment]
Yes @Khaledgarbaya , `publishedAt` is not returned.

**Comment by jorgemarrero** [comment]
> What @bradgarropy said
> 
> > Looks like publishedAt is only returned with the Content Management API, and not with the Content Delivery API.
> 
> in delivery API the equivalent of `publishedAt` is `updatedAt`

@Khaledgarbaya, the problem comes when I have a **draft in contentful**, I am not able to know it in gatbsy since I receive both `createdAt` and `updatedAt` in published and drafts elements.

**Is there any way to know if an element is in published or draft?** I just want to show and generate pages of published elements

In addition, the elements in draft don't have all the required fields completed and a double-check in gatbsy would be required.

**Comment by Khaledgarbaya** [comment]
> Is there any way to know if an element is in published or draft? I just want to show and generate pages of published elements

The source plugin is using the delivery API so you will only get the published entries.

Can you explain more you use case because maybe I misunderstood something

**Comment by Khaledgarbaya** [comment]
Hey @jorgemarrero,

Unfortunately, the only solution for this is to use a `Date` field in your content model to act as the publisher at and you can change it however you want.

**Comment by rensio** [comment]
I have a related issue. If you update an old blog post e.g. because there is a typo and you want to correct it, it suddenly becomes the newest blog post with updatedAt. Whereas with createdAt it takes the day it was originally created as a draft. It would therefore be really helpful if the "firstPublishedAt" field would be available.
