### ISSUE TITLE
Old site served from cache despite new one being deployed

### ISSUE THREAD

**Issue by brtkdigital** [gatsbyjs/gatsby#23447]
## Relevant information

Last week I deployed a new version of my site to Netlify (https://kompilator.se) but visitors who've visited the old site are still getting the old site served from cache. This is just the vanilla gatsby-starter-blog template which I then restyled.

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by danabrit** [comment]
Hi @brtkdigital !

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by brtkdigital** [comment]
Hi @danabrit! 

Thanks for reaching out! I managed to find the culprit, which was a rogue service worker that refused to update. https://www.gatsbyjs.org/packages/gatsby-plugin-offline/ made short work of it :)

I'll close this if it's alright with you.
