### ISSUE TITLE
Use gastby-image to load an image within an SVG element?

### ISSUE THREAD

**Issue by braxex** [gatsbyjs/gatsby#23459]
## Summary
I'm working on a site which has a custom SVG animation on one page. The animation loads an image within the SVG using the `<image>` SVG element.  The rest of the site utilizes `gatsby-image` to process and load images. Ideally I'd like to leverage the amazing capabilities of `gatsby-image` to load the image within the SVG, but I haven't been able to work out how to do that yet. 

So what I'm wondering is: is it possible to use `gatsby-image` to load an image inside an SVG?

Here's some (obviously simplified) example code showing the past state of the animation SVG : 

```
import React from 'react';
import loadedPNG from '../../loadedPNG.png';

const Animation = () => {
  <svg>
    <g>
      <image 
        width="500"
        height="500"
        href={loadedPNG}
      />
    </g>
  </svg>
}
```

What I'd like to do:
```
import React from 'react';
import { useStaticQuery, graphql } from 'gatsby';
import Img from 'gatsby-image';

const Animation = () => {
  const images = useStaticQuery(graphql`
    query PublishPagesAnimationQuery {
      gatsbyLoadedPNG: file(
        relativePath: { eq: "assets/images/loadedPNG.png" }
      ) {
        childImageSharp {
          fluid(maxWidth: 1200) {
            ...GatsbyImageSharpFluid_noBase64
          }
        }
      }
    }
  `);
  return (
    <svg>
      <g>
        <Img 
          fluid={images.gatsbyLoadedPNG.childImageSharp.fluid}
          alt="gatsby loaded png alt text"
        />
      </g>
    </svg>)
  );
}
```

The [image SVG element documentation on MDN](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/image) notes that the only image formats supported are JPEG, PNG, and other SVG files. Could I somehow process the image using `gatsby-image` and access it as a JPEG or PNG within the `<svg>` element?

What do you think? Would something like this be possible?

## Disclaimers

I understand:
1. `gatsby-image` isn't a drop-in replacement for image tags
2. SVGs are not compatible for processing with `gatsby-image`

**Comment by LekoArts** [comment]
Thank you for opening this!

> So what I'm wondering is: is it possible to use gatsby-image to load an image inside an SVG?

No, this isn't possible. `gatsby-image` creates a bunch of div elements, a `<picture>` element and other stuff that isn't valid inside an SVG tag.

> The image SVG element documentation on MDN notes that the only image formats supported are JPEG, PNG, and other SVG files. Could I somehow process the image using gatsby-image and access it as a JPEG or PNG within the <svg> element?

Since you won't be able to replicate the `fluid` behavior you could make a `fixed` query with a defined width and height. The `src` you'll get back can be used inside the image tag.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by braxex** [comment]
Excellent answer. Thank you!
