### ISSUE TITLE
umlaut in siteurl crashes gatsby

### ISSUE THREAD

**Issue by ksjogo** [gatsbyjs/gatsby#23468]
## Description

Adding an umlaut within siteurl within sitemetadata within gatsby-config.js will crash gatsby with a not very helpful error message.

```
~/d/k/s/hoerte master↑2✚23… [1]
λ pnpm run build

> hoerte-site@1.0.0 build /Users/johannes/dev/ksjogo/sites/hoerte
> gatsby build


 ERROR

Reducers may not dispatch actions.



  Error: Reducers may not dispatch actions.

  - redux.js:214 dispatch
    [temp]/[4.0.5]/[redux]/lib/redux.js:214:13

  - index.js:64
    [temp]/[2.20.27_ae05c4833656f6138655498ac6132642]/[gatsby]/dist/redux/index.js:64:88

  - index.js:14 Object.dispatch
    [temp]/[2.3.0]/[redux-thunk]/lib/index.js:14:16

  - index.js:45 dispatch
    [temp]/[2.11.13_613cc7926f51925b306214bd5518e1b4]/[gatsby-cli]/lib/reporter/redux/index.js:45:9

  - redux.js:483 Object.createLog
    [temp]/[4.0.5]/[redux]/lib/redux.js:483:12

  - reporter.js:163 Reporter.log
    [temp]/[2.11.13_613cc7926f51925b306214bd5518e1b4]/[gatsby-cli]/lib/reporter/reporter.js:163:72

  - patch-console.js:18 Object.console.log
    [temp]/[2.11.13_613cc7926f51925b306214bd5518e1b4]/[gatsby-cli]/lib/reporter/patch-console.js:18:14

  - config.js:20 module.exports
    [temp]/[2.20.27_ae05c4833656f6138655498ac6132642]/[gatsby]/dist/redux/reducers/config.js:20:19

  - redux.js:465 combination
    [temp]/[4.0.5]/[redux]/lib/redux.js:465:29

  - redux.js:219 dispatch
    [temp]/[4.0.5]/[redux]/lib/redux.js:219:22

  - index.js:64
    [temp]/[2.20.27_ae05c4833656f6138655498ac6132642]/[gatsby]/dist/redux/index.js:64:88

  - index.js:14 Object.dispatch
    [temp]/[2.3.0]/[redux-thunk]/lib/index.js:14:16

  - index.js:170 module.exports
    [temp]/[2.20.27_ae05c4833656f6138655498ac6132642]/[gatsby]/dist/bootstrap/index.js:170:9

  - build.js:88 async build
    [temp]/[2.20.27_ae05c4833656f6138655498ac6132642]/[gatsby]/dist/commands/build.js:88:7


not finished open and validate gatsby-configs - 0.079s
 ERROR  Command failed with exit code 1.
~/d/k/s/hoerte master↑2✚23… [1]
``

**Comment by DSchau** [comment]
Here's a [reproduction](https://github.com/DSchau/umlaut-issue-23468).

Are umlauts and these types of special characters even possible in the URL specification? Did some preliminary digging here -- but surfaced [this StackOverflow article](https://stackoverflow.com/a/2744184) which may be illustrative.

In any scenario -- this does seem like a bug that should be fixed, but given the above, it may be better to surface an error message (?) alerting the user while also fixing the bug.

@ksjogo what are your thoughts? What's the exact URL that you'd want to express here?

**Comment by pieh** [comment]
Few notes from some discovery:
The unhelpful message for sure need fixing. It also seem to be same issue as one reported in https://github.com/gatsbyjs/gatsby/issues/22812

The actual (now hidden) error looks a bit like this (it seems to depend if you use global `gatsby-cli` or use npm/yarn script:
```
➜  i23468 git:(master) gatsby build                   
The site's gatsby-config.js failed validation
ValidationError: child "siteMetadata" fails because [child "siteUrl" fails because ["siteUrl" must be a valid uri]]
⠋ open and validate gatsby-configs
 ERROR 
The site's gatsby-config.js failed validation
  Error: The site's gatsby-config.js failed validation
  - config.js:27 module.exports
    [pr23468]/[gatsby]/dist/redux/reducers/config.js:27:17
  - redux.js:465 combination
    [pr23468]/[redux]/lib/redux.js:465:29
  - redux.js:219 dispatch
    [pr23468]/[redux]/lib/redux.js:219:22
  - index.js:64 action
    [pr23468]/[gatsby]/dist/redux/index.js:64:88
  - index.js:14 Object.dispatch
    [pr23468]/[redux-thunk]/lib/index.js:14:16
  - index.js:170 module.exports
    [pr23468]/[gatsby]/dist/bootstrap/index.js:170:9
not finished open and validate gatsby-configs - 0.144s
```

@madalynrose tracked this to issue to this report in `@hapi/joi` (which we use to do some validation) - https://github.com/hapijs/joi/issues/1298

Because of above issue that was closed due to inactivity (after surfacing some difficulties with doing it), only way for us to fix this in gatsby would be to either remove validation completely or  do some massaging on the value to remove or replace characters like "umlaut" so it passes validation (just for validation, we should not make actual changes to this value), but this seems dangerous and I would love to hear some if anyone have other alternative ideas for handling it

**Comment by ksjogo** [comment]
Hey everyone, I am not sure about which specification it would adhere to or which not, but the domain name I registered is "hörte.de" and includes the umlaut in its official registration name.
I am not sure if/how browsers transform this to something else when trying to access the webserver, but I can just type that into my address bar and I will get to my hosted website.
It doesn't seem to work with curl though for some reason.
Replacing the umlaut version with `siteUrl: 'http://xn--hrte-5qa.de',` works on gatsby level (and in the browser) (and curl can access that url directly.

These replacements seem save on URL level, maybe that is one avenue?

**Comment by pieh** [comment]
The converted URL that you shared uses [Punycode](https://en.wikipedia.org/wiki/Punycode). Support for both Punycode and unicoded urls seems to vary between clients (browsers / curl / postman / etc). There is not a great deal of resources around that on the internet given how domain names using just ASCII characters dominant are.

We could potentially add Punycode encoding (using https://www.npmjs.com/package/punycode ) before passing it to validation ... but I must say we are really not experts in this area and I wonder if we can potentially cause more harm than good trying to support things we know little about. Also Punycode seems limited to domain names only and because users can define `siteUrl` as `https://domain.name/some/sub/resource` - we would only want to apply this selectively to domain part of url.

I do wonder if better avenue to instead of trying to do this automatically - on `siteUrl` validation error mentioning case of non-ASCII and to consider passing punycoded version there (for example using https://www.punycoder.com/ ). But this might have not great effect on how some plugins make use of `siteUrl`. It just seems like there is no good option here.

In general the punycoded urls don't look as neat as unicode ones. They also are less memorable. There might be "marketing damage" caused by trying to force usage of those (depending on how the `siteUrl` is used)
