### ISSUE TITLE
Accessing frontmatter in a mdx post in gatsby-theme-blog fails (?)

### ISSUE THREAD

**Issue by kuworking** [gatsbyjs/gatsby#23490]
Trying to see how to access to `frontmatter` within the same `mdx` post, it should work out-of-the-box as said in the docs https://www.gatsbyjs.org/docs/mdx/writing-pages/

But if tried in gatsby-theme-blog https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-theme-blog it doesn't work

1. `gatsby new my-themed-blog https://github.com/gatsbyjs/gatsby-starter-blog-theme`
2. add `<h1>{props.pageContext.frontmatter.title}</h1>` to `hello-world.mdx`
3. `gatsby develop` -> visit the post -> `TypeError: Cannot read property 'frontmatter' of undefined`

Related: I'm facing the same in my blog, wondering if something has to be added when using MDXProvider and MDXRenderer to make this work, or in `gatsby-node`, as I'm using the structure shown in this repo

** this is not a bug, but how can I change the label?

**Comment by lannonbr** [comment]
I was able to confirm this.

Looking in `gatsby-plugin-mdx` there's a call for [onCreatePage](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-mdx/gatsby/on-create-page.js) which adds in the frontmatter as commented in the docs, but it's not working here.

**Comment by laurieontech** [comment]
Thanks for opening the issue! In this case, the docs are a bit misleading. Going to tag @gatsbyjs/learning to see if they have ideas on how to clarify.

The example that you're referencing, is meant to be for mdx pages inside `src/pages` where `pageContext` is available. In the case of your blog post, this same information can be accessed via `_frontmatter`. So instead of `<h1>{props.pageContext.frontmatter.title}</h1>` you want `<h1>{_frontmatter.title}</h1>`.

Seeing as `_frontmatter` is available in both cases, that's likely what the docs should reference.

**Comment by kuworking** [comment]
@laurieontech thanks for the clarification 👏👏
