### ISSUE TITLE
Import Shopify product

### ISSUE THREAD

**Issue by iKeeko** [gatsbyjs/gatsby#23509]
Products not being pulled from imported products by Shopify [Import Store app](https://help.shopify.com/en/manual/migrating-to-shopify/import-store-app/woocommerce-migration)

### Expected result
All products were successfully imported on Shopify dashboard and expected to be pulled and use by using gatsby-source-shopify

### Actual result
Only the products I added manually is being pulled, The imported products are not on graphql query at all

**Comment by LekoArts** [comment]
Thank you for opening this!

Please reach out to Shopify's support so that they can make sure that your store has the products in their correct state. The source plugin only accesses the Storefront API. They can give you some more information why it might not appear in the Storefront API.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
