### ISSUE TITLE
Urlencoded slashes in paths break custom 404 pages.

### ISSUE THREAD

**Issue by monachilada** [gatsbyjs/gatsby#23580]
## Description

`loader.isPageNotFound()` reports false positive if `page` variable is undefined in the return statement.

This appears to be caused by a path name containing url encoded slashes and perhaps other characters that somehow tricks the function into returning true when it should not.

This results in a flashing 404 page before throwing an error for unknown paths containing urlencoded slashes.

### Steps to reproduce

Compare URLs from my [starter repo](https://github.com/monachilada/gatsby-starter-hello-world) with a basic custom 404 page added.

### Expected result

Site should display it's custom 404 page, which should look like this: https://serene-joliot-c89197.netlify.app/some/path

### Actual result

When attempting a link with urlencoded slashes such as: https://serene-joliot-c89197.netlify.app/some%2Fpath

The behavior I see is that the 404 page is shown momentarily and then goes to a blank screen. In the console, I can see an error being thrown, which appears to be traceable to `cache-dir/loader.js` and specifically the `isPageNotFound` function returning a false negative.

### Environment

System:
    OS: macOS 10.15.3
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 81.0.4044.122
    Firefox: 75.0
    Safari: 13.0.5

**Comment by vladar** [comment]
Thank you for opening this, @monachilada 

I see this bug but not sure if it is related to `loader.isPageNotFound`. Still a good place to start. Thanks! Are you interested to prepare a PR with a fix?

**Comment by monachilada** [comment]
Would like to keep this open. I haven't had a chance to create a PR for this. I would be happy if someone else would.

**Comment by Pyrax** [comment]
What I have found out, so far:

If you have a page like http://localhost:9000/foo/bar and call it with http://localhost:9000/foo%2Fbar, it rewrites location to the former variant because `window.pagePath != window.location.pathname`. For 404 pages this behavior is disabled (see: [production-app.js](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/cache-dir/production-app.js#L104)).

Assuming, we are trying to call a non-existant page http://localhost:9000/foo/bar%2Fabc. On initial page load, `loader.loadPage(rawPath)` gets executed with rawPath being window.location.pathname which is "/foo%2Fbar/eqweqwe" in this case. This is fine as `trimPathname(rawPathname)` in find-path.js decodes this URI. 
Now, when react-dom is ready, `loader.loadPageSync(rawPath)` is called with http://localhost:9000/foo/bar%252Fabc as rawPath which comes from router location. So, location has been encoded for some reason. This behavior might come from reach/router because I haven't seen any modification of the location in other places.

One simple solution could be to decode the URI twice in `trimPathname`. Any other suggestions?
