### ISSUE TITLE
how use useQueryParam wihout reload page?

### ISSUE THREAD

**Issue by e-purik** [gatsbyjs/gatsby#23601]
hi all
Guys who worked with useQueryParam why  when trying to change the URL does reload the page and how not to reload the page when using useQueryParam?

**Comment by vladar** [comment]
Hi @e-purik 

I think this is some mistake because Gatsby doesn't have `useQueryParam` in the codebase. In fact, this issue is the only place mentioning `useQueryParam`: https://github.com/gatsbyjs/gatsby/search?q=useQueryParam&unscoped_q=useQueryParam

So I am going to close this. But if you want to continue - please create a new issue. Also, we have guidelines on [how to file an issue](https://www.gatsbyjs.org/contributing/how-to-file-an-issue/) as well as an issue template. Please use those to describe your problem in detail so that we were able to help.

Thanks for using Gatsby :muscle:
