### ISSUE TITLE
[gatsby-plugin-canonical-urls] `pathname` is undefined in development

### ISSUE THREAD

**Issue by dlindahl** [gatsbyjs/gatsby#2362]
During development, `gatsby-ssr` does not get a `pathname` argument to `onRenderBody`. Therefore, the canonical URL [it generates](https://github.com/gatsbyjs/gatsby/blob/524ff171cd890b79ce9535d6dc10550c70365d33/packages/gatsby-plugin-canonical-urls/src/gatsby-ssr.js#L4) is `<link rel="canonical" href="http://example.comundefined">`

While this doesn't necessarily hurt anything since it is in development, it looks like a bug. If adding the actual `pathname` is out of scope for `gatsby-ssr`, then maybe using an empty string is or some other "this doesn't work in DEV"-type string preferable to `undefined`.

Additionally, in production, when navigating from one page to another, the canonical URL meta tag does not update. Not sure if that is important enough to fix, but it was unexpected behavior that I thought warranted a report.

**Comment by KyleAMathews** [comment]
Thanks for the detailed bug report!

Definitely agree this should work in development and you've correctly identified the problem that a pathname isn't being passed in. Would you like to PR a fix for that? It should just be `/` since we only SSR a blank page for development.

On the meta tag not updating, this plugin just adds the meta tag to the SSRed HTML so won't updated in the client. My understanding is that's fine for SEO. If not, that's a serious problem that might make this plugin unusable. In which case we'd deprecate it for gatsby-plugin-react-helmet which does update in the client.

**Comment by dlindahl** [comment]
I could PR but I'm not sure I know enough about the various page building APIs yet. So far, I Have Opinions :tm:, but I'd like to gain more experience before expressing them :D

I worked around this by pulling in `pageResources: { page: { path } }` from my entry component props since that has, AFAIK, the best representation of the current path. Plus, it changes accurately when navigating to soothe my code OCD.

**Comment by dlindahl** [comment]
Bare minimum PR added at #2363
