### ISSUE TITLE
data hot reloading breaks when using `gatsby-plugin-transition-link`

### ISSUE THREAD

**Issue by piotrf** [gatsbyjs/gatsby#23622]
## Description

Hi, I’m having issues with page templates not hot reloading. I have them wrapped with a layout component in *gatsby-browser.js*. The layout component updates just fine, but pages don’t. I tried wrapping my template files with `React.memo`—didn’t work.

### Steps to reproduce

Here’s the repo I’m working on: https://github.com/storycopter/storycopter-idoc

1. run the site with `gatsby develop`
2. open localhost:8000
3. edit `src/essentials/home.json`
4. save changes

### Expected result

Page should hot load on file save and new data should surface in the UI.

### Actual result

Layout component `console.log` returns updated data, Pages do not.

### Environment

```
System:
    OS: macOS 10.15.4
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.11.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.7 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 81.0.4044.129
    Firefox: 75.0
    Safari: 13.1
  npmPackages:
    gatsby: 2.21.5 => 2.21.5
    gatsby-cli: 2.12.5 => 2.12.5
    gatsby-image: 2.4.0 => 2.4.0
    gatsby-link: 2.4.0 => 2.4.0
    gatsby-plugin-material-ui: 2.1.8 => 2.1.8
    gatsby-plugin-react-helmet: 3.3.0 => 3.3.0
    gatsby-plugin-sharp: 2.6.0 => 2.6.0
    gatsby-plugin-styled-components: 3.3.0 => 3.3.0
    gatsby-plugin-transition-link: 1.18.0 => 1.18.0
    gatsby-react-router-scroll: 2.3.0 => 2.3.0
    gatsby-source-filesystem: 2.3.0 => 2.3.0
    gatsby-transformer-json: 2.4.0 => 2.4.0
    gatsby-transformer-sharp: 2.5.0 => 2.5.0
  npmGlobalPackages:
    gatsby-cli: 2.11.15
```

**Comment by pieh** [comment]
I was testing this out and it doesn't really seem related to `wrapPageElement` - after removing gatsby-ssr and gatsby-browser compeletely it still doesn't hot reload data.

What seemed to actually help is commenting out `gatsby-plugin-transition-link` (+ adjusting `gatsby-plugin-transition-link/AniLink` imports/usage, because those seem to crash application when plugin is not used).

**Comment by pieh** [comment]
I found https://github.com/TylerBarnes/gatsby-plugin-transition-link/issues/131 which seems like it might be same case as here.

I think the reason why Layout (added with `wrapPageElement`) have data hot reloading still working is because it ends up above wrappers that `gatsby-plugin-transition-link` add in component tree.

**Comment by piotrf** [comment]
This is helpful info @pieh, I can work with that. Much appreciated.

**Comment by danabrit** [comment]
Closing, as this issue appears resolved. Please reopen with current status information if that is not the case.
