### ISSUE TITLE
Should node id's be unique and meaningless?

### ISSUE THREAD

**Issue by ediblecode** [gatsbyjs/gatsby#23638]
#  Summary

I'm writing a source plugin where I download JSON from an API and create nodes - all pretty standard. Objects I receive have an a field called `topicId` with is a guid (uuid) that represents the main id of the item.

Now I *could* use this field directly as the node id in Gatsby like this:

```js
createNode({
  id: item.topicId
})
```

However, the `createNodeId` function exists (to create guid ids) so it seems like I should use it, and store the `topicid` as its own field, like this:

```js
const { topicId } = item;
createNode({
  id: createNodeId(topicId),
  topicId
})
```

So the question is, **should id's be unique and meaningless?** And therefore which approach above is favourable?

One of the benefits of `createNodeId` is that it _'will generate different IDs for different plugins if they use same input'_. In my particular case, this is irrelevant because I've already got a guid, so I could probably safely just use it directly.

## Relevant information

[This comment](https://github.com/gatsbyjs/gatsby/issues/1853#issue-251309225) suggests that node ids _should_ be unique and meaningless, so people don't rely on them for anything, which makes sense.

However, I couldn't find anything about this in the docs either in [node creation](https://www.gatsbyjs.org/docs/node-creation/) or [createNodeId](https://www.gatsbyjs.org/docs/node-api-helpers/#createNodeId). In fact, several of the examples in the docs actually _don't_ use `createNodeId` and use predictable ids directly.

I'd be happy to contribute to the docs if anyone thinks this needs adding/clarifying.

### Environment (if relevant)

N/A

### File contents (if changed)

`gatsby-config.js`: N/A
`package.json`: N/A
`gatsby-node.js`: N/A
`gatsby-browser.js`: N/A
`gatsby-ssr.js`: N/A

**Comment by pieh** [comment]
`id`s should be unique - we have dictionary of nodes by `id` so if two nodes share same `id` - then it would just mean that one overwrites the other. Note that the this is in global scope, so even if nodes have different types - they still can't use same `id`

https://github.com/gatsbyjs/gatsby/issues/22004 is example of issues when `id`s are not unique (in this case those have different types but same `id`).

The "meaningless" part is somewhat related to uniqueness - it's not strict requirement, but it is good practice - when users would want to query by `id` (and not by something like `topicId`) it just increases chance of colissions, because you need to factor in that nodes that you create in your plugin or site are just parts of all the nodes that exist in data layer - other plugins share the same `id` pool. So best way to go about it is to make `id` meaningless (so users don't use this) and have meaningful identifiers as some other field (`topicId`).

> several of the examples in the docs actually don't use createNodeId and use predictable ids directly.

It does sound like the documentation adjustments is good idea, but there is always nuance. Sometimes we don't want to go on tangential problem when explaining some particular concept. So we might need to evaluate this for each documentation page separately - do you have examples in mind?

**Comment by ediblecode** [comment]
Thanks for clarifying. I'll def use the second option and store `topicId` separately to `id` and use `createNodeId`.

I see what you mean about the nuance. Don't want to overwhelm someone!

I was thinking mostly about the [Node creation page](https://www.gatsbyjs.org/docs/node-creation/) and specifically the [Node relationship storage model section](https://www.gatsbyjs.org/docs/node-creation/#node-relationship-storage-model). It explains the flat dictionary you referenced above and the implications, and does make a reference to child field inference.

I wonder if this is a good place to explain about unique/meaningless ids?

Or possibly a new section alongside Parent/Child/Refs, Fresh/stale nodes, Changing a node's fields and Node Tracking - it definitely fits on that page as one of the fairly important things to know.

**Comment by marcysutton** [comment]
Hey @ediblecode, thanks for opening the issue! And thanks to @pieh for the initial triage. I think a new section on the Node Creation page about handling IDs would be awesome. If you're up for contributing it, I'd say go for it!

**Comment by ediblecode** [comment]
Not stale, still going to submit a PR for the updated docs just haven't got round to it, sorry
