### ISSUE TITLE
[gatsby-plugin-manifest] Different icon source for smaller sizes

### ISSUE THREAD

**Issue by derykmarl** [gatsbyjs/gatsby#23730]
I'm new to Gatsby and its plugins so apologies if asking something stupid.  Had a good dig through existing issues too.

I have a logo that looks good at about 96x96 upwards (company logo incorporating full name) but once you go down to smaller sizes used for browser favicons etc it isn't very readable so I use a different logo that is just the first letter of the company logo instead.

Would a second, alternative icon source be possible for generating the smaller sizes?  It seems at the moment you either have the full automation, or hybrid mode that just lets you decide what sizes and filenames to output but you still use the same source icon, or override the whole thing with full manual mode (and disable favicon and do it through helmet).  Ideally it'd be automatic but along the lines of "if size <= 72x72 then icon: src/images/icon-small.png else icon: src/images/icon.png"

Right now I'm overriding it by providing my own favicon-32x32.png, icons/icon-48x48.png and icons/icon-72x72.png in the static directory.  But I'm not sure how robust that is.  Right now the build command appears to be doing gatsby-plugin-manifest first and then copying the contents of /static to /public and overwriting the smaller generated icons (leaving the larger generated icons in place), so my workaround works - but if the build order changes then the workaround could break.

**Comment by LekoArts** [comment]
Thank you for opening this!

Using the [manual configuration](https://www.gatsbyjs.org/packages/gatsby-plugin-manifest/#manual-mode-configuration) is perfectly fine and is the thing you'll need to do. So that's the route you should take :)

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by derykmarl** [comment]
Thanks for the friendly response!  What I had in mind was something in-between (more or less how I thought hybrid would have worked) where you specify some manually as an override but have it auto-resize the rest, OR better still have it auto-resize from 2 different source images depending on the target size.

Still, I could just use manual mode and copy what it's generated into static, just thought it might not be _too_ unusual a requirement for designers to have a simplified icon at smaller sizes, and maybe helpful for other new users
