### ISSUE TITLE
Transform node fields with gatsby-source-graphql

### ISSUE THREAD

**Issue by crgeary** [gatsbyjs/gatsby#23799]
I have a number of fields that contain absolute URLs to content with my CMS. Let's say hypothetically my CMS lives at https://cms.example.com and my website is at https://example.com. All of the content that comes from the CMS over GraphQL has cms.example.com as part of the absolute URL, but this is incorrect once it ends up within Gatsby.

I've seen that other plugins have ways to modify data, the Remark plugin has "plugins", and the WordPress plugin has "normalisers". Each let you "hook in" and make changes to the data before it's stored. Is that possible with the GraphQL plugin?

Is there any way to search & replace links in the content with Gatsby (without doing it inside React components). Essentially, I need to do exactly what the `searchAndReplaceContentUrls` fields option from the `gatsby-source-wordpress` plugin, but for GraphQL.

To clarify, I want to edit the current node fields, not create new ones.

Also posted here: https://hashnode.com/post/transform-content-with-gatsby-source-graphql-ck9u8aj4503wx6es17hqmko37

**Comment by mmende** [comment]
I have the same problem especially for fields containing markdown with embeded images. For now I use a [modified](https://github.com/mmende/gatsby-plugin-graphql-image) version of `gatsby-plugin-graphql-image` to create local file nodes for all uploaded files. To fix the markdown links I then use a regex to replace all occurrences of cms paths for the field containing markdown like so:

```js
// gatsby-node.js
const escapeRegexp = require('lodash.escaperegexp')

exports.createResolvers = ({ createResolvers }) => {
  const baseUrl = 'https://cms.example.com'
  // Matches file url's starting with baseUrl inside markdown image tags like ![Some image](https://cms.example.com/file.png)
  const re = new RegExp(`${escapeRegexp(baseUrl)}[^ )]+`, 'g')

  const resolvers = {
    CMS_ComponentContentParagraph: {
      markdown: {
        type: 'String!',
        resolve: (source, args, context) => {
          const fileNodes = context.nodeModel.getAllNodes({ type: 'File' })
          return source.Content.replace(re, url => {
            const fileName = url.replace(/.*\//, '') // => file.png
            const staticFile = fileNodes.find(({ base }) => base === fileName)
            if (staticFile) {
              const { internal, name, ext } = staticFile
              return `/static/${name}-${internal.contentDigest}${ext}`
            }
            console.warn(`Could not find static file for`, url)
            return url
          })
        },
      },
    },
  }
  createResolvers(resolvers)
}
```

This adds the field `markdown` to the graphql type `CMS_ComponentContentParagraph` where the unmodified markdown is in the field `Content`.

The problem with this approach is that I need to add this resolver to each graphql type containing a markdown field manually. Furthermore I need to add the original field to the query otherwise `source.Content` is undefined.

**Comment by mmende** [comment]
I've created a gatsby plugin [gatsby-plugin-source-graphql-files](https://github.com/mmende/gatsby-plugin-source-graphql-files) for that purpose now. It's a bit hacky here and there but it seems to work pretty well for my use case.

**Comment by ashleynexvelsolutions** [comment]
@crgeary Did you happen to find a solution for this? I'm in the exact same boat.

**Comment by crgeary** [comment]
@ashleynexvelsolutions if I'm honest, I haven't looked further into it. It's not high on my priorities as this was actually for a friends personal project that he was stuck with. He's just search/replacing the content within the React components for the time being. Not ideal, but it works.

I don't know for sure, but I assume this isn't possible without modifications to the source plugin, or to Gatsby itself. I'd like to see this in Gatsby core, so it's available to all source plugins, but Immutable fields seems like an intentional design decision, in order to increase compatibility between plugins.

So, sorry no solution from me.

**Comment by Jaikant** [comment]
@ashleynexvelsolutions  Here's an example, if I recall it is in the docs. To convert markdown to html and download images using the gatsby-source-graphql plugin. It doesn't really transform a node, but creates a new field with the information we need. In the example below bodyHtml will contain the html (body has the markdown)

```
const { createRemoteFileNode } = require(`gatsby-source-filesystem`)
const remark = require(`remark`);
const html = require(`remark-html`);

exports.createResolvers = ({
  actions,
  cache,
  createNodeId,
  createResolvers,
  store,
  reporter,
}) => {
  const { createNode } = actions
  createResolvers({
    GraphStrapi_UploadFile: {
      imageFile: {
        type: `File`,
        resolve(source, args, context, info) {
          return createRemoteFileNode({
            url: `http://localhost:xyz${source.url}`,
            store,
            cache,
            createNode,
            createNodeId,
            reporter,
          })
        },
      },
    },
    GraphStrapi_Article: {
      bodyHtml: {
        type: `String`,
        resolve(source, args, context, info) {
          return remark().use(html).processSync(source.body).contents
        },
      },
    },
  })
}
```

Anyone knows, why the `filter` option is not available on the query data, with this plugin?

**Comment by LekoArts** [comment]
Thank you for opening this!

`gatsby-source-graphql` only does schema stitching, it doesn't create actual nodes. As noted in the first paragraph:

> Plugin for connecting arbitrary GraphQL APIs to Gatsby’s GraphQL. Remote schemas are stitched together by declaring an arbitrary type name that wraps the remote schema Query type (typeName below), and putting the remote schema under a field of the Gatsby GraphQL query (fieldName below).

Hence you can't really modify those entries beyond the `createResolvers` lifecycle (and not having "filter" available would also be expected behavior).

For the features you're asking for you'll need to create a source plugin that downloads the actual data from your API and creates its nodes. In case of e.g. Strapi they afaik are working on a dedicated source plugin. Those are (at the moment) the better way than the generic `gatsby-source-graphql` one.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
