### ISSUE TITLE
Page layout messed up on refresh or direct link

### ISSUE THREAD

**Issue by faiwiz** [gatsbyjs/gatsby#23850]
Page layout showing perfect when navigating from internal link and page messed  up on refresh or direct link.
On refresh first it load index page elements then render the required page.

**Comment by ascorbic** [comment]
Hi! Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by danabrit** [comment]
Closing due to no reproduction.

**Comment by joseph4tw** [comment]
Hello, I actually ran into the same issue and I was finally able to identify what was happening (although I don't know why it's happening).

Following the [minimal reproduction](https://gatsby.dev/reproduction) steps, I have 2 pages: index.js and page2.js:

*index.js*
```js
import React from "react"
import { Link } from "gatsby"

export default function Home() {
  return (
    <div>
      <h1>Home</h1>
      <Link key="page2" to="/page2/">Go to Page 2</Link>
      <p dangerouslySetInnerHTML={{ __html: '<main><em>p:main:em:blah</em></main>' }}></p>
      <p dangerouslySetInnerHTML={{ __html: '<div><em>p:div:em:blah</em></div>' }}></p>
      <div dangerouslySetInnerHTML={{ __html: '<main><em>div:main:em:blah</em></main>' }} />
    </div>
  )
}
```

*page2.js*
```js
import React from "react"
import { Link } from "gatsby"

export default function Home() {
  return (
    <div>
      <h1>Page 2</h1>
      <Link key="home" to="/">Go to Home</Link>
      <p dangerouslySetInnerHTML={{ __html: '<main><em>p:main:em:blah</em></main>' }}></p>
      <p dangerouslySetInnerHTML={{ __html: '<div><em>p:div:em:blah</em></div>' }}></p>
      <div dangerouslySetInnerHTML={{ __html: '<main><em>div:main:em:blah</em></main>' }} />
    </div>
  )
}
```

If you run `gatsby develop`, everything looks fine. You can refresh the pages and the elements render like you would expect them to.

However, if you run `gatsby build && gatsby serve` something very weird happens.

If you follow the links to the different pages, the elements show up fine, but if you refresh the page through the browser (either on index or page2) the first two `<p>` tags briefly show their innerHTML and then the inner elements are quickly removed. The `<div>` tag ends up rendering, but it renders the innerHTML of the second `<p>` tag's innerHTML.

For me, I was able to resolve this bug by just using the `<div>` tag instead of the `<p>` tag when using `dangerouslySetInnerHTML` (and honestly I don't know why I used the `<p>` tag in the first place). If you're wondering why I was using `dangerouslySetInnerHTML` at all, it was because I was rendering the html transformed from markdown pages. I just used this minimal example to demonstrate the issue.

I can't tell if this is a react bug or something else, but I just wanted to at least highlight what was happening for me and maybe this will help someone else in the future.

**Comment by r9software** [comment]
Hi @danabrit  or @ascorbic We also have the very same issue in a big project using Gatsby, could it be that the @joseph4tw comment could help fix our issue?
