### ISSUE TITLE
gatsby createPages

### ISSUE THREAD

**Issue by ciprian97** [gatsbyjs/gatsby#23866]
## Summary
Hello, I have a question about gatsby createPages. I'm working for a project that creates products. With createPages API, I created a pages based on the id
for each product with information. But if a new user create a product, he can't acces the product page beacause he get 404.
From what I read the solution is to rebuild the project. Do you know another workaround for this situation?
## Relevant information
Here is a part of my code:
After the user create another product I will have the { id: '4' } but when I acces /products/4 I get 404.
```
result.data.idProduct.findAllProducts.edges.forEach(edge => {
          console.log('edge', edge.node) -> edge { id: '1' } edge { id: '2' } edge { id: '3' }
          createPage({
            path: `/product/${edge.node.id}/`,
            component: productPageTemplateFinal,
            context: {
              id: edge.node.id,
            },
          })
        })
```

**Comment by ascorbic** [comment]
Hi,
You are correct that in order to see the new page, the site will need to be rebuilt. This doesn't necessarily mean that the whole site will need rebuilding, because a lot of the data is cached, but there does need to be a build step. What is the source of the data? The build step is usually triggered by data provider (such as a CMS) calling a webhook to rebuild the site. If you give me a bit more detail I should be able to give more specific advice.

**Comment by ciprian97** [comment]
Hi @ascorbic, thanks for the reply, I'm not using a CMS, I'm using a spring boot backend.

**Comment by ciprian97** [comment]
@ascorbic do you need more details and if so, like what?

**Comment by ascorbic** [comment]
What are you using to build and deploy your site? Gatsby Cloud? Netlify? What you need is for your spring boot service to call a webhook to trigger a build whenever an entry is added.

**Comment by ciprian97** [comment]
@ascorbic I'm using Netlify

**Comment by ascorbic** [comment]
Ok, so your Netlify site settings will have the URL of a webhook that you can hit to trigger a build. If your server can do that when a product is added then it will rebuild it. 
Rather than querying the API inside createPages, you would be better using sourceNodes. Here's a guide on how to do this: 
https://www.gatsbyjs.org/docs/creating-a-source-plugin/

**Comment by LekoArts** [comment]
Thank you for opening this!

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
