### ISSUE TITLE
graphql query for GatsbyContentfulFluid does not work in gatsby-node.js

### ISSUE THREAD

**Issue by stephaniedavidson** [gatsbyjs/gatsby#23891]
## Description

Have a portfolio site with Contentful + Gatsby. I'm trying to replace regular img's with gatsby-image's fluid Img. I have succesfully done this on my index.js landing page with a query that looks like this:
```
  const data = useStaticQuery(graphql`
    query {
      allContentfulWork(sort: { fields: publishedDate, order: DESC }) {
        edges {
          node {
            title
            slug
            tags
            featured
            publishedDate(formatString: "YYYY")
            heroImage {
              fluid(maxWidth: 1800) {
                ...GatsbyContentfulFluid
              }
              title
              file {
                url
                contentType
              }
            }
          }
        }
      }
    }
  `)
```

However, when I add that fluid query in gatsby-node.js, where I generate tag pages from a template using createPages, it breaks the build: 
> "gatsby-node.js" threw an error while running the createPages lifecycle:
> Cannot read property 'allContentfulWork' of undefined

my gatsby-node.js file looks like this:

```
const path = require("path")

removeSpaces = word => {
  return word.replace(/ /g, "")
}

const createTagPages = (createPage, posts) => {
  const tagTemplate = path.resolve("./src/templates/tagged.js")
  const allTagTemplate = path.resolve("./src/templates/allTags.js")
  const postsByTags = {}
  posts.forEach(({ node }) => {
    const splitTags = node.tags.split(",").map(t => t.trim())
    //split tags is an array of strings of tags for each post ['illustration', 'motion']
    if (node.tags) {
      splitTags.forEach(tag => {
        if (!postsByTags[tag]) {
          postsByTags[tag] = []
        }
        //postsByTags[tag] is all the post objects with that tag
        postsByTags[tag].push(node)
      })
    }
  })

  const tags = Object.keys(postsByTags)
  createPage({
    path: `/tags`,
    component: allTagTemplate,
    context: {
      tags: tags.sort(),
    },
  })
  //create EACH TAG PAGE
  tags.forEach(tagName => {
    const posts = postsByTags[tagName]
    createPage({
      path: `/${tagName.replace(/ /g, "")}`,
      component: tagTemplate,
      context: {
        posts,
        tagName,
      },
    })
  })
}

module.exports.createPages = async ({ graphql, actions }) => {
  const { createPage } = actions
  const res = await graphql(`
    query {
      allContentfulWork(sort: { fields: publishedDate, order: DESC }) {
        edges {
          node {
            slug
            tags
            title
            heroImage {
              title
              file {
                url
                contentType
              }
            }
          }
        }
      }
    }
  `)
  const posts = res.data.allContentfulWork.edges
```

so in heroImage up there, right below it in gatsby-node.js, when I add
```
fluid(maxWidth: 1800) {
     ...GatsbyContentfulFluid
 }
```
it breaks.

### Steps to reproduce

Problem is coming from trying to parse a particular Contentful setup I have with a heroImage and comma separated tags for each post so not sure how you would recreate.
Repo: https://github.com/stephaniedavidson/steph

### Expected result

I think I should be able to use gatsby-image's fluid <Img> in my tag template but I cannot access 
            heroImage {
              fluid(maxWidth: 1800) {
                ...GatsbyContentfulFluid
              }
in gatsby-node.js

### Actual result
npm run dev error:
> "gatsby-node.js" threw an error while running the createPages lifecycle:
> Cannot read property 'allContentfulWork' of undefined

### Environment

  System:
    OS: Windows 10
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
  Binaries:
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.21.16 => 2.21.16
    gatsby-image: ^2.2.40 => 2.2.40
    gatsby-plugin-layout: ^1.3.1 => 1.3.1
    gatsby-plugin-react-helmet: ^3.1.18 => 3.1.18
    gatsby-plugin-sass: ^2.1.23 => 2.1.23
    gatsby-plugin-sharp: ^2.6.1 => 2.6.1
    gatsby-remark-images: ^3.1.35 => 3.1.35
    gatsby-remark-images-contentful: ^2.3.1 => 2.3.1
    gatsby-remark-relative-images: ^0.2.3 => 0.2.3
    gatsby-source-contentful: ^2.3.2 => 2.3.2
    gatsby-source-filesystem: ^2.1.37 => 2.1.37
    gatsby-transformer-remark: ^2.6.35 => 2.6.35
    gatsby-transformer-sharp: ^2.5.1 => 2.5.1

**Comment by pvdz** [comment]
@vladar do you think you could help here?

**Comment by vladar** [comment]
Hi @stephaniedavidson 

We need a way to reproduce it. Maybe you can provide your spaceId and temporary access token so that we could check? If you don't want to expose it publicly, you can send it to me directly via vladimir@gatsbyjs.com

Also please share specific steps to reproduce (or maybe a separate branch on your repo where this error occurs)?

**Comment by stephaniedavidson** [comment]
thanks Vladimir, will write you with my tokens

**Comment by vladar** [comment]
Sadly, this is expected behavior at the moment. Page queries (as well as static queries) are additionally processed when we extract them from source files using babel. For those queries, we append global fragments automatically.

In other words, when you write the following page or static query:
```graphql
query {
  allContentfulWork(sort: { fields: publishedDate, order: DESC }) {
    edges {
      node {
        heroImage {
          ...GatsbyContentfulFluid
        }
      }
    }
  }
}
```

It is transformed to a full executable version automatically:
```graphql
query {
  allContentfulWork(sort: { fields: publishedDate, order: DESC }) {
    edges {
      node {
        heroImage {
          ...GatsbyContentfulFluid
        }
      }
    }
  }
}
fragment GatsbyContentfulFluid on ContentfulAsset {
  # list of fragment fields
}
```

But it doesn't happen for custom queries in gatsby-node. Mostly because they are not statically analyzable, and we can't easily process them for you. That's why for now, you need to add a fragment manually to the query in gatsby-node OR simply list the fields you need (as you do now).

Unfortunately, Contentful plugin doesn't expose raw fragment strings, so it's not possible to require them and interpolate in your query.

**Comment by stephaniedavidson** [comment]
thank you so much for looking into this! really appreciate it. 

I'm a beginner so not sure what the query not being statically analyzable entails but I understand you're saying it's not possible right now to generate tag pages from gatsby-node and send it fluid image data, correct?

I wonder then instead of trying to generate static tagged pages if I should just make a vanilla js filter on my index page, unless you can recommend another approach?

**Comment by vladar** [comment]
> it's not possible right now to generate tag pages from gatsby-node and send it fluid image data, correct?

Not exactly. You can do this, you just need to add all the fields manually instead of using a fragment. Here is a fragment for contentful fluid: https://github.com/gatsbyjs/gatsby/blob/e267ca00f519a1cddb230a34fc11acf5d8e2fc17/packages/gatsby-source-contentful/src/fragments.js#L92-L97

So instead of spreading a fragment you use the equivalent query manually:

```graphql
query {
  allContentfulWork(sort: { fields: publishedDate, order: DESC }) {
    edges {
      node {
        heroImage {
          base64
          aspectRatio
          src
          srcSet
          sizes
        }
      }
    }
  }
}
```

This query is identical to the query with a fragment. A fragment is simply a convenient tool to re-use the same set of fields in different queries, but you can always replace them by listing fields manually (fragments don't have any special semantic meaning).

But I guess the real question in your situation is why do you want to send fluid image data when creating a page instead of querying it inside the page template?

**Comment by stephaniedavidson** [comment]
Thanks for clarifying, understand how to edit the gatsby-node page now, but I see what you're saying about querying in the template making more sense. Sorry this is probably getting into stackoverflow question territory here, but I don't know GraphQL well and I'm not sure what the query would look like in the tagged.js page. I'm sending the tagged.js page all my post data as a json under a certain tag, how would I query just those posts within t he tagged template?

thanks again!

**Comment by vladar** [comment]
Hey, check out this [article in our docs](https://www.gatsbyjs.org/docs/page-query/#how-to-add-query-variables-to-a-page-query) which explains this.

In short, you add an array of post `ids` to the tagged page `context` when creating a page and then use those `ids` as a variable to fetch the actual posts with all the data needed (maybe using `in: $ids` filter). Here is a [document on filtering](https://www.gatsbyjs.org/docs/graphql-reference/#filter).

**Comment by stephaniedavidson** [comment]
thank you!!
