### ISSUE TITLE
Saving the Gatsby source WordPress data

### ISSUE THREAD

**Issue by JimmothySanchez** [gatsbyjs/gatsby#23932]
This probably isn't the right place to ask but I'm having trouble finding a solution to this problem. I'm currently trying to migrate a personal wordpress site to Gatsby. I'm using the source wordpress plugin, but I'd like to retire my old site and just keep everything in Gatsby. Is there a way to use the plugin to pull the info fromwordpress, but then store it locally in a file so that it don't need to pull it again?  I've tried saving the xml export from wordpress and then consuming that, and I've tried using various Json exporters from wordpress, but the source wordpress plugin-in Gatsby seems to collect the most information and make the graphql syntax the simplest.

**Comment by KyleAMathews** [comment]
Curious what information source-wordpress gets that other ways of exporting data doesn't?

This is a cool idea though — a process for exporting data into the repo & then having a source plugin which keeps the data in the same shape so if you stop using a CMS or some other source — you could close it & all your templates work the same.

**Comment by TylerBarnes** [comment]
That's a cool idea indeed! Since nothing like that exists right now I think a reasonable path forward is to write a script to export to JSON files and then use  [`gatsby-transformer-json`](https://www.gatsbyjs.org/packages/gatsby-transformer-json/) to create a similar or identical schema to `gatsby-source-wordpress`. For example if you have posts you could export to `src/json/posts/*.json`, be sure to add the type of the node to each node object as you're writing to json, and then add something like this to your `gatsby-config.js`:

```js
module.exports = {
  plugins: [
    {
      resolve: `gatsby-transformer-json`,
      options: {
        typeName: ({ node }) => node.savedTypeName,
      },
    },
  ],
}
```

Since `gatsby-source-wordpress` uses inference on the node object to create the schema, you wouldn't even need to do gql queries to export. You can use [`getNodesByType`](https://www.gatsbyjs.org/docs/node-api-helpers/#getNodesByType) on each type you want to export and write the nodes raw json to disk.

**Comment by JimmothySanchez** [comment]
So I've added a fs.writeFile to the gatsby-node.js file for each word-press post and it's a bit of a workaround, but seems to be working. What about the images though? Is there a good way to write those to disk locally, and if I do is there a way to make sure that the paths match the old paths that the posts already reference?

**Comment by TylerBarnes** [comment]
@JimmothySanchez you'll need to write a script to download them all and save them to disk as well. You can store them in a directory the same way they're stored on the server so the paths match up, then modify the paths in your nodes to point to them. `yoursite.com/wp-content/uploads/2020/01/image.jpeg` could be fetched and stored at `images/wp-content/uploads/2020/01/image.jpeg`, then in your nodes you can replace any references so they're relative from the json to the file `../../wp-content/uploads/2020/01/image.jpeg`. Then if you have `gatsby-transformer-sharp` set up you should be able to use those images the same as before. You could either rewrite the image links to paths on disk or during onCreateNode in every build.

**Comment by TylerBarnes** [comment]
Hi @JimmothySanchez , I believe this issue was answered and it sounds like you have it working so I'm going to close this. Feel free to comment here or re-open if you're having trouble with this.
