### ISSUE TITLE
How do I make a page already loaded with data retain its loaded data when a user re-visit the page

### ISSUE THREAD

**Issue by Blissfulair** [gatsbyjs/gatsby#23994]
I am new to gatsby and i developing shopping app. currently i am fetching data from laravel backend with axios when the page loads but if I leave the current page and return back, the data have to load up again. I don't think this is experience for a user. How can I make the already loaded page retain the fetched data on re-visit?

**Comment by madalynrose** [comment]
Hi @Blissfulair!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by Blissfulair** [comment]
Thanks @**madalynrose**
I have solved the problem using localstorage but I am not sure if this is the best solution anyway

**Comment by wardpeet** [comment]
Hey @Blissfulair,

What data are you fetching with axios? It seems like, it's better to opt into the datalayer gatsby provides. If you want to read more about how to configure gatsby to load your data into the datalayer, here are some resources:
- https://www.gatsbyjs.org/docs/creating-a-source-plugin/
- https://www.gatsbyjs.org/docs/data-fetching/
- https://www.gatsbyjs.org/docs/content-and-data/

If you still need to use axios for parts of your site, I would refer to https://web.dev/storage-for-the-web/ to see what storage option suits the best for your use-case.

Thanks so much for opening this issue! As stated, this is slightly tangential to Gatsby, and it seems like we’ve provided enough information to make an informed decision.

If this is not the case, or if we can help further--please don’t hesitate to reach out or comment on this issue, and we’d love to take another look.

Thanks for using Gatsby 💪
