### ISSUE TITLE
ACF Images Return Null

### ISSUE THREAD

**Issue by mpaccione** [gatsbyjs/gatsby#24036]
Hello, I have a bug test repo here:
https://github.com/mpaccione/gatsby-debug

Just install and run develop, then go to 8000 and look in the textarea where I output stringified JSON of ACF Fields.

All of my ACF Fields are populated in the Wordpress site. 

Here is the GraphQL

```
export const pageQuery = graphql`
  query {
    allWordpressPage {
      edges {
        node {
          id
          title
          excerpt
          slug
        }
      }
    }
    allWordpressPost {
      edges {
        node {
          title
          excerpt
          slug
          acf {
            team_members {
              value
              label
            }
            video_iframe
            viewing_link
            repo_link
            images {
              dummy
              image {
                localFile {
                  url
                }
              }
            }
          }
        }
      }
    }
  }
`
```

```
{
      resolve: `gatsby-source-wordpress`,
      options: {
        // your WordPress source
        baseUrl: `agencydb.giddyuppupsf.com`,
        protocol: `http`,
        // is it hosted on wordpress.com, or self-hosted?
        hostingWPCOM: false,
        // does your site use the Advanced Custom Fields Plugin?
        useACF: true,
      }
    },
```

**Comment by wardpeet** [comment]
I'm adding some extra information to the ticket

In console while running I see:
```
warn Multiple node fields resolve to the same GraphQL field `wordpress__POST.acf.images.image` - [`image`, `image___NODE`]. Gatsby will use `image___NODE`.
warn Multiple node fields resolve to the same GraphQL field `wordpress__acf_posts.acf.images.image` - [`image`, `image___NODE`]. Gatsby will use `image___NODE`.
```

This is the ACF content:
```
{"team_members":[{"value":"Michael Paccione","label":"Front End Engineer"},{"value":"Joshua Rubin","label":"Back End Engineer"}],"video_iframe":"","viewing_link":"","repo_link":"","images":[{"dummy":null,"image":null},{"dummy":null,"image":null},{"dummy":null,"image":null}]}
```

**Comment by jasonbahl** [comment]
@mpaccione I have 2 things to try can you change your image field in ACF to output the "image array" instead of the "image URL"?

![Screen Shot 2020-05-13 at 8 10 10 AM](https://user-images.githubusercontent.com/1260765/81824079-4c38aa80-94f2-11ea-8460-6036d4b60ee9.png)

This will change your WP REST API to output full objects instead of just the url: 

**Before**:
![Screen Shot 2020-05-13 at 8 09 55 AM](https://user-images.githubusercontent.com/1260765/81824164-63779800-94f2-11ea-998a-b30d136c9fda.png)

**After**:
![Screen Shot 2020-05-13 at 8 11 22 AM](https://user-images.githubusercontent.com/1260765/81824217-6e322d00-94f2-11ea-9419-09c27db8acb6.png)

If, for some reason that doesn't help in your environment, can you also try using the ACF Gallery Field for a list of images instead of a Repeater field with an image field inside it and see if that makes any kind of difference?

**Comment by mpaccione** [comment]
Hi again Jason, thanks for your help, 

In wanting to debug this I am experiencing some strangeness... I went and created an image gallery field. Populated one post with the gallery field but it doesn't show on the graphql inspector.

Do all posts need to have the field populated for it to show in the graphql inspector?

**Comment by mpaccione** [comment]
Hey everyone so I went through and made sure to populate all posts gallery field, cleaned gatbsy, and ran develop. 

**The gallery field appears as an empty array.** I have pushed to the repo.

The old graphql in index.js is commented out and the new one with the gallery field is in effect. I haven't changed the field structure on the wordpress database so you can still go back and test the issue with the old images bit.

`// NEW QUERY USING GALLERY - GALLERY APPEARS EMPTY
export const pageQuery = graphql`
  query {
    allWordpressPage {
      edges {
        node {
          id
          title
          excerpt
          slug
        }
      }
    }
    allWordpressPost {
      edges {
        node {
          title
          excerpt
          slug
          acf {
            team_members {
              value
              label
            }
            video_iframe
            viewing_link
            repo_link
            gallery {
              localFile {
                url
              }
              link
              source_url
            }
          }
        }
      }
    }
  }
``

Please check this image url in case the gatbsy plugins I have on the site would be causing an issue.
https://pasteboard.co/J8PNy1x.png

**Comment by jasonbahl** [comment]
@mpaccione Ah yes. This happened to work for me because I modified the first post in my local site and that allowed Gatsby to infer the shape from that post and create a schema from that. I see how this would be an issue if the first post had different shape of data. This gets us back to why Gatsby is investing in WPGraphQL for the future of WordPress + Gatsby.

Since the WP REST API doesn't enforce a Schema, plugins such as the ACF 2 REST API chose not to make use of the WP REST API Schema and that makes it very difficult for decoupled applications, such as Gatsby, to know what to expect from the REST API responses. When each Post returned from the API can have a wildly different shape that makes it very difficult to build anything with confidence.

When Gatsby consumes data from the WP REST API it analyzes the first Post and creates an inferred Schema from that, then assumes subsequent objects of the same type will have the same shape. Posts with ACF Field Groups, especially when you start using Flex Fields, will almost never have the same shape. This gets problematic for Gatsby pretty quickly.

WPGraphQL and the WPGraphQL for ACF extension solve this problem by making use of a strongly typed Schema on the WordPress server. Things like ACF fields, that can be unpredictable, are now predictable because they are exposed to the WPGraphQL Schema. Gatsby asks for the WPGraphQL Schema and because of that Schema Gatsby knows what is _possible_ on each Post before even asking for data. This allows Gatsby to use WordPress as a data source much more reliably because it knows what to expect, even in the face of unpredictable input (such as flex fields).

I believe the options for you here are:

- **(My official recommendation)** Migrate away from the current `gatsby-source-wordpress` + WP REST API setup and begin using [WPGraphQL](https://github.com/wp-graphql/wp-graphql), [WPGraphQL for Advanced Custom Fields](https://github.com/wp-graphql/wp-graphql-acf) and the new [Gatsby Source WordPress Experimental](https://www.npmjs.com/package/gatsby-source-wordpress-experimental) plugin. Here's a [repo](https://github.com/TylerBarnes/using-gatsby-source-wordpress-experimental) showing it in action.
- Continue using `gatsby-source-wordpress` and the WP REST API, and make use of the [Gatsby Schema Customization](https://www.gatsbyjs.org/docs/schema-customization/) APIs to manually register the Types and Fields you need so that Gatsby can behave consistently even when WordPress is not.

**Comment by mpaccione** [comment]
Okay I have gone with your official recommendation and made a local repo to test this migration.

I just did a quick test to see if I could get the gallery field src and I am able to. 👍 

I suppose I will go to my main repo and migrate this over. 

Naturally for anyone else viewing and referencing the files and urls my gatsby-debug repo db side now will be changed so just rely on the text and image content.

Thanks Jason :+1: :+1: :+1:
Looking forward to gatsby-source-wordpress getting deprecated and replaced.
