### ISSUE TITLE
Shouldn't gatsby build warn developers of missing plugins, if possible?

### ISSUE THREAD

**Issue by mclarkestudio** [gatsbyjs/gatsby#24096]
Gatsby is very well documented. 
Although, shouldn't [common troubleshooting errors](https://www.gatsbyjs.org/docs/troubleshooting-common-errors/#inconsistent-css-styles-between-develop-and-build-using-styled-components-or-emotion) such as missing plugins be added directly to the `gatsby build` log?

It seems worthwhile to warn the developer that they are using a library with a missing gatsby plugin. If the developer is using `styled-components` warn that there is no plugin for it to be processed server-side by gatsby. (Or can you use it client side with gatsby??)

(Note: I had a local VSCode bug as well, so the built CSS and build process were especially confusing to debug.)

**Comment by pieh** [comment]
Theoretically yes, but `gatsby` core is rather agnostic to plugins and we try to keep it that way. As soon as gatsby core know about styled components - maybe instead of suggesting plugin it should just come with plugin as internal dependency? But styled components is just one example of it - if we do this for everything then every user pays the perf price for things like this, so there is non-zero cost to it.

We do acknowledge this problem, but in general I don't think this should be included in core package. Instead we explore idea of having some form of "diagnostics" command that user would run and would be mentioned in documentation as well as issue template etc and other places to raise awareness of command like this (because it might be hard to discover). However there is no work being done yet on this other than research and collecting ideas for what we could check in diagnostic tool.

Additionally - there is currently effort on creating wrappers around adding packages and equivalent plugins to projects - check out https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-recipes (if you have recent `gatsby(-cli)` version - you can try `gatsby recipes` which has one for styled-components that installs and setups gatsby-config for you.
