### ISSUE TITLE
Some 'Best Practices' Questions

### ISSUE THREAD

**Issue by nickrazes** [gatsbyjs/gatsby#24139]
Hello everyone:

What's the best practice for going about the following? Can someone with experience using these things point me in the right direction?

1. SVG files? How should I use these kinds of image files within my Gatsby.js project? I first tried using gatsby-image to no avail. I seem to be having problems with this no matter what I try. Should I be using the publicURL approach or just simply importing them into my file? The weird thing with this is that I feel like it was working at one point and then stopped...

2. Integration with React Bootstrap?  (https://react-bootstrap.github.io/). Good idea? Bad idea? I'd like to use some of their components, in particular: the navbar dropdown functionality and possibly the carousel. I also kinda like the Row and Col approach. Is it safe to use this or should I be avoiding it and building my own components? What about the Row/Col tags vs something else (flexbox?)?

3. How to set an image as a background image of an element? For example, I wanted a div that was basically an image that has page content in front of it. I tried doing it through css, doing it directly in the component but aren't having any luck getting it to show no matter what I try. It seems the gatsby-image is causing me problems because I'm trying to pass a component off as an image but I'm not sure. To make matters worse there is one part where I'm using a standard gatsby-image processed image as the background and another place where I'd like to do the same thing with an SVG. What's the best practice for doing this?

Thanks for your time.

**Comment by capndave** [comment]
I'll take a stab at these though I'm sure someone else may have better insight into this.

1. You should use gatsby-image rather than importing directly into your file. Basically it gives you optimized image loading. If you're having trouble getting that to work please post a separate issue with more detailed information and samples of your code.

2. I don't know of any reason why using react bootstrap would conflict with Gatsby. I'm sortof a DIY style guy so I don't personally love bootstrap or other CSS frameworks, but React Bootstrap should be all about style, Gatsby is about functionality, I think they should play nice together.

3. Did you check out [gatsby-background-image](https://www.gatsbyjs.org/packages/gatsby-background-image/)? Again, if you're having problems getting image loading to work I'd suggest making a separate issue with more detailed info. If you're struggling with multiple image issues, you might try backing up or making your project more simple, getting it to work one image or issue at a time.

**Comment by nickrazes** [comment]
Thanks for the reply. It is greatly appreciated. In response:

1. So my follow up question is that you're saying that the answer to the following issue is wrong?
https://github.com/gatsbyjs/gatsby/issues/10297
Don't get me wrong. I'm not necessarily disagreeing as the following issue seems to agree with you.
https://github.com/gatsbyjs/gatsby/issues/12499
Hence the question. These two issues seem to be contradicting themselves. Which one should I be going with? Have you used svg image files in your projects? Does the graphql approach even do anything with a vector image file?

2. Thank you. So far I haven't had any problems with it. I'll post a separate issue if something comes up with this. 

3. I did not see this. Thank you. It seems to be what I needed :)

**Comment by nickrazes** [comment]
I'm still messing around with it but it seems like the #10297 importing approach only works if you're importing an svg to be used directly within a component. If you try to import an svg directly into a page it will fail to compile because it can't find the svg (even if it is referenced correctly) and basically force you to use the publicURL approach of #12499.

**Comment by LekoArts** [comment]
Thank you for opening this!

To answer your questions:

1. gatsby-image never supported SVG files (there also wouldn't be much of a benefit). Some options are outlined here: https://www.gatsbyjs.org/docs/importing-media-content/#images-svg-and-pdfs

2. Gatsby works with every UI library (albeit there might be some hiccups if they use `window` object internally), but for React bootstrap you can have a look at these starters: https://www.gatsbyjs.org/starters/?c=Styling%3ABootstrap&v=2

3. This is solvable with CSS, however you can use a helper component like https://www.gatsbyjs.org/packages/gatsby-background-image/ to make it easier.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
