### ISSUE TITLE
Installing module in gatsby removing some gatsby dependent modules.

### ISSUE THREAD

**Issue by rakeshshubhu** [gatsbyjs/gatsby#24176]
#issue 
My issue is similar to his https://github.com/gatsbyjs/gatsby/issues/6834. I've faced this issue before just a day in a new gatsby project. 
When installing a module after a project is set up it deletes some of the gatsby depencies. And I'm unable to run `gatsby develop` because of missing dependencies.

#solution: 
It can be solved by running Npm install again which is definately not ideal.

#Steps to reproduce:
1. generated a fresh new gatsby site without any template.
```
gatsby new site
```
2. `npm i gatsby-plugin-typescript` this will remove the depencies.

I don't have the warnings but it was showing something like` update core.js 2.3.`

**Comment by LekoArts** [comment]
Thank you for opening this!

As mentioned in some other issue (https://github.com/gatsbyjs/gatsby/issues/20225, https://github.com/gatsbyjs/gatsby/issues/19827, https://github.com/gatsbyjs/gatsby/issues/19064) this is due to a bug with npm and its lock files. You probably have `yarn` installed or chose it as your package manager for the Gatsby CLI hence a `gatsby new` will delete the `package-lock.json` file upon installation. This then causes problems if you use `npm` again.

You can change your default manager if you always want to use `npm`: https://www.gatsbyjs.org/docs/gatsby-cli/#how-to-change-your-default-package-manager-for-your-next-project

We'll work on improving this by maybe e.g. not deleting the lock files (as `yarn` doesn't have problems with this).

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by jaytommy** [comment]
This is absolutely bonkers! I am a Gatsby newbie and have a similar issue to so many here.  I installed the sass plugin (along with node-sass) and the gatsby develop command fails.  I've had the cannot find React error.  Now I am getting the issue where it cannot interpret my scss file.
![image](https://user-images.githubusercontent.com/38990412/93905783-f60a1e00-fcc0-11ea-94a5-e09a3ef95f0a.png)

I deleted lock files and node_modules then ran npm install.  Still no luck.
I deleted lock files and node_modules then attempted to install with yarn.  Still no luck.

I am willing to start anew, but need some guidance on the most reliable path.  Use npm? yarn?  Are there certain versions of gatsby, react, react-dom, etc to avoid?
