### ISSUE TITLE
Update shopify plugin to support  Accept-Language Header

### ISSUE THREAD

**Issue by alexantom** [gatsbyjs/gatsby#24173]
## Summary

Shopify Store Front API Supports Multi Language by adding `Accept-Language: "it"` in request header

https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-source-shopify

https://shopify.dev/tutorials/manage-app-translations-with-admin-api

https://github.com/Shopify/js-buy-sdk/pull/749/files

### Basic example

https://shopify.dev/tutorials/manage-app-translations-with-admin-api

### Motivation

Having this option will  support multi language gatsby shopify store.
Expectation is to query products, collection by passing language flag  and get the data to render the pages.

### Approach
If we add as part of options, we will only able to pull one language at a time , Better way is to pass language while querying and add headers dynamically
https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-source-shopify#how-to-use

Tried some options from my localhost here
https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-shopify/src/lib.js#L25

```
const queryOnce = async (client, query, first = 250, after) => {
   if(lang) {
      client.setHeader('Accept-Language', lang) // How to pass language code ?
  }
  return await client.request(query, {
    first,
    after
  });
}
```
I'm not sure how i can pass language code from  page or product query

**Comment by smthomas** [comment]
Thanks for documenting this feature feature request. After some investigation, I discovered the following things that would need to be considered when implementing this feature:

1. The Shopify API version that is currently used would need to be updated. It's currently set at 2019-07 while the current version is 2020-04 (this version supports translations with the Accept-Language header). I don't know enough about the differences between these versions, but it could require some changes to the GraphQL queries and could potentially cause breaking changes for those currently using gatsby-source-shopify when they upgrade.

2. When you retrieve the translated content from the Shopify Storefront API (using the Accept-Language header) the translated items have the same `id` value as the untranslated items. I think this would cause issues as Gatsby would just overwrite the internal node rather than creating a new one. This means even if you could pass the Language as shown in your Approach above it would require additional refactoring to get it to work.

Overall, I think this would be a great change to make. I'm happy to try to help point you in the right direction but it seems like it is going to require a significant amount of refactoring to get it to work. Is this something you are still looking to figure out? If so, would you be interested in helping build out this functionality?

**Comment by alexantom** [comment]
@smthomas , if  i have to pass language from config and set as part of the header, what is the best way?

I will try to  test out the solution locally.

If you share some code snippet to accomplish this, that would be very helpful.

In my use case, i will have multiple build process targeting different language code.

**Comment by gempi** [comment]
I added a pull request #27413 to add multi language support. feel free to contribute!

**Comment by LekoArts** [comment]
You can follow progress in this new issue: https://github.com/gatsbyjs/gatsby-source-shopify-experimental/issues/66
