### ISSUE TITLE
gatsby image increases assembly

### ISSUE THREAD

**Issue by Gercog52** [gatsbyjs/gatsby#24191]
## off gatsby imges
![1](https://i.ibb.co/9vs3HJY/test.png)
## on gatsby images
![2](https://i.ibb.co/6wkmHMc/test2.png)

# how to fix big bundle ?

**Comment by herecydev** [comment]
Having 80 images isn't ideal for 1 page but it's your website scripts I would be most concerned about. It's 5x bigger than your images size.

**Comment by pvdz** [comment]
With gatsby image the size of script+image is less than without.

I would have a look at the config and figure out why the website is shipping so much JS in the first place.

Additionally, per definition, more images on a page will make your page slower to load.

**Comment by Gercog52** [comment]
> С изображением Гэтсби размер сценария + изображение меньше, чем без.
> 
> Я бы взглянул на конфиг и выяснил, почему на сайте так много JS.
> 
> Кроме того, по определению, больше изображений на странице замедлит загрузку вашей страницы.

js size increases after adding gatsby image

**Comment by LekoArts** [comment]
Thank you for opening this!

It doesn't seem like this issue is actionable or reports an error/bug or what your question is. As pointed out by the others there is nothing "to fix" with Gatsby image. It comes with a bit of JS to e.g. handle lazy-loading of images but the bulk of your overall bundle comes from something different. You should look into your other imports in your project or use something like `webpack-bundle-analyzer` to see where it's coming from.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
