### ISSUE TITLE
Contentful should be able to cache its network responses

### ISSUE THREAD

**Issue by wardpeet** [gatsbyjs/gatsby#24222]
# Summary

If we could cache network responses from contentful we would be able to startup gatsby quicker and it would help us triage issues for our customers.

**Comment by esped-dfds** [comment]
I've made a feature request to contentful so they 

1: dont wipe cache for sync api(for full(100 entries) pages) since those should never change
2: reuse the response from sync?initial=true because any updated entries will just be added to the last pages

These changes make the difference between 150ms or 900ms IOW: 3 minutes or 15 minutes for 100k entries

In the meantime i'm using a local proxy while developing, which I've pasted below. Enable it by setting environment variable HTTPS_PROXY=http://localhost:3001

    const express = require('express')
    const axios = require('axios').default
    const { stringify } = require('querystring')
    const syncCache = {}

    const app = express()
    app.get('*', async (req, res) => {
      const qs = stringify(req.query)
      const key = req.path + '?' + qs
      const cached = syncCache[key]
      if (cached) return res.send(cached)
      const { accept, authorization } = req.headers
      const { data, status } = await axios.get(`https://${req.header('host')}${req.path}?${qs}`, {
        proxy: { host: 'localhost', port: 8888 },
        validateStatus: () => true,
        headers: { accept, authorization },
      })
      console.log('req', status, req.path, req.method.toLocaleLowerCase(), req.header('host'), qs)
      if (status === 200 && data.items && data.items.length === 100) syncCache[key] = data
      res.status(status).send(data)
    })
    app.listen(3001, () => console.log('listening'))
