### ISSUE TITLE
Is there a way to actually get the error message from 'internal server error'?

### ISSUE THREAD

**Issue by MitchEff** [gatsbyjs/gatsby#24246]
Whenever we get 'internal server error', my team spends humongous amounts of time just throwing mud at the wall to try and figure out what it's hinting at. 

In another other environment, when there's an 'internal server error', we at least get some information about what went wrong. In this case, it's more of a 'I'm not telling - go figure it out'. 

Is there any way of getting any extra context, or is that all Gatsby's able to say?

**Comment by KyleAMathews** [comment]
This is when running gatsby develop on a dev machine?

**Comment by MitchEff** [comment]
It is, yeah. If it helps at all, we're connecting to WordPress through WP GraphQL. 

Just for clarity's sake - the errors themselves are indeed always our fault - we're just having difficulty debugging them when they occur.

**Comment by LekoArts** [comment]
Hi, thanks for the issue! Please follow our issue template in the future and I'd appreciate if you could edit your initial post, too. Otherwise we also have to figure out what you're hinting at :)

**Comment by jasonbahl** [comment]
@MitchEff The "Internal Server Error" message sounds like it is likely coming from the WordPress/WPGraphQL side of things rather than Gatsby. 

We have a page on debugging here: https://docs.wpgraphql.com/guides/debugging/ which includes a section on the "Internal Server Error" message. Try walking through those tips. If you continue having issues on the WPGraphQL side of things and the information in the docs for debugging doesn't help, please open an issue on the WPGraphQL repo: https://github.com/wp-graphql/wp-graphql and we can look into it further.
