### ISSUE TITLE
Gatsby image progressive loading issue

### ISSUE THREAD

**Issue by milesalex** [gatsbyjs/gatsby#24270]
## Description

Describe the issue that you're seeing.

When I refresh my page, the logos all use the same preload image. It looks quite odd.

![Screen Capture on 2020-05-20 at 11-52-51](https://user-images.githubusercontent.com/421362/82480094-8674ef80-9a90-11ea-9bda-3bd0fdf9edcc.gif)

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

How to Make a Minimal Reproduction: https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/

### Expected result

What should happen?

### Actual result

What happened.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by milesalex** [comment]
I updated to the latest version and now getting broken images on load

![Screen Capture on 2020-05-20 at 11-56-32](https://user-images.githubusercontent.com/421362/82480429-04d19180-9a91-11ea-814b-aed0a26a5ee8.gif)

**Comment by ascorbic** [comment]
Hi

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it would be really helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

Thanks!

[reproduction]: https://gatsby.dev/reproduction

**Comment by milesalex** [comment]
Updating the packages solved it. Not sure what was happening tho.
