### ISSUE TITLE
Update Documentation links after Typescript conversion

### ISSUE THREAD

**Issue by smthomas** [gatsbyjs/gatsby#24313]
## Summary

There are some links in the documentation that point to code in the Gatsby repo that was a Javascript file and has now been converted to a Typescript file. This is causing those documentation links to 404 as the URL's need to be updated with the `.ts` extension.

I only did a quick search through the docs, but uncovered a few pages with issues.

1. https://www.gatsbyjs.org/docs/making-your-site-accessible/#linting-with-eslint-plugin-jsx-a11y - Broken .eslint-config.js link
2. https://www.gatsbyjs.org/docs/page-node-dependencies/#how-dependency-information-is-used - Broken findIdsWithoutDataDependencies and findDirtyIds links
3. https://www.gatsbyjs.org/docs/schema-generation/ - A number of broken links

I think we need to do a further dive into the docs as I expect we will find many other examples where these links need to be updated.

**Comment by lwkchan** [comment]
i've started working on this issue! should have a pr ready soon :)

**Comment by AishaBlake** [comment]
The specific issues you uncovered have been addressed but I agree we still need to do a deeper dive to try and find additional broken links. From what I can tell, it looks like any additional broken links are because files have been moved or deleted (as long as a year ago). This should be taken care of as Core team members update internals docs. I'll revisit links as those changes come in but I don't think it's productive to update them now without also fixing the surrounding docs!
