### ISSUE TITLE
404 error when querying wp-json/wp/v2/pages

### ISSUE THREAD

**Issue by speculati0n** [gatsbyjs/gatsby#24319]
Hello, I am using the gatsby-source-wordpress plugin. Has anyone encountered the issue of their wp-json/wp/v2/pages getting a 404 error  when fetching using gatsby develop? every other endpoint works for me, except for /pages. and it was working fine until today. randomly out of no where starts throwing a 404 error. Is it possible that somehow my endpoint for "pages" was unregistered (no clue how to fix that if so)? As you can see below. 

![image](https://user-images.githubusercontent.com/26420672/82601185-290a9c80-9b7d-11ea-9a17-89a5b98389b0.png)

edit: I installed the Disable Rest API plugin to enable me to see what endpoints are available and the /pages endpoint is in fact there. I tried to activate it and still getting the same 404 error. 
![image](https://user-images.githubusercontent.com/26420672/82608984-a5a37800-9b89-11ea-887b-80ef9a906e43.png)

**Comment by jasonbahl** [comment]
@speculati0n In the screenshot you shared the error is a 504 timeout, not a 404. 

This means your WordPress server is having issues returning the data the endpoint is exposing. 

I can visit the endpoint `http://dynamicvol.com/wp-json/wp/v2/pages` in the browser and it indeed takes a long time to resolve. This is for the default 10 posts per page.

**Size:** 1.7mb
**Time:** 1.3min

![Screen Shot 2020-05-22 at 6 41 55 AM](https://user-images.githubusercontent.com/1260765/82668720-56942c00-9bf7-11ea-88c4-0ec262649d6f.png)

If I do it for the max allowed 100 posts per page the server takes even longer to respond. I'm surprised it didn't 504 for me also. 

The page with ID `2503`, slug of `vol-dashboard` alone takes 17.43 seconds to respond in the REST API (http://dynamicvol.com/wp-json/wp/v2/pages/2503). 

The page with ID `2168`, slug of `alpha-studio` also takes quite a while to respond in the REST API (http://dynamicvol.com/wp-json/wp/v2/pages/2168).

It's hard to say for sure what the culprit is without knowing more about your setup, but it looks like these pages are making use of quite a bit of data and WordPress is waiting for all of that to process before it can respond. My guess is that behind the scenes WordPress needs to make many different queries to many different resources to gather the data that is displayed in these tables? If that's the case, you might want to look into caching those queries to make sure they're not re-executing every single time the REST endpoints are hit. 

You should also consider using [WPGraphQL](https://github.com/wp-graphql/wp-graphql) on your WordPress server and the new [Gatsby Source WordPress Experimental](https://www.gatsbyjs.org/packages/gatsby-source-wordpress-experimental/) plugin. This is the future of WordPress and Gatsby we're planning to support longterm. You can find a repo that uses it here to reference as a starting point: (https://github.com/TylerBarnes/using-gatsby-source-wordpress-experimental)

WPGraphQL solves many problems the WP REST API faces when it comes to using WordPress in a decoupled manner. Performance is one area WPGraphQL improves upon. The WP REST API suffers from a problem called the n+1 problem. 

When you hit an endpoint such as `/wp/v2/pages` the WP REST API behind the scenes makes a query for 10 posts, then it runs a loop over those to posts and makes additional queries for connected resources (tags, categories, images, authors, etc). 

So for each page (10) you end up with 10 queries for tags, 10 for categories, 10 for images, 10 for authors. If you ask for 100 items, you end up with 100 queried for these things. 

With WPGraphQL, if you ask for 10 (or 100) pages, it defers the resolution of the connected resources and makes a batch request for all of them. 

For example, instead of a foreach loop calling `get_post_author( 1 )`, `get_post_author( 2 )`, etc it will make just 1 query to get all authors for posts 1-10, or 1-100. This can drastically increase performance for fetching data from WordPress over an API. 

You might see immediate wins using WPGraphQL instead of the WP REST API.

I do think there will likely still be performance issues with your site using WPGraphQL though, as I have a feeling the "content" field is doing a lot of processing behind the scenes to compile the data for the charts and WPGraphQL likely can't solve that out of the box.

**Comment by jasonbahl** [comment]
@speculati0n I'm going to close this as it doesn't appear to be a Gatsby issue, but an issue that needs resolved on the WordPress side. 

You can join the public WPGraphQL Slack here: https://wpgql-slack.herokuapp.com/ where there's an active ecosystem of WordPress developers using WordPress in decoupled stacks that would likely be able to contribute ideas for improving the performance of the data/chart heavy pages.

**Comment by speculati0n** [comment]
@jasonbahl thank you so much for your very detailed response. I will look into everything you suggested, that was extremely helpful. have a great weekend!
