### ISSUE TITLE
contextModified is not properly re-evaluated if pages are deleted & created

### ISSUE THREAD

**Issue by xavivars** [gatsbyjs/gatsby#24353]
## Description

In https://github.com/gatsbyjs/gatsby/commit/6d7c5766fb1b4f70ccaf54627389a3d2fc9ee68a logic was added to re-evaluate page query when page context was changed. However, this doesn't work in all cases: sometimes pageContext change and there's no way to retrigger a change

This is the code that re-evaluates if page context have changed:

https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/redux/actions/public.js#L475

But when we try to replace pages hooking into `createPage`, following this documentation

https://www.gatsbyjs.org/docs/creating-and-modifying-pages/#pass-context-to-pages

with some logic like this one:

```
exports.onCreatePage = ({ page, actions }) => {
  const { createPage, deletePage } = actions

  if (page.data.replace) {
    deletePage(page)
    // You can access the variable "house" in your page queries now
    createPage({
      ...page,
      context: {
        ...page.context,
        house: `Gryffindor`,
      },
    })
  }
}
```

and when using gatsby develop, after hitting the `__refresh` data endpoint, if the conditions when the page gets replaced change, the `contextModified` logic doesn't work, because after "deleting" the original page, the condition `const contextModified =
    !!oldPage && !_.isEqual(oldPage.context, internalPage.context)` evaluates to false (`oldPage` does not exist)..

### Steps to reproduce

* Gatsby develop with `page.data.replace` is `false`
* Render page
* Change remote data source so `page.data.replace` becomes `true`
* Hit the `__refresh` endpoint
* Render the page

### Expected result

Replaced page is rendered with the new context

### Actual result

Replaced page with the original context

**Comment by pieh** [comment]
You are right. I just wonder how we could fix that... `deletePage` has immediate effect so our store removes that completely and when we recreate it, there's nothing to compare.

I do wonder if we could figure out "entry" `createPage` action call to grab `oldPage` from it, run all of the `onCreatePage` cascade and then compare after everything finished.

**Comment by xavivars** [comment]
I'm afraid I don't have the full picture to undertand what the side effects could be of having this

```
const contextModified =
    !!oldPage && !_.isEqual(oldPage.context, internalPage.context)
```

changed to this

```
const contextModified =
    !oldPage || !_.isEqual(oldPage.context, internalPage.context)
```

Basically, every time the "old page" didn't exist, firing the event with `contextModified` being `true`.

We've workarounded it by just doing a `createPage` (and skipping `deletePage`), and it seems that it works. That made me think what a "page" is for Gatsby, and it seems the _id_ of a page is it's path, and that is the reason why, in this case, we don't need to delete because we're essentially _updating_ the page. 

So maybe just having better documentation on what actually "delete" and "create" do (and that "create" also works for "update")...

But
1. I'm not sure if that is actually true, or if it just works by chance.
2. I will still not work in cases where delete/create have to create pages with different paths.

**Comment by pieh** [comment]
Not deleting cause other problems (depending on scenarios) - keep in mind that there can be multiple plugins that implement `onCreatePage` hook:

All of them gets called when page is created. What we do when page is deleted in this hook - is we short circuit `onCreatePage` calls for the rest of plugin that implement `onCreatePage` (with now outdated `page`) and we create new API run for the new shape of page.

Additionally keep in mind that there are plugins that actually adjust `path` of a page (plugins like https://www.gatsbyjs.org/packages/gatsby-plugin-remove-trailing-slashes/ ), so the old page just can't stay around.

Using code change like one you suggested will also cause Gatsby to always re-run all queries on initial run (instead of rerunning subset of them that we know for sure need rerunning). This is not trivial problem to solve :( That's why I was exploring idea of delaying context comparison to after entire `onCreatePage` cascade finishes and not directly in `createPage` action creator - because there will be quite a bit of `createPage` calls called for "same page" with plugins making use of `onCreatePage`

**Comment by xavivars** [comment]
So what are your suggestions to move forward, @pieh ?

**Comment by LekoArts** [comment]
Hi!

I'm closing this as a stale issue as in the meantime Gatsby 4 and related packages were released. You can check our [Framework Version Support Page](https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/) to see which versions currently receive active support.

Please try the mentioned issue on the latest version (using the `next` tag) and if you still see this problem, open a new bug report. It **must** include a [minimal reproduction](https://gatsby.dev/reproduction).

Thanks!
