### ISSUE TITLE
Is that possible to skip buildProductionBundle phase

### ISSUE THREAD

**Issue by ShinyLeee** [gatsbyjs/gatsby#24404]
## Summary

Is that possible to skip buildProductionBundle phase？

## Relevant information

![image](https://user-images.githubusercontent.com/13724426/82751994-b81deb80-9ded-11ea-87c0-0385c426cf21.png)

When i use docz to generate **multiple** components library docs，the `buildProductionBundle` phase take a long time，even if we **_only change doc content without modify project source code_**. 

And after i test skip `buildProductionBundle` phase in my local environment，i found a problem that `chunk-map.json` is not update because of the [webpack plugin extractStats ](https://github.com/gatsbyjs/gatsby/blob/44cbb14010/packages/gatsby/src/utils/webpack.config.js#L222) to generate `chunk-map` is only added in `build-javascript` phase.

So I wonder if there's any other considerations besides this one, and is that possible to move `extractStats` to `buildHTML` phase？

In addition, `GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES` is worked to speed up `buildHTML` phase.

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by wardpeet** [comment]
Hi @ShinyLeee,

Sadly we need to rebuild your javascript files, webpack doesn't give us a way to get the dependency graph and store it. That's why we always have to rerun the bundle. You could add a plugin like [SMP](https://www.npmjs.com/package/speed-measure-webpack-plugin) to see where webpack is slow.

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜
