### ISSUE TITLE
`gatsby serve` correctly serves on 9001 when 9000 is occupied but reports incorrectly

### ISSUE THREAD

**Issue by goleary** [gatsbyjs/gatsby#24518]
![image](https://user-images.githubusercontent.com/16123225/82961497-63f04400-9f72-11ea-8ea6-b2655baad00a.png)

## Description
when `gatsby serve` conflicts it says it's serving on the wrong port

### Steps to reproduce
run `gatsby serve` in on projects 
run again in another project
respond with `y` when asked if gatsby should use a different port

### Expected result
serve on port 9001 and say so

### Actual result
serves on port 9001 but says it's serving on port 9000

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 10.20.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.7.2
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.22.5 => 2.22.5 
    gatsby-image: ^2.4.5 => 2.4.5 
    gatsby-plugin-create-client-paths: ^2.3.2 => 2.3.2 
    gatsby-plugin-google-analytics: ^2.3.2 => 2.3.2 
    gatsby-plugin-manifest: ^2.4.8 => 2.4.8 
    gatsby-plugin-material-ui: ^2.1.8 => 2.1.8 
    gatsby-plugin-react-helmet: ^3.3.2 => 3.3.2 
    gatsby-plugin-sass: ^2.3.2 => 2.3.2 
    gatsby-plugin-sharp: ^2.6.8 => 2.6.8 
    gatsby-source-filesystem: ^2.3.7 => 2.3.7 
    gatsby-transformer-sharp: ^2.5.3 => 2.5.3

**Comment by thefrontendwizard** [comment]
I believe I can solve this one.

So I did some investigation here and I believe the cause of the problem is this line:
https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/commands/serve.ts#L154

This command relies on mutating the `port` variable, but the urls don't use them directly, using the `program.port` coming as an argument when the command is called, which is never mutated. My educated guess would be to change this line to use the mutated `port` instead.

I'd like to open a PR for this, but I need help on how to test this locally to confirm my hypothesis.
