### ISSUE TITLE
[Question] How to remove unused javascript in GatsbyJS?

### ISSUE THREAD

**Issue by daydream05** [gatsbyjs/gatsby#24586]
## Summary
The new Lighthouse added additional reccomendations such as
`Remove unused javascript`

How would I go about figuring out how to remove the unused javascript?

The report shows the path but they're all minified but I'm not sure how to get rid of them. (It looks a couple is Firebase)

I've deleted all unused imports but I still have a large chunk of unused js.

## Relevant information

Here's the [lighthouse](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fprtwd.com%2Fservices%2Fsla-3d-printing%2F&tab=mobile) report for [the page](https://prtwd.com/services/sla-3d-printing/) in question:

<img width="751" alt="Screen Shot 2020-05-28 at 5 14 29 PM" src="https://user-images.githubusercontent.com/11723413/83194695-0d683e80-a107-11ea-8a87-4d1b40e193d1.png">

Gatsby site has also some unused js
<img width="772" alt="Screen Shot 2020-05-28 at 5 18 08 PM" src="https://user-images.githubusercontent.com/11723413/83194855-50c2ad00-a107-11ea-88b2-1c1f70af55dc.png">

**Comment by LekoArts** [comment]
Thank you for opening this!

You'll want to use something like https://www.gatsbyjs.org/packages/gatsby-plugin-webpack-bundle-analyser-v2/ to see which packages are included in the individual pages so that you can either remove them (if not necessary) or lazy-load them.

Furthermore, it seems like Google changed their metrics. It makes sense to group this under this issue https://github.com/gatsbyjs/gatsby/issues/24332 - feel free to comment there once you figured out what your individual issue was. 

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by IwateKyle** [comment]
Yes, I'm new to Gatsby and was wondering the same thing.  I just built a tutorial and ran it thru Lighthouse and get pretty low scores.  The first observation was too much unused javascript.
