### ISSUE TITLE
Transparency of GitHub label usage

### ISSUE THREAD

**Issue by lannonbr** [gatsbyjs/gatsby#24588]
## Summary

It is convenient to have the various labels for the issue & PR queue, but something that I think has arisen is the lack of transparency to the community maintainers. Over the past few months, the labels have been going under some improvements, but that has not been clarified to the community and rather likely only to the people who work at Gatsby. Some labels do not have descriptions on what they are for other than the name of the label alone. Some have an asterisk at the end and it isn't mentioned what it is for.

There is the [How To Label an Issue](https://www.gatsbyjs.org/contributing/how-to-label-an-issue/) page in the docs so I think if these things were done more transparently, it could be put there.

**Comment by lannonbr** [comment]
As well, the color changes that happened today as well is a little unsettling, as I know the core team uses stuff other than just the GitHub UI for issues, but for everyone else, no longer having visual cues for specific issue types feels like a degregation of the UX

**Comment by danabrit** [comment]
@lannonbr Thank you for your message. You are right that we are going through the process of iterating on our first touch procedures to better serve our community and address issues and pull requests as quickly as possible. 

The plan is to also update our published first touch procedures so that the community can have as much transparency as possible into what those procedures are. This all takes time, of course, but know that we do hear you and we have the same goals in mind.

Color changes happened today, and are limited only to `topic` and `status` labels at this point. `topic` labels are now all blue (most issues and PRs should only need one), and most `status` labels are lime green, with the exception of the `status: blocked` (red) and `status: triage needed` (teal) labels. At almost 70 labels already, the distinction between one color over another is already degrading (we have several dupe and near-duped colors), and we will be adding even more topic labels to help better segment PRs and issues by topic.

I apologize for any confusion or concern this may have caused, and thank you for sharing your thoughts. Hopefully we will be done iterating on these changes in the next week or two and can share an all-inclusive description of our first touch procedures with the community, rather than a frequently-changing description of evolving processes.

**Comment by danabrit** [comment]
@lannonbr Oh! I forgot to address the asterisk: those are proposed/probationary labels that Core team members have created during First Touch that will be reviewed in team meetings at a later date. That is their only significance. :)
