### ISSUE TITLE
SPA on mobile and different routes on desktop

### ISSUE THREAD

**Issue by LauraBeatris** [gatsbyjs/gatsby#24674]
## 📖 Summary

Recently my team started a project of a landing page and we chose to use Gatsby in order to have good SEO. 
At a point in our project, the designers changed the mobile layouts to be a SPA, and the desktop ones still having different routes and pages. 

Refer to that example: 

<img width="962" alt="Screen Shot 2020-05-31 at 15 47 25" src="https://user-images.githubusercontent.com/48022589/83360301-a214ab80-a356-11ea-9e2f-cd195090db05.png">

<img width="274" alt="Screen Shot 2020-05-31 at 15 50 14" src="https://user-images.githubusercontent.com/48022589/83360298-9d4ff780-a356-11ea-900b-088921dfa657.png">

Since Gatsby creates pages in build time, we don't know if the environment is mobile or desktop, it's difficult to think in a way to deal with that behavior.

## 🐛 Workaround 

One quick way that our team thought to temporarily resolve that problem was to ``map`` between sections and hide than in desktop screens. 
And the biggest problem is: On the first load of the page the content takes almost a second to load because it's not static anymore. 

```
      <div>
        {
          breakpoints.md
            ? pages.map((page) => renderPage(page))
            : renderPage(selectedPageRef.current)
        }
      </div>
```

## 🚀 Goals 

I would like to discuss about a solution that will change the behavior of the pages in desktop and mobile without killing the SEO of the application.

**Comment by LekoArts** [comment]
Thank you for opening this!

> I would like to discuss about a solution that will change the behavior of the pages in desktop and mobile without killing the SEO of the application.

If you don't want the layout logic (you mentioned in your "workaround" section) you'll need to have separate pages. The normal index one for your desktop, a `/app` one for your SPA on mobile. Not really much you can do about it otherwise.

I personally would argue that there is no need to have a SPA and also your mobile page should just be the normal pages. If that's not possible, then yeah, you'll need to switch layouts on breakpoints.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
