### ISSUE TITLE
Jest unit test case will execute before executing actuall function so getting error in expect part

### ISSUE THREAD

**Issue by anjneeksharma** [gatsbyjs/gatsby#24689]
AddingFeedback will not execute fully by the time all the test cases will execute

```
it('addFeedback should create a feedback', done => {
request
.post('/graphql')
.send({
query: query,
operationName: 'AddingFeedback',
variables: {
input: mock
}
})
.expect(res => {
expect(res.body).not.toHaveProperty('errors');
expect(res.body).toHaveProperty('data');
expect(res.body.data).toHaveProperty('addFeedback');
expect(res.body.data.addFeedback).toHaveProperty('_id', mock._id);
expect(res.body.data.addFeedback).toHaveProperty('description', mock.description);
expect(res.body.data.addFeedback).toHaveProperty('ticketID', mock.ticketID);
expect(res.body.data.addFeedback).toHaveProperty('experience', mock.experience);
})
.end((err, res) => {
done(err);
});
});
```

**Comment by madalynrose** [comment]
Hi @anjneeksharma!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by anjneeksharma** [comment]
Hi @madalynrose   
Can you please elaborate  bit what is minimal reproduction and how it will help me in solving my issue.

**Comment by LekoArts** [comment]
Hi Anjnee,

this repository is about Gatsby as a project and not the right place for general React/programming questions. Please reach out to other communities like Reactiflux or Stack Overflow where you could ask your question. Thanks!
