### ISSUE TITLE
gatsby-source-drupal - pull only nodes and menus?

### ISSUE THREAD

**Issue by RoySegall** [gatsbyjs/gatsby#24682]
I've been through the issue queue and could not find any reference for that.

I have a Drupal installation that has the GrpahQL and JsonAPI module enabled. From what I saw, the `gatsby-source-drupal` plugin pulls from the JSON API only nodes, file, and menu entities. I have custom entities that appear in the JSON API endpoint but the grpahql explorer of my Gatsby ignores them.

Anything I'm missing? I also looked on the `filters` in plugin option but that did not do the trick as well.

**Comment by smthomas** [comment]
If the entities are showing up in the JSON API endpoint, it's likely a caching issue. I would clear the Drupal cache (required if you have unauthenticated users accessing the endpoint). I would also clear the Gatsby cache by running `gatsby clean`

I also noticed that you asked this in Drupal slack and appeared to get your question answered. Let me know if this issue can be closed now.

**Comment by RoySegall** [comment]
I switched to another way for getting the data from Drupal via the graphql source plugin, but I wanted to file this one since I could not find any reference to this one. I'll check this one in a couple of hours and let you know how it's ended.

Thanks!

**Comment by smthomas** [comment]
Great! Yes, you can use gatsby-source-graphql with Drupal's GraphQL module or you can use gatsby-source-drupal with Drupal's JSON:API module. You should be able to access custom entities with either approach.

**Comment by RoySegall** [comment]
Sorry for the late response but I checked it a bit more and unless I'm missing something in my setup none nodes entity are not displayed in the graphql explore (and probable won't be recognize by GatsbyJS as well).

On the right my jsonAPI results from local Drupal installation and on the left the graphql explorer:
![image](https://user-images.githubusercontent.com/1222368/83595891-e75df680-a56b-11ea-9f50-08e5439c539c.png)

Do I need to set up anything else for getting other entities rather than menu, file and node?

**Comment by smthomas** [comment]
Thanks for pointing this out! I'm doing some local testing to verify and if I get the same thing I will look at what it will take to make sure custom entities are included.

**Comment by smthomas** [comment]
I spent some time testing this locally and I was able to get other entities to show up correctly. A few things that need to be checked:

- The cache sometimes needs to be cleared. At first my new entities did not show up until I ran a `gatsby clean` and cleared the Drupal cache
- Permissions are important. I was not use a user/password in my gatsby-config.js and this made some entities not show up. For me, I was logged in locally so I could see all the entities at the /jsonapi endpoint. However, if I opened an incognito/private browsing window and went to the /jsonapi endpoint you might start seeing less data because of permissions. The solution is to make sure you use a user/password in your gatsby-config.js that has adequate permissions

I hope that helps. Let me know if you are still seeing the same issue.

**Comment by RoySegall** [comment]
@smthomas Permissions are correct. Since My drupal is only for gatsbyjs and some other microservices I did something like this:
```php
/**
 * Implements hook_entity_access().
 */
function open_pension_core_entity_access(\Drupal\Core\Entity\EntityInterface $entity, $operation, \Drupal\Core\Session\AccountInterface $account) {

  if ($operation != 'view') {
    // Not a view operation, skip this one.
    return;
  }

  if ($entity->getEntityType()->id() == 'user') {
    // Don't expose user via this hook.
    return;
  }

  // All entities, beside user, are allowed to be watched.
  return \Drupal\Core\Access\AccessResult::allowed();
}
```
