### ISSUE TITLE
[gatsby-plugin-react-helmet] and [gatsby-plugin-google-analytics] don't play well with Title changes

### ISSUE THREAD

**Issue by jbrantly** [gatsbyjs/gatsby#2478]
When using React Helmet and the Google Analytics plugin together, it seems that the route change handler causing GA to fire occurs before React Helmet has a chance to update the `<title>`. This results in GA data often having the *previous* page title for any given URL. 

This can be seen in the existing gatsbyjs.org site by navigating to the homepage, then to the "Community" page, and back and forth. The Community page has a different title than the other pages, and if you check the Network tab for the GA tracker you can see that the title is always the previous page.

**Comment by KyleAMathews** [comment]
Yeah that makes sense!

Perhaps we just wrap the GA update in a setTimeout to let react helmet finish before running?

How's that sound? Want to put together a PR?

**Comment by tylercrosse** [comment]
I haven't dug too deeply into this but using [nfl's react metrics](https://github.com/nfl/react-metrics) might be an option

**Comment by LeKoArts** [comment]
@KyleAMathews Would also be interested in a solution? So you propose to set a timeout here?
https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-google-analytics/src/gatsby-browser.js

**Comment by KyleAMathews** [comment]
@LeKoArts yeah exactly. Just set a timeout of 0 and that *should* be enough to make GA wait for the title update to finish.

**Comment by Chuloo** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues as many of them have already been resolved with the latest updates or explained in a previous issue.

Feel free to [open a new one](https://github.com/gatsbyjs/gatsby/issues/new/choose) if you still experience this problem or a similar one! 👍
