### ISSUE TITLE
Please clarify actions.createPage

### ISSUE THREAD

**Issue by dandv** [gatsbyjs/gatsby#24795]
This is the [createPage](https://www.gatsbyjs.org/docs/actions/#createPage) documentation for the `path` parameter:

> "Any valid URL. Must start with a forward slash"

That is inexact (URLs [must start with a non-empty scheme](https://tools.ietf.org/html/rfc3986#section-1.1.1), so this is a URL path, more precisely), but the more important reason I've filed this issue is to get an explanation for what exactly the purpose of `path` *is*, and *how it's used*. The documentation could be more helpful than only saying "must start with a forward slash".

`createPages` has been involved in long-running issues ([1](https://github.com/gatsbyjs/gatsby/issues/13645), [2](https://github.com/gatsbyjs/gatsby/issues/10742), [3](https://github.com/gatsbyjs/gatsby/issues/16250), [4](https://github.com/gatsbyjs/gatsby/issues/13965) etc.), but its documentation is extremely thin. Some points to expand on:
* how do `path` and `matchPath` relate?
* what is the role of `path` for client-only routes that need `matchPath`?
* why is it OK to [put junk in `path`](https://github.com/gatsbyjs/gatsby/issues/13645#issuecomment-487145323)?

**Comment by herecydev** [comment]
> how do path and matchPath relate?

Path is a slug that corresponds to a generated file, i.e. /foo will generate a /foo/index.html with the expectation that your host (CDN or otherwise) will serve that for users navigating to yoursite.com/foo.

Matchpath is an instruction to gatsby that before loading a page if it sees an entry in matchPath that matches that path that's been requested, it'll instead request the matchPath page. This is best explained with an example:

You've got a `/pay` page, with a matchPath of `/pay/*`. If a user clicks a link to `/pay/creditcard` Gatsby will know to render the `/pay` page instead.

So it's used for client-only routes.

> what is the role of path for client-only routes that need matchPath?

Because there still has to be a page to resolve for the matchPaths. A page needs to exist that handles the client routes.

>why is it OK to put junk in path?

I'm not sure what you mean by junk. Gatsby is not prescriptive about path names, it will generate precisely what was requested. It's up to your host how that gets served, but the default /<pagename>/index.html is a well recognized system.

**Comment by dandv** [comment]
Thanks for clarifying. By ["junk" I had linked to](https://github.com/gatsbyjs/gatsby/issues/13645#issuecomment-487145323), I was referring to @slorber's usage of `path: "/WeDontCareOfThisPathActually"` in the call to `createPage`.

Now I understand that `path: '/products/:id'` in my code,
```js
  actions.createPage({
    path: '/products/:id',  // <-- HERE
    component: resolve('./src/templates/product.tsx'),
    matchPath: '/products/:id/*',  // matches :id/ and :id/edit
  });
```

was misguided (it generated an actual `/products/:id/index.html` file), and I should've used just `/products`.

Other points that I think merits clarification:

1. (how) are the parameters provided to `matchPath` passed to components?

2. When is `matchPath` sufficient, and when should it be used in conjunction with `<Router>` statements on the client?

Some examples would help:

3. What would `matchPath: '/products/:id/*'` pass via props to the default-exported component defined in `product.tsx`? In my observations, `props.id`; this should be clearly documented.

4. How should `matchPath` be set to:
   * pass an id to the template
   * pass an id and whatever follows, e.g. `/123/edit`
   * still call the template on `/products/`

I tried the code below, but the template was not called for `/products/`, and Gatsby returned a blank page:
```js
  actions.createPage({
    path: '/products',
    component: resolve('./src/templates/product.tsx'),
    matchPath: '/products/:id/*',  // matches :id/ and :id/edit but not /products
  });
```

If I set `matchPath: '/products/*`, then the `Products` component defined in the template is called for `/products`, but the `id` is not passed from `products/123`.

```ts
export default function Product({ id }: { id: string }): ReactElement { ... }
```

**Comment by herecydev** [comment]
Matchpath only affects what page gatsby will load, as far as I know it only support wildcards like `/products/*`. Any parameters belong to the page and whatever data was injected to the page, so that distinction needs to be understood. Matchpath doesn't "have any parameters"

It's then up to you as the developer to decide what you do when that page is loaded. It's not mandatory to use a router but it makes no sense not to. https://reach.tech/router answers a lot of the questions about how to structure the routes to pass parameters

**Comment by marcysutton** [comment]
Hey, thanks for the input here. It would certainly help to beef up the docs where information is limited or unclear, but I also want to mention @blainekasten's RFC PR for Unified Routes. The work proposed should hopefully improve the experience of working with pages, so your feedback would be welcome: https://github.com/gatsbyjs/gatsby/pull/24463
