### ISSUE TITLE
Relative links in repo and site

### ISSUE THREAD

**Issue by CollierCZ** [gatsbyjs/gatsby#24812]
Hi. I haven't found an answer to this, so I'm hoping someone can help me with it.

I'm creating a documentation site that pulls docs from various repos. We chose Gatsby partly because of the ability to source easily.

But we'd like relative links to be able to work both in the repo itself (for devs browsing the code) and in the site. Currently, it doesn't seem to do that.

We're using MDX and passing our own link components using the `navigate` function from Gatsby, if that matters.

An example:
- [Link in a repo](https://github.com/Rocketseat/gatsby-starter-rocket-docs/blob/master/src/docs/getting-started.mdx) (at the bottom of the file)
- [Link on a page](https://rocketdocs.netlify.app/getting-started)

The link works on the page but not in the repo.

Any advice on how to resolve this? Thanks in advance.

**Comment by sidharthachatterjee** [comment]
Hey @CollierCZ 

Interesting question! Removing the preceding `/` in the relative link makes it route correctly on GitHub (and continues working in Gatsby)

However, as illustrated in https://github.com/sidharthachatterjee/gatsby-starter-rocket-docs/tree/patch-1, GitHub renders a 404 page without the `.mdx` extension in the link. That's something that we unfortunately can't do anything about. 

Since this isn't related to Gatsby, I'll close ahead and close this. Thanks for opening this and have a lovely day!
