### ISSUE TITLE
Using gatsby-remark-images & gatsby-remark-images-contentful together makes images fade out (opacity 0)

### ISSUE THREAD

**Issue by labithiotis** [gatsbyjs/gatsby#24830]
## Description

When both remark transforms are used together inside of `gatsby-transformer-remark` the contentful markdown images fade out to opacity 0. 

### Steps to reproduce

If I don't include the `gatsby-remark-images` plugin the contentful blog images work as expected, it only happens if I have both plugins defined.

*gatsby-config.js*
```
{
      resolve: 'gatsby-transformer-remark',
      options: {
        plugins: [
          {
            resolve: 'gatsby-remark-images',
            options: {
              maxWidth: 800,
              backgroundColor: 'var(--color-background)',
            },
          },
          {
            resolve: 'gatsby-remark-images-contentful',
            options: {
              maxWidth: 800,
              backgroundColor: 'var(--color-background)',
            },
          },
        ],
      },
}
```

<img width="1181" alt="Screenshot 2020-06-06 at 7 33 43 am" src="https://user-images.githubusercontent.com/784306/83936939-d827b480-a7c8-11ea-9c94-fedba3f44e77.png">

### Expected result

Images from contentful markdown should not fade out.

**Comment by danabrit** [comment]
Hi @labithiotis !

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by labithiotis** [comment]
https://github.com/labithiotis/gatsby-bug example repo where images are opacity 0.

http://localhost:8000/blog/automate-with-webhooks

**Comment by labithiotis** [comment]
@danabrit Example repo: https://github.com/labithiotis/gatsby-bug where images are opacity 0.
Start project and goto this blog page: http://localhost:8000/blog/automate-with-webhooks

**Comment by ascorbic** [comment]
I've assigned @pieh , but I'm unsure if this is a Contentful or remark issue. Maybe @axe312ger could take a look too?

**Comment by pieh** [comment]
Ok, the problem here is that initially `gatsby-remark-images-contentful` was almost the same as `gatsby-remark-images` and so used same class names for image markup. Later on `gatsby-remark-images` had refactors, but class names stayed. I think to fix this we just need to make sure that `gatsby-remark-images-contentful` is using different class names than `gatsby-remark-images` to not cause any conflicts

**Comment by pieh** [comment]
@labithiotis would you be willing to submit PR that change class names in https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-images-contentful/src/index.js so they don't conflict with ones in `gatsby-remark-images` ( https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-images/src/constants.js#L15-L17 )?

(as a note, changing class names is a breaking change so we will need major version bump, but this is not a blocker, and we should just do it)

**Comment by d1che** [comment]
I would love to help with this issue but there's something I don't understand yet. Why would one want to use both `gatsby-remark-images` and `gatsby-remark-images-contentful` in conjunction? I'm asking this because I encountered issue [#16516](https://github.com/gatsbyjs/gatsby/issues/16516#issue-479287087) also when using `gatsby-remark-images-contentful`. PR [#17154](https://github.com/gatsbyjs/gatsby/pull/17154#issue-311986069) fixed this but only for `gatsty-remark-images`. Wouldn't fixing this issue for `gatsby-remark-images-contentful` make the use of both plugins unnecessary?

**Comment by LekoArts** [comment]
Hi!

I'm closing this as a stale issue as in the meantime Gatsby 4 and related packages were released. You can check our [Framework Version Support Page](https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/) to see which versions currently receive active support. If this is a feature request, please [create a discussion](https://github.com/gatsbyjs/gatsby/discussions/categories/ideas-feature-requests) as we moved feature requests from issues to GitHub Discussions.

Please try the mentioned issue on the latest version (using the `next` tag) and if you still see this problem, open a new bug report. It **must** include a [minimal reproduction](https://gatsby.dev/reproduction).

Thanks!
