### ISSUE TITLE
Extending html.js with vendor files fails when loading nested routes

### ISSUE THREAD

**Issue by ilrein** [gatsbyjs/gatsby#24879]
## Description

The vendor files are placed in /public, and they work perfectly fine in all top level routes. The issue is when using a nested route, suddenly the app throws an error: `Uncaught SyntaxError: Unexpected token '<'`

### Steps to reproduce

1) Add a JS file to /public/company/random-file.js
2) Extend html.js (in the head tag) with:

<script type="text/javascript" src="company/random-file.js"></script>

### Expected result

There should be no errors loading this JS file in all routes

### Actual result

In a _nested_ route (ie '/dashboard/orders') all vendor files are unable to be loaded: `Uncaught SyntaxError: Unexpected token '<'`

Top level routes work fine (ie '/dashboard').

### Environment

  System:
    OS: macOS 10.15.5
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 3.0.2 - /usr/local/bin/fish
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 83.0.4103.97
    Safari: 13.1.1
  npmPackages:
    gatsby: ^2.22.15 => 2.22.15 
    gatsby-image: ^2.4.5 => 2.4.5 
    gatsby-plugin-load-script: ^1.1.0 => 1.1.0 
    gatsby-plugin-manifest: ^2.4.9 => 2.4.9 
    gatsby-plugin-offline: ^3.2.7 => 3.2.7 
    gatsby-plugin-react-helmet: ^3.3.2 => 3.3.2 
    gatsby-plugin-sharp: ^2.6.9 => 2.6.9 
    gatsby-source-filesystem: ^2.3.8 => 2.3.8 
    gatsby-transformer-sharp: ^2.5.3 => 2.5.3 
  npmGlobalPackages:
    gatsby-cli: 2.12.44

**Comment by danabrit** [comment]
Hi @ilrein !

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by ilrein** [comment]
I was able to overcome this issue with:

```
{
      resolve: 'gatsby-plugin-load-script',
      options: {
        src: '/apiGateway-js-sdk/lib/axios/dist/axios.standalone.js',
      },
    },
```
