### ISSUE TITLE
Featured Showcase sites no longer using Gatsby

### ISSUE THREAD

**Issue by lannonbr** [gatsbyjs/gatsby#24975]
## Summary

It is shown on the front page that Both Nike and Snapchat are "trusted users" of Gatsby.

![Screen Shot 2020-06-13 at 10 17 54 AM](https://user-images.githubusercontent.com/3685876/84571118-55ba6a00-ad5f-11ea-80d8-c6532eb7e3b0.png)

That said, Snapchat switched their Snap Kit site over to NextJS and Nike's Just Do It page no longer exists. I would normally just submit a PR to remove it from the showcase, but having their logos on the front page feels disingenuous as they are moving to other platforms / took down the sites that used Gatsby.

Even further, other than looking at a wall of images and then following along to possible featured sites in a showcase, how can you tell a company "trusts" Gatsby. What does "trusted" even mean in this context? What should be done when a site is found to be taken down or migrate to another framework / technology?

**Comment by gillkyle** [comment]
Nike is still using Gatsby here: https://engineering.nike.com/ the site showcase isn't holistically indicative of Gatsby usage, there are a variety of ways we can gauge Gatsby usage outside of developers from companies submitting their sites to the showcase. The httparchive is one, customers of Gatsby Cloud, etc. 

I think "trusts" in this case can mean many things because many use Gatsby differently, for some it's internal docs or design systems, for others it's their whole suite of user facing web properties. Trusts does imply usage here though so Snap perhaps ought to be removed.
