### ISSUE TITLE
How to have a multi-language site based on different domains?

### ISSUE THREAD

**Issue by adrianopulz** [gatsbyjs/gatsby#24998]
I have different domains like .com, .de, .com.br and I would like to have a static version of each language, and use it for the different domains we have. We have a source API link to each language, for example, en/api/ | pt-br/api | de/api. The best option would be to build a static version of each language, which could be an environment parameter on the build or something like that.

How is the best way to deal with this requirement? Do we have a good way to have something like this as the build result? When each folder is a build of each API language source?

public/
|-en/
|-pt-br/
|-de/

**Comment by LekoArts** [comment]
Thank you for opening this!

> The best option would be to build a static version of each language, which could be an environment parameter on the build or something like that

An environment variable is perfectly fine as this could specify your API endpoint and other values that differ for each version.

> How is the best way to deal with this requirement? Do we have a good way to have something like this as the build result? When each folder is a build of each API language source?
> public/
> |-en/
> |-pt-br/
> |-de/

What you're describing is a single build output. If you want it in a single `public` folder you need to create all the pages in a singular Gatsby app.

If you want to go forward with your environment variable solution you'd have your Gatsby app and then e.g. run the `gatsby build` command with the env vars in your CI/CD environment. Then you need to deploy each build artifact to its own folder so that you get something like:

en/
| public/
pt-br/
| public/
de/
| public/

Then you can serve the different versions of the website from these folders.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by adrianopulz** [comment]
Thank you @LekoArts! The environment variable will work fine. I'm using a Drupal backend with the JSON API module. For gatsby, I'm using the **gatsby-source-drupal** plugin.

On my Drupal site I have something like:
http://drupal.local/jsonapi
http://drupal.local/pt-br/jsonapi
http://drupal.local/de/jsonapi

I tried to use this code below for the Drupal plugin options, fixing on PT-BR language for tests, but it always returns just the English data. When I'm exploring the /___graphql link, I can access only the English information. Do you know anything about it?

`{
      resolve: `gatsby-source-drupal`,
      options: {
        baseUrl: `http://drupal.local/pt-br`,
        apiBase: `jsonapi`,
      },
}`

**Comment by adrianopulz** [comment]
It looks like a JSON API issue: https://www.drupal.org/project/drupal/issues/3056602

**Comment by LekoArts** [comment]
Yeah, unfortunately I can't help with Drupal :/ Hope you resolve it though!

**Comment by adrianopulz** [comment]
Yes, no problem.
Thanks for your help with the Gatsby issue.
