### ISSUE TITLE
HTML generation performance degradation when moving query from template to node

### ISSUE THREAD

**Issue by kdichev** [gatsbyjs/gatsby#25051]
# Summary

We have several thousands of pages(15k) and 5-6 page templates we use to source with gatsby-source-graphql and render.

We were fetching data for main menu, footer and some global settings on every template (the data is the same across templates which adds a bit of time for our fetching step and we have issues with limits and query complexity.

I thought to move the main menu, footer queries to `gatsby-node`. That worked wonders and manage to decrease the the overall fetching time for the app with about 10-15%.

The data right now is passed in `pageContext` and this introduced html generation speeds to decrease by half. I know that `pageContext` is not the best place to put large set of data and then wrote the data to file and imported where I needed it (wrapRootElement). 
This change worked but did not bring be back to html gen speeds prior the template changes.

I was wondering as to why this would introduce html gen pef degradation and if there is another way to do it in order to be back at default times we usually expect. (sourceNodes and then query again from templates?)

**Comment by vladar** [comment]
Can you share console output `before` and `after` moving to pageContext? This way we will see exactly the times taken for each step.

There is a known issue with page context performance (with existing workaround): https://www.gatsbyjs.org/docs/scaling-issues/#switch-off-type-inference-for-sitepagecontext 

But it doesn't sound like your situation because it would have slowed down `update schema` step, not html generation.

But the best way to help you would be to get access to your project and investigate. You can share it privately via vladimir@gatsbyjs.com then I can take a closer look.

BTW, we are working on a new tool that you could use in place of `gatsby-source-graphql`. It can be beneficial for big sites. Basically it will fetch the data into gatsby store once (during `sourceNodes` step as other source plugins do) instead of running queries against remote GraphQL schema for each page. Here is a relevant issue: #15906 I will post updates there when we have something to share.

**Comment by kdichev** [comment]
before

success run queries - 324.731s - 2375/2375 7.31/s
success Building static HTML for pages - 249.307s - 2365/2365 9.49/s

after

success run queries - 245.208s - 2374/2374 9.68/s
success Building static HTML for pages - 512.757s - 2364/2364 4.61/s

at some point i was able to get to this:

success run queries - 249.033s - 2374/2374 9.53/s
success Building static HTML for pages - 253.966s - 2364/2364 9.31/s

but I am investigating further as I think this was before I cleaned up the PR.

I don't know if is related but the queries I am doing now in `createPages`  were inside of the page queries as fragments. I did not want to duplicate fragments from node to the gatsby app so I used a graphql helper so I can import certain fragments to gatsby node.

**Comment by kdichev** [comment]
@vladar I am closing this issue as it seems not to be directly connected to Gatsby per say.
We have bumped up our build agent hardware (cpu cores) and we are experiencing extreme speeds now.
Our rendering now is 2000% faster, I guess this was the issue here.

ps. for anyone landing here if you have ssr perf regressions you should probably consider using gatsby cloud or bumping up your build agent CPU to 8+ cores
