### ISSUE TITLE
Umbrella Issue: MDX app bundle bloating and global scope problems

### ISSUE THREAD

**Issue by johno** [gatsbyjs/gatsby#25069]
MDX currently shoehorns imports into the app bundle, and adds all imports to the global scope (causing imports to need to be namespaced to avoid clashing). When the new webpack APIs land we should leverage them to improve some of the rough edges around gatsby-plugin-mdx.

This is also related to how `gatsby-plugin-feed` works with MDX because it requires more complex bundling and rendering than its remark counterpart.

## Related issues reporting bugs

- https://github.com/gatsbyjs/gatsby/issues/15881
- https://github.com/gatsbyjs/gatsby/issues/24321
- https://github.com/gatsbyjs/gatsby/issues/17119
- https://github.com/gatsbyjs/gatsby/issues/25407
- #27416

## Related PRs for APIs

- https://github.com/gatsbyjs/gatsby/pull/25057
- https://github.com/gatsbyjs/gatsby/pull/24903

**Comment by janosh** [comment]
> When the new webpack APIs land we should leverage them to improve some of the rough edges around gatsby-plugin-mdx.

Sounds great! Is this a `gatsby-plugin-mdx` only matter? Or is this tied to the MDX 2.0 release?

**Comment by pieh** [comment]
> Sounds great! Really excited for any and all improvements to MDX! Is this a `gatsby-plugin-mdx` only matter? 

API is generic and other plugins (or sites directly) can use it (if there is need for it) - there are slightly more details / context / discussion about this in https://github.com/gatsbyjs/gatsby/issues/18689 . But this issue is about `gatsby-plugin-mdx` specific `app` bundle issue (we still will need to integrate those new APIs in `gatsby-plugin-mdx` when API lands) and also `html` field (`gatsby-plugin-feed`) 

> Or is this tied to the MDX 2.0 release?

Not tied to MDX 2.0 functionally. We might bundle those if both MDX 2.0 and webpack api changes will require us to make breaking changes in plugin to do 1 major release instead of 2 in short period of times.

**Comment by mohsenkhanpour** [comment]
There is an issue when `react` and  `react-dom` are upgraded to "16.14.0" or "17.0.0-rc".

Steps to reproduce:
1. Clone the default MDX starter:
`gatsby new my-site https://github.com/ChristopherBiscardi/gatsby-starter-mdx-basic`

2. Upgrade `react` and  `react-dom` to "16.13.1" and `yarn build`, it works.
3. Upgrade `react` and  `react-dom` to "16.14.0" and `yarn build`, it doesn't work.

The build fails with the following error:
```js
/src/pages/page-2.mdx: pragma and pragmaFrag cannot be set when runtime is automatic.
> 1 | import * as React from 'react'
    | ^
  2 |   /* @jsx mdx */
  3 | import { mdx } from '@mdx-js/react';
  4 | /* @jsx mdx */

File: src/pages/page-2.mdx
```

This only effects mdx pages in `src/pages/`, mdx pages created with templates seem to be working fine.
