### ISSUE TITLE
Proposal: allow org members to delete selected outdated bot messages

### ISSUE THREAD

**Issue by dandv** [gatsbyjs/gatsby#25074]
# Current situation

Certain popular issues in this repo with a long history, also have many comments from @gatsbot or @github-actions marking the issue as stale, followed shortly by a community member replying the issue was not stale and providing a new use case, or updated debugging information.

For a user new to the discussion, seeing the first few bot messages provides information about the issue stale-marking and closing process. Seeing the subsequent messages does not really provide anything new. Seeing the last bot messages shows the current status of the issue.

![image](https://user-images.githubusercontent.com/33569/84937278-579e6900-b090-11ea-9f28-75c0e796f353.png)

# Motivation

The repetitive bot comments between and excluding the first and last, may be cluttering the comments from humans more than adding to the discussion.

This proposal aims to allow org members to clean up these comments, *except* for the first and last message of the same type (stale, close). The timeline item labels will still remain, both next to the first and last message, and instead of the cleaned up repetitive messages in between:

![image](https://user-images.githubusercontent.com/33569/84936675-7a7c4d80-b08f-11ea-857c-234ab0999c64.png)

The bots will continue to function as before, and people will still be informed of the bots' actions.

**Comment by KyleAMathews** [comment]
Another option as well is the bot could delete previous rounds of marking issues as stale

**Comment by janson** [comment]
Yup, thanks @dandv for the context and excellent use-case. As Kyle mentioned we could automate part of it instead of, or in addition to, adjusted GH perms. I'll dig in further and keep ya'll updated.

**Comment by dandv** [comment]
@KyleAMathews, @janson - until the bot gets updates, does your agreement with the spirit of this issue mean that it would be OK for volunteers to manually delete bot comments as specified in the proposal?

**Comment by muescha** [comment]
similar: 
- #26489 `Bug: github bot not remove the "stale" label on new comment, adding label "not stale" is restricted`

**Comment by LekoArts** [comment]
Two major changes occurred since the creation of this issue.

1) We had to change our GitHub organization model/permissions and thus non-employees can no longer delete comments
2) We're in the process of moving questions & feature requests over to [Discussions](https://github.com/gatsbyjs/gatsby/discussions). The bot won't be active there (as nothing can be closed anyways)

In most cases the behavior/problem that is described here occurred on long-standing feature requests or questions which was now resolved by moving it to a more appropriate place. I think for bug reports we should still keep the behavior as often times a reproduction is missing and thus the issue isn't actionable really.

Therefore I'll close this one. Sidenote: We also increased the time to 60 days for issues being marked stale.
