### ISSUE TITLE
page-data.json is cached?

### ISSUE THREAD

**Issue by huaying** [gatsbyjs/gatsby#25088]
## Summary

Not sure if it's a bug or I just understand it wrong.
I guess `page-data.json` shouldn't be cached, right? 

## Relevant information

I found the page-data.json has been added a preload mechanism and it results in getting data from prefetch cache.

![image](https://user-images.githubusercontent.com/3991678/84988377-7bd37600-b174-11ea-8b08-c69fc5fb7708.png)

![image](https://user-images.githubusercontent.com/3991678/84988476-a1f91600-b174-11ea-85fe-585111b3fd82.png)

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by ascorbic** [comment]
Hi. What you're seeing there is that it is first pre-fetched because of the links in the head, so when it is loaded via XHR when the page is hydrated, the XHR loads it from the prefetch cache. This isn't a cache that's being persisted: it's the same pageload, it's just that it was pre-fetched a second or so before meaning the load is instant. 

I'm going to close this, but if I've misunderstood you or you have more questions about this then please do re-open.
