### ISSUE TITLE
[www] Highlight active page in nav. RFC

### ISSUE THREAD

**Issue by markmichon** [gatsbyjs/gatsby#2516]
Currently the nav doesn't display the active page, which sometimes causes the "where am I?" cognitive load to increase.

Quick and dirty mocked-up-in-chrome examples:
Currently:
![desktop-inactive](https://user-images.githubusercontent.com/1649672/31730644-8ea7002c-b400-11e7-91e9-c876b3873699.png)

Active desktop state:
![desktop-active](https://user-images.githubusercontent.com/1649672/31730669-a25f7fe0-b400-11e7-9660-d5012f35b266.png)

Active mobile state:
![mobile-active](https://user-images.githubusercontent.com/1649672/31731472-29b80ea6-b403-11e7-88a8-340839ad9182.png)

That's with the middle purple. With the harsher Gatsby purple it looks like:
![desktop-alternate](https://user-images.githubusercontent.com/1649672/31731516-4fdeddda-b403-11e7-8e6d-294a5efcbf81.png)
Only issue with the harsher version is it would require the mobile icons to be tweaked for contrast.

Alternately, we could adapt some ideas from the system's iconography, or incorporate some of the sharp lines that the homepage uses.

Thoughts? Ideas? Concerns?

**Comment by chrisgeary92** [comment]
Agreed. I often have this confusion between the docs & tutorial sections.

What do you think about a solid underline, as an accent colour instead of a full background colour on the nav-items? The site is so white/clean, it seems a little overpowering with the full background. Also helps to not interfere with the icons.

![image](https://user-images.githubusercontent.com/3949335/31733101-8c843850-b432-11e7-88ef-e344ad17f40b.png)

![screen shot 2017-10-18 at 18 32 41](https://user-images.githubusercontent.com/3949335/31733178-c92ed7b0-b432-11e7-99eb-186dd3a862b9.png)

**Comment by markmichon** [comment]
I definitely prefer that on mobile, but on desktop it looks really out of place with the sidebar (particularly on tutorial)
<img width="478" alt="underline-tuts-desktop" src="https://user-images.githubusercontent.com/1649672/31733537-edba65f0-b409-11e7-9bd4-9a6cd89e04d1.png">

**Comment by chrisgeary92** [comment]
😂  Oh yeah, didn't think that one through!

**Comment by markmichon** [comment]
Perhaps bold desktop, underline mobile. I'm not sure it stands out enough
<img width="687" alt="screen shot 2017-10-18 at 1 50 49 pm" src="https://user-images.githubusercontent.com/1649672/31734091-9679ac40-b40b-11e7-9958-9c8f4385e033.png">

**Comment by KyleAMathews** [comment]
I like this idea!

I like the idea of a more subtle treatment on mobile. Perhaps underline on mobile and the original highlight on desktop?

@fk thoughts?

**Comment by fk** [comment]
Ah yes, forgot about this yesterday … :1st_place_medal: 🎉 

I totally agree with the RFC 👍, also I feel the "how to" pain – the observations by @markmichon and @chrisgeary92 are spot-on. Didn't tackle it during my last major edits because of exactly what @markmichon describes regarding sidebar/bottom border. Top border felt weird, too IIRC.

Only thing I can add is a [pill-like](https://getbootstrap.com/docs/4.0/components/navs/#pills) active (hover?) state I guess 🙄 … ~

![image](https://user-images.githubusercontent.com/21834/31780342-b9d06aea-b4f5-11e7-92b6-dc4194c01803.png)

Maybe we should try "overline" for mobile?

**Comment by markmichon** [comment]
Initial reaction to the pill is good, I just wonder if the rounded corners don't clash too much with the hard lines in the rest of the site's design elements.

I tired "overline" on mobile just now and it feels so out of place. I haven't seen an overline that felt natural anywhere though. What about a pop of color when active, and scale back to one of the lighter purples (or a grey) when not active. This would require the svg setup change from base64 images to inline so we can modify them.
<img width="431" alt="screen shot 2017-10-19 at 12 05 09 pm" src="https://user-images.githubusercontent.com/1649672/31781184-cf879d66-b4c5-11e7-8ed2-e91e9dbe1d17.png">
(excuse the gross alignments and sizing)

**Comment by fk** [comment]
Hey, happy Docs icon! 🤗 😃 

> (edit: now that I've looked at the icons in my image below, the pills edges don't seem so out of place lol)

Yeah things have been growing slightly uncontrolled – explanatory diagram, icons, blog cards … it's a mess yo! Will add issues today for the things I have in mind.

I like the mock you posted a lot @markmichon, should have done so in the first place!
Also makes me want to check contrast ratios ;)

@KyleAMathews Should we keep the original icon SVGs in the repo somewhere?

**Comment by Chuloo** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues as many of them have already been resolved with the latest updates or explained in a previous issue.

Feel free to [open a new one](https://github.com/gatsbyjs/gatsby/issues/new/choose) if you still experience this problem or a similar one! 👍

**Comment by fk** [comment]
FWIW :-/ … we're actually working on this (again). Took only almost a year 🙄🙏
