### ISSUE TITLE
SEO effect of populating data with useStaticQuery

### ISSUE THREAD

**Issue by kerematam** [gatsbyjs/gatsby#25174]
Afaik, pre-rendered HTML contents where text contents already populated inside DOM have better SEO performance as Google bots do not need to mess with javascript to read data inside the page.

As I saw in the documentation of Gatsby, data can be populated via useStaticQuery where data loaded with XHR requests and injected with javascript to the page which requires another render. I wonder how efficient it is in terms of SEO performance.

Also if this query approach has a negative effect on SEO performance, is there any built-in way in Gatsby to pre-render those contents?

**Comment by jzabala** [comment]
When you use `useStaticQuery` Gatsby, at built-time, is going to parse and execute the queries, and inject that data. So, no XHR requests happening in the front-end. This is good for SEO since like you said, the data will already be there in the html.

https://www.gatsbyjs.org/blog/2019-02-20-introducing-use-static-query/

**Comment by kerematam** [comment]
@jzabala Thank you for quick response. Beside this, how about internationalization, pre-render option exist for languages too?

**Comment by herecydev** [comment]
@kerematam where did you read the following?

> As I saw in the documentation of Gatsby, data can be populated via useStaticQuery where data loaded with XHR requests

Internationalization doesn't exists out of the box but you can find a sample [here](https://github.com/gatsbyjs/gatsby/tree/master/examples/using-i18n) or use a plugin like I've made: https://github.com/herecydev/gatsby-plugin-internationalization

**Comment by kerematam** [comment]
@herecydev i didn't read it somewhere. i was working on one gatsby project and as I saw some xhr request flying around. I assumed that they were data from staticQuery. (which apparently not)

![image](https://user-images.githubusercontent.com/5495509/85233659-a04b7e80-b410-11ea-973c-20c2ffff47df.png)

Thank you for the sample.

**Comment by herecydev** [comment]
The html is rendered but will need to request those files in order to hydrate the page correctly, which you can read about here: https://www.gatsbyjs.org/docs/react-hydration/

Rest assured that Gatsby is really strong in all areas: https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fgatsby-starter-blog-demo.netlify.app%2F

**Comment by kerematam** [comment]
@herecydev thank you for the contents.

**Comment by herecydev** [comment]
No problem, I'm going to close this but feel free to create another issue if you have any further questions
