### ISSUE TITLE
Could give a tutorial for integrating gatsby and redwood

### ISSUE THREAD

**Issue by zwl1619** [gatsbyjs/gatsby#25294]
There is an issue of redwood: https://github.com/redwoodjs/redwood/issues/217

I want to use Gatsby for the static parts of my site and Redwood for the dynamic parts. The auth system of redwood relies on third parties at present.  I want to try the [authentication service](https://www.gatsbyjs.org/tutorial/authentication-tutorial) of gatsby. 

Could give a tutorial for integrating gatsby and redwood?

**Comment by pieh** [comment]
Hi @zwl1619!

Side note first - Gatsby itself also doesn't have authentication system built-in - in practice it will also rely on 3rd party services - the tutorial you linked is using just some hardcoded values, but in reality you would want to use external service for authentication/authorization.

As for using Gatsby and "something else" together - this will not be `redwoodjs` specific because I don't know much about it, but I can at least make few notes about general things:

a) You want part of your frontend to NOT use Gatsby:

This is complex case, because most guides assume your app/site is "homogeneous" (and this is not just Gatsby thing). And this is for good reason - joining 2 different systems is pretty delicate and may require custom server/hosting rewrite rules, server/hosting caching configuration (that hopefully wouldn't conflicts between Gatsby and `redwoodjs`, but this might just not be possible) to ensure server/hosting is configured in a way that frontend apps need it to. Gatsby does have plugins that configure hosting (like `gatsby-plugin-netlify`), but those are not really prepared for scenarios like that and you would need custom solutions for those things.

If you want to go this route, probably better solution is to split that would save you a lot of headaches would be to split the app/site into multiple (sub)domains ( example.com, app.example.com) or go with option b)

b) All of frontend use Gatsby, but parts of it are dynamic routes that talk to other services (potentially `redwoodjs` data layer if you can use it outside of `redwoodjs` frontend):

This is mostly expanded on https://www.gatsbyjs.org/docs/client-only-routes-and-user-authentication/ so I will just leave this link. Because Gatsby produces static assets only, this would be client-side rendered content and in cases like that you can `fetch` data you need in the browser (in `useEffect` or something like that) and render based on that.
