### ISSUE TITLE
bug: theme template mirroring lossing query data

### ISSUE THREAD

**Issue by sbardian** [gatsbyjs/gatsby#25313]
## Description

As of 6a82da8b8b3aca106f0f1b14ab11d2d087827df1 

Situation:   A theme with a page template including a page query.  If using the theme and mirroring the template, the query `data` is no longer forwarded to the mirror as a prop.  Query appears to be dropped when viewing `gatsby repl`->`components`.  

Guessing this might be a miss match from the components store to the new `page.component` returned here: 
https://github.com/gatsbyjs/gatsby/blob/d41526fe6e220cfcd5debc08d4dbb67df7e86aba/packages/gatsby/src/redux/actions/public.js#L265

### Steps to reproduce

Use a theme with a page template that includes a page query.  Mirror the template and attempt to access/use the `data` prop returned from the query.  Worked prior to 6a82da8b8b3aca106f0f1b14ab11d2d087827df1

### Expected result

query `data` prop should be forwared to the mirrored page template.  

### Actual result

`data` prop is not forwarded/matched to mirror.  `data` is undefined. 

### Environment

Functionality worked prior to gatsby@2.18.1.  Breaking change appears to be here: 6a82da8b8b3aca106f0f1b14ab11d2d087827df1

**Comment by pieh** [comment]
For clarification - shadowed template file doesn't include any query in this example?

If that's the case - then current is behaviour desired (and previous was a bug) - otherwise there would be no option to remove page query when shadowing. So this is case of "It's a feature, not a bug".

However I do understand that this makes it harder to adjust component without changing query - while Gatsby itself doesn't have a way to do this, the solution here is for themes to structure templates like in https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-theme-blog-core/src/templates/post-query.js where template files do have query, but actual template component is imported (no direct react code in the template file) - this means that users can separately shadow query (if they want to) and separately shadow component

**Comment by sbardian** [comment]
@pieh this might be for the best.  Looking into this more, I don't see a way to preserve the query before the shadowing takes place.  Since it is being shadowed in `createPages`, the original template page has not been created, and so the page has not had the page query extracted/saved to the store/etc.   

That said, I am surprised that I was "shadowing/mirroring" (functionally at least) my template with a page query successfully before this commit updating of the `page.component`.  Shadowing/mirroring the template file worked fine, and with no change to the `page.component` prop I had the query `data` prop as expected.  Did this update fix some other issue I just had not run into, and my with my limited need/mirroring I wasn't affected by it, or..?

**Comment by sbardian** [comment]
> For clarification - shadowed template file doesn't include any query in this example?

@pieh Sorry, I'm not sure what you are asking here, I have seen examples in the documentation of template files _having_ page queries in them (can dig some up if it's helpful), but I am not sure if _shadowing_ them has been a part of that documentation.  

This is something I had going in a theme I was working on awhile back, and just picked it back up and noticed the breaking change (breaking for me and what I was doing anyway).

**Comment by sbardian** [comment]
> If that's the case - then current is behaviour desired (and previous was a bug) - otherwise there would be no option to remove page query when shadowing. So this is case of "It's a feature, not a bug".

I see your point here.  I guess lets consider this me taking advantage of a bug, and it has been fixed 👍 

Thanks for taking the time to address/explain this to me 🥇
