### ISSUE TITLE
my surge is not deploying

### ISSUE THREAD

**Issue by zohaibulhassan** [gatsbyjs/gatsby#25335]
## Description

Describe the issue that you're seeing.

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

How to Make a Minimal Reproduction: https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/

### Expected result

What should happen?

### Actual result

What happened.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by Escavalier** [comment]
I do not get the bug here?

**Comment by zohaibulhassan** [comment]
I am creating the dynamic application using surge and git,if update a code than  push the code to git its remotely change at the surge,but my surge is not deploying on my code

**Comment by blainekasten** [comment]
Are you using gatsby cloud?

**Comment by blainekasten** [comment]
I'm going to close this issue because it is severely lacking information and the author did not fill in the issue template as we require. If this is a gatsby cloud issue, please email support@gatsbyjs.com and include as much information as possible. 

If you are not using Gatsby Cloud, we need more information.
