### ISSUE TITLE
error-map.js 11328 shows undefined

### ISSUE THREAD

**Issue by hcygit** [gatsbyjs/gatsby#25462]
## Description

The output variable context.fileName in "11328" should use context.component instead of context.fileName if someone have one file like this:
```
import A from './a'
import B from './b'
export { A, B }
```
In spite of no any valid component importing this file, this method is totally no problem while running in development but result in an error exception while building production.

### Steps to reproduce

gatsby develop -> OK
gatsby build -> ERROR

### Expected result

A page component must export a React component for it to be valid. Please make sure this file exports a React component:
undefined

### Actual result

A page component must export a React component for it to be valid. Please make sure this file exports a React component:
{actual file path} (context.component)

### Environment
macos

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by hcygit** [comment]
> Hi!
> 
> Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction](https://gatsby.dev/reproduction). This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.
> 
> If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction](https://gatsby.dev/reproduction) and we'll be able to take another look.
> 
> Thanks for using Gatsby! 💜

[https://github.com/hcygit/gatsby-issue-25462](url)

gatsby develop is okay
gatsby build will reproduce the problem

**Comment by freiksenet** [comment]
Any file inside `pages` directory must be a valid Gatsby page. So you can't have file like `src/pages/ab/index.js`. It will work if you delete this file.

**Comment by hcygit** [comment]
the problem is, thus user can not know which file have to fix cause the message only show undefined
