### ISSUE TITLE
enhancement(www): (Re)-add "Last updated" field for gatsby docs

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#25485]
## Description

Re-add a "Last updated" field for the markdown documentation that shows when the page was last updated (according to git logs)

## Background

This feature was previously implemented in  #19391, but there was a bug: the "Last updated" date was always displayed as the last time the site was built. The feature was removed in #25397 to prevent confusion, but we'd like to add it back.

The reason for the bug is most likely because the Gatsby Cloud build does a shallow checkout of the monorepo, only keeping the latest git log entry. It could be fixed by doing a deep clone of the monorepo, but it's too big and would increase the website's already slow build time.

**Comment by muescha** [comment]
possible solutions (you suggested some in #25397):
- get last commit date from the GitHub GraphQL API (see https://github.community/t/how-to-use-graphql-api-to-get-the-latest-commit-date-of-a-specific-file/13999) but I don‘t know if it is possible to request more than one file (some sort of getAll and then with Pagination) otherwise with file by file it is possible to run into a api rate limit?
- use a post git commit hook to place the last edit date into frontmatter (or some helper file with all last commits)

**Comment by muescha** [comment]
in Doctocat they get it from REST-API for each page:
- fetching the latest commits and contributors in [gatsby-node.js](https://github.com/primer/doctocat/blob/master/theme/gatsby-node.js)
- adding additionalContributors from frontmatter in [layout.js](https://github.com/primer/doctocat/blob/master/theme/src/components/layout.js)
- display with compontent `Contributors` in [contributors.js](https://github.com/primer/doctocat/blob/master/theme/src/components/contributors.js)

related docs: [Doctocat customization#contributors](https://primer.style/doctocat/usage/customization#contributors)
