### ISSUE TITLE
Type error in .cache/navigation.js

### ISSUE THREAD

**Issue by ergunpp** [gatsbyjs/gatsby#25480]
Hi,
I have newly launched a cloud9 instance for my gatsby developments and cloned a a prior project. The project returns success on gatsby develop; but whenever I click on a link in the app it throws the error:
<img width="600" alt="Screen Shot 2020-07-02 at 19 27 57" src="https://user-images.githubusercontent.com/24900951/86386296-3d70a780-bc9a-11ea-8ca6-9e4b4962c114.png">

Thanks for help.

**Comment by freiksenet** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by ergunpp** [comment]
Hi,
I can provide a git repo or direct access to my cloud9 box. I don't know how to create a minimal reproduction for this case.
Here are some screenshots of my versions:
<img width="569" alt="Screen Shot 2020-07-03 at 10 51 04" src="https://user-images.githubusercontent.com/24900951/86446040-0ba02500-bd1c-11ea-80ef-fd3d01f9b952.png">
<img width="638" alt="Screen Shot 2020-07-03 at 10 54 06" src="https://user-images.githubusercontent.com/24900951/86446052-1064d900-bd1c-11ea-91b0-57aa7fb23099.png">

**Comment by freiksenet** [comment]
@ergunpp Do you get this error when you run locally? If yes, then I think git repo would be enough. Otherwise I'd need to check the Cloud9 instance. My email is `freiksenet@gatsbyjs.com`.

**Comment by ergunpp** [comment]
Sent you an email.

**Comment by freiksenet** [comment]
@ergunpp I've fixed it by upgrading `gatsby` and `gatsby-link` (`yarn add gatsby@latest gatsby-link@latest`) to latest version. I'm not sure how to do it on cloud IDE, but I could reproduce it locally.

**Comment by ergunpp** [comment]
Thank you very much. Updating both modules solved my problem. 🙏👍
