### ISSUE TITLE
Downloadable ZIP File 

### ISSUE THREAD

**Issue by andrevildozo** [gatsbyjs/gatsby#25550]
For some reason when trying to download a zip file, it fails. I've tried few different ways, all of them failed. 

 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed

Unexpected character '' (1:2)

File: src/downloads/files.zip

IN CODE:
import File from '../downloads/file.zip'

I use a component to call this file example:
downloadFile={File}
our
<a href={File}>Download the file from the static folder</a>

**Comment by pieh** [comment]
If you want to use `import` route, you would need to add rule for `.zip` files because currently we don't have one built in by default. You can do that by adding following snippet to `gatsby-node` file:

```js
exports.onCreateWebpackConfig = ({ actions, loaders }) => {
  actions.setWebpackConfig({
    module: {
      rules: [
        {
          test: /\.zip/,
          use: [loaders.file()],
        },
      ],
    },
  })
}
```

**Comment by pieh** [comment]
Alternatively instead of using `import` you could place your `.zip` files in `static` directory and follow https://www.gatsbyjs.org/docs/static-folder/ (files from `static` will end up in `public` directory as they are, so if you have your file in `<project_directory>/static/file.zip` you can then do something like `<a href="/file.zip" download>download file</a>` (assuming you will host your site in the root of domain, otherwise your href might be something like `/some-path-prefix/fil.zip`)

**Comment by andrevildozo** [comment]
> If you want to use `import` route, you would need to add rule for `.zip` files because currently we don't have one built in by default. You can do that by adding following snippet to `gatsby-node` file:
> 
> ```js
> exports.onCreateWebpackConfig = ({ actions, loaders }) => {
>   actions.setWebpackConfig({
>     module: {
>       rules: [
>         {
>           test: /\.zip/,
>           use: [loaders.file()],
>         },
>       ],
>     },
>   })
> }
> ```

thanks for your help, it works here
