### ISSUE TITLE
gatsby build suppresses the last line of console.log output

### ISSUE THREAD

**Issue by patspam** [gatsbyjs/gatsby#25591]
## Description

When running `gatsby build`, all `console.log()` calls except for the last one are printed to STDOUT.

### Steps to reproduce

Add some `console.log` calls to an empty Gatsby page and run `gatsby build`

eg.
```
import React from "react"

console.log(1)
console.log(2)

const IndexPage = () => null

export default IndexPage
```

### Expected result

```
...
success Rewriting compilation hashes - 0.004s
[                            ]   0.000 s 0/1 0% Building static HTML for pages
1
2
success Building static HTML for pages - 0.322s - 1/1 3.11/s
...
```

### Actual result

```
...
success Rewriting compilation hashes - 0.004s
[                            ]   0.000 s 0/1 0% Building static HTML for pages
1
success Building static HTML for pages - 0.322s - 1/1 3.11/s
...
```

### Environment
```
  System:
    OS: macOS 10.15.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.5.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 83.0.4103.116
    Safari: 13.1.1
  npmPackages:
    gatsby: ^2.23.12 => 2.23.12
    gatsby-image: ^2.4.9 => 2.4.9
    gatsby-plugin-manifest: ^2.4.14 => 2.4.14
    gatsby-plugin-offline: ^3.2.13 => 3.2.13
    gatsby-plugin-react-helmet: ^3.3.6 => 3.3.6
    gatsby-plugin-sharp: ^2.6.14 => 2.6.14
    gatsby-source-filesystem: ^2.3.14 => 2.3.14
    gatsby-transformer-sharp: ^2.5.7 => 2.5.7
```

**Comment by pieh** [comment]
This is unfortunately known issue. 

This happens because html rendering happens in different process(es) than the majority of work that Gatsby does. Processes share same stdout stream right now and the result is that there is some "fighting" between main process that displays spinners and rewrite stdout when step is done and SSR processes - in here the `Building static HTML for pages` activity is still spinning while the SSR processes try to output to it and when it's done it rewrites stdout to remove spinner and mark step as "success" which also happen to "eat" the last output.

For now workaround is to add some blank console logs, so those get eaten and not the valuable ones

**Comment by herecydev** [comment]
Could this not be solved by Gatsby logging _whatever_ to the console which then gets chewed up?
