### ISSUE TITLE
Can only query the first post of a custom post type, can't use edges > node 

### ISSUE THREAD

**Issue by sjoerdvermeijden** [gatsbyjs/gatsby#25645]
When i try to query posts from a custom post type i can't select "edges{}", therefore i am not able to get all the posts from the custom post. I am only able to query the first one. Anybody have any ideas?

## Summary
![Schermafbeelding 2020-07-09 om 14 47 40](https://user-images.githubusercontent.com/13441035/87046889-08b0a300-c1fa-11ea-8278-9b9930b05fe9.png)

## Relevant information

![Schermafbeelding 2020-07-09 om 15 41 42](https://user-images.githubusercontent.com/13441035/87047392-bf148800-c1fa-11ea-8de1-d5b7aa7eace9.png)

**Comment by pieh** [comment]
You will need to use `allWordpressWpProject` field instead of `wordpressWpProject` one - the one you are using will always return single piece of data (first one that matches provided filters, and because you didn't use any filter it will just return first one)

Fields starting with `all` are "connection fields" and those have `edges.nodes` (or just `nodes` for connivence)

**Comment by sjoerdvermeijden** [comment]
Thank you a bunch! That dit it ;)
