### ISSUE TITLE
Can I change the build directory?

### ISSUE THREAD

**Issue by pratikluitel** [gatsbyjs/gatsby#25653]
## Summary
Hey, I migrated a project to Gatsby, and want to change the build directory so I could deploy from there. Can't seen to find any solutions to change the directory.

**Comment by pieh** [comment]
No, `public` is hard coded right now and adding this option can lead to compatibility issues with plugins because a lot f plugins also expect this directory and generally there is not enough pros there to add this option and handle inevitable issues that will be reported because of that. You might try doing symlinks or so public is there but it's also available under different path
