### ISSUE TITLE
Is there an alternative to StaticQuery that allows passing parameters into a graphql query?

### ISSUE THREAD

**Issue by pratikluitel** [gatsbyjs/gatsby#25675]
## Summary

I wanted to make use of variables in a graphql query within a component, and can't seem to find any way to do that.

**Comment by dalxds** [comment]
In gatsby, you can pass variables to GraphQL queries only through the page context. 
Check the [docs](https://www.gatsbyjs.org/docs/page-query/).

**Comment by TylerBarnes** [comment]
Hi @pratikluitel , thanks for opening an issue and asking such a great question!
It sounds like you're interested in using variables within StaticQuery and this is currently not possible. You'll need to make use of pageContext when you call createPage and use variables only in your page queries for now.
However: there is work in progress that might potentially solve your use-case in a different way in the near future. That is renderable types https://github.com/gatsbyjs/gatsby/issues/18976. Components will be able to be queried for from within your page query. What this means is instead of adding a component with a query inside of it, your component will come from your query and have all the context it needs so that it wont require a second query at all.

Let us know if you have any more questions and thanks again!
