### ISSUE TITLE
Add prettyPath to markdown models

### ISSUE THREAD

**Issue by blainekasten** [gatsbyjs/gatsby#25726]
## Summary

With the upcoming routing APIs in #25204 one pain point is creating url paths from markdown files. A common use case in current mdx apps is to generate a slug from the file path in gatsby node. 

Instead of creating that path when creating the page, we want to add that to the mdx schema. Something like this should work:

```js
exports.setFieldsOnGraphQLNodeType = ({type, getNode}) => {
 if (type.name === `allMdx`) {
    return {
      prettyPath: {
        type: GraphQLString,
        resolve: (node) => createFilePath({ node, getNode })
      }
    }
  }
  return {}
}
```

### Basic example
```js
graphql`
  allMdx {
    nodes {
      prettyPath
    }
  }
`
```
### Motivation

This will make creating these filepaths really easy:

`/src/pages/blog/{prettyPath}.js`

**Comment by connorlindsey** [comment]
I'm interested in picking this up / walking through it with you Blaine.

**Comment by blainekasten** [comment]
@connorlindsey Great! Let me circle back on this tomorrow. I just realized this should apply to all `File` models, not just `mdx` so I need to do a little research to how to do this now

**Comment by pieh** [comment]
I'm all for it as creating slug from file path is task that consistently repeat in a lot of projects.

One thing to be mindful here is that both `mdx` and `remark` nodes can be created from remote data (for example from Contentful long text field), which doesn't have actual file associated with it

**Comment by laurieontech** [comment]
@pieh in that situation what would you expect the behavior to be? A null prettyPath? A path based on title? Something else?

**Comment by blainekasten** [comment]
@pieh in those situations is the model's parent of type `File` or something else? I'm thinking if we just add this value to the `File` property maybe it'll solve it for us?

**Comment by pieh** [comment]
> @pieh in that situation what would you expect the behavior to be? A null prettyPath? A path based on title? Something else?

TBH I don't know. It's pretty impossible to confidently do this for nodes other than File, because it will depend on structure of data etc. I think that returning `null` and possibly displaying some warning to explain why there is no `prettyPath` would be fine handling to unlock this feature for File based situation.

> @pieh in those situations is the model's parent of type `File` or something else? I'm thinking if we just add this value to the `File` property maybe it'll solve it for us?

It's something else, at least in Contentful case - it might differ from case to case. Mdx and Remark are not looking into type of parent node - they are looking for "mediaType"

Remark transformer:
https://github.com/gatsbyjs/gatsby/blob/79348f9c4ca749d5d0d9123962f54f5d961f0344/packages/gatsby-transformer-remark/src/on-node-create.js#L17-L21

Mdx transformer (I guess it checks specifically for file extension for File nodes because `.mdx` extension doesn't result in `text/markdown` mime type):
https://github.com/gatsbyjs/gatsby/blob/79348f9c4ca749d5d0d9123962f54f5d961f0344/packages/gatsby-plugin-mdx/gatsby/on-create-node.js#L36-L43

Contentful:
https://github.com/gatsbyjs/gatsby/blob/79348f9c4ca749d5d0d9123962f54f5d961f0344/packages/gatsby-source-contentful/src/normalize.js#L230-L241

**Comment by LinnJS** [comment]
Happy to pick this up if someone else has not already!

**Comment by laurieontech** [comment]
Going to close this as we've handled the MDX case directly in the plugin. Should we want to revisit a more wide-ranging solution we'll examine that in the future.
