### ISSUE TITLE
GraphQL in the gatsby starter

### ISSUE THREAD

**Issue by accordingtoherr** [gatsbyjs/gatsby#25738]
### File contents (if changed)

starter I am using: https://github.com/chronisp/gatsby-starter/blob/master/README.md

I am having some trouble with this starter. I am using it for a portfolio and connecting to Contentful which was no issue. I am getting errors in my Graph QL. I already looked into this and deleted and reinstalled gatsby sharp and sharp plugins which helped a little. Also, Gatsby was saying my query was wrong and it is expecting something else which I edited it to (thinking it was an older version)  What is confusing me now is that Gatsby is saying a query is wrong but the item it is expecting is the same as the incorrect one.

```shell
Error:   7:63  error  Expected type ContentfulContentTypeFieldsEnum, found ContentfulContentTypeFieldsEnum  graphql/template-strings
```

My Graph QL Query:

```js
import { useStaticQuery, graphql } from 'gatsby';

const useBlogPosts = () => {
  const data = useStaticQuery(
    graphql`
      query {
        allContentfulContentType(sort: { order: DESC, fields: ContentfulContentTypeFieldsEnum}) {
          edges {
            node {
              title
              author {
                name
              }
              ContentfulContentTypeFieldsEnum
              body {
                childMarkdownRemark {
                  html
                }
              }
              heroImage {
                fluid(maxWidth: 960) {
                  ...GatsbyContentfulFluid_withWebp
                }
              }
            }
          }
        }
      }
    `
  );
  return data;
};

export default useBlogPosts;
```

**Comment by sidharthachatterjee** [comment]
Hey @accordingtoherr 

Thank you for opening this issue! It seems that this starter is at https://github.com/chronisp/gatsby-starter

I would suggest opening an issue and discussing this error with the author there. On a quick look, it appears to me that perhaps your Contentful space might not be set up the way the starter needs? Or maybe you're using a version of `gatsby-source-contentful` that the starter doesn't work with? 

Nonetheless, I'll go ahead and close this for now since the author of the starter would have more context and be able to help. Cheers and have a good day!

**Comment by accordingtoherr** [comment]
Ty and confirming contentful is set up it seems to be a graph QL issue I think a bug
