### ISSUE TITLE
No type attribute in source tag of gatsby-image

### ISSUE THREAD

**Issue by burlakko** [gatsbyjs/gatsby#25740]
## Description

Gatsby image does not generate the `type`  attribute two the second `source`  tag while using `GatsbyImageSharpFluid_withWebp` fragment

### Steps to reproduce

Go to the default [starter demo](https://gatsby-starter-default-demo.netlify.app/). Check the code of generated image on main page:
```
<picture>
<source srcset="/static/6d91c86c0fde632ba4cd01062fd9ccfa/5db04/gatsby-astronaut.png 75w,
/static/6d91c86c0fde632ba4cd01062fd9ccfa/6d161/gatsby-astronaut.png 150w,
/static/6d91c86c0fde632ba4cd01062fd9ccfa/630fb/gatsby-astronaut.png 300w,
/static/6d91c86c0fde632ba4cd01062fd9ccfa/62b1f/gatsby-astronaut.png 450w,
/static/6d91c86c0fde632ba4cd01062fd9ccfa/2a4de/gatsby-astronaut.png 600w,
/static/6d91c86c0fde632ba4cd01062fd9ccfa/ee604/gatsby-astronaut.png 800w" sizes="(max-width: 300px) 100vw, 300px">
<img sizes="(max-width: 300px) 100vw, 300px" srcset="/static/6d91c86c0fde632ba4cd01062fd9ccfa/5db04/gatsby-astronaut.png 75w,
/static/6d91c86c0fde632ba4cd01062fd9ccfa/6d161/gatsby-astronaut.png 150w,
/static/6d91c86c0fde632ba4cd01062fd9ccfa/630fb/gatsby-astronaut.png 300w,
/static/6d91c86c0fde632ba4cd01062fd9ccfa/62b1f/gatsby-astronaut.png 450w,
/static/6d91c86c0fde632ba4cd01062fd9ccfa/2a4de/gatsby-astronaut.png 600w,
/static/6d91c86c0fde632ba4cd01062fd9ccfa/ee604/gatsby-astronaut.png 800w" src="/static/6d91c86c0fde632ba4cd01062fd9ccfa/630fb/gatsby-astronaut.png" alt="" loading="lazy" style="position: absolute; top: 0px; left: 0px; width: 100%; height: 100%; object-fit: cover; object-position: center center; opacity: 1; transition: opacity 500ms ease 0s;">
</picture>
```
Source tag does not have `media` or `type` attributes

### Expected result

According to [specification](https://html.spec.whatwg.org/multipage/embedded-content.html#the-source-element):

> When a source element has a following sibling source element or img element with a srcset attribute specified, it must have at least one of the following:
>    * A media attribute specified with a value that, after stripping leading and trailing ASCII whitespace, is not the empty string and is not an ASCII case-insensitive match for the string "all".
>    * A type attribute specified.

### Actual result

[Html validator](https://validator.w3.org/nu/) marks this behavior as an error:
> A source element that has a following sibling source element or img element with a srcset attribute must have a media attribute and/or type attribute.

### Environment

Any environment

**Comment by sidharthachatterjee** [comment]
Hey @burlakko 

Thank you so much for reporting this. You are correct in suggesting that we should probably set a type attribute to the source element. What we'll need to do is perhaps maintain a Map of file extension to MIME type and set it at https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-image/src/index.js

We're happy to receive a PR adding this. 

Side note: I've relabelled this from a bug to an enhancement because it doesn't seem like one that affects the functionality of these images. Please feel free to correct me if I'm missing something.

**Comment by ehrencrona** [comment]
I might be missing something here, but to me it seems like it's rather the `srcset` on the `img` tag that should be removed (and probably `sizes` too). 

What the validation error means is: "Don't specify the srcset in two tags unless I can distinguish them by media type or media query?" and indeed since the `srcset` is identical in both places it would seem to me that it could be dropped on the `img`.

**Comment by SilencerWeb** [comment]
Nope, it is not stale, I'm facing the same issue with the validator and I'd love to have a fix for this 🙂

**Comment by han-so1omon** [comment]
I'd like to hop on this. I'll comment back after I do some digging.

**Comment by geekiam** [comment]
Hey guys 👋🏻
I've faced the same issue:
```
A “source” element that has a following sibling “source” element or “img” element with a “srcset” attribute must have a “media” attribute and/or “type” attribute.
```
![image](https://user-images.githubusercontent.com/6225592/92492251-d2909f00-f1fb-11ea-9c9c-a400e1f64fa5.png)


What the status on this issue? Do you need any help?

**Comment by jussivirtanen** [comment]
![image](https://user-images.githubusercontent.com/3430121/104320936-a22f7900-54eb-11eb-9eae-6925189c1237.png)

I'm having the same issue. Any tips or updates?

**Comment by MaVo289** [comment]
The reason for this behaviour is in the gatsby-image index.js file: 
The following line check does not work and sets by default an empty string, instead of the type attribute and causes the html validator to complain: 

var typeAttr = isWebp ? "type='image/webp' " : "";

A fix could set the typeAttr correctly for the different image formats.

**Comment by MaVo289** [comment]
I figured out how to fix at least the HTML-Errors that are generated due to gatsby-image: 
A simple fix is to set explicitly the media attribute, which in turn fixes the HTML-Errors. Here is a small example: 

`<Img style={imageStyle} fluid={{...image.childImageSharp.fluid,media:"(max-width: 240px)"}} alt={alt} />`

Could of use for some users I guess :-)

**Comment by Viktor19931** [comment]
still have this issues 
<img width="1586" alt="Screenshot 2024-03-10 at 23 00 18" src="https://github.com/gatsbyjs/gatsby/assets/29923015/054426b9-0d39-48c6-ac37-fec689038c8b">
