### ISSUE TITLE
gatsby-remark-copy-linked-files plugin does not copy files

### ISSUE THREAD

**Issue by tinrab** [gatsbyjs/gatsby#2581]
The `gatsby-remark-copy-linked-files` plugin stopped working in my project and it seems for official examples as well.

Steps to reproduce:
1. Clone [gatsby-starter-blog](https://github.com/gatsbyjs/gatsby-starter-blog)
2. Update `index.md` for one of the pages
```markdown
![gif](./test.gif)
![svg](./test.svg)
```
3. Put these files in the same directory as `index.md`
4. Run development server or production build

Files don't get copied over to the `public` folder.

**Comment by Piyush3dB** [comment]
It works for me, I can see my gifs copied over.  My plugins are 

```javascript
  plugins: [
    'gatsby-plugin-react-next',
    'gatsby-plugin-catch-links',
    {
      resolve: 'gatsby-source-filesystem',
      options: {
        path: `${__dirname}/src/pages`,
        name: 'pages',
      },
    },
    {
      resolve: 'gatsby-transformer-remark',
      options: {
        plugins: [
          'gatsby-remark-copy-linked-files',
          {
            resolve: 'gatsby-remark-images',
            options: {
              linkImagesToOriginal: false
            }
          }
        ]
      }
    },
    'gatsby-plugin-react-helmet',
    'gatsby-plugin-sharp'
  ],
```

**Comment by tinrab** [comment]
@Piyush3dB Have you tried linking a GIF with the starter-blog? It's not working for me, in starter-blog and in my own project.

**Comment by KyleAMathews** [comment]
There's a test for copying gifs https://github.com/gatsbyjs/gatsby/blob/161e2aafac75be4549ff59657fda982903b56e42/packages/gatsby-remark-copy-linked-files/src/__tests__/index.js#L46

@tinrab is test.gif in the same file as the markdown post?

**Comment by tinrab** [comment]
@KyleAMathews Yes.

**Comment by KyleAMathews** [comment]
@tinrab not really sure why things aren't working now. It's fairly easy to setup a Gatsby development environment so you could add some console.logs to copy-linked-files to understand where things are going wrong.

https://www.gatsbyjs.org/docs/how-to-contribute/#contributing

**Comment by tinrab** [comment]
@KyleAMathews I've found the problem. [Here](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-copy-linked-files/src/index.js#L30) and [here](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-copy-linked-files/src/index.js#L122) path comparison fails on Windows, because path separators are backslashes, not forward slashes like in `file.absolutePath`. A lot of tests fail for me as it is, so I can't make a pull request.

**Comment by KyleAMathews** [comment]
@tinrab elsewhere we use the NPM package normalize-path https://github.com/jonschlinkert/normalize-path

That might help solve your problem + fix the tests.

**Comment by Chuloo** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues as many of them have already been resolved with the latest updates or explained in a previous issue.

Feel free to [open a new one](https://github.com/gatsbyjs/gatsby/issues/new/choose) if you still experience this problem or a similar one! 👍

**Comment by Terry-Su** [comment]
As starting a new custom project without using gatsby-starter-blog, I encounted this problem too. After long struggle, finnaly solved problem. Add here for anyone who get the similiar problem.

1. while using `gatsby-source-filesystem'` to source markdowns' root  directory, the **name** must be same with the name of the last folder of the path, for me, everything get fine after keeping names same.
```js
{
  resolve: 'gatsby-source-filesystem',
  options: {
    name: 'NAME_MUST_BE_SAME',
    path: `${__dirname}/NAME_MUST_BE_SAME`
  }
},
```

2. add `gatsby-remark-images` plugin in `gatsby-transformer-remark`, otherwise it also doesn't work 
```js
{
  resolve: `gatsby-transformer-remark`,
  options: {
    plugins: [
      `gatsby-remark-images`,
      `gatsby-remark-copy-linked-files`
    ],
  },
},
```

**Comment by moshfeu** [comment]
If you came here and you're using mdx and somehow you missed the docs (like me_

https://www.gatsbyjs.com/docs/working-with-images-in-markdown/#using-the-mdx-plugin
