### ISSUE TITLE
Retext-spell needs to run on PRs

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#25937]
## Description

With https://github.com/gatsbyjs/gatsby/pull/24372/, the retext-spell bot checks spelling against a dictionary.txt file. It's working okay, except that it doesn't run on PRs. This results in changes going in without a notification of issues with the dictionary, causing builds on master to fail.

Contributors and team members should know whether a PR actually passes the linter, rather than guessing or causing a broken build.

### Motivation

We need the status checks to accurately reflect the status of a PR, including spelling/dictionary issues, so we don't have to come back in and fix them after the fact (and cause a headache for other PR authors).

### Steps to reproduce

Look at the checks in [this PR](https://github.com/gatsbyjs/gatsby/pull/24652), and see how `ci/circleci: lint` says "Your tests passed on CircleCI!" 

![A GitHub PR with passing checks](https://user-images.githubusercontent.com/1045233/88112801-6e3f5080-cb65-11ea-9798-90068228fcba.png)

When this PR was merged to master, it broke the build: https://app.circleci.com/pipelines/github/gatsbyjs/gatsby/46391/workflows/40268339-bbd9-4ad1-a883-2c3ddc6def23/jobs/472848

![CircleCI showing failing checks](https://user-images.githubusercontent.com/1045233/88112823-7a2b1280-cb65-11ea-8e6a-832236c2eaf2.png)

### Expected result

The linter should fail code at PR stage, not when merged to master. I wouldn't expect it to automatically fix issues with the dictionary, but at least warn contributors when it's failing on a branch.

### Actual result

Dictionary checks don't run on PRs, so we miss linting issues. This is unsustainable.

### Environment

N/A. this happens for all GitHub users.

**Comment by jaebradley** [comment]
@marcysutton is this still an issue?

Here's a test commit on a PR (https://github.com/gatsbyjs/gatsby/pull/26898/commits/e627dd44d4b95d21b904ab87d97c59d375ff6c8a) where it seems like documentation linking _is_ working per PR.

I wonder if the reason why the `lint:docs` command successfully completed was that the repository (https://github.com/mistryvatsal/gatsby) hadn't rebased before merge and was missing some essential files that had been merged into `master`.

For example, the repository (which doesn't seem to have been modified since the PR referenced in this issue was merged) seems to have [a different `.remarkrc.js` file](https://github.com/mistryvatsal/gatsby/blob/e911332d23fd347b1a24ff0a3912d46c39b9ace8/.remarkrc.js) from what was on `master` on time of merge.

![image](https://user-images.githubusercontent.com/8136030/93142005-34954c80-f6b3-11ea-88f3-ec1452665839.png)

When I copy the `.remarkrc.js` configuration in the above repository, I can get documentation linting to pass even though I've introduced a `docs` markdown file with typos (https://github.com/gatsbyjs/gatsby/pull/26898/commits/30ba7693696717fee20af857dbdb86298bcc9f61)

Build is here: https://app.circleci.com/pipelines/github/gatsbyjs/gatsby/49230/workflows/73abd618-11da-4f70-ab26-de264f66f6e2/jobs/504345

I could totally be missing something - I mostly stumbled upon this issue because I've been looking to contribute and this seemed like a good issue to help with; unfortunately, I am unsure if this is still a problem, but if it is, I'm happy to help out if I can!

**Comment by LekoArts** [comment]
Yeah, that seems correct that it works now and the PR in question had an outdated fork of the repository.
