### ISSUE TITLE
Issues with installing gatsby first time.

### ISSUE THREAD

**Issue by iAbdullahWaleed** [gatsbyjs/gatsby#25951]
its give me this error:
`npm WARN deprecated @hapi/joi@15.1.1: joi is leaving the @hapi organization and moving back to 'joi' (https://github.com/sideway/joi/issues/2411)
npm ERR! Unexpected end of JSON input while parsing near '...26.0","codecov":"3.0.'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ufuq\AppData\Roaming\npm-cache\_logs\2020-07-22T12_18_19_901Z-debug.log
`

**Comment by wardpeet** [comment]
Hi @iAbdullahWaleed!

It's helpful if you could share a repository?

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a minimal reproduction. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could provide a minimal reproduction and we'll be able to take another look.

Thanks for using Gatsby! 💜

**Comment by iAbdullahWaleed** [comment]
Sorry for wasting your time, it's was slow connection issue from me.
