### ISSUE TITLE
Images aren't rendering on iOS when using "column-count" CSS property

### ISSUE THREAD

**Issue by raymestalez** [gatsbyjs/gatsby#25967]
## Description

When I'm loading [this page](https://playmirage.netlify.app/world/) on my iPad, half of the images aren't rendered (the right column), there's just empty space where images should be. Everything works just fine on desktop.

I suspect it happens because I'm using "column-count" css property to organize images into columns.

When I use a regular `<img/>` tag, everything works fine, the issue appears only when I'm switching to `<Img/>` tag from `gatsby-image`.

Here's the link to the code of that page:

https://github.com/raymestalez/mirage-gatsby/blob/master/src/pages/world.js

### Steps to reproduce

Open the link above in Safari on iPad, look at the right column.

### Expected result

See images.

### Actual result

Don't see images.

### Environment

  System:
    OS: Linux 5.3 Pop!_OS 19.10
    CPU: (4) x64 Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 13.14.0 - /usr/bin/node
    npm: 6.14.5 - /usr/bin/npm
  Languages:
    Python: 2.7.17 - /usr/bin/python
  Browsers:
    Chrome: 83.0.4103.116
    Firefox: 73.0.1
  npmPackages:
    gatsby: ^2.23.12 => 2.23.12 
    gatsby-image: ^2.4.13 => 2.4.13 
    gatsby-plugin-feed-mdx: ^1.0.1 => 1.0.1 
    gatsby-plugin-google-analytics: ^2.3.6 => 2.3.6 
    gatsby-plugin-manifest: ^2.4.14 => 2.4.14 
    gatsby-plugin-mdx: ^1.2.27 => 1.2.27 
    gatsby-plugin-offline: ^3.2.13 => 3.2.13 
    gatsby-plugin-preload-fonts: ^1.2.18 => 1.2.18 
    gatsby-plugin-react-helmet: ^3.3.6 => 3.3.6 
    gatsby-plugin-remove-trailing-slashes: ^2.3.11 => 2.3.11 
    gatsby-plugin-sass: ^2.3.12 => 2.3.12 
    gatsby-plugin-sharp: ^2.6.19 => 2.6.19 
    gatsby-plugin-typography: ^2.5.6 => 2.5.6 
    gatsby-remark-copy-linked-files: ^2.3.7 => 2.3.7 
    gatsby-remark-images: ^3.3.14 => 3.3.14 
    gatsby-remark-responsive-iframe: ^2.4.7 => 2.4.7 
    gatsby-remark-smartypants: ^2.3.6 => 2.3.6 
    gatsby-source-filesystem: ^2.3.14 => 2.3.14 
    gatsby-transformer-sharp: ^2.5.11 => 2.5.11 
  npmGlobalPackages:
    gatsby-cli: 2.12.60

**Comment by polarathene** [comment]
Appears to be due to inline CSS on the `gatsby-image-wrapper` div(top/root element of the `gatsby-image` component). I haven't verified if that will reproduce the problem with a regular `img` but I assume it would. 

I do not have iOS, and you did not verify what "desktop" means browser wise. On Linux I have verified the issue with Epiphany browser which uses webkit like Safari does. You can toggle off the `overflow: hidden` style and your images with `gatsby-image` will appear.

That appears to work, I'll need to look into the overflow style, I suspect it's mostly relevant to fluid images, so it may be safe for you to disable. For now you'll need to manually override this, see the docs for `gatsby-image`.

**Comment by raymestalez** [comment]
Thank you very much, this helped!
