### ISSUE TITLE
Square Payment Processing missing second crucial half of instructions

### ISSUE THREAD

**Issue by amandakievet** [gatsbyjs/gatsby#26055]
The documentation about how to use Square with Gatsby [here](https://www.gatsbyjs.org/docs/processing-payments-with-square/) goes through how to get a `nonce` but not how to actually capture a payment. Looking through the Square documentation, it seems like you need to have a server side function to actually capture a payment. Can someone help me understand how that's possible with Gatsby as a static site?

Thank you

**Comment by jonniebigodes** [comment]
@amandakievet i picked on your issue as i was the contributor that created the documentation based on @AishaBlake original issue. As a complement to that documentation i have a example that is mentioned in the documentation. But also there's a starter that i made. You can take a look at it [here](https://github.com/jonniebigodes/gatsby-starter-square). 

In said starter i used a netlify function to handle some of the integration with Square SDK. 

Take a look at the `functions` folder and you'll see what i mean. 

Also as a side note, i know that some of dependencies might be a bit outdated. But honestly i hadn't had the time to take care of the repo and update what needs to be updated. But the repo should at least get you a perspective on what you intend to do.

Stay safe

**Comment by meganesu** [comment]
Adding some extra notes so that hopefully someone can pick this issue up during Hacktoberfest!

## Steps to resolve this issue

- [ ] Update the [Processing Payments with Square](https://www.gatsbyjs.com/docs/processing-payments-with-square/) documentation to include steps for how to capture a payment.
    - If this requires setting up Netlify functions, include steps to show users how to do that.
    - As mentioned above, the Square starter includes a file [`functions/processpay.js`](https://github.com/jonniebigodes/gatsby-starter-square/blob/master/functions/processpay.js) that shows how users can capture payments from the server.
- [ ] Test the reference guide by following along with all the steps from start to finish. Verify that all the necessary steps have been included.
- [ ] Update the outdated dependencies in the [example Square payments project](https://github.com/gatsbyjs/gatsby/tree/master/examples/using-square-payments).

### Open a pull request

- [ ] Open a pull request with your work including the words "closes #26055" in the pull request description

**Comment by imshubhamsingh** [comment]
Hi @meganesu. I just recently started learning Gatsby. This would be a great start for me as well. I would love to pick this up. I'll share PR by the end of this weekend. Thanks ✌️

**Comment by jonniebigodes** [comment]
@meganesu the starter's dependencies will be updated towards the end of the week. I've been trying but i haven't got around to get some time and update it. Once i've applied the changes i'll let you know.

**Comment by meganesu** [comment]
@imshubhamsingh @jonniebigodes sounds good to both! Feel free to reach out if you have any questions.

**Comment by imshubhamsingh** [comment]
@meganesu I've updated the doc and example project. Do let me know if I missed something. 
Thanks ✌️

**Comment by amandakievet** [comment]
Thanks all!

**Comment by davidhowland** [comment]
@imshubhamsingh thank you for adding the missing documentation - it's extremely helpful. As I was reading through I noticed that your example Netlify lambda function uses the deprecated square-connect sdk instead of the new node.js SDK released in December. Is there a specific reason for this that I missed somewhere?

**Comment by imshubhamsingh** [comment]
Hey @davidhowland, thanks for informing me about it. As PR #27272 was opened long back, it was written keeping in mind which ever version was latest at that point of time. At the moment I'm occupied with other work. If this is something you want to pickup, you can. Otherwise I can send in a separate PR with updated examples and doc using latest version in coming weeks.

**Comment by davidhowland** [comment]
@imshubhamsingh ah, that makes sense. I missed the original date here. Thanks! I am currently trying to figure out how to implement this payment form via Netlify functions and have not been successful so any help that you have the time to provide here would be greatly appreciated.

**Comment by LekoArts** [comment]
The original issue was addressed. If you want to keep the docs up-to-date feel free to contribute a PR. Thanks!
