### ISSUE TITLE
Is gatsby a good solution for a doc center with multiple  user interaction？

### ISSUE THREAD

**Issue by lanlan112** [gatsbyjs/gatsby#26063]
Hi,there:

I am new to gatsby, I have few questions that I would like to get help here.Thanks a lot.

I know that a static site (like the one generated by Gatsby) can handle the static aspects of a doc center quite well (show  document directory tree,doc details ,etc.). But, can it also handle the dynamic aspects (giving like and managing messages in personnal center, etc)?  And by the way I am fetching the dynamic data from a restful api.

Should Gatsby be used for My doc center? Does the page has a quick response with the dynamic aspect?

Any guidance would be very appreciated!

**Comment by marcysutton** [comment]
Hey there! What you're talking about is referred to as a Hybrid app page, which Gatsby can certainly support like any React application would. You'll have to write the client-side code to fetch and display data from the restful API, as Gatsby doesn't have APIs for that specifically.

You can read more about that type of architecture in the docs: https://www.gatsbyjs.org/docs/adding-app-and-website-functionality/#hybrid-app-pages

To manage state, you could use something like Redux for which there's an example linked in the docs: https://www.gatsbyjs.org/docs/adding-redux-store/

You may also want to read up on client-only routes if there are any multi-page interactions that depend on user input, since that has to be handled at runtime (as opposed to build time, when Gatsby compiles static pages): https://www.gatsbyjs.org/docs/client-only-routes-and-user-authentication/

We'd love to hear more about what you create, that sounds really cool! I'm going to close this issue for now, but let us know if you have any more questions.
