### ISSUE TITLE
[Gatsby Image] Second <source> tag in missing type attribute

### ISSUE THREAD

**Issue by JulianKleinExternJimdo** [gatsbyjs/gatsby#26125]
## Description

Gatsby Images is rendering  the second source node (see https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-image/src/index.js#L177) without a type attribute. This is not in accordance with the web standard: https://html.spec.whatwg.org/multipage/embedded-content.html#the-source-element 

>When a source element has a following sibling source element or img element with a srcset attribute specified, it must have at least one of the following:

>A media attribute specified with a value that, after stripping leading and trailing ASCII whitespace, is not the empty string and is not an ASCII case-insensitive match for the string "all".

>A type attribute specified.

### Steps to reproduce

Just check https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-image/src/index.js#L177

### Expected result

The source node should have a type attribute in accordance with the web standard

### Actual result

The attribute is not shown

### Environment

Not needed

**Comment by ascorbic** [comment]
Unless I'm missing something this seems to be following the spec, as it includes a `media` attribute. The spec says it should have _at least one_ of `media` and/or `type`.

**Comment by ascorbic** [comment]
I'm going to close this, but if I'm mistaken and this does break the standard please reopen and explain! Thanks.

**Comment by JulianKleinExternJimdo** [comment]
Might be that I am missing something here, but this is my reasoning: It is correct that I could specify a media attribute to resolve the issue. However, I do not want to do that. The media query specifies if the sources node should be skipped depending on the viewport being too small or too large. I do want to use the same source node of webp files on all browser that support webp, and the same set of png files if the browser does not support webp. This should be independent from the size of the viewport. Gatsby Image provides a size attribute for both source nodes, allowing the browser to choose which size version to choose from. In this scenario, I would need to specify the type.

**Comment by polarathene** [comment]
[MDN `<source>` docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/source), under `type` attribute:

> If the `type` attribute isn't specified, the media's type is retrieved from the server and checked to see if the user agent can handle it; if it can't be rendered, the next `<source>` is checked. If the `type` attribute is specified, it's compared against the types the user agent can present, and if it's not recognized, the server doesn't even get queried; instead, the next `<source>` element is checked at once.

> When used in the context of a `<picture>` element, the browser will fall back to using the image specified by the `<picture>` element's [`<img>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img "The HTML <img> element embeds an image into the document.") child if it is unable to find a suitable image to use after examing every provided `<source>`.

So what happens is the first `<source>` should be checked, which would be webp `type`, this is either supported by the browser and requested, or if not it gets ignored and the next fallback `<source>`(or the `<img>` if no other `<source>` was provided) is checked instead. Since we don't add a `type` attribute, that will send a request to the server, which was going to happen regardless at this point.

`media` attribute on the other hand is useful when there is more than two `<source>`, which for `gatsby-image` is still going to only cover a single format or webp and a fallback format, so same logic applies, except that `media` conditions are used as the first filter for selection.

---

Everything should be working as expected, with no issues from not specifying the `type` attribute on the fallback `<source>`, you do not need to manage this yourself `gatsby-image` handles it for you.

Granted, it may not be fully spec compliant, but we're also considering an active PR to fix an issue with Art Direction which embeds `<style>` elements for media queries prior to React being available to ensure the correct image variant is shown (as the one pre-rendered into markup during SSR assumes specific inline CSS for the aspectRatio on fluid images or width/height on fixed images), that is against HTML spec as well, browsers support it but `<style>` is only meant to be in the `<head>`, not `<body>`. Other popular packages like Emotion however do the same thing afaik.

**Comment by j9t** [comment]
Thanks for elaborating, @polarathene. For context, @JulianKleinExternJimdo and I both work for @Jimdo, where we use Gatsby extensively.

> Granted, it may not be fully spec compliant

This is the interesting piece here I find. Could this be revisited, to make it fully compliant? In my mind making sure this code (and code in general) is compliant with respective web standards would not only indicate better software quality and craftsmanship, but could also send a strong signal in terms of Gatsby taking web standards, as well as Gatsby users valuing these standards, seriously.

Have you looked at this from this angle?

**Comment by polarathene** [comment]
> Could this be revisited, to make it fully compliant?

I imagine it'd be low on the Gatsby teams priorities, so you might have to hope for a volunteer contribution unless someone from Jimbo wants to contribute it? 

It should be possible to infer the type attribute from image extension in a `srcSet` field via regex I guess? I haven't looked at how the handling for webp does it, might be metadata added via `sharp`/`graphql` that preps the image data for `gatsby-image`.

> could also send a strong signal in terms of Gatsby taking web standards, as well as Gatsby users valuing these standards, seriously.

Perhaps, although without migrating inline styles for the component to a preferred CSS-in-JS lib, it'd be much more work AFAIK to be spec compliant for the sake of it regarding `<style>` example I cited earlier. If the desired functionality works, and that doesn't cause any real problems, I prefer taking a pragmatic approach personally.

> Have you looked at this from this angle?

I can understand the appeal of what you're asking for, but I'm not a member of the Gatsby team, just a community contributor to `gatsby-image`. It's not something I'd be interested to volunteer my free time on doing. No harm in leaving this issue open though in hopes someone else feels differently?

**Comment by j9t** [comment]
Thanks for sharing more context and your perspective, @polarathene! I suppose keeping this open can draw extra attention and maybe allows to check for some options to achieve valid output, so thanks for that!

**Comment by polarathene** [comment]
Not stale, [someone created a PR](https://github.com/gatsbyjs/gatsby/pull/26558) resolving a [duplicate issue](https://github.com/gatsbyjs/gatsby/issues/25740).

**Comment by j9t** [comment]
After https://github.com/gatsbyjs/gatsby/pull/26558 got discarded, how can this issue be resolved? @polarathene?

**Comment by polarathene** [comment]
@j9t someone will have to resubmit that mentioned PR and make the requested changes from the review I gave.

After that, you need a core dev to review and actually merge it. I won't be reviewing it, as my interest in contributing to gatsby has waned from the lack of progress on my PRs started in June. 

You could try resubmitting the existing PR as-is and see if the core devs provide a less thorough review or they may decline it upfront before you invest your time to improve on it.

**Comment by LekoArts** [comment]
I know that @wardpeet has some thoughts on this and he'll share them, but to keep things tidy I'll close this in favour of https://github.com/gatsbyjs/gatsby/issues/25740 :)
