### ISSUE TITLE
Gatsby develop problem: Source and destination must not be the same

### ISSUE THREAD

**Issue by ashishp166** [gatsbyjs/gatsby#26200]
Description
Tried creating a new gatsby site and got an error message

Steps to reproduce
Ran the usual
gatsby new gatsby-workspace
cd gatsby-workspace
gatsby develop

Expected result
What should happen?

Actual result
ERROR

UNHANDLED REJECTION Source and destination must not be the same.

Error: Source and destination must not be the same.

stat.js:80 getStats
[gatsby-workspace]/[fs-extra]/lib/util/stat.js:80:17

stat.js:38 fs.stat
[gatsby-workspace]/[fs-extra]/lib/util/stat.js:38:16

polyfills.js:295 callback
[gatsby-workspace]/[graceful-fs]/polyfills.js:295:20

Environment
Run ```gatsby info --clipboard``` in your project directory and paste the output here.

System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.18.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.7 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 84.0.4147.105
    Firefox: 78.0.2
    Safari: 13.0.5
  npmPackages:
    gatsby: ^2.23.12 => 2.23.12
  npmGlobalPackages:
    gatsby-cli: 2.12.68

**Comment by freiksenet** [comment]
Hi!

Could you try upgrading gatsby-cli (npm install -g gatsby-cli) and see if the problem persists? Otherwise, it'd be incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by ashishp166** [comment]
Hey, thanks for reaching out to help out. I have actually figured out the problem as I named a folder in the path to my file with an asterisk which resulted in gatsby not being able to develop. Once I took out the asterisk, it was able to properly work.
