### ISSUE TITLE
How to avoid "window is not defined" simply

### ISSUE THREAD

**Issue by Hentaro1989** [gatsbyjs/gatsby#26310]
## Summary
I need to avoid `WebpackError: ReferenceError: window is not defined` as simply as possible when "gatsby build".

## Relevant information
I've already seen https://gatsby.dev/debug-html . Actually, I'm avoiding it like this.

```js
if (typeof window === 'undefined' || typeof JSON === 'undefined') {
  return <></>;
}
```

But I don't prefer to take the solution below.

```js
// Wrap the require in check for window
if (typeof window !== `undefined`) {
  const module = require("module")
}
```

```js
const module = typeof window !== `undefined` ? require("module") : null
```

Because I write my codes with thinking that "browser globals" exist. And the solution pollutes my codes when each time or each file. I just want to write "browser globals" naturally. So If you have any ideas, please let me know. 

Thank you.

**Comment by herecydev** [comment]
> Because I write my codes with thinking that "browser globals" exist

I don't think that's a good view to have, Gatsby operates in 2 ways. It builds pages statically where the `window` doesn't exist and then the pages are hydrated in the browser where window (and other browser features) does exist. Understanding both of these scenarios is pretty key to developing with Gatsby.

The best thing I've found to do is extract the window check into a function (like a react hook).

**Comment by Hentaro1989** [comment]
I also think the thought is an important to developing with Gatsby. But it's a thought of seniors in Gatsby. I feel strange about browser globals don't exist. Because I'm writing codes for frontend not SSR. I think browser globals should exist on "gatsby build".

For example, there is a developer who is not sure about Gatsby. He asks me like this. "Why do you check window every time?" After that I have to answer with "These codes we are writing are exactly for frontend. But Gatsby builds it where browser globals don't exist". In other words, this is not intuitive.

But this is exactly the Gatsby concept, right? So if I use Gatsby, I thought I want to write intuitively as I can.

Window checking function sounds good for me. Thank you for your comment. I'll try it.

**Comment by polarathene** [comment]
> Because I'm writing codes for frontend not SSR.

Gatsby build creates HTML output of your pages for faster rendering and accessibility before React is ready which has it's benefits, otherwise you can probably get away with just using React?

> I think browser globals should exist on "gatsby build".

How would that work? There is no browser, except with some testing(Jest) which uses JSDom (but is incomplete in `window` globals/API sometimes stubbing it out). 

Remember that the build process is creating HTML to output and send to the users browser, regardless at this stage you can run into situations where there are differences such as with `gatsby-image` using Art Direction feature(different images based on browser viewport width), where it must choose only one and writes inline CSS for the width and height which might not match other image variants for different viewports.

> In other words, this is not intuitive.

There is an SSR step, the build. It's to generate the HTML as clarified above. The frontend/client uses that until React is loaded, then it becomes your frontend site/app in the browser. It is as intuitive as understanding media queries, you write code to handle different conditions, and in this case it's a condition for when the code is run without a web browser.

---

You do not need to conditionally import your modules like that, you can still import the module just fine AFAIK, it's just using it within the component that needs to be guarded against. You can set it as a const and reference it like this:

```jsx
// sub-component that is used in render which needs `window` access
import myActualComponent from `mycomponents`

const isBrowser = typeof window !== `undefined`

// Function Component with renturned JSX only
const myComponent = (props) => (
  isBrowser && <myActualComponent data={props.data} />
)

// Function Component with body, can return early if not in a browser
const anotherComponent = (props) => {
  if (!isBrowser) { return null }

  return (
    <myActualComponent data=props.data />
  )
}
```

**Comment by Hentaro1989** [comment]
Thank you for your explanation. I'm gradually understanding about Gatsby. When you write codes, you need to handle some conditions. That is Gatsby. If you want to write only for frontend like me, Gatsby might be not suitable.

 And thank you for your sample code. Since "isBrowser" indicates that you need to handle different conditions, I don't feel strange from this code. I'm going to use this to my project.
