### ISSUE TITLE
Need HTML attribute onClick="" on an element for an iOS fix

### ISSUE THREAD

**Issue by aidanalexander** [gatsbyjs/gatsby#2635]
For an iOS fix I need onClick="" as an attribute on a div. However, when Gatsby builds my site it doesn't add the attribute to the div and is instead adding the functionality of the onClick via the included JS . This would normally be fine, but for the fix to work I simply need the empty onClick="" attribute to be on the element. 

I've thought of using element.setAttribute("onclick", "") but this seems messy as there are 18 elements and I was hoping someone would know  a better way. 

Thanks!

**Comment by KyleAMathews** [comment]
I'm not sure how to do this. Gatsby is just react under the hood though so try googling around for how other people have solved this for React SSR.

Please report back if you find a solution!

**Comment by Chuloo** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues as many of them have already been resolved with the latest updates or explained in a previous issue.

Feel free to [open a new one](https://github.com/gatsbyjs/gatsby/issues/new/choose) if you still experience this problem or a similar one! 👍
