### ISSUE TITLE
WWW going private?

### ISSUE THREAD

**Issue by lannonbr** [gatsbyjs/gatsby#26421]
# Description

With the merge of .com and .org, the "docs site" seems to no longer be fully open source, and it seems with some discussion that some people have been against this internally, but supposedly the team "had a deadline". Now this seems to be ghosting the community contributors who many of us have helped out with the site itself.

This was not discussed at all in public and it is really gives a bad look to the company that supposedly says "you belong here". I get some things should be privatized (Cloud stuff, Blog), but the way this has happened is extremely disappointing. I hope for some public discussion on this matter and figure out what is going to be kept open and what is going to stay proprietary for some transparency.

**Comment by caitlinthefirst** [comment]
Hi, Ben -

Thanks for the feedback. The .com site was aways maintained internally, and that carries over to the merged site. That said, our documentation remains open source and we will continue to accept (and appreciate!) contributions from the community. 

The [contributor workflow](https://www.gatsbyjs.com/contributing/docs-contributions/) has changed a bit as a result, and those changes have been reflected in our docs. The site that you set up locally for contributing to the docs will look different than the .com site, but we will continue to source our docs from gatsbyjs/gatsby, and our review process will remain the same. We will also manage the placement of docs within the docs structure internally but will have conversations with contributors when it’s not clear and/or to confirm where things should land.

The sites were merged because maintaining two sites was complicated and time-consuming, we were hurting our own SEO, and it was confusing to many visitors and users. We are still dedicated to our open source software and community, and we're working hard to put tools and systems in place to support an even more active and inclusive open source community.

Thanks for everything you have contributed to Gatsby and to our community, and please do not hesitate to reach out if you have any other concerns.

**Comment by lannonbr** [comment]
I guess a follow-up question is what is the status of the `www` folder. As that site & the current gatsbyjs.com start to slide further from each other, it just leaves `www` as an artifact that isn't really maintained. Should `www` even be kept around anymore?

**Comment by gillkyle** [comment]
To try and respond to the follow up question. The state of `www` is that it is good to keep around for now for at least a few reasons I'd cite:

1. it keeps the existing code and implementation of some Gatsby best practices in the open (the only things that have moved in the last month are changes to order of docs in the sidebar)
2. it allows contributors to the docs to preview additions to the docs like code highlighting and using MDX components locally

The next step forward of how we improve the contributing experience, whether that be an ironed out documentation theme that is open sourced that we use and publish or just keeping the `docs` folder is still a little bit up in the air though. I know that doesn't give perfect clarity of the future, but hopefully is some consolation.
