### ISSUE TITLE
Comparison page looks broken (/features/jamstack/gatsby-vs-nextjs)

### ISSUE THREAD

**Issue by thehanimo** [gatsbyjs/gatsby#26475]
## Description

After reaching the bottom of the table, scrolling further shows data (that was already there in the table) in an unformatted way.

### Steps to reproduce

Visit https://www.gatsbyjs.com/features/jamstack/gatsby-vs-nextjs and keep scrolling.

### Expected result

Unformatted (duplicate?) data shouldn't be rendered.

### Actual result

Unformatted data is rendered.

### Environment

Tested on Safari & Firefox.

<img width="1440" alt="Screenshot 2020-08-15 at 9 30 35 PM" src="https://user-images.githubusercontent.com/37334271/90316345-2da5dd80-df3f-11ea-9963-9daa876ba2f1.png">

### Additional Notes
Would love to take this up if it isn't already being fixed.

**Comment by polarathene** [comment]
I viewed in Chrome, initially it seemed the table was incomplete and rather than duplicate entries for me I'm pretty sure I just got the unformatted content like in your image. I had closed the tab, but to verify the duplicate content issue I visited the link again, this time the page was looking perfectly correct, not like your screenshot, everything was in a table.

Either it just got fixed or there is some weird bug going on.

**Comment by nephlin7** [comment]
Seems this happen in the whole pages:

![Captura de Pantalla 2020-08-25 a la(s) 10 42 43 a  m](https://user-images.githubusercontent.com/22168189/91202932-bb13cb00-e6bf-11ea-8841-ff48b2b8a871.png)

![Captura de Pantalla 2020-08-25 a la(s) 10 41 19 a  m](https://user-images.githubusercontent.com/22168189/91202826-9881b200-e6bf-11ea-9d49-bbc881570927.png)
...

**Comment by LekoArts** [comment]
Please visit those sites now (with a cleared cache), I pushed some changes in the hope of fixing the issue. I don't see the issue anymore, please let me know if that is also the case for you.

**Comment by thehanimo** [comment]
@LekoArts, LGTM 👍

**Comment by polarathene** [comment]
Looks fine for me too now.

**Comment by LekoArts** [comment]
Great!
