### ISSUE TITLE
sometimes it takes too long to redirect from gatsby.org to gatsby.com

### ISSUE THREAD

**Issue by ghassanmas** [gatsbyjs/gatsby#26477]
So if you are googling a gatsby plugin or something, you will get result from gtasby.org 

i.e search  query `gatsby-plugin-remark emojis`
The result link will be as following `https://www.gatsbyjs.org/packages/gatsby-remark-emojis/` 
And this link then redirect to `https://www.gatsbyjs.com/plugins/gatsby-remark-emojis/` 

And this may be the third time in the day that it takes really too long to redirect more than 4 minutes sometimes. It was Okay for me because I know about the merge between gatsby.org and gatsby.com and trick to replace `/pancakes/` with `/plugins/`. But for other it may be super annoying.

**Comment by polarathene** [comment]
> And this may be the third time in the day that it takes really too long to redirect more than 4 minutes sometimes.

Probably best to add info about your internet connection and location in the world? If a VPN was in use or anything else that might have an affect on the connection (downloads or uploads elsewhere in the background unrelated to Gatsby on a slower connection for example). All that can contribute to the issue experienced.

In the browser dev tools for network tab, you should be able to observe a request and presumably when this happens you're experiencing a very long TTFB (time between a request and a response being received before any network transfer of content or redirect occurs).

**Comment by ghassanmas** [comment]
https://www.loom.com/share/0e16d04af7fe442388e59aa59dad16cd

**Comment by polarathene** [comment]
It's about 700ms of TTFB across several 301 redirects for me.

Seems to be a DNS issue on your end according to the chrome error page? You didn't show me the network request (if you filter it for `doc` type).

I had a HTTP->HTTPS redirect to the gatsby.com/plugins URL, followed by a 2nd redirect for `www` subdomain, and a third redirect for adding a trailing slash. All served from Netlify, so you might need to bring the issue up with them unless it's something to do with `gatsby.org` DNS. 

For whatever reason, your system was unable to resolve the IP address to that domain (what DNS does), if you do have anything that might be modifying your local DNS resolver, such as a VPN, it's possible that is interfering somehow, but I don't know why it'd only be the org domain.

The Speedtest doesn't tell me much, that will test for speed locally, those results don't apply globally. For example while in China, I'd have amazing speeds within China, but accessing anything outside of China with or without VPN often had very poor connection speeds, sometimes failing to load websites or complete an image download when doing a gatsby build and pulling from CMS.

I unfortunately do not know how to debug the issue, I am aware of someone else based in the EU somewhere that experiences similar with a non-gatsby site that I manage, but it is not frequent for them(about once a month), I suspect due to some cache behaviour, the responses from the gatsby domains are explicitly avoiding any caching without validation passing, which might be why it would be reproducible each time.

**Comment by polarathene** [comment]
One potential solution you could try and explore is changing your DNS. Not sure what you are using currently, but you can configure your system to use [Google's DNS `8.8.8.8`](https://en.wikipedia.org/wiki/Google_Public_DNS) or [Cloudflare's DNS `1.1.1.1`](https://1.1.1.1/dns/), might be some other options but those are popular ones.

Let us know if it works for you and what one you go with.

**Comment by Bram-Zijp** [comment]
I am having extreme load times on Gatsbyjs.org. Like 20-60 seconds. I'm running a clean Windows 10 machine with no custom DNS.

**Comment by polarathene** [comment]
@Bram-Zijp if it's easy for you to reproduce, monitor the network dev tools tab, what sort of TTFB are you seeing? It's still very fast for me to respond, even though the page weight appears to be 4.4MB network transfer (7MB uncompressed).

I'd suggest giving the advice to change your DNS to one of the two public DNS providers and sharing back here if that makes any difference.

**Comment by blainekasten** [comment]
Thanks for the report. We've fixed this!
