### ISSUE TITLE
Gatsby Documentation Update

### ISSUE THREAD

**Issue by rlongio** [gatsbyjs/gatsby#26499]
## Summary

gatsbyjs documentation >  0. Set Up Your Development Environment > Create a Gatsby site

The shell command is incorrect to create a new gatsby site
`gatsby new hello-world https://github.com/gatsbyjs/gatsby/tree/master/starters/hello-world`

The command returns:

> ERROR
> starter https://github.com/gatsbyjs/gatsby/tree/master/starters/hello-world doesn't exist

## Proposed Solution
From the documentation at the above address, the shell command should be
`gatsby new hello-world https://github.com/gatsbyjs/gatsby-starter-hello-world`

This does create the new 'hello-world' site.  However, likely a separate issue, upon successful creation of the starter directory layout, this error occurs

```
info Creating new site from git: https://github.com/gatsbyjs/gatsby-starter-hello-world.git
Cloning into 'my-hello-world-starter'...
remote: Enumerating objects: 16, done.
remote: Counting objects: 100% (16/16), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 16 (delta 0), reused 9 (delta 0), pack-reused 0
Unpacking objects: 100% (16/16), done.
Checking connectivity... done.
success Created starter directory layout
info Installing packages...
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /vagrant/my-hello-world-starter/node_modules/yurnalist/node_modules/debug/package.json.1939036142
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/vagrant/my-hello-world-starter/node_modules/yurnalist/node_modules/debug/package.json.1939036142'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2020-08-17T02_28_25_198Z-debug.log

ERROR 

Command failed with exit code 254: npm install
Error: Command failed with exit code 254: npm install

  - error.js:56 makeError
    [lib]/[gatsby-cli]/[execa]/lib/error.js:56:11

  - index.js:114 handlePromise
    [lib]/[gatsby-cli]/[execa]/index.js:114:26

  - next_tick.js:68 process._tickCallback
    internal/process/next_tick.js:68:7
```

This is fixed by changing directory to hello-world and running `npm install` as per the template repositories README.md.

### Motivation

The documentation should be updated as instructions up to this point are solid.  It may also be beneficial to reference the bash script lines:

```
=> nvm source string already in /home/vagrant/.bashrc
=> bash_completion source string already in /home/vagrant/.bashrc
=> Close and reopen your terminal to start using nvm or run the following to use it now:

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
```

Nowhere in the documentation does it mention restarting your terminal or the option to manually run the 3 lines referenced above.

## Steps to resolve this issue

Update the url of the hello-world starter repository
Mention that you must restart your terminal in order for the changes to take affect.

**Comment by polarathene** [comment]
Referenced documentation page: https://www.gatsbyjs.com/tutorial/part-zero/

Doc provides failing command:

```
gatsby new hello-world https://github.com/gatsbyjs/gatsby/tree/master/starters/hello-world
```

Claimed working command:

```
gatsby new my-hello-world-starter https://github.com/gatsbyjs/gatsby-starter-hello-world
```

The projects appear to be similar but do differentiate, just diff the README for example. The latter one with it's own repo appears to have a Vercel deploy button in README while the documentation referenced one only has a Netlify deploy button, however is lacking the update for the Gatsby logo new URL, and references files that are not in that project codebase.

---

> This does create the new 'hello-world' site. However, likely a separate issue, upon successful creation of the starter directory layout, this error occurs

I could not reproduce, worked perfectly fine for me.

> This is fixed by changing directory to hello-world and running npm install as per the template repositories README.md.

We must be looking at different READMEs because both seem to have no mention of `npm install`, only `gatsby develop`.

---

> Nowhere in the documentation does it mention restarting your terminal or the option to manually run the 3 lines referenced above.

That may depend how you go about installing it, first thing to do when troubleshooting would be to look up the docs for that tool(since it's nothing to do with Gatsby, but sure, they could probably direct you there for troubleshooting, they do ask you to verify the command works which you seem to have omitted), here's the instructions for linux troubleshooting: https://github.com/nvm-sh/nvm#troubleshooting-on-linux

> *On Linux, after running the install script, if you get `nvm: command not found` or see no feedback from your terminal after you type `command -v nvm`, simply close your current terminal, open a new terminal, and try verifying again.*

I use [`asdf`](https://github.com/asdf-vm/asdf) personally ( supports more than just node but `nvm` is probably simpler).

**Comment by rlongio** [comment]
I failed to mention that this was using Ubuntu 18.04LTS (Bionic).  

I'm closing this issue after spending numerous unsuccessful hours trying to install Gatsby and create the "hello world starter without success.

There were numerous dependency issues that I could not resolve without creating another dependency issue, leading me to believe that there must be some local underlying issue I'm not seeing.  This is further enforced by @polarathenes comments that he has not been able to replicate the issue.

**Comment by polarathene** [comment]
@rlongio if you have Discord and need some assistance, feel free to contact me on there(either by ping on the Gatsby help channel or Direct Message).

Were you using Ubuntu as your host OS, or was that the OS used with Vagrant?

Would be interesting if you do find out what went wrong and could share here what happened if anyone else runs into your experience, it might assist them :)

I'd ignore Gatsby for now, and just make sure `nvm` is installed and working properly, perhaps with a basic React project, or any other JS projects that you may already have and could try installing  

If node or npm were installed in your Ubuntu system packages, and not only provided from `nvm` it's possible that there was a conflict there and your calls could have been using the system binaries instead of `nvm` provided ones. When I first used Linux, this was a common problem I ran into (using system packages for development), as they were root(admin) owned, and my user running them would hit permission issues causing `npm install` and such to fail (and the cause I don't think was always obvious).

You could also try `asdf` as an alternative, I think following the README should be enough instructions wise, otherwise you might have luck with google search, you'll need to install a `asdf-nodejs` plugin IIRC. Then like NVM, configure it to install/default to your preferred node version.

One other option, is finding a nodejs vagrant image that should already have nodejs setup for you and you can skip all that. I use Docker these days, but generally do development on my local / host OS (Manjaro KDE), likewise you could get the official nodejs Docker image and open a shell into the container(if you're not familiar with Docker, it'll be a bit different than what you may be used to with Vagrant, again feel free to reach out and I'd be happy to run you through the basics). 

Docker is often popular for being immutable, in that you can have a clean slate and reproduce an environment without retaining any state like a VM may(requiring you to create a new VM or rollback a snapshot instead). To persist state with Docker, you can add local folders, similar to VirtualBox(and I assume Vagrant, I haven't used Vagrant myself). 

The one gotcha, which may also apply in your Vagrant case, is that you shouldn't run an `npm install` on your host OS system, but within the VM or container itself, even on Linux with a linux container there can be subtle differences that would cause problems like this.

---

> This is further enforced by @polarathenes comments that he has not been able to replicate the issue.

Just to clarify, the documentation instruction does fail for me as well. 

Using the alternative github repo URL you provided does work for me without any issues, I just noted that the two github repo projects while similar don't appear to be in sync, so I'm not sure what the status is of them both or why there would be that duplication of effort in maintaining them.

**Comment by polarathene** [comment]
Also, there's a related issue [here](https://github.com/gatsbyjs/gatsby/issues/26503), and a core dev has chimed in that they're going to resolve that, not sure if that'll help you.

**Comment by SaltyCatFish** [comment]
@polarathene I will take you up on the offer for help soon and appreciate you taking the time to clarify.

This was an attempted vagrant installation:

## Vagrantfile
```
Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.network "forwarded_port", guest: 8000, host: 8000
    config.vm.network "public_network", ip: "192.168.1.34"
    config.vm.synced_folder ".", "/vagrant", type: "nfs", mount_options: ["dmode=777", "fmode=776"]
    config.vm.provision "shell", path: "provision.sh"
end
```

## provision.sh
```
sudo apt-get update && sudo apt-get upgrade -y
git config --global user.name "Ryan Long"
git config --global user.email "ryan@rlong.io"
```

I was trying to build the image first manually and writing the steps that succeeded into the `provision.sh` script, the above was the only part implemented during the `vagrant up`.

I followed the Gatsby instructions from the gatsbyjs.com site /tutorial/part-zero -0. Set Up Your Development Environment
[Ubuntu, Debian, and other apt based distros](https://www.gatsbyjs.com/tutorial/part-zero/#ubuntu-debian-and-other-apt-based-distros)

I stumbled for a while (my fault for not reading more carefully) after runnning `curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.1/install.sh | bash` when I finally read the message and realized I had to either restart or run the commands displayed.

After running `nvm install 10` and `nvm use 10`, I verified the versions and everything looked correct.

It was once I tried to start the "hello world starter" that things started to fall apart.

The shell command from the documentation failed, so I entered the URL in my browser and followed the installation instructions there.  The `npm install` from the starter project was the part I could not get to work.  There would always be a dependency failure, either gatsby itself was missing, or a sub_module ~yasuoti was missing (though this was not in the package.json)

I'm fairly certain that the root cause is installing `gatsby-cli` in vagrant.  I did at first without using `sudo` as per the docs, then with sudo, then just tried poking and hoping, not installing it globally, etc.

I was able to install without issue in a Windows 10 environment, which again leads me to believe it is a vagrant vs. node issue.

This is why I closed the ticket; it seemed more like a vagrant/environment issues than a gatsby/node issue.

**Comment by polarathene** [comment]
> then with sudo

Don't do that for globally installed packages. NVM and others like it are meant to provide a version of node/npm that is local to the user, sudo would be required for installing to root owned files(eg the system/OS and it's admin user that should be separate from your own logged in user). That will cause problems for this sort of development.
