### ISSUE TITLE
[React Docgen] Doesn't work with other processors

### ISSUE THREAD

**Issue by LKay** [gatsbyjs/gatsby#2650]
I'm trying to use `gatsby-transformer-react-docgen` along with `gatsby-plugin-typescript` as my files are written in typescript. The files get properly transpiled into `.js` files but docgen comments are not being extracted into GraphQL objects resulting in warnings/errors such as:

```
warning The gatsby-transformer-react-docgen plugin has generated no Gatsby nodes. Do you need it?
```

```
GraphQL Error Unknown type "ComponentDescription".

  file: (...)/ComponentPage.tsx

  1 |
> 2 |   fragment ComponentPage_desc on ComponentDescription {
    |                                  ^
  3 |     childMarkdownRemark {
  4 |       html
  5 |     }
  6 |   }
  7 |
```

Poke: @jquense

**Comment by sebastienfi** [comment]
I don't know these plugins, but it seems a good idea for you to publish a repro repo so others can help you figure that out faster :)

**Comment by Chuloo** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues as many of them have already been resolved with the latest updates.

Please make sure to update to the latest Gatsby version and check if that solves the issue. Let us know if that works for you by adding a comment 👍
