### ISSUE TITLE
Using gatsby-plugin-sass how to obfuscate class name

### ISSUE THREAD

**Issue by asinha08** [gatsbyjs/gatsby#26556]
## Relevant information

I am using gatsby-plugin-sass. How can I obfuscate class name?

### Environment (if relevant)

NA

### File contents (if changed)

NA

`gatsby-config.js`:  
Plugin (gatsby-plugin-sass) changes looks like below
```
{
			resolve: `gatsby-plugin-sass`,
			options: {
				name: `styles`,
				data: `@import "./src/styles/global.scss";`,
				includePaths: [`${__dirname}/src/styles`],
				modules: true,
				sourceMap: activeEnv !== PROD,
				localIdentName: activeEnv === PROD
					? '[hash:base64:5]'
					: '[path][name]__[local]--[hash:base64:5]'
			}
		}
```
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by pieh** [comment]
You'd need to put `css-loader` specific options (so `modules`, `sourceMap` and `localIdentName`) in `cssLoaderOptions` field.

Here's small example (that doesn't use all of your options, specially the `node-sass` ones (`data` or `includePaths`) in here, because I didn't have your exact project. But I did verify the minimal one that "obfuscates" the class name (so the `localIdentName` one):

```js
    {
      resolve: `gatsby-plugin-sass`,
      options: {
        cssLoaderOptions: {
          localIdentName: "[hash:base64:5]",
        },
      },
    },
```
