### ISSUE TITLE
Auto invitation for contributors not working

### ISSUE THREAD

**Issue by Aman-zishan** [gatsbyjs/gatsby#26615]
## Summary

It's mentioned in the website that contributors will be invited automatically to organization. But it seems like it's not working :(

**Comment by lannonbr** [comment]
As of about a week or two ago, this policy was removed (See https://www.gatsbyjs.com/blog/2020-08-04-gh-community-permissions-changes-gatsbyjs ). I see it is still mentioned here: https://www.gatsbyjs.com/contributing/community/ and it may be in other locations as well, so that copy needs to be changed as the only people in the gatsby org anymore are employees
