### ISSUE TITLE
Gatsby build rearranges my JSX output

### ISSUE THREAD

**Issue by ilyador** [gatsbyjs/gatsby#26621]
No idea why, but after the build the HTML is slightly different from the develop version and it messes up my website, here are two examples:

Original:
```html
<div class="MuiPaper-root makeStyles-modal-3 MuiPaper-elevation5 MuiPaper-rounded">
  <form class="makeStyles-form-4 makeStyles-form-13"></form>
  <div style="transition: opacity 600ms ease-in-out 0s; opacity: 0;"></div>
</div>
```
Build:
```html
<div class="MuiPaper-root jss3 MuiPaper-elevation5 MuiPaper-rounded">
  <div style="transition:opacity 600ms ease-in-out;opacity:0"> <====== Duplicated and moved outside
    <form class="jss4 jss13">...</form>
    <div style="transition: opacity 600ms ease-in-out 0s; opacity: 0;"></div>
  </div>
</div>
```

Original:
```html
<div id="___gatsby">
  <div class="wrapper"> <====== Missing from build
    <div tabindex="-1" id="gatsby-focus-wrapper" style="outline: none;">
      <div class="web-course">
        <section>
```
Build:
```html
<div id="___gatsby">
  <div style="outline:none" tabindex="-1" id="gatsby-focus-wrapper">
    <div class="web-course">
      <div class="web-course"> <====== Duplicate
        <section>
```

**Comment by herecydev** [comment]
Can you put a reproduction together? Also, in what way does it cause issues (other than being slightly different?)

**Comment by ilyador** [comment]
@herecydev I can't put my development code since it is a private repo, only the build.
It messes up the HTML structure causing many visual issues.

**Comment by blainekasten** [comment]
This occasionally happens to users and it's usually due to reacts reconciliation process with SSR. Right now you won't run into this because we don't do SSR in develop (Though that will be changing #25729 ). 

It's hard to advise without seeing more code. But you likely have some components somewhere that are conditionally rendering differently on the server vs on the client. This could be something like a component that does `if (!window) return null` or a host of other issues. 

The easiest way right now to debug this is to use `gatsby build` and `gatsby serve` locally to find the bug and fix it locally.
