### ISSUE TITLE
Adding dark mode for gatsbyjs.com

### ISSUE THREAD

**Issue by GuillouTran** [gatsbyjs/gatsby#26713]
## Summary
Adding back the dark mode for gatsbyjs.com

## Relevant information
Dark mode was a available feature on gatsbyjs.org but after got merged to gatsbyjs.com, it disappear and it really frustrating me because I work a lot at night and it make my eyes sore every time I have to go and read documentation

### File contents (if changed)
`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by sidharthachatterjee** [comment]
Hey @GuillouTran 

Thanks for pointing this out! We're aware of this and it's definitely something we intend to add back support for. 

@gillkyle who owns the website at the moment should be able to tell us more regarding when we can expect to see this!

**Comment by gillkyle** [comment]
Hi there 👋  this is certainly a pain point, I'll try and provide updates for this when I have more info, but we're still scoping out work for further improvements to the site so I'm not sure I can promise specifically _when_ this will be added. 

Know that we do intend to add it back though!

**Comment by gillkyle** [comment]
Hey @GuillouTran, as a follow-up, we probably won't be able to get to re-implementing dark mode soon. In your case of preferring dark mode perhaps an extension like [Dark Mode Reader](https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh) could be a compromise. Solutions not catered to the docs specifically (this is extension) aren't perfect of course because various components like code blocks won't have great highlighting, but might help.

To reimplement dark mode adds a lot of work to designs that we hadn't done ahead of time. This is further complicated by unifying websites because we have marketing pages, a blog, and the entire Gatsby Cloud app that don't have dark mode implemented yet either. Dark mode can be an accessibility improvement, but it can also be a big accessibility failure if we don't get it right, because it's very easy to have low contrast colors (this was something we ran into on the old version of the docs). For those reasons we're holding off for now, but understand that to you (and many others!) having dark mode would be the ideal and will hopefully be able to add it back in a future iteration 🙂

**Comment by GuillouTran** [comment]
Thank you for your feedback
