### ISSUE TITLE
[gatsby-source-shopify] - Caching, Images & General Performance Improvements

### ISSUE THREAD

**Issue by jasonbiondo** [gatsbyjs/gatsby#26726]
I'd like to know how I can speed up the performance of this plugin.  I have a store with thousands of products and every time I use npm run dev, the build process takes minutes and is killing my productivity.  

1. Is there a way to cache the product and collection data?
2. Is there a way to eliminate the querying of all data? (I don't need terms, policies, blog etc - I only need products and collections) 

Is there any documentation on this, because I don't see that available?

**Comment by jasonbiondo** [comment]
@smthomas @pvdz I'm thrilled this got assigned.  Any ETA, when you think you'll be able to optimize this?

**Comment by pvdz** [comment]
@jasonbiondo Some of the other sourcing plugins support an env flag that stores remote data in an explicit location, outside of Gatsby cache. This may speed up development and build time, at the expense of realizing at some point your remote changes aren't reflected (this will hit you sooner or later ;) ). 

These are generally footguns so would not be documented. Mostly for debugging or profiling sites, where you repeatedly run a build without caring about upstream changes. You could look through the plugin to see if the shopify plugin has this. If it doesn't, you could open a PR that adds this. Ideally such a flag, like `GATSBY_SHOPIFY_EXPERIMENTAL_FORCE_CACHE` would only hit the remote server if the cache does not exist, and otherwise read the remote data from a local file verbatim (`v8.serialize` / `v8.deserialize`).

It may not be that trivial but that's it in a nutshell.

For example, I happen to have added this for Contentful this week, see https://github.com/gatsbyjs/gatsby/pull/27404

**Comment by jasonbiondo** [comment]
@pvdz I couldn't find any GATSBY_SHOPIFY_EXPERIMENTAL_FORCE_CACHE or anything similar in the plugin.  Can someone put in a fix for this? I'd like to have a flag for dev and have my prod builds run without the cache flag.

**Comment by pvdz** [comment]
@jasonbiondo Yeah, you can submit a PR that adds it. I don't expect myself or anyone on our team to have time to do this in the foreseeable future, if that's what you're asking.

**Comment by sandro768** [comment]
Is there a way to disable cache invalidation for a plugin? So, the issue mentioned above will be resolved.

**Comment by zachbresler21** [comment]
Can this please be reopened as the build times are terrible while waiting to pull from Shopify. Any news on if caching will be included soon?

**Comment by KyleAMathews** [comment]
Have you tried the new version yet?

**Comment by mwogates** [comment]
Can we reopen this issue as the build is taking a long time? It seems it hasn't been improved yet, in the new versions.

**Comment by dav92lee** [comment]
+1 can we please reopen this issue please?
