### ISSUE TITLE
input onChange() fires too much!

### ISSUE THREAD

**Issue by mimiza** [gatsbyjs/gatsby#26731]
Hello there!
After upgrading gatsby-cli and gatsby  to the latest version:
Gatsby CLI version: 2.12.46
Gatsby version: 2.24.53
I noticed that <input> onChange event fires too much. Indeed, it fires on every single letter input. This is very annoying because it makes the input field stuck. User has to re-click the input field to continue typing.

**Comment by herecydev** [comment]
This isn't a gatsby issue, this is a react feature. By design it fires every time an input changes, if you put together a minimal reproduction I'm happy to help diagnose why it's causing issues for you.

**Comment by madalynrose** [comment]
Thanks for your response @herecydev! And I'm sorry you're running into this issue @mimiza!

To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] either in a public repo or in something like [codesandbox](https://codesandbox.io/) and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by mimiza** [comment]
@herecydev @madalynrose Thanks for reading and your offer to help. Before running 'yarn upgrade', everything worked just fine. But from this issue, I decided to change my code so now there is no need for help. But thanks for reading thou. I appreciate gatsbyjs and a fan of it.
