### ISSUE TITLE
Graphql query works in development but not in production

### ISSUE THREAD

**Issue by vladandrei0** [gatsbyjs/gatsby#26773]
## Description

Query not returning anything in production. Works perfectly in development.

### Steps to reproduce
![InkedCapture_LI](https://user-images.githubusercontent.com/24414516/92139460-6d623580-ee18-11ea-91bf-5a9c6df1814a.jpg)

#### works in development

![Capture2](https://user-images.githubusercontent.com/24414516/92139139-ffb60980-ee17-11ea-8fdd-93083e77c0a5.PNG)

### Actual result

After the build, the deployed version filtered query returns no results. All the other queries in the project work including the ones not highlighted in green.
I tried everything!! There are no errors whatsoever. It's my first question ever so be kind pls 🤕 

### Environment

System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  Binaries:
    Node: 13.7.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.7 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.7.0 - /c/ProgramData/Anaconda3/python
  Browsers:
    Chrome: 84.0.4147.135
    Edge: Spartan (44.18362.449.0)
  npmPackages:
    gatsby: ^2.23.3 => 2.23.3
    gatsby-firesource: ^2.0.3 => 2.0.3
    gatsby-image: ^2.4.7 => 2.4.7
    gatsby-plugin-gdpr-cookies: ^1.0.7 => 1.0.7
    gatsby-plugin-google-fonts: ^1.0.1 => 1.0.1
    gatsby-plugin-layout: ^1.3.10 => 1.3.10
    gatsby-plugin-manifest: ^2.4.11 => 2.4.11
    gatsby-plugin-offline: ^3.2.9 => 3.2.9
    gatsby-plugin-react-helmet: ^3.3.4 => 3.3.4
    gatsby-plugin-sharp: ^2.6.11 => 2.6.11
    gatsby-plugin-styled-components: ^3.3.5 => 3.3.5
    gatsby-plugin-svgr: ^2.0.2 => 2.0.2
    gatsby-source-contentful: ^2.3.18 => 2.3.18
    gatsby-source-filesystem: ^2.3.11 => 2.3.11
    gatsby-transformer-sharp: ^2.5.5 => 2.5.5
  npmGlobalPackages:
    gatsby-cli: 2.12.65

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by vladandrei0** [comment]
Hi!
Solved!
I updated everything and it worked.

**Comment by ascorbic** [comment]
Great. Thanks for the update.
