### ISSUE TITLE
Why Gatsby reads useStaticQuery for componenets

### ISSUE THREAD

**Issue by iamabdullahmalik** [gatsbyjs/gatsby#26794]
Hi,

I have the following structure.

src
  --components
  -- pages

I have a page home and home component which has multiple sections. I am import using sections in home but I just created the components for now. Why gatsby is giving me error at build time that query failed even thought I have not imported components yet.

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by iamabdullahmalik** [comment]
Hi @LekoArts ,

simply i created section in project and commit the code for now use latter, i am using airtable with staticQuery. while code is commented gatsby compile static query.
here is screen shot of code.
![aboutCode](https://user-images.githubusercontent.com/7901693/92444806-d6f19380-f1cc-11ea-9d69-77b1e25554d6.PNG)
![commented_code](https://user-images.githubusercontent.com/7901693/92444839-e1139200-f1cc-11ea-8a00-44631527834d.PNG)
![terminal_error](https://user-images.githubusercontent.com/7901693/92444866-ebce2700-f1cc-11ea-8388-08a98aba8597.PNG)

Thanks.

**Comment by LekoArts** [comment]
Ah, I see!

This is expected behavior at the moment, Gatsby automatically tries to parse those queries whether they are used or not. You'll need to comment out the query to not see this error.

Slightly related issues:
https://github.com/gatsbyjs/gatsby/issues/23729
https://github.com/gatsbyjs/gatsby/issues/16338

**Comment by iamabdullahmalik** [comment]
okay thanks
