### ISSUE TITLE
Use of StaticQuery works on develop but not working in build

### ISSUE THREAD

**Issue by karltud123** [gatsbyjs/gatsby#26827]
I have create a gatsby site and it works fine in dev but it doesnt work on build.

Issue says
react-dom.production.min.js:209 Error: The result of this StaticQuery could not be fetched.

The query i'm using is to query image

***highlight.js***
```
    query Ipad {
      ipadA: file(relativePath: { eq: "ipad-a.png" }) {
        childImageSharp {
          fluid {
            ...GatsbyImageSharpFluid_withWebp
          }
        }
      }
    }

<Image fluid={ipadA.childImageSharp.fluid} />
```

***index.js***

```
import Highlight from './components/highlight.js'
const Home = () => (
  <div>
    <Highlight />
  </div>
)
```

**Comment by karltud123** [comment]
update: what i did now is move each image query to their own component and before i run `gatsby build` i remove .cache, public folder

that did the trick

**Comment by ascorbic** [comment]
Hi. I'm glad you've found a workaround, but this seems like it is a bug. You shouldn't need to clean the cache before building. To help us best begin debugging the underlying cause, it would be really helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

Thanks!

[reproduction]: https://gatsby.dev/reproduction

**Comment by karltud123** [comment]
you can check it out: https://github.com/karltud123/gatsby-btnt

On my local it is working fine, but when i try to build it, sometimes the images are not loading, and sometimes  the URL doesnt work, for example the url is `www.example.com/mysite`. This returns `File not found` but `www.example.com/mysite/index.html` is working (but URL is changing back to `www.example.com/mysite` on page load)

Thank you so much for the help.

**Comment by karltud123** [comment]
All working fine now, the issue was not relate to gatsby at all.. it was in the servers.

thank you very much,.
