### ISSUE TITLE
GASTBY - ERROR #85923 GRAPHQL There was an error in your GraphQL query: Cannot query field “tags” on type “MarkdownRemarkFrontmatter”

### ISSUE THREAD

**Issue by ReinheimerPiano** [gatsbyjs/gatsby#26881]
Hello!

I'm having a problem trying to run my website with gastby, both

above sea level start

how much

npm run build

. The Error in question is:

ERROR #85923  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "tags" on type "MarkdownRemarkFrontmatter".
Initially only this error is wrong, now I am facing several others related to GraphQL.

I have no idea what it might be.

If anyone can help, follow the repo link on Github.

repo Github ibbppta

Thanks in advance!

**Comment by ReinheimerPiano** [comment]
https://github.com/ReinheimerPiano/ibbppta

**Comment by ReinheimerPiano** [comment]
https://pt.stackoverflow.com/questions/472055/gastby-error-85923-graphql-there-was-an-error-in-your-graphql-query-cannot-q

**Comment by LekoArts** [comment]
Thank you for opening this!

Please follow our issue template in the future as the questions and requests are there to speed up the process (for both sides) :)
You've modified the https://github.com/netlify-templates/gatsby-starter-netlify-cms starter and probably broke it in the process. The specific error you mentioned comes from the fact that you don't have any blog posts in your /blog directory.

Your repo: https://github.com/ReinheimerPiano/ibbppta/tree/master/src/pages/blog
Starter: https://github.com/netlify-templates/gatsby-starter-netlify-cms/tree/master/src/pages/blog

Since you're querying for that data [here](https://github.com/ReinheimerPiano/ibbppta/blob/master/src/templates/blog-post.js#L99) you'll need to have markdown files that have `tags`.

I'd recommend starting fresh from the above starter and change it bit by bit. Also keep at least one markdown file in every directory so that the required data is there (unless you change the shape).

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
