### ISSUE TITLE
createRedirect with anchor not working

### ISSUE THREAD

**Issue by pacocom** [gatsbyjs/gatsby#26934]
## Description
Create redirect working but create redirect with anchor not working!

gatsby-node.js
```js
const { createRedirect } = actions;

const from = '/old-url';
const to = '/new-url';

createRedirect({
  fromPath: from,
  toPath: to,
  redirectInBrowser: true,
  isPermanent: true,
});
```

### Steps to reproduce
When I try to navigate from localhost:8000/old-url redirect to localhost:8000/new-url correctly! but when I try to navigate from localhost:8000/old-url# redirect to localhost:8000/new-url --> error! (anchor was deleted!).

### Expected result
Redirect navigation with hash is wrong!

What should happen?
Redirect with hash (anchor) with correct redirection.

Example:

### Environment
  System:
    OS: Windows 10 10.0.19041
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
  Binaries:
    Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.2 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.17 - /c/Python27/python
  Browsers:
    Edge: 44.19041.423.0

package.json
```json
    "gatsby": "2.23.3",
    "gatsby-image": "2.4.7",
    "gatsby-plugin-catch-links": "2.3.5",
    "gatsby-plugin-manifest": "2.4.11",
    "gatsby-plugin-meta-redirect": "1.1.1",
    "gatsby-plugin-react-helmet": "3.3.4",
    "gatsby-plugin-remove-serviceworker": "1.0.0",
    "gatsby-plugin-sass": "2.3.4",
    "gatsby-plugin-sharp": "2.6.11",
    "gatsby-plugin-typescript": "2.4.6",
    "gatsby-remark-autolink-headers": "2.3.5",
    "gatsby-remark-copy-linked-files": "2.3.5",
    "gatsby-remark-external-links": "0.0.4",
    "gatsby-remark-images": "3.3.10",
    "gatsby-remark-link-rewrite": "0.2.1",
    "gatsby-remark-prismjs": "3.5.4",
    "gatsby-remark-relative-images": "0.3.0",
    "gatsby-remark-responsive-iframe": "2.4.5",
    "gatsby-remark-smartypants": "2.3.4",
    "gatsby-source-filesystem": "2.3.11",
    "gatsby-transformer-json": "2.4.5",
    "gatsby-transformer-remark": "2.8.15",
    "gatsby-transformer-sharp": "2.5.5",
```

**Comment by LekoArts** [comment]
Thank you for opening this!

I tried this locally with an example project:

![image](https://user-images.githubusercontent.com/16143594/93755482-aa456f00-fc03-11ea-8a9d-aaa53344ae92.png)

The output of the store that plugins that interact with `createRedirect` is correct:

```js
exports.onPostBuild = ({ store }) => {
  const { redirects } = store.getState()

  console.log(redirects)
}
```

So you'll need to make sure to insert the correct `toPath` into the action and make sure that the plugin you're using is not messing up the final URL. Maybe open an issue on https://github.com/nsresulta/gatsby-plugin-meta-redirect or try out the plugin https://github.com/dhakerShiv/gatsby-plugin-client-side-redirect

Because the `createRedirect` action isn't doing anything, you'll need to use a plugin (as you already do) to handle on it.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
