### ISSUE TITLE
CSS breaking when using multiple themes

### ISSUE THREAD

**Issue by DWShuo** [gatsbyjs/gatsby#26952]
## Description
The two themes works fine when they are on their own, but when used together the css seems to break. I am using the gatsby-theme-blog and @wkocjan/gatsby-theme-intro to be more specific.

Another thing i found is that when used together gatsby-theme-blog does not appear to be picking up the content in the default location `content/posts`, i had to use contentPath option to point it to the new folder, is this behavior intended?

### Steps to reproduce

- yarn init -y
- yarn add gatsby react react-dom gatsby-theme-blog @wkocjan/gatsby-theme-intro
- edit gatsby-config.js with the following
```
module.exports = {
  siteMetadata: {
    description: "Test site",
    locale: "en",
    title: "TEST",
  },
  plugins: [
    {
      resolve: "@wkocjan/gatsby-theme-intro",
      options: {
        theme: "classic",
        basePath: "/",
      },
    },
    {
      resolve: `gatsby-theme-blog`,
      options: {
        basePath: `/blog`,
        contentPath: `blog/posts`,
        assetPath: `blog/assets`,
      },
    },
  ],
}
```
- gatsby develop

### Actual result
This is what the blog page ends up looking like, if i were to use gatsby-theme-blog on its own it turns out fine
![2020-09-16-180434_701x841_scrot](https://user-images.githubusercontent.com/8460330/93411464-14e75b00-f850-11ea-8d75-214b7b2eee80.png)

### Environment
  System:
    OS: Linux 5.8 Manjaro Linux
    CPU: (1) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 5.0.18 - /bin/bash
  Binaries:
    Node: 10.22.0 - ~/.nvm/versions/node/v10.22.0/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v10.22.0/bin/npm
  Languages:
    Python: 3.8.5 - /usr/bin/python
  Browsers:
    Firefox: 80.0.1
  npmPackages:
    gatsby: ^2.24.62 => 2.24.62 
    gatsby-theme-blog: ^2.0.2 => 2.0.2 
  npmGlobalPackages:
    gatsby-cli: 2.12.97
`

**Comment by LekoArts** [comment]
Thank you for opening this!

Sadly we can't give any immediate help with this as the underlying issue is that both themes use different CSS styling solutions (gatsby-theme-blog uses Theme UI, the other one postcss) and thus the styles will most likely overlap, override themselves and not work together. Which is unfortunate of course! If e.g. both themes would use Theme UI you could unify the style to one style.

You could use both themes separately (with `pathPrefix`) or copy the contents of one of the themes into the other project and override/remove parts.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by DWShuo** [comment]
Didn't realize they were using different CSS styling, thanks for pointing me in the right direction. In case someone else comes across the same problem here is a stack overflow post that helped a lot. https://stackoverflow.com/questions/55551076/how-to-combine-two-gatsby-sites-together
