### ISSUE TITLE
gatsby-plugin-emotions: Add style in header

### ISSUE THREAD

**Issue by SimonKlausLudwig** [gatsbyjs/gatsby#26964]
## Summary

I added Gatsby-plugin-emotions to my project. The plugin adds the styles tags right above the element. The w3c show me an error that "Element style not allowed as child of element div in this context".

Is there a way to add the styles generated by emotions into the head of the document ?

### Basic example

```
<style data-emotion-css="8atqhb">
    .css-8atqhb {
                            width: 100%;
       }
</style>

<div class="css-8atqhb e4v22nr1"></div>

```

**Comment by LekoArts** [comment]
Hi!

If you look at the HTML of https://using-emotion.gatsbyjs.org/ you'll see all the style tags in the `<head>`. This is the default behavior for production builds.

If this is not the case for you please [provide a minimal reproduction][reproduction] and we'll be able to take another look.

[reproduction]: https://gatsby.dev/reproduction

**Comment by SimonKlausLudwig** [comment]
Hey LekoArts, unfortunately even in your example the style tags are within the html code (See attached image)
![Uploading Bildschirmfoto 2020-09-21 um 10.44.26.png…]()

**Comment by LekoArts** [comment]
Ah, now I see what you mean.

You're looking at the generated HTML, I was referring to the HTML after Rehydration on the client (I was using the DevTools). Still, what you're describing is expected behavior as outlined here: https://emotion.sh/docs/ssr#default-approach

`gatsby-plugin-emotion` implements this default approach (and uses `babel-plugin-emotion`).

If you want a different behavior you'll probably have to remove the gatsby plugin and re-implement it on your own and/or ask on the emotion repository, e.g. https://github.com/emotion-js/emotion/issues/1370

On a personal note: I wouldn't care too much about W3C as in the case of Gatsby you'll serve the rehydrated website to most users anyways. I'll close this as it's an upstream issue.

**Comment by SimonKlausLudwig** [comment]
One of the main reasons to use Gatsby is the huge impact it has on your SEO. 

You will get warnings in most of the SEO-Checking-Tools (Seranking e.g.). That's why I think it makes sense to add the possibility to enable this option. 

Here are 6 Reasons why Valid HTML is important: https://www.searchenginejournal.com/google-valid-html/258881/#close
