### ISSUE TITLE
gatsby - javascript heap out of memory

### ISSUE THREAD

**Issue by TrevPennington** [gatsbyjs/gatsby#26981]
## Description

I have come across the 'Javascript heap out of memory' problem. I am using netlify cms if that matters. I've tried downgrading versions of various npm's as mentioned in other threads. None seem to work. I've also tried the 'export NODE_OPTIONS=--max_old_space_size=4096' solution. No success there either.

### Steps to reproduce

This is my project to reproduce: https://github.com/TrevPennington/trevpenningtonportfolio

### Expected result

gatsby develop works

### Actual result

gatsby develop fails with 'javascript heap out of memory error'

### Environment

  System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.10.0 - /usr/local/bin/node
    Yarn: 1.19.2 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 85.0.4183.102
    Safari: 14.0
  npmPackages:
    gatsby: ^2.10.5 => 2.24.63 
    gatsby-image: ^2.4.19 => 2.4.19 
    gatsby-plugin-netlify: ^2.3.15 => 2.3.15 
    gatsby-plugin-netlify-cms: ^2.10.5 => 4.3.14 
    gatsby-plugin-purgecss: ^5.0.0 => 5.0.0 
    gatsby-plugin-react-helmet: ^3.3.11 => 3.3.11 
    gatsby-plugin-sass: ^2.3.13 => 2.3.13 
    gatsby-plugin-sharp: ^2.6.36 => 2.6.36 
    gatsby-remark-copy-linked-files: ^2.3.15 => 2.3.15 
    gatsby-remark-images: ^3.3.30 => 3.3.30 
    gatsby-remark-relative-images: ^0.3.0 => 0.3.0 
    gatsby-source-filesystem: ^2.3.30 => 2.3.30 
    gatsby-transformer-remark: ^2.8.35 => 2.8.35 
    gatsby-transformer-sharp: ^2.5.15 => 2.5.15 
  npmGlobalPackages:
    gatsby-cli: 2.10.10

**Comment by pvdz** [comment]
The dependencies in the project are super old. I wouldn't be surprised if that was causing the problems. Your Gatsby version is over a year old, for example.

The problem appears to stem from using styled-icons where the css pruning plugin does not do its job properly. The build also ends in a crash for me, due to syntax errors.

I would suggest to first make sure your dependencies are up to date and to look into why the styled-icons library is not properly shaken.

If the webpack-js step is taking a long time that means a lot JS is being included (and minified). Often large JS bundles being minified increases the memory requirement. But it's also a bad tell. A 13 page site should not be hitting 1mb JS payloads.

Good luck.

**Comment by ascorbic** [comment]
Hi @TrevPennington 
@pvdz is correct that you should upgrade to latest Gatsby. Hwoever I think I've fixed your immediate issue. You need to change your styled-icons import to import the specific icon. In `src/components/AboutMe.js`

```diff
- import { TriangleDown } from 'styled-icons'
+ import { TriangleDown } from '@styled-icons/octicons/TriangleDown'
```

**Comment by TrevPennington** [comment]
@pvdz and @ascorbic thank you. The downgrading was an attempt to use other threads' solutions on this. Turns out it was the styled-icon! I appreciate it.
