### ISSUE TITLE
There was a problem parsing  ... any GraphQL fragments or queries in this file were not processed.

### ISSUE THREAD

**Issue by simonjoom** [gatsbyjs/gatsby#27161]
Hi,
Here sometimes gatsby cannot finish processing query and give this error because some bad code ...

In my case i found out  that if you important 2 times same lib it's creating the error and unfortunately there is no help to know where is the line in cause... i spent hours to find the problem. and it wasn't from graphql query.

i did
import { ApolloProvider } from "react-apollo";

import { graphql as graphqlap, compose, withApollo, ApolloProvider } from "react-apollo"; <-duplicate ApolloProvider.

Is there any solution to make this process without hog?

**Comment by LekoArts** [comment]
Thank you for opening this!

This isn't necessarily something that Gatsby can fix, I'd say you can catch those issues with a linter like https://eslint.org/. Gatsby had problems parsing the file because it was invalid but it should have given the file name that was problematic. This way you can pin point the issue -- anyways, a linter will help you with these issues in the future.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
