### ISSUE TITLE
Gatsby not creating page with filename "template-create"

### ISSUE THREAD

**Issue by shripadk** [gatsbyjs/gatsby#27174]
## Description

Gatsby is not picking up a file with the name `template-create` in any folder/sub-folder within the `src/pages` directory. Works perfectly fine with other names.

### Steps to reproduce

Create a `template-create.js` or `template-create.tsx` file anywhere in the `src/pages` directory and try navigating in the browser.

Have provided a minimal reproduction case here for anyone wanting to try: https://github.com/shripadk/test-repo

### Expected result

Should render a page with "Hello World".

### Actual result

Get a 404 instead.

This is with `template-create.tsx` file in `src/pages` ( https://localhost:8000/template-create )

<img width="834" alt="template-create.tsx in src/pages" src="https://user-images.githubusercontent.com/189344/94595546-9e634800-02a8-11eb-963a-c019bddf0425.png">

This is with `template-create.js` file in `src/pages/admin` ( https://localhost:8000/admin/template-create )

<img width="834" alt="template-create.js in src/pages/admin" src="https://user-images.githubusercontent.com/189344/94595958-19c4f980-02a9-11eb-913f-15f1fd8ce477.png">

### Environment

```bash
 ~/@/test-repo:master > gatsby info --clipboard

  System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
    Shell: 2.6.0 - /usr/local/bin/fish
  Binaries:
    Node: 10.18.1 - /usr/local/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Languages:
    Python: 2.7.14 - /Users/shripadkrishna/.nix-profile/bin/python
  Browsers:
    Chrome: 85.0.4183.121
    Firefox: 74.0
    Safari: 14.0
  npmPackages:
    gatsby: ^2.24.66 => 2.24.66
    gatsby-image: ^2.4.20 => 2.4.20
    gatsby-plugin-manifest: ^2.4.32 => 2.4.32
    gatsby-plugin-offline: ^3.2.29 => 3.2.29
    gatsby-plugin-react-helmet: ^3.3.12 => 3.3.12
    gatsby-plugin-sharp: ^2.6.37 => 2.6.37
    gatsby-source-filesystem: ^2.3.31 => 2.3.31
    gatsby-transformer-sharp: ^2.5.16 => 2.5.16
```

**Comment by LekoArts** [comment]
Thank you for opening this!

This is expected behavior as Gatsby [ignores files starting with `template-`](https://github.com/gatsbyjs/gatsby/blob/293b471fcfea2ed530686af560dfaa313a2dc832/packages/gatsby-page-utils/src/validate-path.ts#L25). This was added back in 2017 -- probably with the intention to bring people to put their templates into a `src/templates` folder or that people can store their templates in `src/pages` without creating pages for them.

Anyways, removing that behavior would be a breaking change so for now you'll need to rename your files if your intention for them is to be created :)

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by shripadk** [comment]
@LekoArts Thank you so much for the clarification. I did not know this as it wasn't documented anywhere. Makes complete sense.
