### ISSUE TITLE
Questions regarding @typescript-eslint/eslint-plugin & @typescript-eslint/eslint-parser updates

### ISSUE THREAD

**Issue by hzhu** [gatsbyjs/gatsby#27177]
## Summary

I noticed that there are only Renovate PRs opened for minor versions of `@typescript-eslint/eslint-plugin` and `@typescript-eslint/eslint-parser`, e.g. https://github.com/gatsbyjs/gatsby/pull/27080.

It seems like a [requirement](https://github.com/typescript-eslint/typescript-eslint/issues/2540#issuecomment-692866111) to use the latest versions of `@typescript-eslint/eslint-plugin` and `@typescript-eslint/eslint-parser` require project dependencies (such as Gatsby?) to be up-to-date with `v4` at least. We've a project that [indicates](https://github.com/zendeskgarden/website/pull/184#pullrequestreview-497945525) Gatsby might be the reason we aren't able to upgrade `@typescript-eslint/eslint-plugin` to `v4`.

## Questions 

Does Gatsby plan on updating major versions of `@typescript-eslint/eslint-plugin` and `@typescript-eslint/eslint-parser`?

**Comment by LekoArts** [comment]
Seems like Gatsby is not at fault? https://github.com/zendeskgarden/react-components/pull/871#issuecomment-700910188

**Comment by hzhu** [comment]
Hi @LekoArts 👋  

I pointed to the incorrect link earlier. It should have pointed here instead: https://github.com/zendeskgarden/website/pull/184#pullrequestreview-497945525

**Comment by LekoArts** [comment]
Ok, I see. We'll have to look into the breaking changes for the major change. In the meantime you can force the version by using `yarn resolutions`: https://classic.yarnpkg.com/en/docs/selective-version-resolutions/

**Comment by hzhu** [comment]
Awesome, that sounds great. Yarn's resolution should work in the meantime. Thank you! 🙏

**Comment by ROHIT498** [comment]
I have the same problem, although it's for all files.

$ yarn list --pattern "typescript"
yarn list v1.22.4
├─ @babel/plugin-syntax-typescript@7.8.3
├─ @babel/plugin-transform-typescript@7.8.3
├─ @babel/preset-typescript@7.8.3
├─ @typescript-eslint/eslint-plugin@2.24.0
├─ @typescript-eslint/experimental-utils@2.24.0
├─ @typescript-eslint/parser@2.24.0
├─ @typescript-eslint/typescript-estree@2.24.0
├─ typescript-tslint-plugin@0.5.5
└─ typescript@3.8.3
VSCode Eslint version: 2.1.1

module.exports = {
    root: true,
    parser: '@typescript-eslint/parser',
    plugins: [
        '@typescript-eslint',
    ],
    parserOptions: {
        tsconfigRootDir: __dirname,
        project: ['./tsconfig.json'],
    },
    extends: [
        'eslint:recommended',
        'plugin:@typescript-eslint/eslint-recommended',
        'plugin:@typescript-eslint/recommended',
        'plugin:@typescript-eslint/recommended-requiring-type-checking',
    ],
};
Do you know how the vscode plugin watches for changes and adds new files to compilation context ? I feel that’s where the issue is.

This issue is happening for our whole team currently across VSCode and Atom IDEs. Our only solution has been to remove node_modules and reinstall all packages. It usually happens when pulling in new files from Git.

**Comment by hzhu** [comment]
> I have the same problem

Are you using Gatsby? How come it isn't listed in your `yarn list` tree? It doesn't seem like the same problem as this issue.

**Comment by ROHIT498** [comment]
Ya but i have provided to just give an idea of using yarn

**Comment by jens-duttke** [comment]
Is there an update? I have another dependency which requires @typescript-eslint `v4`, while Gatsby is using `v2.34.0`.

**Comment by LekoArts** [comment]
This was fixed by https://github.com/gatsbyjs/gatsby/pull/29388
