### ISSUE TITLE
Badge

### ISSUE THREAD

**Issue by JimLynchCodes** [gatsbyjs/gatsby#27186]
Hey, the gatsby badge on my profile just disappeared! 😢

Is Gatsby going away? Maybe it got bought out and is being privatized?

Welp, RIP Gatsby. It was great while it lasted! ♥️

**Comment by LekoArts** [comment]
Hi! I think you're misunderstanding some GitHub features here. You had the badge because you were a member of the GitHub organization. As explained in https://www.gatsbyjs.com/blog/2020-08-04-gh-community-permissions-changes-gatsbyjs we removed those permissions.

Nothing else changed with Gatsby and the open-source project :)
