### ISSUE TITLE
repo configuration thoughts

### ISSUE THREAD

**Issue by jquense** [gatsbyjs/gatsby#2719]
It occurs to me that we don't have to locate everything under `/packages` but can specify a few globs. Would it make sense to organize the repo a bit more inline with how we organize gatsby packages? e.g.

```
- plugins
- transformers
- source
- core
- libraries (or packages?) stuff like the babel presets, skip-limit, etc.
```

**Comment by jquense** [comment]
might even include `examples` there for yarn (not lerna) so you get easier to work on installs with the local gatsby versions

**Comment by KyleAMathews** [comment]
Makes sense to me! Yeah `packages` is already pretty huge and we'll add more so more organization sounds great.

**Comment by Chuloo** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues as many of them have already been resolved with the latest updates or explained in a previous issue.

Feel free to [open a new one](https://github.com/gatsbyjs/gatsby/issues/new/choose) if you still experience this problem or a similar one! 👍

**Comment by moonmeister** [comment]
@KyleAMathews We still interested in doing this?

**Comment by KyleAMathews** [comment]
Perhaps? It's not a pain point for me but it could be confusing to others?
