### ISSUE TITLE
How to throw 401/403 for anything that matches /admin/*

### ISSUE THREAD

**Issue by ProteanCode** [gatsbyjs/gatsby#27193]
I am writing a CMS that fetches a lot of content from API, and one thing I know for sure is that if user access the url like `/admin/invoices` without being authorized by `authorize()` method.

My way of thinking about that comes from Laravel framework, so lets say we have such a page in our src directory:

`/src/pages/admin/invoices`

When we enter the `/admin/invoices` URL in the browser, I expect that there is a way to return 401/403 on `/admin` without even going into further URL segments.

So far I only found that I need to spam massive `PrivateRoute` component which is hard to manage. I would really have something like `PrivateGroup` in which I can just use normal routes

**Comment by wardpeet** [comment]
You're using client side routes I assume so PrivateRoute is sadly the way you have to go. 
https://www.gatsbyjs.com/docs/client-only-routes-and-user-authentication/

Gatsby can't set a 403 itself but you can configure your hosting to do it if you have control over it.

**Comment by pieh** [comment]
> Gatsby can't set a 403, but it can host itself on custom port like 8000, which basically requires a some form of a web server that can handle any HTTP response code?

`gatsby develop` that by default have server listening on 8000 is development server used with development bundles and it's not meant for production scenarios. Similarly `gatsby serve` (which defaults to port 9000) is really just thin wrapper around `express` setup with `express.static` to serve static assets produced by `gatsby build` - while this "serves" production version of the site, goal of it is to have some quick way to spin up server to manually verify production builds locally or for e2e tests. Technically you could use either to serve your site but it's really not advised and especially with `develop` variant it's straight dangerous because `/___graphiql` endpoint give access to all the data in data store.

Gatsby is meant to produce static assets that are hosted on CDNs - at least for production sites.

**Comment by ProteanCode** [comment]
> > Gatsby can't set a 403, but it can host itself on custom port like 8000, which basically requires a some form of a web server that can handle any HTTP response code?
> 
> `gatsby develop` that by default have server listening on 8000 is development server used with development bundles and it's not meant for production scenarios. Similarly `gatsby serve` (which defaults to port 9000) is really just thin wrapper around `express` setup with `express.static` to serve static assets produced by `gatsby build` - while this "serves" production version of the site, goal of it is to have some quick way to spin up server to manually verify production builds locally or for e2e tests. Technically you could use either to serve your site but it's really not advised and especially with `develop` variant it's straight dangerous because `/___graphiql` endpoint give access to all the data in data store.
> 
> Gatsby is meant to produce static assets that are hosted on CDNs - at least for production sites.

Thanks. This explains a lot and helps me to understand why my routing / authorization approach is invalid. Not sure if this should be noted in https://www.gatsbyjs.com/docs/quick-start/ or rather obvious to most of people that spent some time with node-based solutions.
