### ISSUE TITLE
How can I prevent gatsby-plugin-mdx from automatically creating mailto links?

### ISSUE THREAD

**Issue by lumenwrites** [gatsbyjs/gatsby#27216]
Hi! Right now the mdx plugin seems to automatically detect emails in my mdx files (hello@mywebsite.com), and replacing them with mailto links. Is there a way to prevent that? I want to keep emails as plain text.

**Comment by pieh** [comment]
Not ideal, only way I can think of is to use `gfm: false` in plugin options for `gatsby-plugin-mdx` (that's not really documented, I had to dig in the code pretty deep for that). GFM = GitHub Flavoured Markdown which adds few features like autolinking - but it's not limited to that and it might cause issues elsewhere - so use with caution.

**Comment by pieh** [comment]
This is also maybe question better directed at `@mdx-js/mdx` package / repository - `gatsby-plugin-mdx` does pass plugin options to that package and it's not doing autolinking on gatsby level (it happens in mdx and even more precisely in `remark-parse` package - there's multiple levels in there).

https://github.com/remarkjs/remark/blob/main/packages/remark-parse/lib/tokenize/email.js is the actual thing that autolink emails in plaintext (this is where I found that `gfm: false` could short circuit it - but maybe there are other options to do so - and that's where asking that question upstream might give you more details.

I will mark this as upstream and close, because this is not directly in gatsby(-plugin-mdx) control.
