### ISSUE TITLE
I cannot edit css in Chrome Developer tools using gatsby develop

### ISSUE THREAD

**Issue by khanakia** [gatsbyjs/gatsby#27256]
## Summary
I just started using gatsby and i am running gatsby using `gatsby develop` and i have css include but when i go to the chrome developer tools and try to make changes to css i cannot. Css options are disabled. I saw on internet it's because of CSSDOM Injection so how to disable CSS DOM Injection so i can edit css or is there any other solution >

## Relevant information
CSS are disabled
<img width="1368" alt="Screenshot 2020-10-03 at 12 19 06 PM" src="https://user-images.githubusercontent.com/2174170/94985250-a3f3b300-0572-11eb-850e-c374f02031f4.png" />

### Environment (if relevant)

```

  System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.6.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.7 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 85.0.4183.121
    Firefox: 81.0
    Safari: 13.1.2
  npmPackages:
    gatsby: ^2.24.63 => 2.24.66
    gatsby-plugin-prefetch-google-fonts: ^1.4.3 => 1.4.3
    gatsby-plugin-sass: ^2.3.14 => 2.3.14
  npmGlobalPackages:
    gatsby-cli: 2.12.101

```

### File contents (if changed)

`gatsby-config.js`:
```
module.exports = {
  /* Your site config here */
  plugins: [
    `gatsby-plugin-sass`
  ],
}
```
`gatsby-browser.js`:
```
import 'bootstrap/dist/css/bootstrap.css';
import "./src/resources/lib/fontawesome5131/css/all.min.css"
import "./src/resources/fonts/inter-font/stylesheet.css"
import "./src/resources/sass/main.scss"
```

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by khanakia** [comment]
@LekoArts the issue resolver automatically very strange. I did not made any changes at all. But anyway now i can edit my css styles directly in the developer tools :smiley: Thanks you very much 👍
