### ISSUE TITLE
Styling not loading on components using styled-components without first visiting homepage

### ISSUE THREAD

**Issue by Ashto10** [gatsbyjs/gatsby#27502]
## Description
Apologies in advance, it appears this is a frequently asked question, but I've been unable to fix my issue by following many of the answers listed previously.

I'm building a basic blog template using Gatsby, and opted to use the styled-components plugin to handle the css side of things. Styling works well throughout the site when using `gatsby develop`, but the navigation bar appears to break when using `gatsby serve`. It appears that the styling does not load specifically for the navigation bar if users don't first visit the site's index, although other components are unaffected.

### Attempted solutions

- Verified that "gatsby-plugin-styled-components" was included in the plugins array in gatsby-config.js
- Tried adding "babel-plugin-styled-components" as a dependency to see if the issue relates to server-side rendering
- In [navigation.js](https://github.com/Ashto10/gatsby-styled-components-issue/blob/master/src/components/navigation.js), the component's body is wrapped in a @reach/router `<Location>` tag. Attempted to remove it to see if that was the culprit

- The instant I submitted this ticket, I remembered that the `<Navigation>` component is the only one being passed props in order to determine styling. Sure enough, removing the props allows the component to display properly.

### Steps to reproduce

1. Set up the site as in this [minimal reproduction](https://github.com/Ashto10/gatsby-styled-components-issue/blob/master/src/components/navigation.js)

2. Run `gatsby build`, then `gatsby serve`

3. Navigate directly to http://localhost:9000/about

### Expected result

The navigation background should be blue to match the paragraph text.

### Actual result

The navigation appears to be unstyled, although other components on the page work as expected. By either clicking home, or by navigating directly to https://localhost:9000, the navigation styling will load and display properly throughout the site.

### Environment

  System:
    OS: Windows 10 10.0.17134
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
  Binaries:
    Node: 12.18.4 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 86.0.4240.75
    Edge: Spartan (42.17134.1.0)
  npmPackages:
    gatsby: ^2.24.79 => 2.24.79 
    gatsby-plugin-styled-components: ^3.3.14 => 3.3.14 
  npmGlobalPackages:
    gatsby-cli: 2.12.101

**Comment by Ashto10** [comment]
On further research, this appears to be a duplicate issue of #9918

**Comment by LekoArts** [comment]
Thank you for opening this!

As you have noticed this is an SSR issue where the client-side content is different from the one in the HTML. This is because the `Location` component you used isn't returning anything on the build. Gatsby automatically provides that information for each page in `src/pages` or in the `wrapPageElement` API.

I created a PR to your example repo which works: https://github.com/Ashto10/gatsby-styled-components-issue/pull/1

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
