### ISSUE TITLE
gatsby build doesn't clean all old build files

### ISSUE THREAD

**Issue by baseten** [gatsbyjs/gatsby#2751]
Multiple copies of app-&ast;.js and component--src-&ast;.js are added during `gatsby build`. 

app-&ast;.js file seems to be created every time whereas component--src-&ast;.js files only during some builds. I'm having to run rimraf during prebuild to workaround this at the moment.

**Comment by KyleAMathews** [comment]
We consider having having old copies of js files a good thing. The reason is that gatsby sites are single page apps so someone could leave a site open for a while and then click to a new part of the site which will trigger fetching new JavaScript. If you've redeployed since they opened the site and deleted older js then the user's request will fail.

tl;df it's perfectly safe and a good thing to do to leave older copies of JavaScript bundle files around which is why we don't delete them automatically (like we do html files).

**Comment by theredwillow** [comment]
Could you figure out a way to clean files that have been touched though? Simple file renaming is identified by source control, but I have to remember to run clean for Gatsby.
