### ISSUE TITLE
Date Format String Causes an issue

### ISSUE THREAD

**Issue by sumanchapai** [gatsbyjs/gatsby#27516]
## 

A certain pattern on date format string on graphql query causes error specifically ``MMM DD``

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

{
      allSanityCalendar(sort: { order: ASC, fields: date }) {
        nodes {
          title
          date(formatString: "MMM DD")
          remaingTime: date(fromNow: true)
          timeFrom(formatString: "HH:MM")
          timeTo(formatString: "HH:MM")
          isUpdated
        }
      }
    }
  `)

How to Make a Minimal Reproduction: https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/

### Expected result

What should happen?

### Actual result

What happened.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.
System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Shell: 3.1.2 - /usr/local/bin/fish
  Binaries:
    Node: 12.18.3 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.7 - /usr/local/bin/npm
  Languages:
    Python: 3.7.7 - /opt/anaconda3/bin/python
  Browsers:
    Chrome: 86.0.4240.80
    Firefox: 80.0.1
    Safari: 12.1.2
  npmPackages:
    gatsby: ^2.24.66 => 2.24.66
    gatsby-background-image: ^1.1.2 => 1.1.2
    gatsby-image: ^2.4.21 => 2.4.21
    gatsby-plugin-google-fonts: ^1.0.1 => 1.0.1
    gatsby-plugin-postcss: ^3.0.1 => 3.0.1
    gatsby-plugin-sharp: ^2.6.40 => 2.6.42
    gatsby-source-filesystem: ^2.3.34 => 2.3.34
    gatsby-source-sanity: ^6.0.4 => 6.0.4
    gatsby-transformer-json: ^2.4.14 => 2.4.14
    gatsby-transformer-sharp: ^2.5.17 => 2.5.17
  npmGlobalPackages:
    gatsby-cli: 2.12.65

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

I've used [our example project](https://graphql-reference-1124782374.gtsb.io/___graphql?query=%7B%0A%20%20books%3A%20allMarkdownRemark(filter%3A%20%7Bfrontmatter%3A%20%7Btitle%3A%20%7Bne%3A%20%22%22%7D%7D%7D)%20%7B%0A%20%20%20%20totalCount%0A%20%20%20%20edges%20%7B%0A%20%20%20%20%20%20node%20%7B%0A%20%20%20%20%20%20%20%20frontmatter%20%7B%0A%20%20%20%20%20%20%20%20%20%20date%0A%20%20%20%20%20%20%20%20%20%20formattedDate%3A%20date(formatString%3A%20%22MMM%20DD%22)%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A&explorerIsOpen=false) and the query is working fine.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by sumanchapai** [comment]
Seems like it's working for me today. I couldn't reproduce the issue myself in the same environment…so, i think we can close the thread now. Thanks again though!
