### ISSUE TITLE
Testing with ava fails

### ISSUE THREAD

**Issue by syzer** [gatsbyjs/gatsby#2756]
I get `TypeError: graphql is not a function`

Babel / test config
```
"babel": {
    "presets": "react-app"
  },
  "ava": {
    "babel": "inherit",
    "require": [
      "babel-register",
      "ignore-styles",
      "./server/test-setup"
    ]
  }
```

Is there any `babel/transpiler` preset that we could use to skip/ or set gatsby code to be ok?: 
```js
export const query = graphql`
 query IndexQuery {
  site {
    siteMetadata {
      id
     }
   }
}`
```

**Comment by syzer** [comment]
was thinking to sth along those lines
```js
const jsdom = require('jsdom')
const { JSDOM } = jsdom

const { document } = new JSDOM('<body></body>').window
global.document = document
global.window = document.defaultView
global.navigator = window.navigator
global.graphql = require('graphql')
```
wdyt?

**Comment by Chuloo** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues as many of them have already been resolved with the latest updates or explained in a previous issue.

Feel free to [open a new one](https://github.com/gatsbyjs/gatsby/issues/new/choose) if you still experience this problem or a similar one! 👍
