### ISSUE TITLE
Page html is cached by client for too long? gatsby-plugin-netlify

### ISSUE THREAD

**Issue by Ortimis** [gatsbyjs/gatsby#27696]
## Description

When updating page data and deploying the changes on netlify, the client only registers the changes when the page is reloaded a second time - even multiple days after the update. 

### Steps to reproduce

- Publish your Gatsby Project on Netlify,
- Update Content such that page html is changed
- Check with multiple clients whether you see the changes

### Expected result

Changed Content should be immediately visible

### Actual result

Changes are only visible after explicit page reload

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.
```
  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
  Binaries:
    Node: 12.18.4 - c:\Program Files\nodejs\node.EXE
    npm: 6.14.6 - c:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.18362.449.0)
  npmPackages:
    gatsby: ^2.24.77 => 2.24.80 
    gatsby-image: ^2.4.19 => 2.4.19 
    gatsby-plugin-eslint: 2.0.8 => 2.0.8 
    gatsby-plugin-gdpr-cookies: ^1.0.10 => 1.0.10 
    gatsby-plugin-manifest: 2.4.18 => 2.4.18 
    gatsby-plugin-netlify-cms: ^4.3.15 => 4.3.15 
    gatsby-plugin-netlify-cms-paths: ^1.3.0 => 1.3.0 
    gatsby-plugin-offline: 3.2.17 => 3.2.17 
    gatsby-plugin-postcss: 2.3.11 => 2.3.11 
    gatsby-plugin-react-helmet: 3.3.10 => 3.3.10 
    gatsby-plugin-scroll-reveal: 0.0.7 => 0.0.7 
    gatsby-plugin-sharp: ^2.6.19 => 2.6.19 
    gatsby-source-airtable: ^2.1.1 => 2.1.1 
    gatsby-source-filesystem: ^2.3.19 => 2.3.29 
    gatsby-transformer-remark: ^2.8.25 => 2.8.34 
    gatsby-transformer-sharp: ^2.5.15 => 2.5.15 
  npmGlobalPackages:
    gatsby: 2.24.90
```

**Comment by noahsb** [comment]
I'm no expert, but I believe that this is intentional. See [here](https://www.gatsbyjs.com/docs/caching/). You should be able to control what is cached and for how long, depending on what you're working on. 
It also looks like the [gatsby-plugin-netlify](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-netlify) already automates the creation of caching headers and you might need to modify it to your use case. 
Again, no expert, but that's what I found.
