### ISSUE TITLE
Declaration or statement expected in reporter.d.ts

### ISSUE THREAD

**Issue by reachchris** [gatsbyjs/gatsby#27690]
Hello

When running the lint with gatsby version "2.24.88" I get the following error

## Description
```
node_modules/gatsby-cli/lib/reporter/reporter.d.ts:86:1 - error TS1128: Declaration or statement expected.

86 export type { Reporter };
   ~~~~~~

node_modules/gatsby-cli/lib/reporter/reporter.d.ts:86:13 - error TS1005: ';' expected.
```

86 export type { Reporter };
               ~

Found 2 errors.

Something wrong with rimraf or how can we resolve this?

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by reachchris** [comment]
This issue was no longer present after updating TypeScript version.
