### ISSUE TITLE
Gatsby Starter page showing "Updated Invalid Date" for each starter

### ISSUE THREAD

**Issue by NguyenDa18** [gatsbyjs/gatsby#27758]
## Description

Gatsby starter page showing ""Updated Invalid Date"

### Steps to reproduce

Go to link https://www.gatsbyjs.com/starters/? , reset all filters and you will see result

### Expected result
Dates should be valid, in MM DD, YYYY or MM/DD/YYYY format, etc.

What should happen?
Dates should be in correct format.

### Actual result
What happened.
Seeing "Invalid Date" in place of actual date, could be a date parsing bug.

<img width="1605" alt="gatsby-invalid-date-starters" src="https://user-images.githubusercontent.com/14105469/97799036-20b09600-1be0-11eb-99c0-c116dc37fbb0.png">

**Comment by rexindan** [comment]
I've been trying to take a look at this issue, but this part of 'gatsby develop' takes too long to wait, to check my guess in code
```
not finished Generating image thumbnails - 4630.980s
```
**Can some cache be used during this stage to speed things up or some dummy image maybe?**


Nevertheless, basing on what I've found, this issue is clearly connected to
```
./www/src/views/starter-library/starter-list.js

175 <div sx={{ display: `inline-block`, fontSize: 0 }}>
176   Updated {new Date(lastUpdated).toLocaleDateString()}
177 </div>
```
and
```
./www/src/views/starter-library/filtered-starters.js
14 import StarterList from "./starter-list" // imports 'Starter'
235 <StarterList // uses 'Starter'

./www/src/views/starter-library/starter-list.js
218 export default StartersList // whereas export is 'StarterS'
```
though.

If someone gives me an advice on how to speed up 'gatsby develop' loading stage, I will continue looking.

**Comment by LekoArts** [comment]
Thanks for the issue, we're aware of it and a fix is currently in flight!
