### ISSUE TITLE
[Feature Request] Choosing which data to pull in from WordPress site

### ISSUE THREAD

**Issue by SilasOtoko** [gatsbyjs/gatsby#2780]
I'm working on an app currently that only requires me to pull in WordPress Media and ACF data. Unfortunately the site has a bunch of other data from other plugins that I don't want to pull in and will never use, so it would be nice to be able to specify things like fetching only the WordPress Posts, Pages, Media, and ACF data.

@KyleAMathews suggested that blacklisting sources could be a good solution.

**Comment by sebastienfi** [comment]
Hello! 
The source plugin will create grahql nodes for the whole set of data exposed using the rest API, but as long as you don't query it in your templates or layout it won't be loaded client side. So, this is your way to filter.
What use case are you trying to improve ?

**Comment by SilasOtoko** [comment]
I guess the pain I'm feeling is server side. Every time I have to restart my local server it takes 5 minutes or so to grab all the data. It could also be giving me trouble deploying the app with Surge, but I don't know for sure on that yet.

**Comment by KyleAMathews** [comment]
It'd be really nice too if WordPress allowed for requesting only data updated or new since the last time the site was built.

A slightly hacky way of doing this is since the API does allow for ordering by modification date, use that & grab the last 10 modified posts — then check that data to see if the oldest post is older than the last time you fetched data. If it is, then don't fetch more. If not, keep fetching back until you're past the last fetched date.

**Comment by KyleAMathews** [comment]
Hey, closing out old issues. Please re-open if you have additional questions, thanks!
