### ISSUE TITLE
Flow: How to implement flow in a gatsby project ?

### ISSUE THREAD

**Issue by abumalick** [gatsbyjs/gatsby#2784]
I searched in the examples and package folder and couldn't find something about it.

Has someone integrated flow in a gatsby project ?

I would like to use flow with this https://github.com/brigand/babel-plugin-flow-react-proptypes

**Comment by jquense** [comment]
Same way you might in a none gatsby project! Add the dependencies and Babel plugin and gtg

**Comment by abumalick** [comment]
okay, I will try that, thank you very much

**Comment by abumalick** [comment]
It worked very well, I didn't know that you can edit babel config so easily with gatsbyjs. Thank you very much for the tip @jquense.

**Comment by dustinhorton** [comment]
@abumalick Mind sharing your how it's setup?

**Comment by camsloanftc** [comment]
In case this helps someone, we just did:

`yarn add --dev babel-preset-flow flow-bin`

then since we are using gatsby's babel here to strip the flow-types, you need to add this to your `gatsby-node.js` file: 
``` javascript
exports.modifyBabelrc = ({ babelrc }) => ({
	...babelrc,
	presets: babelrc.presets.concat(['flow']),
})```

then you should be able to run `yarn run flow init` to set up the `.flowconfig` file, and then run `yarn run flow` to check your files.

Then add whatever plugin you need to your editor to setup the highlighting, but that is a different subject.

For a simple flow check, just follow the example at the [docs](https://flow.org/en/docs/usage/). Don't forget to add `// @flow` to the top of your files.

**Comment by abumalick** [comment]
sorry @dustinhorton I didn't see your message.

Here is an example of a flow configuration with eslint and prettier : https://github.com/abumalick/gatsby-starter

You have some examples of using flow with React in `src/components`.

I really like these tools.

Maybe I could add this in starter kits.

**Comment by sarneeh** [comment]
Actually, as `babel-preset-flow` is part of `babel-preset-react` which is by default in Gatsby you don't need this additional configuration. `flow-bin` will be just enough 😄

**Comment by arhtudormorar** [comment]
Check [this ](https://stackoverflow.com/a/51358194/4264699) setup out - for me it works.
