### ISSUE TITLE
Markdown isn't rendering as expected

### ISSUE THREAD

**Issue by rutikwankhade** [gatsbyjs/gatsby#27870]
## Description

The markdown files are rendering as plain text. for example
`# h1` 
is rendering as
h1 only
### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

How to Make a Minimal Reproduction: https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/

### Expected result

`# heading` should be displayed as 
# heading
### Actual result
but it is rendered as h1 i.e. plain text

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

I tried implementing solutions from the following issues,
https://github.com/gatsbyjs/gatsby/issues/10874
https://github.com/gatsbyjs/gatsby/issues/10510

but the problem still exists.

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by rutikwankhade** [comment]
Thanks for the quick response. Sorry I couldn't create a minimal reproduction. But here is the repo where I hosted the code https://github.com/rutikwankhade/rutikwankhade.dev

I am using tailwindcss with gatsby and this issue is frustrating me a lot. a little help would be very helpful.

**Comment by dannycahyo** [comment]
I have the same issues. I've already used HTML to display my markdown file. For example like this : 
 `<div dangerouslySetInnerHTML={{ __html: html }}  />`
 I still can't display the markdown file properly, here is the case. I want to display ## Heading 2, but it just shows Heading 2, which is just plain text.
 Besides, I also use Chakra UI. And based on @rutikwankhade suggestion, I've set my global layout.css file like this :
`h1{font-size:2em;}
h2 { font-size: 1.5em; }
h3 { font-size: 1.17em; }
h4 { font-size: 1.12em; }
h5 { font-size: .83em; }
h6 { font-size: .75em; }`
 
 Can anyone give me the solution, please?
