### ISSUE TITLE
  TypeError: Cannot read property 'initial' of undefined

### ISSUE THREAD

**Issue by pungggi** [gatsbyjs/gatsby#2798]
here is my repo: https://github.com/pungggi/agrama

when launching npm run build

I got 
![image](https://user-images.githubusercontent.com/5635709/32414060-0874cc1e-c21f-11e7-958a-0d161ca6b1bf.png)

**Comment by emmafallancy** [comment]
Hi @pungggi , seems like it's caused by the importing of `terms` page in `footer` component in line 4. Would you be able to confirm that it's able to build the JavaScript bundle once you remove it or commented it, since it's not being used in `footer` component?

Also, when JavaScript bundle successfully being build, you might encounter error where `document` or `window` is undefined. It that happens, you may refer to [error in debugging html build](https://www.gatsbyjs.org/docs/debugging-html-builds/)

Let me know how it goes and I hope the above might help you 😄

**Comment by pungggi** [comment]
Thank you, it was this and another import, same with document.. (I thougt that this could fail, still experimenting..) very nice, thank you for your time
