### ISSUE TITLE
Client-only route not working

### ISSUE THREAD

**Issue by wonder-dev** [gatsbyjs/gatsby#28002]
I have an issue with the setting of client-only route with the new file system route api. I have set a file src/pages/products/[calegorySlug].js but every time I try to go to the page in the browser, I'm redirected to the 404 of gatsby.

can you send me more infos about this kind of settings because the documentation is unclear for me

- do I need to use some plugins/source
- do I need to setup something in the gatsby-node.js
- do I need to setup something else in the source code

thank's in advance,

Grégory

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by wonder-dev** [comment]
Ok I found, what's wrong. I update my gatsby version and I add GATSBY_EXPERIMENTAL_ROUTING_APIS=1 with cross-env

Thank's to make gatsby 💜

I close the issue
