### ISSUE TITLE
Full page reload on data update (gatsby develop)

### ISSUE THREAD

**Issue by benomatis** [gatsbyjs/gatsby#28023]
If I update data in redux that the app depends on in useEffects, it will cause a full reload, which appears to be due to the below code snippet. I saw [a comment against the original commit](https://github.com/gatsbyjs/gatsby/commit/f227e85728168d104ed0a7982823923dcd3bba62#r44003636) experiencing a redirect loop issue pointing to this piece of code as well.

Fast refresh (`GATSBY_HOT_LOADER=fast-refresh gatsby develop`) does seem to resolve this issue.

https://github.com/gatsbyjs/gatsby/blob/f227e85728168d104ed0a7982823923dcd3bba62/packages/gatsby/cache-dir/error-overlay-handler.js#L32-L40

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by benomatis** [comment]
I'll ba lame and not provide minimal reproduction because the code is very complex (and I'm the only one to be blamed for it), and I am very much behind with my work right now. I'll just proceed to close this, as I have a workaround, which appears to have answered my question on this. I understand from the discussion introducing fast refresh that it will be the new direction, so that will suffice to me at this stage.

Thanks anyways and hope I didn't steal too much of your time.
