### ISSUE TITLE
Calling a graphql query in separate file not working

### ISSUE THREAD

**Issue by willaay96** [gatsbyjs/gatsby#28050]
## Description

When trying to call a graphql query from a different file, receive this "Error: The result of this StaticQuery could not be fetched."

### Steps to reproduce

Create a file which exports a graphql query like: 

```
import { graphql } from "gatsby";

const GET_ALL_PROJECTS = graphql`
  query t {
    site {
      siteMetadata {
        title
      }
    }
  }
`;

export { GET_ALL_PROJECTS };
```
Call that query from a component like: 
```
const Projects = () => {
  const classes = useStyles();
  const { site } = useStaticQuery(GET_ALL_PROJECTS);
  return (
    <Grid container className={classes.root} spacing={5}>
      <Grid item xs={12}>
        <Grid container justify="center" spacing={6}>
          {[0, 1, 2].map((card) => {
            return (
              <Grid item key={card}>
                <ProjectCard />
              </Grid>
            );
          })}
        </Grid>
      </Grid>
    </Grid>
  );
};

export default Projects;
```

### Expected result

Expected for the query to run, exactly the same way that this would: 
```
const { site } = useStaticQuery(graphql`
    query getAllProjects {
      site {
        siteMetadata {
          projects {
            title
          }
        }
      }
    }
  `);
```
### Actual result

"Error: The result of this StaticQuery could not be fetched."

### Environment

  System:
    OS: Windows 10 10.0.19041
    CPU: (16) x64 AMD Ryzen 7 3800X 8-Core Processor
  Binaries:
    Node: 12.13.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.12.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.8.4
  Browsers:
    Edge: Spartan (44.19041.423.0), Chromium (86.0.622.69)       
  npmPackages:
    gatsby: ^2.25.3 => 2.25.3 
    gatsby-image: ^2.4.21 => 2.4.21 
    gatsby-plugin-manifest: ^2.5.2 => 2.5.2 
    gatsby-plugin-offline: ^3.3.3 => 3.3.3
    gatsby-plugin-react-helmet: ^3.3.14 => 3.3.14
    gatsby-plugin-sharp: ^2.7.1 => 2.7.1
    gatsby-source-filesystem: ^2.4.2 => 2.4.2
    gatsby-transformer-sharp: ^2.5.21 => 2.5.21
  npmGlobalPackages:
    gatsby-cli: 2.13.1

**Comment by LekoArts** [comment]
Thank you for opening this!

This is expected behavior. You can't collocate the query from the file it's supposed to be in. If you want to have reusable parts of a query you should use [GraphQL fragments](https://www.gatsbyjs.com/docs/using-graphql-fragments/).

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
