### ISSUE TITLE
Non-nullable filters introduce a problem with pageContext and page queries

### ISSUE THREAD

**Issue by henrikwirth** [gatsbyjs/gatsby#28108]
## Description

When using a glob or regex filter, setting their value null, produces errors. Yet if I wanna use them with pageContext and situations where they should be null and ignored, this introduces problems.

### Steps to reproduce

Query:

```graphql
# works
query ALL_CONTENT_TYPES {
  wpMenuItem(url: {eq: "", regex: ""}) {
    label
  }
}

# errors out
query ALL_CONTENT_TYPES {
  wpMenuItem(url: {eq: "", regex: null}) {
    label
  }
}

# errors out
query ALL_CONTENT_TYPES {
  wpMenuItem(url: {eq: "", glob: null}) {
    label
  }
}

#  errors out
query ALL_CONTENT_TYPES {
  wpMenuItem(url: {eq: "", glob: ""}) {
    label
  }
}
```

### Expected result

For example if I want to use it in a page query like this:
```graphql
export const query = graphql`
  query page(
    $urlContext: String
  ) {
    activeSubNavLabel: wpMenuItem(locations: { eq: MAIN},  url: { glob: $urlContext }) {
      label
    }
  }
`;
```

I would want it to work if `$urlContext` is null.

### Actual result

```json
{
  "errors": [
    {
      "message": "Expected a non-empty string",
    }
  ]
}
```

### Environment

```

  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.3 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 86.0.4240.198
    Firefox: 79.0
    Safari: 14.0
  npmPackages:
    gatsby: ^2.26.1 => 2.26.1 
    gatsby-awesome-pagination: ^0.3.6 => 0.3.6 
    gatsby-image: ^2.4.16 => 2.4.19 
    gatsby-plugin-env-variables: ^2.0.0 => 2.0.0 
    gatsby-plugin-layout: ^1.3.12 => 1.3.12 
    gatsby-plugin-loadable-components-ssr: ^2.1.0 => 2.1.0 
    gatsby-plugin-notifications: ^0.0.2 => 0.0.2 
    gatsby-plugin-sass: ^2.3.13 => 2.3.13 
    gatsby-plugin-segment-js: ^3.6.0 => 3.6.0 
    gatsby-plugin-sharp: ^2.6.27 => 2.6.36 
    gatsby-plugin-svgr: ^2.0.2 => 2.0.2 
    gatsby-source-filesystem: ^2.3.24 => 2.3.30 
    gatsby-source-wordpress-experimental: ^1.7.9 => 1.7.9 
    gatsby-transformer-sharp: ^2.5.13 => 2.5.15 
  npmGlobalPackages:
    gatsby-cli: 2.12.87
```

**Comment by pvdz** [comment]
Hi @henrikwirth . This isn't so much a bug as it that `null` isn't supported for the regex operator. Historically hasn't been because Sift didn't support that.

It shouldn't be too difficult to support it at this point since Sift was replaced with a custom engine.

Maybe you could take a look at the code and try to come up with a PR?

https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/redux/run-fast-filters.ts#L99
https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/redux/nodes.ts#L760

And update the tests with the `null` cases as well.

Also keep in mind that the code path for `regex` and `glob` operators are shared. They are almost the same thing.

There might be another point to look at (your schema?) as the error you reported does not appear to come from the fast filter code.

**Comment by henrikwirth** [comment]
Hi @pvdz ,

it just happened to me after a recent update that I couldn't pass an empty string to the `glob` filter. Which in the end broke my code. 

I sadly won't have time right now until February to come up with a PR since I'm super busy in a project already working overtime, so I just gonna try to build something around the problem.

Yet, I think every filter in the Gatsby world should be nullable, since that way you could decide when a filter should be applied and when it shouldn't. Otherwise there is no way to compose a query since the queries have to be predefined before build.

**Comment by pvdz** [comment]
What version did you upgrade from, and to which version? I don't think this code has changed in months.

**Comment by henrikwirth** [comment]
From:  
 ```
"gatsby": "^2.24.47",
"gatsby-source-wordpress-experimental": "^1.7.5",
```

To:
```
"gatsby": "^2.26.1",
"gatsby-source-wordpress-experimental": "^1.7.9",
```

**Comment by pvdz** [comment]
I suspect that a field in wordpress became nullable. I'm pretty sure filters have not changed in that range.

**Comment by henrikwirth** [comment]
@jasonbahl do you know more on this?

**Comment by TylerBarnes** [comment]
I just did a git diff on the compatible remote versions of WPGraphQL between v1.7.5 and v1.7.9 and there are no changes to our compatibility API for it. Unless you also changed your version of WPGraphQL when you upgraded Gatsby and the source plugin, that wont be the cause. I'd suggest reverting everything and making 1 change at a time to identify what the cause is.

**Comment by TylerBarnes** [comment]
Out of curiousity, what's your query achieving? Why not just use a filter for the location?

**Comment by henrikwirth** [comment]
@TylerBarnes So what I'm trying to do is that if I pass null values to the query, I want the result to be null too.

That way I can use the same pageQuery for multiple things and conditionally render the frontend depending of the data that is actually there.

I have this query now, but I do get a Menu returned, even though `locations` is null.

```
    subNav: wpMenu(locations: { eq: $subNavLocation }) {
      ...SubNavigation
    }
```
