### ISSUE TITLE
[gatsby-source-shopify]: Sort by price results in string sorting

### ISSUE THREAD

**Issue by darrenkeen** [gatsbyjs/gatsby#28215]
## Description
I am using the shopify plugin to gain access to my stores data. Using the `allShopifyProduct` query with a sort by `variants__price` `DESC` results in the strings being sorted instead of the actual price. For example it woul put `9.99` as a higher price than `100.99` (9 is higher than 1).

Here is the query and the result:
```
allShopifyProduct(sort: {fields: variants___price, order: DESC}) {
    nodes {
      variants {
        price
      }
    }
  }
```
```
{
  "data": {
    "allShopifyProduct": {
      "nodes": [
        {
          "variants": [
            {
              "price": "9.99"
            }
          ]
        },
        {
          "variants": [
            {
              "price": "89.43"
            }
          ]
        },
        {
          "variants": [
            {
              "price": "7.50"
            }
          ]
        },
        {
          "variants": [
            {
              "price": "32.99"
            }
          ]
        }
      }
    ]  
  }
}
```

Describe the issue that you're seeing.

### Steps to reproduce

Using the above query connected to a store

### Expected result

Prices should be sorted in the following order:
```
89.43
32.99
9.99
7.50
```

### Actual result

Prices are sorted by string
```
9.99
89.43
7.50
32.99
```

### Environment

```
  System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.15.1 - /var/folders/6z/_370xw392xz5yrfm6hysg0h40000gp/T/yarn--1605922018438-0.2572953401028433/node
    Yarn: 1.22.10 - /var/folders/6z/_370xw392xz5yrfm6hysg0h40000gp/T/yarn--1605922018438-0.2572953401028433/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.1/bin/npm
  Languages:
    Python: 3.6.3 - /usr/local/bin/python
  Browsers:
    Safari: 13.1.2
  npmPackages:
    gatsby: ^2.24.63 => 2.26.1 
    gatsby-image: ^2.4.17 => 2.5.0 
    gatsby-plugin-react-helmet: ^3.3.10 => 3.4.0 
    gatsby-source-sanity: ^6.0.4 => 6.0.4 
    gatsby-source-shopify: ~3.4.0 => 3.4.0 
```

**Comment by pieh** [comment]
Hi, likely fix here would be to add separate field that is actually a number and not a string in the `gatsby-source-shopify` plugin (we can't just change type of existing field because users might already rely no it being a string). Gatsby make use of data provided by Shopify GraphQL API as-is, and in their schema they do use Strings too:

![Screenshot 2020-11-23 at 19 14 38](https://user-images.githubusercontent.com/419821/99999256-328cef80-2dc0-11eb-8721-8169a063be90.png)
![Screenshot 2020-11-23 at 19 14 43](https://user-images.githubusercontent.com/419821/99999261-34ef4980-2dc0-11eb-91b7-485863142a51.png)

Gatsby will use lexical order when sorting strings, so this explains the behaviour here. I opened https://github.com/gatsbyjs/gatsby/pull/28243 with change that should cover this (it would then require you to adjust sorting field to use newly added one)

**Comment by darrenkeen** [comment]
Great, thanks for that @pieh. Will keep and eye on the PR for merge and realease.
