### ISSUE TITLE
[Question] How to stay in sync with a Gatsby starter?

### ISSUE THREAD

**Issue by codejet** [gatsbyjs/gatsby#2824]
I already asked this on [StackOverflow](https://stackoverflow.com/questions/47148063/how-to-stay-in-sync-with-a-gatsby-starter) after not finding anything really helpful searching the web. But since it got almost no views, I decided to ask here as well.

When I use a Gatsby starter (`gatsby new some-starter`) how can I best stay in sync with that starter? I didn't see something like a `gatsby update` command. 

Maybe someone can share his "battle-tested" approach using Git, for example.

**Comment by KyleAMathews** [comment]
Starters are (somewhat deliberately) not easy to upgrade.

For something to be "upgradeable" there needs to be some sort of API/boundary between what's *your* code and what's not your code so that you can upgrade the "not your code" and your site still works.

One way of doing this is to just clone a starter and for the most part don't change any code. This way you can keep pulling from the upstream as it changes.

I think there could be a better solution though. There's been some discussion already about adding the concept of "themes" to Gatsby which would do what it seems you want. I invite you to add to the discussion that's started already on this thread https://github.com/gatsbyjs/gatsby/issues/2662

**Comment by codejet** [comment]
Thanks @KyleAMathews!

**Comment by Undistraction** [comment]
FWIW This is relevant to anyone creating a starter. In this case it makes sense to create a separate example site that that uses the starter. However this is problematic because there is no mechanism for updating the starter.

**Comment by fpigeonjr** [comment]
I am going to try this method.
https://stigrune.dev/posts/keep-your-website-in-sync-with-gatsby-starter
