### ISSUE TITLE
Customize paths to static files

### ISSUE THREAD

**Issue by sungwoncho** [gatsbyjs/gatsby#2826]
I would like to customize paths to static files.

Currently `gatsby build` builds the following files:

```
public
├── 404
│   └── index.html
...
├── static
│   └── logo.c17c5425.png
├── stats.json
└── styles.css
```

Does gatsby allow users to configure the paths for static files (`static`)? If it does not, would you consider a PR?

For more context, the reason for my wanting this is because I am generating static website using gatsby for guests, and a React app using create-react-app for logged-in users. In my dev environment, I use nginx to route paths to appropriate destinations. But both create-react-app and gatsby use 'static' to serve files (bundle.js in CRA) in dev, and I cannot get them both working at the same time.

**Comment by KyleAMathews** [comment]
Yeah making this an option seems reasonable.

There's several places in the codebase where this is hard-coded that'd need changed.

Also the PR would need to document the new option.

**Comment by KyleAMathews** [comment]
We're not going to do this. Also, you don't need to use CRA with Gatsby as Gatsby sites work the same as CRA! It's just React running in the client!

See https://www.gatsbyjs.org/docs/building-apps-with-gatsby/ for more.

**Comment by itmayziii** [comment]
@KyleAMathews 

I have some use cases for this feature besides the one mentioned by the submitter. I'm in the process of moving an older site over to Gatsby and their images currently reside at a http://<domain>/images. This company is heavily SEO focused and I don't believe they are going to be on board with all the urls to their images changing to /static/<random-hash>/<image-path>. Right now it would not even be possible for me to write a nginx or apache rule that points all requests to /images/* to the correct path since the path has a random hash in it.

Any advice or thoughts would be appreciated.

**Comment by KyleAMathews** [comment]
Are you planning on using gatsby-plugin-sharp? Or gatsby-image? If not, you can just put files in the static directory as they'll be copied directly into the root of the site. https://www.gatsbyjs.org/docs/static-folder/

**Comment by itmayziii** [comment]
Yes to both of those questions, gatsby-image + sharp seems to provide a lot out of the box that we have done manually in the past (lazy loading, responsive sizes). Seems we might have to give up on these benefits though and use the static folder.

**Comment by KyleAMathews** [comment]
Yeah, giving people complete control over naming files isn't something we've prioritized as most people don't care. It's something we're open too PRs for though if you'd like to tackle it.

**Comment by KyleAMathews** [comment]
You could e.g. pass into the gatsby-plugin-sharp a function for creating names.

**Comment by Wendenburg** [comment]
actually we jus have a similar problem. Due to a legacy system, we have some redirects also for a path containing '/static/'. Now we set up a new system based on static sites rendered by gatsby and the redirect for '/static/' causes a conflict now. For now we have a post-process to move the static files and rename all appearances of '/static/' in the build files. It's a hack, something like an output config option would be a great feature for more complex setups.

**Comment by richburdon** [comment]
The use case I have is sharing image assets across multiple gatsby projects in the same monorepo. Currently having to copy files in a pre-build script, which makes netlify builds complicated.

**Comment by seaneking** [comment]
I just ran into the same limitation as @richburdon — sharing static assets across a monorepo (eg: between design system with Storybook, site with Gatsby, and app in vanilla React). Is it still not possible to set a custom path for the `static` directory, in an env variable or something?

**Comment by Acidic9** [comment]
I have a library which depends on some html files, and when putting this in the gatsby `static` folder, gatsby cannot find it and attempts to look for a page which of course does not exist.

`static/lib.html` and `my-site.com/lib.html` works in production, but not indevelopment.
