### ISSUE TITLE
TailwindCSS: group-hover defaults not working and if specified in tailwind.config.js > variants > extend

### ISSUE THREAD

**Issue by Hahlh** [gatsbyjs/gatsby#28328]
## Description

The group-hover defaults are not working (like textColor and backgroundColor) and [following the docs](https://tailwindcss.com/docs/hover-focus-and-other-states#group-hover) and specifying them in the config doesn't seem to take effect.

<img width="850" alt="image" src="https://user-images.githubusercontent.com/45669613/100480782-89f9cb00-30f2-11eb-9c9a-4dd476f22571.png">

If specified in tailwind.config.js under variants > extend as shown in the docs, the changes don't have effect:
<img width="528" alt="image" src="https://user-images.githubusercontent.com/45669613/100480494-bcef8f00-30f1-11eb-8fee-44cc8224a929.png">

**Comment by Hahlh** [comment]
**The solution to this is to also add 'hover', not only 'group-hover'.** 

The defaults are overridden and 'hover' is one of them.


I found the solution while creating this issue, but decided to open this issue nevertheless for the befit of future generations. 
May that spare them some valuable minutes.

Another point would be of course, why the defaults for group-hover, that normally shouldn't be needed to be added are not working, but I will close this issue for the time being until I have further investigated.

**Comment by Hahlh** [comment]
Okay,  I actually have to reopen this issue. 

Apparently the difference is indeed, that variants don't take effect, if applied via extend. 
They are only applied, if added directly under variants.

<img width="980" alt="image" src="https://user-images.githubusercontent.com/45669613/100517860-33da6580-318e-11eb-9176-8ac471ea2132.png">

I will add to this, that apparently the defaults, that [according to the docs](https://tailwindcss.com/docs/hover-focus-and-other-states#group-hover) should be working without any changes to the config, are not:
<img width="662" alt="image" src="https://user-images.githubusercontent.com/45669613/100517896-72702000-318e-11eb-9e10-9367bbc10c78.png">

**Comment by LekoArts** [comment]
Please open this on TailwindCSS repository, this one here is specific for issues with Gatsby.

**Comment by Hahlh** [comment]
Hey @LekoArts ! 
Thanks you for looking at this issue.

Apparently TailwindCSS updated to 2.0 a couple of days ago, [which included the possibility to use 'extend' for variants](https://github.com/tailwindlabs/tailwindcss/pull/2651).

Changing the version manually in package.json allows to update to TailwindCSS 2.0.1, but that breaks building as PostCSS 8 is required.

Looking at [this issue](https://github.com/gatsbyjs/gatsby/issues/26939), gatsby-plugin-postcss started to use PostCSS 8 beginning with 3.0.0.

If you use gatsby-plugin-sass ([Option #3 in the Gatsby docs](https://www.gatsbyjs.com/docs/tailwind-css/#option-3-scss)) for making TailwindCSS work, the dependency is not satisfied.

I reverted back to tailwindcss@^1.9.6 for the moment, which works fine if you don't follow the Tailwind docs and use 'extend', but add the variants directly.

**Comment by Hahlh** [comment]
@LekoArts 

I changed the title to reflect my new understanding of this issue.
Do you have any update regarding this?

**Comment by Hahlh** [comment]
@LekoArts

I changed the title to reflect my new understanding of this issue.
Any update regarding this?

![image](https://user-images.githubusercontent.com/45669613/104838295-59e0d400-58ba-11eb-80a1-b2181050852b.png)

[Related stackoverflow thread](https://stackoverflow.com/questions/64925926/error-postcss-plugin-tailwindcss-requires-postcss-8) and [related docs, if Tailwind > 1.9.6 is required](https://tailwindcss.com/docs/installation#post-css-7-compatibility-build).

**Comment by Kevsonschouten** [comment]
Hi,

Joining in, because I'm experiencing the exact same issue.
![image](https://user-images.githubusercontent.com/38126483/107081410-ed8b2d80-67f2-11eb-9e15-f271122ee1e6.png)

Might be overseeing something here, but as i understand I'm having all the correct versions?
![image](https://user-images.githubusercontent.com/38126483/107081578-37741380-67f3-11eb-8694-33e37fbbdde5.png)

Thanks in advance for helping out.

**Comment by Hahlh** [comment]
@Kevsonschouten The solution I have provided above should fix the issue for you for the moment.

**Comment by Hahlh** [comment]
[Another option are the instructions provided by Tailwind to avoid gatsby-plugin-sass.](https://tailwindcss.com/docs/guides/gatsby)

**Comment by Kevsonschouten** [comment]
Hi Hahlh , I’ve got things working. Thank you !

**Comment by austonpramodh** [comment]
> Hi Hahlh , I’ve got things working. Thank you !
Hi, I am facing the same problem. Can you please tell me how did you get it fixed?

**Comment by Hahlh** [comment]
> > Hi Hahlh , I’ve got things working. Thank you !
> 
> Hi, I am facing the same problem. Can you please tell me how did you get it fixed?

Hey @austonpramodh. Hope you had a great weekend!

I described two solutions above. Did you try to implement them and ran into problems?

**Comment by austonpramodh** [comment]
Hi @Hahlh. I did have a great weekend playing around with tailwind and gatsby. Thanks for asking. 

hope you had a great weekend too.

I tried solution no 2 - using tailwind with postcss7. At first, npm didn't allow me to downgrade the postcss. This was because i had gatsby-plugin-postcss installed. I uninstalled gatsby-plugin-postcss and followed [your solution](https://github.com/gatsbyjs/gatsby/issues/28328#issuecomment-774458097), configured gatsby config following [Tailwind with Gatsby](https://www.gatsbyjs.com/docs/how-to/styling/tailwind-css/) and it worked.

So the complete steps would be to follow [Tailwind with Gatsby](https://www.gatsbyjs.com/docs/how-to/styling/tailwind-css/) with option #3. Then use the [Your solution](https://github.com/gatsbyjs/gatsby/issues/28328#issuecomment-774458097) to install tailwind-postcss7.
![image](https://user-images.githubusercontent.com/5049050/110252802-23b3fc80-7fad-11eb-8979-b9a4cf979ab8.png)

Hope this helps others too.

Thank you so much.
