### ISSUE TITLE
gatsby@2.29.0-next.3 hang up in source and transform nodes due to new md5-file

### ISSUE THREAD

**Issue by simonjoom** [gatsbyjs/gatsby#28496]
with last Gatsby 
gatsby@2.29.0-next.3

It seems that the use of the new version md5-file don't allow the process to go further after "source and transform nodes" for me

roll back to the old version using md5-file/promise did do the work for me...

this code below make the process hang up like a promise never been resolved
```
 const hashes = await Promise.all([!!process.env.GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES, (0, _md5File.default)(`package.json`),(0, _md5File.default)(`${program.directory}/gatsby-config.js`).catch(() => {})
   ]);
```

I rolled back to  md5-file/promise and it's pass:

```
 const hashes = await Promise.all([!!process.env.GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES, (0, _promise.default)(`package.json`), Promise.resolve((0, _promise.default)(`${program.directory}/gatsby-config.js`).catch(() => {})) 
  ]); 

```

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment]
Hi!

Since we didn't receive an answer for 7 business days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or reopen the issue. Thanks!

**Comment by simonjoom** [comment]
I found the issue, I should to update gatsby-source-filesystem which use as well md5-file. 
Resolved !
