### ISSUE TITLE
childMarkdownRemark is not querring

### ISSUE THREAD

**Issue by soumikp02** [gatsbyjs/gatsby#2857]
the version of "gatsby" I am using is "^1.9.106"  graphiql  says that 
----------------Cannot query field \"childMarkdownRemark\"--------------------

**Comment by calcsam** [comment]
Is this the first time you've used GraphiQL? You may want to read a tutorial such as https://medium.com/the-graphqlhub/graphiql-graphql-s-killer-app-9896242b2125 and try to get some example queries working.

**Comment by Chuloo** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues as many of them have already been resolved with the latest updates or explained in a previous issue.

Feel free to [open a new one](https://github.com/gatsbyjs/gatsby/issues/new/choose) if you still experience this problem or a similar one! 👍
