### ISSUE TITLE
[gatsby-plugin-offline] Build fails for 'glob patterns not matching any files'

### ISSUE THREAD

**Issue by julsmon** [gatsbyjs/gatsby#28571]
## Description

On my multi language gatsby JS site, I'm using both gatsby-plugin-manifest and gatsby-plugin-offline. 

When I build the website (I'm building on Netlify), I get the following error:

```
warning One of the glob patterns doesn't match any files. Please remove or fix the following: {
                      "globDirectory": "public",
9:58:35 AM:   "globPattern": "offline-plugin-app-shell-fallback/index.html",
9:58:35 AM:   "globIgnores": [
9:58:35 AM:     "**/workbox-v4.3.1/*.+(js|mjs)*",
9:58:35 AM:     "**/node_modules/**/*",
9:58:35 AM:     "**/sw.js"
9:58:35 AM:   ]
9:58:35 AM: }
9:58:35 AM: info Generated public/sw.js, which will precache 0 files, totaling 0 bytes.
9:58:35 AM: The following pages will be precached:
9:58:35 AM: /offline-plugin-app-shell-fallback/index.html
```

The site goes live, but it can't be accessed.

### Steps to reproduce

This is my configuration for plugin-manifest:
```
{
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `FM Sito`,
        short_name: `FM`,
        start_utl: `/it/`,
        lang: `it`,
        background_color: `#35b775`,
        theme_color: `#2196f3`,
        display: `standalone`,
        icon: `src/images/cta-icon.png`,
        cache_busting_mode: 'none', 
        localize: [
          {
            start_url: `/en/`,
            lang: `en`,
            name: `FM English`,
            short_name: `FM`,
          },
          {
            start_url: `/es/`,
            lang: `es`,
            name: `FM Espanol`,
            short_name: `FM`,
          },
        ],
      },
    },
```

And this is my configuration for plugin-offline:
```
    {
      resolve: 'gatsby-plugin-offline',
      options: {
          workboxConfig: {
            globPatterns: ['**/*']
          }
       }
     },
```

### Expected result

The plugin-offline is supposed to work fine.
I have to mention that before adding locales to my website, the plugin used to work as expected and I would get 100 score in PWA Lighthouse score.

### Actual result

The site isn't accessible.

### Environment

System:
    OS: Windows 10 10.0.19041
    CPU: (4) x64 Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
  Binaries:
    Node: 12.16.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.9.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.8.3
  Browsers:
    Chrome: 87.0.4280.88
    Edge: Spartan (44.19041.423.0), Chromium (87.0.664.57)
  npmPackages:
    gatsby: ^2.28.2 => 2.28.2
    gatsby-image: ^2.2.44 => 2.2.44
    gatsby-plugin-google-gtag: ^2.1.0 => 2.1.0
    gatsby-plugin-manifest: ^2.8.0 => 2.8.0
    gatsby-plugin-offline: ^3.6.0 => 3.6.0
    gatsby-plugin-react-helmet: ^3.1.24 => 3.1.24
    gatsby-plugin-robots-txt: ^1.5.1 => 1.5.1
    gatsby-plugin-sass: ^2.2.1 => 2.2.1
    gatsby-plugin-sharp: ^2.6.30 => 2.6.30
    gatsby-plugin-sitemap: ^2.3.5 => 2.3.5
    gatsby-source-filesystem: ^2.1.56 => 2.1.56
    gatsby-transformer-remark: ^2.7.4 => 2.7.4
    gatsby-transformer-sharp: ^2.5.13 => 2.5.13
  npmGlobalPackages:
    gatsby-cli: 2.12.29

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment]
Hi!

Since we didn't receive an answer for 7 business days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or reopen the issue. Thanks!
