### ISSUE TITLE
Gatsby-Image rendering in low quality issue still exists

### ISSUE THREAD

**Issue by JenniferFuBook** [gatsbyjs/gatsby#28589]
## Description

The issue described in https://github.com/gatsbyjs/gatsby/issues/25783 still exists.

### Steps to reproduce

I followed the steps in https://www.gatsbyjs.com/docs/how-gatsby-works-with-github-pages/
The deployed page is https://jenniferfubook.github.io/gatsby-site/.
You can see the resolution is low.

### Expected result

Expect a high resolution.

### Actual result

I lost the resolution.

### Environment
$ gatsby info --clipboard
error (node:68063) ExperimentalWarning: Package name self resolution is an experimental feature. This feature could change at any time

  System:
    OS: macOS Mojave 10.14.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.0 - ~/.nvm/versions/node/v12.16.0/bin/node
    npm: 6.14.8 - ~/.nvm/versions/node/v12.16.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 87.0.4280.88
    Firefox: 82.0.3
    Safari: 14.0.1
  npmPackages:
    gatsby: ^2.26.1 => 2.26.1 
    gatsby-image: ^2.5.0 => 2.5.0 
    gatsby-plugin-manifest: ^2.6.1 => 2.6.1 
    gatsby-plugin-offline: ^3.4.0 => 3.4.0 
    gatsby-plugin-react-helmet: ^3.4.0 => 3.4.0 
    gatsby-plugin-sharp: ^2.8.0 => 2.8.0 
    gatsby-source-filesystem: ^2.5.0 => 2.5.0 
    gatsby-transformer-sharp: ^2.6.0 => 2.6.0 
  npmGlobalPackages:
    gatsby-cli: 2.15.1

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by JenniferFuBook** [comment]
This is the minimal case:
Github: https://www.gatsbyjs.com/docs/how-gatsby-works-with-github-pages/
The problem page is https://jenniferfubook.github.io/gatsby-site/.

**Comment by achilleleal** [comment]
Hi! 

It seems that your `pathPrefix` inside your `gatsby-config.js` is not your repo name, but the repo link. You should change it to `pathPrefix: "/gatsby-site"` since that is your repo's name. Hope that helps!

Cheers!

**Comment by JenniferFuBook** [comment]
Yes, fixing the path solves the problem.
Thanks!
