### ISSUE TITLE
[Question] How to run gatsby develop with --inspect-brk?

### ISSUE THREAD

**Issue by nwshane** [gatsbyjs/gatsby#2866]
I'd like to run the `gatsby develop` command and be able to debug the generation of pages with node's debugger. For example, be able to put the `debugger` command in a blog post template to debug passing of data as blog post pages are generated.

Is there a way I can run the `gatsby develop` command with `--inspect-brk`? i.e. `node --inspect-brk [insert-script-called-by-gatsby-develop-here]`

**Comment by KyleAMathews** [comment]
You can run the actual command at `node_modules/gatsby/dist/commands/develop.js`.

**Comment by Chuloo** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues as many of them have already been resolved with the latest updates or explained in a previous issue.

Feel free to [open a new one](https://github.com/gatsbyjs/gatsby/issues/new/choose) if you still experience this problem or a similar one! 👍
