### ISSUE TITLE
404 page renders only html

### ISSUE THREAD

**Issue by VitaliiZhukov** [gatsbyjs/gatsby#2878]
Hi!
I have an issue with 404 page.
I created pages/404.js file and configured cloudfront to give back this route if page not found.
As result I have next case:
www.mysite.com/404 - opens correct 404 page
www.mysite.com/fakeurl - opens only 404 html without mounting. Only prebuilt html content.
I've seen similar issue here but didn't found the solution:
https://github.com/gatsbyjs/gatsby/issues/2223

Is that matter of gatsby or probably server configuration?
Thanks!

**Comment by KyleAMathews** [comment]
You configured Cloudfront to serve `404.html`? Or `404.js`?

You should do the former.

**Comment by VitaliiZhukov** [comment]
Hi @KyleAMathews !
Yeah, I've configured "/404.html" as response page path in cloudfront
![image](https://user-images.githubusercontent.com/10582247/32723240-d29b198a-c87d-11e7-9f89-36eaa6c89b7d.png)

When I have url like "/somepage" I can see line in console:
![image](https://user-images.githubusercontent.com/10582247/32723313-17327886-c87e-11e7-9614-3d982bf2c194.png)

And only prebuilt html is rendered.

**Comment by KyleAMathews** [comment]
Does your issue seem the same as https://github.com/gatsbyjs/gatsby/issues/1838?

**Comment by VitaliiZhukov** [comment]
Hi @KyleAMathews 
Seems no. I have a link on my 404 page, and it works properly.

**Comment by emmafallancy** [comment]
@VitaliiZhukov @KyleAMathews it's not mounted because previously, the callback to mount the DOM was not executed. I suppose the link works fine if it's not relying on gatsby's `history` in `window` 😃 

https://github.com/gatsbyjs/gatsby/blob/6b2732a17b45d3fbe6fd888ee823f61046cb6c5e/packages/gatsby/cache-dir/loader.js#L248-L253

**Comment by VitaliiZhukov** [comment]
Hi @KyleAMathews , @emmafallancy 
thank you so much for your help. I checked out last release and not found page composed with gatsby.
But I've got another issue: it's mounted twice. In my console I can see now two messages: A page wasn't found for "/somepage"

Did you have such behaviour? Or it's only my case?
Also I noticed that if I create /pages/404.js file then after building I see 404.html file in root, and also /404/index.html file. Why do we have two paths?

**Comment by emmafallancy** [comment]
> But I've got another issue: it's mounted twice. In my console I can see now two messages: A page wasn't found for "/somepage"
Yup, this is expected since the `component-renderer` is called twice, as during the constructing of the component, it searches for resources on the `layout` and `pages` level.

> Also I noticed that if I create /pages/404.js file then after building I see 404.html file in root, and also /404/index.html file. Why do we have two paths?
Some host would search for `404.html` file to serve for any pages which couldn't be found. So during production build, if `pages/404.js` exist, Gatsby will build the `404.html` from the `pages/404.js`. If somehow the host couldn't find any `404.html` in production, the host will use its own `404` page.

**Comment by VitaliiZhukov** [comment]
Got it, thanks!
