### ISSUE TITLE
There was an error in your GraphQL query:

### ISSUE THREAD

**Issue by Blackwatch1910** [gatsbyjs/gatsby#28869]
## Description

everytime i hit "gatsby develop", it displays the same message.

### Steps to reproduce

1. npm install
2. gatsby develop

### Expected result

the local server should start without any issue

### Actual result

Error Codes #85923 and #98123

### Environment

System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 15.2.1 - ~/.nvm/versions/node/v15.2.1/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.10 - ~/.nvm/versions/node/v15.2.1/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  Browsers:
    Firefox: 84.0
  npmPackages:
    gatsby: ^2.20.2 => 2.29.3
    gatsby-plugin-manifest: ^2.3.1 => 2.9.1
    gatsby-plugin-offline: ^3.1.0 => 3.7.1
    gatsby-plugin-react-helmet: ^3.2.0 => 3.7.0
    gatsby-plugin-sass: ^2.2.0 => 2.8.0
    gatsby-theme-testimonials: 0.0.11 => 0.0.11
  npmGlobalPackages:
    gatsby-cli: 2.16.2

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by Blackwatch1910** [comment]
Solved the error by cleaning the following code snippet:
export const query = graphql`
 {
     allTestimonialsJson {
       edges {
         node {
           name
           company
           blurb
           twitter
           linkedIn
         }
       }
     }
   }
 `;

in node_modules/gatsby-theme-testimonials/src/components/TestimonialSection.js

**Comment by LekoArts** [comment]
You should open an issue with https://github.com/molebox/gatsby-theme-testimonials then :)
Editing the file in `node_modules` won't persist as you don't commit this anywhere. You'll need to shadow the file: https://www.gatsbyjs.com/docs/how-to/plugins-and-themes/shadowing/
