### ISSUE TITLE
Warn if people put graphql queries in non-page/layout components

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#2889]
This is a super common problem and we should be able to detect this and warn people about it.

Working on writing some GraphQL docs and we'd be able to send them to the docs section on using fragments.

**Comment by Chuloo** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues as many of them have already been resolved with the latest updates or explained in a previous issue.

Feel free to [open a new one](https://github.com/gatsbyjs/gatsby/issues/new/choose) if you still experience this problem or a similar one! 👍
