### ISSUE TITLE
Links causing re-render on hover after Query on Demand patch.

### ISSUE THREAD

**Issue by FileManagerKim** [gatsbyjs/gatsby#29011]
## Description

After a recent update, my Links now cause re-renders of the components they are inside of on the initial hover of the Link component. I know this is an error that has sprung after after the inclusion of the query on demand changes, and replacing Links with hrefs on a tags does rectify the problem. Ive managed to reproduce the problem in a simplified form, and have narrowed the issue down to how the Link tag behaves with URLS leading to generated pages. My assumption is that this is behavior caused by how the Link component's onHover functionality is routing to the graphcms query generated pages, however I'm not too sure and really am just grasping at straws at this point. I currently had to rollback the production version of my actual site to continue working on it, however any help fixing the problem would be appreciated. 

### Steps to reproduce

Note: the reproduction is linked to a dummy graphcms account.

Link to reproduction: https://github.com/FileManagerKim/ErrorReproduction/tree/master

### Expected result

The cards on the index page should not cause a re-render on hover.

### Actual result

Cards on the index page cause a re-render on first hover.

### Environment

  System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
  Binaries:
    Node: 12.17.0 - D:\Tools\Node\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.4 - D:\Tools\Node\npm.CMD
  Browsers:
    Edge: Spartan (44.18362.449.0)
  npmPackages:
    gatsby: ^2.26.1 => 2.30.2 
    gatsby-image: ^2.5.0 => 2.9.0 
    gatsby-plugin-manifest: ^2.6.1 => 2.10.0 
    gatsby-plugin-offline: ^3.4.0 => 3.8.0 
    gatsby-plugin-react-helmet: ^3.4.0 => 3.8.0 
    gatsby-plugin-sharp: ^2.8.0 => 2.12.1 
    gatsby-source-filesystem: ^2.5.0 => 2.9.0 
    gatsby-source-graphcms: ^2.1.1 => 2.1.1 
    gatsby-transformer-sharp: ^2.6.0 => 2.10.1 
  npmGlobalPackages:
    gatsby-cli: 2.12.106

**Comment by vladar** [comment]
I checked this and it seems that `StaticQueryStore` causes this re-render here:

https://github.com/gatsbyjs/gatsby/blob/90b6e3d3c5526e4f3db891019969f7cfddc11958/packages/gatsby/cache-dir/query-result-store.js#L102-L106

This happens because of the [`onPostLoadPageResources` event](https://github.com/gatsbyjs/gatsby/blob/90b6e3d3c5526e4f3db891019969f7cfddc11958/packages/gatsby/cache-dir/loader.js#L295) that occurs when pre-loaded page is ready. 

The interesting piece is that we also have this in the `StaticQueryStore`:

https://github.com/gatsbyjs/gatsby/blob/90b6e3d3c5526e4f3db891019969f7cfddc11958/packages/gatsby/cache-dir/query-result-store.js#L118-L123

And obviously this is always `false` because of destructuring in the `setState`.

**Comment by FileManagerKim** [comment]
> 
> 
> I checked this and it seems that `StaticQueryStore` causes this re-render here:
> 
> https://github.com/gatsbyjs/gatsby/blob/90b6e3d3c5526e4f3db891019969f7cfddc11958/packages/gatsby/cache-dir/query-result-store.js#L102-L106
> 
> This happens because of the [`onPostLoadPageResources` event](https://github.com/gatsbyjs/gatsby/blob/90b6e3d3c5526e4f3db891019969f7cfddc11958/packages/gatsby/cache-dir/loader.js#L295) that occurs when pre-loaded page is ready.
> 
> The interesting piece is that we also have this in the `StaticQueryStore`:
> 
> https://github.com/gatsbyjs/gatsby/blob/90b6e3d3c5526e4f3db891019969f7cfddc11958/packages/gatsby/cache-dir/query-result-store.js#L118-L123
> 
> And obviously those object references are always different because of spreading in the `setState`. This change was introduced in #28075 Before it we had it written as `staticQueryData: getStaticQueryResults()` (so no spreading)
> 
> Also seems that it was intentional given this comment: https://github.com/gatsbyjs/gatsby/pull/28075/files#diff-40ccde30988a097bbbeb6d6e6ca0f67e7572c189c850b42781692a272f3ff141L100

**Comment by FileManagerKim** [comment]
Woops I accidentally closed the issue, anyways so it look like the component wants to update when the static query results change, but in this case the static query doesn't change only the retrieval of query itself is causing the re-render does if I'm understanding correctly?

**Comment by pieh** [comment]
> Also seems that it was intentional given this comment: https://github.com/gatsbyjs/gatsby/pull/28075/files#diff-40ccde30988a097bbbeb6d6e6ca0f67e7572c189c850b42781692a272f3ff141L100

Partially intentional. The problematic part I guess is how to force rerender because we have same object that gets mutated and that wasn't trigerring react re-renders when it should. The impact however as seen by this issue with current approach is not acceptable, so there need to be some changes there to make sure we DO rerender when static queries change, but don't rerender on every `onPostLoadPageResources` event if nothing changed

**Comment by jdesherlia** [comment]
I have recently run into this issue as well. Definitely only affects develop which is nice, but it still caused a minor panic attack as I thought that I had accidentally done something to cause a re-render every time I hovered over one of my new components. I have rolled back to 2.29.x for now, as I needed to move forward, but I would be interested in helping debug this if its needed.

Thanks,

-Josh-

**Comment by jdesherlia** [comment]
> I have recently run into this issue as well. Definitely only affects develop which is nice, but it still caused a minor panic attack as I thought that I had accidentally done something to cause a re-render every time I hovered over one of my new components. I have rolled back to 2.29.x for now, as I needed to move forward, but I would be interested in helping debug this if its needed.
> 
> Thanks,
> 
> -Josh-

**UPDATE:**
I am no longer sure that my issue is due to Query on Demand. I rolled back to 2.29.x and even set `QUERY_ON_DEMAND: false` in my config flags, and I am still seeing the issue. I will keep digging in, but I am kind of stumped at this point. The behavior is exactly as is described in this issue. Hovering any link causes a top-down re-render of the page. For reference, all of my pages are created using createPage in gatsby-node. I will try and see if the issue doesn't happen on a statically defined page.

**Comment by mrbjjackson** [comment]
@vladar thanks for linking these my issue to this one. It seems as though it is the same issue. 

I just wanted to mention something though (and I'm not sure if this is linked or not):

On my site (not the reproduction), I was alerted to this rerender because a useStaticQuery hook was being refired and on the second render, it was returning an empty node array.

When I do a `gatsby build` rather than a `gatsby develop`, the "on hover" rerender does indeed stop happening as mentioned above, however my useStaticQuery issue is still happening. i.e. on the first visit of a page, the useStaticQuery returns all the info as expected however if you navigate away and then go back to the page, the query returns empty. 

Note: the reproduction I made in my issue doesn't contain this bug because it was the "on hover" bug that I was focussing on.

Does this sound like it could be linked? Any ideas? Should I open another issue maybe?

Thanks

**Comment by jdesherlia** [comment]
I've done a little more narrowing down as well. Maybe this is obvious, but for me it's exclusive to links that are rendered with the Gatsby Link component. I've tried it on static pages and pages created with createPage, and it happens on both. I'm going to try and bump package versions and see if I get differing results, but right now its really not apparent why this just started happening.

**Comment by jdesherlia** [comment]
> I've done a little more narrowing down as well. Maybe this is obvious, but for me it's exclusive to links that are rendered with the Gatsby Link component. I've tried it on static pages and pages created with createPage, and it happens on both. I'm going to try and bump package versions and see if I get differing results, but right now its really not apparent why this just started happening.

**UPDATE:**
I have rolled back progressively to Gatsby v2.24.x and am still seeing the issue, so i'm pretty sure at this point that its something that I did ( unless there is a dependency causing the issue ). I still am not quite sure how to debug whats triggering the re-render though. Any insights on how to test further would be appreciated.

**Comment by logemann** [comment]
I also ran into this issue with a QandA component which gets its data from staticQuery, but for me its not only in development. Because i also do some kind of randomizing of entries on each page, i end up having wrong links for the entries. Hard to explain but it all starts because of the re-rendering  inside the Link component.

I can show the code which turns out to be very problematic. The `<Link>` is inside the other component `<LexikonBadge>` which just has some HTML markup and the LINK stuff in it.

```
import React from "react"
import LexikonBadge from "./Badge"
import { Row } from "react-bootstrap"
import { graphql, useStaticQuery } from "gatsby"

function getRandom(arr, n) {
  var result = new Array(n),
    len = arr.length,
    taken = new Array(len);
  if (n > len)
    throw new RangeError("getRandom: more elements taken than available");
  while (n--) {
    var x = Math.floor(Math.random() * len);
    result[n] = arr[x in taken ? taken[x] : x];
    taken[x] = --len in taken ? taken[len] : len;
  }
  return result;
}

function LexikonBadgesRandomSection({ product = "Netversys" }) {

  console.log("ReRender");
  const data = useStaticQuery(graphql`
    query BenutzermanagementQuery {
      qa: allMarkdownRemark(
        filter: {
          fields: {collection: {eq: "qa"}}, 
        }) { 
        edges {
          node {
            id
            frontmatter {
              question
              category
              icon {
                childImageSharp {
                  gatsbyImageData(width:50)
                }
              }
            }
            fields {
              slug
            }
          }
        }
      }            
    }`
  )
  const calculatedCategoryBasedOnProduct = product === "Netversys" ?
    "Versandlogistik" : product === "Netstorsys" ?
    "Warehouse Management" : "Logistik / Allgemein"

  const entries = data.qa.edges.filter((entry) => {
    return entry.node.frontmatter.category === calculatedCategoryBasedOnProduct
  })

  const randomXEntriesOfArray = getRandom(entries,4);

  return (
    <Row>
      {
        entries.map((entry) => {
          return (
            <LexikonBadge key={entry.node.id} item={entry} />
        )})
      }
    </Row>
  )
}

export default LexikonBadgesRandomSection
```

**Comment by logemann** [comment]
I also ran into this issue with a QandA component which gets its data from staticQuery, but for me its not only in development. Because i also do some kind of randomizing of entries on each page, i end up having wrong links for the entries. Hard to explain but it all starts because of the re-rendering  inside the Link component.

I can show the code which turns out to be very problematic. The `<Link>` is inside the other component `<LexikonBadge>` which just has some HTML markup and the LINK stuff in it.

```
import React from "react"
import LexikonBadge from "./Badge"
import { Row } from "react-bootstrap"
import { graphql, useStaticQuery } from "gatsby"

function getRandom(arr, n) {
  var result = new Array(n),
    len = arr.length,
    taken = new Array(len);
  if (n > len)
    throw new RangeError("getRandom: more elements taken than available");
  while (n--) {
    var x = Math.floor(Math.random() * len);
    result[n] = arr[x in taken ? taken[x] : x];
    taken[x] = --len in taken ? taken[len] : len;
  }
  return result;
}

function LexikonBadgesRandomSection({ product = "Netversys" }) {

  console.log("ReRender");
  const data = useStaticQuery(graphql`
    query BenutzermanagementQuery {
      qa: allMarkdownRemark(
        filter: {
          fields: {collection: {eq: "qa"}}, 
        }) { 
        edges {
          node {
            id
            frontmatter {
              question
              category
              icon {
                childImageSharp {
                  gatsbyImageData(width:50)
                }
              }
            }
            fields {
              slug
            }
          }
        }
      }            
    }`
  )
  const calculatedCategoryBasedOnProduct = product === "Netversys" ?
    "Versandlogistik" : product === "Netstorsys" ?
    "Warehouse Management" : "Logistik / Allgemein"

  const entries = data.qa.edges.filter((entry) => {
    return entry.node.frontmatter.category === calculatedCategoryBasedOnProduct
  })

  const randomXEntriesOfArray = getRandom(entries,4);

  return (
    <Row>
      {
        entries.map((entry) => {
          return (
            <LexikonBadge key={entry.node.id} item={entry} />
        )})
      }
    </Row>
  )
}

export default LexikonBadgesRandomSection
```
This results in something like this:

![Bildschirmfoto 2021-06-17 um 10 50 08](https://user-images.githubusercontent.com/346353/122364854-744ad680-cf5a-11eb-935c-ae246ec56102.png)

In Development i get new entries when i hover over the links which looks like a weird puzzle effect, in production i have entries with wrong links, which is even tougher to understand and should be there because of re-rendering.

**Comment by simonjoom** [comment]
i ve got the same issue "Links causing re-render on hover" even with this patch. 
i used the last gastby code.

I found something working for query-result-store
```
  shouldComponentUpdate(nextProps, nextState) {
    // We want to update this component when:
    // - static query results changed

    return JSON.stringify(this.state.staticQueryData) !== JSON.stringify(nextState.staticQueryData)
   // return this.state.staticQueryData !== nextState.staticQueryData
  }

```

**Comment by simonjoom** [comment]
some update for performance

const shallowEqual = (objA, objB) => {
  if (!objA || !objB) {
    return objA === objB
  }
  return !Boolean(
    Object
      .keys(Object.assign({}, objA, objB))
      .find((key) => objA[key] !== objB[key])
  )
}

...
export class StaticQueryStore extends React.PureComponent {
  shouldComponentUpdate(nextProps, nextState) {
    // We want to update this component when:
    // - static query results changed

return !shallowEqual(this.state.staticQueryData,nextState.staticQueryData)
 //   return JSON.stringify(this.state.staticQueryData) !== JSON.stringify(nextState.staticQueryData)
   //

**Comment by joyfulelement** [comment]
Curious if anyone from the community could help with this issue?
I've nailed down the exact upgrade of Gatsby version that cased this, that is:
`gatsby: v2.26.1` <= No issue
`gatsby: v2.27.0` <= Has the re-rendering issue when hover over Gatsby Link component
As mentioned by @FileManagerKim, this was perhaps introduced from the query on demand feature.
The issues occurs on both development and production for my website.

**Comment by joyfulelement** [comment]
After another day of digging, I was able to workaround this issue by adjusting the react context provider (from `gatsby-plugin-dark-mode`) sitting at the layout level. For some reason, the `onMouseOver` event from Gatsby Link was causing the unintended re-render with my setup with `gatsby-plugin-dark-mode`. React profiler in Chrome DevTool was used to help pin point the culprit in this case, I would recommend using this tool to help troubleshoot if anyone else experience the same issue.

**Comment by MikeBroders** [comment]
hey, i just want to mention that this is still happening (Gatsby V4)... is there a plan to fix this at any time?

**Comment by ashleynexvelsolutions** [comment]
Any updates on this?

**Comment by LekoArts** [comment]
Hi!

I'm closing this as a stale issue as in the meantime Gatsby 4 and related packages were released. You can check our [Framework Version Support Page](https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/) to see which versions currently receive active support. If this is a feature request, please [create a discussion](https://github.com/gatsbyjs/gatsby/discussions/categories/ideas-feature-requests) as we moved feature requests from issues to GitHub Discussions.

Please try the mentioned issue on the latest version (using the `next` tag) and if you still see this problem, open a new bug report. It **must** include a [minimal reproduction](https://gatsby.dev/reproduction).

Thanks!

**Comment by paulwellnerbou** [comment]
This is still happening in Gatsby 5.
Is there any way to disable this re-rendering behaviour?
