### ISSUE TITLE
Cannot query field "references" on type 

### ISSUE THREAD

**Issue by jordan-miguel** [gatsbyjs/gatsby#29049]
## Summary

I'm following [this](https://www.gatsbyjs.com/plugins/gatsby-source-contentful/#query-rich-text-content-and-references) doc, unfortunately gatsby does not recognize the references field when querying richtext in the GraphQL schema.

- I have successfully ran `npm install @contentful/rich-text-react-renderer`
- [This](https://github.com/gatsbyjs/gatsby/issues/28729) issue mentioned creating dummy data as a workaround - **_how can I do this?_**

### Error
```
Cannot query field "references" on type "ContentfulArticleContent".
```

**Comment by jordan-miguel** [comment]
Update: Screenshot
<img width="581" alt="Screenshot 2021-01-16 at 00 44 55" src="https://user-images.githubusercontent.com/14114089/104791895-33c11400-5794-11eb-87c7-74b1214131a8.png">

**Comment by daydream05** [comment]
On Contentful, you basically create a fake content with all the fields, filled out. Including your hyperlinks for your rich text.

It’s really annoying but it’s the only way to make Contentful would work with Gatsby’s graphql.

**Comment by LekoArts** [comment]
Thank you for opening this!

This is currently a limitation of the Contentful source plugin. If you have questions about the new rich text implementation you can go to https://github.com/gatsbyjs/gatsby/discussions/28098, for improvements on the plugin you can follow https://github.com/gatsbyjs/gatsby/projects/24.

The workaround is adding at least one entry for every reference so that Gatsby creates the schema through inference.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by joshuaswilcox** [comment]
Can someone explain what 

> adding at least one entry for every reference

means?

**Comment by benbalderas** [comment]
> Can someone explain what
> 
> > adding at least one entry for every reference
> 
> means?

@joshuaswilcox it means adding at least one entry in Contentful with all your needed references (e.g. bold, link, asset, ul, etc.)

**Comment by aintHuman** [comment]
> > Can someone explain what
> > > adding at least one entry for every reference
> > 
> > 
> > means?
> 
> @joshuaswilcox it means adding at least one entry in Contentful with all your needed references (e.g. bold, link, asset, ul, etc.)

How rediculous.

**Comment by JuliusGoddard** [comment]
> > > Can someone explain what
> > > > adding at least one entry for every reference
> > > 
> > > 
> > > means?
> > 
> > 
> > @joshuaswilcox it means adding at least one entry in Contentful with all your needed references (e.g. bold, link, asset, ul, etc.)
> 
> How rediculous.

Well said. Definitely room for improvement here.
