### ISSUE TITLE
UNHANDLED REJECTION Command failed with E2BIG:

### ISSUE THREAD

**Issue by Nicolasmata** [gatsbyjs/gatsby#29044]
any ideas about this issue at develop? 

 ERROR 

UNHANDLED REJECTION Command failed with E2BIG: node /..../node
_modules/gatsby-recipes/dist/graphql-server/server.js 50400
spawn E2BIG

  Error: Command failed with E2BIG: node /....../node_modules/ga
  tsby-recipes/dist/graphql-server/server.js 50400
  spawn E2BIG
  
  - child_process.js:366 ChildProcess.spawn
    internal/child_process.js:366:11
  
  - index.js:80 Object.execa [as default]
    [passport-frontend]/[execa]/index.js:80:26
  
  - index.js:25 startGraphQLServer
    [passport-frontend]/[gatsby-recipes]/src/graphql-server/index.js:25:29

**Comment by LekoArts** [comment]
Hi!

Please follow the issue template for bug reports and [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks!

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment]
Hi!

Since we didn't receive an answer for 7 business days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or reopen the issue. Thanks!
