### ISSUE TITLE
Issue with gatsby-plugin-remove-fingerprints and gatsby-plugin-netlify

### ISSUE THREAD

**Issue by probablyup** [gatsbyjs/gatsby#29055]
## Description

When using `gatsby-plugin-remove-fingerprints` and `gatsby-plugin-netlify` together, undesired behavior occurs. Remove fingerprints takes the contenthash off the built file, but the netlify plugin with `mergeCachingHeaders` and `mergeLinkHeaders` on (the default) adds `cache-control: immutable` and a very long max age so the browser will never pull an update from Netlify's e-tag header.

The netlify plugin should detect if remove fingerprints is in use and not add the headers, as it will lead to a broken deployment story by default.

**Comment by LekoArts** [comment]
Thank you for opening this!

We shouldn't make the Netlify plugin try to fix this issue as it then would require the correct order they are run in. Please open an issue/PR on the repository of gatsby-plugin-remove-fingerprints to document the necessary changes. This is how other plugins also deal with (possible) clashes. Rather than trying to fix each other, it should be documented.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
