### ISSUE TITLE
Markdown images with space in filename break

### ISSUE THREAD

**Issue by fk** [gatsbyjs/gatsby#2909]
From `examples/using-remark-copy-linked-files`:

![image](https://user-images.githubusercontent.com/21834/32745316-a7319924-c8b2-11e7-9ba0-0ea5344a2187.png)

**Comment by KyleAMathews** [comment]
Any idea why? Is this a new thing w/ your PR or an older problem?

**Comment by fk** [comment]
Putting together `examples/using-remark-copy-linked-files` is the first time I'm seeing it. The images I originally used there are from the example Markdown post @chiedo posted in https://github.com/gatsbyjs/gatsby/pull/2871#issuecomment-343663432:

**Comment by fk** [comment]
> Is this a new thing w/ your PR or an older problem?

Older problem, just tested with a local site with `gatsby-remark-copy-linked-files@1.5.7`
![image](https://user-images.githubusercontent.com/21834/32747653-b86cae0c-c8b9-11e7-8166-1c61c693f94a.png), same problem already:

![image](https://user-images.githubusercontent.com/21834/32747765-0f565a6a-c8ba-11e7-9e66-6a2615e33bab.png)

**Comment by Chuloo** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues as many of them have already been resolved with the latest updates or explained in a previous issue.

Feel free to [open a new one](https://github.com/gatsbyjs/gatsby/issues/new/choose) if you still experience this problem or a similar one! 👍

**Comment by fk** [comment]
FWIW this is working—just checked `examples/using-remark-copy-linked-files` in `master` (`gatsby 2.0.0-rc.4`, `gatsby-remark-copy-linked-files 2.0.0-rc.1`): 
![image](https://user-images.githubusercontent.com/21834/44825190-b4a20400-ac09-11e8-937d-5a61b7e2afa4.png)

**Comment by clarkd** [comment]
Will this be fixed in gatsby 1 at all?
