### ISSUE TITLE
Sometimes, the development server stops responding

### ISSUE THREAD

**Issue by lucis** [gatsbyjs/gatsby#29165]
## Description

From time to time (and across different projects), my `gatsby develop` process reloads from code changes, but my local development server stops responding (`Error: socket hang up`). I have to stop the `gatsby develop` process and run it again. My hot-reload flow usually works just fine.

![image](https://user-images.githubusercontent.com/18706156/105638728-14408000-5e53-11eb-802b-1605db163dca.png)

### Steps to reproduce

I still haven't found what causes it. I strongly believe it's not related with some specific code modification.

### Expected result

I'd want my server to hot reload on my code changes.

### Actual result

The server stops (with no error) and I have to restart the `gatsby develop` process.

### Environment

```
  System:
    OS: macOS 11.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 88.0.4324.96
    Firefox: 83.0
    Safari: 14.0.2
  npmPackages:
    gatsby: ^2.26.1 => 2.26.1
    gatsby-image: ^2.5.0 => 2.5.0
    gatsby-plugin-google-fonts: ^1.0.1 => 1.0.1
    gatsby-plugin-less: ^4.6.0 => 4.6.0
    gatsby-plugin-linaria: ^2.2.0 => 2.2.0
    gatsby-plugin-manifest: ^2.6.1 => 2.6.1
    gatsby-plugin-no-index: ^1.0.2 => 1.0.2
    gatsby-plugin-offline: ^3.4.0 => 3.4.0
    gatsby-plugin-react-helmet: ^3.4.0 => 3.4.0
    gatsby-plugin-sharp: ^2.8.0 => 2.8.0
    gatsby-plugin-typescript: ^2.10.0 => 2.10.0
    gatsby-source-filesystem: ^2.5.0 => 2.5.0
    gatsby-transformer-sharp: ^2.6.0 => 2.6.0
```

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by tu4mo** [comment]
I had a similar issue, which was partly fixed in gatsby@2.27.2. Have you tried updating your deps?

**Comment by lucis** [comment]
@LekoArts unfortunately, as I've described, it's an intermittent problem and not related with code per-se! I'd imagine someone had seen this and might help in finding out what is happening.

@tu4mo thanks, I'll definitely try and get back here. I now remember that I've started this last project with `gatsby new` with the default starter, probably getting a not-latest-stable `gatsby`.

**Comment by robertocerdasilva** [comment]
I am having this same problem! sometimes it's really slow to visualize new changes while I'm developing. It just stops responding and I have to restart the "gatsby develop" command.  (v2.31.0)

**Comment by LekoArts** [comment]
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!
