### ISSUE TITLE
styled-component issue working in dev but intermittent in prod

### ISSUE THREAD

**Issue by cheehau** [gatsbyjs/gatsby#29269]
## Description

I am using styled-component@4 with gatsby but there is some intermittent issue which does not show up in dev, but it show up in prod

if I go to https://bidbid.live/login/ straight, the styled rendered is missing partially which break the UI. However if I go to https://bidbid.live/ and click on Guest->Signin, it is fine. So a few question arise, why the behaviour is dfferent  among pages. How to we debug dynamic inline styles?

### Steps to reproduce

Navigate to https://bidbid.live/login/
Notice the broken design

https://bidbid.live/
Then Click on Guest->Sigin
Notice the design still works

### Expected result

Styles should be consistent among pages

### Actual result

Styles is missing

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by vrgimael** [comment]
I'm having a similar problem using emotion

**Comment by cheehau** [comment]
Hi I think i found the reason for my issue. So you check if you have implement anything for gatsby-browser, for e.g wrapRootElement, make sure you implement it for gatsby-ssr also, so the SSR  site will be able to reconcile with React after loading.

**Comment by LekoArts** [comment]
Hi!

Seems like you figured out your issue. And yes, especially with styling, you'll want your `gatsby-browser.js` and `gatsby-ssr.js` to align, otherwise you'll have a mismatch between the generated HTML and what the client tries to re-hydrate.

Also, please add a [minimal reproduction][reproduction] in the future. Thanks!

[reproduction]: https://gatsby.dev/reproduction
