### ISSUE TITLE
GraphQL query returns no data after deleting cache

### ISSUE THREAD

**Issue by kildareflare** [gatsbyjs/gatsby#2934]
I added a new field to some content in prismc and restarted the development server, but I was not seeing my change come through, despite restarting several times, clearing browser cache etc. I thought maybe it was not updating the cache, so I deleted that related file from the cache.

However at this point, no data is returned from my graph query. And yet if I run the same query in graphiql the data *is* returned.....

If i put console logs in  gatsby-source-prismic I can see the data getting returned and nodes created.
It's just not pulling the data in via the index graph query, the only change being to add the new field (uid).

I then took the field out and the query worked again (returned data).
Put it back in and no data returned.
Put a load of debug in gatsby-source-prismic and confirmed the property was getting mapped to a node and had correct value.

Added the property back to the query and, it worked!
No functional change.

I've seen this behaviour a few times - that is, data not coming through straight away. I spend time debugging it and then it just starts coming through.

Am I missing something obvious?

**Comment by Chuloo** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues as many of them have already been resolved with the latest updates or explained in a previous issue.

Feel free to [open a new one](https://github.com/gatsbyjs/gatsby/issues/new/choose) if you still experience this problem or a similar one! 👍
