### ISSUE TITLE
Static site generation - Multi Page model

### ISSUE THREAD

**Issue by vinothvk** [gatsbyjs/gatsby#2935]
Though this is not an issue to report here. I would like to know whether GatsbyJS supports generation of multi page apps. So far the example i have seen are all single page apps and navigation is driven by javascript.

Do you have any sample to take a look ?

Thanks

**Comment by dustinhorton** [comment]
Gatsby generates static HTML. Check out the source of https://www.gatsbyjs.org—navigation is not 'driven by javascript.' There are `a` tags with `href` values.

**Comment by Chuloo** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues as many of them have already been resolved with the latest updates or explained in a previous issue.

Feel free to [open a new one](https://github.com/gatsbyjs/gatsby/issues/new/choose) if you still experience this problem or a similar one! 👍
