### ISSUE TITLE
Error: ENOENT: no such file or directory, open xxx .cache/json/xxx.json

### ISSUE THREAD

**Issue by adominguez** [gatsbyjs/gatsby#29435]
## Description

Im trying to do a build with Gatsby but I'm getting an error like this:
```
 ERROR 

UNHANDLED REJECTION ENOENT: no such file or directory, open
'/xxx/xxx/xxx/xxx/.cache/json/_differents-files.json'

  Error: ENOENT: no such file or directory, open '/xxx/xxx/xxx/xxx/.cache/json/_differents-files.json'
```
I'm try in locally with mac, and so with netlify site and I have the same problem always with differents json files.

In case it can help I can serve the application with npm run develop and it´s work ok, only, __I have problems with build__

### Steps to reproduce

1. clone the repo https://github.com/adominguez/automatic-store-front-template.git
2. npm i && npm run build
3. wait to get error 🙂

### Environment
```
  System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.4 - ~/.nvm/versions/node/v12.18.4/bin/node
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.4/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 88.0.4324.150
    Firefox: 85.0
    Safari: 14.0.2
  npmPackages:
    gatsby: ^2.24.73 => 2.32.3
    gatsby-cli: ^2.19.1 => 2.19.1
    gatsby-image: ^2.4.20 => 2.11.0
    gatsby-plugin-manifest: ^2.4.32 => 2.12.0
    gatsby-plugin-offline: ^3.6.0 => 3.10.0
    gatsby-plugin-postcss: ^3.3.0 => 3.7.0
    gatsby-plugin-react-helmet: ^3.3.12 => 3.10.0
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0
    gatsby-plugin-sharp: ^2.6.37 => 2.14.1
    gatsby-source-filesystem: ^2.3.31 => 2.11.0
    gatsby-transformer-sharp: ^2.5.16 => 2.12.0
  npmGlobalPackages:
    gatsby-cli: 2.19.1
```
Thank you so much

**Comment by ascorbic** [comment]
Hi. The problem is that you're not correctly awaiting your `createPages` calls. This is why you get the error warning about createPages happening outside of the lifecycle. The issue is that you can't await an `Array.prototype.forEach` call, because it doesn't return anything. When calling async functions on an array you should use `Array.prototype.map`, and wrap it in `Promise.all`. If I change this code in `gatsby-node.js`:

```js
  await allPages.forEach(async page => {
///snip
  });
```

..to this:

```js
  await Promise.all(allPages.map(async page => {
///snip
  }));
```
...then it works for me.

I hope that helps. If it doesn't, please reply and tag me.

**Comment by adominguez** [comment]
@ascorbic Great!! Thank you so much it´s work for me 😉 👍  Perfect!!
