### ISSUE TITLE
gatsby-source-wordpress is not getting all  CustomPostType's posts from WordPress

### ISSUE THREAD

**Issue by Baartooo** [gatsbyjs/gatsby#29704]
## Description

I'm using **_gatsby-source-wordpress_** in version **_4.0.1_**. In my WordPress I'm using **_CustomPostTypes_** along with **_AdvancedCustomFields_**. I created _**CPT**_ called _**MapPlace**_ with _**ACF**_ inside including _**Google Maps marker**_. I imported exactly 301 _**MapPlaces**_ using _**WP All Import Pro**_. Because of the _**Google Maps marker**_ inside, I had to add custom importing script which gets my place's address and place pin on _**Google Maps**_ field. Each post is being imported correctly. The problem occures when I'm fetching _**MapPlaces**_ to my _**Gatsby**_ project. As I said, I have exactly 301 published _**MapPlaces**_ in my WordPress (pic rel). During the build **_gatsby-source-wordpress'_** logs shows me that fetched 294 _**MapPlaces**_, and in my GraphiQL I see 286 real ones.
![image](https://user-images.githubusercontent.com/44865225/108833231-d0b17100-75cc-11eb-86d9-d57d8a2a07bc.png)
![image](https://user-images.githubusercontent.com/44865225/108833253-d5762500-75cc-11eb-8b6f-e840fbcc3242.png)
![image](https://user-images.githubusercontent.com/44865225/108833264-d9a24280-75cc-11eb-876d-c7cd53ad1f23.png)

### Steps to reproduce

- have big number (e.g. 301 as in my case) of **_CustomPostType's_** posts with **_GoogleMaps_** pin field
- try to query in _**Gatsby's**_ GraphiQL all these posts belonging to this particular **_CPT_**

### Expected result

You get all these posts.

### Actual result

You get less posts than it's actually published

### Environment

WordPress:
wp-graphql version : 
![image](https://user-images.githubusercontent.com/44865225/108833724-867cbf80-75cd-11eb-8aef-f815408d5c60.png)

Gatsby: 
`"gatsby-source-wordpress": "4.0.1"`

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by Baartooo** [comment]
Here (https://github.com/Baartooo/gatsby-bug-repro) I opened clean repo with only displaying data amount at the _**index.js**_ page. The GraphQL query is also in _**index.js**_. When you run `gatsby develop` notice that logs are displaying: 
![image](https://user-images.githubusercontent.com/44865225/108858322-509b0380-75ec-11eb-99fb-9a7b432e41a3.png)
and compare those numbers with actual data numbers in GraphiQL or look at the numbers at _**index.js**_ page

**Comment by TylerBarnes** [comment]
Thanks for the reproduction! That was really helpful.

This isn't a bug in this plugin but appears to be a problem in your WP site.

You do have 294 public posts being returned from WPGraphQL like the terminal output mentions however it seems some of the posts returned from WPGraphQL are duplicates - I logged out a few of these to try to figure out what was going on:

<img width="1617" alt="Screen Shot 2021-03-02 at 3 16 21 PM" src="https://user-images.githubusercontent.com/14190743/109728017-450a8800-7b6a-11eb-9d76-a9adbdd4d00e.png">

One possible explanation for the problem here is that you have some plugins or filters in your WP site that's messing with the WPQuery used by WPGraphQL. There isn't anything we're able to do on the Gatsby site to fix this - it'll need to be debugging WP-side and might take a bit of time to figure out. I recommend disabling plugins and custom code until you find the source 👍

**Comment by Baartooo** [comment]
@TylerBarnes I very appreciate your help! Thank you for your time and explanation. We're going to look further for the bug at the WP-side :)

**Comment by Baartooo** [comment]
@TylerBarnes We found where the problem was located! [Post Types Order](https://wordpress.org/plugins/post-types-order/) plugin was making mess in posts' amount comming to Gatsby. If we turned this plugin off, we got all posts straight to Gatsby :) I write this here, cause someone could have similiar issue. Again, thanks for help anyway!

**Comment by TylerBarnes** [comment]
Glad to hear you found it :smile:
