### ISSUE TITLE
[gatsby-plugin-image] Image requested and downloaded multiple times 

### ISSUE THREAD

**Issue by matthewkwong2** [gatsbyjs/gatsby#30272]
## Description
Similar to #23501, the same image is requested multiple times. Except for this time, it happens on multiple modern browsers.
![image](https://user-images.githubusercontent.com/32725014/111305797-5a1b0700-8692-11eb-9f1c-293932cc11bf.png)

### Steps to reproduce
Same as that in #23501, basically:
1. Create a Gatsby project from the default starter
```bash
gatsby new gatsby-starter-default https://github.com/gatsbyjs/gatsby-starter-default
```
2. Start the dev build

### Expected result

`gatsby-astronaut.webp` should only be requested and downloaded once.

### Actual result
`gatsby-astronaut.webp` is requested and downloaded multiplier times.

### Environment
```
  System:
    OS: Windows 10 10.0.19041
    CPU: (4) x64 Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
  Binaries:
    Node: 15.11.0 - C:\Program Files\nodejs\node.EXE
    npm: 7.6.1 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.9.2
  Browsers:
    Edge: Spartan (44.19041.423.0), Chromium (89.0.774.54)
  npmPackages:
    gatsby: ^3.0.1 => 3.0.1 
    gatsby-plugin-gatsby-cloud: ^2.0.0 => 2.0.0 
    gatsby-plugin-image: ^1.0.0 => 1.0.0 
    gatsby-plugin-manifest: ^3.0.0 => 3.0.0 
    gatsby-plugin-offline: ^4.0.0 => 4.0.0 
    gatsby-plugin-react-helmet: ^4.0.0 => 4.0.0 
    gatsby-plugin-sharp: ^3.0.0 => 3.0.0 
    gatsby-source-filesystem: ^3.0.0 => 3.0.0 
    gatsby-transformer-sharp: ^3.0.0 => 3.0.0 
  npmGlobalPackages:
    gatsby-cli: 3.0.0
```

**Comment by kelvindecosta** [comment]
I've experienced this bug as well.

In my case I have a single `GatsbyImage` on a `Layout` component handled by `gatsby-plugin-layout`.
Basically, when routes change, the `Layout` component should persist.

However, when the route changes for the first time the image flashes.
From the Network tab on DevTools I gathered that the image is being downloaded again.

**Comment by t2ca** [comment]
I'm also having the same issue.

**Comment by wardpeet** [comment]
It's a bug in safari: https://bugs.webkit.org/show_bug.cgi?id=159484

**Comment by matthewkwong2** [comment]
> It's a bug in safari: https://bugs.webkit.org/show_bug.cgi?id=159484

As I said, unlike the old issue, this issue affects multiple modern browsers, including Chrome and Safari.

I'm pretty sure these two are not the same bug despite the symptoms look similar.

**Comment by t2ca** [comment]
Im using Chrome.

**Comment by simonjoom** [comment]
I'm not sure about my thinking but 
does the problem of image loading twice can coming because useEffect runs after the paint ?

see https://reacttraining.com/blog/useEffect-is-not-the-new-componentDidMount/
Maybe using useLayoutEffect instead useEffect for the plugin-image?

**Comment by matthewkwong2** [comment]
It seems that this issue has been fixed with the latest release of `gatsby-plugin-image`. It would be great if others can confirm this.

**Comment by mikevercoelen** [comment]
This problem is still here, and indeed with preact

**Comment by Confidenceiskey** [comment]
I can also confirm that I have the issue (and without using preact)!

I just migrated my site from Gatsby v2 --> v3, updated all my packages and switched from `gatsby-image` to `gatsby-plugin-image`. I noticed the double network request issue happening...

If this is really fixed, could someone show me an example codebase where it's working properly?

**Comment by kelvindecosta** [comment]
Hey @Confidenceiskey 

Thanks for taking the time to conduct these experiments and share your results with us!

I just wanted to clarify if you observed this behavior in both the development and production builds. The Firefox example shows a `localhost:8000` which is the default for the dev server.

The problem is much more serious on a production build. 

In my case, I have a single `GatsbyImage` as part of the `Layout` component that acts as the root content wrapper. This image component should not change during route navigation, but is still downloaded again after the second route change.

I have only tested with Chrome on Linux so far.

**Comment by Confidenceiskey** [comment]
Hey @kelvindecosta , 

Aye... I just did both of the tests on the development build. I didn't have such issues on the dev environment previously, so this is definitely new. I also can't imagine that the environment would play a role here, but who knows...

I can push the changes to my live site (since it doesn't get much/any traffic) and see if it's also reproducible in production. 

*I just did `gatsby build` & `gatsby serve` as a quick check on Chrome Canary.*
- Initial page load => no double requests. 
- Lazy loaded images => double requests 

I'll post my results for a live production site in a bit...

**Comment by matthewkwong2** [comment]
> @matthewkwong2 , could you check if this is happening for you again?
Yep, it is happening to me again. In my case, both DEV and PROD build are having this issue. I'm using Chromium Edge (latest stable version).

I also observed similar results to yours when testing on FIrefox (also latest stable version).

**Comment by Confidenceiskey** [comment]
@kelvindecosta , 

Update: So it might not be a `gatsby-plugin-image` specific issue. I checked all 4 four browsers again and basically had the same results as in the development environment, except on the initial page load everything was OKAY. 

2 observations... (with cache disabled in the network tab)

1. The double requests happened for **lazy loaded images** on all browsers I tried (NOTE: In Safari & Chrome - for lazy loaded images - the requests happened 3 times!!! 😱 )
2. The double requests also happened for other content as well (ex: any **`page-data.json`**). This was happening for all browsers that I tried.

One note regarding the triple requests - If I set the service worker to network only (disabled) in Chrome, I only got 2 requests.

Maybe this is a Gatsby v3 issue for lazy loaded content? I checked my gatsby v2 site right before and it didn't behave like this...

**Comment by kelvindecosta** [comment]
That's very interesting! I vaguely remember seeing multiple requests for `page-data.json` too.

Maybe this might be unrelated, but I noticed my `favicon.ico` file being requested multiple times on my local prod build. This was not the case with the deployment on Gatsby Cloud.

**Comment by t2ca** [comment]
Could we please have someone from the Gatsby team look at this issue? @KyleAMathews 

Downloading images twice does not provide a very optimized website. 

This issue does not exist with `gatsby-image` and is only present when using `gatsby-plugin-image`.

Thanks

**Comment by titenis** [comment]
Issue still reproducible with 
"gatsby": "3.6.0",
"gatsby-plugin-image": "1.6.0",

**Comment by KyleAMathews** [comment]
If you see this, it's probably because you have "Disable cache" enabled in your devtools. Compare these two times I load the default starter. If the cache is disabled, the browser will load the same asset every time it's requested. With the cache, it won't.

<img width="1449" alt="Screen Shot 2021-06-10 at 3 45 45 PM" src="https://user-images.githubusercontent.com/71047/121606470-11f65100-ca03-11eb-94d1-bb6b884ce3a7.png">

<img width="1237" alt="Screen Shot 2021-06-10 at 3 46 00 PM" src="https://user-images.githubusercontent.com/71047/121606457-0c990680-ca03-11eb-9868-4bf0a0ce3a00.png">

**Comment by titenis** [comment]
This sounds like hiding bug behind cache. Why the same image is being requested two times in first place?

**Comment by KyleAMathews** [comment]
The image is in the HTML so is requested as soon as it loads. And then apparently when React hydrates. I'm not deeply familiar with this code and how/why browsers request images but apparently when React hydrates, something changes in the image html enough that the browser thinks it needs to try requesting the image again. If the cache is in place, it immediately short-circuits but without the cache, it does request the image again.

**Comment by Justbigmack** [comment]
The weird thing is that it is treated as expected behavior, but when comparing gatsby-image images to gatsby-plugin-images, the former don't have this issue and the latter do.

**Comment by limichange** [comment]
This problem continues to exist. So weird, i have to remove the images when not at client, then when the browser load js to display image.
