### ISSUE TITLE
Please use your discussion: https://github.com/gatsbyjs/gatsby/discussions/30703

### ISSUE THREAD

**Issue by danielmoessner** [gatsbyjs/gatsby#30724]
Please use your discussion: https://github.com/gatsbyjs/gatsby/discussions/30703
You verified that something out of Gatsby's control (the CMS) sets the image metadata incorrectly. Thus it's not a bug per se but a question/discussion if this can be worked around or be an additional feature.

_Originally posted by @LekoArts in https://github.com/gatsbyjs/gatsby/issues/30704#issuecomment-813895855_

This was a mistake from my side. The meta data is actually correct. Gatsby-image-plugin doesn't read the Orientation meta data which turns width to height and height to width. Therefore it is not the CMS that sets the imagedata incorrectly. The problem is that Gatsby-plugin-image doesn't read the orientation meta data.

So please unlock the issue. And if you tell me where the width and height from the meta data is read and set I'm happy to help with code.

**Comment by LekoArts** [comment]
Please comment with these new findings in https://github.com/gatsbyjs/gatsby/discussions/30703 and @ascorbic will have a look when he has time. Maybe it's still a user error / upstream issue or actually a bug but until then it doesn't speed up the process if you create new issues all the time instead of sticking to a single place to discuss the issue itself. Thanks!
