### ISSUE TITLE
bug(gatsby-source-wordpress): maxFileSizeBytes option silently excludes entire MediaItem node instead of just the File node

### ISSUE THREAD

**Issue by dannyvaughton** [gatsbyjs/gatsby#30755]
## Description

The featuredImage node is not working for pages & custom post types. It only works for posts.

Here's my query:

```
query PAGE_QUERY {
  allWpPage {
    nodes {
      id
      featuredImage {
        node {
          altText
          sourceUrl
        }
      }
    }
  }
}
```

And here's the result:

```
{
    "id": "cG9zdDo0NTI=",
    "featuredImage": null // this page does NOT have a featured image
},
{
     "id": "cG9zdDoyOTQ3NzA=",
     "featuredImage": {
         "node": null // this page has a featured image
      }
}
```

The second item in the list has a featured image and notice that it's returning a "node" which is null, whereas the top page does not have a featured image and is just returning null

### Steps to reproduce

1. Create a page with a featured image (or any other custom post type) in WP
2. Run the PAGE_QUERY above in Gatsby's in-browser IDE

### Expected result

For pages with a featured image, the `node` object should not be null. It should return `altText` & `sourceUrl` or whatever properties are specified in the query.

### Actual result

The featuredImage.node object is null.

### Environment

It's worth noting I am using Polylang & ACF plugins in WordPress. However, the WPGraphQL IDE works and returns the featuredImage. So it must be an issue with gatsby-source-wordpress.

I am using `gatsby-source-wordpress@5.3.0-next.2`

```
System:
    OS: macOS Mojave 10.14
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.4.0 - ~/.nvm/versions/node/v14.4.0/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 7.7.6 - ~/.nvm/versions/node/v14.4.0/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 89.0.4389.114
    Firefox: 84.0.2
    Safari: 12.0
```

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by adrianhewitt** [comment]
Just updated everything here (literally everything, v3 / Gatsby Image / gatsby-source-wordpress and plugins etc) and I'm running into a similar issue. There is a particular post when queried just wont return the feature image data on the gatsbyjs end, and it's not downloaded to the cache. I can query it through the wordpress graphql plugin, it just doesnt make it over to gatsbyjs...

**Comment by holliepearson** [comment]
I had this issue after updating everything, I changed the featured image to a different one and back as well as clearing my gatsby cache and that fixed it for me. Perhaps that might work for you too?

**Comment by adrianhewitt** [comment]
I can change the image to another and it's fine, but clearing the cache and changing it back to that specific image makes it die again. Just so i'm not hijacking this ticket i've made my own with a paired down project reproducing my issue.

https://github.com/gatsbyjs/gatsby/issues/30844

**Comment by veryspry** [comment]
@adrianhewitt We'll track your're issue here as well since this seems to be the same issue as https://github.com/gatsbyjs/gatsby/issues/30844

**Comment by TylerBarnes** [comment]
I believe I've figured out what's going on here. If you check out [this option](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/docs/plugin-options.md#typemediaitemlocalfilemaxfilesizebytes), you can see there's a default max file size limit of 15mb. @adrianhewitt the yoga school media item you've mentioned as being missing is 17mb. 

So I believe the issue here is:
- There's no terminal output mentioning that one or more images haven't been fetched due to the maxFileSyzeBytes option.
- This option seems to exclude the entire media item rather than just the localFile node which doesn't particularly make sense. If you have a max size for local files, we can only detect images larger than that cheaply via the MediaItem node which means these are being fetched and then discarded. It should work that you can still query the attached MediaItem but the localFile field returns null rather than the whole MediaItem returning null.

**Comment by adrianhewitt** [comment]
POW solved, thanks! Yes a warning would be very handy, hard tracking these things down when you've got nothing to go on.

**Comment by jooola** [comment]
Great news, any idea when a fix will be shipped in a release ?
