### ISSUE TITLE
Gatsby-plugin-image placeholder loads with black color

### ISSUE THREAD

**Issue by mhatvan** [gatsbyjs/gatsby#30870]
## Description

I didn't encounter this issue until today, I think it had to do with deleting the whole `node_modules` folder and `yarn.lock`, after a fresh install I noticed the black backgrounds for loading images.

### Expected result

It should be transparent background and color could be configurable

### Actual result

It loads with a black color on a white web page, which doesn't look good.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

```
  System:
    OS: Linux 5.8 Ubuntu 20.10 (Groovy Gorilla)
    CPU: (8) x64 Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 15.12.0 - ~/.nvm/versions/node/v15.12.0/bin/node
    Yarn: 1.22.5 - ~/.nvm/versions/node/v15.12.0/bin/yarn
    npm: 7.6.3 - ~/.nvm/versions/node/v15.12.0/bin/npm
  Languages:
    Python: 3.8.6 - /bin/python
  Browsers:
    Chrome: 84.0.4147.135
    Firefox: 87.0
  npmPackages:
    gatsby: ^3.2.1 => 3.3.0
    gatsby-plugin-catch-links: ^3.2.0 => 3.3.0
    gatsby-plugin-gatsby-cloud: ^2.3.0 => 2.3.0
    gatsby-plugin-google-analytics: ^3.2.0 => 3.3.0
    gatsby-plugin-image: ^1.2.0 => 1.2.0
    gatsby-plugin-intl: ^0.3.3 => 0.3.3
    gatsby-plugin-manifest: ^3.2.0 => 3.3.0
    gatsby-plugin-nprogress: ^3.2.0 => 3.3.0
    gatsby-plugin-offline: ^4.2.0 => 4.3.0
    gatsby-plugin-postcss: ^4.2.0 => 4.3.0
    gatsby-plugin-react-helmet: ^4.2.0 => 4.3.0
    gatsby-plugin-sharp: ^3.2.0 => 3.3.0
    gatsby-plugin-sitemap: ^3.2.0 => 3.3.0
    gatsby-source-contentful: ^5.2.0 => 5.3.0
    gatsby-source-filesystem: ^3.2.0 => 3.3.0
    gatsby-transformer-sharp: ^3.2.0 => 3.3.0
```

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by ascorbic** [comment]
Hello. The default it to use the dominant color of the image. If you want to diable it, you can set `placeholder="none"`on `StaticImage` or `placeholder: NONE` in GraphQL

**Comment by mhatvan** [comment]
Is the dominant color default a new behavior? I didn't experience this before when working with Gatsby v3. 
Also reported by https://github.com/gatsbyjs/gatsby/issues/30811 just recently.

Some additional information:
I don't encounter the wrong dominant background color (it is always transparent) when running in development, only in production build.
Additionally, there is also an image with mainly white and blue elements that has a black background placeholder.

I was able to work around the whole situation by using traced svg placeholders on all images for now.

Also not sure if using dominant color as a placeholder makes sense as in 90% of the cases it probably looks bad on a website with e.g. white background.

**Comment by ascorbic** [comment]
Dominant color has been the default since the plugin launched, but is simple to change: you can change the default in your plugin options. You can also set the background color manually. Dominant color works best for raster images (e.g. JPEG) which make up most images on the web. Traced SVG works better for transparent PNGs.

**Comment by njbmartin** [comment]
I was investigating issues upgrading from 3.2.1 to 3.5.1, ultimately diagnosing this issue:
https://github.com/gatsbyjs/gatsby/discussions/30927

While I may have found the culprit for that issue, it's a line of code that hasn't been touched for 3 years. So it didn't explain how this worked fine in 3.21, but not in 3.5.1.

After a bit more digging, I discovered like others above, the default `placeholder` was now `dominantColor` instead of `blurred`...

@ascorbic I know you say that the default has always been in `gatsby-plugin-image` since launch, but I discovered that the default `placeholder` for Contentful was only added in 3.3.0.

I have no doubt this is why we were confused by the sudden change!

https://www.gatsbyjs.com/docs/reference/release-notes/v3.3/#contributors

**Comment by ruben00001** [comment]
I have a similar problem I think. The default of 'dominant color' is working correctly on two routes of my site (amyrodriguez.art/portfolio/1 and https://www.amyrodriguez.art/press) but not on another (https://www.amyrodriguez.art/shop). I haven't changed anything on any of GatsbyImages with regard to placeholder.
