### ISSUE TITLE
Images changing their name to null on gatsby-source-wordpress

### ISSUE THREAD

**Issue by Aschab** [gatsbyjs/gatsby#30892]
## Description

When using source-gatsby-wordpress the inline images are being correctly optimized, but changing the name to `null.png `null.jpg` 

### Steps to reproduce

If you setup a gatsby-source-wordpress pointed to https://dev-dc-www-wordpress-prod.pantheonsite.io/gatsby_feed
load all the blog posts and look for the one with database id `58792` you will find a few images that are named null.png and they shouldnt.

### Expected result

The name of the image should carry

### Environment

  System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 15.13.0 - /usr/local/bin/node
    npm: 7.7.6 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 89.0.4389.128
    Safari: 13.1.3
  npmGlobalPackages:
    gatsby-cli: 3.2.0

@TylerBarnes

**Comment by veryspry** [comment]
Hi @Aschab!

Sorry to hear you're running into an issue. We tried to reproduce this on our end by creating a basic Gatsby site using the WordPress source plugin and pointing it at the graphql endpoint you provided.

To help us best begin debugging the underlying cause, it would be really helpful if you're able to create a [minimal reproduction][reproduction] as well as the GraphQL query with which you are seeing this issue. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment]
Hi!

I'm closing this as a stale issue as in the meantime Gatsby 4 and related packages were released. You can check our [Framework Version Support Page](https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/) to see which versions currently receive active support. If this is a feature request, please [create a discussion](https://github.com/gatsbyjs/gatsby/discussions/categories/ideas-feature-requests) as we moved feature requests from issues to GitHub Discussions.

Please try the mentioned issue on the latest version (using the `next` tag) and if you still see this problem, open a new bug report. It **must** include a [minimal reproduction](https://gatsby.dev/reproduction).

Thanks!
