### ISSUE TITLE
CSS-included Assets not loading on all routes

### ISSUE THREAD

**Issue by hitchcott** [gatsbyjs/gatsby#310]
I'm using semantic ui framework which requires icon font files. This works on every route in development.

After building, the icons load fine on root url, but if you refresh or visit on a different route, the icons are 404ing - as they're trying to load relatively.

**Comment by KyleAMathews** [comment]
Could you paste please the code you're using to link to them?

Almost certainly you just need to make the links to the icons absolute e.g. `/path/to/icon` instead of `path/to/icon`.

**Comment by hitchcott** [comment]
It's an npm package with a `dist` folder, which I'm importing in js.

Looking at the source, It's including the icon font along the lines of:

```
src: url("../themes/default/assets/fonts/icons.eot");
```

In both develop and bundle, it generates the request on the root url: `URL:http://0.0.0.0:8000/97493d3f11c0a3bd5cbd959f5d19b699.woff2`

But only in the bundle, if I'm at another route, it'll request:
`URL:http://0.0.0.0:8000/currentRoute/97493d3f11c0a3bd5cbd959f5d19b699.woff2`

How can I make this absolute?

**Comment by KyleAMathews** [comment]
It's possible then the webpack configuration for loading urls is wrong.
Could you investigate that?

**Comment by hitchcott** [comment]
Sure, I can take a look - although to be honest I'm using gatsby party to try and get away from webpack configs!

Where is a good place to start poking around?

**Comment by KyleAMathews** [comment]
lib/utils/webpack.config.js

**Comment by Maxhodges** [comment]
@hitchcott semantic-ui-react is now very mature. I'm thinking to see about using it with gatsby, wanted to see if you might already have blazed that trail

**Comment by hitchcott** [comment]
@Maxhodges sui-react is frigging awesome and my go-to choice right now. Highly recommended.

**Comment by Maxhodges** [comment]
@hitchcott yes yes I love it too. We are using it in a Meteor + React + Redux (blackship.com), but I've interested in using for a static site. I'm torn between trying to get it working with Gatsby, or just building the site with Metalsmith. Gatsby was a bit confusing to me. I feel Metalsmith is a better developer experience, more flexible and better documented. But wondering if I should try harder with Gatsby since it's React out-of-the-box. Have you gotten SUI-react up and running in Gatsby?
