### ISSUE TITLE
AVIF image being served as application/octet-stream

### ISSUE THREAD

**Issue by SampsonCrowley** [gatsbyjs/gatsby#31068]
## Description

Instead of being served with mime type `image/avif`, the new avif format is served with `application/octet-stream`

This is on a brand new app.

### Steps to reproduce

`npx gatsby new new-gatsby-repo`
`cd new-gatsby-repo`
`npm run develop`

### Expected result

AVIF images that are included in the _default_ starter should be rendered correctly

### Actual result

AVIF images are served with an `application/octet-stream` mime type instead of `image/avif`

This not only breaks the image rendering, but stops chrome from falling back to the created `webp` images because chrome _does_ support AVIF, so it doesn't fall back to another source

Also, as a related side note, I think there should be a config option to set known mime types for custom file extensions.

### Environment

System:
    OS: Linux 5.11 Arch Linux
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 15.1.0 - ~/.nodenv/versions/15.1.0/bin/node
    Yarn: 1.22.10 - ~/.nodenv/versions/15.1.0/bin/yarn
    npm: 7.9.0 - ~/.nodenv/versions/15.1.0/bin/npm
  Languages:
    Python: 3.9.3 - /usr/bin/python
  Browsers:
    Chrome: 91.0
    Firefox: 88.0
  npmPackages:
    gatsby: ^3.3.1 => 3.3.1
    gatsby-plugin-gatsby-cloud: ^2.2.0 => 2.3.0
    gatsby-plugin-image: ^1.2.1 => 1.3.1
    gatsby-plugin-manifest: ^3.2.0 => 3.3.0
    gatsby-plugin-offline: ^4.2.0 => 4.3.0
    gatsby-plugin-react-helmet: ^4.2.0 => 4.3.0
    gatsby-plugin-resolve-src: ^2.1.0 => 2.1.0
    gatsby-plugin-sharp: ^3.2.1 => 3.3.1
    gatsby-source-filesystem: ^3.3.0 => 3.3.0
    gatsby-transformer-sharp: ^3.2.0 => 3.3.0

**Comment by SampsonCrowley** [comment]
I tried adding a custom mime type in `onPreBootstrap`, but it didn't seem to make a difference.

```js
exports.onPreBootstrap = () => {
  mime.define({ "image/avif": [ "avif" ] })
}
```

**Comment by SampsonCrowley** [comment]
may be related to: https://github.com/lovell/sharp/issues/2666

**Comment by SampsonCrowley** [comment]
I just when through the public folder and tried to just open any generated `.avif` files directly from the file system, and they are all just small gray squares in chrome 91. they do open in GIMP. So there may also be other factors involved other than MIME type.

![Screenshot from 2021-04-26 23-24-37](https://user-images.githubusercontent.com/22461638/116189804-bdaf4000-a6e6-11eb-8afe-defb45af3664.png)

![Screenshot from 2021-04-26 23-24-57](https://user-images.githubusercontent.com/22461638/116189814-c1db5d80-a6e6-11eb-964e-6319e747a547.png)

**Comment by FelDev** [comment]
I also noticed this issue because I work in Chrome Beta and Chrome (not beta).
Check out this site: https://gatsbystarterdefault73442.gatsbyjs.io/ (it's an unmodified fork of [gatsby-starter-default](https://github.com/gatsbyjs/gatsby-starter-default))

In Chrome, the .avif file loads normally, but in Chrome Beta as well as Chrome Dev it just serves a tiny square https://gatsbystarterdefault73442.gatsbyjs.io/static/6d91c86c0fde632ba4cd01062fd9ccfa/f5860/gatsby-astronaut.avif

For some reason, the demo version of gatsby-starter-default doesn't have this problem: https://gatsby-starter-default-demo.netlify.app/
But I literally just pressed the "Deploy to Gatsby Cloud" button in the gatsby-starter-default repo to make my example (https://gatsbystarterdefault73442.gatsbyjs.io/).

Hope this helps!

**Comment by pieh** [comment]
> may be related to: [lovell/sharp#2666](https://github.com/lovell/sharp/issues/2666)

I think this is the reason for displaying incorrectly (gray square). I tried using some sample `.avif` image and serving with out express app and despite being `application/octet-stream` it was displaying correctly in Chrome Canary.

So while content type would be good to be correct, it doesn't seem like is the thing that cause issues.

> tried adding a custom mime type in `onPreBootstrap`, but it's already defined as `image/avif`
> 
> ```js
> // gatsby-node.js
> exports.onPreBootstrap = () => {
>   mime.define({ "image/avif": [ "avif" ] })
> }
> ```
> 
> causes warning:
> 
> ```
> Error: Attempt to change mapping for "avif" extension from "image/avif" to "image/avif". Pass `force=true` to allow this, otherwise remove "avif" from the list of extensions for "image/avif".
> ```

Hey, this is because `mime` that is used for serving is not the same as the one you are defining (you are defining on newer one which already includes `avif`):

```
yarn why v1.22.10
[1/4] 🤔  Why do we have the module "mime"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "mime@2.5.2"
info Has been hoisted to "mime"
info Reasons this module exists
   - Hoisted from "gatsby#mime"
   - Hoisted from "gatsby-source-filesystem#mime"
   - Hoisted from "gatsby#st#mime"
   - Hoisted from "gatsby#webpack-dev-server#webpack-dev-middleware#mime"
info Disk size without dependencies: "92KB"
info Disk size with unique dependencies: "92KB"
info Disk size with transitive dependencies: "92KB"
info Number of shared dependencies: 0
=> Found "send#mime@1.6.0"
info This module exists because "gatsby#express#send" depends on it.
info Disk size without dependencies: "76KB"
info Disk size with unique dependencies: "76KB"
info Disk size with transitive dependencies: "76KB"
info Number of shared dependencies: 0
=> Found "load-bmfont#mime@1.6.0"
info This module exists because "gatsby-plugin-sharp#potrace#jimp#@jimp#custom#@jimp#core#load-bmfont" depends on it.
info Disk size without dependencies: "76KB"
info Disk size with unique dependencies: "76KB"
info Disk size with transitive dependencies: "76KB"
info Number of shared dependencies: 0
```

`mime` used by express is the 1.6.0 (one that is dependency of `send`). This one doesn't include the `avif` one. 

According to http://expressjs.com/en/resources/middleware/serve-static.html#different-settings-for-paths we can get "hold" of `mime` package that is actually used by our express app, so I'll go ahead and same entry you did there.
