### ISSUE TITLE
gatsby-source-shopify altText does not exist for collection and article objects

### ISSUE THREAD

**Issue by dungle-scrubs** [gatsbyjs/gatsby#31235]
This is more of a feature request.

Regarding `gatsby-source-shopify` (version 4.5.0-next.0 as of this writing): While product nodes' image arrays contain altText values to query, article and collection nodes could also include these for a better shop owner / developer experience.

Editing the alt text of these two images objects are a permanent feature in Shopify's admin. Because this feature cannot be disabled by a developer, I makes sense for these values to pass through to Gatsby's data layer.  Without this, it's not possible to use the `alt` attribute the way it's meant, even if built programatically.

**Comment by LekoArts** [comment]
Hi!

For feature requests please use https://github.com/gatsbyjs/gatsby/discussions/categories/ideas-feature-requests in the future.

But since the current Shopify source plugin will soon be replaced with https://github.com/gatsbyjs/gatsby-source-shopify I'd recommend using this forward. For the time being you can open an issue there if it doesn't already have the feature you want. Please keep in mind that you can modify the GraphQL query of what to fetch.
