### ISSUE TITLE
Gatsby build stuck after "success Caching JavaScript and CSS webpack compilation"

### ISSUE THREAD

**Issue by shivaping** [gatsbyjs/gatsby#31281]
## Description

After upgrading to 3.4.0 we are seeing Gatsby build stuck after "success Caching JavaScript and CSS webpack compilation"

### Steps to reproduce

npm install
npm run-script build

How to Make a Minimal Reproduction: https://www.gatsbyjs.com/contributing/how-to-make-a-reproducible-test-case/

### Expected result

It should out put the files to public folder

### Actual result

Build stuck at Gatsby build stuck after "success Caching JavaScript and CSS webpack compilation"

### Environment

  System:
    OS: Windows Server 2016 10.0.14393
    CPU: (2) x64 Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz
  Binaries:
    Node: 12.20.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.18
  Browsers: {}
  npmGlobalPackages:
    gatsby-cli: 3.4.1
flags: { PRESERVE_WEBPACK_CACHE: true, PRESERVE_FILE_DOWNLOAD_CACHE: true },

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by shivaping** [comment]
[log (26).txt](https://github.com/gatsbyjs/gatsby/files/6434603/log.26.txt)
attaching the log

**Comment by supriome** [comment]
I have the same problem.

**Comment by supriome** [comment]
@shivaping After I delete `PRESERVE_WEBPACK_CACHE: true` in `gatsby-config.js`, then the build is successful. Maybe you should try this solution if you enable `PRESERVE_WEBPACK_CACHE` in `flags` object.

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

I just now see that your issue is about a specific experiment/flag we currently have. We collect any feedback (bug reports, feature requests, questions, etc.) inside a respective discussion in the [Umbrella Discussions](https://github.com/gatsbyjs/gatsby/discussions/categories/umbrella-discussions) category.

Please direct your feedback here: https://github.com/gatsbyjs/gatsby/discussions/28331

Thanks!

**Comment by shivaping** [comment]
> @shivaping After I delete `PRESERVE_WEBPACK_CACHE: true` in `gatsby-config.js`, then the build is successful. Maybe you should try this solution if you enable `PRESERVE_WEBPACK_CACHE` in `flags` object.

I tried this @supriome. still no luck

**Comment by supriome** [comment]
Try upgrading to 3.5.0? I see this [Experimental: Enable webpack persistent caching for production builds](https://www.gatsbyjs.com/docs/reference/release-notes/v3.4#experimental-enable-webpack-persistent-caching-for-production-builds) on release note on 3.4.0. But then I have this problem you face. So I disable it.
