### ISSUE TITLE
Improve new Gatsby Image Plugin docs with examples

### ISSUE THREAD

**Issue by AnderUstarroz** [gatsbyjs/gatsby#31301]
## Summary

Static image generation seems pretty straight forward nonetheless Dynamic image generation just gives this example:

```
query {
  blogPost(id: { eq: $Id }) {
    title
    body
    avatar {
      childImageSharp {
        gatsbyImageData(width: 200)
      }
    }
  }
}
```
But it's not clear what **avatar** is: 

- Should it be a public URL pointing to an image? 
- Should it be a relative/absolute path to some existing image in localhost that requires `gatsby-source-filesystem`? 
- Should it be raw base64 image encoded data?

### Motivation

I have found many people getting confused  (including myself) on how to implement the Gatsby Dynamic images.

## Steps to resolve this issue

Adding a short example of how the dynamic data was obtained will clarify things, for instance:
```
{
    title: "some text",
    body: "my description",
    avatar: "https://mysite.com/my-image.jpg"  < -- Not sure if this is allowed or must be a local image.
}
```

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

You're referring to this section: https://www.gatsbyjs.com/docs/how-to/images-and-media/using-gatsby-plugin-image/#dynamic-images

In the introduction we have this part:

> For other data sources, images are downloaded and processed locally at build time. This section shows how to use gatsby-transformer-sharp to query for these images.

In the first step this part:

> Any GraphQL File object that includes an image will have a childImageSharp field that you can use to query the image data.

That's how `avatar` came to be. It's a local file created by `gatsby-source-filesystem`. The linked https://www.gatsbyjs.com/plugins/gatsby-transformer-sharp/ has this section at the top:

> Please note that you must have a source plugin (which brings in images) installed in your project. Otherwise, no ImageSharp nodes can be created for your files. Examples would be gatsby-source-filesystem or source plugins for (headless) CMSs like gatsby-source-wordpress.

---

What section was unclear to you that would need further explanation?

The answer to all three questions of yours is condensed in this paragraph:

> Any GraphQL File object that includes an image will have a childImageSharp field that you can use to query the image data.

One:

> Should it be a public URL pointing to an image?

This only works if you download the image and thus have a `File` node: https://www.gatsbyjs.com/docs/how-to/images-and-media/preprocessing-external-images/

Otherwise it won't work.

Two:

> Should it be a relative/absolute path to some existing image in localhost that requires gatsby-source-filesystem?

It can be, but doesn't have to. Since this is an arbitrary example the image can also come from a CMS or your custom source plugin.

Three:

> Should it be raw base64 image encoded data?

No, it needs to be a valid `File` node
