### ISSUE TITLE
Build problem using NPM package (google-maps-react) to add Gmaps

### ISSUE THREAD

**Issue by IronTony** [gatsbyjs/gatsby#3134]
Hi all,

I am trying to use this package `google-maps-react` to add GMaps to my Gatsby project (Gatsby v.1.9.102).
Everything seems to work well, but when I build the application, I get back the following error:

![image](https://user-images.githubusercontent.com/3645225/33618407-c1a62ec8-d9e2-11e7-8551-c587470ba752.png)

So I added to my `gatsby-node.js` the following code:
```
if (stage === 'build-html') {
    config.loader('null', {
      test: [/bootstrap/, /GoogleApi/],
      loader: 'null-loader'
    })
  }
```
But without success, as you can see:

<img width="608" alt="screen shot 2017-12-05 at 17 39 34" src="https://user-images.githubusercontent.com/3645225/33618690-85311d8a-d9e3-11e7-91d6-5d1a6700f504.png">

Any hint would be more than appreciated.
Thank you in advance

**Comment by jquense** [comment]
using the null loader only works if the code path isn't hit in the static build mode, which in your case it is, hence the second error. 

Since the google api wrapper depends on the `window` object you need to not use it when the window doesn't exist. In tandem with the null-loader setup I'd either export nothing if it doesn't exist or export a dummy object:

```js
let api = !GoogleApiWrapper ? {} : GoogleApiWrapper({ ... })
```

**Comment by jbolda** [comment]
It sounds as if that module is not built for server side rendering. See https://www.gatsbyjs.org/docs/debugging-html-builds/#how-to-check-if-window-is-defined for additional details.

**Comment by IronTony** [comment]
@jbolda you were right. I replaced the `google-maps-react` with `react-gmaps` and rewrote some part of my code and now it works great.
