### ISSUE TITLE
[gatsby-source-wordpress] REMOTE_NODE_NOT_YET_UPDATED preview post

### ISSUE THREAD

**Issue by amcc** [gatsbyjs/gatsby#31528]
## Description

Trying to preview a post (happens to be a custom post type) in wordpress with the preview button. Preview remains on "Loading Preview" and eventually states that it is taking too long.

In the console I have "REMOTE_NODE_NOT_YET_UPDATED, this is ticking along and logging every five seconds or so

I'm using gatsby cloud and confirm that the preview is triggering and successfully rebuilding and creating the preview site and page (at the normal preview url outside of the wordpress site). I have no filters on createPages, I am passing the id through context

### Steps to reproduce

The info in my site is private currently - using the following versions:
"gatsby-source-wordpress": "^5.5.1"
WP Gatsby: 1.0.10
WP GraphQL: 1.3.8

### Expected result

Preview should load for post

### Actual result

Preview remains in loading state. Though it does rebuild when i navigate to the preview url, and i can see it refreshing in gatsby clound

### Environment

System:
    OS: macOS Mojave 10.14.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
    npm: 6.14.10 - ~/.nvm/versions/node/v14.15.4/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 90.0.4430.212
    Safari: 14.0.3
  npmPackages:
    gatsby: ^3.1.2 => 3.4.1
    gatsby-plugin-gatsby-cloud: ^2.1.0 => 2.4.1
    gatsby-plugin-global-context: ^1.0.0 => 1.0.0
    gatsby-plugin-image: ^1.4.0 => 1.4.0
    gatsby-plugin-manifest: ^3.1.0 => 3.4.0
    gatsby-plugin-react-helmet: ^4.1.0 => 4.4.0
    gatsby-plugin-sass: ^4.3.0 => 4.4.0
    gatsby-plugin-sharp: ^3.1.2 => 3.4.1
    gatsby-plugin-sitemap: ^3.1.0 => 3.3.0
    gatsby-plugin-svgr: ^3.0.0-beta.0 => 3.0.0-beta.0
    gatsby-source-filesystem: ^3.1.0 => 3.4.0
    gatsby-source-wordpress: ^5.5.1 => 5.5.1
    gatsby-transformer-sharp: ^3.1.0 => 3.4.0
  npmGlobalPackages:
    gatsby-cli: 3.3.0

**Comment by aaronetales** [comment]
I also have this issue.

**Comment by jacksellwood** [comment]
We're working on a similar bug (not documented here in GH). We'll loop back here once we have a potential fix.

**Comment by moonmeister** [comment]
Any update on the fix?

**Comment by TylerBarnes** [comment]
@moonmeister unfortunately there isn't. The errors on the WP side are very generic (there are only 3 or 4 possible errors in the loader) and any problem on the Gatsby or WP side can trigger them. So for example 10 different issues could all have this same error on the WP side due to this. This is because WP being on a different server doesn't have as much context about Gatsby and Gatsby Cloud. 

I'm going to close this issue because of that and recommend that everyone who runs into this issue open a Gatsby Cloud support request so we can work more easily together with things like private repos and WP backends.

For what it's worth we are working on a Gatsby Cloud preview loader service which will have more context on Cloud and the Gatsby process as it will live on the Cloud side instead of the WP side. It's being built to work with all sources and should generally be less prone to these kinds of issues.
