### ISSUE TITLE
Using sass with svgs as data uris, build reports Css Minimizer Plugin errors

### ISSUE THREAD

**Issue by spikyjt** [gatsbyjs/gatsby#31619]
## Description

Using sass with svgs as data uris, e.g. with Bootstrap, running build reports errors in the Css Minimizer Plugin config, related to postcss-svgo.

e.g.
```
Css Minimizer Plugin: postcss-svgo: [SCSS FILE PATH, LIINE NO]: Error: Plugin name should be specified
warn undefined
```

### Steps to reproduce

Install a basic gatsby starter with scss enabled, including gatsby-plugin-sass.
Add bootstrap and import bootstrap.scss in gatsby-browser.js.
Run `npm build`

### Expected result

No errors. Sass built with svgs.

### Actual result

Errors.

### Environment

```
  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    npm: 6.14.13 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Safari: 14.1
  npmPackages:
    gatsby: ^3.6.1 => 3.6.1 
    gatsby-plugin-react-helmet: ^4.6.0 => 4.6.0 
    gatsby-plugin-resolve-src: ^2.1.0 => 2.1.0 
    gatsby-plugin-sass: ^4.6.0 => 4.6.0 
    gatsby-plugin-sitemap: ^4.2.0 => 4.2.0 
```

**Comment by spikyjt** [comment]
I've tracked this down to the config for svgo in webpack-utils and proposed solutions here https://github.com/gatsbyjs/gatsby/pull/15636#issuecomment-846611862

I've asked for comments from the contributors to the PR that is responsible for this @m-allanson @pieh but perhaps commenting on an old PR wasn't the best approach.

I'd like to know what the intention was of the original PR, so that I can create a new one to correct this.

**Comment by pieh** [comment]
Let's not use old PR (I'm not following old PRs), and continue here:

It seems like the current config (what we set in linked PR) was working ... back then ( https://github.com/svg/svgo/blob/d17c429c4f12467fa2beee2d7396bbcb1074bf05/lib/svgo/config.js#L206-L230 ), but since then we bumped optmizer and by that also `svgo` (from ^1 to ^2) and now it needs config in shape like you mentioned in your comment (?).

As for intention (quite a long time ago), but I think it was just matter that default config had some potentially dangerous optims/transforms that at least in some cases caused problems ( https://github.com/gatsbyjs/gatsby/issues/15629 )

Thanks for opening PR to fix the config for currently used svgo version!

**Comment by spikyjt** [comment]
It looks like an array of strings is fine, or an array of individual plugin objects, as I've used, but not one big object with plugin names as properties and boolean values to indicate enabled/disabled.
