### ISSUE TITLE
Error: connect ETIMEDOUT

### ISSUE THREAD

**Issue by Quernest** [gatsbyjs/gatsby#31737]
## Description

I can't launch / build the project because the plugin constantly throws ETIMEDOUT error (most often for **MediaItem**).

### Steps to reproduce

Just follow this instruction:
https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/docs/getting-started.md

gatsby-config.js
```js
{
  resolve: 'gatsby-source-wordpress',
  options: {
    url: process.env.WPGRAPHQL_URL,
  },
}
```

Then

```bash
yarn start
```

### Expected result

Expect that the project will be launched and the requests will be fulfilled.

- how to increase timeout?
- can I possibly skip these errors?

### Actual result
Some time for random query:
![изображение](https://user-images.githubusercontent.com/21086792/120538797-9c312a80-c3ef-11eb-9910-9f041a0d3680.png)

And for MediaItem (very often)

![120539428-3ee9a900-c3f0-11eb-9814-eaf239628f52](https://user-images.githubusercontent.com/21086792/120539834-abfd3e80-c3f0-11eb-8220-c014901846a6.png)

### Environment

![изображение](https://user-images.githubusercontent.com/21086792/120539973-d3540b80-c3f0-11eb-8628-707703b87aed.png)

### What I tried

1) package.json (didn't help)

```json
"develop": "GATSBY_CONCURRENT_DOWNLOAD=5 gatsby develop",
```

2) config options (didn't help)

gatsby-config.js
```js
{
  // ...
  MediaItem: {
    localFile: {
      requestConcurrency: 5,
    },
    lazyNodes: false,
  },
  html: {
    useGatsbyImage: true,
    fallbackImageMaxWidth: 200,
    createStaticFiles: true,
    imageMaxWidth: 756,
  },
  schema: {
    timeout: 3000000,
    requestConcurrency: 5,
  },
  // ...
}
```

Halp!

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by ThyNameIsMud** [comment]
Timeouts for creating a new node aren't directly applied to fetching a remote node. Instead of using `gatsby-source-filesystem` the `gatsby-source-wordpress` plugin decided to reimplement it.

https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/src/steps/source-nodes/create-nodes/create-remote-file-node/index.js#L58

These timeouts **need** to be adjustable because there is no one-size-fits-all solution here. These calls **ALWAYS** fail after a threshold. This is the second time an issue like this has burned me, the first time was from the `gatsby-source-filesystem` which I submitted the fix for. Now it's this reimplemented solution that needs it.

**Comment by iamkratos** [comment]
@ThyNameIsMud could you plz recommend a way I can implement a temporary fix to the plugin in my local plugins folder? Would love to throw a bandaid on this until it is addressed

**Comment by ThyNameIsMud** [comment]
`node_modules/gatsby-source-wordpress/dist/steps/source-nodes/create-nodes/create-remote-file-node/index.js`

Look for `got.stream` in the file and the timeout associated. Change it to look like

```
const responseStream = got.stream(url, {
    headers,
    timeout: { send: CONNECTION_TIMEOUT },
    retries: CONNECTION_RETRY_LIMIT,
    ...httpOpts
});
```

This will have the timeout execute when the socket is connected instead of when it's queued. The documentation notes how the times are treated: https://github.com/sindresorhus/got/tree/v11.7.0#timeout

You may want to adjust `CONNECTION_TIMEOUT` or `STALL_TIMEOUT` as well.

You will want to use something like [patch-patch](https://github.com/ds300/patch-package#readme) to make the change until this is properly fixed

**Comment by TylerBarnes** [comment]
@ThyNameIsMud that's really good to know. The createRemoteFileNode helper was forked in the WP package to fix some issues with it and the fixes were never added back to the main copy of it. We'll be refocusing efforts on the WP plugin in the next couple months and will likely move back to using the main helper instead of the forked one at that time.
