### ISSUE TITLE
community.md - translations as a form of contributing are redundant

### ISSUE THREAD

**Issue by weronikadominiak** [gatsbyjs/gatsby#31883]
## Summary

Hi! Recently I wanted to contribute to [gatsby/gatsby-pl](https://github.com/gatsbyjs/gatsby-pl), but after a short conversation I've found out that translations are on hold (See [this comment](https://github.com/gatsbyjs/gatsby-pl/issues/1#issuecomment-859770467)), but there's no information about it on gatsbyjs.com and it still encourages to contribute in translations.

Could we please update [community.md](https://github.com/weronikadominiak/gatsby/blob/master/docs/contributing/community.md#ways-to-contribute) (and potentially [contributing/translation](https://github.com/weronikadominiak/gatsby/tree/master/docs/contributing/translation))?

I'm happy to create PR with the change if you would confirm the information above that translations are no longer required.

### Motivation

Someone might want to work on a translation that won't be used. 

## Steps to resolve this issue

Include an annotation that at the moment translations are on hold or remove them completely from the docs.

**Comment by LekoArts** [comment]
cc @meganesu

**Comment by AdamSiekierski** [comment]
@meganesu 👀 :)

**Comment by meganesu** [comment]
Hi there! Thanks for your patience (I've been on PTO the last few weeks).

You're totally right, we should update the Contributing docs to let folks know that translations are on hold.

If you're still willing to open a PR, I think it makes sense to add a note to those docs you mentioned, as well as each of the docs under the "Translating the Gatsby Documentation" dropdown. It's probably fine to use the same message across all the docs, so that people will see the same information regardless of which page they're entering from. You could use some of the language from @LekoArts's message in the Discord.

Thanks for flagging this! Let me know if you have any questions or other thoughts 💜

**Comment by weronikadominiak** [comment]
Hi! No worries, I hope you had a nice time off!

Sure, I can prepare a PR. Will work on it over a weekend. :)

Thanks! :)
