### ISSUE TITLE
Could you help remove the vulnerabilities from your dependency? 

### ISSUE THREAD

**Issue by paimon0715** [gatsbyjs/gatsby#32257]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Hi,@KyleAMathews
### Issue

   1 vulnerability (medium severity) is introduced in **_gatsby-transformer-remark_**:
   Vulnerability **CVE-2021-23368** (medium severity) is detected in package **_postcss_** (versions: >=7.0.0 <8.2.10):  [https://snyk.io/vuln/SNYK-JS-POSTCSS-1090595](https://snyk.io/vuln/SNYK-JS-POSTCSS-1090595)
  The above vulnerable package is transitively referenced by **_gatsby-transformer-remark_** via:
` gatsby-transformer-remark@2.16.1 ➔ sanitize-html@1.27.5 ➔ postcss@7.0.35`

### Solution
Since **_gatsby-transformer-remark 2.16.*_** is transitively referenced by **187** downstream projects (e.g., [gatsby-theme-apollo-docs 4.8.0-alpha.1](https://www.npmjs.com/package/gatsby-theme-apollo-docs) (latest version),[formare 0.5.2](https://www.npmjs.com/package/formare) (latest version), [@docpocalypse/gatsby-theme 0.11.30](https://www.npmjs.com/package/@docpocalypse/gatsby-theme)  (latest version), [@reflexjs/gatsby-theme-base 0.6.4](https://www.npmjs.com/package/@reflexjs/gatsby-theme-base) (latest version), [@docpocalypse/gatsby-theme-core 0.8.19](https://www.npmjs.com/package/@docpocalypse/gatsby-theme-core)) (latest version)), 

If **_gatsby-transformer-remark_** removes the vulnerable packages from the above versions, then its fixed version can help downstream users decrease their pain.

Could you help update packages in these versions?

### Fixing suggestions

In **_gatsby-transformer-remark 2.16.*_**, you can kindly perform the following upgrades :
`sanitize-html ^1.27.5 ➔ 1.16.0 `;  

**Note:**
_sanitize-html@1.16.0 directly depends on postcss@8.3.5 (a vulnerability CVE-2021-23368  patched version)_

Thanks for your contributions to the npm ecosystem!

Best regards,
Paimon

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

While those audit messages might seem scary they are almost always irrelevant in the context of Gatsby as it's a build tool. So there is nothing to "fix" as the warning is not relevant.

Gatsby creates static assets and runs everything at build time and not during runtime. `npm audit` is designed for runtime / Node apps so it flags issues that can occur there. This means that almost every "vulnerability" report we receive are false positives. While in principle Gatsby can also have vulnerabilities you need to make sure that it's relevant to Gatsby before reporting it. For example a "Regex DDOS attack" can never be a real vulnerability for a development-time tool. If you want to override/update a transitive dependency you can use [yarn resolutions](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/).

If you know that a vulnerability affects Gatsby because you understand what the vulnerability is, please report it [here](https://github.com/gatsbyjs/gatsby/blob/master/SECURITY.md). Thanks!
