### ISSUE TITLE
Building static site from contentful

### ISSUE THREAD

**Issue by micahrye** [gatsbyjs/gatsby#324]
Is it possible to use a service like [Contentful](https://www.contentful.com/) with Gatsby. I want to build a static site from content stored/created on Contentful. Unfortunatly it does not work, and while the data is retrieved while running develop server, the build does not capture/use the content from Contentful. 

This hybrid feature would be nice, pointers on where to start building this into Gatsby would be welcome too.

**Comment by KyleAMathews** [comment]
Hi how are you doing the integration now? I'm not overly familiar with
contentful. Probably what you need to do though is write a script which
automatically copies down content to files within the Gatsby pages
directory.

**Comment by ivanoats** [comment]
I'm working on this too - I have a build step that connects to Contentful and then writes out the .md files needed for the build. I can ask if I can open source the code.

**Comment by micahrye** [comment]
Ivanoats - if you can open source it I would be interested in contributing rather than starting from scratch. I want to use Gatsby for a project and in scoping out the project contentful fits one side and I want to use reactjs and Gatsby for the other side. 

Kyle - not doing any integration yet. Just been scoping a project and deciding on tech approach. I think such support for something like contentful will be a nice addition though.

**Comment by KyleAMathews** [comment]
@micahrye @ivanoats nice 👍 FYI, I'm going to be working fairly soonish on a site that will pull content from Evernote & (probably) Dropbox. I have some ideas for APIs that could be added to Gatsby that would simplify integration with 3rd party content sources as it'd be nice if each content source could have a robust Gatsby plugin. It'll be a little while so continue on with your approach but let's collaborate on a core solution down the road a bit.

**Comment by micahrye** [comment]
sounds good, will do :)

**Comment by ivanoats** [comment]
Here's the script I am using to pull down data from Contentful:
https://gist.github.com/ivanoats/e79ebbd711831be2536d1650890055c4

I run this via an npm run script before gatsby build.

I would love to work on a plugin or get ideas on better architecture for this process.

**Comment by erlend-sh** [comment]
> I have some ideas for APIs that could be added to Gatsby that would simplify integration with 3rd party content sources as it'd be nice if each content source could have a robust Gatsby plugin.

That sounds awesome. We've been playing with ideas like these for @discourse/discourse as well. Would for instance love to see a straight forward way to use Discourse as a backend for docs solutions like this one:

http://blog.discourse.org/2016/05/using-discourse-as-a-community-powered-wiki/

**Comment by KyleAMathews** [comment]
@erlend-sh the new version of Gatsby will be perfect for this! Totally love the idea of Discourse-powered sites as well.

If you read the "Pull instead of push" section in my recent blog post https://bricolage.io/gatsby-open-source-work/ basically what you'll be able to do for Discourse is create a GraphQL schema that wraps the Discourse REST API and then construct a site where page-providing components query Discourse directly for the data they need.

With Gatsby's support for themes, you'd be able to distribute a ready-to-use version of this e.g. for the community-powered-wiki use case.

**Comment by micahrye** [comment]
Cool. I have been busy between projects, but I did implement something with Gatsby + Contentful. Starting to explore using Gatsby in a hybrid way of static and distributed data. As I get more time I will try and structure it and see if it might be a PR.

**Comment by Khaledgarbaya** [comment]
Hey Guys,

I am maintaining the Contentful JS SDK and I will be glad to provide help/direction for building the integration.
I think you Using the Sync api through the SDK would be a good idea to pull only the changed/new data and then write to md files as @ivanoats mentionned.

Cheers,
Khaled

**Comment by vishalniit** [comment]
Hi @Khaledgarbaya ,

Did you eventually create a plugin or resource on how to get Contentful integrated with gatsby. I wish to discuss further. Our team has decided to use contentful as CMS.
Our goal is to enable content authoring at CMS and clck of button have ability to publish to live website where it runs on gatsby.
Oviously we are looking in hybrid model, where few of content we want to download to local files which can be queried by graphql data layer now in alpha release & for few cases fetch data dynamically.

Regards
Vishal Gupta

**Comment by ivanoats** [comment]
I am still interested in helping out on this, too. Just let me know if anyone has progressed beyond the snippet I wrote.

**Comment by 0x80** [comment]
I recently worked on a scraping tool for Contentful. It's not completely finished but already useful I think.

It takes the data and optionally converts it to a simple structure that contains only the fields from your models (stripping out the sys metadata). It then downloads the assets either in bundled form per entry or all in one place.

It doesn't have any priority for me at the moment since I'm working with a different CMS now, but I will see if I can release it at the end of this week. I would be interested to see some people collaborate on this.

**Comment by Khaledgarbaya** [comment]
hi @vishalniit and @ivanoats , 
I started something [here](https://github.com/Khaledgarbaya/gatsby-contentful)  but it is not production ready nor fully functioning yet. 
Unfortunately, I had to pause working on it due to lack of time.
Please note this is not an official Contentful plugin it was just a personal project I started.
Feel free to grab the code, hopefully, or contribute to it I will be more than happy to help and give guidance.
Best,
Khaled

**Comment by KyleAMathews** [comment]
FYI, the plugin architecture changed recently w/ alpha13. If anyone will be working on this soon, checkout the [filesystem source plugin](https://github.com/gatsbyjs/gatsby/blob/1.0/packages/gatsby-source-filesystem/src/gatsby-node.js) and the (coming) [Hacker News source plugin](https://github.com/gatsbyjs/gatsby/pull/841/files#diff-521aa63ad67aded67123b7e822435f9a).

**Comment by KyleAMathews** [comment]
Would love your feedback on creating source plugins! There'll be dozens/hundreds of these so it's really important to get the API spot on. Actually, ping me if you will be working on this because I should document this.

**Comment by 0x80** [comment]
@KyleAMathews I'd like to go over te source plugin and see if I can so one for a CMS, but documentation is very welcome as a start.

I've noticed that the plugins in alpha13 compile the source to their root. Is there a reason you're not using the standard `dist` or `lib` folders common to transpiled node modules?

**Comment by KyleAMathews** [comment]
Very quick documentation.

A source plugin is responsible for defining nodes. Transformer plugins listen for new nodes being created and can either add additional fields to nodes created by the source or transform them into new fields.

You use bound action creators from Redux to create and update nodes. You can see those in use in the filesystem and hacker news source plugins.

You can see the required fields here: https://github.com/gatsbyjs/gatsby/blob/1.0/packages/gatsby/lib/joi-schemas/joi.js#L19

On why no dist/lib folders — it's mainly because I don't want to have to rely on compiling the modules and not using a dist/lib folder means you have the option of writing straight uncompiled JS. I want to add support for sites to have a "plugins" folder where more complex sites can split up functionality into multiple plugins. We could add some sort of config in plugin's package.json to say where code is but [the code for finding plugins](https://github.com/gatsbyjs/gatsby/blob/1.0/packages/gatsby/lib/bootstrap/index.js#L110) is simpler by saying code is at the root of the plugin. I guess there's nothing preventing us from reading something out of a plugin's package.json which says where the code is at. We can't use the common convention of the index.js exporting the location of things because gatsby-node/gatsby-browser/gatsby-ssr code are all incompatible with each other given possible webpack/babel enhancements to the language.

**Comment by 0x80** [comment]
@KyleAMathews thanks for the feedback. I don't think I agree with your points about the src/dist folders. Maybe I'm missing something, but in any case I'll take this to separate issue discussing the plugin API.

**Comment by KyleAMathews** [comment]
@mericsson added a source plugin for Contentful as well as an example website so considering this
issue fixed now.

https://using-contentful.gatsbyjs.org/
