### ISSUE TITLE
Is it possible to remove the vulnerability introduced by css-what ?

### ISSUE THREAD

**Issue by vincentsum777** [gatsbyjs/gatsby#32657]
Hi, @KyleAMathews @pieh, I stumbled upon a vulnerability introduced by package **css-what@3.4.2**:
### Issue Description
I accidentally find that **_gatsby@2.32.13_** transitively depends on **css-what@3.4.2**. However, the vulnerability [**CVE-2021-33587**](https://snyk.io/vuln/SNYK-JS-CSSWHAT-1298035) is detected in package **css-what<5.0.1)**.  
   As far as I aware,  **gatsby@2.32.13** is so popular that a large number of projects depend on it ([68,468 downloads per week](https://www.npmjs.com/package/gatsby/v/2.32.13?activeTab=versions) and about **2,007 downstream projects**, e.g., @prismicio/gatsby-source-prismic-graphql 3.6.13, @sentrei/blog 1.42.0, decentraland-gatsby 3.41.7, @antv/gatsby-theme-antv 1.1.6, maga-components 1.0.0-beta.41, etc.). 
In this case, the vulnerability [**CVE-2021-33587**](https://snyk.io/vuln/SNYK-JS-CSSWHAT-1298035) can be propagated into these downstream projects and expose security threats to them.
   As you can see, **_gatsby@2.32.13_** is introduced into the above projects via the following package dependency paths:
(1)`@moneygeek/ui-components@1.122.0 ➔ docz@2.3.1 ➔ gatsby@2.32.13 ➔ optimize-css-assets-webpack-plugin@5.0.8 ➔ cssnano@4.1.11 ➔ cssnano-preset-default@4.0.8 ➔ postcss-svgo@4.0.3 ➔ svgo@1.3.2 ➔ css-select@2.1.0 ➔ css-what@3.4.2`
(2)`maga-components@1.0.0-beta.41 ➔ docz@2.3.1 ➔ gatsby@2.32.13 ➔ optimize-css-assets-webpack-plugin@5.0.8 ➔ cssnano@4.1.11 ➔ cssnano-preset-default@4.0.8 ➔ postcss-svgo@4.0.3 ➔ svgo@1.3.2 ➔ css-select@2.1.0 ➔ css-what@3.4.2`
    **......**

I know that it's kind of you to have removed the vulnerability since **_gatsby@3.0.0-next.5_**. But, in fact, the above large amount of downstream projects cannot easily upgrade **gatsby** from version **_2.32.13_** to _**(>=3.0.0-next.5)**_:
    The projects such as **docz**, which introduced **gatsby@2.32.13**, are not maintained anymore. These unmaintained packages can neither upgrade **gatsby** nor be easily migrated by the large amount of affected downstream projects.  

   **Given the large number of downstream users, is it possible to release a new patched version with the updated dependency to remove the vulnerability from package gatsby@2.32.13?**

### Suggested Solution

Since these inactive projects set a version constaint **2.32.\*** for **gatsby** on the above vulnerable dependency paths, if **gatsby** removes the vulnerability from **2.32.13** and releases a new patched version **_gatsby@2.32.14_**, such a vulnerability patch can be automatically propagated into the downstream projects.

The simplest way to remove the vulnerability is to perform the following upgrade in **_gatsby@2.32.14_**:
`optimize-css-assets-webpack-plugin ^5.0.3 ➔ ^6.0.0`;  
**Note:**
**_optimize-css-assets-webpack-plugin@6.0.0(>=6.0.0)_** transitively depends on **css-what@5.0.1** which has fixed the vulnerability ([**CVE-2021-33587**](https://snyk.io/vuln/SNYK-JS-CSSWHAT-1298035))
Of course, you are welcome to share other ways to deal with the issue.

Thank you for your attention to this issue.^_^

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

While those audit messages might seem scary they are almost always irrelevant in the context of Gatsby as it's a build tool. So there is nothing to "fix" as the warning is not relevant.

Gatsby creates static assets and runs everything at build time and not during runtime. `npm audit` is designed for runtime / Node apps so it flags issues that can occur there. This means that almost every "vulnerability" report we receive are false positives. While in principle Gatsby can also have vulnerabilities you need to make sure that it's relevant to Gatsby before reporting it. For example a "Regex DDOS attack" can never be a real vulnerability for a development-time tool. If you want to override/update a transitive dependency you can use [yarn resolutions](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/).

If you know that a vulnerability affects Gatsby because you understand what the vulnerability is, please report it [here](https://github.com/gatsbyjs/gatsby/blob/master/SECURITY.md). Thanks!
