### ISSUE TITLE
Webpack Error #98123: Javascript Dev Bundle Build Fail

### ISSUE THREAD

**Issue by TylerAPfledderer** [gatsbyjs/gatsby#33224]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

After updating Gatsby to 1.13.1 to address the [Webpack issue #33216](https://github.com/gatsbyjs/gatsby/issues/33216), I have now discovered a new error from Webpack,  stating `Generating development JavaScript bundle failed`.

I tried the suggestion provided in [Closed Ticket #17557](https://github.com/gatsbyjs/gatsby/issues/17557#issuecomment-531518940) to no avail. I am using yarn.

What might I be overlooking here?

Thank you!!

### Reproduction Link

https://github.com/TylerAPfledderer/coffeeroaster-subscription-site

### Steps to Reproduce

Not able to recreate in minimal reproduction

### Expected Result

Successful development build to view in localhost

### Actual Result

The following full message in terminal:
```
ERROR #98123  WEBPACK

Generating development JavaScript bundle failed

Invalid Options:
- Unknown options: test, options

failed Building development bundle - 19.221s
ERROR in Invalid Options:
- Unknown options: test, options
```

### Environment

```
  System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 14.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.9.0 - /c/Python39/python
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (93.0.961.47)
  npmPackages:
    gatsby: ^3.13.1 => 3.13.1 
    gatsby-cli: ^3.13.0 => 3.13.0 
    gatsby-plugin-eslint: ^4.0.0 => 4.0.0 
    gatsby-plugin-gatsby-cloud: ^3.1.0 => 3.1.0 
    gatsby-plugin-image: ^1.13.0 => 1.13.0 
    gatsby-plugin-manifest: ^3.13.0 => 3.13.0 
    gatsby-plugin-offline: ^4.13.0 => 4.13.0 
    gatsby-plugin-react-helmet: ^4.13.0 => 4.13.0 
    gatsby-plugin-scroll-reveal: 0.0.7 => 0.0.7 
    gatsby-plugin-sharp: ^3.13.0 => 3.13.0 
    gatsby-source-filesystem: ^3.13.0 => 3.13.0 
    gatsby-transformer-json: ^3.13.0 => 3.13.0 
    gatsby-transformer-sharp: ^3.13.0 => 3.13.0 
  npmGlobalPackages:
    gatsby-cli: 3.9.0

```

### Config Flags

DEV_SSR: false

**Comment by pieh** [comment]
Hey @TylerAPfledderer 

I checked your repro and this errors specifally comes from https://github.com/TylerAPfledderer/coffeeroaster-subscription-site/blob/60a315e3d80e2f18fccda2bce0e32eb865a629df/gatsby-config.js#L65-L85 - commenting out "fixes" the error (just as confirmation of source of problem), so I think plugin options there are not correct (or maybe plugin doesn't handle them correctly).

Seems like instead of `test`, you probably would need to use `extensions` property and `emitWarning` and `failOnError` should be top level properties and not under nested `options` - this let me build development bundle:
![Screenshot 2021-09-17 at 11 14 38](https://user-images.githubusercontent.com/419821/133758429-9ab72118-5f08-4740-aa4d-55d50ca4ca19.png)

**Comment by pieh** [comment]
I marked this issue as `upstream` and will close the issue here as it's related to configuration of 3rd party plugin (`gatsby-plugin-eslint` is maintained in https://github.com/mongkuen/gatsby-plugin-eslint).

Currently that plugin doesn't do plugin options validation and because of that it later fails with undescrptive errors (for ref. here's example plugin options validation we have in one of our plugins https://github.com/gatsbyjs/gatsby/blob/0eba91161c900466a136f3ca47065fa4a0567a89/packages/gatsby-source-contentful/src/gatsby-node.js#L60-L151 - if plugin would implement it, there would be earlier feedback loop with more descriptive messages - like `test` and `options` not being valid fields in config)

**Comment by TylerAPfledderer** [comment]
Thank you, @pieh! 

I indeed overlooked this plugin, as I just updated to the most recent version, which appears to have updated the options tree, removed options (`failOnError`), and/or made the ones in question here default. So, I have simply removed them from the config, and all is working fine now!

Take care.
