### ISSUE TITLE
[Discussion] Will Gatsby support org-mode?

### ISSUE THREAD

**Issue by jack2gs** [gatsbyjs/gatsby#3361]
Hi guys,

Could anyone tell me if Gatsby will support org-mode? Or if any advice?

Thanks,
Jack

**Comment by calcsam** [comment]
Could you outline what's needed to support Org mode? Lots of emacs users using Gatsby so definitely open to the idea as well as to PRs if it's fairly straightforward

**Comment by jack2gs** [comment]
Hi @calcsam,

Actually, I want to know if we could support to convert org-mode files to html's, as MD is supported by default. I usually use org-mode to write articles. 

Thanks,
Jack

**Comment by calcsam** [comment]
Ah, got it. To clarify, Gatsby current has this functionality in an official plugin called Gatsby-transformer-remark. In order to replicate this for org-mode files, you'd want to create another plugin called gatsby-transformer-org-mode. Right now such a plugin does not exist. 

Creating one would be fairly straightforward -- you'd want to use the structure of gatsby-transformer-remark but use a tool that ported org-mode into HTML (or into markdown and then use the markdown transform code). Unclear on a quick search if a specific tool exists (in Node.js) but there's a Node port of pandoc which should work.

**Comment by jack2gs** [comment]
yes, I tried to find a tool for converting org-mode to html, but failed. Maybe we can convert it to MD, then use `gatsby-transformer-remark`.

**Comment by calcsam** [comment]
Yes pandoc should do that

**Comment by jack2gs** [comment]
Cool

**Comment by KyleAMathews** [comment]
A pandoc Gatsby transformer would be 🔥🔥🔥

**Comment by fuxialexander** [comment]
#3907

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
