### ISSUE TITLE
ERR_REQUIRE_ESM error in gatsby-recipes

### ISSUE THREAD

**Issue by dangreen** [gatsbyjs/gatsby#33713]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

```
/Users/dangreen/github/react-chartjs-2/node_modules/gatsby-recipes/dist/graphql-server/server.js:52
var remarkMdx = require('remark-mdx');
                ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/dangreen/github/react-chartjs-2/node_modules/gatsby-recipes/node_modules/remark-mdx/index.js from /Users/dangreen/github/react-chartjs-2/node_modules/gatsby-recipes/dist/graphql-server/server.js not supported.
Instead change the require of index.js in /Users/dangreen/github/react-chartjs-2/node_modules/gatsby-recipes/dist/graphql-server/server.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/dangreen/github/react-chartjs-2/node_modules/gatsby-recipes/dist/graphql-server/server.js:52:17) {
  code: 'ERR_REQUIRE_ESM'
}
```

https://github.com/gatsbyjs/gatsby/blob/d04f563342f7679728738e623578dd712a34caca/packages/gatsby-recipes/package.json#L53

`remark-mdx@^2.0.0-next.4` resolves to [`remark-mdx@2.0.0-rc.1`](https://unpkg.com/browse/remark-mdx@2.0.0-rc.1/package.json) which is ESM only package

### Reproduction Link

https://codesandbox.io/s/cocky-sound-og3zh?file=/package.json

### Steps to Reproduce

1. `yarn add -D docz react react-dom`
2. `yarn docz dev`

### Expected Result

All works without any errors.

### Actual Result

ERR_REQUIRE_ESM error

### Environment

```shell
System:
    OS: macOS 11.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.10.0 - /var/folders/h2/gn99zpsn25j5w47332yy8jfw0000gn/T/yarn--1635416469908-0.7042407843892959/node
    Yarn: 1.22.13 - /var/folders/h2/gn99zpsn25j5w47332yy8jfw0000gn/T/yarn--1635416469908-0.7042407843892959/yarn
    npm: 7.24.0 - ~/.nvm/versions/node/v16.10.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 95.0.4638.54
    Firefox: 91.0.2
    Safari: 15.0
```

**Comment by Hannah-goodridge** [comment]
Any update on this? Its affecting me too.

**Comment by iChenLei** [comment]
#### Gatsby use `rollup` to bundle `gatsby-recipes` package, 
here is rollup config -> packages/gatsby-recipes/rollup.config.js
https://github.com/gatsbyjs/gatsby/blob/d04f563342f7679728738e623578dd712a34caca/packages/gatsby-recipes/rollup.config.js#L33-L38

All `import` Declaration will be transform to `require` Declaration

https://github.com/gatsbyjs/gatsby/blob/dcc32a7db3413c79c5d62f9f72d8aaafb39b58df/packages/gatsby-recipes/src/parser/index.js#L2

to

> https://cdn.jsdelivr.net/npm/gatsby-recipes@1.2.0/dist/graphql-server/server.js
```js
var remarkMdx = require('remark-mdx');
```

https://github.com/mdx-js/mdx/blob/main/packages/remark-mdx/package.json#L34

remark-mdx breaking change -> pr https://github.com/mdx-js/mdx/pull/1661

![2021-11-23 22 55 34](https://user-images.githubusercontent.com/14012511/143047536-446e09cd-5c65-4a63-8428-ba25ee949fa4.png)

The CommonJS module `require` always treats the files it references as CommonJS.
Using `require` to load an ES module is not supported because ES modules have asynchronous execution. Instead, use import() to load an ES module from a CommonJS module.

> https://nodejs.org/api/esm.html#require

### sindresorhus's `The ESM move`
https://github.com/sindresorhus/meta/discussions/15

I think more and more npm package will be `esm-only` in the future (e.g. https://github.com/sindresorhus/meta/discussions/15#discussioncomment-1263848), so gatsby need care this trends.

### Current workaround
lock `remark-mdx` version
```diff
- ^2.0.0-next.4
+ 2.0.0-next.9
```

**Comment by iChenLei** [comment]
https://nodejs.org/api/esm.html#import-expressions

It’s worth noting that the only way to import ESM files from a CJS module is using dynamic `import()` calls. This can present challenges, but is the behavior in Node.js today.

**Comment by jonasdev** [comment]
Any updates?

**Comment by poc-worldomkar** [comment]
`yarn add @mdx-js/mdx @mdx-js/react`

in newly created gatsby project moves @mdx-js/mdx versions from "v1"  to ==>  "^2.1.1".

Then this is seen:
`
Error: [ERR_REQUIRE_ESM]: require() of ES Module /Volumes/source/websites/new-gatsby-site/node_modules/@mdx-js/mdx/index.js from /Volumes/sourc
  e/websites/new-gatsby-site/node_modules/gatsby-plugin-mdx/utils/mdx.js not supported.
  Instead change the require of index.js in /Volumes/source/websites/new-gatsby-site/node_modules/gatsby-plugin-mdx/utils/mdx.js to a dynamic import() which is available in all CommonJS modules.
`
  
The expectation is newer versions of packages will be always compatible, updated and use the latest standards and best practices.
Can't wrap my head around why "v1" works but not "^2.1.1". Doesn't sound right.

If I manually edit package.json and revert @mdx-jx/mdx and @mdx-js/react versions to `"v1"`, and run yarn install, it starts to work again.

I may be missing something very silly basic, but what??

**Comment by cgarrovillo** [comment]
Think this needs to be reopened

**Comment by TomaszWaszczyk** [comment]
I have probably the error.

**Comment by 0x80** [comment]
I just ran into this trying to start an old project.

I solved it by locking remark-mdx using the resolutions field in package.json:

```
"resolutions": {
    "remark-mdx": "1.6.22"
  },
 ```
 
 Don't know if it will be picked up by all package managers.  I was using Yarn classic, and had to remove my node_modules first.
