### ISSUE TITLE
While giving Gatsby 4 a spin using `gatsby-source-graphql`, I found that DSG is not working :(

### ISSUE THREAD

**Issue by pragmaticpat** [gatsbyjs/gatsby#33906]
While giving Gatsby 4 a spin using `gatsby-source-graphql`, I found that DSG is not working :( 

I've set my codebase https://github.com/laurenskling/using-gatsby-source-graphql to defer rendering the `film` pages, and now these pages get an `errors` prop.

Example on Gatsby Cloud: https://build-58701a40-9907-423a-9f26-9f80e4b3beea.gtsb.io/ZmlsbXM6Mg== Saying: Cannot query field "swapi" on type "Query". So the entire external Graphql isn't found.

Building and serving locally I do no get this specific error, but another one. I'm getting in my `errors` prop:
```
{
  message: "nodeFetch is not a function"
  path: (2) ['swapi', 'film']
}
```

_Originally posted by @laurenskling in https://github.com/gatsbyjs/gatsby/discussions/33218#discussioncomment-1436754_

**Comment by LekoArts** [comment]
From https://github.com/gatsbyjs/gatsby/discussions/33218#discussioncomment-1643486

---

Probably caused by the issue in `node-fetch` when bundled with webpack: https://github.com/node-fetch/node-fetch/issues/450

The fix described in https://github.com/node-fetch/node-fetch/issues/450#issuecomment-387045223 should probably help. I encourage you to submit a PR! I guess it should just change a single line:

https://github.com/gatsbyjs/gatsby/blob/83ca1df6a903027bbaf93b3efd02c32ac4cb054b/packages/gatsby-source-graphql/src/fetch.js#L1

to:
```js
const nodeFetch = require(`node-fetch`).default
```

But please double check if it works for you in normal develop/build workflow!

**Comment by laurenskling** [comment]
Seems like that actually did the trick! 

https://build-87bc0901-70ee-477a-8d31-740b2702abc4.gtsb.io/films/

https://github.com/laurenskling/using-gatsby-source-graphql/commit/f1fb90ab8f550f808ed59cfb6a7d6b30ce5a1ad6

**Comment by laurenskling** [comment]
This led me to investigate something.. Because `gatsby-source-graphql` allows you to bring your own `fetch`: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-graphql/src/gatsby-node.js#L42
and since `nodeFetch` was not a function, I tried passing something like `cross-fetch` to fix it, but that didn't do much.

Now I found, that `fetch` is `undefined` in the `options` when I log it out here: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-graphql/src/gatsby-node.js#L34 not during build time, but when starting with `gatsby serve`. (this is also true for `createLink` by the way.) I guess it goes thru something that doesn't accept functions in the object?

**Comment by LekoArts** [comment]
Functions are not serializable so when passed in through functions they won't be working.

**Comment by laurenskling** [comment]
> Functions are not serializable so when passed in through options they won't be working.

Yeah this is what I figured. So now `gatsby-source-graphql` is able to run on the client, and passing functions doesn't work, this actually creates bugging experiences. The documentation states you can use `fetch` or `createLink` to add auth headers. So this will not be working in DSG. Should we change the docs, or?
