### ISSUE TITLE
`config` export is removed from non-template source files

### ISSUE THREAD

**Issue by jessehart** [gatsbyjs/gatsby#33998]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

after upgrading from 4.0.0 to 4.2.0 i'm getting an error:

<img width="1037" alt="Screen Shot 2021-11-16 at 3 25 59 PM" src="https://user-images.githubusercontent.com/311958/142067057-9bc1ab42-039a-44f7-9448-8dfd09184f97.png">

### Reproduction Link

https://github.com/jessehart/gatsbystitches

### Steps to Reproduce

gatsby develop

### Expected Result

site loads without error

### Actual Result

unhandled runtime error

### Environment

```shell
System:
    OS: macOS 12.0.1
    CPU: (10) arm64 Apple M1 Max
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.9.1 - ~/.nvm/versions/node/v16.9.1/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 7.24.0 - ~/.nvm/versions/node/v16.9.1/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  Browsers:
    Chrome: 96.0.4664.45
    Safari: 15.1
  npmPackages:
    gatsby: ^4.2.0 => 4.2.0
  npmGlobalPackages:
    gatsby-cli: 4.2.0
```

**Comment by graysonhicks** [comment]
I was able to reproduce this is 4.1.0 and 4.2.0, but not 4.0.0, so it seems to have been introduced in 4.1.0. I don't see an obvious culprit in the [changelog](https://github.com/gatsbyjs/gatsby/compare/gatsby@4.1.0-next.0...gatsby@4.1.0).

**Comment by iChenLei** [comment]
### Temporary Workaround

```diff
- export const {
+ const {
  styled,
  css,
  globalCss,
  keyframes,
  getCssText,
  createTheme,
  config,
} = createStitches({
  theme: {
    colors: {
      gray400: 'gainsboro'
    },
  }
});
+ export {
+ styled
+ }
```
Disbale `named destructuring const export` usage, It will work as export when you run `gatsby develop`

#### `named destructuring const export` with `gastby develop` on gatsby 4.2

> missing `var _createStitches = (0,_stitches_react__WEBPACK_IMPORTED_MODULE_0__.createStitches)`

![2021-11-26 14 24 03](https://user-images.githubusercontent.com/14012511/143536322-36d4189a-69b1-4764-9d82-1a1849b3b365.png)

#### Disable `named destructuring const export` with `gastby develop` on gatsby 4.2

![2021-11-26 14 24 31](https://user-images.githubusercontent.com/14012511/143536458-a9564215-59e3-4006-8418-d171fa30e623.png)

> it works as expected, I think it's gatsby's internal `webpack/babel` or `file system` bug.

**Comment by mikeytown19** [comment]
@iChenLei where does one disable that? I'm having the same issue.

**Comment by iChenLei** [comment]
@mikeytown19 Can you provide a minimal reproducation repo? I have enough time to this issue this weekend.

**Comment by iChenLei** [comment]
@mikeytown19  @jessehart  Can you guys upgrade gatsby to v4.4.0 ? It looks like work as expected when you use latest version `gatsbyjs`.

**Comment by jessehart** [comment]
@iChenLei updated dependencies but the issue persists. I've been using your workaround with success in the interim.

**Comment by iChenLei** [comment]
@jessehart Thanks for feedback, I will dig it this weekend.

**Comment by pieh** [comment]
I tried taking a look here, but this seems quite confusing so didn't do a lot of progress on actual fix. It's definitely problem with babel setup and in particular this one - https://github.com/gatsbyjs/gatsby/blob/6ffe0afd15a4f4b327a108399f14183f337eab97/packages/gatsby/src/utils/babel-loader-helpers.js#L61-L66

If you remove `config` from options it works. Seems like there is cascade of problems happening. One would expect at most it would remove the `config` export but that's not full story. It also remove actual:
```
     var _createStitches = createStitches({
       theme: {
         colors: {
           gray400: 'gainsboro'
         }
       }
     }),
```
part as well.

Weirdly enough if you remove https://github.com/gatsbyjs/gatsby/blob/6ffe0afd15a4f4b327a108399f14183f337eab97/packages/gatsby/src/utils/babel-loader-helpers.js#L109-L111 - it comes back (but `config` is still not exported).

So root of the issue is that our `babel-plugin-remove-api` removes `config` in non-template files, but later there is cascade of weird interactions happening that I don't quite follow.

For easier debugging / testing I did prepare a test case in https://github.com/gatsbyjs/gatsby/compare/fix/i33998 so at very least iteration can happen faster for anyone that would pick this issue up.
