### ISSUE TITLE
File System API - Two folders using fileAbsolutePath to separate

### ISSUE THREAD

**Issue by hisnameisjimmy** [gatsbyjs/gatsby#34108]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Using the File System Route API, I have two different areas of the site utilizing collections routes, which work more or less like separate blogs. They look remarkably similar, but I want them to be on different routes and they use different collection route files. 

Essentially:
`/blog` and `/portfolio`

This seems to work fine when using gatsby develop, but fails on gatsby build. After hours of searching, I can't figure out why. I'm not totally sure this is the kosher way of doing things either, maybe there's a better way. But, at the very least, this shouldn't succeed on `gatsby develop` and fail on `gatsby build`. They should reflect eachother. 

### Reproduction Link

https://github.com/hisnameisjimmy/gatsby-mdx-tutorial-filie-system-route-by-folder

### Steps to Reproduce

1. Run gatsby develop
2. Navigate to /portfolio and /blog
3. Run gatsby build
4. Notice that you run into a build error with mdx being null

### Expected Result

Gatsby develop should reflect Gatsby build

### Actual Result

Gatsby develop succeeds, gatsby build runs into an error with mdx being null. It appears this is because it's trying to build files using a template not meant for it. 

For example, it appears to be trying to use the collection route for the blog post for the portfolio post, even though I am regexing the absolute path to only be for the portfolio. 

### Environment

```shell
System:
    OS: macOS 11.5.2
    CPU: (8) arm64 Apple M1
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.9.1 - ~/.nvm/versions/node/v16.9.1/bin/node
    npm: 7.21.1 - ~/.nvm/versions/node/v16.9.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 96.0.4664.55
    Safari: 14.1.2
  npmPackages:
    gatsby: ^4.0.0 => 4.0.0
    gatsby-plugin-image: ^2.0.0 => 2.0.0
    gatsby-plugin-mdx: ^3.0.0 => 3.0.0
    gatsby-plugin-sharp: ^4.0.0 => 4.0.0
    gatsby-remark-images: ^6.2.0 => 6.2.0
    gatsby-source-filesystem: ^4.0.0 => 4.0.0
    gatsby-transformer-sharp: ^4.0.0 => 4.0.0
  npmGlobalPackages:
    gatsby-cli: 4.2.0
```

**Comment by leithonenglish** [comment]
Hi @hisnameisjimmy!

Sorry to hear you're running into an issue. If I understand correctly you are trying to use a different template for mdx nodes using the absolute file path. The problem is that a page will be created for each mdx node since file system route is not filtered by the graphql query. What you are aiming to do may not be possible with the `File System API` I recommend using the [createPage API](https://www.gatsbyjs.com/docs/reference/config-files/actions/#createPage)

URLs like http://localhost:8000/blog/yet-another-portfolio-post/ are actually broken on the site but you won't see them until the visit the actual page. That's the reason why it was successful using `gatsby develop` but failed after running `gatsby build`.
