### ISSUE TITLE
[gatsby-source-graphql] download images from remote schema using Gatsby v4

### ISSUE THREAD

**Issue by jaredhill4** [gatsbyjs/gatsby#34192]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Summary

When using the `gatsby-source-graphql` plugin, the previous recommended way to download images from a remote GraphQL schema was to create a custom resolver inside the `createResolvers` function. Here is the documentation for that way of doing it:

https://www.gatsbyjs.com/docs/how-to/plugins-and-themes/adding-gatsby-image-support/#add-the-resolver

However, according to the Gatsby v4 documentation and migration guide, generating file nodes inside `createResolvers` is no longer supported. See:

- https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v3-to-v4/#do-not-create-nodes-in-custom-resolvers
- https://www.gatsbyjs.com/docs/reference/release-notes/migrating-source-plugin-from-v3-to-v4/#2-data-mutations-need-to-happen-during-sourcenodes-or-oncreatenode

As far as I can tell, the `gatsby-source-graphql` does not explicitly generate nodes containing all the data necessary to generate a file node in the `onCreateNode` function (which would be the only way of doing here, since the consumer of the plugin is not in control of the `sourceNodes` function of the plugin).

All that said, neither the documentation for Gatsby v4 nor that for the plugin in question provide adequate information about how to generate file nodes for images when using this plugin.

### Steps to Resolve this Issue

1. Visit the documentation links above and read my description of the issue.
...

**Comment by jaredhill4** [comment]
Because of the issue stated above, I'm unable to use the `gatsby-source-graphql` plugin if I want to generate file nodes for use with `gatsby-plugin-image`.

**Comment by LekoArts** [comment]
Hi!

It is correct that with our changes in v4 the explanation in https://www.gatsbyjs.com/docs/reference/graphql-data-layer/schema-customization/#extending-third-party-types isn't accurate anymore. For now you'll want to switch to https://github.com/gatsbyjs/gatsby-graphql-toolkit to create a proper source plugin if you need image support.

The documentation you linked to is not the same as the changes in v4. The section explains how to set up a resolver that uses data/URLs from CMS and is not downloading images itself. The image downloading piece is the problem here.

Two things that should be changed:

1. Remove https://www.gatsbyjs.com/docs/reference/graphql-data-layer/schema-customization/#extending-third-party-types completely
2. Add a short note about https://github.com/gatsbyjs/gatsby-graphql-toolkit to https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v3-to-v4/#do-not-create-nodes-in-custom-resolvers section

**Comment by Emeka-Ugbanu-hub** [comment]
i would love to help with this
