### ISSUE TITLE
Gatsby SSR pages doesn't work with GCP Firebase/ Cloud Run : Missing documentation 

### ISSUE THREAD

**Issue by shivaping** [gatsbyjs/gatsby#34306]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

There is no documentation for deploying Gatsby SSR Capabilites on GCP. Please provide same at the earliest. 

### Reproduction Link

https://www.marlin-staging-john-rogers.guidesly.com/ssr-page

### Steps to Reproduce

1. Followed article on https://www.gatsbyjs.com/docs/reference/config-files/gatsby-ssr/
2. created a page ssr-page under pages folder
3. Deployed the site to https://www.marlin-staging-john-rogers.guidesly.com
4. tried browsing https://www.marlin-staging-john-rogers.guidesly.com/ssr-page. The page is not working

### Expected Result

https://www.marlin-staging-john-rogers.guidesly.com/ssr-page should stay on the page and render the dynamic content

### Actual Result

https://www.marlin-staging-john-rogers.guidesly.com/ssr-page is redirected to home page.

### Environment

```shell
GCP Cloud, Firebase/Cloud Run

Node : 16.x
npm : 8.x
```

**Comment by LekoArts** [comment]
Hi,

Gatsby doesn’t officially support running SSR or DSG anywhere other than Gatsby Cloud at this time. However, there are community implementers that have made these features available on other platforms, which could be referenced in order to implement these features in any hosting environment you choose.

**☝️ Note**: Since Gatsby doesn’t officially support these features outside of Gatsby Cloud, we cannot guarantee their performance or stability.

All that said, here are some useful references at this time:
- [gatsby-plugin-fastify](https://www.npmjs.com/package/gatsby-plugin-fastify) - this plugin can be deployed anywhere you choose to run a Fastify web server
- [netlify-plugin-gatsby](https://github.com/netlify/netlify-plugin-gatsby#readme) - only useful if you’re hosting with Netlify
