### ISSUE TITLE
Unable to get storybook to work with Gatsby

### ISSUE THREAD

**Issue by alveshelio** [gatsbyjs/gatsby#3435]
Hi guys, I'm sorry to create a new issue regarding Storybook, however this issue https://github.com/gatsbyjs/gatsby/issues/633 is closed and I can't reopen it.

Here is my repo in case you guys want to take a look at the code: https://github.com/alveshelio/personal-website

I've followed the steps described in this Gatsby starter https://github.com/fabien0102/gatsby-starter, and I got storybook to work, when I run yarn run storybook, I get storybook on port 9001, however, whenever I create a file MyModule.stories.js, I get this error:

```
WARNING in ./src/components/Header/Menu/Menu.stories.jsx
Module build failed: SyntaxError: Unexpected token (8:4)

storiesOf('Menu', module)
   .add('default', () => (
     <Menu />
     ^
   ));

@ ./src .stories.[jt]sx?$
@ ./.storybook/config.js
```

Here's the content of my config.js file in .storybook
```
import { configure } from "@storybook/react";
import { setOptions } from "@storybook/addon-options";

setOptions({
name: 'My website',
downPanelInRight: true
});

// Stories loader
const req = require.context("../src", true, /.stories.[jt]sx?$/);
function loadStories() {
req.keys().forEach(req);
}

// Initialize react-storybook
configure(loadStories, module);
```

and the content of my file webpack.config.js

```
const path = require("path");
const genDefaultConfig = require("@storybook/react/dist/server/config/defaults/webpack.config.js");

module.exports = (baseConfig, env) => {
  const config = genDefaultConfig(baseConfig, env);


  // Add markdown loader
  config.module.rules.push({
    test: /\.md$/,
    include: path.resolve(__dirname, "../src"),
    loader: require.resolve("raw-loader")
  });
  config.resolve.extensions.push(".md");

  return config;
};
```
Do you have any idea why I'm getting this error?

Thank you

**Comment by fabien0102** [comment]
Just see your issue after my comment ^^, I will try directly on your code source :wink:

**Comment by fabien0102** [comment]
Very strange, you have the exact same bug if I erase all the storybook stack and do a classic `getstorybook` (provide by `npm i -g @storybook/cli`), react loader is not correctly loaded… 

I already find a weird conflit with gatsby/storybook/yarn (https://github.com/fabien0102/gatsby-starter/issues/37).

I also try with npm instead of yarn, but same result… (with getstorybook and your config)

I'm sorry, but I really don't know…

**Comment by alveshelio** [comment]
@fabien0102,

Yes, it's really weird and I really can't find the reason why it's not working because I'm using the same configuration are yours. I've used this Gatsby Starter: https://github.com/Vagr9K/gatsby-advanced-starter. So I don't know if there's a conflict with some other configuration.

Thank you very much for your time Fabien.

**Comment by fabien0102** [comment]
@alveshelio Your welcome, the step after is to uninstall each plugin one by one to find which one have a conflict with storybook 😉 But I really don't have the time for that ^^ But I think that it's a package conflict same as my issue with the dragging panel bug :wink:

**Comment by fabien0102** [comment]
@alveshelio I think I finded your issue! (I got the same issue on a private repo ^^) If you have a .babelrc, storybook take this one and only this one instead of the default provide by storybook. You can try to delete your .babelrc and launch again your storybook to have a confirmation.

If it's really that, you should just add the babel thing to parse the jsx (I don't have fix yet on my project)

Have fun 😄

**Comment by fabien0102** [comment]
.storybook/.babelrc
```json
{
  "presets": [
    "env",
    "stage-0",
    "react"
  ],
  "plugins": [
    "transform-regenerator",
    [
      "transform-runtime",
      {
        "helpers": true,
        "polyfill": true,
        "regenerator": true
      }
    ]
  ]
}
```

and you need to install the plugins/presets of course ^^

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
