### ISSUE TITLE
Error in function useStaticQuery in ./.cache/gatsby-browser-entry.js:77

### ISSUE THREAD

**Issue by genesis16** [gatsbyjs/gatsby#34730]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Hello when running gatsby develop, I am getting this error: 

Unhandled runtime error: Error in function useStaticQuery in ./.cache/gatsby-browser-entry.js:77

The result of this StaticQuery could not be fetched. This is likely a bug in Gatsby and if refreshing the page does not fix it, please open an issue in https://github.com/gatsbyjs/gatsby/issues

### Reproduction Link

https://github.com/genesis16/jjgatsby

### Steps to Reproduce

1. Clone repo and use version 082ac18 This is the last working version on Netlfy. 
2. Run Gatsby develop
3. See runtime error. 
...

### Expected Result

Local host to spin up dev site

### Actual Result

Runtime error- site would not develop. 

### Environment

```shell
Mac os: 11.6.2 
Software: Big Sur
VS Code
Netlify
```

**Comment by pieh** [comment]
Hi @genesis16 - I tried this locally and this is what I got in terminal:

```
 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Unknown argument "formatString" on field
"MarkdownRemarkFrontmatter.date".

GraphQL request:12:18
11 |             tags
12 |             date(formatString: "DD MMMM, YYYY")
   |                  ^
13 |             description

File: src/pages/blog.js:99:18
```

By default Gatsby will try to infer type based on data. In this case seems like it can't figure out that `date` field is supposed to represent ... a date.

In particular `date` in https://github.com/genesis16/jjgatsby/blob/bc7889e889fa79384d7a3437cfe05ea7995982e5/content/projects/vinnies.md is `2021-8-26` is not recognized as a date due to month being single digit.

You can force gatsby to treat this as a string by adding following snippet to `gatsby-node.js`:

```
exports.createSchemaCustomization = ({ actions }) => {
  actions.createTypes(`
    type MarkdownRemarkFrontmatter {
      date: Date @dateformat
    }

    type MarkdownRemark implements Node {
      frontmatter: MarkdownRemarkFrontmatter
    }
  `);
};
```

That said - I couldn't reproduce the error you reported (neither on `master` nor on the specific commit you mentiond - `082ac18 `) - I only saw errors related to GraphQL schema etc on `master`

**Comment by LekoArts** [comment]
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!
