### ISSUE TITLE
[gatsby-image-plugin] TRACED_SVG giving an input error when used as placeholder

### ISSUE THREAD

**Issue by rishFilet** [gatsbyjs/gatsby#34752]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

For some reason TRACED_SVG does not work anymore when making a graphql query to contentful. There was no change yo my packages or code and when i run the develop build, the image does not show up and i get an error in my terminal:

![image](https://user-images.githubusercontent.com/28996036/152891887-c6befdd6-b3a8-461c-825b-6ab1c44bf6c9.png)

Running blurred works fine but traced_svg does not. Here ist he output from the graphql explorer:
![image](https://user-images.githubusercontent.com/28996036/152891974-a52ddd1d-e312-4a6e-9e58-a90714907538.png)
![image](https://user-images.githubusercontent.com/28996036/152891992-8e61e5ec-d3e5-4a2b-91cc-42945a2f333b.png)

### Reproduction Link

No link

### Steps to Reproduce

1. Install gatsby-plugin-image 2.6.0 
2. Create a graphql query to contenful using gatsbyImageData and placeholder as TRACED_SVG
3. Run gatsby develop 
...

### Expected Result

No errors in terminal and image shows up normally in develop build

### Actual Result

Returns and error and image does not appear. The rest of the build appears except the image itself that is being queried.

### Environment

```shell
System:
    OS: Linux 5.15 Pop!_OS 20.04 LTS
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.13.2 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.3.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 98.0.4758.80
    Firefox: 96.0
  npmPackages:
    gatsby: ^4.0.0 => 4.6.2 
    gatsby-plugin-google-fonts: ^1.0.1 => 1.0.1 
    gatsby-plugin-image: ^2.6.0 => 2.6.0 
    gatsby-plugin-prefetch-google-fonts: ^1.4.3 => 1.4.3 
    gatsby-plugin-react-svg: ^3.0.0 => 3.1.0 
    gatsby-plugin-recaptcha: ^1.0.5 => 1.0.5 
    gatsby-plugin-root-import: ^2.0.6 => 2.0.8 
    gatsby-plugin-sharp: ^4.6.0 => 4.6.0 
    gatsby-plugin-styled-components: ^5.6.0 => 5.6.0 
    gatsby-source-contentful: ^7.4.0 => 7.4.0 
    gatsby-source-filesystem: ^4.6.0 => 4.6.0 
    gatsby-transformer-sharp: ^4.6.0 => 4.6.0 
  npmGlobalPackages:
    gatsby-cli: 4.6.1
```

**Comment by marvinjude** [comment]
Hi @rishFilet,

Thanks for reporting this issue. It's on the list of things we're working on. For now,  please check [this commit](https://github.com/Khaledgarbaya/chocolate-free-website/pull/13/commits/cb0c97ccd28e37105f0155aeec05d08bfd111a82) for how to temporality patch this problem. Thanks!

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment]
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!
