### ISSUE TITLE
Error: Error loading a result for the page query in "/". Query was not run and   no cached result was found

### ISSUE THREAD

**Issue by AleJo2995** [gatsbyjs/gatsby#34764]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Hi team,

This error is happening when it attempts to build our site via Travis randomly. When I say randomly is that a couple of days, happen and other days the build runs successfully. What is the root cause of the issue per-sé? I have ran the development instance and it runs perfectly fine but I don´t fully understand why when the build runs it toggles between working and not working sometimes. Even when it runs bad one day I restart the build and then it runs perfectly fine.

I´ve reviewed other issues related to this behavior such as https://github.com/gatsbyjs/gatsby/issues/27644, and the solution provided is the usage of gatsby clean before build which I thought it was not necessary any longer. Even though i tried that solution it still behaves weird and toggles between working and not.

![image](https://user-images.githubusercontent.com/8278478/153050774-eb91c02a-88a3-4996-8110-a33b965225bf.png)

**Brief context**
We´re using gatsby build out a site with fetches different sorts of markdown files from other repos using `gatsby-source-git` plugin, with which I haven´t face any problem during the sourcing. 

### Reproduction Link

n/a

### Steps to Reproduce

1.
2.
3.
...

### Expected Result

Build should work consistently and not toggling with this random and non descriptive issue

### Actual Result

Right now we´re unable to build consistently without human assist

### Environment

```shell
System:
    OS: macOS 11.6.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.3.1 - /usr/local/bin/npm
  Languages:
    Python: 3.9.2 - /usr/local/bin/python
  Browsers:
    Chrome: 98.0.4758.80
    Firefox: 96.0.2
    Safari: 15.0
  npmPackages:
    gatsby: ^3.12.1 => 3.13.0
    gatsby-plugin-changelog-context: ^1.1.0 => 1.1.0
    gatsby-plugin-local-search: ^2.0.1 => 2.0.1
    gatsby-plugin-mdx: ^2.12.0 => 2.13.0
    gatsby-plugin-page-creator: ^3.12.0 => 3.13.0
    gatsby-plugin-slug-field: ^0.3.1 => 0.3.1
    gatsby-remark-check-links: ^2.1.0 => 2.1.0
    gatsby-remark-embed-markdown: ^0.0.4 => 0.0.4
    gatsby-source-filesystem: ^3.12.0 => 3.13.0
    gatsby-source-git: ^1.1.0 => 1.1.0
    gatsby-theme-carbon: ^2.0.0 => 2.0.0
    gatsby-transformer-csv: ^3.14.0 => 3.14.0
    gatsby-transformer-javascript-frontmatter: ^3.12.0 => 3.13.0
    gatsby-transformer-json: ^4.0.0 => 4.0.0
    gatsby-transformer-remark: ^4.9.0 => 4.10.0
  npmGlobalPackages:
    gatsby-cli: 3.6.0
```

**Comment by giladmaker** [comment]
I am also facing this issue intermittently, regardless of whether or not I ran `gatsby clean` prior to building.

Some very basic findings I might as well share: I've put a couple of logs in my local gatsby source code and observed that in failing builds, the readPageData function in page-data.ts:
https://github.com/gatsbyjs/gatsby/blob/gatsby%404.6.0/packages/gatsby/src/utils/page-data.ts#L34-L36

```
  const rawPageData = await fs.readFile(filePath, `utf-8`)

  return JSON.parse(rawPageData)
```

reading the file results in a string that is not a valid JSON (which causes the error in the JSON.parse call):
e.g.:
```
    {
        "componentChunkName": "component---src-pages-search-tsx",
        "path": "/Search/",
        "result": {"pageContext":{}},
        "staticQueryHashes": ["1123334258","1533406189","3918896094","4124834038"]}rch","crumbs":[{"pathname":"/","label":"Home"},{"pathname":"/search","label":"Search"}]}}},
        "staticQueryHashes": ["1123334258","1533406189","3918896094","4124834038"]}
```

As opposed to (when build is successful):
    ```{
        "componentChunkName": "component---src-pages-search-tsx",
        "path": "/Search/",
        "result": {"pageContext":{}},
        "staticQueryHashes": ["1123334258","1533406189","3918896094","4124834038"]}```

So looks like a page's file is getting corrupted by part of a different page's data.
Unfortunately this is where I had to stop, will update if I get to investigate further and get closer to the root cause.

### Environment:

```
  System:
    OS: macOS 11.5.2
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.13.2 - /var/folders/gg/bs4yvn9x3y17lhkp526gbf3r0000gn/T/yarn--16444
02456727-0.2157799619599572/node
    Yarn: 1.22.17 - /var/folders/gg/bs4yvn9x3y17lhkp526gbf3r0000gn/T/yarn--16444
02456727-0.2157799619599572/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 98.0.4758.80
    Safari: 14.1.2
  npmPackages:
    gatsby: ^4.6.1 => 4.6.1
    gatsby-alias-imports: ^1.0.6 => 1.0.6
    gatsby-image: ^3.11.0 => 3.11.0
    gatsby-plugin-better-jss: ^1.0.3 => 1.0.3
    gatsby-plugin-eslint: 4.0.2 => 4.0.2
    gatsby-plugin-force-trailing-slashes: ^1.0.5 => 1.0.5
    gatsby-plugin-google-tagmanager: 4.6.0 => 4.6.0
    gatsby-plugin-manifest: ^4.6.0 => 4.6.0
    gatsby-plugin-react-helmet: ^5.6.0 => 5.6.0
    gatsby-plugin-s3: ^0.3.8 => 0.3.8
    gatsby-plugin-sharp: ^4.6.0 => 4.6.0
    gatsby-plugin-sitemap: ^5.6.0 => 5.6.0
    gatsby-source-filesystem: ^4.6.0 => 4.6.0
    gatsby-source-graphql: ^4.6.0 => 4.6.0
    gatsby-transformer-sharp: ^4.6.0 => 4.6.0
```

**Comment by pieh** [comment]
Thanks @giladmaker for providing your research here. This gives me ideas (in particular it seems like there might be parallel writes happening resulting in corrupted page-data json files)

**Comment by pieh** [comment]
@giladmaker 

```
 {
        "componentChunkName": "component---src-pages-search-tsx",
        "path": "/Search/",
        "result": {"pageContext":{}},
        "staticQueryHashes": ["1123334258","1533406189","3918896094","4124834038"]}rch","crumbs":[{"pathname":"/","label":"Home"},{"pathname":"/search","label":"Search"}]}}},
        "staticQueryHashes": ["1123334258","1533406189","3918896094","4124834038"]}
```

Do you have page query in your `search.tsx`? If not, do you have query elsewhere that uses `crumbs` field? 

Just adding some resources to potentially additionally check:

here we construct json string:
https://github.com/gatsbyjs/gatsby/blob/ec20301df296aeff5ec29f23d21ddfadd40032c1/packages/gatsby/src/utils/page-data-helpers.ts#L13-L42

I think there is 2 options:
 - 1. for some reason resulting string is malformatted
 - 2. there are parallel writes happening to same file resulting in corrupted content

I doubt it's 1 just because of this `,"4124834038"]}rch","cr` piece - this seems too weird to actually happen. So next step for me would actually add logs in https://github.com/gatsbyjs/gatsby/blob/ec20301df296aeff5ec29f23d21ddfadd40032c1/packages/gatsby/src/utils/page-data.ts#L117-L142

and just log both `outputFilePath` and `body` - this would allow us to see wether we try to write to same file couple of times in single "batch" and/or wether actual content (`body`) is malformatted to begin with

**Comment by pieh** [comment]
> Still feels like a bug in gatsby though? As in, I'd expect there will be support for pages with multiple routes that differ only in their casing (and if not, probably should be handled more gracefully e.g. throw a more informative error message)

Yeah, this is potentially tricky. In linux this actually is not a problem because `public/page-data/Search/page-data.json` and `public/page-data/search/page-data.json` are actually different files (it's "just" Windows and Mac OS where those are the same). So what the behaviour should be? Do we disallow it/warn on platforms that are affected by it (then there is different behaviour locally vs what will happen in CI/CD as those will most likely run linux). Do we disallow it everywhere? Could someone rely on being able to create pages that only differ by casing? (not something I would recommend to do but 🤷‍♂️ )

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by AleJo2995** [comment]
A reproduction is going to be quite difficult to be provided since I´m working with sensitive/non sharable data here.

**Comment by LekoArts** [comment]
We don't want access to your project, you'll want to create a new project from scratch that shows this behavior that you then can share with us.

**Comment by AleJo2995** [comment]
Well, the thing is that I´m not quite sure if the issue is going to be actually reproduced since it seems to be related with an specific file in the whole build, and sometimes it fails and sometimes it doesn´t. I will try to setup a repo from scratch and try reproduce it.

**Comment by LekoArts** [comment]
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!
