### ISSUE TITLE
[gatsby-transformer-remark] - version 1.7.27 breaking build

### ISSUE THREAD

**Issue by ChrisSki** [gatsbyjs/gatsby#3481]
## Description

Updating to 1.7.27 and above breaks my Gatsby build using `gatsby-source-contentful`

**Note:** I have not tried this with any other source.

### Environment

Gatsby version: 1.9.153
Node.js version: 8.9.1
Operating System: MacOS High Sierra

### Actual result

Build failed with follow error:

```
TypeError: Cannot read property 'parent' of null

  - parse.js:69 Function.exports.update
    [guru-blog-contentful]/[gatsby-remark-responsive-iframe]/[cheerio]/lib/parse.js:69:26

  - parse.js:19 module.exports
    [guru-blog-contentful]/[gatsby-remark-responsive-iframe]/[cheerio]/lib/parse.js:19:11

  - static.js:27 Function.exports.load
    [guru-blog-contentful]/[gatsby-remark-responsive-iframe]/[cheerio]/lib/static.js:27:14

  - index.js:37
    [guru-blog-contentful]/[gatsby-remark-responsive-iframe]/index.js:37:23

  - index.js:31 one
    [guru-blog-contentful]/[unist-util-visit]/index.js:31:16

  - index.js:54 all
    [guru-blog-contentful]/[unist-util-visit]/index.js:54:25

  - index.js:39 one
    [guru-blog-contentful]/[unist-util-visit]/index.js:39:14

  - index.js:54 all
    [guru-blog-contentful]/[unist-util-visit]/index.js:54:25

  - index.js:39 one
    [guru-blog-contentful]/[unist-util-visit]/index.js:39:14

  - index.js:22 visit
    [guru-blog-contentful]/[unist-util-visit]/index.js:22:3

  - index.js:36
    [guru-blog-contentful]/[gatsby-remark-responsive-iframe]/index.js:36:5

  - debuggability.js:303 Promise._execute
    [guru-blog-contentful]/[bluebird]/js/release/debuggability.js:303:9

  - promise.js:483 Promise._resolveFromExecutor
    [guru-blog-contentful]/[bluebird]/js/release/promise.js:483:18

  - promise.js:79 new Promise
    [guru-blog-contentful]/[bluebird]/js/release/promise.js:79:10

  - index.js:31 module.exports
    [guru-blog-contentful]/[gatsby-remark-responsive-iframe]/index.js:31:10

  - extend-node-type.js:144
    [guru-blog-contentful]/[gatsby-transformer-remark]/extend-node-type.js:144:32

  - util.js:16 tryCatcher
    [guru-blog-contentful]/[bluebird]/js/release/util.js:16:23

  - reduce.js:155 Object.gotValue
    [guru-blog-contentful]/[bluebird]/js/release/reduce.js:155:18

  - reduce.js:144 Object.gotAccum
    [guru-blog-contentful]/[bluebird]/js/release/reduce.js:144:25

  - util.js:16 Object.tryCatcher
    [guru-blog-contentful]/[bluebird]/js/release/util.js:16:23

  - promise.js:512 Promise._settlePromiseFromHandler
    [guru-blog-contentful]/[bluebird]/js/release/promise.js:512:31

  - promise.js:569 Promise._settlePromise
    [guru-blog-contentful]/[bluebird]/js/release/promise.js:569:18
```

### Expected behavior

Successful build 

### Steps to reproduce

1\. Update from 1.7.26 to 1.7.27

2\. Use `gatsby-source-contentful`

3\. `gatsby develop` or `gatsby build`

...

**Comment by durkinio** [comment]
Having the same issue at the moment. My build failed error:

`gatsby develop -H $IP -p $PORT
success delete html files from previous builds — 0.109 s
success open and validate gatsby-config.js — 0.010 s
info One or more of your plugins have changed since the last time you ran Gatsby. As
a precaution, we're deleting your site's cache to ensure there's not any stale
data
success copy gatsby files — 0.031 s
success onPreBootstrap — 0.013 s
success source and transform nodes — 0.292 s
success building schema — 0.536 s
success createLayouts — 0.032 s
success createPages — 0.047 s
success createPagesStatefully — 0.021 s
success onPreExtractQueries — 0.006 s
success update schema — 0.242 s
success extract queries from components — 0.267 s
⠂ run graphql queriesvips warning: VipsJpeg: error reading resolution
⢀ run graphql queriesvips warning: VipsJpeg: error reading resolution
vips warning: VipsJpeg: error reading resolution
vips warning: VipsJpeg: error reading resolution
error UNHANDLED REJECTION


  TypeError: Cannot read property 'parent' of undefined
  
  - parse.js:69 Function.exports.update
    [workspace]/[gatsby-remark-responsive-iframe]/[cheerio]/lib/parse.js:69:25
  
  - parse.js:19 module.exports
    [workspace]/[gatsby-remark-responsive-iframe]/[cheerio]/lib/parse.js:19:11
  
  - static.js:27 Function.exports.load
    [workspace]/[gatsby-remark-responsive-iframe]/[cheerio]/lib/static.js:27:14
  
  - index.js:37 
    [workspace]/[gatsby-remark-responsive-iframe]/index.js:37:23
  
  - index.js:25 one
    [workspace]/[unist-util-visit]/index.js:25:16
  
  - index.js:46 all
    [workspace]/[unist-util-visit]/index.js:46:20
  
  - index.js:29 one
    [workspace]/[unist-util-visit]/index.js:29:14
  
  - index.js:46 all
    [workspace]/[unist-util-visit]/index.js:46:20
  
  - index.js:29 one
    [workspace]/[unist-util-visit]/index.js:29:14
  
  - index.js:16 visit
    [workspace]/[unist-util-visit]/index.js:16:3
  
  - index.js:36 
    [workspace]/[gatsby-remark-responsive-iframe]/index.js:36:5
  
  - debuggability.js:303 Promise._execute
    [workspace]/[bluebird]/js/release/debuggability.js:303:9
  
  - promise.js:483 Promise._resolveFromExecutor
    [workspace]/[bluebird]/js/release/promise.js:483:18
  
  - promise.js:79 new Promise
    [workspace]/[bluebird]/js/release/promise.js:79:10
  
  - index.js:31 module.exports
    [workspace]/[gatsby-remark-responsive-iframe]/index.js:31:10
  
  - extend-node-type.js:144 
    [workspace]/[gatsby-transformer-remark]/extend-node-type.js:144:32
  
  - util.js:16 tryCatcher
    [workspace]/[bluebird]/js/release/util.js:16:23
  
  - reduce.js:155 Object.gotValue
    [workspace]/[bluebird]/js/release/reduce.js:155:18
  
  - reduce.js:144 Object.gotAccum
    [workspace]/[bluebird]/js/release/reduce.js:144:25
  
  - util.js:16 Object.tryCatcher
    [workspace]/[bluebird]/js/release/util.js:16:23
  
  - promise.js:512 Promise._settlePromiseFromHandler
    [workspace]/[bluebird]/js/release/promise.js:512:31
  
  - promise.js:569 Promise._settlePromise
    [workspace]/[bluebird]/js/release/promise.js:569:18
  


(sharp:10633): GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(sharp:10633): GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(sharp:10633): GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(sharp:10633): GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(sharp:10633): GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(sharp:10633): GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(sharp:10633): GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(sharp:10633): GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(sharp:10633): GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(sharp:10633): GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(sharp:10633): GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(sharp:10633): GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(sharp:10633): GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(sharp:10633): GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(sharp:10633): GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(sharp:10633): GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed`

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
