### ISSUE TITLE
gatsby-source-wordpress doesn't create static files for all media

### ISSUE THREAD

**Issue by dongepulango** [gatsbyjs/gatsby#34899]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

gatsby-source-wordpress doesn't create static files for all media items in the `uploads` folder.

I have this setting turn on:
```
html: {
   createStaticFiles: true,
}
```
But now sure why some images are created, some are not. They all have the same format, as png.

### Expected Result

All images generated static files.

### Actual Result

Some images still have `src` to L**ocal by Flywheel** server that I use.

### Environment

```shell
System:
    OS: macOS 12.1
    CPU: (8) x64 Apple M1
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.4 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.19.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  Browsers:
    Chrome: 98.0.4758.102
    Firefox: 90.0.2
    Safari: 15.2
  npmPackages:
    gatsby: ^4.4.0 => 4.6.0
    gatsby-image: ^3.11.0 => 3.11.0
    gatsby-plugin-image: ^2.5.0 => 2.6.0
    gatsby-plugin-manifest: ^4.4.0 => 4.6.0
    gatsby-plugin-offline: ^5.4.0 => 5.6.0
    gatsby-plugin-react-helmet: ^5.0.0 => 5.6.0
    gatsby-plugin-sass: ^5.6.0 => 5.6.0
    gatsby-plugin-sharp: ^4.5.0 => 4.6.0
    gatsby-plugin-sitemap: ^5.7.0 => 5.7.0
    gatsby-plugin-styled-components: ^5.4.0 => 5.6.0
    gatsby-plugin-wpgraphql-seo: ^1.4.1 => 1.4.1
    gatsby-source-filesystem: ^4.4.0 => 4.6.0
    gatsby-source-wordpress: ^6.4.0 => 6.6.0
    gatsby-transformer-json: ^4.4.0 => 4.6.0
    gatsby-transformer-remark: ^5.4.0 => 5.6.0
    gatsby-transformer-sharp: ^4.5.0 => 4.6.0
  npmGlobalPackages:
    gatsby-cli: 3.1.0
```

**Comment by tyhopp** [comment]
Hi @dongepulango, thanks for the report!

Like the other issue you filed, it would be great if you could provide a [minimal reproduction][reproduction] and share a link to the public GitHub repo here. If it's the same site as the one from https://github.com/gatsbyjs/gatsby/issues/34883 please do share the link here as well.

[reproduction]: https://gatsby.dev/reproduction

**Comment by Mrchow86** [comment]
What do u mean.... I think this has been a big mix up.

**Comment by peach-inzn** [comment]
I seem to have the same issue. I would like to download _all_ images to the static folder from my WordPress as I have two components that will only show when a state is met.


Basically, this is my code:
```
const PostTemplate = ({ data }) => {
  const [isToggled, setIsToggled] = useState(true);
  return (
    <Layout class="page post">
      <main>
        <div className="post__overview">
          <div className="post__filter">
            <button onClick={() => setIsToggled(true)} data-active={isToggled}>
              Views
            </button>
            <h2>/</h2>
            <button
              onClick={() => setIsToggled(false)}
              data-active={!isToggled}
            >
              Works
            </button>
          </div>
          {isToggled ? (
            <div dangerouslySetInnerHTML={{ __html: data.views.content }} />
          ) : (
            <div dangerouslySetInnerHTML={{ __html: data.works.content }} />
          )}
        </div>
        <div className="post__text">
          <h2>{data.text.title}</h2>
          <div
            className="post__description"
            dangerouslySetInnerHTML={{
              __html: data.text.content,
            }}
          />
        </div>
      </main>
    </Layout>
  );
};
```

On load, Views (meaning: data.views.content) shows both images and captions perfectly with GatsbyImage. The moment I switch state to mount Works (data.works.content) and unmount Views, the captions change the the GatsbyImage src as well. However, it is empty since the images haven't yet been downloaded. When I then switch back to Views, they don't get displayed either anymore (captions still change).

If I add:
```
html: {
          createStaticFiles: false,
          useGatsbyImage: false,
        },
        type: {
          MediaItem: { createFileNodes: false },
        }
```
it works, but of course doesn't use GatsbyImage anymore. 

Is there a way to download all the images so I can keep on using GatsbyImage but don't have issues with the images in the components?

**Comment by LekoArts** [comment]
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Comment by dongepulango** [comment]
> Hi!
> 
> Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

Ok, But doesn't mean it's resolved. 😉

**Comment by arjendejong12** [comment]
So I also experienced this issue and I have been able to fix this by changing two files:

https://github.com/gatsbyjs/gatsby/blob/912cd003f90601c120fbaf30bb8057f4fac0fcd3/packages/gatsby-source-wordpress/src/steps/source-nodes/create-nodes/process-node.js#L745-L746
```js
} else if (node.localFile) { 
  fileNode = await helpers.getNode(node.localFile.id ?? node.localFile) 
```
The reason for this change is that the media item `node.localFile` is already the ID for reasons I don't know. By falling back to `node.localFile`, I can correctly retrieve the media items I used in the content. Before it wouldn't process any media item.

&mdash;&mdash;&mdash;
https://github.com/gatsbyjs/gatsby/blob/912cd003f90601c120fbaf30bb8057f4fac0fcd3/packages/gatsby-source-wordpress/src/steps/source-nodes/fetch-nodes/fetch-referenced-media-items.js#L442
```js
return allResults.concat(previouslyCachedMediaItemNodes).flat()
```
The reason for this change is that I'm using some media items in multiple pages and when an item is already processed in one page, it gets stored in the `previouslyCachedMediaItemNodes` variable for the other page, but this variable is not used anywhere after, so that's the reason (for me) that some items are not being made static.

&mdash;&mdash;&mdash;

@tyhopp @LekoArts Could you shed some light on this and maybe reopen this issue?

**Comment by arjendejong12** [comment]
@TylerBarnes Could you take a look at my comment above this one?
