### ISSUE TITLE
gatsby-plugin-preact: Can't resolve 'react/jsx-runtime' with `@mui/material`

### ISSUE THREAD

**Issue by mikhin** [gatsbyjs/gatsby#35145]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Hi. I get an error when using `gatsby-plugin-preact` with `@mui/material`:

```
"@mui/material": "^5.4.1",
"gatsby": "^4.7.1",
"gatsby-plugin-preact": "^6.9.0",
"preact": "^10.6.6",
"preact-render-to-string": "^5.1.20",
"gatsby-plugin-sharp": "^4.7.0",
"gatsby-transformer-sharp": "^4.7.0",
```

### Reproduction Link

https://github.com/mikhin/my-gatsby-site

### Steps to Reproduce

1. Import some component in project, `import Slider from "@mui/material/Slider";`
2. Run `npx gatsby build`
3. Get a lot of errors like that: 
```
 ERROR #98124  WEBPACK

Generating JavaScript bundles failed

Can't resolve 'react/jsx-runtime' in '/node_modules/@mui/system/esm/cssVars'

If you're trying to use a package make sure that 'react/jsx-runtime' is
installed. If you're trying to use a local file make sure that the path is
correct.

File: node_modules/@mui/system/esm/cssVars/getInitColorSchemeScript.js:2:0

not finished Running gatsby-plugin-sharp.IMAGE_PROCESSING jobs - 26.385s
```

### Expected Result

Successful build

### Actual Result

Build process finished with error

### Environment

```shell
macos 12.12.1
node 16.14.0
yarn 1.22.17
```

EDIT:

Adding of code

```
actions.setWebpackConfig({
    resolve: {
      alias: {
        "react": "preact/compat",
        "react/jsx-runtime": "preact/jsx-runtime"
      }
    }
  })
```

to `gatsby-node.js` solves this issue, but it is a redundant measure, isn't it?

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by mikhin** [comment]
Hi! Here it is — https://github.com/mikhin/my-gatsby-site

Thank you!
