### ISSUE TITLE
gatsby-source-contentful Cannot read properties of null (reading 'url')

### ISSUE THREAD

**Issue by afladmark** [gatsbyjs/gatsby#35216]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I've run into another breaking issue with gatsby-source-contentful. It seems to relate to the changes made for the Image CDN beta and likely is related to our locale setup. I've created a reproduction.

The Contentful configuration is simple. Add a second locale. In the test environment we have English and Spanish. Spanish is configured without a fallback. We do this so that we can tell when content isn't translated and most often we hide it.

<img width="1411" alt="image" src="https://user-images.githubusercontent.com/11227540/159802169-3255f071-367a-42b0-b739-307ef4a49480.png">

Then, I've just created two image assets with only the default English one uploaded.

From there, just run `npm run develop` and it will crash with:

```
 ERROR #11321  PLUGIN

"gatsby-source-contentful" threw an error while running the sourceNodes lifecycle:

Cannot read properties of null (reading 'url')

  TypeError: Cannot read properties of null (reading 'url')
  
  - normalize.js:651 
    [gatsby-contentful-url]/[gatsby-source-contentful]/normalize.js:651:26
  
  - Array.forEach
  
  - normalize.js:619 createAssetNodes
    [gatsby-contentful-url]/[gatsby-source-contentful]/normalize.js:619:11
  
  - source-nodes.js:305 Object.sourceNodes
    [gatsby-contentful-url]/[gatsby-source-contentful]/source-nodes.js:305:75
  
  - task_queues:96 processTicksAndRejections
    node:internal/process/task_queues:96:5
  
  - api-runner-node.js:462 runAPI
    [gatsby-contentful-url]/[gatsby]/src/utils/api-runner-node.js:462:16
```

### Reproduction Link

https://github.com/afladmark/gatsby-contentful-url

### Steps to Reproduce

1. Download the reproduction repro
2. `npm install` then `npm run develop`
3. See the above error

### Expected Result

Not to error.

### Actual Result

The error above is displayed.

### Environment

```shell
System:
    OS: macOS 12.3
    CPU: (10) arm64 Apple M1 Max
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.17 - ~/.yarn/bin/yarn
    npm: 8.5.3 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Browsers:
    Chrome: 99.0.4844.83
    Edge: 99.0.1150.46
    Firefox: 98.0.1
    Safari: 15.4
  npmPackages:
    gatsby: ^4.10.2 => 4.10.2 
    gatsby-plugin-image: ^2.10.1 => 2.10.1 
    gatsby-plugin-sharp: ^4.10.2 => 4.10.2 
    gatsby-source-contentful: ^7.8.2 => 7.8.2
```

**Comment by shameer-rahman** [comment]
i get the same error too...

**Comment by axe312ger** [comment]
I can confirm that the e2e tests use a content model with locale fallback on the second locale. We might have missed this.

**Comment by xavivars** [comment]
It seems this line is the culprit: 

https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-contentful/src/normalize.js#L720

    const file = assetItem.fields.file ? getField(assetItem.fields.file) : {}


`getField(assetItem.fields.file)` can return null, and then everything fails later. Not sure what should be the right solution, though... skip the node if field is null? or use default locale if there's no localized version?

**Comment by axe312ger** [comment]
When we fix this, we should add (e2e) tests that run:

* On a Space without locale fallback
* Test Contentful CDA and CPA APIs
* Include empty, translated and untranslated assets
* Content entities/entries with empty required fields and invalid validations

**Comment by xavivars** [comment]
I added an MR that prevents the null pointer exception, but I'm not convinced if it's the right solution.

As it is, it already allows to run `gatsby build`, so it's definitely a step forward. But I'm not sure if the right thing to do is to create half-empty/broken asset nodes.

**Comment by pieh** [comment]
> As it is, it already allows to run `gatsby build`, so it's definitely a step forward (it was enough for me to have builds passing). But I'm not sure if the right thing to do is to create half-empty/broken asset nodes.

Just trying to think on this:
While this might not be "best" solution, but if we skip creating asset nodes when `file` is not there then links on actual content might be wrong (we might have links to nodes that don't exist). I did short experiment and could confirm that:
```
# logged when creating links on content nodes
linked "cd4cda84-9999-5826-8555-e019b68c45ef"
# logged when I skipped creating asset node while localized file is not there
skipping "cd4cda84-9999-5826-8555-e019b68c45ef"
```

Then I added `localeFilter` to plugin options in config:
```
localeFilter: (locale) => locale.code === `es`,
```

And without any actual media uploaded to `es` locale I got dreaded

```
Violation: Encountered an error trying to infer a GraphQL type for:
`image___NODE`. There is no corresponding node with the `id` field matching:
"cd4cda84-9999-5826-8555-e019b68c45ef".'. Stacktrace was 'Invariant Violation:
Encountered an error trying to infer a GraphQL type for: `image___NODE`. There is
 no corresponding node with the `id` field matching:
"cd4cda84-9999-5826-8555-e019b68c45ef".
```

So skipping asset node creation for assets without actual files would require much more work (prevent creating links for assets that won't be created).

What are the alternatives:
1. If Contentful requires default locale to contain actual file, maybe we just fallback to default locale file. We can add some boolean field saying this asset node is borked (and user might chose to check and skip it). Problem - this is not actually correct, as fallback locale wasn't set.
2. Create "shim nodes" (like https://github.com/gatsbyjs/gatsby/pull/35244 ). Problem - with PR as is, `url` and `placehodler` field on it will be `https:undefined` (or something like that) - we should check what happens when we try to run some image processing on those or use `downloadLocal` option. Maybe it would be enough just to make those fields `undefined` and then adjust (if needed) image processing or file downloading code to handle cases like that?

**Comment by afladmark** [comment]
From our perspective, the way it has worked to date is effectively alternative number 2. Then we've manually implemented alternative 1 using resolvers. When the Asset's `childImageSharp` or `localFile` node is `null` in a locale we query for the same `contentful_id` in our base locale and return that node's data instead.

The only annoyance with the original implementation was that we got a warning for every single asset in every single non-base locale as none of them are translated (we don't have text in our images). For us that is some 19k lines of warnings spewed on every build for a perfectly valid Contentful configuration.

I agree this issue needs two different interventions in terms of resolution. As it is you've broken production releases for some customers since you introduced the Image CDN beta feature implementation. As a consequence, we're also blocked from updating and receiving other bug fixes we desperately need. That feels like a big process red flag to me. Why isn't the Image CDN stuff on a pre-release tag/branch? From our perspective, please, please fix the null issue with some urgency.

Then yes, ultimately, there is a need to write meaningful tests for these missed use cases and come up with a solution for how to implement the new Image CDN functionality without breaking existing, valid configurations of Contentful and the Contentful source plugin.

**Comment by axe312ger** [comment]
I created a space that mimics the content structure of @afladmark and created tests out of it.

Found a few more edge cases that would let the build fail.

Check out https://github.com/gatsbyjs/gatsby/pull/35244 for the fix :)

**Comment by emmgait** [comment]
Hello guys just faced this error:

"gatsby-source-contentful" threw an error after adding a new locale in Contentful:

`"gatsby-source-contentful" threw an error
while running the sourceNodes lifecycle:

Cannot read property 'url' of null
`

In order to fix this make sure to have a language assigned as a fallback in Countentful.

![Screenshot 2022-04-21 at 2 11 58 PM](https://user-images.githubusercontent.com/55083442/164446193-6f49149d-4562-48b8-8e37-95338d98429e.png)
