### ISSUE TITLE
Add debug step for missing data

### ISSUE THREAD

**Issue by elliott-w** [gatsbyjs/gatsby#35230]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Summary

1. Run `gatsby clean`
2. Run `gatsby build`  - at this point it retrieves all graphql data correctly
3. Run `gatsby build` again - it consistently returns an empty list of nodes for all your queried post types using `allWpPage`, `allWpPost`, etc.

### Steps to Resolve this Issue

1. Deleting all my posts for every post type
2. Restoring them from trash

Please add this as a recommended step in the documentation (if all else fails).

I have no idea why this was happening. Somehow the state of my pages, posts, etc became corrupted. How? My best guess is either:
1. When I registered a new post type
2. When I added/updated acf fields

**Comment by tyhopp** [comment]
Hi @elliott-w,

Sorry to hear you're running into an issue. Please add more detail to your issue (e.g. output from [`gatsby info`](https://www.gatsbyjs.com/docs/reference/gatsby-cli/#info)) and a [minimal reproduction][reproduction]. This helps make it clear what the issue is and gives us context to begin debugging if it is an issue.

Alternatively if you have a question, please post in https://github.com/gatsbyjs/gatsby/discussions instead.

[reproduction]: https://gatsby.dev/reproduction

**Comment by elliott-w** [comment]
Hi @tyhopp,

You can find a minimal repo here: https://github.com/elliott-w/gatsby-wp-acf-starter/tree/bug

To reproduce the bug you will need my production wordpress site files and database, which I'm happy to send you privately.

**Comment by tyhopp** [comment]
Hi @elliott-w, if you haven't already I recommend having a look at the [`gatsby-source-wordpress` debugging and troubleshooting guide section on node sourcing](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/docs/debugging-and-troubleshooting.md#node-sourcing), which has a lot useful info related to this (including the build and build again method you mentioned).

I'll close this since we have this mentioned in the guide.

**Comment by elliott-w** [comment]
@tyhopp could you please re-open this issue?

I've gone through the debugging and troubleshooting steps. I used the [Altair](https://altair.sirmuel.design/) graphql client and for step 10, the Altair graphql response does NOT have missing data, unlike the response from `gatsbyUtilities.graphql(query)` which is returning an empty list of page nodes.

I have a dropbox link of all the wordpress files (including the database.sql file) you need to recreate this issue, along with this repo: https://github.com/elliott-w/gatsby-wp-acf-starter/tree/bug

Any help would be much appreciated, thank you

**Comment by elliott-w** [comment]
@tyhopp Could you please re-open so this doesn't get lost to the ether? Cheers

**Comment by elliott-w** [comment]
Hi @tyhopp I understand you're probably busy, but if there's anything else I can do to get this one moving along, more than happy to help.

**Comment by elliott-w** [comment]
@tyhopp this is still a major issue for me. Any chance I could get somebody to look into this please?

**Comment by TylerBarnes** [comment]
@elliott-w this doesn't appear to be related to source-wordpress. I pulled down your reproduction and ran it against a local site twice and both times all the data existed. I'm sure you have a bug in your custom create pages code that's causing this issue.

If you can provide a minimal reproduction (not a full site) with a public WP instance (or an export from Local by flywheel that we can download) we can take another look
