### ISSUE TITLE
trailingSlash option isn't applied on client-side links when a relative path is specified

### ISSUE THREAD

**Issue by pragmaticpat** [gatsbyjs/gatsby#35419]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

See : https://github.com/gatsbyjs/gatsby/discussions/34205#discussioncomment-2544407

### Reproduction Link

https://github.com/wad-im/wadim-on-the-internet

### Steps to Reproduce

1. Clone the linked repository
2. Run `gatsby develop`
3. Hover the first blog post => notice no trailing slash
4. Click the first blog post -> notice no trailing slash in the URL
5. Refresh the page -> notice trailing slash has been applied

### Expected Result

The hover and clicked link should both have trailing slashes, as requested in the configuration option `trailingSlash: "always"`

### Actual Result

The hover and clicked link should both lack trailing slashes, even though trailing slash was requested in the configuration option `trailingSlash: "always"`

### Environment

```shell
- n/a -
```

### Config Flags

`trailingSlash: "always"`

**Comment by LekoArts** [comment]
A way to "fix" this is to add leading slashes to the `slug` in the frontmatter.

https://github.com/wad-im/wadim-on-the-internet/blob/c4bea721c3972abbe02fbe0fc3454e9395c01e2f/blog/first-post/index.mdx

Because that's why it's not working. So instead of `first-blogpost/` it would be `/first-blogpost`.

Inside `gatsby-link` we `absolutify` this path since the check for this is falsy:

https://github.com/gatsbyjs/gatsby/blob/f63d13db0c635c0ade66169982e061630306fca0/packages/gatsby-link/src/rewrite-link-path.js#L38-L40

So after we successfully apple the trailing slash, with `absolutify` it's gone afterwards.

Our `<Link>` in the e2e tests all use links with leading slash: https://github.com/gatsbyjs/gatsby/blob/master/e2e-tests/trailing-slash/src/pages/index.js
We should use (for testing purposes) `to` without a leading slash.

**Comment by LekoArts** [comment]
Because the page you created now has two leading slashes:
https://github.com/wad-im/wadim-on-the-internet/blob/c4bea721c3972abbe02fbe0fc3454e9395c01e2f/gatsby-node.ts#L24

Removing it there and rerunning a build will work. (with `path: node.frontmatter.slug`)

**Comment by wad-im** [comment]
Thank you, Lennart. You are of course right and it works like a charm and as expected now.
