### ISSUE TITLE
[gatsby-source-wordpress] After adding wordpress plugin, gatsby develop throws error

### ISSUE THREAD

**Issue by qdupendra** [gatsbyjs/gatsby#3562]
I have created a new trial project with gatsby-bootstrap starter and installed gatsby-source-wordpress plugin as instructed with all the wp plugin configuration/credentials etc. 

When trying to build or develop the project to check it in the browser, it throws an error and won't compile.

The error log is as followed: 

`error UNHANDLED EXCEPTION`

`  Error: ENOENT: no such file or directory, rename '/Volumes/Data/WebsiteProjects/GatsbyWordpress/.cache/gatsby-source-filesystem/tmp-e8c2ad91b6179055d0ae09c526e48078.jpg' -> '/Volumes/Data/WebsiteProjects /GatsbyWordpress/.cache/gatsby-source-filesystem/e8c2ad91b6179055d0ae09c526e48078.jpg'`
  
`  - Error`
  
`  - index.js:27 tryRenameSync
    [GatsbyWordpress]/[fs-extra]/lib/move-sync/index.js:27:19`
  
`  - index.js:22 Object.moveSync
    [GatsbyWordpress]/[fs-extra]/lib/move-sync/index.js:22:3`
  
`  - create-remote-file-node.js:101 DuplexWrapper.<anonymous>
    [GatsbyWordpress]/[gatsby-source-filesystem]/create-remote-file-node.js:101:22`
  
` - next_tick.js:74 _combinedTickCallback
    internal/process/next_tick.js:74:11`
  
`  - next_tick.js:98 process._tickCallback
    internal/process/next_tick.js:98:9`

This error occurs after wordpress plugin has finished fetching pages, posts, comments etc.

I have built and used `develop` command to start the local server with the site successfully before I installed the wordpress plugin, after which, I cannot finish the build process.

Please help me resolve this issue.

Thanks.

**Comment by KyleAMathews** [comment]
Does the `.cache/gatsby-source-filesystem/` directory exist in your site?

**Comment by qdupendra** [comment]
Yes, the directory exists and has many items in it, but I couldn't find the said item in the directory, hence the error. I don't know how to go about it

**Comment by Fetten** [comment]
I also had this issue recently on a multi-language WordPress site, which uses Polylang Pro as translation plugin. 

Polylang creates an additional database entry (= post) for every image translation, but doesn't duplicate the image file itself. So gatsby-source-wordpress receives e.g. 3 entities from the REST api, which all point to the same image file.

I think the problem could might be in `gatsby-source-filesystem`'s image creation in `create-remote-file-node`. After downloading the image with a temporary file name, [it renames this file to a non temporary name](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-filesystem/src/create-remote-file-node.js#L87). The next process with the same file can't proceed, because the tmp file is already deleted.

I haven't really worked through gatsby-source-filesystem, but could think of the following solutions:
* check if a filename already exists
* keep track of already downloaded files and skip multiple creations

Any thoughts on this or additional ideas?

**Comment by Fetten** [comment]
Ok, I have a PR ready for this, which checks for duplicate media files.
Just waiting for the [new normalizer PR](https://github.com/gatsbyjs/gatsby/pull/3783) to get merged before adding it.

**Comment by justinwhall** [comment]
@Fetten Care to share a branch? :)

**Comment by Fetten** [comment]
@justinwhall Sure :)
https://github.com/Fetten/gatsby/commit/dae56645aa67d7bd38c5d4c36e017d4b59a6b721
