### ISSUE TITLE
Content from Wrodpress disappears on load

### ISSUE THREAD

**Issue by andreybo** [gatsbyjs/gatsby#35646]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Content part on blog post page disappear on page load. Few seconds content is visible. Thumbnail, title, data etc are okay, but text going out after load. the same result with old working builds. 
One issue in console:
react-dom.development.js:67 Warning: Expected server HTML to contain a matching <div> in <div>

Some posts work but mostly crash. Dont see logic on it, because posts content the same. Also page can be good on desktop, but hidden on mobile.

Maybe-maybe something with react hydrate.

### Reproduction Link

https://github.com/andreybo/gatsby-issue

### Steps to Reproduce

1. gatsby start
2. go to homepage
3. click to post
4. take a look at content after page load

### Expected Result

See full post content

### Actual Result

Post content disappear after load

### Environment

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  Binaries:
    Node: 14.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.10.4
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (101.0.1210.39)
  npmPackages:
    gatsby: ^4.12.1 => 4.14.0 
    gatsby-plugin-disqus: ^1.2.3 => 1.2.4 
    gatsby-plugin-gatsby-cloud: ^4.12.1 => 4.14.0 
    gatsby-plugin-gdpr-cookies: ^2.0.8 => 2.0.9 
    gatsby-plugin-google-analytics: ^4.12.1 => 4.14.0 
    gatsby-plugin-image: ^2.12.1 => 2.14.1 
    gatsby-plugin-local-search: ^2.0.1 => 2.0.1 
    gatsby-plugin-manifest: ^4.12.1 => 4.14.0 
    gatsby-plugin-react-helmet: ^5.12.0 => 5.14.0 
    gatsby-plugin-robots-txt: ^1.7.1 => 1.7.1 
    gatsby-plugin-sass: ^5.12.1 => 5.14.0 
    gatsby-plugin-sharp: ^4.12.1 => 4.14.1 
    gatsby-plugin-sitemap: ^5.12.1 => 5.14.0 
    gatsby-remark-images: ^6.12.1 => 6.14.0 
    gatsby-remark-lazy-load: ^1.0.2 => 1.0.2 
    gatsby-source-filesystem: ^4.12.1 => 4.14.0 
    gatsby-source-graphcms: ^2.8.0 => 2.8.0 
    gatsby-source-wordpress: ^6.12.2 => 6.14.1 
    gatsby-transformer-remark: ^5.12.1 => 5.14.0 
    gatsby-transformer-sharp: ^4.12.1 => 4.14.0
```

**Comment by pieh** [comment]
Hey @andreybo 

I can't run repo you provided because I lack concrete WP_GRAPHQL url ( https://github.com/andreybo/gatsby-issue/blob/22bf39c1b56ed9ce0a4b96093a7c4d2f21cf1d16/gatsby-config.js#L74 )

Any chance you can provide that URL for me to test on? If you don't want to share the URL publicly but are fine with private form - you can DM me on twitter ( https://twitter.com/mipiechowiak ) or on our Discord ( https://gatsby.dev/discord , user `pieh#4986` )

**Comment by andreybo** [comment]
Hey @pieh the problem was in .lock file. Build is okay with old file, and content id disappeared if i try to remove lock file and build it again. 
.lock files [here](https://drive.google.com/drive/folders/116PkmoLE8fQXgKrGgNOlmp_LcCF9tTtC?usp=sharing)
build with disappeared posts [here](https://build-1a7d1084-3116-4879-9ffc-aaeed775b4d0.gtsb.io/)
please take a look

**Comment by LekoArts** [comment]
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!
