### ISSUE TITLE
[gatsby-transformer-documentationjs] jsx file support

### ISSUE THREAD

**Issue by kieuvyn12** [gatsbyjs/gatsby#35842]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

This plugin is not extracting all of the code metadata for `.jsx` files, it is only for `.js`, `.ts` and `.tsx` files.

In this case, I am trying to pull the `returns` and `params` information from the PropTypes JSDocs information for functions in a React component.

Please see below for the Graphiql query that shows that the `childrenDocumentationJs` field is empty for `.jsx` files, but grabs the correct information for an identical file that is `.js` instead of `.jsx`.

<img width="1626" alt="Screen Shot 2022-06-03 at 11 06 01 AM" src="https://user-images.githubusercontent.com/46635942/171881284-fd77b810-5bad-4631-847b-56d79761f463.png">

I believe this is related to these lines of code from https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-transformer-documentationjs/src/gatsby-node.js#L188 since the `node.internal.mediaType` does not include `text/jsx`: 
<img width="568" alt="image" src="https://user-images.githubusercontent.com/46635942/171881717-ae6435d9-151c-498b-9a3c-8eb15ce6bc1f.png">

### Reproduction Link

https://github.com/kieuvyn12/gatsby-bug-reproduction

### Steps to Reproduce

1. Clone the reproduction repository
2. `npm install`
3. `gatsby develop`
4. navigate to http://localhost:8000/__graphql
5. add this GraphQL query: 

```query MyQuery {
  allFile {
    edges {
      node {
        name
        childrenDocumentationJs {
          name
          params {
            name
          }
          returns {
            name
          }
        }
        internal {
          mediaType
        }
      }
    }
  }
}
```
6. observe the differences between the 2 nodes of the same files with different types (.jsx vs .js file)

### Expected Result

The `childrenDocumentationJs` field should be populated with the correct `params` and `returns` information

### Actual Result

The `childrenDocumentationJs` field is empty

### Environment

```shell
System:
    OS: macOS 12.3.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.2.0 - /usr/local/bin/node
    npm: 8.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 102.0.5005.61
    Edge: 102.0.1245.30
    Safari: 15.4
  npmPackages:
    gatsby: ^4.15.2 => 4.15.2
    gatsby-plugin-mdx: ^3.15.1 => 3.15.1
    gatsby-source-filesystem: ^4.15.0 => 4.15.0
    gatsby-transformer-documentationjs: ^6.15.0 => 6.15.0
  npmGlobalPackages:
    gatsby-cli: 4.15.1
```

**Comment by kieuvyn12** [comment]
@cameron-yee @cmahrtian

**Comment by cameron-yee** [comment]
From the [Gatsby Node APIs Docs](https://www.gatsbyjs.com/docs/reference/config-files/gatsby-node/#unstable_shouldOnCreateNode), `exports.unstable_shouldOnCreateNode` is:

> Called before scheduling a onCreateNode callback for a plugin. If it returns falsy then Gatsby will not schedule the onCreateNode callback for this node for this plugin.

Does this mean that the control flow check on [line 204-206](https://github.com/gatsbyjs/gatsby/blob/0cd90d9bd1f1d93f598fa137341b1438214f25e8/packages/gatsby-transformer-documentationjs/src/gatsby-node.js#L204) of `gatsby-node.js` is unnecessary?

The `childrenDocumentationJs` field is not created for `.jsx` files because the mediaType is `text/jsx`. Adding this mediaType or adding the `.jsx` extension to the `exports.unstable_shouldOnCreateNode` function should fix the issue.

For testing, [this test](https://github.com/gatsbyjs/gatsby/blob/0cd90d9bd1f1d93f598fa137341b1438214f25e8/packages/gatsby-transformer-documentationjs/src/__tests__/gatsby-node.js#L374) should be updated to check for the `jsx` extension. This test is also missing checks for `ts` and `tsx` extensions so they should be added to this test as well.

```
it(`should only process javascript File nodes`, async () => {
    await run({ internal: { mediaType: `text/x-foo` } })         
        expect(createdNodes.length).toBe(0)

    await run({ internal: { mediaType: `application/javascript` } })
        expect(createdNodes.length).toBe(0)

    await run({ internal: { type: 'File' }, extension: 'jsx' })
        expect(createdNodes.length).toBe(1)
      
    await run({ internal: { type: 'File' }, extension: 'ts' })
        expect(createdNodes.length).toBe(1)
      
    await run({ internal: { type: 'File' }, extension: 'tsx' })
        expect(createdNodes.length).toBe(1)

    await run(getFileNode(`code.js`))
        expect(createdNodes.length).toBeGreaterThan(0)
    })
  })
```
