### ISSUE TITLE
Critical Vulnerability in parse-url

### ISSUE THREAD

**Issue by akshits96** [gatsbyjs/gatsby#36018]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

A new critical vulnerability in parse-url pulled in by gatsby:
https://nvd.nist.gov/vuln/detail/CVE-2022-2216
https://huntr.dev/bounties/505a3d39-2723-4a06-b1f7-9b2d133c92e1/

### Reproduction Link

https://github.com/IonicaBizau/parse-url

### Steps to Reproduce

A new critical vulnerability in parse-url pulled in by gatsby:
https://nvd.nist.gov/vuln/detail/CVE-2022-2216
https://huntr.dev/bounties/505a3d39-2723-4a06-b1f7-9b2d133c92e1/

### Expected Result

either its not applicable/false positive or library version needs to be bumped

### Actual Result

vulnerable version is pulled in

### Environment

```shell
NA
```

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

While those audit messages might seem scary they are almost always irrelevant in the context of Gatsby as it's a build tool. So there is nothing to "fix" as the warning is not relevant.

Gatsby creates static assets and runs everything at build time and not during runtime. `npm audit` is designed for runtime / Node apps so it flags issues that can occur there. This means that almost every "vulnerability" report we receive are false positives. While in principle Gatsby can also have vulnerabilities you need to make sure that it's relevant to Gatsby before reporting it. For example a "Regex DDOS attack" can never be a real vulnerability for a development-time tool. If you want to override/update a transitive dependency you can use [yarn resolutions](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/).

You can also read [npm audit: Broken by Design](https://overreacted.io/npm-audit-broken-by-design/) to learn more about this.

If you know that a vulnerability affects Gatsby because you understand what the vulnerability is, please report it [through our security document](https://github.com/gatsbyjs/gatsby/blob/master/SECURITY.md). Thanks!
