### ISSUE TITLE
[gatsby-source-wordpress]: `options.develop.hardCacheData` does not work if any fields are generated by `createNodeField`

### ISSUE THREAD

**Issue by tsdexter** [gatsbyjs/gatsby#36264]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

`options.develop.hardCacheData` does not work if any fields are generated by `createNodeField`

### Reproduction Link

https://github.com/tsdexter/gatsbycreatenodefieldhardcachedatarepro

### Steps to Reproduce

1. clone https://github.com/tsdexter/gatsbycreatenodefieldhardcachedatarepro
2. `npm install`
3. `npm run develop`
4. wait for it to build
5. `cmd+c` (quit the `develop` process)
6. `npm run clean`
7. `npm run develop` a second time

### Expected Result

Subsequent `develop` sessions should build and run

### Actual Result

development build fails with error below. Having to turn off this feature really slows down development builds. 

```
Error: Plugins creating nodes can not set data on the reserved field "fields"
      as this is reserved for plugins which wish to extend your nodes.       

      If your plugin didn't add "fields" you're probably seeing this
      error because you're reusing an old node object.
```

### Environment

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
  Binaries:
    Node: 14.20.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.17 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.8 - /c/Python27/python
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.71)
  npmPackages:
    gatsby: ^4.0.0 => 4.19.2 
    gatsby-plugin-image: ^2.0.0 => 2.19.0 
    gatsby-plugin-manifest: ^4.0.0 => 4.19.0 
    gatsby-plugin-offline: ^5.0.0 => 5.19.0 
    gatsby-plugin-react-helmet: ^5.0.0 => 5.19.0 
    gatsby-plugin-sharp: ^4.0.0 => 4.19.0 
    gatsby-source-filesystem: ^4.0.0 => 4.19.0 
    gatsby-source-wordpress: ^6.0.0 => 6.19.0 
    gatsby-transformer-sharp: ^4.0.0 => 4.19.0
```

**Comment by tsdexter** [comment]
not stale, afaik

**Comment by tsdexter** [comment]
@LekoArts @TylerBarnes I've updated the repro to 4.22.1 and the issue still persists...you can't run `develop` again until `rm -rf .wordpress-cache` which defeats the purpose of the feature

**Comment by TylerBarnes** [comment]
Hey @tsdexter, thanks for opening this issue. `hardCacheData` is [marked as an experimental feature](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/docs/plugin-options.md#develophardcachedata) because there are many cases where it doesn't work properly. In this case I would recommend not using it. For development a more effective way to cut down `gatsby develop` start up times is to use the [limit option](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/docs/plugin-options.md#type__alllimit)

You can set a limit to the total number of nodes fetched for each type. Check [this example](https://github.com/henrikwirth/gatsby-starter-wordpress-twenty-twenty/blob/master/gatsby-config.js#L51-L57). You can also add a limit for nodes of all types by substituting the typename for `__all` (so instead of `Post` in the example).
