### ISSUE TITLE
When using the route after redirect it reloads the page additionally

### ISSUE THREAD

**Issue by erkand-imeri** [gatsbyjs/gatsby#36559]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Hello, I updated Gatbsy.js and dependencies

```js
"dependencies": {
    "@n8tb1t/use-scroll-position": "^2.0.3",
    "autoprefixer": "^10.2.4",
    "flickity": "^2.2.2",
    "gatsby": "^4.22.0",
    "gatsby-plugin-image": "^2.22.0",
    "gatsby-plugin-manifest": "^4.22.0",
    "gatsby-plugin-optimize-svgs": "^1.0.5",
    "gatsby-plugin-postcss": "^5.22.0",
    "gatsby-plugin-react-helmet": "^5.22.0",
    "gatsby-plugin-remove-serviceworker": "^1.0.0",
    "gatsby-plugin-sharp": "^4.22.0",
    "gatsby-plugin-sitemap": "^5.22.0",
    "gatsby-plugin-smoothscroll": "^1.2.0",
    "gatsby-source-filesystem": "^4.22.0",
    "gatsby-transformer-json": "^4.22.0",
    "gatsby-transformer-sharp": "^4.22.0",
    "postcss": "^8.4.16",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-flickity-component": "^3.2.0",
    "react-helmet": "^6.1.0",
    "tailwindcss": "^2.0.3"
  },
  "devDependencies": {
    "gatsby-plugin-webpack-bundle-analyser-v2": "^1.1.21",
    "prettier": "2.2.1"
  },

```

But i am facing this weird behaviour when i deploy on hosting server, whenever i navigate any page either initially or via the Link component it redirects to the page then it reloads the page after that which is a strange behaviour.

I actually build gatsby site locally and served it just as it is done on production and the issue doesn't appear on local machine. What could this cause, anyone any idea?

### Reproduction Link

https://emelord.ca/

### Steps to Reproduce

1. Visit the website domain
2. It fetches website and reloads second time
3. Route/Navigate to a page, it navigates and reloads for the second time
...

### Expected Result

The reload on second time should not happen. 

### Actual Result

It keeps reloading the website for 2nd time whenever i visit the main page or use the route navigation provided via the Gatsby component Link

### Environment

```shell
Production Environment.

cpanel server, Static file serving.
```

**Comment by marvinjude** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction](https://gatsby.dev/reproduction). This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction](https://gatsby.dev/reproduction) and we'll be able to take another look.

Thanks for using Gatsby! 💜

**Comment by erkand-imeri** [comment]
Hello, sure i will.

**Comment by LekoArts** [comment]
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!
