### ISSUE TITLE
Offer to start server on different port if taken

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#368]
Currently we suggest people try a different port but no reason not to just do it for them.

Idea from https://github.com/facebookincubator/create-react-app/pull/101

**Comment by LukeSheard** [comment]
I'll take this on. We can use the same idea as react app and increment the port if it's in use after prompting the user?

**Comment by KyleAMathews** [comment]
Yup! Thanks!

**Comment by janosh** [comment]
@KyleAMathews I would take it a step further and automatically increment the port if 8000 is already occupied. Saves the user from having to confirm it every time. I often go away after typing `gatsby develop`, return a minute or two later expecting to be greeted by a finished compilation only to discover that the prompt has the whole time been awaiting my confirmation to use a different port.

Since the CLI supplies the port at which successful compilations can be viewed, I think there is little chance for confusion.

> DONE  Compiled successfully in 3299ms                  21:45:36
> 
> You can now view your site in the browser running at http://localhost:8001

**Comment by shannonbux** [comment]
Figma file ready for commenting: https://www.figma.com/file/z81zOLund5Z5FCjnHnUIrN/CLI?node-id=167%3A66

**Comment by lannonbr** [comment]
What's the status of this issue? The original issue has been solved and it looks that by the figma file that there is some improvements that want to be made, but maybe instead of keeping this issue open, a new one describing more in detail of the improvements could be made?
