### ISSUE TITLE
[gatsby-plugin-image] StaticImage "src" refers to an image with the same filename in another directory.

### ISSUE THREAD

**Issue by hitima** [gatsbyjs/gatsby#36809]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Hi, everyone.
I have found a strange behavior for me in StaticImage and would like to report it.
It is possible that I have missed something important, but I am not jumping to conclusions, and I need help.

First, the file structure in which the phenomenon occurs is as follows
Or please check the reproduced repo https://github.com/hitima/gatsby-pluguin-image-bug-repro

```
// Simplified Project Structure
src
├── components
│   └── Pages
│       ├── TestA
│       │   ├── index.tsx
│       │   └── kv.png // Image with the letters ComponentA
│       └── TestB
│           ├── index.tsx
│           └── kv.png // Image with the letters ComponentB
├── gatsby-types.d.ts
└── pages
    └── index.tsx // import TestA and TestB
```

`pages/index.tsx` consists of Components in `Pages/TestA and Pages/TestB`

Suppose we want to load kv.png from Components' index.tsx in the same directory with StaticImage.

```
// part of src/pages/index.tsx
<layout>
  <Page>
    <Container>
      <TestA />
      <TestB />
    </Container>
  </Page>
</layout>
```

TestA/index.tsx and TestB/index.tsx use StaticImage to call images from the same directory, as shown below. 
```
// part of src/Pages/TestA/index.tsx
<StaticImage src="kv.png" alt="" placeholder="blurred" />
```

then like this...
I expect to see a ComponentA image and a ComponentB image respectively, but they refer to the same image. is this because gatsby-plugin-image is using the src string as a cache key?
<img width="618" alt="image" src="https://user-images.githubusercontent.com/8252163/195559776-606df5db-18d5-4db5-95fb-9bda53928594.png">

For example, the official documentation includes an example that references an image in the same directory.

```
// OK
export function Dino() {
  const width = 300
  return <StaticImage src="trex.png" width={width} />
}
````
ref: https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-plugin-image/

Does this mean that it must be a unique string, preferably for use in a Structure that places the image on the same level as the Components presented at the top?

I'm sure I could be missing something, and I'd be glad if someone could help me.

### Reproduction Link

https://github.com/hitima/gatsby-pluguin-image-bug-repro

### Steps to Reproduce

1. clone  https://github.com/hitima/gatsby-pluguin-image-bug-repro
2. npm i && npm run  dev
3. see http://localhost:8000/

### Expected Result

Images in the same directory are displayed.

### Actual Result

Images from different directories are displayed.

### Environment

```shell
System:
    OS: macOS 11.6.8
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.15.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.17 - /usr/local/bin/python
  Browsers:
    Chrome: 106.0.5249.103
    Edge: 106.0.1370.42
    Firefox: 102.0.1
    Safari: 15.6.1
  npmPackages:
    gatsby: ^4.15.1 => 4.24.4
    gatsby-plugin-image: ^2.17.0 => 2.24.0
    gatsby-plugin-sharp: ^4.17.0 => 4.24.0
    gatsby-transformer-sharp: ^4.17.0 => 4.24.0
  npmGlobalPackages:
    gatsby-cli: 4.23.0
    gatsby: 3.10.1
```

**Comment by hitima** [comment]
Does anyone know anything about this?
I'm very confused...

**Comment by Talaxy009** [comment]
I've run the code and found that only one image is cached, it's the "Component B" image

![image](https://user-images.githubusercontent.com/41264828/201131934-5063eea4-2c5b-4ed0-a9d2-cfbba953669f.png)

According to this documentation <https://www.gatsbyjs.com/docs/conceptual/image-plugin-architecture/#write-out-image-data>

> Write out image data
This object is then written to disk as a JSON file. The filename is generated using a hash of the props, and it is saved in .cache/caches/gatsby-plugin-image. If there have been any errors, an object with the error data is written instead. This is so the errors can be displayed in the browser console too.

I think it is because you use same props in `StaticImage`, so both images have the same hash and "component B" overwrites "component A" during processing. Ended up having the page with two "Component B" images.

To prove my idea is right, I modify the code like this:

```jsx
// part of src/Pages/TestA/index.tsx
<StaticImage src="kv.png" alt="" placeholder="dominantColor" />
```
```jsx
// part of src/Pages/TestB/index.tsx
<StaticImage src="kv.png" alt="" placeholder="blurred" />
```

And here is the outcome 😁：
![image](https://user-images.githubusercontent.com/41264828/201138254-31cf91e8-e118-46da-92ff-b2eeabdbb5cb.png)
![image](https://user-images.githubusercontent.com/41264828/201139461-518d3213-2073-4e25-abb2-e7c5803e004d.png)

So my idea is right and I think it might be a bug in gatsby-plugin-image?🧐

**Comment by hitima** [comment]
@Talaxy009 
Thank you for the detailed explanation.
The architecture documentation was also helpful.

My original goal was inspired by the collocation approach, which confines related images and Components into a single directory.

If the props are hashed, I think that it seems risky to put the related files, including images, in one directory.

It seems like a big price to pay for duplicate props (mainly filenames) with respect to all the image files we will be developing.

I think I'll go back to using src/images as the starting point.

I'll wait for more feedback from the developers to see if this is a bug or not.
The official directory only says "images directory is good choice", so maybe there is a better fix.

**Comment by LekoArts** [comment]
Thanks for the investigation @Talaxy009, you're correct. The props are hashed here: https://github.com/gatsbyjs/gatsby/blob/f595257c51fed9ab18dc558e4b85188853eb0e15/packages/gatsby-plugin-image/src/node-apis/parser.ts#L75-L96

Since they are the same it'll be the same murmurhash for the .json files. It's a bug that we should fix :)
