### ISSUE TITLE
Latest gatsby fails to compile

### ISSUE THREAD

**Issue by floofydoug** [gatsbyjs/gatsby#37294]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I cannot start `gatsby develop`

### Reproduction Link

n/a

### Steps to Reproduce

1. gatsby init
2. gatsby new test
3. gatsby develop

### Expected Result

starts project

### Actual Result

```
dyld: lazy symbol binding failed: Symbol not found: _pthread_jit_write_protect_supported_np
  Referenced from: /Users/{{USER_REDACTED}}/{{blog_name_redacted}}/node_modules/sharp/build/Release/../.././vendor/8.13.3/darwin-x64/lib/libvips-cpp.42.dylib
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _pthread_jit_write_protect_supported_np
  Referenced from: /Users/{{USER_REDACTED}}/{{blog_name_redacted}}/node_modules/sharp/build/Release/../.././vendor/8.13.3/darwin-x64/lib/libvips-cpp.42.dylib
  Expected in: /usr/lib/libSystem.B.dylib
  ```

### Environment

```shell
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 108.0.5359.124
    Safari: 15.6.1
  npmPackages:
    gatsby: ^5.3.2 => 5.3.2
    gatsby-plugin-image: ^3.3.2 => 3.3.2
    gatsby-plugin-manifest: ^5.3.1 => 5.3.1
    gatsby-plugin-sharp: ^5.3.2 => 5.3.2
    gatsby-source-filesystem: ^5.3.1 => 5.3.1
    gatsby-transformer-sharp: ^5.3.1 => 5.3.1
  npmGlobalPackages:
    gatsby-cli: 5.3.1
```

### Config Flags

no

**Comment by teachdugsimt** [comment]
I have same issue.

**Comment by OlBal** [comment]
I am also having the same issue. Commenting out the offending plugins in my `gatsby-config.ts ` file gives me:
```
Error 610: GraphQLDocumentError: Unknown type "ImageSharpFluid".
    at undefined:2:55
Error 613: GraphQLDocumentError: Unknown type "ImgixFixed".
    at undefined:2:32
    ```

**Comment by tyhopp** [comment]
This appears to happen in the latest version of sharp (v0.31.2), see https://github.com/lovell/sharp/issues/3438.

Temporarily can you try using [resolutions](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/) to force usage of the prior sharp (v0.31.1) to see if this makes it work on your machines? I'm not able to reproduce on my macOS machine since it's on the latest version

**Comment by tyhopp** [comment]
Following up on this, we recommend the same as https://github.com/lovell/sharp/issues/3438#issuecomment-1342722874.

Since the issue only seems to happen on macOS 10.x, and macOS 10.x is end of life as of 3 months ago, we will not pin sharp so we don't block future version bumps.

For anyone running into this then on macOS 10.x I'd recommend either upgrading to macOS 11 or pinning to older Gatsby versions (which should be `gatsby-plugin-sharp@5.2.0` and `gatsby-transformer-sharp@5.2.0`).
