### ISSUE TITLE
Default starter package-lock.json has outdated dependency versions

### ISSUE THREAD

**Issue by raffishquartan** [gatsbyjs/gatsby#37316]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Following the steps of [Part 1 of the Gatsby Tutorial](https://www.gatsbyjs.com/docs/tutorial/part-1/) with Gatsby 5.3.3 creates a gatsby site that fails to deploy on Gatsby Cloud. This is because the generated package-lock.json file is out of date.

### Reproduction Link

https://github.com/gatsbyjs/gatsby

### Steps to Reproduce

Using gatsby v5.3.3 and with node and npm set up in the WSL per the instructions for Linux in [part 0 of the tutorial](https://www.gatsbyjs.com/docs/tutorial/part-0/):

1. gatsby new - accept all default options and install no additional features
2. Push this git repository to a Github repo, and from there deploy it to Gatsby Cloud using the instructions in [part 1 of the tutorial](https://www.gatsbyjs.com/docs/tutorial/part-1/)

### Expected Result

Site builds and deploys to Gatsby Cloud per the tutorial

### Actual Result

Deployments in Gatsby Cloud fails during the install dependencies step with Gatsby Cloud raw log error messages:

16:27:12 PM: npm ERR! code EUSAGE
16:27:12 PM: npm ERR! 
16:27:12 PM: npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.

This error can be fixed locally in the Gatsby site by deleting the package-lock.json file, running npm install and then pushing the updated code to Github.

### Environment

```shell
Gatsby environment info:
System:
OS: Linux 4.4 Ubuntu 20.04.5 LTS (Focal Fossa)
CPU: (8) x64 Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz
Shell: 5.0.17 - /bin/bash
Binaries:
Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
npmPackages:
gatsby: ^5.3.3 => 5.3.3
npmGlobalPackages:
gatsby-cli: 5.3.1
```

**Comment by pieh** [comment]
At first I looked at lock files, but then after doing more checks - we will be fixing this on Gatsby Cloud side of things, we already have proposed changes to handle this problem. It's not matter of lock files - instead installation command need to be adjusted.

NPM decided to make "breaking change" in regards to behaviour of `npm ci` at some point ( https://github.com/npm/cli/issues/4998 ) which is root of the problem. We will be adjusting installation command to include `--legacy-peer-deps` on Cloud side of things.

Until the fix is finished and deployed here are 2 possible workarunds (either/or):
 - add `.npmrc` file in root of the site with following content:
   ```
   legacy-peer-deps=true
   ```
 - or set following env var - `NPM_CONFIG_LEGACY_PEER_DEPS=true`

**Comment by LekoArts** [comment]
As this is unrelated to Gatsby as the OSS project we can close this :) It'll be fixed soon on Gatsby Cloud
