### ISSUE TITLE
When using gatsby develop with JS disabled, instruct the user that the HTML for pages are not rendered on the server

### ISSUE THREAD

**Issue by savolai** [gatsbyjs/gatsby#374]
instruct users on how to get both static and dynamic site running

Re: https://github.com/gatsbyjs/gatsby-starter-documentation/issues/10#issuecomment-235993501

**Comment by KyleAMathews** [comment]
In other words, instead of not including anything for the body when rendering in the dev server, add a `<noscript>` element with a message saying something like "The Gatsby development server does not work without Javascript enabled. If you'd like to test how your site works without Javascript, first build the site 'gatsby build' and then serve the built site 'gatsby serve-build'"

**Comment by nason** [comment]
Hi @KyleAMathews, I'd like to take this on. just ran into this situation and thought I would open an issue, but its already here. I'll have a PR up shortly.

Btw, thank you for this excellent tool!
