### ISSUE TITLE
css @media queries aren't working with styled-components/Gatsby-plugin-styled-components

### ISSUE THREAD

**Issue by oklex** [gatsbyjs/gatsby#37415]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Using @media queries for responsiveness on `styled-components` + `gatsby-plugin-styled-components` doesn't work. 

### Reproduction Link

https://github.com/oklex/gatsby-styled-components-bug

### Steps to Reproduce

1. create a styled component with a media query using screen width
2. use the styled component on a page
3. change the screen width and notice that the responsive CSS is not being applied

### Expected Result

The media query css should be applied for their responsive screen width 

### Actual Result

The media query css is not being applied for their responsive screen width

### Environment

```shell
System:
    OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 18.12.1 - ~/.volta/tools/image/node/18.12.1/bin/node
    npm: 8.19.2 - ~/.volta/tools/image/node/18.12.1/bin/npm
  npmPackages:
    gatsby: 5.5.0-next.0 => 5.5.0-next.0
    gatsby-alias-imports: 1.0.6 => 1.0.6
    gatsby-plugin-google-fonts-v2: 1.0.1 => 1.0.1
    gatsby-plugin-polished: 1.0.4 => 1.0.4
    gatsby-plugin-sass: 6.3.1 => 6.3.1
    gatsby-plugin-styled-components: 6.3.0 => 6.3.0
```

### Config Flags

n/a

**Comment by tyhopp** [comment]
Hi @oklex, can you provide a more minimal reproduction so it's clear what the issue is? The current reproduction has a lot of other things going on that make it difficult to use for triage.

I created this reproduction as an example you can clone and use - https://github.com/tyhopp/gatsby-styled-components-minimal.

The index file https://github.com/tyhopp/gatsby-styled-components-minimal/blob/main/src/pages/index.js uses breakpoints with styled components and they work as expected.

Thanks!

**Comment by oklex** [comment]
Hi @tyhopp turns out this was entirely my bad - I had several problems going on on my side. Thanks for the response!
