### ISSUE TITLE
Throws error if gatsby version 4.**.* saying it requires gatsby@^5.0.0-next

### ISSUE THREAD

**Issue by dmxt** [gatsbyjs/gatsby#37483]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I did try gatsby@^5.0.0 but had too much problems with plugins so I decided to rollback to v4 for now. But for some reason, it says it's not compatible with v4 while it works perfectly fine.

```
warn Plugin gatsby-remark-images is not compatible with your gatsby version 4.25.3 - It requires
gatsby@^5.0.0-next
warn Plugin gatsby-remark-images is not compatible with your gatsby version 4.25.3 - It requires
gatsby@^5.0.0-next
warn Plugin gatsby-remark-images is not compatible with your gatsby version 4.25.3 - It requires
gatsby@^5.0.0-next
warn Plugin gatsby-remark-images is not compatible with your gatsby version 4.25.3 - It requires
gatsby@^5.0.0-next
warn Warning: there are unknown plugin options for "gatsby-remark-images": sizeByPixelDensity
Please open an issue at https://ghub.io/gatsby-remark-images if you believe this option is valid.
warn Plugin gatsby-remark-images is not compatible with your gatsby version 4.25.3 - It requires
gatsby@^5.0.0-next
warn Plugin gatsby-remark-images is not compatible with your gatsby version 4.25.3 - It requires
gatsby@^5.0.0-next
```
when running `gatsby develop` on v4

### Reproduction Link

https://github.com/dmxt/dmxt-blog

### Steps to Reproduce

1. install gatsby-cli v4
2. install `gatsby-remark-images`
3. run `gatsby develop` on a functioning gatsby template and the error will arise
...

### Expected Result

Nothing because it works just fine?

### Actual Result

Throws errors. Errors annoy me.

### Environment

```shell
`gatsby-cli: 5.4.0`
`gatsby: 4.25.3`
(it's messed up because I downgraded from v5 to v4 due to too many errors)

`npm: 8.19.2`
`node v18.12.1`
```

**Comment by LekoArts** [comment]
Hi!

If you're cloning the https://github.com/gatsbyjs/gatsby-starter-blog starter everything will be working fine. You didn't specify which errors you mean, if you mean peer dependency errors (https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v4-to-v5/#updating-community-plugins) you can use the `--legacy-peer-deps` flag for other community plugins.

You don't need to install the `gatsby-cli` to a project, it's not necessary for the site to work. You'd only install the CLI globally.

Your lock file still have the latest version of `gatsby-remark-images` in it, so the version you have installed is showing the error correctly: https://github.com/dmxt/dmxt-blog/blob/6fed0b3bf7a6df942aaa65673300ed1cb8758a6c/yarn.lock#L5949

I'd recommend using https://github.com/gatsbyjs/gatsby-starter-blog as a base and use Gatsby 5 since only this version will receive new features.
