### ISSUE TITLE
Gatsby page content not updating after a deploy that modifies page-data.json files

### ISSUE THREAD

**Issue by JamesToohey** [gatsbyjs/gatsby#37493]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Hi Gatsby team, thank you in advance.

We have a Gatsby site which is deployed using Netlify, however our users are finding that they are seeing very stale content. We've realised that no matter how long after a deployment, if a user has left our site open, they will remain on the old site.

At first we thought this was a caching issue, however I've narrowed down a replication case which will work even with caching disabled entirely.

[I found this relevant blog post from 2019](https://www.gatsbyjs.com/blog/2019-06-12-performance-improvements-for-large-sites/#gatsby-sites-are-now-more-live-) but it still feels like this is a bug?

>The new page-data.json resources are not content-hashed. This means that if a user is on the site and a rebuild occurs resulting in changed page-data.json, the user will then see that new information when they navigate to that page. However, this is only true if a page hasn't already been prefetched. We have some ideas for periodically expiring prefetched data to ensure that new changes are visible to users. Stay tuned for more on this front!

### Reproduction Link

https://github.com/JamesToohey/gatsby-data-update

### Steps to Reproduce

[Steps in README](https://github.com/JamesToohey/gatsby-data-update#readme)

### Expected Result

When navigating between pages, Gatsby should always (or periodically) inspect the data in the `page-data.json` files to see if the page content has changed, and update accordingly.

### Actual Result

Navigating between pages using Gatsby `Link` will result in content never being updated. A manual refresh is always required.

### Environment

```shell
System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1 Pro
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.6.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.1.0 - /opt/homebrew/bin/npm
  Languages:
    Python: 3.10.7 - /Users/jamestoohey/.pyenv/shims/python
  Browsers:
    Chrome: 109.0.5414.87
    Safari: 16.1
  npmPackages:
    gatsby: ^5.4.0 => 5.4.0
```

**Comment by JamesToohey** [comment]
[I've just found this](https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-link/#handling-stale-client-side-pages)

>However, if the page has previously loaded, it will not re-request app-data.json. In that case, the hash comparison will not occur and the previously loaded content will be used.

Is this expected behaviour? If so, is there a ways I can manually perform this hash comparison?

**Comment by LekoArts** [comment]
Hi!

Thanks for the issue! How it's currently working is expected behavior. In our loader we have a bunch of maps that keep track of a couple of things, including visited pages: https://github.com/gatsbyjs/gatsby/blob/0017375e857c929e97a19853db01188c6702df25/packages/gatsby/cache-dir/loader.js#L113-L143

We do this as requesting those files all the time is expensive. The `app-data.json` is only changing when something that goes through webpack changes, e.g. a React component. If you have data updates or content updates, that hash won't change.

So yes, one of the blog posts you quoted has one possible idea for this (periodically clear that cache) but there weren't many reports on this over the years so it got forgotten really. The hard question with cache invalidation in that instance is then e.g. what timeframe is appropriate, would there be triggers?

To answer your last question, no, there's currently no way to force this update. Maybe you could build something custom to tell people that the page has been updated and they could reload with a button. But yeah, the behavior you probably want I'd consider a feature request which you can open here: https://github.com/gatsbyjs/gatsby/discussions/categories/ideas-feature-requests

Hope that helps with context!

To end with a fitting quote:

> There are only two hard things in Computer Science: cache invalidation and naming things.
> -- Phil Karlton

**Comment by JamesToohey** [comment]
Hi @LekoArts 

Thanks so much for the detailed response. I'll go away and have a think about how we'd solve this for our case and try some things.

I'll come back with any solutions we find that work.

James

**Comment by JamesToohey** [comment]
In simple terms we ended up doing the following:

1. Generate a cache key every time we build the site, place it in a public directory as a text file
2. Replace all instances of `Link` with a new component which does not prefetch (we will add prefetching to this later). It uses Gatsby `navigate` internally.
3. In a useEffect in our top level component, we check the cache key and compares it with localStorage, saving it if it is new
4. If the cache key has changed, we use React Context to set a global variable to inform our `Link` component that it should use `window.location.assign` rather than `navigate` the next time the user navigates to a new page

We realise there are performance tradeoffs here, however they're **definitely** worth it rather than showing users outdated content.

>There are only two hard things in Computer Science: cache invalidation and naming things.

Would a new build of the site not be a good time to invalidate cache? We can't think of a reason except that there is a risk that some pages haven't changed and may remain cached, which we're not concerned about.
