### ISSUE TITLE
Security: change all insecured http to https 

### ISSUE THREAD

**Issue by dmxt** [gatsbyjs/gatsby#37604]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

On this repository, I noticed many unsecured HTTP links. 

For example, this link contains HTTP:

`itemType="http://schema.org/Article"`

It should be changed to HTTPS:

`itemType="https://schema.org/Article"`

And then test if the link work.

There are many instances of `http` in this repository, `gatsbyjs/gatsby`, and it should be fixed. A few years ago, http got compromised, and there was a big warning site insisting everyone certify their site to HTTPS.

<img width="828" alt="Screenshot 2023-02-01 at 6 22 13 PM" src="https://user-images.githubusercontent.com/3248782/216189963-65c1b623-999c-4f2c-9e10-854f56bfb91c.png">

https://www.cloudflare.com/learning/ssl/why-is-http-not-secure/

---

### Reproduction Link

https://github.com/gatsbyjs/gatsby

### Steps to Reproduce

Not relative

### Expected Result

Secured HTTPS link everywhere.

### Actual Result

Some links are unsecured HTTP

### Environment

```shell
Not relative
```

**Comment by LekoArts** [comment]
Hi, thanks for the issue.

This is not something we need to fix since all modern browsers will redirect to HTTPS or have an option to enforce this. The example you gave also is just microdata, not something people will click on. For example `localhost` URLs don't need to be HTTPS, and so on.

This repository is a couple years old, there will be links with `http` yes but there's no need to change them. All newer docs/links use their current format which is now almost always `https`.
