### ISSUE TITLE
chore(security): upgrade resolve-url-loader to 3.1.5 to avoid security issues

### ISSUE THREAD

**Issue by mohamedMok** [gatsbyjs/gatsby#37663]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

In the relase of `@gatsby/gatsby-plugin-sass` version `5.25.0` (the latest). 
The version used for `@resolve-url-loader` is the `3.1.4` which contains a security issue due to `loader-utils` 

`Prototype pollution in webpack loader-utils`

### Reproduction Link

https://github.com/adeo/mozaic-design-system

### Steps to Reproduce

1- Install `@gatsby/gatsby-plugin-sass` version `5.25.0` 
2- Check `yarn.lock` or  `package-lock.json` the installed version for  `@resolve-url-loader`

### Expected Result

Upgrade the version of  `@resolve-url-loader` and release a new fix `5.25.1` 

### Actual Result

Version with security issues

### Environment

```shell
System:
    OS: macOS 11.7
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.10.0 - ~/.nvm/versions/node/v16.10.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.24.0 - ~/.nvm/versions/node/v16.10.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 109.0.5414.119
    Firefox: 108.0.1
    Safari: 16.0
  npmPackages:
    gatsby: ^4.25.4 => 4.25.4
    gatsby-plugin-google-analytics: ^4.24.0 => 4.25.0
```

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

While those audit messages might seem scary they are almost always irrelevant in the context of Gatsby as it's a build tool. So there is nothing to "fix" as the warning is not relevant.

Gatsby creates static assets and runs everything at build time and not during runtime. `npm audit` is designed for runtime / Node apps so it flags issues that can occur there. This means that almost every "vulnerability" report we receive are false positives. While in principle Gatsby can also have vulnerabilities you need to make sure that it's relevant to Gatsby before reporting it. For example a "Regex DDOS attack" can never be a real vulnerability for a development-time tool. If you want to override/update a transitive dependency you can use [yarn resolutions](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/).

You can also read [npm audit: Broken by Design](https://overreacted.io/npm-audit-broken-by-design/) to learn more about this.

If you know that a vulnerability affects Gatsby because you understand what the vulnerability is, please report it [through our security document](https://github.com/gatsbyjs/gatsby/blob/master/SECURITY.md). Thanks!

**Comment by LekoArts** [comment]
`gatsby-plugin-sass` is already using the latest version. You'll need to update to the latest version.

**Comment by mohamedMok** [comment]
Many thanks @LekoArts for your feedback! You rock! 
Can you please give me the latest version `5` with the patch please
