### ISSUE TITLE
Gatsby parallel query running error

### ISSUE THREAD

**Issue by ericphungg** [gatsbyjs/gatsby#38076]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

yarn dev works as expected but yarn build does not and returns this error 
<img width="788" alt="image" src="https://github.com/gatsbyjs/gatsby/assets/129699557/7e1b8f24-9ee4-40db-a4ab-d82d7e50dd6a">

### Reproduction Link

N/A

### Steps to Reproduce

1. clone repo
2. yarn install
3. yarn build
...

### Expected Result

successful build

### Actual Result

failed build

### Environment

```shell
System:
    OS: macOS 12.6.4
    CPU: (8) arm64 Apple M1 Pro
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.15.0/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
  Browsers:
    Safari: 15.6.1
  npmPackages:
    gatsby: ^4.19.2 => 4.24.8
    gatsby-plugin-brotli: ^2.0.0 => 2.1.0
    gatsby-plugin-force-trailing-slashes: ^1.0.5 => 1.0.6
    gatsby-plugin-gatsby-cloud: ^4.19.0 => 4.24.1
    gatsby-plugin-google-tagmanager: ^4.19.0 => 4.24.0
    gatsby-plugin-image: ^2.19.0 => 2.24.0
    gatsby-plugin-manifest: ^4.19.0 => 4.24.0
    gatsby-plugin-netlify: ^3.0.0 => 3.14.0
    gatsby-plugin-offline: ^5.19.0 => 5.24.0
    gatsby-plugin-prismic-previews: ^5.2.8 => 5.2.10
    gatsby-plugin-react-helmet: ^5.19.0 => 5.24.0
    gatsby-plugin-robots-txt: ^1.7.1 => 1.8.0
    gatsby-plugin-root-import: ^2.0.8 => 2.0.9
    gatsby-plugin-sass: ^5.19.0 => 5.24.0
    gatsby-plugin-sharp: ^4.19.0 => 4.24.0
    gatsby-plugin-sitemap: ^5.19.0 => 5.24.0
    gatsby-plugin-svgr: ^3.0.0-beta.0 => 3.0.0-beta.0
    gatsby-source-filesystem: ^4.19.0 => 4.24.0
    gatsby-source-google-spreadsheets: ^3.0.8 => 3.0.8
    gatsby-source-prismic: ^5.2.9 => 5.2.10
    gatsby-transformer-sharp: ^4.19.0 => 4.24.0
  npmGlobalPackages:
    gatsby: 5.8.1
```

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment]
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!
