### ISSUE TITLE
Redirects and Headers stopped working on Netlify (and work again in gatsby 5.12.12 / adapter 1.0.4)

### ISSUE THREAD

**Issue by laurenskling** [gatsbyjs/gatsby#38752]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

My sites weren't processing things like headers and redirects anymore since Dec 7th, between 3:13PM and 4:09PM (GMT+1)

I thought it was netlify/plugin-gatsby 3.8.0 but it's probably gatsby@5.12.11 or .12 or something that did it.

Nuking my yarn.lock and installing gatsby 5.12.12 (I was running 5.12.3), gatsby-adapter-netlify 1.0.4 (from 1.0.0) made redirects and headers work again.

Just wanted to throw it out there for others who might have their clients calling that redirects aren't working anymore 🥲 

### Reproduction Link

https://gatsby.dev/reproduction

### Steps to Reproduce

1. have gatsby 5.12.3
2. build a site with redirects
3. they dont work
4. installed @latest
5. it works.
...

### Expected Result

Things not breaking

### Actual Result

Things breaking

### Environment

```shell
System:
    OS: macOS 13.6.1
    CPU: (8) arm64 Apple M2
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.2 - /var/folders/50/3fndm5d13gs_kr96nwxpxd9c0000gn/T/yarn--1702407952305-0.35108371319464915/node
    Yarn: 1.22.19 - /var/folders/50/3fndm5d13gs_kr96nwxpxd9c0000gn/T/yarn--1702407952305-0.35108371319464915/yarn
    npm: 9.8.1 - /usr/local/bin/npm
  Languages:
    Python: 3.10.9 - /usr/local/bin/python
  Browsers:
    Chrome: 120.0.6099.71
    Safari: 17.1
```

**Comment by pieh** [comment]
This is probably related to https://github.com/gatsbyjs/gatsby/pull/38745 which was released in timeframe you reported.

Did the builds with not working redirects perhaps had warning line like that?
> gatsby-adapter-netlify@X is not compatible with your current Gatsby version

Looking at the code I do see that it would then skip trying to use adapter completely if manually managed adapter version is deemed incompatible with used gatsby version and that would make it so nothing tries to handle redirects.

I do think it probably should discard used version when deemed in compatible and try to install compatible one to avoid this or maybe just fail the build with informative message to avoid those broken deploys - but before doing any improvements there, it would be good to confirm my assumption about how that happened and wether warning did happen in build logs

**Comment by laurenskling** [comment]
Yes I now see it as well:

```4:11:32 PM: warning gatsby-adapter-netlify@1.0.0 is not compatible with your current Gatsby version 5.12.3 - Install gatsby-adapter-netlify@1.0.3 or later.```

I did not spot this earlier, there's a lot in my logs ;) 

Yeah, I would really wished this was a crash, not a warning. Now my builds were inacurate for 7 days, because I have some business logic that rely on the redirects.

**Comment by pieh** [comment]
I will make it crash, but of course this would only applicable to new gatsby versions and can't really make already released versions handle it properly.

After few thoughts - discarding user managed adapter version and installing "compatible" one is not good, because it would lose any adapter options that user specified, so failing the build is the best solution here

**Comment by laurenskling** [comment]
Yeah in my opinion crashing (with a good message) and letting me fix it is always best. It's build time. 

You cannot allow 1.0.0-1.0.3 in that manifest file? That would fix it as well right?

**Comment by pieh** [comment]
> You cannot allow 1.0.0-1.0.3 in that manifest file? That would fix it as well right?

I can and will update it to allow those versions (was doing some testing and `>=1.0.0 <=1.0.3` is valid version selector not only for verifying version range, but also as argument for `npm install gatsby-adapter-netlify@">=1.0.0 <=1.0.3"` which would be used for "zero-conf" scenarios)

But that will be part of changes to break the build for incompatible versions by default to prevent potentially broken deploys like ones you reported (there will be escape hatch to continue the build with things as-is but this is something that user will have to opt into meaning they acknowledge gatsby doesn't want to allow that and basically user become responsible for potential problems caused by "incompatibility")

**Comment by pieh** [comment]
Actually - I will split things - I wasn't sure initially if installation will continue to work with code as-is (just knew it could work overall, but possibly changes were needed). As I looked into adjusting the behavior it was clear I will need to spend quite a bit of time on testing new behavior in bunch of scenarios - so at least for now I could do quick relaxation of compatible version to help with the issue faster and improve the logic as next step.

So https://github.com/gatsbyjs/gatsby/pull/38758 will update just the manifest
