### ISSUE TITLE
Issue with page-transitions

### ISSUE THREAD

**Issue by gagan0723** [gatsbyjs/gatsby#3880]
## Description
Using page-transitions, clicking on Gatsby which links to ```localhost```, the transition is triggered even on index route.

![peek 2018-02-06 23-15](https://user-images.githubusercontent.com/6944095/35887524-d24952d0-0b94-11e8-8bad-0cc2bc020253.gif)

### Environment

Gatsby version: 1.9.169
Node.js version: v8.9.4
Operating System: ubuntu 16.04 LTS

### Expected behavior

When the user is on index route the transition must not trigger.

### Steps to reproduce

1\. ```gatsby new demo```

2\. Install dependencies and edit files as per https://github.com/gatsbyjs/gatsby/tree/master/examples/using-page-transitions.

3\. Run ```gatsby develop``` or ```gatsby build && gatsby serve```.

**Comment by calcsam** [comment]
Why shouldn't it trigger? The alternative is to click on the Gatsby icon and *nothing* happens, which feels broken -- "I clicked and the page isn't listening to me!!"

**Comment by KyleAMathews** [comment]
I agree with @calcsam — it's not obvious that the page transition shouldn't happen again. It'd depend on your project whether running the transition or not again makes sense.

Since page transitions require some custom code, you can add exceptions for transitions in your personal code. I'd take a PR to the example as well that disabled transitions when someone clicks on a link pointing to the current path.
