### ISSUE TITLE
Use createNodeId for gatsby-source-contentful

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#4016]
People think they can query contentful nodes with the Contentful IDs but get tripped up because sometimes they can't due to needing to left-pad ids starting with numbers. Let's just make all IDs UUIDs to prevent that confusion https://github.com/gatsbyjs/gatsby/issues/4001

**Comment by mxlje** [comment]
Maybe i‘m missing something, how would we see those IDs? And how would they be persistent?

Right now I have to run IDs through the `fixId` function before I can actually use them, but at least it explicitly references the entry by its canonical (contentful) ID in the code.

**Comment by pieh** [comment]
@mxlje  use `contentful_id` field instead of `id` field

**Comment by anjawaldbauer** [comment]
I might be mistake here, but I think the use of `contentful_id` is limited to the case where you only have one locale. When you use the `contentful_id` on a localized node, i.e. where the `id` ends in `__de` (for the `de` localization) you will retrieve the default - e.g. English - node instead of the German (`de`) node.

**Comment by pieh** [comment]
This was already done in #3807 and later updated in #5167
