### ISSUE TITLE
Invariant Violation: Unknown Field allUtopianPost

### ISSUE THREAD

**Issue by codingdefined** [gatsbyjs/gatsby#4049]
## Description

When created a new Plugin gatsby-source-utopian, and installed it using the npm getting error as "Invariant Violation: Unknown Field allUtopianPost", when tried to use allUtopianPost as

```
export const query = graphql`
  query IndexQuery {
    allUtopianPost {
      totalCount
    }
  }
`;
```

The source plugin is in https://github.com/codingdefined/gatsby-source-utopian

### Environment

Gatsby version: 1.9.153
Node.js version: 8.9.3
Operating System: Windows 10

### File contents (if changed):

`gatsby-config.js`: 

```
module.exports = {
  plugins: [
    {
      resolve: 'gatsby-source-utopian',
      options: {
        user: 'codingdefined',
      },
    },
  ],
};
```

**Comment by KyleAMathews** [comment]
Can you verify in your plugin that it's correctly downloading data? Also, what do you see in GraphiQL?

**Comment by codingdefined** [comment]
@KyleAMathews Yes the data is there in nodeStr.  And below thing I see in GraphiQL

![image](https://user-images.githubusercontent.com/13746289/36268287-1832a6da-129c-11e8-828b-2a01969e20a5.png)

**Comment by pieh** [comment]
Examining code for that source plugin - https://github.com/codingdefined/gatsby-source-utopian/blob/master/gatsby-node.js - you have async operation but you don't return promise so gatsby will move on with build and not wait for Your data before building schema. 

Instead of empty return try returning promise you get when you run `utopian.getPostByAuthor(...)`

**Comment by codingdefined** [comment]
@pieh Thanks a lot, it worked.
