### ISSUE TITLE
Deleted nodes are still in the data graph when developing

### ISSUE THREAD

**Issue by lourd** [gatsbyjs/gatsby#4176]
## Description

When deleting items from the end of a list in yaml or json, using either the gatsby-transformer-yaml and gatsby-tranformer-json plugins, they aren't removed from the data graph.

### Environment

Gatsby version: 1.9.206

### Steps to reproduce

See [this repo](https://github.com/lourd/gatsby-node-deletion-bug)

**Comment by KyleAMathews** [comment]
Oh interesting! Yeah, this would be the case. So these transformers would need to track the new nodes they create the second time around against those they made the first time and delete any nodes  that didn't get created again. `gatsby-source-filesystem` does this but derived nodes won't. If a File node is deleted, we do delete any transformed child nodes. But in this case, only the transformers would know if a transformed node is deleted or not.

I'll put together a PR real quick.

**Comment by KyleAMathews** [comment]
(Thanks for the nice reproduction as well! Makes it very easy to fix)

**Comment by lourd** [comment]
👍For sure, you're welcome

**Comment by KyleAMathews** [comment]
Hmmm ok, this is a deeper flaw than I thought. When a node is changed or deleted we should always recursively remove previously created children nodes as all of them are "dirty" due to their being derived from a now changed ancestor node.

I'll modify deleteNode to be recursive + change the createNode behavior that when there's a previously created node with the same ID, that before recreating the old node with the new data, we'll remove all descendant nodes.

**Comment by KyleAMathews** [comment]
Oh and fun fact about why I've never seen this before. My Vim install is setup to write new changes to a temp file, delete the old copy, and then move the temp file over. For reasons I now forget 🤔 but in any case, Gatsby has always worked perfectly in this regard for me as it'd first delete the old node then recreate it for me :-D

**Comment by lourd** [comment]
Hahaha, that is one hell of a masking effect.

Yeah, I had a hunch the solution would be lower than the transformer plugins. Sounds like a good plan of attack to me!

**Comment by lourd** [comment]
That was quick, nice work!
