### ISSUE TITLE
[v2] can't override predefined rules via `modifyWebpackConfig`

### ISSUE THREAD

**Issue by nihgwu** [gatsbyjs/gatsby#4179]
## Description

We are using `webpack-merge` to modify the webpack config in v2, but it's a bit limited.
According to the `webpack-merge`'s mechanism, new defined rules will be always concatenated to the end of the predefined rules 
```
[
  {
	test: /\.jsx?$/,
	exclude: [something else],
  },
  {
	test: /\.svg$/,
	use: [
	  {
	    loader: 'svgo-loader',
	  },
	],
  }
]
```
for the first one, I want to change the default behavior for js files, for the second one, I want to use custom loaders for svg files, so I have to add exclude to images test, but all my new rules are appended instead of override, I read about the source code of `webpack-merge`, and end up using `replaceWebpackConfig` to achieve my purpose.

**Comment by nihgwu** [comment]
@KyleAMathews what about using `https://github.com/kolodny/immutability-helper` to modify webpack config, then you can take full control of it

**Comment by jquense** [comment]
You can already take full control of it in the API by getting and manually modifying the parts you want. You also usually don't have to modify existing rules, appending or prepending another rule with the same test (such as in svg example) works fine. In general tho editing the existing loaders is not _supposed_ to be super easy, because changing them will likely break gatsby.

**Comment by nihgwu** [comment]
@jquense but how can I apply another rule for `svg`?
In my case, I have a custom loader for svg files, to turn svg file to a function, so it's `use: ['myloader', 'svgo-loader']`, how can I achieve this via `setWepackConfig`? I thought I could override the default rules for `images` to exclude my svg files, I tried one whole night but failed, I also tried to use `merge.smart` instead of `merge`, but there are checks before overriding over appending,so I end up using `replaceWebpackConfig` to modify the webpack config.
BTW, you said `prepending` rules, how to do that? I do think we need the ability to override array values instead of extending them

**Comment by nihgwu** [comment]
Also I think `replaceWebpackConfig` should be the last option we have to take, and how can we solve the problem I mentioned in #4182 via `setWepackConfig`

**Comment by jquense** [comment]
> In my case, I have a custom loader for svg files, to turn svg file to a function, so it's use: ['myloader', 'svgo-loader'] 

Webpack loaders are executed in order, and you have many tests for the same thing. if you want to handle svg files special, then you don't need combine it with the existing rule, just add a new one

```js
const existingConfig = getConfig();
replaceWebpackConfig({ 
  ...existingConfig, 
  module: {
    rules: [
      { test: /\.svg$/, use: ['myloader', 'svgo-loader'] },
      ...existingConfig.module.rules,
    ]
  }
})
```

For an easier syntax using something like your immutability helper would make it simple for you.

> Regarding break gatsby, if you changes breaks gatsby, you will fail develop and build

Yeah and thats generally frustrating for users, we don't want make breaking gatsby in confusing ways something that's really simple to do. I think you should (and can) be able to make those changes, but it not being "quick and easy" is an important signal that you are in dangerous and unknown territory

I realize that the above example is not particularly simple, and maybe we should have more examples on how to do it. Ultimately tho the goal is that most users won't have to touch webpack themselves, and that most things like that are handled via gatsby plugins. Webpack's API is not particularly amenable to since api abstractions on top of it (at the moment anyway) and so far any attempt to add something tends to limit use-cases without making the 80% cases much simpler or less error prone. The v2 "abstraction" is just a set functions that return bits of webpack's config, it relies on language level composition and overall should give folks access to all the right pieces of webpack without a new api.

**Comment by nihgwu** [comment]
You are still using `replaceWebpackConfig` to solve the svg problem, that's also the way I'm using now.
perhaps it's the **set**WebpackConfig make me thought that I can set particular rules instead of concatenating, it's actually an **extend** way, but we **set** plain value and **extend** array
What about adding a new action `updateWebpackConfig` which backed by `immutability-helper`

**Comment by nihgwu** [comment]
BTW, you still haven't answer the problem in #4182, I don't think we can solve that via `setWebpackConfig` as before because it modifies the `include/exclude` field

**Comment by jquense** [comment]
> What about adding a new action updateWebpackConfig which backed by immutability-helper

I think that would add another api for folks to learn without really providing a specific benefit over `replaceWebpackConfig`. You can use `immutability-helper` yourself with `replaceWebpackConfig`. I think you seem to be trying to avoid this api when it's designed to meet the need you have, which is specific, more advanced, merging/editing of the webpack config.

**Comment by jquense** [comment]
>  I don't think we can solve that via setWebpackConfig as before because it modifies the include/exclude field

I think thats correct, `setWebpackConfig` is not the right api for doing this, but I don't think that's a bad thing for the various reason's i've specified above.
