### ISSUE TITLE
docs/themes Needs to be better documented

### ISSUE THREAD

**Issue by ajayns** [gatsbyjs/gatsby#4236]
The theming docs for gatsby https://www.gatsbyjs.org/docs/themes/ just has a rough outline of how themes are supposed to be. It has no examples for themes or any guides on developing themes.

**Comment by igolden** [comment]
I just saw this as well - I’ve found a couple issues with good discussions that we could summarize and add into that page. 

Essentially:

- starters are basically themes 
- how to conditionally load one of multiple themes (layouts)
- config files with jay and gatsby manor 
- how to create a simple starter/theme 

Themes seem to be evolving quickly. Would be happy to help get this documented maybe with some guidance from @kyleamathews

**Comment by DamnedScholar** [comment]
The *content* of the themes documentation makes sense to me, but it doesn't match my mental idea of what a theme *is*. The category is inclusive of packages that configure full-featured blogs or galleries, which could be called themes, but it also includes packages that might provide support for services like Disqus or a sidebar feed, which I would refer to as "widgets" or "components".

Part of making a feature that people appreciate and want to help support is having a coherent idea of what the feature is supposed to achieve. It's a small thing, but if the name of a section of the documentation doesn't intuitively make sense with all that the documentation covers, that's something that might cause confusion or consternation. And I'm not just poo-pooing the existing copy without offering an alternative, because there's a common English word that already refers to a mixture of different reagents in configurations from simple classics to decadently complex concoctions. And it fits with the theme of this particular framework. What if they were called Cocktails?

**Comment by igolden** [comment]
I agree about the word Themes. Themes, in past contexts, are usually interchangeable layouts, styles, and assets. In the Gatsby context you really have to choose your theme at the beginning to forego a larger migration later. And it dictates the overall design of your pages/templates. Maybe there’s a clearer definition (and name) for this feature in the future. For them to be traditional “themes”, we’d need a way to make them more modular for devs. It’d be nice to plug and play themes in the future mid project or when it’s time to upgrade the website down the road.

Cocktails work well with the Jay Gatsby theme, though I’m not the person to ask about branding.


Just want to say Gatsby is awesome! I’d love to pull my own weight in this area if we can get some clear definitions of where themes are headed in the immediate and distant future.

**Comment by ajayns** [comment]
I had a very specific question actually. I'm working on a theme for Gatsby, which has interactive components such as forms and commenting etc which would maybe post to a server. What should I be looking at for theme development? Is gatsby-manor/ jay the project I'm looking for? @igolden @KyleAMathews

**Comment by KyleAMathews** [comment]
That doc page was written when I was still hopeful it'd get done for v1. I removed it from gatsbyjs.org but apparently more people than expected read the docs on github :-) I'll delete it as it doesn't reflect too well my current thinking nor the discussions that we've had here on github.

Starters aren't what I want themes to be. Basically what I've figured out is that the idea of "themes" don't make sense unless you have a fixed data structure. Themes need to know what data is available and in what form. Otherwise you can't switch themes or upgrade themes independent of a site's data.

So first things first, https://github.com/gatsbyjs/gatsby/issues/3344 needs to be solved. @pieh is going to working on some PRs toward that.

Then once we can define a GraphQL schema, we need a few more primitives in core. First to validate data. Imagine there's a schema for blogs. If someone is using markdown, we need a way to say they're adding data correctly — both where on the file system and the types of data they're adding to frontmatter.

Then we need a way to abstract out possible back ends and do any init work needed for those backends. Ideally a blog schema would work with markdown and any number of headless CMSs backends. Say you install a blog theme and a backend for Contentful. You'd then run some sort of init command to setup Contentful with the correct schema.

Finally we'd need a way to do schema "migrations". If we update the blog schema, we'd also need a way for backends to migrate to the new schema.

Once these are in place, we can define schemas for blogs, ecommerce, magazines, portfolio sites, etc. etc. and then make it really easy to "skin" these and try out the different skins, etc.

Thoughts?

**Comment by KyleAMathews** [comment]
Also on the need to define a data format — this is the big difference between Gatsby and systems like Jekyll and WordPress that have big theme ecosystems. Those two ship with predefined schemas (both for blogs) which means their themes can expect certain data to be available. Because Gatsby has no default structure, we can't have true themes without a new schema layer that themes can rely on.

**Comment by DamnedScholar** [comment]
@KyleAMathews So, once these things happen and themes have their own identity and function, the role that the starters currently play could be described as "themes plus data structure"?

**Comment by KyleAMathews** [comment]
Hmm kinda. "starters" are just git repos with a working Gatsby site. A starter could include a theme (every theme will probably have a starter to quickly get going with it) or it could just be a standalone site w/ gatsby plugins, etc.

**Comment by ajayns** [comment]
@KyleAMathews That sounds like a solid idea. Adding on, the gatsby-cli can have functionality to switch between/migrate themes etc, making it simple as a command. This could be a very smooth theming experience.

**Comment by KyleAMathews** [comment]
Yeah, themes would expose which data schema they're based on and the CLI would read that and give you ways to switch between themes, install new themes, etc.

**Comment by ajayns** [comment]
So what is gatsby-manor right now? I'm sorry I haven't worked on it yet, just wanted to know what it does for theming? @KyleAMathews

**Comment by nodox** [comment]
@KyleAMathews thanks for the CC. Happy to make a PR adding Gatsby Manor and Jay as the unofficial community driven solution to themes in Gatsby if you or the community would find it useful.

Disclaimer: I'm the maintainer of Gatsby Manor and Jay.

@ajayns If you want to focus on theme development for Gatsby then I would encourage you to contribute to the Gatsby Manor project. Our [docs](https://www.gatsbymanor.com/docs/tutorials/theme-development) will guide you on how to build a theme that is compatible with the `gatsby-jay` tool. 

As for the desired features you mentioned, Jay takes care of downloading themes to your project, setting an active theme, and also switching between themes once you've decided its time to change. Upgrades are still an area of active development, might be clearer when more people start using our themes.

The future of Gatsby Manor and Jay is going to act similar to `npm` and the `npm registry`.  On the next release, Jay will act as retrieval and bootstrapping tool. In our registry, each theme will have all the necessary Gatsby specific config (`gatsby-node.js`, `gatsby-config`, components, styles) needed to apply the desired functionality. 

For example, if a user wanted to start an ecommerce store, they would use jay to install a ecommerce theme with all the necessary structure in place to drive the store with Gatsby. And after  collaboration with @stefanjudis from contentful, we are also going to add the ability to specify the data sources that feed your theme. Our initial work can be seen in this [PR](https://github.com/gatsbymanor/gatsby-jay-registry/pull/2). Also this means our current docs will be updated soon. 

Gatsby is a wonderful project with tons of ongoing work. Themes are important to the community so we've decided to provide a solution to that now, while Kyle addresses the immediate needs of Gatsby. As we continue to grow as a stable community driven solution to theming with Gatsby, we hope to someday be the officially supported solution to Gatsby themes. 

@igolden @DamnedScholar and everyone else if this sounds interesting send me questions. I'm happy to talk more in-depth on the present and future of the Gatsby Manor + Jay project if its of interest. We're also looking for contributors!

I hope this helps. ☺️
