### ISSUE TITLE
has gatsby-node.js changed on build?

### ISSUE THREAD

**Issue by uttrasey** [gatsbyjs/gatsby#4249]
## Description

gastby-node.js updated caching issue. I have a very simple gatsby-node file which delegates out to several other files. Those files change often, `gatsby-node.js` changes super rarely.

It looks like something is checking to see if things are diffferent by just checking gatsby-node.js only? 

Is there a way to do this better?

**Comment by uttrasey** [comment]
Just to add that my workaround for this has been to `touch` that file when restarting

**Comment by m-allanson** [comment]
The code that makes this check is [here](https://github.com/gatsbyjs/gatsby/blob/82867ee4fe2cafc08345035201ba44f7b421ab25/packages/gatsby/src/bootstrap/index.js#L90-L126). 

Currently there's no way for Gatsby to know which files your `gatsby-node.js` depends on. Are you able to create [locally defined plugins](https://www.gatsbyjs.org/docs/plugins/#locally-defined-plugins) to handle your use case?

Maybe the checking code should be expanded - where there are local plugins, instead of just hashing their `package.json` version number, instead Gatsby could hash the contents of the whole plugin directory.

That means you could create a local plugin (structured how you like), and the cache would be recreated when any file in the plugin was changed.

**Comment by KyleAMathews** [comment]
Yeah, happy to take PRs improving this. Just hashing the whole plugins directory seems like a reasonable improvement that's still light-weight.

**Comment by uttrasey** [comment]
Cool local plugins sounds like the way. I occasionally share some code between gatsby-xxx logic and the app but can live those edge cases for now.

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
