### ISSUE TITLE
Tutorial-4: make steps more explicit to avoid error

### ISSUE THREAD

**Issue by rohancragg** [gatsbyjs/gatsby#4257]
I experienced a problem with https://www.gatsbyjs.org/tutorial/part-four/

I followed up to the first `gatsby develop` but I got:

```
info bootstrap finished - 4.257 s
error Class constructor ProvidePlugin cannot be invoked without 'new'

```
This was entirely my error. I had not first changed directory into the new `tutorial-part-four `folder before executing the npm install for glamor!

Perhaps the tutorial could be more fool-proof and instruct explicitly people to  change directory.

This references a problem I originally reported in Discord channel.
It was suggested that this be added to the Documentation Project...

**Comment by m-allanson** [comment]
@rohancragg I've updated the tutorial which you can see linked above. Any feedback welcome!

`gatsby develop` should normally warn you when it can't find a gatsby site, so I wonder if your issue was caused by something else? If you're able to write up steps to reproduce your error, maybe we can improve how Gatsby is handling unexpected cases.

**Comment by fk** [comment]
Oups, sorry for merging so quickly. :-/
Please let us know if #4259 looks good to you @rohancragg!
