### ISSUE TITLE
Support hot re-running of fragments

### ISSUE THREAD

**Issue by axe312ger** [gatsbyjs/gatsby#4268]
## Description

Fragments are currently not watched while developing. This makes working with their GraphQL queries in subfragments painful since it requires to delete the `.cache`folder for every change.

### Steps to reproduce

1\. Create a Fragment which is included in another GraphQL query

2\. `gatsby develop`

3\. Open page

4\. Change query in Fragment

5\. Switch to browser

### Actual result

Fragment result stays the same

### Expected behavior

Fragment query should be reresolved based on the changes.

### Example

Fragment: https://github.com/gatsbyjs/gatsby/blob/master/examples/gatsbygram/src/components/post.js#L136-L138
Parent query:
https://github.com/gatsbyjs/gatsby/blob/master/examples/gatsbygram/src/pages/index.js#L216-L217

### Environment

Gatsby version: v1
Node.js version: all
Operating System: all

**Comment by KyleAMathews** [comment]
Yes! This totally needs done as it makes using fragments kind of a drag otherwise.

The tricky part about watching fragments is they can be used in multiple queries whereas page queries are only used on the pages for that component.

The algorithm would be roughly:

1. detect a file with a fragment changed
2. extract the fragment name
3. scan page queries for which ones used the fragment (we're not storing that right now so this would also need to be stored — right now we just store the processed query from relay-compiler which already has the fragment added in. We'd just need to start tracking internally the "raw query" string)
4. Invalidate all pages that use the fragment and re-run their query.

**Comment by KyleAMathews** [comment]
@pieh it'd be cool to do this still.
