### ISSUE TITLE
[v2] Support Graphql queries in npm package / node_modules

### ISSUE THREAD

**Issue by jbolda** [gatsbyjs/gatsby#4322]
As another layer of abstraction, it would be great to support templates and/or graphql fragments in npm packages as originally noted [here](https://github.com/gatsbyjs/gatsby/issues/2662#issuecomment-368198729) in #2662 . This would require extracting graphql queries from node_modules. The low hanging fruit is to support extracting queries from any "components" specified in `createPage`, but eventually supporting fragments would be nice as well.

Tangentially related is that gatsby would need to babel templates as well to deal with the graphql queries nicely. This is already planned in #3870 5).

**Comment by KyleAMathews** [comment]
I think this is a great idea! We'd need to evaluate how to do this in a performant way but it seems doable. I'm not going to make this a blocker for v2's release (it can go in at any time since it's not a breaking change) but would love someone to investigate the implications of doing this & make a PR if they'd like.

**Comment by jbolda** [comment]
Point 5) in #3870 moved to #7064 it seems for anyone following along.

**Comment by LekoArts** [comment]
fixed by https://github.com/gatsbyjs/gatsby/pull/15284

**Comment by arturhenryy** [comment]
@LekoArts not 100% sure but i think this broke my app. I use the plugin gatsby-plugin-mailchimp and in there are two example folders for the implementation of the plugin in v1 and v2. both have a file where they use a query named SiteTitleQuery. And since a few days my app does throw a error during build and dev:

```
There was an error in your GraphQL query:

Error: RelayParser: Encountered duplicate defintitions for one or more documents: each document must have a unique name. Duplicated documents:

SiteTitleQuery
```

**Comment by arturhenryy** [comment]
How can i prevent gatsby from extracting those queries now?
