### ISSUE TITLE
GraphQL Query Error (only on Build)

### ISSUE THREAD

**Issue by jarodtaylor** [gatsbyjs/gatsby#4323]
## Description

I'm unable to run `gatsby build` without getting an error. I do not get any errors when using `gatsby develop`.

### Environment

Gatsby version: 1.9.204
Node.js version: 9.5.0
Operating System: OS X Sierra (10.12.6)

### Actual result

![image](https://user-images.githubusercontent.com/362248/36884345-0f518490-1da6-11e8-8040-0858f10c59b5.png)

What's interesting is the build seems to still happen, but not without this error. The TagsPage still renders everything fine, but I'm not sure how to get rid of his error. 

### Steps to reproduce

1\. Clone: git@github.com:jarodtaylor/gatsby-starter.git

2\.` npm i`

3\. `gatsby build`

**Comment by m-allanson** [comment]
I get a 404 message for https://github.com/jarodtaylor/gatsby-starter, is it a private repo?

**Comment by jarodtaylor** [comment]
@m-allanson yeah, sorry, I forgot I still had it private. It's public, now. Thanks for taking a look! Like I said, the build actually works fine (as far as I can tell), but not without getting the error.

**Comment by m-allanson** [comment]
I'm just about to step away from the computer, so haven't fully investigated this. But I think what's happening is that Gatsby is building all your `/tags/foo` pages ok. 

But because you have a `src/pages/tag.jsx` file, it's also trying to build a `/tag/` page. This fails because there are no query results for a tag page without any tags :)

So you could check your data exists in `src/pages/tag.jsx` before using it, or move your `tag.jsx` file to the `/src/templates/` directory.

HTH!

**Comment by jarodtaylor** [comment]
@m-allanson that was exactly the problem. Thanks for the help!
