### ISSUE TITLE
[Discussion] Dedicated Gatsby Discord server

### ISSUE THREAD

**Issue by LeKoArts** [gatsbyjs/gatsby#4349]
Around 20.12.2017 Kyle and I spoke about what a dedicated Discord Server for Gatsby could look like.
I initially suggested this idea as around this time (and I think also right now in the past couple of days) the Gatsby channel on the Reactiflux server got flooded with messages from the GitHub bot. **I often see messages from users (also first time Gatsby users) getting overlooked and never answered which is pretty frustrating.**
I personally think that the advantages will balance out the downsides and it would be a huge improvement to the community on Discord.

These could be the possible channels:
- announcements (News about bigger changes, Asking for help/Informing about giving feedback to issues etc.)
- general (Talk about Gatsby. Just like the channel on Reactiflux right now)
- beginners (A dedicated "Ask for Help" channel for people starting with Gatsby)
- links-and-showcase (People can share their links to blogposts/tutorials or just their website they made with Gatsby)
- github (Only the GitHub bot creates posts there)

Advantages:
- Organized structure and smaller chance of questions getting lost (especially from beginners)
- Possibility to extend the channels, e.g. for creating a dedicated channel for Gatsby V2
- By using roles people (again: especially beginners) can easily identify other experienced users. Right now Kyle gets most of the mentions as he stands out with his colored name/role. But there are also a lot of other helpful people 👍 
- By having the "core" community there "here/everyone mentions" are a viable option to attract attention to a topic
- Overall more control over possible extensions etc.
- Own/Custom invite links (Analytics/Tracking would be possible by restricting the creation of invite links to Admins only and putting different links on different places (Docs, CLI))

Disadvantages:
- Setting up the server
- Moderating the server
- Loosing possible audience from the Reactiflux server

To weaken two disadvantages:
Setting up the server isn't that time consuming, especially with a low amount of channels and roles. I also didn't see (a lot of) spam in the Gatsby channel so I guess the "moderating" would be sending the people into the right channel for discussion.

Kyle **must** create the server. After that I'm happy to help with the setup.

I'm also happy to hear your opinions about that!

**Comment by nickmccurdy** [comment]
It's ironic that I saw this issue from a post of the Reactiflux Discord bot. 😉 

I'm biased because I spend a lot of time on Reactiflux, but in my opinion most of this could be solved by disabling the bot or moving it to another channel. There's already a lot of support on the Gatsby channel. Additionally, a lot of times beginners aren't confused with Gatsby, but with general React questions or other things that also have their own channels on Reactiflux. In other words, rather than have more Gatsby specific channels, we can keep the existing one focused. It's already possible for users to mute all channels besides Gatsby if they're uninterested in other conversations. Keep in mind that this Discord is linked from the React docs themselves, users will likely get a lot less React specific support if they move to a smaller server which could fragment support. Also Reactiflux is pretty lenient about having Gatsby content outside the Gatsby channel. Maybe this could be made more obvious in Gatsby's docs. I think having the GitHub bot in its own channel at least is a good idea though, but it could probably just be disabled in favor of people linking issue. I'm curious what Kyle thinks since he spends a lot of time in the Gatsby channel. 😄

**Comment by jlengstorf** [comment]
I'll second @nickmccurdy on this: I worry that splitting away from the Reactiflux instance is adding an extra place for people to check, and removes the ability to point non-Gatsby questions to the appropriate channel (e.g. #react).

Is there a way to change the GitHub bot so it posts a daily digest instead of every issue? That could be a way to reduce noise without removing the signal entirely.

If not, it could be worth experimenting with turning it off to see if engagement in the #gatsby channel increases and/or engagement in issues changes.

**Comment by LeKoArts** [comment]
> I'm biased because I spend a lot of time on Reactiflux, but in my opinion most of this could be solved by disabling the bot or moving it to another channel.

You'd solve the problem with the bot by disabling it. I don't think that's a good solution at all. I didn't ask the admins of Reactiflux but I guess it's not their intention to create extra channels for bots. Because then everyone wants it and the channel overview gets unclear.
And I don't want the bot to be removed as it's sometimes helpful.

> Additionally, a lot of times beginners aren't confused with Gatsby, but with general React questions or other things that also have their own channels on Reactiflux. [...] Keep in mind that this Discord is linked from the React docs themselves, users will likely get a lot less React specific support if they move to a smaller server which could fragment support.

The Gatsby Discord server would be about Gatsby and not React. The problem you describe already got solved by a lot of other communities, e.g. Discord.js (Javascript Framework for Discord Bots) links websites/Discord servers about Javascript as they don't want to give support for general JS questions. You'd simply link the Reactiflux server. If the person already joined it he/she just needs to press **Ctrl+K**.
I don't understand what you mean with your second sentence. Why would a Gatsby server fragment support? People joining the Reactiflux server via React Docs join it because of React, not Gatsby.

> Also Reactiflux is pretty lenient about having Gatsby content outside the Gatsby channel.

This also applies to other topics. It's no use to actively force people into channels just because topics overlap.

> but it could probably just be disabled in favor of people linking issue.

Not every person on GitHub owns a Discord account.

> There's definitely an issue of mention spam to be honest, but this can be improved with moderation

How? People who would be willing to get pinged instead (as they're some sort of "Helper" etc.) can't be mentioned as they have no specific role. As I said: With our own structure this would be solved in 5 seconds.

-----------

> I worry that splitting away from the Reactiflux instance is adding an extra place for people to check, and removes the ability to point non-Gatsby questions to the appropriate channel (e.g. #react).

Creating an own server implies that the channel would be removed or disabled with a link to the server. As mentioned above: The problem of pointing users to other channels can be solved by just linking to it. After clicking the link you instantly join the server. If you're already there you'd just need to use **Ctrl+K** to find it. Discord and its interface allows it to easily interact with more than just one server.

> Is there a way to change the GitHub bot so it posts a daily digest instead of every issue? That could be a way to reduce noise without removing the signal entirely.

Webhooks trigger these messages. So no, I don't think that's possible.

-----------

You didn't react to the advantages I mentioned so I'd also be interested in your opinion about that.

**Comment by nickmccurdy** [comment]
> You'd solve the problem with the bot by disabling it. I don't think that's a good solution at all. I didn't ask the admins of Reactiflux but I guess it's not their intention to create extra channels for bots. Because then everyone wants it and the channel overview gets unclear.
And I don't want the bot to be removed as it's sometimes helpful.

If it were my project and channel I'd personally just disable the bot, it doesn't seem to be used often (from my limited experience) especially since the GitHub Issues here are active. But I'd like to know what Kyle thinks.

> I don't understand what you mean with your second sentence. Why would a Gatsby server fragment support? People joining the Reactiflux server via React Docs join it because of React, not Gatsby.

Sorry I was being a bit unclear, my concern is more about the number of people in the server to provide support. While I'm sure some Gatsby users would prefer to not see the other channels of Reactiflux (and they have the option to mute them), moving to another server would reduce the number of people that could help in the gatsby rooms overall. Speaking more specifically about React, someone new to Gatsby may assume that React is a part of Gatsby that isn't used for anything else, so they may not know to switch to another server like Reactiflux if they need help designing React components. By keeping it in Reactiflux, there will be more React devs that could offer help even if they don't know anything specific about Gatsby. There are also other topics like React Router and Webpack that are built into Gatsby and have rooms on Reactiflux. While a separate Gatsby server could have its own React Router and Webpack rooms, I think it's more helpful to have them in one place personally.

> It's no use to actively force people into channels just because topics overlap.

Agreed, I like this leniency.

> Not every person on GitHub owns a Discord account.

I was unclear again, I mean that if we disabled the Gatsby bot in Reactiflux, people discussing GitHub Issues on Discord could still link to GitHub Issues manually, without the bot posting issues that aren't being discussed. This would only apply to people talking about Gatsby on Discord, I'm not suggesting we move all GitHub Issue discussion to Discord as I think that would be counterproductive.

> People who would be willing to get pinged instead (as they're some sort of "Helper" etc.) can't be mentioned as they have no specific role.

In my experience in Reactiflux (which has a smaller number of roles compared to some servers) some contributing users will often be pinged by other users that need help when they notice them answering someone else's question, even if they don't have a role. Perhaps Gatsby discussion could use more roles in which case a separate server would help, but the current room/role structure is working okay so far in my opinion.

> Creating an own server implies that the channel would be removed or disabled with a link to the server. As mentioned above: The problem of pointing users to other channels can be solved by just linking to it. After clicking the link you instantly join the server. If you're already there you'd just need to use Ctrl+K to find it. Discord and its interface allows it to easily interact with more than just one server.

I agree that if we had a separate server, this would be a way to go. There are some existing Reactiflux rooms that already do this. For example, `#mobx` was added as a channel that redirects to the official MobX chatroom because so many Reactiflux users were asking for MobX specific help. While the fragmentation of Gatsby specific discussion itself wouldn't be an issue, there's still the issue of non-gatsby-specific discussion happening in a separate Gatsby server where non-Gatsby developers in Reactiflux wouldn't see them.

**Comment by nickmccurdy** [comment]
Advantages:

> Organized structure and smaller chance of questions getting lost (especially from beginners)
That's a very good point, I do see some questions getting lost in both the Gatsby room and other Reactiflux rooms. I think experimenting with changes to the bot can help, but there are other things we could do.

> Possibility to extend the channels, e.g. for creating a dedicated channel for Gatsby V2

My instinct is that it might fragment discussion if we made version specific rooms, granted I haven't used Gatsby 2 much yet so I'm not very knowledgable about how different its usage would be.

> By using roles people (again: especially beginners) can easily identify other experienced users. Right now Kyle gets most of the mentions as he stands out with his colored name/role. But there are also a lot of other helpful people 👍

Good point. Reactiflux does have an MVP role, thought they're not necessarily experienced with Gatsby.

> By having the "core" community there "here/everyone mentions" are a viable option to attract attention to a topic

I personally don't like here/everyone mentions as they can cause people to be notified when they prefer not to be. Hopefully we can simplify Gatsby discussion on Discord (whether in the existing channel or a new server) to make this less necessary.

> Overall more control over possible extensions etc.

Another good point. Depending on the extension, this is something else we could add to Reactiflux's `#gatsby` room, but I could see us quickly hitting limitations by only having one Gatsby room.

> Own/Custom invite links (Analytics/Tracking would be possible by restricting the creation of invite links to Admins only and putting different links on different places (Docs, CLI))

I know very little about Discord analytics but I'm curious if a Gatsby specific server could improve this. I thought it was possible to have a room specific Discord invite link, but the one in Gatsby's docs seems to link me to unrelated rooms in Reactiflux.

**Comment by LeKoArts** [comment]
> my concern is more about the number of people in the server to provide support. While I'm sure some Gatsby users would prefer to not see the other channels of Reactiflux, moving to another server would reduce the number of people that could help in the gatsby rooms overall.

I understand how you want to argue that but you mentioned the big flaw of that thought yourself: You can mute channels you're not interested in. While in theory the > 2000ish people who are online could help in the Gatsby channel, only the people who are actually interested in Gatsby will visit the channel. The others mute that channel or don't look at it. You can't put them into. Why should one visit the Gatsby channel thinking: Hey, maybe someone needs help with React? If you want to help with React you look into the React channel.

> Speaking more specifically about React, someone new to Gatsby may assume that React is a part of Gatsby that isn't used for anything else, so they may not know to switch to another server like Reactiflux if they need help designing React components.

Tutorial Part 0 (WIP) will include such information (that JS/React is underneath etc.) and we could link to Reactiflux there.

> By keeping it in Reactiflux, there will be more React devs that could offer help even if they don't know anything specific about Gatsby. 

See above. You can't mention a React role so how and why should people look into the channel?

> While a separate Gatsby server could have its own React Router and Webpack rooms, I think it's more helpful to have them in one place personally.

No, in my opinion a Gatsby server shouldn't have such channels. Because Reactiflux is a better place for that and your first argument applies then (more people with knowledge).

> In my experience in Reactiflux (which has a smaller number of roles compared to some servers) some contributing users will often be pinged by other users that need help when they notice them answering someone else's question, even if they don't have a role.

First and foremost Kyle probably gets over 9000 more mentions than other people even though other people are also qualified to answer the "easy" questions. After that you have to rely on your memory to ping the right people. As a person who just recently joined the server you can't ping anyone (because it's not obvious that Kyle is the creator). I don't say that mentioning people is the way to go, doing the separation/getting attention with channels is the better way.

> I agree that if we had a separate server, this would be a way to go. There are some existing Reactiflux rooms that already do this. For example, #mobx

Yes, that's exactly what I was suggesting.

**Comment by LeKoArts** [comment]
> My instinct is that it might fragment discussion if we made version specific rooms, granted I haven't used Gatsby 2 much yet so I'm not very knowledgable about how different its usage would be.

Now I was being unclear 😅 
This channel would be for the "core" team discussing about the next version (that's why v2) and people could suggest things/be redirected to GitHub. After release the channel would be renamed or closed.

> I personally don't like here/everyone mentions as they can cause people to be notified when they prefer not to be. Hopefully we can simplify Gatsby discussion on Discord (whether in the existing channel or a new server) to make this less necessary.

You can disable it though. I like here/everyone (restricted to higher roles of course) for bigger announcements. But at least we have the option to do so then.

> I know very little about Discord analytics but I'm curious if a Gatsby specific server could improve this. I thought it was possible to have a room specific Discord invite link, but the one in Gatsby's docs seems to link me to unrelated rooms in Reactiflux.

It was just a small advantage I thought of. Yes, you can link to specific channels, so not a big pro/con.

**Comment by nickmccurdy** [comment]
> You can't mention a React role so how and why should people look into the channel?

This is one of the advantages to having a single server with both Gatsby and non-Gatsby topics, a React dev that otherwise wouldn't care about Gatsby may see a question there they could answer. You have a good point that a React dev may just mute Gatsby anyway and that the opt in nature of channels can be overwhelming. You can now mute entire groups of channels in Discord, but it's still significantly inconvenient to mute all but one room (like `#gatsby`). Also it's not just about channel structure, but how many people are available in the server to offer help. By having both topics in the same server, a Gatbsy user may be inclined to ask a question in another room that hopefully more people could see.

> I don't say that mentioning people is the way to go, doing the separation/getting attention with channels is the better way.

Totally agree, mentions can be a lot to deal with and channels take care of async communication more effectively. I personally think the size of the existing gatsby room is okay without splitting it up (depending on what Gatsby maintainers and Discord moderators feel), but if we need a fancier channel structure, a new server is the way to go.

> You can disable it though. I like here/everyone (restricted to higher roles of course) for bigger announcements. But at least we have the option to do so then.

True, though pinning messages has similar advantages. This still might get too messy with our existing single room setup though.

**Comment by LeKoArts** [comment]
> that otherwise wouldn't care about Gatsby may see a question there they could answer

What are the chances? Realistically looking at it I think they're pretty low. Especially if the messages from members are spread over hundreds of messages because the Bot posted something in the meantime or other people talked about something different.

> Also it's not just about channel structure, but how many people are available in the server to offer help. By having both topics in the same server, a Gatbsy user may be inclined to ask a question in another room that hopefully more people could see.

I already tried to explain that:
It's not about the total number of users but the number of users who are interested in Gatsby and actually look into the channel. Yes, if you then go to the ``#react`` channel or something you have more people willing to help you. But you don't need to be part of the server. Discord makes it **super easy** to join other servers and interact with them. Other services/projects also focus their server on their own product/service. They want to build their own community around their product. If you join these servers you expect experts for the specific product there.

And yes, I actually didn't add it to the disadvantages that some users may be bugged by the whole server (regular everyone pings) even though they only want to follow ``#gatsby``.

> I personally think the size of the existing gatsby room is okay

For now it may be okay, yes. But I think sooner or later this step is necessary to improve user engagement, community projects, communication and overall Gatsby.

**Comment by KyleAMathews** [comment]
>I personally think the size of the existing gatsby room is okay

>For now it may be okay, yes. But I think sooner or later this step is necessary to improve user engagement, community projects, communication and overall Gatsby.

I think one channel is fine for now. I'm on two other discord servers and one is a ghost town and the other is pretty active across many channels. Until our channel is too crowded, there's not much point in expanding as we lose access to the casual drive-bys from people already on #reactiflux + I agree that people having access to the other #reactiflux channels is really helpful.

I'll remove the bot in the meantime as it seems more noisy than helpful.

**Comment by m-allanson** [comment]
Let's talk about this again, now that Gatsby is growing so quickly maybe the time is right for a dedicated Gatsby Discord server.

**Comment by LeKoArts** [comment]
I'd only emphasize that the server should start with a low count of channels to keep the activity in these at first 😊

**Comment by KyleAMathews** [comment]
We just went ahead and made it so join away! https://discord.gg/pbcTfjD

There's currently one channel so very low! :-P

**Comment by iammatthias** [comment]
@KyleAMathews the link says the invite is expired?

**Comment by KyleAMathews** [comment]
Try this one https://discord.gg/jUFVxtB
