### ISSUE TITLE
Search bar not loading search results

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#4431]
## Description

The search bar seems to not load search results in some specific situations.

### Steps to reproduce problem 1

1. Typed graphql into search in the docs
2. Hit enter
3. Click around
4. I navigated back to the homepage 
5. typed graphql into search bar and hit enter
6. Nothing happened

### Expected result

I'm guessing in 6. above, the search results modal ought to appear.

### Actual result

See step 6 above.

### Steps to reproduce problem 2

It seems like this same thing happens when I try to use the search bar a second time after clicking around.

@m-allanson

**Comment by m-allanson** [comment]
Thanks for the reproduction steps @shannonbux! 

It looks like this is caused by focussing a search input that already has content, and then pressing enter. This 'submits' the form, but we're just ignoring the submit.

A workaround is to add a few lines to [`search-form.js`](https://github.com/gatsbyjs/gatsby/blob/efa8fe92cd7525c950f10fc27c632ef6dbd8ff8a/www/src/components/search-form.js#L295):

```
      autocompleteOptions: {
        openOnFocus: true,
      },
```

However, that causes styling issues with the search box on the home page. Posting this here in case anyone can investigate.
