### ISSUE TITLE
acf gallery type

### ISSUE THREAD

**Issue by kepi0809** [gatsbyjs/gatsby#4461]
Hi!

First of all thanks for you hard work, this is really awesome! 👍 

I have encountered a bug/problem... I want to query with graphql an acf custom field gallery from a custom post type but the query contains only a boolean and no img sources. 

On wp side it must be good, because in json I can find the attributes of each images  so it must be something wrong when gatsby fetches the data probably. With single img it works perfectly so till I can fix it I'm using 3 fields. 

The problem is that in graphql editor it doesn't see any attributes of the gallery type.

Thank you for your help in advance! :)

**Comment by pieh** [comment]
Hi @kepi0809 - this usually happens because wordpress return `false` instead of empty array or null in case there are no data for some posts (you propably could check if that's the case by manually examining wordpress REST endpoint - something like `http://your-url/wp-json/wp/v2/name-of-custom-type`) and this make gatsby confused because field is once array and once boolean.

If this is the case - then You would need to add following code snippet that force to return null instead of any empty values (like `false` or empty arrays) to your wordpress instance - either via theme functions.php or via custom plugin. I didn't used gallery fields, so you might need to adjust filter name that target gallery - but image and relationship works fine for me.
```php
function nullify_empty($value, $post_id, $field)
{
    if (empty($value)) {
        return null;
    }

    return $value;
}

add_filter('acf/format_value/type=image', 'nullify_empty', 100, 3);
add_filter('acf/format_value/type=relationship', 'nullify_empty', 100, 3);
// not sure if gallery is internally named gallery as well but this should work
add_filter('acf/format_value/type=gallery', 'nullify_empty', 100, 3); 
```

**Comment by kepi0809** [comment]
Yeas thank you, one of the instances had indeed empty gallery. 👍

**Comment by pieh** [comment]
@kepi0809 Can we close this issue or you still experience this issue?

**Comment by kennethormandy** [comment]
Just in case anyone else is searching, @pieh’s solution also fixed the problem I was having related to #3009 with repeaters:

```php
add_filter('acf/format_value/type=repeater', 'nullify_empty', 100, 3);
```

**Comment by garethgd** [comment]
Just on a sidenote from the the ACF docs.

"Renamed from acf/format_value_for_api in v5.0.0"

So in my functions.php I changed the filter to:

`add_filter('acf/format_value_for_api/type=image', 'nullify_empty', 100, 3);`

**Comment by alex9pro1** [comment]
Thank you, guys! It is working :)

**Comment by SimonIMG** [comment]
Nailed it @pieh ! Thank you. Your suggested addition to my theme's functions.php has solved my repeatable image fields not working.

My error was `Field "gallery_image" must not have a selection since type "Boolean" has no subfields`. This error is gone, GraphQL is querying repeatable image fields correctly and my Gatsby site is displaying images correctly.

**Comment by u12206050** [comment]
Hi,

I have applied this fix and though I can see it works via the REST api, it still shows that it is conflicting in Gatsby. I have removed .cache and rebuilt but still doesn't work.

Anything else I am missing?

**Comment by AllanPooley** [comment]
Using Advanced Custom Fields PRO 5.5.3 and this solution worked for me:

```
// Nullifying Empty ACF Values
// Fixes optional fields being obscured by GraphQL

function nullify_empty($value, $post_id, $field)
{
    if (empty($value)) {
        return null;
    }
    return $value;
}

add_filter('acf/format_value/type=image', 'nullify_empty', 100, 3);
add_filter('acf/format_value/type=relationship', 'nullify_empty', 100, 3);
add_filter('acf/format_value/type=repeater', 'nullify_empty', 100, 3);
add_filter('acf/format_value/type=gallery', 'nullify_empty', 100, 3);

```

Thanks so much @pieh @kennethormandy !

**Comment by kmcaloon** [comment]
So I was also having some trouble with empty text fields, was able to resolve by filtering all fields and returning an empty string vs null:

```

function nullify_empty( $value, $post_id, $field ) {

  if( empty( $value ) ) {
    return '';
  }
  return $value;

}
add_filter( 'acf/format_value', 'nullify_empty', 100, 3  );

```

**Comment by melilocacr** [comment]
Is there a way to implement this nullify_empty function with the acf object? 

Sometimes my custom posts don't have any acf fields and so the build process crashes. I used  @kmcaloon's solution to no avail.
