### ISSUE TITLE
Parent/children role in nodes

### ISSUE THREAD

**Issue by pieh** [gatsbyjs/gatsby#4537]
## Context:

Change adding deletion of posibly stale descedent nodes after creating node ( https://github.com/gatsbyjs/gatsby/pull/4209 and https://github.com/gatsbyjs/gatsby/pull/4353 ) introduced problems in some of plugins. We fixed that since then but it raised question about role of parent/children - initial discussion can be found in comments here - https://github.com/gatsbyjs/gatsby/pull/4429 . 
**TLDR**: don’t use parent/children properties for defining relationship between nodes - use node linking instead. Parent/children should be reserved for transformer plugins.

I also found older issue somewhat related to that I don’t think was defenitely answered - https://github.com/gatsbyjs/gatsby/issues/1220 .

### Docs:
I didn’t find any mentions of `___NODE` convention that is used for node linking anywhere in the docs. Not sure what's good place for it. Add section here https://www.gatsbyjs.org/docs/node-interface/ or here https://www.gatsbyjs.org/docs/create-source-plugin/ ?
### Code / api changes to `createNode` action:
- `children` field:
  
  If parent/children should be dedicated for transformer plugins this means it will be used in `onCreateNode` and therefore we can’t know ids of children when creating nodes - so we will have to pass empty array for `children` field. Should we deprecate it for v2?
- `parent` field / `createParentChildLink` action:

  Now that we need to create parent node before children nodes. This allow us to automatically call `createParentChildLink` action in `createNode` if parent is defined (or implement same logic). This could also allow us to potentially depracate `createParentChildLink` action.

Sidenote: Removing `children` and maybe making `parent` optional instead of required could also potentially make it easier for beginners to grasp concept of nodes in gatsby as this would be few things less to worry about when doing first steps with data sourcing in gatsby.

### Adding comments in plugins code:
As `___NODE` convention is currently missing in docs usually what happens is people check and copy code from existing plugins. Some of the plugins in gatsby repo use parent/children relationship incorrectly (according to recently decided role of parent/children). I think it would be worth adding comments to code where it’s used that it’s incorrect but it’s not removed yet to not break projects relying on it, but it will be removed in v2 (or rather whatever version the plugin will have when we ship v2). I've already checked what plugins are affected as I needed to check each plugin and "bandaid" fix it if needed ( https://github.com/gatsbyjs/gatsby/pull/4513 any plugin that has status different than "not used" ).

**Comment by m-allanson** [comment]
This sounds good 👍 I'm not exactly sure on the differences between using `___NODE` and `child`/`parent`, but I guess that's as good a reason as any to add docs. When I've written plugins I've used the `child` and `parent` fields, because that's what some of the existing plugins seem to do, and as you mentioned there's not much documentation on using `___NODE`.

Is this change to ensure that Gatsby can correctly invalidate descendants of stale nodes? Or is it achieving something else?

On your points for discussion:

### Docs

Maybe https://www.gatsbyjs.org/docs/node-interface/ could be expanded to include example usages of `parent` and `child` fields, along with the `___NODE` convention? This feels like a case where a few examples would be really helpful. Or there should be a new docs page describing how to use them.

If there was a new docs page that could also be linked from https://www.gatsbyjs.org/docs/create-source-plugin/ 

### Code / api changes to createNode action

I don't know enough to really comment here, other than to say anything that makes the APIs simpler gets a 👍 from me :)

### Adding comments in plugins code

Any plugins in the gatsbyjs monorepo should be written in a 'best practice' style, as they'll often be used as reference for people writing their own plugins. Would it be possible to add deprecation notices in v1? And then update any plugins for v2.

**Comment by pieh** [comment]
It should be covered by https://github.com/gatsbyjs/gatsby/pull/6793
