### ISSUE TITLE
Documentation on nested plugins?

### ISSUE THREAD

**Issue by pauldotknopf** [gatsbyjs/gatsby#4572]
https://github.com/gatsbyjs/gatsby/blob/918b6c85e93604fe215540e267f757775d2e0574/www/gatsby-config.js#L49

Is there guidance on how they work and when to use them?

**Comment by m-allanson** [comment]
@pauldotknopf There's not a lot on nested plugins, maybe have a look at the [Plugin Authoring Guide](https://www.gatsbyjs.org/docs/plugin-authoring/#plugin-naming-conventions). 

Nested plugins can be used to extend the capabilities of the parent plugin. As an example, all of Gatsby's [`gatsby-remark-x` plugins](https://github.com/gatsbyjs/gatsby/tree/master/packages) extend the [`gatsby-transformer-remark` plugin](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-transformer-remark#gatsby-transformer-remark).

**Comment by KyleAMathews** [comment]
Any plugin can have its own plugins. But the parent plugin has to be expecting this and have code to call the code from the sub-plugin for this to have any effect otherwise nothing happens. `gatsby-transformer-remark` is the only plugin I know that does this currently. Here is where it let's each sub-plugin mutate the markdown AST https://github.com/gatsbyjs/gatsby/blob/39405449fee04357d442f80681544528b445c6fc/packages/gatsby-transformer-remark/src/extend-node-type.js#L163

**Comment by jkjustjoshing** [comment]
Can we re-open this? This seems like a pretty important thing to document inside the [Plugin Authoring Guide](https://www.gatsbyjs.org/docs/plugin-authoring/#plugin-naming-conventions). 

I'm writing an extension right now that is taking nodes defined by `gatsby-source-filesystem` and transforming them. Should `gatsby-source-filesystem` be a nested plugin of my transformer plugin? I do not know the answer to that question, and the docs do not currently provide an answer. The only way I can answer that question right now is digging into the source code of `gatsby-transformer-remark`.
