### ISSUE TITLE
What Makes Gatsbya PWA (Progressive Web App)?

### ISSUE THREAD

**Issue by melissamcewen** [gatsbyjs/gatsby#4575]
I've been using Gatsby for a bit and loving it! I'm curious about what makes it a PWA vs. something like Jekyll?

**Comment by benjaminhoffman** [comment]
Out of the box, you get:
- super fast initial page load speed
- code splitting
- caching
- service workers

please read: https://www.gatsbyjs.org/docs/prpl-pattern/
and https://www.gatsbyjs.org/blog/2017-09-13-why-is-gatsby-so-fast/
and https://www.gatsbyjs.org/features/

If you are asking about a specific part of PWAs and Gatsby, please clarify and I'll be happy to dive into more details! 👍

**Comment by melissamcewen** [comment]
Thanks! I did the Lighthouse PWA audit for my out of the box sites and it said they had no service workers? Do I need some specific plugins for that like gatsby-plugin-offline? 

I also assume `gatsby-plugin-manifest` takes care of the manifest thing. 

I'm writing an article on easy PWAs and thought GatsbyJS would be a good example.

**Comment by jlengstorf** [comment]
Hey, @melissamcewen! You're correct: to turn on Service Workers, you'll need `gatsby-plugin-offline`, and for a manifest you need `gatsby-plugin-manifest`.

They're opt-in because the offline storage can be really confusing to debug if you're not familiar with how it works.

I'm going to close this, but let me know if you have any other questions, and please mention @gatsbyjs when the article goes live so we can share it!

**Comment by melissamcewen** [comment]
Hi all, just published it belatedly! https://rollout.io/blog/progressive-web-app-running-20-minutes/
