### ISSUE TITLE
Upgrade to webpack 2 in 1.0 branch

### ISSUE THREAD

**Issue by f0rr0** [gatsbyjs/gatsby#461]
webpack 2 is fairly stable. Bundle sizes could reduce drastically via tree shaking.

**Comment by KyleAMathews** [comment]
I'm planning on shipping 1.0 with this. It's only "fairly" stable atm though so don't want to convert over just yet.

**Comment by mgamsjager** [comment]
Regarding this issue: https://github.com/gatsbyjs/gatsby/issues/445

Maybe the migration to webpack 2 resolved the memory issue as well.

**Comment by KyleAMathews** [comment]
Perhaps but I doubt it — it seems like that's a core design decision (which I agree with fwiw) so it's probably stayed.

**Comment by fitzk** [comment]
Hey there, has anyone picked up this ticket? If not, I can pick it up, I would love to contribute.

**Comment by KyleAMathews** [comment]
@fitzk nope! Not yet! Feel free to take it on. Though you'll probably want to hit me up in Discord to chat about things as 1.0 is still a moving target. Thanks!

**Comment by fitzk** [comment]
For sure, thanks!

**Comment by designorant** [comment]
There's a very helpful guide for this: https://webpack.js.org/guides/migrating/

**Comment by akadop** [comment]
Any progress on this? I'm finding it difficult to wrap my head around the stages (build-css, build-html, etc). Are they actively used? If not, perhaps just a standard dev / production config will work so that we can reap the benefits of webpack 2

**Comment by KyleAMathews** [comment]
@akadop not yet. It'll come though as part of the 1.0 release.

The stages are a necessary part of how Gatsby works.

We have to have at least two stages for building JavaScript bundles and HTML as they're very different way so using webpack. We added the CSS as an optimization so that we could easily inline CSS in the `<head>` of websites. See https://github.com/gatsbyjs/gatsby/issues/145

**Comment by MoOx** [comment]
FYI webpack 3 is out for a while now :) (as I am writing 3.5.x)

**Comment by LegNeato** [comment]
FYI, not having treeshaking with a newer webpack currently makes any site using gatsby with `material-ui` (a fairly popular UI lib) bloated.

**Comment by KyleAMathews** [comment]
@LegNeato hoping to get Gatsby v2 with webpack 3 out in the next few weeks! @jquense has much of the work done already! Would love your help testing out alphas/betas. There's already alphas out and you can check out the work on the v2 branch.

Closing this issue since we're not going to upgrade to webpack 3 for 1.x

**Comment by monsieurnebo** [comment]
Hello !

Any news about the Webpack v2 progress? :)

**Comment by monsieurnebo** [comment]
Hello !

Any news about the Webpack update progress? I'm stuck with some dependencies that need Webpack v2+ :(

**Comment by KyleAMathews** [comment]
Still a bit off. @jquense has done a lot of the work but there's some other things I want to do for v2 that we're blocked on. I can't get to working on the upgrade for another couple weeks probably. My plan/hope is to have the release done by Christmas.

**Comment by calpa** [comment]
FYI, for those who want dynamic import, just wait for gatsbyjs to upgrade webpack version.

**Comment by felipearosemena** [comment]
Any news on upgrading webpack?

**Comment by m-allanson** [comment]
See https://github.com/gatsbyjs/gatsby/pull/4588
