### ISSUE TITLE
Add Algolia notes to Plugin Authoring doc

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#4673]
- [ ] Add instructions to the page for plugin authors about how to get their plugin to show up — namely
    - [ ] add "gatsby-plugin" as keyword
    - [ ] wait 24 hours while Algolia reindexes

**Comment by KyleAMathews** [comment]
I think I said at some point it was 24 hours but I most have made that up as I'm not sure the reindex time is documented and in practice, it seems Algolia updates very quickly after a new publish to NPM.

**Comment by hcavalieri** [comment]
Hey there :)

So, when I published `gatsby-source-sanity` I was a bit anxious to see it in the docs, so I went straight to https://gatsbyjs.org and https://next gatsbyjs.org, and in both I could see the result from algolia but the page wasn't built yet, so it returned a 404...

It took from 12 to 30 hours for the page to show up (sorry for the broad range), I believe that's because you have a daily routine to check algolia and rebuild the website?

Anywho, it seems like algolia is the faster side here. I'd be glad to do a PR with this tiny addition to the plugin authoring docs ;)

**Comment by jlengstorf** [comment]
@hcavalieri we'd absolutely love to have you update the docs! Thanks so much! 💪💜

**Comment by hcavalieri** [comment]
Hey there, @jlengstorf , how's it going? So, 4 days ago I forked the repo and [added this change](https://github.com/hcavalieri/gatsby/commit/b848dfdacdd75b79439f5c39506a025580a45c92) for the docs but it doesn't seem to have been submitted as a PR... sorry for the silly question, but any suggestions?

**Comment by jlengstorf** [comment]
Hey, @hcavalieri!

Now that you've made the changes, you'll need to open a pull request as well. This should help you get started: https://github.com/gatsbyjs/gatsby/compare/master...hcavalieri:patch-1

Let me know if you have any questions!
