### ISSUE TITLE
[v2] Refactor Babel config loading to use the new loadPartialConfig and createConfigItem APIs

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#4689]
Much better than our hacky current way of loading user config :-)

https://github.com/babel/babel/tree/master/packages/babel-core#babelloadpartialconfigoptions-object-partialconfig

/cc @loganfsmyth

**Comment by loganfsmyth** [comment]
Per https://github.com/babel/babel-loader/issues/598#issuecomment-375934972, it seems like if we expose that from `babel-loader`, the main difficulty depends on what exactly Gatsby wants plugin developers to be able to do with the `modifyBabelrc` hook that you offer. If it's purely a "add this plugin" API, then it should be really easy, otherwise it seems like you'd have to call `modifyBabelrc` for ever single file as it is compiled, which could be slow.

**Comment by KyleAMathews** [comment]
Hmmm interesting — not sure I understand just yet — what's the problem with allowing Gatsby plugins modify the babelrc? It'd only be done once at the start of the Gatsby process. Why would we need to call modifyBabelrc for every file that's compiled?

**Comment by jquense** [comment]
ya my thought was we'd turn off options on the babel loader, load the user options up front and then use that, cached and all.

**Comment by loganfsmyth** [comment]
The options vary by filename, so there isn't really an "up front" to load. You can certainly load them yourself, but I still think doing it per-file would be important. I wouldn't worry about performance on Babel's side, it's all cached pretty well, it's just that since you expose `modifyBabelrc` I guess you'd want to run that per-file too, if it's meant to modify the user's actual config.

**Comment by KyleAMathews** [comment]
Oh, so users can specify in their .babelrc per file config? I had no idea.

**Comment by loganfsmyth** [comment]
Yes, in Babel 6 it was already possible because you could have multiple `.babelrc` files in nested directories, but in Babel 7 it's encouraged with https://github.com/babel/babel/pull/7091

**Comment by jquense** [comment]
Looks like babel-loader has added the relevant API for us to use (a bit a go). https://github.com/babel/babel-loader#customized-loader From what i'm seeing we should use the custom-loader option here, merge in any additional gatsby specific plugins (graphql, etc) and if there is no filesystem config provide the default babel one.

Some implications here for the Gatsby babel API...As noted above it seems like we can't actually have Gatsby store a single authoritative config for the entire project since babel could be using nested `.babelrc`s or `overrides` in the root one. Storing the root `babelrc` and modifying that in redux (the current approach) is a bit weird in those. How do nested configs behave? etc etc. The question then is what should the scope and effect of Gatsby's babel hooks for plugins? 

My initial thought is we should remove the babel redux state, and let babel itself be the authoritative input for what a config is. That means we move gatsby-node babel apis to run on demand, e.g. during each call of babel-loader `config()` method, or in the case of our internal parsing needs (the query-parser for example) we use [loadPartialConfig](https://new.babeljs.io/docs/en/next/babel-core.html#babelloadpartialconfig-options-options-object-partialconfig) per file and run the same pipeline

thoughts? Does that seem reasonable, I may be entirely off base :P

**Comment by jquense** [comment]
FYI @KyleAMathews I think there is likely a breaking change here, we should definitely try and nail this down before a final v2

**Comment by KyleAMathews** [comment]
Yeah, this does seem like a breaking change. Been planning on looking into this more but that hasn't happened yet so appreciate you jumping on it @jquense! 

Yeah, seems like storing babel settings in redux doesn't make much sense anymore. So yeah, calling gatsby plugins whenever babel wants to call them seems reasonable. I'm not entirely sure I grok the the `.custom` loader entirely but it seems like we can still get what we want namely ship a default setup and also allow people to override it while still allowing gatsby plugins to add babel plugins and override other plugin settings as necessary.

**Comment by KyleAMathews** [comment]
It _might_ not be a breaking change perhaps though?

**Comment by KyleAMathews** [comment]
Oh interesting. Yeah, that would be a slight breaking change though for most plugins, they'd still do the exact same thing. I assume @loganfsmyth we could still pass in what environment babel is running in e.g. development vs. production?

**Comment by loganfsmyth** [comment]
Yeah you can still set the environment in a couple ways.
