### ISSUE TITLE
v2: Local gatsby-ssr.js is not run anymore on a static build.

### ISSUE THREAD

**Issue by jquense** [gatsbyjs/gatsby#4718]
Not sure what the deal here is, but trying my `onRenderBody` hook is no longer run when doing a gatsby build

**Comment by jquense** [comment]
This is because, `resolve-module-exports` is not robust enough. Why are trying to do this statically again? false negatives are a pretty error here, it seems like we should be reallly safe about this and just require and inspect the exports.

**Comment by jquense** [comment]
exports are not always statically determinable in commonJS

**Comment by jquense** [comment]
oops sorry that doesn't seem to be the issue here, but it's still a valid question :P

**Comment by jquense** [comment]
OK. what is actually wrong is that: 

```js
import React from 'react'

exports.onRenderBody = ({ setHeadComponents }) => {
  setHeadComponents([
}
```
is silently failing because there is mixed exports and commonJs, i'm not sure WHAT is failing but something is, maybe babel?

**Comment by KyleAMathews** [comment]
Ah yeah — I think it's webpack 4 that's now preventing that. I had to fix a bunch of things in core + in sites i've upgraded.

**Comment by KyleAMathews** [comment]
`resolve-module-exports` is required though since we can't require them directly if they have webpack only code. Setting up webpack to build each module seems pretty heavy.

**Comment by pieh** [comment]
I've encountered this too when updating freecodecamp guides site to test with v2. 

It also seems like `master` have more checks (https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/bootstrap/resolve-module-exports.js#L47-L75) than v2 ( https://github.com/gatsbyjs/gatsby/blob/v2/packages/gatsby/src/bootstrap/resolve-module-exports.js#L47-L56 ).

**Comment by jquense** [comment]
It should pretty agressive about warning I think. getting no error or message isn't ideal especially since my intent is clear. IDK we should definitely warn if no apis are found, or figure out why Babel isn't throwing here?

**Comment by m-allanson** [comment]
Ok spent some time tracking down the cause of this with @pieh (thanks!). Using this `gatsby-ssr.js` file as an example:

```js
// gatsby-ssr.js
import React from "react"
exports.onRenderBody = ({ setPreBodyComponents }) => {
    setPreBodyComponents(<h1>LA LA LA</h1>)
}
```

The bug is caused by using an ES6 module `import` with a CommonJS `exports` (@jquense [pointed this out already](https://github.com/gatsbyjs/gatsby/issues/4718#issuecomment-376249953)), which causes the `exports` to be ignored by webpack.

Why this happens is - using `import` means the module is treated as an ES6 module (import / export) instead of  a CommonJS module (require / modules.exports / exports). 

As `gatsby-ssr.js` is treated as an ES6 module, `exports` doesn't do anything  and _should_ be undefined. However, this transformed module ends up in a bundle `render-page.js`, which gets run in a Node environment.

When running in a Node environment, `exports` defaults to `{}`:

```shell
echo "console.log(exports)" > test.js && node test.js
{}
```

Which means that the onRenderBody definition `exports.onRenderBody = ` does not error (`exports` is defined), and also does not get exported (`exports` is not an `export`). It just silently gets defined and then sits there doing nothing.

So `onRenderBody` does not get exported, meaning it doesn't get called by the `apiRunner`.

One "fix" is to not use `import` with `exports` (related: https://github.com/webpack/webpack/issues/4039#issuecomment-273804003), but we can't really control that.

I've [opened a PR that hacks in a very basic fix](https://github.com/gatsbyjs/gatsby/pull/6326), just prepending `exports=null` to the beginning of the webpack bundle.

This will throw:

```
error UNHANDLED EXCEPTION


  TypeError: Cannot set property 'onRenderBody' of null

  - render-page.js:661 Module../gatsby-ssr.js
```

if you try and use `exports` in an ES6 module. Which is one step better than silent failure.

I think throwing a helpful error describing how to update your file is the best way to resolve this. 

We could do it with eslint? But people can override that. Carry on down [the static analysis path](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/bootstrap/resolve-module-exports.js#L1) we're already using to load plugins? Something else?

<details>
  <summary>Example inputs / outputs for `gatsby-ssr.js`</summary>


## ES6 Module import, CommonJS exports

```js
// gatsby-ssr.js
import React from "react"

exports.onRenderBody = ({ setPreBodyComponents }) => {
    setPreBodyComponents(<h1>LA LA LA</h1>)
}
```

```js
// webpack bundle render-page.js 
// ...more code
/***/ "./gatsby-ssr.js":
/*!***********************!*\
  !*** ./gatsby-ssr.js ***!
  \***********************/
/*! no exports provided */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var react__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! react */ "./node_modules/react/index.js");
/* harmony import */ var react__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(react__WEBPACK_IMPORTED_MODULE_0__);


exports.onRenderBody = ({
  setPreBodyComponents
}) => {
  setPreBodyComponents(react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement("h1", null, "LA LA LA"));
};
// ...more code
```

note the `/*! no exports provided */` and `__webpack_exports__` being passed in.

## Full CommonJS

```js
// gatsby-ssr.js
const React = require("react")

exports.onRenderBody = ({ setPreBodyComponents }) => {
    setPreBodyComponents(<h1>LA LA LA</h1>)
}
```

```js
// webpack bundle render-page.js 
// ...more code
/***/ "./gatsby-ssr.js":
/*!***********************!*\
  !*** ./gatsby-ssr.js ***!
  \***********************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

const React = __webpack_require__(/*! react */ "./node_modules/react/index.js"); 

exports.onRenderBody = ({
  setPreBodyComponents
}) => {
  setPreBodyComponents(React.createElement("h1", null, "LA LA LA"));
};

/***/ }),
// ...more code
```

Here it's `/*! no static exports found */` and `exports` is passed in instead of  `__webpack_exports__`
</details>

**Comment by jeroenransijn** [comment]
Is this supposed to work currently? I can't make `gatsby-ssr.js` do anything it seems.

```javascript
// gatsby-ssr.js
const React = require("react")

exports.onRenderBody = ({ setPreBodyComponents }) => {
    setPreBodyComponents(<h1>LA LA LA</h1>)
}
```

**Comment by KyleAMathews** [comment]
Oh ok, so es6 _is_ already working. Tried this and it worked fine:

```javascript
import React from "react"

export const onRenderBody = ({ setPreBodyComponents }) => {
  setPreBodyComponents(<h1>LA LA LA</h1>)
}
```

**Comment by KyleAMathews** [comment]
I think the solution is to just put together a little babel script which checks for mixed commonjs/es6 and tells you to stop it :-)

**Comment by bitttttten** [comment]
I can only get this to work with mixing commonjs imports, and es6 exports.

```js
const React = require("react")

export const onRenderBody = ({ setHeadComponents }, pluginOptions) => {
  if (process.env.NODE_ENV !== `production`) {
    return null
  }
  setHeadComponents([
    <link
      rel="preconnect dns-prefetch"
      key="gatsby-plugin-myplugin-preconnect"
      href="https://mymyplugin.cloudfront.net/"
    />,
  ])
}
```

If I use commonjs exports, like `exports.onRenderBody`, it will "fail" "silently".

**Comment by rikakomoe** [comment]
The same issue with @bitttttten 

CommonJS exports will not get triggered while ES6 exports work.

This code doesn't work and print nothing.
```javascript
const React = require("react")
const { dom } = require('@fortawesome/fontawesome-svg-core')

exports.onPreRenderHTML = ({ getHeadComponents, replaceHeadComponents }) => {
  const headComponents = getHeadComponents()
  headComponents.push(
    <style id="fontawesome-ssr" dangerouslySetInnerHTML={{__html: dom.css()}} />
  )
  console.log(headComponents)
  replaceHeadComponents(headComponents)
}
```

This code works and print as expected.
```javascript
const React = require("react")
const { dom } = require('@fortawesome/fontawesome-svg-core')

export const onPreRenderHTML = ({ getHeadComponents, replaceHeadComponents }) => {
  const headComponents = getHeadComponents()
  headComponents.push(
    <style id="fontawesome-ssr" dangerouslySetInnerHTML={{__html: dom.css()}} />
  )
  console.log(headComponents)
  replaceHeadComponents(headComponents)
}
```

**Comment by molebox** [comment]
This information needs to be added to the docs as its vital to getting gatsby-ssr.js file to work.

**Comment by rubas** [comment]
This needs to be documented. 

This is the winning combination, everything else fails **silently** 👻  

```
const React = require("react")

const wrapRootElement = () => <h1>aaa</h1>
const wrapPageElement = () => <h1>bbb</h1>

export { wrapRootElement, wrapPageElement }
```

**Comment by happylolonly** [comment]
Faced this issue several weeks ago, it was a problem that export with default functions doesn't work, but arrow function work. (I prefer normal functions when I can).

`export function ...` - didn't work
`export const ... = () => {}` - worked

**Comment by cesarvarela** [comment]
You don't need to do es6 exports for it to work, `export.whatever` does.

**Comment by timmywil** [comment]
@happylolonly That's strange. I switched mine to arrow functions as well and it started working. I wonder why a function declaration would be treated differently.

**Comment by Zauberfisch** [comment]
This is still an issue.
The examples provided here https://www.gatsbyjs.com/docs/ssr-apis/#onPreRenderHTML are therfore not working.

Converting it to ES6 fixed it for me, but having this fail silently with examples from the official docs is problematic and took me some time to figureout.

**Comment by ianks** [comment]
yeah this is a bad one... for one, i forgot to import React and gatsby just went on like nothing was wrong, now i'm stuck on this exports mismatch thing.

i think it would be best to fail loudly in these cases.
