### ISSUE TITLE
Editing & Adding new content to an existing page via Contentful?

### ISSUE THREAD

**Issue by squaredindex** [gatsbyjs/gatsby#4807]
Hi, new to Gatsby and JAMStack setup and still trying to get to grips with everything, so apologies if this is something apparent I've not understood via the docs.

I've managed to get posts created via Contentful, however, I'd like to add the ability to edit content on existing pages and if possible add new sections/content to those existing pages rather than create separate pages for those sections.

So, for example, say you have a one-page website and that has sections such as 'About us', 'What we do', 'Contact us' etc. What would be the best approach to making those sections individually editable via Contentful?

**Comment by KyleAMathews** [comment]
Editable in the Contentful UI?

**Comment by squaredindex** [comment]
@KyleAMathews Yeah, that's right. I wouldn't mind a solution that uses NetlifyCMS either, really just need something easy for clients to use.

**Comment by grantly7** [comment]
@squaredindex  I'm using Gatsby + Contentful + Netlify and loving it in terms of how flexible the entire setup is. An enjoyable developer experience and the clients love the simplicity of editing content via Contentful compared to other solutions I had wired up for Jekyll but really never felt truly stoked on.

I'd recommend a couple things to get into the groove quicker.

- Run through the entire Gatsby tutorial, there is a ton of gold in there I didn't see at first glance.
- Take in everything you can regarding GraphQL if your new to it like I am. [How to GraphQL](https://www.howtographql.com/) Coming back to Gatsby tutorial and docs made a lot more sense to me after this.
- Check out the [this video series](https://www.youtube.com/playlist?list=PL8KiuH6vpACV-F7jXribe4YveGBhBeG9A) that Khaled Garbaya from Contentful put together. He focuses mostly on a simple blog setup but watching him wire it up on the fly and correct little things was worthwhile.
- Finally scope out some repos like [gatsby-contentful-starter](https://github.com/contentful-userland/gatsby-contentful-starter) this will give you some ideas about how you can leverage the GraphQL data layer and template a layout anyway you can think of. Try taking a peak at the components folder especially. That really made Contentful's content models and entries make more sense for stuff like wiring up unique sections/components that are client editable.

I'm very new to it myself but hopefully this helps.
Oh and be sure to join us all on the [Spectrum community for Gatsby](https://spectrum.chat/gatsby-js)! Its pretty fun for open ended discussions on the fly.

**Comment by ryanditjia** [comment]
I might be able to help here. I create a custom Content Model for each page that I want for the user to be able to edit.

## Content model examples
Homepage
![image](https://user-images.githubusercontent.com/16177372/38232714-4dd4460c-3742-11e8-8246-32d4a40c90e8.png)

About page
![image](https://user-images.githubusercontent.com/16177372/38232687-34ff46f4-3742-11e8-8b3d-102a1a40f6b4.png)

## Single entry protection
You have to make sure that there is only **1 entry** for each page’s Content Model. This is a little bit of a workaround, but it gets the job done. Notice the _Single entry protection_ field? Here are the settings for that field:
![image](https://user-images.githubusercontent.com/16177372/38232897-fcff410e-3742-11e8-9cc4-a0fd9f0e9dd5.png)
![image](https://user-images.githubusercontent.com/16177372/38232914-0ebaef24-3743-11e8-94fb-dc2b42c88b6b.png)
![image](https://user-images.githubusercontent.com/16177372/38232963-35177412-3743-11e8-9cc5-b48b2b2c7ddc.png)

Key here being *Required field*, *Unique field*, and *Accept only specified value* — which I have set to `ugs` (you can change `ugs` to whatever, I choose it because it’s my client’s initial).

## Creating the entry
I then create an entry, the only valid entry for the entire Content Model. When user tries to create another entry, he/she won’t be able to publish it, because I have reserved the only valid protection keyword.
![image](https://user-images.githubusercontent.com/16177372/38233153-c2cb0292-3743-11e8-80db-beef5334d4d7.png)

## Querying with Gatsby
Now, querying with Gatsby is easy, you don’t even have to know the ID of the entry.
### pages/index.js
```
export const query = graphql`
  query HomeQuery {
    contentfulPageHome(protection: { eq: "ugs" }) {
      metaDescription {
        metaDescription
      }

      bannerImage {
        description
        resize(width: 1344) {
          src
          width
          height
        }
      }

      bannerCopy {
        childMarkdownRemark {
          html
        }
      }

      ...FeaturedBrandFragment
    }
  }
`
```

### pages/about.js
```
export const query = graphql`
  query AboutQuery {
    contentfulPageAbout(protection: { eq: "ugs" }) {
      metaDescription {
        metaDescription
      }
      introduction {
        introduction
      }
      stats {
        internal {
          content
        }
      }
    }
  }
`
```

**Comment by squaredindex** [comment]
@ryanditjia Thank you so much for giving such a complete & clear explanation, that was incredibly helpful! 😁

This sort of setup will work perfectly for my client.

**Comment by squaredindex** [comment]
@grantly7 Thanks for sharing those resources, looking forward to really diving in and learning as much as possible.

**Comment by ryanditjia** [comment]
No worries. It’s a workaround and can be bypassed by a naughty user deleting the entry and creating a new one from scratch. Just have to tell them not to do that 😃. Consider closing the issue if it’s solved your problem.
