### ISSUE TITLE
Default font-size is non-standard

### ISSUE THREAD

**Issue by grod220** [gatsbyjs/gatsby#4851]
Looks like the default css sheet uses a 112.5% default font size. This means all rem values will be relative to 18px instead of the normal browser default of 16px. Makes it just slightly off what sizes one expect if they've been working with the normal 100% value.

```
html {
  font: 112.5%/1.45em georgia, serif;
  box-sizing: border-box;
  overflow-y: scroll;
}
```
Further, there is a media query to resize this at very small screen sizes. Quite surprising if you didn't realize this was here.
```
@media only screen and (max-width: 480px) {
  html {
    font-size: 100%;
  }
}
```

### Solution

Set default font-size on html element to be 100%, remove media query, and convert all default rem values accordingly (value * 18 / 16).

**Comment by fk** [comment]
Hey @grod220! 👋
We define all of that in `www/src/utils/typography.js`:

baseFontSize: https://github.com/gatsbyjs/gatsby/blob/02a0f40ed33f0fad2741ae131c650158c41c2457/www/src/utils/typography.js#L52

16px for < 480px: https://github.com/gatsbyjs/gatsby/blob/02a0f40ed33f0fad2741ae131c650158c41c2457/www/src/utils/typography.js#L239-L244

17px for < 768px: https://github.com/gatsbyjs/gatsby/blob/02a0f40ed33f0fad2741ae131c650158c41c2457/www/src/utils/typography.js#L245-L249

Since we (at least try to ;-)) make all our typography-related definitions relative to the font-size of the root element (using [typographs.js](https://github.com/KyleAMathews/typography.js)' `scale`), am I right that your proposed solution is mostly about making the default font size easier to understand (and "more mobile-first")?

> Set default font-size on html element to be 100%, remove media query, and convert all default rem values accordingly (value * 18 / 16).

We'd still need a media query to scale up the root font size to 17/18px as the screen gets bigger, so things wouldn't get (much) simpler, just a little different.

**Comment by fk** [comment]
Btw., the breakpoint constants we're using are from here: https://github.com/KyleAMathews/typography.js/blob/34a98113ac6117ca74a8641adab9be8994abfe9f/packages/typography-breakpoint-constants/src/index.js

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
