### ISSUE TITLE
Rename top-level "docs" directory to "content"

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#4874]
Anyone have a problem with this? It's bugged me for a while that paths to docs pages is `docs/docs/` :-)

Also because blog posts and other content are in there so "content" is a more neutral label.

**Comment by rstacruz** [comment]
Hey Kyle! This seems kind of strange to me, because now there isn't a top-level `docs/` where I'd expect one to be. It's also very strange to have both `www/` and `content/` in the top-level, as those 2 words seem functionally-equivalent.

(This is mostly me playing devil's advocate, it's not that big of a deal, really.)

Maybe naming the directories as `www.gatsby.org/` and `docs.gatsby.org/`? This'd preserve the congruence that the directory names correspond to URLs (where `www`/`docs` used to correspond to subdomains, but `www`/`content` doesn't)

**Comment by KyleAMathews** [comment]
Yeah, that's a good point — `docs` is a very common top-level directory.

Though actually this is a good reason to rename it because people keep trying to read the Gatsby docs on GitHub — which we don't want — and submit PRs "fixing" links, etc. that don't work on GitHub but do on gatsbyjs.org :-)

`www` is pretty ambigious for the website code — perhaps yeah just naming that directory gatsbyjs.org would make it more clear. There's a possibility we'll be maintaining additional websites in the future in the monorepo so making the directory name clearer would help there too.
