### ISSUE TITLE
[gatsby-image] Scale image to height of container

### ISSUE THREAD

**Issue by martynhoyer** [gatsbyjs/gatsby#4898]
I'm not sure if this is possible and my brain is now fried looking at it, so I'm asking the question here.

I want to load a gastby-img `<Img>` inside a modal (lightbox-style) but have the modal dimensions (and therefore, the image) not exceed the current viewport. The modal styles are fairly straight forward, but when I put the image in there, it can break out of the container, because of the absolute positioning and aspect ratio stuff. 

Ideally it would just adhere to a max width/height of 100% and just scale whichever axis down accordingly. 

I'm using the `sizes` option to get maximum responsiveness - I suspect using `resolutions` would be more straight forward, but since it could be a giant (or tiny) viewport, I don't think that's viable.

Any suggestions?

**Comment by pieh** [comment]
This is proabaly hack - but I think you can use `gatsby-image` with `resulutions` prop (to set width and height to 100%), apply custom style to set `object-fit` to `contain` instead of default `cover` and in query actually use `sizes` query for `srcSet` values.

Alternatively you could build custom react component that would fit your needs.
