### ISSUE TITLE
Does this work with Preact?

### ISSUE THREAD

**Issue by matthewmueller** [gatsbyjs/gatsby#495]
Hey there! Super interested in trying this out, but curious if this works with Preact or is it tied to React?

**Comment by KyleAMathews** [comment]
It *should* just work with Preact if you include the preact-compat package and [setup Webpack](https://github.com/developit/preact-compat#usage-with-webpack). There was problems with react-router but [those were fixed a few months ago](https://github.com/developit/preact-compat/issues/47). I'm planning on experimenting with it myself as Preact is awesome but haven't got to it yet — would love to hear about your experience! Please report back if you try it and tell us how it went! With the plugin support coming to Gatsby 1.0, I'll be adding a plugin so it's very easy to get going.

**Comment by Rusta** [comment]
Has anyone been able to get this working? I'd be really interested to see the difference in bundle.js size if it is possible to switch to Preact. I've had a feeble attempt at getting this working by adding a gatsby-node.js file with a modifyWebpackConfig function but no joy as yet... (as I'm not overly sure what needs to be added and where)

**Comment by Rusta** [comment]
In response to my own comment, I worked out what needed to be updated in gatsby-node.js (based on https://www.npmjs.com/package/gatsby-plugin-preact) and the bundle.js file size dropped from 430KB to 318KB as a result of switching to Preact. 

Still a rather large file for my use case unfortunately.

**Comment by KyleAMathews** [comment]
Cool, glad you found that :-) Just switched my blog yesterday to Preact with it.

What's your use case? 318KB is before gzipping so that should be around 100kb gzipped which is pretty decent. You could also try using https://github.com/rodneyrehm/source-map-explorer on your bundle.js to see if there's anything else that can be trimmed out.

**Comment by Rusta** [comment]
My use case isn't particularly grand, I'm just building a simple website with tabular data (literally just a handful of pages with data in HTML tables) and I wanted to add a sprinkle of JavaScript for filtering the views - while still staying SEO / no JavaScript friendly. 

I was a bit put off by how big the JS file was - 318KB - compared to how big the rest of the site assets will be - however as you say, when gzipping is taken into account it's not as much of an issue.

At that time I was basing this on the main 'gatsby-starter-default' repo. However, I've since stripped away the parts of the starter that were not relevant to how I wanted to use the main gatsby engine (e.g. stripped out the typography stuff and a few of the other React component dependencies) and the bundle file is now down to 136KB (38KB gzipped)

So I am back in a gatsby build wonderland!

I'll definitely check out the source-map-explorer - thanks

**Comment by KyleAMathews** [comment]
Sweet! That's like 9kb more than jQuery :-)

Yeah I'm really keen on Preact. Most Gatsby sites need relatively little on the frontend. Mainly the component abstraction and client side routing. So the extra nicities of react are a bit wasted. With the plugin system in 1.0 it'll be a lot easier for people to play with options.

**Comment by pomber** [comment]
@Rusta any chance to get that stripped down site with preact as a starter?

**Comment by Rusta** [comment]
I've created two 'barebones' starter repos

One that is just a trimmed back starter kit https://github.com/Rusta/gatsby-starter-barebones 

The other is a clone of that but switches in Preact in the build step https://github.com/Rusta/gatsby-starter-barebones-preact

Should add these to the docs I guess

**Comment by KyleAMathews** [comment]
@Rusta would love a PR!

**Comment by Rusta** [comment]
@KyleAMathews done

**Comment by misterbrownlee** [comment]
set-preact-mode: DO_WANT

**Comment by KyleAMathews** [comment]
@misterbrownlee checkout @Rusta's work! https://github.com/gatsbyjs/gatsby/issues/495#issuecomment-294976027
