### ISSUE TITLE
NetlifyCMS Plugin Missing /dist folder in v2.0.1

### ISSUE THREAD

**Issue by blargity** [gatsbyjs/gatsby#5009]
## Description

We're trying to upgrade to the latest version of the Netlify CMS plugin, but are getting a build error.

```
error There was an error compiling the html.js component for the development server.

See our docs page on debugging HTML builds for help https://goo.gl/yL9lND


  Error: Module not found: Error: Cannot resolve module 'netlify-cms/dist/cms.css' in <my_project_path>/node_modules/gatsby-plugin-netlify-cms
  resolve module netlify-cms/dist/cms.css in <my_project_path>/node_modules/gatsby-plugin-netlify-cms
    looking for modules in <my_project_path>/node_modules
      <my_project_path>/node_modules/netlify-cms doesn't exist (module as directory)
    looking for modules in <my_project_path>/node_modules
      <my_project_path>/node_modules/netlify-cms doesn't exist (module as directory)
...etc... (repeats quite a few times)
```

### Steps to reproduce

I presume you could take the NetlifyCMS starter and upgrade it to the latest version and see the same.

### Expected result

I should be able to use NetlifyCMS with Gatsby.

### Actual result

Because the `/dist` folder wasn't published to NPM, the build fails.

### Environment

(I suspect this doesn't matter but will supply more info if needed.)

### File contents (if changed):

(I suspect this doesn't matter but will supply more info if needed.)

**Comment by blargity** [comment]
I suspect this is just that I didn't correctly install the peer dep. Will re-open if necessary.

**Comment by comerc** [comment]
I have the same bug. We need to add 'netlify-cms' package for fix it.

**Comment by jephjohnson** [comment]
This is still an issue when updating your modules.

```
"dependencies": {
    "bulma": "^0.7.1",
    "gatsby": "^1.9.277",
    "gatsby-link": "^1.6.46",
    "gatsby-plugin-netlify": "^1.0.21",
    "gatsby-plugin-netlify-cms": "^2.0.1",
    "gatsby-plugin-react-helmet": "^2.0.11",
    "gatsby-plugin-sass": "^1.0.26",
    "gatsby-plugin-sharp": "^1.6.48",
    "gatsby-remark-images": "^1.5.67",
    "gatsby-source-filesystem": "^1.5.39",
    "gatsby-transformer-remark": "^1.7.44",
    "gatsby-transformer-sharp": "^1.6.27",
    "lodash": "^4.17.10",
    "lodash-webpack-plugin": "^0.11.5",
    "netlify-cms": "^2.0.9",
    "prop-types": "^15.6.2",
    "react": "^16.4.2",
    "react-helmet": "^5.2.0",
    "uuid": "^3.3.2"
  },
```

Error: Module not found: Error: Cannot resolve module 'netlify-cms/dist/cms.css'

**Comment by visti** [comment]
Having the same issue as OP. netlify-cms is listed as a dependency, but develop throws the same errors as in the original post.

**Comment by kenjwho** [comment]
I was having the same issue and a fixed by running `npm install --save netlify-cms gatsby-plugin-netlify-cms@next` as now documented [https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-netlify-cms](url)

I did end up running into a couple other issues that Im not sure if they are related.   Incase it helps here they are:

Error: `Cannot find module '@babel/runtime/helpers/interopRequireDefault'`
Fix (not sure if correct): `npm install @babel/runtime@7.0.0-beta.55`

Next Error: `TypeError: Cannot destructure property 'createHash' of 'undefined' or 'null'. `
Fix (not sure if correct): Removed node_modues `rm -rf node_modules`.  Then ran `yarn` to reinstall.  `npm install` did not work.

I hope this helps as I'm no expert.
