### ISSUE TITLE
404 page layout

### ISSUE THREAD

**Issue by b0gd4n** [gatsbyjs/gatsby#5045]
I've got one layout with header, children and footer inside.
I want the 404 page (`pages/404.js` - which is one of the children) to not contain the header/footer in the layout - what's the best way to tackle this?

Thanks

**Comment by m-allanson** [comment]
Check out the [Creating and modifying pages](https://www.gatsbyjs.org/docs/creating-and-modifying-pages/#choosing-the-page-layout) section of the docs.

**Comment by b0gd4n** [comment]
I am still struggling to get this to work. I am currently checking the location in the `layout.js` file to decide if I render the header/footer or not.
What I want to do is render only the `pages/404.js` page without the header & footer.

**Comment by ryanfiller** [comment]
I came across this while trying to do the exact same thing you are doing.

I'm not sure the validity of this solution, but it does work.

I want to hide the header on my 404 page, so inside my single layouts/index.js file I added this ternary.

`{
    this.props.location.key ?
        <Header />
    : ''
}`

This means that if a page does not return a valid key from Gatsby's routing, the header is not displayed. Any page that IS found (so not a 404), will return a key. Since these are dynamically generated this won't work to add logic to any specific page, I am successfully using this to hook into 404.js.

**Comment by ryanfiller** [comment]
As an update to this, I'm finding that appending hash links to the url (ex. /portfolio/#header) will also trigger `this.props.location.key` to return undefined.

I have modified my ternary to check against `this.props.location.key || this.props.location.hash`, however I do realized this locks you out of linking to has link on your 404 page.
