### ISSUE TITLE
CHANGELOG about major release

### ISSUE THREAD

**Issue by huchenme** [gatsbyjs/gatsby#5054]
Recently I noticed that [gatsby-remark-prismjs](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-remark-prismjs) bumped to version 2. But I could not find the changelog at all. 

Where is the best place to find the breaking changes?

**Comment by pieh** [comment]
`prismjs` was moved to peerDepedency meaning now you have to install `prismjs` yourself

`npm install --save gatsby-transformer-remark gatsby-remark-prismjs prismjs`

instead of just

`npm install --save gatsby-transformer-remark gatsby-remark-prismjs`

But you have good point about changelog not being there - would you be interested in documenting that change?

**Comment by huchenme** [comment]
@m-allanson Thanks, I just replied to one of the issues here: https://github.com/gatsbyjs/gatsby/issues/3920#issuecomment-383047438. It will be great if we could have automatic CHANGELOG setup

**Comment by Undistraction** [comment]
A CHANGELOG would be really helpful. It's hard to track changes and the addition of new plugins. It would certainly be worth removing the current, very stale one.
