### ISSUE TITLE
SyntaxError: Unexpected reserved word

### ISSUE THREAD

**Issue by luandro** [gatsbyjs/gatsby#54]
Just installed a fresh copy of gatsby, and created a blog. When I try to run `gatsby serve` I get this error:
```
/usr/local/lib/node_modules/gatsby/lib/utils/serve.js:2
import Hapi from 'hapi';
^^^^^^
SyntaxError: Unexpected reserved word
```

Seems like babel isn't running for some reason. Any clues?

**Comment by KyleAMathews** [comment]
I think I removed it accidentally earlier... though it was working on my
machine. I'll be home in a bit and will fix and release. Thanks for filing
an issue!

In the meantime downgrade to 0.5.0 which is almost identical.

**Comment by luandro** [comment]
:+1:

**Comment by KyleAMathews** [comment]
Hmmm... so babel-node doesn't work with globally installed packages...
https://github.com/babel/babel/issues/1889

It's suggested that you pre-compile your code... not fun...

**Comment by KyleAMathews** [comment]
Ok, I *think* things should work now with 0.6.1.

@gesposito looks like we're either going to have to go vanilla ES5 or pre-compile code.

**Comment by gesposito** [comment]
What are the steps to reproduce this?
I have 0.6.0 -g installed and I tested serve against all the starters and they worked.

**Comment by KyleAMathews** [comment]
Basically that :) Did you run `npm link` though against your local clone of Gatsby? It *does* work in that scenario which is why I didn't detect it until @luandro reported the bug.

**Comment by gesposito** [comment]
Yeah, I still had the `npm link`ed version on.
I'll take a look at it if I can.

**Comment by gesposito** [comment]
So, I dug a bit, and found that `babel` actually might ignore `gatsby` because its ignore includes `node_modules` where `gatsby` is `npm install`ed (as per https://github.com/babel/babel/issues/1270 https://github.com/babel/babel/issues/1889 as you referenced).

Some solutions that I couldn't get to work are:

### reverse ignore `gatsby`:
```
require('babel/register')({
  ignore: /node_modules\/(?!gatsby)/
});
```

### use 
```
#!/usr/bin/env babel-node
```
### or spawn a child process/command
```
./node_modules/.bin/babel-node --harmony ./bin/cli.js
```
Note, both `babel-node` based solutions are [not meant for production use](https://babeljs.io/docs/usage/cli/).

Last one, that is the advised solution is to precompile, such as
```
"compile": "coffee --output dist --compile lib && babel -d dist/ lib/",
"prepublish": "npm run compile"
```
that would require some project restructuring.

**Comment by KyleAMathews** [comment]
Thanks for your research! Yeah, precompile is doable but takes some careful setup.
