### ISSUE TITLE
[v2] Since gatsby@2.0.0-alpha.16, the main package entry point is unavailable

### ISSUE THREAD

**Issue by kripod** [gatsbyjs/gatsby#5410]
## Description

In gatsby@2.0.0-alpha.13, the main entry point is [available](https://unpkg.com/gatsby@2.0.0-alpha.13), but since gatsby@2.0.0-alpha.16, [it cannot be found](https://unpkg.com/gatsby@2.0.0-alpha.16), thus, eslint-plugin-import's [`import/no-unresolved`](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-unresolved.md) rule cannot pass.

### Environment
* Gatsby version (`npm list gatsby`): 2.0.0-alpha.32
* gatsby-cli version (`gatsby --version`): 2.0.0-alpha.32
* Node.js version: 8.11.1
* Operating System: Windows 10 x64

**Comment by m-allanson** [comment]
The `browser.js` file was removed in #4887. In [the diff](https://github.com/gatsbyjs/gatsby/pull/4887/files) you can see the file `packages/gatsby/src/browser.js` was removed, along with the `browser` entry from `packages/gatsby/package.json`. The `main` entry was left unchanged.

This was replaced with a [webpack alias mapping `gatsby` to `.cache/gatsby-browser-entry.js`](https://github.com/gatsbyjs/gatsby/blob/aa7ca665972143053f1f55d058a5e64c953e01d5/packages/gatsby/src/utils/webpack.config.js#L342-L344).

I guess this can be fixed by updating `main` in `packages/gatsby/package.json` to point to `.cache/gatsby-browser-entry.js`?

`gatsby-browser-entry.js` contains uncompiled ES6 and JSX, but I think that'll be fixed by #4402.

**Comment by pieh** [comment]
Closed by #5481
