### ISSUE TITLE
Programmatic blog pages without using markdown?

### ISSUE THREAD

**Issue by brohlson** [gatsbyjs/gatsby#5453]
Hey Gatsby team, 

I'm trying to couple Gatsby with Graph CMS, so I'll be getting back a JSON object containing all my blog content.  In pure React, I would make a variable route and query the JSON object with the slug that the user has hit.  

I haven't been able to find much documentation on building a programmatic blog without using markdown.  

Is it possible?  And if so, could you link me to any documentation you may have?

Thank you!!

**Comment by daydream05** [comment]
Hey there's a plugin for Graph CMS that will allow you to grab your data and access it through GraphQL. https://github.com/GraphCMS/gatsby-source-graphcms/blob/master/README.md

Basically from the Gatsby tutorial about programatically creating pages, you can use the same principle. Instead of using, MarkdownRemark, you'll be using allArticle or whatever the name of your node is (which you would automatically get from the plugin). You can use the GraphiQL to check for internal type of your node. 

Hope I was able to help.

**Comment by daydream05** [comment]
Graphcms actuallly released a source code of a gatsby starter that uses graph cms https://github.com/GraphCMS/graphcms-examples/tree/master/gatsby-source-plugin-blog

**Comment by daydream05** [comment]
If you look at the gatsby-node.js, you can see that everytime gatsby creates a page, a path is automatically created depending on that posts slug value. I think that last link i sent is the answer you're looking for.

**Comment by m-allanson** [comment]
Thanks @daydream05! @brohlson this sounds like it's solved? Closing this issue but please re-open or create a new issue if that's not the case.
