### ISSUE TITLE
Pages whose filename end with a dot show as blank page.

### ISSUE THREAD

**Issue by decimoseptimo** [gatsbyjs/gatsby#5487]
Seemingly, pages whose filename end with a dot (e.g. `/pages/blog-title.`) show as a blank page when opened in a new window. They do are fetched with `gatsby-link` though.

This is troublesome for blog pages where the path is a slug based on page titles that end in a dot. I provide code example.

### File contents (if changed)
`gatsby-node.js`:
```js
const slugify = require(`slugify`);
const path = require(`path`);

const makeRequest = (graphql, request) => new Promise((resolve, reject) => {
  // Query for nodes to use in creating pages.
  resolve(
    graphql(request).then(result => {
      if (result.errors) {
        reject(result.errors)
      }

      return result;
    })
  )
});

// Implement the Gatsby API “createPages”. This is called once the
// data layer is bootstrapped to let plugins create pages from data.
exports.createPages = ({ boundActionCreators, graphql }) => {
  const { createPage } = boundActionCreators;

  const getArticles = makeRequest(graphql, `
    {
      allStrapiArticle {
        edges {
          node {
            id
            title
          }
        }
      }
    }
    `).then(result => {
    // Create pages for each article.
    result.data.allStrapiArticle.edges.forEach(({ node }) => {
      createPage({
        path: `/blog/${slugify(node.title, {lower: true })}`,
        component: path.resolve(`src/templates/blog-post.js`),
        context: {
          id: node.id,
        },
      })
    })
  });

  // Query for articles nodes to use in creating pages.
  return getArticles;
};

```

**Comment by daydream05** [comment]
I think it was intended that way since url's usually don't end with a dot unless it's a really special case. 

https://webmasters.stackexchange.com/questions/73934/how-can-urls-have-a-dot-at-the-end-e-g-www-bla-de

According to that link, urls that end in a dot is generated by the DNS and not by a webpage.

I'm assuming your use case is you just want to show articles, would it be okay if you just clean up the title before you slugify it?

str = str.replace(/\.$/, "");

Also, you might want to add a generated number at the end of each title in case 2 articles have the exact title.

**Comment by decimoseptimo** [comment]
Its interesting, because the npm package I was using for creating the slugs was "url-safe". I'll fix it then thanks.

**Comment by daydream05** [comment]
You're using [this](https://github.com/slugify/slugify) right?

Have you tried checking the url without the dot at the end? If it's url safe maybe it automatically created urls without the dot at the end for you.

**Comment by decimoseptimo** [comment]
No, now I changed from https://www.npmjs.com/package/slugify to https://www.npmjs.com/package/slug and the URLs are compliant.
