### ISSUE TITLE
gatsby-source-faker not working

### ISSUE THREAD

**Issue by Whaitiri** [gatsbyjs/gatsby#5523]
## Description

Gatsby Source Faker doesn't seem to pull any data from Faker. I couldn't get it working on my own site following the `using-faker` example, nor by cloning the example and building it myself.

### Steps to reproduce

Download the `using-faker` gatsby example and build it as normal.

### Expected result

Site is able to build, using data pulled from Faker

### Actual result

Unknown field errors on type `'RootQueryType'` during build/develop, and visiting pages on develop gives TypeError

### Environment
* Gatsby version 1.9.261
* gatsby-cli version 1.1.52
* Node.js version 8.11.1
* Operating System: MacOs 10.13.4

**Comment by ryanditjia** [comment]
Can confirm that it doesn’t currently work. The current package doesn’t have the built `gatsby-node.js` in its root directory.

`Screenshot of node-modules`
![image](https://user-images.githubusercontent.com/16177372/40418991-14718f30-5eae-11e8-87f1-047fd2aad22a.png)

Probably an error during npm publish or due to missing `babel-cli` in its dependency.

Perhaps @KyleAMathews @m-allanson could take a look?

**Comment by ryanditjia** [comment]
To get it to work right now, the workaround is manually building:

```sh
cd your_gatsby_site/node_modules/gatsby-source-faker

npm run build
```

Also note that the plugin README currently shows wrong instruction. https://github.com/gatsbyjs/gatsby/pull/5530/files
