### ISSUE TITLE
[gatsby-site] Various Issues In Plugins Library

### ISSUE THREAD

**Issue by Undistraction** [gatsbyjs/gatsby#5541]
I just worked my way through the plugin library and while I was going I noted any missing / blank README's:

* All plugins that are namespaced - @example/example **Blank README**
* gatsby-transformer-readme **Missing README**
* gatsby-plugin-i18n **Blank README**
* gatsby-transformer-pdf-images **Missing README**
* gatsby-source-graphcms **Blank README**
* gatsby-plugin-ant-d **Blank README**
* gatsby-parser-sharp **Missing README**
* gatsby-parser-remark **Missing README**
* gatsby-parser-yaml **Missing README**

I didn't get through all of them but I'll try later and add any more I find.

**Comment by ryanditjia** [comment]
I believe Gatsby checks for README.md in the repo referenced by the `"repository"` field inside `package.json`.

For example: [gatsby-plugin-antd](https://github.com/bskimball/gatsby-plugin-antd/blob/master/package.json)’s README shows up on [npm](https://www.npmjs.com/package/gatsby-plugin-antd) but is missing on [Gatsby site](https://www.gatsbyjs.org/packages/gatsby-plugin-antd/) because `repository` is misspelt as `respository`.

The packages with missing README are mostly remote packages / community plugins—aka those not in [packages](https://github.com/gatsbyjs/gatsby/tree/master/packages) folder.

You can help by sending PR to the respective authors!

**Comment by Undistraction** [comment]
Well something has definitely changed since yesterday as many more READMEs are showing up that were not showing yesterday. 

I think it would be helpful to display a message in cases where a README is blank:

> This README is empty

Instead of displaying nothing (which looks like something has failed to load).

**Comment by ryanditjia** [comment]
That could be because Gatsby [uses Algolia](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-npm-package-search/src/gatsby-node.js) and Algolia has just finished indexing.

[GraphCMS package](https://www.gatsbyjs.org/packages/gatsby-source-graphcms/?=graphcms) seems to satisfy requirements for README to show up, but it doesn’t.

Here’s the result of GraphQL query:

```
{
  "node": {
    "name": "gatsby-source-graphcms",
    "repository": {
      "url": "https://github.com/GraphCMS/gatsby-source-graphcms",
      "host": "github.com",
      "user": "GraphCMS",
      "project": "gatsby-source-graphcms",
      "path": "",
      "branch": "a1291d12c4d7283319e4a9b09a5ad1e727eb4267",
      "head": "a1291d12c4d7283319e4a9b09a5ad1e727eb4267",
      "type": null
    },
    "githubRepo": {
      "user": "GraphCMS",
      "project": "gatsby-source-graphcms",
      "path": ""
    },
    "readme": {
      "childMarkdownRemark": {
        "html": ""
      }
    }
  }
}
```

`readme` has nothing in it, I’m not sure what’s up.

**Comment by KyleAMathews** [comment]
Thanks for looking into this @Undistraction!

Some of those packages need deprecated which will remove them from the repo so I'll do that now.

**Comment by tri613** [comment]
Hi, I have a related question to this issue, I have recently published my gatsby remark plugin [gatsby-remark-twemoji-shortcut](https://www.npmjs.com/package/gatsby-remark-twemoji-shortcut) to the npm, and it could be found on the gatsby plugin library page, but if I clicked on the search result, I will get a "Page not found" like this:
![image](https://user-images.githubusercontent.com/10163715/41398006-881e0814-6fe8-11e8-89a1-796f687e96f7.png)

Did I miss something? Any help will be appreciated, thanks alot!

**Comment by ryanditjia** [comment]
I checked your package.json and it seems you’ve filled the required fields. Check back tomorrow, Algolia indexes in intervals.

**Comment by tri613** [comment]
Got it, thanks @ryanditjia!

**Comment by KyleAMathews** [comment]
@undistraction. There also has to be a redeploy of the website. Your README shows up now https://www.gatsbyjs.org/packages/gatsby-plugin-node-fields/?=fields
