### ISSUE TITLE
[v2] replaceComponentRenderer API got removed

### ISSUE THREAD

**Issue by jquense** [gatsbyjs/gatsby#5552]
#3830 removed it accidentally I think.

**Comment by KyleAMathews** [comment]
Deliberately actually — since the only reason it was added AFAIK is to work around the layout component so we can do page transitions. With the layout component removed, page transitions now work the same as they do normally in React so I assumed this API isn't needed.

Is that not the case?

Even if it is ok to remove, I should have added it to the breaking change list.

**Comment by KyleAMathews** [comment]
https://github.com/gatsbyjs/gatsby/blob/c9d96d6f9335f329ccb1bd7592e7e98e8c7fe86b/packages/gatsby/src/utils/api-browser-docs.js#L56

**Comment by jquense** [comment]
ah ok, so I might leave it in for migrations at least. With the new changes i have no way of programmatically wrapping my existing pages in a component. For big sites that's leaving me with like hundreds of pages to manaully open and wrap in the appropriate layout component.

**Comment by KyleAMathews** [comment]
>For big sites that's leaving me with like hundreds of pages to manually open and wrap in the appropriate layout component.

Woah 😮 

I didn't realize people had other usages for this API but yeah, being able to programmatically wrap the component renderer is a useful thing to be able to do. Also it'd still be useful for page transitions e.g. a plugin which automatically adds page transitions to pages (though in general making that explicit by importing is better).

Want to add a PR adding it back?

**Comment by m-allanson** [comment]
Done in #5600 👍
