### ISSUE TITLE
a11y issues: page nav doesn't trigger assistive tech

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/gatsby#5581]
## Description

Right now, using assistive tech to navigate between pages works, but doesn't announce that the user has reached the next page. This is confusing, so we should find a way to mimic standard navigation behavior when using `gatsby-link` for navigation.

Thanks to @nickcolley for pointing this out! Here were a few suggestions he came up with:

- Focus the page after routing
- Use ARIA live regions
- Use a Service Worker to simulate server routing, but with less lag
  - This seems like the least desirable options, since it would require a full page re-render for all navigation; if someone wants this behavior, they could omit `gatsby-link` to get it.

Nick has done some research and mentioned he'll follow up on this issue with his findings.

This _may_ be an upstream fix for React Router, but let's make sure it's at least working with a11y in mind in Gatsby.

### Steps to reproduce

1. Visit <https://gatsbyjs.org>
2. Start VoiceOver (`command` + `F5`)
3. Use the tab  key to focus on a link in the gatsbyjs.org navigation
4. "Click" the link using `control` + `option` + `space`

It will announce that it is following the link, but will not announce the next page.

### Expected result

After navigation, the new page should be announced. For a working example, visit <https://smashingmagazine.com>, activate VoiceOver, and navigate to the Articles page.

### Actual result

After navigation, nothing happens.

### Environment
* Gatsby version (`npm list gatsby`): V1 & V2
* Operating System: OS X

**Comment by nickcolley** [comment]
Thanks so much for putting this together!

I'm going to put together the research on the possible options we can go down (that you mentioned).

This will include how they perform when using the [most commonly used assistive technologies](https://www.gov.uk/service-manual/technology/testing-with-assistive-technologies#what-to-test).

**Comment by LJWatson** [comment]
Thanks @jlengstorf for the ping.

The trick is to mimic the default behaviour of the browser (and therefore the AT) as closely as possible, and to adopt good practices for authoring content to support this behaviour.

When a conventional page loads in the browser, keyboard focus is returned to the top of the viewport. This enables keyboard users (whether they use an AT or not), to explore the page from the top using whatever techniques they're used to. It also causes screen readers to announce the content of the ```<title>``` element - the first indication a blind person has that they've reached their intended destination.

It is good practice to give each page in a website/webapp a unique title that concisely describes the primary purpose of the content. It's also useful if the page title is reflected in an ```<h1>``` heading at the start of the main content area.

To make this happen in an SPA you need to fake it: use JS to take keyboard focus to the ```<body>``` element (or nearest sensible container) when the view is replaced/updated, replace the ```<title>``` element with something unique to the current SPA view, and update the ```<h1>``` (assuming it's there) at the start of the main content area accordingly.

**Comment by jlengstorf** [comment]
Thanks so much, @LJWatson!

Since Gatsby won't be able to control the `<title>` or `<h1>` parts of the app, we'll have to focus on what we can:

1. Let's add a11y docs to talk about best practices (#5592)
2. We can (hopefully) patch `gatsby-link` to focus on the Gatsby container div after page transitions

I just ran a local test that appears to confirm page navigation works as expected after adding a step that focuses the `___gatsby` wrapper after navigation. Will open a PR shortly.

**Comment by LJWatson** [comment]
One thing I should have mentioned, is that when a conventional page is loaded and keyboard focus is returned to the top of the viewport, screen readers will automatically announce the ```<title>``` element and then start to read the content of the page. When faking it for an SPA, the content of the page may not be automatically read by the screen reader - but this is ok, because focus is in the expected place and the user can explore the content for themselves from this logical starting point. Worth mentioning in case it comes up when you test your fix.

**Comment by jlengstorf** [comment]
Thanks @LJWatson! I was able to confirm with VoiceOver that the fix I'm proposing in #5593 causes the page title to be announced. If you don't mind, once it's merged I'd love to send you a link for confirmation that it's working as you'd expect.

**Comment by nickcolley** [comment]
As far as I know, this is a fairly well documented problem but no projects attempt to fix it by default.

This means it requires pre-existing knowledge of the issue, so the majority of projects are broken.

Ember.js community have a great add-on: https://github.com/ember-a11y/ember-a11y.

While this is not very scientific, if we check how often this is downloaded compared to the `ember-cli` package, you can see how many people actually opt-in to this.

127 downloads vs 85k downloads
http://www.npmtrends.com/ember-a11y-vs-ember-cli

**Comment by LJWatson** [comment]
@jlengstorf No problem.

@nickcolley
My hunch is that most screen reader users wil think the link (or whatever they activated) is broken, because to all intents and purposes nothing will have happened. Focus will remain on the link and/or be cut loose if the link isn't present in the new view and the page title won't have been announced. Unless they choose to go exploring, people are likely to be oblivious at worst and very confused at best I think. Understanding development certainly helps me figure these things out for sure though!

**Comment by marcysutton** [comment]
I think we need to reopen this, as I'm not hearing page changes announced on my website or gatsbyjs.org now that @reach/router is in place. The resetting of focus to the top of the page works fine, but I don't hear anything announced when I navigate through top-level pages in Voiceover with Safari and Chrome, IE11 and JAWS, or Edge and NVDA. I can open an issue with Reach Router as well, but rather than open a new issue I thought I'd keep the discussion here. It seems like we need to more to communicate to screen reader users here (and hence [tweets like this one](https://twitter.com/5t3ph/status/1096447164715356160)). 

One odd thing with NVDA or JAWS on gatsbyjs.org is when I navigate to  `/docs`, I hear probably the `aria-current` value for link for some reason, like it's rendering before focus is reset to the top of the page. But it only happens on `/docs`.

Can someone test a bit with one of the above screen readers as well to make sure I'm not imagining this regression? :)

**Comment by marcysutton** [comment]
Update: I'll do some more testing of my own once the CSUN Assistive Tech conference is over, but I'm also doing prototype testing with people with disabilities to try and establish a best practice: https://marcysutton.com/prototype-testing-accessible-clientside-routing/

**Comment by nickcolley** [comment]
@marcysutton thanks Marcy, let me know if you need any help!

**Comment by marcysutton** [comment]
Not stale, just juggling priorities. This is still in progress

**Comment by mattcdowning** [comment]
@marcysutton Can confirm not hearing page changes announced on MacOS with VoiceOver in Chrome/Safari.

**Comment by kencoxdesign** [comment]
Any update on this? Just finished my first Gatsby site and really don't feel comfortable releasing it with such a huge accessibility hole. Safari/Voiceover is not managing page change focus at all for <Link>s

**Comment by marcysutton** [comment]
@kencoxdesign yes! I've been conducting user testing on [accessible client-side routing](https://marcysutton.com/prototype-testing-accessible-clientside-routing/) for the past month, determining the best way forward to serve people with disabilities beyond screen reader usage only. The latest code development is that we have #13197 to merge, which will make an incremental improvement to at least announce page changes in assistive technology–but we want to improve this even further to handle focus and announcements in a way that better supports keyboard users and screen magnification. So stay tuned for more on that front.

**Comment by marcysutton** [comment]
This issue can be closed with the merge of #13197! But this effort is not over yet–stay tuned for more information about what I uncovered with user testing and how to make routing even more accessible.

**Comment by mattcdowning** [comment]
@marcysutton I'm still not hearing page change announcements with Gatsby 2.13.2 using Voiceover in Safari on MacOS in [@pieh's](https://5cf57f3314a67857eb443b8d--gatsby-org-pieh-previews.netlify.com/tutorial/) and my [gatsby-starter-default](https://optimistic-ptolemy-948f38.netlify.com) example.

**Comment by marcysutton** [comment]
@mattcdowning bummer! I can reproduce that now with an upgraded test project, too. I tested this more fully before to support assistive technology beyond Chrome and Voiceover, and I'm not sure where it went wrong. I'll reopen the issue for now since it still isn't addressed, and needs to be. Thanks for the heads up.

**Comment by marcysutton** [comment]
To follow up on this: we are investigating and working on some improvements. Stay tuned.

**Comment by marcysutton** [comment]
Alright folks, here's what I have to report:

This issue isn't actually Gatsby-specific: it stems from @reach/router not providing consistent announcements when a wrapper DIV is focused ([Test case in a Codesandbox](https://codesandbox.io/s/reach-router-starter-v1-tf8el)). The wrapper element currently has `role="group"` and `tabindex="-1"`, but Voiceover needs an `aria-label` to expose an accessible name and NVDA wants a different role: `"status"` and `"application"` are two working candidates right now, but neither of these solutions are particularly great. I could possibly live with `role="status"` to get announcements working in NVDA, but there are likely side-effects in Talkback and we'd want to test it thoroughly. `role="application"` is an absolute no-go as it would sabotage the [screen reader experience](https://marcozehe.wordpress.com/2012/02/06/if-you-use-the-wai-aria-role-application-please-do-so-wisely/) for all Gatsby sites and isn't worth it in my opinion.

Focusing on a heading in the newly changed content area would be fantastic but it's in the realm of "userland" where we can't control what goes in there. Hence the idea to focus on a wrapper element. It's worth adding that this wrapper focus approach is intended to be a _fallback method_ as more component-driven approach is introduced that provides better functionality and access to a range of users with disabilities. For more on that approach, my blog post is up in PR form now (and open to comments). https://github.com/gatsbyjs/gatsby/pull/15579

**Comment by kishba** [comment]
@marcysutton I *loved* that blog post. It really has me thinking about how a button could be added programmatically to receive focus. I wonder if it would be distracting or too repetitive if the button's label was automatically informed by the first heading within the new content (if one existed)?

**Comment by marcysutton** [comment]
@kishba that's sort-of what I was thinking–using `aria-labelledby` pointed to a nearby heading to label it. But we'll need some more testing on that part. Once I've got a solution working I'll circulate it to get some input from users.

**Comment by kencoxdesign** [comment]
@marcysutton Great blog post, and I'm glad your testing also caught the aria-current issue. I was already looking into what it would take to add that myself. Would need to add aria-current under the same conditions that the existing css class is added to visually highlight the currently active link.

**Comment by PigeardSylvain** [comment]
Is it possible to disabled frontend router to keep a standard way of loading pages ? I think it's the safest way for everyone to access the content.

**Comment by nickcolley** [comment]
@PigeardSylvain I think that Gatsby should take a step back and review the user needs that led them to making this decision in the first place.

For example, one of the drivers for client side routing is for fast page transitions, this can be achieved with better caching via Service Workers.

This way users can get really quick pages while getting the benefits of full page refreshes.

**Comment by PigeardSylvain** [comment]
I agree that the speed of loading is a positive point to work on. However, there are accessibility laws in Europe (and in other countries) that cannot be satisfied by the current functioning and that prevent us from using the product.

**Comment by eps1lon** [comment]
> This way users can get really quick pages while getting the benefits of full page refreshes that I have listed above.

To be honest I personally would prefer standard navigation anyway. Client side routing without a signifier (vanilla routing has this by adding the loading spinner in the tab, client side routing needs transitions) can be confusing ("did something actually happen?"). 

Wasn't there some research that suggested that some actions can be too fast i.e. users should have to wait a minimal amount of time otherwise they don't recognize that an action happened?

**Comment by m-allanson** [comment]
See https://github.com/gatsbyjs/gatsby/pull/19290 for our current research into accessible routing in Gatsby.

**Comment by madalynrose** [comment]
# Update: 
Our first iteration of accessible client-side routing has been released! Because this issue goes so far back and it's taken us a while to create a deliverable, I'd like to spend some time highlighting the work that went into this improvement, roadblocks that came up during development, and our hopes for future iterations.

With #19290, Gatsby announces routing updates using a live region embedded within our Router. This behavior is confirmed for the following technologies:
* NVDA + Firefox
* NVDA + Chrome
* Safari + VoiceOver
* Chrome + VoiceOver
* NVDA + IE11
* Narrator + Edge
* Safari + VoiceOver (iOS)
* Chrome + TalkBack (Android) 
NOTE: Talkback reliably announces each update twice. We were able to minimize bugs in all other testing conditions, but this one seems potentially unfixable. Please let us know if you have a solution. 

# Work so far
The largest effort in implementing this improvement was in the research phase. @marcysutton  has written about her efforts in the comments above, but I'll summarize here as well. Gatsby worked closely with Fable Labs in July 2019 to gather feedback from users with disabilities on a set of prototypes with navigation techniques for JavaScript web apps. You can read more in this [blog post](https://www.gatsbyjs.org/blog/2019-07-11-user-testing-accessible-client-routing/), which was updated just recently (January 2020). Based on the July 2019 testing and additional testing done at the [Inclusive Design 24 Virtual Conference](https://www.youtube.com/watch?v=Tr21FqQQv-U) in October 2019, it was determined that we should:
* manage focus on page change #13197
* add an ARIA Live Region to announce location on page load #19290

I was hired in October 2019 to pick up these efforts. Additional constraints applied to this project, as implementing these changes in Gatsby core is different than implementing them in "userland." This was evidenced by differences in behavior between Marcy's [prototypes](https://marcy.codes/prototypes/routing/) that handled routing themselves and testing sites using Gatsby's core routing.

Once the MVP was created, extensive testing was conducted for as many combinations of free tooling as possible. 

## Next steps
It's clear that our work is not done here. I want to keep iterating and keep improvin go we can raise the baseline accessibility that each Gatsby site ships with by default. 

In order for this issue to not continually expand, we ask that you create new issues for scoped chunks of work (e.g. If you feel especially strongly about Gatsby having an option to turn off client side routing, creating a new issue for that would be fantastic and would help us gauge impact). I'm already creating issues for:
* Localization of "Navigated to" announcement
* Adding configuration options for focus and announcements instead of programmatically inferring what should happen on page change (e.g. allowing developers to specify a component or heading that should signify a page change has occurred)

Thank you all for caring so much about this and helping us make the web better for everyone, one incremental improvement at a time. ❤️ 🚀

**Comment by nickcolley** [comment]
@madalynrose awesome work ❤️ great to see this shipped 👏

**Comment by Wolfr** [comment]
Thanks so much for this work, this is groundbreaking work to make SPAs accessible in general. I can't believe it's only happening just now. We're building a router for [Svelte](https://svelte.dev/) and closely watching this work. If we can contribute back we will.

**Comment by marcysutton** [comment]
Following up here to to ask a specific question of you, @PigeardSylvain, since I'm digging deeper into success criteria for modern web applications. You said:

> there are accessibility laws in Europe (and in other countries) that cannot be satisfied by the current functioning and that prevent us from using the product.

Improvements have shipped since then, and I'm familiar with the EU Accessibility Directive and how it relates to WCAG. But I still wanted to ask if there are specific regulations, guidelines, or success criteria that prevented you from using Gatsby. I have some ideas, but in general there aren't exact requirements for user problems related to client-side routing. So I'd love to hear more from your perspective (or anyone else with relevant input).
