### ISSUE TITLE
Cannot query in gatsby-node file

### ISSUE THREAD

**Issue by tsmith123** [gatsbyjs/gatsby#5677]
I have a very strange scenario and I have spent considerable time trying to establish what the route cause is with no luck. I have managed to boil it down to the very basics and hoping that someone could shed some light on this for me.

My `gatsby-node` file looks like this (I've removed the actual creating of pages for now):

```
const path = require('path')

exports.createPages = ({ graphql }) => {
  const test = graphql(`
    {
      allMongodbTestReviews {
        edges {
          node {
            slug
          }
        }
      }
      allMongodbTestPages {
        edges {
          node {
            slug
          }
        }
      }
    } 
  `)

  console.log(test)
  return test
}
```
and the output of the console.log is:

```
Promise {
  _bitField: 33554432,
  _fulfillmentHandler0: undefined,
  _rejectionHandler0: { errors: [ [GraphQLError] ] },
  _promise0: undefined,
  _receiver0: undefined }
```

You can see there is a GraphQLError which when logged too is:

GraphQLError: Cannot query field "allMongodbTestReviews" on type "RootQueryType". Did you mean "allMongodbTestPages" or "mongodbTestPages"?

**However, when I run the exact GraphQL query in `localhost:8000/___graphql` then it shows the correct results.**

Why can I not run the query in `gatsby-node.js` file???

**Comment by ryanditjia** [comment]
I think that’s got to do with unresolved promises. Try using async await instead:

```js
const path = require('path')

exports.createPages = async ({ graphql }) => {
  const allMongodb = await graphql(`
    {
      allMongodbTestReviews {
        edges {
          node {
            slug
          }
        }
      }
      allMongodbTestPages {
        edges {
          node {
            slug
          }
        }
      }
    } 
  `)

  if (allMongodb.errors) {
    console.error(allMongodb.errors)

    throw Error(allMongodb.errors)
  }

  console.log(allMongodb)
}
```

**Comment by tsmith123** [comment]
Thanks for the suggesting but this results in exactly the same issues/errors.

**Comment by tsmith123** [comment]
Yes, it works with one query.

**Comment by pieh** [comment]
I was looking into `gatsby-source-mongodb` and my first guess would be that `sourceNodes` there (https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-mongodb/src/gatsby-node.js#L6-L42) when used with array of collections will call `done` callback after first collection (`done` callback will tell gatsby to continue with build process, so it will start construct schema without waiting for handling rest of collections).

If you are up for doing some dev work on this - I would recommend changing both `sourceNodes` and helper `createNodes` in `gatsby-source-mongodb` to return Promise instead of using `done` callback (check "Async plugins" in [Gatsby Node APIs](https://www.gatsbyjs.org/docs/node-apis/)) and use Promise.all in case there is array of collections.

**Comment by tsmith123** [comment]
Was thinking of passing array of collections to `createNodes` (whether 1 collection or many) and then the helper could iterate through the collections array, then each document and only then should it call `done()`

What's the process for contributing by the way?

**Comment by pieh** [comment]
Yeah that would work too.

[Link to contributing docs](https://www.gatsbyjs.org/docs/how-to-contribute/#contributing-to-the-repo)

**Comment by tsmith123** [comment]
Well this is a complete blocker for me but I'm not sure I have the time to start delving into Gatsby that much. How likely is it that someone will take this on if I dont?

**Comment by tsmith123** [comment]
Ok, managed to get round to this @pieh. I hope my solution is acceptable. I've issued a PR here: https://github.com/gatsbyjs/gatsby/pull/5738
