### ISSUE TITLE
How to prevent a component from unmounting during a route change?

### ISSUE THREAD

**Issue by kripod** [gatsbyjs/gatsby#5773]
## Summary
I am trying to build a website with a fixed vertically scrollable header, providing similar experience as https://reactjs.org/ does for mobile users. Unfortunately, I couldn't figure out how to keep the header menu's scroll position intact during on-page navigation with `Link`s.

## Relevant information
Source code: https://github.com/reactjs/reactjs.org

### Environment (if relevant)
* Gatsby version (`npm list gatsby`): 2.0.0-alpha.49

**Comment by ryanditjia** [comment]
I’d like to know about this too.

This could fix Gatsby’s own site in v2, where navigating between the programmatically created pages doesn’t reset the Sidebar position. But as soon as you click on, say, `/src/pages/actions.js` or any of the ones listed [here](https://github.com/gatsbyjs/gatsby/tree/v2/www/src/pages/docs), it resets.

![jun-07-2018 20-10-21](https://user-images.githubusercontent.com/16177372/41101677-01ea716e-6a8f-11e8-8976-273d25cdb27b.gif)

**Comment by sbugert** [comment]
One rather hacky solution I found was to add a wrapper component to gatsby-browser.js with `replaceRouterComponent` and gatsby-ssr.js with `replaceRenderer`.

My use case was a div that should not get remounted on page changes because it has animations.

An obvious disadvantage is that some plugins break if you do this. For example, I had to manually add `StyleSheetManager` to gatsby-ssr.js for styled-components to work again (which gatsby-plugin-styled-components already does for you).

Maybe there could be an API to supply a wrapper component? But afaik that would not be too different from the old layout API.

**Comment by juanmaperez** [comment]
I'm in the same problem since I have an animated menu. Instead of scroll, I am losing the animation since the menu component is remounting every single time I change the route to another page

**Comment by LekoArts** [comment]
You can use [`gatsby-plugin-layout`](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-layout) now. It uses the [`wrapPageElement` browser API](https://gatsbyjs.org/docs/browser-apis/#wrapPageElement) (and the [SSR equivalent](https://gatsbyjs.org/docs/ssr-apis/#wrapPageElement)).

Put your navigation and state into the layout and it will persist on page changes / animation will fade-in and fade-out.

**Comment by algebrathefish** [comment]
@LekoArts I have api request that need to be made once a container component to several pages, when I change the route the requests get done again. Will this help in this case? It is not in the layout, one level deeper, thanks
