### ISSUE TITLE
How to use feature flags to disable things?

### ISSUE THREAD

**Issue by ds300** [gatsbyjs/gatsby#5823]
## Summary

I would like to use build-time feature flags (e.g. env vars) to prevent certain pages from being built and certain parts of GraphQL queries from being incorporated.

For motivation context: we want to develop new features and pages against a 'development' contentful space, but still merge those unfinished features/pages into master incrementally, keeping them behind a feature flag until ready for release, without adding test content into the production contentful space.

Is this possible? At the moment I'm getting stuck with build tim errors because 

1. I can't figure out how to provide different versions of GraphQL queries based on feature flags (the development queries might reference fields which do not appear in the production data)
2. I can't figure out how to prevent Gatsby from loading GraphQL queries in JavaScript files that never actually get used when building the production version of the site.

### Environment (if relevant)
* Gatsby version (`npm list gatsby`):
* gatsby-cli version (`gatsby --version`):
* Node.js version:
* Operating System:

### File contents (if changed)
`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by m-allanson** [comment]
You might be able to get some of the way there [using fragments](https://www.gatsbyjs.org/docs/querying-with-graphql/#fragments)? As an example, the [Contentful source plugin exports a series of fragments](https://github.com/gatsbyjs/gatsby/blob/v2/packages/gatsby-source-contentful/src/fragments.js#L10) which [get copied at build time to a fragments directory](https://github.com/gatsbyjs/gatsby/blob/v2/packages/gatsby-source-contentful/src/gatsby-node.js#L203:L206
). I'd guess you could do something similar in your `gatsby-node.js` based on the environment?

For point 2, the code that [pulls in GraphQL queries is in the internal `query-runner` plugin](https://github.com/gatsbyjs/gatsby/blob/v2/packages/gatsby/src/internal-plugins/query-runner/query-compiler.js#L87-L113). It's greedily checking every file rather than just the files used in the project. There's a TODO in the comments for improving how that works, but I'm not sure what the best approach would be.

**Comment by ds300** [comment]
Copying files around in gatsby-node.js might do the trick for now. It's not a ideal approach since it means things behind feature flags need to be kept in surprising places and I'm worried that it might mess up certain aspects of dev tooling like hot reloading 🤔.

Thanks for the note about point 2.
