### ISSUE TITLE
[www/showcase] Screenshots are not rendering non-roman characters

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#5929]
Looks like screenshots in site showcase aren't rendering non-roman characters, like this one in Japanese: https://5b1ac9153672df15a1c3b201--gatsbyjs.netlify.com/showcase/www-yuuniworks-com/

**Comment by KyleAMathews** [comment]
@ThatOtherPerson looks like we need to install some extra packages https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-in-docker Not sure if those packages are available in Lambda.

**Comment by ThatOtherPerson** [comment]
@KyleAMathews Lambda doesn't let you write to anything other than the `/var/task` and `/tmp` directories, so you can't install font packages in the normal locations. I'm hoping there's an environment variable or a Chrome setting where you can add to the font search path. If nothing else works we can probably make a change in the Chromium source code.

**Comment by ooloth** [comment]
Emojis are also not rendered in showcase screenshots:

[https://next.gatsbyjs.org/showcase/www.michaeluloth.com](url)

If there's a way I can manually submit a more accurate screenshot, please let me know!

**Comment by shannonbux** [comment]
oh good catch @ooloth ~

The screenshots are rendered by the plugin `gatsby-transformer-screenshot` and not sure if it's possible to replace the automatic screenshot with a manually chosen one @ThatOtherPerson in the meantime, until someone has time to update the plugin?

**Comment by Yash-Garg** [comment]
SITE is using UTF-8 locale ?

**Comment by missmatsuko** [comment]
This appears to still be an issue.

<img width="394" alt="Chinese characters appearing as boxes." src="https://user-images.githubusercontent.com/17884198/55443185-aaacfe80-5566-11e9-84ee-7edf1ca7778c.png">

<img width="370" alt="Emojis appearing as boxes." src="https://user-images.githubusercontent.com/17884198/55443166-949f3e00-5566-11e9-8a8f-e5ca2a7e8008.png">

**Comment by lannonbr** [comment]
I'll reopen this

**Comment by missmatsuko** [comment]
There's a [Chromium binary for Lambda](https://github.com/alixaxel/chrome-aws-lambda). It includes [a function to download fonts](https://github.com/alixaxel/chrome-aws-lambda#fonts). There's [a link to it from the puppeteer troubleshooting docs](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-on-aws-lambda) and is kept up to date within 2 days. 

Maybe this should be used in `gatsby-transformer-screenshot` instead of puppeteer.

I'm not sure which fonts should be downloaded, though. The puppeteer docs mentions this for Docker:
```
// fonts to support major charsets 
// (Chinese, Japanese, Arabic, Hebrew, Thai and a few others)
fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst ttf-freefont
```

Maybe we should use all the [Google Noto (No Tofu) fonts](https://www.google.com/get/noto/)? Would that be too much?

**Comment by sever1an** [comment]
It might be possible to put the fonts in `~/.fonts`, possibly even setting `$HOME` to something helpful if it is poorly defined in Lambda.

**Comment by LekoArts** [comment]
The screenshots are now sourced from WordPress and not by creating screenshots anymore with `gatsby-transformer-screenshot`. We've taken the screenshots it created though so entries with problems will still have issues. We can manually change the screenshots now though so will need to ask what to do about it now.

**Comment by gillkyle** [comment]
I just made an update to our screenshot on WordPress to fix the site for calpa.me, feel free to let me know if you encounter other sites with this issue. If it's a bigger problem across many sites we can investigate a better automated audit of these kinds of issues, but for now I'm going to close this issue since we no longer use the plugin to take screenshots through a Lambda function anyway 🙂
