### ISSUE TITLE
Update to 0.12.21 generates warnings

### ISSUE THREAD

**Issue by cutemachine** [gatsbyjs/gatsby#593]
I get the following when running `gatsby build`. I get the same for the HTML build step. The version of Gatsby is 0.12.21 on node v5.6.0. Any ideas?

Generating CSS
(node) warning: possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
  at EventEmitter.addListener (events.js:252:17)
  at module.exports (/Users/long/Projects/balla/node_modules/signal-exit/index.js:41:11)
  at module.exports.promise (/Users/long/Projects/balla/node_modules/execa/index.js:146:23)
  at /Users/long/Projects/balla/node_modules/exec-buffer/index.js:35:15

**Comment by briancappello** [comment]
Do you recall what version of Gatsby you upgraded from? I was seeing this warning on 0.12.19 with node 7.1

**Comment by KyleAMathews** [comment]
Hmmm... this is perhaps the most annoying warning node.js does because a) it may or may not indicate a problem (there's plenty of legitimate reasons for having more than 10 listeners) and b) the warning does nothing to help you find the problem (if there is one).

Can you reproduce this one any of the core starters? Or just on your sites?

**Comment by cutemachine** [comment]
Thanks @briancappello, @KyleAMathews. I'm glad to report that this was not related to Gatsby.

This was an error by myself. I had some code in the `gatsby-node.js` and `post-build.js` which did not work.

Sorry I stole your time.

**Comment by briancappello** [comment]
@KyleAMathews @cutemachine  Upon further investigation it seems like the `gatsby-node.js`/`post-build.js`files were red herrings, but that the conclusion of this being unrelated to gatsby was none-the-less correct. 

Upgrading to `signal-exit` to v3.0.2 makes the warnings go away. 

Discovered by modifying the shebang in `bin/gatsby.js` to be `node --trace-warnings` (there must be a better way?!?) then you'll see something like this:
```
> (node:30573) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
  at _addListener (events.js:259:19)
  at EventEmitter.addListener (events.js:275:10)
  at module.exports (/home/brian/dev/gatsby_site/node_modules/signal-exit/index.js:41:11)
  at module.exports (/home/brian/dev/gatsby_site/node_modules/execa/index.js:146:23)
  at fsP.writeFile.then (/home/brian/dev/gatsby_site/node_modules/exec-buffer/index.js:35:15)
```
Which leads to https://github.com/sindresorhus/execa/issues/61 and ultimately https://github.com/tapjs/signal-exit/pull/45, where the issue was fixed just a few days ago.

**Comment by KyleAMathews** [comment]
Nice detective work! What dependencies of ours need upgraded? Could you create a quick PR to upgrade things as needed?

**Comment by briancappello** [comment]
None of the libraries in the traceback are explicit dependencies of gatsby, so as I understand it, npm should pull in the latest version for fresh installs? (execa specifies greater than 3.0.0 for signal-exit)

**Comment by KyleAMathews** [comment]
Haha perfect then. OK cool thanks!
