### ISSUE TITLE
Part 8 of tutorial is not accessible on mobile

### ISSUE THREAD

**Issue by deadcoder0904** [gatsbyjs/gatsby#6110]
https://next.gatsbyjs.org/tutorial/part-eight/ part can't be reached from https://next.gatsbyjs.org/tutorial/

**Comment by m-allanson** [comment]
Thanks @deadcoder0904 - part 8 is still 'under construction', I've added a note to ensure that part 8 is linked up correctly once it's finished (#5607).

Note that there's a project to restructure the docs, which should make the tutorial _and_ docs more accessible on mobile - see the RFC over at: https://github.com/gatsbyjs/rfcs/pull/5

I'm going to close this for now as I think the issue is being handled. Thanks again!
