### ISSUE TITLE
[small DX feature request] timeout when build gets stuck on "source and transform nodes"

### ISSUE THREAD

**Issue by tsiq-swyx** [gatsbyjs/gatsby#6125]
## Summary

In my gatsby work I have noticed that gatsby sometimes get stuck on "source and transform nodes" - usually it takes <10 seconds and sometimes it will just "hang" for minutes. the usual fix is to kill the process and rerun gatsby, but of course that isn't satisfactory.

### Basic example

```
cd www
yarn run develop
```

usually will run into some sort of hanging within the first few attempts

### Motivation

> Why are we doing this? What use cases does it support? What is the expected outcome?

we want better DX. adding a timeout like "this Gatsby process seems to be taking longer than it should. You can report this here (link to URL) and we recommend restarting this process while we figure out what is wrong".

**Comment by KyleAMathews** [comment]
This is a problem with gatsby-transformer-screenshot.

**Comment by polarathene** [comment]
@KyleAMathews is it? I just went to raise a new issue(This one came up when I entered DX in the title).

I'm on what I assume is a slow connection in China with a VPN to the outside world. I ran `gatsby build` on the `using-gatsby-image` example and wondered why it was taking so long or if it had hung(or in some sort of loop). Then I noticed this example is pulling images remotely, 130MB worth..

Is there a way that this stage in the build could provide a little more context/info about it's progress or what it's presently doing within that task? My connection can be unreliable at times, I'm not sure what happens during this process if one of the remote image downloads fails halfway through.

```
$ docker run -it --rm -v $(pwd)/site:/site -p 9000:8000 gatsby-alpine stage
/bin/sh: lscpu: not found
success open and validate gatsby-configs — 0.007 s
success load plugins — 0.152 s
success onPreInit — 0.446 s
success delete html and css files from previous builds — 0.004 s
success initialize cache — 0.047 s
success copy gatsby files — 0.023 s
success onPreBootstrap — 0.017 s
success source and transform nodes — 702.413 s
success building schema — 0.222 s
success createPages — 0.001 s
success createPagesStatefully — 0.023 s
success onPreExtractQueries — 0.002 s
success update schema — 0.092 s
success extract queries from components — 0.121 s
```

**success source and transform nodes — 702.413 s** - 11+ minutes!

The DX could be improved by having something output after running the task for longer than what might be expected usually and overriding that line again whenever the stage is still running for the same time unit since. eg:

> Still processing.. taking longer than expected? Fetching remote sources can take a while (Total time: 3 minutes)

Or..

> source and transform nodes (17/42)

After a minute or so you could append a tip that changes each minute about reasons why it could be taking long?(not actually specific to why, just possible reasons in general)

> source and transform nodes (17/42) - TIP: Remote sources may take a while to retrieve

> source and transform nodes (143/1337) - TIP: Lot of nodes to transform? Good time for a coffee ;)
