### ISSUE TITLE
[v2] Guidelines around layout changes

### ISSUE THREAD

**Issue by jonbellah** [gatsbyjs/gatsby#6127]
## Summary
It's possible that I may be misinterpreting the documentation, but it appears that the suggested method of wrapping pages with a layout component causes those pages to re-render completely upon navigation.

## Relevant information
The docs for layout in v2 say:
```
3. Import and wrap pages with layout component
Adhering to normal React composition model, you import the layout component and use it to wrap the content of the page.

src/pages/index.js

import React from "react"
import Layout from "../components/layout"

export default () => (
  <Layout>
    <div>Hello World</div>
  </Layout>
)
Repeat for every page and template that needs this layout.
```
See: https://next.gatsbyjs.org/docs/migrating-from-v1-to-v2/#update-layout-component

I've followed the guide, wrapping each of the pages in my `/pages/` directory with my new Layout component. I have a little slide down animation on my header on initial page load... following the new `<Layout />` component guidelines causes that to animate every time the page changes.

I understand I can use the `html.js` file or render routes directly from react-router inside my`<Layout />`, but I figured I'd surface the issue I found with the docs (or my misunderstanding of the docs, so that I can help bring a bit more clarity for others following the guide soon).

![gatsby](https://user-images.githubusercontent.com/2601219/41814567-81057c24-770e-11e8-8bda-630d0480a5c4.gif)

The code for this can be found here: https://github.com/jonbellah/jonbellah.com/tree/v2

Relevant pieces of code: 
- https://github.com/jonbellah/jonbellah.com/blob/v2/src/components/Layout.js
- https://github.com/jonbellah/jonbellah.com/tree/v2/src/pages

Please let me know if I can provide any other clarity. I'm interested in contributing back to the docs, if this proves to be something worth addressing there.

**Comment by viktorbengtsson** [comment]
I'm having this exact problem. I would be interested in how to solve it.

**Comment by jonbellah** [comment]
I'm seeing the same issue with the built version: https://5b310bfdc6aed603a12b4cc7--jonbellah.netlify.com/contact/

**Comment by timurc** [comment]
Hey! I also got the same problem. I got into gatsby when it was reaaaally fresh and love it. Now, I am in the process of migrating our website from 0.x and thought "yay I'll just skip v1 and go straight to v2!"

However, I do need components that don't re-render on page transition for my new Ideas. I don't see yet how this is supposed to work. To demonstrate, here is a very barebones start of the new site:

live site: http://gatsby-transition-issue.volligohne.de/
code: https://github.com/timurc/vo-website-2/tree/gatsby-transition-issue

The heading always flashes red when re-rendered with a css transition. The are console.log()s in the layout component when it gets constructed, mounts and unmounts you can check out in the console. Surprisingly, it does not re-render when you use the next and previos buttons. I guess because the markdown based pages share a template.

For me there is no difference between development mode and the build version.

Even if it does not get fixed very soon, I would be very happy if anyone got an idea how to hack around it for now so I dont have to start this new project on v1.

Thanks!

**Comment by jquense** [comment]
I think the way to avoid this is to use [`replaceComponentRenderer`](https://www.gatsbyjs.org/docs/browser-apis/#replaceComponentRenderer) api to add your layout component _above_ the Page component so that page switches don't unmount the Layout.

**Comment by m-allanson** [comment]
Yeah I think using `replaceComponentRenderer` is the best way to handle this at the moment. It doesn't seem particularly intuitive to me, I wonder if there's a friendlier way we can do this?

**Comment by jquense** [comment]
I still think adding a layout plugin that uses that api is the best migration path. It wouldn't handle nested layouts but should be a nice inbetween solution

**Comment by jonbellah** [comment]
I'd be interested in taking a stab at a layout plugin. I don't have any experience with `replaceComponentRenderer`, but I'll dig through the docs and source this evening and come back with questions if I get stuck.

**Comment by jonbellah** [comment]
Okay, so I did a bit of reading through the source and thinking on an approach. 

I'm thinking `plugins: ['gatsby-plugin-layout']` will import the `src/layouts/index.js` file, since most people migrating to v2 will already be using that file (though they should still follow the upgrade guide and remove the `props.children()` function in favor of `props.children`, etc).

Optionally, a different path could be specified:
```
{
    resolve: 'gatsby-plugin-layout',
    options: {
        path: 'src/components/layout.js'
    }
}
```

Then using the `replaceComponentRenderer` API, wrap all pages with the specified layout component.

Limitations that I can see with this approach would be nested layouts, as mentioned, as well as lacking support for multiple layouts.

Thoughts on this approach?

**Comment by timurc** [comment]
Hey everyone, thanks for the hints and ideas and discussion!

I don't quite understand yet how `replaceComponentRenderer` can help me with my case. What I want is somehow a component that survives a page transition without being re-rendered, so that I can keep state there, have css animations running, so do stuff kinda independent of page transitions.

I modified the given example in `replaceComponentRenderer` again to make the heading flash red on transition and log out in the console each time the `Transition` component and the `Layout` component are constructed. It does fade the content, but that's what I need—I would love to have a component that survives the whole time and holds state. 

demo: http://gatsby-transition-issue-2.volligohne.de/
code: https://github.com/timurc/gatsby-transition-issue-2

Maybe I am mistaken but is it maybe also not cool for performance if always everything is re-rendered? Isn't part of the idea of react to only re-render what's needed?

So yes it seems to me such a layout plugin would be really good to have. Apart from that, if this is possible with the current v2 I would be very happy about hints on how to do it :)

**Comment by jonbellah** [comment]
@timurc I don't think you're actually hooking into the `replaceComponentRenderer` API in that demo. I think the docs may be a little misleading, as it looks like the `replaceComponentRenderer` code was removed from that repo sometime after [this commit](https://github.com/gatsbyjs/gatsby/blob/c31d75399fe78ce83e0a946e6c28ee819970260e/examples/using-page-transitions/gatsby-browser.js).

I've been working off the example there, along with the tests I found in `packages/gatsby/src/bootstrap/__tests__/resolve-module-exports.js` and the `PageRenderer` component in `packages/gatsby/src/cache-dir/page-renderer.js`.

I'm still working on a proof of concept... running into some rough edges here and there, but working through them.

**Comment by jonbellah** [comment]
Okay, I'm a little stuck.

I have the `replaceComponentRenderer` stuff working... in v1. ([Demo](https://5b3588f0fdd72a35800fee38--jonbellah.netlify.com/) / [Code](https://github.com/jonbellah/jonbellah.com/blob/v2-test/gatsby-browser.js))

But in v2, I'm getting an error -- `TypeError: (0 , _apiRunnerBrowser.apiRunner) is not a function`. I dug through the code and issue history and @jquense it looks like you may have some experience with this from https://github.com/gatsbyjs/gatsby/pull/5600... any direction you can point me in there is helpful. ([Demo](https://5b35858b792f895d1ca6d657--jonbellah.netlify.com/) / [Code](https://github.com/jonbellah/jonbellah.com/blob/v2/gatsby-browser.js))

**Comment by KyleAMathews** [comment]
`gatsby-plugin-layout` sounds like the best approach. And apologize for thinking about this issue when I did the remove-layout RFC :-\ Ironically, animating layout menu items is the original reason I added the layout concept to v1 😜 

One layout component could be sufficient since it could switch between layouts based on routes. Since it's a normal component, it can do nesting as needed as well.

**Comment by KyleAMathews** [comment]
https://github.com/dantman/rfcs/blob/reparenting/text/0000-reparenting.md would be nice

**Comment by KyleAMathews** [comment]
@m-allanson were you planning on writing `gatsby-plugin-layout`? I think doing something similar to gatsby-plugin-typography where it generates some code based on the options would work well https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-typography/src/gatsby-node.js

**Comment by KyleAMathews** [comment]
Or @jonbellah are you interested in doing a PR?

**Comment by KyleAMathews** [comment]
I verified as well that `replaceComponentRenderer` works as expected. I added to a little site to my gatsby-browser.js the following:

```jsx
const React = require("react");
const Layout = require("./src/components/layout").default;

exports.replaceComponentRenderer = ({ props, component }) => {
  console.log({ props, component });
  return <Layout>{React.createElement(component, props)}</Layout>;
};
```

**Comment by jonbellah** [comment]
@KyleAMathews I'm interested in putting together a PR. I'll work one up this weekend. The code you posted is super helpful. Thanks!

**Comment by jonbellah** [comment]
@KyleAMathews I'm a bit stumped. The `replaceComponentRenderer` code you posted doesn't work for me. 

Tried each of the following steps to no avail.
- Uninstalled my global `gatsby`
- Installed `-g gatsby@next`
- Cleared my `.cache` dir
- Deleted my `node_modules` folder and reinstalled
- Tried node 8.11.3 and 10.5.0
- Tried `children()` and `children` in the layout itself
- Tried with two different code bases (one from scratch)
- Tried `gatsby develop` and `gatsby build`

Always the same error - `TypeError: (0 , _apiRunnerBrowser.apiRunner) is not a function`. Am I missing something there?

**Comment by KyleAMathews** [comment]
Hmm that sucks... I've never seen that error so not sure. Check the generated api-runner-browser.js file in .cache?

**Comment by m-allanson** [comment]
I was looking at this earlier in the week and saw the same error (or
something very similar). I'll dig out some more details on Monday.

**Comment by timurc** [comment]
I do have the same error as @m-allanson and @jonbellah. For me it only happens when I try to import a component to `gatsby-browser.js`, it does not seem to be connected to `replaceComponentRenderer`. So my guess is that something is wrong with the loader...?

Strangely, for me the example of @KyleAMathews does not work because `replaceComponentRenderer` does not get `component`. It is part of the `props` though and then it works:

```javascript
const React = require('react');

// fails when imported: "Uncaught TypeError: (0 , _apiRunnerBrowser.apiRunner) is not a function"
// const Layout = require('./src/components/layout').default;

exports.replaceComponentRenderer = ({ props }) => {
    return <StateTest>{React.createElement(props.pageResources.component, props)}</StateTest>;
};

class StateTest extends React.Component {
    constructor(props) {
        super(props);
        console.log('constructing...'); // Does not fire on page transition!
    }
    render() {
        const { children } = this.props;
        return <div>{children}</div>;
    }
}
```

So in the example above the component `StateTest` only renders once and survives the page transitions! Now the only mystery for me is why I cant import components there. Hope that helps :-)

**Comment by jonbellah** [comment]
@timurc What a find... nice work!

I'll hold off on moving anymore on `gatsby-plugin-layout` until a course has been charted for the import issue, but I'm still very much interested in contributing there.

**Comment by m-allanson** [comment]
This error seems to be triggered if the component you're importing also imports Gatsby's `Link` component.

Here's a demo repo: https://github.com/m-allanson/gatsby-v2-layout-test

This [`gatsby-browser.js`](https://github.com/m-allanson/gatsby-v2-layout-test/blob/c348f5b2e85ff49668e2c9e65a628cd266066eda/gatsby-browser.js#L8-L17) will work after changing [`layout.js`](https://github.com/m-allanson/gatsby-v2-layout-test/blob/c348f5b2e85ff49668e2c9e65a628cd266066eda/src/components/layout.js) to remove the `Link` import.

**Comment by pieh** [comment]
>This error seems to be triggered if the component you're importing also imports Gatsby's Link component.

So this is because from importing from `gatsby` which when we follow imports will cause circular import to browser `apiRunner` (in `loader.js`). I think if we inject `apiRunner` into `loader.js` instead of importing it will fix both this and https://github.com/gatsbyjs/gatsby/issues/6235

**Comment by m-allanson** [comment]
I've opened a PR which fixes the `Uncaught TypeError: (0 , _apiRunnerBrowser.apiRunner) is not a function` error.

However we might need to do some more thinking about how this should work. Using `replaceComponentRenderer` to implement a persistent layout works. But it only renders your layouts on the client, it _doesn't_ SSR render them. You could use the SSR API `replaceRenderer`, but that doesn't play nicely with any other plugin that already uses `replaceRenderer`.

Maybe this calls for a couple of new APIs? something like `wrapPageClient` and `wrapPageSSR`? A `gatsby-plugin-layout` plugin could implement these. They could also be useful for setting up React context providers (although I've not looked into how that works with SSR).

**Comment by jonbellah** [comment]
I see that #6272 made it in this morning. I'll work on `gatsby-plugin-layout` this weekend and report back if I get stuck again.

I agree SSR definitely needs to be handled, I'll dig in on that. I think the new API's sound like a solid approach.

**Comment by jonbellah** [comment]
Just keeping lines of communication open: I have a PoC working, but doing some cleanup. Will have a WIP PR in the next couple days.

**Comment by jonbellah** [comment]
![alertthesegentoopenguin-size_restricted](https://user-images.githubusercontent.com/2601219/42634490-953395c8-85a0-11e8-9a1e-78df4d09cbba.gif)

Still working...

**Comment by jonbellah** [comment]
So I have a conceptual issue that I'm chewing on and could use some thoughts on. I have `gatsby-browser.js` working as expected using `replaceComponentRenderer` (though I haven't implemented the `wrapPageClient` API yet).

I've been working on the SSR side (and have been bouncing off rough edges here and there), and ultimately what I've landed on is one of two approaches.

### Context
At first I was attempting to use `replaceRenderer` and wrap everything with the layout component. The problem here is that the `replaceStaticRouterComponent` API hook happens just before `replaceRenderer`, so if you have a `GatsbyLink` component in your `<Layout />` then you run into an error (since there's no router around your layout).

The other downside of `replaceRenderer` is that only one plugin can implement it (though providing an API for other plugins/devs would help `gatsby-plugin-layout` not be an impediment).

### Question
I'm leaning towards using the `replaceStaticRouterComponent` API, instead of `replaceRenderer`, then implementing the `StaticRouter` directly in `gatsby-plugin-layout` as a wrapper around a specified layout component.

Are there any downsides to this approach that you see? Would it make more sense to implement an API directly in core to wrap components being set as `bodyComponent`?

The other issue I'm having with this approach is that the documentation for `replaceStaticRouterComponent` appears to be TBD, so I'm not sure how stable the API is (and an issue search returned little in the way of results).

Anyways... thanks for being patient as this PR takes me a bit to feel my way around the core codebase and whack-a-mole problems as I run into them.

**Comment by timurc** [comment]
@jonbellah Thanks for your efforts so far! I am missing the time currently to dig into the gatsby source myself at the moment and also lack the deep understanding of the inner workings there but appreciate so much you're looking into it. For my current project, it would be really needed, otherwise the whole concept of the site is kinda not working. I am now trying to find a fix until this lands in the main repo but not very successful so far.

Adding my layout to `replaceComponentRenderer` only works in development for me and fails in build with the following error: 

```
react-dom.production.min.js:188 TypeError: Cannot read property 'markdownRemark' of undefined
    at t.render (blog-post.js:11)
```

The template does not get the `data` it that contains `markdownRemark `. Here is the branch i tried: https://github.com/timurc/vo-website-2/tree/try-saving-state

I now went for a pragmatic way: I save the state in global window object on `componentWillUnmount` to restore it on `componentDidMount`. That feels super stupid and won't help with css animations, but I don't know how else to fix it: https://github.com/timurc/vo-website-2/commit/cb9cf8292fa1df22c728fd89b9e739575a1ba8d5

To give some context, for the kind of playful websites we build this is one huge stand-out feature of gatsby. I know I should not complain about a beta not being feature complete–I just want to elaborate why this is important to us. Transform animations and keeping state / animations running during the route change is one thing a *normal* static website can't do. 

I keep looking forward for movement in this issues or hints on how to work around this! Thanks for your help 🙂

**Comment by jonbellah** [comment]
@timurc I'm still wrapping my head around much of the core codebase, particularly the v2 codebase... I admittedly didn't have a chance to spend much time digging into your specific issue, but it looks like error you're seeing is that `blog-post.js` isn't getting the `data` prop from `pageQuery`. Is that issue present when you remove your `gatsby-browser.js` file?

I saw this issue recently with a duplicate query name, as well (though the console spits out an appropriate error for that).

I ask because I'm wondering if the issue is less with your `replaceComponentRenderer` code and more in line with an issue related to the move towards the [`StaticQuery`](https://next.gatsbyjs.org/docs/migrating-from-v1-to-v2/#4-change-query-to-use-code-classlanguage-textstaticquerycode) work in v2. Though that doesn't *seem* to be the case, I figured it's worth at least asking.

**Comment by jonbellah** [comment]
@m-allanson @KyleAMathews Just wanted to ping you gents to see if you have any thoughts on https://github.com/gatsbyjs/gatsby/issues/6127#issuecomment-404821665 - I've halted work on `gatsby-plugin-layout` until I get some feedback there.

Thanks!

**Comment by m-allanson** [comment]
@jonbellah I haven't had a chance to dig into your comment yet, but chatted about this issue with @KyleAMathews and @pieh yesterday. @KyleAMathews is planning to come back round to this when he can clear some time for it. I'm not sure when that will be, but wanted you to know that this is definitely on the radar. Hope that helps!

**Comment by timurc** [comment]
@jonbellah thanks for the hints! This week is stuffed with other things, I'll try that next week.

@m-allanson That sounds great, thanks for updating us!

**Comment by jonbellah** [comment]
@m-allanson Completely understand being busy... I know y'all have a ton of stuff on your plate, but I didn't @ you in the first comment so I wanted to make sure you saw. Thanks!

**Comment by bw** [comment]
Just jumping in here-- I don't want to be one of those people who just comments a +1, but I think that Gatsby should message in the v1-to-v2 upgrade guide that this is a major design shift (from layout wrapping pages, to pages wrapping layouts). I just spent ~3 hrs of work moving everything to v2, only to realize this flaw (lack of CSS animations is a dealbreaker for us).

I think clarity around the changed encapsulation is important. Just my 2c.

**Comment by cpboyd** [comment]
@timurc @jonbellah I'm also seeing the same page query issues in builds.

I wonder if it's related to @m-allanson's #6750 (which hopefully means it's been fixed).

If not, have you found any work-arounds?  Should we be using `<StaticQuery>` instead of page queries?

**Comment by cpboyd** [comment]
Perhaps related to the query issue:

If I try to do something like `React.createElement(bodyComponent, { muiContext, })` (rather than just using the `bodyComponent` as-is) then I get this Invariant Violation error:
```javascript
  40 |       var args = [a, b, c, d, e, f];
  41 |       var argIndex = 0;
> 42 |       error = new Error(format.replace(/%s/g, function () {
     | ^
  43 |         return args[argIndex++];
  44 |       }));
  45 |       error.name = 'Invariant Violation';


  WebpackError: Invariant Violation: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=object&args[]= for the full message or use the no  n-minified dev environment for full errors and additional helpful warnings.
```

**Comment by cpboyd** [comment]
So, it seems the page query issue in builds is caused by the `replaceComponentRenderer` in `gatsby-browser`.

By commenting it out, page queries worked as expected.

**Comment by alpgumus** [comment]
Here is my solution. Let me know if you need help passing down props or anything else, I played around with this quite a lot.

`gatsby-browser.js: `

```
export const replaceRouterComponent = ({ history }) => ({ children }) => (
      <Router history={history}>
        <YourLayout>{children}</YourLayout>
      </Router>
)
```

`gatsby-ssr.js:`

```
export const replaceStaticRouterComponent = () => ({ children, ...props }) => (
  <StaticRouter {...props}>
    <YourLayout>{children}</YourLayout>
  </StaticRouter>
)
```

**Comment by cpboyd** [comment]
@alpgumus Interesting...

After you mentioned that, I just noticed that the `<StaticRouter>` is currently added **before** `replaceRenderer` is called in [static-entry.js](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/cache-dir/static-entry.js#L114)


@m-allanson @KyleAMathews Is there any reasoning why replacing the routers, as @alpgumus has done, would properly run the graphQL page queries when the following doesn't seem to do so?

```jsx
export const replaceComponentRenderer = ({ props }) => {
    const children = React.createElement(props.pageResources.component, props);
    return (
        <YourLayout>
            {children}
        </YourLayout>
    );
};
```

I've also tried to use `replaceStaticRouterComponent` (without the layout component) with the `replaceComponentRenderer` to see if simply having it would resolve the issue, but it doesn't.

**Comment by DylanVann** [comment]
@alpgumus could you include imports in that code? Is it just off of `gatsby`? Thank you

**Comment by alpgumus** [comment]
@DylanVann `import { StaticRouter, Route } from 'react-router-dom'`

@timurc   Try this in `gatsby-ssr.js` if you want the data props on your layout:

```javascript
export const replaceStaticRouterComponent = () => ({ children, ...props }) => (
  <StaticRouter {...props}>
    <Route
      render={routeProps => {
        const pageRendered = children.props.render({ ...routeProps })
        const {data} = pageRendered.props
        return <YourLayout {...{data}}>pageRendered</YourLayout>
      }}
    />
  </StaticRouter>
)

```

**Comment by DylanVann** [comment]
@alpgumus Awesome, that worked, thank you!

This is what I ended up with. Router props are passed since I needed to know what page I was on in the layout.

```js
// gatsby-ssr.js
const React = require('react')
import { StaticRouter, Route } from 'react-router-dom'
const Layout = require('./src/components/Layout').default

export const replaceStaticRouterComponent = () => ({ children, ...props }) => (
    <StaticRouter {...props}>
        <Route
            render={routeProps => {
                const pageRendered = children.props.render(routeProps)
                const { data } = pageRendered.props
                return (
                    <Layout {...{ data }} {...routeProps}>
                        {pageRendered}
                    </Layout>
                )
            }}
        />
    </StaticRouter>
)
```

```js
// gatsby-browser.js
const React = require('react')
import { Router } from 'react-router-dom'
const Layout = require('./src/components/Layout').default

export const replaceRouterComponent = ({ history }) => ({ children }) => (
    <Router history={history}>
        <Layout history={history}>{children}</Layout>
    </Router>
)
```

**Comment by ken0x0a** [comment]
I love how gatsby, manage data, handle all necessary staff without pain.

But without Layout I need to write same code in all page.

I tried @alpgumus way, but somehow page become so heavy and chrome freeze, react-headroom create 

```html
<div class="headroom-wrapper" style="height: 124px;">
```
(sometime 125px)

even I passed `disableInlineStyles` option...

If not need one Layout, just can do like this.

```js
const Layout = ({ children }) => (
  <>
    {children}
  </>
)
```

and also, it was easy switch many layout from layout component using pathname.

Come back my lovely layout!!! plz

**Comment by ken0x0a** [comment]
```js
```

**Comment by cpboyd** [comment]
After going over @ken0x0a's posts and back over [page-renderer.js](https://github.com/gatsbyjs/gatsby/blob/0513a6cbad4026b05cff370d94dd0f7746fda3dc/packages/gatsby/cache-dir/page-renderer.js#L120) everything seems to be a little clearer.

I do worry that we might not be taking the proper `pathContext`, though:
```jsx
    const pathContext =
      process.env.NODE_ENV !== `production`
        ? this.props.pageContext
        : this.state.pageResources.json.pageContext

    const props = {
      ...this.props,
      ...this.state.pageResources.json,
      pathContext,
    }
```

As a result, I'm now using:
```jsx
export const replaceComponentRenderer = ({ props, loader }) => {
    const {pageResources, ...origProps} = props;
    const pathContext =
      process.env.NODE_ENV !== `production`
        ? props.pageContext
        : pageResources.json.pageContext;

    const newProps = {
        ...origProps,
        ...pageResources.json,
        pathContext
    };

    return (
        <Layout location={props.location}>
            {React.createElement(pageResources.component, newProps)}
        </Layout>
    );
};
```

Since I'm also using material-ui and redux, I've also created an `OuterRoot` component and use this in `gatsby-browser.js`:
```jsx
export const wrapRootComponent = ({ Root }, options) => () => {
  return (
    <OuterRoot>
      <Root />
    </OuterRoot>
  )
}
```

And this in `gatsby-ssr.js`:
**Note:** There's no need to re-use the `Layout` component since `replaceComponentRenderer` is called by the `page-renderer` in the build process
```jsx
export const replaceRenderer = ({
  bodyComponent,
  replaceBodyHTMLString,
  setHeadComponents,
}) => {
    // Get the context of the page to collected side effects.
    const muiContext = getPageContext();
  
    const bodyHTML = renderToString(
        <JssProvider
          registry={muiContext.sheetsRegistry}
          generateClassName={muiContext.generateClassName}
        >
          <OuterRoot muiContext={muiContext}>
            {bodyComponent}
          </OuterRoot>
        </JssProvider>
    );
  
    replaceBodyHTMLString(bodyHTML);
    setHeadComponents([
      <style
        type="text/css"
        id="server-side-jss"
        key="server-side-jss"
        dangerouslySetInnerHTML={{ __html: muiContext.sheetsRegistry.toString() }}
      />,
    ]);
}
```

Thanks for all the input!

**Comment by octalmage** [comment]
There’s talks of a plugin to handle it for you, but the final solution is still being developed.

**Comment by HriBB** [comment]
I am using `material-ui@1.4.0` and had a really hard time setting it up with `gatsby@2.0.0-beta.59`. Debugging is hard, because no `console.log` entries are shown on the SSR.

@KyleAMathews is there a way to output some `console.log` during the SSR?

Anyways, this is my implementation ...

**gatsby-browser.js**
```js
const React = require('react')
const { Router, Route } = require('react-router-dom')

const { CartProvider } = require('providers/cart')
const Layout = require('components/app/Layout').default

exports.replaceRouterComponent = ({ history }) => ({ children }) => (
  <Router history={history}>
    <CartProvider>
      <Route path={'/:page?/:subpage?'} render={routeProps => 
        <Layout {...routeProps}>{children}</Layout>
      }/>
    </CartProvider>
  </Router>
)
```

**gatsby-ssr.js**
```js
const React = require('react')
const { StaticRouter, Route } = require('react-router-dom')
const { renderToString } = require('react-dom/server')
const { JssProvider } = require('react-jss')

const postcss = require('postcss')
const autoprefixer = require('autoprefixer')
const csswring = require('csswring')

const { CartProvider } = require('providers/cart')
const getPageContext = require('utils/getPageContext').default
const Layout = require('components/app/Layout').default

const prefixer = postcss([autoprefixer])
const minifier = postcss([csswring])

exports.replaceStaticRouterComponent = () => ({ children, ...props }) => (
  <StaticRouter {...props}>
    <CartProvider>
      <Route path={'/:page?/:subpage?'} render={routeProps => 
        <Layout {...routeProps}>{children}</Layout>
      }/>
    </CartProvider>
  </StaticRouter>
)

exports.replaceRenderer = ({ bodyComponent, replaceBodyHTMLString, setHeadComponents }) => {
  // Get the context of the page to collected side effects
  const pageContext = getPageContext()

  const bodyHTML = renderToString(
    <JssProvider
      registry={pageContext.sheetsRegistry}
      generateClassName={pageContext.generateClassName}
    >
      {React.cloneElement(bodyComponent, {
        pageContext,
      })}
    </JssProvider>,
  )

  replaceBodyHTMLString(bodyHTML)

  // extract and minify styles
  const css = pageContext.sheetsRegistry.toString()
  const options = { from: undefined }
  const prefixed = prefixer.process(css, options)
  const minified = minifier.process(prefixed.css, options)

  setHeadComponents([
    <style
      type={'text/css'}
      id={'server-side-jss'}
      key={'server-side-jss'}
      dangerouslySetInnerHTML={{ __html: minified.css }}
    />,
  ])
}
```

This would be perfect, if I could somehow pass `pageContext` and other props down to my `Layout` component. I need to know which page I am on, so for now I am using a `Route` component to pass `page` and `subpage` match params down to `Layout`.

Is it possible to pass some extra props down to `replaceRouterComponent` and `replaceStaticRouterComponent`? Something like a `pageResources` for example?

**Comment by octalmage** [comment]
@HriBB I've used `fs.appendFileSync` to debug SSR. That plus `util.inspect(myObject, false, null)` to get the full object output printed. There might be a better way but this works.

**Comment by DylanVann** [comment]
Trying to use the latest Gatsby beta. I can't figure out a way to get a template component working with the available APIs.

Closest I've got:

```js
// gatsby-ssr.js
import React from 'react'
import Layout from './src/components/Layout'
import { Location } from '@reach/router'
import { renderToString } from "react-dom/server"

export const replaceRenderer = ({
                               bodyComponent,
                               replaceBodyHTMLString,
                           }) => {
    const newBody = (
        <Location>
            {props => (
                <Layout {...props}>
                    {bodyComponent}
                </Layout>
            )}
        </Location>
    )
    const newBodyString = renderToString(newBody)
    replaceBodyHTMLString(newBodyString)
}
```

```js
// gatsby-browser.js
import React from 'react'
import Layout from './src/components/Layout'
import { Location } from '@reach/router'

export const wrapRootComponent = ({ Root }) => {
    const WrappedRootComponent = props => (
        <Location>
            {routeProps => (
                <Layout {...routeProps}>
                    <Root {...props} />
                </Layout>
            )}
        </Location>
    )

    return WrappedRootComponent
}
```

The problem with this is that it breaks the emotion plugin.

**Comment by pieh** [comment]
Solution here will be few parts:
- implement new APIs mentioned in comment above - this plus updating plugins to use new APIs will allow painless use of multiple plugins that currently are conflicting (like we currently really only support single `wrapRootComponent` or `replaceRenderer/replaceBodyHTMLString`)
- creating `gatsby-plugin-layout` that will use new APIs - this will be very simple plugin that just will skip you from writing some boilerplate in both `gatsby-ssr` and `gatsby-browser` for most common use case + adding documentation how to handle data flow from layout to page and page to layout (using react context)

**Comment by alpgumus** [comment]
@DylanVann try this interim, let me know if you have more questions

```js
// gatsby-browser.js
const LayoutRenderer = ({ PageComponent, pageProps }) => 
  <YourLayout {...pageProps}><PageComponent {...pageProps} /></YourLayout>

export const replaceComponentRenderer = ({ props: { pageResources, ...pageProps } }) => 
  <LayoutRenderer PageComponent={pageResources.component} pageProps={pageProps} />

```

```js
// gatsby-ssr.js
export const replaceRenderer = ({ bodyComponent }) => {
  const page = bodyComponent.children.props.children
  bodyComponent.children.props.children = <YourLayout {...page.props}>{page}</YourLayout>
  return bodyComponent
}

```

**Comment by DylanVann** [comment]
@alpgumus That code almost works. I'm hitting: Duplicate replaceRenderer found, skipping gatsby-ssr.js for plugin: gatsby-plugin-emotion.

So it looks like I'd have to implement emotion SSR myself using this API.

@pieh That sounds awesome, looking forward to trying it out.

**Comment by cpboyd** [comment]
@pieh I'm glad to see that someone's working on allowing for multiple iterations of `replaceRenderer`.

It's not necessarily true that someone who needs one for css-in-jss stuff like `gatsby-plugin-emotion` or `gatsby-plugin-jss` (or material-ui like myself) won't also need another renderer for something else.

**Comment by pieh** [comment]
Actually it will probably be separate API and not `replaceRenderer` - problem with `replaceRenderer` is `replaceBodyHTMLString` function - once this is called to wrap stuff, other plugins can't do anything insteresting, because at this point we work with html string and not react components. So this is problematic only because we don't have better way of injecting providers right now.

I did some tests with jss plugin with my new APIs and it worked nicely, but will probably need to change those because they are hard to explain (you know your API is not well designed if you can't figure out how to document it so people understand it :) )

**Comment by pieh** [comment]
This most likely be copy of `wrapRootComponent` from `gatsby-browser` (to handle providers) and `wrapPageComponent` to target this layout problems (as well as possibly use it for page transitions)

**Comment by pieh** [comment]
So first PR is opened  - https://github.com/gatsbyjs/gatsby/pull/7204, after that this will follow - https://github.com/pieh/gatsby/commit/7442f7088e445fc40c55b8e3dd73761d16b1abb8 (`gatsby-plugin-layout`)

and a lot of doc changes

**Comment by pieh** [comment]
Migration guide is updated to mention `gatsby-plugin-layout` for usecases that require layout component to stay mounted between page changes - https://next.gatsbyjs.org/docs/migrating-from-v1-to-v2/#remove-or-refactor-layout-components, so I'll close this issue for now. 

Next item on to-do list is to put this information somewhere else in documentation, so people can discover if they are not migrating from v1 and need this behaviour.

**Comment by dallanlee** [comment]
Is there a solution for nested layouts?

**Comment by jessepinho** [comment]
Same question as @dallanlee. 

My situation: I have a `<Layout />` component that lives at the top of the React tree. I use `wrapPageElement` to put it on the page, and that works fine.

One of my page types (created via `createPage()`) is an article page. I use an `<ArticlePage />` component for this page. When clicking a link from one article to another article in my Gatsby site, **the entire `<ArticlePage />` component and its children are re-mounted**, rather than simply being re-rendered with new props.

## Possible solution

I could move `<ArticlePage />` into `wrapPageElement`. The downside is that _all_ pages would include the code for `<ArticlePage />`, including non-article pages. This results in more bytes of JavaScript being sent to the browser, and the browser having to parse more code.

To avoid the extra JS payload, I could make `ArticlePage` an asynchronously loaded component — i.e., use the `import()` function and thus only load the component if it's rendered. The problem there is that it won't actually be rendered as part of Gatsby's SSR. Maybe I could use an async import in `gatsby-browser.js`'s `wrapPageElement` and a non-async import in `gatsby-ssr`'s `wrapPageElement`?

Even if I do, this feels like a suboptimal solution. The "proper" solution, it seems, would be to simply rerender the page component when the path changes, as long as the page component itself hasn't changed between paths.

thoughts?

**Comment by cyberwombat** [comment]
@jessepinho I had a similar issue whereas my front page has a slightly different layout than the rest. I was able to use the `createPage` hook for this as outlined in the multiple layout section [here](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-layout#handling-multiple-layouts).  I am not actually clear on what happens internally as far as whether my front page layout is completely rerendered or not but for my use case its enough.

**Comment by jessepinho** [comment]
@cyberwombat the issue is that the code for both layouts is always loaded, in that case — which means a lot of extra bytes of JS sent to the browser.
