### ISSUE TITLE
bundle.js size

### ISSUE THREAD

**Issue by g8tguy** [gatsbyjs/gatsby#614]
I included simple lodash function in my code

```
       var users = [
            { 'user': 'fred',   'age': 48 },
            { 'user': 'barney', 'age': 36 },
            { 'user': 'fred',   'age': 40 },
            { 'user': 'barney', 'age': 34 }
        ];
        sortBy(users, [function(o) { return o.user; }])
```
and the bundle size grew by 70kb - isn't that too mach for just a `sortBy`?
```
moment("2015-12-15T15:30").format("Do MMMM YYYY")
```
and then I added momentjs  it's +40kb also.

shouldn't webpack to include only the necessary code?

**Comment by jquense** [comment]
webpack includes what _modules_ you tell it too. So `import { sortBy } from 'lodash'` is going to include all of lodash, because you imported all of lodash. webpack2 has a feature called tree shaking that can **somewhat** optimize that import by understanding the es module syntax. **however** its an optimization that is really susceptible to failure, because how dynamic JavaScript is as a language, its not always possible to know what code is needed, even if you know the imports. In confusing cases, the compiler has to bail out and just include everything.

**Comment by g8tguy** [comment]
Thanks!  I'm going to try the `lodash-webpack-plugin` maybe it will help.  And isn't gatsby 1.0 based on webpack 2.0 ?

**Comment by KyleAMathews** [comment]
>isn't gatsby 1.0 based on webpack 2.0

I haven't quite moved things over but it will be by the launch of 1.0.

And +1 to just importing the exact functions you need from lodash.

**Comment by g8tguy** [comment]
well, in Gatsby with **typescript** to cherry pick the lodash functions we can use:  
```ts
import * as includes from "lodash/includes.js"
import * as sortBy from "lodash/sortBy.js"
```
so it will take like 1.5kb instead of 70kb in minimized bundle.js

and instead of `moment`  I decided to use `date-fns`
it has modular structure like 'lodash' 
Lets say we need a simple date time formatting:

```ts
import * as format from "date-fns/format"
format(page.data.date,"Do MMMM YYYY")
```
it will include only the `format` functionality and not the whole library like `moment`
