### ISSUE TITLE
Print GraphQL schema to file for better tooling integration

### ISSUE THREAD

**Issue by kkemple** [gatsbyjs/gatsby#6167]
## Summary

Once the schema is generated, it would nice for it to be printed to file in the root of the project (or in a `.schema` folder?). This would allow 3rd party tooling (like linters) to use the schema to improve DX for Gatsby projects.

### Motivation

Not only is it beneficial to 3rd party tooling, it's also step 1 in breaking out Gatsby's Eslint config to make it easier for developers to use Gatsby lint config in IDEs, on CI, etc

**Comment by sedubois** [comment]
I would also love to see this. Additionally such a schema file serves as a quick reference when debugging a Gatsby site that doesn't build any more (e.g while tinkering in gatsby-node).

There might be additional benefits like creating a mock auto-generated GraphQL API, referring to the type definitions in discussions and documentation, etc.

(Further down the line, we could speculate about inverting the reasoning by generating and migrating the Gatsby API based on a schema definition rather than building the schema based on some other config (similar to Prisma etc)?)
