### ISSUE TITLE
Question: How SEO friendly is Gatsby?

### ISSUE THREAD

**Issue by ugiacoman** [gatsbyjs/gatsby#619]
Loving Gatsby so far, great job building such a powerful framework :D! I'm building a webapp with Next.js, but was thinking about building my static pages with Gatsby. I know Gatsby SSRs its pages. Other than that, is there any other SEO friendly perks?

**Comment by KyleAMathews** [comment]
Very! The main boost is that static sites load faster (almost always) than dynamic generated ones and the extra speed gives your site some amount of rankings boost for Google at least.

**Comment by ugiacoman** [comment]
Sounds good enough for me :) thanks @KyleAMathews

**Comment by vning93** [comment]
Hi @KyleAMathews,

On this note, I've used markdown for some of my content files
... like these: https://github.com/scaphold-io/scaphold-community/blob/master/pages/blog/

... and jsx for others, like these: https://github.com/scaphold-io/scaphold-community/tree/master/pages/questions.

Do you recommend one way over another for SEO?

I've noticed that in the `public` directory about I build my site, the markdown files turn into statically rendered files with the content inside the html file, but the jsx ones hide everything inside the bundle.js file at the base directory of the project. Will the affect my SEO at all?

Thanks!
Vince

**Comment by KyleAMathews** [comment]
@vning93 both markdown (and json, yaml, etc.) pages and JSX pages get built to an HTML file. There should be in your public folder for example a questions/index.html and questions/questions/index.html file. If you load the example jsx page on the default site example without javascript (http://gatsbyjs.github.io/gatsby-starter-default/react/), the page loads normally but when you click on a button, nothing happens as React hasn't loaded to add event listeners.

**Comment by vning93** [comment]
Just test it out. Works perfectly! Thanks for clarifying 😄

**Comment by vning93** [comment]
Hi @KyleAMathews! Looks like my Gatsby site running in production is using React Router to route to my files, where it should be statically hitting that page. Is there any way to ignore the react-router package on build so it removes any chance of it hijacking my routing in production?

I realized this was the issue since when I took out the JS bundle after my site was built, everything worked fine from an SEO standpoint and things were actually being served up statically (as opposed to dynamically through React Router).

That solution works for statically serving my files, but the problem now is that I still need the rest of my JS features enabled for things like fuzzy search (using Fuse.js) and Google Analytics.

So is there any way to ignore the React-Router package upon building the site?

**Comment by KyleAMathews** [comment]
Are you sure that having react router controlling client side routing in
production causes SEO problems?

**Comment by vning93** [comment]
Yeah it's been a problem, since when we tried it with React Router in production for a couple weeks, Google didn't index each of our posts as separate URLs and aggregated all of them into just the base site homepage. And as soon as we took the bundle out, things were working properly and Google indexed each of our posts in about a week.

**Comment by KyleAMathews** [comment]
Hmmm I can't see why this would happen. All of my gastby sites are indexed
just fine. Google has been able to crawl SPA only sites for a while so even
if Gatsby sites didn't have a static version of pages things would be fine.

I'm guessing something else is the issue or that the  reindexing and your
disabling JavaScript just happened to occur at the same time.

Have you looked at Google's webmaster console for the site? There's SEO
tools that'll test your site. Also if you haven't you could add a sitemap.

**Comment by vning93** [comment]
Yeah I've tried the webmaster tools and submitted a sitemap as well (https://scaphold.io/sitemap.txt), but to no avail.

**Comment by KyleAMathews** [comment]
Hmm weird. Well whatever the problem is it's not react router. React router links are just "a" elements. So I'd enable JavaScript again and see what happens. Google's crawler/search system is a complex beast. I've heard of people loosing pages and they pulling out their hair trying to "fix" things and then as mysteriously as the pages left they returned.

**Comment by vning93** [comment]
Hm ok I'll try that out. Thanks for the advice.

**Comment by eugenehp** [comment]
@vning93 
Hey Vincent,
did you figure out what was the issue with it?

**Comment by vning93** [comment]
Yep, it was actually a line in my `nginx.conf` file where I was serving up the index file incorrectly.

**Comment by benjaminb10** [comment]
So will Google be able to index all pages created with Gatsby?

**Comment by abdulhannanali** [comment]
@benjaminb10 It should do it totally fine :+1:
