### ISSUE TITLE
[www] IA redesign: Ensure active navigation item is always visible

### ISSUE THREAD

**Issue by fk** [gatsbyjs/gatsby#6191]
(Following up on #6153) We should update the sidebar scroll position so that the currently active navigation item is visible above the fold/scrolled into view:

* Click https://deploy-preview-6153--gatsbyjs.netlify.com/tutorial/part-eight/ and you'll end up seeing this: 
![image](https://user-images.githubusercontent.com/21834/41992467-ced050b8-7a48-11e8-8012-4eee7f664e20.png)
* We want this: 
![image](https://user-images.githubusercontent.com/21834/41992520-f98fc0ae-7a48-11e8-89a3-c9e1cecbb583.png)

**Comment by fk** [comment]
Seeing https://material.io/design/usability/bidirectionality.html not taking caring of this makes me think this is maybe not as crucial as I thought it would be.

/cc @shannonbux @calcsam

**Comment by shannonbux** [comment]
Yeah @fk it doesn't seem crucial. I really do like it when the selected
menu item somehow gets "pinned" to the top of the menu while I scroll to
look at other stuff, but like you said, not crucial. Actually, now that I
think about it, it isn't really even necessary because if the text on the
page stays the same while I scroll, then I don't need a reminder of the
title. The only need I can see is this: let's say I scroll way way down on
a menu and want to "jump" back to the section of the menu where I've
currently selected a menu item. That could be handy. But again, not crucial.
