### ISSUE TITLE
Accompanying videos for each docs page

### ISSUE THREAD

**Issue by kkemple** [gatsbyjs/gatsby#6192]
## Summary

Not everyone prefers text when it comes to taking in information. Some people (myself included) actually prefer videos to text content and find it easier to follow along with or jump around with. (I know some people don't like videos but not suggesting ditching text, just adding new formats!)

Essentially each docs page would be summarized in a video explaining how things worked. Maybe there would be some code examples? 🤷‍♀️ 

We could start by most viewed and work our way down. Would be nice to have a way to @ mention someone when a doc changed to make sure content stays in sync. Could be a job for Peril? (@jlengstorf)

### Motivation

I think providing the core information about Gatsby in as many formats as possible means we can reach as many people as possible! 💜

**Comment by m-allanson** [comment]
👍 for making the content available in as many formats as possible. 

> when a doc changed to make sure content stays in sync

This would need to be thought about carefully - worse than no docs is incorrect docs, and there's a relatively higher cost with creating / editing video content vs text content. 

Some ways to minimise the risk of outdated content could be:

- smaller videos, maybe one per heading so they're easier to change
- commit to keeping video content updated for the top x% most popular docs (rather than trying to add videos for _all_ docs)
- (vague haven't really thought this through) tag videos to specific versions of the docs, so the right videos always show up on the right docs

💯 for making use of _all_ the formats :) I'd love to hear other ideas on how to do this and keep it manageable.

**Comment by KyleAMathews** [comment]
Closing this for now but pinging @shannonbux in case you missed this discussion.
