### ISSUE TITLE
[www] IA redesign: Fix top-level docs headers for non-JS users

### ISSUE THREAD

**Issue by fk** [gatsbyjs/gatsby#6194]
(Following up on #6153) Picking up @m-allanson's comment from https://github.com/gatsbyjs/gatsby/pull/6153#issuecomment-400242491:

> - Would it be useful for the top level docs headers to link through to their own page for non-JS users?
>   - disable JS
>   - go to https://deploy-preview-6153--gatsbyjs.netlify.com/docs/
>   - click a top level heading like _Guides_ or _Reference_
>   - nothing happens :)
> 
>    A fix would be to create a page for each top level item and have the sidebar link to those pages for non-JS users. I realise this is probably out of scope and probably not _that_ important. Feel free to ignore!

**Comment by fk** [comment]
Thinking about this more, how about just linking to the first child item instead?

**Comment by m-allanson** [comment]
> Thinking about this more, how about just linking to the first child item instead?

**Comment by m-allanson** [comment]
Just spotted another place where it'd be useful to have these section overview pages. On the [lifecycle APIs docs](https://www.gatsbyjs.org/docs/gatsby-lifecycle-apis/) it says:

> See the links along the left under “REFERENCE” for the full API documentation.

The links on the left won't be on the left for smaller browser sizes, but there's no way to link to the _Reference_ section. Maybe this should be a separate issue as a future enhancement?

**Comment by fk** [comment]
Ah good catch!
Two things I wondered about:

* How would such a section overview look? We can easily generate a page with links to all items in the section, but do we want to add some copy, to?
* Could these section overviews help with … "search engine discoverability"?

> The links on the left won't be on the left for smaller browser sizes

I just realized they never were. ;-)

/cc @shannonbux

**Comment by m-allanson** [comment]
> How would such a section overview look? We can easily generate a page with links to all items in the section, but do we want to add some copy, to?

I'm not sure - maybe a title, a paragraph covering _What's in this section of the docs?_, followed by a list of links?

> Could these section overviews help with … "search engine discoverability"?

I don't know if this will make much difference. I haven't followed the latest updates on the IA redesign, I guess it depends on whether the URL structure for documentation will change to match the content structure?

e.g like this:

- `/docs/`
- `/docs/guides/`
- `/docs/guides/adding-a-404-page/`
- `/docs/reference/`
- `/docs/reference/node-apis/`
- `/docs/reference/browser-apis/`

instead of like this:

- `/docs/`
- `/docs/adding-a-404-page/`
- `/docs/node-apis/`
- `/docs/browser-apis/`

Anyway, this feels like I'm de-railing the conversation. Let's stick to: 

> how about just linking to the first child item instead?

and then go from there?

**Comment by shannonbux** [comment]
What would the first child item be for, say, the Tutorial? Or the Showcase? Is that what we're talking about?

I just had a usability test yesterday with a guy who disables lots of JS scripts on his browser, and the search bar for gatsbyjs.org didn't show up for him until he turned off whatever service he's using to filter scripts. I never knew until then that some people disable stuff like that.

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
