### ISSUE TITLE
Cross-fading page transitions

### ISSUE THREAD

**Issue by ryanturnbull** [gatsbyjs/gatsby#6303]
So i have implemented the page transition detailed in https://github.com/gatsbyjs/gatsby/tree/master/examples/using-page-transitions , and it works great. However, the fade-to-white then fade-to-page transition isn't really pleasing for dark backgrounds. I have a couple of dark -> dark page transitions in my site.

What would be great is to have custom cross-fade capability. If there is, please point me in the direction, as all the methods i've found  don't seem to work. I understand that it's because of the way Gatsby has built its router, but this functionality would be great.

Currently using react-transition-group, in combination with a timeout on getUserConfirmation

**Comment by m-allanson** [comment]
There's a discussion about page transitions over in https://github.com/gatsbyjs/gatsby/issues/5213 that might be useful?

**Comment by TylerBarnes** [comment]
I think the problem here is that your transitions are inside your page components but you want the transitions to apply to the routes instead. Your animations can't overlap because the pages are suddenly unmounted/mounted by the router. 

If you install [gatsby-plugin-layout](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-layout) then you will be able to create a layout component which automatically gets wrapped around all pages which is outside of the automatically placed router component. This is important because then you're able to wrap transitions around the routes instead of having them inside the page components of the routes. 

The only issue with this is that you're stuck with a single transition for all pages. I think the solution for that is to use react context as explained in the [gatsby-plugin-layout](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-layout#passing-data-from-layout-to-page--from-page-to-layout) documentation at the bottom. That way you can pass data from your page component up to the layout component to tell it to wrap a different transition around the router.

**Comment by TylerBarnes** [comment]
check out https://github.com/TylerBarnes/gatsby/tree/using-page-transitions for a working example.

**Comment by TylerBarnes** [comment]
@01ivr3 I couldn't actually get this working using react context. I added a default prop to the page component which has the transition component as a prop that the layout file is then grabbing and wrapping around the page (check #8659 for more info on what I did if you're curious). I'm not actually sure if it would work with react spring for per page transitions. I did a quick search for how they're animating routes and [all I could see](https://github.com/drcmda/react-spring/issues/2) from my quick search is that they're wrapping all routes inside a single transition component. There's probably a way to have multiple transitions but I'm not sure how to do it with react-spring.

**Comment by octalmage** [comment]
@TylerBarnes Do you have that example up anywhere? The link you shared is now throwing a 404.

**Comment by TylerBarnes** [comment]
@octalmage, oops! I cleaned up my github account and didn't realize I had linked to my gatsby fork here. After a lot of investigation into transitions in Gatsby I actually ended up writing a [page transition plugin](https://github.com/TylerBarnes/gatsby-plugin-transition-link) to solve all my transition issues and make things easier. It uses the method I described above but also allows for triggering functions and passing transition state around your site. I'm working on a documentation site and a gatsby blog post right now but the readme at the repo should get you started.
