### ISSUE TITLE
bundle size serve-build and build

### ISSUE THREAD

**Issue by ufon** [gatsbyjs/gatsby#638]
at simple http-server i have 700 kb
![image](https://cloud.githubusercontent.com/assets/4355972/22108482/7697d5d2-de64-11e6-870e-dd4721960af3.png)
at serve-build i have fantastic 200kb
![image](https://cloud.githubusercontent.com/assets/4355972/22108519/974472c2-de64-11e6-9c59-f605e3d07561.png)
i don't understand   
i also read #613 but not finally understand :(

**Comment by g8tguy** [comment]
The only thing you should care about is `gatsby build` size.
It is a minified version of the final `js`, you will  then upload to the server.
Also, the server will compress the `bundle.js` with gzip, making it even smaller.  

In #613 I messed up with some configs and the js minifier got broken, so the `bundle.js` size was pretty huge.

In order to understand how `gatsby` is working, it's a good idea to start with:
`webpack` and `react` basics.

**Comment by ufon** [comment]
@g8tguy thx u! i power on my gzip on server and bundle was compressed to 200kb.

**Comment by KyleAMathews** [comment]
This will get even smaller in 1.0! https://github.com/gatsbyjs/gatsby/issues/431

E.g. loading my blog bricolage.io requires eval/parsing around 110kb of minified/gzipped JS. The absolute minimum is smaller. I'm also going to be experimenting soon with using preact/inferno which seem ideal for a content-only Gatsby site which would reduce the size even further.
