### ISSUE TITLE
Gatsby websites auto scroll back to the top

### ISSUE THREAD

**Issue by DeveloperDavo** [gatsbyjs/gatsby#6392]
## Description

When a Gatsby website loads, the user can happily start scrolling. However, after some time has elapsed the page scrolls back up to the top.

### Steps to reproduce

This can be reproduced at https://www.gatsbyjs.org/ or https://reactjs.org/ by going to the website with a throttled network connection and scrolling down before render() is called.

### Expected result

It should not scroll to the top

### Actual result

It scrolls to the top. This will not happen if JS is disabled.

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by m-allanson** [comment]
Thanks for the report @DeveloperDavo. This is mentioned over in #5675. For anyone interested in picking this up, [check the discussion in 5675](https://github.com/gatsbyjs/gatsby/issues/5675#issuecomment-394082598) for pointers on where to start investigating.

**Comment by DeveloperDavo** [comment]
Thanks for the reply! I am happy to investigate this. If anyone else wants to investigate at the same time, please feel free!

**Comment by humphreybc** [comment]
Any update on this? I don't believe it's resolved in v2.

**Comment by KyleAMathews** [comment]
@humphreybc no not yet unfortunately. The fix is I believe to check in https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-react-router-scroll/README.md if scroll has already happened and to _not_ then scroll to the top which is it's default. Or perhaps easier to just not scroll at all on the initial load of the website.

Would you like to work on a PR? This would be really nice to fix!

**Comment by stefanprobst** [comment]
I think this would be fixed by returning `false` in [`shouldUpdateScroll`](https://github.com/gatsbyjs/gatsby/blob/b2a030a962f63bc9e211b4aa8df1631d0e07be6f/packages/gatsby/cache-dir/navigation.js#L125). The problem is: what should happen on page reload (when we want to scroll to the last saved position)?

**Comment by abumalick** [comment]
I really think that this one is important

**Comment by KyleAMathews** [comment]
@wardpeet actually fixed this a couple of weeks ago!

https://github.com/gatsbyjs/gatsby/pull/11224
