### ISSUE TITLE
gatsby-image-sharp missing 'resize' export

### ISSUE THREAD

**Issue by cupojoe** [gatsbyjs/gatsby#6394]
## Description

According to the documentation for gatsby-image-sharp v2 beta 3 there is a method called resize to just resize one image. Trying to import this method from the package fails and looking at the source the export is not there:

https://github.com/gatsbyjs/gatsby/blob/c4ee17afb599afb4ce02cfc195b1ce0a17eecd92/packages/gatsby-plugin-sharp/src/index.js#L740-L747

Should it be added or the documentation updated?

**Comment by LeKoArts** [comment]
You would use resize in the GraphQL query. Or what did you try to do?

**Comment by m-allanson** [comment]
@cupojoe I'd be interested to hear what you're aiming to do!

I just had a dig through the history of `gatsby-image-sharp`, and it doesn't look like `resize` has ever been exported. Resize operations are instead handled by the `queueImageResizing` function, which is designed to work with Gatsby file nodes rather than file paths directly. 

See [the tests](https://github.com/gatsbyjs/gatsby/blob/608f8212bde61e38fc1da808c956d5b608c09fa6/packages/gatsby-plugin-sharp/src/__tests__/index.js#L26) for example usages, or take a look at [`extend-node-type.js` in `gatsby-transformer-sharp`](https://github.com/gatsbyjs/gatsby/blob/608f8212bde61e38fc1da808c956d5b608c09fa6/packages/gatsby-transformer-sharp/src/extend-node-type.js#L362) to see how this is hooked up to `resize()` in a GraphQL query.

I'd love to see a PR updating the docs to remove `resize` and include `queueImageResizing` if you or anyone else is interested.

**Comment by KyleAMathews** [comment]
We could export a resize function that just calls queueImageResizing if someone wanted to PR that.

**Comment by cupojoe** [comment]
I'm making a gatsby plugin to process `poster` attributes so you can add html 5 video tags directly into the markdown files (using plain html). 
I think exporting resize as an alias would be great since that is what is documented in the package and it can be confusing that it doesn't work while the docs refer to it.

**Comment by KyleAMathews** [comment]
Sounds like a sweet plugin! And yeah! Please PR the change!

**Comment by cupojoe** [comment]
@KyleAMathews will do, also a PR to include the plugin in the plugins registry. Gotta checkout the plugin contribution guidelines first :)

**Comment by KyleAMathews** [comment]
Sweet! Plugins btw are auto pulled in if you add "gatsby-plugin" as a keyword

**Comment by cupojoe** [comment]
you mean if I add `gatsby-plugin` as a keyword in the `package.json` and also include the plugin in a pr to the gatsby mono repo?

**Comment by cupojoe** [comment]
sounds good 👍

**Comment by cupojoe** [comment]
@KyleAMathews I can see the new plugin in the list of plugins, but if you select it you get a 404. Did I miss something for it to populate correctly?
