### ISSUE TITLE
Contentful source

### ISSUE THREAD

**Issue by Amanej** [gatsbyjs/gatsby#6433]
## Description

So when I run the contentful starter, or even a clean gatsby site and add the gatsby-source contentful plugin it runs into an error.

### Steps to reproduce

1. gatsby new site
2. npm install gatsby-source-contentful --save-dev
3. gatsby develop

### Expected result

Access contentful data in graphql interface.

### Actual result

Throws error at build time.

´  TypeError: entryItemFields[foreignReference.name].push is not a function´

![image](https://user-images.githubusercontent.com/10694878/42698722-0664798c-86bf-11e8-9cd0-577c99caea16.png)

**Comment by pieh** [comment]
Please provide Environment info here so we know which versions of gatsby and plugins You are using:
> Required. Run `gatsby info --clipboard` in your gatsby project directory and paste its contents here.
  Not working? You may need to update your global gatsby-cli - `npm install -g gatsby-cli`

It would also be great if You could provide minimal reproduction repository

**Comment by Amanej** [comment]
![image](https://user-images.githubusercontent.com/10694878/42751625-a7deca28-88eb-11e8-97e9-bc116dd00694.png)

**Comment by Amanej** [comment]
I created another project with the same plugins and now the error is "cannot find module 'graphql'".

**Comment by Khaledgarbaya** [comment]
Hey @Amanej,
did you try this with a fresh space or different content types?

**Comment by m-allanson** [comment]
> and now the error is "cannot find module 'graphql'"

`Cannot find module` errors are usually caused by missing dependencies - try deleting your `node_modules` directory, along with `yarn.lock` or `package-lock.json` files and reinstall. Then make sure npm installed the plugnis that you're using for your project. Does that help?

**Comment by chrisheninger** [comment]
I just ran into this same thing after adding a new content type... I've been digging around trying to figure out what/why it's happening but haven't had any luck.

I've found that by removing my `.cache` directory and restarting gatsby– it works just fine. But after stopping and restarting, it will always throw the following error and I have to `rm -rf .cache` before running gatsby again.

<img width="571" alt="screen shot 2018-08-15 at 2 03 55 pm" src="https://user-images.githubusercontent.com/5051745/44173301-6121a900-a094-11e8-9326-ed4903633b1e.png">

The file it's referring to is https://github.com/elm-street-technology/elevate-marketing-site/blob/master/gatsby-node.js – I didn't start seeing the error until I most recently added Testimonial into the mix– but I can't figure out why that would affect it because it's doing the same exact thing as the others.

**Comment by kakadiadarpan** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub issues, we have to clean some of the old issues as many of them have already been resolved with the latest updates.

Please make sure to update to the latest Gatsby version and check if that solves the issue. Let us know if that works for you by adding a comment 👍

**Comment by kakadiadarpan** [comment]
This issue is being closed because there hasn't been any activity for at least 30 days. Feel free to [open a new one](https://github.com/gatsbyjs/gatsby/issues/new/choose) if you still experience this problem 👍
