### ISSUE TITLE
Investigate CI optimisation

### ISSUE THREAD

**Issue by m-allanson** [gatsbyjs/gatsby#6534]
## Summary

Gatsby runs a lot of CI builds every day. Spend some time to see if they can be sped up.

### Basic example

Things to investigate:

- caching between runs?
- run jobs in parallel?
- remove unnecessary work? e.g. use npx?
- review / reduce dependencies?

Windows CI builds are particularly slow. How can they be sped up?

- use a paid Appveyor account? 
- use Visual Studio Team Services CI instead? 

### Motivation

Spend less time waiting for CI builds to finish.

**Comment by KyleAMathews** [comment]
That looks promising! You want to try running our tests on their service (e.g. fork the repo and setup your fork to run there) and see how the test times compare?

**Comment by mmaksimovic** [comment]
Hey @m-allanson and @KyleAMathews 

Here are my results on [Semaphore](https://semaphoreci.com/mmaksimovic/gatsby/branches/master/builds/1) and here are the latest results on [Travis](https://travis-ci.org/gatsbyjs/gatsby/builds/408011022?utm_source=github_status&utm_medium=notification). I'll add my results from Travis later on, since the build is waiting in queue [for quite a long time](https://travis-ci.org/mmaksimovic/gatsby/requests?requestId=125113834).  

Hope I helped :)
