### ISSUE TITLE
Is there a way to merge all JS build files in only one bundle?

### ISSUE THREAD

**Issue by guilhermeutzig** [gatsbyjs/gatsby#6548]
Hey guys, enjoying a lot my experience here with Gatsby, it's really nice!

There is something I want to know, when I run `gatsby build`, it generates a ton of files on public directory:

![image](https://user-images.githubusercontent.com/36337530/42905815-7b037c54-8aaf-11e8-97f1-6fad0f7809bd.png)

Is there a way to envolve all of this in a single bundle file?

Thanks!

**Comment by LeKoArts** [comment]
No, this is by design to enable code splitting and other optimizations which make Gatsby so fast.

**Comment by guilhermeutzig** [comment]
@LeKoArts Ok, thanks for your answer!

**Comment by KyleAMathews** [comment]
We did move js/css files into their own directory recently https://github.com/gatsbyjs/gatsby/pull/6346

**Comment by adueck** [comment]
It would be great if there was an option to bundle it all into one file, because right now offline support (with `[gatsby-plugin-offline](https://www.gatsbyjs.org/packages/gatsby-plugin-offline/)` is not very good because **the individual route files only get cached/saved when a visitor visits them, and then when the app is updated they lose those again**. 

*It would be so nice if there was an option to have one big bundle that a service worker could cache, and then you could automatically have a fully offline-available site.* 

I asked a question along those lines [eariler here](https://github.com/gatsbyjs/gatsby/issues/13417), but there was no response and it was marked as stale.

**Comment by AdityaAnand1** [comment]
I'm using gatsby as a single page application generator, so I only have one page.

In this case, having one file (and one request) instead of 4-5 would be the more performant route. Shouldn't be too hard to have an option/plugin that just appends the JS file and give this as an option.

cc @LekoArts
