### ISSUE TITLE
[www/showcase] Site showcase jumps to top of page when closing a site modal

### ISSUE THREAD

**Issue by thebigredgeek** [gatsbyjs/gatsby#6552]
On the showcase, if I scroll down and click a site to open the site's modal and then close the modal, the site will have scrolled me back up to the top.

The expected behavior would be to remain in place behind the modal, and to persist placement state between opening and closing modals.

**Comment by berraknil** [comment]
Been working on this for most of today, it seems there are three possible causes for this,

First of all, Scroll position resets on modal open, not after modal is closed, which can mean

a) It's the Link component (anchor) which causes the default browser behavior due to not having "event.preventDefault()" in onClick.

b) It's the push to the history API made by the Link component

c) It's react-modal causing this, which seems to be an issue for a few people see https://github.com/reactjs/react-modal/issues/117 and https://github.com/reactjs/react-modal/issues/585

I tried to do a preventDefault on on click but that also stops the modal from firing, so not really tested.

It could be the react-modal CSS but we need to override the css-in-js with a classname etc, which didn't seem to pick up.

Will try more things soon, but this is the current situation. 

Also [Gatsbygram](https://gatsbygram.gatsbyjs.org/) seems to be handling similar behavior although I don't think there is a push to state on Link component (if I am not mistaken) so that might be the scroll behavior culprit here.

**Comment by KyleAMathews** [comment]
In v1 I froze the html. I disabled in for the v2 version as I couldn't get it working for some reason that I don't really remember https://github.com/gatsbyjs/gatsby/blob/00214271f968d5f02f73ca715c4cd8671b6bb63f/examples/gatsbygram/src/layouts/index.js#L32

**Comment by Bilie** [comment]
Hi here is my take on this issue so far:

On modal open the user is being redirected to the showcase details.

The content of the site appears to be scrolled to the top on modal open, but this is a side effect of `PageRenderer` which rerenders the page specified in the `modalBackgroundPath` prop (`/showcase` in this case) as a background of the modal window.


The same path provided in the props (`modalBackgroundPath="/showcase"`) is used when the user closes the modal:

```js
handleCloseModal() {
  navigate(this.props.modalBackgroundPath)
}
```

This though pushes a new item in the browser history stack instead of going back to a previous state, so the scroll position is not retained.

To verify, go to `/showcase`, scroll to the bottom of the list (without clicking on load more), click on an item, then use the browser back button -> scroll position should have been retained, and you should be at the bottom of the list.

Load more action does not push anything to the browser history, so on going back, previously loaded items are no longer displayed.

Not sure what is the best solution for this.

Adding load more to the url like `/showcase/?page=3` would fix losing previously loaded items on going back.

On the modal issue, either not displaying page as background (to avoid scroll to top) or not using modal altogether might improve experience.

If using modal is preferred, instead of hard coded path, using a prop to pass current showcase url might help.

What do you think? Looking forward to your feedback
