### ISSUE TITLE
[v2] Remove support for remotedev-server

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#6575]
It's not used afaik and it adds more packages and code complexity.

**Comment by m-allanson** [comment]
@KyleAMathews did you mean `remotedev-server` instead of `redux-dev-server`? If yes, then the steps would be:

- Remove these lines from  https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/redux/index.js#L61-L80
- Remove the [_Redux devtools_ section from the docs](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/how-to-contribute.md#redux-devtools)
- Remove the [`remotedev-server` dependency from package.json](https://github.com/gatsbyjs/gatsby/blob/master/package.json#L35)

This would resolve https://github.com/gatsbyjs/gatsby/issues/5335#issuecomment-408102530

**Comment by KyleAMathews** [comment]
yes :-) fixed the title
