### ISSUE TITLE
Design Specs for Individual & Orgs Pages

### ISSUE THREAD

**Issue by berraknil** [gatsbyjs/gatsby#6677]
A few questions about the design specs for the Organization Page (as I think that would be a good starting point). 

- [x] First of all, is this page going to live in a separate directory (let's say /creators ) and with a completely separate page layout (meaning it will not be implemented below the Featured Sites header/section  in the main Showcase page)? If so, additional question, how do we direct people to there from the main Showcase page below?

![image](https://user-images.githubusercontent.com/6593585/43076814-1843aec6-8e8e-11e8-9aef-15a2a8ec301f.png)

- [x] It seems from https://github.com/gatsbyjs/gatsby/issues/6564 there will be only one filter for the Organizations which is Company/Agency, so probably best to not build a whole filter section on the left but instead use a simpler toggle to switch between the two? (same can be applied to an upper level differentiation between Individuals and Orgs) ?

- [x] Assuming */orgs/(all orgs)* will be a grid layout and clicking on the grid items will take us to */orgs/[org-name]* ?

- [x] Should we implement sorting? Newest/Alphabetic etc as a dropdown/checkbox etc to list these Orgs?

- [x] Should we implement search like we have one in the Showcase page?

- [x] There also seems to be a filter for _Agency_ already which I am guessing will be removed/replaced with the dedicated page we are going to be building? (or not?)

- [x] Are we going to use a single page for both Orgs and Individuals as talked about in https://github.com/gatsbyjs/gatsby/issues/6564#issuecomment-406379860 or separate pages?

If some of these questions are already answered somewhere else etc, or if there are already some design specs are available please excuse me as I am just trying to get a clearer picture before starting the wireframing process :)

Also open to any feedback, ideas, additions, suggestions here from everyone, especially from UX/Design teams to start this process on the right foot.

Pinging @calcsam @kkemple @shannonbux @fk @jlengstorf @KyleAMathews and anyone else I forgot!

**Comment by calcsam** [comment]
> First of all, is this page going to live in a separate directory (let's say /creators ) and with a completely separate page layout (meaning it will not be implemented below the Featured Sites header/section in the main Showcase page)? If so, additional question, how do we direct people to there from the main Showcase page below?

Yes. We're going to need to redesign the navbar soonish to add linkability. @fk is thinking about that. You don't need to worry about that right now though. An individual site page should link to the page of its creator. The creator page should link to the page of all creators through breadcrumbs. 

> It seems from #6564 there will be only one filter for the Organizations which is Company/Agency, so probably best to not build a whole filter section on the left but instead use a simpler toggle to switch between the two? (same can be applied to an upper level differentiation between Individuals and Orgs) ?

See discussion on that ticket. Just altered the description to reflect the discussion below.

> Assuming /orgs/(all orgs) will be a grid layout and clicking on the grid items will take us to /orgs/[org-name] ?

Sort of, see new altered description spec

> Should we implement sorting? Newest/Alphabetic etc as a dropdown/checkbox etc to list these Orgs? 

I'm not sure. We should have some organization system to allow this to grow to eg 500-1000 organizations, with a way to feature "high-profile". I'm not sure what the best way of doing that is. 

I'm also not sure what kind of filters would be useful for companies. My guess is that we'll want a set of dropdowns (similar to [here](https://www.meteor.com/partners)). Eg Vertical, eventually Has E-commerce. I think we'll also probably want AND filters rather than OR filters.   

We should have a way to feature company logos on the /companies page (eg having them appear at the top of whatever the default sort is). 

>  Should we implement search like we have one in the Showcase page?

Definitely. 

> There also seems to be a filter for Agency already which I am guessing will be removed/replaced with the dedicated page we are going to be building? (or not?)

No. This will be a different page. The default display for the individual will be their photo, default for agencies / companies will be logo. 

> Are we going to use a single page for both Orgs and Individuals as talked about in #6564 (comment) or separate pages?

Updated the spec.
