### ISSUE TITLE
GraphQL not work in subdirectories page component

### ISSUE THREAD

**Issue by dzuncoi** [gatsbyjs/gatsby#6682]
## Summary
Currently, my folder structure is like
<rootFolder>
-- pages
---- index.js
---- hiring
------ hiring.js
------ index.js

Those `index` and `hiring` page work correctly, but the problem comes when I need some graphQL in `hiring.js` page:
```javascript
export const pageQuery = graphql`
  query RecQuery {
    allStrapiRecruitment {
      edges {
        node {
          id
          openingAmount
          description
        }
      }
    }
  }
`
```
But there is no data in hiring.js props. I notice that this piece of code work perfectly with files inside `pages` folder directly, but doesn't work with file in sub-directories. 
My question is: is it intentional or do I miss something?

### Environment (if relevant)
node 8.9.3
npm 5.6.0
gatsby 1.1.52

**Comment by giraffesyo** [comment]
Can you provide your gatsby-config.js? I'm interested in seeing what options you have for `gatsby-source-filesystem`.

**Comment by dzuncoi** [comment]
@giraffesyo here is my `gatsby-config.js`
```javascript
module.exports = {
  siteMetadata: {
    title: 'Title',
  },
  plugins: [
    'gatsby-plugin-react-helmet',
    {
      resolve: `gatsby-source-strapi`,
      options: {
        apiURL: `http://localhost:1337`,
        contentTypes: [ // List of the Content Types you want to be able to request from Gatsby.
          `recruitment`,
          // `user`
        ]
      },
    },
    {
      resolve: `gatsby-plugin-react-css-modules`,
      options: {
        // *.css files are included by default.
        // To support another syntax (e.g. SCSS),
        // add `postcss-scss` to your project's devDependencies
        // and add the following option here:
        filetypes: {
          ".scss": { syntax: `postcss-scss` },
          ".sass": { syntax: `postcss-scss` },
        },
  
        // Exclude global styles from the plugin using a RegExp:
        exclude: `\/global\/`,
      },
    },
    `gatsby-plugin-sass`,
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/assets/images/`
      }
    },
    {
      resolve: `gatsby-plugin-facebook-pixel`,
      options: {
        pixelId: 'My pixel Id',
      },
    },
  ],
};

```
So subdirectories pages component still can get GraphQL data, and I'm doing something wrong?

**Comment by brotzky** [comment]
This is on purpose:
https://github.com/gatsbyjs/gatsby/issues/3290#issuecomment-353162384

The pattern to do this is to use GraphQL Fragments 
https://github.com/gatsbyjs/gatsby/issues/2168#issuecomment-330648458

Review the two issues above and it should get in you in the right direction! Thanks!

Closing this as there's no action to be taken.

**Comment by giraffesyo** [comment]
I don't think those two answer the OP's problem. He mentioned that the same file works fine if he brings it up one directory into the pages folder. That means that he is making a `page` component, not a `non-page` component. The default export should be receiving props from the graphql query. However, I'm not sure what the exact issue here is from the details provided. 

Do you have some steps we can take to reproduce this issue?

**Comment by dzuncoi** [comment]
@giraffesyo you point out my issue correctly
So I follow this one https://hackernoon.com/building-a-static-blog-using-gatsby-and-strapi-8b5acfc82ad8
using strapi as data layer for gatsby. So I setup exactly the same with this tutorial (in terms of strapi), then setup gatsby like `gatsby new my-site`, add  `gatsby-source-strapi` into `gatsby-config` like above. Then create some data in strapi, import this piece of code 
```javascript
export const pageQuery = graphql`
  query RecQuery {
    allStrapiRecruitment {
      edges {
        node {
          id
          openingAmount
          description
        }
      }
    }
  }
`
```
to `pages/index.js` or `pages/hiring.js`, it works correctly, but doesn't in `pages/hiring/index.js`

**Comment by dzuncoi** [comment]
Hi @giraffesyo @brotzky, any update for this?

**Comment by m-allanson** [comment]
Hey @dzuncoi this does sound like a bug... could you create a small project that recreates this issue? Then someone can use that for testing and debugging.

**Comment by kingluddite** [comment]
I'd like to keep this open
i'd love to be able to use nested folders inside pages



instead of:
pages/index.js
pages/about.js
pages/contact.js

I'm using Styled Components and would love the following folder structure to keep my pages modular, tidy and easy to remove/swap pages - I really like Josh Comeau's react structure (https://www.joshwcomeau.com/react/file-structure/) and would love to have this inside Gatsby Js project

but I'm having issues importing styled components as named exports and get that gatsby template pages should only have default exports warning

and my graphql page queries don't work in nested folders inside the pages directory

I want
-- pages
---- home
------ HomeStyles.js
------ HomePage.js
------ index.js
---- about
------ AboutPage.js
------ AboutStyles.js
------ index.js
---- contact
------ ContactPage.js
------ ContactStyles.js
------ index.js
-- index.js

Can anyone point me to a GitHub repo that uses a structure similar to this in a Gatsby JS app? Or point me in a direction to make this work? My hair that I'm going to pull out will thank you for saving me from pulling all my hair out :)
