### ISSUE TITLE
Refactor code from site showcase into components

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#6705]
Make any reusable parts of the site showcase into components. I believe Shawn and @kkemple already started this.

This will be important for polishing the starter showcase and also helping with the Gatsby agency pages @berraknil is working on.

**Comment by fk** [comment]
I refactored a couple of things in #6838 but held off from doing more because I was worried about doing so making it potentially harder for @sw-yx to merge stuff back into his PR for the starter showcase (#6113).

Maybe it's easier to merge Shawn's current version of the PR and then refactor?

/cc @calcsam @KyleAMathews @sw-yx

**Comment by sw-yx** [comment]
it sounds like this project has been moved to backlog so i'll wait for further instructions on this if i am to proceed. sorry i have never meant to be a blocker on your work.

**Comment by berraknil** [comment]
@calcsam I don’t know how much (if any) of the components will be needed in the pages I am designing. I suggested the card component as an idea, because @fk asked at the meetıng, but I might end up creating a new one depending on the necessities. 

I am currently working on wireframes and design of the new pages as we agreed so not really in a place to refactor these components myself, as I haven’t even worked on the original code.

This is not a blocker for me or urgent in my case as I will probably end up writing new components anyway.

**Comment by calcsam** [comment]
Agreed. Main goal here is to get a list of the things that _should_ or _could_ be extracted out so we can scope this ticket appropriately. It definitely belongs in a different project than yours @berraknil.

**Comment by berraknil** [comment]
Sure, it seemed that there are already some components that are used in both starter showcase and site showcase (?) in our meeting, so I didn't want to be a blocker on refactoring of those with my possible list of components. 

If I end up using one of the available ones, good, but I might not use any of them, so just wanted to clarify that to not block the work on this.

**Comment by berraknil** [comment]
Starting a list here for future reference,

- [ ] The Search component, shared between main page, showcase and on creators/community pages so far as well. I pretty much copy pasted most of the current animation and styling from there, so probably can be abstracted to an external shared component.
