### ISSUE TITLE
Starter showcase: Users need to see Gatsby dependencies filtering list above the fold in browser window

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#6706]
Need to be able to see Gatsby Dependencies. Currently it is below the fold in my browser. Flo to give tech reqs--each accordion can take 50% of available space (calculating available space necessary).

**Comment by fk** [comment]
See #6724

**Comment by shannonbux** [comment]
Should we close this one, @fk? Or do we need both this one and #6724?

**Comment by sw-yx** [comment]
these are related so would close

**Comment by fk** [comment]
Over the weekend I fixed #6724 via #6838 which removed the hardcoded height of `500px` and also supports multiple collapsibles via flexbox. The basic implementation should be very similar to what you've already done regarding "responsive collapsibles" @sw-yx.

In the PR I refactored `www/src/views/showcase/filtered-showcase.js` (https://github.com/gatsbyjs/gatsby/pull/6838/files#diff-51865a2ea87f4bfd5fb20a85ed340a9b), adding two new components:

* https://github.com/gatsbyjs/gatsby/blob/master/www/src/views/showcase/filters.js contains all sidebar contents -- the "Filters & Refine" headline, the container for the collapsibles, and the collapsibles itself via
* https://github.com/gatsbyjs/gatsby/blob/master/www/src/views/showcase/collapsible-filter-list.js

Those two components along with the CSS for the container in https://github.com/gatsbyjs/gatsby/blob/10e4465d018e4f8ec61a245b45722c611b635418/www/src/views/showcase/filtered-showcase.js#L102-L125 result in multiple accordions behaving [as shown in this video](https://www.dropbox.com/s/3kgrsoe07o39djj/showcase-collapsible-filters.mov?dl=0).

This issue is for the starter showcase implementation, so I'd keep it around.

@sw-yx I don't know your starter showcase PR very well, but maybe you can reuse above components (or update them for this to be possible)? Happy to help with that and/or resolving the conflicts. Will take a look at the other open starter showcase issues now. Sorry for taking so long! 🙏

**Comment by sw-yx** [comment]
happy to use your thing, i'll update my fork!

**Comment by fk** [comment]
Great! I hope it's not to painful; FWIW I don't plan on causing more merge pains this week!
Let me know if I can help in any way!
