### ISSUE TITLE
Overall typography edits - starter showcase

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#6719]
We need typography and iconography (like the star) to match Flo's sketches:

Index page:

![startershowcase.png](https://images.zenhubusercontent.com/5ada1b064b5806bc2bcffa08/01bd3145-05d9-4bc1-849c-665b09d47f9b)

Detail page:

![startershowcasedetail](https://user-images.githubusercontent.com/32467162/43238997-cc051240-904d-11e8-8cbf-f612ca8aa8e3.png)

**Comment by shannonbux** [comment]
@fk have you provided @sw-yx with design specs like fonts/font sizes/icons OR are we just using the same ones from the site showcase?

**Comment by sw-yx** [comment]
just FYIing that some stuff isnt present in the site showcase, like the star. would love all assets provided up front but so far ive been handrolling my own haha

**Comment by sw-yx** [comment]
also typography wise i basically clone everything from site showcase. would love to explore if any discrepancies crop up, but i'd be surprised to see it since i dont override it

**Comment by shannonbux** [comment]
Oh, ok, I see probably how these font differences happened. Maybe it's just
fields that don't exist or we don't show in the Site Showcase index page?

Here are screenshots that have red boxes around all the serif fonts, which
we haven't used in the Site Showcase. I think sans serif is the standard
for these fields, not sure what size or font @fk?

**Comment by sw-yx** [comment]
screenshots are missing fyi

**Comment by fk** [comment]
Hey Shawn! Screenshots are working for me.
They are the same as in https://github.com/gatsbyjs/gatsby/issues/5334#issuecomment-396557749 ff.

> just FYIing that some stuff isnt present in the site showcase, like the star. would love all assets provided up front but so far ive been handrolling my own haha

That is true. I wasn't aware that I didn't share the Sketch sources for the designs I posted in https://github.com/gatsbyjs/gatsby/issues/5334. Please accept my apologies. 🙏

I just imported the design in Figma: https://www.figma.com/file/G3x7aYuyigYaibEpyxMsKLcP/gatsbyjs.org%3Ashowcase-starters and shared it with you.

---

For the star, please use "MdStar" from http://react-icons.github.io/react-icons/md.html (which we already use in `www` for various icons) instead of the emoji. It's the one I used in the design (FWIW I think I mentioned this in one of our chats).

Regarding typography, please:

* Change all serif fonts on the list view starter cards and the detail/modal pages to "Futura PT" like e.g. in https://github.com/gatsbyjs/gatsby/blob/10e4465d018e4f8ec61a245b45722c611b635418/www/src/views/showcase/filtered-showcase.js#L232
<img width="327" alt="bildschirmfoto 2018-07-30 um 19 24 41" src="https://user-images.githubusercontent.com/21834/43412884-cd8c7240-942e-11e8-84d2-35d2a340ce03.png">  and
<img width="713" alt="bildschirmfoto 2018-07-30 um 19 40 59" src="https://user-images.githubusercontent.com/21834/43413567-aba94516-9430-11e8-98ec-15adb6f53e61.png">

* Decrease the vertical space in between repository owner (e.g. `kripod/`) and repository name (e.g. `gatsby-starter-modern`), ideally so that copy, preview and source links to the right of the repository owner do not conflict (move closer) to the repository name: 
<img width="322" alt="bildschirmfoto 2018-07-30 um 19 31 09" src="https://user-images.githubusercontent.com/21834/43413161-91671e0e-942f-11e8-8be2-92fa58f1bb2e.png">

* Please ignore the detail/modal page header with starter title and deploy buttons, etc. for now -- will provide a new design in #6098 that hopefully covers all requirements of both site and starter showcase detail headers

* Remove the background appearing on `:hover` from the card's copy, preview and source links and make them `colors.gatsby` instead when hovered, similar to the [GitHub icon on the site showcase cards](https://next.gatsbyjs.org/showcase/): 
<img width="316" alt="bildschirmfoto 2018-07-30 um 19 48 08" src="https://user-images.githubusercontent.com/21834/43413897-956f663a-9431-11e8-9997-5e55fc33e51b.png">

* Make the "Dependencies" links on the detail page `font-weight: normal` and only show the underline when hovering: 
<img width="1017" alt="bildschirmfoto 2018-07-30 um 19 52 58" src="https://user-images.githubusercontent.com/21834/43414352-cae28c2e-9432-11e8-9223-fb1ceda9430e.png">

* Change the appearance of the "Show x more" button that is shown for starters with lots of dependencies to the one in the design -- remove the background, make the `colors.gatsby`, `font-weight: normal`, add the "angle down" symbol from [react-icons](http://react-icons.github.io/react-icons/fa.html) (https://github.com/gatsbyjs/gatsby/blob/10e4465d018e4f8ec61a245b45722c611b635418/www/src/views/showcase/collabsible.js#L2): 
<img width="1010" alt="bildschirmfoto 2018-07-30 um 20 00 46" src="https://user-images.githubusercontent.com/21834/43414526-47211de6-9433-11e8-9a99-d09651fcf5b1.png">

Let me know if you have any questions!

**Comment by sw-yx** [comment]
great instructions, thank you very much!

**Comment by shannonbux** [comment]
@fk and @sw-yx if I'm understanding Flo's suggestion right, I think the
listed dependencies on the detail view should stay underlined so they are
clearly "clickable" (and then when someone hovers on them, they are fully
highlighted. OR I'm find with another way of indicated they are clickable!

On Mon, Jul 30, 2018 at 12:05 PM, Florian Kissling <notifications@github.com
