### ISSUE TITLE
building css with @import in file will have "undefined" message

### ISSUE THREAD

**Issue by twxia** [gatsbyjs/gatsby#673]
Hi there :smile:

My css file use `@import` to import other files but when building process done, it'll show `undefined` in the message. Someone know how to solve this problem? It runs pretty well, but just have a weird `undefined` message.

static/css/styles.css :
```
@import './common/_base.css';
```

static/css/styles.css :
```
* {
    margin: 0;
    padding: 0;
    outline: none;
    box-sizing: border-box;
}
```

terminal : 
```
webpack building...
static/css/styles.css
undefined [undefined]
```

**Comment by bntzio** [comment]
Yeah it happens to me as well 😞 the css works but the message is pretty annoying.

**Comment by jbolda** [comment]
If you haven't figured it out, feel free to reopen.

**Comment by omeid** [comment]
I have the same problem, why close the issue without a fix?

**Comment by m-allanson** [comment]
@omeid I had this issue too. I think it's due to Gatsby using an older version of postcss-reporter. [Version 2](https://github.com/postcss/postcss-reporter/blob/master/CHANGELOG.md#200) fixed the problem.

I tried creating a PR for this but couldn't get Gatsby's tests to pass. I assume all these deps will be upgraded when Gatsby switches from webpack 1 to webpack 3.

**Comment by sarneeh** [comment]
Got the same issue. Doesn't affect anything, just annoying :)
