### ISSUE TITLE
Curious about performance on Raspberry PI / More limited machines

### ISSUE THREAD

**Issue by hassanshaikley** [gatsbyjs/gatsby#6791]
Has anyone done any research on what the performance of a Gatsby site is like on a Raspberry PI, at least after loading.

I think I have a PI 1 I can try later tonight perhaps but wondering how that changes across PI versions, and where the bottleneck might be (probably the browser, but I am really curious about the performance after initialization).

Does anyone have any idea?

Not sure if this is a silly question but is there any sort of minimum hardware requirement for Gatsby (at least a general requirement). I will do research on my own later but I wonder if anybody has done any work I can recycle / learn from.

**Comment by KyleAMathews** [comment]
Building or loading a site? For loading a site in e.g. Chrome, a Gatsby site uses generally the same amount of resources as any other site.

**Comment by hassanshaikley** [comment]
Well I'm most interested in the speed post load, so going from page to page and stuff like that.

Is Gatsby ram intensive at all? ( I would imagine it is with its insane speeds )

**Comment by KyleAMathews** [comment]
Not particularly. You can do a memory profile in chrome in a gatsby site easily enough and compare it to other sites. Gatsby is fast mainly because it's really smart about loading things before they're needed instead you needing to wait. That's good design not anything that takes more resources.

I suggest trying a few site on a PI and seeing what happens! Good luck!
