### ISSUE TITLE
Maintainers being added for sites.yml updates

### ISSUE THREAD

**Issue by giraffesyo** [gatsbyjs/gatsby#6813]
Hi,

I noticed that in #6811 gatsbot commented about welcoming the user to the organization.

If you look at the user's [commits](
https://github.com/gatsbyjs/gatsby/commits?author=stoutlabs) to the repo, this is the only one they've made.

It seems silly to give out swag and invite someone to the organization after they updated the sites.yaml to advertise their content (or even after a single commit maybe?). Is this the intended direction of this feature?

**Comment by stoutlabs** [comment]
I thought it was a bit odd too, and I was the one who made the PR! 

(However, I do plan to actually _contribute_ to the project soon... I'm in love with Gatsby, and look forward to helping when possible. ❤️)

**Comment by jlengstorf** [comment]
Hey, @giraffesyo and @stoutlabs!

From the perspective of the @gatsbyjs/inkteam, building a site with Gatsby is 💯 part of being a contributor, and we're more than happy to send you swag for sharing your Gatsby creations with the world!

We're also sending swag and inviting people as maintainers for non-code contributions:

- Writing articles
- Giving talks
- Teaching workshops
- Participating in research
- [and lots of other ways to get involved](https://next.gatsbyjs.org/docs/how-to-contribute/)

We're leaning toward _more_ openness and inclusiveness in our maintainer strategy, since we can roll back anything destructive and coach people (or remove them, if they're obviously acting in bad faith).

It's our sincere hope that adopting a highly welcoming toward contributors of all kinds will build a stronger community, and encourage more people like @stoutlabs to get more involved with contributing to the core repo — and open source in general — in the future. (To that end: Daniel, if you'd like to pair up with an Inkteam member to get started with your first core contribution, [we offer pair programming sessions](https://calendly.com/gatsbyjs/pair-programming).)

I hope that clears up your question, @giraffesyo! Let me know if I can expand on any of this in more detail.

Thanks so much for being here! 💪💜

**Comment by giraffesyo** [comment]
@jlengstorf Cool, thanks for the thought out answer. That sounds like a really good philosophy. Glad to be a part of it!
