### ISSUE TITLE
GraphQL Error Unknown field `siteMetadata` on type `Site`

### ISSUE THREAD

**Issue by menglingyu** [gatsbyjs/gatsby#6847]
GraphQL Error Unknown field `siteMetadata` on type `Site`

**Comment by menglingyu** [comment]
GraphQL Error Unknown field `siteMetadata` on type `Site`

  file: /Users/stronger-yu/git-18/gatsby-site/src/layouts/index.js

  1 |
  2 |   query SiteTitleQuery {
  3 |     site {
> 4 |       siteMetadata {
    |       ^
  5 |         title
  6 |       }
  7 |     }
  8 |   }

**Comment by mattbag** [comment]
Are those in your gatsby-config?
```
module.exports = {
  siteMetadata: {
    title: 'Matt Bagni @ 2018 w/ Gatsby_v2',
    author: 'mattbag.github.io',
    description: 'A starter blog demonstrating what Gatsby can do.',
    siteUrl: 'https://gatsbyjs.github.io/gatsby-starter-blog/',
  },
  // pathPrefix: '/gatsby-starter-blog',
  plugins: [ ...
```

**Comment by Chuloo** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues as many of them have already been resolved with the latest updates.

Please make sure to update to the latest Gatsby version and check if that solves the issue. Let us know if that works for you by adding a comment 👍

**Comment by kakadiadarpan** [comment]
This issue is being closed because there hasn't been any activity for at least 30 days. Feel free to [open a new one](https://github.com/gatsbyjs/gatsby/issues/new/choose) if you still experience this problem 👍
