### ISSUE TITLE
is there a blog starter for this lib, similar to Ghost js that works with firebase? (question)

### ISSUE THREAD

**Issue by jasan-s** [gatsbyjs/gatsby#685]

**Comment by emilyaviva** [comment]
Do you mean, can you load content dynamically from a Firebase database, like a WordPress blog loads its data from a MySQL database? Or do you mean, is there a way to hook up Firebase so that the Gatsby build process reads JSON (or whatever) from Firebase and compiles those into static pages, rather than locally hosted files, as part of its build process?

**Comment by Unforgiven-wanda** [comment]
@emilyaviva Now I wish you'd answered your own questions ^^

**Comment by emilyaviva** [comment]
Can you load content dynamically with Firebase and use Gatsby to render it on-the-fly? No, but you can use React—that's not what Gatsby is for.

Could you write an extension for Gatsby that would grab JSON objects from Firebase and run them through a wrapper to generate static HTML? Absolutely! (In principle, anyway!)

**Comment by KyleAMathews** [comment]
@emilyaviva well Gatsby *is* React :D 

You could have a React.js Gatsby page that doesn't render anything on the server but in the client loads data from firebase and renders it. That'd be totally reasonable. Gatsby is just React after all. Also there's many scenarios where you want to build something that has both static elements and dynamic elements and Gatsby helps you easily blend the two.

**Comment by emilyaviva** [comment]
@KyleAMathews Well, yes, I suppose so, you could do it that way!

**Comment by adamleithp** [comment]
Wow, you're here too. lol. Better start developing it then.
