### ISSUE TITLE
gatsby-source-dropbox plugin

### ISSUE THREAD

**Issue by xuopled** [gatsbyjs/gatsby#6883]
## Summary

Hello, I was looking for some plugin to fetch content from Dropbox but I did not find any. Is there a reason ? I found [this issue](https://github.com/gatsbyjs/gatsby/issues/324#issuecomment-225398868) where @KyleAMathews speaking about fetching content from Dropbox 2 years ago. Maybe there is some example somewhere

### Basic example

I want to build a web app using my sport activities as content. So I connect my services with [Tapirrik](https://tapiriik.com/) and export all my activities to dropbox. So It could be great to fetch content directly to my dropbox repo

**Comment by LeKoArts** [comment]
> Is there a reason ?

No one created a source plugin yet, easy as that 😅
You could create it if you don’t want to wait for someone else to do it:
https://next.gatsbyjs.org/docs/source-plugin-tutorial/

**Comment by xuopled** [comment]
Thank you for the link

**Comment by oorestisime** [comment]
this looks fun. i ll work on a dropbox source plugin.

**Comment by oorestisime** [comment]
Hey, so i ve worked out a plugin here https://github.com/oorestisime/gatsby-source-dropbox
it is not published yet since i am waiting on the PR i referenced here. You could install this along with the plugin-source-filesystem of the PR to test it :) 

After talking a bit on discord i dont think it makes sense to PR the whole plugin in the main gatsby repo so i am closing the issue. Feel free to open issues / propose features on the other repo.
For the moment i am tracking the release issues here https://github.com/oorestisime/gatsby-source-dropbox/issues/1

**Comment by oorestisime** [comment]
@xuopled it is now released
