### ISSUE TITLE
v2 docs change - make sure layout components changes are reflected in docs

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#6912]
## Why make this change?
Part 3 of the tutorial (and other parts of the docs) should reflect that layout components work differently in Gatsby now. We need to come up with something to replace the content in Part 3 and other parts of the docs that talk about layout components. 

Here's the explanation of what removing layout components means:
https://next.gatsbyjs.org/docs/migrating-from-v1-to-v2/#remove-or-refactor-layout-components

## Tutorials
Both v1 and v2 tutorials look identical for Part 3 right now, and they shouldn't because layout components have been removed from Gatsby.
v1 tutorial Part 3: https://www.gatsbyjs.org/tutorial/part-three/#our-first-layout-component
v2 tutorial Part 3: https://next.gatsbyjs.org/tutorial/part-three/

## The rest of the docs
There are likely mentions of layouts in places other than the tutorial, and those will need to be edited as well.

**Comment by shannonbux** [comment]
@Chuloo I think this issue includes the `StaticQuery` change you'd like to make. https://next.gatsbyjs.org/docs/migrating-from-v1-to-v2/#5-change-query-to-use-staticquery

**Comment by jlengstorf** [comment]
Hey, @shannonbux — I'm not sure if work was done to update this, but I just took a look at part three in the v2 tutorial, and it uses the new layout pattern (which is to create a `Layout` component in the `src/components/` directory.

I'm going to close this for now, because I believe everything is V2-correct in the tutorial in relation to layouts. Please reopen if I'm misunderstanding the issue.
