### ISSUE TITLE
[gatsby-source-contentful] TypeError: Cannot read property 'internal' of null

### ISSUE THREAD

**Issue by akolybelnikov** [gatsbyjs/gatsby#6949]
## Description

Build fails with: 
```
Fetch Contentful data: 250.798ms
success source and transform nodes — 1.107 s
error UNHANDLED REJECTION

  TypeError: Cannot read property 'internal' of undefined

  - infer-graphql-type.js:227 _.uniqBy.v
    [blumenhaus]/[gatsby]/dist/schema/infer-graphql-type.js:227:44

  - lodash.js:4296 baseUniq
    [blumenhaus]/[lodash]/lodash.js:4296:35

  - lodash.js:8418 Function.uniqBy
    [blumenhaus]/[lodash]/lodash.js:8418:40

  - infer-graphql-type.js:227 inferFromFieldName
    [blumenhaus]/[gatsby]/dist/schema/infer-graphql-type.js:227:15

  - infer-graphql-type.js:354 _.each
    [blumenhaus]/[gatsby]/dist/schema/infer-graphql-type.js:354:23

  - lodash.js:4925
    [blumenhaus]/[lodash]/lodash.js:4925:15

  - lodash.js:3010 baseForOwn
    [blumenhaus]/[lodash]/lodash.js:3010:24

  - lodash.js:4894
    [blumenhaus]/[lodash]/lodash.js:4894:18

  - lodash.js:9342 Function.forEach
    [blumenhaus]/[lodash]/lodash.js:9342:14

  - infer-graphql-type.js:333 _inferObjectStructureFromNodes
    [blumenhaus]/[gatsby]/dist/schema/infer-graphql-type.js:333:5

  - infer-graphql-type.js:403 inferObjectStructureFromNodes
    [blumenhaus]/[gatsby]/dist/schema/infer-graphql-type.js:403:10

  - build-node-types.js:150 createNodeFields
    [blumenhaus]/[gatsby]/dist/schema/build-node-types.js:150:30

  - build-node-types.js:183 fields
    [blumenhaus]/[gatsby]/dist/schema/build-node-types.js:183:25

  - Array.forEach
```

### Steps to reproduce

I have republished a few contentful nodes, so these have more than one version. The develop build started failing immediately after that.

I believe this issue might be related to [#4479](https://github.com/gatsbyjs/gatsby/issues/4479). I have taken the suggested steps, installed and ran the contentful-links-cleaner, which showed no broken links in the space.

I have uninstalled and re-installed node_modules.

### Environment

- Gatsby: 2.0.0-beta.14
- Gatsby-cli: 2.0.0-beta.3
- Node: 10.6.0
- OS: Windows 10

**Comment by tbaustin** [comment]
I am getting the same error when trying fetch cache after using `createRemoteFileNode` from `gatsby-source-filesystem`. 

```
let updated = {}

          if (res[`webImages`]) {
            const updatedImages = await Promise.all(
              res[`webImages`].map(async img => {
                let fileNodeID
                const webImageCacheKey = `web-images-${img.id}`
                // TypeError: Cannot read property 'internal' of null on 2nd run
                const cacheMediaData = await cache.get(webImageCacheKey)

                if (cacheMediaData) {
                  fileNodeID = cacheMediaData.fileNodeID
                  touchNode({ nodeId: cacheMediaData.fileNodeID })
                }

                if (!fileNodeID) {
                  try {
                    const fileNode = await createRemoteFileNode({
                      url: cloud(img.url, `w_2000`, `dn_72`),
                      store,
                      cache,
                      createNode,
                      createNodeId,
                    })

                    if (fileNode) {
                      fileNodeID = fileNode.id
                      await cache.set(webImageCacheKey, {
                        fileNodeID,
                      })
                    }
                  } catch (e) {
                    // Ignore
                    console.log(`ERROR ${e}`)
                  }
                }
                if (fileNodeID) {
                  return fileNodeID
                }
              }),
            )
            updated.localWebImages___NODE = updatedImages
          }
          console.log(updated)
          return { ...node, ...updated }
```

**Comment by ldelbeccaro** [comment]
Same for me on Gatsby 1.9.277. No broken links with `contentful-link-cleaner`.

Neither `gatsby develop` nor `gatsby build` works on my machine (mac OSX), but `gatsby build` is fine when it builds on Netlify (Linux).

**Comment by stoltzrobin** [comment]
@akolybelnikov @ndjamenamarmon @ldelbeccaro 
Have you tried deleting the .cache folder? otherwise try that.

**Comment by ldelbeccaro** [comment]
I ended up creating a new space in Contentful with the same schema, switching to that space, then switching back. That worked, so it was likely a cache issue, but I can't say for sure because I can no longer reproduce.

**Comment by akolybelnikov** [comment]
@stoltzrobin I can confirm that in Gatsby@2.0.0-rc.0 the issue can be resolved by deleting the .cache folder. This did not work in Gatsby@2.0.0-beta.3 though.

**Comment by sarahbethfederman** [comment]
This is still broken in 2.0.40 and deleting .cache doesn't seem to help

**Comment by akselinurmio** [comment]
I don't care for this stale bot system a bit, but this issue isn't stale. If anyone doesn't fix stuff, it's okay, but covering things up by just closing issues isn't a solution.

**Comment by pieh** [comment]
@akselinurmio stale stuff is automatic, we don't manually mark issues as stale.

It would be great if we have reproduction for this issue, but we don't so we have no way of finding actual problem and fixing it.

**Comment by akselinurmio** [comment]
@pieh, I know it's automatic (that's why I wrote ‘stale bot system’) and I think it's problematic. But that's not a discussion to have here. 😄

**Comment by KyleAMathews** [comment]
"covering things up" is pretty strong language :-)

FWIW, I _don't_ think it's problematic — software always has problems — we as an ecosystem/core team need to focus on the most pressing issues — the ones with the largest impact and affecting the most users. If an issue _doesn't_ get any comments or isn't fixed, then in all likelihood it's not affecting that many people.

Also, as @pieh mentioned, this issue isn't fixable given it doesn't have a reproduction.

Auto-closing low-quality issues like this leaves room for better issues you can create with good reproductions ;-)

**Comment by akselinurmio** [comment]
As I completely agree with you @KyleAMathews on the fact that all issues are not fixable, I do think that closing issues as non-fixable or non-reproducible is a human job.

People should always be told what they are doing wrong. If the issue is low quality, tell it. If the bug can't be reproduced, tell it. After that if nothing happens, only then I think auto-closing is acceptable.

The issue not gathering any replies is not always low quality or not affecting people. The current bot implementation doesn't evaluate the importance of issues in any way. Many of the issues that have been or are being auto-closed are labeled as "to be reviewed". That doesn't seem right to me.

At least we should add labels to problematic issues. Many OSS projects are doing that and I think that helps the project and people using the software a lot.

**Comment by pieh** [comment]
@akselinurmio that's why we don't close issues and put up this "warning" message first: 

> We get a lot of issues, so we currently close issues after 30 days of inactivity. It’s been at least 20 days since the last update here.
> 
> If we missed this issue or if you want to keep it open, please reply here. You can also add the label "not stale" to keep this issue open!

So anyone subscribed to the issue can comment, which will reset "stale-ness" counter. And even if bot will close the issue - it can be re-opened or new one created (this also is included in the message that bot adds when closing the issue: `Please feel free to reopen this issue or create a new one`. 

It's not ideal but closing issue being `human job` just doesn't scale - we tried it - result was that issues were never getting closed and people couldn't find up to date information, because there was just too much traffic to handle both new issues and do triaging of "old" ones (and do actual bug fixing work, adding features and doing PR reviews).

I know it sucks if your issue is getting closed without proper resolution, but we hoped that adding as much context to stale system messages as possible, this wouldn't feel as "won't fix" approach.

And we definitely dropped the ball on asking for reproduction in this issue and labelling it appropriately - no arguing on this one.

**Comment by KyleAMathews** [comment]
The meta issue here is we need help to know if an issue is real and to figure out how to solve it. Reproductions are the best way to do that.

**Comment by KyleAMathews** [comment]
Oops, didn't mean to close it

**Comment by jonniebigodes** [comment]
@akselinurmio speaking from a contributor's perspective, we, at the lack of a better definition exist to take the pressure from the core team, helping out as much as possible, with some more vocal than others. And also some would be awesome detectives, because they can pinpoint the actual issue and provide an answer just by looking at the error or title or description.

From the time i've been here i caught a glimpse on how a monumental task it can be to have one,two,three, four people trying to handle the issues, redirecting them to the appropriate labels, performing some "house cleaning", by closing them to avoid "loose ends" laying about, 

With that on my mind and on a more personal note, i usually sync my email account at 6h30 am while i'm having my cup of coffee. I filter the issues i'm sure i can help out. Go about my business, re-check the email during my lunch hour, or when i get back home. if it has not been provided an answer i try to come up with a reproduction/solution and provide with the most detailed answer i can provide. Some might think of this as "fanboyism" or other adjectives similar, me personally i think of it as a challenge, where i can learn something new with every issue. And boy let me tell you it's been a real challenge, with some being easily fixed, others attest to the ingenuity of people.

**Comment by amclin** [comment]
This issue happens when there's a GraphQL query that requests a field which is not in the Contentful API responses. Usually it's because of a reference field in Contentful being left empty.

The real problem here IMHO is that the error from Gatsby is completely useless in identifying what query failed.

**Comment by florinme** [comment]
Hi all, I came across this issue from searching Google. 

I'm working on a project using **WordPress + Gatsby** and this issue comes up when I delete an ACF flexible content field in WordPress. I believe this is a problematic and the responsible party is the one that creates/updates the GraphQL schema. I believe Gatsby is responsible for that?

This is a big deal because when developing back-end layout builder fields, clients often will want to remove a column, or module. Because of this, the build will fail.

Deleting the `.cache` folder in Gatsby root fixes it and so I think the temporary fix might be to delete this .cache within the build script. Unless theres something I'm not understanding correctly.

**Comment by shiranZe** [comment]
hi, still can't run `npm run build` or `sudo npm run build` in linux server.
i deleted node modules, `.cache` and `yarn.lock`

**Comment by inblock-io** [comment]
> This issue happens when there's a GraphQL query that requests a field which is not in the Contentful API responses. Usually it's because of a reference field in Contentful being left empty.
> 
> The real problem here IMHO is that the error from Gatsby is completely useless in identifying what query failed.

Correct. I have done everything I can in my case and I cannot find the offending entry. I iterated through all queries used in the current project (thank god it is only a few distinct ones, this would be a death knell in any serious project).

Is there NO way to identify which query or subquery failed?

**Comment by md-weber** [comment]
> Is there NO way to identify which query or subquery failed?
I still have the same issue and it seems that there is really no way...
