### ISSUE TITLE
[v2] docs / tutorial top nav architecture

### ISSUE THREAD

**Issue by amberleyromo** [gatsbyjs/gatsby#7166]
Capturing notes from discussing with @shannonbux.

# 1. Docs
The side nav under `/docs` currently, with notes:
* QUICK START ^ - _I think this should be DOCS, mirroring the primary nav_
  * Quick start - 👍🏼
  * Starters - 👍🏼
  * Recipes - 👍🏼
  * Overview of the docs - _rename 'Overview', landing paragraph with numbered bullets of the other section categories_
  * Main Tutorial (step-by-step) - _rename 'Tutorial', unnecessarily verbose_

Proposed:
* DOCS ^
  * Overview
  * Quick start
  * Tutorial
  * Starters
  * Recipes
 
# 2. Tutorial
The side nav under `/tutorial` currently, with notes:
- Quick start - _propose eliminating this, it's linked in the tutorial introduction. on the `/tutorial` page I would expect `TUTORIAL` to be the top nav item of the secondary menu.
- TUTORIAL ^
  - Introduction
  - 0 Set up your development environment
  - 1 Get to know Gatsby building blocks
  - 2 Introduction to using CSS in Gatsby
  - 3 Creating nested layout components
  - 4 Querying for data in a blog
  - 5 Source plugins and rendering queried data
  - 6 Transformer plugins
  - 7 Programmatically create pages from data
  - 8 Preparing a site to go live

**Comment by shannonbux** [comment]
thanks @amberley! Would you mind somehow making sure these notes are
discoverable via [EPIC] Docs redesign phase 2?

Also, agree with all proposed changes except overview of the docs possibly.
The quick start is intentionally the default view when people land on the
docs because most developers I've interviewed immediately want to see
something they can install.

Re: overview page. I actually prefer a nice landing page with an overview,
but I'm not sure where to put the overview, or if we should even have it.
This is one of the differences I've noticed when showing the .org site to
designers/educators vs. devs. Devs prefer the quick start, designers want a
clean landing page with only a search bar, or a very simple overview with
like 4 buttons.

I have an idea to have a "featured docs" page in [EPIC] Docs redesign phase
3, which would probably involve a pretty landing page. Not sure this will
fly haha! We'll have to weigh the data we have against what we
intentionally want to share.

**Comment by amberleyromo** [comment]
> making sure these notes are discoverable via [EPIC] Docs redesign phase 2?

sure! though it looks like there are two? #6900, #7128

> Re: overview page

Definitely worth further discussion! I see a really great case for a nice landing page with a more custom design hitting `/docs` -- since we never know who will be hitting the page, we could make the overview page a way for people to self-route.
