### ISSUE TITLE
[gatsby-source-mongodb] Race condition when specifying the more than 1 collection

### ISSUE THREAD

**Issue by michalczaplinski** [gatsbyjs/gatsby#7223]
## Description

When specifying more than 1 collection, there is a race condition between the promises for each of the collections. The first promise to resolve, closes the database connection thus preventing access for the other on line 60:

https://github.com/gatsbyjs/gatsby/blob/ac5ddfaa237eeecb1209fbcae1158769cb517050/packages/gatsby-source-mongodb/src/gatsby-node.js#L60-L67

### Steps to reproduce
https://github.com/michalczaplinski/mongo-bug-reproduction/tree/bug/mongo-underfetching

It can be verified by running the project (on the `bug/mongo-underfetching` branch), opening `localhost:8000/___graphql` and running the following query: 
```
{
  allMongodbGatsbyContacts {
    totalCount
    edges {
      node {
        id
        first_name
      }
    }
  }
}
```
Gatsby will only fetch about 100 results. 

Then, you can change ```        collection: [`companies`, `contacts`],
``` line in `gatsby-config.js` to        ``` collection: [`contacts`]``` and verify that 10459 documents are fetched.

### Expected result

The plugin should fetch all documents for each collection.

### Actual result

Only a subset of documents is fetched.

### Environment

```
  System:
    OS: macOS High Sierra 10.13.4
    CPU: x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.9.1 - ~/.nvm/versions/node/v8.9.1/bin/node
    Yarn: 1.7.0 - /usr/local/bin/yarn
    npm: 5.5.1 - ~/.nvm/versions/node/v8.9.1/bin/npm
  Browsers:
    Chrome: 68.0.3440.106
    Safari: 11.1
  npmPackages:
    gatsby: ^1.9.277 => 1.9.277
    gatsby-link: ^1.6.46 => 1.6.46
    gatsby-plugin-react-helmet: ^2.0.11 => 2.0.11
    gatsby-source-mongodb: ^1.5.21 => 1.5.21
  npmGlobalPackages:
    gatsby-cli: 1.1.58
```

### File contents (if changed)
See the reproduction.

PR coming in  a few minutes...

**Comment by LuisLoureiro** [comment]
Hey guys.
I'm facing the same problem as @michalczaplinski  but I'm using **Gatsby v1**.
I tried to update the version of the `gatsby-source-mongodb` dependency in my `package.json` to the `next` dist-tag (i.e. 2.0.0-rc.0) but it causes an error compiling my site:
```
  ReferenceError: actions is not defined

  - gatsby-node.js:19 Object.exports.sourceNodes
```
Seems that the `sourceNodes` API changed the name of the `boundActionCreators` to `actions` in **Gatsby v2** that's why it's giving me an error.

@michalczaplinski I don't want to that credits on your work so, would you mind creating a new PR for v1? ;)
Thanks in advance!

**Comment by michalczaplinski** [comment]
Hey @LuisLoureiro 

Yeah, you’re right about the API change :)

I saw that you already created a PR yourself #7676. I’m a new contributor, but I’ve read in contributing guidelines that someone from the gatsby team will  normally back port the changes made to the v2 .

**Comment by LuisLoureiro** [comment]
Hi @michalczaplinski !

Yes, I decided to create a new PR because I was (and I still am) in need of this change.

> but I’ve read in contributing guidelines that someone from the gatsby team will  normally back port the changes made to the v2 .

Back porting changes made to **v2** sounds really cool. I searched for that in the docs but I couldn't find that.
The really meaningful thing I found (taking in consideration this problem) is that fixing bugs in **v1** are still acceptable but not new features.

I suppose that Gatsby team is really involved in a lot of new features and issues but a lot of time has passed since your PR and nothing changed in the `gatsby-source-mongodb`.
The PR I created is still waiting for someone to review it. I don't know if there's something wrong with it, still has no comments.
