### ISSUE TITLE
[v2] Additional div wrapper

### ISSUE THREAD

**Issue by LeKoArts** [gatsbyjs/gatsby#7310]
On one of my sites with the latest Gatsby I noticed that my layout is wrapped with an additional div:

```HTML
<div style="outline:none" tabindex="-1" role="group">Normal content</div>
```

You can also see this behavior on https://next.gatsbyjs.org/
Why is that happening?

**Comment by KyleAMathews** [comment]
@reach/router adds it so it can automatically manage the focus as part of making sure sites are usable by screen readers.

https://reach.tech/router/accessibility

**Comment by jonysam** [comment]
I realize this is quite silly but I think it would be preferable if there was only one wrapping div.

It doesn't seems to be anything special about the reach div, would it perhaps be possible to merge the reach div with the wrapping `id="___gatsby"` div by adding the html attributes there instead?

**Comment by KyleAMathews** [comment]
It's unfortunately not possible to merge the two. Perhaps you could work with @reach/router on them reusing the div where React is mounted.

**Comment by colmtuite** [comment]
I need to add `height: 100%` to it but there's no `class` or `id` on it. I tried looking for it in the app but can't find it. Can you tell me how I can add an `id` to it?

**Comment by janosh** [comment]
@colmtuite It's not ideal but since the grouping `div` is the only child of `<div id="___gatsby">`, you can simply target it via
```
#___gatsby > * {
    height: 100%;
  }
```

**Comment by kaishin** [comment]
Relevant issue: https://github.com/reach/router/issues/63

I personally think this is misguided and is a source of issues for those not using styled components.

**Comment by janosh** [comment]
@kaishin Could you expand on what you mean? What exactly is misguided?

**Comment by kaishin** [comment]
@janosh I meant the decision of reach/router maintainers to not provide a way to disable, or at least customize this wrapper div. I am a big proponent of semantic HTML and I am bummed that I have to deal with yet another wrapper div that only serves as a hook to a library that I barely knew about before facing this issue.

**Comment by janosh** [comment]
I understand your point now and quite agree. I feel much the same about non-semantic markup.
I was just confused by the end of your comment
> ... is a source of issues for those not using styled components

as I don't see why people who _are_ using `styled-components` would be unaffected.

**Comment by danielo515** [comment]
I can't believe this issue has been closed with so unreasonable solution.

**Comment by kaishin** [comment]
@danielo515 Well, the issue is with a dependency, so it's somewhat understandable.

This comment offers a CSS workaround: https://github.com/reach/router/issues/63#issuecomment-428050999

**Comment by LekoArts** [comment]
> as I don't see why people who are using styled-components would be unaffected.

@janosh Since I opened this issue I didn't have any problems whatsoever with styling. So what's the problem here actually?

**Comment by janosh** [comment]
@LekoArts Unsemantic markup that breaks CSS solutions for keeping the footer at the bottom of the window even in the absence of sufficient content. Using `styled-components` and knowing a workaround CSS selector doesn't make the wrapper `div` any more semantic.

**Comment by skinenbayev** [comment]
@colmtuite Consider to use something like height: 100vh.

**Comment by Schmerb** [comment]
@skinenbayev @colmtuite 
Or with flex,
```
div[role="group"][tabindex] {
  display: flex;
  flex-direction: column;
  flex-grow: 1;
}
```

**Comment by skinenbayev** [comment]
@Schmerb I think setting 100vh to your css dedicated class is more convenient way than manipulating with some generated code.

**Comment by Schmerb** [comment]
@skinenbayev 
I guess I should have clarified...`100vh` is great if you want your app to have a fixed height the same size as your viewport...

<b>BUT</b>  if you need the app to take up all available space

(essentially what everyone with `height: 100%` is attempting but is most likely failing due to parent not having a set height)

then <b>`Flexbox`</b> to the rescue.

To further clarify my specific case, screenshots of both attempts:
The blue/orange border is a `/page` component. The random 'hook' div that Gatsby places is the white space. With `height: 100vh` the white space can be seen extending well below the bottom of the viewport...pushing the footer off the page even though the page itself essentially has no content.

Using `flex` with its main axis switched (`flex-direction: column` instead of default `flex-direction: row`) and flex-grow property, you can see it very nicely takes up all available space.

with ```height: 100vh;```
![Screen Shot 2019-03-18 at 3 40 21 PM](https://user-images.githubusercontent.com/18368207/54558496-48fc6a00-4994-11e9-806e-dcbd20cba10f.png)

with ```
display: flex;
  flex-direction: column;
  flex-grow: 1;```
![Screen Shot 2019-03-18 at 3 40 11 PM](https://user-images.githubusercontent.com/18368207/54558530-5f0a2a80-4994-11e9-8ca5-554bfc16c771.png)

**Comment by danielo515** [comment]
All that I see are workarounds for a problem that should not even exist.
What if your target browser does not support flexbox?

**Comment by JoshLong23** [comment]
I've had issues as well with a bug when setting `height: 100vh' where when scrolling is required, I get a double scrollbar in chrome.

The way I've solved a similar problem is rather than use `height: 100vh;`, is to add `min-height: 100vh;` to my wrapping `Layout` component. When you combine that with something like setting:
`grid-template-areas: 'Header' 'Content' 'Footer';`
`grid-template-rows: auto 1fr auto;`
`min-height: 100vh;`

Now, the wrapping component will always be _at least_ the height of the view port, but if the content is large enough to require scrolling, the footer element will be pushed to remain at the bottom of the screen.

But (big but!) unfortunately, grid has less browser support than flexbox, but it feels less 'hacky' personally. 

Maybe not an answer to help with not having flex support, but perhaps a neater way to get a footer to stick to the bottom of the page?

**Comment by spiritcapsule** [comment]
Unfortunately, while the line of code in question addresses accessibility, it also causes an accessibility error. I've logged an issue at https://github.com/reach/router/issues/257.

**Comment by nilfalse** [comment]
Be aware that `100vh` might mean something different to Android browsers.
Quick googling unveiling example: https://stackoverflow.com/q/30148956

**Comment by gabrielmoncea** [comment]
For some reason `div[role="group"][tabindex]` is not applying any style to that div. I had to specify the id `#gatsby-focus-wrapper`

**Comment by Diveafall** [comment]
Still no reasonable solution to the height problem?

**Comment by jgaehring** [comment]
I used this in my root CSS and it has fixed similar issues I had with height and other properties:

```css
#___gatsby, #gatsby-focus-wrapper {
  all: inherit;
}
```

Now if I make any changes to the `html` or `body` elements, like the `display` property etc, the Gatsby wrappers are effectively transparent, and I can forget about them. Not sure if this would work in all cases, but for my project it does the trick, and seems like a pretty sustainable solution.

**Comment by HeyParkerJ** [comment]
To elaborate on @jgaehring's solution - I put this in src/pages/styles.css and then in src/pages/index.js

```
import "../styles.css"
```

**Comment by astroTANSAN** [comment]
For people who want to a 100% height div, this is the next best thing that worked for me without hacky fixes.
```
<Router style={{height: '100%'}}>
...
</Router>
```

**Comment by barbalex** [comment]
> For people who want to a 100% height div, this is the next best thing that worked for me without hacky fixes.
> 
> ```
> <Router style={{height: '100%'}}>
> ...
> </Router>
> ```

This does not work if you use gatsby but not reach-router itself. We have absolutely no control but gatsby forces us to deal with a div inserted by reach-router that breaks our styling in very complex and misterious ways.

We have so far spent many hours on this issue.

Not to mention that reach-router has been basically dead since Oktober 2019.

Plus: A huge chunk of react apps use react-router proper, for lots of great reasons (loaders, outlets...). Yet gatsby keeps forcing reach-router onto us.

Seems that the only way to get control over our app's dom tree and be able to use a modern router is to migrate away from gatsbyjs. 

Or maybe not? @KyleAMathews @LekoArts Is gatsby going to migrate to react-router proper any time soon?
