### ISSUE TITLE
NPM Audit issues when creating new Gatsby project

### ISSUE THREAD

**Issue by GiraffeCoding** [gatsbyjs/gatsby#7360]
## Description

Getting npm audit issues on:

- webpack-dev-server (critical status)
- gatsby > webpack-configurator > lodash (low status)
- gatsby > webpack-validator > lodash (low status)
 
### Steps to reproduce

In terminal:

`Gatsby new Gatsby-site`

### Expected result

No audit issues

### Actual result

got 3 npm audit issues

### Environment

Mac OS X

**Comment by jonniebigodes** [comment]
a simple answer to this is that even with the updates on project, it depends on some packages that might be somewhat outdated mostly due to the minor versions mostly. the webpack one is due to the fact that gatsby version 1 relies on a older version of webpack so you might get those issues. My thoughts on this read the docs, try to understand ou it works, fiddle with it and keep an eye also on the upcoming version of gatsby, so when drops you're not completely in the dark.

**Comment by sidharthachatterjee** [comment]
This is fixed for now and `gatsby new` results in no `npm audit` issues

Closing this
