### ISSUE TITLE
[www] doesn't show selected state along top nav bar

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#7425]
### Initial problem

Many users, when they are on the Tutorial page, can't remember how to get back to Docs.

In an effort to solve this issue, I made a link to the Main Tutorial under Quick Start category in Docs. I also made a link to the Quick Start doc at the top of the Tutorial sidebar. 

It appears this has created more confusion and didn't solve the initial problem. So that's getting taken care of in Issue #7424 

Let's make sure we make the selected state along the top nav bar clear and see if it solves the initial problem.

**Comment by arzafran** [comment]
Let me know if I understood well and my approach fixes the issue.

**Comment by fk** [comment]
Thanks for adding this @shannonbux! 🙏

**Comment by fk** [comment]
Hey @arzafran! 👋
Thank you for your PR, looking good! 🤗 

Coincidentially I also took a look at this over the weekend. I didn't even consider using `font-weight: bold` because I thought that it would cause the sibling nav items to "jump", but your PR looks nice -- much less of an issue than I thought!

FWIW I added some [mockups](https://www.figma.com/file/G3x7aYuyigYaibEpyxMsKLcP/gatsbyjs.org%3Ashowcase-starters?node-id=91%3A2227) showing some variants (for both (basically interchangable) "selected" and "hover" states):

<img width="699" alt="bildschirmfoto 2018-08-20 um 16 54 09" src="https://user-images.githubusercontent.com/21834/44348054-b6e1c100-a499-11e8-8ebb-fc184710ec53.png">

**Comment by arzafran** [comment]
Nice Mockups!
I just took the easiest approach but you're right it makes the page 'jump' a little. but since paddings were a little off making any background decoration look misaligned I went with it and just used the font-weight to know if my idea was in the right direction.

**Comment by fk** [comment]
> Nice Mockups!
> I just took the easiest approach […]

Thank you! And: Nothing wrong with the easiest approach -- super happy you're working on this!

> but since paddings were a little off making any background decoration look misaligned

Oh yeah, I saw that, too. 😁
Feel free to change that if you want to take another look!

**Comment by fk** [comment]
Just stumbled upon #2516 :-/ 🙄
