### ISSUE TITLE
[www] do 2 more usability tests to verify whether overview articles clearly indicate they have content

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#7426]
#### Clicking on titles
1. User clicks on title
2. Category expands
3. User clicks on title again

### Expected behavior
Category would collapse

### Actual behavior
Category does not collapse

_____________________________
Related user data:
#### Clicking only on arrows
1. User clicks on arrows next to overview article titles
2. User never clicks on title itself, so never sees overview article content

**Comment by fk** [comment]
FWIW I believe we predicted this might happen when we first discussed this. ;-) :-/

To recapture: Given that the user currently is viewing **page A**,
the benefit the current implementation offers to the user is

* an item linking to a **page B**, and containing subitems
* can be expanded/collapsed via the "caret" button _without_ forcing the user to leave page A,
* its "introduction" or "overview" page is accessible with _one_ instead of _two_ clicks (the latter two clicks being 1) to expand the accordion and 2) to click the first of the now expanded links)

We could (without much effort I believe) add the described expected behavior:

* user clicks the title of an item that contains subitems
* subitem visibility is toggled (expanded if hidden, collapsed if visible)

I personally would not expect this behavior, but that's another topic… :-)

---

IMO the "related user data" you mention here presents the bigger issue:
Users are **missing out on content** because the UI _does not currently imply_ that if the user choses to expand an item's subitems, they really (should? ;-)) want to navigate to the page associated with the item.

What can we do to avoid confusion ((over)thinking out loud)?

1) All items that are containing subitems can _not_ link to a page
 * pros:
   * clears up confusion -- an item either allows to toggle its subitems _or_ links to a page
   * users can control which nested items they want to see without being forced to leave the current page
 * cons:
    * potentially two clicks to discover content -- click the item title to expand its subitems, click the first subitem
    * we need to revise our current "title" styles (e.g. "[Tutorial (Step-by-step)](https://next.gatsbyjs.org/tutorial/)" so that they work for longer item titles like e.g. "[0. Set up your Development Environment](https://next.gatsbyjs.org/tutorial/part-zero/)"

2) Clicking an item linking to a page and containing subitems implicitly expands the latter (while still navigating to the page associated with the item)
 * pros:
    * resolves the "user misses out on content" issue
 * cons:
    * user loses control over subitem "expanded/collapsed" state
    * the "discoverability" of subitems is implicitly connected to page navigation
    * we probably would want to implicitly collapse all subitems but the ones that are associated with the currently active item

3) Add clearer "hover" states -- it seems the bullet point shown when hovering the title is not clear enough; we could add a background color here to make things clearer (at least for desktop), and also extend the white background shown when hovering just the "caret" button to cover the whole height of the item

**Comment by kkemple** [comment]
@fk and/or @shannonbux could someone provide me with an update on the state of this issue? What is the work to do here?

**Comment by shannonbux** [comment]
oh hi @kkemple this is something I should assign to myself. Will do that
right now. I need to do two more usability tests to really verify if this
is an issue or not
