### ISSUE TITLE
[doc] Improve the doc about how to handle global styles

### ISSUE THREAD

**Issue by Manoz** [gatsbyjs/gatsby#7447]
As discussed [here](https://github.com/gatsbyjs/gatsby/issues/7413#issuecomment-413944617) we should improve the documentation about how to handle global styles and css-in-js in gatsby-browser.js .

As Kyle said: _gatsby-browser.js isn't included when server rendering which means styles there aren't extracted and inlined in the generated html files_ so we should be more clear about this.

Thanks for the report @alexandernanberg :)

**Comment by durwasa-chakraborty** [comment]
If this issue is still open I would like to contribute and get familiarized with the code base, not only because of the goodies but because I am almost fed up with Octopress. 😄 

Here is my understanding - 
We try to avoid the use of globals (like `.button {...}`) by in-lining the style components. Since, styles are not extracted in server renderings we need to explicitly include the style components that does not involve server renderings and `global-styles.js` is a good candidate for that.
