### ISSUE TITLE
Set key on <img> inside gatsby-image

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#7585]
The `key` should be set on components so that React knows to reset the image when the props change. `gatsby-image` doesn't currently do this which means if you try passing in different props to the same `gatsby-image` component, it'll briefly show the old version of the image before showing the new one.

Probably the simplest way to do this is to set the `src` prop passed into the component as the `key` on the outermost layer.

https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-image/src/index.js

**Comment by roachnt** [comment]
#7587 is this what you're looking for Kyle?

**Comment by sat0yu** [comment]
> Probably the simplest way to do this is to set the src prop passed into the component as the key on the outermost layer.

added `key` prop in the most outer element of `gatsby-image` component.

I'd like to add tests for this change from now. 
however it's a bit hard to me since `react-testing-library` seems not to write `key` prop out in snapshot.

does anyone have a good idea?

**Comment by luanorlandi** [comment]
Hello guys 👋  I'd an investigation on this issue.

Setting `key` value as the image `src` is a good way, but I don't think is the ideal approach.
Think about two images with the same `src`, they could be different with their own props, so both should have a unique `key`.

It would be better to let the developer choose the value of the key as a `prop`, in this case a prop `key` would not work on the current version of React, since it's a [special prop](https://reactjs.org/warnings/special-props.html).

Also, is this issue only on v1? I did some tests on v2, seems to be working fine, React pass on the `key` as expect.

**Comment by stefanprobst** [comment]
Can you share an example how to reproduce this? Thanks.

**Comment by KyleAMathews** [comment]
@luanorlandi makes sense! The key should be a compound then of several props e.g. if it's fixed or fluid and the src and the srcset.

**Comment by stefanprobst** [comment]
Although this has now been closed, I am still unclear about what the actual problem is?
