### ISSUE TITLE
Implement pagination for starter showcase

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#7608]
@amberleyromo here's an edit from the future!

Design: the plan is to imitate blog pagination like so: https://github.com/gatsbyjs/gatsby/pull/7523

**Comment by shannonbux** [comment]
@NickyMeuleman thought you might have ideas of how to do this--want to go for it?

**Comment by NickyMeuleman** [comment]
To be clear, you mean for this https://github.com/gatsbyjs/gatsby/pull/6113 ?
Would that then also be mirrored in the regular site showcase, since the designs are very similar?

Keeping the same look/feel everywhere seems valuable, so the same pagination as in https://github.com/gatsbyjs/gatsby/pull/7523.
Or keep the "load more" button that is there now. The total amount of starters found is shown in the header (and responds to filters), so the user knows what to expect and won't endlessly click that button.

Will definitely give it a try. Code looks complex, so no promises ;)

**Comment by shannonbux** [comment]
Ok update here @amberleyromo, this will stay assigned to you! Thanks to @NickyMeuleman for laying a foundation in #7523 👍
