### ISSUE TITLE
[EPIC] Improve wordpress integration

### ISSUE THREAD

**Issue by pieh** [gatsbyjs/gatsby#7624]
### Who will own this?

_What Area of Responsibility does this fall into? Who will own the work, and who needs to be aware of the work?_

**Area of Responsibility:**

_Select the Area of Responsibility *most impacted* by this Epic_

- [ ] Admin
- [ ] Cloud
- [ ] Customer Success
- [ ] Dashboard
- [ ] Developer Relations
- [x] OSS
- [ ] Learning
- [ ] Marketing
- [ ] Sales

     |                 |       |
     | --------------- | ----- |
     | AoR owner       | @KyleAMathews |
     | Domain owner    | TBD |
     | Project manager | TBD |
     | Tech lead       | TBD |
     | Contributors    | TBD |

### Summary

Wordpress plugin works fine for smaller sites, but it's getting very slow and unreliable for larger sites. Big problem here is that Gatsby will pull all data on each bootstrap. We could improve speed of pulling data if we would support incremental data fetching (ask just for data that has changed since last time). This would involve create actual wordpress plugin to add support for that in wordpress endpoints.

### How will this impact Gatsby?

**Domains**

_List the impacted domains here_

**Components**

_List the impacted Components here_

### Goals

_What are the top 3 goals you want to accomplish with this epic? All goals should be specific, measurable, actionable, realistic, and timebound._

1.  
2.  
3.

### How will we know this epic is a success?

_What changes must we see, or what must be created for us to know the project was a success. How will we know when the project is done? How will we measure success?_

**User Can Statement**

- User can...

**Metrics to Measure Success**

- We will see an increase /decrease in...

### Additional Description

_In a few sentences, describe the current status of the epic, what we know, and what's already been done._

### What are the risks to the epic?

_In a few sentences, describe what high-level questions we still need to answer about the project. How could this go wrong? What are the trade-offs? Do we need to close a door to go through this one?_

### What questions do we still need to answer, or what resources do we need?

_Is there research to be done? Are there things we don’t know? Are there documents we need access to? Is there contact info we need? Add those questions as bullet points here._

### How will we complete the epic?

_What are the steps involved in taking this from idea through to reality?_

### How else could we accomplish the same goal?

_Are there other ways to accomplish the goals you listed above? How else could we do the same thing?_

**Comment by octalmage** [comment]
I'd be happy to help with this. I've personally built a bunch of WordPress plugins, and WordPress REST API plugins. So anything I an do to help let me know!

**Comment by octalmage** [comment]
@dbismut I'm not sure if I understand, you built incremental building for the wordpress-source-plugin, or is this unrelated?

**Comment by octalmage** [comment]
Here's a reference plugin to show how to add a query parameter to the core endpoints: 

https://github.com/WP-API/rest-filter/blob/master/plugin.php

We could add a ?since query parameter to be able to grab the posts published "since" a timestamp.

**Comment by dbismut** [comment]
@octalimage you’re right this is unrelated I’ll remove my post for clarity.

**Comment by TylerBarnes** [comment]
Hey guys,
I wasn't aware you had this planned so I actually already built a gatsby plugin that pairs with a wordpress theme / plugins to solve a lot of the gatsby/wordpress integration issues.
I don't have anything public to show yet but I have a release planned in the next couple weeks.

An overview of what my plugin/theme does:
- Simple gatsby previews from the WP admin
- A new endpoint which combines all post types and has built in acf support (this speeds things up a lot because there are way less http requests + wayyy less graphql structures(?) that need to be built)
- A basic template hierarchy with fallback templates
- Connection to the WP edit screen template picker to choose page/post templates from inside WP
- Full Wp menu support, essentially you just have a component `<MenuItems slug="primary-menu>` that uses children as a function to pass the menu items to your markup
- I'm using the WP permalink structure so gatsby-node doesn't need to be touched at all
- Support for using WP forms in gatsby with very little configuration
- Easy archive pages with pagination (setup from the wp page edit screen in a metabox, you select archive, then type in the posts per page, then select which post type its for from a dropdown)
- automatic taxonomy term and archive pages if a template exists in gatsby

I've tested it with sites that have 1000+ pages and it builds as quickly as a markdown site. The only step that is slow is downloading images. 
I think gatsby core needs to add support for an image downloading step that has a progress bar.

The reason I built this integration was to make it super easy for WP webshops to switch to gatsby with no compromises. I essentially built it to use it at work and I've been using it and it's really great!

**Comment by TylerBarnes** [comment]
Almost forgot! This is only mildly related but I actually went a little crazy and redesigned the WP backend while I was at it. Since gatsby doesn't really need the WP toolbar at the top I figured I should give it a once over. As a little fun bonus, user profile pictures are downloaded from unsplash if they dont have anything set. I checked the WP sourcecode and rebuilt the left menu from scratch but architected it so that post types exclusively get added as children of the "collections" menu item and any extra plugins exclusively get added as children of the "development" menu item.

<img width="1440" alt="screen shot 2018-11-22 at 10 31 44 am" src="https://user-images.githubusercontent.com/14190743/48918519-042b5100-ee42-11e8-8757-bc0c679a7c9f.png">
<img width="1440" alt="screen shot 2018-11-22 at 10 34 59 am" src="https://user-images.githubusercontent.com/14190743/48918580-50769100-ee42-11e8-9157-a7129839d9df.png">

<img width="1436" alt="screen shot 2018-11-22 at 10 32 09 am" src="https://user-images.githubusercontent.com/14190743/48918522-05f51480-ee42-11e8-9a50-e51d93a73344.png">

**Comment by pieh** [comment]
@TylerBarnes that is exciting!

> A new endpoint which combines all post types and has built in acf support (this speeds things up a lot because there are way less http requests + wayyy less graphql structures(?) that need to be built)

How is this producing less graphql structures? Did you also built separate gatsby source plugin for it? I'm actually pretty interested how that output looks like and if you used pagination there to chunk output (I'd imagine single route returning 10000 of entries might be a bit slow and maybe cause timeouts or 500 errors on server?)

> The only step that is slow is downloading images.
> I think gatsby core needs to add support for an image downloading step that has a progress bar.

That's also something we want to prioritize soon - see https://github.com/gatsbyjs/gatsby/issues/10049 for ideas - it actually touches on both general slowness as well as visual indication

**Comment by lightstrike** [comment]
@TylerBarnes Exciting stuff! I created a [wp-gatsby](https://github.com/lightstrike/wp-gatsby/) plugin a few months ago I've been working on recently to work with Gatsby's [upcoming Preview feature](https://www.gatsbyjs.org/blog/2018-07-17-announcing-gatsby-preview/). It would be great to compare notes sometime and see how we can combine efforts :smile: 

P.S. Great job with the new WP admin!

**Comment by KyleAMathews** [comment]
Epic work! Excited to see the new code!

**Comment by TylerBarnes** [comment]
> How is this producing less graphql structures? Did you also built separate gatsby source plugin for it? I'm actually pretty interested how that output looks like and if you used pagination there to chunk output (I'd imagine single route returning 10000 of entries might be a bit slow and maybe cause timeouts or 500 errors on server?)

@pieh I don't know super well how you guys are handling all the graphql stuff behind the scenes so that's just a guess. I'm still using `gatsby-source-wordpress` but i only need to include a few routes to get a site with full menu support, unlimited post types, acf support, and images. I set the following in the config:

```javascript
        useACF: false, 
        includedRoutes: [
          '**/wp-api-menus/v2/',
          '**/wp-api-menus/v2/**',
          '**/wp/v1/collections',
          '**/wp/v2/media',
          '**/wp/v2/media/(?P<id>[d]+)',
        ],
```
I converted another site that was still using "includedRoutes" but it had to include 5 more routes + all the acf routes (another 11 routes?) and after converting it to use my plugin it takes 30 - 40 seconds less to build. I figured that must not just be the requests but also that gatsby had to figure out what to do with all of that in graphql but I'm not 100% sure on that.

I've only tested using the single route for all post types on a site with 1300 posts and 1100 images but that was on a VPS so I'm not sure how it holds up on shared hosting. On the VPS that was pretty quick to build. Besides the image downloading step it seemed to be the same speed as a small site. The test site has 900mb of images. Each step takes less than a second except for the image download step which takes 113s. If I then run it again immediately after the first time, this site only takes 30 seconds to build.

I am using it on shared hosting for a smaller site as well but I'll generate a really big site and move it to shared hosting and try it out. I imagine the json for 10,000 posts would still only be around 5mb though so a site on shared hosting could probably just use https://github.com/airesvsg/wp-rest-api-cache to handle that. I'll try it out and if it's an issue it would be easy to add chunking to the endpoint.

The other thing is that my WP theme is preventing any extra media sizes from being generated. Do you think that could be helping as well?

@lightstrike I'm super busy right now working full time + also working on my [other gatsby plugin](https://github.com/TylerBarnes/gatsby-plugin-transition-link) after work but once I finish that and get a beta of this up, I'm totally down to collaborate!

Actually, I can give you an overview of how it works right now. I have a cli tool which generates a separate version of the site which has a preview component wrapped around pages that will feed preview data to pages. The cli tool pushes that up to the actual wp server using an api key instead of having previews on the static host. Then when you click the preview button in wordpress, there is a wp hook which opens the right gatsby route on the wp server and passes it an endpoint. The preview component then hits that endpoint using cookie authentication and "hydrates" the preview data into the gatsby site. It's super fast. Previews are essentially instant, I added a loading screen but it's so quick that I think I actually have to remove it. The one thing I'm working on now is the easiest way to make this work with gatsby image since the preview wont have the image sharp queries and all that. Probably I'll just make a wrapper around gatsby image that passes everything through to gatsby image but if fluid or fixed are missing it will try to pass the image url to an img tag instead.

**Comment by Ontopic** [comment]
Sounds really nice. Can't wait to see some code, even when it's not done yet!

**Comment by lightstrike** [comment]
@TylerBarnes Really interesting stuff, curious to see the data structure of `/collections`. I imagine you're passing the post type back as an attribute so that collections can be filtered to create pages with templates for certain types? (ie. `const pages = collections.filter(n => n.postType === "page"`)

Thanks for the initial rundown. For your preview setup, I'm having a little trouble visualizing. When you say a separate version of the site, do you mean like a separate Gatsby build? So in essence, you have one WP server and two Gatsby builds (live and preview)? Then inside the WP admin, you're setting the view published buttons to go to the live site, and the preview buttons to go to your preview component?

Why doesn't your preview setup work with gatsby-image? For creating a wrapper, feel free to take a look at some work I started doing around [running WP inline images through sharp](https://github.com/gatsbyjs/gatsby/pull/7567/files#diff-fefbe2ae5d780d697ea808847ddd513aR115).

Looking forward to chatting through this more with you!

**Comment by lightstrike** [comment]
@TylerBarnes Thanks for the extra notes. Excited to dig in more, let me know when the alpha is out!

**Comment by TylerBarnes** [comment]
Hey again, so I made a rough version public just now.

You can check it out at https://github.com/TylerBarnes/wordsby
Theres a starter at https://github.com/TylerBarnes/wordsby-starter
The admin theme can be found at https://github.com/TylerBarnes/wordsby-admin

It could use some cleaning up and refining but so far it's made WP/Gatsby dev at work much easier.

As of now my plan is to add a gitlab/github/bitbucket api integration that actually just commits the endpoints & WP media files straight to the site repo to be consumed by a hybrid of `gatsby-source-json` and `gatsby-source-wordpress`. Heavily inspired by netlify CMS of course. I haven't started on that yet though.

@pieh if you want to checkout the endpoint you can see it live [here](http://transitionlink.temperance.online/wp-json/wp/v1/collections).
I tested it on shared hosting and it was fine up to 7k posts with a few categories and 5 - 15 paragraphs of content with no images. If each of those had an img though it wouldn't build. I guess that's just the concurrent download problem though from the issue you linked earlier. 
Is it possible to add a concurrent downloads option to `gatsby-source-wordpress` until the problem is fixed? Seems like it would be an easy interim solution.

**Comment by TylerBarnes** [comment]
Apologies for spamming this issue!

I added gitlab and github support to my admin theme so WordPress commits data and media files directly to the gatsby filesystem via the github and gitlab API's. This means you don't need to redownload all your data every time the site builds and when you're developing. If WP data changes while you're developing all you need to do is git pull to get the new data :).
I copied `gatsby-transformer-json` and migrated the ACF flexible content resolver over into a new plugin `gatsby-plugin-wordsby`.

If you want to try it out follow the install at https://github.com/TylerBarnes/wordsby.
Alternatively you can just install [the starter](https://github.com/TylerBarnes/wordsby-starter) and run `gatsby develop` since some WP data is commited directly to that starter.

To me this feels like a huge improvement even though it's a messy WIP. I'd love to hear people's thoughts!

**Comment by jonniebigodes** [comment]
@TylerBarnes i'll take a look at it today and during the weekend and then provide some feedback. Sounds good?

**Comment by TylerBarnes** [comment]
@jonniebigodes that sounds great, looking forward to it!

**Comment by riddla** [comment]
I hope this one isn’t going stale, as @TylerBarnes does some great stuff :)
