### ISSUE TITLE
[v2] gatsby-plugin-layout: location "delay"

### ISSUE THREAD

**Issue by LeKoArts** [gatsbyjs/gatsby#7637]
## Description

The `location` prop of the layout component while using `gatsby-plugin-layout` seems to have a delay at the first load. Only when navigating the site and revisiting the index page the right component gets displayed **instantly**. On the first load for a short time the location is not available (or something else, I can't figure it out) and therefore the check gets falsy.

This only happens on `build`, not on `dev`.

This bug is breaking my navigation/navigation style as I check for the location.pathname and display different elements!

### Steps to reproduce

Clone the reproduction repo:
https://github.com/LeKoArts/layout-location-bug

Run `gatsby build` and `gatsby serve`.

### Expected result

https://github.com/LeKoArts/layout-location-bug/blob/master/src/layouts/index.js

The index page should only display "THIS IS HOME HOME".

### Actual result

For a split second the text "SECOND SECOND SECOND" gets displayed just before the normal "THIS IS HOME HOME" comes.

**Comment by cpboyd** [comment]
@LeKoArts Possibly related to #7568

**Comment by cpboyd** [comment]
@LeKoArts My bad, #7564 is what I meant to say, since `gatsby-plugin-layout` uses `wrapPageElement`

On a related note, modifying `static-entry.js` will remove the initial "SECOND SECOND SECOND":
```jsx
class RouteHandler extends React.Component {
    render() {
      const props = {
        ...this.props,
        ...dataAndContext,
        pathContext: dataAndContext.pageContext,
      }

      const pageElement = createElement(
        syncRequires.components[page.componentChunkName],
        props
      )

      // const wrappedPage = apiRunner(
      //   `wrapPageElement`,
      //   { element: pageElement, props },
      //   pageElement,
      //   ({ result }) => {
      //     return { element: result, props }
      //   }
      // ).pop()

      return pageElement
    }
  }
```

This isn't really a solution, however, since it just results in the div not being there initially.

Conversely, making a similar change to `page-renderer.js` will result in the "SECOND SECOND SECOND" div appearing briefly and then disappearing.

It seems counter-productive to have the browser re-render everything on production builds.
Part of the whole point to the static site generator is that stuff is rendered right the first time, right?

**Comment by chasemccoy** [comment]
I think #7577 will fix this.

**Comment by pieh** [comment]
fixed with https://github.com/gatsbyjs/gatsby/pull/7577

**Comment by LeKoArts** [comment]
Yep, solved the issue 👍
