### ISSUE TITLE
Cannot read property 'site' of undefined

### ISSUE THREAD

**Issue by mittalyashu** [gatsbyjs/gatsby#7715]
## Description

![2018-08-29_15-23-20](https://user-images.githubusercontent.com/29014463/44780454-9dc6c780-ab9f-11e8-83b8-2f18a35aa39c.gif)

#### Index.js _(page)_

```js
import React from 'react'
import LeftSide from '../components/LeftSide'

const IndexPage = () => (
  <LeftSide/>
)

export default IndexPage
```

#### LeftSide.js _(component)_

```js
import React from 'react'
import { graphql } from 'gatsby'

export default ({ data }) => {
  return (
    <div>
      Title: {data.site.siteMetadata.title}
    </div>
  )
}

export const query = graphql`
  query {
    site {
      siteMetadata {
        title
      }
    }
  }
`
```

### Terminal output

![2018-08-31_01-25-56](https://user-images.githubusercontent.com/29014463/44875819-e2945080-acbc-11e8-8a22-65be3784bf2b.gif)

### Expected result

It doesn't show title `{data.site.siteMetadata.title}`.

### Actual result

It should show title.

**Comment by pieh** [comment]
Can you provide reproduction for it? Is content of your file actually page component? What's the terminal output?

**Comment by mittalyashu** [comment]
> Can you provide reproduction for it? Is content of your file actually page component? What's the terminal output?

https://github.com/gatsbyjs/gatsby/issues/7715#issue-355085989

**Comment by DSchau** [comment]
@mittalyashu pretty sure I know the issue here. There's a helpful console warning that would've led you in the right direction too!

```
Exported queries are only exported for Page components...
```

So what you're running into here is that you're using a page level feature (the graphql query) with a component, when that functionality is reserved for pages.

Introducing... 

## StaticQuery

The new StaticQuery component and functionality is tailor made for this use case. It lets you fetch data at _build_ time for a component where it needs it, rather than passing data down.

The code will look something like

```js
import React from 'react'
import { graphql, StaticQuery } from 'gatsby'

export default () => {
  return (
    <StaticQuery
      query={graphql`
        query {
          site {
            siteMetadata {
              title
            }
          }
        }
      `}
      render={data => (
        <div>
          Title: {data.site.siteMetadata.title}
        </div>
      )}
    />
  );
}
```

Please re-open if you need further assistance, or if I was off-base here! Thanks!!
