### ISSUE TITLE
Starter Showcase: Improve data sourcing from GitHub / screenshot generation

### ISSUE THREAD

**Issue by amberleyromo** [gatsbyjs/gatsby#7730]
Improve current process for sourcing GitHub data for starters.

- [x] source from GitHub directly (no scraping/committing)
- [x] ensure that sans token, front-end isn't broken for DX but fails for build
- [x] modify gatsby-transformer-screenshot to accept other yml files

**Comment by amberleyromo** [comment]
@jlengstorf @kkemple

**Comment by jlengstorf** [comment]
I just verified that we can pull all repos' metadata from the [GitHub GraphQL API](https://developer.github.com/v4/explorer/) in a single query like this:

```gql
query {

  gatsby: repository(owner: "gatsbyjs", name: "gatsby") {
    stargazers {
      totalCount
    }
    updatedAt
  }
  
  gatsbyStarterCasper: repository(owner: "haysclark", name: "gatsby-starter-casper") {
    stargazers {
      totalCount
    }
    updatedAt
  }
  
  verious:repository(owner: "cpinnix", name: "verious-boilerplate") {
    stargazers {
      totalCount
    }
    updatedAt
  }

}
```

However, since we can't dynamically create queries in Gatsby, I think we'd need to do a pre-build step to write this query.

Something like:

1. Grab the .md files or YAML file and extract the `owner` and `name` values from the `repo` field.
2. Write the generated query to a file
3. The starter showcase card would need to load that query in from somewhere — maybe the write in step 2 would update a `StaticQuery`? That feels a bit hacky, but until https://github.com/gatsbyjs/gatsby/issues/6545 is fixed I don't think there's another option that uses `StaticQuery`.

Maybe there's a better way to handle this? Any ideas, @kkemple?

**Comment by jlengstorf** [comment]
Actually, I think there might be a way around this.

The [`gatsby-source-github-api`](https://github.com/ldd/gatsby-source-github-api) config takes a query, and it _looks_ like that query can be a variable.

So we could run the `prebuild` step into a file that's something like this:

```
export const githubStartersQuery = `
query {

  gatsby: repository(owner: "gatsbyjs", name: "gatsby") {
    stargazers {
      totalCount
    }
    updatedAt
  }
  
  gatsbyStarterCasper: repository(owner: "haysclark", name: "gatsby-starter-casper") {
    stargazers {
      totalCount
    }
    updatedAt
  }
  
  verious:repository(owner: "cpinnix", name: "verious-boilerplate") {
    stargazers {
      totalCount
    }
    updatedAt
  }

  # ...
}
`;
```

And then in `gatsby-config.js`, we could just import that:

```
import { githubStartersQuery } from './path/to/githubStartersQuery.js';

module.exports = {
  // ...
  plugins: [
    // ...
    {
      resolve: `gatsby-source-github-api`,
      options: {
        // token: required by the GitHub API
        token: process.env.GITHUB_TOKEN,
        graphQLQuery: githubStartersQuery,
      }
    }
  ]
}
```

I think that could simplify the process a bit, and theoretically we could run that on every build without worrying about rate limiting since it's a single query.

**Comment by kkemple** [comment]
I like it, i wish there was a way to do this via page context and make the query as part of each page generation but I don't think that is possible.

**Comment by jlengstorf** [comment]
@kkemple Yeah, I agree that it'd be nice to do this in the code itself. However, I don't know if that would be much help since we have to generate the overview page with all starters on it anyways, which would rate limit us almost immediately I think.

**Comment by kkemple** [comment]
I just hate pre-build steps but agree that no better option and a pre-build step is worlds better than a scraper, so... 🤷🏻‍♂️
