### ISSUE TITLE
[gatsby-source-contentful] Preview unpublished entries not working

### ISSUE THREAD

**Issue by ciokan** [gatsbyjs/gatsby#7768]
I have a blog that pulls content from contentful. I'm using the preview feature which works in detecting changes...up to a point. 

If I'm editing an existing entry, everything is fine. If I add a new entry in contentful, I can see it in my list of posts but, if I click to navigate to the post page I'm directed to a 404 because there is no route to that post.

My guessing is that gatsby updates the content up to a point but `createPages` is not called. I don't know if this is a bug or not but I find it impossible to preview unpublished entries because there are no routes towards them.

Any suggestions?

**Comment by BayPhillips** [comment]
I haven't run into this myself. I use the `preview.contentful.com` host and access token for my local development and am able to see unpublished entries. This is generally how I write out new blog posts while being able to preview them (haven't made it into the [Gatsby preview alpha](https://www.gatsbyjs.org/blog/2018-07-17-announcing-gatsby-preview/) yet...  😉). I do have to rerun `gatsby develop` in order to pull down the changes.

When you're running `gatsby develop`, do you see the updates come down the pipe in the source plugin's output in the terminal?

**Comment by wardpeet** [comment]
Gatsby doesn't rebuild when a new blog post is made so you'll have to retrigger the build by running `gatsby develop` as @BayPhillips suggested.

I'm closing this issue as I believe it's resolved, thanks for answering @BayPhillips!
If it's not resolved feel free to re-open.
