### ISSUE TITLE
Need clarification around PrivateRouter/auth required pages in Gatsby

### ISSUE THREAD

**Issue by akoolenbourke** [gatsbyjs/gatsby#7818]
## Summary

So I've seen the demos floating around such as this one that allow you to mix both static and dynamic pages (https://github.com/gatsbyjs/gatsby/tree/master/examples/simple-auth)

What I would like is some clarification as to why this is the suggested method? Couldn't I just have a component that I put in all pages that need gating that checks 'isLoggedIn' and redirects, possibly in componentDidMount if the pages were wrapped in a component? What, if any does implementing onCreatePage and having routing based gating give me? Is it purely an organisational thing. That is, you have your PrivateRoute(s) and the gating handled in a single place?

Note, I'm asking because we need to implement this functionality very soon and I want to take the best approach.

Also, is there any better documentation on what all the parameters to the node/ssr etc .js files are and how to use them to their fullest? I have seen the docs that cover the basics but they don't really explain all the parameters to all the callback functions.

Thanks

**Comment by kakadiadarpan** [comment]
Hey @akoolenbourke, `PrivateRoute` component implemented in [simple-auth](https://github.com/gatsbyjs/gatsby/tree/master/examples/simple-auth) is just an example showing Gatsby's ability to support dynamic content in client-only routes. Also, when you have a `PrivateRoute` component you can easliy determine which are the private routes in your application just by taking a look at one file, instead of checking each and every component. You are always free to choose any other implementation that suits your needs.

**Comment by akoolenbourke** [comment]
Thanks. I thought it was such and I see the benefit from an organisational point, I was just curious as to whether it offered some other benefit with dynamic pages.

I'm quite new to web dev and especially React and Gatsby so I'm still a little confused as to what really is the practical difference between client and server in this example. For instance, I could take that auth-example with PrivateRoute components which render content for my private routes. I could also just write regular pages and components and get the exact same end result couldn't I? Both would still require me to request dynamic data from the server and so the only difference could be at what point the "pages" are requested. Am I understanding this right or is there more to it?

**Comment by kakadiadarpan** [comment]
When you are using Gatsby, you don't need to worry about writing different code for server and client. 

All this code goes in your client build along with the server. When your application is loads a specific route and if it's a `PrivateRoute`, then the client will automatically redirect it to the login page. It doesn't need to go to the server to check if a specific route is accessible for the user. When you use `PrivateRoute` you only allow authenticated users to view some of the pages in your application, so in case if the user is not logged in your page wouldn't even load and there would be no API call made.

You can read up more about client-side vs server-side routing [here](https://medium.com/@wilbo/server-side-vs-client-side-routing-71d710e9227f).

**Comment by akoolenbourke** [comment]
Thanks. I think what you said is what I was thinking - that it can avoid another server request - however it seems that PrivateRoute won't really save anything much. Here is why I'm thinking this.

`PrivateRoute` when used as in the examples will resolve to some component, say `<UserProfile>`. Now, for that to be displayed it needs to be retrieved from the server at "some point". If it was a regular server side route in Gatsby, from say a `<Link>`, Gatsby would preload that page, or load it if it needed to at some point. If this is a client side route, that `<UserProfile>` component still needs to get from the server to the client. So in the end it seems like there is little benefit other than maybe organisational, by having private routes handled in one  place. 

Thanks for your time and sorry for all the questions; I'm just trying to get a mental model of this all so I can make the best decisions for our site.

**Comment by kakadiadarpan** [comment]
Generally, authentication in web apps is implemented in such a way that it is globally available. It can be done using cookies/local-storage/session-storage. So when your application loads initially, you also get the authentication information. You won't need to make another request to check if the user is authenticated. So whenever an unauthenticated user tries to access `PrivateRoute`, it will directly redirect the user to `Login` page.

Let us know if you need more clarification, otherwise feel free to close the issue. 👍
