### ISSUE TITLE
Gatsby V2 website error

### ISSUE THREAD

**Issue by gc** [gatsbyjs/gatsby#7821]
## Description

I received lots of errors in the console when loading the V2 website, and the page remained completely blank and didn't load anything.
![chrome_2018-09-03_20-07-19](https://user-images.githubusercontent.com/30398469/44981360-ad864780-afb5-11e8-8bc4-430d58c07edd.png)

### Steps to reproduce

I'm not sure how to reproduce it. I just visited https://next.gatsbyjs.org/

### Expected result

Should load normally.

### Actual result

Didn't load at all, completely blank page, had to refresh the page.

### Environment

Chrome 68 on Windows 7.

**Comment by KyleAMathews** [comment]
Hey! Thanks for reporting this! We had some bugs with gatsby-plugin-offline which @davidbailey00 has been busily fixing recently e.g. https://github.com/gatsbyjs/gatsby/pull/7355

I haven't seen any more errors like this since #7355 landed so I believe future loads of next.gatsbyjs.org will be smooth for you.
