### ISSUE TITLE
[v2] Builds are inconsistent

### ISSUE THREAD

**Issue by oltodo** [gatsbyjs/gatsby#7836]
I realized that builds in Gatsby v2 are inconsistent. It means two builds based on the same code base couldn't provide the same the result (in the `public` folder). That can cause troubles when building your Gatsby project on multiple load-balanced servers (for instance).

To reproduce the case:

- `$ gatsby new my-blazing-fast-site https://github.com/gatsbyjs/gatsby-starter-default\#v2`
- `$ cd my-blazing-fast-site`
- `$ yarn build`
- `$ mv public previous`
- `$ rm -rf .cache`
- `$ yarn build`
- `$ diff -rq previous public`

Unless you're lucky, you should have a diff like this:

![image](https://user-images.githubusercontent.com/483842/44999241-035dee00-afbc-11e8-919b-c4c966a1e1d0.png)

Which is caused by a random sorting of pages' dataPaths:

![image](https://user-images.githubusercontent.com/483842/44999274-41f3a880-afbc-11e8-8a19-aae53e64600b.png)

**Comment by kakadiadarpan** [comment]
I'm able to reproduce this. Just create a new Gatsby(v2) project, and follow the steps provided in the description. This doesn't happen in v1.

**Comment by kakadiadarpan** [comment]
Hi @oltodo, thanks for sharing the environment info. We'll look into this.

**Comment by oltodo** [comment]
Thanks @kakadiadarpan!

**Comment by pieh** [comment]
Hey, this is happening because we run graphql queries in parallel and order of inserting entries to `dataPaths` is not guaranteed. (`dataPaths` are partial paths to .json files that contain results of graphql queries - files are located in `public/static/d/${dataPath}.json`).

Here's where we are writing file that has random order of keys: https://github.com/gatsbyjs/gatsby/blob/faf58c8a05453763301f5de631e5efc95abd788e/packages/gatsby/src/internal-plugins/query-runner/pages-writer.js#L120-L126

We could process `jsonDataPaths` before writing it to ensure keys are sorted and therefore consistent between builds (f.e. using something like `_(jsonDataPaths).toPairs().sortBy(0).fromPairs()` - not tested). Would you be up for checking this out and creating PR for it @oltodo?

**Comment by pieh** [comment]
Right, yeah I think this would be good idea to do this for `pagesData` as well (I guess sort by path there).

**Comment by oltodo** [comment]
Fixed through https://github.com/gatsbyjs/gatsby/pull/7878
