### ISSUE TITLE
Gatsby data layer cannot pull in object which has a `length` field.

### ISSUE THREAD

**Issue by Jaikant** [gatsbyjs/gatsby#7859]
The gatsby data layer while making the schema is using a `_.each` to iterate over an object. If the object has a `length` field, it [fails](https://lodash.com/docs/#forEach). 

https://github.com/gatsbyjs/gatsby/blob/faf58c8a05453763301f5de631e5efc95abd788e/packages/gatsby/src/schema/infer-graphql-type.js#L336

Can this be replaced with a [_.forIn](https://lodash.com/docs/4.17.10#forIn)

**Background**: I was migrating an existing web app to gatsby. The data for the app is in a mongo database and one of the collections has a `length` field in it.

**Comment by kakadiadarpan** [comment]
Hi @Jaikant, would you like to submit a PR for fixing this?

**Comment by Jaikant** [comment]
@kakadiadarpan I am not sure if the `_.forIn` is the right solution to the problem. @jlengstorf @KyleAMathews please let me know, don't want to cause other things to break!

**Comment by kakadiadarpan** [comment]
In my opinion, it should not break things as we are iterating over an object there. If you check before line 336, it declares the type of `resolvedExample` as an `Object`.

https://github.com/gatsbyjs/gatsby/blob/faf58c8a05453763301f5de631e5efc95abd788e/packages/gatsby/src/schema/infer-graphql-type.js#L330

Also, as per the documentation of [forIn](https://lodash.com/docs/4.17.10#forIn), it would be the best way of iterating over an object's properties while [forEach](https://lodash.com/docs/4.17.10#forEach) should ideally be used to iterate over a collection (and that's why `length` key is ignored in `forEach` as it specifies the length of the collection).

@KyleAMathews @m-allanson @pieh what do you suggest?

**Comment by pieh** [comment]
Replacing `_.each` with `_.forIn` sounds reasonable here. TIL that `_.forEach` has this edge case with `length` property (which does make sense I guess). @Jaikant would you be up for creating PR for it? Other place similiar change should also be done is https://github.com/gatsbyjs/gatsby/blob/faf58c8a05453763301f5de631e5efc95abd788e/packages/gatsby/src/schema/infer-graphql-input-fields.js#L255 and updating tests to cover `length` would be great too!

**Comment by Jaikant** [comment]
I did a quick test with the `forIn`.
The error I was seeing earlier is resolved, but it seems to mess with the schema. which throws up a new error. Not sure why.

**Comment by Jaikant** [comment]
oops, this seemed to have slipped from my list. I will look at this over the weekend.
