### ISSUE TITLE
Upload file in to root/parent directory

### ISSUE THREAD

**Issue by futuregerald** [gatsbyjs/gatsby#799]
Hey guys, I was wondering how to upload a file with no extension as part of the build to go into the root directory? I'm new to loaders so I'm not quite sure how to write one, or if I need one for this.

**Comment by futuregerald** [comment]
I found this copy plugin:

https://github.com/kevlened/copy-webpack-plugin

I'm having trouble getting it to work with gatsby-node.js. I just have a file that I need to be in the public directory once the build is done. Anyone have a similar issue?

**Comment by KyleAMathews** [comment]
Normally you'd just import the file from one of your pages but hmmm... the lack of extension could cause a problem cause then webpack would assume you're trying to import a JS file (as it'll automatically add the js extension when requiring those files).

Perhaps the easiest would be to just copy it in like you're doing but instead of adding the webpack plugin, do it in the `postBuild` step https://github.com/gatsbyjs/gatsby#perform-additional-post-build-step
