### ISSUE TITLE
[gatsby-plugin-offline] Location of Workbox runtime libraries

### ISSUE THREAD

**Issue by wKovacs64** [gatsbyjs/gatsby#8037]
## Summary

Migrating from sw-precache to Workbox (#7605) broke the service worker functionality on my site because [the default behavior](https://developers.google.com/web/tools/workbox/modules/workbox-build#full_generatesw_config) of the `workbox-build` package is to download its runtime libraries from the Google Cloud Storage CDN, which the `script-src` directive of my CSP header does not allow. This was easily solved by supplying the `importWorkboxFrom: 'local'` config option, but I definitely didn't expect `gatsby-plugin-offline` to be reaching out to rogue URLs 😅. Is it unsurprising for a plugin to depend on external sources? If not, should we consider making `importWorkboxFrom: 'local'` the default?

cc @davidbailey00 

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by kakadiadarpan** [comment]
Hi @wKovacs64, it's always better to serve files from a CDN rather than your own server. It is very effective in speeding the delivery of the content. That is why this is the default behavior currently. But, if anyone has restrictions with fetching from CDN, they can always update the config to generate local copies (just like you did).

@davidbailey00 can obviously provide more inputs on this

**Comment by KyleAMathews** [comment]
Hmm in gatsby's case we generally already are serving sites from a CDN so loading part of a lib from another CDN will always be slower.

**Comment by davidbailey00** [comment]
Yeah I agree with @kyleamathews - we might as well make "local" the default behaviour given most sites are served from a CDN, and that this matches the previous behaviour. I'll submit a PR later.

**Comment by davidbailey00** [comment]
Just opened a PR to change the default behaviour
