### ISSUE TITLE
working with dynamic links

### ISSUE THREAD

**Issue by designforhuman** [gatsbyjs/gatsby#8161]
I'm using 'react-device-detect' in index.js in order to send users to different websites based on their device. (ie. iOS to Apple Podcast, Android to another podcast website, and Desktop for another one.)
It runs fine on development mode, but it creates static html pages with static links when I build it. Is there a way that I can make the links dynamic in the final build as in dev mode?
I'm using v2.

**Comment by kakadiadarpan** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub issues, we have to clean some of the old issues as many of them have already been resolved with the latest updates.

Please make sure to update to the latest Gatsby version and check if that solves the issue. Let us know if that works for you by adding a comment 👍

**Comment by kakadiadarpan** [comment]
This issue is being closed because there hasn't been any activity for at least 30 days. Feel free to [open a new one](https://github.com/gatsbyjs/gatsby/issues/new/choose) if you still experience this problem 👍
