### ISSUE TITLE
onCreateNode creates no nodes when cache exists

### ISSUE THREAD

**Issue by fabe** [gatsbyjs/gatsby#8216]
When creating/extending nodes (e.g. nodes derived from markdown files) with the `onCreateNode` API, I am only able to query the created nodes when there is no cache (after `rm -rf .cache`). Could be a usage error on my part, but I can't seem to figure out what's wrong here.

### Steps to reproduce

Example repo: https://github.com/fabe/test-gatsby-oncreatenode

1. Run `yarn develop` once (without cache), query works
2. Exit and run `yarn develop` again (now with cache), the query fails
3. Delete cache (`rm -rf .cache`) and run `yarn develop` again, query works

###### gatsby-node.js

```js
const crypto = require('crypto');

exports.onCreateNode = async ({ node, actions, loadNodeContent, reporter }) => {
  const { createNode } = actions;

  if (
    node.internal.mediaType !== `text/markdown` &&
    node.internal.mediaType !== `text/x-markdown`
  ) {
    return;
  }

  const content = await loadNodeContent(node);

  // Modify content...

  const digest = crypto
    .createHash(`md5`)
    .update(content)
    .digest(`hex`);

  createNode({
    id: `ModifiedMarkdown__${node.id + 1}`,
    parent: `__SOURCE__`,
    children: [],
    internal: {
      type: `ModifiedMarkdown`,
      contentDigest: digest,
    },
    content,
  });
};

```

This also happens when refactoring `onCreateNode` to return Promises.

### Expected result

Pages can use the creates nodes inside their queries.

### Actual result

Queries fail with `Cannot query field "allWhatever" on type "Query"`.

### Environment

```bash
System:
  OS: macOS High Sierra 10.13.5
  CPU: x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  Shell: 5.3 - /bin/zsh
Binaries:
  Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
  Yarn: 1.7.0 - /usr/local/bin/yarn
  npm: 5.6.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
Browsers:
  Chrome: 69.0.3497.92
  Firefox: 61.0
  Safari: 11.1.1
npmPackages:
  gatsby: next => 2.0.0-rc.25 
  gatsby-source-filesystem: ^2.0.1-rc.6 => 2.0.1-rc.6 
```

**Comment by pieh** [comment]
If nodes are already in cache and they didn't change since last run (contentDigest didn't change) Gatsby will just touch them and no re-create them (which would be the case if markdown files weren't changed). As they are just touched, `onCreateNode` isn't called in that case. Installing new plugins or making changes to `gatsby-node.js` should automatically clear cache, so nodes should actually be created in those cases and as a result `onCreateNode` should be called.

**Comment by fabe** [comment]
For some reason, setting a valid `parent` id instead of `null` or `__SOURCE__` gets it to work as expected. Although the docs state that `null` should be fine. Anyways, closing this for now, thank you!

**Comment by camden** [comment]
@pieh Can we reopen this issue? I'm experiencing the same issue, and @fabe's "fix" doesn't apply to my situation.

**Comment by pieh** [comment]
Can you elaborate @camden? It is by design that `onCreateNode` isn't called if node didn't change (as what's already cached should have all children node already created in previous run).

**Comment by camden** [comment]
Setting the parent id fixed this for me!

**Comment by mxxk** [comment]
How does one express that a newly created node depends on more than one node? "Multiple parents" isn't a thing, so should this mechanism perhaps be extended to support this use case?

Imagine keeping track of all tags on each post, and creating exactly _one_ node per tag (i.e. `PostTag`). In this case, which node should be the parent? From a caching perspective, a change to the tags of _any_ post has the potential to delete or add new `PostTag` nodes. This is why in https://github.com/gatsbyjs/gatsby/issues/4614#issuecomment-500628839 I used `parent: null`.

However, because `PostTag` nodes are created in `onCreateNode`, they are missing in subsequent builds of the site like this issue explains.

---

The only way I can think of to work around this is fairly complicated... In `sourceNodes`, call `getNodesByType('MarkdownRemark')` to detect whether a site is built from scratch or from cache. Only cache builds will yield a non-empty array, because `sourceNodes` fires before `MarkdownRemark` nodes are transformed into existence. For every such `MarkdownRemark` node, examine its tags and mark the corresponding `PostTag` node as non-stale with `touchNode`.
