### ISSUE TITLE
[gatsby-image] should accept aria attributes

### ISSUE THREAD

**Issue by stefanprobst** [gatsbyjs/gatsby#8256]
Currently, `gatsby-image` does not pass on aria attributes to `<img>`. We should at least allow setting `role=none`, since `using-gatsby-image` shows how to set a background image.

**Comment by kakadiadarpan** [comment]
@stefanprobst we should definitely do this. Would you like to work on this and raise a PR?

**Comment by mikelax** [comment]
[gatsby-image](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-image/src/index.js#L80) is already setting `alt=""` if no `alt` property is specified, so that is a good first step. 

I think a simple enhancement would be to also add `role="presentation"` **only if** no property value was specified for `alt`

>Three common uses of role presentation are:
>  1. Hiding a decorative image; it is equivalent to giving the image null alt text.

From [Section 7.1](https://www.w3.org/TR/wai-aria-practices-1.1/)

Based on the quote above I am not sure if there is any action item needed, but I don't think there is any harm in adding the above logic. The parameter table for the gatsby-image plugin should be updated to note this change if made.

**Comment by DSchau** [comment]
@mikelax love this idea! If you're interested in PRing this later, we'd love to take a look, otherwise I'll try and get to that this afternoon. All for improving Gatsby's accessibility defaults!

**Comment by LeKoArts** [comment]
I think setting `role=presentation` with an empty alt tag is not necessary. Screen readers automatically assume that images with an empty alt tag are background images as the quote from above (section 7.1) states.

**Comment by stefanprobst** [comment]
If screenreaders indeed already do this I am totally fine with closing this issue.

**Comment by 1-800-jono** [comment]
Screen readers don't skip over images with just an empty alt. While testing on MacOs with `VoiceOver`, I discovered that instead of skipping the images it was still reading out load the word "image" (Which seems completely unnecessary because it just adds noise and extra steps to reach content) . Experimented a bit and was able to skip decoractive images with the screen reader only when using either `aria-hidden` or `role="presentation"`.
