### ISSUE TITLE
Does gatsby-plugin-emotion accept an "env" config?

### ISSUE THREAD

**Issue by GabrielDuarteM** [gatsbyjs/gatsby#8298]
## Summary

Does gatsby-plugin-emotion accept an "env" config, like [babel-plugin-emotion's docs](https://github.com/emotion-js/emotion/tree/master/packages/babel-plugin-emotion#usage) uses on the recommended setup?

## Relevant information

It's nice to have the ability to customize the emotion output depending on the build type, for example, to display the component labels on the class on dev, but omit them on prod for smaller builds

### File contents (if changed)
tried the following, but it doesn't seems to work
`gatsby-config.js`: 
```js
    {
      resolve: `gatsby-plugin-emotion`,
      options: {
        "env": {
		    "production": {
		      "plugins": [["emotion", { "hoist": true }]]
		    },
		    "development": {
		      "plugins": [["emotion", { "sourceMap": true, "autoLabel": true }]]
		    }
		  }
      },
    }
```
but this yields the following error: 
```bash
Error: Type production_2 must define one or more fields.
  Type development_2 must define one or more fields.
```
`package.json`: N/A 
```json
"devDependencies": {
  "gatsby-plugin-emotion": "^2.0.5",
},
"dependencies": {
  "emotion": "^9.2.9",
  "emotion-server": "^9.2.9"
},
```
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by DSchau** [comment]
@GabrielDuarteM we kinda handle that for you!

[Here's the relevant code](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-emotion/src/gatsby-node.js)

We disable `sourceMap`, `autoLabel` in production, and enable `hoist`. This is effectively the same as what you're trying to do, so you don't have to do it that way!

That said, to answer your question, no, we don't support the `env` mechanism you were attempting to use! That's because we directly pass all pluginOptions to the babel plugin itself. Therefore, all valid options `labelFormat`, `importedNames`, etc. are available for your usage.

Thanks for the question!
