### ISSUE TITLE
Certain resource files are blocked by adblockers leaving the page non-interactive

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#8307]
https://www.gatsbyjs.org/packages/gatsby-plugin-google-analytics/

Tried it in regular and incognito windows.

/cc @davidbailey00

**Comment by davidbailey00** [comment]
This is caused by adblockers, e.g. uBlock Origin. To workaround this, we should move lines 15 to 30 in load-directly-or-404.js into their own function, and export this separately (in addition to calling it from the same place in the default export), then call this function at line 102 of ensure-resources.js.

I'll be happy to review a PR which fixes this, or if it's not done by next week then I'll start work on it myself!

**Comment by davidbailey00** [comment]
Having said that, a workaround like the one described above could mean that the page isn't interactive or some parts fail to load - not entirely sure of the consequences.

**Comment by davidbailey00** [comment]
#8510 should fix the flickering issue, but the page will still be non-interactive when using an adblocker and show the following message in the console:

    Found no-cache=1 while attempting to load a page directly; this is likely due to a bug in Gatsby, or a misconfiguration in your project.

...which was added as a check to prevent this kind of infinite loop which should be impossible.

So the problem is that we need to prevent adblockers from blocking "https://www.gatsbyjs.org/static/d/41/path---packages-gatsby-plugin-google-analytics-aac-98e-qnUF1p28LlafU5nMmRyf44Hgk.json".

Since the page is rendered server-side, we can afford to keep ignoring this error - the only reasonable way we could fix would be to rename the file to something else which isn't blocked by most adblockers. Unfortunately this means we don't have any interactivity, but we can't really do anything about that (apart from maybe links if we use the link-catcher plugin).

**Comment by KyleAMathews** [comment]
Thinking we could maintain the same list of keywords and just remove them from file names and replace them with gibberish? Or hashes I guess of the "bad" words?

**Comment by pieh** [comment]
We can control hashes for query results pretty easily using above method, not sure about hashes for js bundles/chunks produced by webpack?
