### ISSUE TITLE
Gatsby Docs images not loaded in Firefox browser

### ISSUE THREAD

**Issue by aschrijver** [gatsbyjs/gatsby#8388]
## Description

Both on Ubuntu 16.04 laptop and Android mobile in the Firefox browser the images of the Docs page at https://next.gatsbyjs.org/docs/graphql-reference/ are not loading. The image frames stay empty with a 'Loading...' text.

### Steps to reproduce

Just navigate to the https://next.gatsbyjs.org/docs/graphql-reference/ page with a Firefox browser.
On Ubuntu I use `v61.01` and on mobile` v62.01`

### Expected result

The images should load, just like they do when viewing with Chrome.

### Actual result

The image frames stayed empty with a 'Loading...' text.

The developer toolbar shows 14 error messages (See below. 5 msg are of the first kind, and the other 9 for the second error shown. There are also 9 images on the page)

![gatsby-operation-is-insecure-error](https://user-images.githubusercontent.com/5111931/45846061-0d574f00-bd27-11e8-879f-09958e1e2e60.png)

### Environment

Firefox v61.x and later

**Comment by oorestisime** [comment]
I get no error on Firefox 62 (desktop version). Maybe an addon you have installed is causing this?

**Comment by stefanprobst** [comment]
Allowing third-party cookies seems to make it work.

**Comment by aschrijver** [comment]
I personally use Privacy Badger (v2018.9.20), but the result is the same if I disable it.

**Comment by jskksj** [comment]
Just FYI, I had to enable 'All cookies are allowed' with the Brave browser to get the images to load on the **GraphQL Reference** page.  [https://www.gatsbyjs.org/docs/graphql-reference/](url)

**Comment by m-allanson** [comment]
Note that this page was recently updated to use codesandbox.io instead of the old gatsbygraphql.sloppy.zone url for the iframes. 

If you're blocking _all_ third-party cookies in Firefox, I don't think there's a lot the Gatsby site can do to make the iframes load. (Note that the Firefox settings page says blocking all third party cookies  _may cause websites to break_). 

There is a direct link to open the iframe url as a dedicated page, but it's tucked away at the end of the article. https://711808k40x.sse.codesandbox.io/___graphql

Maybe a note could be added near the top of the article, describing how to view the iframes directly if the content doesn't load for you?
