### ISSUE TITLE
Staticquery  bundle size increase too much

### ISSUE THREAD

**Issue by simonjoom** [gatsbyjs/gatsby#8403]
## Description

gatsbyjs v2  (stable)
A static query for allfiles by example produce output in bundle and when we use childImageSharp the data all of image is too big

Is it normal? Is babel-plugin-remove-graphql-queries supposed to remove it normally? 
To look the situation you can compile:
https://github.com/Vagr9K/gatsby-material-starter

and check public/component---src-templates-post-jsx-***-
inside the query is till there

**Comment by pieh** [comment]
https://github.com/Vagr9K/gatsby-material-starter/blob/eaabf33a16da33e487a03ccd5c20a21c8a60800d/src/components/PostCover/index.jsx this does pull all files so result of this query will need to be loaded somehow anyway - static queries are attached to js bundles because gatsby has no control over how people use this and this was only way to do that - you can lazy load PostCover component (using dynamic import) to alleviate some of it

**Comment by simonjoom** [comment]
Thanks a lot for explanation , it's what is thought about after a while ))
yes i thought to use dynamic import . as well take off base64 who take too much space (using a file is better)
