### ISSUE TITLE
Define a process for labeling and updating issues to make community discovery and contribution easier

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/gatsby#8421]
One of the hardest things about getting into OSS is finding issues that don't require tons of context to start working on them.

We've found that any issue that gets written out with all context and goals clearly defined gets picked up quickly by the community. We need to design workflows that will help more issues reach this stage.

This helps us in several ways:

1. It makes contributing much more approachable, especially for first-time contributors
2. It gives us a clear list of things that we could use help with when people ask what to work on
3. It relieves the load on core maintainers and allows them to focus on the really complex stuff

To make this happen, we need a workflow to determine:

1. How we should be identifying which issues should be written up with context and goals
2. Who owns writing up the issues
3. How those issues will be labeled for the community (e.g. level of effort, level of expertise required)
4. How to measure the impact (e.g. do the core maintainers feel like their workload is lighter? are issues being resolved faster?)
	- Is it possible to make these objective measures?

@pieh @m-allanson @KyleAMathews @DSchau @kakadiadarpan this would most likely happen during OSS backlog grooming and/or first-touch triage, so it will probably require your input and buy-in to have any hope of working.

@marisamorby will own putting the process and docs together once we've defined how this can work.

**Comment by DSchau** [comment]
I didn't get a chance to mention it in the meeting, but I think one of the most helpful things we can do to increase community engagement is simply sizing of issues, and adding corresponding labels (e.g. t-shirt sizing=small, medium, large, etc.). An issue that requires a great deal of context may necessarily be "large" not because it's necessarily challenging, but because the ramp up curve to get to that level is more challenging.

That's something that any of us on the OSS team are able to simply do as we look at an issue, and it doesn't involve a lot of additional process while still being (I think!) valuable to contributors or potential contributors. In much the same way that "Good first issue" is valuable to get community engagement, so too would S/M/L labels.

A nice benefit is that seeing a label also gives an indication that it's been reviewed by one of us with the necessary knowledge/context to size it in the first place.

Thoughts @pieh @m-allanson @KyleAMathews ?

**Comment by marisamorby** [comment]
I 100% agree with this. I think the additional question here is who can correctly size issues and where should that live in the issue review process?

**Comment by jlengstorf** [comment]
We're using #8719 as an experiment to see how much of an impact this kind of issue writing has on community engagement with issues. (Early signs point to this being a _really_ good idea.)
