### ISSUE TITLE
[gatsby-plugin-preact] Uncaught TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by rwieruch** [gatsbyjs/gatsby#8545]
## Description

I wanted to use gatsby-plugin-preact but I ran into an issue. So I created a minimal issue where it happens too.

### Steps to reproduce

Take the [gatsby-starter-blog](https://github.com/gatsbyjs/gatsby-starter-blog) (or I guess any other project), do the setup, and install [gatsby-plugin-react](https://www.gatsbyjs.org/packages/gatsby-plugin-preact/). [Here is a minimal application for this problem](https://github.com/rwieruch/gatsby-starter-blog-with-preact).

### Expected result

The application should work.

### Actual result

I get the following stack trace:

```
Users/mydspr/Developer/Repos/gatsby-blog/node_modules/@reach/router/es/index.js:61 Uncaught TypeError: Object(...) is not a function
    at createNamedContext (Users/mydspr/Developer/Repos/gatsby-blog/node_modules/@reach/router/es/index.js:61)
    at eval (Users/mydspr/Developer/Repos/gatsby-blog/node_modules/@reach/router/es/index.js:69)
    at Module../node_modules/@reach/router/es/index.js (commons.js:1176)
    at __webpack_require__ (commons.js:725)
    at fn (commons.js:102)
    at eval (Users/mydspr/Developer/Repos/gatsby-blog/node_modules/gatsby-link/index.js:23)
    at Object../node_modules/gatsby-link/index.js (commons.js:2608)
    at __webpack_require__ (commons.js:725)
    at fn (commons.js:102)
    at Module.eval (Users/mydspr/Developer/Repos/gatsby-blog/.cache/gatsby-browser-entry.js:8)
```

**Comment by kakadiadarpan** [comment]
@rwieruch Thanks for providing us with the reproduction repo. I can confirm that `gatsby-plugin-preact` is breaking with Gatsby v2.

Gatsby uses `@reach/router` for routing, and it seems like it isn't compatible with `preact`. Check this [codesandbox](https://codesandbox.io/s/9jpv93q9nr) where only preact and `@reach/router` are being used.

reach/router#9

**Comment by rwieruch** [comment]
@kakadiadarpan thanks for your response and providing a solution. Would you say this is the solution to go for or will the gatsby-preact-plugin get an update eventually and this is only a workaround?

**Comment by kakadiadarpan** [comment]
@rwieruch I'm afraid it's not a solution. If you uncomment the line number 10 then you'll see the build failing

**Comment by ArthurYidi** [comment]
Partially fixed with https://github.com/developit/preact/pull/1138 and https://github.com/developit/preact/pull/963.

Also requires aliasing `hydrate = render`.

However, due to type changes it introduced a bug that requires fixing:
https://github.com/developit/preact/issues/1232

After all of those fixes I was able to get local version working, hopefully everything lands in preact 8.4.

It would be helpful to document that Preact support for React 16 and Reach/Router (Gatsby 2) is broken until new updates land.

**Comment by pieh** [comment]
@ArthurYidi Would you be interested in adding warning to `gatsby-plugin-react` readme - it can even point to this issue to provide more context

**Comment by simonjoom** [comment]
For me i use reach router and inferno and i have no issue 
https://github.com/simonjoom/gatsby-starter-inferno-master

**Comment by rrcobb** [comment]
Updating the codesandbox @kakadiadarpan to preact 8.4.2 and preact-compat 3.18.4 makes the @reach/router issues go away - (here's a forked [sandbox](https://codesandbox.io/s/6w3y24w32z))

**Comment by rrcobb** [comment]
Looks like the other issues are dependencies on react's context api (still mostly from @reach/router, since that uses a ton of the new react 16 features). 

https://github.com/developit/preact/pull/963 is the preact core issue tracking adding support, and 
 https://github.com/developit/preact-compat/issues/475 is the issue to follow on the preact-compat side.

As mentioned in [this comment](https://github.com/developit/preact/pull/963#issuecomment-408635151) there's still a big hack you have to do to make preact-compat export a viable `createContext` function.

In [this commit](https://github.com/gatsbyjs/gatsby/commit/e8a99d97a67707607d61509970efdc56c924f121) I tried to do the set of updates needed to load a working version of the plugin, but things are still broken with those, in the following ways:

`npm run dev` yields no errors, but somehow yields a page with the following html:

```
<div id="___gatsby"><undefined></undefined></div>
```

🤔 🤔 🤔 

`npm run build` also doesn't fail, and serving it promisingly shows the starter's homepage! However, there are errors in the console, and trying to visit any of the other pages fails. 

```
Uncaught TypeError: o is not a function
    at production-app.js:127
```

Digging into the source around that point, it looks like something with the renderer:

```
const renderer = apiRunner(
        `replaceHydrateFunction`,
        undefined,
        ReactDOM.hydrate
      )[0]

      domReady(() => {
        renderer(
          <NewRoot />,
          typeof window !== `undefined`
            ? document.getElementById(`___gatsby`)
            : void 0,
          () => {
            apiRunner(`onInitialClientRender`)
          }
        )
      })
```

I have not uncovered what this means or what's wrong, but maybe this is what @ArthurYidi meant by 

> Also requires aliasing hydrate = render.

I'll probably keep digging some. 

Adding documentation of how this is broken to the plugin seems like a pretty easy step - I can whip up a quick summary and PR tomorrow with a pointer to this issue.
