### ISSUE TITLE
Can't we "name-export" graphQL fragments from components?

### ISSUE THREAD

**Issue by dotlouis** [gatsbyjs/gatsby#8792]
## Summary

Gatsby throws a `Error: Invariant Violation: GraphQLCompilerContext: Unknown document 'HeaderFragment'.` when exporting a named graphQL Fragment from a Component.

## Relevant information

This is more of a question of how it works rather than a bug I think. That's why I labeled it as a question.

When using GraphQL fragments. I do as the [docs](https://www.gatsbyjs.org/docs/querying-with-graphql/#fragments) say to export the fragment and it works.
```js
// HeaderComponent
export const HeaderFragment = graphql`
  fragment HeaderFragment on ContentfulHomePage {
    title
  }
`
```

this is a named export. BUT when using the alternative syntax:
```js
// HeaderComponent
const HeaderFragment = graphql`
  fragment HeaderFragment on ContentfulHomePage {
    title
  }
`
export {HeaderFragment};
```
it throws `Error: Invariant Violation: GraphQLCompilerContext: Unknown document 'HeaderFragment'.`

Am I wrong thinking this should be the same thing ? both are named-export to me.

Also there must be something I don't quite get because I don't understand how fragments are picked-up if we don't import them in the parent component that uses it? Just by importing the default export, it magically knows what named-export is the fragment to use ?

Thanks for enlighting me, and for a great product that is gatsby 😃 

### File contents (if changed)

`gatsby-config.js`:
```js
module.exports = {
  siteMetadata: {
    siteUrl: '...',
    title: `...`,
  },
  plugins: [
    'gatsby-plugin-react-helmet',
    'gatsby-plugin-emotion',
    {
      resolve: 'gatsby-plugin-mailchimp',
      options: {...},
    },
    {
      resolve: `gatsby-plugin-manifest`,
      options: {...},
    },
    'gatsby-plugin-netlify',
    {
      resolve: 'gatsby-source-contentful',
      options: {...},
    },
    'gatsby-plugin-sitemap',
  ],
}

```
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by kakadiadarpan** [comment]
I was able to reproduce this in `gatsbygram` example. It's strange that it doesn't work, when they are both the same thing

**Comment by tdharmon** [comment]
I found a bit of a workaround. If you declare the export like `export const FragmentName` (as opposed to declaring it and then `export { FragmentName}`), you can then import/export them as normal in other files. 

I decided to stick all of my queries in a folder (in separate files), import them into an index file of that folder, and then I can export like `export { query1, query2, query3 }` from there. Then throughout my app, if I need a fragment, I just `import { FragmentName } from './queries'`.

Obviously this isn't a solution, but just a tip for future googlers who ran into this issue.

**Comment by tdharmon** [comment]
@dotlouis I ran into a similar issue, so I started doing some research. Gatsby uses Relay to extract out the GraphQL queries, "transform/optimize them, and then generate build artifacts" [source](https://facebook.github.io/relay/docs/en/compiler-architecture.html). So it treats them differently than a normal React component with imports/exports.

I've chosen to use this to my advantage by creating a "queries" folder and directly exporting graphQL fragments within files in that folder (like `export const MyGraphQLQuery =...`). Gatsby is smart enough to recognize those fragments when building and then to figure out where they go. You can reference those fragments in any page/template query without even importing the fragment's file.

One of the downsides of this is the lack of variable interpolation into the GraphQL query because of the way it extracts/transforms/builds the query (as far as I'm aware–maybe that's possible!).

**Comment by dotlouis** [comment]
@tdharmon Thanks for the explanation. I wonder if this should still be considered an issue though.
While not urgent, this may leave people to scratch their head for no apparent reason.

**Comment by tdharmon** [comment]
@dotlouis I think that, because this is an artifact of how Relay functions (not how Gatsby functions), the solution to this is better documentation (I had to dig to find why this is the case). Especially because these aren't true javascript components, I don't think there is a need for them to work exactly like normal javascript components, especially when there are other graphQL features that would be more helpful. That's just my opinion.

**Comment by dotlouis** [comment]
@tdharmon Thanks for your comment; and in this case, I find it confusing to export queries like any other Javascript variable if they do not work the same under the hood. Better documentation is one thing, but maybe we should declare the queries differently.
Can anyone in the core team confirm this is the expected behavior? I don't want to close this issue just yet.
