### ISSUE TITLE
i18n with different Markdown files

### ISSUE THREAD

**Issue by Siregar** [gatsbyjs/gatsby#9119]
👋
Hi,
I am working on a new Gatsby project and want to implement i18n.
My plan was to store the content in multiple markdown files (**de** and **en**). Routes like `/de/product1` and `/en/about` should be available.

My folder structure for the content looks like this:
- content/
  - pages/
    - index.en.md
    - index.de.md
    - about.en.md
    - about.de.md

  - products/
    - product_1.en.md
    - product_1.de.md
    - product_2.en.md
    - product_2.de.md
    - [...]

Does anyone have an approach for my intention?

**Comment by smakosh** [comment]
you can add a `language` property to the front matter of each markdown file and handle the rest with graphql queries.

**Comment by grubersjoe** [comment]
You might also want to look into https://github.com/angeloocana/gatsby-plugin-i18n

**Comment by CanRau** [comment]
Still didn't had the time to properly write about my i18n implementation
I use a file structure as the following
```
├── about-us
│   ├── assets
│   │   ├── anon.png
│   ├── de.js
│   └── en.js
├── contributors
│   ├── de.js
│   └── en.js
```
pages are in js, blog posts are in md, but that doesn't really matter as you already figured out
right now I'm still duplicating the language in the files frontmatter but it could be easily extracted from the file name, so every page has it's own folder this way every page/post can have it's own assets for easier reference in md and VSCode, personally I don't like the one huge messy folder for all assets..

Page urls are being generated based on the language and the sluggified title or an optional slug field as it's sometimes nice for SEO to shorten or otherwise customize the url..

Pages will receive a node field containing it's `translations` which are auto linked based on the folder structure, before that I linked them myself, it's okay but it's tedious 😉 

And than as @smakosh the rest is just a matter of querying for that url, which I store in a `url` node field for easier querying..

Think that's basically it, and right now my preferred way of managing multi language sites
Uh and having each page in a directory makes it easier to grow to more languages later on without flooding a single folder ;)

Only thing, the directories are named after the english name/url/workname of the page, can be a trade off, but for me it works so far..

Here's the repo: https://github.com/GaiAma/gaiama.org maybe it helps (this one uses the same technique and might be a little less cluttered https://github.com/GaiAma/rescue-amazonian-rainforest.com)
