### ISSUE TITLE
[1.0] Custom GraphQL nodes

### ISSUE THREAD

**Issue by miracle2k** [gatsbyjs/gatsby#913]
I was looking into adding Contentful as a data source to Gatsby 1.0. There is a pretty good contentful graphql wrapper already:

https://github.com/jelz/cf-graphql

Ideally, I would want to just add a contentful node at the graphql root and then inject the query types from the wrapper below, as in:

```
allFiles { ... }
contentful {
    products(q: "fields.id=contentful-query-api-stuff") {
       sys { id }
    }
}
```

But it seems to me that `buildSchema()` currently does not account for that option. The only API provided is "createNode()`.

Looking at the HackerNews sample source,  don't quite understand why it is first quering a GraphQL API, and then creating nodes from that. The original HackerNews GraphQL API could be queried directly. 

Is this not a good idea, or is it something that could be added?

**Comment by jquense** [comment]
Check out the remark markdown typegen and transformer plugins for a bit clearer example of adding nodes. 

The hacker news example can't query the API directly since the sites are static and date is processed and queried ahead of time

**Comment by miracle2k** [comment]
Hm. I understand that Gatsby generates a static site. What I am wondering is why during the Gatsby build we cannot query the Hackernews API directly. In other words, why not replace this query:

https://github.com/gatsbyjs/gatsby/blob/1.0/examples/hn/gatsby-node.js#L24

With this one:

https://github.com/gatsbyjs/gatsby/blob/1.0/packages/gatsby-source-hacker-news/src/gatsby-node.js#L26

**Comment by miracle2k** [comment]
For the hackernews example, it's conceivable that https://www.graphqlhub.com doesn't provide a way to query individual stories directly, but the principal idea remains.

If I want to have a source for a UI-based editor like Contentful, and that backend already provides a GraphQL AP, why should I wrap it and force it into the Gatsby "node" model?

**Comment by jquense** [comment]
Mainly because graphql doesn't love when you try and query two different schema's, you'd always have to redefine all the types in the gatsby schema with resolves that point to the graphql one. It doesn't really suit "proxying" through to a different server. IF you were hand rolling the schema you could allow for that definately (e.g split queries and send certain root node queries to serverA and the others to serverB) but that's a really complicated use and i'm not sure there is a great way to handle that in a general, pluggable way that Gatsby would need to provide.

@KyleAMathews will have more coherant thoughts than me though :) It does seem like something that would be a really neat feature

**Comment by jquense** [comment]
The other thing is if you want to query an existing server, it doesn't need to run through gatsby. you can just query the server in your client code.

**Comment by KyleAMathews** [comment]
@miracle2k hey great questions! Yes in an ideal world Gatsby could just proxy beautiful APIs from the 1000s of data source in the world and it'd serve as a thin layer coordinating these APIs and serve mainly as the dev tool and static build layer.

But as you well know I'm sure, most APIs aren't very good. Most are pretty horrid actually. They don't give you powerful querying, sorting, filtering, grouping, pagination, data transformation options etc. that Gatsby gives you. Also while a few APIs are really good, using their APIs imposes a cost on the average user of Gatsby because then choosing a new data source means learning a new API which could be built with very different assumptions than other ones you're using. By standardizing on Gatsby's node format, every API gets lots of query power + users are presented with a standardized interface.

With Gatsby a site can use markdown and Contentful and the data querying experience is *exactly* the same for both which I think is really cool and really powerful.

Doing what Gatsby does also gives some big performance gains. Passing off individual queries to an external API during development and builds would add a lot of latency to individual queries and dramatically balloon total build time for many sites. Gatsby source plugins can be really smart about caching data and taking advantage of APIs that support queries like this to only pull updated content.

The goal with Gatsby is that incremental builds take seconds and starting the development server is almost instantaneous — goals we can't achieve if we're simply proxying requests to an external API.

**Comment by miracle2k** [comment]
Ok. Some good points made. I am just starting with Gatsby, and will wait until I have some more experience to see what my needs really are. 

The reason this came up is because I have some experience with the Contentful GraphQL API and was looking forward to building a very thing Gatsby source plugin wrapper around it, and but wasn't really excited about writing a lot of code to wrap everything into a different node structure.

Regarding what @jquense said about proxying Hackernews,  completely missed that. I want to note though that the contentful-graphql wrapper would not be a proxy; it generates the schema locally by itself, so would become a first-party part of the Gatsby schema.

**Comment by miracle2k** [comment]
FWIW,  don't doubt the benefits of having a common data querying system. But not every API will always have a plugin available ready to use. I do think it would be pretty powerful if any GraphQL API was available to be queried. 

Performance and caching might be big problem, though.

**Comment by KyleAMathews** [comment]
Yeah bootstrapping a new ecosystem is always tough.

My hope is that with a bit more work on Gatsby core plus some documentation that people will find creating new source plugins really easy. All they are is basically a) get data from somewhere b) break that into logical "units" (the nodes) and c) give them to Gatsby. Most source plugins will be a very thin layer between the actual source API (or whatever) and Gatsby.

There's some fanciness you can add around being smart about caching, deleting old nodes, etc. but the basics should only take an hour or three for a given source plugin.

I'm actually planning on using Contentful for a little upcoming side project. Would love to collaborate on building a gatsby-source-contentful plugin!

**Comment by miracle2k** [comment]
I added some API hooks to Gatsby that allow me to add the Contentful API as-is. Probably not a production-ready patch, one problem that I can see as a Gatsby-novice is that `customGraphQLContext` is called twice.

https://github.com/gatsbyjs/gatsby/compare/1.0...miracle2k:custom-graphql

That allows me now to do queries such as:

```
query ProductPage {
    products(q: "fields.mytitle=foo&content_type=product") {
      sys { id },
      name,
      productGroup {
        _backrefs {
          allVariants: products__via__productGroup {
            name
          }
        }
      }
    }
  }
```

For now, it was too much for me to figure out how to model things like object relations and `_backrefs` in Gatsby. If you do come up with a gatsby-source-contentful plugin I'd be curious to try it.

**Comment by stereobooster** [comment]
I have a bit other side of coin view. Didn't you consider that final version of Gatsby GraphQL schema will be competitor to CMS API providers, like contentful? At this point it would make sense make it a standard so any provider can give a compatible GraphQL endpoint.

As af as I understood this will be shema good enough for any website: list of nodes or pages, content, title, description, custom fields from front-matter, images with sizes url sets etc.

**Comment by angeloashmore** [comment]
To add to this, I wonder if it's possible to create a `gatsby-source-graphql` plugin that just forwards queries? I'm looking into the feasibility of utilizing Shopify with Gatsby to build an e-commerce site, and luckily Shopify now has a GraphQL endpoint.

**Comment by ooloth** [comment]
@angeloashmore Would love to see a Gatsby-Shopify integration!

**Comment by KyleAMathews** [comment]
Closing this as we've got gatsby-source-contentful now
