### ISSUE TITLE
gatsby-plugin-offline: Service worker is causing blank pages when JS is disabled

### ISSUE THREAD

**Issue by thornberger** [gatsbyjs/gatsby#9166]
[source.html.txt](https://github.com/gatsbyjs/gatsby/files/2484611/source.html.txt)
## Description
The plugin gatsby-plugin-offline is causing a blank page on any page except index when JavaScript is disabled.
If the service worker is unregistered, the pages are showing.

This is what is showing up in the Chrome developer console (not sure if it is helpful):

`workbox-precaching.prod.js:1 Fetch finished loading: GET "https://www.**********/static/d/84/path---offline-plugin-app-shell-fallback-549-4b4-NZuapzHg3X9TaN1iIixfv1W23E.json".`

`The resource https://www.***********/static/d/84/path---offline-plugin-app-shell-fallback-549-4b4-NZuapzHg3X9TaN1iIixfv1W23E.json was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.`

### Steps to reproduce

1. Enable gatsby-plugin-offline in the gatsby-config and deploy site.
2. Navigate to page /foo (the problem does not occur on index, resp. "/").
3. Use the developer console to disable JavaScript.
4. Refresh the page.

### Expected result

The page should be rendered as proper HTML.

### Actual result

A broken, white page is showing (see attached source).

However, when I unregister the service worker, everything works fine and as expected.

### Environment

```  System:
    OS: Linux 2.6 Debian GNU/Linux 9 (stretch) 9 (stretch)
    CPU: x64 Intel(R) Xeon(R) CPU E5-2620 v2 @ 2.10GHz
    Shell: 4.4.12 - /bin/bash
  Binaries:
    Node: 10.10.0 - /usr/bin/node
    Yarn: 1.9.4 - /usr/bin/yarn
    npm: 6.4.1 - /usr/bin/npm
  npmPackages:
    gatsby: ^2.0.25 => 2.0.25
    gatsby-image: ^2.0.15 => 2.0.15
    gatsby-plugin-extract-schema: ^0.0.4 => 0.0.4
    gatsby-plugin-google-analytics: ^2.0.6 => 2.0.6
    gatsby-plugin-manifest: ^2.0.2 => 2.0.5
    gatsby-plugin-offline: ^2.0.7 => 2.0.7
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0
    gatsby-plugin-remove-trailing-slashes: ^2.0.3 => 2.0.3
    gatsby-plugin-robots-txt: ^1.3.0 => 1.3.0
    gatsby-plugin-sharp: ^2.0.7 => 2.0.7
    gatsby-plugin-sitemap: ^2.0.1 => 2.0.1
    gatsby-plugin-typescript: ^2.0.0 => 2.0.0
    gatsby-remark-images: ^2.0.4 => 2.0.4
    gatsby-source-contentful: ^2.0.4 => 2.0.4
    gatsby-source-filesystem: ^2.0.4 => 2.0.4
    gatsby-transformer-json: ^2.1.2 => 2.1.4
    gatsby-transformer-remark: ^2.1.6 => 2.1.7
    gatsby-transformer-sharp: ^2.1.4 => 2.1.4```

**Comment by ascorbic** [comment]
This is [a Chrome bug](https://bugs.chromium.org/p/chromium/issues/detail?id=656516). When JavaScript is disabled via chrome://settings then the SW cache is correctly bypassed. However if it is disabled via the devtools then it still uses the SW cache. Firefox has the same behaviour: JS diabled via about:config bypasses the SW, but disabled in devtools it still uses the SW. The problem here is that the SW is returning the fallback shell, which is meant to load the real content via js. I'd say that this is enough of an edge case for us to ignore. The only person who will encounter is is someone who loads the site with the devtools open and JS disabled there. This is only likely to be the site developer. A "real" user with JS disabled is likely to have done is via the browser settings, not the dev tools.

**Comment by thornberger** [comment]
Thanks for the investigation @ascorbic!

I will close this issue.
