### ISSUE TITLE
[gatsby-plugin-google-tag@1.0.0] Build error when used

### ISSUE THREAD

**Issue by extesy** [gatsbyjs/gatsby#9218]
## Description

When `gatsby-plugin-google-tag` is installed, it breaks the build because it exports `__esModule` variable.

### Steps to reproduce

1. Install `gatsby-plugin-google-tag@1.0.0`
2. Enable plugin in `gatsby-config.js`
3. Build project using `gatsby build`

### Expected result

Successful build

### Actual result

```
> gatsby build

success open and validate gatsby-config — 0.008 s
error
Your plugins must export known APIs from their gatsby-browser.js.
The following exports aren't APIs. Perhaps you made a typo or your plugin is outdated?

See https://www.gatsbyjs.org/docs/browser-apis/ for the list of Gatsby Browser APIs

- The plugin "gatsby-plugin-google-gtag@1.0.0" is exporting a variable named "__esModule" which isn't an API.
```

### Environment

```
  System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.12.0 - /usr/local/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 70.0.3538.67
    Firefox: 62.0.3
    Safari: 12.0
  npmPackages:
    gatsby: ^2.0.25 => 2.0.25
    gatsby-plugin-feed: ^2.0.8 => 2.0.8
    gatsby-plugin-google-gtag: ^1.0.0 => 1.0.0
    gatsby-plugin-manifest: ^2.0.5 => 2.0.5
    gatsby-plugin-offline: ^2.0.7 => 2.0.7
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0
    gatsby-plugin-sharp: ^2.0.7 => 2.0.7
    gatsby-plugin-sitemap: ^2.0.1 => 2.0.1
    gatsby-plugin-typography: ^2.2.0 => 2.2.0
    gatsby-remark-copy-linked-files: ^2.0.5 => 2.0.5
    gatsby-remark-external-links: ^0.0.4 => 0.0.4
    gatsby-remark-images: ^2.0.4 => 2.0.4
    gatsby-remark-katex: ^2.0.5 => 2.0.5
    gatsby-remark-prismjs: ^3.0.2 => 3.0.2
    gatsby-remark-responsive-iframe: ^2.0.5 => 2.0.5
    gatsby-remark-smartypants: ^2.0.5 => 2.0.5
    gatsby-remark-sub-sup: ^1.0.0 => 1.0.0
    gatsby-source-filesystem: ^2.0.4 => 2.0.4
    gatsby-transformer-remark: ^2.1.7 => 2.1.7
    gatsby-transformer-sharp: ^2.1.4 => 2.1.4
  npmGlobalPackages:
    gatsby-cli: 1.1.58
```

**Comment by DSchau** [comment]
ah, got it!

So what's happening is that packages are distributed as CommonJS. We're using babel to transpile ES2015+ to CommonJS and minimally Node 6 support.

gatsby-plugin-google-gtag is following a similar approach, but it's exporting ES modules, rather than CommonJS.

Normally, this isn't a big deal, but babel is trying to be helpful here and give us a hint that this code is _now_ commonjs but was transpiled from ES.

So, as I see it, we have two options here (which could also be combined).

1. Update gatsby-plugin-google-gtag src/ directory to use CommonJS exports, (e.g. exports.onRenderBody instead of export const onRenderBody)
1. Update gatsby core to not throw an error on unrecognized APIs if the API is `__esModule`

Any interest in fixing this?

**Comment by Seldszar** [comment]
I'd like to take this one if you don't mind.

**Comment by tylerbuchea** [comment]
I think solution 2 would probably be the best don't you guys think? You're more than welcome to take this on @Seldszar if you need help or get stuck please reach out we can collaborate on it 😄

**Comment by Seldszar** [comment]
@tylerbuchea  Sure! I was thinking about making 2 PRs, one for the plugin for unifying code style, then another one for the ES module support. Does that sound good to you?

**Comment by tylerbuchea** [comment]
Sounds groovy 😎
