### ISSUE TITLE
[1.0] build example site with fancy page transitions

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#925]
Something like this would be 💯 

https://codepen.io/sdras/full/gWWQgb/?utm_source=reactnl&utm_medium=email

**Comment by anthonysapp** [comment]
I'm actually working on implementing something with 
https://github.com/reactjs/react-transition-group#low-level-api-transitiongroup

Any ideas on how to do that?
I've tried a couple of approaches so far in fiddling around: 

1. Something like this in the default layout, in the render method:
```
<TransitionGroup component="div" className="page">
    {children}
</TransitionGroup>
```

2. Wrapping the root component in using the gatsby-browser.js wrapRootComponent lifecycle hook.

For both, the pages render fine, but I haven't been able to get TransitionGroup's lifecycle hooks to work.

**Comment by KyleAMathews** [comment]
I'm not really sure how TransitionGroup works but I'd love to get things working such that there could be plugins which auto add transition effects (perhaps have 5-6 diff options) to a site or to individual pages.

**Comment by KyleAMathews** [comment]
Also this will effect things https://github.com/gatsbyjs/gatsby/pull/940

**Comment by KyleAMathews** [comment]
*affect

**Comment by anthonysapp** [comment]
Ah crap. I for some reason thought Gatsby had already changed to RR V4. That's probably part of the problem :)

I will keep plugging away and report back findings. The TransitionGroup functionality seems to have changed in a recent update to React, and it's been moved to a new repo with new maintainers, so I'm sure that's also part of my misunderstanding.

**Comment by KyleAMathews** [comment]
Check back tomorrow and it might be! :-)

**Comment by anthonysapp** [comment]
@KyleAMathews so after some more digging I've definitely figured out what needs to be done to implement this type of transition at the page level. I **think** an elegant way to do this would be to wrap the component for each page you want to transition in a TransitionGroup component. I'm having a crack at doing this using a HOC at the moment.

**Comment by anthonysapp** [comment]
After reading the plan for #940 , I think it's best to wait to do any further implementation of this. I did figure it out, though. I'll have a crack at explaining it, so perhaps it will help in some way with the changes that are coming:

What I ultimately found is that I needed to interact with the components that are generated for each page in the `.cache/child-routes.js` file. SInce it is those components that are ultimately rendered as the children of your layout eg: `src/layouts/default.js`. This was obviously a bit problematic - maybe due to something I'm missing. What I ended up doing in my `default.js` layout is wrapping the rendered child component in a `<TransitionGroup>` component:

```
<div className="page-container">
    <TransitionGroup>
        <children.type {...this.props} key={this.props.location.pathname} />
    </TransitionGroup>
</div>
```
I know that <children.type/> is the component Gatsby derives, and the `default.js` layout component doesn't get removed from the DOM, so it seems to be the place you want to control page transitions from (unless the layout changes, I suppose).

So the problem from there was, TransitionGroup calls lifecycle methods in the component it's wrapping... so it's going to try to call them in the derived component in `child-routes.js`, NOT in my actual template component for each page. So from there, I wrote a little utility to map the lifecycle methods up the chain to the page template component, but it seems very hack-ish to me. 

Helper script `src/transitions/bindTransitions.js`
```
const lifeCycleHooks = [
  "componentWillAppear",
  "componentWillEnter",
  "componentWillLeave",
  "componentDidAppear",
  "componentDidEnter",
  "componentDidLeave"
];

const bindTransitions = instance => {
  const parentPrototype = instance.props.children.type.prototype;
  lifeCycleHooks.forEach(methodName => {
    if (instance[methodName] !== undefined) {
      instance[methodName] = instance[methodName].bind(instance);
      parentPrototype[methodName] = instance[methodName];
    }
  });
};
export default bindTransitions;
```

Then, in `src/templates/page-template.js`:
```
import { bindTransitions } from "../transitions";
class PageTemplate extends React.Component {
  isAnimating = false;
  animationCallBack = null;

  constructor(props) {
    super(props);
    
    // call helper script to map TransitionGroup lifecycle hooks
    bindTransitions(this);
  }

  componentWillAppear(cb) {
    this.animateIn(cb);
  }

  componentWillEnter(cb) {
    this.animateIn(cb);
  }

  componentWillLeave(cb) {
    this.animateOut(cb);
  }

  animateIn(cb){
      //... do animation and trigger 
      cb()
  }
   animateOut(cb){
      //... do animation and trigger 
      cb()
  }

  render(){
      ...
  }
}
```
TransitionGroup now works as expected, with the ability to map lifecycle hooks to any page template component, and do custom animations with EG `gsap` tweening engine.

Hopefully that makes some kind of sense :)

**Comment by anthonysapp** [comment]
In messing around with this some more this morning, I realized this method doesn't work when doing a production build... I still think the above post might be useful though, hopefully.

**Comment by KyleAMathews** [comment]
#940 is merged now btw. Since this.props.children is a function now for layouts, perhaps that can be leveraged for this?

**Comment by anthonysapp** [comment]
Cool, I will have a look.

**Comment by anthonysapp** [comment]
So much better! I was able to get something workable going.
One remaining issue in my example: on a production build, if I go to a non-index route I get this error:

<img width="500" alt="screen shot 2017-05-16 at 4 12 08 pm" src="https://cloud.githubusercontent.com/assets/5347604/26126137/8459319e-3a52-11e7-80a9-37ab7441bea4.png">

Seems like it might have something to do with code splitting not loading a required file, but I'm not 100% sure.

**Comment by 0x80** [comment]
I've been experiencing this issue too, but hadn't investigated enough to report it yet. Not sure how long has been there but I suspect since the router v4 update.

**Comment by KyleAMathews** [comment]
Do you have a layout component? At layouts/index.js?

**Comment by 0x80** [comment]
@KyleAMathews Yes

**Comment by anthonysapp** [comment]
Yes, at layouts/index.js

**Comment by KyleAMathews** [comment]
Afaik none of the example apps do this. If you can help narrow down things
more. Also what is that line of code?

**Comment by anthonysapp** [comment]
@KyleAMathews of course, apologies for being vague. I will have a closer look tomorrow and report back. Worth opening a new issue?

**Comment by KyleAMathews** [comment]
Yeah sounds like it

**Comment by 0x80** [comment]
#981

**Comment by muhajirframe** [comment]
Any progress on this? is it possible now?

**Comment by yunda** [comment]
☝️

**Comment by sebastienfi** [comment]
https://github.com/gatsbyjs/gatsby/tree/master/examples/using-page-transitions

**Comment by KyleAMathews** [comment]
Per @sebastienfi comment, we've got solid support now for page transitions — would love a really fancy example site too someday but this will suffice for now.

**Comment by thebarty** [comment]
Hi guys,

is anyone using scroll-to-anchor animations?

I am having weird rendering-issues with https://www.npmjs.com/package/react-anchor-link-smooth-scroll

**Comment by mvasin** [comment]
Did somebody use [react-spring](https://github.com/drcmda/react-spring) / [react-motion](https://github.com/chenglou/react-motion) / [pose](https://popmotion.io/pose/) for more sophisticated transitions between pages? Are there any examples on integration gatsby with those libraries?

Ideally I'd morph one page to another like [this](https://brunnolou.github.io/react-morph/?selectedKind=Advanced&selectedStory=Morphing%20from%20card%20to%20details&full=0&addons=0&stories=1&panelRight=0).

Transition-In is no-brainer, but I'm not sure how can I transition-Out or cross-fade.
