### ISSUE TITLE
Build source plugin for Marvel API

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#9300]
Marvel has a great API that lets you access a ton of data — it'd be great to have it wrapped in a source plugin that let sites easily pull in data

https://developer.marvel.com/

**Comment by oorestisime** [comment]
This seems quite fun to do. I had a look at the API and it is separated in entities (characters, comics, events, series etc ) and i think a source plugin could take in options a list of objects describing the resource they need.
For example 

```js
[
    {
        entity: 'characters',
        characterId: 'a character id',
        limit: 100,
        resource: {
            entity: 'comics',
            fields: ['id', 'title', 'pageCount']
        }
    },
    ...
]
```

would return basic character information and the comics associated with selecting the
specified comics fields. If the user does not provide a characterId then we return
all the characters up to the specific limit etc. And the plugin would need to have sensible default options.

Instead of character id we could take a name and query first the API to get the
corresponding characterId and then get the details the user requested etc.

All entities seem to have thumbnails, if the user requests this field we could use
the create remote api of filesystem to download the resource etc.

Is this what you had in mind?
I can give this a go!
