### ISSUE TITLE
.org redesign: homepage [design] gatsby diagram

### ISSUE THREAD

**Issue by amberleyromo** [gatsbyjs/gatsby#9525]
_(This issue is **design-focused**, not implementation-focused.)_

@fk has begun working on and mocking up updated designs for the Gatsby homepage diagram:

<img width="837" alt="screen shot 2018-10-29 at 12 45 27 pm" src="https://user-images.githubusercontent.com/3461087/47669272-8b094880-db78-11e8-8fea-fca128f4bb06.png">

This issue is intended to support discussion and feedback on the diagram update.

**Comment by fk** [comment]
I finally picked up work on this yesterday and here's what I've got so far:

<img width="1280" alt="desktop_ homepage" src="https://user-images.githubusercontent.com/21834/47669719-d0933900-dbab-11e8-803d-04fb54bb1b0a.png">

FYI: With [us deciding to expand the existing diagram](https://gatsbyjs.slack.com/archives/CDFLS39AB/p1540580649005100) and add some more detail inspired by the [`react-static` diagram used in their "Introduction" article](https://medium.com/@tannerlinsley/%EF%B8%8F-introducing-react-static-a-progressive-static-site-framework-for-react-3470d2a51ebc#6695), I decided the vertical format is the only route to pick. Thus I completely abandoned all (long-standing) ambitions to do a vertical _and_ a horizontal (for bigger screens) version of the diagram for now.

**Comment by fk** [comment]
As you can see, I'm a little stuck on both "Build" and "Serve" parts though:

- I want to make sure that Gatsby's "build" and "serve" stages really match the ones of our [reference diagram](https://medium.com/@tannerlinsley/%EF%B8%8F-introducing-react-static-a-progressive-static-site-framework-for-react-3470d2a51ebc#6695): Do "React/Gatsby Bootstrap", "Template", "JSON" really make 100% sense for Gatsby, too? /cc @kylemathews @pieh
- I'm a little confused about "JSON" being part of "Page" in `react-static`s "Build" step. I would have expected "JSON" to be _associated_ with "Page", but not being _part_ of it here.

I also would like to avoid copying the `react-static` diagram 1:1 in terms of "Build" and "Serve", but I'm missing some "Gatsby internals" knowledge to think about ways to do so. Plis halp! 🆘 

- Do we want to feature @reach/router in "Serve" as `react-static` does with React Router?

**Comment by fk** [comment]
Further wondering:

- Should we add a "Develop" section, too? My vote is for "yes", because it allows us to point out the great dev UX features Gatsby offers (hot reloading being the main one). That's something where the `react-static` diagram falls short on IMO.

- I added a bunch of "explanatory copy" for "Source Data" and "Deploy" — does that make sense to y'all? The current copy is borrowed from the existing "six cards above diagram" on the current https://www.gatsbyjs.org/.
  - I initially did so because there was space, and I wanted to see how adding a short explanation would feel. ;-)
  - When adding the copy that is there now in that WIP design, I wondered if we should drastically reduce their copy, and turn them into something more "unordered list of features" kind of thing — something that can be scanned quickly to get a feature overview — while at the same time adding that copy to the diagram.

**Comment by KyleAMathews** [comment]
>I'm a little confused about "JSON" being part of "Page" in react-statics "Build" step. I would have expected "JSON" to be associated with "Page", but not being part of it here.

Yeah — theirs and our build steps generate JSON (the data for each page)

>Do we want to feature @reach/router in "Serve" as react-static does with React Router?

I'd vote yes — a lot of people aren't sure exactly how Gatsby works so emphasizing we ship a client router will help them get that "oh, Gatsby _is_ generating a React app and I can add client routes, etc."

>I added a bunch of "explanatory copy" for "Source Data" and "Deploy" — does that make sense to y'all? 

👍 

>Should we add a "Develop" section, too?

Seems promising — if it makes the diagram more confusing I'd vote for just showing the "build" diagram

>I want to make sure that Gatsby's "build" and "serve" stages really match the ones of our reference diagram: Do "React/Gatsby Bootstrap", "Template", "JSON" really make 100% sense for Gatsby, too? 

Yup! Except we call them "page template components" https://www.gatsbyjs.org/docs/building-with-components/ (or maybe just "page templates"

**Comment by jlengstorf** [comment]
I had an idea and put together a super rough sketch:

![img_20181031_152008](https://user-images.githubusercontent.com/163561/47858413-41537480-dda9-11e8-8840-1a88d47a2ab7.jpg)

The general idea is that Gatsby has 3 distinct phases:

1. Sourcing (the content mesh)
2. Developing (incredible DX)
3. Building (performance, UX)

This is an attempt to show all three phases inside a “band” of Gatsby work, so we can see:

1. The data coming in from The Cloud™
2. Gatsby’s source, develop, and build steps
3. The deployment process and how that affects the UX and perf.

I could also make an argument that the “what happens when you request a Gatsby site” section is its own diagram in a separate area. These are actually two distinct concepts:

1. What does Gatsby do?
2. How are Gatsby sites so fast?

**Comment by jlengstorf** [comment]
I needed to create a way to show the Gatsby flow in slides for the GraphQL Summit, and this is what I ended up with: https://jlengstorf.github.io/presentations/beyond-static/#/20

Note that you'll need to advance through the slides to see the full diagram.

If this is helpful, I can share the Figma file as well.

**Comment by jlengstorf** [comment]
Here's the Figma link of my diagram: https://www.figma.com/file/egCho5h1PYnLcC4DppKPJiP1/Diagram-Ideas?node-id=1%3A2

**Comment by marisamorby** [comment]
This is blocked by the .org homepage research. We'll revisit once research is complete and we can get to design.
