### ISSUE TITLE
Gatsby Transformer Html

### ISSUE THREAD

**Issue by JanaVanMaele** [gatsbyjs/gatsby#9721]
I followed the tutorial generating markdown files in to static pages as a blog post.
Now I want to do the same, but instead of using .md files, I'd like to use .html files.
My .html files should exist out of frontmatter and a html string.
My goal is to render the html of the .html files inside a react layout/template.
Is there an easy way to do this? Does there exist a formatter for this?

I am using Gatsby version 2.4.4
generated my project from the gatsby-starter-default

**Comment by btk** [comment]
If I were you, I would create nodes, relative to that HTML files, in my gatsby-node.js. Than create pages for that nodes, that would get the contents of the HTML string as context.

And create a template which would insert the HTML string into a react div like;

```HTML
<div dangerouslySetInnerHTML={{ __html: yourNode.HTMLcontent }} />
```

**Comment by JanaVanMaele** [comment]
@btk Thank you for your reply
Can you give me a hint on how "create a node, relative to HTML files" would look like in code? I have a rough idea how to do the rest of your explanation in code, but as a newbie to node, react and gatsby, I have no idea how to read the content of a HTML file.
Thank you in advance!

**Comment by btk** [comment]
@JanaVanMaele ofc.

You should have a quick look at these page, it is a general reference for node apis on gatsby. https://www.gatsbyjs.org/docs/node-apis/  (Especially `createNode` and `createPage` actions)

Since your problem is pretty spesific I can't really point you out to a good source code you can edit. But you can try these links;

https://www.gatsbyjs.org/docs/source-plugin-tutorial/
https://www.gatsbyjs.org/docs/create-source-plugin/

A "source plugin", as defined on gatsby, is a plugin that sources data, creates nodes and creates pages  of of these nodes. What you need to do is, instead of getting the data for creating a node from an rest api, you will read the content of the .html files (which is a[ just reading a local file in nodejs](https://nodejs.org/api/fs.html#fs_fs_readfile_path_options_callback)).

Hope all these helps, if you start composing a gatsby-node.js file and got stuck at somewhere, you can email me for help, (my email is on my profile)

**Comment by JanaVanMaele** [comment]
@btk Thanks! I'll give it a try

**Comment by aplachka** [comment]
> @btk Thanks! I'll give it a try

any luck with your investigation?
