### ISSUE TITLE
.org redesign: homepage [content/copy] - Blog / Newsletter section

### ISSUE THREAD

**Issue by amberleyromo** [gatsbyjs/gatsby#9744]
## Goal

As we're going through the .org redesign, we'll be updating the copy on each of the pages. We want to make sure that we have input and agreement on all sections of homepage copy.

## Next steps

We need to finalize the mockup for the Blog / Newsletter section: https://github.com/gatsbyjs/gatsby/issues/9711#issuecomment-436335535

@shannonbux @lindaleebumblebee ^take a look, and please either give approval as it stands on the mockup, or provide copyedits?

### Approvals
- [x] @lindaleebumblebee 
- [x] @shannonbux

**Comment by amberleyromo** [comment]
@lindaleebumblebee's input: https://github.com/gatsbyjs/gatsby/issues/9711#issuecomment-436355046

**Comment by lindaleebumblebee** [comment]
I'm good with the design so I've marked it as 'approved' from my end with just the one change to the title (The Gatsby Blog instead of Gazette).

**Comment by shannonbux** [comment]
I like sentence caps instead of title caps for buttons because it seems like these are complete sentences rather than a "title" for something. Don't know who has the final say though. I don't think this is blocking, so I'll approve this. Just a consideration for how we handle buttons across the site. In this case the change would read:
"View all posts"
"Submit an article" or "Submit a post"

We've been somewhat inconsistent with our capitalization on buttons around the site :)

In some brief browsing, I'm noticing that many websites do sentence caps (first word starts with capital letter), title capitalization, or ALL CAPS. Marvelapp does sentence caps and Sketchapp does title caps. I looked at them since they have similar buttons to us.
