### ISSUE TITLE
.org redesign: homepage [design] "used by" section

### ISSUE THREAD

**Issue by fk** [gatsbyjs/gatsby#9752]
Up to now, the "Used by" section was featured prominently above the fold.
We could keep it that way…

![image](https://user-images.githubusercontent.com/21834/48089337-8857c480-e204-11e8-93e1-fcd90593d4a3.png)

or move the section down, allowing it to span the whole width of the page, possibly scrolling the logos in an endless loop, freeing the space next to claim and main CTA buttons to be used for other content:

![image](https://user-images.githubusercontent.com/21834/48089102-f780e900-e203-11e8-8746-99fefbe5f5ae.png)

In any case, I want to suggest updating the logos we show here, if possible:
- I took a first look at the sites in the [Showcase](https://www.gatsbyjs.org/showcase) and added a few logos which you can see in the mocks above.
- I'm wondering wether we have to get the permission to show these logos—from a past job I seem to recall that we had to do so, but can't remember exactly.
- AirBnb and Nike probably are misrepresenting things, making it look like their main websites were built with Gatsby (while it's really "just" https://airbnb.design/ and https://justdoit.nike.com/)

/cc @lindaleebumblebee Maybe you can help in terms of my "legal concerns?"

**Comment by greglobinski** [comment]
> possibly scrolling the logos in an endless loop,
I like that :+1:

**Comment by lindaleebumblebee** [comment]
I agree with @fk about the legal grey area for showing logos. It's best to get permission but may not be legally required (since Gatsby is open source and anyone can see who uses it). Most startups our size take the approach of 'it's easier to get forgiveness than permission'. Many of these logos we will have case studies for soon so that should be fine showing their logo in this section (just depends on how conservative we want to be). It's worth asking our lawyers if we're concerned of the implications.

**Comment by marisamorby** [comment]
@fk: Closing this since we will do layout prototyping that will answer where this should live on the homepage.
