### ISSUE TITLE
Error CSS on production (with w3c validation) why?

### ISSUE THREAD

**Issue by Steffi3rd** [gatsbyjs/gatsby#9810]
I have a CSS and it's transformed into `-ms-grid-columns`

Why, and where is it done?

I use the `gatsby-contentful-starter`

### Before
![capture d ecran 2018-11-08 a 11 23 20](https://user-images.githubusercontent.com/814410/48193200-4042ba00-e34a-11e8-9fbe-06c214348418.png)

### After
![capture d ecran 2018-11-08 a 11 31 41](https://user-images.githubusercontent.com/814410/48193205-43d64100-e34a-11e8-9fc9-f01a41dd96f7.png)

**Comment by kakadiadarpan** [comment]
[-ms-grid-columns](https://msdn.microsoft.com/en-us/ie/hh772246(v=vs.94)) is inserted for compatibility to convert `grid-template-cloumns`. I'm not sure though why it would fail w3c validation.

**Comment by LekoArts** [comment]
It's done by `autoprefixer`. Also don't see why W3C should flag this. I use grid and didn't get this error. Furthermore you're _probably_ using an outdated starter. We can't really tell as you didn't follow the issue instructions.

Please fill out the instructions/template as otherwise no one can really help you as you don't give any valuable information on how to reproduce this issue.
