### ISSUE TITLE
The links in the "Behind the scenes" documentation does not work

### ISSUE THREAD

**Issue by sondrele** [gatsbyjs/gatsby#9816]
## Description

Tested in **Firefox 64** and **Chrome 70**.

The links in the generated graph of the Gatsby architecture does not work properly.

When hovering over a node (e.g. **source nodes**) the link seams to be interpreted correctly by the browser, but by clicking the node you get routed to this path [0] instead of [1] which was to be expected.
It does however work when you open the link in a new tab (by holding down the ctrl key while clicking the links).

[0] **/docs/behind-the-scenes/[object%20SVGAnimatedString]**
[1] **/docs/node-creation/**

### Steps to reproduce

1. Navigate to the [behind the scenes](https://www.gatsbyjs.org/docs/behind-the-scenes/) documentation
2. Press one of the links in the graph (e.g. the **source nodes** node).

### Expected result

You get routed to this page: https://www.gatsbyjs.org/docs/node-creation/

### Actual result

You end up on a page with the title **Page not found** and that the path in the browser window is this: https://www.gatsbyjs.org/docs/behind-the-scenes/[object%20SVGAnimatedString].

### Environment

This happens in the live documentation hosted on gatsbyjs.org

**Comment by Bassetts** [comment]
I also noticed this and have narrowed it down to

https://github.com/gatsbyjs/gatsby/blob/6fed3e5452dd5544924396b2a46633defb9f2e2b/packages/gatsby-plugin-catch-links/src/catch-links.js#L121

Because the `xlink:href` attribute of `SVGAElement` is an `SVGAnimatedString` it causes `destination.href` to become malformed for anchors in SVGs. In order to handle this situation I believe the code should be using the `animVal` property when it encounters an SVG anchor.

I am happy to attempt a fix for this.
