### ISSUE TITLE
[gatsby-source-contentful] Specify Locale as an option

### ISSUE THREAD

**Issue by KleiOz** [gatsbyjs/gatsby#9836]
## Summary

Add an option to specify the locale we want to fetch data with

### Basic example

```
module.exports = {
    plugins: [{
      resolve: `gatsby-source-contentful`,
      options: {
        spaceId: contentfulSpaceId,
        accessToken: contentfulAccessToken,
        environment: contentfulEnvironment,
        locale: 'en' // <---- Add this
      }
    }]
```

### Motivation

Get the same data as a result than the request below, without having to specify the filter on each request : 

```
{
  allContentfulData(filter: {node_locale: {eq: "en"}}) {
    edges {
      node {
        node_locale
        id
        something
      }
    }
  }
}
```

To become : 

```
{
  allContentfulData {
    edges {
      node {
        node_locale
        id
        something
      }
    }
  }
}
```
And have the same result if the Locale option is specified.

Why ? Because we generate 2 static websites (FR/EN) in 2 different processes, and for now each instance queries both locales data even if we are able to filter them on pages afterwards.

**Comment by mattwexa** [comment]
Hi, we still have the issue. Do you have any suggestion? From what I can see in the code, we could filter the `locales` to the one specified in the plugin's `options`, and it should pretty much do the job. Am I correct?

**Comment by mattwexa** [comment]
@KleiOz @kakadiadarpan do you know who I can ping who could advise me and perhaps guide me in implementing this feature? Thanks!

**Comment by sidharthachatterjee** [comment]
Thanks @kakadiadarpan 

@mattwexa I just tried this out by filtering locales from contentful by a locales key passed in options 
```
// Optionally filter all locales from Contentful by ones passed in options.
  const filteredLocales = options.locales
    ? _.filter(locales, locale => {
        console.log(locales, locale)
        return _.includes(options.locales, locale.code)
      })
    : locales
```

Unfortunately, this is a little trickier than this because of possible fallback locales. You would have to account for selected locales + their fallbacks so the localization algorithm doesn't break. 

On a side note: I'd like to understand your use case better — is the issue overfetching or having to filter out everything but the current locale on every page?

**Comment by mattwexa** [comment]
Hi, we still have the issue. How do we go from here? Should we try to add the locale option and then open a PR with these changes?

**Comment by mattwexa** [comment]
Hi, actually we migrated to the source-graphql plugin to query the GraphQL API of Contentful instead of using the source-contentful plugin. This allowed us to circumvent several issues we had with Gatsby and the source-contentful plugin: the inferred schema is very large (we're using gql-gen to get TypeScript type declarations), and when there is missing data in Contentful some queries don't work (also related to the inferred schema). So I guess I can close this issue now.
