### ISSUE TITLE
Passing data through navigate to markdown page template

### ISSUE THREAD

**Issue by jodays** [gatsbyjs/gatsby#9991]
Passing state through navigate

**Comment by justinformentin** [comment]
Is the Nav conditional based on what markdown page is rendered, or is it static? Also, by "expand", you're saying that the Nav has nested links that get opened and closed when you click?

Maybe you can try converting the Nav component into a class component so you can access the state, then make the expanding/closing of the links a state that gets toggled onClick.

**Comment by jodays** [comment]
@justinformentin Yes, my sidebar is a stateful component and I am toggling the expansion panels through openPath state and yes the nav has nested panels which are built dynamically by the directory structure of my markdown through a graphQL query. However, I'm confused about how to persist the state on the redirect. I'm using a navigate on click of the list items (which are the markdown files).

**Comment by justinformentin** [comment]
Oh I gotcha, I misundertood, thought the code you posted was an example of the nav itself. 

A good way to do this that I've seen in many projects is to use a `location` prop. If you look at some examples similar to what you want to do, like the Gatsby and React docs, you'll see that's what they do. I don't know the structure of the rest of your project, but maybe reverse engineering those will help.

[React Docs Sidebar](https://github.com/reactjs/reactjs.org/blob/master/src/components/StickyResponsiveSidebar/StickyResponsiveSidebar.js)

[Gatsby Docs Sidebar](https://github.com/gatsbyjs/gatsby/tree/master/www/src/components/sidebar)

Though I think the React docs might be closer to what you're looking for because the Gatsby docs accordion/submenu stays open even when navigating to another accordion.
